### ISSUE TITLE
iOS Flutter 2.10.3 got crash because of EXC_BAD_ACCESS KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by BlakeWuh** [flutter/flutter#101498]
## Steps to Reproduce

1. 100% of the users crashed when the app is in foreground.
2. 67% of the users crashed on iOS 15. 33% of the users crashed on iOS 14.
3. The crash got reported to Firebase console.
4. I haven't found a way to reproduce it.

**Expected results:** 

**Actual results:** 

```
crashed: io.flutter.1.raster
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000000005c8328

Crashed: io.flutter.1.raster
0  ???                            0x5c8328 (missing)
1  Runner                         0x2afc74 SEASignalHandler + 111 (SEAExceptionManager.m:111)
2  libsystem_platform.dylib       0x2d48 _sigtramp + 52
3  libsystem_pthread.dylib        0xd854 pthread_kill + 208
4  libsystem_c.dylib              0x1f6a4 abort + 124
5  libsystem_malloc.dylib         0x1b9d8 _malloc_put + 546
6  libsystem_malloc.dylib         0x1bc40 malloc_zone_error + 96
7  libsystem_malloc.dylib         0x14d2c free_list_checksum_botch + 36
8  libsystem_malloc.dylib         0x7364 small_free_list_remove_ptr_no_clear + 1216
9  libsystem_malloc.dylib         0x78e0 free_small + 592
10 Flutter                        0x99a20 (missing UUID be105c8b7c053a8ba51f83e291732357)
11 Flutter                        0x7bbc8 (missing UUID be105c8b7c053a8ba51f83e291732357)
12 Flutter                        0x48324 (missing UUID be105c8b7c053a8ba51f83e291732357)
13 Flutter                        0xbd8f8 (missing UUID be105c8b7c053a8ba51f83e291732357)
14 Flutter                        0xbd4c4 (missing UUID be105c8b7c053a8ba51f83e291732357)
15 Flutter                        0xbd1f8 (missing UUID be105c8b7c053a8ba51f83e291732357)
16 Flutter                        0x1ec648 (missing UUID be105c8b7c053a8ba51f83e291732357)
17 Flutter                        0x214c58 (missing UUID be105c8b7c053a8ba51f83e291732357)
18 Flutter                        0x22f300 (missing UUID be105c8b7c053a8ba51f83e291732357)
19 Flutter                        0x1902c0 (missing UUID be105c8b7c053a8ba51f83e291732357)
20 Flutter                        0x1907dc (missing UUID be105c8b7c053a8ba51f83e291732357)
21 Flutter                        0x5b364 (missing UUID be105c8b7c053a8ba51f83e291732357)
22 Flutter                        0x516c78 (missing UUID be105c8b7c053a8ba51f83e291732357)
23 Flutter                        0x48f838 (missing UUID be105c8b7c053a8ba51f83e291732357)
24 Flutter                        0x3cc584 (missing UUID be105c8b7c053a8ba51f83e291732357)
25 Flutter                        0x3ccaa0 (missing UUID be105c8b7c053a8ba51f83e291732357)
26 Flutter                        0x2fd380 (missing UUID be105c8b7c053a8ba51f83e291732357)
27 Flutter                        0x3cc078 (missing UUID be105c8b7c053a8ba51f83e291732357)
28 Flutter                        0x3cdadc (missing UUID be105c8b7c053a8ba51f83e291732357)
29 Flutter                        0x3ccd68 (missing UUID be105c8b7c053a8ba51f83e291732357)
30 Flutter                        0x3d4e14 (missing UUID be105c8b7c053a8ba51f83e291732357)
31 Flutter                        0x2fbbf0 (missing UUID be105c8b7c053a8ba51f83e291732357)
32 Flutter                        0x2ff1bc (missing UUID be105c8b7c053a8ba51f83e291732357)
33 CoreFoundation                 0xa6c58 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
34 CoreFoundation                 0x304e8 __CFRunLoopDoTimer + 1008
35 CoreFoundation                 0x2b0a0 __CFRunLoopDoTimers + 316
36 CoreFoundation                 0xad94 __CFRunLoopRun + 1964
37 CoreFoundation                 0x1dc30 CFRunLoopRunSpecific + 572
38 Flutter                        0x2ff088 (missing UUID be105c8b7c053a8ba51f83e291732357)
39 Flutter                        0x2fe848 (missing UUID be105c8b7c053a8ba51f83e291732357)
40 libsystem_pthread.dylib        0x3348 _pthread_start + 116
41 libsystem_pthread.dylib        0x1948 thread_start + 8
```

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
crashed: io.flutter.1.raster
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000000005c8328

Crashed: io.flutter.1.raster
0  ???                            0x5c8328 (missing)
1  Runner                         0x2afc74 SEASignalHandler + 111 (SEAExceptionManager.m:111)
2  libsystem_platform.dylib       0x2d48 _sigtramp + 52
3  libsystem_pthread.dylib        0xd854 pthread_kill + 208
4  libsystem_c.dylib              0x1f6a4 abort + 124
5  libsystem_malloc.dylib         0x1b9d8 _malloc_put + 546
6  libsystem_malloc.dylib         0x1bc40 malloc_zone_error + 96
7  libsystem_malloc.dylib         0x14d2c free_list_checksum_botch + 36
8  libsystem_malloc.dylib         0x7364 small_free_list_remove_ptr_no_clear + 1216
9  libsystem_malloc.dylib         0x78e0 free_small + 592
10 Flutter                        0x99a20 (missing UUID be105c8b7c053a8ba51f83e291732357)
11 Flutter                        0x7bbc8 (missing UUID be105c8b7c053a8ba51f83e291732357)
12 Flutter                        0x48324 (missing UUID be105c8b7c053a8ba51f83e291732357)
13 Flutter                        0xbd8f8 (missing UUID be105c8b7c053a8ba51f83e291732357)
14 Flutter                        0xbd4c4 (missing UUID be105c8b7c053a8ba51f83e291732357)
15 Flutter                        0xbd1f8 (missing UUID be105c8b7c053a8ba51f83e291732357)
16 Flutter                        0x1ec648 (missing UUID be105c8b7c053a8ba51f83e291732357)
17 Flutter                        0x214c58 (missing UUID be105c8b7c053a8ba51f83e291732357)
18 Flutter                        0x22f300 (missing UUID be105c8b7c053a8ba51f83e291732357)
19 Flutter                        0x1902c0 (missing UUID be105c8b7c053a8ba51f83e291732357)
20 Flutter                        0x1907dc (missing UUID be105c8b7c053a8ba51f83e291732357)
21 Flutter                        0x5b364 (missing UUID be105c8b7c053a8ba51f83e291732357)
22 Flutter                        0x516c78 (missing UUID be105c8b7c053a8ba51f83e291732357)
23 Flutter                        0x48f838 (missing UUID be105c8b7c053a8ba51f83e291732357)
24 Flutter                        0x3cc584 (missing UUID be105c8b7c053a8ba51f83e291732357)
25 Flutter                        0x3ccaa0 (missing UUID be105c8b7c053a8ba51f83e291732357)
26 Flutter                        0x2fd380 (missing UUID be105c8b7c053a8ba51f83e291732357)
27 Flutter                        0x3cc078 (missing UUID be105c8b7c053a8ba51f83e291732357)
28 Flutter                        0x3cdadc (missing UUID be105c8b7c053a8ba51f83e291732357)
29 Flutter                        0x3ccd68 (missing UUID be105c8b7c053a8ba51f83e291732357)
30 Flutter                        0x3d4e14 (missing UUID be105c8b7c053a8ba51f83e291732357)
31 Flutter                        0x2fbbf0 (missing UUID be105c8b7c053a8ba51f83e291732357)
32 Flutter                        0x2ff1bc (missing UUID be105c8b7c053a8ba51f83e291732357)
33 CoreFoundation                 0xa6c58 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
34 CoreFoundation                 0x304e8 __CFRunLoopDoTimer + 1008
35 CoreFoundation                 0x2b0a0 __CFRunLoopDoTimers + 316
36 CoreFoundation                 0xad94 __CFRunLoopRun + 1964
37 CoreFoundation                 0x1dc30 CFRunLoopRunSpecific + 572
38 Flutter                        0x2ff088 (missing UUID be105c8b7c053a8ba51f83e291732357)
39 Flutter                        0x2fe848 (missing UUID be105c8b7c053a8ba51f83e291732357)
40 libsystem_pthread.dylib        0x3348 _pthread_start + 116
41 libsystem_pthread.dylib        0x1948 thread_start + 8
```

```
```

</details>

**Comment by maheshmnj** [comment]
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/101498#issue-1195809854 force flutter#v2.10.3 ios release arm64

**Comment by maheshmnj** [comment]
Hi @BlakeWuh, Thanks for filing the issue. Labeling this issue for further investigation from the team.

**Comment by zanderso** [comment]
As with the other crashers from @BlakeWuh, this appears to be a memory corruption error that we likely won't be able to track down without a local reproduction. If memory is corrupted, causing crashes in essentially random subsystems, then the backtraces aren't enough information to help track it down.

**Comment by haidarcorp** [comment]
> 

So what information would help you track it down? How does one debug an issue like this if stacktraces aren't helping? 

In my case, every stacktrace contains this line: __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32

Surely that means something significant? Otherwise, it's impossible to recreate this crash since it happens randomly around 60% of the time on app launch. If it doesn't happen then, it may just happen randomly at any point later for no clear reason at all (no user inputs).

The only possible cause I can think of is firebase database when there's an active listener being notified on incoming data since there's no other input (at least in my case).

This is affecting 100% of my beta users and preventing my launch on iOS.

**Comment by haidarcorp** [comment]
After over 8 hours of debugging I'm confident this issue is caused by firebase_database. It can happen at any point you load data (using .once() and more frequently when you listening on child.

**Comment by zanderso** [comment]
@Salakar @rrousselGit and @russellwheatley are active in the firebase_database repo. Maybe they have some advice for how to proceed.

**Comment by Salakar** [comment]
Hmm, without a _fully_ symbolized (not just Flutter symbols) stack trace that indicates anything relating to Firebase/Database then I'm not sure if I can help on this sorry 🙈 .

However, `firebase_database` is ultimately a thin wrapper on https://github.com/firebase/firebase-ios-sdk - where I have seen similar issues there before for this as well, e.g. https://github.com/firebase/firebase-ios-sdk/issues/8956 so on that the only thing I can suggest right now is to make sure you're using the latest versions of the `firebase_core` and `firebase_database` plugins, since these ship with the latest Firebase iOS SDKs - and if [this](https://github.com/firebase/firebase-ios-sdk/issues/8956.) is ultimately the issue then it _should_ have been resolved.

**Comment by DarioSiroki** [comment]
+1 on this issue. Also I can confirm that this issue started appearing after adding `firebase_database` a week ago.

App is randomly crashing for some testflight users, but not for me so I'm still not sure how to reproduce this...

I'll update if I find out anything

All latest versions are used
```
firebase_core: ^1.16.0
firebase_crashlytics: ^2.7.2
firebase_database: ^9.0.13
firebase_messaging: ^11.3.0
```

Log:

```
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0001f980000003dc -> 0x00000000000003dc (possible pointer authentication failure)
Exception Codes: 0x0000000000000001, 0x0001f980000003dc
VM Region Info: 0x3dc is not in any region.  Bytes before following region: 4305255460
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                   1009d0000-1009d8000 [   32K] r-x/r-x SM=COW  ...er.app/Runner
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: SIGNAL 11 Segmentation fault: 11
Terminating Process: exc handler [12387]

Triggered by Thread:  0

Kernel Triage:
VM - Compressor failed a blocking pager_get

Thread 0 name:
Thread 0 Crashed:
0   libobjc.A.dylib               	0x0000000198e5b528 objc_msgSend + 8
1   Flutter                       	0x00000001043e5694 invocation function for block in SetStreamHandlerMessageHandlerOnChannel(NSObject<FlutterStreamHandler>*, NSString*, NSObject<FlutterBinaryMessenger>*, NSObject<FlutterMethodCodec>*) + 628
2   Flutter                       	0x0000000103f19ce8 flutter::PlatformViewIOS::HandlePlatformMessage(std::__1::unique_ptr<flutter::PlatformMessage, std::__1::default_delete<flutter::PlatformMessage> >) + 516
3   Flutter                       	0x00000001042abca4 std::__1::__function::__func<fml::internal::CopyableLambda<flutter::Shell::OnEngineHandlePlatformMessage(std::__1::unique_ptr<flutter::PlatformMessage, std::__1::default_delete<flutter::PlatformMes... + 92
4   Flutter                       	0x00000001041d3bf0 fml::MessageLoopImpl::FlushTasks(fml::FlushType) + 1668
5   Flutter                       	0x00000001041d71bc fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) + 32
6   CoreFoundation                	0x000000018064a318 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32 (CFRunLoop.c:1812)
7   CoreFoundation                	0x00000001805cecf0 __CFRunLoopDoTimer + 1076 (CFRunLoop.c:2420)
8   CoreFoundation                	0x00000001805c94ec __CFRunLoopDoTimers + 328 (CFRunLoop.c:2580)
9   CoreFoundation                	0x00000001805a7d08 __CFRunLoopRun + 1944 (CFRunLoop.c:3116)
10  CoreFoundation                	0x00000001805bb468 CFRunLoopRunSpecific + 600 (CFRunLoop.c:3268)
11  GraphicsServices              	0x000000019c14638c GSEventRunModal + 164 (GSEvent.c:2200)
12  UIKitCore                     	0x0000000182f5d088 -[UIApplication _run] + 1100 (UIApplication.m:3493)
13  UIKitCore                     	0x0000000182cdb958 UIApplicationMain + 2092 (UIApplication.m:5046)
14  Runner                        	0x00000001009d80cc main + 64 (AppDelegate.swift:8)
15  dyld                          	0x0000000100c95aa4 start + 520 (dyldMain.cpp:879)
```

**Comment by DarioSiroki** [comment]
Seems like this is fixed as of flutter 3.0.0, it's been almost 2 weeks of no crashes now

**Comment by jbxbergdev** [comment]
I'm seeing this issue, too. We also use firebase_database, and the crashes 

Note to maintainers: Please don't lock this issue, since the problem is very much real, but hard to reliably reproduce (i.e. to produce a concise code sample).

**Comment by maheshmnj** [comment]
Thanks for reporting @jbxbergdev, We have seen significantly low crash reports in flutter 3  (zero to my view), From your description, it looks like you are still using `flutter 2` if so, I would suggest upgrading to the latest `stable 3.0.2` and if you still see crash on the latest version then please consider filing the issue and we would be happy to look at your report.
