### ISSUE TITLE
Dart/Flutter never release memory of "Dart/Flutter Native" leading to OOM crash

### ISSUE THREAD

**Issue by NeroThroN** [flutter/flutter#102140]
# Problem
Recently I encounter some crashs on an app because it was Out Of Memory. After some digging with DevTools I quickly found that a scrollable list of images was filling anormaly the memory.
After some testing I have the feeling that pictures are remove from "**Dart/Flutter**" cache but are never release from "**Dart/Flutter Native**" memory.

I've tried to use **cacheWidth** and **cacheHeight** parameters but same issue the memory never empty itself. I've tried **cached_network_image** package but the same issue occurs with the fact that it fills up faster the memory since the images are cached. I've tried also to download the content of pictures (Uint8List) to display with **Image.memory** but same issue occurs. This behaviors confort me that the problem is based on the ListView keeping rasterize children in memory or something like this.

On this graph we can see the evolution of the "**Dart/Flutter Native**" that increase constantly without decreasing in contrary of the "**Dart/Flutter**" that manage smarter the memory consumption.

![Graph](https://user-images.githubusercontent.com/38684083/163982250-da09f6c8-0190-4b3f-af36-15af1cb90da7.png)

On the **Analysis** and **Allocations** tab we can see that the **_List** class is instantiate a large number of times causing to use a lot's of bytes.
![Analysis](https://user-images.githubusercontent.com/38684083/163982726-6ccab558-7019-4b39-9b97-5b94193d4117.png)
![Allocations](https://user-images.githubusercontent.com/38684083/163982828-4bc2a3d7-598c-4825-ba45-9ba5c2c101be.png)

# How to reproduce
In order to reproduce, just create a ListView that contains images. After scrolling for a bunch of minutes, take a look of the analysis tab of Devtool memory page. After poping the screen containing the ListView, memory is never releaseed.

```dart
ListView.builder(
  scrollDirection: Axis.horizontal,
  itemBuilder: (context, index) {
    return Padding(
      padding: const EdgeInsets.all(6),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(12),
        child: AspectRatio(
          aspectRatio: 1,
          child: Container(
            decoration: BoxDecoration(color: Colors.grey[200]),
            child: Image.network(pictures[index % pictures.length], fit: BoxFit.cover),
          ),
        ),
      ),
    );
  },
)
```
I have created a blank flutter project that reproduce this issue : [Complete demo code](https://github.com/NeroThroN/flutter-oom-crash)

# Questions
- What's the solution to this issue ?
- What would be a good alternative to avoid this problem ?
- Is Flutter team aware of this behavior and can create a discussion to view the evolution of a potential solution ?

**Comment by maheshmnj** [comment]
Hi @NeroThroN, Thanks for filing the issue. On which target platform are you experiencing the crash? Please share the complete logs by running `flutter run -v` and the output of `flutter doctor -v`.

**Comment by maheshmnj** [comment]
Thanks for the info @NeroThroN, I am seeing a very high number of instances of `_List`  as soon as the app loads without interacting with the app. This is reproducible on stable and the master channel. 

The below output was reproduced on Xiaomi k20 pro (Android 11) in debug mode.


<img width="1440" alt="image" src="https://user-images.githubusercontent.com/31410839/164164711-85790e11-6cd8-4897-b474-7ed40b654a2e.png">

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Listview sample',
      home: ListViewSample(),
    );
  }
}

class ListViewSample extends StatefulWidget {
  const ListViewSample({Key? key}) : super(key: key);

  @override
  _ListViewSampleState createState() => _ListViewSampleState();
}

class _ListViewSampleState extends State<ListViewSample> {
  final myController = TextEditingController();

  @override
  void dispose() {
    myController.dispose();
    super.dispose();
  }

  List<String> pictures = [
    'https://picsum.photos/250?image=9',
    'https://picsum.photos/250?image=10',
    'https://picsum.photos/250?image=11',
    'https://picsum.photos/250?image=12',
    'https://picsum.photos/250?image=13',
    'https://picsum.photos/250?image=14',
    'https://picsum.photos/250?image=15',
    'https://picsum.photos/250?image=16',
    'https://picsum.photos/250?image=17',
    'https://picsum.photos/250?image=18',
    'https://picsum.photos/250?image=19',
    'https://picsum.photos/250?image=20',
    'https://picsum.photos/250?image=21',
    'https://picsum.photos/250?image=22',
    'https://picsum.photos/250?image=23',
    'https://picsum.photos/250?image=24',
    'https://picsum.photos/250?image=25',
    'https://picsum.photos/250?image=26',
    'https://picsum.photos/250?image=27',
    'https://picsum.photos/250?image=28',
    'https://picsum.photos/250?image=29',
    'https://picsum.photos/250?image=30',
    'https://picsum.photos/250?image=31',
    'https://picsum.photos/250?image=32',
    'https://picsum.photos/250?image=33',
    'https://picsum.photos/250?image=34',
    'https://picsum.photos/250?image=35',
    'https://picsum.photos/250?image=36',
    'https://picsum.photos/250?image=37',
  ];
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: ListView.builder(
      itemCount: pictures.length,
      scrollDirection: Axis.horizontal,
      itemBuilder: (context, index) {
        return Padding(
          padding: const EdgeInsets.all(6),
          child: ClipRRect(
            borderRadius: BorderRadius.circular(12),
            child: AspectRatio(
              aspectRatio: 1,
              child: Container(
                decoration: BoxDecoration(color: Colors.grey[200]),
                child: Image.network(pictures[index % pictures.length],
                    fit: BoxFit.cover),
              ),
            ),
          ),
        );
      },
    ));
  }
}

```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 2.10.5 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (12 hours ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.39.20220405

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:55555                    • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 535317A4-921C-488F-B234-C2CC6D4AE5A1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 100.0.4896.88

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.602, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 2.13.0-0.0.pre.602 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f4875ae865 (34 hours ago), 2022-04-17 15:19:07 -0400
    • Engine revision 3c6d4da868
    • Dart version 2.18.0 (build 2.18.0-24.0.dev)
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.39.20220405

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:55555                    • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 535317A4-921C-488F-B234-C2CC6D4AE5A1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 100.0.4896.88

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by NeroThroN** [comment]
Thanks for your time,

I've copy the code you provide, and juste increase the image size ("https://picsum.photos/250" => "https://picsum.photos/2500") to better see the increase in the memory and be more realistic of some real use cases.

After 3 minutes of scroll back and forth in the listview waiting each image to load before going to the next, here are my results:
![image](https://user-images.githubusercontent.com/38684083/164171450-56c691e8-bafa-4d36-8fee-de6ff23e3b1a.png)

Here I have only reached 0.5GB of memory usage in 3 minutes, but we can see already that "Dart/Flutter"never release it's memory and he is responsible of 80% of the memory used. However the memory usage should be align with the "Dart/Flutter Native", which manages to remain stable during the whole 3 minutes session by deallocating images when there are disposed because out of view.

**Comment by orestesgaolin** [comment]
Experiencing the same or very similar problem. In our case we have even bigger images and bigger allocation number, to the point that Flutter DevTools crash 

![screenshot_2022-04-26_11 34 36](https://user-images.githubusercontent.com/16854239/165270247-97f35809-f4ac-4f3a-8c21-124bdd48899f.png)

**Comment by chinmaygarde** [comment]
cc @dnfield

**Comment by dnfield** [comment]
I'm not really sure what the issue here is. Looking at the allocation map in dev mode proably isn't giving us enough good information, and looking in profile mode doesn't seem to show the same behavior. 

I do see memory go up as you scroll, but it seems to stabilize after a certain point.

**Comment by NeroThroN** [comment]
> I do see memory go up as you scroll, but it seems to stabilize after a certain point. @dnfield

I've created a simple scenario of an app that display a grid of pictures in 2 columns. I added a very basic automatic scroll based on loading of pictures to ensure that a lot's of picture loads before being scrolled away. After a little bit more of 10 minutes of looping through those 75 pictures, DevTools was incredibly slow at the point that it was useless to debug and even if the Android emulator did not crash (compared to a real Android or iOS device) it was running the app at nearly 2 frames/s.

<details>
<summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) => const MaterialApp(home: Home());
}

class Home extends StatelessWidget {
  const Home({Key? key}) : super(key: key);

  Future<void> openGallery(BuildContext context) {
    return Navigator.of(context).push(MaterialPageRoute(builder: (_) => Gallery()));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          child: const Text("Start"),
          onPressed: () => openGallery(context),
        ),
      ),
    );
  }
}

class Gallery extends StatelessWidget {
  final String imageURL = 'https://picsum.photos/2500?image=';
  final int maxImageID = 75;
  final int columns = 2;
  final ScrollController controller = ScrollController();

  Gallery({Key? key}) : super(key: key);

  void animateToOffset(double offset) {
    if (offset > controller.offset) {
      Future.delayed(const Duration(seconds: 1)).then((_) {
        controller.animateTo(
          offset,
          duration: const Duration(seconds: 1),
          curve: Curves.easeInOut,
        );
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    double imageSize = MediaQuery.of(context).size.width / columns;

    return Scaffold(
      appBar: AppBar(title: const Text("Gallery")),
      body: GridView.builder(
        controller: controller,
        gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: columns),
        itemBuilder: (context, index) {
          return Image.network(
            "$imageURL${index % maxImageID}",
            fit: BoxFit.cover,
            height: imageSize,
            width: imageSize,
            frameBuilder: (context, child, frame, _) {
              if (frame == null) return child;
              animateToOffset(imageSize * (index ~/ columns));
              return child;
            },
          );
        },
      ),
    );
  }
}

```

</details>

On these screenshots we can see the evolution of the use of the memory which continues to grow and never disallocates.

- DevTools failing to hold the performance drain:
![DevTools in pain](https://user-images.githubusercontent.com/38684083/166335785-444e7fd7-878d-4221-8d27-78ee3ac9d99a.png)

- The graph of those 12 minutes scrolling in a GridView full of pictures:
![The graph at the end](https://user-images.githubusercontent.com/38684083/166335794-a6bb0aca-61c5-4642-8df6-85039cc2ada0.png)
As seen above as soon as the memory usage approached 2B (Usage limit before crash on real iOS and Android devices) the application was ultra slow to the point where scrolling was rarer because the pictures almost stopped loading.

I completely agree that we can see that "Dart/Flutter native" does not exceed 300MB until the end and is relatively stable throughout the test. The problem comes from the memory taken by "Dart/Flutter" which even after closing the page containing the pictures and waiting several minutes has not emptied what it keeps in memory.

**Comment by dnfield** [comment]
The thing I'd like to understand is whether this happens _only_ in debug mode, or whether it happens in profile mode (and even more importantly, whether it happens in release mode).

If you run your same test just using Xcode or Android studio in release mode for example, do you see similar behavior?
If you run your test in profile mode, does devtools behave better?

It seems like there's _some_ bug here, but right now it's not clear to me if that bug is in tooling/profiling code or in what the user gets as well.

**Comment by NeroThroN** [comment]
These crashes were reported by users on a product already in production following the addition of a screen containing a list full of images (the majority of crashes coming from iOS which seems to be more strict on applications using more than 2B of memory).

It was by looking for where these crashes could come from on my side that I was able to reproduce them on a minimal project and use devtools to try to understand what was happening and when the application was crashing.

So from what I was able to test and encounter, the crash is not dependent on the monitoring tools.

**Comment by dnfield** [comment]
This bug sounds like it's trying to address two problems:

1. An application showing lots of large images in a list view is crashing, particularly on iOS devices.
2. DevTools seems to be showing a leak of memory in debug mode.

For the first issue, this is very likely a bug in the application. Flutter can probably do more to make it harder to achieve this, but it currently provides the necessary API to avoid using more memory than needed when showing images. That said, defaults (particularly the image cache sizing and the fact that images by default decode at full resolution) are still configured in such a way that makes it easy to run out of memory.

The second issue would be good to get a handle on to confirm the first. When I run your samples in profile mode, I cannot recreate the same continued allocation of _List data that I'm seeing in debug mode. That accumulation in debug mode is concerning, but it does not affect the user facing application code.

**Comment by jason-simmons** [comment]
The example app is downloading a list of huge images from the network.

If you click "Open gallery", scroll the image list, and then tap the back button, then I noticed that the images continue to consume resources after the image list is no longer on screen.

One reason for this is the post-frame callback added by `_CachedImageBase.dispose` that disposes the `ImageStreamCompleterHandle` and removes the image from the image cache's `_liveImages` set.

After pressing the back button, some of the large images in the list may still be midway through downloading.  When the download completes, the `_CachedImageBase` object is no longer needed by the UI and will be disposed.  But the image cache is still holding a reference to the underlying image because the post-frame callback has not yet run.

Tapping the "+" button on the main screen will draw a new frame and trigger the post-frame callbacks.  At that point the images will be evicted from `_liveImages` and can be GCed.

After the GC, I still see high resource consumption in the graphics heap (possibly due to Skia caches or other components of the graphics stack).  Not sure what can be done to reclaim those resources more aggressively.

**Comment by quicksystems-auto** [comment]
Guys, In embedded systems, framework shall control memory by notifying App that there is no memory left to add something , so it should not crash system , just  report appropriate code so Application showing issue for user ("Picture is too large"...)
This is sort of of system guard to be a part of framework  to avoid unpredicted behavior.    However I do not know how Flutter framework is designed. Embedded system always has resources limitations.

**Comment by wsb1689** [comment]
I have encountered similar problems. Is there any feasible scheme now？

**Comment by NeroThroN** [comment]
Succeeding seeing @Yeatse PR I wanted to test it to see if thoses changes have any impact on my issue.

After migrating Flutter to the master channel, I ran the exact same code that my past [comment](https://github.com/flutter/flutter/issues/102140#issuecomment-1115434261) and observed very differents results !

![Capture d’écran 2022-05-30 104148](https://user-images.githubusercontent.com/38684083/170957316-a529e566-4769-4842-846a-9954ef5688e1.png)

Memory fluctuates much more than before, but never increases as high as before. Given that we are still quite far from 2GB, I suppose that IOS or Android will stop stopping the application because of too much resource consumption.

On the other hand, I think there is still room for improvement when we see the height of the memory peaks during the test and the "Dart/Flutter" memory which continues to rise at times before collapsing.

**Comment by SamerCat** [comment]
I'm facing the same issue 
have you found any possible solution for it ?

**Comment by NeroThroN** [comment]
@SamerCat
The only solution we use for now to reduce (the problem still there) is to compress the images in the backend before loading them in the application. This makes it possible to load the memory more slowly and therefore to postpone the problem a little.

Despite this, on screens with a lot of images in a listView, the application will eventually crash due to OOM.

**Comment by SamerCat** [comment]
<img width="872" alt="Screen Shot 2022-08-03 at 3 16 16 PM" src="https://user-images.githubusercontent.com/107835083/182595271-6ec6f387-0631-4a96-97f6-8fad95be599e.png">


I solved the issue by adding memCacheHeight and memCacheWidth in this way.
I reduced the memory usage from 2GB to 200MB

**Comment by gslender** [comment]
Also seeing _List growing and growing with no way for it to be released.

Any tips on what might be causing this and where I can look - the tools are not that helpful for _List code ??

This is an app that does continuously refreshes / animations of the UI and left running for 15 mins or so. It just eventually runs out of memory and crashes.

![Screen Shot 2022-10-04 at 5 06 58 pm](https://user-images.githubusercontent.com/2344457/193756475-b2f451ec-49bc-4a5a-9768-3fca94200fa8.png)

**Comment by gslender** [comment]
Same as #111536

**Comment by gslender** [comment]
Just switched to the current Master channel Flutter 3.4.0-40.0.pre.15 and the app memory usage is very stable and no longer growing out of control. Not sure what has improved/changed, but it was fixed in the current master.

**Comment by gslender** [comment]
I get the same positive result running on the current beta, but switching back to stable 3.3.x immediately has the OOM issues. 
```
Flutter 3.4.0-17.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision d6260f127f (2 weeks ago) • 2022-09-21 13:33:49 -0500
Engine • revision 3950c6140a
Tools • Dart 2.19.0 (build 2.19.0-146.2.beta) • DevTools 2.16.0

**Comment by gslender** [comment]
@dnfield are you able to shed light as to what may have been fixed such that is no longer leaking memory so badly? I only ask because the stable release isn't viable for my app, but the beta/master channels are and I'm slightly uncomfortable with this situation if it isn't clear what fixed it

**Comment by monolidth** [comment]
Hi @gslender, 
thanks for the update. However, I face the same issue (even on master, tested today). The sample code is similar to @NeroThroN. Suppose I remove the `Image. network` the issue does not appear anymore. 

So far, I only face this issue on IOS devices and not on an Android device even if both devices have the same memory specs (and have no other applications running in the back). 

So is this issue officially resolved? How can I help you with this issue?

Regards,
William

**Comment by quyenpham6841** [comment]
I'm facing the same issue on stable 3.7.0 😢

**Comment by quyenpham6841** [comment]
Any soulutions or workarounds?

**Comment by SamerOrfali22** [comment]
@quyenpham6841 check my comment https://github.com/flutter/flutter/issues/102140#issuecomment-1203813067

**Comment by quyenpham6841** [comment]
> @quyenpham6841 check my comment [#102140 (comment)](https://github.com/flutter/flutter/issues/102140#issuecomment-1203813067) it worked for me

Thank for your time, I added _memCacheHeight_ and _memCacheWidth_ but it didn't work for me.

**Comment by NeroThroN** [comment]
> @quyenpham6841 check my comment [#102140 (comment)](https://github.com/flutter/flutter/issues/102140#issuecomment-1203813067) it worked for me

The problem of your solution is that for non-square pictures, they are not cropped but crushed to the specified memCacheHeight and memCacheWidth. And there is no solution to get the size of the picture before to calculate the ratio.

**Comment by NeroThroN** [comment]
> Any soulutions or workarounds?

If you can, reduce the size of your pictures to display from your backend
It doesn't solve the problem, but at least it keeps it away a little bit

**Comment by quyenpham6841** [comment]
Thank you @NeroThroN, I have tried the ways people mentioned but it seems that the image size is still too big but cannot be reduced anymore. "_List growing and growing with no way for it to be released." - it happened to me. Only in Profile / Release mode. Debug works just fine. (Sorry, my English is not good)

**Comment by anchaoLu** [comment]
In my cases, this only appears when the app is installed and launched for the first time. After relaunch the app, it becomes normal.

app first launch
<img width="1870" alt="截屏2023-02-06 15 17 22" src="https://user-images.githubusercontent.com/106209730/216907912-dc390df9-82d7-4282-a0f5-cf087db018d8.png">
<img width="654" alt="截屏2023-02-06 15 04 00" src="https://user-images.githubusercontent.com/106209730/216907929-49920a3f-6de8-4e2a-bfbc-c36437cec256.png">

app exit and relaunch
<img width="1857" alt="截屏2023-02-06 15 22 50" src="https://user-images.githubusercontent.com/106209730/216909727-4664a6ae-d3b3-4e46-bbca-f27b342fd723.png">
<img width="698" alt="截屏2023-02-06 15 22 41" src="https://user-images.githubusercontent.com/106209730/216909747-0c0d8f84-11e3-482c-b939-5f0caec3de12.png">'

flutter doctor -v
```dart
$ flutter doctor -v                      
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.3.9 on channel stable at /Users/luanchao/Desktop/Development/SDKS/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (3 months ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/luanchao/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.75.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • iPhone1 (mobile) • 00008101-001A4DC41440001E • ios            • iOS 15.6 19G71
    • macOS (desktop)  • macos                     • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm
    • Chrome (web)     • chrome                    • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by inc16sec** [comment]
Started facing this issue after upgrading to 3.7.0. Right now I'm on 3.7.3 and the app is still crashing. In my case, I have a list of images and I don't even have to scroll down for it to run out of memory. Like all I do is launch the app (debug or profile mode) and not scroll at all, and it will run out of memory after a while (20 mins or so). Resizing the images won't do it for me too because the app relies on a list of posts that can contain images (think a social network kinda app). The app was working fine until 3.3.10 (although I don't know if it was consuming a lot of memory because It wasn't crashing), but after upgrading to 3.7.0 it started to crash. I've had to limit the images on a list but still crashes.
This issue means (unfortunately) my app can't be useable. I love Flutter and I appreciate the work that the Flutter team does. I have high hope when it comes to this issue being resolved and hopefully, it will be soon. GOD BLESS ALL.

**Comment by moisey312** [comment]
I have the same problem

**Comment by NeroThroN** [comment]
It's been a long time, several versions of Flutter have been released since my issue.
I wanted to test if the problem was still present, for that I took the code sample I had done [previously](https://github.com/flutter/flutter/issues/102140#issuecomment-1115434261)

<details>
<summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) => const MaterialApp(home: Home());
}

class Home extends StatelessWidget {
  const Home({Key? key}) : super(key: key);

  Future<void> openGallery(BuildContext context) {
    return Navigator.of(context).push(MaterialPageRoute(builder: (_) => Gallery()));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          child: const Text("Start"),
          onPressed: () => openGallery(context),
        ),
      ),
    );
  }
}

class Gallery extends StatelessWidget {
  final String imageURL = 'https://picsum.photos/2500?image=';
  final int maxImageID = 75;
  final int columns = 2;
  final ScrollController controller = ScrollController();

  Gallery({Key? key}) : super(key: key);

  void animateToOffset(double offset) {
    if (offset > controller.offset) {
      Future.delayed(const Duration(seconds: 1)).then((_) {
        controller.animateTo(
          offset,
          duration: const Duration(seconds: 1),
          curve: Curves.easeInOut,
        );
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    double imageSize = MediaQuery.of(context).size.width / columns;

    return Scaffold(
      appBar: AppBar(title: const Text("Gallery")),
      body: GridView.builder(
        controller: controller,
        gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: columns),
        itemBuilder: (context, index) {
          return Image.network(
            "$imageURL${index % maxImageID}",
            fit: BoxFit.cover,
            height: imageSize,
            width: imageSize,
            frameBuilder: (context, child, frame, _) {
              if (frame == null) return child;
              animateToOffset(imageSize * (index ~/ columns));
              return child;
            },
          );
        },
      ),
    );
  }
}

```

</details>

As can be seen in the screenshot, I let the application scroll in the gallery automatically for about 4 minutes (20:41 - 20:45).

During this period of time, memory raise to just over 1GB while looping through the same 75 images in a `GridView` that eliminates widgets to normally free up memory.

To end the automatic scrolling, I left the screen to return to the previous one (20:45). After 2 more minutes, it can be seen that the memory was not freed despite the fact that the screen containing the image gallery should be cleared from memory.

![image](https://github.com/flutter/flutter/assets/38684083/8419ac67-6a7c-4867-a09e-8b2141acc5e5)

**Comment by SoftWyer** [comment]
Possibly related to [this issue](https://github.com/flutter/flutter/issues/128099)?

**Comment by gnprice** [comment]
Indeed, #128099 sounds like it's the same issue. Thanks @SoftWyer for drawing that connection!

From your comment https://github.com/flutter/flutter/issues/128099#issuecomment-1700858552 it sounds like that issue is currently fixed in main, though not yet in a beta release. @NeroThroN @inc16sec or anyone else who has a reproducer for this issue: if you try it with Flutter from the main/master channel, does it still reproduce?

**Comment by NeroThroN** [comment]
I've switch to the master channel (with [fvm](https://fvm.app/))
<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.14.0-13.0.pre.68, on Fedora Linux 38 (Workstation Edition) 6.4.12-200.fc38.x86_64, locale en_US.UTF-8)
    • Flutter version 3.14.0-13.0.pre.68 on channel master at /home/nerothron/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4324d2112e (33 minutes ago), 2023-09-01 02:45:32 -0400
    • Engine revision 0769aba5b7
    • Dart version 3.2.0 (build 3.2.0-128.0.dev)
    • DevTools version 2.27.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/nerothron/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /var/lib/snapd/snap/android-studio/127/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6 (Fedora 16.0.6-2.fc38)
    • cmake version 3.27.3
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[✓] Android Studio (version 2022.3)
    • Android Studio at /var/lib/snapd/snap/android-studio/127/android-studio
    • Flutter plugin version 75.1.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.81.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Fedora Linux 38 (Workstation Edition) 6.4.12-200.fc38.x86_64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 118.0.5966.0 dev

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

I re-ran the same code as for my [previous comment](https://github.com/flutter/flutter/issues/128099#issuecomment-1692258504)

And here are the results after about 6 minutes of scrolling:
![image](https://github.com/flutter/flutter/assets/38684083/602d6572-6d85-411e-a3c8-7ce3c0069609)

I'm amazed at the difference in performance between the tests! I am filled with hope that such improvements can be achieved in the stable branch soon!

**Comment by kirill-21** [comment]
Faced the same issue, had multiple images shown in GridView.builder, memory usage was something around 900MB for 20 images. Updated Flutter to master branch, RSS memory is less for ~200MB, but it's still not good, overall usage of 700MB for 20 images does not look normal 
![image](https://github.com/flutter/flutter/assets/63228361/2aea1826-0c9e-4bab-8ea8-1238eb043615)

**Comment by kirill-21** [comment]
> > @quyenpham6841 check my comment [#102140 (comment)](https://github.com/flutter/flutter/issues/102140#issuecomment-1203813067) it worked for me
> 
> Thank for your time, I added _memCacheHeight_ and _memCacheWidth_ but it didn't work for me.

For me too, but i tested maxHeightDiskCache & maxWidthDiskCache and it seems to work better

**Comment by ayyoubelamrani4** [comment]
> ```
> 3.14
> ```

@NeroThroN is this fixing the issue? what flutter version is it?

**Comment by NeroThroN** [comment]
> @NeroThroN is this fixing the issue? what flutter version is it?

@ayyoubelamrani4  Yes this issue is fixed, but only on the master channel, not the stable nor the beta
I'll keep this issue open as long as this is not the case in the stable channel

**Comment by ayyoubelamrani4** [comment]
> > @NeroThroN is this fixing the issue? what flutter version is it?
> 
> @ayyoubelamrani4 Yes this issue is fixed, but only on the master channel, not the stable nor the beta I'll keep this issue open as long as this is not the case in the stable channel

@NeroThroN Thanks! do you know in what flutter version this would be released?

**Comment by ayyoubelamrani4** [comment]
Was this fixed in Flutter 3.16?

**Comment by SoftWyer** [comment]
> Was this fixed in Flutter 3.16?

It does appear to now be fixed in Stable with 3.16.

**Comment by JulianBissekkou** [comment]
Can someone from the dart team confirm this?

**Comment by NeroThroN** [comment]
> I've switch to the master channel (with [fvm](https://fvm.app/))
> Doctor output
> 
> I re-ran the same code as for my [previous comment](https://github.com/flutter/flutter/issues/128099#issuecomment-1692258504)
> 
> And here are the results after about 6 minutes of scrolling: ![image](https://user-images.githubusercontent.com/38684083/264952377-602d6572-6d85-411e-a3c8-7ce3c0069609.png)
> 
> I'm amazed at the difference in performance between the tests! I am filled with hope that such improvements can be achieved in the stable branch soon!

I reran the same code again with Flutter version 3.16, and here are the results:

![image](https://github.com/flutter/flutter/assets/38684083/cc651487-e5a2-4d5f-ab17-0e79a38ac7bf)

So theses fixes inside master branch aren't on stable branch yet unfortunately :(

**Comment by jipersonlloyd** [comment]
Does anyone can confirm if it's already fixed in 3.16 or not TIA

**Comment by mennovanhout** [comment]
Still a problem it seems like

**Comment by kirill-21** [comment]
Stabe/master branches still have this problem. Yeah, memory is cleaned sometimes, to ~1.5GB... but then within a few seconds it fills even more
![image](https://github.com/flutter/flutter/assets/63228361/51887cb4-4fd0-49fa-a3db-8ffcdb2382af)

This is Release build btw

**Comment by bradv123** [comment]
I am running into this same problem. Is there any ETA of when this will be solved in stable?

**Comment by Passer-by** [comment]
I have the same issue

**Comment by Passer-by** [comment]
3.19 fix this issue？

**Comment by NeroThroN** [comment]
> Does anyone know the cause of this bug or if there's a fix for?

@resucutie 
Can you please try running you app with the `master` channel ? 
Since I create the issue, there have been no changes in the `stable` version that really fixes it. But the `master` version seems to have much better performance (Although it doesn't seem to be perfect for all platforms)

**Comment by resucutie** [comment]
> > Does anyone know the cause of this bug or if there's a fix for?
> 
> @resucutie 
> Can you please try running you app with the `master` channel ? 
> Since I create the issue, there have been no changes in the `stable` version that really fixes it. But the `master` version seems to have much better performance (Although it doesn't seem to be perfect for all platforms)
> 

I tested it and the RAM usage didn't change at all. Still skyrocketing to 1.1GB of usage

**Comment by tofylion** [comment]
Not sure if this will be the same issue with someone. If you're using `CachedNetworkImage`, this may help you
My issue was with RSS memory usage being too high while the dart heap taking very little memory. The pages I opened, the more the RSS memory increased without going down. Of course, the app crashed after using it for a while.

## Problem:
Surprisingly, my problem was with the cached_network_image library. When I replaced the `CachedNetworkImage` widget with a container, the issue disappeared.

**Code:**
Here's the code that caused the problem:
```dart
CachedNetworkImage(
      imageUrl: imageUrl,
      ...
      imageBuilder: (context, imageProvider) => Image(
          width: width,
          height: height,
          fit: fit,
          image: ResizeImage(imageProvider,
              width: width,
              height: height,)));
```

## Solution:
For some reason, using the `CachedNetworkImage` widget with the image builder that I used caused memory leaks. The solution was simple. Instead of having the `CachedNetworkImage` as the widget I returned, I used the `CachedNetworkImageProvider` and placed it in an `Image` widget.

**Code:**
```dart
late final imageProvider = CachedNetworkImageProvider(
    widget.imageUrl,
    cacheKey: widget.imageUrl,
    cacheManager: cacheManager,
    headers: widget.httpHeaders,
  );
return Image(
      image: ResizeImage(
          imageProvider,
          width: widget.width.cacheSize(context),
          height: widget.height.cacheSize(context),
          policy: ResizeImagePolicy.fit,
        )));
```

## Cause:
I'm not sure what the cause was to be honest. I suspect that the imageProvider would get referenced somewhere. I'm glad it works and would like to discuss what may be causing the issue

**Comment by resucutie** [comment]
On my research I saw some people way back on 2019-2020 reporting the issue, and their solution was then fixed on an update. But they were reporting for network images, so I guess the fix only went to network images

Do you have a solution for local images? My app requires to load multiple images from local storage, so it is very much appreciated a solution for

**Comment by resucutie** [comment]
Found the solution to my issue

Flutter decompresses the images when loading them, and as such if you have a 4000x4000 image, it'll decompress to 16MB (if 1 pixel = 1 byte), no matter if the file size is lower than that

As such, using ResizeImage will reduce the amount of ram used

**Comment by boomery** [comment]
same problem

**Comment by Toasbi** [comment]
Could this be related to this OctoImage issue, which is in this lib as well?
https://github.com/Baseflow/octo_image/issues/26
