### ISSUE TITLE
'WidgetsBinding' runtime warnings using 3.0.0 stable release

### ISSUE THREAD

**Issue by pattobrien** [flutter/flutter#103561]
## Pre-Requisites

- Flutter installed with the latest 3.0.0 stable, using FVM version manager.

## Steps to Reproduce

1. Execute `flutter create test_app` to create a new app
2. Execute `flutter run` to build and run app

**Expected results:** 

No warnings in debug console.

**Actual results:** 

The following warnings are seen:

```
 Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
../…/src/framework.dart:275
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../fvm/versions/stable/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
    if (SchedulerBinding.instance!.schedulerPhase ==
                         ^
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
../…/src/widgets_binding_observer.dart:42
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../fvm/versions/stable/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
    _state = WidgetsBinding.instance!.lifecycleState;
                            ^

: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
../…/src/widgets_binding_observer.dart:43
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../fvm/versions/stable/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
    WidgetsBinding.instance!.addObserver(this);
                   ^
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
../…/src/widgets_binding_observer.dart:52
```

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
```

```
fvm flutter analyze
Analyzing custom_widgets_custom_themes...                       
No issues found! (ran in 0.9s)
```

```
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm, locale en-US)
    • Flutter version 3.0.0 at /Users/pattobrien/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (2 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/pattobrien/Library/Android/sdk
    • Platform android-31, build-tools 33.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • iPhone 12 Pro (mobile) • 0296EE26-719D-4F1A-B59D-50FCB6EC3F7E • ios          • com.apple.CoreSimulator.SimRuntime.iOS-15-4
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64 • macOS 12.3.1 21E258 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by hiranlakshika** [comment]
@pattobrien Did you find any temp fix for this?

**Comment by meitesi** [comment]
The same problem was found

**Comment by ingmferrer** [comment]
same warnings for me

**Comment by yk3372** [comment]
@[Hixie](https://github.com/flutter/flutter/commits?author=Hixie) 
How do we make compatibility with this change for plugins，thanks? https://github.com/flutter/flutter/pull/89451

**Comment by pattobrien** [comment]
> @pattobrien Did you find any temp fix for this?

nope, no workaround found yet.

**Comment by maxlapides** [comment]
You can just ignore the errors for now :)

**Comment by darshankawar** [comment]
Can somebody try to run `dart fix --apply` and see if the warnings go away ?
Also, they seem to be warnings and may not be hampering the build flow. Probably this PR might be related https://github.com/flutter/flutter/pull/89451

**Comment by dkbast** [comment]
fixed them all in my code, but I get messages from dependencies which is quite annoying

**Comment by GitHelge** [comment]
Can we somehow suppress the warnings in third party dependencies? - It makes logs unreadable on _flutter test_

**Comment by darshankawar** [comment]
These warnings could also be the result of the fact that Flutter 3 introduces nullability changes to WidgetsBinding.

**Comment by ChrisElliotUK** [comment]
> Can somebody try to run `dart fix --apply` and see if the warnings go away ? Also, they seem to be warnings and may not be hampering the build flow. Probably this PR might be related #89451

This fixed my issue from here: https://github.com/flutter/flutter/issues/103571#issuecomment-1124731837

**Comment by darshankawar** [comment]
These warnings could also be the result of the fact that Flutter 3 introduces nullability changes to WidgetsBinding.

**Comment by darshankawar** [comment]
These warnings could also be the result of the fact that Flutter 3 introduces nullability changes to WidgetsBinding.

**Comment by AnAlpaca** [comment]
This issue has NOT gone away for me after running dart fix --apply unfortunately. Below is the only thing that shows in my terminal as an error and not a warning.

`Error: The non-abstract class 'GaMaterialLocalizations' is missing implementations for these members:
 - MaterialLocalizations.keyboardKeyAlt
 - MaterialLocalizations.keyboardKeyAltGraph
 - MaterialLocalizations.keyboardKeyBackspace
 - MaterialLocalizations.keyboardKeyCapsLock
 - MaterialLocalizations.keyboardKeyChannelDown
 - MaterialLocalizations.keyboardKeyChannelUp
 - MaterialLocalizations.keyboardKeyControl
 - MaterialLocalizations.keyboardKeyDelete
 - MaterialLocalizations.keyboardKeyEisu
 - MaterialLocalizations.keyboardKeyEject
 - MaterialLocalizations.keyboardKeyEnd
 - MaterialLocalizations.keyboardKeyEscape
 - MaterialLocalizations.keyboardKeyFn
 - MaterialLocalizations.keyboardKeyHangulMode
 - MaterialLocalizations.keyboardKeyHanjaMode
 - MaterialLocalizations.keyboardKeyHankaku
 - MaterialLocalizations.keyboardKeyHiragana
 - MaterialLocalizations.keyboardKeyHiraganaKatakana
 - MaterialLocalizations.keyboardKeyHome
 - MaterialLocalizations.keyboardKeyInsert
 - MaterialLocalizations.keyboardKeyKanaMode
 - MaterialLocalizations.keyboardKeyKanjiMode
 - MaterialLocalizations.keyboardKeyKatakana
 - MaterialLocalizations.keyboardKeyMeta
 - MaterialLocalizations.keyboardKeyMetaMacOs
 - MaterialLocalizations.keyboardKeyMetaWindows
 - MaterialLocalizations.keyboardKeyNumLock
 - MaterialLocalizations.keyboardKeyNumpad0
 - MaterialLocalizations.keyboardKeyNumpad1
 - MaterialLocalizations.keyboardKeyNumpad2
 - MaterialLocalizations.keyboardKeyNumpad3
 - MaterialLocalizations.keyboardKeyNumpad4
 - MaterialLocalizations.keyboardKeyNumpad5
 - MaterialLocalizations.keyboardKeyNumpad6
 - MaterialLocalizations.keyboardKeyNumpad7
 - MaterialLocalizations.keyboardKeyNumpad8
 - MaterialLocalizations.keyboardKeyNumpad9
 - MaterialLocalizations.keyboardKeyNumpadAdd
 - MaterialLocalizations.keyboardKeyNumpadComma
 - MaterialLocalizations.keyboardKeyNumpadDecimal
 - MaterialLocalizations.keyboardKeyNumpadDivide
 - MaterialLocalizations.keyboardKeyNumpadEnter
 - MaterialLocalizations.keyboardKeyNumpadEqual
 - MaterialLocalizations.keyboardKeyNumpadMultiply
 - MaterialLocalizations.keyboardKeyNumpadParenLeft
 - MaterialLocalizations.keyboardKeyNumpadParenRight
 - MaterialLocalizations.keyboardKeyNumpadSubtract
 - MaterialLocalizations.keyboardKeyPageDown
 - MaterialLocalizations.keyboardKeyPageUp
 - MaterialLocalizations.keyboardKeyPower
 - MaterialLocalizations.keyboardKeyPowerOff
 - MaterialLocalizations.keyboardKeyPrintScreen
 - MaterialLocalizations.keyboardKeyRomaji
 - MaterialLocalizations.keyboardKeyScrollLock
 - MaterialLocalizations.keyboardKeySelect
 - MaterialLocalizations.keyboardKeySpace
 - MaterialLocalizations.keyboardKeyZenkaku
 - MaterialLocalizations.keyboardKeyZenkakuHankaku
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.`

**Comment by pranavo72bex** [comment]
Facing same issue 

`dart fix --apply`

It wouldn't work for me.

**Comment by blue492** [comment]
This command NOT helped me `dart fix --apply` Android studion still show same warnings, and cant run the flutter app on it

**Comment by darshankawar** [comment]
Circling back on this issue, the warnings seems to be coming from framework itself and as mentioned earlier, could be related to https://github.com/flutter/flutter/pull/89451

If the warnings are coming from community plugins / packages, the fix need to be made in respective packages. 

Based on the report and the traction received for this issue, I am going ahead and labeling it for further insights from the team.

/cc @Hixie

**Comment by bulletBane** [comment]
May be you can try 'flutter pub upgrade'

**Comment by Hixie** [comment]
It sounds like there are several issues being discussed here.

If you are seeing `Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.`, then that is this bug. The actual issue in that case is that either your code or a dependency can be updated to remove some null checks, because we simplified some of the APIs to be non-nullable. If it is your code, running `dart fix --apply` should fix it. If it is a dependency's code, then the developer of that dependency should be able to do it and release a new version. In either case, these warnings are non-fatal and should not cause any problems beyond being annoying in the logs (for which we apologize, we're [considering](https://github.com/dart-lang/sdk/issues/46264) removing warnings of this nature from the compilation flow in the future).

If you are seeing other warnings, for example relating to `GaMaterialLocalizations`, that is a separate issue, please file a separate issue on GitHub so that we can track that separately.

If these warnings are in any way preventing your code from building or running, that is a very serious problem, please file a separate issue with the logs and a test case we can use to reproduce the failure. It should definitely not be the case that these warnings are causing builds to fail. They are supposed to be non-fatal warnings.

**Comment by pattobrien** [comment]
> If you are seeing `Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.`, then that is this bug. The actual issue in that case is that either your code or a dependency can be updated to remove some null checks, because we simplified some of the APIs to be non-nullable. If it is your code, running `dart fix --apply` should fix it. 

As mentioned in the original issue, the only dependency is the Flutter SDK and the app in question is the starter counter project. The only other tool dependency I have is FVM, but I assume this is not a source of the problem (if you need me to check with a fresh SDK install without FVM, I can do that).

I agree that this isn't the highest priority issue - especially with 3.0.0 just having shipped, I'm sure there are other higher prio issues that will surface. But please keep in mind that 'ignoring' 100% reproducible warnings (no matter severity) is a relatively bad DX, which is evident from the amount of activity this issue has received in 24 hours.

That said, such complaints are easy to make when the standards for DX have been made so high in the first place... All in all, this is a very small price to pay for an otherwise amazing major release, which I will still be migrating to even on production releases, warning or no warning; so sincerely, thank you Flutter team for your effort!

**Comment by Hixie** [comment]
That should definitely not be happening without any dependencies other than the core framework. It does look like from the logs there might be an fvm issue (I see "fvm" in the paths). In fact now that I look closer, the quoted code does not exist in the framework any more in the way shown in those error messages...

**Comment by realArafatBen** [comment]
Hi, 
Having the same issue. i just upgraded to 3.0.0

**Comment by pattobrien** [comment]
> That should definitely not be happening without any dependencies other than the core framework. It does look like from the logs there might be an fvm issue (I see "fvm" in the paths). In fact now that I look closer, the quoted code does not exist in the framework any more in the way shown in those error messages...

According to other commenters ([like here](https://github.com/flutter/flutter/issues/103561#issuecomment-1124881972)), not everyone is using FVM and is still encountering the problem. Keep in mind, FVM is just the folder that contains the multiple flutter versions, which can be switched to dynamically. Within that Flutter is the standard SDK files, which is no different than using any other folder to store the SDK. I highly doubt this is the source of the problem.

**Comment by leoafarias** [comment]
@pattobrien can you open an issue on https://github.com/fluttertools/fvm ?.. it seems the analyzer is not ignoring the linked project, but I need more info..

**Comment by Hixie** [comment]
What's strange is that the error message shown above points to code that no longer exists in 3.0.0. It suggests that something is happening during the update that means the compiler is hitting different code than what is currently checked out.

It would be interesting if someone who is hitting this without using fvm could let me know, if you look at the file that is mentioned in the warning message, does it actually contain the exact code that the warning message includes?

**Comment by alper-efe-sahin** [comment]
I am having the same issue!

**Comment by Egessa** [comment]
I suggest a downgrade. Apparently after downgrading to the previous flutter version my code runs and build without the warning. 
Will definitely upgrade when the flutter teams gets a solution to this

**Comment by leoafarias** [comment]
@Hixie I was able to replicate the issue by creating a new app, with a fresh install of 3.0.0 (no fvm). I added a dependency called flutter_typeahead which is a dependency I was able to see the issue.

When running `flutter run` on ios (macOS does not happen), I am able to see the error as described by @pattobrien 

Here is a repository that you can just clone and build
https://github.com/leoafarias/flutter_3_0_0_widget_binding

Hopefully, this helps.

**Comment by Hixie** [comment]
@leoafarias Yes, dependencies that have not yet updated are expected to show this until they migrate (they just need to run `dart fix --apply`). The original report is different from that, however, it shows an app with no dependencies having this problem.

**Comment by kkoken** [comment]
I am wondering one aspect of this nullabilty change. Will people face the same thing like 1.xx to 2.xx migration? (Plugins started not to work and warning all over.)

Correct me if I am wrong, this is killing backwards compatibility. When you are app relies on flutter 2.xx and new version of the plugin relies on flutter 3.xx so your app won't get the new features/fixes.

Do not get me wrong, i love what flutter team do, but this creates additional development cost.

**Comment by Hixie** [comment]
@kkoken As new features are added, and APIs changed, there will be plugins that take advantage of those features and APIs and thus are not compatible with earlier versions, sure. In the case of the binding.instance API change, though, there's an [easy workaround](https://github.com/flutter/website/blob/3e6d87f13ad2a8dd9cf16081868cc3b3794abb90/src/development/tools/sdk/release-notes/release-notes-3.0.0.md#your-code) that allows plugins to continue to work with the older API. See also [Stuart's comment](https://github.com/flutter/flutter/issues/103583#issuecomment-1125497847).

**Comment by kkoken** [comment]
> @kkoken As new features are added, and APIs changed, there will be plugins that take advantage of those features and APIs and thus are not compatible with earlier versions, sure. In the case of the binding.instance API change, though, there's an [easy workaround](https://github.com/flutter/website/blob/3e6d87f13ad2a8dd9cf16081868cc3b3794abb90/src/development/tools/sdk/release-notes/release-notes-3.0.0.md#your-code) that allows plugins to continue to work with the older API. See also [Stuart's comment](https://github.com/flutter/flutter/issues/103583#issuecomment-1125497847).

Thank you for your kind answer. i will keep in mind references you mentioned.

**Comment by Hixie** [comment]
@realArafatBen can you give more detail about what you're seeing? is the error in your own code, in the framework, or in your dependencies?

**Comment by Hixie** [comment]
@pattobrien have you had any luck determining what is happening in your case? I'm concerned that the error message is pointing to code that doesn't exist any more in 3.0.0, and nothing we've investigated so far has unearthed anything that could cause that...

**Comment by Hixie** [comment]
@AnAlpaca your case seems to be slightly different, if you're still seeing this can you file a separate bug with more information? thanks

**Comment by Hixie** [comment]
@kkoken interesting, that sounds serious. Can you file a separate bug for that?

**Comment by kkoken** [comment]
> @kkoken interesting, that sounds serious. Can you file a separate bug for that?

i will check again in the morning, if it continues, i will file it.

**Comment by pattobrien** [comment]
@Hixie after having it work on another similar machine of mine, I tried creating a new project on the M1 Mac from the original filing and it's now working too. To be honest I'm not quite sure what has changed since yesterday.

If I see the error again, I'll try to investigate it in more depth (follow the warning down the dependency tree)... Until then, I guess this issue can be closed.

**Comment by josepaulodelacruz** [comment]
> A temporary solution is downgrading: `flutter downgrade v2.10.5`

I reverted back to my previous version. The error stills occur after this.

**Comment by sefadincer** [comment]
`../../../../flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/router_report.dart:53:22: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.addPostFrameCallback((_) {
                     ^
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/snackbar/snackbar.dart:452:22: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../../flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance!.addPostFrameCallback(
                     ^
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/extension_navigation.dart:357:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../../flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((_) {
                       ^
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/extension_navigation.dart:468:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../../flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((_) {
                       ^
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_state_manager/src/simple/get_controllers.dart:90:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(this);
                   ^
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_state_manager/src/simple/get_controllers.dart:96:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.removeObserver(this);
                   ^
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_state_manager/src/rx_flutter/rx_notifier.dart:130:22: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../../flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance?.addPostFrameCallback((_) => onReady());
                     ^
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_state_manager/src/rx_flutter/rx_disposable.dart:20:22: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../../flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance?.addPostFrameCallback((_) => onReady());`

**Comment by Hixie** [comment]
@sefadincer Those should be non-fatal warnings, and will get resolved when the package mentioned there is updated (namely `get`).

**Comment by Hixie** [comment]
@pattobrien actually looking more closely at the logs you posted it's possible that they are being truncated in a misleading way -- I think the framework URLs I thought were indicating that the framework was broken are actually just saying where the type comes from, and the part of the message that is truncated (with an ellipsis) shows the actual source of the problem (which might have been fixed by `dart fix --apply` or might have been fixed upstream if it was in a package).

**Comment by JacoFourie** [comment]
Dart 2.17 has new lint rules. I think it is those rules that are breaking Flutter 3. I also have this issue. I have been looking around and found this.

https://github.com/dart-lang/lints/blob/main/CHANGELOG.md#200

I think it may be this one

unnecessary_null_aware_assignments

**Comment by cremfert** [comment]
I experiencing the same issue, the warning comes from framework code I guess:
`.../flutter-3.0/.pub-cache/hosted/pub.dartlang.org/macos_ui-1.3.0/lib/src/buttons/pulldown_button.dart`
The file and the mentioned codeline exists in the file (line 771ff):
```
@override
  void dispose() {
    WidgetsBinding.instance!.removeObserver(this);
    _removeMacosPulldownRoute();
    WidgetsBinding.instance!.focusManager
        .removeHighlightModeListener(_handleFocusHighlightModeChange);
    focusNode!.removeListener(_handleFocusChanged);
    _internalNode?.dispose();
    super.dispose();
  }
```
I'm not using fvm, but I will go back to 2.10.5 for safety reasons.
Any other ideas what I can do?

Thanks a lot.

**Comment by darshankawar** [comment]
Everyone in this thread who is facing warnings related to `WidgetsBinding`, please see [this](https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#if-you-see-warnings-about-bindings) link on various solutions.

**Comment by bleroux** [comment]
@cremfert This warning does not come from the framework code. It comes from a third-party package: [macos_ui](https://pub.dev/packages/macos_ui/example). It probably will soon be updated.

**Comment by Fraa-124** [comment]
> Everyone in this thread who is facing warnings related to `WidgetsBinding`, please see [this](https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#if-you-see-warnings-about-bindings) link for various solutions.

That doesn't work, I'm afraid a lot projects, the vast majority won't be able to upgrade to Flutter 3 in a while, because not all packages will be able to update to reflect this change.

**Comment by Hixie** [comment]
@cremfert @Fraa-124 These warnings should not be breaking anything (just causing log spam, for which we apologize; we plan to fix that in the next release, we didn't realize how big of an issue it would be). If your app no longer works, that is unlikely to be related to this issue and I urge you to file a separate issue so we can debug that with you.

**Comment by realArafatBen** [comment]
@Hixie having an error about widgetBinding anytime I try building my app. Becoz how often this happens I have to downgrade back to v2.10 for now.

**Comment by Hixie** [comment]
@realArafatBen If you're getting an _error_, not a warning, please file a new bug, that should not be happening.

**Comment by kumangho** [comment]
any one fixed this issue, please answer to[]( https://stackoverflow.com/questions/72210211/warning-operand-of-null-aware-operation-has-type-widgetsbinding-which-exc)

**Comment by kumangho** [comment]
any one fixed this issue, please answer here.

https://stackoverflow.com/questions/72210211/warning-operand-of-null-aware-operation-has-type-widgetsbinding-which-exc

thanks.

**Comment by kumangho** [comment]
if you are using device preview package.
check this. https://github.com/aloisdeniel/flutter_device_preview/issues/183

**Comment by AxanIqbal** [comment]
the flutter pub upgrade did fix my crash that prevent me from build. i guess some packages really needs to upgrade/check if its compatible with v3

**Comment by ahmadbintariq4u** [comment]
dependencies needs to be upgraded!!, wait for the authors to update the dependencies.

**Comment by Nayuta403** [comment]
I have released a small tool that can solve this problem with a single command.
https://pub.dev/packages/upgrade_tool  😘

**Comment by Nayuta403** [comment]
#103853

**Comment by maheshmnj** [comment]
Those warnings are coming from third-party plugins compiled against the older version of flutter, Updating the plugin code with `dart fix --apply` as mentioned in the [release notes](https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#if-you-see-warnings-about-bindings) should help fix this issue. To reiterate this is just a warning this shouldn't break the build process.

originally filed here https://github.com/flutter/flutter/issues/101497 (closed)

**Comment by kaanaytemir** [comment]
Changing my Kotlin version (manually), did the trick.

You can do that in your `build.gradle`.

```
buildscript {
    ext.kotlin_version = '1.6.21'
    repositories {
        google()
        jcenter()
    }
```

**Comment by ahmadrafidev** [comment]
> Upgrading my Kotlin version (manually), did the trick.
> 
> You can do that in your `build.gradle`.
> 
> ```
> buildscript {
>     ext.kotlin_version = '1.6.21'
>     repositories {
>         google()
>         jcenter()
>     }
> ```

doing the same thing, not work for me.

**Comment by YassineChe** [comment]
In my case i use
```
flutter.targetSdkVersion=31
flutter.minSdkVersion=30
```
All these warning will disappear

**Comment by cbalmeida** [comment]
Backward compatibility says 'Hi!' to Dart/Flutter team! 
At least they are consistent! Every f* single time they release a new version, they break something!

**Comment by pranavo72bex** [comment]
Any update ?

**Comment by BerndWessels** [comment]
Same here, upgraded to Flutter 3 and created a brand new app and getting:

```
Performing hot reload...
Syncing files to device Android SDK built for x86...
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_web_auth-0.4.1/lib/flutter_web_auth.dart:33:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.removeObserver(_resumedObserver); // safety measure so we never add this observer twice
                   ^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_web_auth-0.4.1/lib/flutter_web_auth.dart:34:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addObserver(_resumedObserver);
                   ^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_web_auth-0.4.1/lib/flutter_web_auth.dart:47:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.removeObserver(_resumedObserver);
                   ^
Reloaded 0 libraries in 193ms.
```

**Comment by hassanannajjar** [comment]
The same issue 💻 
Any update?

**Comment by skuzakov-voc** [comment]
The same issue here. As far as I understand now, you can either ignore the warnings from third-party dependencies, or roll back to the previous version and wait until the dependency versions are updated to compatible with flutter 3.0.

**Comment by JacoFourie** [comment]
The app will not build. It is stated that they are only warnings but in my case the app will not build. So I can not ignore the warnings.

/E:/Flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.1.55/lib/src/legend/legend.dart:548:30: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/scheduler/binding.dart').
            SchedulerBinding.instance!.addPostFrameCallback(
                             ^


FAILURE: Build failed with an exception.

* Where:
Script 'E:\Flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1156

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'E:\Flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by RudyLie1988** [comment]
> ## Pre-Requisites
> * Flutter installed with the latest 3.0.0 stable, using FVM version manager.
> 
> ## Steps to Reproduce
> 1. Execute `flutter create test_app` to create a new app
> 2. Execute `flutter run` to build and run app
> 
> **Expected results:**
> 
> No warnings in debug console.
> 
> **Actual results:**
> 
> The following warnings are seen:
> 
> ```
>  Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
> ../…/src/framework.dart:275
> - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../fvm/versions/stable/packages/flutter/lib/src/scheduler/binding.dart').
> package:flutter/…/scheduler/binding.dart:1
>     if (SchedulerBinding.instance!.schedulerPhase ==
>                          ^
> : Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
> ../…/src/widgets_binding_observer.dart:42
> - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../fvm/versions/stable/packages/flutter/lib/src/widgets/binding.dart').
> package:flutter/…/widgets/binding.dart:1
>     _state = WidgetsBinding.instance!.lifecycleState;
>                             ^
> 
> : Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
> ../…/src/widgets_binding_observer.dart:43
> - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../fvm/versions/stable/packages/flutter/lib/src/widgets/binding.dart').
> package:flutter/…/widgets/binding.dart:1
>     WidgetsBinding.instance!.addObserver(this);
>                    ^
> : Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
> ../…/src/widgets_binding_observer.dart:52
> ```
> 
> Code sample
> Logs

I think i should share with you guys.
I update Flutter to latest version using Android Studio
![image](https://user-images.githubusercontent.com/68724809/168824037-e56fd443-25d1-479f-b028-d8b8cef57e42.png)

When I run project, error shown below
![image](https://user-images.githubusercontent.com/68724809/168824519-6187a745-515f-490f-81a4-be468752d8ad.png)

Then I go to grouped_list.dart, and find function addPostFrameCallback.
I remove exclamation mark before function call.

If your editor prompt this, just proceed
![image](https://user-images.githubusercontent.com/68724809/168825246-0c3d7f32-e4e4-4c38-b44a-0bd229351fe8.png)

Note:
I also change my build.gradle 
from: ext.kotlin_version = '1.3.50'
to: ext.kotlin_version = '1.5.10'

Now my apps run without error.

**Comment by JacoFourie** [comment]
@RudyLie1988 the issue is not my own code but all the libraries and packages that I do not have control over also has them in. Yes I can remove it from my own code but your fix will not fix all the libs I am using. I did a Dart --fix and it removed all the ! from my own code but not the libs. And people say it should not stop the build. Yet it does break the build.

**Comment by chaooWoo** [comment]
> You can just ignore these warnings for now :)

i want to know how to ignore it? plz.

**Comment by jnthnklvn** [comment]
> @jnthnklvn are you trying to be funny? I can not ignore it as the build fails as I showed above. So not looking at it won't help.

No, I'm not. I was answering just about his mention. In your case could be this:

https://github.com/flutter/flutter/issues/103561#issuecomment-1126416045

**Comment by JacoFourie** [comment]
All works 100% and compiles using 2.10.5. After I upgrade to version 3 I get all these errors and the build will fail.
I updated the kotlin version to 1.6.21 also. Still no luck.
So how do I see what is causing the issue as this is the output.

```
Launching lib\main.dart on SM A013G in debug mode...
Running Gradle task 'assembleDebug'...
lib/screens/flow_screen.dart:176:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addObserver(this);
                   ^
lib/screens/flow_screen.dart:342:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.removeObserver(this);
                   ^
lib/screens/flow_screen.dart:695:24: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
        WidgetsBinding.instance?.addPostFrameCallback((_) {
                       ^
lib/screens/flow_screen.dart:735:22: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance?.addPostFrameCallback((_) {
                     ^
lib/screens/flow_screen.dart:1877:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addPostFrameCallback((_) {
                   ^
lib/screens/pv_screen.dart:85:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
lib/screens/pv_history_chart_screen.dart:38:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(this);
                   ^
lib/screens/pv_history_chart_screen.dart:50:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
lib/screens/grid_screen.dart:61:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
lib/screens/load_screen.dart:62:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
lib/screens/load_history_chart_screen.dart:44:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(this);
                   ^
lib/screens/load_history_chart_screen.dart:58:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
lib/screens/battery_screen.dart:54:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
lib/screens/systems_screen.dart:32:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
lib/screens/profile_screen.dart:32:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
lib/screens/battery_history_chart_screen.dart:44:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(this);
                   ^
lib/screens/battery_history_chart_screen.dart:58:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
lib/screens/overview_chart_screen.dart:45:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(this);
                   ^
lib/screens/overview_chart_screen.dart:60:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
lib/screens/overview_history_chart_screen.dart:48:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(this);
                   ^
lib/screens/overview_history_chart_screen.dart:63:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
lib/screens/grid_history_chart_screen.dart:44:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(this);
                   ^
lib/screens/grid_history_chart_screen.dart:58:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
lib/screens/log_screen.dart:33:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
lib/screens/switch_screen.dart:28:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
/E:/Flutter/.pub-cache/hosted/pub.dartlang.org/rive-0.8.4/lib/src/controllers/one_shot_controller.dart:40:26: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
        : WidgetsBinding.instance?.addPostFrameCallback((_) => onStop?.call());
                         ^
/E:/Flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.1.55/lib/src/chart/base/chart_base.dart:1820:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance!.addPostFrameCallback((_) {
                         ^
/E:/Flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.1.55/lib/src/chart/base/chart_base.dart:1829:28: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/scheduler/binding.dart').
          SchedulerBinding.instance?.addPostFrameCallback((_) => _refresh());
                           ^
/E:/Flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.1.55/lib/src/circular_chart/base/circular_base.dart:948:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance!.addPostFrameCallback((_) {
                         ^
/E:/Flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.1.55/lib/src/circular_chart/base/circular_base.dart:962:28: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/scheduler/binding.dart').
          SchedulerBinding.instance!.addPostFrameCallback((_) => _refresh());
                           ^
/E:/Flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.1.55/lib/src/funnel_chart/base/funnel_base.dart:720:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance!.addPostFrameCallback((_) {
                         ^
/E:/Flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.1.55/lib/src/funnel_chart/base/funnel_base.dart:732:28: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/scheduler/binding.dart').
          SchedulerBinding.instance!.addPostFrameCallback((_) => _refresh());
                           ^
/E:/Flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.1.55/lib/src/pyramid_chart/base/pyramid_base.dart:714:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance!.addPostFrameCallback((_) {
                         ^
/E:/Flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.1.55/lib/src/pyramid_chart/base/pyramid_base.dart:725:28: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/scheduler/binding.dart').
          SchedulerBinding.instance!.addPostFrameCallback((_) => _refresh());
                           ^
/E:/Flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_datepicker-20.1.55/lib/src/date_picker/date_picker.dart:8063:22: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance?.addPostFrameCallback((_) {
                     ^
/E:/Flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_datepicker-20.1.55/lib/src/date_picker/date_picker.dart:9832:22: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance!.addPostFrameCallback((_) {
                     ^
/E:/Flutter/.pub-cache/hosted/pub.dartlang.org/rive-0.8.4/lib/src/rive_core/state_machine_controller.dart:220:24: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance?.addPostFrameCallback((_) {
                       ^
/E:/Flutter/.pub-cache/hosted/pub.dartlang.org/rive-0.8.4/lib/src/rive_render_box.dart:190:26: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance?.scheduleFrameCallback(_frameCallback) ?? -1;
                         ^
/E:/Flutter/.pub-cache/hosted/pub.dartlang.org/back_button_interceptor-5.0.2/lib/src/back_button_interceptor.dart:29:74: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
  static Future<void> Function() handlePopRouteFunction = WidgetsBinding.instance!.handlePopRoute;
                                                                         ^
/E:/Flutter/.pub-cache/hosted/pub.dartlang.org/back_button_interceptor-5.0.2/lib/src/back_button_interceptor.dart:32:22: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.handlePushRoute as Future<void> Function(String?);
                     ^
/E:/Flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_gauges-20.1.55/lib/src/linear_gauge/gauge/linear_gauge_scope.dart:40:10: Error: A value of type 'Widget' can't be assigned to a variable of type 'InheritedWidget'.
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'InheritedWidget' is from 'package:flutter/src/widgets/framework.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/framework.dart').
        .widget;
         ^
/E:/Flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_gauges-20.1.55/lib/src/radial_gauge/pointers/marker_pointer_renderer.dart:607:22: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!
                     ^
/E:/Flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.1.55/lib/src/legend/legend.dart:548:30: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/E:/Flutter/packages/flutter/lib/src/scheduler/binding.dart').
            SchedulerBinding.instance!.addPostFrameCallback(
                             ^


FAILURE: Build failed with an exception.

* Where:
Script 'E:\Flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1156

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'E:\Flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 9s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by jnthnklvn** [comment]
@JacoFourie, the error appears to have something about this:

> /E:/Flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_gauges-20.1.55/lib/src/linear_gauge/gauge/linear_gauge_scope.dart:40:10: Error: A value of type 'Widget' can't be assigned to a variable of type 'InheritedWidget'.
>  - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/framework.dart').
>  - 'InheritedWidget' is from 'package:flutter/src/widgets/framework.dart' ('/E:/Flutter/packages/flutter/lib/src/widgets/framework.dart').
>         .widget;

May you can try to update that package and see if the build problem solves...

**Comment by Hixie** [comment]
If you are getting an error please file a separate bug.

**Comment by Hixie** [comment]
I'm going to close this issue since I think we understand it well now.

The underlying issue of showing warnings about dependencies is an issue we will resolve on the Dart side via https://github.com/dart-lang/sdk/issues/46264.

If you are *only* getting warnings, meaning the app still runs, you may ignore them, they are harmless, and do not indicate a problem. As your dependencies update, the warnings will go away.

If you are getting *errors*, or if you appear to only be getting warnings but the app nonetheless does not build or execute, please [file a new bug](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=2_bug.md&title=) and we will try to determine the cause and resolve those issues. Make sure to include full logs from `flutter run -v`.

Thank you for your continued use of Flutter!
