### ISSUE TITLE
After copying the repository, when executing the command: "flutter doctor" one ERROR.

### ISSUE THREAD

**Issue by antondca** [flutter/flutter#10484]
## Steps to Reproduce

Please tell us what you were doing and what went wrong. If you are running flutter tools from the command line, please try adding the `-v` or `--verbose` option to gather more information.

If the problem is with your application's rendering, please attach a screenshot and any relevant source code.
If you are getting an exception in the logs, and your code is implicated in the first few frames, then please include the source code for the functions involved.

## Logs

Run your application with `flutter run` and attach all the log output.

Same Error ^^.

Run `flutter analyze` and attach any output of that command also.

Same Error ^^.

## Flutter Doctor

Paste the output of running `flutter doctor` here.

Hi to all, I'm new here, me have one ERROR to install Flutter. After copying the repository, when executing the command: "flutter doctor" gives me the following error. I can not update the flutter sdk. Al can not do this step I can not use "flutter" What can I do? I use Windows 10 Pro 64bit.

ERROR:
"Where" is not recognized as an internal or external command,
Program or executable batch file.
Error: Unable to find git in your PATH.

Here url image: https://s6.postimg.org/lgowhgy69/Error_flutter_doctor_windows.jpg

Thank you so much everyone. I hope you understand me, I do not speak much English.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by eseidelGoogle** [comment]
@goderbauer this was also discussed with @mit-mit on Gitter this morning.

**Comment by antondca** [comment]
Okay thanks ;)

**Comment by antondca** [comment]
I have fixed my Path, and now I have another problem. Pass how much I try to update the flutter sdk with the command "flutter doctor"
En esta imgen se puede ver como tengo las variables "Path" y el error que me da al ejecutar el comando "flutter doctor"

https://s6.postimg.org/o3i73mtj5/Error_Unable_to_update_Dart_SDK.jpg

What is the reason for this error?

Thank you very much 
The best regards

Anton

**Comment by goderbauer** [comment]
Just to document for the future: The first problem was resolved by re-adding `C:\Windows\System32` to the `PATH` environment variable. It should have been there by default as this is how Windows is configured after a fresh install.

I don't really understand the second exception as I don't speak that language. Can you provide a translation to english? Given that it has something to do with BitTransfer trying to download the Dart SDK my guess is that your Firewall is blocking access to the Internet though. Can you try `flutter doctor` after temporarily disabling your firewall?

**Comment by antondca** [comment]
@goderbauer A lot of thanks, **the problem** ( Translation) _"Start-BitsTransfer: There are no more endpoints available from the endpoint mapper. (Exception from HRESULT: 0x800706D9)"_
It **is fixed** by disabling the Windows Firewall as you said. Thank you.

**Photos here:**
https://s6.postimg.org/nm6c9hvcx/Firewall_des.png

https://s6.postimg.org/o958z0s8x/Flutter_Updating!!!.jpg

https://s6.postimg.org/epvk5k4qp/fluter_doctor_ok.jpg

Muchisimas gracias ;)

**Comment by goderbauer** [comment]
Awesome! Have fun with Flutter!

**Comment by karlembeast** [comment]
Just a suggestion. 
After having difficulty launching flutter doctor through cmd, I have discovered an alternative way. Navigate your way to the directory where flutter is installed. In my case that was "C:\\Users\User\flutter\bin". And finally, running flutter.exe launches the flutter doctor.

**Comment by monojbasumatary** [comment]
Upgrading engine...
'where' is not recognized as an internal or external command,
operable program or batch file.
Error: Unable to find git in your PATH.

Flutter 0.4.5-pre.7 • channel master • https://github.com/flutter/flutter.git
Framework • revision ace27819fe (3 hours ago) • 2018-05-14 17:11:38 -0700
Engine • revision 06afdfe54e
Tools • Dart 2.0.0-dev.54.0.flutter-46ab040e58

Running flutter doctor...
'where' is not recognized as an internal or external command,
operable program or batch file.
Error: Unable to find git in your PATH.



^^^^^^ this is what i'm getting

**Comment by monojbasumatary** [comment]
i have already setup my environment variables for git and flutter sdk multiple times and checked again... but still not working

**Comment by monojbasumatary** [comment]
C:\Windows\System32>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v0.4.5-pre.7, on Microsoft Windows [Version 10.0.16299.431], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

**Comment by monojbasumatary** [comment]
C:\Windows\System32>flutter doctor -v
[√] Flutter (Channel master, v0.4.5-pre.7, on Microsoft Windows [Version 10.0.16299.431], locale en-US)
    • Flutter version 0.4.5-pre.7 at C:\Windows\System32\flutter
    • Framework revision ace27819fe (3 hours ago), 2018-05-14 17:11:38 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\monoj\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-P, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

**Comment by monojbasumatary** [comment]
but still my flutter application creation fails in android studio

**Comment by akwa-peter** [comment]
Please I have downloaded and added the path for my flutter SDK and have also installed the plugin in my android studio, but when I run "flutter doctor", it displays "flutter: command not found". 
Please can someone help me out, what could be the cause?

**Comment by zoechi** [comment]
@akwa-peter sounds like adding the path didn't work then

**Comment by samueosborn** [comment]
ok so where is actually found in this directory " C:\Windows\System32\ " so add this to your path in your environment variables

**Comment by devsumanprasad** [comment]
[flutter] flutter doctor
'where' is not recognized as an internal or external command,
operable program or batch file.
Error: Unable to find git in your PATH. 
exit code 1

it came, in visual studio code

**Comment by goderbauer** [comment]
First paragraph of https://github.com/flutter/flutter/issues/10484#issuecomment-306244934 explains the fix:

> Just to document for the future: The first problem was resolved by re-adding C:\Windows\System32 to the PATH environment variable. It should have been there by default as this is how Windows is configured after a fresh install.

**Comment by Brijesh-kumar-Vaishya** [comment]
I Have Same issue:

Issue is: 
C:\Users\Brijesh-Kr.-Vaishya\Downloads\flutter\bin\flutter.bat --no-color doctor
'where' is not recognized as an internal or external command, operable program or batch file.
Error: Unable to find git in your PATH. 
Process finished with exit code 1
===============


Git path has been set. (  C:\Program Files\Git\bin\git.exe  )
Flutter Path set   (  C:\Users\Brijesh-Kr.-Vaishya\Downloads\flutter\bin  )
Dart Sdk Path set ( C:\Program Files\Dart\dart-sdk\bin;  )
Where command also set (  C:\Windows\System32\where.exe  )

Still getting same issue again and again..

Plz provide us some proper solution

**Comment by 21Supriya** [comment]
I solved this problem by running cmd as administrator.

**Comment by adelhamid** [comment]
i went to install flutter in vs code and when i went to run the doctor and select the sdk file it send to me this errore ''[flutter] flutter doctor -v
Error: The Flutter directory is not a clone of the GitHub project.
       The flutter tool requires Git in order to operate properly;
       to set up Flutter, run the following command:
       git clone -b stable https://github.com/flutter/flutter.git
exit code 1"

**Comment by eseidelGoogle** [comment]
@adelhamid would you be willing to file a new bug?  This one was closed many months ago and I worry you may be hitting a different issue?

**Comment by pwi23270** [comment]
To share my solution:
1- Go to "Edit environment variable for your account"
2- Go "PATH" variable if exist.
3- Press edit which will take you to another window contains paths.
4- Don't press edit and don't add ";" then the flutter bin folder path.  Instead press new and add the flutter bin folder path.
5- Reboot the system.
If doesn't work, after step 4 add another path "C:\Windows\System32"
