### ISSUE TITLE
TimePicker input field shrinks in error state

### ISSUE THREAD

**Issue by glaceon2000** [flutter/flutter#110563]
This looks wonky.
![image](https://user-images.githubusercontent.com/51567674/187349499-377fad11-6477-4077-aabc-675bd2651745.png)

**Comment by iapicca** [comment]
yup,the size of the numeric field seems fixed in [here](https://lh3.googleusercontent.com/WniD2UmFRzysXxQUeS0qUXYSwHyx7laGZdWltwENONNEXbmFHocLzKcGKN2mrctPW7WMsbyv8wi-d66-kGIPSxbd1V5lffPHtIfh4g=w1064-v0) ([source](https://material.io/components/time-pickers#specs))

**Comment by danagbemava-nc** [comment]
I was only able to reproduce this when I tested on the web platform. 

Labelling for further investigation. 

<details>
<summary>screenshots</summary>


| android | iOS | chrome | macOS | 
| -- | -- | -- | -- |
| <img width="789" alt="Screenshot 2022-08-30 at 10 15 53" src="https://user-images.githubusercontent.com/88313112/187414690-fb56dccc-397a-45ae-a85c-d72fe2720b0a.png"> | <img width="488" alt="Screenshot 2022-08-30 at 10 08 53" src="https://user-images.githubusercontent.com/88313112/187414714-36780af0-0cb6-43d6-8c5e-eee632ca70cb.png"> | <img width="660" alt="Screenshot 2022-08-30 at 10 07 58" src="https://user-images.githubusercontent.com/88313112/187414719-b6699930-57c4-4abd-9d42-4d9692f001d0.png"> | <img width="583" alt="Screenshot 2022-08-30 at 10 07 47" src="https://user-images.githubusercontent.com/88313112/187414728-b1cc6ae2-c802-4392-b0af-711e73733f77.png"> |

</details>

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      restorationScopeId: 'app',
      title: _title,
      theme: ThemeData.light().copyWith(useMaterial3: true),
      home: MyStatelessWidget(),
    );
  }
}

class MyStatelessWidget extends StatelessWidget {
  const MyStatelessWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: OutlinedButton(
          onPressed: () {
            Future<TimeOfDay?> selectedTime = showTimePicker(
              initialTime: TimeOfDay.now(),
              context: context,
              // errorInvalidText: 'Please enter a valid time'
            );
          },
          child: const Text('Open Dialog'),
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale en-GB)
    • Flutter version 3.0.5 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (7 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5556                        • android-arm64  • Android 13 (API 33) (emulator)
    • iPhone 13 Pro (mobile)      • 6E074BA5-191C-47D4-892F-FD96AFC34148 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2574, on macOS 12.5 21G72 darwin-arm64, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.2574 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 052cd87246 (6 hours ago), 2022-08-30 00:26:24 -0400
    • Engine revision 28e8fe2765
    • Dart version 2.19.0 (build 2.19.0-150.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5556                        • android-arm64  • Android 13 (API 33) (emulator)
    • iPhone 13 Pro (mobile)      • 6E074BA5-191C-47D4-892F-FD96AFC34148 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 12.5 21G72 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by yjbanov** [comment]
I see that the fonts used in the web version are different from others. Does the problem reproduce if you used the same font?

**Comment by danagbemava-nc** [comment]
@yjbanov It seems to reproduce regardless of the font used. In the screenshots below, I use the montserrat fonts and the bug still reproduces for me only on, web. 

<details>
<summary>screenshots</summary>

| chrome | macOS | iOS | android | 
| -- | -- | -- | -- |
| <img width="667" alt="Screenshot 2022-09-05 at 06 20 03" src="https://user-images.githubusercontent.com/88313112/188375151-0226778f-5e33-431d-8681-0862a0d4edb5.png"> | <img width="764" alt="Screenshot 2022-09-05 at 06 22 20" src="https://user-images.githubusercontent.com/88313112/188375180-804ac2da-632a-4d4b-84d8-f1e455e2fc65.png"> | <img src="https://user-images.githubusercontent.com/88313112/188375190-4b2f77cd-349e-4937-897a-e9cf750fc848.png" /> | <img width="789" alt="Screenshot 2022-09-05 at 06 31 59" src="https://user-images.githubusercontent.com/88313112/188377913-8907b20c-a3eb-4174-aaf0-72800eb70508.png"> |

</details>

Upon further testing, this seems to only reproduce for me when I use the canvaskit web-renderer. In the screenshot below, the HTML renderer is on the left and the canvaskit renderer is on the right. 

<img width="1118" alt="Screenshot 2022-09-05 at 06 36 28" src="https://user-images.githubusercontent.com/88313112/188380215-53323304-87d4-4097-b0ce-018802e7cfad.png">




<details>
<summary>updated code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      restorationScopeId: 'app',
      title: _title,
      theme: ThemeData.light().copyWith(useMaterial3: true, textTheme: GoogleFonts.montserratTextTheme()),
      home: const MyStatelessWidget(),
    );
  }
}

class MyStatelessWidget extends StatelessWidget {
  const MyStatelessWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: OutlinedButton(
          onPressed: () {
            Future<TimeOfDay?> selectedTime = showTimePicker(
              initialTime: TimeOfDay.now(),
              context: context,
              // errorInvalidText: 'Please enter a valid time'
            );
          },
          child: const Text('Open Dialog'),
        ),
      ),
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 3.4.0-19.0.pre.72, on macOS 12.5 21G72 darwin-arm64, locale en-GB)
    • Flutter version 3.4.0-19.0.pre.72 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 202f5771f4 (6 hours ago), 2022-09-04 20:28:23 -0400
    • Engine revision b94120dfe9
    • Dart version 2.19.0 (build 2.19.0-168.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • Nexus (mobile)              • 00008020-001875E83A38002E            • ios            • iOS 15.6.1 19G82
    • iPhone 13 Pro (mobile)      • 6E074BA5-191C-47D4-892F-FD96AFC34148 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 12.5 21G72 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 104.0.5112.101
    ! Error: Nexus is busy: Fetching debug symbols for Nexus. Xcode will continue when Nexus is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by hterkelsen** [comment]
This is caused by this bug: https://github.com/flutter/flutter/issues/75837

I sent a fix for it here: https://skia-review.googlesource.com/c/skia/+/593616

**Comment by eyebrowsoffire** [comment]
This was fixed a long time ago.
