### ISSUE TITLE
Whole app is jumping after update

### ISSUE THREAD

**Issue by kirill-21** [flutter/flutter#110957]
![j4KEge8GJH](https://user-images.githubusercontent.com/63228361/188335723-dffe3faf-c9dd-4b66-bd88-cf153833e25e.gif)
All elements in my Flutter apps started jumping after updating to Flutter 3.3.0.

I have several projects and this issue is reproducible in all apps where i use any Animated... widget(AnimatedOpacity, AnimatedSwitcher, AnimatedContainer, ...)

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Material App Bar'),
        ),
        body: Center(
          child: SingleChildScrollView(
            child: Column(
              children: <Widget>[
                for (int i = 0; i < 100; i++)
                  Padding(
                    padding: const EdgeInsets.only(top: 100),
                    child: EasyCheckbox(
                      isChecked: false,
                      onChanged: (_) {
                        /* Do something */
                      },
                      title: 'Test Title 123',
                      description: 'Bad update :C',
                      width: 300,
                    ),
                  ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

class EasyCheckbox extends StatefulWidget {
  final bool isChecked;
  final Function onChanged;
  final String title;
  final String? description;
  final double? width;
  final TextStyle? textStyle;
  final Color? textColor;
  final bool isLocked;

  const EasyCheckbox({
    super.key,
    this.isChecked = false,
    required this.onChanged,
    required this.title,
    this.description,
    this.width,
    this.textStyle,
    this.textColor,
    this.isLocked = false,
  });

  @override
  _EasyCheckboxState createState() => _EasyCheckboxState();
}

class _EasyCheckboxState extends State<EasyCheckbox> {
  late bool value = widget.isChecked;
  Color? _color;

  @override
  Widget build(BuildContext context) {
    return IgnorePointer(
      ignoring: widget.isLocked,
      child: SizedBox(
        width: widget.width,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                MouseRegion(
                  cursor: SystemMouseCursors.click,
                  onEnter: (_) => setState(
                    () => _color = Colors.blueGrey,
                  ),
                  onExit: (_) => setState(() => _color = Colors.grey),
                  child: GestureDetector(
                    onTap: () {
                      setState(() => value = !value);
                      widget.onChanged(value);
                    },
                    child: Container(
                      padding: const EdgeInsets.symmetric(
                        horizontal: 4.0,
                        vertical: 6.0,
                      ),
                      decoration: BoxDecoration(
                        color: Colors.black12,
                        boxShadow: [
                          BoxShadow(
                            color: Colors.black.withOpacity(0.11),
                            blurRadius: 4.0,
                            offset: const Offset(
                              0.0,
                              2.0,
                            ), // changes position of shadow
                          ),
                        ],
                        borderRadius: const BorderRadius.all(
                          Radius.circular(6.0),
                        ),
                      ),
                      child: AnimatedOpacity(
                        duration: const Duration(milliseconds: 350),
                        curve: Curves.easeInOutCubic,
                        opacity: value ? 1.0 : 0.0,
                        child: const Icon(
                          Icons.check,
                          size: 8.0,
                          color: Colors.blue,
                        ),
                      ),
                    ),
                  ),
                ),
                const SizedBox(width: 10.0),
                Expanded(
                  child: Text(
                    widget.title,
                    style: TextStyle(
                      fontSize: 14.0,
                      fontWeight: FontWeight.w600,
                      color: widget.textColor,
                    ),
                    textAlign: TextAlign.left,
                  ),
                ),
              ],
            ),
            if (widget.description != null)
              Padding(
                padding: const EdgeInsets.only(
                  left: 28.0,
                  top: 0.5,
                ),
                child: Text(
                  widget.description!,
                  style: const TextStyle(
                    fontSize: 13.0,
                    fontWeight: FontWeight.w500,
                    color: Colors.grey,
                  ),
                  textAlign: TextAlign.left,
                ),
              ),
          ],
        ),
      ),
    );
  }
}
```

There is also a huge performance issue, animations are not smooth as before, apps lag on startup for some time.

**Comment by jonahwilliams** [comment]
I was able to reproduce this, but it required me to change my monitor default settings from 1.25 dpr to 1.0. It happens on both 3.3 and near tip of tree

> There is also a huge performance issue, animations are not smooth as before, apps lag on startup for some time.

You'll need to file a new issue for this, and include timeline traces that demonstrate the performance regression

**Comment by jonahwilliams** [comment]
Update: I'm able to "fix" the issue by disabling raster caching. Investigating whether we're incorrectly positioning fractional drawings for raster cache entries

**Comment by kirill-21** [comment]
By the way i've noticed that widgets that jumped on Flutter 3.0.5 (happened if widget was wrapped with AnimatedSwitcher) do not jump anymore

**Comment by 7AveNooN7** [comment]
I have the same issue. It happens to widget with Canvas and Painters inside them.

**Comment by jonahwilliams** [comment]
Cherry pick request for fix is https://github.com/flutter/flutter/issues/111145

**Comment by chinmaygarde** [comment]
This is waiting for the [CP to land](https://github.com/flutter/flutter/issues/111231).

**Comment by kirill-21** [comment]
Will this be pushed as a hot-fix to flutter 3.3.0 on stable channel?

**Comment by jonahwilliams** [comment]
We've released a hotfix that restores pixel snapping. It would be great if you could verify that this fixes your application.

**Comment by kirill-21** [comment]
> ###

It helped but not fully, some parts of the app still jump

**Comment by jonahwilliams** [comment]
can you provide sample code that reproduces that?

**Comment by kirill-21** [comment]
In this code sample it's not visible so much but still present. There are some more necessary steps to reproduce it:
- You'll have to change window size in windows\main.cpp to
```
  Win32Window::Size size(1580, 890);
```
 
![studio64_mExXkx35UR](https://user-images.githubusercontent.com/63228361/190267603-6bfab4ec-464f-4474-9e01-f69e2a7d9cc9.gif)

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

/// Darkens provided color.
Color darken(Color color, [double amount = 0.05]) {
  final hsl = HSLColor.fromColor(color);
  final hslDark = hsl.withLightness((hsl.lightness - amount).clamp(0.0, 1.0));

  return hslDark.toColor();
}

/// Lightens provided color.
Color lighten(Color color, [double amount = 0.05]) {
  final hsl = HSLColor.fromColor(color);
  final hslLight = hsl.withLightness((hsl.lightness + amount).clamp(0.0, 1.0));

  return hslLight.toColor();
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        backgroundColor: const Color(0xFF1B1B23),
        body: Container(
          height: 890.0 - 50.0 - 65.0,
          width: 1580.0 - 65.0,
          decoration: BoxDecoration(
            color: darken(
                const Color(0xFF616161).withOpacity(0.25),
              0.3,
            ),
          ),
          child: AnimatedSize(
            duration: const Duration(milliseconds: 350),
            curve: Curves.easeOutCubic,
            child: GridView.builder(
              itemCount: 7,
              padding: const EdgeInsets.all(12.0),
              physics: const BouncingScrollPhysics(),
              gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                crossAxisCount: 4,
                mainAxisSpacing: 12.0,
                mainAxisExtent: 170.0,
                crossAxisSpacing: 12.0,
              ),
              itemBuilder: (_, index) {
                return _GameCard(index);
              },
            ),
          ),
        ),
      ),
    );
  }
}

class _GameCard extends StatefulWidget {
  final int index;

  const _GameCard(this.index);

  @override
  State<_GameCard> createState() => _GameCardState();
}

class _GameCardState extends State<_GameCard> {
  bool _isHovered = false;

  /// Retrieves color for mark background.
  Color _getMarkBackgroundColor(double rate) {
    // Green(kSafeColor)
    if (rate >= 7.0) return Colors.green;

    // Orange(kNeutralColor)
    if (rate >= 5.0 && rate <= 6.9) {
      return Colors.orange;
    }

    // Red (kUnsafeColor)
    return Colors.redAccent;
  }

  @override
  Widget build(BuildContext context) {
    return MouseRegion(
      onEnter: (_) => setState(() => _isHovered = true),
      onExit: (_) => setState(() => _isHovered = false),
      child: Container(
        clipBehavior: Clip.antiAlias,
        constraints: const BoxConstraints(
          maxHeight: 200.0,
          maxWidth: 365.0,
        ),
        decoration: BoxDecoration(
          color: Colors.transparent,
          boxShadow: [
            BoxShadow(
              color: Colors.black.withOpacity(0.2),
              blurRadius: 8.0,
              spreadRadius: 4.0,
              offset: const Offset(
                0.0,
                0.0,
              ), // changes position of shadow
            ),
          ],
          borderRadius: BorderRadius.circular(6.0),
        ),
        child: Stack(
          alignment: Alignment.center,
          clipBehavior: Clip.antiAliasWithSaveLayer,
          children: <Widget>[
            Image.network(
              'https://cdn.akamai.steamstatic.com/steam/apps/261570/header.jpg',
              height: 200.0,
              width: 365.0,
              fit: BoxFit.fill,
              filterQuality: FilterQuality.medium,
            ),
            Positioned(
              bottom: -(4.0 / 2),
              left: -4.0,
              right: -4.0,
              child: EasyFadingGradient(
                width: 1280.0,
                height: 75.0,
                begin: Alignment.topCenter,
                end: Alignment.bottomCenter,
                color: darken(const Color(0xFF616161), 0.45),
                opacity: const [0.30, 0.50, 0.80],
              ),
            ),
            Positioned(
              bottom: 12.0,
              left: 12.0,
              child: Container(
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(4.0),
                  color: _getMarkBackgroundColor(7.0),
                ),
                child: Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 4.0),
                  child: Text(
                    7.1.toStringAsFixed(1),
                    style: const TextStyle(color: Colors.white, fontSize: 14.0),
                  ),
                ),
              ),
            ),
            Positioned(
              bottom: 12.0,
              right: 12.0,
              child: Image.network(
                'https://steamuserimages-a.akamaihd.net/ugc/914674978442492164/234BCCA1FCE231306BA731CE1C55A6255F0268B2/?imw=512&amp;imh=512&amp;ima=fit&amp;impolicy=Letterbox&amp;imcolor=%23000000&amp;letterbox=true',
                width: 22.0,
                filterQuality: FilterQuality.medium,
              ),
            ),
            Positioned(
              bottom: 0.0,
              top: 0.0,
              right: -1.0,
              left: -1.0,
              child: AnimatedOpacity(
                opacity: _isHovered ? 1.0 : 0.0,
                duration: const Duration(milliseconds: 350),
                curve: Curves.easeOutCubic,
                child: Center(
                  child: Container(
                    color: darken(
                      const Color(0xFF616161),
                      0.25,
                    ).withOpacity(0.90),
                    child: Padding(
                      padding: const EdgeInsets.only(
                        right: 12.0,
                        left: 12.0,
                        bottom: 12.0,
                        top: 8.0,
                      ),
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: <Widget>[
                          const Text(
                            'The forest of Nibel is dying. After a powerful storm sets a series of devastating events in motion, an unlikely hero must journey to find his courage and confront a dark nemesis to save his home. “Ori and the Blind Forest” tells the tale of a young orphan destined for heroics, through a visually stunning action-platformer crafted by Moon Studios for PC. Featuring hand-painted artwork, meticulously animated character performance, and a fully orchestrated score, “Ori and the Blind Forest” explores a deeply emotional story about love and sacrifice, and the hope that exists in us all',
                            style: TextStyle(
                              fontSize: 14.0,
                              color: Colors.white,
                            ),
                            maxLines: 5,
                            overflow: TextOverflow.ellipsis,
                          ),
                          Row(
                            children: <Widget>[
                              Expanded(
                                child: Padding(
                                  padding: const EdgeInsets.only(
                                    right: 10.0,
                                  ),
                                  child: ElevatedButton(
                                    child: const Text('more info'),
                                    onPressed: () {},
                                  ),
                                ),
                              ),
                              ElevatedButton(
                                child: const Text('more info'),
                                onPressed: () {},
                              ),
                            ],
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class EasyFadingGradient extends StatelessWidget {
  final double width;
  final double height;
  final Alignment begin;
  final Alignment end;
  final Color color;
  final List<double> opacity;

  EasyFadingGradient({
    required this.width,
    required this.height,
    required this.begin,
    required this.end,
    required this.color,
    required this.opacity,
  }) : super(key: UniqueKey());

  @override
  Widget build(BuildContext context) {
    return IgnorePointer(
      child: Container(
        clipBehavior: Clip.antiAliasWithSaveLayer,
        height: height,
        width: width,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: begin,
            end: end,
            colors: <Color>[
              color.withOpacity(0.00),
              for (final double opacity in opacity) color.withOpacity(opacity),
            ],
          ),
        ),
      ),
    );
  }
}
```

**Comment by kirill-21** [comment]
Not sure if it's an issue or an animation, but here is one more example as text inside the button jumps
![test_window2_Z1n3lF3tNc](https://user-images.githubusercontent.com/63228361/190367887-b7badded-ef01-44a5-8b98-f1771d05fdd8.gif)

To make it more visible i enabled slow animations in DevTools
```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Material App Bar'),
        ),
        body: const Center(
          child: SizedBox(
            child: Text('Hello World'),
          ),
        ),
        floatingActionButton: Builder(
          builder: (context) => FloatingActionButton(
            onPressed: () {
              showDialog(
                context: context,
                builder: (_) {
                  return const TestDialog();
                },
              );
            },
          ),
        ),
      ),
    );
  }
}

class TestDialog extends StatefulWidget {
  const TestDialog({super.key});

  @override
  State<TestDialog> createState() => _TestDialogState();
}

class _TestDialogState extends State<TestDialog> {
  bool _isHintVisible = false;

  @override
  Widget build(BuildContext context) {
    return UnconstrainedBox(
      child: Container(
        width: 250.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(6.0),
          color: Colors.grey,
        ),
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 12.0, vertical: 12.0),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              const Text(
                'Dialog title is here',
                style: TextStyle(
                  fontSize: 22.0,
                  color: Colors.white,
                  height: 1.0,
                ),
              ),
              Padding(
                padding: const EdgeInsets.only(top: 8.0, bottom: 8.0),
                child: ElevatedButton(
                  onPressed: () {
                    setState(() => _isHintVisible = !_isHintVisible);
                  },
                  child: const Text('press me!'),
                ),
              ),
              AnimatedSize(
                duration: const Duration(milliseconds: 350),
                curve: Curves.easeOutCubic,
                child: AnimatedOpacity(
                  duration: const Duration(milliseconds: 350),
                  curve: Curves.easeOutCubic,
                  opacity: _isHintVisible ? 1.0 : 0.0,
                  child: SizedBox(
                    height: !_isHintVisible ? 0.0 : null,
                    child: const Text(
                      "The game will be installed to the provided directory path! If directory you've chose is not empty then it will be cleared!",
                      style: TextStyle(
                        fontSize: 14.0,
                        color: Colors.white,
                        height: 1.0,
                      ),
                    ),
                  ),
                ),
              ),

            ],
          ),
        ),
      ),
    );
  }
}
```

**Comment by kirill-21** [comment]
I guess problem is in AnimatedOpacity widget, literally every place where i use it, jumps

**Comment by jonahwilliams** [comment]
Got it, have a change that fixes this locally in https://github.com/flutter/engine/pull/36173

**Comment by kirill-21** [comment]
> Got it, have a change that fixes this locally in [flutter/engine#36173](https://github.com/flutter/engine/pull/36173)

It fixes both cases?

**Comment by kirill-21** [comment]
> Got it, have a change that fixes this locally in [flutter/engine#36173](https://github.com/flutter/engine/pull/36173)

Hi. I've tested it on Master channel. First example is fixed, however, some parts of the app still jump

```dart
import 'package:flutter/material.dart';
import 'package:flutter_svg/svg.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Material App Bar'),
        ),
        body: Center(
          child: SizedBox(
            child: EasyDropdown(
              items: const ['123', '321'],
              fontSize: 14.0,
              onChanged: () => print('123'),
              width: 245.0,
              forceTwoIcons: true,
              value: 'Genre',
              hintText: 'Genre',
            ),
          ),
        ),
        floatingActionButton: Builder(
          builder: (context) => FloatingActionButton(
            onPressed: () {
              showDialog(
                context: context,
                builder: (_) {
                  return const TestDialog();
                },
              );
            },
          ),
        ),
      ),
    );
  }
}

class TestDialog extends StatefulWidget {
  const TestDialog({super.key});

  @override
  State<TestDialog> createState() => _TestDialogState();
}

class _TestDialogState extends State<TestDialog> {
  bool _isHintVisible = false;

  @override
  Widget build(BuildContext context) {
    return UnconstrainedBox(
      child: Container(
        width: 250.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(6.0),
          color: Colors.grey,
        ),
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 12.0, vertical: 12.0),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              const Text(
                'Dialog title is here',
                style: TextStyle(
                  fontSize: 22.0,
                  color: Colors.white,
                  height: 1.0,
                ),
              ),
              Padding(
                padding: const EdgeInsets.only(top: 8.0, bottom: 8.0),
                child: ElevatedButton(
                  onPressed: () {
                    setState(() => _isHintVisible = !_isHintVisible);
                  },
                  child: const Text('press me!'),
                ),
              ),
              AnimatedSize(
                duration: const Duration(milliseconds: 350),
                curve: Curves.easeOutCubic,
                child: AnimatedOpacity(
                  duration: const Duration(milliseconds: 350),
                  curve: Curves.easeOutCubic,
                  opacity: _isHintVisible ? 1.0 : 0.0,
                  child: SizedBox(
                    height: !_isHintVisible ? 0.0 : null,
                    child: const Text(
                      "The game will be installed to the provided directory path! If directory you've chose is not empty then it will be cleared!",
                      style: TextStyle(
                        fontSize: 14.0,
                        color: Colors.white,
                        height: 1.0,
                      ),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class EasyDropdown extends StatefulWidget {
  final String? hintText;
  final List<String> items;
  final List<IconData>? icons;
  final double fontSize;
  final Function onChanged;
  final String? value;
  final bool useAppLocaleOnItems;
  final double heightWithoutScale;
  final double? insets;
  final EdgeInsets? iconInsets;
  final Color? textColor;
  final FontWeight? fontWeight;
  final double width;
  final double? textMaxWidth;
  final Color? backgroundColor;
  final Color? menuBackgroundColor;
  final Function? onTapCallbackInsteadOfMenu;
  final bool forceTwoIcons;
  final double? maxDropdownMenuHeight;

  const EasyDropdown({
    Key? key,
    this.value,
    this.hintText,
    required this.items,
    this.icons,
    required this.fontSize,
    required this.onChanged,
    this.useAppLocaleOnItems = false,
    this.heightWithoutScale = 35.0,
    this.insets,
    this.iconInsets,
    this.textColor,
    this.fontWeight,
    required this.width,
    this.backgroundColor,
    this.menuBackgroundColor,
    this.onTapCallbackInsteadOfMenu,
    this.forceTwoIcons = false,
    this.textMaxWidth,
    this.maxDropdownMenuHeight,
  }) : super(key: key);

  @override
  _EasyDropdownState createState() => _EasyDropdownState();
}

class _EasyDropdownState extends State<EasyDropdown> {
  // A notifier to control arrow icon opacity
  final ValueNotifier<bool> _isHovered = ValueNotifier(false);

  @override
  void dispose() {
    _isHovered.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    /// Pre-cache text widget so that it can be used both with and without
    /// expanded parent.
    final Widget text = Padding(
      padding: const EdgeInsets.only(bottom: 1.0, right: 4.0),
      child: Container(
        alignment: Alignment.centerLeft,
        child: Container(
          constraints: BoxConstraints(
            maxWidth: widget.textMaxWidth ?? double.infinity,
          ),
          child: Text(
            widget.value != null
                ? widget.useAppLocaleOnItems
                    ? widget.value!
                    : widget.value!
                : widget.hintText!,
            overflow: TextOverflow.ellipsis,
            textAlign: TextAlign.left,
            style: TextStyle(
              fontSize: widget.fontSize,
              color: widget.textColor ?? Colors.white,
            ),
          ),
        ),
      ),
    );

    return MouseRegion(
      onEnter: (_) => _isHovered.value = true,
      onExit: (_) => _isHovered.value = false,
      cursor: SystemMouseCursors.click,
      child: GestureDetector(
        onTapDown: (_) {},
        child: Container(
          constraints: BoxConstraints(maxWidth: widget.width),
          decoration: BoxDecoration(
            color: widget.backgroundColor ?? Colors.black.withOpacity(0.50),
            boxShadow: [
              BoxShadow(
                color: Colors.black.withOpacity(0.25),
                blurRadius: 6.0,
                offset: const Offset(
                  0.0,
                  1.0,
                ), // changes position of shadow
              ),
            ],
            borderRadius: const BorderRadius.all(Radius.circular(6.0)),
          ),
          child: SizedBox(
            height: widget.heightWithoutScale,
            child: Padding(
              padding: EdgeInsets.symmetric(
                horizontal: widget.insets ?? 12.0,
              ),
              child: Row(
                mainAxisSize: MainAxisSize.min,
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: <Widget>[
                  widget.iconInsets == null
                      ? Expanded(child: text)
                      : Padding(
                          padding: widget.iconInsets ?? EdgeInsets.zero,
                          child: text,
                        ),
                  ValueListenableBuilder(
                    valueListenable: _isHovered,
                    builder: (_, bool value, __) => AnimatedOpacity(
                      duration: const Duration(milliseconds: 350),
                      curve: Curves.easeInOutCubic,
                      opacity: value ? 1.0 : 0.5,
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        key: ValueKey(value),
                        children: [
                          if (widget.onTapCallbackInsteadOfMenu != null ||
                              widget.forceTwoIcons)
                            Padding(
                              padding: const EdgeInsets.only(bottom: 4.0),
                              child: SvgPicture.asset(
                                'resources/icons/drop-arrow-flipped.svg',
                                color: Colors.white,
                                height: 4.0,
                                key: ValueKey('$value flipped'),
                              ),
                            ),
                          SvgPicture.asset(
                            'resources/icons/drop-arrow.svg',
                            color: Colors.white,
                            height: widget.onTapCallbackInsteadOfMenu != null ||
                                    widget.forceTwoIcons
                                ? 4.0
                                : 7.0,
                            key: ValueKey('$value normal'),
                          ),
                        ],
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

Resources used in this example:
![drop-arrow-flipped](https://user-images.githubusercontent.com/63228361/190631436-9f8476a2-5a32-462b-a5c3-b8bbae262dd8.svg)
![drop-arrow](https://user-images.githubusercontent.com/63228361/190631440-2b784dc7-e0ad-4764-b176-8808f1ec79a1.svg)

Add them with pubspeck.yaml, 
```
  assets:
    - resources/icons/

  dependencies:
    flutter_svg: ^1.1.5
```

**Comment by jonahwilliams** [comment]
https://github.com/flutter/engine/pull/36213 fixes this additional case

**Comment by kirill-21** [comment]
<details>

<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_svg/svg.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Material App Bar'),
        ),
        body: const Center(
          child: SizedBox.shrink(),
        ),
        floatingActionButton: Builder(
          builder: (context) => FloatingActionButton(
            onPressed: () {
              showDialog(
                context: context,
                builder: (_) {
                  return const TestDialog();
                },
              );
            },
            child: const Center(
              child: Text(
                'press me!',
                textAlign: TextAlign.center,
              ),
            ),
          ),
        ),
      ),
    );
  }
}

class TestDialog extends StatefulWidget {
  const TestDialog({super.key});

  @override
  State<TestDialog> createState() => _TestDialogState();
}

class _TestDialogState extends State<TestDialog> {
  bool _isHintVisible = false;

  @override
  Widget build(BuildContext context) {
    return UnconstrainedBox(
      child: Container(
        width: 250.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(6.0),
          color: Colors.grey,
        ),
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 12.0, vertical: 12.0),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              const Padding(
                padding: EdgeInsets.only(bottom: 3.0),
                child: Text(
                  'title for dropmenu',
                  style: TextStyle(
                    fontSize: 16.0,
                    color: Colors.white,
                  ),
                ),
              ),
              EasyDropdown(
                items: const [
                  'items',
                  'items1',
                ],
                fontSize: 14.0,
                onChanged: (_) {},
                width: 344.5,
                value: 'items',
                hintText: 'items1',
              ),
              Padding(
                padding: const EdgeInsets.only(top: 8.0, bottom: 8.0),
                child: ElevatedButton(
                  onPressed: () {
                    setState(() => _isHintVisible = !_isHintVisible);
                  },
                  child: const Text('press me!'),
                ),
              ),
              AnimatedSize(
                duration: const Duration(milliseconds: 350),
                curve: Curves.easeOutCubic,
                child: AnimatedOpacity(
                  duration: const Duration(milliseconds: 350),
                  curve: Curves.easeOutCubic,
                  opacity: _isHintVisible ? 1.0 : 0.0,
                  child: SizedBox(
                    height: !_isHintVisible ? 0.0 : null,
                    child: const Text(
                      "The game will be installed to the provided directory path! If directory you've chose is not empty then it will be cleared!",
                      style: TextStyle(
                        fontSize: 14.0,
                        color: Colors.white,
                        height: 1.0,
                      ),
                    ),
                  ),
                ),
              ),
              AnimatedPadding(
                duration: const Duration(milliseconds: 350),
                curve: Curves.easeOutCubic,
                padding: EdgeInsets.only(top: _isHintVisible ? 8.0 : 0.0),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: <Widget>[
                    Container(
                      height: 35.0,
                      decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(4.0),
                          color: Colors.transparent,
                          border: Border.all(
                            width: 2.5,
                            color: Colors.red,
                          )),
                      child: const Text(
                        'Back button',
                        style: TextStyle(fontSize: 14.0, color: Colors.white),
                      ),
                    )
                  ],
                ),
              )
            ],
          ),
        ),
      ),
    );
  }
}

class EasyDropdown extends StatefulWidget {
  final String? hintText;
  final List<String> items;
  final List<IconData>? icons;
  final double fontSize;
  final Function onChanged;
  final String? value;
  final bool useAppLocaleOnItems;
  final double heightWithoutScale;
  final double? insets;
  final EdgeInsets? iconInsets;
  final Color? textColor;
  final FontWeight? fontWeight;
  final double width;
  final double? textMaxWidth;
  final Color? backgroundColor;
  final Color? menuBackgroundColor;
  final Function? onTapCallbackInsteadOfMenu;
  final bool forceTwoIcons;
  final double? maxDropdownMenuHeight;

  const EasyDropdown({
    Key? key,
    this.value,
    this.hintText,
    required this.items,
    this.icons,
    required this.fontSize,
    required this.onChanged,
    this.useAppLocaleOnItems = false,
    this.heightWithoutScale = 35.0,
    this.insets,
    this.iconInsets,
    this.textColor,
    this.fontWeight,
    required this.width,
    this.backgroundColor,
    this.menuBackgroundColor,
    this.onTapCallbackInsteadOfMenu,
    this.forceTwoIcons = false,
    this.textMaxWidth,
    this.maxDropdownMenuHeight,
  }) : super(key: key);

  @override
  _EasyDropdownState createState() => _EasyDropdownState();
}

class _EasyDropdownState extends State<EasyDropdown> {
  // A notifier to control arrow icon opacity
  final ValueNotifier<bool> _isHovered = ValueNotifier(false);

  @override
  void dispose() {
    _isHovered.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    /// Pre-cache text widget so that it can be used both with and without
    /// expanded parent.
    final Widget text = Padding(
      padding: const EdgeInsets.only(bottom: 1.0, right: 4.0),
      child: Container(
        alignment: Alignment.centerLeft,
        child: Container(
          constraints: BoxConstraints(
            maxWidth: widget.textMaxWidth ?? double.infinity,
          ),
          child: Text(
            widget.value != null
                ? widget.useAppLocaleOnItems
                    ? widget.value!
                    : widget.value!
                : widget.hintText!,
            overflow: TextOverflow.ellipsis,
            textAlign: TextAlign.left,
            style: TextStyle(
              fontSize: widget.fontSize,
              color: widget.textColor ?? Colors.white,
            ),
          ),
        ),
      ),
    );

    return MouseRegion(
      onEnter: (_) => _isHovered.value = true,
      onExit: (_) => _isHovered.value = false,
      cursor: SystemMouseCursors.click,
      child: GestureDetector(
        onTapDown: (_) {},
        child: Container(
          constraints: BoxConstraints(maxWidth: widget.width),
          decoration: BoxDecoration(
            color: widget.backgroundColor ?? Colors.black.withOpacity(0.50),
            boxShadow: [
              BoxShadow(
                color: Colors.black.withOpacity(0.25),
                blurRadius: 6.0,
                offset: const Offset(
                  0.0,
                  1.0,
                ), // changes position of shadow
              ),
            ],
            borderRadius: const BorderRadius.all(Radius.circular(6.0)),
          ),
          child: SizedBox(
            height: widget.heightWithoutScale,
            child: Padding(
              padding: EdgeInsets.symmetric(
                horizontal: widget.insets ?? 12.0,
              ),
              child: Row(
                mainAxisSize: MainAxisSize.min,
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: <Widget>[
                  widget.iconInsets == null
                      ? Expanded(child: text)
                      : Padding(
                          padding: widget.iconInsets ?? EdgeInsets.zero,
                          child: text,
                        ),
                  ValueListenableBuilder(
                    valueListenable: _isHovered,
                    builder: (_, bool value, __) => AnimatedOpacity(
                      duration: const Duration(milliseconds: 350),
                      curve: Curves.easeInOutCubic,
                      opacity: value ? 1.0 : 0.5,
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        key: ValueKey(value),
                        children: [
                          if (widget.onTapCallbackInsteadOfMenu != null ||
                              widget.forceTwoIcons)
                            Padding(
                              padding: const EdgeInsets.only(bottom: 4.0),
                              child: SvgPicture.asset(
                                'resources/icons/drop-arrow-flipped.svg',
                                color: Colors.white,
                                height: 4.0,
                                key: ValueKey('$value flipped'),
                              ),
                            ),
                          SvgPicture.asset(
                            'resources/icons/drop-arrow.svg',
                            color: Colors.white,
                            height: widget.onTapCallbackInsteadOfMenu != null ||
                                    widget.forceTwoIcons
                                ? 4.0
                                : 7.0,
                            key: ValueKey('$value normal'),
                          ),
                        ],
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

Title above the dropdown:
![test_window2_at9Mcg12MC](https://user-images.githubusercontent.com/63228361/190850822-7a99e1b0-95a3-4714-9ef4-1097ec0639b1.gif)

Text inside the dropdown: (remove animatedPadding from 117 to 140 lines)
![test_window2_4wiSlvkahi](https://user-images.githubusercontent.com/63228361/190850860-796366e9-480b-4c4a-8b6a-9c2edfead5e4.gif)

**Comment by jonahwilliams** [comment]
@kirill-21 have you tried latest master?

**Comment by kirill-21** [comment]
> @kirill-21 have you tried latest master?

Yes, it was tested on latest master

**Comment by jonahwilliams** [comment]
These all look like examples that would have been jumping in 3.0 and before. @kirill-21 are these new regressions?

**Comment by kirill-21** [comment]
> These all look like examples that would have been jumping in 3.0 and before. @kirill-21 are these new regressions?

Have no idea, i don't remember how that looked on Flutter 3.0

**Comment by jonahwilliams** [comment]
At least the first case still has the jiggle for me on 3.0. That means I'm not able to fix it with a revert.

Ultimately the problems with pixel snapping are UI artifacts like this. Unfortunately, removing pixel snapping is not an option as long as we have raster caching.

**Comment by kirill-21** [comment]
@jonahwilliams i've installed flutter 3.0.5 sdk and checked those code samples there:

Code sample №3 does not jump there, the other ones jump
![image](https://user-images.githubusercontent.com/63228361/190869686-7d5f6019-3daa-4058-b2ec-8356e9ccfe1a.png)

**Comment by kirill-21** [comment]
@jonahwilliams seems that jumping is also not fixed in scrollable widgets. (on flutter 3.0.5 there wasn't any jumps here)

![studio64_hn7yKa1ii3](https://user-images.githubusercontent.com/63228361/190929224-4610cfcd-92ad-42a9-bc6a-5be622aeb5b7.gif)

<details>

<summary>Code sample</summary>

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class EasyScrollBehavior extends ScrollBehavior {
  @override
  Set<PointerDeviceKind> get dragDevices => {
    PointerDeviceKind.touch,
    PointerDeviceKind.mouse,
    PointerDeviceKind.stylus,
  };
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      scrollBehavior: EasyScrollBehavior().copyWith(scrollbars: false),
      home: Scaffold(
        backgroundColor: Colors.black,
        appBar: AppBar(
          title: const Text('Material App Bar'),
        ),
        body: SingleChildScrollView(
          physics: const BouncingScrollPhysics(),
          child: Column(
            children: <Widget>[
              for (int i = 0; i < 30; i++)
                Padding(
                  padding: const EdgeInsets.only(bottom: 7.5),
                  child: EasySwitcher(
                    value: true,
                    onChange: (_) {},
                    title: 'Test',
                    description:
                        'Testing jumping issue inside scrollable widgets',
                    maxWidth: 390.0,
                  ),
                ),
            ],
          ),
        ),
      ),
    );
  }
}

class EasySwitcher extends StatefulWidget {
  final bool value;
  final Function onChange;
  final String title;
  final String tooltip;
  final String description;
  final double? maxWidth;
  final CrossAxisAlignment? alignment;
  final TextAlign? textAlign;

  const EasySwitcher({
    super.key,
    required this.value,
    required this.onChange,
    required this.title,
    this.tooltip = '',
    this.description = '',
    this.maxWidth,
    this.alignment,
    this.textAlign,
  });

  @override
  _EasySwitcherState createState() => _EasySwitcherState();
}

class _EasySwitcherState extends State<EasySwitcher> {
  late bool value = widget.value;
  bool _isHovered = false;

  /// Updates current value and executes onChange callback
  void _updateValue() => setState(() {
        value = !value;
        widget.onChange(value);
      });

  @override
  Widget build(BuildContext context) {
    const Color color = Color(0xFF636B73);
    const Color activeColor = Colors.white;

    return Container(
      constraints: BoxConstraints(maxWidth: widget.maxWidth ?? double.infinity),
      child: Column(
        crossAxisAlignment: widget.alignment ?? CrossAxisAlignment.start,
        children: [
          Wrap(
            crossAxisAlignment: WrapCrossAlignment.center,
            children: <Widget>[
              MouseRegion(
                onExit: (_) => setState(() => _isHovered = false),
                onEnter: (_) => setState(() => _isHovered = true),
                child: Container(
                  decoration: BoxDecoration(
                    color: Colors.transparent,
                    border: Border.all(
                      color: color,
                      width: 2.0,
                    ),
                    borderRadius: const BorderRadius.all(Radius.circular(13.0)),
                  ),
                  child: GestureDetector(
                    onTap: _updateValue,
                    child: MouseRegion(
                      cursor: SystemMouseCursors.click,
                      child: AnimatedPadding(
                        duration: const Duration(milliseconds: 350),
                        curve: Curves.easeInOutCubic,
                        padding: EdgeInsets.only(
                          left: value ? 13.0 : 0.0,
                          right: value ? 0.0 : 13.0,
                        ),
                        child: AnimatedContainer(
                          duration: const Duration(milliseconds: 350),
                          curve: Curves.easeInOutCubic,
                          margin: const EdgeInsets.all(3.0),
                          width: 9.0,
                          height: 9.0,
                          decoration: BoxDecoration(
                            color: _isHovered
                                ? Colors.blue.withOpacity(
                                    !value ? 0.50 : 0.75,
                                  )
                                : value
                                    ? activeColor
                                    : color,
                            borderRadius: const BorderRadius.all(
                              Radius.circular(19.0),
                            ),
                          ),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
              const SizedBox(width: 7.5),
              Padding(
                padding: const EdgeInsets.only(bottom: 1.0),
                child: Text(
                  widget.title,
                  style: const TextStyle(
                    fontSize: 16.0,
                    color: Colors.white,
                  ),
                  textAlign: widget.textAlign,
                ),
              ),
              const SizedBox(width: 5.0),
            ],
          ),
          if (widget.description.isNotEmpty)
            Container(
              constraints: BoxConstraints(
                maxWidth: widget.maxWidth ?? double.infinity,
              ),
              child: Text(
                widget.description,
                style: const TextStyle(
                  fontSize: 15.0,
                  color: Color(0xFF636B73),
                ),
                textAlign: widget.textAlign,
              ),
            )
        ],
      ),
    );
  }
}
```

</details>

**Comment by jonahwilliams** [comment]
I actually think that one is unrelated to the changes I'm reverting. Because you're using a column, all of your children are in a single picture layer, so the snapping might be happening in the display list code. I'll follow up on monday

**Comment by chinmaygarde** [comment]
@jonahwilliams Can we try looking into disabling raster caching on certain platforms?

**Comment by chinmaygarde** [comment]
From Triage: This is a collection of various issues related to raster caching. @jonahwilliams says he needs to go back and verify when each one was introduced (if they were indeed a regression). The removal of pixel snapping has been fixed and CP'ed though. Updating priority here.

**Comment by kirill-21** [comment]
> From Triage: This is a collection of various issues related to raster caching. @jonahwilliams says he needs to go back and verify when each one was introduced (if they were indeed a regression). The removal of pixel snapping has been fixed and CP'ed though. Updating priority here.

But not all examples(which are regressions) were fixed, app still looks bad from user experience side

**Comment by kirill-21** [comment]
One more example by the way
![test_window2_PjsNDZgvqo](https://user-images.githubusercontent.com/63228361/193672840-d64347ab-8811-4239-87ea-d4a218b09deb.gif)

<details>

<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_svg/svg.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with TickerProviderStateMixin {
  late final AnimationController _controller;
  late final Animation<Color?> _colorTween;

  @override
  void initState() {
    _controller = AnimationController(
      duration: const Duration(seconds: 2),
      reverseDuration: const Duration(seconds: 2),
      vsync: this,
    )..repeat(reverse: true);
    _colorTween = ColorTween(
      begin: Colors.red,
      end: Colors.red.withOpacity(0.75),
    ).animate(
      CurvedAnimation(
        parent: _controller,
        curve: Curves.easeInOutCubic,
      ),
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    bool isVisible = true;

    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: SizedBox(
            width: 200.0,
            height: 100.0,
            child: GestureDetector(
              onTap: () {
                setState(() => isVisible = !isVisible);

              },
              child: AnimatedSwitcher(
                duration: const Duration(milliseconds: 350),
                switchOutCurve: Curves.easeInOutCubic,
                switchInCurve: Curves.easeInOutCubic,
                child: Container(
                  key: UniqueKey(),
                  color: Colors.black,
                  width: 200.0,
                  height: 100.0,
                  child: !isVisible ? const SizedBox.shrink() : UnconstrainedBox(
                    child: AnimatedBuilder(
                      builder: (_, __) {
                        // Double size wrapper because widget jumps on
                        // color animation. Crazy...
                        return SizedBox(
                          height: 27.0,
                          child: SvgPicture.asset(
                            'resources/icons/unverified.svg',
                            color: _colorTween.value,
                            height: 26.0,
                          ),
                        );
                      },
                      animation: _colorTween,
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

Asset:
![unverified](https://user-images.githubusercontent.com/63228361/193673248-a042fb73-2498-4442-aa2c-43f3a3db8a33.svg)

**Comment by kirill-21** [comment]
Update; One more example; This AnimatedOpacity also jumps if shown in overlay
```dart
class _SmoothLayoutWidgetAppearance extends StatefulWidget {
  final Widget child;

  const _SmoothLayoutWidgetAppearance(this.child);

  @override
  State<_SmoothLayoutWidgetAppearance> createState() =>
      _SmoothLayoutWidgetAppearanceState();
}

class _SmoothLayoutWidgetAppearanceState
    extends State<_SmoothLayoutWidgetAppearance> {
  // Help with smooth appearing animation on widget creating
  double opacity = 0.0;

  @override
  void initState() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (mounted) setState(() => opacity = 1.0);
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedOpacity(
      opacity: opacity,
      duration: const Duration(milliseconds: 250),
      child: widget.child,
    );
  }
}

/// A delegate for computing the layout of a tooltip to be displayed above or
/// bellow a target specified in the global coordinate system.
class _TooltipPositionDelegate extends SingleChildLayoutDelegate {
  /// Creates a delegate for computing the layout of a tooltip.
  ///
  /// The arguments must not be null.
  _TooltipPositionDelegate({
    required this.target,
    required this.verticalOffset,
    required this.preferBelow,
  });

  /// The offset of the target the tooltip is positioned near in the global
  /// coordinate system.
  final Offset target;

  /// The amount of vertical distance between the target and the displayed
  /// tooltip.
  final double verticalOffset;

  /// Whether the tooltip is displayed below its widget by default.
  ///
  /// If there is insufficient space to display the tooltip in the preferred
  /// direction, the tooltip will be displayed in the opposite direction.
  final bool preferBelow;

  @override
  BoxConstraints getConstraintsForChild(BoxConstraints constraints) =>
      constraints.loosen();

  @override
  Offset getPositionForChild(Size size, Size childSize) {
    return positionDependentBox(
      size: size,
      childSize: childSize,
      target: target,
      verticalOffset: verticalOffset,
      preferBelow: preferBelow,
    );
  }

  @override
  bool shouldRelayout(_TooltipPositionDelegate oldDelegate) {
    return target != oldDelegate.target ||
        verticalOffset != oldDelegate.verticalOffset ||
        preferBelow != oldDelegate.preferBelow;
  }
}
```
```dart
OverlayEntry? overlayEntry;
      
      // Retrieve current widget global position with the help of context
      final RenderBox box = context.findRenderObject()! as RenderBox;
      final Offset target = box.localToGlobal(box.size.center(Offset.zero));

      // Create this widget outside of the overlay entry's builder to prevent
      // updated values from happening to leak into the overlay when the overlay
      // rebuilds.
      final Widget _overlay = Positioned.fill(
        child: CustomSingleChildLayout(
          delegate: _TooltipPositionDelegate(
            target: target,
            verticalOffset: 32.0,
            preferBelow: true,
          ),
          child: _SmoothLayoutWidgetAppearance(widget.layoutChild!),
        ),
      );

      // Create an entry to be displayed on top of the widget tree
      overlayEntry = OverlayEntry(
        builder: (_) {
          return _overlay;
        },
      );
```

**Comment by kirill-21** [comment]
@chinmaygarde @jonahwilliams Maybe issue priority can be changed to P3 or to P2 again? There are still a lot of places where widgets jump. Crazy workarounds has to be invented to fix it manually

**Comment by guchengxi1994** [comment]
still have the same issue on 3.3.7
![0_0_1_3](https://user-images.githubusercontent.com/33513462/200721468-ba44aac0-c718-4a7a-a9ca-13acb460772c.gif)

**Comment by kirill-21** [comment]
> still have the same issue on 3.3.7 ![0_0_1_3](https://user-images.githubusercontent.com/33513462/200721468-ba44aac0-c718-4a7a-a9ca-13acb460772c.gif) [ ![0_0_1_3](https://user-images.githubusercontent.com/33513462/200721468-ba44aac0-c718-4a7a-a9ca-13acb460772c.gif) ](https://user-images.githubusercontent.com/33513462/200721468-ba44aac0-c718-4a7a-a9ca-13acb460772c.gif) [ ](https://user-images.githubusercontent.com/33513462/200721468-ba44aac0-c718-4a7a-a9ca-13acb460772c.gif)

Can you share a code sample?

**Comment by guchengxi1994** [comment]
@kirill-21 here is the code.
```dart
class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Map<int, bool> status = {
    1: false,
    2: false,
    3: false,
    4: false,
    5: false,
    6: false,
    7: false,
    8: false,
    9: false,
  };

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Wrap(
      spacing: 10,
      runSpacing: 10,
      children: status.entries
          .map(
            (e) => MouseRegion(
              onEnter: (event) {
                setState(() {
                  status[e.key] = true;
                });
              },
              onExit: (event) {
                setState(() {
                  status[e.key] = false;
                });
              },
              child: Container(
                // color: e.value == true ? Colors.amber : Colors.green,
                decoration: e.value == true
                    ? BoxDecoration(
                        border: Border.all(
                            color: Colors.blue, width: 0.5), // border
                        borderRadius: BorderRadius.circular((1)), // 圆角
                      )
                    : null,
                // ignore: sized_box_for_whitespace
                child: Container(
                  width: 70,
                  height: 70,
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      const SizedBox(
                        width: 40,
                        height: 40,
                        child: Text(
                          "pretend here is an image",
                          maxLines: null,
                        ),
                      ),
                      const SizedBox(
                        height: 5,
                      ),
                      Text(
                        e.key.toString(),
                        overflow: TextOverflow.ellipsis,
                      )
                    ],
                  ),
                ),
              ),
            ),
          )
          .toList(),
    ));
  }
}
```

I am not sure if this bug is same to yours, but i  remembered that it didnt happened on 3.0.5.

I am sure it is related to this part
![image](https://user-images.githubusercontent.com/33513462/200977685-85190991-a848-40aa-8308-1db188e2eb16.png)
(decoration border)

if you use `color: e.value == true ? Colors.amber : Colors.green,`, it will not jump.
![11101](https://user-images.githubusercontent.com/33513462/200977853-132cbd7b-1b68-447e-8bef-f16186306491.gif)

![11102](https://user-images.githubusercontent.com/33513462/200977966-f578bb2d-741f-444f-b741-afad100092fa.gif)

**Comment by kirill-21** [comment]
> @kirill-21 here is the code.

This is not related to jumping issue, that's because border is not rendered until e.value == true, as soon as it renders it takes it's own space and moves the child.

You should change your code to
```dart
 decoration: BoxDecoration(
                    border: Border.all(
                      color: e.value == true ? Colors.blue : Colors.transparent,
                      width: 0.5,
                    ), // border
                    borderRadius: BorderRadius.circular((1)), // 圆角
                  ),
```

**Comment by guchengxi1994** [comment]
@kirill-21 thanks

**Comment by alexmercerind** [comment]
In my case, all `TextButton`'s label is jumping on scroll. Windows & Linux.

**Comment by kirill-21** [comment]
> In my case, all `TextButton`'s label is jumping on scroll. Windows & Linux.

You use BouncingScrollablePhysics?

**Comment by kirill-21** [comment]
https://flutter.github.io/samples/web/material_3_demo/#/ jumping issue even present in official flutter examples. When you switch from M3 to M2 design styles widgets jump

**Comment by kirill-21** [comment]
Any update on this?

**Comment by krll-kov** [comment]
Now when Impeller is released, this issue is also present on Android :c

**Comment by krll-kov** [comment]
real google pixel 7a on android 15

flutter run --enable-impeller --release

https://github.com/user-attachments/assets/3aa44cfd-8a24-46b4-a345-0fb4618cd20a


flutter run --no-enable-impeller --release


https://github.com/user-attachments/assets/373b46db-186e-4a64-b1fe-f33c8f9a3e8f

**Comment by krll-kov** [comment]
@jonahwilliams should this be referenced in a new issue or this is the same thing?
