### ISSUE TITLE
letterSpacing on Text adds leading and trailing space depending on the platform

### ISSUE THREAD

**Issue by alardizabal** [flutter/flutter#11196]
It seems adding letter spacing to a text widget also adds spacing to the end of the string. In a tab it causes the text to appear off-center. If the string terminates, I believe spacing shouldn't be added. The gist below demonstrates the issue.

https://gist.github.com/alardizabal/5dd5870628d8240da2af1259c8987bc7

![screenshot_20170713-114307](https://user-images.githubusercontent.com/3614291/28174944-ec0f3d38-67c0-11e7-8606-46239b37d0f0.png)

**Comment by Hixie** [comment]
cc @jason-simmons @GaryQian

**Comment by collinjackson** [comment]
Here's a workaround that should get you going in the meantime

```
tabs: new List<Widget>.generate(widget.tabCount, (int tabIndex) {
              return new Container(
                padding: const EdgeInsets.only(left: 12.0, right: 7.0),
                height: 46.0,
                constraints: const BoxConstraints(minWidth: 72.0),
                child: new Center(
                  child: new Text(
                    'A L',
                    style: const TextStyle(
                      letterSpacing: 5.0,
                    ),
                  ),
                ),
              );
            }),
```

**Comment by jason-simmons** [comment]
The engine's behavior is derived from Blink's implementation of the CSS letter-spacing property, which also appends space after each character (including the last)

**Comment by collinjackson** [comment]
I talked to @lukef and they're going to try the workaround since I don't expect a quick fix on this.

**Comment by zoechi** [comment]
Seems like the switch to libtxt solved this.

![screenshot_1545322168](https://user-images.githubusercontent.com/405837/50296151-0ea92c80-047a-11e9-9ab3-683f8ab72098.png)

**Comment by GaryQian** [comment]
Yes, for reference, LibTxt does not draw/reduces width to zero for trailing whitespace when the text is ltr center or right aligned.

**Comment by hasen6** [comment]
2 years on this problem still exists. The letter spacing property is adding an extra space at the end which is causing alignment issues. Flutter already has enough problems with alignment without this. Is it really difficult to fix?

**Comment by GaryQian** [comment]
@hasen6 Do you mind elaborating on what you are seeing as well as the output of `flutter doctor`? I was under the impression that this bug is fixed, at least as it was originally reported. Since the original report, Flutter has already completely switched text layout backends and behavior should have been drastically shaken up.

If you are seeing this again or some other bug, I will be happy to see if I can help you resolve it.

**Comment by hasen6** [comment]
@GaryQian Not sure that anyone said it was fixed, but anyway here is the problem, you can see that  the subtitle should be flush with the end of the title above but it's not because of the extra space at the end added by `letterSpacing`. With `letterSpacing` disabled it is flush as can be seen below.

![屏幕快照 2019-09-09 下午4 27 28](https://user-images.githubusercontent.com/15882674/64515335-fb4b3380-d31e-11e9-8052-42ee5a38ee77.png)
![屏幕快照 2019-09-09 下午4 28 57](https://user-images.githubusercontent.com/15882674/64515343-ff775100-d31e-11e9-93be-62eb13802548.png)

```
IntrinsicWidth(
  child: Column(
    crossAxisAlignment: CrossAxisAlignment.stretch,
    children: <Widget>[
      Text(
        'Title'
      ),
      Text(
        'small',
        textAlign: TextAlign.right
      ),
    ],
  ),
),
```

**Comment by markusaksli-nc** [comment]
Reproducible on the latest master `1.22.0-10.0.pre.428`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-10.0.pre.428, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.22.0-10.0.pre.428 at C:\Development\flutter_master
    • Framework revision a06f385145 (5 hours ago), 2020-09-29 21:37:04 -0400
    • Engine revision d18c3ea75c
    • Dart version 2.11.0 (build 2.11.0-178.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (5 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.508]
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 85.0.4183.121
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 85.0.564.51

• No issues found!
```
</details>
<details>
 <summary>Minimal reproducible code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
      title: 'Sample',
      home: MyApp(),
    ));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  var space = 0.0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Sample'),
      ),
      body: Center(
        child: IntrinsicWidth(
          child: Container(
            color: Colors.grey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                /*Text(
                  'Title',
                  style: TextStyle(
                    fontSize: 40,
                    letterSpacing: 100,
                  ),
                ),
                Text(
                  'small',
                  textAlign: TextAlign.right,
                ),*/
                Text(
                  'This is heading 1',
                  style: Theme.of(context)
                      .textTheme
                      .headline1
                      .copyWith(letterSpacing: 2 * space),
                ),
                Text(
                  'This is heading 2',
                  style: Theme.of(context)
                      .textTheme
                      .headline2
                      .copyWith(letterSpacing: space),
                ),
                Text(
                  'This is heading 3',
                  style: Theme.of(context)
                      .textTheme
                      .headline3
                      .copyWith(letterSpacing: 0),
                ),
              ],
            ),
          ),
        ),
      ),
      bottomNavigationBar: Container(
        height: 40,
        child: Card(
          child: Slider(
            min: 0,
            max: 100,
            value: space,
            onChanged: (double value) => setState(() => space = value),
          ),
        ),
      ),
    );
  }
}
```
</details>

The issue still remains exactly the same on web HTML (`letterSpacing` isn't working at all on Skia).

<img src="https://user-images.githubusercontent.com/68219924/94652397-a0f28b80-0302-11eb-8581-996686554062.png" width="100%" />

Seems like the leading and trailing spacing just became even on some platforms (Tested on Android and Windows).

<img src="https://user-images.githubusercontent.com/68219924/94652338-8a4c3480-0302-11eb-8ede-97c776261b54.png" width="100%" />

This leads to the behavior @hasen6 saw.

<img src="https://user-images.githubusercontent.com/68219924/94651514-3bea6600-0301-11eb-9bb0-fe9bb340a7f7.png" height="400" />

**Comment by otopba** [comment]
@markusaksli-nc Any updates?

**Comment by kf6gpe** [comment]
@jason-simmons This likely changes after the SkParagraph migration, true? Behavior change, not necessarily better or worse.

**Comment by jason-simmons** [comment]
SkParagraph tries to match the current behavior of Flutter's text APIs as closely as possible.  I tried running the sample code and confirmed that SkParagraph also renders letter spacing after the last character in the text.

This behavior dates back to the original implementation of Flutter text based on how CSS letter-spacing behaves in the Blink rendering engine.  Changing this would be a breaking change.

**Comment by exaby73** [comment]
This looks to be fixed in the latest stable versions, therefore I am closing it. If this issue is still reproducible, please comment of file a new issue. Thank you
