### ISSUE TITLE
Could not extract native JNI library.

### ISSUE THREAD

**Issue by JFixby** [flutter/flutter#11602]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

String: Exit code 1 from: D:\mobile_app\android\gradlew.bat -v:

FAILURE: Build failed with an exception.

* What went wrong:
Could not extract native JNI library.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:214)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:146)
<asynchronous suspension>
#2      _ensureGradle (package:flutter_tools/src/android/gradle.dart:128)
<asynchronous suspension>
#3      _calculateGradleAppOutDirV2 (package:flutter_tools/src/android/gradle.dart:83)
<asynchronous suspension>
#4      _getGradleAppOutDirV2 (package:flutter_tools/src/android/gradle.dart:76)
<asynchronous suspension>
#5      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:70)
<asynchronous suspension>
#6      AndroidApk.fromCurrentDirectory (package:flutter_tools/src/application_package.dart:88)
<asynchronous suspension>
#7      getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:267)
<asynchronous suspension>
#8      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:210)
<asynchronous suspension>
#9      HotRunner.run (package:flutter_tools/src/run_hot.dart:196)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:339)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:220)
<asynchronous suspension>
#12     RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:227)
<asynchronous suspension>
#13     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:162)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:277)
<asynchronous suspension>
#16     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#17     new Future.sync (dart:async/future.dart:222)
#18     CommandRunner.run (package:args/command_runner.dart:109)
#19     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#20     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#21     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#22     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#23     _rootRun (dart:async/zone.dart:1120)
#24     _CustomZone.run (dart:async/zone.dart:1001)
#25     runZoned (dart:async/zone.dart:1467)
#26     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#27     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#28     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#29     main (file:///D:/AndroidDev/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#30     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[вњ“] Flutter (on Microsoft Windows [Version 6.3.9600], locale en-US, channel master)
    вЂў Flutter at D:\AndroidDev\flutter
    вЂў Framework revision 1d353f6dcb (5 days ago), 2017-08-08 16:38:47 +0200
    вЂў Engine revision ff50334587
    вЂў Tools Dart version 1.25.0-dev.7.0

[вњ“] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    вЂў Android SDK at D:\AndroidSDK
    вЂў Platform android-26, build-tools 26.0.1
    вЂў ANDROID_HOME = D:\AndroidSDK
    вЂў Java binary at: C:\Program Files\Java\jdk1.8.0_131\bin\java
    вЂў Java version Java(TM) SE Runtime Environment (build 1.8.0_131-b11)

[-] Android Studio (version 2.1)
    вЂў Android Studio at C:\Program Files\Android\Android Studio
    вњ— Unable to find bundled Java version.
    вЂў Try updating or re-installing Android Studio.

[вњ“] IntelliJ IDEA Community Edition (version 2017.2)
    вЂў Flutter plugin version 16.0
    вЂў Dart plugin version 172.3317.48

[вњ“] Connected devices
    вЂў GT N8000 вЂў 410788155420408d вЂў android-arm вЂў Android 4.4.2 (API 19)

```

**Comment by Hixie** [comment]
cc @mravn-google

**Comment by mravn-google** [comment]
@JFixby According to the `flutter doctor` output above, your Android Studio installation is either outdated or incomplete. The latest stable version is 2.3.3.

**Comment by JFixby** [comment]
I'm not using Android Studio.

**Comment by mravn-google** [comment]
Sure. And updating Android Studio may not solve your problem. But we are giving the location of the Java SDK bundled by Android Studio as environment for gradle executions invoked by `flutter build apk`.

Otherwise, [this](https://stackoverflow.com/questions/36797068/gradle-sync-failed-cant-load-library-windows-amd64-native-platform-dll) may be more helpful.

Please let us know if that is the case.

**Comment by JFixby** [comment]
Ok I see.
Also I fixed the problem by cleaning gradle cache.
Now someone should take care of the exception above.

**Comment by mravn-google** [comment]
Yes, it would be nice if flutter tooling could handle this case. Thanks for reporting!

**Comment by Hixie** [comment]
It's not clear how to trigger this exception. Do we know what steps will reproduce this?

**Comment by mravn-google** [comment]
The exact steps may be specific to Windows. Inspired by [this StackOverflow question](https://stackoverflow.com/questions/36797068/gradle-sync-failed-cant-load-library-windows-amd64-native-platform-dll), we can get a similar exception on MacOS by deleting e.g. `$USER/.gradle/native/23/osx-amd64/libnative-platform.dylib`, leaving only the associated `.lock` file. It is still unclear how the Gradle cache could become corrupted in this way though.

**Comment by fritz-playmaker** [comment]
Cleared my cache but still getting this error when I run the command "flutter run"

Could not extract native JNI library.

>

**Comment by achat12** [comment]
Did you check the file directories or check the types of file paths?

**Comment by jonahwilliams** [comment]
I don't think we're ever going to handle going to handle generic Gradle failures. In this case, the best solution is fixing the output message so users can get the full Gradle stack trace. This unlocks existing stack overflow and other tutorial documentation to help them.

https://github.com/flutter/flutter/issues/13466
