### ISSUE TITLE
Update to pre-release package:intl breaking customer_tests

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#117163]
A recent pub autoroll revved package:intl 0.17 -> 0.18 https://github.com/flutter/flutter/pull/117150 while flutter/gallery and some of its dependencies pin intl: ^0.17.0. Thus in the customer_tests pre-submit checks, flutter pub get fails to resolve in the gallery and super editor.

To unblock the roll, I will pin package:intl. To unpin, all customer test apps and their transitive dependencies that are caret depending on package:intl should be updated to not constrain them, since an exact pin constraint will be provided by the flutter sdk repo.

**Comment by christopherfujino** [comment]
https://github.com/superlistapp/super_editor/pull/895 opened to unblock

**Comment by christopherfujino** [comment]
Note the policy update to flutter/tests to try to avoid this situation in the future: https://github.com/flutter/tests/pull/192

**Comment by christopherfujino** [comment]
The super_editor upstream PR was landed. However, I am still blocked by:

1. flutter/gallery depends on `intl: ^0.17.0`
2. flutter/gallery depends on [flutter_localized_locales](https://github.com/guidezpl/flutter-localized-locales) ^2.0.3 (which hasn't been updated in 7 months)
3. flutter_localized_locales depends on `intl: 0.17.0`
4. flutter_localized_locales depends on `[cupertino_icons](https://github.com/flutter/packages/blob/main/third_party/packages/cupertino_icons/pubspec.yaml): ^0.1.3`
5. cupertino_icons depends on dart sdk `">=2.12.0 <3.0.0"`, which does not version solve with the Dart SDK in the latest flutter SDK

To fix would require:

1. updating the Dart SDK constraint in cupertino_icons
2. publishing a new pub release of cupertino_icons
3. updating cupertino_icons and intl constraints in flutter_localized_locales
4. publishing a new pub release of flutter_localized_locales
5. updating flutter/gallery with new constraints for intl and flutter_localized_locales
6. roll new gallery to flutter/tests
7. remove pin of intl in flutter tool and upgrade all packages

**Comment by christopherfujino** [comment]
Actually, blocker #5 might actually be https://github.com/dart-lang/pub/issues/3686

**Comment by christopherfujino** [comment]
@guidezpl could you help unblock this by removing the constraint on `package:intl` to the new flutter gallery and its dependencies?

**Comment by mosuem** [comment]
As the owner of package:intl, is there anything I can do to help? Or are the items in the list above already being addressed?

**Comment by Carapacik** [comment]
Any updates for this?

**Comment by christopherfujino** [comment]
> Of course! I've done 3. and 4., 5. will be done with [flutter/gallery#864](https://github.com/flutter/gallery/pull/864).

Awesome, lemme pick up the thread and roll the gallery.

**Comment by deandreamatias** [comment]
Hi!
[flutter_localizations still with 0.17.0](https://github.com/flutter/flutter/blob/c07f7888888435fd9df505aa2efc38d3cf65681b/packages/flutter_localizations/pubspec.yaml#L11)
This could be solve in this issue or in another?

**Comment by christopherfujino** [comment]
> Hi! [flutter_localizations still with 0.17.0](https://github.com/flutter/flutter/blob/c07f7888888435fd9df505aa2efc38d3cf65681b/packages/flutter_localizations/pubspec.yaml#L11) This could be solve in this issue or in another?

not sure what blob that is, but it's old. This is fixed at HEAD https://github.com/flutter/flutter/blob/main/packages/flutter_localizations/pubspec.yaml#L11

**Comment by deandreamatias** [comment]
Ooh you are right, sorry
This will be release in next Flutter major update?

**Comment by christopherfujino** [comment]
> Ooh you are right, sorry This will be release in next Flutter major update?

It will be in a stable release eventually; I can't say whether or not it will be in the next one, but most likely.

**Comment by husainazkas** [comment]
> > Hi! [flutter_localizations still with 0.17.0](https://github.com/flutter/flutter/blob/c07f7888888435fd9df505aa2efc38d3cf65681b/packages/flutter_localizations/pubspec.yaml#L11) This could be solve in this issue or in another?
> 
> not sure what blob that is, but it's old. This is fixed at HEAD https://github.com/flutter/flutter/blob/main/packages/flutter_localizations/pubspec.yaml#L11

But I still cannot use flutter_localization with intl ^0.18.0

Here is output:
```
Running "flutter pub get" in my_project...
Resolving dependencies... 
Because my_project depends on flutter_localizations from sdk which depends on intl 0.17.0, intl 0.17.0 is required.
So, because my_project depends on intl ^0.18.0, version solving failed.
```

But if I run `flutter update-packages --force-upgrade` it had worked. I think it's not a good solution 'cause if I reinstall or upgrade Flutter SDK so I cannot run pub get again, then I have to run command above again.

Have you a good solution? Thank you.

**Comment by christopherfujino** [comment]
> > > Hi! [flutter_localizations still with 0.17.0](https://github.com/flutter/flutter/blob/c07f7888888435fd9df505aa2efc38d3cf65681b/packages/flutter_localizations/pubspec.yaml#L11) This could be solve in this issue or in another?
> > 
> > 
> > not sure what blob that is, but it's old. This is fixed at HEAD https://github.com/flutter/flutter/blob/main/packages/flutter_localizations/pubspec.yaml#L11
> 
> But I still cannot use flutter_localization with intl ^0.18.0
> 
> Here is output:
> 
> ```
> Running "flutter pub get" in my_project...
> Resolving dependencies... 
> Because my_project depends on flutter_localizations from sdk which depends on intl 0.17.0, intl 0.17.0 is required.
> So, because my_project depends on intl ^0.18.0, version solving failed.
> ```
> 
> But if I run `flutter update-packages --force-upgrade` it had worked. I think it's not a good solution 'cause if I reinstall or upgrade Flutter SDK so I cannot run pub get again, then I have to run command above again.
> 
> Have you a good solution? Thank you.

I'm guessing you're using a release of Flutter that does not yet have the fix. You have two options:

1) Switch to a newer version of the Flutter SDK (such as the current beta release https://github.com/flutter/flutter/blob/beta/packages/flutter_localizations/pubspec.yaml#L11)
2) update `my_project` to depend on `intl: any`. This will satisfy `flutter pub get`, as it will use the exact pin of whatever Flutter SDK you aren't currently using.

**Comment by husainazkas** [comment]
> > > > Hi! [flutter_localizations still with 0.17.0](https://github.com/flutter/flutter/blob/c07f7888888435fd9df505aa2efc38d3cf65681b/packages/flutter_localizations/pubspec.yaml#L11) This could be solve in this issue or in another?
> > > 
> > > 
> > > not sure what blob that is, but it's old. This is fixed at HEAD https://github.com/flutter/flutter/blob/main/packages/flutter_localizations/pubspec.yaml#L11
> > 
> > 
> > But I still cannot use flutter_localization with intl ^0.18.0
> > Here is output:
> > ```
> > Running "flutter pub get" in my_project...
> > Resolving dependencies... 
> > Because my_project depends on flutter_localizations from sdk which depends on intl 0.17.0, intl 0.17.0 is required.
> > So, because my_project depends on intl ^0.18.0, version solving failed.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But if I run `flutter update-packages --force-upgrade` it had worked. I think it's not a good solution 'cause if I reinstall or upgrade Flutter SDK so I cannot run pub get again, then I have to run command above again.
> > Have you a good solution? Thank you.
> 
> I'm guessing you're using a release of Flutter that does not yet have the fix. You have two options:
> 
> 1. Switch to a newer version of the Flutter SDK (such as the current beta release https://github.com/flutter/flutter/blob/beta/packages/flutter_localizations/pubspec.yaml#L11)
> 2. update `my_project` to depend on `intl: any`. This will satisfy `flutter pub get`, as it will use the exact pin of whatever Flutter SDK you aren't currently using.

Thanks for the answer. I use stable release of Flutter (3.7.5) and might not have the fix of this issue. So I downgrade the intl to previous version (0.17.0).

FYI: I used Flutter 3.7.3 before and runs `flutter pub outdated`. It shows intl package have new update version 0.18.0 on resolvable column. So I decide to upgrade it then the error appeared. After run `flutter update-packages --force-upgrade` the error was fixed but today I upgrade Flutter to 3.7.5 it reset again and shows error incompatible version of intl that I described above. Now, I downgrade intl to 0.17.0 then run `flutter pub outdated` it shows intl package only have version 0.18.0 on latest column, not resolvable. It's like joking to me LOL.

**Comment by christopherfujino** [comment]
> FYI: I used Flutter 3.7.3 before and runs `flutter pub outdated`. It shows intl package have new update version 0.18.0 on resolvable column.

Hmm, this actually sounds like a bug that it would not try to solve against package:flutter dependencies.

> After run `flutter update-packages --force-upgrade` the error was fixed but today I upgrade Flutter to 3.7.5 it reset again and shows error incompatible version of intl that I described above.

This command is intended only for maintainers. Of course, Flutter is open source, nothing is stopping you from doing this, however, you've voided your warranty (this is effectively changing the Flutter SDK to an untested version), and if you file bugs on the issue tracker SDK maintainers will tell you to revert your changes.

The officially supported way to get package:intl version 0.18.0 would be to switch to a newer version of the Flutter SDK, such as the newest beta.
