### ISSUE TITLE
[video_player] Boundary times (auto pause points)

### ISSUE THREAD

**Issue by bdezso** [flutter/flutter#117737]
## Use case

I want to stop the video at predefined times. Because of the relationship between flutter and native code it's impossible to do within a reasonable time, so it'll always some delay between the desired time and the actual value after the video stopped.

## Proposal

On iOS side we can use 
https://developer.apple.com/documentation/avfoundation/avplayer/1388027-addboundarytimeobserver **addBoundaryTimeObserver** method of AVPlayer. 

On Android side we can use 
https://exoplayer.dev/listening-to-player-events.html **PlayerMessage**.

When native player fire the boundary time event at the specific times we immediately pause the video and send an event to the flutter side. 

### Extending video_player interface:

`Stream<Duration> getAutoPauseStream();`
This function return a stream which get new data when auto pause happened on native side.

`Future<void> setPausePoints(List<Duration> pausePoints) async;`
This function set **auto pause points** in the native video player.

I've already implemented this whole feature, the only missing parts are unit tests, and the response about this PR is welcome or not.

### Questions
- What kind of unit tests should be written for this feature?
- Are the method names correct?

**Comment by darshankawar** [comment]
Thanks for the report. Treating this as a potential proposal.



> ### Questions
> * What kind of unit tests should be written for this feature?
> * Are the method names correct?

You may take a look at [contribution guide](https://github.com/flutter/flutter/wiki/Tree-hygiene#tests) and see if it helps to answer your questions.

**Comment by stuartmorgan** [comment]
> `Stream<Duration> getAutoPauseStream();`
> This function return a stream which get new data when auto pause happened on native side.

Why would there need to be a new stream, vs. someone just listening to the existing `ValueNotifier` event stream?

**Comment by bdezso** [comment]
@stuartmorgan 
If we don't want to know the cause of the pause, we don't need this extra stream.
You can't be sure if the pause was caused by the user or the system, but it might not matter.

Would we want to know the cause of the pause? 
If not, I will remove this extra stream and we will only need the **`setPausePoints.`**

**Comment by bdezso** [comment]
@stuartmorgan 
I've implemented without the extra stream, could you answer my last question? 
Thank you for your time and consideration.

**Comment by stuartmorgan** [comment]
If you're referring to this:

> Would we want to know the cause of the pause?

I can't provide a useful answer since I'm not a client of the proposed API.

**Comment by bdezso** [comment]
Ok, then I keep the original version with the extra stream. We want to know the cause of the pause.
I'll make a pull request soon.

**Comment by stuartmorgan** [comment]
I'm still not clear on why that requires a whole new steam. Why not a flag or enum on the state indicating the type of source of the transition change for transitions? E.g., none/automatic/manual
