### ISSUE TITLE
Flutter and Dart plugin not installed warnings in flutter doctor

### ISSUE THREAD

**Issue by alardizabal** [flutter/flutter#11940]
I'm using IntelliJ CE 2017.2.3 EAP and I get missing plugin warnings in `flutter doctor` when it seems like everything is installed properly and I have no issues building.

<img width="1134" alt="screen shot 2017-09-05 at 6 35 37 pm" src="https://user-images.githubusercontent.com/3614291/30086432-0acb906e-9269-11e7-8ae3-b2caca9fba16.png">

<img width="1134" alt="screen shot 2017-09-05 at 6 36 43 pm" src="https://user-images.githubusercontent.com/3614291/30086483-3b576ca8-9269-11e7-8c89-7cdf0d7fef3e.png">

<img width="1134" alt="screen shot 2017-09-05 at 6 35 28 pm" src="https://user-images.githubusercontent.com/3614291/30086434-0cc628f2-9269-11e7-8695-87b3e74ed9f7.png">

<img width="1134" alt="screen shot 2017-09-05 at 6 36 56 pm" src="https://user-images.githubusercontent.com/3614291/30086486-404288f6-9269-11e7-9458-f363055ef2cd.png">

```
☆ flutter doctor
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel master)
    • Flutter at /Users/albertlardizabal/dev/flutter
    • Framework revision 321b80961f (85 minutes ago), 2017-09-05 17:00:42 -0400
    • Engine revision 29e0c1c281
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/albertlardizabal/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.0
    • CocoaPods version 1.3.1

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.0 Preview.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] IntelliJ IDEA Community Edition (version EAP IC-172.3968.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices
    • Pixel                        • FA71A0302167                             • android-arm • Android 7.1.2 (API 25)
    • SM G930V                     • a674c503                                 • android-arm • Android 6.0.1 (API 23)
    • Albert Lardizabal's iPhone 6 • c0e109b7e55a826627aa0f3e79af8931534f3554 • ios         • iOS 11.0
    • iPhone                       • 2cb36c18cfeec63f6a68b3192f094aaf35a626d0 • ios         • iOS 10.0.2
```

**Comment by sunglim** [comment]
I recommend you setup again as described on https://flutter.io/setup-macos/
(at least, you are using master branch, but the manual uses 'alpha' branch)

**Comment by Hixie** [comment]
cc @devoncarew @tvolkert

**Comment by waihanko** [comment]
I alerady faced this issue but i solved by myself
-Uninstall Dart and flutter 
-Restart android studio or intellij
-Install Dart and flutter and restart again

Hope you will help

**Comment by bradh43** [comment]
I found an alternative way to fix this issue. You can just install the Flutter and Dart plugin in android studio by following these steps:
1.) Start the Android Studio application
2.) Open plugin preferences (Preferences>Plugins on macOS, File>Settings>Plugins on Windows & Linux).
3.) Select Browse repositories…, select the Flutter plug-in and click install .
4.) Click Yes when prompted to install the Dart plugin.
5.) Click Restart when prompted.

**Comment by arkaghosh98** [comment]
Thanks for helping...:)

**Comment by TusharGogna** [comment]
I did what bradh43 said but I am still getting the following:
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.

They are installed and enabled, also the paths are set. I have also restarted the AS.

**Comment by XiaYongjie** [comment]
@giteekasawlani I have the same problem. Do you know how to solve it?

**Comment by TusharGogna** [comment]
I was able to resolve the issue. In my case, I was not using Stable Android Studio and when I installed the stable version 3.1.2, it worked as a charm and I was able to create an application.

**Comment by anthonyfok** [comment]
I think I am starting to understand the issue.

```
[✓] Android Studio (version 3.2)
    • Android Studio at /opt/google/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b04)
```

According to packages/flutter_tools/lib/src/android/android_studio.dart, for Windows and Linux, `flutter doctor` is looking in

* $HOME/.AndroidStudio<i>X.Y</i> (e.g., $HOME/.AndroidStudio3.1)

for the Flutter and Dart plugins, but for those of us running Beta or even Canary channel of Android Studio, the directory is actually here:

* $HOME/.AndroidStudioPreview<i>X.Y</i> (e.g., $HOME/.AndroidStudioPreview3.2)

The current code actually manages to find the $HOME/.AndroidStudioPreview3.2 directory correctly:

```dart
final RegExp _dotHomeStudioVersionMatcher =
    new RegExp(r'^\.AndroidStudio([^\d]*)([\d.]+)');
```

But elsewhere in the code, it does not use the above result, and instead hard-codes the plugin path like so:

```dart
      if (platform.isMacOS) {
        _pluginsPath = fs.path.join(
            homeDirPath,
            'Library',
            'Application Support',
            'AndroidStudio$major.$minor');
      } else {
        _pluginsPath = fs.path.join(homeDirPath,
            '.AndroidStudio$major.$minor',
            'config',
            'plugins');
      }
```

i.e. $HOME/AndroidStudio3.2/config/plugins, which does not exist today (3.2 is still in beta).

I am very new to Dart and do not know how to fix the code properly yet, but hope the Flutter authors could fix this.  Many thanks!

**Comment by zoechi** [comment]
That should long be fixed in versions newer then `beta 0.5.1`.

**Comment by xiaods** [comment]
@admin95271 只要有代理可以下面。don't worry.

**Comment by lucktail** [comment]
我遇到了相同的问题，因为我的Android Studio是preview版本。我通过安装正式版的Android Studio version3.2.1 解决了这个问题

**Comment by cnscorpions** [comment]
@bradh43 it works, thank you

**Comment by jiayuanfa** [comment]
![image](https://user-images.githubusercontent.com/9419485/49487061-cedc2580-f87b-11e8-8970-c4ee7c969440.png)


![image](https://user-images.githubusercontent.com/9419485/49487043-be2baf80-f87b-11e8-9960-fc600c0bf2a3.png)

![image](https://user-images.githubusercontent.com/9419485/49487030-af44fd00-f87b-11e8-94c2-ceec395f363c.png)

I am also the problem..

**Comment by zoechi** [comment]
@jiayuanfa your Flutter install looks corrupted.
It says Flutter `0.9.5-pre.2 2018-12-05 (48 minutes ago)` but if it were that new, it would be `0.11.x` or `1.0.0`. Please try https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#ways-to-fix to fix your Flutter install and then try again.
If it still doesn't work please post your `flutter doctor -v`

**Comment by tryer3000** [comment]
got the same problem.

following steps save me from this situation.
update as to 3.2.1
install plugins
restart as
ps: i'm using flutter 1.0.0

**Comment by Yuanuo** [comment]
Some people mentioned above have already mentioned this problem by installing a stable version of Android Studio.

Let me talk about the solution for the preview version of Android Studio (tested on Windows 10).

I am using Android Studio Preview 3.4 (Canary 7). The default user directory is $HOME/.AndroidStudioPreview3.4. According to the above analysis of @anthonyfok ([Link](#issuecomment-406203746)), it will actually look for $HOME/.AndroidStudio3.4, so create a directory link. This can solve the problem, such as (xxxx is username):

**C:\Users\xxxx>mklink /J /D ".AndroidStudio3.4" C:\Users\xxxx\.AndroidStudioPreview3.4**

If you use a custom idea.properties, it is also possible to link directly to the actual directory, for example:

**C:\Users\xxxx>mklink /J /D ".AndroidStudio3.4" E:\.AndroidStudio**


before fix:
[√] Android Studio
    • Android Studio at E:\IDE\Android-Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = E:\IDE\Android-Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

after that :
[√] Android Studio (version 3.4)
    • Android Studio at E:\IDE\Android-Studio
    • Flutter plugin version 31.1.4
    • Dart plugin version 183.4733
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

**Comment by Diwas777** [comment]
Configure this :
1)Get path of android sdk  (My Case : C:\Users\DIWAS\AppData\Local\Android\Sdk)
2)Open command on that path run below command
  flutter config --android-sdk C:\Users\DIWAS\AppData\Local\Android\Sdk

**Comment by zoechi** [comment]
@Diwas777 setting `ANDROID_HOME=C:\Users\DIWAS\AppData\Local\Android\Sdk` should do as well. Your approach needs to be done per project.

**Comment by olivrg** [comment]
I experienced this issue on Mac and even with @bradh43's instructions I was still seeing the same messages: 
X Flutter plugin not installed; this adds Flutter specific functionality.
X Dart plugin not installed; this adds Dart specific functionality.

So I fully uninstalled Android Studio and reinstalled the sdk with brew using [this link](https://gist.github.com/patrickhammond/4ddbe49a67e5eb1b9c03#gistcomment-1336645).

Everything worked fine after the reinstallation.

**Comment by farishanugraha** [comment]
> I found an alternative way to fix this issue. You can just install the Flutter and Dart plugin in android studio by following these steps:
> 1.) Start the Android Studio application
> 2.) Open plugin preferences (Preferences>Plugins on macOS, File>Settings>Plugins on Windows & Linux).
> 3.) Select Browse repositories…, select the Flutter plug-in and click install .
> 4.) Click Yes when prompted to install the Dart plugin.
> 5.) Click Restart when prompted.

In addition to bradh43's answer, make sure to **restart android studio**, and **restart your computer** if needed. I use Xubuntu 18.04 and it works.

**Comment by kangwang1988** [comment]
Maybe related to: https://github.com/flutter/flutter/issues/26928

**Comment by zoechi** [comment]
Please check if you can still reproduce in latest master. 
Tentatively closing as duplicate of #26928.
Please add a comment to have it reopened in case you can still reproduce.

**Comment by hero78** [comment]
Thanks for the write up . it has helped me alot . on linux mint

**Comment by MarkJoyful** [comment]
Be sure to install in order
`1.Start Android Studio.`
`2.Open plugin preferences (Preferences > Plugins on macOS, File > Settings > Plugins on Windows & Linux).`
`3.Select Browse repositories, select the Flutter plugin and click Install.`
`4.Click Yes when prompted to install the Dart plugin.`
`5.Click Restart when prompted.`

**Comment by paulo166** [comment]
> I alerady faced this issue but i solved by myself
> -Uninstall Dart and flutter
> -Restart android studio or intellij
> -Install Dart and flutter and restart again

Work nicely!!!

**Comment by paulo166** [comment]
> I found an alternative way to fix this issue. You can just install the Flutter and Dart plugin in android studio by following these steps:
> 1.) Start the Android Studio application
> 2.) Open plugin preferences (Preferences>Plugins on macOS, File>Settings>Plugins on Windows & Linux).
> 3.) Select Browse repositories…, select the Flutter plug-in and click install .
> 4.) Click Yes when prompted to install the Dart plugin.
> 5.) Click Restart when prompted.

Work wonderfully!!!!

**Comment by fakhriamir** [comment]
if you installed intellij idea on your pc
open it and into plugins install fluter and dart

**Comment by Teriroland15** [comment]
for those using Windows 10 follow these steps to fix this issue. You can just install the Flutter and Dart plugin in android studio by following these steps:
1.) Start the Android Studio application
2.) Select (File>Settings(Ctl+Alt+S),>Plugins on Windows.
3.) Select Browse repositories…, select the Flutter plug-in and click install .
4.) Click Yes when prompted to install the Dart plugin.
5.) Click Restart when prompted.

**Comment by onegeqian** [comment]
自定义配置目录后，AS是检测不到的。在flutter中配置 config --android-studio-dir "xxx"，解决检测AS安装，但是，插件目录又检测不到了。所以会一直报 两个插件没装上。
奋战10多个小时，才的出来的结论，何解。

**Comment by onegeqian** [comment]
自定义配置目录后，AS是检测不到的。在flutter中配置 config --android-studio-dir "xxx"，解决检测AS安装，但是，插件目录又检测不到了。所以会一直报 两个插件没装上。
奋战10多个小时，才的出来的结论，何解。
使用syslink 也不行。

**Comment by harishalwala** [comment]
> I found an alternative way to fix this issue. You can just install the Flutter and Dart plugin in android studio by following these steps:
> 1.) Start the Android Studio application
> 2.) Open plugin preferences (Preferences>Plugins on macOS, File>Settings>Plugins on Windows & Linux).
> 3.) Select Browse repositories…, select the Flutter plug-in and click install .
> 4.) Click Yes when prompted to install the Dart plugin.
> 5.) Click Restart when prompted.

This worked for me

**Comment by ifredom** [comment]
use 【 android studio 】 to install the 2 plugins

**Comment by pyjyingjie** [comment]
I have the same issues, but I solved it. Here is my solution. It is best if it helps everyone.

My problem scenario was reported after I installed `Android Studio`, `Flutter Plug-in`, `Dart Plug-in`.

Because my `Android Studio` is installed in the `D:\Program files\Android Studio` directory, even if I move it to  `D:\Android Studio`, it doesn't work because of spaces.

If you change the name of the `Android Studio` folder to a folder name without spaces, you can do it.

So I think that the installation directory of `Android Studio` and `Android Sdk` and its own folder name can not carry any spaces.

My current directory structure is:
```
D:\Android
D:\Android\.gradle
D:\Android\AndroidSdk
D:\Android\Flutter
D:\Android\Studio
```

**Comment by haipv2** [comment]
I use Android studio 3.1
I face the same issue, I've tried to fix very much but it still error:
- Method 1: change channel stable, master. Still error
- Method 2: remove, install flutter, dart plugin (restart IDE if it's necessary) few times. Still error 
- Method 3: run command: flutter config --android-sdk D:\03.android\sdk20180918
Some other methods which I found on the internet. But it's still error. How can I fix ?
Thanks in advance!!! 
![image](https://user-images.githubusercontent.com/11954778/64039759-9ad12f00-cb85-11e9-9446-21c376a8fb25.png)
![image](https://user-images.githubusercontent.com/11954778/64039776-a6245a80-cb85-11e9-916b-5e0b9883662a.png)

**Comment by IbtisamAl** [comment]
try to use the latest version

**Comment by patelkrunal78** [comment]
Very Similar To [Flutter plugin not installed error;. When running flutter doctor](https://icetutor.com/question/flutter-plugin-not-installed-error-when-running-flutter-doctor)

**Comment by milanpatel18** [comment]
Export Flutter Path Permanently

To export flutter path permanently 👍 

export PATH="$PATH:/path/to/dir" in the .bashrc

For example:
export PATH="$PATH:/home/frodo/flutter/bin/flutter"

And run:

source .bashrc 

Find Source Code At [Here](https://icetutor.com/question/flutter-plugin-not-installed-error-when-running-flutter-doctor/)

**Comment by yannble** [comment]
what really helped was: "
 Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir="
from flutter doctor in android studio

**Comment by irahulcse** [comment]
I had also got the same type of the error in VS Code. But I had noticed that in the Android Studio, I had installed the Flutter and Dart Plugin.
Operating System:Ubuntu 18.04

![Screenshot from 2019-11-11 11-40-48](https://user-images.githubusercontent.com/34218254/68584809-9f2f9780-04a6-11ea-85f7-e68fa5218e87.png)

Now after installing the Plugins by going in the Settings of the Android Studio. Go to Plugins and search Flutter and it will automatically going to ask for the Dart Plugin to be installed too. Install the both plugins and restart the Android Studio.
After come to the VS Code and run the `flutter doctor`. The error will be resolved.

![Screenshot from 2019-11-11 11-40-48](https://user-images.githubusercontent.com/34218254/68584954-f0d82200-04a6-11ea-929b-632a26ef9b52.png)

**Comment by jaitjacob** [comment]
![Inked043Bdy3Wo0_LI](https://user-images.githubusercontent.com/14340591/68954327-ec4d9980-0817-11ea-88fb-77dbc3f84cbc.jpg)
I faced this too. all you have to do is install plugin "Flutter" from Android Studio. Please note that installing this plugin will also install the plugin "Dart" along with it.
![image](https://user-images.githubusercontent.com/14340591/68954619-7eee3880-0818-11ea-8d59-afd3efa62a0e.png)

**Comment by arifardians-gibeon** [comment]
> ![image](https://user-images.githubusercontent.com/9419485/49487061-cedc2580-f87b-11e8-8970-c4ee7c969440.png)
> 
> ![image](https://user-images.githubusercontent.com/9419485/49487043-be2baf80-f87b-11e8-9960-fc600c0bf2a3.png)
> 
> ![image](https://user-images.githubusercontent.com/9419485/49487030-af44fd00-f87b-11e8-94c2-ceec395f363c.png)
> 
> I am also the problem..

if you installed intellij idea or android studio on your pc
open both and into plugins install fluter and dart

**Comment by appapurapu** [comment]
In my case, I have two versions of Android studio on mac. Where one android studio app is installed with flutter and dart but not other.
So when flutter doctor is run, it checks all android studio apps and Intellij Idea App and output the result.
After removing the old unused android studio app, flutter doctor not complained any more.
adb server version (32) doesn't match this client (41); killing...
* daemon started successfully

XXXXXXXXXX$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.13.6, on Mac OS X 10.14.6 18G84, locale en-AE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] Proxy Configuration
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
rajaa:development rajaa$

**Comment by essdiel** [comment]
With my installation, I was getting the following:
```
XXXXXX$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

Since I had installed the Android SDK to a folder that was non-writable with user permissions, I ran
`sudo ./studio.sh`
to complete the set-up manager.  However, even though I had installed the Flutter and Dart plug-ins, I was still getting the "... plugin not installed" issue.  I then ran
`chmod 777 <path-to-android-sdk>`
after taking note of the original permissions, and ran Android Studio as non-root.  I completed the set-up manager as non-root, installed the plugins, and `flutter doctor` finally detected the plugins.

As an aside, I resolved the Android licenses as shown [here](https://github.com/flutter/flutter/issues/14942#issuecomment-585022062).

**Comment by NestorBurma1** [comment]
I have problems deteced by flutter doctor with a plugins and android-studio-dir and android-sdk path. 
I just clear path to android-studio-dir and android-sdk path with two flutter command:

flutter config --android-studio-dir=""
flutter config --android-sdk=""

After that I restarted Android Studio.

**Comment by mingdongtu** [comment]
> I found an alternative way to fix this issue. You can just install the Flutter and Dart plugin in android studio by following these steps:
> 1.) Start the Android Studio application
> 2.) Open plugin preferences (Preferences>Plugins on macOS, File>Settings>Plugins on Windows & Linux).
> 3.) Select Browse repositories…, select the Flutter plug-in and click install .
> 4.) Click Yes when prompted to install the Dart plugin.
> 5.) Click Restart when prompted.

thank you very much!

**Comment by dpmccabe** [comment]
I'm trying to set up flutter with intellij (I'm not doing any android dev):

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[!] Android Studio (not installed)
[!] IntelliJ IDEA Ultimate Edition (version 2020.1.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.

[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.
```

The plugins are clearly installed, though:
![Screen Shot 2020-07-08 at 6 27 41 PM](https://user-images.githubusercontent.com/527578/86976563-bb282d80-c148-11ea-9b0a-b131ac62af05.png)
![Screen Shot 2020-07-08 at 6 27 44 PM](https://user-images.githubusercontent.com/527578/86976572-c0857800-c148-11ea-883b-5066cf88f6da.png)

I've tried uninstalling and reinstalling the flutter plugin from within intellij and also restarting my computer. No dice.

**Comment by dpmccabe** [comment]
Never mind, switched to master branch at commit 80b5ee4e7c54875ccc70ca7c1b5510b7399b4fc2 and it works now.

**Comment by steshine** [comment]
this my case , it works now .
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.17.5 at /Library/flutter
    • Framework revision 8af6b2f038 (10 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Library/android_sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Library/android_sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

**beause** before  IntelliJ IDEA version 2020.1.2 ,plugin path was /$USER_HOME/Library/Application Support/IntelliJIdea2020.1 
but in version 2020.1.2 ,it change to /$USER_HOME/Library/Application Support/JetBrains/IntelliJIdea2020.1/plugins .

this code show how get pluginsPath on Mac OS. this at https://github.com/flutter/flutter/blob/6c408a05677139a8fdf79f0d433cc85147d22a3c/packages/flutter_tools/lib/src/doctor.dart

`String get pluginsPath {
    if (_pluginsPath != null) {
      return _pluginsPath;
    }

    final String altLocation = globals.plistParser
      .getValueFromFile(plistFile, 'JetBrainsToolboxApp');

    if (altLocation != null) {
      _pluginsPath = altLocation + '.plugins';
      return _pluginsPath;
    }

    final List<String> split = version.split('.');

    if (split.length < 2) {
      return null;
    }

    final String major = split[0];
    final String minor = split[1];
    _pluginsPath = globals.fs.path.join(
      globals.fsUtils.homeDirPath,
      'Library',
      'Application Support',
      '$id$major.$minor',
    );
    return _pluginsPath;
  }
  String _pluginsPath;
}`

but ! in flutter 1.17.5 stable version. it still use old plugin path.so not found.

so you can copy plugins file to old path ,it works!

**Comment by kunalpohakar** [comment]
Snehal@DESKTOP-5C73N1D MINGW64 ~/AndroidStudioProjects/web_work
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.19041.572], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.50.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.



 i am having this issues in android studio and i already installed plugins but i don't no why this issues is come up

**Comment by i6x86** [comment]
Same issue here:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale es-ES)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
 
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by Shiba-Kar** [comment]
Ok apparently Android Studio 4.1 stable by default creates ```.AndroidStudio4.1``` file @ ```C:\Users\<UserName>\AppData\Roaming\Google\AndroidStudio4.1```. The solution is to copy the folder and place it @ ```/<UserName>/.AndroidStudio4.1```.

**Comment by duongp131994** [comment]
I had problems installing Flutter vs android studio,
[!] Android Studio (version 4.1.0)
X Flutter plugin not installed; this adds Flutter specific functionality.
X Dart plugin not installed; this adds Dart specific functionality.
but, I follow the instructions at: https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#ways-to-fix
it really works

**Comment by fkomaralp** [comment]
Flutter's flutter and dart Android Studio 4.1 plugins are not not found by flutter. You need to switch to flutter dev with `flutter channel dev` command. And after that you need to run `flutter doctor`. Results are like that.

```
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 073263e39d1d12313c9622ac3788cc9f2b01f582...
Building flutter tool...
Running pub upgrade...
Downloading package sky_engine...                                  689ms
Downloading flutter_patched_sdk tools...                            4,3s
Downloading flutter_patched_sdk_product tools...                    4,4s
Downloading windows-x64 tools...                                    9,1s
Downloading windows-x64/font-subset tools...                     1.223ms
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.24.0-7.0.pre, on Microsoft Windows [Version 10.0.19042.572], locale tr-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Android Studio (version 4.1.0)
[✓] VS Code (version 1.51.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

But before all of this, you need to install flutter and dart plugins for Android Studio.

**Comment by serdarpolat** [comment]
change channel master to dev. then upgrade.

```
flutter channel dev
flutter channel upgrade
```

try again

`flutter doctor`

Note: I think it's Android Studio 4.1 issue...

**Comment by vmihda** [comment]
I had the same problem. Run the commands:
```flutter channel dev
flutter doctor
flutter channel master
flutter doctor```

**Comment by ItsCosmas** [comment]
> I had the same problem. Run the commands:
> 
> ```
> flutter channel dev
> flutter doctor
> flutter channel master
> flutter doctor
> ```
> 
> Don't forget to install Dart and Flutter plugins for Android Studio.

This worked like a charm

**Comment by Brackleycassinga** [comment]
This is a quick solution if your android studio cannot find the path :
Just got to the terminal and run flutter create nameofnewApp
then flutter run.After this, you should be able to run your app and find flutter with flutter doctor

**Comment by cikichen** [comment]
> I had the same problem. Run the commands:
> 
> ```
> flutter channel dev
> flutter doctor
> flutter channel master
> flutter doctor
> ```
> 
> Don't forget to install Dart and Flutter plugins for Android Studio.

```
flutter channel stable
flutter doctor
```

```
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.0.1 20B29 darwin-arm, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
[✓] VS Code (version 1.52.0)
[!] Proxy Configuration
    ! NO_PROXY is not set
[✓] Connected device (1 available)
```

**Comment by fluttercorner1** [comment]
Here Is All Possible Solution added [[Solved] Flutter plugin not installed error. When running flutter doctor](https://fluttercorner.com/flutter-plugin-not-installed-error-when-running-flutter-doctor/)

**Comment by koushikromel** [comment]
> I found an alternative way to fix this issue. You can just install the Flutter and Dart plugin in android studio by following these steps:
> 1.) Start the Android Studio application
> 2.) Open plugin preferences (Preferences>Plugins on macOS, File>Settings>Plugins on Windows & Linux).
> 3.) Select Browse repositories…, select the Flutter plug-in and click install .
> 4.) Click Yes when prompted to install the Dart plugin.
> 5.) Click Restart when prompted.

is this will work for linux also!!? @bradh43

**Comment by ChaminduWeerasinghe** [comment]
If you are Linux User, [https://stackoverflow.com/a/64953024](try this)
it works for me

**Comment by huzaifa18** [comment]
I solved this issue by simply updating the Dart and Flutter plugins!
![image](https://user-images.githubusercontent.com/29542625/103410253-6233d200-4b8c-11eb-8736-edf70f94a08a.png)

**Comment by DyaryRaoof** [comment]
I have downgraded to android studio 3.6.3, still the same issue

**Comment by DyaryRaoof** [comment]
> I had the same problem. Run the commands:
> 
> ```
> flutter channel dev
> flutter doctor
> flutter channel master
> flutter doctor
> ```
> 
> Don't forget to install Dart and Flutter plugins for Android Studio.

what if you don't want to work on unstable dev channel ?

**Comment by ashishoffice** [comment]
✗ Flutter plugin not installed; this adds Flutter specific functionality.
✗ Dart plugin not installed; this adds Dart specific functionality.


Flutter 1.22.5 stable version issue

**Comment by sudakoff** [comment]
I fix this problem

step1 : run> flutter channel dev
step2 : run> flutter channel updrade
step3 : run > flutter config --android-studio-dir="C:\Program Files\Android\Android Studio"

**Comment by prajchavadihere** [comment]
> Before
> ```
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19042.572], locale tr-TR)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
> [!] Android Studio (version 4.1.0)
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
> [✓] VS Code (version 1.51.1)
>     ! No devices available
> ```
> 
> Flutter's flutter and dart Android Studio 4.1 plugins are not not found by flutter. You need to switch to flutter dev with `flutter channel dev` command. And after that you need to run `flutter doctor`. Results are like that.
> 
> ```
> Checking Dart SDK version...
> Downloading Dart SDK from Flutter engine 073263e39d1d12313c9622ac3788cc9f2b01f582...
> Building flutter tool...
> Running pub upgrade...
> Downloading package sky_engine...                                  689ms
> Downloading flutter_patched_sdk tools...                            4,3s
> Downloading flutter_patched_sdk_product tools...                    4,4s
> Downloading windows-x64 tools...                                    9,1s
> Downloading windows-x64/font-subset tools...                     1.223ms
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel dev, 1.24.0-7.0.pre, on Microsoft Windows [Version 10.0.19042.572], locale tr-TR)
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
> [✓] Android Studio (version 4.1.0)
> [✓] VS Code (version 1.51.1)
> [!] Connected device
>     ! No devices available
> 
> ! Doctor found issues in 1 category.
> ```
> 
> But before all of this, you need to install flutter and dart plugins for Android Studio.

Thanks for this... Really helpful 😃

**Comment by kayo-chan** [comment]
> > I had the same problem. Run the commands:
> > ```
> > flutter channel dev
> > flutter doctor
> > flutter channel master
> > flutter doctor
> > ```
> > 
> > 
> > Don't forget to install Dart and Flutter plugins for Android Studio.
> 
> This worked like a charm

This really works! No stress!!

**Comment by tehsunnliu** [comment]
I wonder why it works on dev and not in stable?

**Comment by saifamer2030** [comment]
try this line of code, worked for me

ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1

**Comment by saifamer2030** [comment]
try this line of code, worked for me

`ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`

**Comment by kevintao0417** [comment]
> 中国的老哥无论是否翻墙都要配置国内镜像，否则common tools下载不成功

配置了还是不行啊……

**Comment by erperejildo** [comment]
> change channel master to dev. then upgrade.
> 
> ```
> flutter channel dev
> flutter channel upgrade
> ```
> 
> try again
> 
> `flutter doctor`
> 
> Note: I think it's Android Studio 4.1 issue...

this worked for me

**Comment by Mereep** [comment]
Same problem. Installed in alll-standard settings on fresh Mac. The plugins are both not recognized in current stable flutter.

**Comment by eerbee** [comment]
yes mine solved by switching to the dev channel, but why it cant work on stable channel?

**Comment by DyaryRaoof** [comment]
Just change yo the dev channel and that is it

**Comment by zjamshidi** [comment]
> I had the same problem. Run the commands:
> 
> ```
> flutter channel dev
> flutter doctor
> flutter channel master
> flutter doctor
> ```
> 
> Don't forget to install Dart and Flutter plugins for Android Studio.

It works for me, too. Thanks a tone

**Comment by tanveersalmangkn** [comment]
I tried all of this but none worked for me. What I did was super easy and cool
I just run the command **flutter clean** and  `flutter run`
and it worked like a charm :)

**Comment by gustiprp** [comment]
> change channel master to dev. then upgrade.
> 
> ```
> flutter channel dev
> flutter channel upgrade
> ```
> 
> try again
> 
> `flutter doctor`
> 
> Note: I think it's Android Studio 4.1 issue...

ist work

**Comment by exeptionerror** [comment]
3 Working Solution Added [Flutter plugin not installed error. When running flutter doctor](https://fluttercorner.com/flutter-plugin-not-installed-error-when-running-flutter-doctor/)

**Comment by cjxonix** [comment]
> try this line of code, worked for me
> 
> `ln -s ~/Library/Application\ Support/Google/AndroidStudio4.1/plugins ~/Library/Application\ Support/AndroidStudio4.1`

Change the version of the Android studio depending on what you have, I had 4.2 so used.

`ln -s ~/Library/Application\ Support/Google/AndroidStudio4.2/plugins ~/Library/Application\ Support/AndroidStudio4.2`
