### ISSUE TITLE
Running with local engine broken?

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#11976]
## Steps to Reproduce

On a MacBook pro, execute `flutter create hello`, `cd hello`, then...

### Android device

Plug an Android device.
```
$ flutter run --local-engine android_debug_unopt
Running "flutter packages get" in hello...          0.5s
Launching lib/main.dart on Nexus 5X in debug mode...
Initializing gradle...                                0.6s
Resolving dependencies...                             0.9s
Running 'gradlew assembleDebug'...                        
VM initialization failed: Wrong full snapshot version, expected 'b09888a5ec15bcb98fb3ff93c6ece938' found '47f19879b9cac7de1b33e7b7ea414c7a'
Failed to run the Flutter compiler. Exit code: 255
```

### Android emulator

Start an Android emulator.
```
$ flutter run --local-engine android_debug_unopt_x86
No Flutter host engine build found at /Users/mravn/github/engine/src/out/host_debug_unopt_x86.
```

### iOS simulator

Start a Simulator instance.
```
$ flutter run --local-engine ios_debug_sim_unopt
No Flutter host engine build found at /Users/mravn/github/engine/src/out/host_debug_sim_unopt.
```

### iOS device

Works.

## Logs

(From Android device run)

```
$ flutter run -v --local-engine android_debug_unopt
[  +16 ms] [/Users/mravn/github/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +26 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] upstream/master
[        ] [/Users/mravn/github/flutter/] git ls-remote --get-url upstream
[   +5 ms] Exit code 0 from: git ls-remote --get-url upstream
[        ] git@github.com:flutter/flutter.git
[        ] [/Users/mravn/github/flutter/] git log -n 1 --pretty=format:%H
[   +5 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] baf3b45e0d671cd069a7ce9b235327278edb1adb
[        ] [/Users/mravn/github/flutter/] git log -n 1 --pretty=format:%ar
[   +5 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 4 days ago
[ +115 ms] /usr/bin/defaults read /Applications/Android Studio 3.0 Preview.app/Contents/Info CFBundleShortVersionString
[  +47 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio 3.0 Preview.app/Contents/Info CFBundleShortVersionString
[        ] EAP AI-171.4195411
[  +72 ms] /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[  +46 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 2.3
[  +87 ms] Listing devices using /Users/mravn/Library/Android/sdk/platform-tools/adb
[        ] /Users/mravn/Library/Android/sdk/platform-tools/adb devices -l
[  +13 ms] Exit code 0 from: /Users/mravn/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           00bff34682e4b2ab       device usb:337707008X product:bullhead model:Nexus_5X device:bullhead
[   +7 ms] idevice_id -h
[ +123 ms] /usr/bin/xcrun simctl list --json devices
[ +100 ms] /Users/mravn/Library/Android/sdk/platform-tools/adb -s 00bff34682e4b2ab shell getprop
[  +87 ms] ro.hardware = bullhead
[        ] ro.build.characteristics = nosdcard
[ +485 ms] Launching lib/main.dart on Nexus 5X in debug mode...
[   +4 ms] Initializing gradle...
[   +5 ms] Using gradle from /Users/mravn/apps/anarchy/android/gradlew.
[  +70 ms] /Users/mravn/apps/anarchy/android/gradlew -v
[ +529 ms] 
                   ------------------------------------------------------------
                   Gradle 3.3
                   ------------------------------------------------------------
                   
                   Build time:   2017-01-03 15:31:04 UTC
                   Revision:     075893a3d0798c0c1f322899b41ceca82e4e134b
                   
                   Groovy:       2.4.7
                   Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
                   JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b01)
                   OS:           Mac OS X 10.12.6 x86_64
[   +1 ms] Resolving dependencies...
[        ] [android/] /Users/mravn/apps/anarchy/android/gradlew app:properties
[ +848 ms] NDK is missing a "platforms" directory.
                   If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /Users/mravn/Library/Android/sdk/ndk-bundle.
                   If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.
                   
                   Incremental java compilation is an incubating feature.
                   :app:properties
                   
                   ------------------------------------------------------------
                   Project :app
                   ------------------------------------------------------------
                   
                   allprojects: [project ':app']
                   android: com.android.build.gradle.AppExtension_Decorated@476c3b04
                   androidDependencies: task ':app:androidDependencies'
                   ant: org.gradle.api.internal.project.DefaultAntBuilder@8d365f1
                   antBuilderFactory: org.gradle.api.internal.project.DefaultAntBuilderFactory@44d88a9a
                   archivesBaseName: app
                   artifacts: org.gradle.api.internal.artifacts.dsl.DefaultArtifactHandler_Decorated@6cf69abd
                   asDynamicObject: DynamicObject for project ':app'
                   assemble: task ':app:assemble'
                   assembleAndroidTest: task ':app:assembleAndroidTest'
                   assembleDebug: task ':app:assembleDebug'
                   assembleDebugAndroidTest: task ':app:assembleDebugAndroidTest'
                   assembleDebugUnitTest: task ':app:assembleDebugUnitTest'
                   assembleProfile: task ':app:assembleProfile'
                   assembleProfileUnitTest: task ':app:assembleProfileUnitTest'
                   assembleRelease: task ':app:assembleRelease'
                   assembleReleaseUnitTest: task ':app:assembleReleaseUnitTest'
                   attributesSchema: org.gradle.api.internal.attributes.DefaultAttributesSchema_Decorated@4ae4383c
                   baseClassLoaderScope: org.gradle.api.internal.initialization.DefaultClassLoaderScope@590b307c
                   buildDependents: task ':app:buildDependents'
                   buildDir: /Users/mravn/apps/anarchy/build/app
                   buildFile: /Users/mravn/apps/anarchy/android/app/build.gradle
                   buildNeeded: task ':app:buildNeeded'
                   buildScriptSource: org.gradle.groovy.scripts.UriScriptSource@5987fd9d
                   buildscript: org.gradle.api.internal.initialization.DefaultScriptHandler@17cb762
                   check: task ':app:check'
                   checkDebugManifest: task ':app:checkDebugManifest'
                   checkProfileManifest: task ':app:checkProfileManifest'
                   checkReleaseManifest: task ':app:checkReleaseManifest'
                   childProjects: {}
                   class: class org.gradle.api.internal.project.DefaultProject_Decorated
                   classLoaderScope: org.gradle.api.internal.initialization.DefaultClassLoaderScope@6ab24aa9
                   cleanBuildCache: task ':app:cleanBuildCache'
                   compileDebugAidl: task ':app:compileDebugAidl'
                   compileDebugAndroidTestAidl: task ':app:compileDebugAndroidTestAidl'
                   compileDebugAndroidTestJavaWithJavac: task ':app:compileDebugAndroidTestJavaWithJavac'
                   compileDebugAndroidTestNdk: task ':app:compileDebugAndroidTestNdk'
                   compileDebugAndroidTestRenderscript: task ':app:compileDebugAndroidTestRenderscript'
                   compileDebugAndroidTestShaders: task ':app:compileDebugAndroidTestShaders'
                   compileDebugAndroidTestSources: task ':app:compileDebugAndroidTestSources'
                   compileDebugJavaWithJavac: task ':app:compileDebugJavaWithJavac'
                   compileDebugNdk: task ':app:compileDebugNdk'
                   compileDebugRenderscript: task ':app:compileDebugRenderscript'
                   compileDebugShaders: task ':app:compileDebugShaders'
                   compileDebugSources: task ':app:compileDebugSources'
                   compileDebugUnitTestJavaWithJavac: task ':app:compileDebugUnitTestJavaWithJavac'
                   compileDebugUnitTestSources: task ':app:compileDebugUnitTestSources'
                   compileLint: task ':app:compileLint'
                   compileProfileAidl: task ':app:compileProfileAidl'
                   compileProfileJavaWithJavac: task ':app:compileProfileJavaWithJavac'
                   compileProfileNdk: task ':app:compileProfileNdk'
                   compileProfileRenderscript: task ':app:compileProfileRenderscript'
                   compileProfileShaders: task ':app:compileProfileShaders'
                   compileProfileSources: task ':app:compileProfileSources'
                   compileProfileUnitTestJavaWithJavac: task ':app:compileProfileUnitTestJavaWithJavac'
                   compileProfileUnitTestSources: task ':app:compileProfileUnitTestSources'
                   compileReleaseAidl: task ':app:compileReleaseAidl'
                   compileReleaseJavaWithJavac: task ':app:compileReleaseJavaWithJavac'
                   compileReleaseNdk: task ':app:compileReleaseNdk'
                   compileReleaseRenderscript: task ':app:compileReleaseRenderscript'
                   compileReleaseShaders: task ':app:compileReleaseShaders'
                   compileReleaseSources: task ':app:compileReleaseSources'
                   compileReleaseUnitTestJavaWithJavac: task ':app:compileReleaseUnitTestJavaWithJavac'
                   compileReleaseUnitTestSources: task ':app:compileReleaseUnitTestSources'
                   components: []
                   configurationActions: org.gradle.configuration.project.DefaultProjectConfigurationActionContainer@6aba0f53
                   configurations: [configuration ':app:_debugAndroidTestAnnotationProcessor', configuration ':app:_debugAndroidTestApk', configuration ':app:_debugAndroidTestCompile', configuration ':app:_debugAndroidTestJackPlugin', configuration ':app:_debugAnnotationProcessor', configuration ':app:_debugApk', configuration ':app:_debugCompile', configuration ':app:_debugJackPlugin', configuration ':app:_debugUnitTestAnnotationProcessor', configuration ':app:_debugUnitTestApk', configuration ':app:_debugUnitTestCompile', configuration ':app:_debugUnitTestJackPlugin', configuration ':app:_profileAnnotationProcessor', configuration ':app:_profileApk', configuration ':app:_profileCompile', configuration ':app:_profileJackPlugin', configuration ':app:_profileUnitTestAnnotationProcessor', configuration ':app:_profileUnitTestApk', configuration ':app:_profileUnitTestCompile', configuration ':app:_profileUnitTestJackPlugin', configuration ':app:_releaseAnnotationProcessor', configuration ':app:_releaseApk', configuration ':app:_releaseCompile', configuration ':app:_releaseJackPlugin', configuration ':app:_releaseUnitTestAnnotationProcessor', configuration ':app:_releaseUnitTestApk', configuration ':app:_releaseUnitTestCompile', configuration ':app:_releaseUnitTestJackPlugin', configuration ':app:androidJacocoAgent', configuration ':app:androidJacocoAnt', configuration ':app:androidTestAnnotationProcessor', configuration ':app:androidTestApk', configuration ':app:androidTestCompile', configuration ':app:androidTestJackPlugin', configuration ':app:androidTestProvided', configuration ':app:androidTestWearApp', configuration ':app:annotationProcessor', configuration ':app:apk', configuration ':app:archives', configuration ':app:compile', configuration ':app:debugAnnotationProcessor', configuration ':app:debugApk', configuration ':app:debugCompile', configuration ':app:debugJackPlugin', configuration ':app:debugProvided', configuration ':app:debugWearApp', configuration ':app:default', configuration ':app:default-mapping', configuration ':app:default-metadata', configuration ':app:jackPlugin', configuration ':app:profileAnnotationProcessor', configuration ':app:profileApk', configuration ':app:profileCompile', configuration ':app:profileJackPlugin', configuration ':app:profileProvided', configuration ':app:profileWearApp', configuration ':app:provided', configuration ':app:releaseAnnotationProcessor', configuration ':app:releaseApk', configuration ':app:releaseCompile', configuration ':app:releaseJackPlugin', configuration ':app:releaseProvided', configuration ':app:releaseWearApp', configuration ':app:testAnnotationProcessor', configuration ':app:testApk', configuration ':app:testCompile', configuration ':app:testDebugAnnotationProcessor', configuration ':app:testDebugApk', configuration ':app:testDebugCompile', configuration ':app:testDebugJackPlugin', configuration ':app:testDebugProvided', configuration ':app:testDebugWearApp', configuration ':app:testJackPlugin', configuration ':app:testProfileAnnotationProcessor', configuration ':app:testProfileApk', configuration ':app:testProfileCompile', configuration ':app:testProfileJackPlugin', configuration ':app:testProfileProvided', configuration ':app:testProfileWearApp', configuration ':app:testProvided', configuration ':app:testReleaseAnnotationProcessor', configuration ':app:testReleaseApk', configuration ':app:testReleaseCompile', configuration ':app:testReleaseJackPlugin', configuration ':app:testReleaseProvided', configuration ':app:testReleaseWearApp', configuration ':app:testWearApp', configuration ':app:wearApp']
                   connectedAndroidTest: task ':app:connectedAndroidTest'
                   connectedCheck: task ':app:connectedCheck'
                   connectedDebugAndroidTest: task ':app:connectedDebugAndroidTest'
                   convention: org.gradle.api.internal.plugins.DefaultConvention@c377c8c
                   copyFlutterAssetsDebug: task ':app:copyFlutterAssetsDebug'
                   copyFlutterAssetsProfile: task ':app:copyFlutterAssetsProfile'
                   copyFlutterAssetsRelease: task ':app:copyFlutterAssetsRelease'
                   defaultArtifacts: org.gradle.api.internal.plugins.DefaultArtifactPublicationSet_Decorated@68140dcf
                   defaultTasks: []
                   deferredProjectConfiguration: org.gradle.api.internal.project.DeferredProjectConfiguration@108be566
                   dependencies: org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@2af1b0b3
                   dependencyCacheDir: /Users/mravn/apps/anarchy/build/app/dependency-cache
                   dependencyCacheDirName: dependency-cache
                   depth: 1
                   description: null
                   deviceAndroidTest: task ':app:deviceAndroidTest'
                   deviceCheck: task ':app:deviceCheck'
                   displayName: project ':app'
                   distsDir: /Users/mravn/apps/anarchy/build/app/distributions
                   distsDirName: distributions
                   docsDir: /Users/mravn/apps/anarchy/build/app/docs
                   docsDirName: docs
                   ext: org.gradle.api.internal.plugins.DefaultExtraPropertiesExtension@1d156a7d
                   extensions: org.gradle.api.internal.plugins.DefaultConvention@c377c8c
                   extractProguardFiles: task ':app:extractProguardFiles'
                   fileOperations: org.gradle.api.internal.file.DefaultFileOperations@55a77665
                   fileResolver: org.gradle.api.internal.file.BaseDirFileResolver@1a480962
                   flutter: FlutterExtension_Decorated@3d1b56b0
                   flutterBuildDebug: task ':app:flutterBuildDebug'
                   flutterBuildProfile: task ':app:flutterBuildProfile'
                   flutterBuildRelease: task ':app:flutterBuildRelease'
                   flutterBuildX86Jar: task ':app:flutterBuildX86Jar'
                   flutterDependenciesDebug: task ':app:flutterDependenciesDebug'
                   flutterDependenciesProfile: task ':app:flutterDependenciesProfile'
                   flutterDependenciesRelease: task ':app:flutterDependenciesRelease'
                   generateDebugAndroidTestAssets: task ':app:generateDebugAndroidTestAssets'
                   generateDebugAndroidTestBuildConfig: task ':app:generateDebugAndroidTestBuildConfig'
                   generateDebugAndroidTestResValues: task ':app:generateDebugAndroidTestResValues'
                   generateDebugAndroidTestResources: task ':app:generateDebugAndroidTestResources'
                   generateDebugAndroidTestSources: task ':app:generateDebugAndroidTestSources'
                   generateDebugAssets: task ':app:generateDebugAssets'
                   generateDebugBuildConfig: task ':app:generateDebugBuildConfig'
                   generateDebugResValues: task ':app:generateDebugResValues'
                   generateDebugResources: task ':app:generateDebugResources'
                   generateDebugSources: task ':app:generateDebugSources'
                   generateProfileAssets: task ':app:generateProfileAssets'
                   generateProfileBuildConfig: task ':app:generateProfileBuildConfig'
                   generateProfileResValues: task ':app:generateProfileResValues'
                   generateProfileResources: task ':app:generateProfileResources'
                   generateProfileSources: task ':app:generateProfileSources'
                   generateReleaseAssets: task ':app:generateReleaseAssets'
                   generateReleaseBuildConfig: task ':app:generateReleaseBuildConfig'
                   generateReleaseResValues: task ':app:generateReleaseResValues'
                   generateReleaseResources: task ':app:generateReleaseResources'
                   generateReleaseSources: task ':app:generateReleaseSources'
                   gradle: build 'android'
                   group: android
                   identityPath: :app
                   incrementalDebugAndroidTestJavaCompilationSafeguard: task ':app:incrementalDebugAndroidTestJavaCompilationSafeguard'
                   incrementalDebugJavaCompilationSafeguard: task ':app:incrementalDebugJavaCompilationSafeguard'
                   incrementalDebugUnitTestJavaCompilationSafeguard: task ':app:incrementalDebugUnitTestJavaCompilationSafeguard'
                   incrementalProfileJavaCompilationSafeguard: task ':app:incrementalProfileJavaCompilationSafeguard'
                   incrementalProfileUnitTestJavaCompilationSafeguard: task ':app:incrementalProfileUnitTestJavaCompilationSafeguard'
                   incrementalReleaseJavaCompilationSafeguard: task ':app:incrementalReleaseJavaCompilationSafeguard'
                   incrementalReleaseUnitTestJavaCompilationSafeguard: task ':app:incrementalReleaseUnitTestJavaCompilationSafeguard'
                   inheritedScope: org.gradle.api.internal.ExtensibleDynamicObject$InheritedDynamicObject@b6b95ec
                   installDebug: task ':app:installDebug'
                   installDebugAndroidTest: task ':app:installDebugAndroidTest'
                   installProfile: task ':app:installProfile'
                   installRelease: task ':app:installRelease'
                   jarDebugClasses: task ':app:jarDebugClasses'
                   jarProfileClasses: task ':app:jarProfileClasses'
                   jarReleaseClasses: task ':app:jarReleaseClasses'
                   javaPreCompileDebug: task ':app:javaPreCompileDebug'
                   javaPreCompileDebugAndroidTest: task ':app:javaPreCompileDebugAndroidTest'
                   javaPreCompileDebugUnitTest: task ':app:javaPreCompileDebugUnitTest'
                   javaPreCompileProfile: task ':app:javaPreCompileProfile'
                   javaPreCompileProfileUnitTest: task ':app:javaPreCompileProfileUnitTest'
                   javaPreCompileRelease: task ':app:javaPreCompileRelease'
                   javaPreCompileReleaseUnitTest: task ':app:javaPreCompileReleaseUnitTest'
                   libsDir: /Users/mravn/apps/anarchy/build/app/libs
                   libsDirName: libs
                   lint: task ':app:lint'
                   lintDebug: task ':app:lintDebug'
                   lintProfile: task ':app:lintProfile'
                   lintRelease: task ':app:lintRelease'
                   lintVitalRelease: task ':app:lintVitalRelease'
                   logger: org.gradle.internal.logging.slf4j.OutputEventListenerBackedLogger@30a1bf75
                   logging: org.gradle.internal.logging.services.DefaultLoggingManager@6511deba
                   mergeDebugAndroidTestAssets: task ':app:mergeDebugAndroidTestAssets'
                   mergeDebugAndroidTestJniLibFolders: task ':app:mergeDebugAndroidTestJniLibFolders'
                   mergeDebugAndroidTestResources: task ':app:mergeDebugAndroidTestResources'
                   mergeDebugAndroidTestShaders: task ':app:mergeDebugAndroidTestShaders'
                   mergeDebugAssets: task ':app:mergeDebugAssets'
                   mergeDebugJniLibFolders: task ':app:mergeDebugJniLibFolders'
                   mergeDebugResources: task ':app:mergeDebugResources'
                   mergeDebugShaders: task ':app:mergeDebugShaders'
                   mergeProfileAssets: task ':app:mergeProfileAssets'
                   mergeProfileJniLibFolders: task ':app:mergeProfileJniLibFolders'
                   mergeProfileResources: task ':app:mergeProfileResources'
                   mergeProfileShaders: task ':app:mergeProfileShaders'
                   mergeReleaseAssets: task ':app:mergeReleaseAssets'
                   mergeReleaseJniLibFolders: task ':app:mergeReleaseJniLibFolders'
                   mergeReleaseResources: task ':app:mergeReleaseResources'
                   mergeReleaseShaders: task ':app:mergeReleaseShaders'
                   mockableAndroidJar: task ':app:mockableAndroidJar'
                   modelRegistry: org.gradle.model.internal.registry.DefaultModelRegistry@3f48c863
                   modelSchemaStore: org.gradle.model.internal.manage.schema.extract.DefaultModelSchemaStore@2d8f4d9a
                   module: org.gradle.api.internal.artifacts.ProjectBackedModule@72bf658
                   name: app
                   org.gradle.jvmargs: -Xmx1536M
                   packageDebug: task ':app:packageDebug'
                   packageDebugAndroidTest: task ':app:packageDebugAndroidTest'
                   packageProfile: task ':app:packageProfile'
                   packageRelease: task ':app:packageRelease'
                   parent: root project 'android'
                   parentIdentifier: root project 'android'
                   path: :app
                   pluginManager: org.gradle.api.internal.plugins.DefaultPluginManager_Decorated@5801b7ec
                   plugins: [org.gradle.api.plugins.HelpTasksPlugin@66e7535e, org.gradle.language.base.plugins.LifecycleBasePlugin@50735481, org.gradle.api.plugins.BasePlugin@dd435a5, org.gradle.api.plugins.ReportingBasePlugin@315458a3, org.gradle.platform.base.plugins.ComponentBasePlugin@640e152e, org.gradle.language.base.plugins.LanguageBasePlugin@770cd84c, org.gradle.platform.base.plugins.BinaryBasePlugin@48980793, org.gradle.api.plugins.JavaBasePlugin@3b5dc309, com.android.build.gradle.internal.coverage.JacocoPlugin@406c242, com.android.build.gradle.AppPlugin@22e51cf3, FlutterPlugin@733df5e3]
                   preBuild: task ':app:preBuild'
                   preDebugAndroidTestBuild: task ':app:preDebugAndroidTestBuild'
                   preDebugBuild: task ':app:preDebugBuild'
                   preDebugUnitTestBuild: task ':app:preDebugUnitTestBuild'
                   preProfileBuild: task ':app:preProfileBuild'
                   preProfileUnitTestBuild: task ':app:preProfileUnitTestBuild'
                   preReleaseBuild: task ':app:preReleaseBuild'
                   preReleaseUnitTestBuild: task ':app:preReleaseUnitTestBuild'
                   prepareComAndroidSupportTestExposedInstrumentationApiPublish05Library: task ':app:prepareComAndroidSupportTestExposedInstrumentationApiPublish05Library'
                   prepareComAndroidSupportTestRules05Library: task ':app:prepareComAndroidSupportTestRules05Library'
                   prepareComAndroidSupportTestRunner05Library: task ':app:prepareComAndroidSupportTestRunner05Library'
                   prepareDebugAndroidTestDependencies: task ':app:prepareDebugAndroidTestDependencies'
                   prepareDebugDependencies: task ':app:prepareDebugDependencies'
                   prepareDebugUnitTestDependencies: task ':app:prepareDebugUnitTestDependencies'
                   prepareProfileDependencies: task ':app:prepareProfileDependencies'
                   prepareProfileUnitTestDependencies: task ':app:prepareProfileUnitTestDependencies'
                   prepareReleaseDependencies: task ':app:prepareReleaseDependencies'
                   prepareReleaseUnitTestDependencies: task ':app:prepareReleaseUnitTestDependencies'
                   processDebugAndroidTestJavaRes: task ':app:processDebugAndroidTestJavaRes'
                   processDebugAndroidTestManifest: task ':app:processDebugAndroidTestManifest'
                   processDebugAndroidTestResources: task ':app:processDebugAndroidTestResources'
                   processDebugJavaRes: task ':app:processDebugJavaRes'
                   processDebugManifest: task ':app:processDebugManifest'
                   processDebugResources: task ':app:processDebugResources'
                   processDebugUnitTestJavaRes: task ':app:processDebugUnitTestJavaRes'
                   processOperations: org.gradle.api.internal.file.DefaultFileOperations@55a77665
                   processProfileJavaRes: task ':app:processProfileJavaRes'
                   processProfileManifest: task ':app:processProfileManifest'
                   processProfileResources: task ':app:processProfileResources'
                   processProfileUnitTestJavaRes: task ':app:processProfileUnitTestJavaRes'
                   processReleaseJavaRes: task ':app:processReleaseJavaRes'
                   processReleaseManifest: task ':app:processReleaseManifest'
                   processReleaseResources: task ':app:processReleaseResources'
                   processReleaseUnitTestJavaRes: task ':app:processReleaseUnitTestJavaRes'
                   project: project ':app'
                   projectDir: /Users/mravn/apps/anarchy/android/app
                   projectEvaluationBroadcaster: ProjectEvaluationListener broadcast
                   projectEvaluator: org.gradle.configuration.project.LifecycleProjectEvaluator@f929df5
                   projectPath: :app
                   projectRegistry: org.gradle.api.internal.project.DefaultProjectRegistry@649d66b3
                   properties: {...}
                   reporting: org.gradle.api.reporting.ReportingExtension_Decorated@1defb193
                   reportsDir: /Users/mravn/apps/anarchy/build/app/reports
                   repositories: [org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository_Decorated@4884db15, org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository_Decorated@53e28ac5, org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository_Decorated@5cc5c6f4, org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository_Decorated@3cc687d6, org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository_Decorated@5274af28]
                   resources: org.gradle.api.internal.resources.DefaultResourceHandler@1507a301
                   rootDir: /Users/mravn/apps/anarchy/android
                   rootProject: root project 'android'
                   scriptHandlerFactory: org.gradle.api.internal.initialization.DefaultScriptHandlerFactory@67873533
                   scriptPluginFactory: org.gradle.configuration.ScriptPluginFactorySelector@6f77f622
                   serviceRegistryFactory: org.gradle.internal.service.scopes.ProjectScopeServices$4@180d190b
                   services: ProjectScopeServices
                   signingReport: task ':app:signingReport'
                   sourceCompatibility: 1.8
                   sourceSets: []
                   standardOutputCapture: org.gradle.internal.logging.services.DefaultLoggingManager@6511deba
                   state: project state 'EXECUTED'
                   status: integration
                   subprojects: []
                   targetCompatibility: 1.8
                   tasks: [task ':app:androidDependencies', task ':app:assemble', task ':app:assembleAndroidTest', task ':app:assembleDebug', task ':app:assembleDebugAndroidTest', task ':app:assembleDebugUnitTest', task ':app:assembleProfile', task ':app:assembleProfileUnitTest', task ':app:assembleRelease', task ':app:assembleReleaseUnitTest', task ':app:buildDependents', task ':app:buildNeeded', task ':app:check', task ':app:checkDebugManifest', task ':app:checkProfileManifest', task ':app:checkReleaseManifest', task ':app:cleanBuildCache', task ':app:compileDebugAidl', task ':app:compileDebugAndroidTestAidl', task ':app:compileDebugAndroidTestJavaWithJavac', task ':app:compileDebugAndroidTestNdk', task ':app:compileDebugAndroidTestRenderscript', task ':app:compileDebugAndroidTestShaders', task ':app:compileDebugAndroidTestSources', task ':app:compileDebugJavaWithJavac', task ':app:compileDebugNdk', task ':app:compileDebugRenderscript', task ':app:compileDebugShaders', task ':app:compileDebugSources', task ':app:compileDebugUnitTestJavaWithJavac', task ':app:compileDebugUnitTestSources', task ':app:compileLint', task ':app:compileProfileAidl', task ':app:compileProfileJavaWithJavac', task ':app:compileProfileNdk', task ':app:compileProfileRenderscript', task ':app:compileProfileShaders', task ':app:compileProfileSources', task ':app:compileProfileUnitTestJavaWithJavac', task ':app:compileProfileUnitTestSources', task ':app:compileReleaseAidl', task ':app:compileReleaseJavaWithJavac', task ':app:compileReleaseNdk', task ':app:compileReleaseRenderscript', task ':app:compileReleaseShaders', task ':app:compileReleaseSources', task ':app:compileReleaseUnitTestJavaWithJavac', task ':app:compileReleaseUnitTestSources', task ':app:connectedAndroidTest', task ':app:connectedCheck', task ':app:connectedDebugAndroidTest', task ':app:copyFlutterAssetsDebug', task ':app:copyFlutterAssetsProfile', task ':app:copyFlutterAssetsRelease', task ':app:deviceAndroidTest', task ':app:deviceCheck', task ':app:extractProguardFiles', task ':app:flutterBuildDebug', task ':app:flutterBuildProfile', task ':app:flutterBuildRelease', task ':app:flutterBuildX86Jar', task ':app:flutterDependenciesDebug', task ':app:flutterDependenciesProfile', task ':app:flutterDependenciesRelease', task ':app:generateDebugAndroidTestAssets', task ':app:generateDebugAndroidTestBuildConfig', task ':app:generateDebugAndroidTestResValues', task ':app:generateDebugAndroidTestResources', task ':app:generateDebugAndroidTestSources', task ':app:generateDebugAssets', task ':app:generateDebugBuildConfig', task ':app:generateDebugResValues', task ':app:generateDebugResources', task ':app:generateDebugSources', task ':app:generateProfileAssets', task ':app:generateProfileBuildConfig', task ':app:generateProfileResValues', task ':app:generateProfileResources', task ':app:generateProfileSources', task ':app:generateReleaseAssets', task ':app:generateReleaseBuildConfig', task ':app:generateReleaseResValues', task ':app:generateReleaseResources', task ':app:generateReleaseSources', task ':app:incrementalDebugAndroidTestJavaCompilationSafeguard', task ':app:incrementalDebugJavaCompilationSafeguard', task ':app:incrementalDebugUnitTestJavaCompilationSafeguard', task ':app:incrementalProfileJavaCompilationSafeguard', task ':app:incrementalProfileUnitTestJavaCompilationSafeguard', task ':app:incrementalReleaseJavaCompilationSafeguard', task ':app:incrementalReleaseUnitTestJavaCompilationSafeguard', task ':app:installDebug', task ':app:installDebugAndroidTest', task ':app:installProfile', task ':app:installRelease', task ':app:jarDebugClasses', task ':app:jarProfileClasses', task ':app:jarReleaseClasses', task ':app:javaPreCompileDebug', task ':app:javaPreCompileDebugAndroidTest', task ':app:javaPreCompileDebugUnitTest', task ':app:javaPreCompileProfile', task ':app:javaPreCompileProfileUnitTest', task ':app:javaPreCompileRelease', task ':app:javaPreCompileReleaseUnitTest', task ':app:lint', task ':app:lintDebug', task ':app:lintProfile', task ':app:lintRelease', task ':app:lintVitalRelease', task ':app:mergeDebugAndroidTestAssets', task ':app:mergeDebugAndroidTestJniLibFolders', task ':app:mergeDebugAndroidTestResources', task ':app:mergeDebugAndroidTestShaders', task ':app:mergeDebugAssets', task ':app:mergeDebugJniLibFolders', task ':app:mergeDebugResources', task ':app:mergeDebugShaders', task ':app:mergeProfileAssets', task ':app:mergeProfileJniLibFolders', task ':app:mergeProfileResources', task ':app:mergeProfileShaders', task ':app:mergeReleaseAssets', task ':app:mergeReleaseJniLibFolders', task ':app:mergeReleaseResources', task ':app:mergeReleaseShaders', task ':app:mockableAndroidJar', task ':app:packageDebug', task ':app:packageDebugAndroidTest', task ':app:packageProfile', task ':app:packageRelease', task ':app:preBuild', task ':app:preDebugAndroidTestBuild', task ':app:preDebugBuild', task ':app:preDebugUnitTestBuild', task ':app:preProfileBuild', task ':app:preProfileUnitTestBuild', task ':app:preReleaseBuild', task ':app:preReleaseUnitTestBuild', task ':app:prepareComAndroidSupportTestExposedInstrumentationApiPublish05Library', task ':app:prepareComAndroidSupportTestRules05Library', task ':app:prepareComAndroidSupportTestRunner05Library', task ':app:prepareDebugAndroidTestDependencies', task ':app:prepareDebugDependencies', task ':app:prepareDebugUnitTestDependencies', task ':app:prepareProfileDependencies', task ':app:prepareProfileUnitTestDependencies', task ':app:prepareReleaseDependencies', task ':app:prepareReleaseUnitTestDependencies', task ':app:processDebugAndroidTestJavaRes', task ':app:processDebugAndroidTestManifest', task ':app:processDebugAndroidTestResources', task ':app:processDebugJavaRes', task ':app:processDebugManifest', task ':app:processDebugResources', task ':app:processDebugUnitTestJavaRes', task ':app:processProfileJavaRes', task ':app:processProfileManifest', task ':app:processProfileResources', task ':app:processProfileUnitTestJavaRes', task ':app:processReleaseJavaRes', task ':app:processReleaseManifest', task ':app:processReleaseResources', task ':app:processReleaseUnitTestJavaRes', task ':app:properties', task ':app:signingReport', task ':app:sourceSets', task ':app:test', task ':app:testDebugUnitTest', task ':app:testProfileUnitTest', task ':app:testReleaseUnitTest', task ':app:transformClassesWithDexForDebug', task ':app:transformClassesWithDexForDebugAndroidTest', task ':app:transformClassesWithDexForProfile', task ':app:transformClassesWithDexForRelease', task ':app:transformNativeLibsWithMergeJniLibsForDebug', task ':app:transformNativeLibsWithMergeJniLibsForDebugAndroidTest', task ':app:transformNativeLibsWithMergeJniLibsForProfile', task ':app:transformNativeLibsWithMergeJniLibsForRelease', task ':app:transformResourcesWithMergeJavaResForDebug', task ':app:transformResourcesWithMergeJavaResForDebugAndroidTest', task ':app:transformResourcesWithMergeJavaResForDebugUnitTest', task ':app:transformResourcesWithMergeJavaResForProfile', task ':app:transformResourcesWithMergeJavaResForProfileUnitTest', task ':app:transformResourcesWithMergeJavaResForRelease', task ':app:transformResourcesWithMergeJavaResForReleaseUnitTest', task ':app:uninstallAll', task ':app:uninstallDebug', task ':app:uninstallDebugAndroidTest', task ':app:uninstallProfile', task ':app:uninstallRelease', task ':app:validateSigningDebug', task ':app:validateSigningDebugAndroidTest', task ':app:validateSigningProfile', task ':app:validateSigningRelease']
                   test: task ':app:test'
                   testDebugUnitTest: task ':app:testDebugUnitTest'
                   testProfileUnitTest: task ':app:testProfileUnitTest'
                   testReleaseUnitTest: task ':app:testReleaseUnitTest'
                   testReportDir: /Users/mravn/apps/anarchy/build/app/reports/tests
                   testReportDirName: tests
                   testResultsDir: /Users/mravn/apps/anarchy/build/app/test-results
                   testResultsDirName: test-results
                   transformClassesWithDexForDebug: task ':app:transformClassesWithDexForDebug'
                   transformClassesWithDexForDebugAndroidTest: task ':app:transformClassesWithDexForDebugAndroidTest'
                   transformClassesWithDexForProfile: task ':app:transformClassesWithDexForProfile'
                   transformClassesWithDexForRelease: task ':app:transformClassesWithDexForRelease'
                   transformNativeLibsWithMergeJniLibsForDebug: task ':app:transformNativeLibsWithMergeJniLibsForDebug'
                   transformNativeLibsWithMergeJniLibsForDebugAndroidTest: task ':app:transformNativeLibsWithMergeJniLibsForDebugAndroidTest'
                   transformNativeLibsWithMergeJniLibsForProfile: task ':app:transformNativeLibsWithMergeJniLibsForProfile'
                   transformNativeLibsWithMergeJniLibsForRelease: task ':app:transformNativeLibsWithMergeJniLibsForRelease'
                   transformResourcesWithMergeJavaResForDebug: task ':app:transformResourcesWithMergeJavaResForDebug'
                   transformResourcesWithMergeJavaResForDebugAndroidTest: task ':app:transformResourcesWithMergeJavaResForDebugAndroidTest'
                   transformResourcesWithMergeJavaResForDebugUnitTest: task ':app:transformResourcesWithMergeJavaResForDebugUnitTest'
                   transformResourcesWithMergeJavaResForProfile: task ':app:transformResourcesWithMergeJavaResForProfile'
                   transformResourcesWithMergeJavaResForProfileUnitTest: task ':app:transformResourcesWithMergeJavaResForProfileUnitTest'
                   transformResourcesWithMergeJavaResForRelease: task ':app:transformResourcesWithMergeJavaResForRelease'
                   transformResourcesWithMergeJavaResForReleaseUnitTest: task ':app:transformResourcesWithMergeJavaResForReleaseUnitTest'
                   uninstallAll: task ':app:uninstallAll'
                   uninstallDebug: task ':app:uninstallDebug'
                   uninstallDebugAndroidTest: task ':app:uninstallDebugAndroidTest'
                   uninstallProfile: task ':app:uninstallProfile'
                   uninstallRelease: task ':app:uninstallRelease'
                   validateSigningDebug: task ':app:validateSigningDebug'
                   validateSigningDebugAndroidTest: task ':app:validateSigningDebugAndroidTest'
                   validateSigningProfile: task ':app:validateSigningProfile'
                   validateSigningRelease: task ':app:validateSigningRelease'
                   version: unspecified
                   
                   BUILD SUCCESSFUL
                   
                   Total time: 0.745 secs
[  +32 ms] /Users/mravn/Library/Android/sdk/platform-tools/adb -s 00bff34682e4b2ab logcat -v time -t 1
[  +96 ms] Exit code 0 from: /Users/mravn/Library/Android/sdk/platform-tools/adb -s 00bff34682e4b2ab logcat -v time -t 1
[        ] --------- beginning of system
           09-07 14:27:03.040 I/ActivityManager( 3782): Killing 10190:com.android.printspooler/u0a70 (adj 906): empty #17
[   +3 ms] /Users/mravn/Library/Android/sdk/platform-tools/adb -s 00bff34682e4b2ab logcat -v time
[   +7 ms] /Users/mravn/Library/Android/sdk/platform-tools/adb version
[  +14 ms] Android Debug Bridge version 1.0.39
           Revision 3db08f2c6889-android
           Installed as /Users/mravn/Library/Android/sdk/platform-tools/adb
[   +2 ms] /Users/mravn/Library/Android/sdk/platform-tools/adb start-server
[  +11 ms] Building APK
[ +122 ms] Running 'gradlew assembleDebug'...
[        ] Using local engine: /Users/mravn/github/engine/src/out/android_debug_unopt
[   +1 ms] [android/] /Users/mravn/apps/anarchy/android/gradlew -PlocalEngineOut=/Users/mravn/github/engine/src/out/android_debug_unopt -Ptarget=/Users/mravn/apps/anarchy/lib/main.dart assembleDebug
[ +793 ms] NDK is missing a "platforms" directory.
[        ] If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /Users/mravn/Library/Android/sdk/ndk-bundle.
[        ] If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.
[  +29 ms] Incremental java compilation is an incubating feature.
[  +42 ms] :app:preBuild UP-TO-DATE
[        ] :app:preDebugBuild UP-TO-DATE
[        ] :app:checkDebugManifest
[        ] :app:prepareDebugDependencies
[        ] :app:compileDebugAidl UP-TO-DATE
[   +1 ms] :app:compileDebugRenderscript UP-TO-DATE
[   +3 ms] :app:generateDebugBuildConfig UP-TO-DATE
[ +476 ms] VM initialization failed: Wrong full snapshot version, expected 'b09888a5ec15bcb98fb3ff93c6ece938' found '47f19879b9cac7de1b33e7b7ea414c7a'
[  +19 ms] Failed to run the Flutter compiler. Exit code: 255
[  +16 ms] :app:flutterDependenciesDebug FAILED
[        ] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script '/Users/mravn/github/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 329
[        ] * What went wrong:
[        ] Execution failed for task ':app:flutterDependenciesDebug'.
[        ] > Process 'command '/Users/mravn/github/flutter/bin/flutter'' finished with non-zero exit value 255
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
[        ] BUILD FAILED
[        ] Total time: 1.303 secs
[ +426 ms] "flutter run" took 4,709ms.
Gradle build failed: 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:281)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:214)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/commands/build_apk.dart:82)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:360)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:247)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:195)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:341)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:239)
<asynchronous suspension>
#9      RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:227)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:181)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:276)
<asynchronous suspension>
#13     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#14     new Future.sync (dart:async/future.dart:222)
#15     CommandRunner.run (package:args/command_runner.dart:109)
#16     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#17     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#18     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#19     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#20     _rootRun (dart:async/zone.dart:1120)
#21     _CustomZone.run (dart:async/zone.dart:1001)
#22     runZoned (dart:async/zone.dart:1467)
#23     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#24     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#25     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#26     main (file:///Users/mravn/github/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#27     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


[  +20 ms] ensureAnalyticsSent: 16ms
[   +1 ms] exiting with code 1
```

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel master)
    • Flutter at /Users/mravn/github/flutter
    • Framework revision baf3b45e0d (4 days ago), 2017-09-02 22:27:17 -0700
    • Engine revision 29e0c1c281
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/mravn/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /Applications/Android Studio 3.0 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-884-b01)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.1

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.0 Preview.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-884-b01)

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.3)
    • Flutter plugin version 17.0
    • Dart plugin version 172.3968.27

[✓] Connected devices
    • iPhone 7 Plus • 03AC9832-B82E-4D9D-BDC8-2465D4ECC86F • ios • iOS 10.3 (simulator)
```

**Comment by mravn-google** [comment]
@aam Am I holding it wrong?

**Comment by mravn-google** [comment]
@aam It appears necessary now to create additional "host/target" combined engine builds, such as `./flutter/tools/gn --unoptimized --android-cpu x86` to get a local engine for `host_debug_unopt_x86`. Is that on purpose?

Anyway, after doing that, `flutter run` with Android emulator produces same error as with Android device:
```
$ flutter run --local-engine android_debug_unopt_x86
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                0.7s
Resolving dependencies...                             1.0s
Running 'gradlew assembleDebug'...                        
VM initialization failed: Wrong full snapshot version, expected '54dd2b5b98559a6b61b7cf5e01ccacfb' found '47f19879b9cac7de1b33e7b7ea414c7a'
Failed to run the Flutter compiler. Exit code: 255
```

**Comment by aam** [comment]
What revision of flutter is this on?
Snapshot-related issues sounds similar to https://github.com/flutter/flutter/issues/11937, which was fixed few days ago.
Requirement of having host engine has been moved to only when you use `--preview-dart-2` flag few days ago too here: https://github.com/flutter/flutter/commit/59bc0a0fce781298538ab4bd557c6068f69da4a4. Yes, it is on purpose as we need to have standalone dart sdk to run frontend_server.dart app as part of the engine.

**Comment by Hixie** [comment]
We should make sure to update all the CONTRIBUTOR.md docs and so on to be clear about it.

**Comment by mravn-google** [comment]
@aam Thought I was at tip-of-tree, but wasn't. My bad. After updating past 59bc0a0, I don't get the "No Flutter host engine build found at /Users/mravn/github/engine/src/out/host_xxx" anymore, but I still get the "Wrong full snapshot version". Interestingly, that error goes away, if I include the `--preview-dart-2` flag. This is not #11937 as far as I can tell.

**Comment by aam** [comment]
@cbracken

**Comment by cbracken** [comment]
Ah my favourite bit of the code. Seems like maybe a dupe of #11977 assuming that #11977 includes the concept of engine revision (whether local or not).

**Comment by aam** [comment]
The fact that there is no error when running with `--preview-dart-2` is as expected since we don't create snapshot when running with that flag: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/flx.dart#L52. Instead of sending snapshot created on the host, we send kernel file(created with `frontend_server`) on the host.

**Comment by mravn-google** [comment]
@cbracken The error happened also following a `flutter build clean`. In fact,

* Update to tip-of-tree in local `~/github/flutter` and `~/github/engine` repos.
* `rm -rf ~/github/flutter/bin/cache`
* In `~/github/engine/src`:
  * `gclient sync`
  * `./flutter/tools gn --android --android-cpu x86 --unoptimized`
  * `ninja -C out/android_debug_unopt_x86`
* Launch Android emulator.
* In `~/apps`:
  * `flutter create hello`
* In `~/apps/hello`:
  * `flutter run --local-engine android_debug_unopt_x86`

Then I get
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                0.7s
Resolving dependencies...                             1.0s
Running 'gradlew assembleDebug'...                        
VM initialization failed: Wrong full snapshot version, expected '54dd2b5b98559a6b61b7cf5e01ccacfb' found '612403d9b12f03d4d5740731af83c312'
Failed to run the Flutter compiler. Exit code: 255

FAILURE: Build failed with an exception.

* Where:
Script '/Users/mravn/github/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 329

* What went wrong:
Execution failed for task ':app:flutterDependenciesDebug'.
> Process 'command '/Users/mravn/github/flutter/bin/flutter'' finished with non-zero exit value 255

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Gradle build failed: 1
```

**Comment by mravn-google** [comment]
@cbracken Update: In the end,  I wiped `~/github/engine/src/out` and redid the steps above. And now the error is gone 🎉

**Comment by cbracken** [comment]
> The error happened also following a flutter build clean.

Might be worth verifying that when `--local_engine` is specified that we're using the specified engine's snapshotter, rather than the default. If it's the latter, and the snapshot serialisation logic differs in the local engine and the default, I'd expect snapshot SHA mismatches like you're seeing. We should definitely check we're using the appropriate gen_snapshot.

**Comment by mravn-google** [comment]
> We should definitely check we're using the appropriate gen_snapshot.

The code appears to be OK:
* https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/build.dart#L55
* https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/artifacts.dart#L238
