### ISSUE TITLE
iOS plugin builds are *much* slower on ARM macOS than Intel macOS hosts

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#119750]
I'm attempting to convert the flutter/plugin integration tests from Intel to ARM host machines ([PR](https://github.com/flutter/plugins/pull/7066)), but they are often timing out. These same tests are currently running on Intel hosts, where the do not have this problem, but we want them to be on ARM going forward.

I originally thought that they were randomly hanging, but looking closer it seems like the problem is that they are actually just running out of time, even though the 60 minute timeout should be plenty (the Intel versions of these tests generally take about 20-35 minutes per shard, and that's with 4 shards; we increased to 5 as part of the ARM transition since that's getting to be long).

It looks like all of the Xcode steps are just taking a lot longer. For instance, compare [this Intel run](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_x64%20ios_platform_tests_4_of_4%20master/191/overview) of shard 4/4 for a PR that built all packages (the plugins repo only runs tests on changed packages most of the time, but things like rolls or CI changes run all packages) to [this ARM run](https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_arm64%20ios_platform_tests_shard_5%20master%20-%20plugins/4/overview) for shard 5/5 on an all-packages PR. They are running the same set of packages (video_player, video_player_avfoundation, webview_flutter, webview_flutter_wkwebview), except that the Intel one is also running url_launcher. Comparing some step times:

```
Build:         Intel 6.2m, ARM 25m
Xcode analyze: Intel 1.6m, ARM 9m
Native test:   Intel 6.1m, ARM 12m
```

I would expect the ARM machines to be as fast or faster, not 2-4x slower. Are these machines spec'd substantially differently?

**Comment by godofredoc** [comment]
Seems like none of the builds are using goma, is this expected?

**Comment by stuartmorgan** [comment]
Plugins are built as part of Flutter projects, so goma isn't involved.

**Comment by stuartmorgan** [comment]
Interesting, it's not all builds. I just found https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_arm64%20ios_platform_tests_shard_5%20master%20-%20plugins/3/overview which is the same shard, for anther build-all run, but has times that match Intel (and are in fact slightly faster). So it's just *sometimes* dramatically slower.

**Comment by stuartmorgan** [comment]
@godofredoc Is there a way to see bot memory? I was comparing https://chromium-swarm.appspot.com/bot?id=mac-695-g580 and https://chromium-swarm.appspot.com/bot?id=mac-348-g140 (the bots for those two runs) to see if there was an obvious difference, and I see a lot of information but nothing that was obviously memory. Having insufficient memory and thus having to swap frequently could be a cause of much slower builds.

**Comment by godofredoc** [comment]
You can see those values expanding the state button in the bot page:

![image](https://user-images.githubusercontent.com/54371434/216162947-d966b8ca-4dac-4882-89dd-e98b69b8d2ee.png)

**Comment by stuartmorgan** [comment]
Thanks. Looks like memory is the same, so that's not it. And in checking more examples I found a bot that was part of a normal run and also a slow run, so it doesn't seem to be bot-specific. Is it possible that something else is running on these machines sometimes that is fighting for resources? Can we see CPU or memory usage over time, or anything like that?

**Comment by godofredoc** [comment]
@yusuf-goog @christopherfujino I remember we disabled some services on the Chromium Mac X64 machines do you remember which services?

**Comment by godofredoc** [comment]
Maybe something related with the logging daemon?

**Comment by yusuf-goog** [comment]
I think it was the spotlight indexing service.

**Comment by christopherfujino** [comment]
not sure if it's the same as the spotlight daemon, but there's also fseventsd https://github.com/flutter/flutter/issues/88060#issuecomment-902176193

**Comment by christopherfujino** [comment]
> not sure if it's the same as the spotlight daemon, but there's also fseventsd [#88060 (comment)](https://github.com/flutter/flutter/issues/88060#issuecomment-902176193)

Looks like with that issue, it was resolved in https://bugs.chromium.org/p/chromium/issues/detail?id=1247735, by ensuring `/System/Volumes/Data/.fseventsd/no_log` exists

**Comment by yusuf-goog** [comment]
We are working on getting access to salt, after which we can make this a state. but till then, I'm just going to add the `/System/Volumes/Data/.fseventsd/no_log` file to all the new macs manually.

**Comment by godofredoc** [comment]
We'll need to open a bug to the chromium team, those machines use puppet instead of salt

**Comment by yusuf-goog** [comment]
Yup, just noticed that its on those machines as well. I'll deploy to the devicelab hosts and open a ticket to chromium for their machines.

**Comment by jmagman** [comment]
I was afraid `mac_toolchain` was maybe stripping arm64 from the Xcode bundle before uploading it as a cipd package, which would cause Xcode to run with Rosetta and therefore be slower.  However I just downloaded the package and it's not doing that, or for the simulator runtime, so one thing to rule out.

```
$ file Xcode.app/Contents/MacOS/Xcode
Xcode.app/Contents/MacOS/Xcode: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
Xcode.app/Contents/MacOS/Xcode (for architecture x86_64):	Mach-O 64-bit executable x86_64
Xcode.app/Contents/MacOS/Xcode (for architecture arm64):	Mach-O 64-bit executable arm64
```

**Comment by yusuf-goog** [comment]
Created a ticket for the chromium team: https://bugs.chromium.org/p/chromium/issues/detail?id=1412259

**Comment by jmagman** [comment]
I have links to other runs in https://github.com/flutter/flutter/issues/119764.  In the arm version here's the process info:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8790321140276300705/+/u/OS_info__2_/stdout

Here's the highest CPU processes. 

```
90775  CollectionsPoste 42.3 00:00.69 7     5    78+    77M+   0B     0B     90775 5045  sleeping *1+[3+]      0.68006  0.11211    502 21120+    4461+  290+       69+       10358+     7373+      729+      0       0       42.3  3706878565 1311993896 chrome-bot         N/A    N/A   N/A   N/A   N/A   N/A   
90774  GradientPosterEx 38.4 00:00.66 8     6    78+    73M+   0B     0B     90774 5045  sleeping *1+[3+]      0.74436  0.17545    502 20079+    4199+  290+       69+       9588+      7036+      780+      0       0       38.4  3168955291 1176923526 chrome-bot         N/A    N/A   N/A   N/A   N/A   N/A  
44196  diagnosticd      17.3 07:01.06 11    10   395+   64M    0B     48M    44196 44138 sleeping *0[1]        0.00000  0.59801    502 33294     155    386        4567130+  137258258+ 9136239+   10668521+ 66      155     17.3  1110304908 509323432  chrome-bot         N/A    N/A   N/A   N/A   N/A   N/A  
5104   diagnosticd      12.3 05:28.46 11    10   300-   55M    0B     39M    5104  5045  sleeping *0[1]        0.00000  0.35957    502 31021     155    527+       3469888+  87765522+  6941425+   7714916+  9       328     12.3  897283358  385954982  chrome-bot         N/A    N/A   N/A   N/A   N/A   N/A  
560    ReportCrash      29.6 15:38.08 10/2  3    119+   12M+   0B     976K   560   1     running  *0[1]        4.22915  21.97469   502 58880872+ 117    123253929+ 61080695+ 26124681+  111449423+ 11472572+ 75300   2       29.6  2244324906 888319746  chrome-bot         N/A    N/A   N/A   N/A   N/A   N/A  
```

 `diagnosticd` and `ReportCrash` make it seem like something crashed, which would cause the machine to slow down while it's gathering logs, etc.

What is `CollectionsPoste` and `GradientPosterEx`?

**Comment by yusuf-goog** [comment]
I have added the `/System/Volumes/Data/.fseventsd/no_log` file to all devicelab mac machines.

Chromium macs have also been checked to have the no_log file, and it should be automatic for new machines as well.

Some observations by chromium team:

1) There are 3 flavors of Macs in this collection.

Macmini7,1 (2014 Intel Macmini)
Macmini8,1 (2018 Intel Macmini)
Macmini9,1 (2020 Apple Silicon Macmini aka M1 Mini)

The RAM on these is...

Macmini7,1: 16GB
Macmini8,1: 32GB or 64GB (mostly 64)
Macmini9,1: 16GB


2) xcrun dialog is popping up sometimes: https://screenshot.googleplex.com/6UYrmJsJWqYuX4Y

3) https://luci-milo.appspot.com/ui/p/flutter/builders/try/Mac_arm64%20ios_platform_tests_shard_1%20master/36/overview

This task is looking for ruby in several places and eventually resolves to the system ruby location.

https://screenshot.googleplex.com/4zAZwGFN5KnEKwg

Ruby may be going away in a future macOS release. And in general, unless there is a solid reason to use the system installed version, ruby should be brought in just like python (i.e. cipd package). This may require working with the 3PP team to get that done.

4) Rosetta is still being installed on Apple Silicon Macs in flutter pools.

https://screenshot.googleplex.com/4HyU7M9kViNqfsM

**Comment by jmagman** [comment]
> Ruby may be going away in a future macOS release. And in general, unless there is a solid reason to use the system installed version, ruby should be brought in just like python (i.e. cipd package). This may require working with the 3PP team to get that done.

Isn't that already happening? https://github.com/flutter/flutter/issues/113231#issuecomment-1382400948

> Rosetta is still being installed on Apple Silicon Macs in flutter pools.

Flutter requires Rosetta, see https://bugs.chromium.org/p/chromium/issues/detail?id=1354817

**Comment by yusuf-goog** [comment]
Here are some debug logs that might be useful: https://drive.google.com/drive/folders/1Ncu8vm-QYfzkSXlqmbhGvNb6F8NDS6eC?resourcekey=0-l3bxRz_X0IKoRip65f1Vnw&usp=share_link

**Comment by jmagman** [comment]
This is preventing us from using the new arm64 capacity on the framework side, I had to force `plugin_test_ios` and the Mac build_tests to run only on Intel since the timeouts were causing flakes.

@yusuf-goog has there been any progress figuring out why these machines are running so slowly?

**Comment by yusuf-goog** [comment]
No definitive cause. I am trying some more things and will report back. If you have any ideas, let me know.

**Comment by yusuf-goog** [comment]
Checked, all devicelab mac machines have the no_log file set: 

https://paste.googleplex.com/4635020873433088

**Comment by yusuf-goog** [comment]
Ran `sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist` on all devicelab mac machines, which should unload the spotlight indexing service.

**Comment by stuartmorgan** [comment]
Watching timings for all `Mac_arm64 ios_platform_tests_shard_*` tasks in flutter/plugins for engine rolls (which always run everything, so should take similar amounts of time from run to run), both presubmit and postsubmit, would be a good canary for whether changes are addressing the issue. The downside is that we only have about one of those per day.

**Comment by jmagman** [comment]
`tool_integration_tests` are also now running on Intel-only https://github.com/flutter/flutter/pull/120634

**Comment by nehalvpatel** [comment]
@yusuf-goog Any update on this?

**Comment by yusuf-goog** [comment]
No, still experimenting with the mac m1's to isolate the slowdown.

**Comment by yusuf-goog** [comment]
@jmagman I have been digging through some logs and something I noticed stick out is this one thread takes much longer to run on M1 compared to x86:

x86:
```
[plugin_test] [STDOUT] stdout: [+4599 ms] :app:minifyReleaseWithR8 (Thread[Execution worker Thread 4,5,main]) completed. Took 10.893 secs.
[plugin_test] [STDOUT] stdout: [+4477 ms] :app:minifyReleaseWithR8 (Thread[included builds,5,main]) completed. Took 9.644 secs.
[plugin_test] [STDOUT] stdout: [+2413 ms] :app:minifyReleaseWithR8 (Thread[Execution worker Thread 10,5,main]) completed. Took 11.704 secs.
[plugin_test] [STDOUT] stdout: [ +988 ms] :app:minifyReleaseWithR8 (Thread[Execution worker Thread 8,5,main]) completed. Took 9.891 secs.
[plugin_test] [STDOUT] stdout: [+4255 ms] :app:minifyReleaseWithR8 (Thread[Execution worker Thread 8,5,main]) completed. Took 10.378 secs.
[plugin_test] [STDOUT] stdout: [+4989 ms] :app:minifyReleaseWithR8 (Thread[Execution worker Thread 4,5,main]) completed. Took 9.798 secs.
[plugin_test] [STDOUT] stdout: [+2641 ms] :app:minifyReleaseWithR8 (Thread[Execution worker,5,main]) completed. Took 11.29 secs.
[plugin_test] [STDOUT] stdout: [ +899 ms] :app:minifyReleaseWithR8 (Thread[Execution worker,5,main]) completed. Took 10.098 secs.
[plugin_test] [STDOUT] stdout: [ +948 ms] :app:minifyReleaseWithR8 (Thread[Execution worker Thread 11,5,main]) completed. Took 9.942 secs.
[plugin_test] [STDOUT] stdout: [ +908 ms] :app:minifyReleaseWithR8 (Thread[Execution worker Thread 10,5,main]) completed. Took 9.478 secs.
```

m1:
```
[plugin_test] [STDOUT] stdout: [+21477 ms] :app:minifyReleaseWithR8 (Thread[Execution worker,5,main]) completed. Took 39.055 secs.
[plugin_test] [STDOUT] stdout: [+17398 ms] :app:minifyReleaseWithR8 (Thread[included builds,5,main]) completed. Took 31.92 secs.
[plugin_test] [STDOUT] stdout: [+2370 ms] :app:minifyReleaseWithR8 (Thread[Execution worker Thread 7,5,main]) completed. Took 29.068 secs.
[plugin_test] [STDOUT] stdout: [+2654 ms] :app:minifyReleaseWithR8 (Thread[Execution worker Thread 5,5,main]) completed. Took 36.899 secs.
[plugin_test] [STDOUT] stdout: [+11489 ms] :app:minifyReleaseWithR8 (Thread[Execution worker Thread 3,5,main]) completed. Took 28.136 secs.
[plugin_test] [STDOUT] stdout: [+18833 ms] :app:minifyReleaseWithR8 (Thread[included builds,5,main]) completed. Took 34.267 secs.
[plugin_test] [STDOUT] stdout: [+3065 ms] :app:minifyReleaseWithR8 (Thread[Execution worker Thread 7,5,main]) completed. Took 33.076 secs.
[plugin_test] [STDOUT] stdout: [+2792 ms] :app:minifyReleaseWithR8 (Thread[Execution worker Thread 4,5,main]) completed. Took 36.98 secs.
[plugin_test] [STDOUT] stdout: [+5287 ms] :app:minifyReleaseWithR8 (Thread[Execution worker Thread 2,5,main]) completed. Took 36.954 secs.
[plugin_test] [STDOUT] stdout: [+5623 ms] :app:minifyReleaseWithR8 (Thread[Execution worker Thread 6,5,main]) completed. Took 36.473 secs.
```

**Comment by yusuf-goog** [comment]
Looking into the logs it seems like every task is running slower on m1. Digging more...

**Comment by jmagman** [comment]
arm top output from a timeout:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8789239840882614001/+/u/OS_info__2_/stdout

```
Processes: 577 total, 13 running, 564 sleeping, 2329 threads 
2023/02/13 14:31:53
Load Avg: 22.17, 24.06, 23.29 
CPU usage: 71.51% user, 25.26% sys, 3.21% idle 
SharedLibs: 269M resident, 59M data, 16M linkedit.
MemRegions: 473882 total, 2208M resident, 143M private, 926M shared.
PhysMem: 13G used (1591M wired), 2826M unused.
VM: 220T vsize, 3831M framework vsize, 0(0) swapins, 0(0) swapouts.
Networks: packets: 12410501/14G in, 122277/237M out.
Disks: 2261974/45G read, 2058239/103G written.
```

vs Intel:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8787339957558953953/+/u/OS_info__2_/stdout
```
Processes: 414 total, 2 running, 412 sleeping, 2046 threads 
2023/03/06 13:30:15
Load Avg: 2.78, 2.95, 3.27 
CPU usage: 4.0% user, 1.75% sys, 94.24% idle 
SharedLibs: 489M resident, 90M data, 38M linkedit.
MemRegions: 57373 total, 4484M resident, 216M private, 1465M shared.
PhysMem: 15G used (2703M wired), 17G unused.
VM: 13T vsize, 3152M framework vsize, 0(0) swapins, 0(0) swapouts.
Networks: packets: 20712592/23G in, 1977423/4137M out.
Disks: 8908472/193G read, 5006449/360G written.
```

The [12-core Macmini8,1 Intel bot](https://chromium-swarm.appspot.com/bot?id=build802-m9) is 94% idle when the tests finish, has 17G of free memory, and 3.27 15-minute load average.  The [8-core Macmini9,1 ARM bot](https://chromium-swarm.appspot.com/bot?id=mac-495-g140) is only 3% idle, only has 2.8MB of free space, and high 23.29 (!) 15-minute load average.

**Comment by dnfield** [comment]
Can you get a more verbose Xcode build?

Looking at https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8790455238200338273/+/u/Run_plugin_tests/build_examples/stdout with timestamps, most of the delays are coming from Xcode build with no output, e.g. https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8790455238200338273/+/u/Run_plugin_tests/build_examples/stdout#L5719_0

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/8620741/224389571-2922b0ff-e2cc-46f4-b782-3270591fbabb.png">

**Comment by jmagman** [comment]
Here's an example of a timeout with verbose Xcode logging:
https://github.com/flutter/flutter/issues/119764
https://ci.chromium.org/p/flutter/builders/try/Mac%20plugin_test_ios/13856

Here's one that's not even running any Xcode commands, it's an Android test:
https://github.com/flutter/flutter/pull/120714
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20plugin_test/11192

**Comment by yusuf-goog** [comment]
Huzzah! Progress on the slowdown:

See [run](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/mohsinally_google.com/cbd6fb234e24be40e5217b318c0c0049b8d74c4cf1a4252adff8f0904a7c4ace/+/build.proto).

It turns out that the cipd java was tagged as an arm build, but was actually an x86 build, which contributed to much of the slowdown. We are effectively now at similar, or better times than the x86 builds. There could be other processes that could add to the improvement, but this was the major slowdown for android tests.

I am running additional checks to confirm.

**Comment by stuartmorgan** [comment]
That's great!

Unfortunately the initial case I filed this about was iOS-specific test shards, so there's still at least one other severe problem.

**Comment by stuartmorgan** [comment]
Capturing from chat for reference: currently the flutter/packages repo is just living with this for most of our tests (and have had to set very high timeouts as a result), so there's a constant pool of live data on this. I just checked and it seems like about 20% of our builds are randomly slow.

My methodology:
- Go to https://ci.chromium.org/p/flutter/g/packages/console
- Find a few rows with commits from engine-flutter-autoroll@skia.org (ignore other rows, since in many cases they are only running tests on only a small subset of packages).
- Open a bunch of `Mac_arm64 ios_platform_tests_shard_N` tests (both `stable` and `master` should be fine, since generally they don't take different amounts of time, but for maximal consistency you could stick to just one), for various values of N

Within each slice, the times should be pretty consistent (i.e., `*shard_1 *` should always take about the same amount of time between runs, `*shard_2 *` should always take about the same amount of time within its runs, etc.). But instead some are much, much slower. And when it happens, it's not some specific step having been very slow, it's *every* step.

And in fact, I hadn't registered this before: it's not just the test steps. Most of the `process logs`, 'initialize logs`, 'log link`, etc. steps take several times as long or more too.

**Comment by stuartmorgan** [comment]
Has there been any more progress on this? I'd really like to be able to lower the timeout on our iOS platform tests in flutter/packages, because when they randomly hang (unclear if that's related to this, or a different ARM-specific issue), right now it takes 2 hours before we can restart them due to the workaround for this.

Alternately, should I be migrating all the iOS plugin platform tests back to Intel indefinitely?

**Comment by keyonghan** [comment]
I was supposed to post my findings earlier. Ran `Mac_arm64 ios_platform_tests_shard_1 master` consecutively on the same bot: [mac-481-g140](https://chromium-swarm.appspot.com/bot?id=mac-481-g140) for 20 times, and the slow build happened three times:

- [first](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/a79a753c35df5a197cbb834bf10a869b0e61ec16d677aaeddd4cf20820ff6d7d/+/build.proto)
- [second](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/9dac8f984d943d2ed8e1baa707f29d6ca0fa4c3c399066c8acd60734790b21cb/+/build.proto)
- [third](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/b1569adf00a52575a00f96fd244eddb92502cce80cf3b0f341e1ff79d5378bc4/+/build.proto)

If we compare the slow builds with a [regular one](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/5526e2dfa35f9bdfca96ce3555f389144a70372a784488e3f0e23cce3f92769c/+/build.proto): the slowness started happening from the `build examples` step. The `process logs`, `initialize logs`, `log link` steps also slowed down since the `build examples` step. (the earlier same `process logs`, `initialize logs`, `log link` steps before `build examples` have consistent execution time as regular builds).

Additionally, also print out the OS info at the end of build, see the [slow build](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/b1569adf00a52575a00f96fd244eddb92502cce80cf3b0f341e1ff79d5378bc4/+/build.proto) v.s. [regular build](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/5526e2dfa35f9bdfca96ce3555f389144a70372a784488e3f0e23cce3f92769c/+/build.proto), where no obvious differences.

This sounds to me something happened during the test/build step, which caused the ongoing slowness. @stuartmorgan Do you have any insight from the test/build side (specifically for `Mac_arm64 ios_platform_tests_shard_1 master`) what may cause the slowness?

**Comment by stuartmorgan** [comment]
> the slowness started happening from the `build examples` step

This step is just doing a bunch of `flutter` builds in sequence. There's nothing particularly special or unusual. I would be pretty surprised if flutter/flutter tests that do flutter builds weren't subject to the same effect.

I don't have any ideas offhand other the usual sorts of thing that interact badly with native compilation, like the mds and logging processes that have already been discussed above.

**Comment by godofredoc** [comment]
This is using an old version of xcode, can we give it a try with the version we are using in the framework `14e222b`?

**Comment by keyonghan** [comment]
> This is using an old version of xcode, can we give it a try with the version we are using in the framework `14e222b`?

A good news so far, the issue hasn't reproduced after [switched to `14e222b` on 05/02](https://github.com/flutter/packages/pull/3868. I checked all 5 shards on both `master` and `stable`. No slowness in the recent ~80 runs. Based on our 20% occurrent percentage, the issue sounds resolved with latest xcode.

**Comment by stuartmorgan** [comment]
That's great! I'll lower the timeouts then, and also pay attention to see if we're still seeing the complete hangs, or if they were potentially symptoms of the same problem.

**Comment by keyonghan** [comment]
We are still all good for the past day, except a real time out on one shard (https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_arm64%20ios_platform_tests_shard_5%20stable/551/overview), which is not the slowness issue.

**Comment by keyonghan** [comment]
Newly enabled [Mac targets](https://github.com/flutter/flutter/pull/127230) have been running okay as well. Marking as resolved.
