### ISSUE TITLE
flutter 3.7.5 Issue on web html rendering RTL

### ISSUE THREAD

**Issue by Naz-Mo** [flutter/flutter#122153]
We are trying to upgrade our e-commerce site with multi language English and Arabic interface, but the right to left RTL text direction got missed up in web HTML rendering with Flutter 3.7

How to solve this issue? we are super excited to work on the new version of #flutter

for example:

    correct expected output: 23.5
    wrong web html rendering result: 5.23

Another example:

    correct expected output: (test) (هذا نص تجريبي (اختبار
    wrong web html rendering result: )test() هذا نص تجريبي )اختبار

we have tried this code sample, but it was not working

`void main() {
 runApp(const MyApp());
}

class MyApp extends StatelessWidget {
 const MyApp({super.key});

 @override
 Widget build(BuildContext context) {
   return MaterialApp(
     title: 'Flutter Demo',
     theme: ThemeData(
       primarySwatch: Colors.blue,
     ),
     home: const HomePage(),
   );
 }
}

class HomePage extends StatelessWidget {
 const HomePage({Key? key}) : super(key: key);

 @override
 Widget build(BuildContext context) {
   return Scaffold(
     body: Column(
       children: const [
         Directionality(
           textDirection: TextDirection.rtl,
           child: Text(
             'سعر المنتج 23.5 دولار',
             style: TextStyle(fontSize: 30, fontWeight: FontWeight.bold),
           ),
         ),
         SizedBox(height: 20),
         Directionality(
           textDirection: TextDirection.rtl,
           child: Text(
             '(test) (هذا نص تجريبي (اختبار',
             style: TextStyle(fontSize: 30, fontWeight: FontWeight.bold),
           ),
         ),
       ],
     ),
   );
 }
}`

**Comment by darshankawar** [comment]
Thanks for the report. Verified this using latest master and stable version using both renderers and below are the results:

1. With canvaskit:

<img width="411" alt="Screenshot 2023-03-08 at 1 12 49 PM" src="https://user-images.githubusercontent.com/67046386/223653686-df54957f-61fc-4f90-8bc2-b0d4346bb3e6.png">

2. With html renderer:

<img width="392" alt="Screenshot 2023-03-08 at 1 13 47 PM" src="https://user-images.githubusercontent.com/67046386/223653867-81047aa4-5860-4775-80f5-3073ebcdbf85.png">


@Naz-Mo 


> correct expected output: 23.5
> wrong web html rendering result: 5.23

This seems to be occuring as reported, ie, 5.23 instead of 23.5.



> correct expected output: (test) (هذا نص تجريبي (اختبار
> wrong web html rendering result: )test() هذا نص تجريبي )اختبار

This output is also not matching with what I observed above, ie, `test` is at the end of the text whereas you have mentioned it at the start.

Is this a correct interpretation of the reported behavior ?

**Comment by Naz-Mo** [comment]
@darshankawar the brackets around the word test are correct but the remaining is not 
and in numbers the dot or comma doing the same mirroring effect that generating wrong output value

**Comment by darshankawar** [comment]
Thanks for the update. 

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.7.5, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.7.5 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (7 days ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.9.0-1.0.pre.118, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.9.0-1.0.pre.118 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 036592e0cf (38 minutes ago), 2023-03-08 23:15:14 -0500
    • Engine revision 7e1b3a98d1
    • Dart version 3.0.0 (build 3.0.0-312.0.dev)
    • DevTools version 2.22.2
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by bleroux** [comment]
@Naz-Mo 
Thanks for the detailed report. 
There are two different issues here:
- one with number mirroring
- one with the sentence ''(test) (هذا نص تجريبي (اختبار',"

The first one is specific to the web HTML renderer.
The second one is reproducible on all platforms (I tested on Linux, Android, web canvaskit and web HTML renderer).
Can you please file a new issue with only the second case? Because it needs to have seperate labels to be investigated and fixed by the right team. Thanks!

**Comment by MOdeh90** [comment]
> @Naz-Mo Thanks for the detailed report. There are two different issues here:
> 
> * one with number mirroring
> * one with the sentence ''(test) (هذا نص تجريبي (اختبار',"
> 
> The first one is specific to the web HTML renderer. The second one is reproducible on all platforms (I tested on Linux, Android, web canvaskit and web HTML renderer). Can you please file a new issue with only the second case? Because it needs to have seperate labels to be investigated and fixed by the right team. Thanks!

@bleroux 
we are separated the second point with new issue
[https://github.com/flutter/flutter/issues/122500](url)

**Comment by anyab5** [comment]
Hi, we are having the same issue with number mirroring in rtl.
Is there any suggested workaround for number mirroring issues besides wrapping each number with ltr directionality element ?

**Comment by saif97** [comment]
I can confirm that the issue was introduced in Flutter 3.7.0. Downgrading to 3.3.10 stable resolves the issue. 

I'm interested in contributing to resolving this issue. Any leads?

**Comment by mazroe** [comment]
This is still existing issue event in 3.10.6. I am also interested to contribute here

**Comment by Mahdi2565** [comment]
any update ?
this issue is so important for production

**Comment by Amir-P** [comment]
Probably the bad commit on framework: https://github.com/flutter/flutter/pull/113652
Probably the bad commit on engine: https://github.com/flutter/engine/pull/34085

**Comment by hn-n** [comment]
I'm interested in contributing to resolving this issue. 

it still exists in Flutter 3.22
