### ISSUE TITLE
FLUTTER WEB TEXTFIELD major issue: cursor goes to wrong place after tap on Android and iOS 

### ISSUE THREAD

**Issue by hhkk** [flutter/flutter#124483]
As run in chrome and safari browsers on android and ios cell phones, after many experiments we ask...

seen in flutter version 3.2.2 stable and  3.7.10 stable on 3 people's environments.

issue is also seen using http-server against release flutter build web (build/web) content.

Easy to demonstrate:

Use this example - open this url 

**on a cell phone**

https://docs.flutter.dev/cookbook/forms/focus

1 in the cookbook dev code editor add:
   maxLines: 5

2 click run 

3  in the textfield, past the ~1500 char's lorem ipsum text below.  

4 tap various places within the text (once the on screen keyboard settles) and 

5 !!!!!!  issue: you will see cursor does not end up where the  tap occurred. bounces to other places, with underlines and confused attempts at hi-lighting I guess

sample text to paste:

Lorem ipsum dolor sit amet, dictas habemus nominati ex sed, possit prodesset concludaturque sed ei, usu ut falli constituam. Mea ad ipsum graeci aliquip, iisque volumus theophrastus sit id. Nec ei sumo democritum, qui dicant inimicus repudiare no. Duo no hinc partem ornatus, ei voluptua moderatius eloquentiam cum, pri modus viderer vituperatoribus ad. Ea sea dicunt vidisse sadipscing.

Ut aliquid bonorum definitiones sit, at delenit utroque adversarium ius. At vocent imperdiet definitiones eum. Vulputate dissentiet eu eos, vis virtute urbanitas reprimique et, adhuc errem reprimique eos eu. Duo utinam doctus concludaturque an, ne alienum constituam per.

Rebum impedit volumus ad qui, mei epicurei reprehendunt ad. Mel magna deleniti appetere ex, ex lobortis inciderint quo, saepe vidisse impedit an vim. Legendos deseruisse usu ei, eu nominavi facilisi iudicabit eum. Mel et iracundia torquatos, iudico platonem inciderint nec an, reprimique necessitatibus duo eu.

Enim iusto nec ei, pri no erat mollis erroribus. Usu ex natum cotidieque philosophia, ius cu alienum omittam. Pro dico congue utamur et, vix duis delenit deterruisset ne, te vero atqui usu. Mucius volutpat intellegam duo ea, adhuc putent tacimates mei ex.

Ut falli impetus honestatis est, id sed decore perpetua principes. Animal electram tractatos eam at. An cum dicunt option timeam, maiorum accumsan nominavi pro ad. Mel ne sint disputationi. Cu mea tibique persequeris, an ius wisi cetero.

END SAMPLE TEXT

also we tried many cell phone textfield examples using   

flutter run -d web-server --web-port $1 --web-hostname 0.0.0.0

FLUTTER DOCTOR

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.10, on macOS 12.5.1 21G83 darwin-x64, locale
    en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[!] Xcode - develop for iOS and macOS (Xcode 14.2)
    ! CocoaPods 1.8.4 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.1)
[✓] VS Code (version 1.43.2)
[✓] VS Code (version 1.76.2)
[✓] VS Code (version 1.68.1)
[✓] VS Code (version 1.40.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.

**Comment by hhkk** [comment]
this issue may not manifest with shorter text blocks say 100-300 char's

**Comment by hhkk** [comment]
correction: sorry, step 3 should have included the E in pastE: 

3 in the textfield, pastE the ~1500 char's lorem ipsum text below.

**Comment by darshankawar** [comment]
Thanks for the report @hhkk 
Looks like your issue is closely related / similar to https://github.com/flutter/flutter/issues/120604 ?
Can you check and confirm ?

**Comment by hhkk** [comment]
I will check that within the next few hours. My initial thought is that
that issue is specific to clicking the END of text.

In my case, perhaps requiring long enough text, you can tap pretty much
anywhere (may need to tap  a few times) and you'll see that eventually the
cursor goes to a crazy place even when tapping on places other than the
end.

 Do you know off hand if that fix affected tapping other places besides the
end?

Thank you! So glad to hear from you.

**Comment by hhkk** [comment]
Hi,

in attempting to fulfill your request, I am so far having trouble building master.  But I wanted to get back to you ASAP.  So I did just upgrade stable channel to latest (to same as my prior tested version)
Flutter 3.7.10 • channel stable 

The issue still exists.  

You probably don't need to paste 1500 characters to see the issue by the way.

I will continue to try and get my master channel building so I can answer your question fully.

Is Master the only relevant channel for this test? 

Thank you

**Comment by hhkk** [comment]
i still get the fail unfortunately :(
Flutter 3.10.0-2.0.pre.30 • channel master •
built using  flutter build web --release 

problem happens easily ... 

test program is below (from the dev cookbook + maxLines: 5) 

lorem ipsum test data is above  in comments.  Probably don't need 1500 char's of test data. 

This is a blocking issue for me and others.  Any help so much appreciated. 

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Text Field Focus',
      home: MyCustomForm(),
    );
  }
}

// Define a custom Form widget.
class MyCustomForm extends StatefulWidget {
  const MyCustomForm({super.key});

  @override
  State<MyCustomForm> createState() => _MyCustomFormState();
}

// Define a corresponding State class.
// This class holds data related to the form.
class _MyCustomFormState extends State<MyCustomForm> {
  // Define the focus node. To manage the lifecycle, create the FocusNode in
  // the initState method, and clean it up in the dispose method.
  late FocusNode myFocusNode;

  @override
  void initState() {
    super.initState();

    myFocusNode = FocusNode();
  }

  @override
  void dispose() {
    // Clean up the focus node when the Form is disposed.
    myFocusNode.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Text Field Focus'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            // The first text field is focused on as soon as the app starts.
            const TextField(
maxLines: 5,
              autofocus: true,
            ),
            // The second text field is focused on when a user taps the
            // FloatingActionButton.
            TextField(
              focusNode: myFocusNode,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        // When the button is pressed,
        // give focus to the text field using myFocusNode.
        onPressed: () => myFocusNode.requestFocus(),
        tooltip: 'Focus Second Text Field',
        child: const Icon(Icons.edit),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

**Comment by darshankawar** [comment]
@hhkk 
So I tried the same as you mentioned above and observed that upon trying to tap on the given text, it takes me to the end of the line as shown below:


https://user-images.githubusercontent.com/67046386/231072071-f8412464-482f-40c2-b46a-bc2ce1d05f24.MP4

I scrolled all the way up in the textfield and tried to tap, but it took me to the end of the text everytime. Also, while trying to tap in the middle of the text, instead of showing the cursor, it shows me highlighted text which I think is already reported in one of the linked / related issues.

Are you seeing the same behavior as I see from the video ? If not, a short video of the behavior would be helpful.

**Comment by hhkk** [comment]
FYI - here is a list of all related issues i have found

search key: https://github.com/flutter/flutter/issues?q=is%3Aissue+tap+cursor+textfield 

https://github.com/flutter/flutter/issues/124483  this

https://github.com/flutter/flutter/issues/98720 [Android] TextField cursor doesn't move to tapped position, but converts into text selection mode after selecting input mode from virtual keyboard. #98720

https://github.com/flutter/flutter/issues/100004   two exclamation points

https://github.com/flutter/flutter/issues/121164  feb 21 2023 Text field cursor position in RTL goes to the penultimate character

https://github.com/flutter/flutter/issues/122443   mar 10 2023 
  Failed%20assertion%20when%20trying%20to%20set%20caret%20position%20to%20text%20position%20that%20is%20not%20visible 

https://github.com/flutter/flutter/issues/118566  jan 16 2023   Text field cursor position in RTL goes to the penultimate character

https://github.com/flutter/flutter/issues/114433  not 2022 TextField's cursor cannot move in the middle of the word

https://github.com/flutter/flutter/issues/120604  feb 13  TextField cursor stands in a wrong position while using persian words

https://github.com/flutter/flutter/issues/109175  aug 2022 cursor is not inserting value at the specific position where i tapped when readOnly mode is enabled in textformField

https://github.com/flutter/flutter/issues/100004  mar 2022 tap to move cursor in textfield not working on android

**Comment by hhkk** [comment]
As I've reviewed and thought about the above list of issues and this one, this problem is not addressed in prior issues in my opinion.

**Comment by hhkk** [comment]
the iphone version demonstrating this is
iPhone 12 Pro Max
iOS Version 16.3.1

**Comment by darshankawar** [comment]
Thanks for the update. Based on the report and my [findings](https://github.com/flutter/flutter/issues/124483#issuecomment-1502742944) earlier, I am going ahead and keeping this issue open.

<details>
<summary> code sample used </summary>

```

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Text Field Focus',
      home: MyCustomForm(),
    );
  }
}

// Define a custom Form widget.
class MyCustomForm extends StatefulWidget {
  const MyCustomForm({super.key});

  @override
  State<MyCustomForm> createState() => _MyCustomFormState();
}

// Define a corresponding State class.
// This class holds data related to the form.
class _MyCustomFormState extends State<MyCustomForm> {
  // Define the focus node. To manage the lifecycle, create the FocusNode in
  // the initState method, and clean it up in the dispose method.
  late FocusNode myFocusNode;

  @override
  void initState() {
    super.initState();

    myFocusNode = FocusNode();
  }

  @override
  void dispose() {
    // Clean up the focus node when the Form is disposed.
    myFocusNode.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Text Field Focus'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            // The first text field is focused on as soon as the app starts.
            const TextField(
              autofocus: true,
              maxLines: 5,
            ),
            // The second text field is focused on when a user taps the
            // FloatingActionButton.
            TextField(
              focusNode: myFocusNode,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        // When the button is pressed,
        // give focus to the text field using myFocusNode.
        onPressed: () => myFocusNode.requestFocus(),
        tooltip: 'Focus Second Text Field',
        child: const Icon(Icons.edit),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details>

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.7.10, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.7.10 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (6 days ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.10.0-3.0.pre.56, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.10.0-3.0.pre.56 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8fae9618ce (84 minutes ago), 2023-04-11 23:34:11 -0400
    • Engine revision 176ad4a6d8
    • Dart version 3.0.0 (build 3.0.0-431.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by hhkk** [comment]
OK thanks.

clicking in various places around the text field may reveal other oddities, but probably all included in existing items. 

this is a key issue IMO - can't edit means can't use :)

**Comment by hhkk** [comment]
HI @yjbanov - I don't see reference to 1) tapping the pointer 2) on a cell phone and 3) having the cursor end up in a seemingly unrelated place (the bottom).  So I do not think they are the same issue.  Let me know if I am missing something.  Thanks

**Comment by bleroux** [comment]
FYI, I have a fix for this issue on Android.
I will post more details tomorrow (it is late here) and also tried a similar fix on iOS.

**Comment by hhkk** [comment]
> FYI, I have a fix for this issue on Android. I will post more details tomorrow (it is late here) and also tried a similar fix on iOS.

Sweet!  Please test with clicking around various places in a longish (eg ~1500 char lorem ipsum) text block and see if you see any other similar anomalies in terms if tap location vs resulting cursor location.  (I'm not convinced that it's always "wrongly going to the end of the text block".)

Thank you 
Henry

**Comment by bleroux** [comment]
@hhkk  Thanks for the detailed report.
@darshankawar Thanks for verifying this.

I filed https://github.com/flutter/engine/pull/41202 with a simplified code sample.
From my testing, the fix is ok on Android/Chrome, but I have to find why it partially works on iOS/Safari.

> I'm not convinced that it's always "wrongly going to the end of the text block".)

From my investigation, the cursor does not always jump to the end. It seems to jump to a place which was visible before (for instance, if we scroll and then tap, the cursor will jump where on the text which was at the tap position before the scroll). As described in the PR, it is because both Flutter and the <textarea> elements update the selection at the same time.

**Comment by ammarqusailah** [comment]
This solution worked for me with Android and Windows

```dart
controller.addListener(() {
      if (controller != null) {
        if (controller.selection ==
            TextSelection.fromPosition(
              TextPosition(
                offset: controller.text.length - 1,
              ),
            )) {
          controller.selection = TextSelection.fromPosition(
            TextPosition(
              offset: controller.text.length,
            ),
          );
        }
      }
    });
```

**Comment by deepak786** [comment]
I also have the same issue. See the below video from Android Chrome browser:
https://user-images.githubusercontent.com/14223997/233150374-97b1d784-fb9c-4a45-a908-5eb2040e1fee.mp4

**Comment by hhkk** [comment]
Sorry - I'm somewhat new at this.  How and when would I be able to see a fix in a flutter upgrade?

Or is there a faster way to incorporate a fix from this?  https://github.com/flutter/engine/pull/41202

Thank you

**Comment by bleroux** [comment]
The Android PR is merged.
Unassigned myself and update the title because I have no solution for the moment to fix this on iOS.

**Comment by hhkk** [comment]
> The Android PR is merged. Unassigned myself and update the title because I have no solution for the moment to fix this on iOS.

Thank you Bruno!  At least in the current Beta channel, I no longer see the issue of being unable to place the cursor properly in a multiline textfield on my Android Pixel 7 which has version:

<img width="318" alt="image" src="https://github.com/flutter/flutter/assets/769592/b38d7aa8-ce24-4512-b667-318604e83d35">

And this issue ALSO SEEMS TO BE FIXED iOS ipad version 15.7.3 on an ipad air 2 

Question: Is my observation of a fix having happened (in regards to inability to tap/place the cursor in a textfield) consistent with changes you have made? 

Thank you for these fixes if so!

Henry (middle name Bruno ;)

**Comment by bleroux** [comment]
> And this issue ALSO SEEMS TO BE FIXED iOS ipad version 15.7.3 on an ipad air 2
> Question: Is my observation of a fix having happened (in regards to inability to tap/place the cursor in a textfield) consistent with changes you have made?

@hhkk Did you check this using the Flutter Web build of your app or the Android/iOS builds?

I'm asking because my fix is only for Flutter Web on Chrome/Android, so the issue should be still reproducible on Safari/iOS. And as far as I know, this fix does not reach current the beta channel yet.

**Comment by hhkk** [comment]
Agreed.  Yes I did see the issue continue on iOS. So I agree the issue
appears to be resolved for Android but continues for iOS.

I am only using Flutter Web Chrome.

And I guess the flutter channel matters i.e that beta has the fixed while
Master may not?

I can get you details on the version of iOS that failed, if you're
interested.

Thank you
Henry

**Comment by gnprice** [comment]
> And I guess the flutter channel matters i.e that beta has the fixed while Master may not?

In general all changes will appear in the master/main channel first, then beta and then stable. So any very recent fix will be in master but not in beta, and later it will be in master and beta but not stable.

The reverse (fixed in beta but not in master) would be unusual, though, and if you see something like that it should definitely be reported as a bug. If something's broken in master, then that breakage will probably reach beta and stable in the future unless someone fixes it first.

More here: https://github.com/flutter/flutter/wiki/Flutter-build-release-channels

**Comment by jimmyff** [comment]
I am experiencing this issue too clicking & selecting on TextFields although I've just noticed the issue is only on my external display, when I drag the web browser window to my macbooks internal display, there is no issue. 

Could it be a DPI calculation issue?

**Comment by hhkk** [comment]
It would be great if someone could give us a summary of where we are on
this issue for iOS. Flutter is basically unusable as far as I can tell on
iOS with regards to this multi-line text field cursor position issue.

**Comment by hhkk** [comment]
Second request. It's been 4 months since this major issue was reported regarding iOS (iphone) text fields and cursor positioning via tap. 

Can anyone please comment whether this issue is being worked on?  My test yesterday was with latest master flutter channel and is still failing grossly for cursor positioning within a multiline textfield on iphone.  Works well for android AFAIK.  

It's been 4 months since I reported this issue.  This makes flutter unusable on apple devices!!

Can you please let us know how to think about this issue broadly?  

Thank you 
Henry

**Comment by htoor3** [comment]
hey @hhkk, this issue being worked on as part of a larger fix here https://github.com/flutter/flutter/issues/120613.  I'll take some time this week to investigate and see if there's a potential workaround we can implement before then.

**Comment by hhkk** [comment]
correction: on further testing, we see that the magnifier is good but it can be also be difficult with the magnifier to place cursor in the exact location reliably.

**Comment by htoor3** [comment]
@hhkk Thank you for the notes! So currently selection placement in iOS only works reliably with the magnifier (long press + drag)?

**Comment by hhkk** [comment]
I'm on the current beta version and the magnifier seems like the only
mostly reliable way to place a cursor on an iphone.  I say MOSTLY reliable
because it still can feel clunky with the magnifier in some situations.

It seems like placing the cursor in the bottom portion of the text field is
more trouble some than the top.

We have tested an iPhone SE and an iPhone 12 both on iOS.

Android seems better.

I am using default. Renderer. Is default renderer good for multi-line
purposes?

If it would be helpful, I can try to be more systematic in my testing and
give you some information about results.

Thank you
Henry

**Comment by justinmc** [comment]
Related? https://github.com/flutter/flutter/issues/167805
