### ISSUE TITLE
[camera] Videos are invalid after switched camera when recording

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#126227]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the `camera`'s example on Android devices.
2. Switch a camera instance and start recording.
3. Flip to another camera without stopping the recording.
4. Stop the recording after the camera was flipped.
5. Preview the recording using `video_player`.

### Expected results

Videos produced in this way should behave normally with flipped cameras content.

### Actual results

After the camera is flipped, the content was stopped at the time the camera was flipped.

### Code sample

https://github.com/flutter/packages/blob/07e09301698f88894f3ffc5f1578422db0a2a987/packages/camera/camera/example/lib/main.dart

##### Screen recording

https://user-images.githubusercontent.com/15884415/236682219-dc673643-b210-46e5-b477-9f744f1e3d51.mp4

##### Recorded video

https://user-images.githubusercontent.com/15884415/236682253-67530cc2-203b-4a4f-9b41-1473fe95513a.mp4

### Logs

[logs.txt](https://github.com/flutter/flutter/files/11415158/logs.txt)

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.22621.1555], locale en-US)
    • Flutter version 3.7.12 on channel stable at X:\SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (3 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at X:\Android\SDK
    • Platform android-33-ext5, build-tools 33.0.2
    • ANDROID_HOME = X:\Android\SDK
    • ANDROID_SDK_ROOT = X:\Android\SDK
    • Java binary at: X:\IDEs\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at X:\IDEs\apps\IDEA-U\ch-0\231.8109.175
    • Flutter plugin version 73.0.4
    • Dart plugin version 231.8109.91

[√] Connected device (4 available)
    • ONEPLUS A6010 (mobile) • f8e67ce3 • android-arm64  • Android 11 (API 30)

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by AlexV525** [comment]
cc @BradenBagby since the feature is introduced in https://github.com/flutter/packages/pull/3496.

**Comment by AlexV525** [comment]
Also @camsim99 @chinmaygarde who reviewed the PR might know more details about it.

**Comment by danagbemava-nc** [comment]
Hi @AlexV525, does this only reproduce for you on a OnePlus device? I tested on my Pixel 7 and it seems to work just fine. 

| recorded video | screen recording of repro steps | 
| -- | -- |
| <video src="https://user-images.githubusercontent.com/88313112/236762800-25a029e5-c348-4191-a7b4-3553e2d376c9.mp4" /> | <video src="https://user-images.githubusercontent.com/88313112/236763428-acf5c9f2-a04a-40ba-9ee8-d56cfd0da738.mp4" /> |

**Comment by AlexV525** [comment]
> Hi @AlexV525, does this only reproduce for you on a OnePlus device? I tested on my Pixel 7 and it seems to work just fine.

Seems yes. I've tested on Huawei Mate 9Pro, OnePlus 6T, and 11, only my OnePlus devices can reproduce the issue.

**Comment by AlexV525** [comment]
Collected some feedback from our community, and it's not a OnePlus-specific issue. I've updated device lists in the top comment.

**Comment by AlexV525** [comment]
On OnePlus 3 and Redmi Note 9, the behavior is slightly different.

https://user-images.githubusercontent.com/15884415/236992964-45f13d7b-6432-4ab3-92f0-5f832bda7b52.mp4

**Comment by danagbemava-nc** [comment]
Hi @AlexV525, thanks for the details. 

Labeling for further investigation as I do not have a device that reproduces this issue locally. 

A list of devices the bug reproduces on can be found in the original issue post.

**Comment by BradenBagby** [comment]
For some more context: 
Im guessing this has to do with eglSwapBuffers in VideoRenderer.java on line 329. On some devices this would fail / is not supported, and the idea was to disallow flipping the camera mid recording for these devices. If we fail to detect that its not supported and then try flipping mid recording, the VideoRenderer.java will fail writing the flipped video to the surface on eglSwapBuffers and is probably exactly whats happening above. 

 These devices it is failing on are not being detected as not supported. So a good fix might be a better way of checking if eglSwapBuffers is supported then disabling the flip if unsupported. 

I also do not have any of these devices to reproduce this issue, but I may be able to look into it another way when I get a chance

**Comment by AlexV525** [comment]
> I also do not have any of these devices to reproduce this issue, but I may be able to look into it another way when I get a chance

Sure. We'll be able to help you to test any fixes on these devices.

**Comment by commond140** [comment]
I have the same issue from my S22 Ultra.
<img width="1015" alt="image" src="https://github.com/flutter/flutter/assets/19163067/0f9e8f4d-1f29-4f32-8c12-60966b35c88d">
<img width="995" alt="image" src="https://github.com/flutter/flutter/assets/19163067/1d7eb64a-0cf7-4183-9864-0055aa147c34">
<img width="1005" alt="image" src="https://github.com/flutter/flutter/assets/19163067/2888edb8-6da8-4d72-ac23-3cdd900b6eb3">
<img width="984" alt="image" src="https://github.com/flutter/flutter/assets/19163067/aa0a3c76-7980-4fbc-8e3b-1fe9b4e48f56">

**Comment by Kaival-Simform** [comment]
Tried on Oneplus nord 2 & realme devices, note that the video gets glitchy after switching to other camera.
https://github.com/flutter/flutter/assets/125883703/a199b0fd-4822-4e6f-b5ce-98d481065a18

**Comment by huycozy** [comment]
Reproduced this issue with [plugin example code](https://github.com/flutter/packages/tree/main/packages/camera/camera/example) on `Realme 6, Android 11` (the current plugin version `camera: ^0.10.5+2`). The issue is not reproducible on iOS platform (checked on iPhone 7, iOS 15.7.2).

<details>
<summary>Demo videos</summary>

_Note: When the switch to the front camera, you will see a black background, that's because my camera is covered by a sticker (security). The front camera still works fine._

| Android | iOS |
| --------------- | --------------- |
<video src="https://github.com/flutter/flutter/assets/104349824/6668b767-b19d-4b8e-9360-aa2419be1b68"/> | <video src="https://github.com/flutter/flutter/assets/104349824/7570e373-a144-49fd-a49d-ee0c02748122"/>

</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.6 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (5 hours ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.13.0-10.0.pre.24, on macOS 13.4.1 22F770820d darwin-x64, locale en-VN)
    • Flutter version 3.13.0-10.0.pre.24 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a4f7906692 (8 minutes ago), 2023-07-25 20:07:27 -0700
    • Engine revision db711f1484
    • Dart version 3.1.0 (build 3.1.0-345.0.dev)
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.4.1 22F770820d darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.248
    ! Device EUYTFEUSQSRGDA6D is not authorized.
      You might need to check your device for an authorization dialog.

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by Satti201** [comment]
Experiencing the identical problem here. When I switch the camera from front to back or vice versa while recording a video, I observe inconsistent outcomes. On Infinix Hot Note I, the resulting video turns blurry post-switching. Meanwhile, on the Samsung Galaxy A12, an error "stop failed" occurs when the video stops. Interestingly, everything seems to display correctly on the Oppo A16e. Worth noting is that these phones are running distinct Android versions. This issue emerges on Android 12 but remains unaffected on earlier versions.

**Comment by kmmk42000** [comment]
Does anybody have any solution for the issue?

**Comment by camsim99** [comment]
This issue should be fixed in the [CameraX implementation](https://pub.dev/packages/camera_android_camerax) of the camera plugin, so please try it out!

If you find a similar issue with that implementation (or any other issues), please feel free to file a separate issue.

**Comment by rohan031** [comment]
> Experiencing the identical problem here. When I switch the camera from front to back or vice versa while recording a video, I observe inconsistent outcomes. On Infinix Hot Note I, the resulting video turns blurry post-switching. Meanwhile, on the Samsung Galaxy A12, an error "stop failed" occurs when the video stops. Interestingly, everything seems to display correctly on the Oppo A16e. Worth noting is that these phones are running distinct Android versions. This issue emerges on Android 12 but remains unaffected on earlier versions.

Do you find anyway to solve this. I am also facing this same issue on Samsung s23.

**Comment by Satti201** [comment]
> > Experiencing the identical problem here. When I switch the camera from front to back or vice versa while recording a video, I observe inconsistent outcomes. On Infinix Hot Note I, the resulting video turns blurry post-switching. Meanwhile, on the Samsung Galaxy A12, an error "stop failed" occurs when the video stops. Interestingly, everything seems to display correctly on the Oppo A16e. Worth noting is that these phones are running distinct Android versions. This issue emerges on Android 12 but remains unaffected on earlier versions.
> 
> Do you find anyway to solve this. I am also facing this same issue on Samsung s23.

I have not worked on it for a long time. but at that time I get around it by combining videos. but I think it issue may be resolved as stated above.

**Comment by rohan031** [comment]
> > > Experiencing the identical problem here. When I switch the camera from front to back or vice versa while recording a video, I observe inconsistent outcomes. On Infinix Hot Note I, the resulting video turns blurry post-switching. Meanwhile, on the Samsung Galaxy A12, an error "stop failed" occurs when the video stops. Interestingly, everything seems to display correctly on the Oppo A16e. Worth noting is that these phones are running distinct Android versions. This issue emerges on Android 12 but remains unaffected on earlier versions.
> > 
> > Do you find anyway to solve this. I am also facing this same issue on Samsung s23.
> 
> I have not worked on it for a long time. So at that time, I got around it by combining videos. But this issue may have been resolved in new versions. as stated above.

I am planning to use native camera app and then work on the video. I did try it on another samsung device still getting same issue and for some weird reason when i am getting all available cameras it give me 4 as in 2 front and 2 back.

**Comment by HoangNgocAnh9797tb** [comment]
This issue is still unresolved.
