### ISSUE TITLE
"FLTDisableImpeller" flag not working

### ISSUE THREAD

**Issue by abdalmonem** [flutter/flutter#126508]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. create any app
2. use flutter 3.10.0
3. try to set flag "FLTDisableImpeller" in ios info.plist: `<key>FLTDisableImpeller</key>
    <true/>`

### Expected results

using 'SKIA' is whats i expect.

### Actual results

the app still using Impeller

### Code sample

void main(){}

### Screenshots or Video

Am trying to stop it cuz its make google maps plugin crash the app

### Logs

Launching lib/main.dart on db iphone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: JF3QVYH5AL
Running Xcode build...
Xcode build done.                                           24.8s
Installing and launching...
(lldb) 2023-05-11 11:10:37.218418+0300 Runner[2670:506888] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
[SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.10.0, on macOS 13.2.1 22D68 darwin-arm64
    (Rosetta), locale en-SD)
    • Flutter version 3.10.0 on channel stable at /Users/abdalmonem/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (2 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/abdalmonem/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] Connected device (4 available)
    • db iphone (mobile)                 •
      e3812cb6bdaa04b1fb64492 • ios            • iOS 16.3.1
      20D67
    • Abdalmonem iphone 13 mini (mobile) • 0CE1801E
      • ios            • iOS 16.3.1 20D67
    • macOS (desktop)                    • macos
      • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64 (Rosetta)
    • Chrome (web)                       • chrome
      • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by danagbemava-nc** [comment]
Hi @abdalmonem, the documentation is incorrect. Please use 

```
<key>FLTEnableImpeller</key>
<false/>
```

or `flutter run --no-enable-impeller`


I'll be filing an issue on the website so that this can be corrected in the documentation. 

Closing from here. 

Thank you

**Comment by abdalmonem** [comment]
> Hi @abdalmonem, the documentation is incorrect. Please use
> 
> ```
> <key>FLTEnableImpeller</key>
> <false/>
> ```
> 
> or `flutter run --no-enable-impeller`
> 
> I'll be filing an issue on the website so that this can be corrected in the documentation.
> 
> Closing from here.
> 
> Thank you

thanks for your respond danag , but i already expect this before open the issue , and i tried it , but doesnt work also

**Comment by danagbemava-nc** [comment]
Hi @abdalmonem, when you say it does not work, do you mean the app still crashes or it still runs with impeller?

Please note that when you're running with SKIA, it will not be printed to the console that you are running with SKIA, that only happens when you're using impeller. 
So if you do not see 
`(lldb) 2023-05-12 06:42:20.522982+0000 Runner[2418:194565] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(35)] Using the Impeller rendering backend.
`

In your console, you are using skia.

**Comment by abdalmonem** [comment]
@danagbemava-nc  i will try it again now and reply back.

**Comment by abdalmonem** [comment]
@danagbemava-nc the tow lines mentioned doesnt appear in the console , but i am pretty sure impeller works
why:
impeller has some issues with blue when i use sigma, not like SKIA, when i use `FLTEnableImpeller` i can still see the blur issue , also impeller has issue with "google maps" plugin , its crashes and console show  :
`* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x000000010bbb5348 Flutter`flutter::IOSExternalViewEmbedder::CompositeEmbeddedView(long long) + 1828
Flutter`flutter::IOSExternalViewEmbedder::CompositeEmbeddedView:
->  0x10bbb5348 <+1828>: ldr    x8, [x0]
    0x10bbb534c <+1832>: ldr    x8, [x8, #0x30]
    0x10bbb5350 <+1836>: blr    x8
    0x10bbb5354 <+1840>: cbz    x0, 0x10bbb5538           ; <+2324>`
i know its should be tow different  issues , but i mention this to say 'impeller still works' even after use `FLTEnableImpeller`

**Comment by abdalmonem** [comment]
close...
looks like there is changes in SKIA makes me think impeller is working.
i notice the changes in `BackdropFilter` with filter : `ImageFilter.blur()`, when using 'sigmaX' or 'sigmaY' with '0' value , the blur effect not working.
appreciate your time @danagbemava-nc
