### ISSUE TITLE
Keyboard is hiding the textfields in latest version i.e 3.10.4

### ISSUE THREAD

**Issue by PhaniUmmedisetti** [flutter/flutter#128770]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Wherever we are using a textfield, the keyboard pops up but the textfield hides beneath the keyboard

### Expected results

the keyboard should show up below the text field and not upon it.

### Actual results

the keyboard should show up below the text field and not upon it.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.2.1 22D68 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.79.0)
[✓] Connected device (4 available)
    ! Error: NSPIRA APPS’s iPhone (2) is busy: Fetching debug symbols for NSPIRA APPS’s iPhone (2). Xcode will continue when NSPIRA APPS’s iPhone
      (2) is finished. (code -10)
[✓] Network resources

• No issues found!

**Comment by gizemgizg** [comment]
same problem 🥺

**Comment by PhaniUmmedisetti** [comment]
> same problem 🥺

Any luck finding the solution?

**Comment by gizemgizg** [comment]
There is a scroll problem in 3.10 and later. I am using the Screen utils plugin and Keyboards Actions. The application's Pageview structures are broken. Some pages get 20 builds. I can't scroll. When I touch the textformfield, the textformfield stays below the keyboard instead of above the keyboard. I give SingleChildScroll, scroll does not happen. I had to downgrade to 3.7.12.

**Comment by PhaniUmmedisetti** [comment]
> There is a scroll problem in 3.10 and later. I am using the Screen utils plugin and Keyboards Actions. The application's Pageview structures are broken. Some pages get 20 builds. I can't scroll. When I touch the textformfield, the textformfield stays below the keyboard instead of above the keyboard. I give SingleChildScroll, scroll does not happen. I had to downgrade to 3.7.12.


Just try adding  "MediaQuery.of(context).viewInsets.bottom;" under the build of main.dart. It resolved my problem.

<img width="409" alt="Screenshot 2023-06-13 at 3 01 09 PM" src="https://github.com/flutter/flutter/assets/100353755/78eb0859-6a75-4ca0-bfb2-5091b3694767">

**Comment by darshankawar** [comment]
@PhaniUmmedisetti 
It seems you are hitting https://github.com/flutter/flutter/issues/126585 which discusses same behavior / use case.
Also, based on above comment / solution it seems it is resolved at your end and can be closed.

Everyone else facing the reported issue, please check the linked issue which has root-cause and solution and basically it doesn't seem to be a bug in framework. So closing as duplicate and already resolved based on above comment from OP. If anyone disagree, write in comments and I'll reopen it.

**Comment by gizemgizg** [comment]
@darshankawar Thank you! ✨

**Comment by gizemgizg** [comment]
In Flutter 3.10.4 when I set the Screen utils useInheritedMediaQuery = true parameter to true it breaks the PageView working structure. The last page gets too many builds. I am using the latest version of screen utils. This doesn't solve my problem. Unfortunately

**Comment by PhaniUmmedisetti** [comment]
Why use a retracted package and take risk? Rather you can simply use MediaQuery.of(context).size.height and MediaQuery.of(context).size.width for responsive screen na?
Simple way and use the above code I mentioned and you should be good to go.

**Comment by gizemgizg** [comment]
Since the project is finished, it is not possible for me to use MediaQuery.of(context).size.height and MediaQuery.of(context).size.width. I used screen utils for responsive design.

**Comment by yahya489** [comment]
same problem

**Comment by aiyub007** [comment]
@PhaniUmmedisetti  You are lit :) 
 Thanks!!
Writing this solved the problem 
 MediaQuery.of(context).viewInsets.bottom;
