### ISSUE TITLE
There is a half-pixel gap between `SliverAppBar` and `SliverPersistentHeader`

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#129870]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run the code sample

### Expected results

There should be no gap between a `SliverAppBar` and the `SliverPersistentHeader` below it.

### Actual results

There is a half-pixel gap, which can show up as a faint white line if the background color is not white. See the screenshot below. The faint white line is above the "Click me" button.

The gap increases in size if the content is dragged downwards when the `SliverList` is at the top of its scroll range (because everything on the page is stretched vertically). However there is a gap even when the UI is not stretched.

Really there should be no gap even if the UI is being stretched.

### Code sample

<details><summary>Code sample</summary>

```dart
class _HeaderDelegate extends SliverPersistentHeaderDelegate {
  final double height;

  _HeaderDelegate({
    required this.height,
  });

  @override
  double get maxExtent => height;

  @override
  double get minExtent => 0.0;

  @override
  bool shouldRebuild(covariant SliverPersistentHeaderDelegate oldDelegate) {
    return true;
  }

  @override
  Widget build(
          BuildContext context, double shrinkOffset, bool overlapsContent) =>
      SingleChildScrollView(
        child: Container(
          color: Colors.amber,
          child: Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              ElevatedButton(onPressed: () {}, child: const Text('Click me')),
            ],
          ),
        ),
      );
}

class SliverPage extends StatelessWidget {
  const SliverPage({super.key});

  @override
  Widget build(BuildContext context) {
    return CustomScrollView(
      slivers: <Widget>[
        const SliverAppBar(
          expandedHeight: 100,
          title: Text('Title text'),
          floating: true,                    // (*)
          pinned: false,
          snap: false,
          backgroundColor: Colors.amber,
          // Make the hamburger menu icon white
          iconTheme: IconThemeData(color: Colors.white),
        ),
        SliverPersistentHeader(
          delegate: _HeaderDelegate(height: 48),
          floating: true,                   // (*)
          pinned: false,
        ),
        SliverList(
          delegate: SliverChildBuilderDelegate(
            (_, int index) {
              return ListTile(
                leading: Container(
                  padding: const EdgeInsets.all(8),
                  width: 100,
                  child: const Placeholder(),
                ),
                title: Text('Place ${index + 1}', textScaleFactor: 2),
              );
            },
            childCount: 20,
          ),
        ),
      ],
    );
  }
}

void main() {
  runApp(
    const MaterialApp(
      home: Scaffold(
        body: SafeArea(
          child: SliverPage(),
        ),
      ),
    ),
  );
}
```

</details>

### Screenshot

See the faint white line above the "Click me" button:

![image](https://github.com/flutter/flutter/assets/811305/a1661344-16eb-4f46-b62b-5ef4f8c64680)

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.10.5, on Fedora Linux 38 (Workstation Edition) 6.3.6-200.fc38.x86_64, locale en_US.utf8)
    • Flutter version 3.10.5 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (2 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/luke/Android/Sdk
    • Platform android-UpsideDownCake, build-tools 33.0.1
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.5 (Fedora 16.0.5-1.fc38)
    • cmake version 3.26.4
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[✓] Android Studio (version 2022.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.66.0

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)            • linux         • linux-x64      • Fedora Linux 38 (Workstation Edition) 6.3.6-200.fc38.x86_64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by Mohamed-Aziz-Mhadhbi** [comment]
By setting ``floating`` to ``false`` for both the ``SliverAppBar`` and ``SliverPersistentHeader``, they will remain fixed at the top and won't introduce a gap between them.

**Comment by lukehutch** [comment]
That's not a solution -- I need both to be floating.

**Comment by Mohamed-Aziz-Mhadhbi** [comment]
Ok, maybe you can achieve this by setting the ``collapsedHeight`` property of the ``SliverAppBar`` to a smaller value .

example : 

```
SliverAppBar(
          expandedHeight: 100,
          collapsedHeight: 48, // Set a smaller value
          title: Text('Title text'),
          floating: true,
          pinned: false,
          snap: false,
          backgroundColor: Colors.amber,
          // Make the hamburger menu icon white
          iconTheme: IconThemeData(color: Colors.white),
        ),
```

**Comment by jonahwilliams** [comment]
Assuming that you're running on a non-Impeller backend, this is most likely to be https://github.com/flutter/flutter/issues/14288

In short, this is due to the specific implementation of anti aliasing in the Skia backend. The impeller backend only uses MSAA which does not have this issue, and rolling that out everywhere should fix the issue.

**Comment by lukehutch** [comment]
@jonahwilliams I'm on Android -- you're right, I tried Impeller and it solved the issue.

(Some of the rendering doesn't work on Impeller, so I'm guessing it's still not quite ready yet...)

I'll close this, since Impeller will be the default on Android sometime in the future. Thanks!

**Comment by jonahwilliams** [comment]
Yeah, Android is hard! 🙃 😄  soon though.
