### ISSUE TITLE
[flutter_tools] "Unknown flutter tag" crash during `flutter upgrade`

### ISSUE THREAD

**Issue by dotupNET** [flutter/flutter#133441]
**Edit by @christopherfujino** This is a bug in the tool. Currently known safe workarounds to upgrade are to:

1. flutter upgrade --force
2. change your terminal's working directory to your Flutter SDK repo (you can find this under `flutter doctor -v`), then run `flutter upgrade`

A hotfix is currently being worked on, however, users will still need to use these workarounds to get it.

---

### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run "flutter upgrade" on 3.13.0 stable

### Actual results

I got this error:

`
Unknown flutter tag. Abandoning upgrade to avoid destroying local changes. It is recommended to use git directly if not working on an official channel.
`

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

xxx ~ % flutter doctor -v
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.5 22G74 darwin-arm64, locale de-DE)
    • Flutter version 3.13.0 on channel stable at /Users/xxx/data/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (12 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/xxx/Library/Android/Sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/xxx/Library/Android/Sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 60.1.2
    • Dart plugin version 203.8292

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • Nokia 5 4 (mobile) • GZQL1849FAL41701508 • android-arm64  • Android 12 (API 31)
    • macOS (desktop)    • macos               • darwin-arm64   • macOS 13.5 22G74 darwin-arm64
    • Chrome (web)       • chrome              • web-javascript • Google Chrome 116.0.5845.110

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by dam-ease** [comment]
Hi @dotupNET. Thanks for filing this. Please try running `flutter upgrade --force` instead to see it works in your case

**Comment by dotupNET** [comment]
> Hi @dotupNET. Thanks for filing this. Please try running `flutter upgrade --force` instead to see it works in your case

Hi. I know this Flag. But this is not the expected behaviour. I didn't change anything.

**Comment by mjauernig** [comment]
Same error here. Like @dotupNET didn't change anything. With `--force` the upgrade where installed.

**Comment by sorich87** [comment]
I upgraded to `--force` but wanted to report I unexpectedly got the same error too, as I didn't make local changes (I installed 3.13.0 from scratch a couple of weeks ago).

**Comment by MHTpro** [comment]
I have the same error and didn't change anything. And I upgraded with this command: flutter upgrade -f

**Comment by pastelcode** [comment]
Same error. Could upgrade with `flutter upgrade --force`.

**Comment by MikeAngelE** [comment]
Having the same issue. Flutter doesn't seem to want to build the app on the Pixel_3a emulator until the upgrade is done?

**Comment by danagbemava-nc** [comment]
Hi all, with the release of 3.13.1, can anyone check if they hit this issue when they try to upgrade?

**Comment by leidig54** [comment]
Just tried and no luck for me. 

`Unknown flutter tag. Abandoning upgrade to avoid destroying local changes. It is recommended to use git directly if not
working on an official channel.`

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.5 22G74 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.81.1)
[✓] Connected device (1 available)
[✓] Network resources

• No issues found!
```

**Comment by yackers** [comment]
> Hi all, with the release of 3.13.1, can anyone check if they hit this issue when they try to upgrade?

After force upgrade from 3.13.0 to 3.13.1 ,  `flutter upgrade` working as expected

```
D:\Projects\Flutter\> flutter upgrade
Flutter is already up to date on channel stable
Flutter 3.13.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e1e47221e8 (6 days ago) • 2023-08-22 21:43:18 -0700
Engine • revision b20183e040
Tools • Dart 3.1.0 • DevTools 2.25.0
```

**Comment by TheManuz** [comment]
Facing the same problem.

Solved with `flutter upgrade --force`.

**Comment by smunoz-ml** [comment]
> Same error. Could upgrade with `flutter upgrade --force`.

**Comment by ahmeedev** [comment]
> 

yeah, that works

**Comment by Gufdoor** [comment]
I did the following and it worked (credits for Lano):

On the directory where Flutter is located:
1. Open terminal
2. If your current Flutter version isn't stable, run the following: **git checkout stable**
3. Later, run the following: **git pull**
4. Check your current version: flutter --version
5. If still not on latest version, run: flutter upgrade

Hope it works!

**Comment by denn319** [comment]
`flutter upgrade --force` works for me.

**Comment by dam-ease** [comment]
Hi everyone, thanks for your responses. I am able to reproduce this same behaviour on the `stable` channel, but can't reproduce it on `master`.  Upgrade works after running `flutter upgrade --force`.

**Comment by WorikQCI** [comment]
So we have to use `--force`, no other explanation?  

I am *very* uneasy about that and I will hold off.

What is the issue?

**Comment by christopherfujino** [comment]
> So we have to use `--force`, no other explanation?
> 
> I am _very_ uneasy about that and I will hold off.
> 
> What is the issue?

I have assigned this issue to myself, and I would also like an explanation :) If you'd like to help debug this, I would appreciate if you would share the output of:

```
# log the last 20 commits on the current branch, including any local tags
git log --tags --pretty="%h %d" | head -n 20

# print all local branches, including what they are tracking
git branch -vv

# print all remote repos the local repo is tracking, and what they're named
git remote -v
```

I have not been able to reproduce this locally, so seeing the state of your repo would help me figure out where things went wrong.

Finally, I'll add that `flutter upgrade` is completely safe in this situation. It will skip this check, which is to verify you haven't committed any local changes to your SDK.

**Comment by WorikQCI** [comment]
I had no idea I was running flutter from a git repo

Using `whereis flutter` and changing directory to there...


```bash
flutter % git status
On branch stable
Your branch is behind 'origin/stable' by 4 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit, working tree clean
user@B52SwampMac flutter % git log --tags --pretty="%h %d" | head -n 20

ff5b5b5fa6  (tag: 3.13.2, origin/stable, origin/flutter-3.13-candidate.0)
dc7fa47324  (tag: 3.14.0-11.0.pre, origin/flutter-3.14-candidate.11)
87c1a461e1 
cfe41a6451 
8c69fd550c 
89907f6da3 
382ceb5707  (origin/flutter-3.14-candidate.10)
4930613999 
6fd3387977 
9e59a68c98 
ad78cf3506 
3cfaa34f7d 
fd155a34e4 
d8b1e81c1f 
8ba40bb19b 
bd836cc63a 
575fd7ee22 
4bbcb780a6 
e1e47221e8  (tag: 3.13.1)
88290989a1 
```

```bash
flutter % git branch -vv

* stable efbf63d9c6 [origin/stable: behind 4] [flutter_releases] Flutter stable 3.13.0 Framework Cherrypicks (#132610)
```

```bash
 flutter % git remote -v

origin	https://github.com/flutter/flutter.git (fetch)
origin	https://github.com/flutter/flutter.git (push)
```

HTH

**Comment by WorikQCI** [comment]
`Your branch is behind 'origin/stable' by 4 commits`

Golly.  That is where `upgrade` comes in?

**Comment by christopherfujino** [comment]
@WorikQCI Oops, I'm sorry, I gave you the wrong command. Can you instead share:

```
git log --pretty="%h %d" | head -n 20
```

Apparently the `--tags` flag doesn't do what I thought it did :)

**Comment by christopherfujino** [comment]
> ```
>  flutter % git log --pretty="%h %d" | head -n 20
> 
> efbf63d9c6  (HEAD -> stable, tag: 3.13.0)
> 53841b2cc1 
> ff8ade8b77 
> 54040e6041 
> 0ea0979cc2 
> 7e07cd41cb  (tag: 3.13.0-0.4.pre)
> 95b3a3ed98 
> 85127f4f94 
> f4c42610bb 
> 5c4bfbcc85 
> e90f5d4561  (tag: 3.13.0-0.3.pre)
> 1f0b77f3fd 
> 945b12da6a 
> ac71592bc6  (tag: 3.13.0-0.2.pre)
> 1dc07d26fc 
> 1f6bdb6fa2  (tag: 3.13.0-0.1.pre)
> 257a29931c  (tag: 3.13.0-0.0.pre)
> 761810a0bf 
> bff6b93683 
> 4f6c887751 
> ```

Everything looks good here.

After meeting with some coworkers to discuss this, we have another theory. Can you share the contents of:

```
cat flutter/bin/cache/flutter.version.json
```

Where you update that path to point to your Flutter SDK. I think the issue might be introduced to https://github.com/flutter/flutter/pull/124558, where we cache the computation of hte Flutter version to `flutter/bin/cache/flutter.version.json`. If for some reason at the time we write that file the local git repo doesn't have the right tag, we might be writing an invalid version to disk.

**Comment by ducdx-0072** [comment]
I faced the same error. Although I can upgrade with option --force, it's an error. I don't change anything and am still in the stable channel

**Comment by CaseyHillers** [comment]
I'm still having a difficult time reproducing. I've created the following script (with minor tweaks) and run it on Mac+Linux to no avail.

```sh
#!/bin/bash
set -ex
# The issue happens on flutter upgrade, so start with an older version and go forward
# Our theory is this started on the 3.13.0-0.1.pre beta by https://github.com/flutter/flutter/pull/124558
# Download 3.13.0
wget https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_arm64_3.13.0-stable.zip
unzip flutter_macos_arm64_3.13.0-stable.zip
pushd flutter
# Warm the version cache
./bin/flutter --version
# Upgrade to 3.13.2, should throw an error
./bin/flutter upgrade
./bin/flutter --version
popd
rm -rf flutter*
```

To help us reproduce, can folks include their `flutter doctor` output and their `git --version`?

**Comment by glinesbdev** [comment]
I was getting the same error with `flutter upgrade`. Since I installed flutter via Homebrew, I just had to run `homebrew upgrade flutter` to get the changes to 3.13.1.

**Comment by NSHuman** [comment]
I'm getting the same error.

git version 2.41.0.windows.3

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.0, on Microsoft Windows [Version 10.0.22621.2134], locale en-US)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.1)
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

**Comment by ashiqaliaslam** [comment]
Same error here

```bash
% flutter upgrade
Unknown flutter tag. Abandoning upgrade to avoid destroying local changes. It is
recommended to use git directly if not working on an official channel.
```

**Comment by aerocyber** [comment]
> > ```
> >  flutter % git log --pretty="%h %d" | head -n 20
> > 
> > efbf63d9c6  (HEAD -> stable, tag: 3.13.0)
> > 53841b2cc1 
> > ff8ade8b77 
> > 54040e6041 
> > 0ea0979cc2 
> > 7e07cd41cb  (tag: 3.13.0-0.4.pre)
> > 95b3a3ed98 
> > 85127f4f94 
> > f4c42610bb 
> > 5c4bfbcc85 
> > e90f5d4561  (tag: 3.13.0-0.3.pre)
> > 1f0b77f3fd 
> > 945b12da6a 
> > ac71592bc6  (tag: 3.13.0-0.2.pre)
> > 1dc07d26fc 
> > 1f6bdb6fa2  (tag: 3.13.0-0.1.pre)
> > 257a29931c  (tag: 3.13.0-0.0.pre)
> > 761810a0bf 
> > bff6b93683 
> > 4f6c887751 
> > ```
> 
> Everything looks good here.
> 
> After meeting with some coworkers to discuss this, we have another theory. Can you share the contents of:
> 
> ```
> cat flutter/bin/cache/flutter.version.json
> ```
> 
> Where you update that path to point to your Flutter SDK. I think the issue might be introduced to #124558, where we cache the computation of hte Flutter version to `flutter/bin/cache/flutter.version.json`. If for some reason at the time we write that file the local git repo doesn't have the right tag, we might be writing an invalid version to disk.

Output of `cat flutter/bin/cache/flutter.version.json`

```bash
{
  "frameworkVersion": "3.13.1",
  "channel": "stable",
  "repositoryUrl": "https://github.com/flutter/flutter.git",
  "frameworkRevision": "e1e47221e86272429674bec4f1bd36acc4fc7b77",
  "frameworkCommitDate": "2023-08-22 21:43:18 -0700",
  "engineRevision": "b20183e04096094bcc37d9cde2a4b96f5cc684cf",
  "dartSdkVersion": "3.1.0",
  "devToolsVersion": "2.25.0",
  "flutterVersion": "3.13.1"
}
```

**Comment by ashiqaliaslam** [comment]
> > > ```
> > >  flutter % git log --pretty="%h %d" | head -n 20
> > > 
> > > efbf63d9c6  (HEAD -> stable, tag: 3.13.0)
> > > 53841b2cc1 
> > > ff8ade8b77 
> > > 54040e6041 
> > > 0ea0979cc2 
> > > 7e07cd41cb  (tag: 3.13.0-0.4.pre)
> > > 95b3a3ed98 
> > > 85127f4f94 
> > > f4c42610bb 
> > > 5c4bfbcc85 
> > > e90f5d4561  (tag: 3.13.0-0.3.pre)
> > > 1f0b77f3fd 
> > > 945b12da6a 
> > > ac71592bc6  (tag: 3.13.0-0.2.pre)
> > > 1dc07d26fc 
> > > 1f6bdb6fa2  (tag: 3.13.0-0.1.pre)
> > > 257a29931c  (tag: 3.13.0-0.0.pre)
> > > 761810a0bf 
> > > bff6b93683 
> > > 4f6c887751 
> > > ```
> > 
> > 
> > Everything looks good here.
> > After meeting with some coworkers to discuss this, we have another theory. Can you share the contents of:
> > ```
> > cat flutter/bin/cache/flutter.version.json
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Where you update that path to point to your Flutter SDK. I think the issue might be introduced to #124558, where we cache the computation of hte Flutter version to `flutter/bin/cache/flutter.version.json`. If for some reason at the time we write that file the local git repo doesn't have the right tag, we might be writing an invalid version to disk.
> 
> Output of `cat flutter/bin/cache/flutter.version.json`
> 
> ```shell
> {
>   "frameworkVersion": "3.13.1",
>   "channel": "stable",
>   "repositoryUrl": "https://github.com/flutter/flutter.git",
>   "frameworkRevision": "e1e47221e86272429674bec4f1bd36acc4fc7b77",
>   "frameworkCommitDate": "2023-08-22 21:43:18 -0700",
>   "engineRevision": "b20183e04096094bcc37d9cde2a4b96f5cc684cf",
>   "dartSdkVersion": "3.1.0",
>   "devToolsVersion": "2.25.0",
>   "flutterVersion": "3.13.1"
> }
> ```

yes here it is the contents of  `cat flutter/bin/cache/flutter.version.json` 
```json
{
  "frameworkVersion": "3.13.0",
  "channel": "stable",
  "repositoryUrl": "https://github.com/flutter/flutter.git",
  "frameworkRevision": "efbf63d9c66b9f6ec30e9ad4611189aa80003d31",
  "frameworkCommitDate": "2023-08-15 21:05:06 -0500",
  "engineRevision": "1ac611c64eadbd93c5f5aba5494b8fc3b35ee952",
  "dartSdkVersion": "3.1.0",
  "devToolsVersion": "2.25.0",
  "flutterVersion": "3.13.0"
}
```

**Comment by WorikQCI** [comment]
> cat flutter/bin/cache/flutter.version.json

```
 % cat flutter/bin/cache/flutter.version.json
{
  "frameworkVersion": "3.13.0",
  "channel": "stable",
  "repositoryUrl": "https://github.com/flutter/flutter.git",
  "frameworkRevision": "efbf63d9c66b9f6ec30e9ad4611189aa80003d31",
  "frameworkCommitDate": "2023-08-15 21:05:06 -0500",
  "engineRevision": "1ac611c64eadbd93c5f5aba5494b8fc3b35ee952",
  "dartSdkVersion": "3.1.0",
  "devToolsVersion": "2.25.0",
  "flutterVersion": "3.13.0"
}%                             
```

**Comment by HandsonOmbiro** [comment]
> Hi @dotupNET. Thanks for filing this. Please try running `flutter upgrade --force` instead to see it works in your case

yes --force works but as reported earlier, there is a new bug which throws the reported error if you do not use --force, 
Unknown flutter tag. Abandoning upgrade to avoid destroying local changes. It is recommended to use git directly if
not working on an official channel. This came with the upgrade to 3.13.0

beyond this, the 3.13.0 came with other bugs yet to be resolved: (though resolved and merged to Master, it is yet to be in the stable, hope it is also tested: [https://github.com/firebase/flutterfire/pull/11514](url)

**Comment by danagbemava-nc** [comment]
I want to point out that this also happens with the upgrade from 3.13.1 to 3.13.2 

<details>
<summary>logs</summary>

```
nexus@Daniels-MBP nevercode %flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.4.1 22F770820d darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
[✓] VS Code (version 1.81.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
nexus@Daniels-MBP nevercode % flutter upgrade
Unknown flutter tag. Abandoning upgrade to avoid destroying local changes. It is recommended to use git directly if not working on an official channel.
nexus@Daniels-MBP nevercode % flutter upgrade --force
Upgrading Flutter to 3.13.2 from 3.13.1 in /Users/nexus/dev/sdks/flutter...
Building flutter tool...
Resolving dependencies...
Got dependencies.

Upgrading engine...

Flutter 3.13.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ff5b5b5fa6 (7 days ago) • 2023-08-24 08:12:28 -0500
Engine • revision b20183e040
Tools • Dart 3.1.0 • DevTools 2.25.0

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.4.1 22F770820d darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
[✓] VS Code (version 1.81.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```
</details>

**Comment by mohamedsalah414** [comment]
I have the same error
```
flutter upgrade -v
[ +139 ms] executing: git tag --points-at HEAD
[  +92 ms] Exit code 128 from: git tag --points-at HEAD
[        ] fatal: not a git repository (or any of the parent directories): .git
[   +1 ms] executing: git describe --match *.*.* --long --tags HEAD
[  +78 ms] Exit code 128 from: git describe --match *.*.* --long --tags HEAD
[        ] fatal: not a git repository (or any of the parent directories): .git
[        ] Could not interpret results of "git describe":
[   +3 ms] executing: [C:\src\flutter/] git fetch --tags
[+1192 ms] executing: [C:\src\flutter/] git rev-parse --verify @{upstream}
[  +86 ms] ff5b5b5fa6f35b717667719ddfdb1521d8bdd05a
[   +1 ms] executing: [C:\src\flutter/] git tag --points-at ff5b5b5fa6f35b717667719ddfdb1521d8bdd05a
[ +105 ms] Exit code 0 from: git tag --points-at ff5b5b5fa6f35b717667719ddfdb1521d8bdd05a
[        ] 3.13.2
[  +12 ms] "flutter upgrade" took 1,624ms.
[   +6 ms] Unknown flutter tag. Abandoning upgrade to avoid destroying local changes. It is recommended to use git directly if not working on an
official channel.
[   +8 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      UpgradeCommandRunner.runCommandFirstHalf (package:flutter_tools/src/commands/upgrade.dart:142:9)
           <asynchronous suspension>
           #2      UpgradeCommandRunner.runCommand (package:flutter_tools/src/commands/upgrade.dart:102:7)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[ +269 ms] ensureAnalyticsSent: 251ms
[   +2 ms] Running 0 shutdown hooks
[   +3 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

**Comment by LAPPIT** [comment]
I have the same problem :( 
Worked with flutter upgrade --force :)
Had a fresh Flutter SDK, downloaded last week (when I had the same problem) and no changes after that.

**Comment by 4ddev** [comment]
Same here on mac
```

[   +3 ms] executing: sw_vers -productName
[  +12 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[   +7 ms] Exit code 0 from: sw_vers -productVersion
[        ] 13.4.1
[        ] executing: sw_vers -buildVersion
[   +7 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 22F770820d
[        ] executing: uname -m
[   +3 ms] Exit code 0 from: uname -m
[        ] arm64
[   +4 ms] executing: sysctl hw.optional.arm64
[   +2 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[  +46 ms] executing: git tag --points-at HEAD
[   +7 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] executing: git describe --match *.*.* --long --tags HEAD
[   +5 ms] Exit code 128 from: git describe --match *.*.* --long --tags HEAD
[        ] Schwerwiegend: Keine Namen gefunden, kann nichts beschreiben.
[        ] Could not interpret results of "git describe": 
[   +1 ms] executing: [/opt/homebrew/Caskroom/flutter/3.13.0/flutter/] git fetch --tags
[ +686 ms] executing: [/opt/homebrew/Caskroom/flutter/3.13.0/flutter/] git rev-parse --verify @{upstream}
[   +6 ms] ff5b5b5fa6f35b717667719ddfdb1521d8bdd05a
[        ] executing: [/opt/homebrew/Caskroom/flutter/3.13.0/flutter/] git tag --points-at ff5b5b5fa6f35b717667719ddfdb1521d8bdd05a
[   +7 ms] Exit code 0 from: git tag --points-at ff5b5b5fa6f35b717667719ddfdb1521d8bdd05a
[        ] 3.13.2
[   +4 ms] "flutter upgrade" took 751ms.
[   +2 ms] Unknown flutter tag. Abandoning upgrade to avoid destroying local changes. It is recommended to use git directly if not working on an official channel.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      UpgradeCommandRunner.runCommandFirstHalf (package:flutter_tools/src/commands/upgrade.dart:142:9)
           <asynchronous suspension>
           #2      UpgradeCommandRunner.runCommand (package:flutter_tools/src/commands/upgrade.dart:102:7)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[  +60 ms] ensureAnalyticsSent: 55ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```
```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.4.1 22F770820d darwin-arm64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.81.1)
[✓] VS Code (version 1.74.2)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.

```

**Comment by christoph-zenger-hcsg** [comment]
For me the upgrade worked when running it in the flutter install directory.
It did not work when running it in the directory of my flutter aplication.

It appears to me that it fails when running the upgrade command in the directory of my flutter application when my flutter application has uncommitted files.

**Comment by NirmalAriyathilake** [comment]
I had the same error when trying to upgrade to 3.13.2 from 3.13.0. 

@christoph-zenger-hcsg Thanks for the suggestion.

Running `flutter upgrade` from the flutter directory works, but fails from any other directory.

**Comment by smith558** [comment]
```
stanley@hp-stanley:~$ flutter upgrade
Unknown flutter tag. Abandoning upgrade to avoid destroying local changes. It is recommended to use
git directly if not working on an official channel.
stanley@hp-stanley:~$ flutter upgrade --force
Upgrading Flutter to 3.13.2 from 3.13.1 in /home/stanley/snap/flutter/common/flutter...
Building flutter tool...
Resolving dependencies...
Got dependencies.

Upgrading engine...

Flutter 3.13.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ff5b5b5fa6 (7 days ago) • 2023-08-24 08:12:28 -0500
Engine • revision b20183e040
Tools • Dart 3.1.0 • DevTools 2.25.0

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.2, on Ubuntu 23.04 6.2.0-31-generic, locale en_GB.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.3)
[✓] VS Code (version unknown)
    ✗ Unable to determine VS Code version.
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
stanley@hp-stanley:~$ 

```

**Comment by christopherfujino** [comment]
> For me the upgrade worked when running it in the flutter install directory. It did not work when running it in the directory of my flutter aplication.
> 
> It appears to me that it fails when running the upgrade command in the directory of my flutter application when my flutter application has uncommitted files.

Ahh, thanks for this clue! This whole time my current working directory when I run `flutter upgrade` has been within the Flutter SDK repo, thus I could not reproduce. I'm investigating now, but it seems like I introduced a git callsite and forgot to set the working directory explicitly to the Flutter repo.

**Comment by WorikQCI** [comment]
Still not working.  

Is this a problem in:

```
Flutter 3.13.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision efbf63d9c6 (2 weeks ago) • 2023-08-15 21:05:06 -0500
Engine • revision 1ac611c64e
Tools • Dart 3.1.0 • DevTools 2.25.0
```

so to upgrade I do what exactly?

**Comment by christopherfujino** [comment]
> so to upgrade I do what exactly?

Unfortunately you will need to either do a `flutter upgrade --force` or change your working directory to the Flutter repo. My fix will not apply for you until AFTER you get it.

Also note, that I haven't cherrypicked the fix to stable yet. So even if you use the workaround today, you will still need to use the workaround for the next hotfix release to get the fix.

**Comment by WorikQCI** [comment]
Ok.

It is what it is.

Thank you for your attention
