### ISSUE TITLE
ListView stutters when scrolling (noticeable and consistent stuttering).  

### ISSUE THREAD

**Issue by pkumar8888** [flutter/flutter#134400]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Using the latest Master Flutter channel. and iOS 16.6 (even iOS 16.6.1)
2. Created a basic Flutter app with a simple ListView.builder widget
3. Running the App in debug or even release mode, it can be observed that the ListView is stuttering (noticeable and consistent stuttering) when scrolling. This used to happen before when Promotion devices just came out but was also fixed quite some time ago. But apparently this issue has resurfaced.

### Expected results

This is a simple ListView. Scrolling should be smooth and consistent at 120Hz. 

### Actual results

For some reason, display stays at 120Hz when not scrolling but as soon as I start scrolling the refresh rate is all over the place as seen in the video. This causes stuttering which is quite annoying and noticeable. Also this stuttering is very consistent and continuous. This has started recently. I am not sure if it is due to iOS 16.6. I am running iOS 16.6.1.

### Code sample

<details><summary>Simple ListView scroll stutter example</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: ListApp(),
    );
  }
}

class ListApp extends StatelessWidget {
  const ListApp({super.key});

  @override
  Widget build(BuildContext context) {
    final width = MediaQuery.of(context).size.width;
    final height = MediaQuery.of(context).size.height;
    return Scaffold(
      body: Center(
        child: ListView.builder(
          shrinkWrap: true,
          primary: false,
          itemBuilder: (context, index) {
            return Padding(
              padding:
                  const EdgeInsets.symmetric(horizontal: 32.0, vertical: 32),
              child: Container(
                width: width * 0.8,
                height: height * 0.3,
                decoration: BoxDecoration(
                    color: Colors.purple,
                    borderRadius: BorderRadius.circular(15)),
              ),
            );
          },
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/49350919/8b1f5919-5e6e-446a-9efb-cb0ef98bfd89

</details>

### Logs

<details><summary>Logs</summary>

```console

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.14.0-14.0.pre.211, on macOS 13.5 22G74
    darwin-arm64, locale en-IN)
    • Flutter version 3.14.0-14.0.pre.211 on channel master at
      /Users/pankajkumar/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 69f6e7d15d (40 minutes ago), 2023-09-11 00:50:38 -0400
    • Engine revision 7e41b064eb
    • Dart version 3.2.0 (build 3.2.0-134.0.dev)
    • DevTools version 2.27.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/pankajkumar/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/pankajkumar/Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Users/pankajkumar/Library/Mobile
      Documents/com~apple~CloudDocs/Desktop/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Users/pankajkumar/Applications/Android Studio Iguana
      2023.2.1 Canary 3.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.8+0-17.0.8b1000.8-10699129)

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/pankajkumar/Applications/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[!] Android Studio (version unknown)
    • Android Studio at /Users/pankajkumar/Applications/Android Studio Hedgehog
      2023.1.1 Beta 3.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Community Edition (version 2023.2.1)
    • IntelliJ at /Users/pankajkumar/Applications/IntelliJ IDEA Community
      Edition.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.9559.10

[✓] VS Code (version 1.70.1)
    • VS Code at /Users/pankajkumar/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • iPhone 13 Pro Max (mobile)  • ios
      • iOS 16.6.1 20G81
    • macOS (desktop)                     • macos                     •
      darwin-arm64   • macOS 13.5 22G74 darwin-arm64
    • Chrome (web)                        • chrome                    •
      web-javascript • Google Chrome 116.0.5845.179

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by dam-ease** [comment]
Hi @pkumar8888. Thanks for filing this. This seems to be similar to https://github.com/flutter/flutter/issues/131319 whose fix was cherry-picked in `3.10.7` version as mentioned in the last comments of that issue. Kindly check out [this](https://github.com/flutter/flutter/issues/131319#issuecomment-1683070516) comment and [this](https://github.com/flutter/flutter/issues/131319#issuecomment-1686877394) for more information on this.
Closing this as this seems to be a known issue which has been fixed, if you disagree, kindly comment and I'll reopen this.
Thank you!

**Comment by pkumar8888** [comment]
Hi..I just checked the case #131319. But I would like to be on the latest flutter version and not on the 3.10 branch. This issue was non existent on 3.14 earlier versions (not sure exactly which version brought about this stuttering). 
So I would like to know what are the plans and priority for this issue on version 3.14 and higher, Because this is more or less a show stopper for my startup at this point.

**Comment by dam-ease** [comment]
Hi @pkumar8888. Sorry about that, per this https://github.com/flutter/flutter/issues/131319#issuecomment-1683070516, I guess for this to work well if you would like to remain on a stable channel, you'd need to be on the `3.10.7`. 
You might also want to read more about how bug fix releases work here: https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#will-a-particular-bug-fix-be-provided-in-a-hotfix-release (and whole that page for more info)

**Comment by jwogan5** [comment]
I am still having this issue on the newly released 3.14.  People are saying its fixed in 3.13 but im on the latest and the stutter is still there.

**Comment by pkumar8888** [comment]
I am also wondering why is the fix not yet included in the latest flutter version ( let it be stable or the master channel).
Also surprised why this is not on the top priority as this issue is definitely affecting all the iOS devices on iOS 16.6 .

**Comment by jwogan5** [comment]
After doing some more research I found these open issues.

https://github.com/flutter/flutter/issues/134309

https://github.com/flutter/flutter/issues/134242

It seems that the fix 3.10.7 was causing some crashes so it was reverted back to the jank issue so that apps wouldn't crash. At this time they are still looking for a proper fix to address both the stuttering and the crashes caused by the first fix.

It is a little frustrating how far I had to dig to get a simple answer to why the first fix was reverted in all of the newer releases of Flutter.  Also, this issue has been around for over a month now so I hope a fix comes soon.  My work app on every screen with a listview or CustomScrollView stutters so much that it is very distracting to the end user making our app look very unprofessional.  I just spent a few days trying to re-engineer some of the screens as small as possible to try to mitigate some of the stutter but that only helped a tiny bit.  I have one screen which is just a listview of 10 rows and that stutters. I really hope they find a fix to this issue soon as most apps have listviews.

**Comment by sz7i** [comment]
> I am still having this issue on the newly released 3.14. People are saying its fixed in 3.13 but im on the latest and the stutter is still there. I am looking at the engine change made in 3.10.7 and that change is not in the 3.13 candidates. Wouldn't a fix go into the latest and greatest release.

The fix has been reverted by the flutter team in 3.13.3 (see https://github.com/flutter/flutter/issues/134309#issuecomment-1712513231). We had to downgrade to 3.13.2. But please be aware that picking a video may crash in 3.13.2 (see https://github.com/flutter/flutter/issues/133147)
