### ISSUE TITLE
Performance degradation on high frame rate devices (IPhone 14 Pro) using the latest version of flutter master

### ISSUE THREAD

**Issue by gianfrancopapa** [flutter/flutter#134786]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Very noticeable performance degradation on high frame rate devices (IPhone 14 Pro)  using the latest version of flutter master (Flutter version 3.14.0-14.0.pre.274) compared with flutter stable versions (this comparison was made with 3.13.0)

1. Download latest version of the master branch of Wonderous app
2. Download Flutter version 3.14.0-14.0.pre.274
3. Run Wonderous app using that Flutter version on a High-end iOS device (iPhone 14 pro - IOS 16.6.1) on profile mode
4. Open the Performance Tab of the Flutter Dev Tools

### Expected results

![Screenshot 2023-09-14 at 17 08 54](https://github.com/flutter/flutter/assets/63058517/24a48298-cfdf-4c24-9343-afd985aae6ce)
[Screenshot 1]: Performance Tab of Flutter Dev Tools using Flutter version 3.13.0
Janks: 6
FPS average: 113

### Actual results

![Screenshot 2023-09-14 at 17 19 45](https://github.com/flutter/flutter/assets/63058517/eedeec37-fa44-4f5d-b743-c886a2d77c7a)

[Screenshot 2]: Performance Tab of Flutter Dev Tools using Flutter version 3.14.0-14.0.pre.274
Janks: 305
FPS average: 93

### Code sample

<details><summary>Code sample</summary>

https://github.com/gskinnerTeam/flutter-wonderous-app

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/63058517/a19f36cb-e3fc-4f99-beb1-60ebece390c2

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
Launching lib/main.dart on Somnio’s iPhone in profile mode...
main.dart:1
Automatically signing iOS for device deployment using specified development team in Xcode project: 33P98UGP6U
Xcode build done. 14.0s
(lldb) warning: libobjc.A.dylib is being read from process memory. This indicates that LLDB could not find the on-disk shared cache for this device. This will likely reduce debugging performance.
The Dart VM Service was not discovered after 30 seconds. This is taking much longer than expected...
process interrupt
error: Failed to halt process: Halt timed out. State = running
* thread #1, stop reason = signal SIGSTOP
frame #0: 0x00000001c8635164 dyld`_dyld_debugger_notification
dyld`:
-> 0x1c8635164 <+0>: ret
dyld`dyld4::Atlas::Bitmap::Bitmap:
0x1c8635168 <+0>: pacibsp
0x1c863516c <+4>: sub sp, sp, #0x50
0x1c8635170 <+8>: stp x24, x23, [sp, #0x10]
Target 0: (Runner) stopped.
(lldb) 2023-09-14 17:39:45.068588-0300 Runner[800:108304] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
flutter: bootstrap start...
flutter: Navigate to: /
flutter: Saving...
flutter: Navigate to: /home
Connecting to VM Service at ws://127.0.0.1:51985/YyRBah2wsN4=/ws
flutter: Saving...
flutter: Navigate to: /wonder/greatWall?t=0

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.14.0-14.0.pre.274, on macOS 13.5.2 22G91 darwin-arm64 (Rosetta), locale en-UY)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2023.2.1)
[✓] VS Code (version 1.82.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by zanderso** [comment]
Unfortunately, this is expected due to a bug in iOS introduced in version 16.6. However, we've had reports that the issue is resolved in iOS 17. It would be valuable to know whether this reproduces after updating iOS to version 17.

**Comment by zhangyanzhu88** [comment]
I had the same problem.
Is solved?

**Comment by hadysata** [comment]
Same issue here

**Comment by rzambroni** [comment]
Hi @zanderso, thanks for the feedback. We updated to IOS 17 and ran the same test again. There is definitely some improvement but still not great, compared with Flutter stable versions.


![image](https://github.com/flutter/flutter/assets/54465214/71121eac-23c1-4282-8764-81b17b7e2040)

Flutter: Channel master, 3.14.0-14.0.pre.312   
Janks: 96
AVG FPS: 111

**Comment by zanderso** [comment]
FYI @jonahwilliams

**Comment by jonahwilliams** [comment]
That seems great? Most frames are in budget

**Comment by stuartmorgan** [comment]
Should we dup this against https://github.com/flutter/flutter/issues/134959 ?

**Comment by jonahwilliams** [comment]
We had to lock the last issue and so I'd rather not lead more users to commenting on what you should be a technical discussion

**Comment by chinmaygarde** [comment]
As far as we can tell, this issue was introduced in 16.6 and fixed in 17.0 on high refresh rate devices. De-duping against https://github.com/flutter/flutter/issues/134959 for just this one iOS version.
