### ISSUE TITLE
Allow variable-sized GridView widgets

### ISSUE THREAD

**Issue by maryx** [flutter/flutter#13777]
This is a feature request.
Can we have variable-sized (non-square) GridView widgets? E.g. the example from https://docs.flutter.io/flutter/widgets/GridView-class.html:
```
new GridView.count(
  primary: false,
  padding: const EdgeInsets.all(20.0),
  crossAxisSpacing: 10.0,
  crossAxisCount: 2,
  children: <Widget>[
    const Text('He\'d have you all unravel at the'),
    const Text('Heed not the rabble'),
    const Text('Sound of screams but the'),
    const Text('Who scream'),
    const Text('Revolution is coming...'),
    const Text('Revolution, they...'),
  ],
)
```
<img width="311" alt="screen shot 2017-12-27 at 11 32 21 am" src="https://user-images.githubusercontent.com/3357543/34391314-a3782fdc-eaf9-11e7-8263-c8bcddf4c08e.png">

This results in a lot of extra space below the text, since each grid item is square. It would be neat to set the height of each grid item. The simplest would be to set all the grid items to the same height. But we could envision the height being determined based on the height of the child widgets.

We could use a Wrap widget to have child widgets of variable heights, but then there is no scrolling.

**Comment by Hixie** [comment]
If you're using the constructor used by that example, you can set the aspect ratio (`childAspectRatio` argument to `GridView.count`), and each cell will honor it.

If you want more control, you can use the [`GridView.custom`](https://docs.flutter.io/flutter/widgets/GridView/GridView.custom.html) constructor to provide your own [delegate](https://docs.flutter.io/flutter/rendering/SliverGridDelegate-class.html), at which point you get to define the [geometry](https://docs.flutter.io/flutter/rendering/SliverGridLayout-class.html) of each child as you wish.

**Comment by maryx** [comment]
Great thanks! Completely missed `childAspectRatio`; I had only thought to look for a property with `height` in the name.

**Comment by letsar** [comment]
I've just released this plugin: https://pub.dartlang.org/packages/flutter_staggered_grid_view, you can try it out. If it's not exactly what you need, you can find the code here: https://github.com/letsar/flutter_staggered_grid_view

**Comment by SuWe1** [comment]
Hi.After reviewing your answer， i know that using `childAspectRatio` can control the aspect ratio. unfortunately, if I want to use the same layout in ios and android. but `childAspectRatio` can only control one. Do you have any good way?

**Comment by lifetin** [comment]
我也希望能将gridView的高度固定.不要用比例来控制,这样没办法兼容不同的手机
I would also like to keep the height of gridView fixed. Don't use proportionality control, it's not compatible with different mobile phones.

**Comment by 26shruti** [comment]
> If you're using the constructor used by that example, you can set the aspect ratio (`childAspectRatio` argument to `GridView.count`), and each cell will honor it.
> 
> If you want more control, you can use the [`GridView.custom`](https://docs.flutter.io/flutter/widgets/GridView/GridView.custom.html) constructor to provide your own [delegate](https://docs.flutter.io/flutter/rendering/SliverGridDelegate-class.html), at which point you get to define the [geometry](https://docs.flutter.io/flutter/rendering/SliverGridLayout-class.html) of each child as you wish.

Can you provide some link for this implementation?

**Comment by ollydixon** [comment]
Still an issue. I can't find a single example of Gridview.custom, right now the Gridview on flutter is a negative experience.

**Comment by Piinks** [comment]
This is a duplicate of https://github.com/flutter/flutter/issues/97544, which is actively being worked on. Closing to focus conversation and work there.
