### ISSUE TITLE
[camera] taking image without saving it

### ISSUE THREAD

**Issue by guyluz11** [flutter/flutter#137889]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I would like to take a lot of images process them individually and send them off from my app over the network.

Using `cameraController.takePicture()` also saves the picture to the device cache and that is bloating my app 500mb+.

### Proposal

A new function to take pictures without saving them to the device/cache only to a local variable which Flutter garbage collector will clean (as a normal variable) when stops being in use.

The output of the function will be `XFile`.

**Comment by iapicca** [comment]
@guyluz11 
this should so

```dart
import 'dart:async';

import 'package:camera/camera.dart';
import 'package:image/image.dart' as img;

Future<img.Image?> imageFromCameraController(CameraController controller) async {
  final completer = Completer<CameraImage>();
  await controller
      .startImageStream(completer.complete)
      .then((_) => controller.stopImageStream());
  final image = await completer.future;
  final imageBytes = image.planes[0].bytes;
  return img.decodeImage(imageBytes);
}
```

**Comment by guyluz11** [comment]
Looks interesting, it will probably be better to keep the stream open and just take single photos.


I tested your code and it looks like `await completer.future;` never returns a value.
Here is the log


```dart
I/CameraManagerGlobal(31960): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client com.example.cbj_smart_device_flutter API Level 2User Id 0
I/Camera  (31960): startPreviewWithImageStream
I/Camera  (31960): CameraCaptureSession onConfigured
I/Camera  (31960): Updating builder settings
D/Camera  (31960): Updating builder with feature: ExposureLockFeature
I/Camera  (31960): startPreview
W/_device_flutter(31960): Long monitor contention with owner main (31960) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1402) waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$4.run() for 640ms
D/Camera  (31960): Updating builder with feature: ExposurePointFeature
W/_device_flutter(31960): Long monitor contention with owner main (31960) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1402) waiters=1 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onCaptureStarted(android.hardware.camera2.impl.CaptureResultExtras, long) for 612ms
D/Camera  (31960): Updating builder with feature: ZoomLevelFeature
D/Camera  (31960): Updating builder with feature: AutoFocusFeature
D/Camera  (31960): Updating builder with feature: NoiseReductionFeature
I/Camera  (31960): updateNoiseReduction | currentSetting: fast
D/Camera  (31960): Updating builder with feature: FocusPointFeature
D/Camera  (31960): Updating builder with feature: ResolutionFeature
D/Camera  (31960): Updating builder with feature: SensorOrientationFeature
D/Camera  (31960): Updating builder with feature: FlashFeature
D/Camera  (31960): Updating builder with feature: ExposureOffsetFeature
D/Camera  (31960): Updating builder with feature: FpsRangeFeature
I/Camera  (31960): refreshPreviewCaptureSession
I/Camera  (31960): refreshPreviewCaptureSession: captureSession not yet initialized, skipping preview capture session refresh.
I/Camera  (31960): CameraCaptureSession onClosed
I/Camera  (31960): CameraCaptureSession onConfigured
I/Camera  (31960): Updating builder settings
D/Camera  (31960): Updating builder with feature: ExposureLockFeature
D/Camera  (31960): Updating builder with feature: ExposurePointFeature
W/_device_flutter(31960): Long monitor contention with owner main (31960) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1402) waiters=1 in void android.hardware.camera2.impl.CameraDeviceImpl$4.run() for 145ms
D/Camera  (31960): Updating builder with feature: ZoomLevelFeature
D/Camera  (31960): Updating builder with feature: AutoFocusFeature
D/Camera  (31960): Updating builder with feature: NoiseReductionFeature
I/Camera  (31960): updateNoiseReduction | currentSetting: fast
D/Camera  (31960): Updating builder with feature: FocusPointFeature
D/Camera  (31960): Updating builder with feature: ResolutionFeature
D/Camera  (31960): Updating builder with feature: SensorOrientationFeature
D/Camera  (31960): Updating builder with feature: FlashFeature
D/Camera  (31960): Updating builder with feature: ExposureOffsetFeature
D/Camera  (31960): Updating builder with feature: FpsRangeFeature
I/Camera  (31960): refreshPreviewCaptureSession
I/CameraManagerGlobal(31960): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client com.example.cbj_smart_device_flutter API Level 2User Id 0
I/Camera  (31960): CameraCaptureSession onClosed
W/System  (31960): A resource failed to call Surface.release. 
W/System  (31960): A resource failed to call Surface.release. 

```

**Comment by iapicca** [comment]
I updated the code sample, but there I'm stuck with an issue with data format
which is addressed in here
- https://github.com/flutter/flutter/issues/26348

there are some solution on SO, but to be honest it's a bit disappointing 
that such a feature is severely incomplete

<details>
  <summary>broken code sample</summary>

  ```dart
import 'dart:async';

import 'package:camera/camera.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

extension InMemoryImageFromCameraController on CameraController {
  Future<Uint8List> get inMemoryImage async {
    final completer = Completer<CameraImage>();
    await startImageStream(completer.complete);
    final image = await completer.future;
    await stopImageStream();
    final writeBuffer = WriteBuffer();
    for (final plane in image.planes) {
      writeBuffer.putUint8List(plane.bytes);
    }
    return writeBuffer.done().buffer.asUint8List();
  }
}

typedef InMemoryImage = Future<CameraImage> Function(CameraController);

typedef CameraControllerStore = ValueNotifier<CameraController>;

typedef CameraLifeCycleHandler = void Function(
  CameraControllerStore cameraControllerStore,
  AppLifecycleState appLifecycleState,
);

typedef BuildCameraLifeCycleHandler = CameraLifeCycleHandler Function(
  CameraDescription description,
  ResolutionPreset resolutionPreset,
);

extension FromCameraControllerStoreX on CameraControllerStore {
  CameraController get controller => value;
  CameraValue get camera => controller.value;
}

BuildCameraLifeCycleHandler kBuildCameraLifeCycleHandler =
    (description, resolutionPreset) =>
        (cameraControllerStore, appLifecycleState) {
          switch (appLifecycleState) {
            case AppLifecycleState.inactive:
              () {
                cameraControllerStore.controller.dispose();
              }();
              return;
            case AppLifecycleState.resumed:
              () {
                cameraControllerStore.value = CameraController(
                  description,
                  resolutionPreset,
                );
              }();
              return;
            default:
              return;
          }
        };

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(
    const MaterialApp(home: CameraInitializationWidget()),
  );
}

class CameraInitializationWidget extends StatelessWidget {
  const CameraInitializationWidget({super.key});

  @override
  Widget build(context) => FutureBuilder(
        future: availableCameras(),
        builder: (context, snapshot) {
          switch (snapshot.connectionState) {
            case ConnectionState.done:
              return CameraSelectionWidget(cameras: snapshot.data!);
            default:
              return const Material(
                child: Center(
                  child: CircularProgressIndicator(),
                ),
              );
          }
        },
      );
}

class CameraSelectionWidget extends StatefulWidget {
  final List<CameraDescription> cameras;
  CameraSelectionWidget({super.key, this.cameras = const []})
      : assert(cameras.isNotEmpty);

  @override
  State<CameraSelectionWidget> createState() => _CameraSelectionWidgetState();
}

class _CameraSelectionWidgetState extends State<CameraSelectionWidget>
    with SingleTickerProviderStateMixin {
  late final TabController _tabController;

  @override
  void initState() {
    _tabController = TabController(length: widget.cameras.length, vsync: this);
    super.initState();
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  @override
  Widget build(context) => Scaffold(
        appBar: AppBar(
          bottom: TabBar(
            controller: _tabController,
            tabs: [
              for (final camera in widget.cameras) Tab(text: camera.name),
            ],
          ),
        ),
        body: TabBarView(
          controller: _tabController,
          children: [
            for (final camera in widget.cameras)
              CameraPreviewPage(
                camera: camera,
              ),
          ],
        ),
      );
}

class CameraPreviewPage extends StatefulWidget {
  final CameraDescription camera;

  /// Default Constructor
  const CameraPreviewPage({super.key, required this.camera});

  @override
  State<CameraPreviewPage> createState() => _CameraPreviewPageState();
}

class _CameraPreviewPageState extends State<CameraPreviewPage>
    with WidgetsBindingObserver {
  late final ValueNotifier<CameraController> _cameraControllerStore;
  late final ValueNotifier<CameraDescription> _cameraDescription;
  late CameraLifeCycleHandler _cameraLifeCycleHandler;

  @override
  void didChangeAppLifecycleState(appLifecycleState) {
    if (_cameraControllerStore.camera.isInitialized) {
      return;
    }
    _cameraLifeCycleHandler(
      _cameraControllerStore,
      appLifecycleState,
    );
  }

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    _cameraDescription = ValueNotifier(widget.camera);
    _cameraControllerStore = ValueNotifier(
      CameraController(
        _cameraDescription.value,
        ResolutionPreset.max,
      ),
    );

    _cameraLifeCycleHandler = kBuildCameraLifeCycleHandler(
      _cameraDescription.value,
      ResolutionPreset.max,
    );
  }

  @override
  void dispose() {
    _cameraDescription.dispose();
    _cameraControllerStore.dispose();
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  Widget build(context) => ValueListenableBuilder(
        valueListenable: _cameraControllerStore,
        builder: (context, cameraController, child) => Scaffold(
          body: CameraPreviewWidget(
            cameraController: cameraController,
          ),
          floatingActionButton: FloatingActionButton(
            child: const Icon(Icons.camera),
            onPressed: () async {
              late final Uint8List imageData;
              try {
                imageData = await cameraController.inMemoryImage;
              } catch (e) {
                debugPrint('$e');
              }
              if (mounted) {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => ImageWidget(
                      imageData: imageData,
                    ),
                  ),
                );
              }
            },
          ),
        ),
      );
}

class CameraPreviewWidget extends StatelessWidget {
  final CameraController cameraController;
  const CameraPreviewWidget({super.key, required this.cameraController});

  @override
  Widget build(context) => Center(
        child: cameraController.value.isInitialized
            ? CameraPreview(cameraController)
            : FutureBuilder(
                future: cameraController.initialize(),
                builder: (context, snapshot) {
                  switch (snapshot.connectionState) {
                    case ConnectionState.done:
                      return CameraPreview(cameraController);
                    default:
                      return const Center(child: CircularProgressIndicator());
                  }
                },
              ),
      );
}

class ImageWidget extends StatelessWidget {
  final Uint8List imageData;
  const ImageWidget({
    super.key,
    required this.imageData,
  });

  @override
  Widget build(context) => Scaffold(
        appBar: AppBar(),
        body: Image.memory(imageData),
      );
}

  ```
</details>

**Comment by guyluz11** [comment]
@iapicca thanks, and as you said it works but there is error on converting using `instantiateImageCodec`

```dart
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Invalid image data
#0      _futurize (dart:ui/painting.dart:6950:5)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:6764:12)
#2      instantiateImageCodecWithSize (dart:ui/painting.dart:2307:60)
#3      instantiateImageCodecFromBuffer (dart:ui/painting.dart:2251:10)
#4      instantiateImageCodec (dart:ui/painting.dart:2198:10)
<asynchronous suspension>
#5      _ImageStreamPageState.videoStream.<anonymous closure> (package:cbj_smart_device_flutter/presentation/client/image_stream_page.dart:38:24)
<asynchronous suspension>
```


Also I think `ResolutionPreset.low` gave a Uint8List of size `153600` in the stream and `49372` in a single photo.

**Comment by darshankawar** [comment]
@guyluz11 
Can you take a look at [this](https://github.com/flutter/flutter/issues/25087#issuecomment-497452811) and check if it helps in achieving your use case ?

**Comment by guyluz11** [comment]
> @guyluz11 Can you take a look at [this](https://github.com/flutter/flutter/issues/25087#issuecomment-497452811) and check if it helps in achieving your use case?

I don't understand what to do with the project he linked, it doesn't even include the `path_provider` package as he said.

Maybe I can take a picture and delete it afterwards

**Comment by pcc-cheng** [comment]
To reply to @stuartmorgan:

Our company uses this camera package and thinking of implementing camera package our own due to security concerns. Saving sensitive images on disk in cache could cause information leaks. Manually deleting temp directory could be a solution but in nonhappy path, like app crashes, image will still persist.

**Comment by TyBarthel** [comment]
> To reply to @stuartmorgan:
> 
> Our company uses this camera package and thinking of implementing camera package our own due to security concerns. Saving sensitive images on disk in cache could cause information leaks. Manually deleting temp directory could be a solution but in nonhappy path, like app crashes, image will still persist.

What solution did you end up implementing?

**Comment by AndersKlint** [comment]
My use case is:
* I constantly show a CameraPreview
* I need to take a raw picture for image processing (OCR via google ML Kit)
* I need to crop the captured image

The problems:
* If taking a picture normally using TakePicture:
    * Image is saved to file .
    * I need to decode the file to load it in memory  (slow).
    * I perform a crop on the in memory image.
    * I need to convert it to Raw or save it to disk again to be able to use it with ML kit.
* If using an image stream to capture a picture:
    * A lot of overhead starting and stopping the image stream. (in debug mode it takes 2 seconds to start on a galaxy A51)
    * Need to perform image stabilization myself.
    * I can keep the stream always open for fast capture, but this causes lag in the CameraPreview and is overall pretty performance intensive.
    * Even with no processing in the image stream loop, the CameraPreview is laggy.

I can use platform channels for the processing which makes it feasible to capture images from a continuous image stream, but this doesn't solve the performance issue with the CameraPreview. I need high resolution images for accurate OCR.

I will resort to using platform channels with native APIs, like CameraX, for capturing images instead. But it would be a big time save if raw image capture was available directly in dart :)
