### ISSUE TITLE
Flutter Gallery Animation glitching Error

### ISSUE THREAD

**Issue by braulio94** [flutter/flutter#13817]
I installed [flutter_gallery](https://github.com/flutter/flutter/tree/master/examples/flutter_gallery) and got this glitching error

**IDE:** Android Studio 3.0.1 
**Device:** Samsung Galaxy A5 (2016), with Android 7.0

**Flutter Version:**
`Flutter  channel master  https://github.com/flutter/flutter.git` 
`Framework  revision 4d2c2aaaa1 (4 days ago) • 2017-12-27 07:30:31 -0800` 
`Engine  revision 7c126001d8`
`Tools Dart 1.25.0-dev.11.0`

## [see video](https://goo.gl/nhxeuE)

<img src="https://user-images.githubusercontent.com/20057010/34464444-37e6a99a-ee7f-11e7-8c98-34201cb330e2.png" width="240" height="400">                                                   <img src="https://user-images.githubusercontent.com/20057010/34464577-8c03e82a-ee85-11e7-9d87-475f58e6e178.jpg" width="240" height="400">

**Comment by Hixie** [comment]
cc @chinmaygarde @jason-simmons @cbracken

**Comment by braulio94** [comment]
This might not be a device-specific issue

**Comment by cbracken** [comment]
@braulio94 Are all glitches you see text-related, or do you see other issues?

**Comment by braulio94** [comment]
@cbracken This happens to texts and icons, nothing else. The glitching starts every time I open the animation screen, then the rest gets affected.

**Comment by cbracken** [comment]
@braulio94 

Now that https://skia-review.googlesource.com/c/skia/+/71780 has landed in Skia, which was rolled into the engine in flutter/engine#4364, and rolled into the framework in #13033, could you verify if you're still seeing this?

**Comment by braulio94** [comment]
I have to upgrade flutter first, this could take some time. I'll do that then give you some feedback.

**Comment by braulio94** [comment]
@cbracken  it seems like nothing has changed [see video](https://drive.google.com/file/d/1OGTOK_lk4lMfY9MDIVnRg7y9JG3vqUd8/view)

**Comment by cbracken** [comment]
@braulio94 Based on the video, looks like this repros on an emulator. That's very helpful to know. Thanks for confirming; I'll keep this open then.

**Comment by braulio94** [comment]
@cbracken  it's not an emulator #14385

**Comment by cbracken** [comment]
Thanks for clarifying; I misunderstood what I was seeing (I spend most of my time dealing with iOS). 

We'll follow up with Skia. Sounds like the root cause may be the same as the Skia issue around multi-texturing that was fixed for iOS by the patch I mentioned.

**Comment by braulio94** [comment]
[this](https://gitter.im/flutter/flutter?at=5a771d8f6117191e61f25845) could be something you'd also want to take a look at.

![image](https://i.imgur.com/DdavkEN.png)

**Comment by cbracken** [comment]
I've rolled a new version of Skia to the framework. This version includes some (non-platform-specific) fixes related to this, and re-enables multitexturing on iOS. I'm able to verify that I'm no longer seeing the issue on iOS.

I don't have an Android device that shows the issue's you're seeing on the Samsung A5, but I'll look at getting one ordered. In the meantime, if you get a moment to check, would you mind checking if you still see the issues above on the `master` branch?

**Comment by cbracken** [comment]
Tentatively closing since we're no longer able to reproduce this on any device we have that had this issue. @braulio94 since we don't have a Samsung A5, please let us know if you're still seeing this on that device and we'll re-open and follow-up.

**Comment by Chris1234567899** [comment]
I still experience this behavior in the gallery app (V 0.4.2). I have a Lenovo Vibe K5 with Android 5.1.1.

![screenshot_2018-05-10-20-15-43](https://user-images.githubusercontent.com/12623865/39901642-5ba3e4e4-548f-11e8-9498-ee9a0c546e65.png)

![screenshot_2018-05-10-20-16-04](https://user-images.githubusercontent.com/12623865/39901647-6175e188-548f-11e8-8543-3fe1f87b0116.png)

**Comment by zoechi** [comment]
@Chris1234567899 I think it's better to create a new issue, this one is closed since a while and your issue might be a different one.
Please also add the output of `flutter doctor`

**Comment by Chris1234567899** [comment]
ok will do
