### ISSUE TITLE
bug: a few hot restarts cause a canvaskit failure

### ISSUE THREAD

**Issue by yeikel16** [flutter/flutter#140684]
### Steps to reproduce

1. Open example in VSCode, chose web platform
2. Set a breakpoint on line that calls runApp
3. Debug
4. Then the breakpoint is hit, click hot restart a few times

Issues related:

https://github.com/flutter/flutter/issues/90236

### Expected results

Not error when make hot reload

### Actual results

The app is freezed and show a error in console. The dialog of "Flutter: Hot reloading" not close.

![Captura de pantalla 2023-12-27 a la(s) 10 25 48 p m](https://github.com/flutter/flutter/assets/26438532/c9723e24-77de-4d33-9689-60f067a0d7e6)

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Material App Bar'),
        ),
        body: const Center(
          child: Text('Hello World'),
        ),
      ),
    );
  }
}

```

</details>

### Logs

<details open><summary>Logs</summary>

```console
Launching lib/main.dart on Chrome in debug mode...
This app is linked to the debug service: ws://127.0.0.1:64538/SH-yEsqGG2I=/ws
Debug service listening on ws://127.0.0.1:64538/SH-yEsqGG2I=/ws
Connecting to VM Service at ws://127.0.0.1:64538/SH-yEsqGG2I=/ws
Restarted application in 1,307ms.
Error: Expected a wrapped Dart object, but got a JS object or a wrapped Dart object from a separate runtime instead.
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3       throw_
dart-sdk/lib/_internal/js_shared/lib/js_interop_patch.dart 89:7                   JSBoxedDartObjectToObject.get$35toDart
lib/_engine/engine/canvaskit/native_memory.dart 24:46                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
```

</details>

In some case show this error to

```console
Restarted application in 2,200ms.
Error: Expected a wrapped Dart object, but got a JS object or a wrapped Dart object from a separate runtime instead.
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3       throw_
dart-sdk/lib/_internal/js_shared/lib/js_interop_patch.dart 89:7                   JSBoxedDartObjectToObject.get$35toDart
lib/_engine/engine/canvaskit/native_memory.dart 24:46                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
```

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.2 23C64 darwin-arm64, locale es-US)
    • Flutter version 3.16.5 on channel stable at /Users/yeikel/fvm/versions/3.16.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (hace 8 días), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/yeikel/Library/Android/sdk/
    • Platform android-34, build-tools 33.0.1
    • ANDROID_HOME = /Users/yeikel/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio 2.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio 2020.3.1.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.2 23C64 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.129

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by danagbemava-nc** [comment]
Reproducible using the code sample and steps outlined above. 

Labeling for further investigation


```
Error: Expected a wrapped Dart object, but got a JS object or a wrapped Dart object from a separate runtime instead.
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3       throw_
dart-sdk/lib/_internal/js_shared/lib/js_interop_patch.dart 93:7                   JSBoxedDartObjectToObject.get$35toDart
lib/_engine/engine/canvaskit/native_memory.dart 24:46                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 550:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 555:39  dcall
Application finished.
```

<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel stable, 3.16.5, on macOS 14.1.2 23B92 darwin-arm64, locale en-GB)
    • Flutter version 3.16.5 on channel stable at /Users/nexus/dev/sdks/flutter
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (9 days ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10072.19

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (4 available)
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 17.2.1 21C66
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 17.2 21C62
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 120.0.6099.129

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
  
```
[✓] Flutter (Channel master, 3.18.0-18.0.pre.44, on macOS 14.1.2 23B92 darwin-arm64, locale en-GB)
    • Flutter version 3.18.0-18.0.pre.44 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 420f18be76 (4 hours ago), 2023-12-29 13:45:36 +0800
    • Engine revision 7a7ddc53cd
    • Dart version 3.3.0 (build 3.3.0-270.0.dev)
    • DevTools version 2.31.0-dev.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10072.19

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (4 available)
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 17.2.1 21C66
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 17.2 21C62
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 120.0.6099.129

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```
</details>

**Comment by ericwindmill** [comment]
I'm seeing something similar using Intellij, Flutter 3.14, up-to-date Intellij plugin (231.9411).

I'm not using a debugger or running in debug mode. After 2-3 hot restarts, I start seeing an error.

```
Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:91:12
!isDisposed
"Trying to render a disposed EngineFlutterView."

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 38:3        assertFailed
lib/_engine/engine/window.dart 91:13                                              render
packages/flutter/src/rendering/view.dart 256:7                                    compositeFrame
packages/flutter/src/rendering/binding.dart 587:19                                drawFrame
packages/flutter/src/widgets/binding.dart 991:13                                  drawFrame
packages/flutter/src/rendering/binding.dart 448:5                                 [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1386:7                                [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1311:9                                handleDrawFrame
packages/flutter/src/scheduler/binding.dart 1169:5                                [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1346:5                                invoke
lib/_engine/engine/platform_dispatcher.dart 260:5                                 invokeOnDrawFrame
lib/_engine/engine/initialization.dart 185:36                                     <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 550:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 555:39  dcall
```

Note this is the same as  [141253](https://github.com/flutter/flutter/issues/141253), which has been closed.

**Comment by luckyhandler** [comment]
After upgrading to flutter `3.19.1` I get on Intellij

```
Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:91:12
!isDisposed
"Trying to render a disposed EngineFlutterView."
```

like in https://github.com/flutter/flutter/issues/141253 when hot restarting the app. It still continues to work.

But 
- on VS Code on saving the code and 
- on the terminal when pushing 'r' 

`router` leads me to my login screen and I cannot log in any more. 

Not sure what is different in Intellij Build #IC-233.11799.241 and Terminal / or VsCode.
Maybe helps as hint...

**Comment by nshahan** [comment]
I believe there are two issues being discussed here. Aside from them both happening on a hot restart, in the investigations I've done I haven't seen any connection between the orignal issue:
```
Error: Expected a wrapped Dart object, but got a JS object or a wrapped Dart object from a separate runtime instead.
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3       throw_
dart-sdk/lib/_internal/js_shared/lib/js_interop_patch.dart 89:7                   JSBoxedDartObjectToObject.get$35toDart
lib/_engine/engine/canvaskit/native_memory.dart 24:46                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
```

And the other error referenced by others in the thread:
```
Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:91:12
!isDisposed
"Trying to render a disposed EngineFlutterView."

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 38:3        assertFailed
lib/_engine/engine/window.dart 91:13                                              render
packages/flutter/src/rendering/view.dart 256:7                                    compositeFrame
packages/flutter/src/rendering/binding.dart 587:19                                drawFrame
packages/flutter/src/widgets/binding.dart 991:13                                  drawFrame
packages/flutter/src/rendering/binding.dart 448:5                                 [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1386:7                                [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1311:9                                handleDrawFrame
packages/flutter/src/scheduler/binding.dart 1169:5                                [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1346:5                                invoke
lib/_engine/engine/platform_dispatcher.dart 260:5                                 invokeOnDrawFrame
lib/_engine/engine/initialization.dart 185:36                                     <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 550:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 555:39  dcall
```

@ditman IIRC we ran into the second issue during our debugging sessions in January. Did you have fix out for that?

**Comment by ditman** [comment]
> @ditman IIRC we ran into the second issue during our debugging sessions in January. Did you have fix out for that?

@nshahan affirmative: 

* https://github.com/flutter/engine/pull/49958

The fix landed in Flutter [here](https://github.com/flutter/flutter/commit/236461161a879dfd36d6de55e41afd19c10e31cc) @ `3.19.0-12.0.pre`. It seems that revision missed the 3.19 stable release train, but is currently in `beta`:

```
$ is-in-beta 236461161a879d
Yes!
```

(@ericwindmill's issue should be fixed after a Flutter upgrade that contains the commit above)

**Comment by ditman** [comment]
@vasilich6107 can you provide a stack trace of the failure?

**Comment by JemsLee** [comment]
Hello everyone, is there any progress on this issue? I also encountered similar problems


------------------------------------------------------------------------------------------
Performing hot restart...
Waiting for connection from debug service on Chrome...
Restarted application in 69ms.
 384  951
[GETX] Instance "GetMaterialController" has been created
[GETX] Instance "GetMaterialController" has been initialized

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:91:12
!isDisposed
"Trying to render a disposed EngineFlutterView."

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 38:3        assertFailed
lib/_engine/engine/window.dart 91:13                                              render
packages/flutter/src/rendering/view.dart 256:7                                    compositeFrame
packages/flutter/src/rendering/binding.dart 587:19                                drawFrame
packages/flutter/src/widgets/binding.dart 991:13                                  drawFrame
packages/flutter/src/rendering/binding.dart 448:5                                 [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1386:7                                [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1311:9                                handleDrawFrame
packages/flutter/src/scheduler/binding.dart 1169:5                                [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1346:5                                invoke
lib/_engine/engine/platform_dispatcher.dart 260:5                                 invokeOnDrawFrame
lib/_engine/engine/initialization.dart 185:36                                     <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 550:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 555:39  dcall
====================================================================================================

**Comment by pedromassango** [comment]
@huycozy this seems to be a duplicate of https://github.com/flutter/flutter/issues/141253

**Comment by huycozy** [comment]
@JemsLee That error should be fixed on master channel, please see https://github.com/flutter/flutter/issues/141253.

For the original issue, I re-checked it on the latest Flutter stable `3.19.6` and master `3.22.0-16.0.pre.56` channels, the error doesn't appear even though the dialogs of `Flutter: Hot restarting...` persist:

![Screenshot 2024-04-25 at 11 36 40](https://github.com/flutter/flutter/assets/104349824/4e828f52-71d0-42ca-b9db-5f9f069fdd51)

**Comment by aliaktas-tr** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.19045.4651], locale tr-TR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.4)
[√] Android Studio (version 2022.3)
[√] VS Code (version unknown)
    X Unable to determine VS Code version.
[√] VS Code, 64-bit edition (version 1.67.2)
[√] Connected device (3 available)
[√] Network resources

• No issues found!



My error is like this;

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:102:12
!isDisposed
"Trying to render a disposed EngineFlutterView."

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3        assertFailed
lib/_engine/engine/window.dart 102:13                                             render
packages/flutter/src/rendering/view.dart 309:7                                    compositeFrame
packages/flutter/src/rendering/binding.dart 582:19                                drawFrame
packages/flutter/src/widgets/binding.dart 1138:13                                 drawFrame
packages/flutter/src/rendering/binding.dart 443:5                                 [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1392:7                                [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1313:9                                handleDrawFrame
packages/flutter/src/scheduler/binding.dart 1171:5                                [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1404:5                                invoke
lib/_engine/engine/platform_dispatcher.dart 307:5                                 invokeOnDrawFrame
lib/_engine/engine/initialization.dart 187:36                                     <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 426:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 431:39  dcall
====================================================================================================

**Comment by aliaktas-tr** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.19045.4651], locale tr-TR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.4)
[√] Android Studio (version 2022.3)
[√] VS Code (version unknown)
    X Unable to determine VS Code version.
[√] VS Code, 64-bit edition (version 1.67.2)
[√] Connected device (3 available)
[√] Network resources

• No issues found!

-----------------------------------------------------------------------------------------------------------------------------------


======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:102:12
!isDisposed
"Trying to render a disposed EngineFlutterView."

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3        assertFailed
lib/_engine/engine/window.dart 102:13                                             render
packages/flutter/src/rendering/view.dart 309:7                                    compositeFrame
packages/flutter/src/rendering/binding.dart 582:19                                drawFrame
packages/flutter/src/widgets/binding.dart 1138:13                                 drawFrame
packages/flutter/src/rendering/binding.dart 443:5                                 [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1392:7                                [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1313:9                                handleDrawFrame
packages/flutter/src/scheduler/binding.dart 1171:5                                [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1404:5                                invoke
lib/_engine/engine/platform_dispatcher.dart 307:5                                 invokeOnDrawFrame
lib/_engine/engine/initialization.dart 187:36                                     <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 426:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 431:39  dcall
====================================================================================================

**Comment by chaudharydeepanshu** [comment]
The issue is still happening on newer flutter SDK:

flutter.bat doctor --verbose
```
[√] Flutter (Channel stable, 3.24.1, on Microsoft Windows [Version 10.0.22631.4169], locale en-IN)
    • Flutter version 3.24.1 on channel stable at C:\dev\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (5 weeks ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\deepa\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Users\deepa\AppData\Local\Programs\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.11.35303.130
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Users\deepa\AppData\Local\Programs\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[√] VS Code (version 1.93.1)
    • VS Code at C:\Users\deepa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • M2101K6P (mobile) • d0646b2f • android-arm64  • Android 14 (API 34)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.22631.4169]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 128.0.6613.138
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 129.0.2792.52

[√] Network resources
    • All expected network resources are available.

• No issues found!
Process finished with exit code 0
```

Error log:
```
[E] TIME: 2024-09-25T14:07:53.780 ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞══════════════════════
The following assertion was thrown during a scheduler callback:
Assertion failed:
org-dartlang-sdk:///lib/_engine/engine/window.dart:102:12
!isDisposed
"Trying to render a disposed EngineFlutterView."

When the exception was thrown, this was the stack:
http://localhost:54458/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3     throw_
http://localhost:54458/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3      assertFailed
http://localhost:54458/lib/_engine/engine/window.dart 102:13                                           render
http://localhost:54458/packages/flutter/src/rendering/view.dart 353:7                                  compositeFrame
http://localhost:54458/packages/flutter/src/rendering/binding.dart 607:19                              drawFrame
http://localhost:54458/packages/flutter/src/widgets/binding.dart 1164:13                               drawFrame
http://localhost:54458/packages/flutter/src/rendering/binding.dart 468:5                               [_handlePersistentFrameCallback]
http://localhost:54458/packages/flutter/src/scheduler/binding.dart 1397:7                              [_invokeFrameCallback]
http://localhost:54458/packages/flutter/src/scheduler/binding.dart 1318:9                              handleDrawFrame
http://localhost:54458/packages/flutter/src/scheduler/binding.dart 1176:5                              [_handleDrawFrame]
http://localhost:54458/lib/_engine/engine/platform_dispatcher.dart 1408:5                              invoke
http://localhost:54458/lib/_engine/engine/platform_dispatcher.dart 310:5                               invokeOnDrawFrame
http://localhost:54458/lib/_engine/engine/initialization.dart 187:36                                   <fn>
http://localhost:54458/dart-sdk/lib/_internal/js_dev_runtime/patch/js_allow_interop_patch.dart 188:27  _callDartFunctionFast1
═════════════════════════════════════════════════════════════════

client.js:9937 2 module(s) were hot-reloaded.
```

**Comment by markbeij** [comment]
Same issue: https://github.com/getsentry/sentry-dart/issues/2325
Occurs all the time..

**Comment by YawarOsman** [comment]
Same here on `Hot Reload` and `Hot Restart` too:

```
════════ Exception caught by scheduler library ═════════════════════════════════
Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:102:12
!isDisposed
"Trying to render a disposed EngineFlutterView."
```

**Comment by ditman** [comment]
I thought I had fixed this one, but we must have a different race condition (or similar) elsewhere. We'll take a look!

**Comment by jorge2antibes** [comment]
Notice that this issue was not present while on flutter 3.24.0
It started right after I upgraded to flutter 3.27.1

**Comment by imaNNeo** [comment]
I also have this issue in 3.27.1

**Comment by acpSiam** [comment]
Same issue happening here but, in my case, I am pretty sure it's causing by some of my codes. I just cannot find which part of the code is causing this. I wish there was more in-depth debug information available.

```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:100:12
!isDisposed
"Trying to render a disposed EngineFlutterView."

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 307:3     throw_
dart-sdk/lib/_internal/js_dev_runtime/private/profile.dart 117:39               assertFailed
dart-sdk/lib/_internal/js_dev_runtime/private/profile.dart 117:39               render
packages/flutter/src/rendering/view.dart 363:7                                  compositeFrame
packages/flutter/src/rendering/binding.dart 621:19                              drawFrame
packages/flutter/src/widgets/binding.dart 1231:13                               drawFrame
packages/flutter/src/rendering/binding.dart 482:5                               [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1442:7                              [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1355:9                              handleDrawFrame
packages/flutter/src/scheduler/binding.dart 1208:5                              [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1347:5                              invoke
lib/_engine/engine/platform_dispatcher.dart 301:5                               invokeOnDrawFrame
lib/_engine/engine/initialization.dart 190:36                                   <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/js_allow_interop_patch.dart 224:27  _callDartFunctionFast1
====================================================================================================
```

**Comment by graemep-nz** [comment]
I get this error a lot with hot restarts  - maybe one in eight times. Running web app in chrome browser.

Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:100:12
!isDisposed
"Trying to render a disposed EngineFlutterView."

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 307:3     throw_
dart-sdk/lib/_internal/js_dev_runtime/private/profile.dart 117:39               assertFailed
dart-sdk/lib/_internal/js_dev_runtime/private/profile.dart 117:39               render
packages/flutter/src/rendering/view.dart 363:7                                  compositeFrame
packages/flutter/src/rendering/binding.dart 621:19                              drawFrame
packages/flutter/src/widgets/binding.dart 1231:13                               drawFrame


Flutter 3.29.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 35c388afb5 (4 months ago) • 2025-02-10 12:48:41 -0800
Engine • revision f73bfc4522
Tools • Dart 3.7.0 • DevTools 2.42.2

**Comment by anilari** [comment]
I have same problem with 3.35.1 

Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:99:12
!isDisposed
"Trying to render a disposed EngineFlutterView."

When I try to debug my application it always opens somewhere inside of the framework and distracting my development.

**Comment by nshahan** [comment]
Notes for a future investigation from a random hallway conversation today: 

These errors could be caused by scheduling a callback for after a frame renders. 
https://github.com/flutter/flutter/blob/3a18c9449e59436686dbd1a2bbd29daed68bc0b4/engine/src/flutter/lib/web_ui/lib/src/engine/frame_service.dart#L90-L109

It looks like this could be scheduling a callback on the JavaScript side which means it could persist after a hot restart.

It sounds like there is an API to schedule a callback for after a frame render. We should experiment and see if we can repro the issues with it. 

If that does repro, we could potentially add checks to ensure the callback runs in the same generation of the application or cancel it if it was scheduled before a hot restart of the application and tries to run after.

**Comment by plchekspend** [comment]
Facing the same issue with Flutter 3.35.3

Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:99:12
!isDisposed
"Trying to render a disposed EngineFlutterView."
Another exception was thrown: Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:99:12

Facing this on flutter web also i noticed that when i used dialogue on certain screen and when popping that dialogue facing this error logs exception.
Now it logs continuously whichever part go to in app.

**Comment by eli1stark** [comment]
@nshahan 

Thank you for the follow-up! This is a framework issue that can be consistently reproduced using the sample code below.

**Reproduction steps:**
1. Run the code below in Chrome (or Chrome emulator)
2. Repeatedly alternate between hot reload and hot restart
3. The issue typically reproduces within 1 minute of testing

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return WidgetsApp(
      color: Colors.white,
      builder: (context, child) {
        return const Scaffold();
      },
    );
  }
}
```

</details>

<details>
<summary>Flutter doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.35.3, on macOS 15.6.1 24G90 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 26.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2025.1)
[✓] VS Code (version 1.96.4)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>


Please consider upgrading this from P3 to P2 given its impact on web development, community engagement (👍), and that it's been pending since 2023.

**Comment by plchekspend** [comment]
> [@nshahan](https://github.com/nshahan)
> 
> Thank you for the follow-up! This is a framework issue that can be consistently reproduced using the sample code below.
> 
> **Reproduction steps:**
> 
> 1. Run the code below in Chrome (or Chrome emulator)
> 2. Repeatedly alternate between hot reload and hot restart
> 3. The issue typically reproduces within 1 minute of testing
> 
> Sample code
> import 'package:flutter/material.dart';
> 
> void main() {
>   runApp(const App());
> }
> 
> class App extends StatelessWidget {
>   const App({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     return WidgetsApp(
>       color: Colors.white,
>       builder: (context, child) {
>         return const Scaffold();
>       },
>     );
>   }
> }
> Flutter doctor output
> ```
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 3.35.3, on macOS 15.6.1 24G90 darwin-arm64, locale en-US)
> [✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
> [✓] Xcode - develop for iOS and macOS (Xcode 26.0)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2025.1)
> [✓] VS Code (version 1.96.4)
> [✓] Connected device (4 available)
> [✓] Network resources
> 
> • No issues found!
> ```
> 
> Please consider upgrading this from P3 to P2 given its impact on web development, community engagement (👍), and that it's been pending since 2023.

Hey @eli1stark , Thanks for sharing the reproducing code,
Can you kindly update the code sample for WidgetsApp widget?
Appreciate for your efforts.
