### ISSUE TITLE
[Android] Virtual display - Surface view blank on App Resume

### ISSUE THREAD

**Issue by timbotimbo** [flutter/flutter#144219]
### Description
I just noticed this while testing a fix on master for an unrelated issue.  
An AndroidView becomes blank on every app resume.  

This affects the [flutter_unity_widget](https://pub.dev/packages/flutter_unity_widget) package, but can also be reproduced with a simple SurfaceView example.

### Steps to reproduce
I can reproduces this 100% of my attempts.

- Configure flutter to use the master channel
- Run code sample on Android (10+)
- Leave the app and come back.
  This can be to the home screen or any other app, it doesn't matter.
- You should now only see the color of the container behind the platform view.

##
This can be reproduced starting with a commit last week.  
>[9ed5496] Roll Flutter Engine from 52ffcaadea41 to bf5c003085fd (12 revisions) (#143875)

Given that it is about OnResume, https://github.com/flutter/engine/pull/50792 looks like a likely culprit.

I am not sure if this is a bug or if this fix requires additional logic when resuming the app.

##

**Reproduced on:**

x86 Emulator      - Android 14
Samsung S20FE - Android 13
x86 Emulator      - Android 12
x86 emulator   - Android 11
x86 emulator - Android 10

**Not reproduced on**
x86 emulator - Android 9
Samsung S8 - Android 9
Wileyfox swift - Android 7

### Expected results

The AndroidView should show up like it was when leaving the app, just as it does on any previous Flutter version.
3.13, 3.16, 3.19 and 3.20 beta do not show this behaviour.

### Actual results

The AndroidView is blank on app resume.  
The debug console is spammed with 
```
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned 
```

### Code sample

I can reproduce this using the GLTest example mentioned in another Virtual display bug.

(basic  surfaceview)
https://github.com/timbotimbo/flutter-GLTest/tree/initial

(basic surfaceview + additional surfaceholder)
https://github.com/timbotimbo/flutter-GLTest/tree/master

### Screenshots or Video

Recording on Samsung S23FE Android 13, using the master branch linked in **code sample**. 

https://github.com/flutter/flutter/assets/11444698/782b9ee4-c960-40c8-bcae-35f2b8a5007f

### Logs

<details><summary>Logs</summary>

Log starting when the app is move to the background up to being opened again,
```console
W/ImageReader_JNI(28102): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
W/ImageReader_JNI(28102): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
I/ViewRootImpl@d5b46b8[MainActivity](28102): MSG_WINDOW_FOCUS_CHANGED 0 0
W/ImageReader_JNI(28102): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
W/ImageReader_JNI(28102): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
W/ImageReader_JNI(28102): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
I/ViewRootImpl@d5b46b8[MainActivity](28102): handleAppVisibility mAppVisible = true visible = false
I/SurfaceView@11e3834(28102): onWindowVisibilityChanged(8) false io.flutter.embedding.android.FlutterSurfaceView{11e3834 V.E...... ........ 0,0-1080,2256} of ViewRootImpl@d5b46b8[MainActivity]
I/SurfaceView@11e3834(28102): Changes: creating=false format=false size=false visible=true alpha=false hint=false mUseAlpha=false visible=true left=false top=false
I/SurfaceView@11e3834(28102): 18757684 Cur surface: Surface(name=null)/@0x6c896c4
I/SurfaceView@11e3834(28102): applyTransactionOnVriDraw: vri = ViewRootImpl@d5b46b8[MainActivity] fRS = false t = 0xb4000077ac130600 android.view.SurfaceView.performSurfaceTransaction:959 android.view.SurfaceView.updateSurface:1105 android.view.SurfaceView.onWindowVisibilityChanged:371
I/ViewRootImpl@d5b46b8[MainActivity](28102): applyTransactionOnDraw: mRemoved = false isHardwareEnabled = true t = 0xb4000077ac130600android.view.SurfaceView.applyTransactionOnVriDraw:2048 android.view.SurfaceView.performSurfaceTransaction:959 android.view.SurfaceView.updateSurface:1105 android.view.SurfaceView.onWindowVisibilityChanged:371 android.view.View.dispatchWindowVisibilityChanged:15943
I/SurfaceView@11e3834(28102): surfaceDestroyed
I/SurfaceView@11e3834(28102): surfaceDestroyed callback.size 1 #2 io.flutter.embedding.android.FlutterSurfaceView{11e3834 V.E...... ........ 0,0-1080,2256}
I/SurfaceView@11e3834(28102): updateSurface: mVisible = false mSurface.isValid() = true
I/SurfaceView@11e3834(28102): releaseSurfaces: viewRoot = ViewRootImpl@d5b46b8[MainActivity]
I/SurfaceView@11e3834(28102): applyTransactionOnVriDraw: vri = ViewRootImpl@d5b46b8[MainActivity] fRS = true t = 0xb400007712c20600 android.view.SurfaceView.releaseSurfaces:858 android.view.SurfaceView.updateSurface:1172 android.view.SurfaceView.onWindowVisibilityChanged:371
I/SurfaceView@11e3834(28102): applyTransactionOnVriDraw: viewRoot.applyTransactionOnDrawFromReleaseSurfaces
I/ViewRootImpl@d5b46b8[MainActivity](28102): from releaseSurfaces t.apply t = 0xb400007712c20600
V/SurfaceView@11e3834(28102): Layout: x=0 y=0 w=1080 h=2256, frame=Rect(0, 0 - 1080, 2256)
D/SurfaceView@11e3834(28102): windowPositionLost, frameNr = 0
D/OpenGLRenderer(28102): setSurface called with nullptr
D/OpenGLRenderer(28102): setSurface() destroyed EGLSurface
D/OpenGLRenderer(28102): destroyEglSurface
I/ViewRootImpl@d5b46b8[MainActivity](28102): performTraversals mFirst=false windowShouldResize=false viewVisibilityChanged=true mForceNextWindowRelayout=false params=null
I/ViewRootImpl@d5b46b8[MainActivity](28102): Relayout returned: old=(0,0,1080,2400) new=(0,0,1080,2400) req=(1080,2400)8 dur=28 res=0x2 s={false 0x0} ch=true seqId=0
I/SurfaceView@11e3834(28102): windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{11e3834 V.E...... ........ 0,0-1080,2256} of ViewRootImpl@d5b46b8[MainActivity]
D/SurfaceView@11e3834(28102): updateSurface: surface is not valid
I/SurfaceView@11e3834(28102): releaseSurfaces: viewRoot = ViewRootImpl@d5b46b8[MainActivity]
I/SurfaceView@11e3834(28102): applyTransactionOnVriDraw: vri = ViewRootImpl@d5b46b8[MainActivity] fRS = true t = 0xb40000771539ad00 android.view.SurfaceView.releaseSurfaces:858 android.view.SurfaceView.updateSurface:998 android.view.SurfaceView.setWindowStopped:335
I/SurfaceView@11e3834(28102): applyTransactionOnVriDraw: viewRoot.applyTransactionOnDrawFromReleaseSurfaces
I/ViewRootImpl@d5b46b8[MainActivity](28102): from releaseSurfaces t.apply t = 0xb40000771539ad00
D/SurfaceView@11e3834(28102): updateSurface: surface is not valid
I/SurfaceView@11e3834(28102): releaseSurfaces: viewRoot = ViewRootImpl@d5b46b8[MainActivity]
I/SurfaceView@11e3834(28102): applyTransactionOnVriDraw: vri = ViewRootImpl@d5b46b8[MainActivity] fRS = true t = 0xb4000077ac130700 android.view.SurfaceView.releaseSurfaces:858 android.view.SurfaceView.updateSurface:998 android.view.SurfaceView.lambda$new$0$android-view-SurfaceView:200
I/SurfaceView@11e3834(28102): applyTransactionOnVriDraw: viewRoot.applyTransactionOnDrawFromReleaseSurfaces
I/ViewRootImpl@d5b46b8[MainActivity](28102): from releaseSurfaces t.apply t = 0xb4000077ac130700
I/ViewRootImpl@d5b46b8[MainActivity](28102): stopped(true) old = false
I/ViewRootImpl@d5b46b8[MainActivity](28102): WindowStopped on com.example.myGLView.gltest/com.example.myGLView.gltest.MainActivity set to true
D/SurfaceView@11e3834(28102): updateSurface: surface is not valid
I/SurfaceView@11e3834(28102): releaseSurfaces: viewRoot = ViewRootImpl@d5b46b8[MainActivity]
I/SurfaceView@11e3834(28102): applyTransactionOnVriDraw: vri = ViewRootImpl@d5b46b8[MainActivity] fRS = true t = 0xb40000778447f100 android.view.SurfaceView.releaseSurfaces:858 android.view.SurfaceView.updateSurface:998 android.view.SurfaceView.setVisibility:392
I/SurfaceView@11e3834(28102): applyTransactionOnVriDraw: viewRoot.applyTransactionOnDrawFromReleaseSurfaces
I/ViewRootImpl@d5b46b8[MainActivity](28102): from releaseSurfaces t.apply t = 0xb40000778447f100
I/MSHandlerLifeCycle(28102): removeMultiSplitHandler: no exist. decor=DecorView@1f69415[MainActivity]
D/InputTransport(28102): Input channel destroyed: 'ClientS', fd=161
D/SurfaceView@11e3834(28102): updateSurface: surface is not valid
I/SurfaceView@11e3834(28102): releaseSurfaces: viewRoot = ViewRootImpl@d5b46b8[MainActivity]
I/SurfaceView@11e3834(28102): applyTransactionOnVriDraw: vri = ViewRootImpl@d5b46b8[MainActivity] fRS = true t = 0xb40000778447f300 android.view.SurfaceView.releaseSurfaces:858 android.view.SurfaceView.updateSurface:998 android.view.SurfaceView.lambda$new$0$android-view-SurfaceView:200
I/SurfaceView@11e3834(28102): applyTransactionOnVriDraw: viewRoot.applyTransactionOnDrawFromReleaseSurfaces
I/ViewRootImpl@d5b46b8[MainActivity](28102): from releaseSurfaces t.apply t = 0xb40000778447f300
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
I/ViewRootImpl@d5b46b8[MainActivity](28102): handleAppVisibility mAppVisible = false visible = true
I/ViewRootImpl@d5b46b8[MainActivity](28102): stopped(false) old = true
I/ViewRootImpl@d5b46b8[MainActivity](28102): WindowStopped on com.example.myGLView.gltest/com.example.myGLView.gltest.MainActivity set to false
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
D/SurfaceView@11e3834(28102): updateSurface: surface is not valid
I/SurfaceView@11e3834(28102): releaseSurfaces: viewRoot = ViewRootImpl@d5b46b8[MainActivity]
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
I/SurfaceView@11e3834(28102): applyTransactionOnVriDraw: vri = ViewRootImpl@d5b46b8[MainActivity] fRS = true t = 0xb40000778447f400 android.view.SurfaceView.releaseSurfaces:858 android.view.SurfaceView.updateSurface:998 android.view.SurfaceView.setVisibility:392
I/SurfaceView@11e3834(28102): applyTransactionOnVriDraw: viewRoot.applyTransactionOnDrawFromReleaseSurfaces
I/ViewRootImpl@d5b46b8[MainActivity](28102): applyTransactionOnDraw: mRemoved = false isHardwareEnabled = false t = 0xb40000778447f400android.view.ViewRootImpl.applyTransactionOnDrawFromReleaseSurfaces:12850 android.view.SurfaceView.applyTransactionOnVriDraw:2046 android.view.SurfaceView.releaseSurfaces:858 android.view.SurfaceView.updateSurface:998 android.view.SurfaceView.setVisibility:392
I/MSHandlerLifeCycle(28102): removeMultiSplitHandler: no exist. decor=DecorView@1f69415[MainActivity]
I/ViewRootImpl@d5b46b8[MainActivity](28102): stopped(false) old = false
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
I/DecorView(28102): notifyKeepScreenOnChanged: keepScreenOn=false
I/MSHandlerLifeCycle(28102): removeMultiSplitHandler: no exist. decor=DecorView@1f69415[MainActivity]
I/SurfaceView@11e3834(28102): onWindowVisibilityChanged(0) false io.flutter.embedding.android.FlutterSurfaceView{11e3834 V.E...... ......ID 0,0-1080,2256} of ViewRootImpl@d5b46b8[MainActivity]
D/SurfaceView@11e3834(28102): updateSurface: surface is not valid
I/SurfaceView@11e3834(28102): releaseSurfaces: viewRoot = ViewRootImpl@d5b46b8[MainActivity]
I/SurfaceView@11e3834(28102): applyTransactionOnVriDraw: vri = ViewRootImpl@d5b46b8[MainActivity] fRS = true t = 0xb40000772c0bfb00 android.view.SurfaceView.releaseSurfaces:858 android.view.SurfaceView.updateSurface:998 android.view.SurfaceView.onWindowVisibilityChanged:371
I/SurfaceView@11e3834(28102): applyTransactionOnVriDraw: viewRoot.applyTransactionOnDrawFromReleaseSurfaces
I/ViewRootImpl@d5b46b8[MainActivity](28102): applyTransactionOnDraw: mRemoved = false isHardwareEnabled = false t = 0xb40000772c0bfb00android.view.ViewRootImpl.applyTransactionOnDrawFromReleaseSurfaces:12850 android.view.SurfaceView.applyTransactionOnVriDraw:2046 android.view.SurfaceView.releaseSurfaces:858 android.view.SurfaceView.updateSurface:998 android.view.SurfaceView.onWindowVisibilityChanged:371
I/ViewRootImpl@d5b46b8[MainActivity](28102): performTraversals params={(0,0)(fillxfill) sim={adjust=resize forwardNavigation} ty=BASE_APPLICATION fmt=TRANSLUCENT wanim=0x1030001
I/ViewRootImpl@d5b46b8[MainActivity](28102):   fl=81810100
I/ViewRootImpl@d5b46b8[MainActivity](28102):   pfl=16020040
I/ViewRootImpl@d5b46b8[MainActivity](28102):   vsysui=500
I/ViewRootImpl@d5b46b8[MainActivity](28102):   apr=LIGHT_STATUS_BARS
I/ViewRootImpl@d5b46b8[MainActivity](28102):   bhv=DEFAULT
I/ViewRootImpl@d5b46b8[MainActivity](28102):   fitSides= naviIconColor=0}
I/ViewRootImpl@d5b46b8[MainActivity](28102): performTraversals mFirst=false windowShouldResize=false viewVisibilityChanged=true mForceNextWindowRelayout=false params={(0,0)(fillxfill) sim={adjust=resize forwardNavigation} ty=BASE_APPLICATION fmt=TRANSLUCENT wanim=0x1030001
I/ViewRootImpl@d5b46b8[MainActivity](28102):   fl=81810100
I/ViewRootImpl@d5b46b8[MainActivity](28102):   pfl=16020040
I/ViewRootImpl@d5b46b8[MainActivity](28102):   vsysui=500
I/ViewRootImpl@d5b46b8[MainActivity](28102):   apr=LIGHT_STATUS_BARS
I/ViewRootImpl@d5b46b8[MainActivity](28102):   bhv=DEFAULT
I/ViewRootImpl@d5b46b8[MainActivity](28102):   fitSides= naviIconColor=0}
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
I/ViewRootImpl@d5b46b8[MainActivity](28102): updateBlastSurfaceIfNeeded mBlastBufferQueue=null isSameSurfaceControl=false
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
I/BLASTBufferQueue(28102): new BLASTBufferQueue, mName= ViewRootImpl@d5b46b8[MainActivity] mNativeObject= 0xb4000077842f9b80 sc.mNativeObject= 0xb400007712bb5500 caller= android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:2909 android.view.ViewRootImpl.relayoutWindow:9847 android.view.ViewRootImpl.performTraversals:3884 android.view.ViewRootImpl.doTraversal:3116 android.view.ViewRootImpl$TraversalRunnable.run:10885 android.view.Choreographer$CallbackRecord.run:1301 android.view.Choreographer$CallbackRecord.run:1309 android.view.Choreographer.doCallbacks:923 android.view.Choreographer.doFrame:852 android.view.Choreographer$FrameDisplayEventReceiver.run:1283
I/BLASTBufferQueue(28102): update, w= 1080 h= 2400 mName = ViewRootImpl@d5b46b8[MainActivity] mNativeObject= 0xb4000077842f9b80 sc.mNativeObject= 0xb400007712bb5500 format= -3 caller= android.graphics.BLASTBufferQueue.<init>:84 android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:2909 android.view.ViewRootImpl.relayoutWindow:9847 android.view.ViewRootImpl.performTraversals:3884 android.view.ViewRootImpl.doTraversal:3116 android.view.ViewRootImpl$TraversalRunnable.run:10885
I/ViewRootImpl@d5b46b8[MainActivity](28102): Relayout returned: old=(0,0,1080,2400) new=(0,0,1080,2400) req=(1080,2400)0 dur=10 res=0x3 s={true 0xb400007784480000} ch=true seqId=0
D/OpenGLRenderer(28102): eglCreateWindowSurface
I/ViewRootImpl@d5b46b8[MainActivity](28102): mThreadedRenderer.initialize() mSurface={isValid=true 0xb400007784480000} hwInitialized=true
I/SurfaceView@11e3834(28102): Changes: creating=false format=false size=false visible=false alpha=false hint=false mUseAlpha=false visible=false left=false top=false
I/SurfaceView@11e3834(28102): windowStopped(false) true io.flutter.embedding.android.FlutterSurfaceView{11e3834 V.E...... ......ID 0,0-1080,2256} of ViewRootImpl@d5b46b8[MainActivity]
I/SurfaceView@11e3834(28102): Changes: creating=true format=false size=false visible=true alpha=false hint=false mUseAlpha=false visible=true left=false top=false
I/BLASTBufferQueue(28102): update, w= 1080 h= 2256 mName = null mNativeObject= 0xb4000077842fa280 sc.mNativeObject= 0xb40000772bf57ea0 format= 4 caller= android.view.SurfaceView.createBlastSurfaceControls:1383 android.view.SurfaceView.updateSurface:1079 android.view.SurfaceView.setWindowStopped:335 android.view.SurfaceView.surfaceCreated:1853 android.view.ViewRootImpl.notifySurfaceCreated:2820 android.view.ViewRootImpl.performTraversals:4293
I/SurfaceView@11e3834(28102): 18757684 Cur surface: Surface(name=null)/@0x6c896c4
I/SurfaceView@11e3834(28102): pST: sr = Rect(0, 0 - 1080, 2256) sw = 1080 sh = 2256
D/SurfaceView@11e3834(28102): performSurfaceTransaction RenderWorker position = [0, 0, 1080, 2256] surfaceSize = 1080x2256
I/SurfaceView@11e3834(28102): applyTransactionOnVriDraw: vri = ViewRootImpl@d5b46b8[MainActivity] fRS = false t = 0xb40000778447f800 android.view.SurfaceView.performSurfaceTransaction:959 android.view.SurfaceView.updateSurface:1105 android.view.SurfaceView.setWindowStopped:335
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
I/ViewRootImpl@d5b46b8[MainActivity](28102): applyTransactionOnDraw: mRemoved = false isHardwareEnabled = true t = 0xb40000778447f800android.view.SurfaceView.applyTransactionOnVriDraw:2048 android.view.SurfaceView.performSurfaceTransaction:959 android.view.SurfaceView.updateSurface:1105 android.view.SurfaceView.setWindowStopped:335 android.view.SurfaceView.surfaceCreated:1853
I/SurfaceView@11e3834(28102): updateSurface: mVisible = true mSurface.isValid() = true
I/SurfaceView@11e3834(28102): updateSurface: mSurfaceCreated = false surfaceChanged = true visibleChanged = true
I/SurfaceView@11e3834(28102): visibleChanged -- surfaceCreated
I/SurfaceView@11e3834(28102): surfaceCreated 1 #1 io.flutter.embedding.android.FlutterSurfaceView{11e3834 V.E...... ......ID 0,0-1080,2256}
I/SurfaceView@11e3834(28102): surfaceChanged -- format=4 w=1080 h=2256
I/SurfaceView@11e3834(28102): surfaceChanged (1080,2256) 1 #1 io.flutter.embedding.android.FlutterSurfaceView{11e3834 V.E...... ......ID 0,0-1080,2256}
I/SurfaceView@11e3834(28102): surfaceRedrawNeeded
V/SurfaceView@11e3834(28102): Layout: x=0 y=0 w=1080 h=2256, frame=Rect(0, 0 - 1080, 2256)
I/ViewRootImpl@d5b46b8[MainActivity](28102): reportNextDraw android.view.ViewRootImpl.performTraversals:4438 android.view.ViewRootImpl.doTraversal:3116 android.view.ViewRootImpl$TraversalRunnable.run:10885 android.view.Choreographer$CallbackRecord.run:1301 android.view.Choreographer$CallbackRecord.run:1309
I/ViewRootImpl@d5b46b8[MainActivity](28102): Setup new sync id=1
I/ViewRootImpl@d5b46b8[MainActivity](28102): Setting syncFrameCallback
I/ViewRootImpl@d5b46b8[MainActivity](28102): registerCallbacksForSync syncBuffer=false
D/SurfaceView@11e3834(28102): updateSurfacePosition RenderWorker, frameNr = 1, position = [0, 0, 1080, 2256] surfaceSize = 1080x2256
I/SurfaceView@11e3834(28102): uSP: rtp = Rect(0, 0 - 1080, 2256) rtsw = 1080 rtsh = 2256
I/SurfaceView@11e3834(28102): onSSPAndSRT: pl = 0 pt = 0 sx = 1.0 sy = 1.0
I/SurfaceView@11e3834(28102): aOrMT: ViewRootImpl@d5b46b8[MainActivity] t = android.view.SurfaceControl$Transaction@e4230aa fN = 1 android.view.SurfaceView.-$$Nest$mapplyOrMergeTransaction:0 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1537 android.graphics.RenderNode$CompositePositionUpdateListener.positionChanged:373
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
I/ViewRootImpl@d5b46b8[MainActivity](28102): mWNT: t=0xb40000778447f900 mBlastBufferQueue=0xb4000077842f9b80 fn= 1 caller= android.view.SurfaceView.applyOrMergeTransaction:1455 android.view.SurfaceView.-$$Nest$mapplyOrMergeTransaction:0 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1537
I/ViewRootImpl@d5b46b8[MainActivity](28102): mWNT: t=0xb4000077ac130600 mBlastBufferQueue=0xb4000077842f9b80 fn= 1 caller= android.view.ViewRootImpl.lambda$applyTransactionOnDraw$11$android-view-ViewRootImpl:12865 android.view.ViewRootImpl$$ExternalSyntheticLambda1.onFrameDraw:4 android.graphics.HardwareRenderer$FrameDrawingCallback.onFrameDraw:924
I/ViewRootImpl@d5b46b8[MainActivity](28102): mWNT: t=0xb40000778447f800 mBlastBufferQueue=0xb4000077842f9b80 fn= 1 caller= android.view.ViewRootImpl.lambda$applyTransactionOnDraw$11$android-view-ViewRootImpl:12865 android.view.ViewRootImpl$$ExternalSyntheticLambda1.onFrameDraw:4 android.graphics.HardwareRenderer$FrameDrawingCallback.onFrameDraw:924
I/ViewRootImpl@d5b46b8[MainActivity](28102): Received frameDrawingCallback syncResult=0 frameNum=1.
I/ViewRootImpl@d5b46b8[MainActivity](28102): Setting up sync and frameCommitCallback
I/BLASTBufferQueue(28102): [ViewRootImpl@d5b46b8[MainActivity]#5](f:0,a:0) onFrameAvailable the first frame is available
I/ViewRootImpl@d5b46b8[MainActivity](28102): Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true
I/ViewRootImpl@d5b46b8[MainActivity](28102): onSyncComplete
I/ViewRootImpl@d5b46b8[MainActivity](28102): setupSync seqId=0 mSyncId=1 fn=1 caller=android.view.ViewRootImpl$$ExternalSyntheticLambda11.accept:6 android.window.SurfaceSyncer.lambda$setupSync$1$android-window-SurfaceSyncer:128 android.window.SurfaceSyncer$$ExternalSyntheticLambda1.accept:8 android.window.SurfaceSyncer$SyncSet.checkIfSyncIsComplete:382 android.window.SurfaceSyncer$SyncSet.markSyncReady:359 android.window.SurfaceSyncer.markSyncReady:151 android.view.ViewRootImpl.performTraversals:4503
I/ViewRootImpl@d5b46b8[MainActivity](28102): reportDrawFinished seqId=0 mSyncId=-1 fn=1 mSurfaceChangedTransaction=0xb40000772bf10e00
I/SurfaceView@11e3834(28102): finishedDrawing
I/BLASTBufferQueue(28102): [SurfaceView[com.example.myGLView.gltest/com.example.myGLView.gltest.MainActivity]@0#6](f:0,a:0) onFrameAvailable the first frame is available
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
I/ViewRootImpl@d5b46b8[MainActivity](28102): MSG_WINDOW_FOCUS_CHANGED 1 0
I/ViewRootImpl@d5b46b8[MainActivity](28102): mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0xb400007784480000}
D/InputMethodManager(28102): startInputInner - Id : 0
I/InputMethodManager(28102): startInputInner - mService.startInputOrWindowGainedFocus
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(28102): [ImageReader-1080x2000f22m4-28102-0](id:6dc600000002,api:1,p:1104,c:28102) dequeueBuffer: BufferQueue has been abandoned
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
flutter doctor -v
[√] Flutter (Channel master, 3.20.0-11.0.pre.74, on Microsoft Windows [Version 10.0.19045.4046], locale en-GB)
    • Flutter version 3.20.0-11.0.pre.74 on channel master at C:\Flutter\  
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9ed5496c01 (6 days ago), 2024-02-21 16:04:21 -0500
    • Engine revision bf5c003085
    • Dart version 3.4.0 (build 3.4.0-157.0.dev)
    • DevTools version 2.33.0-dev.6

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\___\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34607.119
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.86.2)
    • VS Code at C:\Users\___\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.82.0

[√] Connected device (4 available)
    • SM G780G (mobile) • RF8R8021WSR • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.19045.4046]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 121.0.6167.187
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 122.0.2365.52

[√] Network resources
    • All expected network resources are available.

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @timbotimbo 
I see that it seems to be occuring only using virtual display. Can you check https://github.com/flutter/flutter/issues/142978 and see if this could be related ?

**Comment by timbotimbo** [comment]
@darshankawar 
The commit that is marked as fixing that issue seems to be the one causing this one.  
Maybe this is an edge case that was missed in that PR.

**Comment by johnmccutchan** [comment]
@timbotimbo Thanks again for the detailed bug report.

I'll take a look shortly.

**Comment by johnmccutchan** [comment]
I've reproduced the issue and understand why it is happening. Currently figuring out the best fix.

**Comment by johnmccutchan** [comment]
The only way to fix this issue is to disable the Samsung-specific fix of cleaning up ImageReaders after an application is foregrounded.

I am preparing a PR that will land today that will do that.

**Comment by johnmccutchan** [comment]
This should be fixed.

**Comment by timbotimbo** [comment]
@darshankawar 
This is no longer fixed.

This issue should be reopened because the fix (https://github.com/flutter/engine/pull/51391)  was just reverted in https://github.com/flutter/engine/pull/51665.
So as of commit a8345d5 this is broken again on the master branch.


I just ran the example again with the latest master and can confirm the issue is back.

**Comment by darshankawar** [comment]
Reopening based on above comment.

/cc @johnmccutchan

**Comment by timbotimbo** [comment]
Looks like the PR got restored https://github.com/flutter/engine/pull/51764 and is in Flutter master again.
