### ISSUE TITLE
Flutter Desktop App Crashes When Freeing Pointers in FFI Integration

### ISSUE THREAD

**Issue by AbdeMohlbi** [flutter/flutter#145658]
### Steps to reproduce

I'm encountering a perplexing issue with my Flutter desktop application. Initially, I faced performance challenges when parsing a large CSV file using Dart, leading to unacceptably long loading times. In an attempt to optimize this process, I adopted an approach inspired by the framework Tauri, leveraging Go instead of Rust. After compiling my Go code into a DLL file and integrating it with Flutter via FFI, the application performance drastically improved, reducing the loading time from over 10 seconds to a mere 1.5 seconds.

However, a new problem emerged. When attempting to free the memory allocated for pointers using 'calloc.free(filePathPtr)' and 'calloc.free(jsonDataPtr)' within the Flutter FFI integration, the desktop application unexpectedly crashes without throwing any exceptions. This behavior is both strange and unexpected, as it disrupts the smooth operation of the application despite the successful integration and performance enhancements achieved through FFI.

This issue poses a significant obstacle in maintaining the stability of the Flutter desktop application while utilizing FFI for improved performance. Any insights or guidance on resolving this unexpected crashing behavior would be greatly appreciated.

### Expected results

 Flutter Desktop App must not crash without throwing an exception or something to help solve the problem

### Actual results

 Flutter desktop app crashes without throwing any error or exception 

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:convert';
import 'dart:ffi';
import 'dart:ui' as ui;
import 'dart:io'; 
import 'package:ffi/ffi.dart';
import 'package:flutter/material.dart';
import 'package:window_manager/window_manager.dart';
typedef ReadDataFromFileFunc = Pointer<Utf8> Function(Pointer<Utf8>);
typedef ReadDataFromFile = Pointer<Utf8> Function(Pointer<Utf8>);
enum FetchState {
  loading,
  success,
  error,
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await windowManager.ensureInitialized();
  WindowOptions windowOptions = const WindowOptions(
    size: ui.Size(800, 600),
    minimumSize: ui.Size(400, 400),
    title: 'prompts_manager',
    center: true,
    backgroundColor: Colors.transparent,
    skipTaskbar: false,
    titleBarStyle: TitleBarStyle.normal,
  );
  windowManager.waitUntilReadyToShow(windowOptions, () async {
    await windowManager.show();
    await windowManager.focus();
  });
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.blue),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  FetchState state = FetchState.loading;
  List<Prompt> currentPrompts = [];
  List<Prompt> oldPrompts = [];
  void getPrompts() {
    try {
      oldPrompts = currentPrompts;
      setState(() {
        state = FetchState.loading;
      });
      currentPrompts.clear();
      String filePath = 'bin/data.json';
    

      final DynamicLibrary yourLibrary = Platform.isWindows
          ? DynamicLibrary.open('bin/mydll.dll')
          : DynamicLibrary.process();

      final ReadDataFromFile readDataFromFile = yourLibrary
          .lookupFunction<ReadDataFromFileFunc, ReadDataFromFile>('ReadDataFromFile');
      Pointer<Utf8> filePathPtr = filePath.toNativeUtf8();
      Pointer<Utf8> jsonDataPtr = readDataFromFile(filePathPtr);
      String jsonData = (jsonDataPtr.cast<Utf8>()).toDartString();
      for (Map<String, dynamic> item in jsonDecode(jsonData)) {
        currentPrompts.add(Prompt(item['act'], item['prompt']));
        //calloc.free(filePathPtr);
        //calloc.free(jsonDataPtr);
      }
      setState(() {
        state = FetchState.success;
      });
    } on Exception {
      setState(() {
        state = FetchState.error;
      });
    }
  }

  void filterData(String filter) async {
    setState(() {
      state = FetchState.loading;
    });

    try {
      setState(() {
        currentPrompts = oldPrompts
            .where((prompt) =>
                prompt.act.toLowerCase().contains(filter.toLowerCase()) ||
                prompt.content.toLowerCase().contains(filter.toLowerCase()))
            .toList();
      });
      setState(() {
        state = FetchState.success;
      });
    } on Exception {
      setState(() {
        state = FetchState.error;
      });
    }
  }

  @override
  void initState() {
    getPrompts();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: AnimatedSwitcher(
          duration: const Duration(milliseconds: 1000), // Animation duration
          transitionBuilder: (Widget child, Animation<double> animation) {
            return ScaleTransition(
              scale: animation,
              child: child,
            );
          },
          child: switch (state) {
            FetchState.error =>
              const Center(child: Text("Something Went Wrong")),
            FetchState.loading =>
              const Center(child: CircularProgressIndicator()),
            FetchState.success => SafeArea(
                child: Column(
                  children: [
                    const SizedBox(
                      height: 20,
                    ),
                    TextField(
                      onChanged: (value) {
                        filterData(value);
                      },
                      decoration: const InputDecoration(
                        border: OutlineInputBorder(
                          borderSide: BorderSide(color: Colors.black),
                        ),
                        enabledBorder: OutlineInputBorder(
                          borderSide: BorderSide(color: Colors.black),
                        ),
                        focusedBorder: OutlineInputBorder(
                          borderSide: BorderSide(color: Colors.black),
                        ),
                        label: Text('Search'),
                        prefixIcon:
                            Icon(Icons.search_sharp, color: Colors.black),
                        labelStyle: TextStyle(
                          color: Colors.black,
                        ),
                      ),
                    ),
                    Text(
                        " total environment variables ${currentPrompts.length}"),
                    const SizedBox(
                      height: 20,
                    ),
                    Expanded(
                      flex: 3,
                      child: ListView.builder(
                        itemCount: currentPrompts.length,
                        itemBuilder: (BuildContext context, int index) {
                          return ExpansionTile(
                              collapsedIconColor: Colors.blue,
                              textColor: Colors.blue,
                              title: Text(
                                currentPrompts[index].act,
                                style: const TextStyle(fontSize: 18.0),
                              ),
                              children: [
                                ListTile(
                                  title: Text(
                                    currentPrompts[index].content,
                                    style: const TextStyle(fontSize: 16.0),
                                  ),
                                )
                              ]);
                        },
                      ),
                    ),
                  ],
                ),
              ),
          },
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          getPrompts();
        },
        child: const Icon(Icons.refresh),
      ),
    );
  }
}

class Prompt {
  final String act;
  final String content;
  Prompt(this.act, this.content);
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

nothing appears 

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.19.4, on Microsoft Windows [version 10.0.19045.3930], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.3.2)
[√] Android Studio (version 2023.3)
[√] VS Code, 64-bit edition (version 1.87.0)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by AbdeMohlbi** [comment]
update 1 after running 'flutter upgrade' with the two lines of free active the app tries to launch then stops with message : 
'Lost connection to device.'
update 2 the app now it says only 'Lost connection to device.'

**Comment by AbdeMohlbi** [comment]
this is the go code (in this code i tried using json format hoping the issue was there but it wasn't): 
``
package main

import (
	"C"
	"encoding/json"
	"log"
	"os"
)

type PromptData struct {
	Act    string `json:"act"`
	Prompt string `json:"prompt"`
}

//export ReadDataFromFile
func ReadDataFromFile(filePathPtr *C.char) *C.char {
	filePath := C.GoString(filePathPtr)

	// Read JSON file
	fileContent, err := os.ReadFile(filePath)
	if err != nil {
		log.Fatalf("Error reading JSON file: %v", err)
		return nil
	}

	// Decode JSON
	var prompts []PromptData
	if err := json.Unmarshal(fileContent, &prompts); err != nil {
		log.Fatalf("Error decoding JSON: %v", err)
		return nil
	}

	// Convert prompts to JSON string
	jsonData, err := json.Marshal(prompts)
	if err != nil {
		log.Fatalf("Error encoding JSON: %v", err)
		return nil
	}

	return C.CString(string(jsonData))
}

func main() {
	// This is needed to compile the program as a shared library
}
``
i compiled the code using this command even if this is irrelevant  :go build -o example.dll -buildmode=c-shared example.go

**Comment by moffatman** [comment]
Your free calls are inside the loop. Which means they may run multiple times with the same pointer. Freeing a pointer multiple times is undefined behaviour in C. Just put those calls after the loop, it should work.

**Comment by AbdeMohlbi** [comment]
> Your free calls are inside the loop. Which means they may run multiple times with the same pointer. Freeing a pointer multiple times is undefined behaviour in C. Just put those calls after the loop, it should work. 

Thank you for your attention but i have tried that also and it is the same result i tried to do that to see if flutter can at least tell where is the problem but nothing at all just lost connection to device

**Comment by moffatman** [comment]
What OS are you running on? You could probably get the stack trace if you attach native debugging tools to the running app before crashing it. E.g. I used WinDbg to figure out flutter FFI crash before on windows.

Btw, have you tried with just one of the free() calls? Does it crash with either, or only with both?

**Comment by AbdeMohlbi** [comment]
@moffatman 
 Windows Version (Installed version of Windows is version 10 or higher)
well good idea brother , now i have noticed that : calloc.free(jsonDataPtr); is the one causing the problem 
well the debugger has caused some problems at the start so i had to rerun it multiple times but now when it crashs: 
Failed to send request: {"jsonrpc":"2.0","id":"3419","method":"lookupResolvedPackageUris","params":{"isolateId":"isolates/3263750300611443","uris":["package:flutter/src/widgets/framework.dart"],"local":true}}

**Comment by moffatman** [comment]
That error is not related

I think the problem is, CGo allocated the CString memory using microsoft C-runtime `malloc`. It has to be freed with C-runtime `free`. And package:ffi calloc.free calls `CoTaskMemFree`. 

It may be easiest if you can create a new FFI function to free the string. Which would just call `C.free` within Go on the passed pointer. Then you are sure to use the proper memory management method. e.g.

```go
func freeString(ptr *C.char) {
    C.free(ptr)
}
```

```dart

typedef GoFreeStringNative = Void Function(Pointer<Utf8>);
typedef GoFreeString = void Function(Pointer<Utf8>);

// ...

final GoFreeString freeString = yourLibrary
          .lookupFunction<GoFreeStringNative, GoFreeString>('freeString');

freeString(jsonDataPtr);

```

More info

- https://github.com/dart-archive/ffi/pull/144
- https://learn.microsoft.com/en-us/windows/win32/memory/comparing-memory-allocation-methods

**Comment by AbdeMohlbi** [comment]
@moffatman 
Thanks for your input, but based on my research, this issue may arise due to various factors. For instance, when the toDartString() method is invoked, memory management is handled by the garbage collector. The problem likely stems from the fact that memory isn't allocated using calloc, which seems rather limiting. As you mentioned, the inability to free memory allocated outside of calloc poses a challenge. In my opinion, it's somewhat impractical to expect users to manage memory themselves, especially when native code references the same space, rendering it impossible to free. This approach seems somewhat odd and warrants reconsideration by the function's creator.

**Comment by moffatman** [comment]
Are you just pasting chat gpt... have you tried my suggestion?

**Comment by AbdeMohlbi** [comment]
nah , i asked some AI but they talk nonesense

**Comment by dcharkes** [comment]
👍 to @moffatman's comments.

As best practice, the code that allocates native memory should also free the native memory. In other words, if some C code that is called through FFI allocates native memory, there should be another FFI call to C code right next to it to free the native memory.

This is due to how the memory management is set up on Windows.

1. The Windows API has multiple allocate and free methods all with their own pros and cons. `alloc`+`free` is not compatible with `HeapAlloc`/`HeapFree` or `CoTaskCalloc`(and its free).
2. On Windows, every `dll` has its own `alloc`/`free` that are not compatible with each other.

As @moffatman mentioned, if the problem is reproducible on Flutter desktop or Dart standalone on Windows, running the executable from visual studio can make you catch the problematic line in the debugger.

**Comment by AbdeMohlbi** [comment]
@moffatman @dcharkes 
the solutions u provided was solved my problem and now i understand what happend and why .
i just wonder why flutter didn't throw an exception are any kind of hint when attemtipng to free a pointer wich was not allocated by the garbage collector .

i have noticed that when attempting to free the pointers they aren't free which is weird :

![cap](https://github.com/flutter/flutter/assets/116356835/f57303a0-f10b-4733-830a-cb929c629073)

**Comment by moffatman** [comment]
I don't think flutter/dart can do anything here. The crash is within native code (Go or C runtime). They close the program before anything gets back to dart

**Comment by AbdeMohlbi** [comment]
so the native code forces flutter to shutdown ?

**Comment by AbdeMohlbi** [comment]
@moffatman 
so if i called the library on a seperat thread it must not crash beacuse it is on a nother thred ?

**Comment by moffatman** [comment]
Separate thread it will probably still crash. Unless you set up your thread with certain interrupt/signal handlers to catch the SIGINT SIGBUS or whatever. And I am not even sure you can do that on Windows

**Comment by AbdeMohlbi** [comment]
yup still crashes any way ,thanks for the guidance brother i was curios about this i'll close the issue because nothing left to do here.
