### ISSUE TITLE
flutter packages get - Invalid argument(s): Minimum version ("2.0.0-dev.23.0") must be less than maximum ("2.0.0-dev.16.0").

### ISSUE THREAD

**Issue by agreensh** [flutter/flutter#14771]
Invalid argument(s): Minimum version ("2.0.0-dev.23.0") must be less than maximum ("2.0.0-dev.16.0").

## Steps to Reproduce
Create a new package 
eg flutter create -t plugin testplug
OR
run 'flutter packages get' in an existing package directory.

## Logs
flutter create -t plugin testplug
Creating project testplug...
  testplug/ios/Assets/.gitkeep (created)
  testplug/ios/testplug.podspec (created)
  testplug/ios/.gitignore (created)
  testplug/CHANGELOG.md (created)
  testplug/.gitignore (created)
  testplug/testplug_android.iml (created)
  testplug/ios/Classes/TestplugPlugin.m (created)
  testplug/ios/Classes/TestplugPlugin.h (created)
  testplug/android/settings.gradle (created)
  testplug/android/.gitignore (created)
  testplug/android/gradle.properties (created)
  testplug/android/src/main/AndroidManifest.xml (created)
  testplug/testplug.iml (created)
  testplug/README.md (created)
  testplug/pubspec.yaml (created)
  testplug/lib/testplug.dart (created)
  testplug/LICENSE (created)
  testplug/android/build.gradle (created)
  testplug/android/src/main/java/com/example/testplug/TestplugPlugin.java (created)
  testplug/.idea/libraries/Dart_SDK.xml (created)
  testplug/.idea/libraries/Flutter_for_Android.xml (created)
  testplug/.idea/modules.xml (created)
  testplug/.idea/workspace.xml (created)
  testplug/.idea/runConfigurations/example_lib_main_dart.xml (created)
Running "flutter packages get" in testplug...             
Invalid argument(s): Minimum version ("2.0.0-dev.23.0") must be less than maximum ("2.0.0-dev.16.0").
package:pub_semver/src/version_range.dart 59         new VersionRange
package:pub/src/pubspec.dart 366                     Pubspec._ensureEnvironment
package:pub/src/pubspec.dart 331                     Pubspec.dartSdkConstraint
package:pub/src/solver/backtracking_solver.dart 511  BacktrackingSolver._checkPubspecMatchesSdkConstraint
package:pub/src/solver/backtracking_solver.dart 474  BacktrackingSolver._checkVersion
package:pub/src/solver/backtracking_solver.dart 432  BacktrackingSolver._findValidVersion.<fn>
dart:async                                           Future.doWhile
package:pub/src/solver/backtracking_solver.dart 430  BacktrackingSolver._findValidVersion
package:pub/src/solver/backtracking_solver.dart 337  BacktrackingSolver._versionQueueFor
package:pub/src/solver/backtracking_solver.dart 290  BacktrackingSolver._solve.<fn>
dart:async                                           _completeOnAsyncReturn
package:pub/src/solver/backtracking_solver.dart 315  BacktrackingSolver._solve.<fn>
dart:async                                           _completeOnAsyncReturn
package:pub/src/solver/version_selection.dart 64     VersionSelection.select
dart:async                                           _completeOnAsyncReturn
package:pub/src/solver/version_selection.dart 91     VersionSelection._addDependencies
dart:async                                           _completeOnAsyncReturn
package:pub/src/solver/version_selection.dart 91     VersionSelection._addDependencies
===== asynchronous gap ===========================
dart:async                                           _Completer.completeError
package:pub/src/solver/backtracking_solver.dart      BacktrackingSolver._checkVersion
===== asynchronous gap ===========================
dart:async                                           _asyncThenWrapperHelper
package:pub/src/solver/backtracking_solver.dart 458  BacktrackingSolver._checkVersion
package:pub/src/solver/backtracking_solver.dart 432  BacktrackingSolver._findValidVersion.<fn>
===== asynchronous gap ===========================
dart:async                                           new Future.microtask
package:pub/src/solver/backtracking_solver.dart 430  BacktrackingSolver._findValidVersion.<fn>
dart:async                                           Future.doWhile
package:pub/src/solver/backtracking_solver.dart 430  BacktrackingSolver._findValidVersion
package:pub/src/solver/backtracking_solver.dart 337  BacktrackingSolver._versionQueueFor
===== asynchronous gap ===========================
dart:async                                           Future.doWhile
package:pub/src/solver/backtracking_solver.dart 430  BacktrackingSolver._findValidVersion
package:pub/src/solver/backtracking_solver.dart 337  BacktrackingSolver._versionQueueFor
===== asynchronous gap ===========================
dart:async                                           _asyncThenWrapperHelper
package:pub/src/solver/backtracking_solver.dart 327  BacktrackingSolver._versionQueueFor
package:pub/src/solver/backtracking_solver.dart 290  BacktrackingSolver._solve.<fn>
===== asynchronous gap ===========================
dart:async                                           _asyncThenWrapperHelper
package:pub/src/solver/backtracking_solver.dart 279  BacktrackingSolver._solve.<fn>
dart:async                                           _completeOnAsyncReturn
package:pub/src/solver/backtracking_solver.dart 315  BacktrackingSolver._solve.<fn>
dart:async                                           _completeOnAsyncReturn
package:pub/src/solver/version_selection.dart 64     VersionSelection.select
dart:async                                           _completeOnAsyncReturn
package:pub/src/solver/version_selection.dart 91     VersionSelection._addDependencies
dart:async                                           _completeOnAsyncReturn
package:pub/src/solver/version_selection.dart 91     VersionSelection._addDependencies
===== asynchronous gap ===========================
dart:async                                           Future.doWhile
package:pub/src/solver/backtracking_solver.dart 279  BacktrackingSolver._solve
===== asynchronous gap ===========================
dart:async                                           new Future.microtask
package:pub/src/solver/backtracking_solver.dart 277  BacktrackingSolver._solve
package:pub/src/solver/backtracking_solver.dart 179  BacktrackingSolver.solve
===== asynchronous gap ===========================
dart:async                                           _asyncThenWrapperHelper
package:pub/src/solver/backtracking_solver.dart 160  BacktrackingSolver.solve
package:pub/src/solver/version_solver.dart 42        resolveVersions.<fn>
package:pub/src/log.dart 409                         progress
package:pub/src/solver/version_solver.dart 40        resolveVersions
package:pub/src/entrypoint.dart 195                  Entrypoint.acquireDependencies
===== asynchronous gap ===========================
dart:async                                           new Future.microtask
package:pub/src/entrypoint.dart 194                  Entrypoint.acquireDependencies
package:pub/src/command/get.dart 38                  GetCommand.run
package:args/command_runner.dart 194                 CommandRunner.runCommand
===== asynchronous gap ===========================
dart:async                                           new Future.microtask
package:args/command_runner.dart 142                 CommandRunner.runCommand
package:pub/src/command_runner.dart 167              PubCommandRunner.runCommand.<fn>
dart:async                                           new Future.sync
package:pub/src/utils.dart 103                       captureErrors.<fn>
package:stack_trace                                  Chain.capture
package:pub/src/utils.dart 118                       captureErrors
package:pub/src/command_runner.dart 167              PubCommandRunner.runCommand
---- Log transcript ----
FINE: Pub 2.0.0-dev.16.0
MSG : Resolving dependencies...
SLVR: Solving dependencies:
    | - flutter any from sdk (flutter)
SLVR: * start at root
IO  : Get versions from https://pub.dartlang.org/api/packages/vector_math.
IO  : HTTP GET https://pub.dartlang.org/api/packages/vector_math
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 086458DD-CFC2-4794-81A0-38A0320D6752
    | X-Pub-Environment: flutter_cli:create_plugin
    | user-agent: Dart pub 2.0.0-dev.16.0
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/vector_math
    | took 0:00:00.297304
    | transfer-encoding: chunked
    | date: Mon, 19 Feb 2018 15:39:31 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
IO  : Get versions from https://pub.dartlang.org/api/packages/http.
IO  : HTTP GET https://pub.dartlang.org/api/packages/http
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 086458DD-CFC2-4794-81A0-38A0320D6752
    | X-Pub-Environment: flutter_cli:create_plugin
    | user-agent: Dart pub 2.0.0-dev.16.0
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/http
    | took 0:00:00.135209
    | transfer-encoding: chunked
    | date: Mon, 19 Feb 2018 15:39:31 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
IO  : Get versions from https://pub.dartlang.org/api/packages/collection.
IO  : HTTP GET https://pub.dartlang.org/api/packages/collection
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 086458DD-CFC2-4794-81A0-38A0320D6752
    | X-Pub-Environment: flutter_cli:create_plugin
    | user-agent: Dart pub 2.0.0-dev.16.0
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/collection
    | took 0:00:00.133083
    | transfer-encoding: chunked
    | date: Mon, 19 Feb 2018 15:39:31 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
IO  : Get versions from https://pub.dartlang.org/api/packages/typed_data.
IO  : HTTP GET https://pub.dartlang.org/api/packages/typed_data
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 086458DD-CFC2-4794-81A0-38A0320D6752
    | X-Pub-Environment: flutter_cli:create_plugin
    | user-agent: Dart pub 2.0.0-dev.16.0
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/typed_data
    | took 0:00:00.132382
    | transfer-encoding: chunked
    | date: Mon, 19 Feb 2018 15:39:31 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
IO  : Get versions from https://pub.dartlang.org/api/packages/meta.
IO  : HTTP GET https://pub.dartlang.org/api/packages/meta
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 086458DD-CFC2-4794-81A0-38A0320D6752
    | X-Pub-Environment: flutter_cli:create_plugin
    | user-agent: Dart pub 2.0.0-dev.16.0
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/meta
    | took 0:00:00.133317
    | transfer-encoding: chunked
    | date: Mon, 19 Feb 2018 15:39:31 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
SLVR: | * select flutter 0.0.0 from sdk
SLVR: | | * select sky_engine 0.0.99 from path
SLVR: | | | version 1.1.5 of typed_data doesn't match 1.1.4:
    | | | |   flutter 0.0.0 from sdk -> typed_data 1.1.4 from hosted (typed_data)
SLVR: | | | * select typed_data 1.1.4 from hosted
SLVR: | | | | * select vector_math 2.0.5 from hosted
SLVR: | | | | | * select collection 1.14.5 from hosted
SLVR: | | | | | | version 1.1.2 of meta doesn't match 1.1.1:
    | | | | | | |   flutter 0.0.0 from sdk -> meta 1.1.1 from hosted (meta)
SLVR: | | | | | | * select meta 1.1.1 from hosted
IO  : Get versions from https://pub.dartlang.org/api/packages/http_parser.
IO  : HTTP GET https://pub.dartlang.org/api/packages/http_parser
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 086458DD-CFC2-4794-81A0-38A0320D6752
    | X-Pub-Environment: flutter_cli:create_plugin
    | user-agent: Dart pub 2.0.0-dev.16.0
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/http_parser
    | took 0:00:00.131971
    | transfer-encoding: chunked
    | date: Mon, 19 Feb 2018 15:39:31 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
IO  : Get versions from https://pub.dartlang.org/api/packages/async.
IO  : HTTP GET https://pub.dartlang.org/api/packages/async
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 086458DD-CFC2-4794-81A0-38A0320D6752
    | X-Pub-Environment: flutter_cli:create_plugin
    | user-agent: Dart pub 2.0.0-dev.16.0
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/async
    | took 0:00:00.132456
    | transfer-encoding: chunked
    | date: Mon, 19 Feb 2018 15:39:32 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
IO  : Get versions from https://pub.dartlang.org/api/packages/path.
IO  : HTTP GET https://pub.dartlang.org/api/packages/path
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 086458DD-CFC2-4794-81A0-38A0320D6752
    | X-Pub-Environment: flutter_cli:create_plugin
    | user-agent: Dart pub 2.0.0-dev.16.0
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/path
    | took 0:00:00.132694
    | transfer-encoding: chunked
    | date: Mon, 19 Feb 2018 15:39:32 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
SLVR: | | | | | | | * select http 0.11.3+16 from hosted
IO  : Get versions from https://pub.dartlang.org/api/packages/charcode.
IO  : HTTP GET https://pub.dartlang.org/api/packages/charcode
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 086458DD-CFC2-4794-81A0-38A0320D6752
    | X-Pub-Environment: flutter_cli:create_plugin
    | user-agent: Dart pub 2.0.0-dev.16.0
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/charcode
    | took 0:00:00.448559
    | transfer-encoding: chunked
    | date: Mon, 19 Feb 2018 15:39:32 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
IO  : Get versions from https://pub.dartlang.org/api/packages/source_span.
IO  : HTTP GET https://pub.dartlang.org/api/packages/source_span
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 086458DD-CFC2-4794-81A0-38A0320D6752
    | X-Pub-Environment: flutter_cli:create_plugin
    | user-agent: Dart pub 2.0.0-dev.16.0
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/source_span
    | took 0:00:00.132036
    | transfer-encoding: chunked
    | date: Mon, 19 Feb 2018 15:39:32 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
IO  : Get versions from https://pub.dartlang.org/api/packages/string_scanner.
IO  : HTTP GET https://pub.dartlang.org/api/packages/string_scanner
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 086458DD-CFC2-4794-81A0-38A0320D6752
    | X-Pub-Environment: flutter_cli:create_plugin
    | user-agent: Dart pub 2.0.0-dev.16.0
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/string_scanner
    | took 0:00:00.132869
    | transfer-encoding: chunked
    | date: Mon, 19 Feb 2018 15:39:32 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
SLVR: | | | | | | | | * select http_parser 3.1.1 from hosted
SLVR: | | | | | | | | | * select charcode 1.1.1 from hosted
SLVR: | | | | | | | | | | * select string_scanner 1.0.2 from hosted
SLVR: | | | | | | | | | | | * select source_span 1.4.0 from hosted
SLVR: BacktrackingSolver took 0:00:02.233328 seconds.
    | - Tried 1 solutions
    | - Requested 13 version lists
    | - Looked up 12 cached version lists
    | 
FINE: Resolving dependencies finished (2.2s).
ERR : Invalid argument(s): Minimum version ("2.0.0-dev.23.0") must be less than maximum ("2.0.0-dev.16.0").
FINE: Exception type: ArgumentError
ERR : package:pub_semver/src/version_range.dart 59         new VersionRange
    | package:pub/src/pubspec.dart 366                     Pubspec._ensureEnvironment
    | package:pub/src/pubspec.dart 331                     Pubspec.dartSdkConstraint
    | package:pub/src/solver/backtracking_solver.dart 511  BacktrackingSolver._checkPubspecMatchesSdkConstraint
    | package:pub/src/solver/backtracking_solver.dart 474  BacktrackingSolver._checkVersion
    | package:pub/src/solver/backtracking_solver.dart 432  BacktrackingSolver._findValidVersion.<fn>
    | dart:async                                           Future.doWhile
    | package:pub/src/solver/backtracking_solver.dart 430  BacktrackingSolver._findValidVersion
    | package:pub/src/solver/backtracking_solver.dart 337  BacktrackingSolver._versionQueueFor
    | package:pub/src/solver/backtracking_solver.dart 290  BacktrackingSolver._solve.<fn>
    | dart:async                                           _completeOnAsyncReturn
    | package:pub/src/solver/backtracking_solver.dart 315  BacktrackingSolver._solve.<fn>
    | dart:async                                           _completeOnAsyncReturn
    | package:pub/src/solver/version_selection.dart 64     VersionSelection.select
    | dart:async                                           _completeOnAsyncReturn
    | package:pub/src/solver/version_selection.dart 91     VersionSelection._addDependencies
    | dart:async                                           _completeOnAsyncReturn
    | package:pub/src/solver/version_selection.dart 91     VersionSelection._addDependencies
    | ===== asynchronous gap ===========================
    | dart:async                                           _Completer.completeError
    | package:pub/src/solver/backtracking_solver.dart      BacktrackingSolver._checkVersion
    | ===== asynchronous gap ===========================
    | dart:async                                           _asyncThenWrapperHelper
    | package:pub/src/solver/backtracking_solver.dart 458  BacktrackingSolver._checkVersion
    | package:pub/src/solver/backtracking_solver.dart 432  BacktrackingSolver._findValidVersion.<fn>
    | ===== asynchronous gap ===========================
    | dart:async                                           new Future.microtask
    | package:pub/src/solver/backtracking_solver.dart 430  BacktrackingSolver._findValidVersion.<fn>
    | dart:async                                           Future.doWhile
    | package:pub/src/solver/backtracking_solver.dart 430  BacktrackingSolver._findValidVersion
    | package:pub/src/solver/backtracking_solver.dart 337  BacktrackingSolver._versionQueueFor
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.doWhile
    | package:pub/src/solver/backtracking_solver.dart 430  BacktrackingSolver._findValidVersion
    | package:pub/src/solver/backtracking_solver.dart 337  BacktrackingSolver._versionQueueFor
    | ===== asynchronous gap ===========================
    | dart:async                                           _asyncThenWrapperHelper
    | package:pub/src/solver/backtracking_solver.dart 327  BacktrackingSolver._versionQueueFor
    | package:pub/src/solver/backtracking_solver.dart 290  BacktrackingSolver._solve.<fn>
    | ===== asynchronous gap ===========================
    | dart:async                                           _asyncThenWrapperHelper
    | package:pub/src/solver/backtracking_solver.dart 279  BacktrackingSolver._solve.<fn>
    | dart:async                                           _completeOnAsyncReturn
    | package:pub/src/solver/backtracking_solver.dart 315  BacktrackingSolver._solve.<fn>
    | dart:async                                           _completeOnAsyncReturn
    | package:pub/src/solver/version_selection.dart 64     VersionSelection.select
    | dart:async                                           _completeOnAsyncReturn
    | package:pub/src/solver/version_selection.dart 91     VersionSelection._addDependencies
    | dart:async                                           _completeOnAsyncReturn
    | package:pub/src/solver/version_selection.dart 91     VersionSelection._addDependencies
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.doWhile
    | package:pub/src/solver/backtracking_solver.dart 279  BacktrackingSolver._solve
    | ===== asynchronous gap ===========================
    | dart:async                                           new Future.microtask
    | package:pub/src/solver/backtracking_solver.dart 277  BacktrackingSolver._solve
    | package:pub/src/solver/backtracking_solver.dart 179  BacktrackingSolver.solve
    | ===== asynchronous gap ===========================
    | dart:async                                           _asyncThenWrapperHelper
    | package:pub/src/solver/backtracking_solver.dart 160  BacktrackingSolver.solve
    | package:pub/src/solver/version_solver.dart 42        resolveVersions.<fn>
    | package:pub/src/log.dart 409                         progress
    | package:pub/src/solver/version_solver.dart 40        resolveVersions
    | package:pub/src/entrypoint.dart 195                  Entrypoint.acquireDependencies
    | ===== asynchronous gap ===========================
    | dart:async                                           new Future.microtask
    | package:pub/src/entrypoint.dart 194                  Entrypoint.acquireDependencies
    | package:pub/src/command/get.dart 38                  GetCommand.run
    | package:args/command_runner.dart 194                 CommandRunner.runCommand
    | ===== asynchronous gap ===========================
    | dart:async                                           new Future.microtask
    | package:args/command_runner.dart 142                 CommandRunner.runCommand
    | package:pub/src/command_runner.dart 167              PubCommandRunner.runCommand.<fn>
    | dart:async                                           new Future.sync
    | package:pub/src/utils.dart 103                       captureErrors.<fn>
    | package:stack_trace                                  Chain.capture
    | package:pub/src/utils.dart 118                       captureErrors
    | package:pub/src/command_runner.dart 167              PubCommandRunner.runCommand
---- End log transcript ----
pub get failed (1)

## Flutter Analyze

Gives the same error

flutter analyze
Running "flutter packages get" in testplug...             
Invalid argument(s): Minimum version ("2.0.0-dev.23.0") must be less than maximum ("2.0.0-dev.16.0").
package:pub_semver/src/version_range.dart 59         new VersionRange
package:pub/src/pubspec.dart 366                     Pubspec._ensureEnvironment
package:pub/src/pubspec
...

## Flutter Doctor

flutter doctor
[✓] Flutter (on Mac OS X 10.13.3 17D47, locale en-GB, channel alpha)
    • Flutter version 0.0.21 at /Users/Andy/Downloads/react-native/flutter
    • Framework revision 2e449f06f0 (3 weeks ago), 2018-01-29 14:26:51 -0800
    • Engine revision 6921873c71
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.da1f52592ef73fe3afa485385cb995b9aec0181a

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/Andy/androidsdk
    • Android NDK at /Users/Andy/androidsdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/Andy/androidsdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected devices
    • Android SDK built for x86 64 • emulator-5554                            • android-x64 • Android 6.0 (API 23) (emulator)
    • iPhoneX                      • 23768a229413152894f2f52b445e0c68d91118ae • ios         • iOS 11.2.5
    • Andy’s iPad                  • dcb26df502ea724a72de6c75b46122e313b14ca4 • ios         • iOS 11.2.5
    • iPhone 6                     • 8342AB45-E2BD-4F29-B205-B0B5B92652E0     • ios         • iOS 11.2 (simulator)

**Comment by agreensh** [comment]
After 'flutter upgrade' said I had the latest version, I cloned the flutter repository again (to a different directory), then 'flutter doctor' on the newly downloaded flutter caused the download of a different version of dart. This fixed the issue.

Looks like 'flutter upgrade' is not updating the dart version?

**Comment by zoechi** [comment]
From all the reports of this issue I got the impression that this was only an issue on this specific Flutter version.

**Comment by tvolkert** [comment]
`flutter upgrade` should take you to the dev channel (on which we just published `v0.1.3`).  If that doesn't work, you can try manually switching to the dev channel using `flutter channel dev` (then upgrading via `flutter upgrade`).

**Comment by tvolkert** [comment]
@agreensh did switching to the dev channel fix things?

**Comment by iambudi** [comment]
I run flutter gallery example and get the same issue.
ERR : Invalid argument(s): Minimum version ("2.0.0-dev.23.0") must be less than maximum ("2.0.0-dev.16.0").
Switching to channel dev still does not solve the issue.

**Comment by guid-empty** [comment]
@tvolkert hello
attempt to use does not resolve the issue:
`
flutter channel dev && flutter upgrade


Switching to flutter channel 'dev'...
Upgrading Flutter from /home/andreysmirnov/flutter...
Transitioning from 'alpha' to 'dev'...
From https://github.com/flutter/flutter
   eabfd57..50b7fad  master     -> origin/master
Already up-to-date.

Upgrading engine...
Already up-to-date.

Flutter 0.0.21 • channel alpha • https://github.com/flutter/flutter.git
Framework • revision 2e449f06f0 (3 weeks ago) • 2018-01-29 14:26:51 -0800
Engine • revision 6921873c71
Tools • Dart 2.0.0-dev.16.0
`

is something else to resolve this isse?

**Comment by iambudi** [comment]
Just tried switching to alpha and beta channel, still does not luck 🤔

**Comment by iambudi** [comment]
Here's to solve the issue.
1. `which flutter` and Rename the flutter directory.
2. Recloning the flutter repo https://github.com/flutter/flutter.git
3. Run flutter doctor
4. Go to flutter_gallery example and run `flutter run`
🎉🎉🎉

**Comment by agreensh** [comment]
@iambudi I already stated that above

> After 'flutter upgrade' said I had the latest version, I cloned the flutter repository again (to a different directory), then 'flutter doctor' on the newly downloaded flutter caused the download of a different version of dart. This fixed the issue.

**Comment by zoechi** [comment]
dup of #14515 ?

**Comment by iambudi** [comment]
When doing flutter upgrade, it should replace the flutter binary to a newer one right?

**Comment by zoechi** [comment]
@iambudi  It should, but that seems to be broken in that specific version

**Comment by pulyaevskiy** [comment]
Could this also be the reason I'm getting error when publishing to Pub?
https://github.com/dart-lang/pub/issues/1809

**Comment by agreensh** [comment]
@pulyaevskiy Yes, looks the same. Try deleting your flutter directory, then re-clone flutter  from git, then run 'flutter doctor' so it fetches all its required packages.
Note, this is not a fix, but a workaround.

**Comment by pulyaevskiy** [comment]
I'm not sure if I can do this on the Pub server which runs the command. See error output here:
https://pub.dartlang.org/packages/parallax_image#-analysis-tab-

Locally everything works for me (though I have ~ a week old version of flutter).

**Comment by agreensh** [comment]
Agreed. Looks like one of the maintainers needs to do it!

**Comment by tvolkert** [comment]
> dup of #14515

Yep, looks like it.  I'm gonna close this one and make that one the canonical issue.
