### ISSUE TITLE
Flutter 3.19.5: Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.

### ISSUE THREAD

**Issue by JDongKhan** [flutter/flutter#148050]
### Steps to reproduce

from online

### Expected results

no crash

### Actual results

crash

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console

0	CoreFoundation ___exceptionPreprocess + 164
1	libobjc.A.dylib  _objc_exception_throw + 60
2	CoreAutoLayout 0x00000001b4e42000 + 22216
3	CoreAutoLayout 0x00000001b4e42000 + 47836
4	CoreAutoLayout 0x00000001b4e42000 + 47088
5	CoreAutoLayout 0x00000001b4e42000 + 46460
6	UIKitCore -[UIView(Hierarchy) layoutSubviews] + 136
7	UIKitCore -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1528
8	QuartzCore CA::Layer::layout_if_needed(CA::Transaction*) + 500
9	QuartzCore CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 144
10	QuartzCore CA::Context::commit_transaction(CA::Transaction*, double, double*) + 464
11	QuartzCore CA::Transaction::commit() + 648
12	QuartzCore CA::Transaction::flush_as_runloop_observer(bool) + 88
13	CoreFoundation ___CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 36
14	CoreFoundation ___CFRunLoopDoObservers + 548
15	CoreFoundation ___CFRunLoopRun + 1028
16	CoreFoundation _CFRunLoopRunSpecific + 608
17	Flutter fml::MessageLoopDarwin::Run() (message_loop_darwin.mm:52)
18	Flutter void* std::_LIBCPP_ABI_NAMESPACE::__thread_proxy[abi:v15000]<std::_LIBCPP_ABI_NAMESPACE::tuple<std::_LIBCPP_ABI_NAMESPACE::unique_ptr<std::_LIBCPP_ABI_NAMESPACE::__thread_struct, std::_LIBCPP_ABI_NAMESPACE::default_delete<std::_LIBCPP_ABI_NAMESPACE::__thread_struct> >, fml::Thread::Thread(std::_LIBCPP_ABI_NAMESPACE::function<void (fml::Thread::ThreadConfig const&)> const&, fml::Thread::ThreadConfig const&)::$_0> >(void*) (message_loop_impl.cc:0)
19	libsystem_pthread.dylib __pthread_start + 136
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4 23E214 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.19.5 on channel stable at /Users/jd/fvm/versions/3.19.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (6 周前), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/jd/Documents/sdk/android-sdk-macosx
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Community Edition (version 2021.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 212.5744

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

```

</details>

**Comment by darshankawar** [comment]
@JDongKhan 
Is that the only log you get ?
If we go by it, the `Flutter` frames point to `_LIBCPP_ABI_NAMESPACE` for which you can check if [this](https://github.com/flutter/flutter/issues/136628) resembles your case or not.

For rest of the log, it looks similar to https://github.com/flutter/flutter/issues/135501 which was already fixed per https://github.com/flutter/flutter/issues/135501#issuecomment-1996172081. You seem to be on 3.19.5 which is already higher than the comment mentions. Can you confirm if the crash occurs in latest version or in older ?

**Comment by JDongKhan** [comment]
It has existed for a long time in version 3.13.9, and still exists when I recently upgraded to 3.19.5.

**Comment by darshankawar** [comment]
@JDongKhan 
Do you have the list of devices / iOS versions on which the crash occurs ? You can also try [this](https://github.com/flutter/flutter/issues/135501#issuecomment-1743958796) and see if it is still replicable at your end or not.

**Comment by JDongKhan** [comment]
Tks, It only happened twice, I will observe for a while longer.
