### ISSUE TITLE
iOS style zoom transition

### ISSUE THREAD

**Issue by MitchellGoodwin** [flutter/flutter#150588]
For WWDC24, Apple showed a new page transition. [Link to a video talking about it](https://www.youtube.com/watch?v=UDaNFV1Ll3E)

Some definitions because talking about page transitions is hard. 
Home page: the top level page when talking about this transition. 
Preview view: the view shown somewhere on the home page. When tapped, it plays a zoom transition going to the next page. Detailed view: the new page after the transition. Shows a full screen version of the preview view. Can have UI elements that were not shown in the preview view.
Sibling view: a detailed view that can be routed to directly from another detailed view. Either page can go directly bake to the home page.

![zoom-transition](https://github.com/flutter/flutter/assets/58190796/cc95cae1-09f9-4a96-8bb2-babe928af222)

The transition starts from a preview view on the previous page. From that preview view, it zooms outwards to fill the whole page. When the view goes back to the original page, then the zoom reverses and ends at the location of the preview image. So the transition needs to adjust based on the dimensions of it's preview.

The underlying page appears to darken and zoom slightly in the opposite direction. The navbar title also does a hero transition upwards to the back button location.

This is all somewhat similar to the CupertinoContextMenu animation, except instead of finishing at a modal view with a menu, it resolves to a full page.

![zoom-transition-drag](https://github.com/flutter/flutter/assets/58190796/3ee3d09b-ab55-419b-8e2f-c3e645aabdca)

The new page can go backwards with a swipe at the edge of the screen on a partial swipe the page transition will match the location of the touch on the screen. On a partial swipe, the page will not finish the pop and return to the detailed view.

![zoom-transition-siblings](https://github.com/flutter/flutter/assets/58190796/456f4990-7636-486d-91f8-c896c4a86c39)

This shows a possibility of going directly from one detailed view to another. The home page has multiple preview views with zoom transitions attatched. The user goes to one detailed view, then goes directly to another sibling detailed view. This transition from detailed view to another detailed view is a standard Cupertino transition that we already support. But when going directly back to the home page, the zoom transition adjusts to finish at the correct preview view for the latest detail view.

**Comment by MaherSafadii** [comment]
hope this gets added soon

**Comment by MaherSafadii** [comment]
@MitchellGoodwin this has been achieved & published in a package too, here's a [showcase](https://x.com/imadetheseworks/status/1907460496061550864) for it, the package is called [heroine](https://pub.dev/packages/heroine/changelog), maybe the new "available on pub" label can be useful here.

**Comment by MitchellGoodwin** [comment]
> [@MitchellGoodwin[<img alt="" width="15" height="15" src="chrome-extension://dlebflppeeemcdpidccbiblndppbmjmh/ospo-chrome-ext-logo.png">](https://teams.googleplex.com/mitchgoodwin@google.com)](https://github.com/MitchellGoodwin) this has been achieved & published in a package too, here's a [showcase](https://x.com/imadetheseworks/status/1907460496061550864) for it, the package is called [heroine](https://pub.dev/packages/heroine/changelog), maybe the new "available on pub" label can be useful here.

That looks really good! I'm going to set aside time to look into heroine.

**Comment by MaherSafadii** [comment]
I just released that the iOS 18 zoom transition feature is still in a prerelease version so keep that in mind.

**Comment by chotixity** [comment]
> [@MitchellGoodwin](https://github.com/MitchellGoodwin) this has been achieved & published in a package too, here's a [showcase](https://x.com/imadetheseworks/status/1907460496061550864) for it, the package is called [heroine](https://pub.dev/packages/heroine/changelog), maybe the new "available on pub" label can be useful here.

It's far better off provided as first party in the PageTransitions

**Comment by timcreatedit** [comment]
> It's far better off provided as first party in the PageTransitions

I agree with this, however I don't know if Flutter's API is flexible enough for this.

The part that stumps me a little bit at the moment is how the nav bar basically stays above the transitioning route... Since in Flutter the `CupertinoNavigationBar` would be part of the child subtree of the route, I don't really see a straightforward way to match this 1:1 with Flutter's built-in tools. With nested `Hero`s/`Heroine`s, it would probably be possible, but both don't support flying nested heroes in the same transition at the moment.

**Comment by timcreatedit** [comment]
Other things might be problematic as well. I am trying to match the `delegatedTransition` of the route behind it to Apple's version, but the scaling down of the route behind it is also tricky to achieve.

At the route transition level, we only have the entire subtree to play with, so if I do a `Transform.scale`, it scales the scaffold, and thus cuts off the content incorrectly. Notice how the list content is cut off in the video.

https://github.com/user-attachments/assets/bc498226-88d0-4a12-aa6f-2b7f3bcffb77

Also SwiftUI doesn't just scale the entire view behind it, but only the list where the transition came from it seems? At least that's how it looks in Apple Music, in the GIFs above it's harder to see because there is no other content besides the navigation bar.

**Comment by timcreatedit** [comment]
> The part that stumps me a little bit at the moment is how the nav bar basically stays above the transitioning route...

This is the closest I could get by manipulating user gesture handling on the parent navigator.

It's quite finicky though and still doesn't look similar enough

https://github.com/user-attachments/assets/a382a5c2-6744-43f7-856b-df32eaffb737

**Comment by MitchellGoodwin** [comment]
> It's quite finicky though and still doesn't look similar enough

Is this on Flutter master? The navbar looks similar to some behavior from before this PR: #164956. I'm wondering if it's still trying to do the wrong background in this case.

> The part that stumps me a little bit at the moment is how the nav bar basically stays above the transitioning route... Since in Flutter the CupertinoNavigationBar would be part of the child subtree of the route, I don't really see a straightforward way to match this 1:1 with Flutter's built-in tools.

Most elements of the CupertinoNavigationBar are a part of a Hero transition. I think there's a path where the navigation bar elements are able to coordinate with each other, but that alone may be a solid bit of work and would need adjustments to the framework at minimum, but likely it would need this transition to just be in core Flutter. In my opinion, it might be better to ignore the navbar for now. I think I'm going to be taking a look at Cupertino navbars in a bit and making some proposals for changes to enable more use cases, and I think this falls under that bucket.

> Also SwiftUI doesn't just scale the entire view behind it, but only the list where the transition came from it seems? 

I agree. They are doing something clever. To my eye it looks like they are scaling the view, then part way through fading into a different scaling view, but I'm not confident that that's what's happening. I think just scaling the whole thing in Flutter is likely going to look odd, from what I understand the scaling happens individually to every element in the transformation, and when it's done at this scale it can look odd. This is from the engine scaling say a box and font differently depending on the platform.

**Comment by timcreatedit** [comment]
I just found out that SwiftUI even lets you pinch to dismiss, including simulating the rotation with a spring...

Seems like there is a lot of ground to cover still. Flutter Heroes don't have a concept of rotation at all, since they just use `Rect`s

https://github.com/user-attachments/assets/294374b4-9e59-4686-a847-7428ee1ed314

**Comment by MitchellGoodwin** [comment]
> I just found out that SwiftUI even lets you pinch to dismiss, including simulating the rotation with a spring...
> 
> Seems like there is a lot of ground to cover still. Flutter Heroes don't have a concept of rotation at all, since they just use `Rect`s

I agree, there's a few challenges there. If a first version doesn't support the spin in particular, that wouldn't be the worst. The pinch seems doable.

Just ideating, but could the hero be a Rect around the visible element that can spin? Maybe using `HitTestBehavior.deferToChild`?

**Comment by ercantomac** [comment]
If it would help, I can provide a custom `Tween<Rect?>` builder to be used as the `createRectTween` property of `Hero` that matches the motion on iOS

**Comment by timcreatedit** [comment]
> Just ideating, but could the hero be a Rect around the visible element that can spin? Maybe using `HitTestBehavior.deferToChild`?

I think you might be onto something and I might have been overthinking it. Since the rotation always ends at 0, the Hero doesn't actually need to know about it and it might be fine to just transform the child.

> If it would help, I can provide a custom Tween<Rect?> builder to be used as the createRectTween property of Hero that matches the motion on iOS

It could be the way to go if we don't want to refactor `Hero` to be driven by a simulation like in my package. It would need to take the velocity of a dismiss gesture into account, and use spring simulations to calculate x, y, width, height (and rotation) :)
