### ISSUE TITLE
Change the default look of CupertinoListSection to the new default

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#154333]
From the API docs, `CupertinoListSection` is modeled after the iOS settings screen. However, there seem to be a bunch of fidelity issues when comparing the settings screen and the first example in the API docs (`flutter create --sample=cupertino.CupertinoListSection.1 mysample`):

1. Padding is missing around the list section itself
2. Rounded corners are missing on the list section itself
3. Rounded corners are missing on the leading color box

**Comment by mit-mit** [comment]
cc @sethladd

**Comment by danagbemava-nc** [comment]
| flutter | iOS Settings App | 
| -- | -- |
| <img src="https://github.com/user-attachments/assets/50b73dc0-1e67-4ed7-9596-620e7ae9af01" width="300"/> | <img src="https://github.com/user-attachments/assets/b7a0da44-ccf7-4a8d-b290-035991d16ea7" width="300"/> |

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.6.1 23G93 darwin-arm64, locale en-US)
    • Flutter version 3.24.1 on channel stable at /Users/deanli/dev/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (9 days ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2
```

```
[!] Flutter (Channel master, 3.25.0-1.0.pre.170, on macOS 14.6.1 23G93 darwin-arm64, locale en-US)
    • Flutter version 3.25.0-1.0.pre.170 on channel master at /Users/deanli/dev/master
    ! Warning: `flutter` on your path resolves to /Users/deanli/dev/stable/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/deanli/dev/master. Consider adding /Users/deanli/dev/master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/deanli/dev/stable/bin/dart, which is not inside your current Flutter SDK checkout at /Users/deanli/dev/master. Consider adding /Users/deanli/dev/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9a622420 (8 hours ago), 2024-08-29 01:08:34 -0400
    • Engine revision f48ecf5b49
    • Dart version 3.6.0 (build 3.6.0-193.0.dev)
    • DevTools version 2.39.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.
```
</details>

**Comment by MitchellGoodwin** [comment]
This may be mostly issues with the sample and possibly some opportunities for improving the API. 

1. We used to have default padding around the list section, but we removed it deliberately as they limited the customizability of the widget. The original issue: #121543 Now to have padding you need to wrap the widget with something to control it's layout. That sample code was missed to be updated.

2. The inset grouped constructor will give you the rounded corners. Maybe we could change the sample to use those as well? I don't know if the base constructor is used much by Apple design. Maybe the inset grouped constructor should be moved to it's own class so it can be highlighted as more important? It might be better to make them the default constructor but that would be a breaking change.

3. The list tile accepts any kind of widget for the leading space. We should probably update the sample to have rounded corners on those. I'm not sure we need specific widget for that, we want to keep it customizable.

**Comment by Piinks** [comment]
1. This might be that the list section needs to be put in a list. The notch would be accounted for in how the list applies default padding.
2. @MitchellGoodwin is spot on, rounded corners are supported by the .insetGrouped 
3. Is this referring to the icons of each row of the list? We can update that too in the sample. The native one looks like those are just the icons. Like Mitchell said, we can put whatever we want in that space.

I can push a PR to update the sample today, from there we can check for any other fidelity issues that are not supported.

**Comment by Piinks** [comment]
Oh wait, there are two samples in the docs.

@mit-mit the second sample shows off the insetGrouped and rounded corners (`cupertino.CupertinoListSection.2`) . Should we delete the other sample? I think they are intended to show off both configurations.

**Comment by mit-mit** [comment]
About the sample: Yes, I think we should remove the sample that has the square corners. Just the one with rounded corners should be sufficient.

About the API: I like that we support a bit of design flexibility so that apps devs can do square corners if they want, but why isn't the default option (and default constructor) to use rounded like Apple? 

Same with padding; I think our default should match Apples defaults, and then you can manually override padding if you want something else.

**Comment by mit-mit** [comment]
Also: it looks like passing something like `Text('foo')` to the `header` and `footer` arguments results in text styled differently than iOS Settings (despite API docs stating "and style that match the iOS style").

**Comment by Piinks** [comment]
> About the sample: Yes, I think we should remove the sample that has the square corners. Just the one with rounded corners should be sufficient.

Ok.

> About the API: I like that we support a bit of design flexibility so that apps devs can do square corners if they want, but why isn't the default option (and default constructor) to use rounded like Apple?

Both layout options are from Apple design. The square corners came first, and then in later versions of iOS the rounded corners were added as a new option, but both are still supported. See these SwiftUI code snippets to see both layout options in action: https://www.hackingwithswift.com/quick-start/swiftui/how-to-create-grouped-and-inset-grouped-lists

> Same with padding; I think our default should match Apples defaults, and then you can manually override padding if you want something else.

I am not sure we can handle this auto magically. One option I did not mention prior was to wrap it in a SafeArea widget. The ListSection itself does not know where on the screen it is being displayed. If it were positioned at the bottom of the screen for example, but automatically shifted lower to account for the notch at the top of the screen, this would be considered a bug. I think this was a reported bug that we fixed in the past. 

> Also: it looks like passing something like Text('foo') to the header and footer arguments results in text styled differently than iOS Settings (despite API docs stating "and style that match the iOS style").

Thanks for helping to enumerate the work we still have to do here. We have not gotten to this widget yet in the [Cupertino Refresh](https://github.com/orgs/flutter/projects/155) project, but will certainly address this when we do.

**Comment by mit-mit** [comment]
> Both layout options are from Apple design. The square corners came first, and then in later versions of iOS the rounded corners were added as a new option, but both are still supported. 

Sorry, I was being imprecise. I meant, why not use the same default as SwiftUI currently does? If you take the example from the page you link to, and remove the `.listStyle(.insetGrouped)` modifier entirely, then you still get the new inset grouped style.

Maybe in our API that translates to something like giving `CupertinoListSection` a new `listStyle` parameter of type `enum ListStyle { insetGrouped grouped}`, and then setting that parameter to a default value of `ListStyle.insetGrouped` so that you get that style if you don't pass it?

**Comment by Piinks** [comment]
> I meant, why not use the same default as SwiftUI currently does?

I am not sure. These were design decisions made years ago. If I were to guess, it was likely because changing the default would be a breaking change for users.

> Maybe in our API that translates to something like giving CupertinoListSection a new listStyle parameter of type enum ListStyle { insetGrouped grouped}, and then setting that parameter to a default value of ListStyle.insetGrouped so that you get that style if you don't pass it?

Thats a nice idea! Changing the default behavior and removing the `.insetGrouped` constructor would be breaking, so we would need to first evaluate the impact of such a break.

I am removing my assignment for now since it looks like this will need more work than I originally thought. It has been added to the project, and we will see about scheduling the work as we progress through the project. Thanks!

**Comment by mit-mit** [comment]
Sounds good, thanks!

**Comment by bernaferrari** [comment]
My guess is that apple just changed the default and flutter stayed with the old. Apple constantly do breaking changes.

**Comment by MitchellGoodwin** [comment]
Yes, we are generally not as willing to do breaking changes as Apple. Which I think is a good thing, but in cases like this it means we create a gap when it comes to default styling when Apple continues to support its old styling in a way.
