### ISSUE TITLE
Failed assertion in sliver_multi_box_adaptor.dart: 'indexOf(child) > index': is not true

### ISSUE THREAD

**Issue by arensonjr** [flutter/flutter#15923]
https://github.com/flutter/flutter/blob/2171fcb882a63e8ea2408dec4771ce0611621739/packages/flutter/lib/src/rendering/sliver_multi_box_adaptor.dart#L215

I got an exception during the rendering of a list view / list tile that asked to be reported to the framework.

Summarizing the widgets that are involved here (I haven't put in the time to find a minimal repro case, and have no idea which pieces could be relevant based on the stack trace):
```dart
class FooState extends State<Foo> {
  List<ViewOfThingState> _things = [ /* ... */ ];

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: /* ... */
      body: new ListView(
        children: _things.map((t) => new ViewOfThing(t)).toList(),
      ),
      floatingActionButton: /* ... */
    );
}
```
```dart
class ViewOfThing extends StatefulWidget { /* .. */ }
class ViewOfThingState extends State<ViewOfThing {
  String name;
  String subtitle;

  void _join() { /* ... */ }
  
  @override
  Widget build(BuildContext context) {
    return new ListTile(
      leading: new Image.network(/* ... */),
      title: new Text('$name'),
      subtitle: new Text('$subtitle'),
      trailing: new RaisedButton(
        onPressed: _join,
        child: new Text('Join'),
      ),
    );
  }
}
```
One weird thing that's happening here is that *I'm* constructing state, not letting an `initState()` method do it. This is probably not the smartest thing to do, but it didn't cause problems until now.

Full error text:
```
I/flutter (16816): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (16816): The following assertion was thrown during performLayout():
I/flutter (16816): 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 755 pos 14:
I/flutter (16816): '_childElements.containsKey(index)': is not true.
I/flutter (16816):
I/flutter (16816): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (16816): more information in this error message to help you determine and fix the underlying cause.
I/flutter (16816): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (16816):   https://github.com/flutter/flutter/issues/new
I/flutter (16816):
I/flutter (16816): When the exception was thrown, this was the stack:
I/flutter (16816): #2      SliverMultiBoxAdaptorElement.removeChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:755:14)
I/flutter (16816): #3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2205:19)
I/flutter (16816): #4      SliverMultiBoxAdaptorElement.removeChild (package:flutter/src/widgets/sliver.dart:754:11)
I/flutter (16816): #5      RenderSliverMultiBoxAdaptor._destroyOrCacheChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:270:21)
I/flutter (16816): #6      RenderSliverMultiBoxAdaptor.collectGarbage.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:440:9)
I/flutter (16816): #7      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1666:58)
I/flutter (16816): #8      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:740:15)
I/flutter (16816): #9      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1666:13)
I/flutter (16816): #10     RenderSliverMultiBoxAdaptor.collectGarbage (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:434:5)
I/flutter (16816): #11     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:251:5)
I/flutter (16816): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (16816): #13     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter (16816): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (16816): #15     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:285:13)
I/flutter (16816): #16     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1008:12)
I/flutter (16816): #17     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:932:20)
I/flutter (16816): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (16816): #19     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (16816): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (16816): #21     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (16816): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (16816): #23     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (16816): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (16816): #25     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (16816): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (16816): #27     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (16816): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (16816): #29     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (16816): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (16816): #31     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (16816): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (16816): #33     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (16816): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (16816): #35     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:124:11)
I/flutter (16816): #36     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:256:7)
I/flutter (16816): #37     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:194:7)
I/flutter (16816): #38     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:338:14)
I/flutter (16816): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (16816): #40     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (16816): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (16816): #42     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (16816): #43     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1138:24)
I/flutter (16816): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (16816): #45     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (16816): #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (16816): #47     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (16816): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (16816): #49     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (16816): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (16816): #51     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (16816): #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (16816): #53     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (16816): #54     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2710:26)
I/flutter (16816): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (16816): #56     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (16816): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (16816): #58     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:509:15)
I/flutter (16816): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (16816): #60     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (16816): #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (16816): #62     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (16816): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (16816): #64     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (16816): #65     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (16816): #66     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (16816): #67     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (16816): #68     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:107:13)
I/flutter (16816): #69     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (16816): #70     RenderView.performLayout (package:flutter/src/rendering/view.dart:142:13)
I/flutter (16816): #71     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
I/flutter (16816): #72     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
I/flutter (16816): #73     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter (16816): #74     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:622:22)
I/flutter (16816): #75     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (16816): #76     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (16816): #77     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (16816): #78     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (16816): #80     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
I/flutter (16816): #81     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
I/flutter (16816): #82     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
I/flutter (16816): (elided 3 frames from class _AssertionError and package dart:async-patch)
I/flutter (16816):
I/flutter (16816): The following RenderObject was being processed when the exception was fired:
I/flutter (16816):   RenderSliverList#4eba4 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (16816):   creator: SliverList ← MediaQuery ← SliverPadding ← Viewport ← _ScrollableScope ←
I/flutter (16816):   IgnorePointer-[GlobalKey#5a600] ← Semantics ← Listener ← _GestureSemantics ←
I/flutter (16816):   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#98d69] ←
I/flutter (16816):   _ExcludableScrollSemantics-[GlobalKey#5034e] ← RepaintBoundary ← ⋯
I/flutter (16816):   parentData: paintOffset=Offset(0.0, 0.0) (can use size)
I/flutter (16816):   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
I/flutter (16816):   scrollOffset: 18.6, remainingPaintExtent: 603.4, crossAxisExtent: 411.4, crossAxisDirection:
I/flutter (16816):   AxisDirection.right, viewportMainAxisExtent: 603.4)
I/flutter (16816):   geometry: SliverGeometry(scrollExtent: 626.4, paintExtent: 321.1, maxPaintExtent: 626.4,
I/flutter (16816):   hasVisualOverflow: true)
I/flutter (16816):   currently live children: 0 to 5
I/flutter (16816): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (16816):   RenderRepaintBoundary#2877d relayoutBoundary=up3 NEEDS-PAINT
I/flutter (16816):     RenderPositionedBox#f3081 relayoutBoundary=up4 NEEDS-PAINT
I/flutter (16816):       RenderPadding#b39d9 relayoutBoundary=up5 NEEDS-PAINT
I/flutter (16816):         RenderParagraph#3f966 relayoutBoundary=up6 NEEDS-PAINT
I/flutter (16816):   RenderRepaintBoundary#8a85d relayoutBoundary=up3 NEEDS-PAINT
I/flutter (16816):     RenderSemanticsGestureHandler#778e8 relayoutBoundary=up4 NEEDS-PAINT
I/flutter (16816):       RenderPointerListener#c913b relayoutBoundary=up5 NEEDS-PAINT
I/flutter (16816):         RenderSemanticsAnnotations#dac79 relayoutBoundary=up6 NEEDS-PAINT
I/flutter (16816):           RenderConstrainedBox#2733a relayoutBoundary=up7 NEEDS-PAINT
I/flutter (16816):   RenderRepaintBoundary#a9ec5 relayoutBoundary=up3 NEEDS-PAINT
I/flutter (16816):     RenderSemanticsGestureHandler#b8644 relayoutBoundary=up4 NEEDS-PAINT
I/flutter (16816):       RenderPointerListener#31f4f relayoutBoundary=up5 NEEDS-PAINT
I/flutter (16816):         RenderSemanticsAnnotations#c7470 relayoutBoundary=up6 NEEDS-PAINT
I/flutter (16816):           RenderConstrainedBox#bf1f7 relayoutBoundary=up7 NEEDS-PAINT
I/flutter (16816):   RenderRepaintBoundary#ff861 relayoutBoundary=up3 NEEDS-PAINT
I/flutter (16816):     RenderSemanticsGestureHandler#81033 relayoutBoundary=up4 NEEDS-PAINT
I/flutter (16816):       RenderPointerListener#a4fc0 relayoutBoundary=up5 NEEDS-PAINT
I/flutter (16816):         RenderSemanticsAnnotations#2b69e relayoutBoundary=up6 NEEDS-PAINT
I/flutter (16816):           RenderConstrainedBox#f27b6 relayoutBoundary=up7 NEEDS-PAINT
I/flutter (16816):   RenderRepaintBoundary#5909b relayoutBoundary=up3 NEEDS-PAINT
I/flutter (16816):     RenderSemanticsGestureHandler#78780 relayoutBoundary=up4 NEEDS-PAINT
I/flutter (16816):       RenderPointerListener#e4de4 relayoutBoundary=up5 NEEDS-PAINT
I/flutter (16816):         RenderSemanticsAnnotations#a5499 relayoutBoundary=up6 NEEDS-PAINT
I/flutter (16816):           RenderConstrainedBox#c8775 relayoutBoundary=up7 NEEDS-PAINT
I/flutter (16816):   RenderErrorBox#f68b4 NEEDS-PAINT
I/flutter (16816):   ...(descendants list truncated after 25 lines)
I/flutter (16816): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by juanjoserodrigolazaro** [comment]
Any solution?

**Comment by arensonjr** [comment]
My workaround was to refactor so that I no longer manually constructed `State` instances.

**Comment by zoechi** [comment]
@arensonjr 

>  manually constructed State instances.

that part seems to be missing in your example code.

@juanjoserodrigolazaro please try to come up with a runnable minimal reproduction.

**Comment by psine** [comment]
I don't know how minimal it is, but here is an example where I get the same error.  It seems related to an inconsistent value of itemCount in ListView.builder.  This example initializes a list of 5 Items, which in turn, generate a total of 10 child widgets (one ListTile plus one Divider per Item), setting the ListView.builder.itemCount to 10.  Upon deleting one of the Items from _items, itemCount remains 10 (when it should be 8) and the Exception is triggered.  But by explicitly setting itemCount to _items.length * 2 within ListView.builder, the Exception is avoided.

`        /*
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (29119): The following assertion was thrown during performLayout():
I/flutter (29119): 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 556 pos 16:
I/flutter (29119): 'indexOf(child) == index': is not true.
         */
`

flutter doctor:

`
PS C:\dev tools\flutter\bin> ./flutter doctor -v
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 0.9.4 at C:\dev tools\flutter
    • Framework revision f37c235c32 (5 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044
`

`
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\-\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)
    • All Android licenses accepted.
`

`
[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin version 12.1 - the recommended minimum version is 16.0.0
    • Dart plugin version 162.2924
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)
`

`
[√] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\Users\-\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\182.4892.20
    • Flutter plugin version 29.1.3
    • Dart plugin version 182.4892.25
`

`
[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)
`

`
• No issues found!
`

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<Item> _items = <Item>[];
  final _biggerFont = const TextStyle(fontSize: 18.0);

  void _addItem() {
    setState(() {
      _items.add(new Item('Item #${_items.length + 1}'));
    });
  }

  @override
  initState() {
    setState(() {
      _items = List<Item>.generate(5, (int i) {
        return new Item('Item #${i+1}');
      }, growable: true);
    });
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: ListView.builder(
        padding: const EdgeInsets.all(16.0),
        // i is double the number of items added plus one by default...???
        // and deleting items fails to update itemCount.
        // this is invoked 7 times (i=0 thru 6) when _items.length == 3:
        itemBuilder: (context, i) {
          if (i.isOdd) return Divider();
          final index = i ~/ 2;
          if (index >= _items.length) {
            return null;
//            throw new Exception('index $index went off the edge!');
          }
          return _buildRow(_items[index]);
        },
//        itemCount: _items.length * 2, // setting manually to prevent rendering assertion exception
        /*
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (29119): The following assertion was thrown during performLayout():
I/flutter (29119): 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 556 pos 16:
I/flutter (29119): 'indexOf(child) == index': is not true.
         */
        ),
      floatingActionButton: new FloatingActionButton(
        onPressed: _addItem,
        tooltip: 'add item',
        child: new Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  } // build
  Widget _buildRow(Item itm) {
    return ListTile(
      title: Text(
        itm.label,
        style: _biggerFont,
      ),
      trailing: new IconButton(
        icon: Icon(Icons.delete_forever,
          color: Colors.red,
        ),
        tooltip: 'delete item',
        onPressed: () {
          print('deleting: ${_items[_items.indexOf(itm)].label}');
          setState(() {
            _items.removeAt(_items.indexOf(itm));
          });
        }, // null disables the button
      ),
    );
  }
} // _MyHomePageState

class Item {
  String label;
  Item(this.label);
}
````

**Comment by chunhtai** [comment]
@psine There is a bug in the the code, if you are copying from our example, we should change it as well.

After the deletion, `_items` has 4 element. In theory, it should be able to build from index 0~7 and all other index should return null. However, the code actually will build every odd index with a divider. This is causing issue when flutter try to rebuild the frame after setstate. Change the item builder to be this should fix the issue
```
        itemBuilder: (context, i) {
          final index = i ~/ 2;
          if (index >= _items.length) {
            return null;
          }
          if (i.isOdd) return Divider();
          return _buildRow(_items[index]);
        },
```

If you want to know what exactly cause the issue, here is the detail

When flutter first build the frame, it is smart to know when to stop building if there is no item count provided by keeping building children until it sees a null.
so when you have 5 items, it will keep building until it reach index 10 and receive a null.

Things are cool until a setstate is trigger. Flutter will think: ok, I have 10 children in the screen currently, I should try to update every single one of them instead of rebuilding everything from scratch to save some time. updating first 0~7 is fine. When it try to update 8 and 9, 8 returns a null and 9 returns a divider. This cause a confusion and throw the assertion.

I think flutter is behaving correctly, this should not be a code change to framework

**Comment by CoreyCole** [comment]
I'm getting this same error using a `ListView` inside of a `StatelessWidget`. It is reproducable in my app every time when I scroll up and down quickly in the iOS iPhone 5s simulator. My `ListView` contains `StreamBuilders`, but the stream data is not changing when I'm reproducing. I'm simply just scrolling up and down over and over again, quickly.
```
'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 263 pos 16: 'child == null || indexOf(child) > index': is not true
```
`flutter doctor -v`:
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.13.6 17G3025, locale en-US)
    • Flutter version 1.7.8+hotfix.3 at /Users/corey/flutter
    • Framework revision b712a172f9 (10 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/corey/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/corey/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/corey/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.4

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[!] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.36.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • iPhone 5s • 804B8E77-7E94-4053-9AA7-AC13257949D5 • ios • iOS 12.1 (simulator)

! Doctor found issues in 1 category.
```
I'll open a separate issue if I can get it minimally reproducible.

**Comment by jama5262** [comment]
> I'm getting this same error using a `ListView` inside of a `StatelessWidget`. It is reproducable in my app every time when I scroll up and down quickly in the iOS iPhone 5s simulator. My `ListView` contains `StreamBuilders`, but the stream data is not changing when I'm reproducing. I'm simply just scrolling up and down over and over again, quickly.
> 
> ```
> 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 263 pos 16: 'child == null || indexOf(child) > index': is not true
> ```
> 
> `flutter doctor -v`:
> 
> ```
> [✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.13.6 17G3025, locale en-US)
>     • Flutter version 1.7.8+hotfix.3 at /Users/corey/flutter
>     • Framework revision b712a172f9 (10 days ago), 2019-07-09 13:14:38 -0700
>     • Engine revision 54ad777fd2
>     • Dart version 2.4.0
> 
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /Users/corey/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • ANDROID_HOME = /Users/corey/Library/Android/sdk
>     • ANDROID_SDK_ROOT = /Users/corey/Library/Android/sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 10.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 10.1, Build version 10B61
>     • CocoaPods version 1.7.4
> 
> [✓] iOS tools - develop for iOS devices
>     • ios-deploy 1.9.4
> 
> [!] Android Studio (version 3.3)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
> 
> [✓] VS Code (version 1.36.0)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.2.0
> 
> [✓] Connected device (1 available)
>     • iPhone 5s • 804B8E77-7E94-4053-9AA7-AC13257949D5 • ios • iOS 12.1 (simulator)
> 
> ! Doctor found issues in 1 category.
> ```
> 
> I'll open a separate issue if I can get it minimally reproducible.
> 
> EDIT: more specifically, it occurs when I flick and scroll to the bottom of the list and it rubber bands at the bottom. I cannot reproduce on android, but there is no rubber band effect on there. I think it might have to do with this rubber band effect.
> 
> See screen recording: https://www.youtube.com/watch?v=M6ZJV06jc9s

@CoreyCole Did you manage to fix it, I have the same problem

**Comment by sarohabhawna** [comment]
I am facing the same issue, I was fetching the data from firebase and then assigning it to a variable. Now, I have kept it locally but it is still throwing the same error. Here is the [link](https://github.com/flutter/flutter/issues/59307) to the issue that I filed on Github.

**Comment by andreimcristof** [comment]
this happened to me today because I was accessing a property of the widget, in the ctor of a State<Widget>, in order to initialize a field. The error is because the widget is null at that point in time. Instead of the ctor, I initialized my field prop inside the initState() override. 

```
class _FilterState extends State<Filter> {
  List<bool> _selectionsofItems;
   
   // NOT OK
  _FilterState() {
    _selectionsofItems = List.generate(widget.items.length, (index) => false);
  }

   // OK
  @override
  initState() {
    super.initState();
    _selectionsofItems = List.generate(widget.items.length, (index) => false);
  }
}
```
