### ISSUE TITLE
ImageFliter.blur having rendering issues on android, after upgrading flutter from 3.24.5 to 3.27.1

### ISSUE THREAD

**Issue by DineshK-1** [flutter/flutter#160648]
### Steps to reproduce

1. Using Flutter 3.27.1, create a screen with a ListView
2. Add the widget mentioned below and add it to ListView
3. Scroll up and down

```dart
class _TestWidget extends StatelessWidget {
  const _TestWidget();

  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(16),
      child: Stack(
        children: [
          Image.network("https://picsum.photos/400/200"),
          Positioned(
            top: 12,
            left: 12,
            child: ClipRRect(
              borderRadius: BorderRadius.circular(20),
              child: BackdropFilter(
                filter: ImageFilter.blur(sigmaX: 5, sigmaY: 5),
                child: Padding(
                  padding: const EdgeInsets.symmetric(
                    vertical: 4.0,
                    horizontal: 8,
                  ),
                  child: Text(
                    "5 mins read",
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

```

### Expected results

This is using 3.24.5 build, blur seems to be working fine.

https://github.com/user-attachments/assets/ab5e88fb-63af-4dd3-9271-3d481f7a6c80

### Actual results

After upgrading from the flutter version from 3.24.5 to 3.27.1, the blur applied by ImageFilter.blur starts flickering a lot on scroll only on **Android** (Both debug and release mode), iOS seems to be fine.

https://github.com/user-attachments/assets/7f246d88-04dd-4379-8cf3-2fa89c3f7a6f

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(title),
      ),
      body: ListView(
        children: <Widget>[
          const _TestWidget(),
          const SizedBox(height: 12),
          const _TestWidget(),
          const SizedBox(height: 12),
          const _TestWidget(),
          const SizedBox(height: 12),
          const _TestWidget(),
          const SizedBox(height: 12),
          const _TestWidget(),
          const SizedBox(height: 12),
          const _TestWidget(),
        ],
      ),
    );
  }
}

class _TestWidget extends StatelessWidget {
  const _TestWidget();

  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(16),
      child: Stack(
        children: [
          Image.network("https://picsum.photos/400/200"),
          Positioned(
            top: 12,
            left: 12,
            child: ClipRRect(
              borderRadius: BorderRadius.circular(20),
              child: BackdropFilter(
                filter: ImageFilter.blur(sigmaX: 5, sigmaY: 5),
                child: Padding(
                  padding: const EdgeInsets.symmetric(
                    vertical: 4.0,
                    horizontal: 8,
                  ),
                  child: Text(
                    "5 mins read",
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}


```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
~/Documents/flutter_bug/bug_2
flutter doctor -v
[✓] Flutter (Channel stable, 3.27.1, on macOS 15.1.1 24B91 darwin-arm64, locale en-IN)
    • Flutter version 3.27.1 on channel stable at /Users/dinesh/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17025dd882 (4 days ago), 2024-12-17 03:23:09 +0900
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/dinesh/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/dinesh/Library/Android/sdk
    • Java binary at: /Users/dinesh/Applications/Android Studio Ladybug 2024.2.1 Patch 3.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Users/dinesh/Applications/Android Studio Ladybug 2024.2.1 Patch 3.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] IntelliJ IDEA Community Edition (version 2024.3.1.1)
    • IntelliJ at /Users/dinesh/Applications/IntelliJ IDEA Community Edition.app
    • Flutter plugin version 83.0.4
    • Dart plugin version 243.23177

[✓] VS Code (version 1.96.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (5 available)
    • AIN065 (mobile)                 • 9c96539d                  • android-arm64  • Android 15 (API 35)
    • iPhone (mobile)                 • 00008120-001964CE02A2201E • ios            • iOS 18.1.1 22B91
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.1.1 24B91 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.1.1 24B91 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 131.0.6778.205

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@DineshK-1 
Can you provide the device details on which this behavior occurs ?

**Comment by DineshK-1** [comment]
Have problems on Nothing phone 2 - Android 15

iPhone 15 iOS 18 - works as expected

**Comment by darshankawar** [comment]
> Nothing phone 2 - Android 15

https://www.gsmarena.com/nothing_phone_(2)-12386.php This likely uses Adreno 730 GPU.

@DineshK-1 Can you switch to latest master and re-run your scenario to check if it still gives you same behavior or not ?

**Comment by jonahwilliams** [comment]
This was almost certainly fixed by https://github.com/flutter/engine/pull/57212 . Checking out master to confirm would be super helpful to us.

**Comment by DineshK-1** [comment]
Experiencing a new error now, when trying to switch to any channel. Can't switch back to stable too, any known fixes for this? Had no issues yesterday. Not using any VPN, removed flutter bin cache but still can't switch to any branch

```console
flutter channel  master
Downloading package sky_engine...                                  414ms
Downloading package flutter_gpu...                                  16ms
Downloading flutter_patched_sdk tools...                           145ms
Downloading flutter_patched_sdk_product tools...                   950ms
Downloading flutter_patched_sdk_product tools...                   306ms
Failed to download https://storage.googleapis.com/flutter_infra_release/flutter/7df127b1ee7d52c4cb0d42eedd00190e2c4ade3d/flutter_patched_sdk_product.zip. Ensure you have network connectivity and then try again.
Exception: 404
```


```console
flutter channel master --verbose
[   +3 ms] Could not interpret results of "git describe": 3.28.0-2.0.pre.38568
[  +16 ms] executing: sysctl hw.optional.arm64
[   +4 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[  +28 ms] executing: sw_vers -productName
[   +9 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[   +9 ms] Exit code 0 from: sw_vers -productVersion
[        ] 15.1.1
[        ] executing: sw_vers -buildVersion
[  +10 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 24B91
[        ] executing: uname -m
[   +4 ms] Exit code 0 from: uname -m
[        ] arm64
[   +8 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +5 ms] Downloading package sky_engine...
[ +119 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/7df127b1ee7d52c4cb0d42eedd00190e2c4ade3d/sky_engine.zip md5 hash: 2KKLg1jAezDXpTl4OU7iMg==
[ +106 ms] Downloading package sky_engine... (completed in 220ms)
[ +111 ms] executing: unzip -o -q /Users/dinesh/Developer/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/7df127b1ee7d52c4cb0d42eedd00190e2c4ade3d/sky_engine.zip -d
/var/folders/8y/f4bcwj8d7v34v33r375n8nq40000gn/T/flutter_tools.8vfJxu/flutter_sky_engine.zip.HASYxI
[ +165 ms] Exit code 0 from: unzip -o -q /Users/dinesh/Developer/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/7df127b1ee7d52c4cb0d42eedd00190e2c4ade3d/sky_engine.zip -d
/var/folders/8y/f4bcwj8d7v34v33r375n8nq40000gn/T/flutter_tools.8vfJxu/flutter_sky_engine.zip.HASYxI
[   +1 ms] executing: rsync -8 -av --delete /var/folders/8y/f4bcwj8d7v34v33r375n8nq40000gn/T/flutter_tools.8vfJxu/flutter_sky_engine.zip.HASYxI/LICENSE.zip_old_location.md /Users/dinesh/Developer/flutter/bin/cache/pkg
[  +16 ms] Exit code 0 from: rsync -8 -av --delete /var/folders/8y/f4bcwj8d7v34v33r375n8nq40000gn/T/flutter_tools.8vfJxu/flutter_sky_engine.zip.HASYxI/LICENSE.zip_old_location.md /Users/dinesh/Developer/flutter/bin/cache/pkg
[        ] building file list ... done
           LICENSE.zip_old_location.md

           sent 712 bytes  received 42 bytes  1508.00 bytes/sec
           total size is 567  speedup is 0.75
[        ] executing: rsync -8 -av --delete /var/folders/8y/f4bcwj8d7v34v33r375n8nq40000gn/T/flutter_tools.8vfJxu/flutter_sky_engine.zip.HASYxI/sky_engine /Users/dinesh/Developer/flutter/bin/cache/pkg
[ +115 ms] Exit code 0 from: rsync -8 -av --delete /var/folders/8y/f4bcwj8d7v34v33r375n8nq40000gn/T/flutter_tools.8vfJxu/flutter_sky_engine.zip.HASYxI/sky_engine /Users/dinesh/Developer/flutter/bin/cache/pkg
[        ] building file list ... done
           sky_engine/
           sky_engine/AUTHORS
           sky_engine/LICENSE
           sky_engine/README.md
           sky_engine/pubspec.yaml
           sky_engine/lib/
           sky_engine/lib/_embedder.yaml
           sky_engine/lib/_empty.dart
           sky_engine/lib/_http/
           sky_engine/lib/_http/crypto.dart
           sky_engine/lib/_http/http.dart
           sky_engine/lib/_http/http_date.dart
           sky_engine/lib/_http/http_headers.dart
           sky_engine/lib/_http/http_impl.dart
           sky_engine/lib/_http/http_parser.dart
           sky_engine/lib/_http/http_session.dart
           sky_engine/lib/_http/overrides.dart
           sky_engine/lib/_http/websocket.dart
           sky_engine/lib/_http/websocket_impl.dart
           sky_engine/lib/_interceptors/
           sky_engine/lib/_interceptors/interceptors.dart
           sky_engine/lib/_internal/
           sky_engine/lib/_internal/allowed_experiments.json
           sky_engine/lib/_internal/vm/
           sky_engine/lib/_internal/vm/lib/
           sky_engine/lib/_internal/vm/lib/array.dart
           sky_engine/lib/_internal/vm/lib/async_patch.dart
           sky_engine/lib/_internal/vm/lib/class_id_fasta.dart
           sky_engine/lib/_internal/vm/lib/concurrent_patch.dart
           sky_engine/lib/_internal/vm/lib/convert_patch.dart
           sky_engine/lib/_internal/vm/lib/core_patch.dart
           sky_engine/lib/_internal/vm/lib/developer.dart
           sky_engine/lib/_internal/vm/lib/double.dart
           sky_engine/lib/_internal/vm/lib/double_patch.dart
           sky_engine/lib/_internal/vm/lib/empty_source.dart
           sky_engine/lib/_internal/vm/lib/errors_patch.dart
           sky_engine/lib/_internal/vm/lib/expando_patch.dart
           sky_engine/lib/_internal/vm/lib/ffi_allocation_patch.dart
           sky_engine/lib/_internal/vm/lib/ffi_dynamic_library_patch.dart
           sky_engine/lib/_internal/vm/lib/ffi_native_finalizer_patch.dart
           sky_engine/lib/_internal/vm/lib/ffi_native_type_patch.dart
           sky_engine/lib/_internal/vm/lib/ffi_patch.dart
           sky_engine/lib/_internal/vm/lib/ffi_struct_patch.dart
           sky_engine/lib/_internal/vm/lib/finalizer_patch.dart
           sky_engine/lib/_internal/vm/lib/function.dart
           sky_engine/lib/_internal/vm/lib/function_patch.dart
           sky_engine/lib/_internal/vm/lib/growable_array.dart
           sky_engine/lib/_internal/vm/lib/hash_factories.dart
           sky_engine/lib/_internal/vm/lib/identical_patch.dart
           sky_engine/lib/_internal/vm/lib/immutable_map.dart
           sky_engine/lib/_internal/vm/lib/integers.dart
           sky_engine/lib/_internal/vm/lib/internal_patch.dart
           sky_engine/lib/_internal/vm/lib/invocation_mirror_patch.dart
           sky_engine/lib/_internal/vm/lib/isolate_patch.dart
           sky_engine/lib/_internal/vm/lib/lib_prefix.dart
           sky_engine/lib/_internal/vm/lib/math_patch.dart
           sky_engine/lib/_internal/vm/lib/mirror_reference.dart
           sky_engine/lib/_internal/vm/lib/mirrors_impl.dart
           sky_engine/lib/_internal/vm/lib/mirrors_patch.dart
           sky_engine/lib/_internal/vm/lib/object_patch.dart
           sky_engine/lib/_internal/vm/lib/print_patch.dart
           sky_engine/lib/_internal/vm/lib/profiler.dart
           sky_engine/lib/_internal/vm/lib/record_patch.dart
           sky_engine/lib/_internal/vm/lib/regexp_patch.dart
           sky_engine/lib/_internal/vm/lib/schedule_microtask_patch.dart
           sky_engine/lib/_internal/vm/lib/stacktrace.dart
           sky_engine/lib/_internal/vm/lib/stopwatch_patch.dart
           sky_engine/lib/_internal/vm/lib/string_patch.dart
           sky_engine/lib/_internal/vm/lib/symbol_patch.dart
           sky_engine/lib/_internal/vm/lib/timeline.dart
           sky_engine/lib/_internal/vm/lib/timer_impl.dart
           sky_engine/lib/_internal/vm/lib/timer_patch.dart
           sky_engine/lib/_internal/vm/lib/type_patch.dart
           sky_engine/lib/_internal/vm/lib/typed_data_patch.dart
           sky_engine/lib/_internal/vm/lib/uri_patch.dart
           sky_engine/lib/_internal/vm/lib/weak_property.dart
           sky_engine/lib/_internal/vm_shared/
           sky_engine/lib/_internal/vm_shared/lib/
           sky_engine/lib/_internal/vm_shared/lib/bigint_patch.dart
           sky_engine/lib/_internal/vm_shared/lib/bool_patch.dart
           sky_engine/lib/_internal/vm_shared/lib/collection_patch.dart
           sky_engine/lib/_internal/vm_shared/lib/compact_hash.dart
           sky_engine/lib/_internal/vm_shared/lib/date_patch.dart
           sky_engine/lib/_internal/vm_shared/lib/integers_patch.dart
           sky_engine/lib/_internal/vm_shared/lib/map_patch.dart
           sky_engine/lib/_internal/vm_shared/lib/null_patch.dart
           sky_engine/lib/_internal/vm_shared/lib/string_buffer_patch.dart
           sky_engine/lib/_js_annotations/
           sky_engine/lib/_js_annotations/_js_annotations.dart
           sky_engine/lib/_js_types/
           sky_engine/lib/_js_types/js_types.dart
           sky_engine/lib/async/
           sky_engine/lib/async/async.dart
           sky_engine/lib/async/async_error.dart
           sky_engine/lib/async/broadcast_stream_controller.dart
           sky_engine/lib/async/deferred_load.dart
           sky_engine/lib/async/future.dart
           sky_engine/lib/async/future_extensions.dart
           sky_engine/lib/async/future_impl.dart
           sky_engine/lib/async/schedule_microtask.dart
           sky_engine/lib/async/stream.dart
           sky_engine/lib/async/stream_controller.dart
           sky_engine/lib/async/stream_impl.dart
           sky_engine/lib/async/stream_pipe.dart
           sky_engine/lib/async/stream_transformers.dart
           sky_engine/lib/async/timer.dart
           sky_engine/lib/async/zone.dart
           sky_engine/lib/collection/
           sky_engine/lib/collection/collection.dart
           sky_engine/lib/collection/collections.dart
           sky_engine/lib/collection/hash_map.dart
           sky_engine/lib/collection/hash_set.dart
           sky_engine/lib/collection/iterable.dart
           sky_engine/lib/collection/iterator.dart
           sky_engine/lib/collection/linked_hash_map.dart
           sky_engine/lib/collection/linked_hash_set.dart
           sky_engine/lib/collection/linked_list.dart
           sky_engine/lib/collection/list.dart
           sky_engine/lib/collection/maps.dart
           sky_engine/lib/collection/queue.dart
           sky_engine/lib/collection/set.dart
           sky_engine/lib/collection/splay_tree.dart
           sky_engine/lib/concurrent/
           sky_engine/lib/concurrent/concurrent.dart
           sky_engine/lib/convert/
           sky_engine/lib/convert/ascii.dart
           sky_engine/lib/convert/base64.dart
           sky_engine/lib/convert/byte_conversion.dart
           sky_engine/lib/convert/chunked_conversion.dart
           sky_engine/lib/convert/codec.dart
           sky_engine/lib/convert/convert.dart
           sky_engine/lib/convert/converter.dart
           sky_engine/lib/convert/encoding.dart
           sky_engine/lib/convert/html_escape.dart
           sky_engine/lib/convert/json.dart
           sky_engine/lib/convert/latin1.dart
           sky_engine/lib/convert/line_splitter.dart
           sky_engine/lib/convert/string_conversion.dart
           sky_engine/lib/convert/utf.dart
           sky_engine/lib/core/
           sky_engine/lib/core/annotations.dart
           sky_engine/lib/core/bigint.dart
           sky_engine/lib/core/bool.dart
           sky_engine/lib/core/comparable.dart
           sky_engine/lib/core/core.dart
           sky_engine/lib/core/date_time.dart
           sky_engine/lib/core/double.dart
           sky_engine/lib/core/duration.dart
           sky_engine/lib/core/enum.dart
           sky_engine/lib/core/errors.dart
           sky_engine/lib/core/exceptions.dart
           sky_engine/lib/core/function.dart
           sky_engine/lib/core/identical.dart
           sky_engine/lib/core/int.dart
           sky_engine/lib/core/invocation.dart
           sky_engine/lib/core/iterable.dart
           sky_engine/lib/core/iterator.dart
           sky_engine/lib/core/list.dart
           sky_engine/lib/core/map.dart
           sky_engine/lib/core/null.dart
           sky_engine/lib/core/num.dart
           sky_engine/lib/core/object.dart
           sky_engine/lib/core/pattern.dart
           sky_engine/lib/core/print.dart
           sky_engine/lib/core/record.dart
           sky_engine/lib/core/regexp.dart
           sky_engine/lib/core/set.dart
           sky_engine/lib/core/sink.dart
           sky_engine/lib/core/stacktrace.dart
           sky_engine/lib/core/stopwatch.dart
           sky_engine/lib/core/string.dart
           sky_engine/lib/core/string_buffer.dart
           sky_engine/lib/core/string_sink.dart
           sky_engine/lib/core/symbol.dart
           sky_engine/lib/core/type.dart
           sky_engine/lib/core/uri.dart
           sky_engine/lib/core/weak.dart
           sky_engine/lib/developer/
           sky_engine/lib/developer/developer.dart
           sky_engine/lib/developer/extension.dart
           sky_engine/lib/developer/profiler.dart
           sky_engine/lib/developer/service.dart
           sky_engine/lib/developer/timeline.dart
           sky_engine/lib/ffi/
           sky_engine/lib/ffi/abi.dart
           sky_engine/lib/ffi/abi_specific.dart
           sky_engine/lib/ffi/allocation.dart
           sky_engine/lib/ffi/annotations.dart
           sky_engine/lib/ffi/c_type.dart
           sky_engine/lib/ffi/dynamic_library.dart
           sky_engine/lib/ffi/ffi.dart
           sky_engine/lib/ffi/native_finalizer.dart
           sky_engine/lib/ffi/native_type.dart
           sky_engine/lib/ffi/struct.dart
           sky_engine/lib/ffi/union.dart
           sky_engine/lib/html/
           sky_engine/lib/html/html_dart2js.dart
           sky_engine/lib/internal/
           sky_engine/lib/internal/async_cast.dart
           sky_engine/lib/internal/bytes_builder.dart
           sky_engine/lib/internal/cast.dart
           sky_engine/lib/internal/errors.dart
           sky_engine/lib/internal/internal.dart
           sky_engine/lib/internal/iterable.dart
           sky_engine/lib/internal/linked_list.dart
           sky_engine/lib/internal/list.dart
           sky_engine/lib/internal/lowering.dart
           sky_engine/lib/internal/print.dart
           sky_engine/lib/internal/sort.dart
           sky_engine/lib/internal/symbol.dart
           sky_engine/lib/io/
           sky_engine/lib/io/common.dart
           sky_engine/lib/io/data_transformer.dart
           sky_engine/lib/io/directory.dart
           sky_engine/lib/io/directory_impl.dart
           sky_engine/lib/io/embedder_config.dart
           sky_engine/lib/io/eventhandler.dart
           sky_engine/lib/io/file.dart
           sky_engine/lib/io/file_impl.dart
           sky_engine/lib/io/file_system_entity.dart
           sky_engine/lib/io/io.dart
           sky_engine/lib/io/io_resource_info.dart
           sky_engine/lib/io/io_service.dart
           sky_engine/lib/io/io_sink.dart
           sky_engine/lib/io/link.dart
           sky_engine/lib/io/namespace_impl.dart
           sky_engine/lib/io/network_profiling.dart
           sky_engine/lib/io/overrides.dart
           sky_engine/lib/io/platform.dart
           sky_engine/lib/io/platform_impl.dart
           sky_engine/lib/io/process.dart
           sky_engine/lib/io/secure_server_socket.dart
           sky_engine/lib/io/secure_socket.dart
           sky_engine/lib/io/security_context.dart
           sky_engine/lib/io/service_object.dart
           sky_engine/lib/io/socket.dart
           sky_engine/lib/io/stdio.dart
           sky_engine/lib/io/string_transformer.dart
           sky_engine/lib/io/sync_socket.dart
           sky_engine/lib/isolate/
           sky_engine/lib/isolate/capability.dart
           sky_engine/lib/isolate/isolate.dart
           sky_engine/lib/js/
           sky_engine/lib/js/js.dart
           sky_engine/lib/js/js_wasm.dart
           sky_engine/lib/js_interop/
           sky_engine/lib/js_interop/js_interop.dart
           sky_engine/lib/js_interop_unsafe/
           sky_engine/lib/js_interop_unsafe/js_interop_unsafe.dart
           sky_engine/lib/js_util/
           sky_engine/lib/js_util/js_util.dart
           sky_engine/lib/math/
           sky_engine/lib/math/math.dart
           sky_engine/lib/math/point.dart
           sky_engine/lib/math/random.dart
           sky_engine/lib/math/rectangle.dart
           sky_engine/lib/typed_data/
           sky_engine/lib/typed_data/typed_data.dart
           sky_engine/lib/ui/
           sky_engine/lib/ui/annotations.dart
           sky_engine/lib/ui/channel_buffers.dart
           sky_engine/lib/ui/compositing.dart
           sky_engine/lib/ui/geometry.dart
           sky_engine/lib/ui/hooks.dart
           sky_engine/lib/ui/isolate_name_server.dart
           sky_engine/lib/ui/key.dart
           sky_engine/lib/ui/lerp.dart
           sky_engine/lib/ui/math.dart
           sky_engine/lib/ui/natives.dart
           sky_engine/lib/ui/painting.dart
           sky_engine/lib/ui/platform_dispatcher.dart
           sky_engine/lib/ui/platform_isolate.dart
           sky_engine/lib/ui/plugins.dart
           sky_engine/lib/ui/pointer.dart
           sky_engine/lib/ui/semantics.dart
           sky_engine/lib/ui/text.dart
           sky_engine/lib/ui/ui.dart
           sky_engine/lib/ui/window.dart
           sky_engine/lib/ui_web/
           sky_engine/lib/ui_web/ui_web.dart
           sky_engine/lib/ui_web/ui_web/
           sky_engine/lib/ui_web/ui_web/asset_manager.dart
           sky_engine/lib/ui_web/ui_web/benchmarks.dart
           sky_engine/lib/ui_web/ui_web/browser_detection.dart
           sky_engine/lib/ui_web/ui_web/flutter_views_proxy.dart
           sky_engine/lib/ui_web/ui_web/images.dart
           sky_engine/lib/ui_web/ui_web/initialization.dart
           sky_engine/lib/ui_web/ui_web/platform_view_registry.dart
           sky_engine/lib/ui_web/ui_web/plugins.dart
           sky_engine/lib/ui_web/ui_web/testing.dart
           sky_engine/lib/ui_web/ui_web/navigation/
           sky_engine/lib/ui_web/ui_web/navigation/platform_location.dart
           sky_engine/lib/ui_web/ui_web/navigation/url_strategy.dart
           sky_engine/sdk_ext/
           sky_engine/sdk_ext/vmservice_io.dart
           sky_engine/sdk_ext/vmservice_server.dart

           sent 7604981 bytes  received 6004 bytes  15221970.00 bytes/sec
           total size is 7585440  speedup is 1.00
[  +29 ms] Downloading package flutter_gpu...
[  +17 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/7df127b1ee7d52c4cb0d42eedd00190e2c4ade3d/flutter_gpu.zip md5 hash: TcF01kaTdb/4jZY46ba9qg==
[   +2 ms] Downloading package flutter_gpu... (completed in 19ms)
[   +2 ms] executing: unzip -o -q /Users/dinesh/Developer/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/7df127b1ee7d52c4cb0d42eedd00190e2c4ade3d/flutter_gpu.zip -d
/var/folders/8y/f4bcwj8d7v34v33r375n8nq40000gn/T/flutter_tools.8vfJxu/flutter_flutter_gpu.zip.v6ttja
[  +14 ms] Exit code 0 from: unzip -o -q /Users/dinesh/Developer/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/7df127b1ee7d52c4cb0d42eedd00190e2c4ade3d/flutter_gpu.zip -d
/var/folders/8y/f4bcwj8d7v34v33r375n8nq40000gn/T/flutter_tools.8vfJxu/flutter_flutter_gpu.zip.v6ttja
[        ] executing: rsync -8 -av --delete /var/folders/8y/f4bcwj8d7v34v33r375n8nq40000gn/T/flutter_tools.8vfJxu/flutter_flutter_gpu.zip.v6ttja/LICENSE.zip_old_location.md /Users/dinesh/Developer/flutter/bin/cache/pkg
[  +14 ms] Exit code 0 from: rsync -8 -av --delete /var/folders/8y/f4bcwj8d7v34v33r375n8nq40000gn/T/flutter_tools.8vfJxu/flutter_flutter_gpu.zip.v6ttja/LICENSE.zip_old_location.md /Users/dinesh/Developer/flutter/bin/cache/pkg
[        ] building file list ... done
           LICENSE.zip_old_location.md

           sent 720 bytes  received 42 bytes  1524.00 bytes/sec
           total size is 575  speedup is 0.75
[        ] executing: rsync -8 -av --delete /var/folders/8y/f4bcwj8d7v34v33r375n8nq40000gn/T/flutter_tools.8vfJxu/flutter_flutter_gpu.zip.v6ttja/flutter_gpu /Users/dinesh/Developer/flutter/bin/cache/pkg
[  +27 ms] Exit code 0 from: rsync -8 -av --delete /var/folders/8y/f4bcwj8d7v34v33r375n8nq40000gn/T/flutter_tools.8vfJxu/flutter_flutter_gpu.zip.v6ttja/flutter_gpu /Users/dinesh/Developer/flutter/bin/cache/pkg
[        ] building file list ... done
           flutter_gpu/
           flutter_gpu/BUILD.gn
           flutter_gpu/analysis_options.yaml
           flutter_gpu/command_buffer.cc
           flutter_gpu/command_buffer.h
           flutter_gpu/context.cc
           flutter_gpu/context.h
           flutter_gpu/device_buffer.cc
           flutter_gpu/device_buffer.h
           flutter_gpu/export.cc
           flutter_gpu/export.h
           flutter_gpu/formats.cc
           flutter_gpu/formats.h
           flutter_gpu/pubspec.yaml
           flutter_gpu/render_pass.cc
           flutter_gpu/render_pass.h
           flutter_gpu/render_pipeline.cc
           flutter_gpu/render_pipeline.h
           flutter_gpu/shader.cc
           flutter_gpu/shader.h
           flutter_gpu/shader_library.cc
           flutter_gpu/shader_library.h
           flutter_gpu/texture.cc
           flutter_gpu/texture.h
           flutter_gpu/dist/
           flutter_gpu/dist/BUILD.gn
           flutter_gpu/lib/
           flutter_gpu/lib/gpu.dart
           flutter_gpu/lib/src/
           flutter_gpu/lib/src/buffer.dart
           flutter_gpu/lib/src/command_buffer.dart
           flutter_gpu/lib/src/context.dart
           flutter_gpu/lib/src/formats.dart
           flutter_gpu/lib/src/render_pass.dart
           flutter_gpu/lib/src/render_pipeline.dart
           flutter_gpu/lib/src/shader.dart
           flutter_gpu/lib/src/shader_library.dart
           flutter_gpu/lib/src/texture.dart

           sent 159637 bytes  received 792 bytes  320858.00 bytes/sec
           total size is 157213  speedup is 0.98
[   +5 ms] Downloading flutter_patched_sdk tools...
[  +15 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/7df127b1ee7d52c4cb0d42eedd00190e2c4ade3d/flutter_patched_sdk.zip md5 hash: fSKjmIaHueOCvDXY8tnaWg==
[ +124 ms] Downloading flutter_patched_sdk tools... (completed in 139ms)
[   +1 ms] executing: unzip -o -q /Users/dinesh/Developer/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/7df127b1ee7d52c4cb0d42eedd00190e2c4ade3d/flutter_patched_sdk.zip -d
/var/folders/8y/f4bcwj8d7v34v33r375n8nq40000gn/T/flutter_tools.8vfJxu/flutter_flutter_patched_sdk.zip.4Orw09
[  +75 ms] Exit code 0 from: unzip -o -q /Users/dinesh/Developer/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/7df127b1ee7d52c4cb0d42eedd00190e2c4ade3d/flutter_patched_sdk.zip -d
/var/folders/8y/f4bcwj8d7v34v33r375n8nq40000gn/T/flutter_tools.8vfJxu/flutter_flutter_patched_sdk.zip.4Orw09
[        ] executing: rsync -8 -av --delete /var/folders/8y/f4bcwj8d7v34v33r375n8nq40000gn/T/flutter_tools.8vfJxu/flutter_flutter_patched_sdk.zip.4Orw09/flutter_patched_sdk
/Users/dinesh/Developer/flutter/bin/cache/artifacts/engine/common
[  +43 ms] Exit code 0 from: rsync -8 -av --delete /var/folders/8y/f4bcwj8d7v34v33r375n8nq40000gn/T/flutter_tools.8vfJxu/flutter_flutter_patched_sdk.zip.4Orw09/flutter_patched_sdk
/Users/dinesh/Developer/flutter/bin/cache/artifacts/engine/common
[        ] building file list ... done
           flutter_patched_sdk/
           flutter_patched_sdk/platform_strong.dill
           flutter_patched_sdk/vm_outline_strong.dill

           sent 11267182 bytes  received 70 bytes  22534504.00 bytes/sec
           total size is 11265560  speedup is 1.00
[        ] executing: rsync -8 -av --delete /var/folders/8y/f4bcwj8d7v34v33r375n8nq40000gn/T/flutter_tools.8vfJxu/flutter_flutter_patched_sdk.zip.4Orw09/LICENSE.flutter_patched_sdk.md
/Users/dinesh/Developer/flutter/bin/cache/artifacts/engine/common
[  +12 ms] Exit code 0 from: rsync -8 -av --delete /var/folders/8y/f4bcwj8d7v34v33r375n8nq40000gn/T/flutter_tools.8vfJxu/flutter_flutter_patched_sdk.zip.4Orw09/LICENSE.flutter_patched_sdk.md
/Users/dinesh/Developer/flutter/bin/cache/artifacts/engine/common
[        ] building file list ... done

           sent 102 bytes  received 20 bytes  244.00 bytes/sec
           total size is 582  speedup is 4.77
[   +6 ms] Downloading flutter_patched_sdk_product tools...
[ +296 ms] Exception: 404
[        ] Downloading flutter_patched_sdk_product tools... (completed in 296ms)
[        ] Downloading flutter_patched_sdk_product tools...
[ +317 ms] Exception: 404
[   +2 ms] Downloading flutter_patched_sdk_product tools... (completed in 319ms)
[        ] "flutter channel" took 1,703ms.
[  +18 ms] Failed to download https://storage.googleapis.com/flutter_infra_release/flutter/7df127b1ee7d52c4cb0d42eedd00190e2c4ade3d/flutter_patched_sdk_product.zip. Ensure you have network connectivity and then try again.
           Exception: 404
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:34:3)
           #1      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:1152:11)
           <asynchronous suspension>
           #2      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:992:7)
           <asynchronous suspension>
           #3      CachedArtifact.update (package:flutter_tools/src/cache.dart:894:5)
           <asynchronous suspension>
           #4      Cache.updateAll (package:flutter_tools/src/cache.dart:765:9)
           <asynchronous suspension>
           #5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1862:7)
           <asynchronous suspension>
           #6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1558:27)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
           <asynchronous suspension>
           #8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:496:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
           <asynchronous suspension>
           #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:431:5)
           <asynchronous suspension>
           #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:98:11)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
           <asynchronous suspension>
           #14     main (package:flutter_tools/executable.dart:99:3)
           <asynchronous suspension>
           
           
[   +1 ms] Running 2 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by josefrasetia** [comment]
The same thing also happens with phone samsung A52s. ImageFilter.blur having rendering issue.
how to fix it?

**Comment by josefrasetia** [comment]
UPDATE - i try use latest master and re-run my app, its running well

**Comment by darshankawar** [comment]
@DineshK-1 Try again if you haven't.

**Comment by DineshK-1** [comment]
Yes, seems to work fine on master branch.

**Comment by darshankawar** [comment]
Closing based on above comment as this seems to be working fine on master.

**Comment by josefrasetia** [comment]
I tried using the master branch, but it still doesn't work well. whereas in version 3.24.5 it works very well

the result is like this

https://github.com/user-attachments/assets/9410c65a-1151-42da-aa22-e7f6cf37398c

ini versi yang saya gunakan 
![Screenshot 2025-01-06 171730](https://github.com/user-attachments/assets/625d94db-126d-427b-afc6-6a0417fbe27f)

**Comment by klleon-mobile-jihunbang** [comment]
The same problem occurs in version 3.7.2.

**Comment by josefrasetia** [comment]
problem not fixed in version 3.27.3 an master channel version 3.29.0-1.0.pre.95

**Comment by jihun-bang** [comment]
As a workaround, you can set `android/gradle.properties` as below.

```
org.gradle.jvmargs=-Xmx4G
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by josefrasetia** [comment]
> As a workaround, you can set `android/gradle.properties` as below.
> 
> ```
> org.gradle.jvmargs=-Xmx4G
> android.useAndroidX=true
> android.enableJetifier=true
> ```
i tried with this configuration, but nothing happens. imagefilter still displays as in my video above when scrolling
