### ISSUE TITLE
Cloud firestore 0.4.0 not working for beta channel ?

### ISSUE THREAD

**Issue by iampawan** [flutter/flutter#16188]
Package cloud_firestore has no versions that match >=0.4.0 <0.5.0 derived from:

flutfire depends on version ^0.4.0
pub get failed (1)
exit code 1

It is not compatible with beta channel and in master channel it works but that has other issues.

**Comment by arduino-master** [comment]
Can you please add more information?

**Comment by iampawan** [comment]
Package cloud_firestore has no versions that match >=0.4.0 <0.5.0 derived from:
- flutfire depends on version ^0.4.0
pub get failed (1)
exit code 1

**Comment by iampawan** [comment]
I am using flutter beta channel 0.2.3

**Comment by arduino-master** [comment]
Mine worked with version 0.3.2.

**Comment by arduino-master** [comment]
Although I still had other errors with xcode and gradle builds

**Comment by iampawan** [comment]
version 0.3.2 has other errors .. But the problem with this version is this: 

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.2.4 <2.0.0"

In their library supported flutter version is >=0.2.4

**Comment by iampawan** [comment]
@arduino-master which flutter channel you are using?

**Comment by iampawan** [comment]
@collinjackson Can you help?

**Comment by zoechi** [comment]
Your pubspec.yaml probably contains a dependency that is not compatible with `cloud_firestore` or a dependency has a version constraint that is not compatible with `cloud_firestore`.
Please provide more information.
- the output of `flutter doctor -v`
- the content of your `pubspec.yaml`

**Comment by iampawan** [comment]
My pubspec.yaml

  cupertino_icons: ^0.1.0
  firebase_auth:
  google_sign_in:
  cloud_firestore: ^0.4.0

**Comment by zoechi** [comment]
@iampawan this means the issue is fixed already anyway, because `dev` is updated more frequently than `beta`. 
You might need to use an older `cloud_firestore` version if you insist in staying on `beta`.

**Comment by arduino-master** [comment]
Version 0.4.0 is not working for me and I am not using beta. Versions 0.3.* do not work either. They throw an error about message codecs and positional arguments. 0.2.* does not work for me on iOS as possible is messing up but I haven't tried with android yet.

**Comment by collinjackson** [comment]
To get the functionality required for cloud_firestore 4.0, you can switch to the dev channel. You can switch back to beta after the next beta release.

**Comment by iampawan** [comment]
@collinjackson yeah that's what i did to fix this as of now.

**Comment by arduino-master** [comment]
I'm using the device channel and 0.4.0 is still not working for me. I'm getting exactly the same error on the dev channel

**Comment by zoechi** [comment]
@arduino-master please post the output of `flutter doctor -v`

**Comment by arduino-master** [comment]
Sorry, it turns out that somehow I was accidentally on the beta channel without realising it. I updated to the dev channel and it started working.

**Comment by collinjackson** [comment]
This should be working as of the latest beta release. Please reopen if it isn't.

**Comment by kroikie** [comment]
@iampawan

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/868. Any further collaboration will be done there.
