### ISSUE TITLE
RTL rendering issue - Strings ending with spaces

### ISSUE THREAD

**Issue by Rmaan** [flutter/flutter#16333]
When rendering in RTL, in some cases, the beginning of the string get clipped. I found that you can reproduce easily by adding spaces at the end of string. It happens with both LTR and RTL languages and in `Text` or `TextField` widgets.

## Steps to Reproduce

1- Set rendering to RTL.
2- Render `new Text("some text    ")`
(Seems Github's markup will collapse adjacent spaces even in code blocks. So put more than one at the end of string.)
3- See "some" will get clipped.

I tested on Flutter beta (Channel beta, v0.2.3, on Microsoft Windows [Version 6.1.7601], locale en-US) and Flutter gallery app (latest version from Google Play). Here is a demo:

![ezgif-2-3826dbf707](https://user-images.githubusercontent.com/1183449/38452745-b6987ca6-3a5f-11e8-8406-01b3026e0fdd.gif)

**Comment by xclud** [comment]
The one in Google Play is out of date and does not showcase lots of recent features.

There have been many bugs in RTL text rendering which was solved in _head_ branch recently. I am not aware if the fixes are in other branches as well. Switching to head branch will fix the problem.

I am using Flutter with Persian text without any issues.

**Comment by Rmaan** [comment]
@xclud What do you mean exactly by "head branch"? There is no branch named head. I checked both master and dev channel. They both have the issue as well. Which version do you use? Did you tried to reproduce aforementioned problem?

[✓] Flutter (Channel master, v0.2.5-pre.8, on Mac OS X 10.13 17A365, locale en-US)
[✓] Flutter (Channel dev, v0.2.9, on Mac OS X 10.13 17A365, locale en-US)

**Comment by QbicFox** [comment]
I'm using beta channel and confirm this issue.

**Comment by xclud** [comment]
@Rmaan this problem exists with v0.2.5-pre.8. If i recall correctly the issue is fixed in 14th release with a huge **libtxt** update.

Currently i am running on _v0.2.10-pre.38_ without any issues on Persian text. You are 30 releases behind.

If you are on master branch run `git pull` and `flutter doctor` commands, or try re-cloning the master branch.

One more thing: make sure you are referencing the correct flutter directory. I had master and dev branches in two separate directories and i switched from dev to master in my settings. But it was still using flutter from the old directory. Finally i ended up with replacing the directory and reverting back my settings.

Good Luck.

**Comment by Rmaan** [comment]
@xclud Thank you for your time! I tried to get the last version in master:
```
$ flutter channel master
...
$ flutter upgrade
...
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v0.2.10-pre.39, on Microsoft Windows [Version 6.1.7601], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.0)
[√] Connected devices (1 available)
$ flutter clean
$ flutter run
```
But I still have the issue.

Here is a sample app and render:
```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new Scaffold(
        appBar: new AppBar(title: new Text("Sample Title")),
        body: new Directionality(
          textDirection: TextDirection.rtl,
          child: new Column(
            children: <Widget>[
              new Container(child: new Text("a "), width: double.infinity),
              new TextField(),
            ],
          ),
        ),
      ),
    );
  }
}
```

![screenshot_1523270153](https://user-images.githubusercontent.com/1183449/38493605-03a195e2-3c08-11e8-8a99-43c8325234f6.png)

See how "a" and text in `TextField` got cut off.

**Comment by Rmaan** [comment]
I found another variant on this bug that happens when texts wrap (for a string that doesn't end with spaces itself but when wrapped some of its lines will end with space). Unlike one line situation I can't reproduce this variant using English letters. Here is a sample program and render (on Nexus 5X Android emulator).

```dart
class BugApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    const sampleText = "این باگ توی متن‌های چند خطه هم پیش میاد!";
//    const sampleText = "It seems this bug happens with multiline texts without additional spaces too!";
    return new MaterialApp(
      home: new Scaffold(
        appBar: new AppBar(title: new Text("Sample Title")),
        body: new Directionality(
          textDirection: TextDirection.rtl,
          child: new Column(
            children: <Widget>[
              new Container(
                child: new Column(
                  children: <Widget>[
                    new Text(sampleText, style: new TextStyle(fontSize: 50.0)),
                    new Divider(),
                    new Text(sampleText.replaceAll(' ', '  '), style: new TextStyle(fontSize: 50.0)),
                  ],
                ),
                width: double.infinity,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

![screenshot_1524389210](https://user-images.githubusercontent.com/1183449/39093521-0dc65d40-4636-11e8-8b53-48dbf5ea9fda.png)

Notice first and second line of text has gone far right and clipped. I added more spaces in second paragraph to clip more letters. 

This bugs happen even if you render in LTR mode (with Persian characters) here is the render (problem is in first line of second paragraph):

![screenshot_1524389722](https://user-images.githubusercontent.com/1183449/39093532-35b3c752-4636-11e8-98e0-3b52667546dd.png)

**Comment by Rmaan** [comment]
@Hixie Sorry for the mention. We want to release an app with Flutter and this bug is kind of release blocker for us. Could someone on the team at least acknowledge this bug? Or help me to contribute a fix?

**Comment by Hixie** [comment]
cc @jason-simmons

**Comment by jason-simmons** [comment]
Sorry about the regression - this should be fixed in the next engine by https://github.com/flutter/engine/commit/f6359e4111d37652409e2392fdb3cb72f1119c2a

**Comment by tvolkert** [comment]
Re-opening because the fix is being reverted due to the introduction of a different bug (https://github.com/flutter/flutter/issues/17502).
