### ISSUE TITLE
When using PlatformView to create TextureView or SurfaceView on Android, the content on the surface disappears when returning from the background to the foreground

### ISSUE THREAD

**Issue by Kongdy** [flutter/flutter#163520]
### Steps to reproduce

1. Run sample project on Android
2. Render content on TextureView or SurfaceView in PlatformView
3. Background app
4. Foreground app

### Expected results

The display remains on the PlatformView.

### Actual results

As shown in the video, the display disappears when returning from the background, but reappears when continuing video playback or performing a hot reload in the code

https://github.com/user-attachments/assets/fbd5199d-2e05-4a27-a949-9be86b32d534

### Code sample

https://github.com/Kongdy/miss_img_demo

https://github.com/LiteAVSDK/Player_Flutter

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Tested Flutter versions
3.29.0 ❌ Issue occurs
3.27.4 ❌ Issue occurs
3.27.3 ❌ Issue occurs
3.27.2 ❌ Issue occurs
3.24.5 ❌ Issue occurs
3.22.3 ❌ Issue occurs
3.19.0  ✓ As expected

### Tested Devices
Oppo reno 7 on  Android 13
Xiaomi MIX4 on Android 14

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
~/StudioProject/SuperPlayer/Flutter/example git:[main]
flutter doctor -v
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.6.1 23G93 darwin-arm64, locale zh-Hans-AL)
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (7 months ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.92.1)

[✓] Connected device (4 available)
[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@Kongdy Thanks for the report. I looked at the repo you shared and it seems to be a full fledged app. In order to properly address the issue, we would need only minimal but complete reproducible code sample without third party package implementation that still shows the reported behavior.

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by timbotimbo** [comment]
Maybe unrelated, but I checked this issue because I thinks it's curious that I had a pretty similar issue around the same Flutter versions.

In my older issue (https://github.com/flutter/flutter/issues/144219)
- Android SurfaceView inside a PlatformView
- Blank on app resume from background
- It broke in Flutter master versions higher than 3.19.x. 

The difference is that my issue was fixed and included in a 3.22.x release.
This was part of a larger app resume saga that even got a [postmortem](https://github.com/flutter/flutter/blob/master/docs/postmortems/Postmortem-Platform-View-android-14-regression.md) in the Flutter repo, so I hope your issue is unrelated to that.

### example tests
To also contribute something, I tried [your example]( https://github.com/Kongdy/miss_img_demo) using:
    - Flutter 3.16.9 stable  (required some gradle file downgrades)  
    - Flutter 3.19.0 stable  (required some gradle file downgrades)  
    - Flutter 3.24.5 stable  
    - Flutter version 3.30.0-1.0.pre.214 on channel master  

And I get the same buggy behaviour on all of them.  
I'm not sure if this was broken in Flutter long ago, or if this example is buggy itself.

- Samsung S8 Android 9.
  - Flutter logo shows on boot.
  - It disappears on app resume.
   - Once invisible, it shows up again on screen rotation to landscape.
   - The image is stretched after screen is rotated.

- Samsung S20FE Android 13 & Samsung S25U Android 15
   - Flutter logo often doesn't even show up on boot.
   - Screen rotation to landscape makes it show up.
   - Once it shows, it will disappear on background -> resume.
   - The image is stretched after screen is rotated.



Based on earlier platform view issues, I think the screen rotation triggers a resize of the platform view, which forces it to draw again.  
Enabling or disabling impeller does not make a difference.

**Comment by timbotimbo** [comment]
> Flutter version 3.30.0-1.0.pre.214 on channel master

I mentioned master (as of yesterday).  
But since I got this bug on 3.19.0, which is marked as correct in the issue, I'm not sure if the example is correct or not.

**Comment by Kongdy** [comment]
@darshankawar 
I have tested it on the latest 3.29.0 version, and the issue still reproduces there. 

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.29.0, on macOS 14.6.1 23G93 darwin-arm64, locale zh-Hans-AL)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 16.2)
    ! CocoaPods 1.15.2 out of date (1.16.2 is recommended).
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      To update CocoaPods, see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.92.1)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for 王康的iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
> The address of the demo is: https://github.com/Kongdy/miss_img_demo

Thanks for the update and the repo. Using it, I was able to replicate the reported behavior on latest sdk versions.

```
stable : 3.29.0
master : 3.30.0-1.0.pre.191
```

**Comment by emakar** [comment]
Could this be the issue described here? https://github.com/flutter/flutter/issues/156488#issuecomment-2675634813
One is caused by using ProcessLifecycleOwner
