### ISSUE TITLE
Cannot read assets when running flutter_tester

### ISSUE THREAD

**Issue by scheglov** [flutter/flutter#16516]
This code works on real device when `flutter run lib/get_asset.dart`.

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

main() async {
  var s1 = await rootBundle.loadString('my_assets/1.txt');
  print(s1);
}
```

  But it fails when I run using `/Users/scheglov/Source/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester --non-interactive --enable-dart-profiling --packages=.packages --flutter-assets-dir=/Users/scheglov/dart/flutter-projects/test_sink/build/flutter_assets build/app.dill` or `flutter run -d flutter-tester lib/get_asset.dart`

```
Observatory listening on http://127.0.0.1:55697/
[ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
Unable to load asset: my_assets/1.txt
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
<asynchronous suspension>
#1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:67:33)
<asynchronous suspension>
#2      CachingAssetBundle.loadString.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:162:56)
#3      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
#4      CachingAssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:162:27)
#5      main (file:///Users/scheglov/dart/flutter-projects/test_sink/lib/get_asset.dart:5:29)
<asynchronous suspension>
#6      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

**Comment by jason-simmons** [comment]
I don't think the current flutter_tester supports this scenario.

This will work after @chinmaygarde's engine refactoring lands:

```
flutter build bundle lib/get_asset.dart
flutter_tester --non-interactive --packages=.packages --flutter-assets-dir=build/flutter_assets build/app.dill
```

**Comment by scheglov** [comment]
Sounds great!
Thanks.

**Comment by chinmaygarde** [comment]
This [should work now](https://github.com/flutter/engine/blob/0b7d6be9765a2ba34bb45c99cbfda817423b779c/shell/testing/tester_main.cc#L162). Make sure to to specify the assets path using [this flag](https://github.com/flutter/engine/blob/master/shell/common/switches.h#L89).

**Comment by zoechi** [comment]
What about `flutter test`?
What is `flutter_tester` anyway?

**Comment by jason-simmons** [comment]
`flutter_tester` is a binary that runs the Flutter engine on the host workstation.  It's used to execute `flutter test` tests.

**Comment by scheglov** [comment]
Hm... It still does not work for me.
Do you see any issue in my versions or command line?

```
scheglov@scheglov-macbookpro4:~/dart/flutter-projects/test_sink$ flutter --version
Flutter 0.2.12-pre.37 • channel master • git@github.com:scheglov/flutter.git
Framework • revision ab9ba3f909 (82 minutes ago) • 2018-04-16 10:04:40 -0700
Engine • revision 76cb311d9c
Tools • Dart 2.0.0-dev.47.0.flutter-f76dad0adc


scheglov@scheglov-macbookpro4:~/dart/flutter-projects/test_sink$ /Users/scheglov/Source/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester --non-interactive --packages=.packages --flutter-assets-dir=build/flutter_assets build/app.dill
Observatory listening on http://127.0.0.1:60998/
[ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
Unable to load asset: my_assets/1.txt
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
<asynchronous suspension>
#1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:67:33)
<asynchronous suspension>
#2      CachingAssetBundle.loadString.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:162:56)
#3      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
#4      CachingAssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:162:27)
#5      main (file:///Users/scheglov/dart/flutter-projects/test_sink/lib/get_asset.dart:5:29)
<asynchronous suspension>
#6      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

scheglov@scheglov-macbookpro4:~/dart/flutter-projects/test_sink$ ls -l build/flutter_assets/my_assets/
total 8
-rw-r--r--  1 scheglov  eng  5 Apr 16 11:03 1.txt
```

**Comment by jason-simmons** [comment]
The engine refactoring re-landed in https://github.com/flutter/engine/commit/58e84c8bf0b6304649340e6eaad988602961d7f6, which hasn't yet rolled over to the framework.

(Currently you're running an engine build from https://github.com/flutter/engine/commit/76cb311d9c33720dcd19274228b39ecdbad8d9af, which is a day older)

Try a locally built engine at the tip of tree, or wait for the next engine roll.

**Comment by scheglov** [comment]
Ah, makes sense.
I will wait then.
Thanks!
