### ISSUE TITLE
"Task bot died: Backend task is interrupted" occurring at high-ish frequency across fleet

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#166845]
[Latest example](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20tool_integration_tests_2_7/24/overview):

> Infra Failure: Step('read_logs') (canceled) (retcode: None) Infra Failure: Step('Killing Processes.kill chrome') (canceled) (retcode: None) Infra Failure: Step('OS info (2)') (canceled) (retcode: None) Task bot died. backend task is interrupted

From talking to Chromium folks:

> Something is sending SIGTERM signal to the running build.
>
> SSH to the machine and examine syslog, maybe there'll be a clue of what is sending this SIGTERM

**Comment by jtmcdole** [comment]
[Latest logs](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8718055138425116721/+/u/run_test.dart_for_tool_integration_tests_shard_and_subshard_2_7/l_debug) shows GLOBAL_SHUTDOWN of the bot.

**Comment by jtmcdole** [comment]
Several other reported bots have events pointing to reboots.

Looking at the logs; this is also not a new thing for either pre or post-submits - but it did start increasing for post-submits around March 24th~25th.

**Comment by jtmcdole** [comment]
Linux boxes were upgraded to Ubuntu 24.04 on the 19th. It took awhile for that to roll out to the whole fleet, but I don't think it was 4-5 days. Log messages show increasing on Tuesday-Friday and then down Sat-Monday.

**Comment by matanlurey** [comment]
Reducing to P1 as we've made little progress and it doesn't seem to be causing any recurring outages.

**Comment by jtmcdole** [comment]
Updates:

- Debugging with the LUCI and Dart team didn't turn up much, other than our documentation was out of date on how to log into machines and dig around.
- journalctl was needed to find logs beyond reboots (/var/log/syslog gets blow away).
- SIGTERM is being sent to some bots, but not others
- On one bot we saw unattended upgrades running, followed by the reboot

Some believe this is just OOM killing on 24.04.  There are only 32 tasks that "died" on prod out of thousands (success: 9898, failure: 136).

Links:

[Non-canary BOT_DIED (Ubuntu)](https://chromium-swarm.appspot.com/tasklist?c=name&c=createdTs&c=pendingTime&c=duration&c=bot&c=pool-tag&c=state&d=desc&et=1744308703222&f=state%3ABOT_DIED&f=os-tag%3AUbuntu&f=authenticated-tag%3Aproject%3Aflutter&f=buildbucket_template_canary-tag%3A0&k=buildbucket_template_canary-tag&s=createdTs&st=1744019640000)


[Non-canary BOT_DIED Prod (Ubuntu)](https://chromium-swarm.appspot.com/tasklist?c=name&c=createdTs&c=pendingTime&c=duration&c=bot&c=pool-tag&c=state&d=desc&f=state%3ABOT_DIED&f=os-tag%3AUbuntu&f=authenticated-tag%3Aproject%3Aflutter&f=buildbucket_template_canary-tag%3A0&f=pool-tag%3Aluci.flutter.prod&k=pool-tag&s=createdTs&st=1744019640000)

**Comment by jtmcdole** [comment]
Closing: we'll keep an eye out.

**Comment by jtmcdole** [comment]
Updates:

-

**Comment by jtmcdole** [comment]
Update: chrome infra landed changes to the images to run unattended upgrades at boot (and reboot if needed). This should make our bots not reboot in the middle of task.

Bad news: it landed this morning, after we rolled our new images. We won't see this benefit till next week.

**Comment by matanlurey** [comment]
@jtmcdole Do we expect this resolved now?

**Comment by jtmcdole** [comment]
> @jtmcdole Do we expect this resolved now?

No, they didn't land the PR in time. I'll check if it landed today

**Comment by matanlurey** [comment]
This needs action - either an escalation to Chromium infra, ask the Dart infra team for help, or something else.

**Comment by jtmcdole** [comment]
The original report for this was due to software updates. An image rolled and and then was rolled back because of some boot issues. I'm unable to get journalctl logs from bots; so holding for now.

Current BOT_DIED reports are at 0.25% for yesterday and 0.06% for the last 2 weeks.

**Comment by chinmaygarde** [comment]
This is [still happening](https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20tool_integration_tests_5_7/4367/infra). I followed the links in https://github.com/flutter/flutter/issues/166845#issuecomment-2797460258 and the rate seems about the same as on Friday. Though it was abnormally high last Wednesday.

Retrying to work around it so not blocked.

**Comment by chinmaygarde** [comment]
[Another one](https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Engine%20Drone/3405534/overview) and the rate now seems way higher. ~35 times today already.

**Comment by jtmcdole** [comment]
There's a conversation going internally about this. We have lose the ability to see any logs and so we have to escallate.
