### ISSUE TITLE
[Google3 Bug]: Recent Impeller Changes Breaks SVG Rendering

### ISSUE THREAD

**Issue by yingshanliu-gh** [flutter/flutter#170173]
### Help us understand the severity of this issue

- [x] causing severe production issues e.g. malfunctions or data loss
- [ ] blocking next binary release
- [x] blocking a client feature launch within a quarter
- [ ] nice-to-have but does not block a launch within the next quarter

### Steps to reproduce

1. For Android, ensure that impeller is enabled. For iOS, impeller is already enabled by default.
2. Render the first SVG in b/421028801#comment8 (actual URL is redacted as it is confidential) using flutter_svg library. A simple widget snippet:
```
// ...
import 'package:flutter_svg/flutter_svg.dart';

// ...
@override
Widget build(BuildContext context) {
  return Container(
    child: SvgPicture.network(
      '<URL to the first SVG in b/421028801#comment8>',
    ),
  );
}
```

### Expected results

Rendering should look normal and the same as e.g. rendering when opened on Chrome browser. (Actual image is redacted as it is confidential)

### Actual results

The result will have anomalies, e.g. stretched lines or other glitches. (Actual image is redacted as it is confidential)

### Code sample

<details open><summary>Code sample</summary>

```dart
// ...
import 'package:flutter_svg/flutter_svg.dart';

// ...
@override
Widget build(BuildContext context) {
  return Container(
    child: SvgPicture.network(
      '<URL to the first SVG in b/421028801#comment8>',
    ),
  );
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by yingshanliu-gh** [comment]
cc: @zanderso

**Comment by zanderso** [comment]
The roll Cl cl/746081573 contained a few Impeller changes, but my eye is drawn to https://github.com/flutter/flutter/commit/06c572c73023775b57c1475c1fc2645e183ed29f as a potential culprit. @flar could you take a look at the repro above? Thanks!

**Comment by flar** [comment]
Hopefully fixed by https://github.com/flutter/flutter/pull/170194 but some verification of the actual apps running with that fix would be nice before we consider this issue closed.

**Comment by yingshanliu-gh** [comment]
The reported issue could be reproducible at the master, I'd recommend to verify at master with the provided mini repo and SVG urls. The rendering issue is very visible, for example: https://screenshot.googleplex.com/8MYdiH48EsswKG2.

I tried to patch #170194 and verified in both my app and master, however, it didn't fix the issue.

**Comment by zanderso** [comment]
@yingshanliu-gh The patch in https://github.com/flutter/flutter/pull/170194 is a change to the Flutter engine. The internal Flutter build rules don't re-build the Flutter engine from source, so simply patching the PR into the internal repo wouldn't have picked up the changes.

**Comment by yingshanliu-gh** [comment]
I see, got it, thanks for sharing the context regarding the build rules.

In that case, I think there might be no easy way for me to help verify the fix before it gets into Google3 Flutter rollout.

Is it possible for me to learn about the estimated timeline for this fix to get rolled into Google3?

**Comment by flar** [comment]
> The reported issue could be reproducible at the master, I'd recommend to verify at master with the provided mini repo and SVG urls. The rendering issue is very visible, for example: https://screenshot.googleplex.com/8MYdiH48EsswKG2.
> 
> I tried to patch [#170194](https://github.com/flutter/flutter/pull/170194) and verified in both my app and master, however, it didn't fix the issue.

I verified with the indicated "comment 8" SVG URL, which it does fix, but there appeared to be other reports as well. I didn't run them all down.

**Comment by yingshanliu-gh** [comment]
Thank you so much for the prompt fix!

**Comment by flar** [comment]
https://github.com/flutter/flutter/pull/170194 has landed in the Flutter repo so using the Flutter ToT should demonstrate the fix.

**Comment by chinmaygarde** [comment]
Closing as completed.
