### ISSUE TITLE
CircularProgressIndicator and other animation controllers on Flutter Web throws infinite !isDisposed exceptions after hot restart (regression in Flutter 3.35 / Dart 3.9)

### ISSUE THREAD

**Issue by hbuhrmann** [flutter/flutter#175260]
### Steps to reproduce

After upgrading to Flutter 3.35.3 stable with Dart 3.9.2, hot restarting a web app that contains a CircularProgressIndicator causes an infinite stream of exceptions:

Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:99:12
!isDisposed
"Trying to render a disposed EngineFlutterView."

This continues endlessly until the browser tab is refreshed.

This did not occur on earlier Flutter versions (≤3.32.x). It appears to be a regression in how the web engine handles active tickers across hot restart.

Steps to Reproduce:

Create a new Flutter project.

Replace main.dart with the code below.

Run in Chrome (flutter run -d chrome).

Perform a hot restart in Android Studio or from the terminal.

Observe the infinite !isDisposed spam in the console.

Does not reproduce on Android or iOS — only Flutter Web.

Other animation-driven widgets (custom AnimationController, AnimatedBuilder) can cause similar errors if active during hot restart.

This is new; it worked fine in earlier stable releases.

### Expected results

Hot restart should cleanly reset the app state without leaving behind any tickers or animation frames.

### Actual results

Hot restart leaves the CircularProgressIndicator’s ticker running, causing an infinite stream of !isDisposed exceptions. Same with pulseExample

### Code sample

<details open><summary>Code sample Progress Indicator</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: CircularProgressIndicator(), // culprit
        ),
      ),
    );
  }
}
```

</details>

<details open><summary>Code sample Another animationController</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: PulseExample(),
        ),
      ),
    );
  }
}

class PulseExample extends StatefulWidget {
  const PulseExample({super.key});

  @override
  State<PulseExample> createState() => _PulseExampleState();
}

class _PulseExampleState extends State<PulseExample>
    with SingleTickerProviderStateMixin {
  late AnimationController _controller;
  late Animation<double> _scale;

  @override
  void initState() {
    super.initState();
    _controller =
        AnimationController(vsync: this, duration: const Duration(seconds: 1));
    _scale = Tween<double>(begin: 1.0, end: 1.5).animate(
      CurvedAnimation(parent: _controller, curve: Curves.easeInOut),
    );
    _loop();
  }

  Future<void> _loop() async {
    while (mounted) {
      await _controller.forward();
      await _controller.reverse();
    }
  }

  @override
  void dispose() {
    _controller.stop();
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: _scale,
      builder: (_, child) =>
          Transform.scale(scale: _scale.value, child: child),
      child: const Icon(Icons.favorite, size: 64, color: Colors.red),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:99:12
!isDisposed
"Trying to render a disposed EngineFlutterView."

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 274:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 44:3        assertFailed
lib/_engine/engine/window.dart 99:13                                              render
package:flutter/src/rendering/view.dart 363:7                                     compositeFrame
package:flutter/src/rendering/binding.dart 634:19                                 drawFrame
package:flutter/src/widgets/binding.dart 1261:13                                  drawFrame
package:flutter/src/rendering/binding.dart 495:5                                  [_handlePersistentFrameCallback]
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 118:77  tear
package:flutter/src/scheduler/binding.dart 1434:7                                 [_invokeFrameCallback]
package:flutter/src/scheduler/binding.dart 1347:9                                 handleDrawFrame
package:flutter/src/scheduler/binding.dart 1200:5                                 [_handleDrawFrame]
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 118:77  tear
lib/_engine/engine/platform_dispatcher.dart 1522:5                                invoke
lib/_engine/engine/platform_dispatcher.dart 265:5                                 invokeOnDrawFrame
lib/_engine/engine/frame_service.dart 192:32                                      [_renderFrame]
lib/_engine/engine/frame_service.dart 99:9                                        <fn>
dart-sdk/lib/async/zone.dart 1849:54                                              runUnary
dart-sdk/lib/async/zone.dart 1804:26                                              <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/js_allow_interop_patch.dart 224:27    _callDartFunctionFast1
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:99:12
!isDisposed
"Trying to render a disposed EngineFlutterView."

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 274:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 44:3        assertFailed
lib/_engine/engine/window.dart 99:13                                              render
package:flutter/src/rendering/view.dart 363:7                                     compositeFrame
package:flutter/src/rendering/binding.dart 634:19                                 drawFrame
package:flutter/src/widgets/binding.dart 1261:13                                  drawFrame
package:flutter/src/rendering/binding.dart 495:5                                  [_handlePersistentFrameCallback]
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 118:77  tear
package:flutter/src/scheduler/binding.dart 1434:7                                 [_invokeFrameCallback]
package:flutter/src/scheduler/binding.dart 1347:9                                 handleDrawFrame
package:flutter/src/scheduler/binding.dart 1200:5                                 [_handleDrawFrame]
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 118:77  tear
lib/_engine/engine/platform_dispatcher.dart 1522:5                                invoke
lib/_engine/engine/platform_dispatcher.dart 265:5                                 invokeOnDrawFrame
lib/_engine/engine/frame_service.dart 192:32                                      [_renderFrame]
lib/_engine/engine/frame_service.dart 99:9                                        <fn>
dart-sdk/lib/async/zone.dart 1849:54                                              runUnary
dart-sdk/lib/async/zone.dart 1804:26                                              <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/js_allow_interop_patch.dart 224:27    _callDartFunctionFast1
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:99:12
!isDisposed
"Trying to render a disposed EngineFlutterView."

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 274:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 44:3        assertFailed
lib/_engine/engine/window.dart 99:13                                              render
package:flutter/src/rendering/view.dart 363:7                                     compositeFrame
package:flutter/src/rendering/binding.dart 634:19                                 drawFrame
package:flutter/src/widgets/binding.dart 1261:13                                  drawFrame
package:flutter/src/rendering/binding.dart 495:5                                  [_handlePersistentFrameCallback]
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 118:77  tear
package:flutter/src/scheduler/binding.dart 1434:7                                 [_invokeFrameCallback]
package:flutter/src/scheduler/binding.dart 1347:9                                 handleDrawFrame
package:flutter/src/scheduler/binding.dart 1200:5                                 [_handleDrawFrame]
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 118:77  tear
lib/_engine/engine/platform_dispatcher.dart 1522:5                                invoke
lib/_engine/engine/platform_dispatcher.dart 265:5                                 invokeOnDrawFrame
lib/_engine/engine/frame_service.dart 192:32                                      [_renderFrame]
lib/_engine/engine/frame_service.dart 99:9                                        <fn>
dart-sdk/lib/async/zone.dart 1849:54                                              runUnary
dart-sdk/lib/async/zone.dart 1804:26                                              <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/js_allow_interop_patch.dart 224:27    _callDartFunctionFast1
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:99:12
!isDisposed
"Trying to render a disposed EngineFlutterView."

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 274:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 44:3        assertFailed
lib/_engine/engine/window.dart 99:13                                              render
package:flutter/src/rendering/view.dart 363:7                                     compositeFrame
package:flutter/src/rendering/binding.dart 634:19                                 drawFrame
package:flutter/src/widgets/binding.dart 1261:13                                  drawFrame
package:flutter/src/rendering/binding.dart 495:5                                  [_handlePersistentFrameCallback]
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 118:77  tear
package:flutter/src/scheduler/binding.dart 1434:7                                 [_invokeFrameCallback]
package:flutter/src/scheduler/binding.dart 1347:9                                 handleDrawFrame
package:flutter/src/scheduler/binding.dart 1200:5                                 [_handleDrawFrame]
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 118:77  tear
lib/_engine/engine/platform_dispatcher.dart 1522:5                                invoke
lib/_engine/engine/platform_dispatcher.dart 265:5                                 invokeOnDrawFrame
lib/_engine/engine/frame_service.dart 192:32                                      [_renderFrame]
lib/_engine/engine/frame_service.dart 99:9                                        <fn>
dart-sdk/lib/async/zone.dart 1849:54                                              runUnary
dart-sdk/lib/async/zone.dart 1804:26                                              <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/js_allow_interop_patch.dart 224:27    _callDartFunctionFast1
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:99:12
!isDisposed
"Trying to render a disposed EngineFlutterView."

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 274:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 44:3        assertFailed
lib/_engine/engine/window.dart 99:13                                              render
package:flutter/src/rendering/view.dart 363:7                                     compositeFrame
package:flutter/src/rendering/binding.dart 634:19                                 drawFrame
package:flutter/src/widgets/binding.dart 1261:13                                  drawFrame
package:flutter/src/rendering/binding.dart 495:5                                  [_handlePersistentFrameCallback]
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 118:77  tear
package:flutter/src/scheduler/binding.dart 1434:7                                 [_invokeFrameCallback]
package:flutter/src/scheduler/binding.dart 1347:9                                 handleDrawFrame
package:flutter/src/scheduler/binding.dart 1200:5                                 [_handleDrawFrame]
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 118:77  tear
lib/_engine/engine/platform_dispatcher.dart 1522:5                                invoke
lib/_engine/engine/platform_dispatcher.dart 265:5                                 invokeOnDrawFrame
lib/_engine/engine/frame_service.dart 192:32                                      [_renderFrame]
lib/_engine/engine/frame_service.dart 99:9                                        <fn>
dart-sdk/lib/async/zone.dart 1849:54                                              runUnary
dart-sdk/lib/async/zone.dart 1804:26                                              <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/js_allow_interop_patch.dart 224:27    _callDartFunctionFast1
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///lib/_engine/engine/window.dart:99:12
!isDisposed
"Trying to render a disposed EngineFlutterView."

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 274:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 44:3        assertFailed
lib/_engine/engine/window.dart 99:13                                              render
package:flutter/src/rendering/view.dart 363:7                                     compositeFrame
package:flutter/src/rendering/binding.dart 634:19                                 drawFrame
package:flutter/src/widgets/binding.dart 1261:13                                  drawFrame
package:flutter/src/rendering/binding.dart 495:5                                  [_handlePersistentFrameCallback]
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 118:77  tear
package:flutter/src/scheduler/binding.dart 1434:7                                 [_invokeFrameCallback]
package:flutter/src/scheduler/binding.dart 1347:9                                 handleDrawFrame
package:flutter/src/scheduler/binding.dart 1200:5                                 [_handleDrawFrame]
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 118:77  tear
lib/_engine/engine/platform_dispatcher.dart 1522:5                                invoke
lib/_engine/engine/platform_dispatcher.dart 265:5                                 invokeOnDrawFrame
lib/_engine/engine/frame_service.dart 192:32                                      [_renderFrame]
lib/_engine/engine/frame_service.dart 99:9                                        <fn>
dart-sdk/lib/async/zone.dart 1849:54                                              runUnary
dart-sdk/lib/async/zone.dart 1804:26                                              <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/js_allow_interop_patch.dart 224:27    _callDartFunctionFast1
====================================================================================================
Application finished.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter 3.35.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision a402d9a437 (8 days ago) • 2025-09-03 14:54:31 -0700
Engine • hash 672c59cfa87c8070c20ba2cd1a6c2a1baf5cf08b (revision ddf47dd3ff) (8 days ago) • 2025-09-03 20:02:13.000Z
Tools • Dart 3.9.2 • DevTools 2.48.0
PS C:\Users\hanne\AndroidStudioProjects\hot_restart_with_material_app_router> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.35.3, on Microsoft Windows [Version 10.0.26100.6584], locale en-GB)
[√] Windows Version (11 Home 64-bit, 24H2, 2009)
[√] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2024.2)
[√] VS Code (version 1.99.3)
[√] Connected device (3 available)
    ! Device Z5P7WG7TJJTCR4PZ is offline.
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by PeterKottas** [comment]
Great catch! I saw this too, but didn't know what was causing it.

**Comment by darshankawar** [comment]
Thanks for the report. I was able to replicate this on latest stable and master versions and also upto 3.27.0. 
The behavior used to work well until 3.24.0 but seem to have regressed after it and continues to throw the error till latest versions.
The same error has been reported / mentioned several times in [this](https://github.com/flutter/flutter/issues/140684) open issue, but it doesn't seem to be same as the error / issue reported in this report. This error reports seems specific to Animation controllers or CircularProgressIndicator while the linked issue doesn't have that code implementation which is also explained in [this](https://github.com/flutter/flutter/issues/140684#issuecomment-1960548143) comment. Looks like the issue reported in this report was fixed as part of https://github.com/flutter/engine/pull/49958, but seem to have re-surfaced.

```
stable: 3.35.3
master : 3.37.0-1.0.pre-111
```

**Comment by biggs0125** [comment]
@mdebbar any idea what may have caused this to resurface?

**Comment by mdebbar** [comment]
~Bisected it to https://github.com/flutter/flutter/pull/173362 (cc @bkonyi) but I'm not sure how or why that PR causes this error.~

I'm not sure about the result of the bisect. I discovered that I'm having caching issues? I checkout a certain commit, then I do `flutter run` but it's not using the checked out commit..

**Comment by mdebbar** [comment]
AFAICT, this issue is reproducible all the way back to 3.24.0. Even with https://github.com/flutter/engine/pull/49958 (which was rolled into flutter/flutter in https://github.com/flutter/flutter/commit/236461161a879dfd36d6de55e41afd19c10e31cc), I'm still getting the same error.

Can you someone else double check? @darshankawar have you found a commit that doesn't reproduce the problem?

**Comment by hbuhrmann** [comment]
Not sure whether this would be helpful or not - previously I was on 3.27 and did not experience the issue. I then upgraded to 3.32.x with no issue. I only started experiencing it after iupgraded to 3.35.3

Debug environment Android Studio, Chrome For Windows

**Comment by darshankawar** [comment]
> [@darshankawar](https://github.com/darshankawar) have you found a commit that doesn't reproduce the problem?

@mdebbar Hi, No, as I wasn't able to replicate on 3.24.0, but I'll try again on same version and will check if I could find the commit.

**Comment by jason-simmons** [comment]
This appears to be related to the introduction of web hot reload in https://github.com/flutter/flutter/commit/7e32a77210b5f22c1d2255ca1c6b4474a8f23fa9

The infinite loop of exceptions does not happen if I run the app with the `--no-web-experimental-hot-reload` flag.

@nshahan

**Comment by PeterKottas** [comment]
How can we at least temporarily prevent these logs from reaching the console? They appear so quickly that it crashes my debug session within a minute or so. At least some temp solution would be great, thanks!

**Comment by mdebbar** [comment]
> This appears to be related to the introduction of web hot reload in [7e32a77](https://github.com/flutter/flutter/commit/7e32a77210b5f22c1d2255ca1c6b4474a8f23fa9)
> 
> The infinite loop of exceptions does not happen if I run the app with the `--no-web-experimental-hot-reload` flag.

You bring up a pretty good distinction actually. There are two separate problems here:

1. The view disposed assertion: This has been happening since the introduction of multi-view AFAICT. We dispose of the implicit view during hot restart, and it causes the next frame to fail because it's happening before the implicit view is recreated (this is a bug that needs to be fixed, but it's less intrusive).
1. The infinite repetition of the assertion: At some point, the above error started being thrown infinitely. This is super intrusive and eventually leads to a Chrome Devtools crash.



> How can we at least temporarily prevent these logs from reaching the console?

@PeterKottas have you tried the `--no-web-experimental-hot-reload` flag suggested above? Add it to your `flutter run` command and let us know if that helps.

**Comment by PeterKottas** [comment]
@mdebbar Thanks! Worked. I am on 3.35 and wrongly assumed the "experimental" was already dropped, as it seems to have been shipped as stable.

**Comment by mdebbar** [comment]
This [comment](https://github.com/flutter/flutter/issues/140684#issuecomment-3251179364) by @nshahan was spot on. I created a [fix](https://github.com/flutter/flutter/pull/175856) based on that and it worked!
