### ISSUE TITLE
GestureDetector onTapDown/onTapUp/onTapCancel multiple callbacks when two are on top of each other

### ISSUE THREAD

**Issue by ebeem** [flutter/flutter#18561]
I am not sure if this is an expected behavior, but when two or more `GestureDetector` are placed on top of each other same as the image below.

The behavior is as follows:

[✔] onTapDown `square 1` calls tap down `square 1`
[✔] onTapUp `square 1` calls tap up `square 1` & tapped `square 1`
[✔] onTapCancel `square 1` calls tap cancel `square 1`

[X] onTapDown `square 2` calls tap down `square 2` & tap down `square 1`
[X] onTapUp `square 2` calls tap up `square 2` & tapped `square 2` & tapped cancel `square 1`
[X] onTapCancel `square 1` calls tap cancel `square 2` & tap cancel `square 1`

while this can be an expected behavior at the same time, since tapping square 2 does not tap square 1 after all, and all the other tap callbacks will just provide more details, having two `FlatButton` placed on top of each other results in the `Ripple Effect`/`Inkwell`/`Splash Effect` to be created in both Flat buttons, which is not an expected behaviour.

is there any way to bypass callbacks on parent `FlatButton` of child `FlatButton` was tapped down?

gist: https://gist.github.com/ebeem/1c331c1606fe9132b70def187a3086e1

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.5-pre.44, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[✓] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
[✓] Connected devices (1 available)

• No issues found!
flutter doctor  6.07s user 0.46s system 122% cpu 5.342 total
```

![screenshot_20180618-111146](https://user-images.githubusercontent.com/25146039/41525210-e00c438a-72e8-11e8-96af-392738b2e94f.png)

**Comment by zoechi** [comment]
Please add the output of `flutter doctor`

**Comment by ebeem** [comment]
added

**Comment by mitko9000** [comment]
@ebeem can I see the code ?

**Comment by mitko9000** [comment]
@ebeem If you make the containers to hold the GestureDetector does this solve the problem ?

**Comment by ebeem** [comment]
@mitko9000 
I think it will, but how will I be able to tell if the inner square was clicked?
and in case a FlatButton is used, this option will be a very difficult one

**Comment by mitko9000** [comment]
@ebeem What is the output of onTap ?

**Comment by ebeem** [comment]
@mitko9000  I am not sure what do you mean
onTap is an event that's handled by the developers, you decide whether you want to have an output or not.
if what you mean is the output when you have a Container with GestureDetector, then you will trigger onTap when the Container is tapped.
if yiy mean the output if you have a GestureDetector on two different containers on top of each others, then it's the same, because the GestureDetector seems not to check if there is another GestureDetector that was triggered at same tapped point, so any Container with a GestureDetector will trigger tap if the tapped point is insde the borders of the Container, whether it's on top, bottom, or between

**Comment by ebeem** [comment]
thank god I am not alone in this
@faob-dev sorry friend, I already investigated this ...
we need to make some changes in the `GestureDetector` to make it work. The problem is, no one knows whether this is the expected behavior or not, and whether fixing this will break some existing apps or not, that's the main reason why I created this issue.

Sadly, I don't know someone who can answer this, all I know is that this is not the behavior in Android Material implementation, and there are a couple of people like you and me who do not see this as an expected behavior.

please cc anyone who can help us, thanks.

**Comment by faob-dev** [comment]
@ebeem i wasted so much time on that i guess this is not expected behavior this should be fixed and i am surprised no one from flutter community replying on that issue at least they should tell us is this expected behavior or not

**Comment by miguelcmedeiros** [comment]
I am also having this issue. Any update?

**Comment by dannyvalentesonos** [comment]
Have you tried setting the GestureDetector's behavior fields to HitTestBehavior.opaque?

HitTestBehavior.opaque:
/// Opaque targets can be hit by hit tests, causing them to both receive
  /// events within their bounds and prevent targets visually behind them from
  /// also receiving events.

**Comment by miguelcmedeiros** [comment]
@zoechi, the no-response bot just closed this issue, perhaps due to "waiting for customer response" label, but since @shinayser replied to the previous proposal and mentioned that it didn't solve the problem, the label is not valid anymore.

Since this is a problem that I have on my app, can you please re-open it?

**Comment by R12-cookies** [comment]
I am also facing the same issue, waiting for updates.
