### ISSUE TITLE
Camera Images are displayed too dark

### ISSUE THREAD

**Issue by jonasbark** [flutter/flutter#19038]
**Steps to reproduce:**
1. Create a new flutter project
2. add Camera dependency
3. use the implementation of the Camera Example.
4. change the implementation slightly that the shot photo preview is a lot bigger (to see the image result)
5. start the app, create a new photo
6. the photo image shown is lot darker than expected

**Observation**:
- the photo file is not at fault as it displays correctly when looking at it on a computer
- this does not happen in the beta channel (see screenshots for comparison)
- this also happens in the dev channel 
- related to https://github.com/flutter/flutter/issues/8630 or https://github.com/flutter/flutter/issues/15600 ?

Preview image (everything fine here):
![master_preview](https://user-images.githubusercontent.com/1151304/42221199-9ffd7382-7ed1-11e8-8162-cf94a27e4063.png)

Resulting image (way too dark):
![master_picture](https://user-images.githubusercontent.com/1151304/42221228-b3158a04-7ed1-11e8-8022-2442f00425c4.png)

Compared to the correct output in the **beta** channel:
![beta_picture](https://user-images.githubusercontent.com/1151304/42221251-c3a6c306-7ed1-11e8-8994-59560b95c7cb.png)

**Flutter Doctor:**
```
[✓] Flutter (Channel master, v0.5.6-pre.100, on Mac OS X 10.13.5 17F77, locale de-DE)
    • Flutter version 0.5.6-pre.100 at /Users/boni/Documents/Programmieren/Dart/flutter
    • Framework revision 7e4038fe27 (5 days ago), 2018-06-28 14:10:26 +0100
    • Engine revision 6fe748490d
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc1)
    • Android SDK at /Users/boni/Library/Android/sdk
    • Android NDK at /Users/boni/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.2 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b04)

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.24.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (2 available)
    • ONEPLUS A3003 • 75aef492                                 • android-arm64 • Android 8.0.0 (API 26)
    • Iphone 6 Grau • 75c53fe05e0703ae0d22634f157f01193712d211 • ios           • iOS 11.0.2

! Doctor found issues in 1 category.
```

**Comment by jonasbark** [comment]
For some reasons it's fixed in the newest master.

**Comment by dessant** [comment]
I see the same with both camera examples on beta, dev and master. The preview image is dark, especially at the bottom of the widget, and it brightens up if video is being recorded. Could you reopen the issue?

**Comment by jonasbark** [comment]
I think that's a different issue and related to the camera plugin while this issue was about wrong colors of existing images

**Comment by dessant** [comment]
I think it's the same underlying bug, we just reproduced it through different paths.

**Comment by zoechi** [comment]
For these who still see this issue. 
Please check #26079 or create a new issue.
