### ISSUE TITLE
Attempt to invoke virtual method 'android.view.Surface android.media.ImageReader.getSurface()' on a null object reference

### ISSUE THREAD

**Issue by aravindhkumar23** [flutter/flutter#19595]
App crashes when users gives permission to access the gallery for the very first time with error message showing 
```
07-20 12:41:37.841 4132-4132/com.----.--- E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.----.-----, PID: 4132
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Surface android.media.ImageReader.getSurface()' on a null object reference
        at io.flutter.plugins.camera.CameraPlugin$Camera.startPreview(CameraPlugin.java:676)
        at io.flutter.plugins.camera.CameraPlugin$Camera.access$2000(CameraPlugin.java:243)
        at io.flutter.plugins.camera.CameraPlugin$Camera$3.onOpened(CameraPlugin.java:443)
        at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:139)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Version:**
Flutter 0.5.1 
camera: "^0.2.1"
image_picker: "^0.4.5"

**Steps To Reproduce,**
1. Create a Stack view with CameraPreview with 2 button to capture and open gallery 
2. Click on open gallery button (At first time it asks for permission click allow -> CRASHED)
 open gallery by using `final File galleryImagePath = await ImagePicker.pickImage(source:ImageSource.gallery);`

sample code to Reproduce [CameraView - sample code](https://gist.github.com/aravindhkumar23/739cf778e31fa48f4f38c7494066d721)

**Comment by bdytx5** [comment]
Same problem.....

**Comment by bdytx5** [comment]
In the Camera plugin.java, I added this on line 670 ish right before   
surfaces.add(imageReader.getSurface());


// here is the code. Works for me...
if(surfaces == null || imageReader == null){
        return;
      }

**Comment by NarHakobyan** [comment]
any plans to fix this?

**Comment by franzejr** [comment]
@NarHakobyan, 
This PR was going to solve it somehow: https://github.com/flutter/plugins/pull/794

You can use the forked library (for testing purposes):

```
camera:
    git:
      url: git://github.com/CircleCurve/plugins.git
      path: packages/camera
```

**Comment by CircleCurve** [comment]
@franzejr hi guys, hope that it can help you to solve this problem haha. I have made a pull request but unfortunately being rejected by the bot. I have not tried it again.

**Comment by aloisdeniel** [comment]
This crash still happens in my app with the latest version.

**Comment by bdytx5** [comment]
Aloisdeniel, make sure the plugin is up to date. If it is and it still doesn’t work, try adding the block of code on line 670 of the plugin. Running “flutter clean” may also do the trick.

**Comment by SaltumDis** [comment]
I am still getting this issue. Camera version: "0.3.0"

**Comment by idealopamp** [comment]
I see this has been fixed in https://github.com/flutter/plugins/pull/1191 and added to the Submit Queue.  Anyone know if/when the PR will be merged? Still seeing crashes from first time users with this.

**Comment by SaltumDis** [comment]
Bug is fixed

**Comment by kevin-lot** [comment]
This issue re happens with version 0.5.3.

**Comment by kevin-lot** [comment]
Possible fix: https://github.com/flutter/flutter/issues/39109#issuecomment-524250114

**Comment by elviskuo07** [comment]
camera: ^0.5.4+1 

still happen

Temp Solution:
change io.flutter.plugins.camera.java, line 435

public void startPreview() throws CameraAccessException {
      createCaptureSession(CameraDevice.TEMPLATE_PREVIEW, pictureImageReader.getSurface());
  }

to

public void startPreview() throws CameraAccessException {
    if (pictureImageReader != null) // <= add this line
      createCaptureSession(CameraDevice.TEMPLATE_PREVIEW, pictureImageReader.getSurface());
  }

**Comment by navinkumar0118** [comment]
@elviskuo07 answers works fine, i have updated same 
for version camera: ^0.5.5+1

go to flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.5.5+1/android/src/main/java/io/flutter/plugins/camera/Camera.java 

Add below code on the line 424

public void startPreview() throws CameraAccessException {
if (pictureImageReader != null) // <= add this line as @elviskuo07  mentioned.
createCaptureSession(CameraDevice.TEMPLATE_PREVIEW, pictureImageReader.getSurface());
}

**Comment by jdeltoft** [comment]
I have been having random failures to start my preview on Android only with my barcode scanning section of my app, and I finally captured the error and found this thread with it.  I will give this a try to see if it eliminates my preview failures, thanks!

**Comment by votruk** [comment]
This issue is still happening for 0.5.7+3 version. Are there any chances that this issue will be resolved in the future?

**Comment by sgehrman** [comment]
same issue.  Using all the latest plugins.

**Comment by singhbhavneet** [comment]
I don't this is related but I solved by requesting camera, storage and microphone permissions and after they all are granted I went to camera screen and it WORKED!

**Comment by maxakak1998** [comment]
My issue is when i swtich the camera ( rear-face) fastly ( 5 times). This error happens, i had added the codes like bdytx5 mentioned. It works

**Comment by dirjud** [comment]
I am also having this issue on 0.5.8+1 on a Pixel 3. I am not seeing this problem on a Galaxy S8 or a Pixel 1.

**Comment by kw2019ltd** [comment]
same issue with latest plugin 

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Surface android.media.ImageReader.getSurface()' on a null object reference
       at io.flutter.plugins.camera.Camera.startPreview(Camera.java:424)
       at io.flutter.plugins.camera.Camera$2.onOpened(Camera.java:160)
       at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:151)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7710)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by kw2019ltd** [comment]
@TahaTesser  any update?

**Comment by pdliuw** [comment]
> 最新插件的相同问题
> 
> 致命异常：java.lang.NullPointerException：尝试
> 在io.flutter.plugins.camera.Camera.startPreview（Camera.org ）上的空对象引用上调用虚拟方法'android.view.Surface android.media.ImageReader.getSurface（）' 。 java：424）
> 位于io.flutter.plugins.camera.Camera $ 2.onOpened（Camera.java:160）
> 位于android.hardware.camera2.impl.CameraDeviceImpl $ 1.run（CameraDeviceImpl.java:151）
> 位于android.os.Handler
> android.os.Handler.dispatchMessage（Handler.java:100）
> 上的.handleCallback（Handler.java:883）android.app.ActivityThread.main（ActivityThread）上android.os.Looper.loop（Looper.java:214）
> 上的。 java：7710），
> 位于java.lang.reflect.Method.invoke（Method.java）
> 在com.android.internal.os.ZygoteInit.main（ZygoteInit.java:950）处com.android.internal.os.RuntimeInit $ MethodAndArgsCaller.run
> （RuntimeInit.java:516）

I also met

**Comment by ch-muhammad-adil** [comment]
> if (pictureImageReader != null)

for me it was 442, but one can search "startPreview" method and handle this exception there.

**Comment by efraespada** [comment]
Same problem here:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Surface android.media.ImageReader.getSurface()' on a null object reference
  	at io.flutter.plugins.camera.Camera.startPreview(Camera.java:424)
  	at io.flutter.plugins.camera.Camera$2.onOpened(Camera.java:160)
  	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:151)
  	at android.os.Handler.handleCallback(Handler.java:883)
  	at android.os.Handler.dispatchMessage(Handler.java:100)
  	at android.os.Looper.loop(Looper.java:214)
  	at android.app.ActivityThread.main(ActivityThread.java:7397)
  	at java.lang.reflect.Method.invoke(Native Method)
  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

**Comment by DevarshRanpara** [comment]
Facing same issue.
plugin version : `camera: ^0.5.8+1`
Flutter doctor output

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.1 19B88, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.48.0)
[✓] Connected device (1 available)

• No issues found!
```
 Error logs
```
08-31 10:24:07.816 E/AndroidRuntime(23702): FATAL EXCEPTION: main
08-31 10:24:07.816 E/AndroidRuntime(23702): Process: com.craypay.app, PID: 23702
08-31 10:24:07.816 E/AndroidRuntime(23702): java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Surface android.media.ImageReader.getSurface()' on a null object reference
08-31 10:24:07.816 E/AndroidRuntime(23702): 	at f.b.c.b.g.d(Unknown Source:5)
08-31 10:24:07.816 E/AndroidRuntime(23702): 	at f.b.c.b.g$b.onOpened(Unknown Source:7)
08-31 10:24:07.816 E/AndroidRuntime(23702): 	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:143)
08-31 10:24:07.816 E/AndroidRuntime(23702): 	at android.os.Handler.handleCallback(Handler.java:873)
08-31 10:24:07.816 E/AndroidRuntime(23702): 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-31 10:24:07.816 E/AndroidRuntime(23702): 	at android.os.Looper.loop(Looper.java:193)
08-31 10:24:07.816 E/AndroidRuntime(23702): 	at android.app.ActivityThread.main(ActivityThread.java:6680)
08-31 10:24:07.816 E/AndroidRuntime(23702): 	at java.lang.reflect.Method.invoke(Native Method)
08-31 10:24:07.816 E/AndroidRuntime(23702): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-31 10:24:07.816 E/AndroidRuntime(23702): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by amirh** [comment]
Flutter doctor output from duplicate issue:

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale fr_FR.UTF-8)
    • Flutter version 1.7.8+hotfix.4 at /home/kevin/Softwares/SDK/flutter
    • Framework revision 20e59316b8 (il y a 5 semaines), 2019-07-18 20:04:33
      -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /home/kevin/Softwares/SDK/android
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at:
      /home/kevin/Softwares/android-studio/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.
[✓] Android Studio (version 3.5)
    • Android Studio at /home/kevin/Softwares/android-studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
[✓] VS Code (version 1.37.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.3.0
[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API
      28) (emulator)
• No issues found!
```

**Comment by dirjud** [comment]
We found a bug in our code where if the phone listed more than one forward facing camera, we would try to open them all in rapid succession. After fixing up the code to only try opening one camera, we stopped having this issue.

**Comment by kw2019ltd** [comment]
still same issue

**Comment by Savyash** [comment]
same issue

**Comment by mvanbeusekom** [comment]
We have been looking into this (with matching PR #2965). The pull request adds a null check before accessing the object which of course prevents the accessing of the null object, but the question was if the `pictureImageReader` is actually allowed to be null at this point. We have been investigating the issue extensively but we are having a hard time reproducing the error in the way described (namely the app crashes directly after the camera permissions have been requested and allowed).

There are two things we did notice:

1. Since version 0.5.0 of the camera plugin, handling of application lifecycle events has been removed from the plugin itself and responsibility has been moved to the developers using the plugin. However this is not documented anywhere except for a sentence in the changelog. According to one of the issue posters, handling the lifecycle events solved the problem for him (see here);
2. We did get the same error when (using the example app) very rapidly switching between the front and back facing cameras. We noticed that in these cases the `onOpened` callback would be called after the `dispose` method has already been run (race condition).

We believe we could make things easier for other developers to add a bit more information to the readme file about handling the lifecycle events correctly (which is our estimation, would help most people experiencing this problem) and to keep the null check as suggested in PR #2965 to solve potential problems caused by race conditions (as described in the second point). @bparrishMines how do you feel about this?

**Comment by bparrishMines** [comment]
@mvanbeusekom Keeping the `null` check works for me. And improving documentation about handling lifecycle events and needing to `await` futures to avoid race conditions also sound like a good solution.

**Comment by mvanbeusekom** [comment]
Hi @panmari, according to the above discussion with @bparrishMines I created a new [PR](flutter/plugins#3127) which contains all the necessary changes to move this issue forward. I made sure to also include your commits but couldn't unfortunately do a compare cross fork to your repo, hence the new PR.

It would be great if you could give your consent on the [pull request](https://github.com/flutter/plugins/pull/3127) by leaving a comment with the following content: `@googlebot I consent.` so the CLA will be accepted.

If all is good the pull requests [#2965](flutter/plugins#2965) can be closed.
