### ISSUE TITLE
Access denied finding property "vendor.debug.egl.swapinterval" - after installing Android P Beta on OnePlus 6

### ISSUE THREAD

**Issue by leodr** [flutter/flutter#19810]
## Steps to Reproduce

1. Install Android P Beta DP3 on OnePlus 6
2. Launch any Flutter application(I tried a few of mine aswell as the example one)

## Logs

```
[  +71 ms] [C:\Users\user\AppData\Local\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +89 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] [C:\Users\user\AppData\Local\flutter\] git rev-parse --abbrev-ref HEAD
[  +41 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] [C:\Users\user\AppData\Local\flutter\] git ls-remote --get-url origin
[  +39 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [C:\Users\user\AppData\Local\flutter\] git log -n 1 --pretty=format:%H
[  +49 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] c7ea3ca377e909469c68f2ab878a5bc53d3cf66b
[        ] [C:\Users\user\AppData\Local\flutter\] git log -n 1 --pretty=format:%ar
[  +45 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 8 weeks ago
[   +1 ms] [C:\Users\user\AppData\Local\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +46 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.5.1-0-gc7ea3ca37
[ +344 ms] C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb devices -l
[  +31 ms] Exit code 0 from: C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb devices -l
[        ] List of devices attached
           10869c2b               device product:OnePlus6 model:ONEPLUS_A6003 device:OnePlus6 transport_id:1
[ +260 ms] C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb -s 10869c2b shell getprop
[ +132 ms] ro.hardware = qcom
[ +885 ms] Launching lib/main.dart on ONEPLUS A6003 in debug mode...
[  +11 ms] Initializing gradle...
[   +1 ms] Using gradle from C:\Users\user\AndroidStudioProjects\testing\android\gradlew.bat.
[ +119 ms] C:\Users\user\AndroidStudioProjects\testing\android\gradlew.bat -v
[ +796 ms]
                   ------------------------------------------------------------
                   Gradle 4.1
                   ------------------------------------------------------------

                   Build time:   2017-08-07 14:38:48 UTC
                   Revision:     941559e020f6c357ebb08d5c67acdb858a3defc2

                   Groovy:       2.4.11
                   Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
                   JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b02)
                   OS:           Windows 10 10.0 amd64
[   +3 ms] Resolving dependencies...
[        ] [android\] C:\Users\user\AndroidStudioProjects\testing\android\gradlew.bat app:properties
[+1762 ms] :app:properties

                   ------------------------------------------------------------
                   Project :app
                   ------------------------------------------------------------

                   allprojects: [project ':app']
                   android: com.android.build.gradle.AppExtension_Decorated@5a0ded40
                   androidDependencies: task ':app:androidDependencies'
                   ant: org.gradle.api.internal.project.DefaultAntBuilder@3edda047
                   antBuilderFactory: org.gradle.api.internal.project.DefaultAntBuilderFactory@22225bbb
                   archivesBaseName: app
                   artifacts: org.gradle.api.internal.artifacts.dsl.DefaultArtifactHandler_Decorated@6f37b750
                   asDynamicObject: DynamicObject for project ':app'
                   assemble: task ':app:assemble'
                   assembleAndroidTest: task ':app:assembleAndroidTest'
                   assembleDebug: task ':app:assembleDebug'
                   assembleDebugAndroidTest: task ':app:assembleDebugAndroidTest'
                   assembleDebugUnitTest: task ':app:assembleDebugUnitTest'
                   assembleProfile: task ':app:assembleProfile'
                   assembleProfileUnitTest: task ':app:assembleProfileUnitTest'
                   assembleRelease: task ':app:assembleRelease'
                   assembleReleaseUnitTest: task ':app:assembleReleaseUnitTest'
                   baseClassLoaderScope: org.gradle.api.internal.initialization.DefaultClassLoaderScope@5ae5301b
                   buildDependents: task ':app:buildDependents'
                   buildDir: C:\Users\user\AndroidStudioProjects\testing\build\app
                   buildFile: C:\Users\user\AndroidStudioProjects\testing\android\app\build.gradle
                   buildNeeded: task ':app:buildNeeded'
                   buildOutputs: BaseVariantOutput container
                   buildScriptSource: org.gradle.groovy.scripts.UriScriptSource@9e96c98
                   buildscript: org.gradle.api.internal.initialization.DefaultScriptHandler@3926119d
                   bundleAppClassesDebug: task ':app:bundleAppClassesDebug'
                   bundleAppClassesDebugAndroidTest: task ':app:bundleAppClassesDebugAndroidTest'
                   bundleAppClassesDebugUnitTest: task ':app:bundleAppClassesDebugUnitTest'
                   bundleAppClassesProfile: task ':app:bundleAppClassesProfile'
                   bundleAppClassesProfileUnitTest: task ':app:bundleAppClassesProfileUnitTest'
                   bundleAppClassesRelease: task ':app:bundleAppClassesRelease'
                   bundleAppClassesReleaseUnitTest: task ':app:bundleAppClassesReleaseUnitTest'
                   check: task ':app:check'
                   checkDebugManifest: task ':app:checkDebugManifest'
                   checkProfileManifest: task ':app:checkProfileManifest'
                   checkReleaseManifest: task ':app:checkReleaseManifest'
                   childProjects: {}
                   class: class org.gradle.api.internal.project.DefaultProject_Decorated
                   classLoaderScope: org.gradle.api.internal.initialization.DefaultClassLoaderScope@6b79acde
                   cleanBuildCache: task ':app:cleanBuildCache'
                   compileDebugAidl: task ':app:compileDebugAidl'
                   compileDebugAndroidTestAidl: task ':app:compileDebugAndroidTestAidl'
                   compileDebugAndroidTestJavaWithJavac: task ':app:compileDebugAndroidTestJavaWithJavac'
                   compileDebugAndroidTestNdk: task ':app:compileDebugAndroidTestNdk'
                   compileDebugAndroidTestRenderscript: task ':app:compileDebugAndroidTestRenderscript'
                   compileDebugAndroidTestShaders: task ':app:compileDebugAndroidTestShaders'
                   compileDebugAndroidTestSources: task ':app:compileDebugAndroidTestSources'
                   compileDebugJavaWithJavac: task ':app:compileDebugJavaWithJavac'
                   compileDebugNdk: task ':app:compileDebugNdk'
                   compileDebugRenderscript: task ':app:compileDebugRenderscript'
                   compileDebugShaders: task ':app:compileDebugShaders'
                   compileDebugSources: task ':app:compileDebugSources'
                   compileDebugUnitTestJavaWithJavac: task ':app:compileDebugUnitTestJavaWithJavac'
                   compileDebugUnitTestSources: task ':app:compileDebugUnitTestSources'
                   compileLint: task ':app:compileLint'
                   compileProfileAidl: task ':app:compileProfileAidl'
                   compileProfileJavaWithJavac: task ':app:compileProfileJavaWithJavac'
                   compileProfileNdk: task ':app:compileProfileNdk'
                   compileProfileRenderscript: task ':app:compileProfileRenderscript'
                   compileProfileShaders: task ':app:compileProfileShaders'
                   compileProfileSources: task ':app:compileProfileSources'
                   compileProfileUnitTestJavaWithJavac: task ':app:compileProfileUnitTestJavaWithJavac'
                   compileProfileUnitTestSources: task ':app:compileProfileUnitTestSources'
                   compileReleaseAidl: task ':app:compileReleaseAidl'
                   compileReleaseJavaWithJavac: task ':app:compileReleaseJavaWithJavac'
                   compileReleaseNdk: task ':app:compileReleaseNdk'
                   compileReleaseRenderscript: task ':app:compileReleaseRenderscript'
                   compileReleaseShaders: task ':app:compileReleaseShaders'
                   compileReleaseSources: task ':app:compileReleaseSources'
                   compileReleaseUnitTestJavaWithJavac: task ':app:compileReleaseUnitTestJavaWithJavac'
                   compileReleaseUnitTestSources: task ':app:compileReleaseUnitTestSources'
                   components: SoftwareComponentInternal set
                   configurationActions: org.gradle.configuration.project.DefaultProjectConfigurationActionContainer@18ef3c42
                   configurationTargetIdentifier: org.gradle.configuration.ConfigurationTargetIdentifier$1@5a201e6b
                   configurations: configuration container
                   connectedAndroidTest: task ':app:connectedAndroidTest'
                   connectedCheck: task ':app:connectedCheck'
                   connectedDebugAndroidTest: task ':app:connectedDebugAndroidTest'
                   consumeConfigAttr: task ':app:consumeConfigAttr'
                   convention: org.gradle.api.internal.plugins.DefaultConvention@5383464b
                   copyFlutterAssetsDebug: task ':app:copyFlutterAssetsDebug'
                   copyFlutterAssetsProfile: task ':app:copyFlutterAssetsProfile'
                   copyFlutterAssetsRelease: task ':app:copyFlutterAssetsRelease'
                   createDebugCompatibleScreenManifests: task ':app:createDebugCompatibleScreenManifests'
                   createProfileCompatibleScreenManifests: task ':app:createProfileCompatibleScreenManifests'
                   createReleaseCompatibleScreenManifests: task ':app:createReleaseCompatibleScreenManifests'
                   defaultArtifacts: org.gradle.api.internal.plugins.DefaultArtifactPublicationSet_Decorated@75ba0fb9
                   defaultTasks: []
                   deferredProjectConfiguration: org.gradle.api.internal.project.DeferredProjectConfiguration@14d62060
                   dependencies: org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@4e5fb7d7
                   depth: 1
                   description: null
                   deviceAndroidTest: task ':app:deviceAndroidTest'
                   deviceCheck: task ':app:deviceCheck'
                   displayName: project ':app'
                   distsDir: C:\Users\user\AndroidStudioProjects\testing\build\app\distributions
                   distsDirName: distributions
                   docsDir: C:\Users\user\AndroidStudioProjects\testing\build\app\docs
                   docsDirName: docs
                   ext: org.gradle.api.internal.plugins.DefaultExtraPropertiesExtension@7a71149
                   extensions: org.gradle.api.internal.plugins.DefaultConvention@5383464b
                   extractProguardFiles: task ':app:extractProguardFiles'
                   fileOperations: org.gradle.api.internal.file.DefaultFileOperations@22c511c3
                   fileResolver: org.gradle.api.internal.file.BaseDirFileResolver@7b5f0db
                   flutter: FlutterExtension_Decorated@34e71ef5
                   flutterBuildDebug: task ':app:flutterBuildDebug'
                   flutterBuildProfile: task ':app:flutterBuildProfile'
                   flutterBuildRelease: task ':app:flutterBuildRelease'
                   flutterBuildX86Jar: task ':app:flutterBuildX86Jar'
                   generateDebugAndroidTestAssets: task ':app:generateDebugAndroidTestAssets'
                   generateDebugAndroidTestBuildConfig: task ':app:generateDebugAndroidTestBuildConfig'
                   generateDebugAndroidTestResValues: task ':app:generateDebugAndroidTestResValues'
                   generateDebugAndroidTestResources: task ':app:generateDebugAndroidTestResources'
                   generateDebugAndroidTestSources: task ':app:generateDebugAndroidTestSources'
                   generateDebugAssets: task ':app:generateDebugAssets'
                   generateDebugBuildConfig: task ':app:generateDebugBuildConfig'
                   generateDebugResValues: task ':app:generateDebugResValues'
                   generateDebugResources: task ':app:generateDebugResources'
                   generateDebugSources: task ':app:generateDebugSources'
                   generateProfileAssets: task ':app:generateProfileAssets'
                   generateProfileBuildConfig: task ':app:generateProfileBuildConfig'
                   generateProfileResValues: task ':app:generateProfileResValues'
                   generateProfileResources: task ':app:generateProfileResources'
                   generateProfileSources: task ':app:generateProfileSources'
                   generateReleaseAssets: task ':app:generateReleaseAssets'
                   generateReleaseBuildConfig: task ':app:generateReleaseBuildConfig'
                   generateReleaseResValues: task ':app:generateReleaseResValues'
                   generateReleaseResources: task ':app:generateReleaseResources'
                   generateReleaseSources: task ':app:generateReleaseSources'
                   gradle: build 'android'
                   group: android
                   identityPath: :app
                   inheritedScope: org.gradle.api.internal.ExtensibleDynamicObject$InheritedDynamicObject@bf57c79
                   installDebug: task ':app:installDebug'
                   installDebugAndroidTest: task ':app:installDebugAndroidTest'
                   installProfile: task ':app:installProfile'
                   installRelease: task ':app:installRelease'
                   javaPreCompileDebug: task ':app:javaPreCompileDebug'
                   javaPreCompileDebugAndroidTest: task ':app:javaPreCompileDebugAndroidTest'
                   javaPreCompileDebugUnitTest: task ':app:javaPreCompileDebugUnitTest'
                   javaPreCompileProfile: task ':app:javaPreCompileProfile'
                   javaPreCompileProfileUnitTest: task ':app:javaPreCompileProfileUnitTest'
                   javaPreCompileRelease: task ':app:javaPreCompileRelease'
                   javaPreCompileReleaseUnitTest: task ':app:javaPreCompileReleaseUnitTest'
                   layout: org.gradle.api.internal.file.DefaultProjectLayout@1342fcd
                   libsDir: C:\Users\user\AndroidStudioProjects\testing\build\app\libs
                   libsDirName: libs
                   lint: task ':app:lint'
                   lintDebug: task ':app:lintDebug'
                   lintProfile: task ':app:lintProfile'
                   lintRelease: task ':app:lintRelease'
                   lintVitalRelease: task ':app:lintVitalRelease'
                   logger: org.gradle.internal.logging.slf4j.OutputEventListenerBackedLogger@354b031e
                   logging: org.gradle.internal.logging.services.DefaultLoggingManager@29af3418
                   mergeDebugAndroidTestAssets: task ':app:mergeDebugAndroidTestAssets'
                   mergeDebugAndroidTestJniLibFolders: task ':app:mergeDebugAndroidTestJniLibFolders'
                   mergeDebugAndroidTestResources: task ':app:mergeDebugAndroidTestResources'
                   mergeDebugAndroidTestShaders: task ':app:mergeDebugAndroidTestShaders'
                   mergeDebugAssets: task ':app:mergeDebugAssets'
                   mergeDebugJniLibFolders: task ':app:mergeDebugJniLibFolders'
                   mergeDebugResources: task ':app:mergeDebugResources'
                   mergeDebugShaders: task ':app:mergeDebugShaders'
                   mergeProfileAssets: task ':app:mergeProfileAssets'
                   mergeProfileJniLibFolders: task ':app:mergeProfileJniLibFolders'
                   mergeProfileResources: task ':app:mergeProfileResources'
                   mergeProfileShaders: task ':app:mergeProfileShaders'
                   mergeReleaseAssets: task ':app:mergeReleaseAssets'
                   mergeReleaseJniLibFolders: task ':app:mergeReleaseJniLibFolders'
                   mergeReleaseResources: task ':app:mergeReleaseResources'
                   mergeReleaseShaders: task ':app:mergeReleaseShaders'
                   mockableAndroidJar: task ':app:mockableAndroidJar'
                   modelRegistry: org.gradle.model.internal.registry.DefaultModelRegistry@2533876e
                   modelSchemaStore: org.gradle.model.internal.manage.schema.extract.DefaultModelSchemaStore@608eb98e
                   module: org.gradle.api.internal.artifacts.ProjectBackedModule@23bdb718
                   name: app
                   normalization: org.gradle.normalization.internal.DefaultInputNormalizationHandler_Decorated@5052105
                   objects: org.gradle.api.internal.model.DefaultObjectFactory@53b073c8
                   org.gradle.jvmargs: -Xmx1536M
                   packageDebug: task ':app:packageDebug'
                   packageDebugAndroidTest: task ':app:packageDebugAndroidTest'
                   packageProfile: task ':app:packageProfile'
                   packageRelease: task ':app:packageRelease'
                   parent: root project 'android'
                   parentIdentifier: root project 'android'
                   path: :app
                   platformAttrExtractor: task ':app:platformAttrExtractor'
                   pluginManager: org.gradle.api.internal.plugins.DefaultPluginManager_Decorated@25ef2c2f
                   plugins: [org.gradle.api.plugins.HelpTasksPlugin@3cfb94f9, com.android.build.gradle.api.AndroidBasePlugin@17b85c51, org.gradle.language.base.plugins.LifecycleBasePlugin@1b762c89, org.gradle.api.plugins.BasePlugin@28b83068, org.gradle.api.plug
ins.ReportingBasePlugin@29d88cf0, org.gradle.platform.base.plugins.ComponentBasePlugin@232d7cff, org.gradle.language.base.plugins.LanguageBasePlugin@4effcb66, org.gradle.platform.base.plugins.BinaryBasePlugin@27fd2fda, org.gradle.api.plugins.JavaBasePlugin@16c4
7cfe, com.android.build.gradle.internal.coverage.JacocoPlugin@60add1d7, com.android.build.gradle.AppPlugin@7095ef2d, FlutterPlugin@37383538]
                   preBuild: task ':app:preBuild'
                   preDebugAndroidTestBuild: task ':app:preDebugAndroidTestBuild'
                   preDebugBuild: task ':app:preDebugBuild'
                   preDebugUnitTestBuild: task ':app:preDebugUnitTestBuild'
                   preProfileBuild: task ':app:preProfileBuild'
                   preProfileUnitTestBuild: task ':app:preProfileUnitTestBuild'
                   preReleaseBuild: task ':app:preReleaseBuild'
                   preReleaseUnitTestBuild: task ':app:preReleaseUnitTestBuild'
                   prepareLintJar: task ':app:prepareLintJar'
                   processDebugAndroidTestJavaRes: task ':app:processDebugAndroidTestJavaRes'
                   processDebugAndroidTestManifest: task ':app:processDebugAndroidTestManifest'
                   processDebugAndroidTestResources: task ':app:processDebugAndroidTestResources'
                   processDebugJavaRes: task ':app:processDebugJavaRes'
                   processDebugManifest: task ':app:processDebugManifest'
                   processDebugResources: task ':app:processDebugResources'
                   processDebugUnitTestJavaRes: task ':app:processDebugUnitTestJavaRes'
                   processOperations: org.gradle.api.internal.file.DefaultFileOperations@22c511c3
                   processProfileJavaRes: task ':app:processProfileJavaRes'
                   processProfileManifest: task ':app:processProfileManifest'
                   processProfileResources: task ':app:processProfileResources'
                   processProfileUnitTestJavaRes: task ':app:processProfileUnitTestJavaRes'
                   processReleaseJavaRes: task ':app:processReleaseJavaRes'
                   processReleaseManifest: task ':app:processReleaseManifest'
                   processReleaseResources: task ':app:processReleaseResources'
                   processReleaseUnitTestJavaRes: task ':app:processReleaseUnitTestJavaRes'
                   project: project ':app'
                   projectConfigurator: org.gradle.api.internal.project.BuildOperationCrossProjectConfigurator@7530c37e
                   projectDir: C:\Users\user\AndroidStudioProjects\testing\android\app
                   projectEvaluationBroadcaster: ProjectEvaluationListener broadcast
                   projectEvaluator: org.gradle.configuration.project.LifecycleProjectEvaluator@4c813241
                   projectPath: :app
                   projectRegistry: org.gradle.api.internal.project.DefaultProjectRegistry@60a02fdd
                   properties: {...}
                   providers: org.gradle.api.internal.provider.DefaultProviderFactory@1b9ddaa4
                   reporting: org.gradle.api.reporting.ReportingExtension_Decorated@3cf2e9b2
                   reportsDir: C:\Users\user\AndroidStudioProjects\testing\build\app\reports
                   repositories: repository container
                   resolveConfigAttr: task ':app:resolveConfigAttr'
                   resources: org.gradle.api.internal.resources.DefaultResourceHandler@4f2af661
                   rootDir: C:\Users\user\AndroidStudioProjects\testing\android
                   rootProject: root project 'android'
                   scriptHandlerFactory: org.gradle.api.internal.initialization.DefaultScriptHandlerFactory@afcc6ff
                   scriptPluginFactory: org.gradle.configuration.ScriptPluginFactorySelector@6bc3deba
                   serviceRegistryFactory: org.gradle.internal.service.scopes.ProjectScopeServices$4@40d70509
                   services: ProjectScopeServices
                   signingReport: task ':app:signingReport'
                   sourceCompatibility: 1.8
                   sourceSets: SourceSet container
                   splitsDiscoveryTaskDebug: task ':app:splitsDiscoveryTaskDebug'
                   splitsDiscoveryTaskDebugAndroidTest: task ':app:splitsDiscoveryTaskDebugAndroidTest'
                   splitsDiscoveryTaskProfile: task ':app:splitsDiscoveryTaskProfile'
                   splitsDiscoveryTaskRelease: task ':app:splitsDiscoveryTaskRelease'
                   standardOutputCapture: org.gradle.internal.logging.services.DefaultLoggingManager@29af3418
                   state: project state 'EXECUTED'
                   status: integration
                   subprojects: []
                   targetCompatibility: 1.8
                   tasks: task set
                   test: task ':app:test'
                   testDebugUnitTest: task ':app:testDebugUnitTest'
                   testProfileUnitTest: task ':app:testProfileUnitTest'
                   testReleaseUnitTest: task ':app:testReleaseUnitTest'
                   testReportDir: C:\Users\user\AndroidStudioProjects\testing\build\app\reports\tests
                   testReportDirName: tests
                   testResultsDir: C:\Users\user\AndroidStudioProjects\testing\build\app\test-results
                   testResultsDirName: test-results
                   transformClassesWithDexBuilderForDebug: task ':app:transformClassesWithDexBuilderForDebug'
                   transformClassesWithDexBuilderForDebugAndroidTest: task ':app:transformClassesWithDexBuilderForDebugAndroidTest'
                   transformClassesWithDexBuilderForProfile: task ':app:transformClassesWithDexBuilderForProfile'
                   transformClassesWithPreDexForRelease: task ':app:transformClassesWithPreDexForRelease'
                   transformDexArchiveWithDexMergerForDebug: task ':app:transformDexArchiveWithDexMergerForDebug'
                   transformDexArchiveWithDexMergerForDebugAndroidTest: task ':app:transformDexArchiveWithDexMergerForDebugAndroidTest'
                   transformDexArchiveWithDexMergerForProfile: task ':app:transformDexArchiveWithDexMergerForProfile'
                   transformDexArchiveWithExternalLibsDexMergerForDebug: task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'
                   transformDexArchiveWithExternalLibsDexMergerForDebugAndroidTest: task ':app:transformDexArchiveWithExternalLibsDexMergerForDebugAndroidTest'
                   transformDexArchiveWithExternalLibsDexMergerForProfile: task ':app:transformDexArchiveWithExternalLibsDexMergerForProfile'
                   transformDexWithDexForRelease: task ':app:transformDexWithDexForRelease'
                   transformNativeLibsWithMergeJniLibsForDebug: task ':app:transformNativeLibsWithMergeJniLibsForDebug'
                   transformNativeLibsWithMergeJniLibsForDebugAndroidTest: task ':app:transformNativeLibsWithMergeJniLibsForDebugAndroidTest'
                   transformNativeLibsWithMergeJniLibsForProfile: task ':app:transformNativeLibsWithMergeJniLibsForProfile'
                   transformNativeLibsWithMergeJniLibsForRelease: task ':app:transformNativeLibsWithMergeJniLibsForRelease'
                   transformResourcesWithMergeJavaResForDebug: task ':app:transformResourcesWithMergeJavaResForDebug'
                   transformResourcesWithMergeJavaResForDebugAndroidTest: task ':app:transformResourcesWithMergeJavaResForDebugAndroidTest'
                   transformResourcesWithMergeJavaResForDebugUnitTest: task ':app:transformResourcesWithMergeJavaResForDebugUnitTest'
                   transformResourcesWithMergeJavaResForProfile: task ':app:transformResourcesWithMergeJavaResForProfile'
                   transformResourcesWithMergeJavaResForProfileUnitTest: task ':app:transformResourcesWithMergeJavaResForProfileUnitTest'
                   transformResourcesWithMergeJavaResForRelease: task ':app:transformResourcesWithMergeJavaResForRelease'
                   transformResourcesWithMergeJavaResForReleaseUnitTest: task ':app:transformResourcesWithMergeJavaResForReleaseUnitTest'
                   uninstallAll: task ':app:uninstallAll'
                   uninstallDebug: task ':app:uninstallDebug'
                   uninstallDebugAndroidTest: task ':app:uninstallDebugAndroidTest'
                   uninstallProfile: task ':app:uninstallProfile'
                   uninstallRelease: task ':app:uninstallRelease'
                   validateSigningDebug: task ':app:validateSigningDebug'
                   validateSigningDebugAndroidTest: task ':app:validateSigningDebugAndroidTest'
                   validateSigningProfile: task ':app:validateSigningProfile'
                   validateSigningRelease: task ':app:validateSigningRelease'
                   version: unspecified
                   writeDebugApplicationId: task ':app:writeDebugApplicationId'
                   writeProfileApplicationId: task ':app:writeProfileApplicationId'
                   writeReleaseApplicationId: task ':app:writeReleaseApplicationId'

                   BUILD SUCCESSFUL in 1s
                   1 actionable task: 1 executed
[  +24 ms] C:\Users\user\AppData\Local\Android\sdk\build-tools\28.0.1\aapt dump badging build\app\outputs\apk\app.apk
[  +31 ms] Exit code 0 from: C:\Users\user\AppData\Local\Android\sdk\build-tools\28.0.1\aapt dump badging build\app\outputs\apk\app.apk
[   +1 ms] package: name='com.example.testing' versionCode='1' versionName='1.0'
           sdkVersion:'16'
           targetSdkVersion:'27'
           uses-permission: name='android.permission.INTERNET'
           application-label:'testing'
           application-icon-160:'res/mipmap-mdpi-v4/ic_launcher.png'
           application-icon-240:'res/mipmap-hdpi-v4/ic_launcher.png'
           application-icon-320:'res/mipmap-xhdpi-v4/ic_launcher.png'
           application-icon-480:'res/mipmap-xxhdpi-v4/ic_launcher.png'
           application-icon-640:'res/mipmap-xxxhdpi-v4/ic_launcher.png'
           application: label='testing' icon='res/mipmap-mdpi-v4/ic_launcher.png'
           application-debuggable
           launchable-activity: name='com.example.testing.MainActivity'  label='' icon=''
           feature-group: label=''
             uses-feature: name='android.hardware.faketouch'
             uses-implied-feature: name='android.hardware.faketouch' reason='default feature for all apps'
           main
           supports-screens: 'small' 'normal' 'large' 'xlarge'
           supports-any-density: 'true'
           locales: '--_--'
           densities: '160' '240' '320' '480' '640'
           native-code: 'arm64-v8a' 'x86' 'x86_64'
[  +13 ms] C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb -s 10869c2b logcat -v time -t 1
[ +172 ms] Exit code 0 from: C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb -s 10869c2b logcat -v time -t 1
[        ] --------- beginning of main
           07-26 12:18:38.505 E/DisplayDevice(  829): map unknown ((deprecated) sRGB sRGB Full range)/(RenderIntent::COLORIMETRIC) to default color mode
[   +5 ms] C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb -s 10869c2b logcat -v time
[ +515 ms] DependencyChecker: nothing is modified after 2018-07-26 12:15:08.000.
[   +9 ms] C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb version
[  +30 ms] Android Debug Bridge version 1.0.40
           Version 4797878
           Installed as C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb.EXE
[   +4 ms] C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb start-server
[  +25 ms] Building APK
[  +10 ms] Running 'gradlew assembleDebug'...
[   +3 ms] [android\] C:\Users\user\AndroidStudioProjects\testing\android\gradlew.bat -Ptarget=C:\Users\user\AndroidStudioProjects\testing\lib/main.dart -Ppreview-dart-2=true -Ptarget-platform=android-arm64 assembleDebug
[+1750 ms] :app:preBuild UP-TO-DATE
[  +16 ms] :app:preDebugBuild UP-TO-DATE
[  +10 ms] :app:compileDebugAidl UP-TO-DATE
[   +9 ms] :app:compileDebugRenderscript UP-TO-DATE
[        ] :app:flutterBuildX86Jar UP-TO-DATE
[   +9 ms] :app:checkDebugManifest UP-TO-DATE
[        ] :app:generateDebugBuildConfig UP-TO-DATE
[        ] :app:prepareLintJar UP-TO-DATE
[  +88 ms] :app:cleanMergeDebugAssets
[+8801 ms] :app:flutterBuildDebug
[   +1 ms] :app:mergeDebugShaders UP-TO-DATE
[   +8 ms] :app:compileDebugShaders UP-TO-DATE
[        ] :app:generateDebugAssets UP-TO-DATE
[   +9 ms] :app:mergeDebugAssets
[ +291 ms] :app:copyFlutterAssetsDebug
[        ] :app:generateDebugResValues UP-TO-DATE
[   +8 ms] :app:generateDebugResources UP-TO-DATE
[  +10 ms] :app:mergeDebugResources UP-TO-DATE
[        ] :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] :app:processDebugManifest UP-TO-DATE
[        ] :app:splitsDiscoveryTaskDebug UP-TO-DATE
[   +8 ms] :app:processDebugResources UP-TO-DATE
[        ] :app:generateDebugSources UP-TO-DATE
[        ] :app:javaPreCompileDebug UP-TO-DATE
[  +19 ms] :app:compileDebugJavaWithJavac UP-TO-DATE
[   +1 ms] :app:compileDebugNdk NO-SOURCE
[        ] :app:compileDebugSources UP-TO-DATE
[   +9 ms] :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[        ] :app:transformDexArchiveWithExternalLibsDexMergerForDebug UP-TO-DATE
[   +9 ms] :app:transformDexArchiveWithDexMergerForDebug UP-TO-DATE
[        ] :app:mergeDebugJniLibFolders UP-TO-DATE
[   +9 ms] :app:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
[        ] :app:processDebugJavaRes NO-SOURCE
[   +9 ms] :app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
[        ] :app:validateSigningDebug
[   +9 ms] :app:packageDebug UP-TO-DATE
[        ] :app:assembleDebug UP-TO-DATE
[        ] BUILD SUCCESSFUL in 10s
[        ] 29 actionable tasks: 5 executed, 24 up-to-date
[ +430 ms] calculateSha: C:\Users\user\AndroidStudioProjects\testing\build\app\outputs\apk/app.apk
[ +649 ms] Built build\app\outputs\apk\debug\app-debug.apk.
[   +2 ms] C:\Users\user\AppData\Local\Android\sdk\build-tools\28.0.1\aapt dump badging build\app\outputs\apk\app.apk
[  +14 ms] Exit code 0 from: C:\Users\user\AppData\Local\Android\sdk\build-tools\28.0.1\aapt dump badging build\app\outputs\apk\app.apk
[        ] package: name='com.example.testing' versionCode='1' versionName='1.0'
           sdkVersion:'16'
           targetSdkVersion:'27'
           uses-permission: name='android.permission.INTERNET'
           application-label:'testing'
           application-icon-160:'res/mipmap-mdpi-v4/ic_launcher.png'
           application-icon-240:'res/mipmap-hdpi-v4/ic_launcher.png'
           application-icon-320:'res/mipmap-xhdpi-v4/ic_launcher.png'
           application-icon-480:'res/mipmap-xxhdpi-v4/ic_launcher.png'
           application-icon-640:'res/mipmap-xxxhdpi-v4/ic_launcher.png'
           application: label='testing' icon='res/mipmap-mdpi-v4/ic_launcher.png'
           application-debuggable
           launchable-activity: name='com.example.testing.MainActivity'  label='' icon=''
           feature-group: label=''
             uses-feature: name='android.hardware.faketouch'
             uses-implied-feature: name='android.hardware.faketouch' reason='default feature for all apps'
           main
           supports-screens: 'small' 'normal' 'large' 'xlarge'
           supports-any-density: 'true'
           locales: '--_--'
           densities: '160' '240' '320' '480' '640'
           native-code: 'arm64-v8a' 'x86' 'x86_64'
[   +1 ms] Stopping app 'app.apk' on ONEPLUS A6003.
[        ] C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb -s 10869c2b shell am force-stop com.example.testing
[ +201 ms] C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb -s 10869c2b shell pm list packages com.example.testing
[  +99 ms] package:com.example.testing
[   +3 ms] C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb -s 10869c2b shell cat /data/local/tmp/sky.com.example.testing.sha1
[  +80 ms] 3ee5929b49b77c2f42e31681b1ffafb0018030fa
[   +1 ms] Latest build already installed.
[        ] ONEPLUS A6003 startApp
[   +2 ms] C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb -s 10869c2b shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true com.example.test
ing/com.example.testing.MainActivity
[ +183 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.testing/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +239 ms] I/FlutterActivityDelegate( 9721): onResume setting current activity to this
[  +61 ms] Observatory URL on device: http://127.0.0.1:38951/
[  +30 ms] C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb -s 10869c2b forward tcp:8103 tcp:38951
[  +31 ms] Forwarded host port 8103 to device port 38951 for Observatory
[   +8 ms] Connecting to service protocol: http://127.0.0.1:8103/
[ +230 ms] Successfully connected to service protocol: http://127.0.0.1:8103/
[   +5 ms] getVM: {}
[  +31 ms] getIsolate: {isolateId: isolates/1053151734}
[   +5 ms] _flutter.listViews: {isolateId: isolates/1053151734}
[  +77 ms] DevFS: Creating new filesystem on the device (null)
[   +2 ms] _createDevFS: {fsName: testing}
[  +27 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.testing/cache/testingGDQTAX/testing/)
[   +3 ms] Updating assets
[ +274 ms] Syncing files to device ONEPLUS A6003...
[   +5 ms] DevFS: Starting sync from LocalDirectory: 'C:\Users\user\AndroidStudioProjects\testing'
[        ] Scanning project files
[   +4 ms] Scanning package files
[  +99 ms] Scanning asset files
[   +2 ms] Scanning for deleted files
[  +54 ms] Compiling dart to kernel with 416 updated files
[   +4 ms] C:\Users\user\AppData\Local\flutter\bin\cache\dart-sdk\bin\dart C:\Users\user\AppData\Local\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\Users\user\AppData\Local\flutter\bin\cache\artifacts\engin
e\common\flutter_patched_sdk/ --incremental --strong --target=flutter --output-dill build\app.dill --packages C:\Users\user\AndroidStudioProjects\testing\.packages --filesystem-scheme org-dartlang-root
[   +2 ms] W/1.gpu   ( 9721): type=1400 audit(0.0:224805): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=16664 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
[        ] E/libc    ( 9721): Access denied finding property "vendor.debug.egl.swapinterval"
[   +4 ms] E/libc    ( 9721): Access denied finding property "vendor.debug.egl.swapinterval"
[        ] W/RenderThread( 9721): type=1400 audit(0.0:224806): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=16664 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
[        ] W/RenderThread( 9721): type=1400 audit(0.0:224807): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=16664 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
[        ] E/libc    ( 9721): Access denied finding property "vendor.debug.egl.swapinterval"
[        ] E/libc    ( 9721): Access denied finding property "vendor.debug.egl.swapinterval"
[        ] W/RenderThread( 9721): type=1400 audit(0.0:224808): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=16664 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
[        ] E/libc    ( 9721): Access denied finding property "vendor.debug.egl.swapinterval"
[        ] E/libc    ( 9721): Access denied finding property "vendor.debug.egl.swapinterval"
[        ] E/libc    ( 9721): Access denied finding property "vendor.debug.egl.swapinterval"
[        ] E/libc    ( 9721): Access denied finding property "vendor.debug.egl.swapinterval"
[        ] E/libc    ( 9721): Access denied finding property "vendor.debug.egl.swapinterval"
[        ] E/libc    ( 9721): Access denied finding property "vendor.debug.egl.swapinterval"
[        ] E/libc    ( 9721): Access denied finding property "vendor.debug.egl.swapinterval"
[   +6 ms] E/libc    ( 9721): Access denied finding property "vendor.debug.egl.swapinterval"
[  +12 ms] E/libc    ( 9721): Access denied finding property "vendor.debug.egl.swapinterval"
[  +19 ms] E/libc    ( 9721): Access denied finding property "vendor.debug.egl.swapinterval"
[  +15 ms] E/libc    ( 9721): Access denied finding property "vendor.debug.egl.swapinterval"
[  +16 ms] E/libc    ( 9721): Access denied finding property "vendor.debug.egl.swapinterval"
[  +17 ms] E/libc    ( 9721): Access denied finding property "vendor.debug.egl.swapinterval"
[  +15 ms] E/libc    ( 9721): Access denied finding property "vendor.debug.egl.swapinterval"
[  +18 ms] E/libc    ( 9721): Access denied finding property "vendor.debug.egl.swapinterval"
[  +14 ms] E/libc    ( 9721): Access denied finding property "vendor.debug.egl.swapinterval"
[  +25 ms] E/libc    ( 9721): Access denied finding property "vendor.debug.egl.swapinterval"
[+4189 ms] Updating files
[ +592 ms] DevFS: Sync finished
[   +1 ms] Synced 0.8MB.
[   +2 ms] _flutter.listViews: {isolateId: isolates/1053151734}
[  +11 ms] Connected to _flutterView/0x7dc42eec98.
[   +1 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +1 ms] An Observatory debugger and profiler on ONEPLUS A6003 is available at: http://127.0.0.1:8103/
[        ] For a more detailed help message, press "h". To quit, press "q".

```

```
Analyzing testing...
No issues found! (ran in 2.4s)
```

```#[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.16299.547], locale de-DE)
    • Flutter version 0.5.1 at C:\Users\user\AppData\Local\flutter
    • Framework revision c7ea3ca377 (8 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[√] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected devices (1 available)
    • ONEPLUS A6003 • 10869c2b • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by BruceZhang1993** [comment]
OnePlus A6000 Android P DP3 same here. Debug and hot reload ok, running release apk force stop.

**Comment by itayganor** [comment]
Oneplus 6, A6003, Official Pie release. 

Every second, more and more errors appear, usually these ones:
```
E/libc    ( 7332): Access denied finding property "vendor.debug.egl.swapinterval"
W/RenderThread( 7332): type=1400 audit(0.0:400608): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=16621 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
E/libc    ( 7332): Access denied finding property "vendor.debug.egl.swapinterval"
W/RenderThread( 7332): type=1400 audit(0.0:400609): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=16621 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
```

**Comment by itayganor** [comment]
In addition, hot reload fails:

```
Hot reload failed: Bad state: No element
#0      List.first (dart:core/runtime/libarray.dart:167:5)
#1      HotRunner._reloadSources.<anonymous closure> (package:flutter_tools/src/run_hot.dart:592:63)
#2      _rootRunUnary (dart:async/zone.dart:1132:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#7      Future._completeWithValue (dart:async/future_impl.dart:486:5)
#8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#14     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#15     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by davide-esr** [comment]
> Oneplus 6, A6003, Official Pie release.
> 
> While a TextField is focused, every second, more and more errors appear, usually these ones:
> 
> ```
> E/libc    ( 7332): Access denied finding property "vendor.debug.egl.swapinterval"
> W/RenderThread( 7332): type=1400 audit(0.0:400608): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=16621 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
> E/libc    ( 7332): Access denied finding property "vendor.debug.egl.swapinterval"
> W/RenderThread( 7332): type=1400 audit(0.0:400609): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=16621 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
> ```

I don't use Flutter but I somehow ended up here with the same issue with Pie and OP6. So I just wanted to tell you that it's probably not a Flutter issue

**Comment by hatched-MaciejPrzybylski** [comment]
on my side it happens when google map is displayed, I'm not using flutter

**Comment by darkmarthur** [comment]
Same here!

E/libc    ( 8029): Access denied finding property "vendor.debug.egl.swapinterval"

OnePlus 6 Android 9

**Comment by JulianBerger** [comment]
Same issue on OnePlus 6 and Android 9 final.

**Comment by pintuag** [comment]
E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
E/libc: Access denied finding property "vendor.debug.egl.swapinterval"


I'm getting this error too in oneplus 6 and I'm not using flutter

**Comment by mdanics** [comment]
So any solution?

**Comment by BruceZhang1993** [comment]
@Kegulf  Actually this issue will not cause op6 crash flutter apps, you can use --software-renderer to remove these errors.

**Comment by Kegulf** [comment]
I can't say that I understand what that means :p

I should probably mention that it was working until we implemented firebase support. (I think)

**Comment by tiholic** [comment]
Same issue One Plus 6 OxygenOS 9.0
In urgent need for this fix. Any help to resolve is much appreciated 😃

**Comment by SaqibJDev** [comment]
Any solution so far? :)

**Comment by SaqibJDev** [comment]
I used a workaround till they fix the problem. Highlight part of the line in your logcat

Access denied finding property "vendor.debug.egl.swapinterval"

right click, fold lines like this. You won't see them so much.

**Comment by Kegulf** [comment]
@BruceZhang1993 could you provide a link for usage? 

I assume it's a CMD command. But I'm sort of new to development.

**Comment by Kegulf** [comment]
Oh, I don't use flutter (I think) I've never inputted it anywhere. Using out of the box Android studio

**Comment by oscargrgm** [comment]
Same error here with a OnePlus 6T using an app without Flutter.

**Comment by LightSun** [comment]
same for me . it flush the loggcat all the time. And my device is oneplus 6t.  Any solution ?

**Comment by ConsoleTVs** [comment]
> same for me . it flush the loggcat all the time. And my device is oneplus 6t. Any solution ?

Same here :D

**Comment by ben-j69** [comment]
Same here...

**Comment by MiXT4PE** [comment]
Same here. OnePlus 6T.

It happens in Android Studio, too. Likely an issue of them not flutter

**Comment by jamiegau** [comment]
I got this too, very annoying.  OnePlus6 device.

**Comment by Idan-BM** [comment]
Me too, could it be problematic while using Flare or Nima?

**Comment by idofilus** [comment]
I made a simple python script to hide those messages:

```
import subprocess
import re

# Searching if 'contains'
ignore = [
    '): Access denied finding property "vendor.debug.egl.swapinterval"',
    'pp_27:s0:c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0',
    'g) 1.gpu identical'
]

regexes = [
    'uid=\d+(\w+) 1.gpu identical \d+ lines'
]

def onLine(line):
    line = line.strip().decode("utf-8")

    for text in ignore:
        if text in line:
            return

    for regex in regexes:
        m = re.search(regex, line)
        if m != None:
            return

    print(line)

proc = subprocess.Popen("flutter run", stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
while proc.poll() is None:
    line = proc.stdout.readline()
    onLine(line)
# Might still be data on stdout at this point. Grab any remainder.
for line in proc.stdout.read().split('\n'):
    onLine(line)
```

**Comment by ConsoleTVs** [comment]
it has been fixed in the latest update of the OnePlus 6T at least.

**Comment by ConsoleTVs** [comment]
@MiXT4PE 
![image](https://user-images.githubusercontent.com/6124435/49971839-28092080-ff30-11e8-8ab0-73c034ac0d8d.png)

I see no error, what version do u have?

**Comment by jamiegau** [comment]
This is the version I am using..  Is different..

![screenshot_20181214-101732](https://user-images.githubusercontent.com/3303822/49973543-a7770e00-ff89-11e8-96e2-e17a2a7e0736.jpg)

**Comment by MiXT4PE** [comment]
I also use 9.0.7 and I still have the constant error log problem, @ConsoleTVs

**Comment by marcelmiguel** [comment]
Same error:
Access denied finding property "vendor.debug.egl.swapinterval"

with Android 6 A6000, OxygenOS version 9.0.2

**Comment by mskrip** [comment]
Fixed for me on OxygenOS 9.0.3 (OP6), no log spam at least.

**Comment by jmodrako** [comment]
@mskrip finally! When did you receive an update to 9.0.3?

**Comment by mskrip** [comment]
VPN to Germany and install as OTA  :stuck_out_tongue_winking_eye: (I did it probably a week ago)

**Comment by CarGuo** [comment]
I solved it by upgrading to v1.1.3

**Comment by idofilus** [comment]
I just solved it yesterday. Here is what I did:
1. Download ExpressVPN
2. Sign up for trial
3. Choose Germany
4. Download the update :)

**Comment by Pittvandewitt** [comment]
Looks like an selinux denial. 
magiskpolicy --live "allow { unstrusted_ app untrusted_app_27 } vendor_default_prop file { read }"
or
supolicy --live "allow { unstrusted_ app untrusted_app_27 } vendor_default_prop:file { read }"
should do the job.
If you´re using magisk you can drop that line in a file called post-fs-data.sh and drop it in the root of any magisk module with auto_mount in it.

**Comment by MichaelPriebe** [comment]
Getting this issue on Xiaomi Mi Mix 3

**Comment by theizzer** [comment]
I am having this issue after upgrading Flutter 1.2.1. In addition to this I am getting "vendor.debug.egl.changepixelformat", too.

Device: OnePlus 6T (ONEPLUS A6013)
Build: A6013_41_190123
OxygenOS: 9.0.12

```
I/chatty  ( 2433): uid=10196(com.example.sample) 1.gpu identical 37 lines
E/libc    ( 2433): Access denied finding property "vendor.debug.egl.swapinterval"
W/example.sample( 2433): type=1400 audit(0.0:1432938): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=15849 scontext=u:r:untrusted_app:s0:c196,c256,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
E/libc    ( 2433): Access denied finding property "vendor.debug.egl.changepixelformat"
W/RenderThread( 2433): type=1400 audit(0.0:1432939): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=15849 scontext=u:r:untrusted_app:s0:c196,c256,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
E/libc    ( 2433): Access denied finding property "vendor.debug.egl.swapinterval"
```

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.590], locale cs-CZ)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.31.1)
[√] VS Code, 64-bit edition (version 1.26.1)
[√] Connected device (1 available)

• No issues found!
```

Strange thing is that I am not getting these error on my older project that was generated in Flutter 1.0.0, even if built now with Flutter 1.2.1 (with upgraded pubspec.yaml to reflect newly generated projects - mainly "environment: sdk"). New projects generated now (the sample one) are throwing these errors.

The app is working as far as I can tell. I can make it show the errors just a few times at the start by running the app as "flutter run --enable-software-rendering".

Did something change in the project settings somewhere from Flutter 1.0.0 to Flutter 1.2.1 that this is happening again? Or was it just using software renderer on Flutter 1.0.0?

**Comment by theizzer** [comment]
Okay, my bad I found the difference.

Flutter 1.0.0 projects had compileSdkVersion and targetSdkVersion set to "27" (Oreo 8.1.0) while Flutter 1.2.1 sample projects have these two variables set to "28" (Pie 9).

So, another "workaround" fix could be to lower those two sdkVersion variables to 27 and wait for future fix - maybe from OnePlus (if it is problem on their side).

**Comment by sh0umik** [comment]
I am getting the same message on OnePlus 6T with Flutter 1.3.9 and Its very annoying

**Comment by mathshenry** [comment]
Still no fix for this? I'm getting this on OP 6T on Oxygen 9.0.12.

**Comment by kyl3r92** [comment]
Getting this too, OP6 (6003) with OxygenOS 9.0.4

**Comment by coeneivan** [comment]
Jus tested this on a One plus 6 and on a pixel 2XL and only see this on the one plus...

**Comment by kay4ik** [comment]
I think its an OnePlus problem....

**Comment by kay4ik** [comment]
But this warning does not impact the app, just destroys my Debug Console. Is there any way to ignore this Error on the Debug Console?

**Comment by coeneivan** [comment]
> I think its an OnePlus problem....

I din't have this with my OnePlus one and then I had no issues? Only on the 6...

**Comment by Uncle-X** [comment]
flutter_app/android/app/src/build.gradle   compileSdkVersion change to 28(default=27),targetSdkVersion change to 28(default=27)

**Comment by leonardus** [comment]
I've tried with targetSdkVersion/compileSdkVersion set to 27, and set to 28, and neither seems to have fixed the issue.

- Android Studio 3.3
- Flutter 1.2.1
- OxygenOS Beta 15

**Comment by robintschroeder** [comment]
I have the same problem. OnePlus 6T, Android Pi, Xamarin.Forms. On PullToRefresh gesture in debug mode.

**Comment by loolooii** [comment]
I'm getting this also on Pixel 3

**Comment by pratik037** [comment]
Any solution yet?

**Comment by rajatpundir** [comment]
This has been reported on OnePlus forums but there has been no fixes as of today.

**Comment by Gallactide** [comment]
> This has been reported on OnePlus forums but there has been no fixes as of today.

Cannot believe I came across this for the first time today and it's *still* an issue...

**Comment by pratik037** [comment]
> > This has been reported on OnePlus forums but there has been no fixes as of today.
> 
> Cannot believe I came across this for the first time today and it's _still_ an issue...

If you are using Flutter, then you can use safe area widget to avoid the notches

**Comment by ConsoleTVs** [comment]
> If you are using Flutter, then you can use safe area widget to avoid the notches

Need more details on that. I need answers.

![image](https://user-images.githubusercontent.com/6124435/63820036-062dbd80-c948-11e9-9454-05e13b0e8268.png)

**Comment by pratik037** [comment]
> > If you are using Flutter, then you can use safe area widget to avoid the notches
> 
> Need more details on that. I need answers.
> 
> ![image](https://user-images.githubusercontent.com/6124435/63820036-062dbd80-c948-11e9-9454-05e13b0e8268.png)

There's something called as SafeArea widget in Flutter. The error is because of the notch area mostly.

**Comment by ConsoleTVs** [comment]
> There's something called as SafeArea widget in Flutter. The error is because of the notch area mostly.

Very interesting. Will try it out.

**Comment by oliver-eastpoint** [comment]
Hi, just to confirm numerous users statement that it's not just a Flutter problem, I write apps using Xamarin.Forms/Android and my debug console logs are flooded with this message; making it painful to do my job at times! 
Doesn't lead to my app crashing or anything so I would love to ignore it for my sanity :)
I'm using OnePlus 6T

**Comment by morphran** [comment]
write this in Manifest file before </application> and hope it works or change the build version to 27.1.1

<uses-library
            android:name="org.apache.http.legacy"
            android:required="false" />

**Comment by morphran** [comment]
```
<uses-library
            android:name="org.apache.http.legacy"
            android:required="false" />
```

**Comment by CoreyCole** [comment]
I think we can remove `severe: crash` tag (https://github.com/flutter/flutter/issues/19810#issuecomment-412461688)

But would definitely like a non-hacky solution to this because it is hard to test on my One Plus 6 using flutter when my console is filled with these warnings/errors.
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.9.1+hotfix.4 at /Users/corey/flutter
    • Framework revision cc949a8e8b (12 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
```

**Comment by kiralex** [comment]
It seems that on Oxygen OS beta 30 (android 10), the problem does not occures anymore. 😄

**Comment by mathshenry** [comment]
> It seems that on Oxygen OS beta 30 (android 10), the problem does not occures anymore. 😄

I will give it a try later, I hope you're right! ;D

**Comment by DineshRajput21** [comment]
Got one solution

Try this one:

flutter run --enable-software-rendering

Working for me in One plus 6T !

**Comment by iapicca** [comment]
Hi @leodr 
does the [solution](https://github.com/flutter/flutter/issues/19810#issuecomment-568379344) proposed by @DineshRajput21  work for you?
thank you

**Comment by leodr** [comment]
> Hi @leodr
> does the [solution](https://github.com/flutter/flutter/issues/19810#issuecomment-568379344) proposed by @DineshRajput21 work for you?
> thank you

Unfortunately I do not own the OnePlus 6 anymore, I’m now developing on OnePlus 7 Pro and iPhone X, haven’t experienced any issues there.

**Comment by crifan** [comment]
copy my answer in another post

[java - Access denied finding property "vendor.debug.egl.swapinterval" i am keep getting this error in android studio when i run my app - Stack Overflow](https://stackoverflow.com/questions/52855807/access-denied-finding-property-vendor-debug-egl-swapinterval-i-am-keep-getting/63259537#63259537)

to here:

> E/libc: Access denied finding property "vendor.debug.egl.swapinterval"

this is the **Access denied finding property** type error.

which is probably caused by previous related **warning** like this:

`type=1400 audit(xxx): avc: denied { xxx } for name=xxx dev=xxx ino=xxx scontext=xxx tcontext=xxx tclass=xxx permissive=0`

# how to fix `avc: denied` error ?

* Simple:
    * refer offical doc [Validating SELinux  |  Android Open Source Project](https://source.android.com/security/selinux/validate) try use `audit2allow` and related tool to fix.
* Detailed:
    * refer my [another post's anwser](https://stackoverflow.com/questions/59533551/access-denied-finding-property-persist-vendor-log-tel-dbg/63259127#63259127)

**Comment by lythanhlong** [comment]
I have some problem but with other message.
I fixed my bug by declare "permission" in android\app\src\main\AndroidManifest.xml
```
<manifest>
...
<uses-permission android:name="android.permission.INTERNET"/>
...
<manifest>
```
