### ISSUE TITLE
Visual bug on CupertinoDialogAction blur effect

### ISSUE THREAD

**Issue by nesscx** [flutter/flutter#20784]
I'm using the <a href="https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/cupertino/cupertino_alert_demo.dart">cupertino_alert_demo</a> from the flutter_gallery example.

<p align="center">
    <img src="https://user-images.githubusercontent.com/16904145/44299681-fb6a3280-a2c8-11e8-9e09-3f7025f4ed52.png" height="50%" width="50%"/>
</p>

Flutter doctor:
[✓] Flutter (Channel master, v0.5.9-pre.79, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.26.0)

**Comment by xster** [comment]
cc @matthew-carroll

**Comment by matthew-carroll** [comment]
I've now confirmed that this issue occurs both on an Android emulator and on an Android device (Nexus 5X).

**Comment by matthew-carroll** [comment]
After some experimentation with the dialog rendering code, I think the problem may be a bug with how Paths calculate their interior when given a Rect.largest and a fill type of evenOdd.  The offending code appears to be:

```Dart
final Path backgroundFillPath = new Path()
      ..fillType = PathFillType.evenOdd
      ..addRect(Rect.largest);
```

**Comment by dnfield** [comment]
Here's a repro - run with software rendering (or changing from Rect.largest to a very large Rect, or comment out the `addOval`), it's fine - run with hardware rendering it doesn't draw correctly.

https://gist.github.com/dnfield/7cd4b64580040abf3b9ce8982c51d68b

**Comment by matthew-carroll** [comment]
This issue is a Skia bug and has been filed here:
https://bugs.chromium.org/p/skia/issues/detail?id=8290

When the Skia bug is fixed, this problem should disappear.  Therefore, we won't take any further action on the framework side.  We'll leave this bug open until the Skia issue is corrected.

**Comment by xster** [comment]
I'm actually seeing this in our 0.6.0 beta build from TestFlight on a physical iOS device as well

**Comment by matthew-carroll** [comment]
Weird.  Ok, well we can probably issue a framework side fix is needed, but the Skia bug was fixed supposedly, so the next Skia roll might have this resolved.

**Comment by xster** [comment]
I can still repro with iPhone XS on master

**Comment by akindone** [comment]
I can still repro with iPhone7 plus. I make a [pull request](https://github.com/flutter/flutter/pull/25076) to fix this problem. Skia's bug may be the chief culprit, but there is something we can do to make cupertino dialog looks better. @zoechi @matthew-carroll

**Comment by Xgamefactory** [comment]
> This should be fixed now

unfortunately not fixed still got transparent background on iphone devices.
