### ISSUE TITLE
Hero flickers on transition (Android & IOS)

### ISSUE THREAD

**Issue by littlemarc2011** [flutter/flutter#20845]
So on previous versions of flutter I didn't have this issue, but after upgrading to the latest version of flutter it makes heros flicker while they transition.
![As can be seen here](https://media.giphy.com/media/1pnWtKOUkAvcAWllTQ/giphy.gif)

## Steps to Reproduce

1. https://github.com/littlemarc2011/FlutterTodo
2. Use the latest version of flutter (master branch)
3. Build to either IOS or android, happens on both.

## Logs

There are no logs/no errors

## Flutter Analyze

```
Analyzing todo...                                                

   info • The top level variable '_kUnspecifiedArgument' isn't used • lib/CustomAppBar.dart:7:14 • unused_element
   info • This method overrides a method annotated as @mustCallSuper in 'State', but does not invoke the overridden method • lib/main.dart:77:8 • must_call_super
   info • The operator x ~/ y is more efficient than (x / y).toInt() • lib/main.dart:85:18 • division_optimization
   info • The value of the local variable '_ratioW' isn't used • lib/main.dart:123:18 • unused_local_variable
   info • The value of the local variable '_ratioH' isn't used • lib/main.dart:126:18 • unused_local_variable
warning • Element 'TextStyle' from SDK library 'ui.dart' is implicitly hidden by 'text_style.dart' • lib/main.dart:184:44 • conflicting_dart_import
   info • Avoid empty statements • lib/main.dart:511:5 • empty_statements
   info • Unused import: 'dart:collection' • lib/todo.dart:5:8 • unused_import

8 issues found. (ran in 1.3s)
```

## Flutter Doctor

```
[✓] Flutter (Channel master, v0.6.1-pre.44, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.6.1-pre.44 at /Users/bigmarco/Repositories/flutter
    • Framework revision 980c8a737b (3 hours ago), 2018-08-20 14:33:27 -0700
    • Engine revision c23690f0d7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[!] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/bigmarco/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 27.1.3
    • Dart plugin version 182.3911.37

[!] VS Code (version 1.26.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (2 available)
    • SM G950U • 9887bc48414134574b                   • android-arm64 • Android 8.0.0 (API 26)
    • iPhone X • 0A1678FE-CBF9-4948-8D87-E5AE8E31BF4C • ios           • iOS 11.4 (simulator)

! Doctor found issues in 3 categories.
```

**Comment by zoechi** [comment]
Did you check in profile or release mode? 
Performance behavior in debug mode is not representative.

**Comment by littlemarc2011** [comment]
@zoechi I just ran it on my s8 in release mode and in profile mode and it is still flickering. (flutter run --release and flutter run --profile).

**Comment by littlemarc2011** [comment]
_All the examples and GIFs are directed towards the text "Custom"_

Previously I had the text wrapped in a material widget, and this is what happens if I do it without:
![Without material](https://media.giphy.com/media/7zitzOQrc7DA1YXr9x/giphy.gif)

Code before:
```
new Hero(
  tag: todoObject.uuid +"_title",
  child: new Material(
    color: Colors.transparent,
    child: new Text(
      todoObject.title,
      style: new TextStyle(
        fontSize: 30.0
      ),
    ),
  ),
)
```

Code after: (What is shown in first GIF)
```
new Hero(
  tag: widget.todoObject.uuid + "_title",
  child: new Text(
    widget.todoObject.title,
    style: new TextStyle(fontSize: 30.0),
  ),
)
```
This would tell us that it is not related to material and more so text.

With a little more digging around, I set the size of the material (I reverted back to the before code) with a SizedBox and it no longer flickers as can be seen here:
![With sizedbox](https://media.giphy.com/media/1FE5MYJs57xbJzwhK2/giphy.gif)
The code is: (140.0 and 30.0 are just some random numbers that happened to fit in this case)
```
new Hero(
  tag: todoObject.uuid + "_title",
  child: new SizedBox(
    width: 140.0,
    height: 30.0,
    child: new Material(
      color: Colors.transparent,
      child: new Text(
        todoObject.title,
        style: new TextStyle(
          fontSize: 30.0
        ),
      ),
    ),
  ),
)
```

I assume something with how Hero's handle the size of text has changed (since a month ago this was working fine). It would be nice if I wouldn't have to specify the width and height of the text but this should help narrow down the issue.

**Comment by mafarque** [comment]
Hello,
Any luck with fixing the issue? It happens to me as well :/

**Comment by kundan9595** [comment]
Facing the same issue. Please help!

**Comment by marquesinijatinha** [comment]
@kundan9595 add a Material parent between your hero and your text, should fix it.

**Comment by Piinks** [comment]
Linking #30647 and #12463 to this issue.

**Comment by andreyeurope** [comment]
Any update on this issue?

**Comment by hp1909** [comment]
> Any update on this issue?

I still have this issue even though I used Material between Text and Hero.

**Comment by LongCatIsLooong** [comment]
Dup of #36220. This issue is older but since I assigned #36220 to myself I'm going to close this instead. This should be fixed once #36220 is closed.
