### ISSUE TITLE
TextField with Chinese character.

### ISSUE THREAD

**Issue by yohom** [flutter/flutter#23934]
When entering Chinese character, the cursor height is too short.

<img width="230" alt="screen shot 2018-11-05 at 16 03 51" src="https://user-images.githubusercontent.com/10418364/47985539-e0170280-e114-11e8-897b-9e86a1decc30.png">

flutter doctor:
```
[✓] Flutter (Channel dev, v0.10.2, on Mac OS X 10.14.1 18B50c, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[!] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[✓] VS Code (version 1.28.2)
[✓] Connected device (2 available)
```

**Comment by 5ummit** [comment]
Can you confirm this occurs on iOS too?

**Comment by yohom** [comment]
Yes, this occurs on iOS too.
![simulator screen shot - iphone xr - 2018-11-05 at 21 08 30](https://user-images.githubusercontent.com/10418364/47999937-05206b00-e13f-11e8-9bf6-99b8166108f1.png)

**Comment by zoechi** [comment]
Somewhat related #20694, #7034, #18888

**Comment by zywj** [comment]
you can solve the problem by setting chinese font family  like `HeiTi SC` in iOS platform.

**Comment by yohom** [comment]
@zywj Thank you for your solution! Solved my problem and it worked on the android platform, too.

**Comment by HansMuller** [comment]
@GaryQian - this sounds like some of the issues you've been looking at

**Comment by GaryQian** [comment]
A fix for this is being worked on: https://github.com/flutter/flutter/pull/24265

**Comment by xia-weiyang** [comment]
I hope to solve this problem as soon as possible, thank!

**Comment by hahafather007** [comment]
> @zywj感谢您的解决方案！解决了我的问题，它也在Android平台上运行。

这是怎么解决的，能说下嘛。怎么设置```HeiTi SC```

**Comment by yohom** [comment]
```dart
MaterialApp(
  theme: ThemeData(fontFamily: 'DroidSansFallback'),
)
```

**Comment by hahafather007** [comment]
@yohom 感谢大神，但是这个```DroidSansFallback```这个字体似乎跟默认的没啥区别，我试试其他字体吧

**Comment by GaryQian** [comment]
This PR is being worked on and should fix this issue: https://github.com/flutter/flutter/pull/24265/

**Comment by zoechi** [comment]
Can you please check if you can still reproduce with `master` channel?
#24876 might have fixed that.

**Comment by zoechi** [comment]
Seems to be fixed in iOS but not yet in Android https://github.com/flutter/flutter/issues/7034#issuecomment-458439876

**Comment by jkyeo** [comment]
Same here on android.

**Comment by yohom** [comment]
With `master` channel and `flutter doctor -v` below, this bug still exists on android(fixed in iOS). @zoechi please reopen this issue.
![6EB8FE5904AF9881EBB4D825D6D8D83E](https://user-images.githubusercontent.com/10418364/54258375-58973f80-459d-11e9-9c7f-4cbde63f91a7.jpg)
```
[✓] Flutter (Channel master, v1.3.10-pre.29, on Mac OS X 10.14.3 18D109, locale en-CN)
    • Flutter version 1.3.10-pre.29 at /Users/yohom/Library/Flutter/flutter
    • Framework revision 89a51272d5 (5 hours ago), 2019-03-12 18:32:42 -0700
    • Engine revision 5ccee95373
    • Dart version 2.2.1 (build 2.2.1-dev.1.0 674fd0e060)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/yohom/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/yohom/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0.beta.2

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 33.3.2
    • Dart plugin version 183.5912.23

[✓] VS Code (version 1.32.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0
```

**Comment by QueryStyle** [comment]
the cursor is not aligned

**Comment by GaryQian** [comment]
@justinmc @jslavitz This may be of interest to one of you? I might take a second shot at it if I get some time too.

**Comment by justinmc** [comment]
This is on my radar for text selection improvements.

**Comment by GaryQian** [comment]
https://github.com/flutter/flutter/pull/30991 Should fix this for Android. It seems to be fine on iOS.

**Comment by PandaGeek1024** [comment]
@GaryQian checkout the master branch and it works. Thanks for saving us.
