### ISSUE TITLE
Gesture recognizer error when using UiKitView

### ISSUE THREAD

**Issue by DCrow** [flutter/flutter#24207]
Getting this error after double tapping a `UiKitView` on ios.
Everything is fine when using `AndroidView` on android.
```
Dart Error: Unhandled exception:
'package:flutter/src/gestures/converter.dart': Failed assertion: line 143 pos 18: '!state.down': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:143:18)
#3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:151:12)
#4      ListQueue.addAll (dart:collection/queue.dart:715:25)
#5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:83:27)
#6      _invoke1 (dart:ui/hooks.dart:165:13)
#7      _dispatchPointerDataPacket (dart:ui/hooks.dart:119:5)
```
## Steps to Reproduce
[Example app](https://github.com/Unact/yandex_mapkit)
1. Launch example
2. Double tap on map(Try a few times. Not every double tap reproduces this error)

## Logs

`flutter analyze`

```
Analyzing example...
No issues found! (ran in 13.1s)
```

`flutter doctor -v`

```
[✓] Flutter (Channel master, v0.11.1-pre.134, on Mac OS X 10.12.6 16G1510, locale en-RU)
    • Flutter version 0.11.1-pre.134 at /Users/ybarkovskij/Work/flutter
    • Framework revision 43407e4e01 (13 hours ago), 2018-11-09 16:04:33 -0500
    • Engine revision 316f6365a6
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/ybarkovskij/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected device (1 available)
    • iPhone 5s • B276608C-A108-426E-BAF7-DE6244D7C4D0 • ios • iOS 11.2 (simulator)

• No issues found!
```

**Comment by DCrow** [comment]
@amirh maybe you can provide some insight to this problem?

**Comment by DCrow** [comment]
Also seems to be related.
Some single tap features for native view(`YMKMapView`) don't work when used in a UiKitView.

**Comment by DCrow** [comment]
@amirh Yes, this error doesn't crash the application.

Layout is simple
```dart
runApp(
  MaterialApp(
    home: Scaffold(
      appBar: AppBar(
        title: Text('')
      ),
      body: Column(
        children: <Widget>[
          Expanded(
            child: YandexMap()
          )
        ]
      )
    )
  )
);
```
`YandexMap` build method returns a UiKitView or AndroidView
A more complete example can be seen [here](https://github.com/Unact/yandex_mapkit/blob/master/example/lib/main.dart)

I think nothing should be competing with platform view, especially since `AndroidView` works as expected

**Comment by sanderAtMaxdoro** [comment]
Single taps do not work either. I have a map view inside the UiKitView. Tapping on the info buttons do not result in the map view accessory callback being called. Having a target-action on the button also does not result in the action being called. I do get the assertions about state down being invalid.

**Comment by DCrow** [comment]
@sanderAtMaxdoro Yeah I also reproduce the same problem(single taps or double taps) using my example

**Comment by DCrow** [comment]
@amirh Seems like this bug is a common problem, even in the `google_maps_flutter` plugin(As seen in #24520) 

I think this bug is a blocker for views which have interactive elements(double taps, long taps, etc)

**Comment by amirh** [comment]
yes, this is high on my priority list.

**Comment by DCrow** [comment]
@amirh 
Still getting this error when using engine SHA [`db5214d3de801a327bc18a828222da24f6583f19`](https://github.com/flutter/engine/commit/db5214d3de801a327bc18a828222da24f6583f19)

Also some gestures(double taps for example) don't arrive to native view.
If I comment [these](https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm#L342-L343) 2 lines they do arrive and native view works as expected, but this change breaks flutters gesture recognizers.

**Comment by amirh** [comment]
@DCrow do you see the problem in the Google Maps example? (the scrolling map page is a good case with competing gestures).
All gestures I tried, including double tap are working for me on a physical device and on a simulator.
Make sure you have both the engine and the framework at HEAD.

(the lines you commented would result in completely skipping the Flutter/UIView gesture integration, you probably don't want to do that)

**Comment by DCrow** [comment]
Also checked using current flutter framework master(without using manually compiled engine)
Still getting this error.
Taps on Google logo also reproduce this error
```
[✓] Flutter (Channel master, v1.1.5-pre.34, on Mac OS X 10.12.6 16G1710, locale en-RU)
    • Flutter version 1.1.5-pre.34 at /Users/ybarkovskij/Work/flutter
    • Framework revision 0220412c53 (35 minutes ago), 2018-12-28 14:05:19 -0800
    • Engine revision f0a1d6f91d
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 d1817ddc91)
```

**Comment by amirh** [comment]
Do you still have double taps undetected by the map?

**Comment by DCrow** [comment]
When using the map in my example double taps are still undetected. Google map detects them.

**Comment by DCrow** [comment]
On Scrolling map view bottom map stops responding to any gesture after trying to rotate the map(I tried this on a real iphone 6 iOS 11.3.1)

**Comment by amirh** [comment]
Interesting I don't see any issues after rotating the map in the Google Maps scrolling map example (iOS 11.4.1).

Can you please file a separate issue for the gesture issues after rotating a Google Map (a screen recording would be great to make sure we mean the same by rotating the map 😄 )

Thanks for all your reports!

**Comment by DCrow** [comment]
Sure(#25859), but I'm not sure about screen recording since I can't show how I am tapping the screen.
By rotating I meant two finger rotation(touch the screen with two fingers and then move one to left/right)

What about Logo, My Location button and double taps in my example?

**Comment by larrymryan** [comment]
when i use uikitview in listView 
alse get this error

**Comment by amirh** [comment]
Reopening this as there are still occurrences of the assertion failure.

**Comment by palancana** [comment]
I'm having the same issue. In my case I'm using the [WebView plugin](https://pub.dartlang.org/packages/webview_flutter) and loading any webpage (google.com for example). If I do a some double taps or pinch to zoom it eventually fails with the same assertion error. It is not happening on an Android emulator. 

I'm using the widget like this:
```dart
WebView(
    initialUrl: 'https://www.google.es/',
),
```
It is easier for me to reproduce it on a real iOS device, but it also happens on the simulator. Also, I'm using the stable version 1.0.0 of Flutter.

**Comment by ViniciusSossela** [comment]
Getting the same error when I tap on my current location icon/button on google maps, also happens when tap on google logo.

`flutter: Caught error: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 143 pos 18: '!state.down': is not true.
flutter: #0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:143:18)
#3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:151:12)
#4      ListQueue.addAll (dart:collection/queue.dart:715:25)
#5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:83:27)
#6      _rootRunUnary (dart:async/zone.dart:1136:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _invoke1 (dart:ui/hooks.dart:170:10)
#10     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
`

**Comment by cuikun** [comment]
![image](https://user-images.githubusercontent.com/9009510/51034366-82ee7000-15e1-11e9-999c-cc63f5483acf.png)
Getting the same error in iPhone, when I tap a mapview in custom plugin

**Comment by csjames** [comment]
Yeah second this!

I am integrating mapbox to my application, all gestures work except single presses... I get the same exception as listed above. 

Any timeline for this?

**Comment by amirh** [comment]
I believe issue where gestures are not detected by the embedded view has been fixed by https://github.com/flutter/engine/pull/7558 (as of writing this it wasn't rolled to the framework yet).

The my location button and google maps logo in google_maps_flutter works for me with this fix.
(Could you update if it also fixed the other gesture detection failures that were reported on this issue?).

The converter assertion failures are still happening, I think the issue might be that for accepted gestures when the delaying gesture recognizer rejects, the same touch sequence that was passed to Flutter through the forwarding recognizer is passed again directly to FlutterView. Will try to take a look soon.

**Comment by DCrow** [comment]
@amirh Great news! Gesture failures in my example stopped happening.

Still some gestures(for example swiping to left/right) sometimes make assertion failures and don't work. I guess those are now related to being passed again to FlutterView.

**Comment by zoechi** [comment]
Same error as #11672
@amirh  do you think this fixes #11672 as well?

**Comment by jesaiasmaia** [comment]
Herer is happing the same. Just when I touch the map first tap, when it is not the focus.

`[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 155 pos 18: '!state.down': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:155:18)
#3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:152:12)
#4      ListQueue.addAll (dart:collection/queue.dart:715:25)
#5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:83:27)
#6      _rootRunUnary (dart:async/zone.dart:1136:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _invoke1 (dart:ui/hooks.dart:203:10)
#10     _dispatchPointerDataPacket (dart:ui/hooks.dart:138:5)`

**Comment by andrea689** [comment]
I have the same problem with Mapbox tobrun/flutter-mapbox-gl#20

I have tested in all flutter channel, this is the last master:

    • Flutter version 1.2.1-pre.66
    • Framework revision 496ddc580c (19 hours ago), 2019-02-02 16:23:39 -0800
    • Engine revision 15f2b92cce
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 71bee8f05e)

**Comment by amirh** [comment]
@andrea689 there are 2 separate problems discussed here:

1. Some gestures didn't go through to the embedded view.
2. The assertion failure.

Which one of these do you see?
I believe #&#x2060;1 was fixed.

**Comment by andrea689** [comment]
@amirh the assertion failure.

**Comment by amirh** [comment]
Thanks.

I'm going to split the assertion error to a separate issue and close this one.

**Comment by amirh** [comment]
split off the assertion failure to https://github.com/flutter/flutter/issues/27700

**Comment by gopchi** [comment]
This issue still persists. We are using flutter_webview plugin to integrate a google map on which when you click a circle is created at the current coordinates. Also we have a floating button on top of the webview which passes a Javascript event to the webview and centers the map on the user's location.

However, whenever I click the button which is on top of the webview in the stack, the click propagates to the webview and this should not be like that. We also switched channels and tried with "master", but the issue persists.

@cyanglaz @amirh

**Comment by amirh** [comment]
Interesting, if you can come up with a minimal app that reproduces the
issue it will be most helpful.

**Comment by gopchi** [comment]
@amirh I set up a simple app that represents the issue. Please just add your Google Maps API key in assets/index.html.

Here is the repo - https://github.com/gopchi/flutter_webview_duplicated_gestures

Thanks!

**Comment by cyanglaz** [comment]
@gopchi I couldn't reproduce the issue on your example. And I also created a simplified version of the APP and it is also working fine.  Here is my simplified version. 
```import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() async {

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text('WebView Example'),
      ),
      body: Stack(
        children: <Widget>[
          Positioned.fill(
            child: WebView(
              initialUrl: 'https://sketch.io/sketchpad',
              javascriptMode: JavascriptMode.unrestricted,
            ),
          ),
          Positioned(
            bottom: 50.0,
            right: 50.0,
            child: GestureDetector(
              onTap: (){print('tapped');},
              behavior: HitTestBehavior.opaque,
              child: Material(
                color: Colors.white,
                elevation: 3.0,
                child: Container(
                  padding: const EdgeInsets.all(2.0),
                  alignment: Alignment.center,
                  width: 100.0,
                  height: 100.0,
                  child: Icon(
                    Icons.my_location,
                    size: 50.0,
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
    ),
    );
  }
}
```
Could you make sure you are using the latest Flutter in Master?
Please also post your flutter doctor -v here.

**Comment by jesaiasmaia** [comment]
In that example could you put a google maps view and a button?. So the test is tap button and then tap in maps, so again and again, just iOS, the error will occurr.

**Comment by jesaiasmaia** [comment]
I am some angry iOS users, complaining that are many erros in app, only when using the map.

**Comment by cyanglaz** [comment]
@jesaiasmaia Could you try your app with the latest Flutter, and maybe post your `flutter doctor -v` here?

**Comment by jesaiasmaia** [comment]
It was with flutter 1.2.1

**Comment by cyanglaz** [comment]
@jesaiasmaia Could you try with Flutter on master branch?

**Comment by gopchi** [comment]
@cyanglaz I tried yesterday with the master branch and the issue persisted.

**Comment by fengqiangboy** [comment]
PanGesture on UIKitView also have this issue

**Comment by cyanglaz** [comment]
> PanGesture on UIKitView also have this issue

Could you provide an reduced test case so we can investigate?

**Comment by fengqiangboy** [comment]
> > PanGesture on UIKitView also have this issue
> 
> Could you provide a reduced test case so we can investigate?

Here is a project can reduced, you can run the example project to reduced it

When you tap the chart and move, it will reduced

[git@github.com:fengqiangboy/flutter_editable_charts.git](git@github.com:fengqiangboy/flutter_editable_charts.git)

**Comment by cyanglaz** [comment]
@fengqiangboy Thank you for providing this. This example you provide is too large and complicated for us to debug. Is it possible you can create a mini app that reproduce your issue? As mini as possible :)

**Comment by fengqiangboy** [comment]
> @fengqiangboy Thank you for providing this. This example you provide is too large and complicated for us to debug. Is it possible you can create a mini app that reproduce your issue? As mini as possible :)

I have create a mini app:

[https://github.com/fengqiangboy/flutter_uikit_view_pan](https://github.com/fengqiangboy/flutter_uikit_view_pan)

It just add a UIPanGestureRecognizer on UIKitView, and when I  gesture happen, it log error like that

```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 172 pos 20: '!state.down': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:172:20)
#3      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:152:12)
#4      ListQueue.addAll (dart:collection/queue.dart:655:25)
#5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:84:27)
#6      _rootRunUnary (dart:async/zone.dart:1136:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _invoke1 (dart:ui/hooks.dart:233:10)
#10     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)
```

**Comment by fengqiangboy** [comment]
> > @fengqiangboy Thank you for providing this. This example you provide is too large and complicated for us to debug. Is it possible you can create a mini app that reproduce your issue? As mini as possible :)
> 
> I have create a mini app:
> 
> https://github.com/fengqiangboy/flutter_uikit_view_pan
> 
> It just add a UIPanGestureRecognizer on UIKitView, and when I gesture happen, it log error like that
> 
> ```
> [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 172 pos 20: '!state.down': is not true.
> #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
> #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
> #2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:172:20)
> #3      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:152:12)
> #4      ListQueue.addAll (dart:collection/queue.dart:655:25)
> #5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:84:27)
> #6      _rootRunUnary (dart:async/zone.dart:1136:13)
> #7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
> #8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
> #9      _invoke1 (dart:ui/hooks.dart:233:10)
> #10     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)
> ```

![image](https://user-images.githubusercontent.com/13598763/56479979-b7c86800-64ea-11e9-9d8b-f548cb18d626.png)

The red view is add UIPanGestureRecognizer, you can pan on it

**Comment by cyanglaz** [comment]
@fengqiangboy

**Comment by cyanglaz** [comment]
Reopened this issue since it has not been fully fixed. @amirh

**Comment by devilishWei** [comment]
Getting this error after using location button, then drag map will crash app exist in ios

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale
    zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.3)
[!] IntelliJ IDEA Ultimate Edition (version 2018.3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.33.1)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.

**Comment by rogeliotrejo13** [comment]
Same error after press floating button, to get current location on map.

[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 155 pos 18: '!state.down': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:155:18)
#3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:152:12)
#4      ListQueue.addAll (dart:collection/queue.dart:715:25)
#5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:83:27)
#6      _rootRunUnary (dart:async/zone.dart:1136:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _invoke1 (dart:ui/hooks.dart:223:10)
#10     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)

**Comment by cyanglaz** [comment]
@rogeliotrejo13 @devilishWei I created a PR to fix the issue flutter/engine#8685
It might take some time to merge this in. But if you want to try it out in your local engine and let me know if it fixed your issue,  that'd be great!
For details to compile a local engine, you can check out here https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment

**Comment by cyanglaz** [comment]
@rogeliotrejo13 @devilishWei https://github.com/flutter/engine/pull/8685 is merged. I am closing this issue now. If it is still not working applying the fix, please feel free to reply to this ticket or create another one.

**Comment by AdamJonsson** [comment]
I am getting this error again on IOS when the gesture detector is overflowing the Stack widget. Use the following app and drag the red Container down to the bottom or top of the screen.

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() async {

  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  double offsetY = 0;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
      appBar: AppBar(
        title: Text('WebView Example'),
      ),
      body: Stack(
        children: <Widget>[
          Positioned.fill(
            child: WebView(
              initialUrl: 'https://www.google.com/',
              javascriptMode: JavascriptMode.unrestricted,
            ),
          ),
          Positioned(
            bottom: 50.0 - offsetY,
            right: 50.0,
            left: 50.0,
            child: GestureDetector(
              onVerticalDragUpdate: (dragEvent) {
                setState(() {
                  offsetY += dragEvent.delta.dy;
                });
              },
              behavior: HitTestBehavior.opaque,
              child: Container(
                height: 100,
                color: Colors.red,
              ),
            ),
          ),
        ],
      ),
    ),
    );
  }
}
```

This is my output of flutter doctor
[✓] Flutter (Channel beta, v1.10.7, on Mac OS X 10.15 19A602, locale en-SE)
    • Flutter version 1.10.7 at /Users/adamjonsson/Development/Flutter
    • Framework revision e70236e36c (4 weeks ago), 2019-10-02 09:32:30 -0700
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 1103600280)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/adamjonsson/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (2 available)
    • Adams iPhone      • 00008020-00141C991E02002E            • ios • iOS 13.1.3
    • iPhone 11 Pro Max • D23C96B9-3195-4B0B-A94D-06154E002A11 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)

• No issues found!

**Comment by danielgrgly** [comment]
Hey! 
I get the same error, with the following output:
```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 176 pos 20: '!state.down': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:176:20)
#3      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:144:12)
#4      ListQueue.addAll (dart:collection/queue.dart:655:25)
#5      GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:84:27)
#6      _rootRunUnary (dart:async/zone.dart:1136:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _invoke1 (dart:ui/hooks.dart:263:10)
#10     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
```

**Comment by rochapablo** [comment]
```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 176 pos 20: '!state.down': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:176:20)
#3      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:144:12)
#4      ListQueue.addAll (dart:collection/queue.dart:655:25)
#5      GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:84:27)
#6      _rootRunUnary (dart:async/zone.dart:1136:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _invoke1 (dart:ui/hooks.dart:263:10)
#10     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
	[C3.1 DD57C25B-15D1-445E-A310-3A3C3F8E9519 192***:62548<->172.217.172.194:443]
```
