### ISSUE TITLE
Green, flickering bar over camera preview

### ISSUE THREAD

**Issue by asgerhallas** [flutter/flutter#24289]
## Steps to Reproduce

1. Make an app exactly like this sample: https://pub.dartlang.org/packages/camera
2. Deploy the app to a Huawei Y6 2018 with Android 8.0.0
3. See this: 

![screenshot_20181113-161703](https://user-images.githubusercontent.com/299575/48423088-3eb92d80-e760-11e8-98ad-86edd84af7cf.jpg)

## Logs
```
Launching lib\main.dart on ATU L21 in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk.
I/CameraManagerGlobal(30810): Connecting to camera service
I/CameraManagerGlobal(30810): single back camera, do not need hide aux camera, device number: 0
I/CameraManagerGlobal(30810): single back camera, do not need hide aux camera, device number: 1
I/CameraManagerGlobal(30810): single back camera, do not need hide aux camera, device number: 2
I/CameraManagerGlobal(30810): single back camera, do not need hide aux camera, device number: 2
E/BufferQueueProducer(30810): [] Can not get hwsched service
E/BufferQueueProducer(30810): [] Can not get hwsched service
I/PermissionManager(30810): camera remind result:true
I/CameraManagerGlobal(30810): single back camera, do not need hide aux camera, device number: 2
I/CameraManagerGlobal(30810): single back camera, do not need hide aux camera, device number: 2
I/zygote64(30810): Do partial code cache collection, code=27KB, data=27KB
I/zygote64(30810): After code cache collection, code=20KB, data=24KB
I/zygote64(30810): Increasing code cache capacity to 128KB

```
```

   info - Duplicate import - lib\main.dart:3:8 - duplicate_import
   info - Unused import: 'package:fluff/main.dart' - test\widget_test.dart:11:8 - unused_import
  error - The constructor returns type 'dynamic' that isn't of expected type 'Widget' - test\widget_test.dart:16:29 -
         strong_mode_invalid_cast_new_expr
  error - Undefined class 'MyApp' - test\widget_test.dart:16:33 - undefined_class

```
```
[√] Flutter (Channel beta, v0.10.2, on Microsoft Windows [Version 10.0.17134.345], locale da-DK)
    • Flutter version 0.10.2 at c:\workspace\flutter
    • Framework revision d8cbb80206 (3 weeks ago), 2018-10-26 01:30:21 -0400
    • Engine revision 6c2ade9fa2
    • Dart version 2.1.0-dev.8.0.flutter-bf26f760b1

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\asgerhallas\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code, 64-bit edition (version 1.28.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.20.0

[√] Connected device (1 available)
    • ATU L21 • GSM9X18A07G03187 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

```

**Comment by zoechi** [comment]
> Deploy the app to a Huawei Y6 2018 with Android 8.0.0

does this mean on other devices (and emulator) this doesn't reproduce?

**Comment by jasnig** [comment]
@zoechi I am meeting the same problem with  xiaomi 4 Android 6.0. By the way, the same problem with the video_player plugin. (Flutter Channel dev, v0.11.3)

**Comment by songfei** [comment]
same issue in video player , xiaomi 4 Android 6.0

**Comment by asgerhallas** [comment]
@zoechi I couldn't get access to another device, sorry.

**Comment by zoechi** [comment]
@asgerhallas that's ok, it just wasn't clear to me if you meant to point out if you see this only on the mentioned device or if this is the only device you tried it with. Thanks for the update.

**Comment by recastrodiaz** [comment]
@songfei do you mean this issue is not present in Flutter 0.7.0?

I have experienced a similar issue on an LG-G2 (D802) Device (https://www.lg.com/uk/mobile-phones/lg-D802) running Android KitKat 4.4.2 when using the video_player. I'll try to get my hands on a screenshot.

**Comment by songfei** [comment]
@recastrodiaz   , YES,  I confirmed it,

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v0.7.3, on Mac OS X 10.14 18A391, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.29.0)
[✓] Connected devices (2 available)

video_player and Camera is OK， same code in Flutter 0.11.3 is NOT OK.

**Comment by recastrodiaz** [comment]
Thanks @songfei 
From this comment in https://github.com/flutter/flutter/issues/24402#issuecomment-439237830, it would seem the regression started in v0.10.2  Would you mind checking if v0.10.1 (https://github.com/flutter/flutter/releases/tag/v0.10.1) works as expected? This might help the flutter team confirm where the regression started. Thanks!

**Comment by tvolkert** [comment]
@asgerhallas this should be fixed in the latest release (`v0.11.10`, available on the dev and beta channels).  Can you please run `flutter upgrade` and then verify to see if it's fixed for you?

**Comment by songfei** [comment]
Flutter 0.11.11-pre.2 • channel master • https://github.com/flutter/flutter.git
Framework • revision a2a1311a1a (5 hours ago) • 2018-11-26 19:43:10 -0800
Engine • revision 84e3b137a1
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

XiaoMi 4 , Android 6.0 
green block is still exist.

**Comment by hariprasadiit** [comment]
facing the same issue. `0.11.10` didn't solve it

**Comment by tvolkert** [comment]
Ok, second take... can you please try `v0.11.11` (on the latest `dev` and `beta` channels - available via `flutter upgrade`)?  Thanks!

**Comment by tvolkert** [comment]
Ok, `v0.11.13` is live on the `dev` and `beta` channels, with the latest attempt at fixing this.

**Comment by Fengxiaojun47503** [comment]
> Ok, `v0.11.13` is live on the `dev` and `beta` channels, with the latest attempt at fixing this.
It is OK on my device. The green block not occur any more.

**Comment by tvolkert** [comment]
Great!  I'm going to close this issue.  Feel free to reopen it if you see this happen again

**Comment by Hangtinh** [comment]
Hãy giúp tôi sửa cái này
E/BufferQueueProducer: [] [hwsched]Can not get hwsched service
E/BufferQueueProducer: [] [hwsched] Sched_config_cust.xml is not exit or file is invalid!
    [] [hwsched] LoadFile error, path:(null), error code:3

**Comment by Genius-LG** [comment]
> Hãy giúp tôi sửa cái này
> E/BufferQueueProducer: [] [hwsched]Can not get hwsched service
> E/BufferQueueProducer: [] [hwsched] Sched_config_cust.xml is not exit or file is invalid!
> [] [hwsched] LoadFile error, path:(null), error code:3

same issue

**Comment by MahdiPishguy** [comment]
i have problem when i try to build final apk or using `--release` parameter
