### ISSUE TITLE
iOS build faild

### ISSUE THREAD

**Issue by Pareshoct7** [flutter/flutter#24376]
## Steps to Reproduce

`     flutter build ios`

## Logs

```
Building com.example for device (ios-release)...
Automatically signing iOS for device deployment using specified development team
in Xcode project: 368*****CR
Starting Xcode build...                                          
 ├─Building Dart code...                             11.5s
 
Xcode build done.                                           18.5s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    Building AOT snapshot in release mode (ios-release)...          

    Compiler message:
    lib/screens/ProfileViewScreen.dart:1:8: Error: Can't access platform private library.
    import 'dart:_http';
           ^
    lib/screens/swipe/cards_section_draggable.dart:1:8: Error: Can't access platform private library.
    import 'dart:_http';
           ^
    Compiler terminated unexpectedly.
    Failed to build /Users/pareshpatil/workspace/example-flutter.

Encountered error while building for device.
14.3s
```

## flutter doctor -v

```
[✓] Flutter (Channel master, v0.11.7-pre.20, on Mac OS X 10.13.6 17G65, locale en-IN)
    • Flutter version 0.11.7-pre.20 at /Users/pareshpatil/sdk/flutter
    • Framework revision 091b73ab6f (83 minutes ago), 2018-11-14 18:54:51 -0800
    • Engine revision 498bbd5ef9
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/pareshpatil/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • iPhone XR • 21381D8F-7EEA-4E74-91AE-1302FC4615D2 • ios • iOS 12.1 (simulator)

• No issues found!
```

**Comment by zoechi** [comment]
Looks like https://github.com/dart-lang/sdk/issues/35009

**Comment by Pareshoct7** [comment]
@zoechi Is there any solution available?

**Comment by zoechi** [comment]
Looks like #24139 which is fixed in `master` channel.

**Comment by Pareshoct7** [comment]
People talking about dev channel I am looking solution for master channel. I don't want to move to dev channel I want to stick with the master channel. may I know how much time it will take to fix on the master channel?

**Comment by a-siva** [comment]
The error you are getting is a valid error message as 'dart:_http' is a private library that cannot be imported from an  application. You should be getting the error when running the app in debug mode also. I verified that by adding that import into a sample app and trying to run it and it does fail

```
Launching lib/main.dart on Moto G 4 in debug mode...
Initializing gradle...                                       0.8s
Resolving dependencies...                                    3.3s
Gradle task 'assembleDebug'...                                   

Compiler message:
lib/main.dart:8:8: Error: Can't access platform private library.
import 'dart:_http';
       ^
Compiler failed on /usr/local/google/home/asiva/workspace/flutter-roll/flutter/examples/flutter_gallery/lib/main.dart
 
Gradle task 'assembleDebug'... Done                         10.7s
Gradle task assembleDebug failed with exit code 1

```

**Comment by a-siva** [comment]
Closing issue as 'works as intended'

**Comment by Pareshoct7** [comment]
Still issue is not resolved I tried with dev channel also.

here is the error:

## Steps to Reproduce

` 
 flutter build ios --release
`

## Logs

```
Running pod install...                                      22.6s
Starting Xcode build...                                          
 ├─Building Dart code...                             11.3s                                                                                                                                                                                                           
Xcode build done.                                           21.0s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc
    Inference" build setting to "Default" for the "Runner" target.
    The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc
    Inference" build setting to "Default" for the "Runner" target.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    Building AOT snapshot in release mode (ios-release)...          

    Compiler message:
    lib/screens/ProfileViewScreen.dart:1:8: Error: Can't access platform private library.
    import 'dart:_http';
           ^
    lib/screens/swipe/cards_section_draggable.dart:1:8: Error: Can't access platform private library.
    import 'dart:_http';
           ^
    Compiler terminated unexpectedly.
    Failed to build /Users/pareshpatil/workspace/kaledate/mobile.

Encountered error while building for device. 
```

## flutter doctor -v

```
[✓] Flutter (Channel dev, v0.11.9, on Mac OS X 10.13.6 17G65, locale en-IN)
    • Flutter version 0.11.9 at /Users/pareshpatil/sdk/flutter
    • Framework revision d48e6e433c (2 days ago), 2018-11-20 22:05:23 -0500
    • Engine revision 5c8147450d
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/pareshpatil/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2018.2.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.5124

[✓] Connected device (1 available)
    • iPhone XR • 21381D8F-7EEA-4E74-91AE-1302FC4615D2 • ios • iOS 12.1 (simulator)

• No issues found!
```

**Comment by mraleph** [comment]
@Pareshoct7 what does `lib/screens/ProfileViewScreen.dart` contain? Can you post the first few lines of the file?

Does it _actually_ contain `import 'dart:_http';` inside or not?

**Comment by Pareshoct7** [comment]
@mraleph  following is the code infollowing file
`lib/screens/ProfileViewScreen.dart`


```

import 'dart:_http';
import 'dart:async';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:flutter_app/Models/FBUser.dart';
import 'package:flutter_app/Utils/DateTimeUtil.dart';
import 'package:flutter_app/auth/authentication_service.dart';
import 'package:flutter_app/database/FBUserDelegate.dart';
import 'package:flutter_app/screens/chat.dart';
import 'package:flutter_app/values/UiColors.dart';
import 'package:flutter_app/values/UiStrings.dart';
import 'package:time_machine/time_machine.dart';
//import 'package:flutter_app/screens/ChatScreen.dart';

class ProfileViewScreen extends StatefulWidget {
  final String userId;

  ProfileViewScreen({Key key, this.userId}) : super(key: key);

  @override
  _ProfileViewScreenState createState() => _ProfileViewScreenState();
}

class _ProfileViewScreenState extends State<ProfileViewScreen> {
  FBUser currentFBUser;
  FBUser chatFBUser;
  String userId;
  String token;

  Map<dynamic, dynamic> friend;

//  var _avatar;
//  bool downloaded = true;

  TextStyle chipTextStyle = TextStyle(
      color: UiColors.chipsBlackText,
      fontSize: 12.0,
      fontWeight: FontWeight.w400);

  @override
  void initState() {
    // TODO: implement initState
    super.initState();

    Firestore firestore = Firestore.instance;

    if (widget.userId == null) {
      return;
    }

    AuthService.userId().then((uId) {
      if (uId == null) {
        return;
      }

      userId = uId;

      StreamSubscription<DocumentSnapshot> streamSub;
      streamSub = firestore
          .collection(FBUserDelegate.userTable)
          .document(uId)
          .snapshots()
          .listen((documentShot) {
        FBUser fbUser = FBUser.fromMap(documentShot.data);

        setState(() {
          currentFBUser = fbUser;
        });

        firestore
            .collection(FBUserDelegate.friendTable)
            .document(currentFBUser.userId)
            .collection(widget.userId)
            .document(widget.userId)
            .snapshots()
            .listen((documentShot) {
//              Map<dynamic, dynamic> map = event.snapshot.value;
//
//              if (map != null && map.values != null) {
//                if (this.mounted) {
//                  setState(() {
//                    friend = map;
//                  });
//                }
//              }

          Map<String, dynamic> map = documentShot.data;
          if (map != null && map.values != null) {
            if (this.mounted) {
              setState(() {
                friend = map;
              });
            }
          }
        });
        streamSub.cancel();
      });
    });

    StreamSubscription<DocumentSnapshot> streamTokenSub;
    streamTokenSub = firestore
        .collection(FBUserDelegate.fcmTokenTable)
        .document(widget.userId)
        .snapshots()
        .listen((documentShot) {
      token = documentShot.data[widget.userId];
      print(token);
      streamTokenSub.cancel();
    });

    firestore
        .collection(FBUserDelegate.userTable)
        .document(widget.userId)
        .snapshots()
        .listen((documentShot) {
      FBUser fbUser = FBUser.fromMap(documentShot.data);
      setState(() {
        this.chatFBUser = fbUser;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Container(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              space(height: 8.0),
              Text(getFLName()),
              space(height: 3.0),
              Text(
                getOnlineStatus(),
                style: TextStyle(fontSize: 12.0),
              ),
            ],
          ),
        ),
      ),
      backgroundColor: UiColors.white,
      body: listOfWidgets(),
//      floatingActionButton: FloatingActionButton(
//        onPressed: () {
//          var route = new MaterialPageRoute(
//            builder: (BuildContext context) => ChatScreen(
//                  userId: fbUser.userId,
//                ),
//          );
//          Navigator.of(context).push(route);
//        },
//        child: Icon(
//          Icons.message,
//          color: UiColors.white,
//        ),
//      ),
    );
  }

  listOfWidgets() {
    return ListView(
      padding: const EdgeInsets.symmetric(horizontal: 16.0),
      children: <Widget>[
//        Chip(
//          avatar: Icon(
//            Icons.brightness_1,
//            color: UiColors.green,
//          ),
//          label: Text(getOnlineStatus()),
//        ),
        space(height: 40.0),
//        Text(fbUser == null ? 'nouser' : (fbUser.isOnline != null && fbUser.isOnline ? 'Online' : (fbUser.lastActive != null ? fbUser.lastActive.toString() : 'no date'))),
        headerView(),
        space(height: 10.0),
        buttonLayout(),
//        Padding(
//          padding: EdgeInsets.symmetric(vertical: 10.0),
//          child: Divider(),
//        ),
        about(),
        address(),
        lookingForChips(),
        kidsChips(),
        interestChips(),
        space(height: 20.0),
      ],
    );
  }

  space({double height = 0.0, double width = 0.0}) {
    return SizedBox(
      width: width,
      height: height,
    );
  }

  headerView() {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        avatarImage(),
        space(width: 20.0),
        Expanded(
            child: Padding(
          padding: const EdgeInsets.only(top: 8.0),
          child: Container(
            width: double.maxFinite,
            child: firstAndLastName(),
          ),
        )),
      ],
    );
  }

  avatarImage() {
    return Center(
        child: Stack(
      alignment: Alignment(0.0, 0.0),
      children: <Widget>[
        SizedBox(
          height: 120.0,
          width: 120.0,
          child: CircleAvatar(
            backgroundColor: UiColors.grey,
            backgroundImage: chatFBUser == null ||
                    chatFBUser.fAvatar == null ||
                    chatFBUser.fAvatar.isEmpty
                ? AssetImage(UiStrings.pathAvatar)
                : NetworkImage(chatFBUser.fAvatar), // : FileImage(_image),
          ),
        ),
//        downloaded
//            ? SizedBox(
//                height: 120.0,
//                width: 120.0,
//                child:
//                    CircularProgressIndicator(backgroundColor: UiColors.white))
//            : Container()
      ],
    ));
  }

  firstAndLastName() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        Row(
          children: <Widget>[
            Text(
              chatFBUser == null
                  ? ''
                  : (chatFBUser.firstName == null ? '' : chatFBUser.firstName),
              style: TextStyle(
                  color: UiColors.greyDark,
                  fontSize: 24.0,
                  fontWeight: FontWeight.w700),
            ),
            space(width: 10.0),
            Text(
              chatFBUser == null
                  ? ''
                  : (chatFBUser.lastName == null ? '' : chatFBUser.lastName),
              style: TextStyle(
                  color: UiColors.greyDark,
                  fontSize: 24.0,
                  fontWeight: FontWeight.w700),
            ),
          ],
        ),
        space(height: 6.0),
        Text(
          chatFBUser == null
              ? ''
              : (chatFBUser.iAmA == null ? '' : chatFBUser.iAmA),
          style: TextStyle(
              color: UiColors.grey,
              fontSize: 17.0,
              fontWeight: FontWeight.w400),
        ),
        space(height: 2.0),
        Row(
          children: <Widget>[
            Text(
              chatFBUser == null
                  ? ''
                  : (chatFBUser.dob == null
                      ? ''
                      : '${getAgeFromDOB(chatFBUser.dob)},'),
              style: TextStyle(
                  color: UiColors.grey,
                  fontSize: 17.0,
                  fontWeight: FontWeight.w400),
            ),
//            space(width: 10.0),
//            Text(
//              '-',
//              style: TextStyle(
//                  color: UiColors.grey,
//                  fontSize: 17.0,
//                  fontWeight: FontWeight.w400),
//            ),
            space(width: 10.0),
            Text(
              chatFBUser == null
                  ? ''
                  : (chatFBUser.gender == null ? '' : chatFBUser.gender),
              style: TextStyle(
                  color: UiColors.grey,
                  fontSize: 17.0,
                  fontWeight: FontWeight.w400),
            ),
          ],
        ),
        space(height: 2.0),
        Text(
          chatFBUser == null
              ? ''
              : (chatFBUser.diet == null ? '' : chatFBUser.diet),
          style: TextStyle(
              color: UiColors.grey,
              fontSize: 17.0,
              fontWeight: FontWeight.w400),
        ),
      ],
    );
  }

  buttonLayout() {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
      children: <Widget>[
        Expanded(
          child: FlatButton(
//      padding: EdgeInsets.symmetric(vertical: 8.0),
            color: UiColors.red,
            textColor: UiColors.white,
            shape: OutlineInputBorder(borderRadius: BorderRadius.circular(4.0)),
            onPressed: () {
              if (friend != null) {
                if (friend['type'] == 0) {
                  sendFriendRequest();
                } else if (friend['type'] == 1 &&
                    friend['idFrom'] == currentFBUser.userId) {
                  // Cancel request
                  sendPushNotification(0);
                } else if (friend['type'] == 1 &&
                    friend['idFrom'] != currentFBUser.userId) {
                  // Accept request
                  sendPushNotification(2);
                } else if (friend['type'] == 2) {
                  // cancel request
                  sendPushNotification(0);
                }
              } else {
                sendFriendRequest();
              }
            },
            child: Text(
              friend == null || friend['type'] == null
                  ? UiStrings.strAddFriend
                  : (friend['type'] == 0
                      ? UiStrings.strAddFriend
                      : (friend['type'] == 1
                          ? (friend['idFrom'] == currentFBUser.userId
                              ? 'Cancel Request'
                              : 'Accept')
                          : 'Unfriend')),
              style: TextStyle(fontSize: 15.0),
            ),
          ),
        ),
        friend == null ||
                friend['type'] == null ||
                friend['type'] == 0 ||
                (friend['type'] == 1 &&
                    friend['idFrom'] == currentFBUser.userId)
            ? Container()
            : space(width: 20.0),
        friend == null ||
                friend['type'] == null ||
                friend['type'] == 0 ||
                (friend['type'] == 1 &&
                    friend['idFrom'] == currentFBUser.userId)
            ? Container()
            : Expanded(
                child: FlatButton(
//      padding: EdgeInsets.symmetric(vertical: 8.0),
                  color: UiColors.red,
                  textColor: UiColors.white,
                  shape: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(4.0)),
                  onPressed: () {
                    if (friend != null) {
                      if (friend['type'] == 1 &&
                          friend['idFrom'] != currentFBUser.userId) {
                        // cancel request
                        sendPushNotification(0);
                      } else if (friend['type'] == 2) {
                        // Open chat screen
                        var route = new MaterialPageRoute(
                          builder: (BuildContext context) => ChatScreen(
                                userId: chatFBUser.userId,
                              ),
                        );
                        Navigator.of(context).push(route);
                      }
                    }
                  },
                  child: Text(
                    friend == null ||
                            friend['type'] == null ||
                            friend['type'] == 0
                        ? ''
                        : (friend['type'] == 2
                            ? UiStrings.strMessage
                            : 'Cancel'),
                    style: TextStyle(fontSize: 15.0),
                  ),
                ),
              )
      ],
    );
  }

  getAgeFromDOB(DateTime dob) {
    var age = (DateTime.now().year - dob.year).toInt();
    return '$age';
  }

  about() {
    if (chatFBUser == null ||
        chatFBUser.aboutYou == null ||
        chatFBUser.aboutYou.isEmpty) {
      return Container();
    }

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        space(height: 20.0),
        Text(
          UiStrings.strAbout,
          style: TextStyle(
              color: UiColors.grey,
              fontSize: 16.0,
              fontWeight: FontWeight.w600),
        ),
        space(height: 10.0),
        Text(
          chatFBUser.aboutYou,
          style: TextStyle(
              color: UiColors.black,
              fontSize: 15.0,
              fontWeight: FontWeight.w400),
        ),
        space(height: 20.0),
      ],
    );
  }

  address() {
    if (chatFBUser == null ||
        chatFBUser.place == null ||
        chatFBUser.place.isEmpty ||
        chatFBUser.isPlacePublic == null ||
        chatFBUser.isPlacePublic) {
      return Container();
    }

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        space(height: 16.0),
        Text(
          UiStrings.strLeaveIn,
          style: TextStyle(
              color: UiColors.grey,
              fontSize: 16.0,
              fontWeight: FontWeight.w600),
        ),
        space(height: 10.0),
        Text(
          chatFBUser.place,
          style: TextStyle(
              color: UiColors.black,
              fontSize: 15.0,
              fontWeight: FontWeight.w400),
        ),
        space(height: 40.0),
      ],
    );
  }

  lookingForChips() {
    if (chatFBUser == null ||
        chatFBUser.lookingFor == null ||
        !chatFBUser.lookingFor.toString().contains('true')) {
      return Container();
    }

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        Text(
          UiStrings.strLookingFor,
          style: TextStyle(
              color: UiColors.grey,
              fontSize: 16.0,
              fontWeight: FontWeight.w600),
        ),
        space(height: 10.0),
        Wrap(
          spacing: 8.0, // gap between adjacent chips
          children: <Widget>[
            chatFBUser == null ||
                    chatFBUser.lookingFor == null ||
                    !chatFBUser.lookingFor.date
                ? Container()
                : Chip(
                    label: Text(
                      UiStrings.arrLookingFor[0].name,
                      style: chipTextStyle,
                    ),
                  ),
            chatFBUser == null ||
                    chatFBUser.lookingFor == null ||
                    !chatFBUser.lookingFor.friendship
                ? Container()
                : Chip(
                    label: Text(
                      UiStrings.arrLookingFor[1].name,
                      style: chipTextStyle,
                    ),
                  ),
            chatFBUser == null ||
                    chatFBUser.lookingFor == null ||
                    !chatFBUser.lookingFor.relationship
                ? Container()
                : Chip(
                    label: Text(
                      UiStrings.arrLookingFor[2].name,
                      style: chipTextStyle,
                    ),
                  ),
            chatFBUser == null ||
                    chatFBUser.lookingFor == null ||
                    !chatFBUser.lookingFor.openRelationship
                ? Container()
                : Chip(
                    label: Text(
                      UiStrings.arrLookingFor[3].name,
                      style: chipTextStyle,
                    ),
                  ),
          ],
        ),
        space(height: 20.0),
      ],
    );
  }

  kidsChips() {
    if (chatFBUser == null ||
        chatFBUser.noOfKids == null ||
        chatFBUser.noOfKids == UiStrings.arrNumberOfKids[0]) {
      return Container();
    }

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        Text(
          '${UiStrings.strKids} ${chatFBUser.noOfKids}',
          style: TextStyle(
              color: UiColors.grey,
              fontSize: 16.0,
              fontWeight: FontWeight.w600),
        ),
        space(height: 10.0),
        Wrap(
          spacing: 8.0, // gap between adjacent chips
          children: <Widget>[
            chatFBUser == null ||
                    chatFBUser.kidsAgeGroup == null ||
                    !chatFBUser.kidsAgeGroup.oneToFive
                ? Container()
                : Chip(
                    label: Text(
                      UiStrings.arrKidsAge[0].name,
                      style: chipTextStyle,
                    ),
                  ),
            chatFBUser == null ||
                    chatFBUser.kidsAgeGroup == null ||
                    !chatFBUser.kidsAgeGroup.sixToTwelve
                ? Container()
                : Chip(
                    label: Text(
                      UiStrings.arrKidsAge[1].name,
                      style: chipTextStyle,
                    ),
                  ),
            chatFBUser == null ||
                    chatFBUser.kidsAgeGroup == null ||
                    !chatFBUser.kidsAgeGroup.thirteenToEighteen
                ? Container()
                : Chip(
                    label: Text(
                      UiStrings.arrKidsAge[2].name,
                      style: chipTextStyle,
                    ),
                  ),
            chatFBUser == null ||
                    chatFBUser.kidsAgeGroup == null ||
                    !chatFBUser.kidsAgeGroup.eighteenPlus
                ? Container()
                : Chip(
                    label: Text(
                      UiStrings.arrKidsAge[3].name,
                      style: chipTextStyle,
                    ),
                  ),
          ],
        ),
        space(height: 20.0),
      ],
    );
  }

  interestChips() {
    if (chatFBUser == null ||
        chatFBUser.interest == null ||
        !chatFBUser.interest.toString().contains('true')) {
      return Container();
    }

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        Text(
          '${UiStrings.strInterest}',
          style: TextStyle(
              color: UiColors.grey,
              fontSize: 16.0,
              fontWeight: FontWeight.w600),
        ),
        space(height: 10.0),
        Wrap(
          spacing: 8.0, // gap between adjacent chips
          children: <Widget>[
            chatFBUser.interest == null || !chatFBUser.interest.yoga
                ? Container()
                : Chip(
                    label: Text(
                      UiStrings.arrInterest[0].name,
                      style: chipTextStyle,
                    ),
                  ),
            chatFBUser.interest == null || !chatFBUser.interest.meditation
                ? Container()
                : Chip(
                    label: Text(
                      UiStrings.arrInterest[1].name,
                      style: chipTextStyle,
                    ),
                  ),
            chatFBUser.interest == null || !chatFBUser.interest.cooking
                ? Container()
                : Chip(
                    label: Text(
                      UiStrings.arrInterest[2].name,
                      style: chipTextStyle,
                    ),
                  ),
            chatFBUser.interest == null || !chatFBUser.interest.traveling
                ? Container()
                : Chip(
                    label: Text(
                      UiStrings.arrInterest[3].name,
                      style: chipTextStyle,
                    ),
                  ),
            chatFBUser.interest == null || !chatFBUser.interest.pets
                ? Container()
                : Chip(
                    label: Text(
                      UiStrings.arrInterest[4].name,
                      style: chipTextStyle,
                    ),
                  ),
            chatFBUser.interest == null || !chatFBUser.interest.reading
                ? Container()
                : Chip(
                    label: Text(
                      UiStrings.arrInterest[5].name,
                      style: chipTextStyle,
                    ),
                  ),
            chatFBUser.interest == null || !chatFBUser.interest.goingToMovies
                ? Container()
                : Chip(
                    label: Text(
                      UiStrings.arrInterest[6].name,
                      style: chipTextStyle,
                    ),
                  ),
            chatFBUser.interest == null || !chatFBUser.interest.gardening
                ? Container()
                : Chip(
                    label: Text(
                      UiStrings.arrInterest[7].name,
                      style: chipTextStyle,
                    ),
                  ),
            chatFBUser.interest == null || !chatFBUser.interest.exercise
                ? Container()
                : Chip(
                    label: Text(
                      UiStrings.arrInterest[8].name,
                      style: chipTextStyle,
                    ),
                  ),
            chatFBUser.interest == null || !chatFBUser.interest.listeningToMusic
                ? Container()
                : Chip(
                    label: Text(
                      UiStrings.arrInterest[9].name,
                      style: chipTextStyle,
                    ),
                  ),
            chatFBUser.interest == null || !chatFBUser.interest.volunteerWork
                ? Container()
                : Chip(
                    label: Text(
                      UiStrings.arrInterest[10].name,
                      style: chipTextStyle,
                    ),
                  ),
          ],
        )
      ],
    );
  }

  getFLName() {
    if (chatFBUser == null) return UiStrings.strProfile;

    String firstName = chatFBUser.firstName == null ? '' : chatFBUser.firstName;

    String lastName = chatFBUser.lastName == null ? '' : chatFBUser.lastName;

    return '$firstName $lastName';
  }

  getFLNameOfSender() {
    if (currentFBUser == null) return UiStrings.strProfile;

    String firstName =
        currentFBUser.firstName == null ? '' : currentFBUser.firstName;

    String lastName =
        currentFBUser.lastName == null ? '' : currentFBUser.lastName;

    return '$firstName $lastName';
  }

  getOnlineStatus() {
    if (chatFBUser == null) return '';

//    fbUser == null ? '' : fbUser.isOnline ? 'Online' : fbUser.lastActive.toString()

    if (chatFBUser.isOnline != null && chatFBUser.isOnline) {
      return 'Online';
    } else if (chatFBUser.lastActive != null) {
//      String lastSeen = DateFormat('dd MMM kk:mm').format(
//          DateTime.fromMillisecondsSinceEpoch(
//              int.parse(fbUser.lastActive)));
      String lastSeen = DateTimeUtil.readTimestamp(
          Instant.fromEpochMilliseconds(int.parse(chatFBUser.lastActive))
              .toDateTimeUtc()
              .millisecondsSinceEpoch);
      return 'last seen $lastSeen';
    } else {
      return '';
    }
  }

  void sendFriendRequest() {
    showDialog(
      context: context,
      builder: (BuildContext context) {
        return AlertDialog(
          title: Text('Add ${getFLName()} as a Friend'),
          content: Text(
              'You are about to add ${getFLName()} as a friend list. We will then notify ${getFLName()}, who will have to confirm that you are friends.'),
          actions: <Widget>[
            FlatButton(
              child: Text('Cancel'),
              onPressed: () {
                Navigator.of(context).pop();
              },
            ),
            FlatButton(
              child: Text(UiStrings.strAddFriend),
              // Type  0 = unFriend, 1 = Send Friend Request, 2 = Friends
              onPressed: () {
                // send friend request
                sendPushNotification(1);
                Navigator.of(context).pop();
              },
            ),
          ],
        );
      },
    );
  }

  sendPushNotification(int type) async {
    // Type  0 = unFriend, 1 = Send Friend Request, 2 = Friends

    Dio dio = Dio();

    Map<String, dynamic> headerMap = {
      'Authorization': UiStrings.fcmKey,
    };

    List tokens = [token];
    print('tokens : $tokens');
    String title = getFLNameOfSender();
    String body = '$title Sent you a friend request';

    Map<String, dynamic> message = {
      'idFrom': userId,
      'idTo': chatFBUser.userId,
      'timestamp':
          Instant.now().toDateTimeUtc().millisecondsSinceEpoch.toString(),
      'content': body,
      'type': type
    };

    FBUserDelegate.updateFriendRequestStatus(
        currentFBUser, chatFBUser, message);

    if (type == 0) {
      return;
    }

    var response = await dio.post(UiStrings.fcmUrlToSendNotification,
        data: {
          'notification': {'title': title, 'body': body},
          'data': {
            'click_action': 'FLUTTER_NOTIFICATION_CLICK',
            'idFrom': userId,
            'idTo': chatFBUser.userId,
            'timestamp':
                Instant.now().toDateTimeUtc().millisecondsSinceEpoch.toString(),
            'content': body,
            'type': type,
            'notiType': 2
          },
          'registration_ids': tokens,
        },
        options: new Options(
            contentType: ContentType.parse("application/json"),
            headers: headerMap));
    print('FCM API call Response : ${response.data}');
  }
}

```

**Comment by mraleph** [comment]
@Pareshoct7 the error you are getting is absolutely correct. You can't do `import 'dart:_http';`. Just remove that line.

**Comment by Pareshoct7** [comment]
@mraleph  Thank you solution worked for me.

**Comment by mraleph** [comment]
@Pareshoct7 do you remember where did you copy that line from?

**Comment by Pareshoct7** [comment]
@mraleph actually i did not copied that line but some how imported using suggetion in android studio. Might be I used some library that uses thi thing or something like that but I am sure that i did not copied it is imported from suggetions.

**Comment by zoechi** [comment]
@mraleph There was a similar mention https://github.com/flutter/flutter/issues/17016#issuecomment-443456241 but also not clear what led to that.

**Comment by nandofalcao** [comment]
Hello everyone! This work for me:

**1) Download ios-deploy from:**
- https://raw.githubusercontent.com/kangwang1988/kangwang1988.github.io/master/others/ios-deploy

**2) Set permissions for ios-deploy**
- chmod +x ios-deploy

**3) Move**
- mv ios-deploy /usr/local/Cellar/ios-deploy/1.9.4/bin

**For iOS 13 beta. Download XCode Beta and set to default on terminal:**
- sudo xcode-select -switch /Applications/Xcode-beta.app

References:
- https://developer.apple.com/library/archive/technotes/tn2339/_index.html
- https://medium.com/@fredriccliver/device-doesnt-support-wireless-sync-amdevicestartservice-880f2050c2bc
