### ISSUE TITLE
Gifs run slower than expected

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#24804]
## Steps to Reproduce

1. Have a gif file
2. Have code like final Image image = Image.file(File('gif_file_path'), fit: BoxFit.contain);
3. Compare gif in chrome with flutter and notice it repeats or runs slower in Flutter

Here's an example video: https://www.youtube.com/watch?v=EoLbQRfTSbM

## Flutter Doctor
```
$ flutter doctor -v
[✓] Flutter (Channel master, v0.11.11-pre.7, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.11.11-pre.7 at /Users/KG/Developer/Flutter/flutter
    • Framework revision bcac1bd5e2 (37 minutes ago), 2018-11-27 14:44:53 -0800
    • Engine revision 5bf4deb435
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 29.1.3
    • Dart plugin version 182.4892.25

[!] VS Code (version 1.21.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

```

**Comment by eseidelGoogle** [comment]
My recollection from my web days is that GIFs can have timing information in them.  I wonder if we're respecting that in our playback with Skia or if we're just doing a frame per frame?  (e.g. this gif could have more than 60fps in it so when it plays back if we're only playing one frame per frame it would be slow).

iirc @amirh added our GIF support?  @chinmaygarde may also know.

**Comment by amirh** [comment]
Current scheduling logic is:

1. Try to decode next GIF frame (or fetch it from cache)
2. When the GIF frame is available wait for the next flutter frame, if the time elapsed since showing previous frame is greater than the GIF frame duration, wait the remaining time, otherwise show the frame.

**Comment by amirh** [comment]
We are currently partially respecting GIF frame durations, that is: we will wait the specified duration for the current GIF frame before showing the next frame, but we won't skip GIF frames if the duration is smaller than Flutter's frame rate.

We should fix that, but I'd also say that if you need such a high frame rate you probably should be using a video.

My guess here would be that we're just not decoding frames fast enough...

@KevinTheGray is the gif in questions running more than 60fps?
Can you share the file so we can investigate?

**Comment by amirh** [comment]
The GIF file was sent to me, it is a 50 fps GIF (frameDuration for all frames is 0.02 seconds).

On a 60 FPS display our current scheduling logic will advance a 50 FPS GIF not faster than 30FPS:

1. We show frame n at t_1
2. We wait for ~0.02 seconds (so we just missed the next Flutter frame which was at t_1+~0.016).
3. We show frame n+1 at the next Flutter frame which is t_1+~0.03.

I prototyped an alternative scheduling logic, which minimizes the absolute timing error by allowing scheduling a GIF frame on an earlier Flutter frame if that results in a smaller absolute timing error.
(the quick prototype is hardcoded to assume that Flutter is rendering at 60FPS).
The prototype does play the 50FPS GIF better, patch is available here: https://github.com/amirh/flutter/tree/minimize_scheduling_error

I'm not 100% sure that this proposal is better as a general solution as it might result in varying frame rate which I guess might feel strange. Additionally we cannot just assume that Flutter renders at 60FPS.

In general for high frame rates I'd definitely discourage using GIFs, videos are a better choice.

Our current GIF scheduling logic is more optimized for low frame rates than the patch mentioned above, which I believe is the more common use case.

**Comment by TahaTesser** [comment]
Using https://media.giphy.com/media/g9582DNuQppxC/source.gif 

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  final Image image = Image.asset('assets/highfps.gif');

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: image,
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.24.0-8.0.pre.375, on macOS 11.0.1 20B29
    darwin-x64, locale en-GB)
    • Flutter version 1.24.0-8.0.pre.375 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision a7f5fd5360 (26 hours ago), 2020-11-30 13:14:13 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 11.0.1 20B29
      darwin-x64
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome
      87.0.4280.67

• No issues found!
```

</details>

**Comment by armoghaddam** [comment]
Flutter are RIDE

**Comment by emmett-deen** [comment]
Still having issues with this on flutter web in 2021. Is there a certain framerate that runs perfectly only flutter web?

**Comment by Binozo** [comment]
Same problem with [this GIF](https://cdn.discordapp.com/attachments/414258067870449665/445736475158380544/discord.gif)
