### ISSUE TITLE
url_launcher: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag

### ISSUE THREAD

**Issue by leoshak** [flutter/flutter#24866]
I cloned the Flutter repo today to check why following error occur when using url_launcher. I have tried latest package and also placing `any`. Most importantly when it is not working I just copy pasted the doc example: https://flutter.io/docs/development/packages-and-plugins/using-packages but still I get the same error message, no luck.

## Log

```
E/MethodChannel#plugins.flutter.io/url_launcher(31054): Failed to handle method call
E/MethodChannel#plugins.flutter.io/url_launcher(31054): android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
E/MethodChannel#plugins.flutter.io/url_launcher(31054):         at android.app.ContextImpl.startActivity(ContextImpl.java:1140)
E/MethodChannel#plugins.flutter.io/url_launcher(31054):         at android.app.ContextImpl.startActivity(ContextImpl.java:1127)
E/MethodChannel#plugins.flutter.io/url_launcher(31054):         at android.content.ContextWrapper.startActivity(ContextWrapper.java:311)
E/MethodChannel#plugins.flutter.io/url_launcher(31054):         at io.flutter.plugins.urllauncher.UrlLauncherPlugin.onMethodCall(UrlLauncherPlugin.java:61)
E/MethodChannel#plugins.flutter.io/url_launcher(31054):         at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#plugins.flutter.io/url_launcher(31054):         at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#plugins.flutter.io/url_launcher(31054):         at android.os.MessageQueue.nativePollOnce(Native Method)E/MethodChannel#plugins.flutter.io/url_launcher(31054):         at android.os.MessageQueue.next(MessageQueue.java:138)
E/MethodChannel#plugins.flutter.io/url_launcher(31054):         at android.os.Looper.loop(Looper.java:150)
E/MethodChannel#plugins.flutter.io/url_launcher(31054):         at android.app.ActivityThread.main(ActivityThread.java:5398)
E/MethodChannel#plugins.flutter.io/url_launcher(31054):         at java.lang.reflect.Method.invokeNative(Native Method)
E/MethodChannel#plugins.flutter.io/url_launcher(31054):         at java.lang.reflect.Method.invoke(Method.java:515)
E/MethodChannel#plugins.flutter.io/url_launcher(31054):         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:940)
E/MethodChannel#plugins.flutter.io/url_launcher(31054):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
E/MethodChannel#plugins.flutter.io/url_launcher(31054):         at dalvik.system.NativeStart.main(Native Method)
E/flutter (31054): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (31054): PlatformException(error, Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?, null)
E/flutter (31054): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter (31054): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
E/flutter (31054): <asynchronous suspension>
E/flutter (31054): #2      launch (package:url_launcher/url_launcher.dart:66:19)
E/flutter (31054): #3      DemoPage.launchURL (package:nov29long/main.dart:19:5)
E/flutter (31054): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
E/flutter (31054): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
E/flutter (31054): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter (31054): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter (31054): #8      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
E/flutter (31054): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
E/flutter (31054): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter (31054): #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter (31054): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:180:19)
E/flutter (31054): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
E/flutter (31054): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
E/flutter (31054): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (31054): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter (31054): #17     _invoke1 (dart:ui/hooks.dart:168:13)
E/flutter (31054): #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
```

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.11.12, on Microsoft Windows [Version 10.0.14393], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    X Android license status unknown.
[√] Android Studio (version 3.1)
[√] IntelliJ IDEA Community Edition (version 2017.3)
[√] IntelliJ IDEA Community Edition (version 2018.1)
[√] VS Code, 32-bit edition
[√] VS Code, 64-bit edition (version 1.29.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

```

**Comment by leoshak** [comment]
Ops! the issue is not the flutter but the package url_launcher, when I decrease the version to 3.0.3, according to this answer: https://stackoverflow.com/questions/53497475/flutter-calling-startactivity-from-outside-of-an-activity-context-requires-th its fixed.

**Comment by Xbobo5530** [comment]
##Similar issue
Hey guys, just upgraded to the latest version of the `url_launcher: ^4.0.2`

here is the log

##Log
```
E/MethodChannel#plugins.flutter.io/url_launcher(26106): Failed to handle method call
E/MethodChannel#plugins.flutter.io/url_launcher(26106): android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
E/MethodChannel#plugins.flutter.io/url_launcher(26106): 	at android.app.ContextImpl.startActivity(ContextImpl.java:672)
E/MethodChannel#plugins.flutter.io/url_launcher(26106): 	at android.app.ContextImpl.startActivity(ContextImpl.java:659)
E/MethodChannel#plugins.flutter.io/url_launcher(26106): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)
E/MethodChannel#plugins.flutter.io/url_launcher(26106): 	at io.flutter.plugins.urllauncher.UrlLauncherPlugin.onMethodCall(UrlLauncherPlugin.java:61)
E/MethodChannel#plugins.flutter.io/url_launcher(26106): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#plugins.flutter.io/url_launcher(26106): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#plugins.flutter.io/url_launcher(26106): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/url_launcher(26106): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#plugins.flutter.io/url_launcher(26106): 	at android.os.Looper.loop(Looper.java:135)
E/MethodChannel#plugins.flutter.io/url_launcher(26106): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
E/MethodChannel#plugins.flutter.io/url_launcher(26106): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/url_launcher(26106): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/MethodChannel#plugins.flutter.io/url_launcher(26106): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E/flutter (26106): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (26106): PlatformException(error, Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?, null)
E/flutter (26106): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter (26106): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
E/flutter (26106): <asynchronous suspension>
E/flutter (26106): #2      launch (package:url_launcher/url_launcher.dart:66:19)
E/flutter (26106): #3      _MainModel&Model&AccountModel&NavModel._launchURL (package:kijiweni_flutter/src/models/nav_model.dart:82:11)
E/flutter (26106): <asynchronous suspension>
E/flutter (26106): #4      _MainModel&Model&AccountModel&NavModel.handleAppInfoAction (package:kijiweni_flutter/src/models/nav_model.dart:73:7)
E/flutter (26106): #5      AppInfoView.build._showAppInfoDialog (package:kijiweni_flutter/src/views/app_info_view.dart:41:13)
E/flutter (26106): <asynchronous suspension>
E/flutter (26106): #6      AppInfoView.build.<anonymous closure>.<anonymous closure> (package:kijiweni_flutter/src/views/app_info_view.dart:47:50)
E/flutter (26106): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
E/flutter (26106): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
E/flutter (26106): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter (26106): #10     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter (26106): #11     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
E/flutter (26106): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
E/flutter (26106): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter (26106): #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter (26106): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:180:19)
E/flutter (26106): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
E/flutter (26106): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
E/flutter (26106): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (26106): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter (26106): #20     _invoke1 (dart:ui/hooks.dart:168:13)
E/flutter (26106): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
```

**Comment by ened** [comment]
Looks like already fixed in GIT, but not yet published to pub.

To use the latest version, you can include it this way in your pubspec.yaml:

```
  url_launcher:
    git:
      url: git://github.com/flutter/plugins
      path: packages/url_launcher
```

**Comment by hungdt-ibl** [comment]
@ened ene
```
Error on line 19, column 5 of pubspec.yaml: A dependency may only have one source.
    url: git://github.com/flutter/plugins
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
error when i'm try using git as dependencies

**Comment by I-am-original** [comment]
@zoechi when we can expect fixed version of plugin? Estimated time. Or it is better used ref to github?
Thanks

**Comment by yathit** [comment]
Is this fix landed in beta channel?

**Comment by zoechi** [comment]
@leoshak can you confirm?

**Comment by zoechi** [comment]
5.0.0 was published and I assume this contains this fix. 
Please let me know if this is not the case and I'll reopen.

**Comment by MarcelEdward** [comment]
It is not working on 5.0.1, I get this:

E/flutter (13141): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method launch on channel plugins.flutter.io/url_launcher)
E/flutter (13141): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
E/flutter (13141): <asynchronous suspension>
E/flutter (13141): #1      launch (package:url_launcher/url_launcher.dart:54:19)
E/flutter (13141): #2      _MyHomePageState.scan (package:produvaroxo/main.dart:1459:17)
E/flutter (13141): <asynchronous suspension>
E/flutter (13141): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:513:14)
E/flutter (13141): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:568:30)
E/flutter (13141): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:120:24)
E/flutter (13141): #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter (13141): #7      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
E/flutter (13141): #8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (13141): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:20)
E/flutter (13141): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:192:22)
E/flutter (13141): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:149:7)
E/flutter (13141): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (13141): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter (13141): #14     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (13141): #15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (13141): #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (13141): #17     _invoke1 (dart:ui/hooks.dart:209:10)
E/flutter (13141): #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)

**Comment by Erwin0Maleki** [comment]
this is version 5.0.2 and still not fixed! even installing url_launcher cause crashing in app

**Comment by Abdelmjid-ASOUAB** [comment]
Version 5.0.2 not fixed !! the same problem with it

**Comment by up3** [comment]
same here, just installing url_launcher (without calling it on the code) causes the app to crash/not open. 
For us, this happens to our Moto Z3, but not in iOS or Nexus 5x android emulator.

**Comment by encrypt0r** [comment]
I am using 5.0.2 and it doesn't even build! I am using the Nexus 5X android emulator
@zoechi please re-open the issue

**Comment by rymotion** [comment]
I actually did get it to work but check this out it’s not properly formatted and I will be adjusting it once I can:

// MARK: Opens embeded urls if any
  _checkLaunch(String urlScheme) async {
    if (await canLaunch(urlScheme)) {
      await launch(urlScheme);
    } else {
      if (urlScheme.contains('//')) {
        // var somethingBack = urlScheme.split('//');
        var somethingBack = urlScheme.replaceFirst('//', 'https:');
        _checkLaunch(somethingBack);
      } else if (urlScheme == " " || urlScheme == null) {
        return new SimpleDialog(
          children: <Widget>[
            new Center(
              child: new Container(
                  child: new Text(
                      'Null link.')),
            )
          ],
        );
      } else {
        // TODO: Add dialog window
        showDialog(
            context: context,
            builder: (context) {
              return new SimpleDialog(
                children: <Widget>[
                  new Center(
                    child: new Container(
                        child: new Text(
                            'You may be missing a required application\nfor $urlScheme')),
                  )
                ],
              );
            });
        throw 'invalid urlSceme: $urlScheme';
        // _callError();
      }
    }
    // launch(urlScheme);
  }

**Comment by saeid-pm** [comment]
In may case needed to do 'Packages upgrade' too,  then problem resolved.

**Comment by vitor-gyant** [comment]
When will the fix arrive ? Thanks

**Comment by theindianappguy** [comment]
Still Not Working for me

**Comment by mdmota** [comment]
problem continues in  url_launcher: ^5.5.0 android
Any news?

**Comment by ShakeebIqbal** [comment]
`<activity android:name="io.flutter.plugins.urllauncher.WebViewActivity"
            android:theme="@android:style/Theme.NoTitleBar.Fullscreen"
            android:exported="false"/>`
Just add This Line of code in Manifest file android/app/src/main/kotlin

**Comment by ShakeebIqbal** [comment]
url_launcher issue not opening in android
`<activity android:name="io.flutter.plugins.urllauncher.WebViewActivity" android:theme="@android:style/Theme.NoTitleBar.Fullscreen" android:exported="false"/>`
Just add This Line of code in Manifest file android/app/src/main/kotlin

**Comment by MojtabaTavakkoli** [comment]
Still got the issue in `url_launcher: ^6.0.9`.
```

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':url_launcher'.
> Could not resolve all artifacts for configuration ':url_launcher:classpath'.
   > Could not find gradle-3.4.2.jar (com.android.tools.build:gradle:3.4.2).
```
