### ISSUE TITLE
Skia regression in v1.1.1

### ISSUE THREAD

**Issue by VolodymyrLykhonis** [flutter/flutter#25426]
## Overview

Issue is not reproducible on Android, iPhone simulators. It's not reproducible on v1.1.0 nor v1.0.0. A flutter version affected is v1.1.1 and detected when run on iPhone 6 device.

Issue was discovered when used Flare framework to render animations. Below are the assets that can be used for debugging the issue only.

## Steps to Reproduce

1. Create sample flutter app
2. Replace main.dart with code below
3. Place https://drive.google.com/file/d/1t4XKIZ7BaNA6IEKA2bLQBtng5iuQzTBQ/view?usp=sharing into `./assets/skia_bug.flr`.
4. Change `pubspec.yaml` to include `flare_flutter` and `skia_bug.flr`. For example:
```yaml
# This is pubspec.yaml
name: i25426
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flare_flutter:

flutter:

  uses-material-design: true

  assets:
  - assets/skia_bug.flr
```
5. Launch on iPhone 6 (may be other iOS) device, not **simulator**.

`main.dart`
```dart
import 'package:flutter/material.dart';
import 'package:flare_flutter/flare_actor.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.white,
      constraints: const BoxConstraints.expand(),
      child: FlareActor(
        'assets/skia_bug.flr',
        animation: 'idle',
        alignment: Alignment.center,
        fit: BoxFit.contain,
      ),
    );
  }
}
```

## Logs
https://gist.github.com/VolodymyrLykhonis/df95a0b70b90b11a3a4a17d04666d522

```
Volodymyrs-MacBook-Pro:skia_bug Vladimir$ flutter analyze
Analyzing skia_bug...                                            
No issues found! (ran in 1.1s)
```

```
Volodymyrs-MacBook-Pro:skia_bug Vladimir$ flutter doctor -v
[✓] Flutter (Channel unknown, v1.1.1, on Mac OS X 10.14.1 18B75, locale en-US)
    • Flutter version 1.1.1 at /Users/Vladimir/Projects/github.com/flutter
    • Framework revision 65df90d8b5 (4 days ago), 2018-12-11 19:29:13 -0800
    • Engine revision 25b58c0c67
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/Vladimir/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 23.1.3
    • Dart plugin version 181.4203.498

[✓] VS Code (version 1.30.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • Volodymyr’s iPhone • f6eace90c1db4e5f27bbe4ef3d8b9cf20338b0bd • ios • iOS 12.1

• No issues found!
```

**Comment by VolodymyrLykhonis** [comment]
Here is a video showing the issue
https://photos.app.goo.gl/65yQ2NR5b8FQuJPK7

**Comment by jvanverth** [comment]
That change is causing similar issues in Android, so I reverted it and will revisit it in the New Year.

**Comment by liyuqian** [comment]
Thank you Jim! This issue should be fixed once https://skia.googlesource.com/skia.git/+/1694a8604be7399a0b445c9b7814b9d40cc9de9a gets rolled into flutter/engine and flutter/flutter.

**Comment by mehmetf** [comment]
@liyuqian 

Where are we with this issue?

**Comment by liyuqian** [comment]
The Skia auto-roller still seems to be blocked on https://github.com/flutter/flutter/issues/25462 so the fix is not rolled in the engine yet. @cbracken and @rmistry may have more info about when the Skia auto-roller can resume.

**Comment by cbracken** [comment]
The fix for #25462 landed yesterday; the auto-roller should be able to resume anytime.

**Comment by rmistry** [comment]
The autoroller is still not working. See this comment: https://github.com/flutter/flutter/issues/25462#issuecomment-448280218

It is likely an issue with the roller setup, but I am not sure how to proceed.

**Comment by cbracken** [comment]
Following up over chat; probably quicker :)

**Comment by mehmetf** [comment]
https://github.com/flutter/flutter/issues/25462 is closed. Status update please?

**Comment by liyuqian** [comment]
It's in the flutter/engine. Unfortunately, the Mac engine buildbot is now having trouble so the engine-to-framework roller could not start merging it.

**Comment by liyuqian** [comment]
This should now be fixed by https://github.com/flutter/flutter/pull/25529
