### ISSUE TITLE
Webview issue with keyboard

### ISSUE THREAD

**Issue by DevFatani** [flutter/flutter#25436]
Could not show keyboard on webview

<img src="https://media.giphy.com/media/93fK5p0zGuulONaFIt/giphy.gif" />
## Logs

```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.13.6 17G3025, locale en-SA)
    • Flutter version 1.0.0 at /Users/DevFatani/Developer/flutter-sdk-2
    • Framework revision 5391447fae (2 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/DevFatani/Library/Android/sdk
    • Android NDK at /Users/DevFatani/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[!] VS Code (version 1.30.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API
      28) (emulator)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by DevFatani** [comment]
This problem is only on [Android]. On iOS work fine, I just [download](https://github.com/flutter/plugins/tree/master/packages/webview_flutter) the example and run into my android device and keyboard never show

**Comment by mattijsf** [comment]
I think this is caused by https://github.com/flutter/engine/pull/5845

**Comment by amirh** [comment]
Duplicate of #19718

**Comment by Kayson91** [comment]
FocusNode _focusNode = FocusNode();
  WebViewController _webViewController;
  TextEditingController _textController;
  bool _isLoading = true;
  Size _deviceSize;

  @override
  Widget build(BuildContext context) {
    _deviceSize = MediaQuery.of(context).size;
    // handle the backbutton behaviour inside the webview
    return WillPopScope(
      child: Scaffold(
        appBar: WAppBar(title: "My keyboard web view"),
        body: SafeArea(
          child: SingleChildScrollView(
            child: Container(
              width: _deviceSize.width,
              height: _deviceSize.height,
              child: Center(
                child: Stack(
                  children: <Widget>[
                    // Creating a TextField hidden behind the WebView and adding the input to the Websites input field using Javascript
                    Container(
                      height: 50,
                      width: _deviceSize.width,
                      child: TextField(
                        focusNode: _focusNode,
                        controller: _textController,
                        onSubmitted: (_) {
                          _webViewController.evaluateJavascript('''
                            if (input != null) {
                              input.submit();
                            }''');
                          _focusNode.unfocus();
                        },
                        onChanged: (input) {
                          _webViewController.evaluateJavascript('''
                            if (input != null) {
                              input.value = '$input';
                            }''');
                        },
                      ),
                    ),
                    Container(
                      height: _deviceSize.height,
                      child: WebView(
                        initialUrl: widget.url,
                        gestureRecognizers: Set()
                          ..add(
                            Factory<VerticalDragGestureRecognizer>(
                              () => VerticalDragGestureRecognizer(),
                            ),
                          ),
                        navigationDelegate: (_) {
                          _focusNode.unfocus();
                          setState(
                            () => _isLoading = true,
                          );
                          return NavigationDecision.navigate;
                        },
                        // nothing works without unrestricted JavascriptMode
                        javascriptMode: JavascriptMode.unrestricted,
                        javascriptChannels: Set.from(
                          [
                            // Listening for Javascript messages to get Notified of Focuschanges and the current input Value of the Textfield.
                            JavascriptChannel(
                              name: 'Focus',
                              // get notified of focus changes on the input field and open/close the Keyboard.
                              onMessageReceived: (JavascriptMessage focus) {
                                print(focus.message);
                                if (focus.message == 'focus') {
                                  FocusScope.of(context)
                                      .requestFocus(_focusNode);
                                } else if (focus.message == 'focusout') {
                                  _focusNode.unfocus();
                                  _textController.text = "";
                                  _webViewController.evaluateJavascript('''
                                    input = null;
                                  ''');
                                }
                              },
                            ),
                            JavascriptChannel(
                              name: 'InputValue',
                              // set the value of the native input field to the one on the website to always make sure they have the same input.
                              onMessageReceived: (JavascriptMessage value) {
                                _textController.value =
                                    TextEditingValue(text: value.toString());
                              },
                            )
                          ],
                        ),
                        onWebViewCreated: (controller) =>
                            _webViewController = controller,
                        onPageFinished: (_) {
                          /* 
                                if you have control over the Website you can set your own ids which is much saver than the method
                                used in this example which could break due to changes on the website. But as long as you're able 
                                to find the Input elements you can use this approach.
                              */
                          _webViewController.evaluateJavascript('''
                            inputs = document.querySelectorAll("input[type=text]");
                            inputs.forEach(function(inp) {
                              let finalInput = inp;
                              finalInput.addEventListener("focus", function() {
                                console.log('focus');
                                input = finalInput;
                                InputValue.postMessage('');
                                Focus.postMessage('focus');
                              });
                              finalInput.addEventListener("focusout", function() {
                                console.log('unfocus');
                                Focus.postMessage('focusout');
                              });
                          });
                            ''');
                          setState(
                            () => _isLoading = false,
                          );
                        },

                      ),
                    ),
                    // overlay to show ProgressIndicator while loading.
                    _isLoading
                        ? Container(
                            width: _deviceSize.width,
                            height: _deviceSize.height,
                            color: Colors.white,
                            child: Center(
                              child: CircularProgressIndicator(),
                            ),
                          )
                        : Container()
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }

**Comment by Kayson91** [comment]
The solution is to add an interaction bridge in the webview with JavaScript:

_webViewController.evaluateJavascript('''
                            inputs = document.querySelectorAll("input[type=text]");
                            inputs.forEach(function(inp) {
                              let finalInput = inp;
                              finalInput.addEventListener("focus", function() {
                                console.log('focus');
                                input = finalInput;
                                InputValue.postMessage('');
                                Focus.postMessage('focus');
                              });
                              finalInput.addEventListener("focusout", function() {
                                console.log('unfocus');
                                Focus.postMessage('focusout');
                              });
                          });
                            ''');

**Comment by Kayson91** [comment]
The solution is to add an interaction bridge in the webview with JavaScript:

```
_webViewController.evaluateJavascript('''
        inputs = document.querySelectorAll("input[type=text]");
        inputs.forEach(function(inp) {
            let finalInput = inp;
            finalInput.addEventListener("focus", function() {
                console.log('focus');
                input = finalInput;
                InputValue.postMessage('');
                Focus.postMessage('focus');
           });
           finalInput.addEventListener("focusout", function() {
               console.log('unfocus');
               Focus.postMessage('focusout');
           });
      });
''');
```

**Comment by urmamb** [comment]
@Kayson91 with your solution keyboard pops up and down several times and the input field is not populating with text. We hope flutter soon finds a fix for it.

**Comment by Kayson91** [comment]
@urmamb it works for me but when you change the field the previous data is copied.

**Comment by Delicate-lee** [comment]
you can use 'flutter_webview_plugin', it works for me

**Comment by abdielcr** [comment]
> you can use 'flutter_webview_plugin', it works for me


it does not work with navigation drawer, it appears in front of all the content, because it is not a native flutter widget

**Comment by Pitrr** [comment]
Did anyone find a reliable solution?

**Comment by tidharnitzan** [comment]
So...any solution? this is a real deal breaker...

**Comment by jameszhao-io** [comment]
Me too. One product of mine is highly depended on this webview plugin and the keyboard issue is a terrible problem. Hope some one will solve this problem...

**Comment by Kayson91** [comment]
> Me too. One product of mine is highly depended on this webview plugin and the keyboard issue is a terrible problem. Hope some one will solve this problem...

What do you really want to do with the webview, because I had problems too but I could find an alternative.

**Comment by amirh** [comment]
Please see https://github.com/flutter/flutter/issues/19718

**Comment by Kayson91** [comment]
> Please see #19718

for sure this issue was fixed with the flutter team see this [https://pub.dev/packages/flutter_webview_plugin](url), but you need to use the latest stable release of the Flutter SDK.

**Comment by moxorama** [comment]
@veselinnguyen - Try to look at I/O->Keyboard->Toggle software keyboard in your Simulator menu.

**Comment by crypto-maria** [comment]
> @veselinnguyen - Try to look at I/O->Keyboard->Toggle software keyboard in your Simulator menu.

Thanks, problem solved, it doesn't have to do anything with flutter channel. @moxorama thanks for the debug.

**Comment by wahyu-handayani** [comment]
I have the same problem like @veselinnguyen and I have tried to look at look at I/O->Keyboard-> and then check the Toggle software keyboard, but the problem still exist, I can not type something inside webview.. is there something that I should add?

**Comment by rafayali** [comment]
Facing same issue as well. I am on stable 2.0.6 using webview_flutter 2.0.4 and keyboard wont show up on iOS simulator. Tried solution by @moxorama to Toggle software keyboard and still facing same issue.

**Comment by rafayali** [comment]
Unchecked  **Hardware > Keyboard > Connect to external keyboard** and soft keyboard would now show up on simulator as suggested in this post https://stackoverflow.com/questions/27644375/keyboard-isnt-visible-when-clicking-text-input-of-uiwebview/30142114#30142114

<img src="https://user-images.githubusercontent.com/1373965/117069954-8ffd7300-ad46-11eb-91b9-debe691a5c89.png" height="720"/>
