### ISSUE TITLE
Race condition crash because of doing background work on GPU on iOS

### ISSUE THREAD

**Issue by Arnold134777** [flutter/flutter#26366]
Internal: b/140829173

## Steps to Reproduce

```
  1. click to jump to flutter page, at the same time back to background
  2. iphone6, 6plus, 5s device
```

```
[✓] Flutter (Channel faceu_dev_1.0.0, v1.0.1-pre.5, on Mac OS X 10.13.6 17G65,
    locale zh-Hans-CN)
    • Flutter version 1.0.1-pre.5 at
      /Users/xiongzhuang/Documents/study/flutter/flutter
    • Framework revision 0fd43583b8 (5 weeks ago), 2018-12-09 19:12:32 +0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.io/setup/#android-setup for detailed
      instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME
      to that location.
      You may also want to add it to your PATH environment variable.


[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed
      instructions).

[!] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

```

**Comment by Arnold134777** [comment]
Our app on-line has many crashes about this.

**Comment by zoechi** [comment]
> 1. click to jump to flutter page, at the same time back to background

Can you please elaborate? What does "jump to flutter page" and "back to background" mean?

Can you provide a minimal reproduction?

**Comment by zoechi** [comment]
Is 

> Crashed: io.flutter.1.gpu EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000001 gldUpdateDispatch

the full error output?

**Comment by Arnold134777** [comment]
> > 1. click to jump to flutter page, at the same time back to background
> 
> Can you please elaborate? What does "jump to flutter page" and "back to background" mean?
> 
> Can you provide a minimal reproduction?

Our app has native and flutter page, we crate a entry can jump to a flutter page. According to online user reponses, we find almost action is click the entry button, and press home to back to background.

**Comment by Arnold134777** [comment]
> Is
> 
> > Crashed: io.flutter.1.gpu EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000001 gldUpdateDispatch
> 
> the full error output?

@zoechi According to the Fabirc crash description：

Heads Up!
OpenGL rendering while app in background state

Crashed: io.flutter.1.gpu
0  libGPUSupportMercury.dylib     0x1bf3a6f28 gpus_ReturnNotPermittedKillClient + 12
1  AGXGLDriver                    0x1c3b818d0 gldUpdateDispatch + 7216
2  libGPUSupportMercury.dylib     0x1bf3a7f04 gpusSubmitDataBuffers + 176
3  AGXGLDriver                    0x1c3b82e18 gldUpdateDispatch + 12664
4  GLEngine                       0x1c4ddd4e4 gliPresentViewES_Exec + 188
5  OpenGLES                       0x1a57a7a8c -[EAGLContext presentRenderbuffer:] + 80
6  Flutter                        0x103a71124 shell::IOSSurfaceGL::GLContextPresent() + 176
7  Flutter                        0x103dc4f64 std::__1::__function::__func<shell::GPUSurfaceGL::AcquireFrame(SkISize const&)::$_1, std::__1::allocator<shell::GPUSurfaceGL::AcquireFrame(SkISize const&)::$_1>, bool (shell::SurfaceFrame const&, SkCanvas*)>::operator()(shell::SurfaceFrame const&, SkCanvas*&&) + 400
8  Flutter                        0x103ac3c20 shell::SurfaceFrame::Submit() + 112
9  Flutter                        0x103ab6c84 shell::Rasterizer::DrawToSurface(flow::LayerTree&) + 364
10 Flutter                        0x103ab7120 shell::Rasterizer::DoDraw(std::__1::unique_ptr<flow::LayerTree, std::__1::default_delete<flow::LayerTree> >) + 44
11 Flutter                        0x103ab7480 std::__1::__function::__func<std::__1::__bind<void (shell::Rasterizer::*)(std::__1::unique_ptr<flow::LayerTree, std::__1::default_delete<flow::LayerTree> >), shell::Rasterizer*, std::__1::placeholders::__ph<1> const&>, std::__1::allocator<std::__1::__bind<void (shell::Rasterizer::*)(std::__1::unique_ptr<flow::LayerTree, std::__1::default_delete<flow::LayerTree> >), shell::Rasterizer*, std::__1::placeholders::__ph<1> const&> >, void (std::__1::unique_ptr<flow::LayerTree, std::__1::default_delete<flow::LayerTree> >)>::operator()(std::__1::unique_ptr<flow::LayerTree, std::__1::default_delete<flow::LayerTree> >&&) + 60
12 Flutter                        0x103ab6fcc shell::Rasterizer::Draw(fml::RefPtr<flutter::Pipeline<flow::LayerTree> >) + 504
13 Flutter                        0x103abafd0 std::__1::__function::__func<shell::Shell::OnAnimatorDraw(fml::RefPtr<flutter::Pipeline<flow::LayerTree> >)::$_23, std::__1::allocator<shell::Shell::OnAnimatorDraw(fml::RefPtr<flutter::Pipeline<flow::LayerTree> >)::$_23>, void ()>::operator()() + 76
14 Flutter                        0x103a7db20 fml::MessageLoopImpl::RunExpiredTasks() + 2028
15 Flutter                        0x103a7ef58 fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) + 32
16 CoreFoundation                 0x1a2428804 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
17 CoreFoundation                 0x1a2428534 __CFRunLoopDoTimer + 864
18 CoreFoundation                 0x1a2427d68 __CFRunLoopDoTimers + 248
19 CoreFoundation                 0x1a2422c44 __CFRunLoopRun + 1880
20 CoreFoundation                 0x1a24221cc CFRunLoopRunSpecific + 436
21 Flutter                        0x103a7ede4 fml::MessageLoopDarwin::Run() + 88
22 Flutter                        0x103a7e68c void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*) + 272
23 libsystem_pthread.dylib        0x1a20b32ac _pthread_body + 128
24 libsystem_pthread.dylib        0x1a20b320c _pthread_start + 48
25 libsystem_pthread.dylib        0x1a20b6cf4 thread_start + 4

**Comment by zoechi** [comment]
> Our app has native and flutter page, we crate a entry can jump to a flutter page. According to online user reponses, we find almost action is click the entry button, and press home to back to background.

Can you please provide a minimal reproduction project on GitHub?

**Comment by windvip** [comment]
Thread 15 name:  tmreader.1.gpu
Thread 15 Crashed:
0   libGPUSupportMercury.dylib          0x00000001a09f4efc gpus_ReturnNotPermittedKillClient + 12
1   AGXGLDriver                         0x00000001a4b63238 156216
2   libGPUSupportMercury.dylib          0x00000001a09f5edc gpusSubmitDataBuffers + 176
3   AGXGLDriver                         0x00000001a4b64734 161588
4   GLEngine                            0x00000001a5c2601c gliPresentViewES_Exec + 188
5   OpenGLES                            0x0000000188716a8c -[EAGLContext presentRenderbuffer:] + 80
6   Flutter                             0x0000000108b175d4 161236
7   Flutter                             0x0000000108e6c9d0 3656144
8   Flutter                             0x0000000108b6ad9c 503196
9   Flutter                             0x0000000108b5d848 448584
10  Flutter                             0x0000000108b5dce4 449764
11  Flutter                             0x0000000108b5e044 450628
12  Flutter                             0x0000000108b5db90 449424
13  Flutter                             0x0000000108b620ac 467116
14  Flutter                             0x0000000108b24690 214672
15  Flutter                             0x0000000108b25acc 219852
16  CoreFoundation                      0x000000018581a92c __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
17  CoreFoundation                      0x000000018581a650 __CFRunLoopDoTimer + 864
18  CoreFoundation                      0x0000000185819e50 __CFRunLoopDoTimers + 248
19  CoreFoundation                      0x0000000185817a38 __CFRunLoopRun + 1928
20  CoreFoundation                      0x0000000185737fb8 CFRunLoopRunSpecific + 436
21  Flutter                             0x0000000108b25958 219480
22  Flutter                             0x0000000108b25200 217600
23  libsystem_pthread.dylib             0x000000018549c31c _pthread_body + 308
24  libsystem_pthread.dylib             0x000000018549c1e8 _pthread_body + 0
25  libsystem_pthread.dylib             0x000000018549ac28 thread_start + 4

**Comment by windvip** [comment]
please see this doc， but i dont know how to fix it ：
https://developer.apple.com/library/archive/qa/qa1766/_index.html

**Comment by PerrchicK** [comment]
Hi @zoechi,
Is there a way we cloud tell Flutter that the app is in background? So the framework won't attempt to draw anything until the app is back to foreground.

I assume that a simple call to this kind of event can prevent crashes like this.

**Comment by dansunhappy** [comment]
```
Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (2 months ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
Still seeing this crash with Flutter 1.5.4-hotfix.2
```
reproduct

https://github.com/flutter/flutter/issues/14178#issuecomment-492065259

**Comment by dansunhappy** [comment]
```
Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (2 months ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
```
# reproduct

```
import 'dart:async';

import 'package:flutter/material.dart';

const int delayInitializeTime = 1000;

void main() async {
  await Future.delayed(Duration(seconds: 2));
  runApp(MaterialApp(
    title: 'Title2',
    home: Scaffold(
      appBar: AppBar(
        title: Text('114'),
      ),
      body: Container(
        height: 52.0,
        decoration: BoxDecoration(
          image: DecorationImage(
            image: AssetImage('assets/slide_A_login_background.png'),
            fit: BoxFit.cover,
          ),
        ),
      ),
    ),
  ));
}

```
启动瞬间点击home 按钮
# device 
iOS 12.1.4 (16D57)
Model: iPad mini 3 (Model A1599))
# 堆栈信息
```
* thread #10, name = 'io.flutter.1.io', stop reason = EXC_BAD_ACCESS (code=1, address=0x1)
  * frame #0: 0x00000001b0e56f28 libGPUSupportMercury.dylib`gpus_ReturnNotPermittedKillClient + 12
    frame #1: 0x00000001b563c8e0 AGXGLDriver`___lldb_unnamed_symbol555$$AGXGLDriver + 464
    frame #2: 0x00000001b0e57f04 libGPUSupportMercury.dylib`gpusSubmitDataBuffers + 176
    frame #3: 0x00000001b563de28 AGXGLDriver`___lldb_unnamed_symbol576$$AGXGLDriver + 292
    frame #4: 0x0000000100ce20f0 Flutter`SkImage::MakeCrossContextFromEncoded(GrContext*, sk_sp<SkData>, bool, SkColorSpace*, bool) + 584
    frame #5: 0x0000000100adf0d8 Flutter`std::__1::__function::__func<fml::internal::CopyableLambda<flutter::(anonymous namespace)::InstantiateImageCodec(_Dart_NativeArguments*)::$_1>, std::__1::allocator<fml::internal::CopyableLambda<flutter::(anonymous namespace)::InstantiateImageCodec(_Dart_NativeArguments*)::$_1> >, void ()>::operator()() + 1264
    frame #6: 0x0000000100acfac8 Flutter`fml::MessageLoopImpl::FlushTasks(fml::MessageLoopImpl::FlushType) + 816
    frame #7: 0x0000000100ad31d4 Flutter`fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) + 32
    frame #8: 0x0000000193e6a718 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
    frame #9: 0x0000000193e6a448 CoreFoundation`__CFRunLoopDoTimer + 864
    frame #10: 0x0000000193e69c7c CoreFoundation`__CFRunLoopDoTimers + 248
    frame #11: 0x0000000193e64b58 CoreFoundation`__CFRunLoopRun + 1880
    frame #12: 0x0000000193e640e0 CoreFoundation`CFRunLoopRunSpecific + 436
    frame #13: 0x0000000100ad32f8 Flutter`fml::MessageLoopDarwin::Run() + 88
    frame #14: 0x0000000100acf71c Flutter`fml::MessageLoopImpl::DoRun() + 52
    frame #15: 0x0000000100ad26d0 Flutter`void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*) + 200
    frame #16: 0x0000000193af425c libsystem_pthread.dylib`_pthread_body + 128
    frame #17: 0x0000000193af41bc libsystem_pthread.dylib`_pthread_start + 48
    frame #18: 0x0000000193af7cf4 libsystem_pthread.dylib`thread_start + 4
```
# log
```
2019-07-10 18:40:29.539666+0800 Runner[1742:367348] You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
2019-07-10 18:40:29.539793+0800 Runner[1742:367348] You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
2019-07-10 18:40:30.154093+0800 Runner[1742:367394] flutter: Observatory listening on http://127.0.0.1:54303/0cbL-6hWs4U=/
2019-07-10 18:40:35.117194+0800 Runner[1742:367348] Could not load IOSurface for time string. Rendering locally instead.
```

**Comment by songfei** [comment]
same issues

**Comment by edwardez** [comment]
+1 , our app crashed in production becasue of this, according to Firebase crashlytics, however I'm not able to reproduce.

It happened to a user on a iPhone 6 Plus, iOS 12.0.0 (16A366) w/ `v1.7.8+hotfix.3` 

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F203, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
```

```
Crashed: io.flutter.1.io
0  libGPUSupportMercury.dylib     0x250fc8f28 gpus_ReturnNotPermittedKillClient + 12
1  AGXGLDriver                    0x2557778c0 gldUpdateDispatch + 7216
2  libGPUSupportMercury.dylib     0x250fc9f04 gpusSubmitDataBuffers + 176
3  AGXGLDriver                    0x255778e08 gldUpdateDispatch + 12664
4  Flutter                        0x100b38688 (Missing)
5  Flutter                        0x1009013f8 (Missing)
6  Flutter                        0x1008f0534 (Missing)
7  Flutter                        0x1008f3cc8 (Missing)
8  CoreFoundation                 0x234106bf0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
9  CoreFoundation                 0x234106920 __CFRunLoopDoTimer + 864
10 CoreFoundation                 0x234106154 __CFRunLoopDoTimers + 248
11 CoreFoundation                 0x234101030 __CFRunLoopRun + 1880
12 CoreFoundation                 0x2341005b8 CFRunLoopRunSpecific + 436
13 Flutter                        0x1008f3ba4 (Missing)
14 Flutter                        0x1008f3774 (Missing)
15 libsystem_pthread.dylib        0x233d912fc _pthread_body + 128
16 libsystem_pthread.dylib        0x233d9125c _pthread_start + 48
17 libsystem_pthread.dylib        0x233d94d08 thread_start + 4
```

**Comment by Greatcallie** [comment]
> +1 , our app crashed in production becasue of this, according to Firebase crashlytics, however I'm not able to reproduce.
> 
> It happened to a user on a iPhone 6 Plus, iOS 12.0.0 (16A366) w/ `v1.7.8+hotfix.3`
> 
> ```
> [✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F203, locale en-US)
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
> ```
> 
> ```
> Crashed: io.flutter.1.io
> 0  libGPUSupportMercury.dylib     0x250fc8f28 gpus_ReturnNotPermittedKillClient + 12
> 1  AGXGLDriver                    0x2557778c0 gldUpdateDispatch + 7216
> 2  libGPUSupportMercury.dylib     0x250fc9f04 gpusSubmitDataBuffers + 176
> 3  AGXGLDriver                    0x255778e08 gldUpdateDispatch + 12664
> 4  Flutter                        0x100b38688 (Missing)
> 5  Flutter                        0x1009013f8 (Missing)
> 6  Flutter                        0x1008f0534 (Missing)
> 7  Flutter                        0x1008f3cc8 (Missing)
> 8  CoreFoundation                 0x234106bf0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
> 9  CoreFoundation                 0x234106920 __CFRunLoopDoTimer + 864
> 10 CoreFoundation                 0x234106154 __CFRunLoopDoTimers + 248
> 11 CoreFoundation                 0x234101030 __CFRunLoopRun + 1880
> 12 CoreFoundation                 0x2341005b8 CFRunLoopRunSpecific + 436
> 13 Flutter                        0x1008f3ba4 (Missing)
> 14 Flutter                        0x1008f3774 (Missing)
> 15 libsystem_pthread.dylib        0x233d912fc _pthread_body + 128
> 16 libsystem_pthread.dylib        0x233d9125c _pthread_start + 48
> 17 libsystem_pthread.dylib        0x233d94d08 thread_start + 4
> ```

Same here. The bug is hard to reproduce and it seems to happen in older iOS devices like iphone 6 and 5c. And yes it still happens in flutter 1.7.8

**Comment by guopeng1994** [comment]
any progress???

**Comment by yxwandroid** [comment]
same issues

**Comment by yxwandroid** [comment]
libobjc.A.dylib	objc_retain + 10
1 Runner	-[FLTVideoPlayer copyPixelBuffer] + 82
2 Flutter	flutter::IOSExternalTextureGL::Paint(SkCanvas&, SkRect const&, bool, GrContext*) (ios_external_texture_gl.mm:63)
3 Flutter	flutter::TextureLayer::Paint(flutter::Layer::PaintContext&) const (memory:4507)
4 Flutter	flutter::ContainerLayer::PaintChildren(flutter::Layer::PaintContext&) const (iterator:1390)
5 Flutter	flutter::TransformLayer::Paint(flutter::Layer::PaintContext&) const (SkCanvas.h:2741)
6 Flutter	flutter::ContainerLayer::PaintChildren(flutter::Layer::PaintContext&) const (iterator:1390)
7 Flutter	flutter::TransformLayer::Paint(flutter::Layer::PaintContext&) const (SkCanvas.h:2741)
8 Flutter	flutter::ContainerLayer::PaintChildren(flutter::Layer::PaintContext&) const (iterator:1390)
9 Flutter	flutter::TransformLayer::Paint(flutter::Layer::PaintContext&) const (SkCanvas.h:2741)
10 Flutter	flutter::ContainerLayer::PaintChildren(flutter::Layer::PaintContext&) const (iterator:1390)
11 Flutter	flutter::TransformLayer::Paint(flutter::Layer::PaintContext&) const (SkCanvas.h:2741)
12 Flutter	flutter::ContainerLayer::PaintChildren(flutter::Layer::PaintContext&) const (iterator:1390)
13 Flutter	flutter::ClipRectLayer::Paint(flutter::Layer::PaintContext&) const (clip_rect_layer.cc:57)
14 Flutter	flutter::ContainerLayer::PaintChildren(flutter::Layer::PaintContext&) const (iterator:1390)
15 Flutter	flutter::TransformLayer::Paint(flutter::Layer::PaintContext&) const (SkCanvas.h:2741)
16 Flutter	flutter::LayerTree::Paint(flutter::CompositorContext::ScopedFrame&, bool) const (layer_tree.cc:0)
17 Flutter	flutter::CompositorContext::ScopedFrame::Raster(flutter::LayerTree&, bool) (compositor_context.cc:72)
18 Flutter	flutter::Rasterizer::DrawToSurface(flutter::LayerTree&) (rasterizer.cc:218)
19 Flutter	flutter::Rasterizer::DoDraw(std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >) (rasterizer.cc:174)
20 Flutter	std::__1::__function::__func<std::__1::__bind<void (flutter::Rasterizer::*)(std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >), flutter::Rasterizer*, std::__1::placeholders::__ph<1> const&>, std::__1::allocator<std::__1::__bind<void (flutter::Rasterizer::*)(std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >), flutter::Rasterizer*, std::__1::placeholders::__ph<1> const&> >, void (std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >)>::operator()(std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >&&) (memory:2635)
21 Flutter	flutter::Pipeline<flutter::LayerTree>::Consume(std::__1::function<void (std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >)>) (memory:2635)
22 Flutter	flutter::Rasterizer::Draw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >) (rasterizer.cc:94)
23 Flutter	_ZNSt3__110__function6__funcIZN7flutter5Shell14OnAnimatorDrawEN3fml6RefPtrINS2_8PipelineINS2_9LayerTreeEEEEEE4$_24NS_9allocatorISA_EEFvvEEclEv (ref_ptr.h:103)
24 Flutter	fml::MessageLoopImpl::FlushTasks(fml::FlushType) (ref_ptr.h:116)
25 Flutter	fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (message_loop_darwin.mm:76)
26 CoreFoundation	__CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
27 CoreFoundation	__CFRunLoopDoTimer + 1026

**Comment by Qxyat** [comment]
We have met the same problem and it is hard to reproduce。

The crash stack is:
Thread 6 name:  io.flutter.1.io
Thread 6: Crashed
0   libGPUSupportMercury.dylib      0x00000001b55c2fe4 _gpus_ReturnNotPermittedKillClient (in libGPUSupportMercury.dylib) + 12
1   libGPUSupportMercury.dylib      0x00000001b55c3fac _gpusSubmitDataBuffers (in libGPUSupportMercury.dylib) + 176
2   AGXGLDriver                     0x00000001b9c71404 0x1b9c4b000 + 156676 ((null))
3   Flutter                         0x0000000107e5c064 SkImage::MakeCrossContextFromEncoded(GrContext*, sk_sp<SkData>, bool, SkColorSpace*, bool) (in Flutter) (SkImage_Gpu.cpp:507)
4   Flutter                         0x0000000107c6e708 std::__1::__function::__func<fml::internal::CopyableLambda<flutter::(anonymous namespace)::InstantiateImageCodec(_Dart_NativeArguments*)::$_1>, std::__1::allocator<fml::internal::CopyableLambda<flutter::(anonymous namespace)::InstantiateImageCodec(_Dart_NativeArguments*)::$_1> >, void ()>::operator()() (in Flutter) (functional:1572)
5   Flutter                         0x0000000107c5efa4 fml::MessageLoopImpl::FlushTasks(fml::MessageLoopImpl::FlushType) (in Flutter) (message_loop_impl.cc:141)
6   Flutter                         0x0000000107c60634 fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (in Flutter) (message_loop_darwin.mm:76)
7   CoreFoundation                  0x0000000199544d60 ___CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ (in CoreFoundation) + 28
8   CoreFoundation                  0x0000000199544a90 ___CFRunLoopDoTimer (in CoreFoundation) + 864
9   CoreFoundation                  0x00000001995442c4 ___CFRunLoopDoTimers (in CoreFoundation) + 248
10  CoreFoundation                  0x000000019953f214 ___CFRunLoopRun (in CoreFoundation) + 1844
11  CoreFoundation                  0x000000019953e7c0 _CFRunLoopRunSpecific (in CoreFoundation) + 436
12  Flutter                         0x0000000107c604c0 fml::MessageLoopDarwin::Run() (in Flutter) (message_loop_darwin.mm:47)
13  Flutter                         0x0000000107c5fd90 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*) (in Flutter) (thread:352)
14  libsystem_pthread.dylib         0x00000001991d12c0 __pthread_body (in libsystem_pthread.dylib) + 128
15  libsystem_pthread.dylib         0x00000001991d1220 __pthread_start (in libsystem_pthread.dylib) + 44

**Comment by cbracken** [comment]
Attaching repro from #14178. We don't have repro instructions from the original filing, so adding instructions from wonderful89 on that bug, which was marked closed, under the assumption these are related.

## 1.  my flutter version
```
➜  flutterDemos git:(master) flutter --version
Flutter 1.4.7 • channel unknown • unknown source
Framework • revision 1bfa2f2311 (6 weeks ago) • 2019-03-29 10:05:18 -0700
Engine • revision c4d14a0071
Tools • Dart 2.2.1 (build 2.2.1-dev.2.0 None)
```
## 2. reproduct steps

* compile and build project in iPad mini（A1490）in release.
* open this project in Xcode and run in release mode.
* wait for ` Please click and enter background:`  log in the console. Then click the home key and enter background.
* wait for a moment(in 10 seconds) and it will crash.


### 2.1 crash
![image](https://user-images.githubusercontent.com/44089389/57668585-679c7b80-763a-11e9-8363-645aa33c633c.png)

### 2.2 demo project
[demo](https://github.com/qqzhao/flutterDemos/tree/master/examples/background_gpu)

### 2.3 key code

open background running task
```objective-c
- (void)applicationDidEnterBackground:(UIApplication *)application {
    NSLog(@"applicationDidEnterBackground =============");
    self.backIden = [[UIApplication sharedApplication] beginBackgroundTaskWithExpirationHandler:^{
        NSLog(@"in ExpirationHandler=============");
        [self endBack]; 
    }];
    
    return [super applicationDidEnterBackground:application];
}
// 

```

render image:
```dart
Widget child2 = Container(
        height: 52.0,
        decoration: BoxDecoration(
          image: DecorationImage(
            image: AssetImage('assets/slide_wave_login_background.png'),
            fit: BoxFit.cover,
          ),
        ),
      );
```

**Comment by cbracken** [comment]
Cross-referencing with #22933 which may be the same issue.

**Comment by BharathMG** [comment]
Any updates on this issue? We are getting this in older iPhones. I was able to reproduce this by doing simple steps,

1. Click on a button to navigate to some screen.
2. Press home immediately after pressing button. It should be during page transition.

Observe the crash in logs.

**Comment by Quanhua-Guan** [comment]
Any updates on this issue?

**Comment by gaaclarke** [comment]
Hi I started looking into the issue.  I found that this issue no longer crashes the app if it is built with XCode 11.1.  It just prints out a warning that you aren't suppose to be doing GPU work while backgrounded.

```
2019-10-29 11:12:21.746735-0700 Runner[465:257566] Execution of the command buffer was aborted due to an error during execution. Insufficient Permission (to submit GPU work from background) (IOAF code 6)
2019-10-29 11:12:21.747700-0700 Runner[465:257566] GLDRendererMetal command buffer completion error: Error Domain=MTLCommandBufferErrorDomain Code=7 "Insufficient Permission (to submit GPU work from background) (IOAF code 6)" UserInfo={NSLocalizedDescription=Insufficient Permission (to submit GPU work from background) (IOAF code 6)}
```

It seems like Apple may have rewritten OpenGL to run on top of Metal and when it did, it turned this from a crash to a warning.

We shouldn't be submitting GPU work when backgrounded but if this solves your issue; this issue is going to be lower priority.  **Can you please give it a try on XCode 11.1?**

P.S. The code didn't run anymore for me without a few changes, [here is what I had to change.](https://gist.github.com/gaaclarke/87e7af3c896fb173c4ac7e317649a357)

**Comment by PonyCui** [comment]
@gaaclarke Are you sure the device is iPhone 6 6+ 5?
The crash only appears on these devices.

**Comment by gaaclarke** [comment]
> @gaaclarke Are you sure the device is iPhone 6 6+ 5?
> The crash only appears on these devices.

Thanks for the heads up.  I repro'd on an iPhone SE.  I have gotten this crash on other products I've worked with on an iPhone SE.  I'll see if I can snag another device for reproing with Flutter.  It looks like the original report was on XCode 10.0.  If someone can confirm with XCode 11.1 with one of the devices before I can that would be appreciated.

**Comment by gaaclarke** [comment]
This issue was originally fixed [a couple years ago](https://github.com/gaaclarke/engine/commit/75c74dc463d56e17be10315cfde409010fd8f90b).  The solution was to [pause the renderer](https://github.com/flutter/engine/blob/b7ea5561d4d85553f27ad01b642746c1c46c073b/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L551:L551) when the application is backgrounded.  I have verified that that is still functioning and no frames are getting rendered after we've backgrounded the application.

The culprit is the other OpenGL context we maintain on the IO thread that is used for image decoding.  By placing a breakpoint on `glBindTexture` and printing out the backtrack for each call I was able to get the stack trace for calls to `glBindTexture` after the app has been backgrounded:

```
* thread #10, name = 'io.flutter.1.io', stop reason = breakpoint 14.1
  * frame #0: 0x00000001c03ea0d0 OpenGLES`glBindTexture
    frame #1: 0x0000000105a7bc70 Flutter`GrGLFunction<void (unsigned int, unsigned int)>::GrGLFunction(this=0x0000000105a7bbd8, buf=0x000000010e0293c8, args=3553, args=1)(unsigned int, unsigned int))::'lambda'(void const*, unsigned int, unsigned int)::operator()(void const*, unsigned int, unsigned int) const at GrGLFunctions.h:284:24
    frame #2: 0x0000000105a7bc04 Flutter`GrGLFunction<void (unsigned int, unsigned int)>::GrGLFunction(buf=0x000000010e0293c8, args=3553, args=1)(unsigned int, unsigned int))::'lambda'(void const*, unsigned int, unsigned int)::__invoke(void const*, unsigned int, unsigned int) at GrGLFunctions.h:283:21
    frame #3: 0x0000000105aa3b24 Flutter`GrGLFunction<void (unsigned int, unsigned int)>::operator(this=0x000000010e0293c0, args=3553, args=1)(unsigned int, unsigned int) const at GrGLFunctions.h:307:16
    frame #4: 0x0000000105aa1514 Flutter`GrGLGpu::bindTextureToScratchUnit(this=0x000000010b846e00, target=3553, textureID=1) at GrGLGpu.cpp:2804:5
    frame #5: 0x0000000105aa1204 Flutter`GrGLGpu::onWritePixels(this=0x000000010b846e00, surface=0x0000000282c98400, left=0, top=0, width=1536, height=83, surfaceColorType=kRGBA_8888, srcColorType=kRGBA_8888, texels=0x000000016bc0f1d8, mipLevelCount=11, prepForTexSampling=false) at GrGLGpu.cpp:844:11
    frame #6: 0x0000000105860670 Flutter`GrGpu::writePixels(this=0x000000010b846e00, surface=0x0000000282c98400, left=0, top=0, width=1536, height=83, surfaceColorType=kRGBA_8888, srcColorType=kRGBA_8888, texels=0x000000016bc0f1d8, mipLevelCount=11, prepForTexSampling=false) at GrGpu.cpp:490:15
    frame #7: 0x000000010585fcd4 Flutter`GrGpu::createTexture(this=0x000000010b846e00, desc=0x0000000283b8c778, format=0x0000000283b8c788, renderable=kNo, renderTargetSampleCnt=1, budgeted=kYes, isProtected=kNo, textureColorType=kRGBA_8888, srcColorType=kRGBA_8888, texels=0x000000016bc0f1d8, texelLevelCount=11) at GrGpu.cpp:254:24
    frame #8: 0x00000001058f76b4 Flutter`GrResourceProvider::createTexture(this=0x0000000281eec4b0, desc=0x0000000283b8c778, format=0x0000000283b8c788, colorType=kRGBA_8888, renderable=kNo, renderTargetSampleCnt=1, budgeted=kYes, isProtected=kNo, texels=0x00000002827944d0, mipLevelCount=11) at GrResourceProvider.cpp:89:18
    frame #9: 0x00000001058a5ffc Flutter`GrProxyProvider::createProxyFromBitmap(this=0x0000000283b8c778, resourceProvider=0x0000000281eec4b0)::$_22::operator()(GrResourceProvider*) const at GrProxyProvider.cpp:406:61
    frame #10: 0x00000001058a5bfc Flutter`decltype(__f=0x0000000283b8c778, __args=0x000000016bc0f610)::$_22&>(fp)(std::__1::forward<GrResourceProvider*>(fp0))) std::__1::__invoke<GrProxyProvider::createProxyFromBitmap(SkBitmap const&, GrMipMapped)::$_22&, GrResourceProvider*>(GrProxyProvider::createProxyFromBitmap(SkBitmap const&, GrMipMapped)::$_22&, GrResourceProvider*&&) at type_traits:4350:1
    frame #11: 0x00000001058a5b8c Flutter`GrSurfaceProxy::LazyCallbackResult std::__1::__invoke_void_return_wrapper<GrSurfaceProxy::LazyCallbackResult>::__call<GrProxyProvider::createProxyFromBitmap(__args=0x0000000283b8c778, __args=0x000000016bc0f610)::$_22&, GrResourceProvider*>(GrProxyProvider::createProxyFromBitmap(SkBitmap const&, GrMipMapped)::$_22&, GrResourceProvider*&&) at __functional_base:318:16
    frame #12: 0x00000001058a45c0 Flutter`std::__1::__function::__func<GrProxyProvider::createProxyFromBitmap(SkBitmap const&, GrMipMapped)::$_22, std::__1::allocator<GrProxyProvider::createProxyFromBitmap(SkBitmap const&, GrMipMapped)::$_22>, GrSurfaceProxy::LazyCallbackResult (GrResourceProvider*)>::operator(this=0x0000000283b8c770, __arg=0x000000016bc0f610)(GrResourceProvider*&&) at functional:1572:12
    frame #13: 0x00000001059158ec Flutter`std::__1::function<GrSurfaceProxy::LazyCallbackResult (GrResourceProvider*)>::operator(this=0x000000010d510860, __arg=0x0000000281eec4b0)(GrResourceProvider*) const at functional:1923:12
    frame #14: 0x00000001059153dc Flutter`GrSurfaceProxyPriv::doLazyInstantiation(this=0x000000016bc0f9f8, resourceProvider=0x0000000281eec4b0) at GrSurfaceProxy.cpp:434:23
    frame #15: 0x000000010589b300 Flutter`GrProxyProvider::createProxyFromBitmap(this=0x00000002810b8300, bitmap=0x000000016bc0fe80, mipMapped=kYes) at GrProxyProvider.cpp:423:28
    frame #16: 0x0000000105b33a6c Flutter`SkImage::MakeCrossContextFromPixmap(context=0x000000010d4004c0, originalPixmap=0x000000016bc10360, buildMips=true, limitToMaxTextureSize=true) at SkImage_Gpu.cpp:503:50
    frame #17: 0x0000000104c900cc Flutter`flutter::UploadRasterImage(image=sk_sp<SkImage> @ 0x000000016bc10978, context=WeakPtr<GrContext> @ 0x000000016bc10960, queue=RefPtr<flutter::SkiaUnrefQueue> @ 0x000000016bc10958, flow=0x00000002834881d0) at image_decoder.cc:177:7
    frame #18: 0x0000000104c8f644 Flutter`flutter::ImageDecoder::Decode(this=0x0000000283488188)>)::$_1::operator()()::'lambda'()::operator()() at image_decoder.cc:267:27
    frame #19: 0x0000000104c8f180 Flutter`auto fml::internal::CopyableLambda<flutter::ImageDecoder::Decode(flutter::ImageDecoder::ImageDescriptor, std::__1::function<void (flutter::SkiaGPUObject<SkImage>)>)::$_1::operator()()::'lambda'()>::operator(this=0x00000002812891d8)<>() const at make_copyable.h:24:12
    frame #20: 0x0000000104c8f134 Flutter`decltype(__f=0x00000002812891d8)>)::$_1::operator()()::'lambda'()>&>(fp)()) std::__1::__invoke<fml::internal::CopyableLambda<flutter::ImageDecoder::Decode(flutter::ImageDecoder::ImageDescriptor, std::__1::function<void (flutter::SkiaGPUObject<SkImage>)>)::$_1::operator()()::'lambda'()>&>(fml::internal::CopyableLambda<flutter::ImageDecoder::Decode(flutter::ImageDecoder::ImageDescriptor, std::__1::function<void (flutter::SkiaGPUObject<SkImage>)>)::$_1::operator()()::'lambda'()>&) at type_traits:4350:1
    frame #21: 0x0000000104c8f0e8 Flutter`void std::__1::__invoke_void_return_wrapper<void>::__call<fml::internal::CopyableLambda<flutter::ImageDecoder::Decode(__args=0x00000002812891d8)>)::$_1::operator()()::'lambda'()>&>(fml::internal::CopyableLambda<flutter::ImageDecoder::Decode(flutter::ImageDecoder::ImageDescriptor, std::__1::function<void (flutter::SkiaGPUObject<SkImage>)>)::$_1::operator()()::'lambda'()>&) at __functional_base:349:9
    frame #22: 0x0000000104c8dbc0 Flutter`std::__1::__function::__func<fml::internal::CopyableLambda<flutter::ImageDecoder::Decode(flutter::ImageDecoder::ImageDescriptor, std::__1::function<void (flutter::SkiaGPUObject<SkImage>)>)::$_1::operator()()::'lambda'()>, std::__1::allocator<fml::internal::CopyableLambda<flutter::ImageDecoder::Decode(flutter::ImageDecoder::ImageDescriptor, std::__1::function<void (flutter::SkiaGPUObject<SkImage>)>)::$_1::operator()()::'lambda'()> >, void ()>::operator(this=0x00000002812891d0)() at functional:1572:12
    frame #23: 0x0000000104c1e000 Flutter`std::__1::function<void ()>::operator(this=0x00000002810a02c0)() const at functional:1923:12
    frame #24: 0x0000000104c311f8 Flutter`fml::MessageLoopImpl::FlushTasks(this=0x00000002805e00c0, type=kAll) at message_loop_impl.cc:121:5
    frame #25: 0x0000000104c3102c Flutter`fml::MessageLoopImpl::RunExpiredTasksNow(this=0x00000002805e00c0) at message_loop_impl.cc:131:3
    frame #26: 0x0000000104c4d6cc Flutter`fml::MessageLoopDarwin::OnTimerFire(timer=0x0000000282598840, loop=0x00000002805e00c0) at message_loop_darwin.mm:75:11
    frame #27: 0x00000001a620ae1c CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
    frame #28: 0x00000001a620ab58 CoreFoundation`__CFRunLoopDoTimer + 880
    frame #29: 0x00000001a620a228 CoreFoundation`__CFRunLoopDoTimers + 276
    frame #30: 0x00000001a6205364 CoreFoundation`__CFRunLoopRun + 1920
    frame #31: 0x00000001a62048bc CoreFoundation`CFRunLoopRunSpecific + 464
    frame #32: 0x0000000104c4daa0 Flutter`fml::MessageLoopDarwin::Run(this=0x00000002805e00c0) at message_loop_darwin.mm:46:20
    frame #33: 0x0000000104c30f48 Flutter`fml::MessageLoopImpl::DoRun(this=0x00000002805e00c0) at message_loop_impl.cc:90:3
    frame #34: 0x0000000104c2fa7c Flutter`fml::MessageLoop::Run(this=0x00000002812946f0) at message_loop.cc:49:10
    frame #35: 0x0000000104c497bc Flutter`fml::Thread::Thread(this=0x0000000281ef4308)::$_0::operator()() const at thread.cc:34:10
    frame #36: 0x0000000104c496f4 Flutter`decltype(__f=0x0000000281ef4308)::$_0>(fp)()) std::__1::__invoke<fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>(fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0&&) at type_traits:4350:1
    frame #37: 0x0000000104c49694 Flutter`void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>(__t=size=2, (null)=__tuple_indices<> @ 0x000000016bc12f6f)::$_0>&, std::__1::__tuple_indices<>) at thread:342:5
    frame #38: 0x0000000104c491fc Flutter`void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(__vp=0x0000000281ef4300) at thread:352:5
    frame #39: 0x00000001a5fa91ec libsystem_pthread.dylib`_pthread_start + 124
```

So, my friends, this means there is a timing aspect to this bug.  It is no accident that the repro code asks you to background the app when the app is just launching.  This gives you the highest likelihood that you'll have outstanding images to decompress.  It's possible if you are getting this crash in your crash logs it is because users are accidentally opening your application and closing it immediately.

It is also interesting the the original reports of this crash were on thread `io.flutter.1.gpu`.  I wonder if we renamed that thread or if the original report was a different crash on the gpu thread, hmm.

Anyway, the solution is forthcoming and it will involve expanding our backgrounding pausing mechanism to the image decoder.

**Comment by zw1924** [comment]
Is there any patch for this issue that can be resolved immediately

**Comment by gaaclarke** [comment]
@zw1924 https://github.com/flutter/engine/pull/13454 is hung up a bit while we debate.  It was put on hold until @chinmaygarde can chime in.

I'm confident in it.  Some of the biggest concerns are about how it will hold up in the future, "It's correct now but I'm concerned it will be easy to break.  Is there a different way to fix this that is cleaner?"

**Comment by doubleSkinMilk** [comment]
We completed the flutter transformation for two months, and now the grayscale test found this problem. If it is not solved, it cannot be released to the appstore.

**Comment by trey-rosius** [comment]
any solution to this yet? I can't release to the appstore unless i resolve this.

**Comment by Hixie** [comment]
(Original title was: Crashed: io.flutter.1.gpu EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000001 gldUpdateDispatch )

@chinmaygarde Any chance you can review https://github.com/flutter/engine/pull/13454 ?

**Comment by chinmaygarde** [comment]
If was fairly low on my list of things to do since both Aaron & Dan are OOO. I'll review it by the time @gaaclarke gets back. There are threading & deadlock concerns in that patch that need to be reasoned about.

**Comment by gaaclarke** [comment]
My previous PR got caught up in debate and a few proposals were floating around.  @chinmaygarde and I just had a chat and we came up with a solution that may make everyone happy:
1) Guard the image decoder's call to `MakeCrossContextFromPixmap` such that it will execute if we are foregrounded.  If we are backgrounded it will make a CPU backed image.  (note `SkiaGPUObject` doesn't actually mean it's a GPU object).
2) Make AppWillBackground notification wait until that the switch in 1 is executed.
3) Make the UnrefQueue also stop consuming its queue while backgrounded, using a mechanism similar to the one used in 1.  We'll have to make a way to flip it back on when the app is foregrounded as well, unlike the image decoder.

The benefits of this are that it doesn't pause the io thread which was worrisome since it's hard to test and could be broken in future PRs.  The disadvantages are that it may cause the first frame after foregrounding to be slower and cause extra memory usage since Skia will cache the GPU texture representation.

This solution still leaves us open to future opengl code on the io thread we haven't considered.  It is up to every implementor to know when a call may use OpenGL and guard it.  I think we may safely be able to implement this.  I'm worried about introducing minefields for a bug that is somewhat rare.  I'll give it a shot shortly.

**Comment by voiddog** [comment]
same issues

**Comment by gaaclarke** [comment]
Should be fixed now.  We opted to guard each call site instead of locking down the thread so this might pop up again in the future for new code.  I tested with the original repro code and the landed PR fixes that.

**Comment by BharathMG-ShareChat** [comment]
@gaaclarke Thanks a lot for this work. I was trying very hard to find which flutter version includes that engine commit. But, the flutter commit https://github.com/flutter/flutter/commit/fad3c7094d2ae22685bd9fc72d87fa155196fdb8 doesn't include any version information. 

Could you let us know which version has this fix? Thanks!

**Comment by MrLittleStrong** [comment]
> @gaaclarke Thanks a lot for this work. I was trying very hard to find which flutter version includes that engine commit. But, the flutter commit [fad3c70](https://github.com/flutter/flutter/commit/fad3c7094d2ae22685bd9fc72d87fa155196fdb8) doesn't include any version information.
> 
> Could you let us know which version has this fix? Thanks!

Stable Channel Flutter 1.12.13+hotfix 5

**Comment by suzhenghao** [comment]
@gaaclarke  hi, my app has upgraded flutter to 1.12.13+hotfix 5, but the crash is still there. Can you give me a help please ?

**Comment by gaaclarke** [comment]
This fix is in 1.15.21 and later.

https://github.com/flutter/flutter/commit/144eb45aa447bd7abde4f05cb24c6c13ced0971f

**Comment by livotov** [comment]
Deployed updated app to production - still happens on iOS 12, Flutter v1.16.0

`Crashed: io.flutter.1.gpu
0  libGPUSupportMercury.dylib     0x1df279fe4 gpus_ReturnNotPermittedKillClient + 12
1  AGXGLDriver                    0x1e38deed8 gldUpdateDispatch + 7184
2  libGPUSupportMercury.dylib     0x1df27afac gpusSubmitDataBuffers + 176
3  AGXGLDriver                    0x1e38e0404 gldUpdateDispatch + 12604
4  GLEngine                       0x1e498a234 gliPresentViewES_Exec + 184
5  OpenGLES                       0x1c6542aa4 -[EAGLContext presentRenderbuffer:] + 80
6  Flutter                        0x1012fb624 (Missing)
7  Flutter                        0x1016f8280 (Missing)
8  Flutter                        0x10135fdf0 (Missing)
9  Flutter                        0x10134d2c0 (Missing)
10 Flutter                        0x10134e044 (Missing)
11 Flutter                        0x10134d56c (Missing)
12 Flutter                        0x1013534c0 (Missing)
13 Flutter                        0x10130bea0 (Missing)
14 Flutter                        0x10130db18 (Missing)
15 CoreFoundation                 0x1c32c9554 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
16 CoreFoundation                 0x1c32c9284 __CFRunLoopDoTimer + 864
17 CoreFoundation                 0x1c32c8ab8 __CFRunLoopDoTimers + 248
18 CoreFoundation                 0x1c32c3a08 __CFRunLoopRun + 1844
19 CoreFoundation                 0x1c32c2fb4 CFRunLoopRunSpecific + 436
20 Flutter                        0x10130d9f4 (Missing)
21 Flutter                        0x10130d3c0 (Missing)
22 libsystem_pthread.dylib        0x1c2f552c0 _pthread_body + 128
23 libsystem_pthread.dylib        0x1c2f55220 _pthread_start + 44
24 libsystem_pthread.dylib        0x1c2f58cdc thread_start + 4`

**Comment by jerzykiler** [comment]
It happened to me on iPhone X

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.4 19E266, locale pl-PL)
    • Flutter version 1.12.13+hotfix.8 
    • Framework revision 0b8abb4724 (7 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Platform android-29, build-tools 29.0.3
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (2 available)
    • iPhone X  • ios           • iOS 13.4
```

```
(lldb) bt
* thread #8, name = 'io.flutter.1.gpu', stop reason = EXC_BAD_ACCESS (code=1, address=0x136740000)
  * frame #0: 0x00000001983dfb28 libobjc.A.dylib`objc_msgSend + 8
    frame #1: 0x00000001b3155844 AppleMetalGLRenderer`GLDContextRec::setRenderPipeline() + 132
    frame #2: 0x00000001b3155624 AppleMetalGLRenderer`GLDContextRec::setRenderState(unsigned int) + 84
    frame #3: 0x00000001b315c174 AppleMetalGLRenderer`gldRenderVertexArray(GLDContextRec*, unsigned int, unsigned int, int, int, unsigned int, void const*, int, void const*) + 1348
    frame #4: 0x00000001b30d86d4 GLEngine`glDrawArrays_ACC_ES2Exec + 348
    frame #5: 0x00000001012f0fa4 Flutter`___lldb_unnamed_symbol11260$$Flutter + 188
    frame #6: 0x00000001012f5f70 Flutter`___lldb_unnamed_symbol11313$$Flutter + 2016
    frame #7: 0x0000000101234dbc Flutter`___lldb_unnamed_symbol8481$$Flutter + 152
    frame #8: 0x0000000101234510 Flutter`___lldb_unnamed_symbol8464$$Flutter + 472
    frame #9: 0x000000010128315c Flutter`___lldb_unnamed_symbol9557$$Flutter + 140
    frame #10: 0x00000001012359a0 Flutter`___lldb_unnamed_symbol8492$$Flutter + 900
    frame #11: 0x0000000101228f48 Flutter`___lldb_unnamed_symbol8221$$Flutter + 2092
    frame #12: 0x00000001012294fc Flutter`___lldb_unnamed_symbol8223$$Flutter + 168
    frame #13: 0x0000000101248f6c Flutter`___lldb_unnamed_symbol8762$$Flutter + 272
    frame #14: 0x00000001012b9c8c Flutter`___lldb_unnamed_symbol10568$$Flutter + 36
    frame #15: 0x0000000101461524 Flutter`___lldb_unnamed_symbol15136$$Flutter + 264
    frame #16: 0x00000001010d8ab8 Flutter`___lldb_unnamed_symbol2979$$Flutter + 104
    frame #17: 0x00000001010c68f0 Flutter`___lldb_unnamed_symbol2497$$Flutter + 464
    frame #18: 0x00000001010c76a4 Flutter`___lldb_unnamed_symbol2517$$Flutter + 104
    frame #19: 0x00000001010c6bb0 Flutter`___lldb_unnamed_symbol2499$$Flutter + 360
    frame #20: 0x00000001010ccb80 Flutter`___lldb_unnamed_symbol2635$$Flutter + 76
    frame #21: 0x0000000101086f58 Flutter`___lldb_unnamed_symbol1173$$Flutter + 1664
    frame #22: 0x00000001010891dc Flutter`___lldb_unnamed_symbol1246$$Flutter + 32
    frame #23: 0x00000001986401c0 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
    frame #24: 0x000000019863fedc CoreFoundation`__CFRunLoopDoTimer + 880
    frame #25: 0x000000019863f5b8 CoreFoundation`__CFRunLoopDoTimers + 276
    frame #26: 0x000000019863a5c8 CoreFoundation`__CFRunLoopRun + 1640
    frame #27: 0x0000000198639c34 CoreFoundation`CFRunLoopRunSpecific + 424
    frame #28: 0x00000001010890b8 Flutter`___lldb_unnamed_symbol1243$$Flutter + 88
    frame #29: 0x00000001010888c4 Flutter`___lldb_unnamed_symbol1219$$Flutter + 200
    frame #30: 0x00000001983d7d98 libsystem_pthread.dylib`_pthread_start + 156
```

<img width="1440" alt="Flutter_error" src="https://user-images.githubusercontent.com/2103762/77836777-68a6a080-7159-11ea-8961-e73f517b1929.png">

To reproduce I do:

1. From flutter channel I get message from button click and do:
```swift
DispatchQueue.main.async {
        result(true)
        let mc = MyViewController(...)
        self.navigationController?.pushViewController(mc, animated: true)
}
```

2. In MyViewController I click back or do swipe back
```swift
    @objc func backClick(sender:UIBarButtonItem){
        navigationController?.popViewController(animated: true)
    }
```
3. Crash - the app disappears

**Comment by MrLittleStrong** [comment]
> Deployed updated app to production - still happens on iOS 12, Flutter v1.16.0
> 
> Crashed: io.flutter.1.gpu
> 0 libGPUSupportMercury.dylib 0x1df279fe4 gpus_ReturnNotPermittedKillClient + 12
> 1 AGXGLDriver 0x1e38deed8 gldUpdateDispatch + 7184
> 2 libGPUSupportMercury.dylib 0x1df27afac gpusSubmitDataBuffers + 176
> 3 AGXGLDriver 0x1e38e0404 gldUpdateDispatch + 12604
> 4 GLEngine 0x1e498a234 gliPresentViewES_Exec + 184
> 5 OpenGLES 0x1c6542aa4 -[EAGLContext presentRenderbuffer:] + 80
> 6 Flutter 0x1012fb624 (Missing)
> 7 Flutter 0x1016f8280 (Missing)
> 8 Flutter 0x10135fdf0 (Missing)
> 9 Flutter 0x10134d2c0 (Missing)
> 10 Flutter 0x10134e044 (Missing)
> 11 Flutter 0x10134d56c (Missing)
> 12 Flutter 0x1013534c0 (Missing)
> 13 Flutter 0x10130bea0 (Missing)
> 14 Flutter 0x10130db18 (Missing)
> 15 CoreFoundation 0x1c32c9554 **CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION** + 28
> 16 CoreFoundation 0x1c32c9284 __CFRunLoopDoTimer + 864
> 17 CoreFoundation 0x1c32c8ab8 __CFRunLoopDoTimers + 248
> 18 CoreFoundation 0x1c32c3a08 __CFRunLoopRun + 1844
> 19 CoreFoundation 0x1c32c2fb4 CFRunLoopRunSpecific + 436
> 20 Flutter 0x10130d9f4 (Missing)
> 21 Flutter 0x10130d3c0 (Missing)
> 22 libsystem_pthread.dylib 0x1c2f552c0 _pthread_body + 128
> 23 libsystem_pthread.dylib 0x1c2f55220 _pthread_start + 44
> 24 libsystem_pthread.dylib 0x1c2f58cdc thread_start + 4

@gaaclarke  please check this

**Comment by rohnsht** [comment]
@gaaclarke Has this issue been fixed for real? I am still getting this error in the latest flutter version 1.16.2.
```Crashed: com.apple.main-thread
0  libGPUSupportMercury.dylib     0x1c757bfe4 gpus_ReturnNotPermittedKillClient + 12
1  AGXGLDriver                    0x1cbc29ed8 gldUpdateDispatch + 7184
2  libGPUSupportMercury.dylib     0x1c757cfac gpusSubmitDataBuffers + 176
3  AGXGLDriver                    0x1cbc2b404 gldUpdateDispatch + 12604
4  GLEngine                       0x1cccdc234 gliPresentViewES_Exec + 184
5  OpenGLES                       0x1ae776aa4 -[EAGLContext presentRenderbuffer:] + 80
6  Flutter                        0x1016af2b0 (Missing)
7  Flutter                        0x101aac26c (Missing)
8  Flutter                        0x10171390c (Missing)
9  Flutter                        0x1017012bc (Missing)
10 Flutter                        0x101701be8 (Missing)
11 Flutter                        0x101701568 (Missing)
12 Flutter                        0x101707064 (Missing)
13 Flutter                        0x1016bfb2c (Missing)
14 Flutter                        0x1016c17a4 (Missing)
15 CoreFoundation                 0x1ab4fd554 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
16 CoreFoundation                 0x1ab4fd284 __CFRunLoopDoTimer + 864
17 CoreFoundation                 0x1ab4fcab8 __CFRunLoopDoTimers + 248
18 CoreFoundation                 0x1ab4f7a08 __CFRunLoopRun + 1844
19 CoreFoundation                 0x1ab4f6fb4 CFRunLoopRunSpecific + 436
20 GraphicsServices               0x1ad6f879c GSEventRunModal + 104
21 UIKitCore                      0x1d7d58c38 UIApplicationMain + 212
22 Runner                         0x100f0a5f4 main + 5 (AppDelegate.swift:5)
23 libdyld.dylib                  0x1aafba8e0 start + 4```

I am getting this crash in ios 12 and below. Can we get the fix for this issue asap as my app is already in appstore and there are lots of this crashes?

**Comment by suancaiAmour** [comment]
> My previous PR got caught up in debate and a few proposals were floating around. @chinmaygarde and I just had a chat and we came up with a solution that may make everyone happy:
> 
> 1. Guard the image decoder's call to `MakeCrossContextFromPixmap` such that it will execute if we are foregrounded.  If we are backgrounded it will make a CPU backed image.  (note `SkiaGPUObject` doesn't actually mean it's a GPU object).
> 2. Make AppWillBackground notification wait until that the switch in 1 is executed.
> 3. Make the UnrefQueue also stop consuming its queue while backgrounded, using a mechanism similar to the one used in 1.  We'll have to make a way to flip it back on when the app is foregrounded as well, unlike the image decoder.
> 
> The benefits of this are that it doesn't pause the io thread which was worrisome since it's hard to test and could be broken in future PRs. The disadvantages are that it may cause the first frame after foregrounding to be slower and cause extra memory usage since Skia will cache the GPU texture representation.
> 
> This solution still leaves us open to future opengl code on the io thread we haven't considered. It is up to every implementor to know when a call may use OpenGL and guard it. I think we may safely be able to implement this. I'm worried about introducing minefields for a bug that is somewhat rare. I'll give it a shot shortly.

@gaaclarke, could tell me the link for this PR?  Is it 97a23a80e1b4f744c6d9d9f6d83f5c0df1aeb11f ?
Thank you very much.

**Comment by yrom** [comment]
@gaaclarke 
This issue has not been completly resolved by https://github.com/flutter/engine/pull/13908.

https://github.com/flutter/flutter/issues/26366#issuecomment-605722708 illustrates it may happen on platform thread, not just io thread:

```
...
21 UIKitCore                      0x1d7d58c38 UIApplicationMain + 212
22 Runner                         0x100f0a5f4 main + 5 (AppDelegate.swift:5)
23 libdyld.dylib                  0x1aafba8e0 start + 4
```


Enable `io.flutter.embedded_views_preview` in info.plist. And now the `GPU` task runner would be same as `platform`, see https://github.com/flutter/engine/blob/v1.12.13-hotfixes/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm#L423-L443. 
In this case the platform thread of App might be more frozen than before when [embedding Flutter](https://flutter.dev/docs/development/add-to-app/),  related issue https://github.com/flutter/flutter/issues/38689.
The `Shell` would  post a rendering task to `GPUTaskRunner` on Flutter drawing, see https://github.com/flutter/engine/blob/v1.12.13-hotfixes/shell/common/shell.cc#L904. But at some rare times, the GPUTaskRunner (platform thread) blocked, that task would be fired after the app `DidEnterBackground` and then the app crashed.

backtrace:
```
flutter::IOSSurfaceGL::GLContextPresent() (in Flutter) (ios_gl_render_target.mm:0)
std::__1::__function::__func<flutter::GPUSurfaceGL::AcquireFrame(SkISize const&)::$_1, std::__1::allocator<flutter::GPUSurfaceGL::AcquireFrame(SkISize const&)::$_1>, bool (flutter::SurfaceFrame const&, SkCanvas*)>::operator()(flutter::SurfaceFrame const&, SkCanvas*&&) (in Flutter) (functional:1651)
flutter::SurfaceFrame::Submit() (in Flutter) (surface.cc:30)
flutter::Rasterizer::DrawToSurface(flutter::LayerTree&) (in Flutter) (rasterizer.cc:317)
std::__1::__function::__func<flutter::Rasterizer::Draw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >)::$_0, std::__1::allocator<flutter::Rasterizer::Draw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >)::$_0>, void (std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >)>::operator()(std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >&&) (in Flutter) (rasterizer.cc:223)
flutter::Rasterizer::Draw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >) (in Flutter) (pipeline.h:154)
std::__1::__function::__func<flutter::Shell::OnAnimatorDraw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >)::$_29, std::__1::allocator<flutter::Shell::OnAnimatorDraw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >)::$_29>, void ()>::operator()() (in Flutter) (functional:1651)
fml::MessageLoopImpl::FlushTasks(fml::FlushType) (in Flutter) (message_loop_impl.cc:125)
fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (in Flutter) (message_loop_darwin.mm:76)
```

**Comment by godLoveY** [comment]
> ```
> Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision 7a4c33425d (2 months ago) • 2019-04-29 11:05:24 -0700
> Engine • revision 52c7a1e849
> Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
> ```
> 
> # 复现
> ```
> import 'dart:async';
> 
> import 'package:flutter/material.dart';
> 
> const int delayInitializeTime = 1000;
> 
> void main() async {
>   await Future.delayed(Duration(seconds: 2));
>   runApp(MaterialApp(
>     title: 'Title2',
>     home: Scaffold(
>       appBar: AppBar(
>         title: Text('114'),
>       ),
>       body: Container(
>         height: 52.0,
>         decoration: BoxDecoration(
>           image: DecorationImage(
>             image: AssetImage('assets/slide_A_login_background.png'),
>             fit: BoxFit.cover,
>           ),
>         ),
>       ),
>     ),
>   ));
> }
> ```
> 
> 启动瞬间点击home 按钮
> 
> # 设备
> iOS 12.1.4 (16D57)
> Model: iPad mini 3 (Model A1599))
> 
> # 堆栈信息
> ```
> * thread #10, name = 'io.flutter.1.io', stop reason = EXC_BAD_ACCESS (code=1, address=0x1)
>   * frame #0: 0x00000001b0e56f28 libGPUSupportMercury.dylib`gpus_ReturnNotPermittedKillClient + 12
>     frame #1: 0x00000001b563c8e0 AGXGLDriver`___lldb_unnamed_symbol555$$AGXGLDriver + 464
>     frame #2: 0x00000001b0e57f04 libGPUSupportMercury.dylib`gpusSubmitDataBuffers + 176
>     frame #3: 0x00000001b563de28 AGXGLDriver`___lldb_unnamed_symbol576$$AGXGLDriver + 292
>     frame #4: 0x0000000100ce20f0 Flutter`SkImage::MakeCrossContextFromEncoded(GrContext*, sk_sp<SkData>, bool, SkColorSpace*, bool) + 584
>     frame #5: 0x0000000100adf0d8 Flutter`std::__1::__function::__func<fml::internal::CopyableLambda<flutter::(anonymous namespace)::InstantiateImageCodec(_Dart_NativeArguments*)::$_1>, std::__1::allocator<fml::internal::CopyableLambda<flutter::(anonymous namespace)::InstantiateImageCodec(_Dart_NativeArguments*)::$_1> >, void ()>::operator()() + 1264
>     frame #6: 0x0000000100acfac8 Flutter`fml::MessageLoopImpl::FlushTasks(fml::MessageLoopImpl::FlushType) + 816
>     frame #7: 0x0000000100ad31d4 Flutter`fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) + 32
>     frame #8: 0x0000000193e6a718 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
>     frame #9: 0x0000000193e6a448 CoreFoundation`__CFRunLoopDoTimer + 864
>     frame #10: 0x0000000193e69c7c CoreFoundation`__CFRunLoopDoTimers + 248
>     frame #11: 0x0000000193e64b58 CoreFoundation`__CFRunLoopRun + 1880
>     frame #12: 0x0000000193e640e0 CoreFoundation`CFRunLoopRunSpecific + 436
>     frame #13: 0x0000000100ad32f8 Flutter`fml::MessageLoopDarwin::Run() + 88
>     frame #14: 0x0000000100acf71c Flutter`fml::MessageLoopImpl::DoRun() + 52
>     frame #15: 0x0000000100ad26d0 Flutter`void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*) + 200
>     frame #16: 0x0000000193af425c libsystem_pthread.dylib`_pthread_body + 128
>     frame #17: 0x0000000193af41bc libsystem_pthread.dylib`_pthread_start + 48
>     frame #18: 0x0000000193af7cf4 libsystem_pthread.dylib`thread_start + 4
> ```
> 
> # log
> ```
> 2019-07-10 18:40:29.539666+0800 Runner[1742:367348] You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
> 2019-07-10 18:40:29.539793+0800 Runner[1742:367348] You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
> 2019-07-10 18:40:30.154093+0800 Runner[1742:367394] flutter: Observatory listening on http://127.0.0.1:54303/0cbL-6hWs4U=/
> 2019-07-10 18:40:35.117194+0800 Runner[1742:367348] Could not load IOSurface for time string. Rendering locally instead.
> ```

这种复现方式在Flutter 1.12.13无效
