### ISSUE TITLE
Images consistently disappear or turn black when app is backgrounded on iOS and Android

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#26654]
If you have an image and background the app, then return to the app, all images will be black.  this happens 100% of the time.  It does not matter what the image is, it is happening with every image.

This will only happen with an actual device.  Does not happen on a simulator.

Example video: https://www.youtube.com/watch?v=IPqctRzgws4

Here's sample code to get it to happen: 
```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey,
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Image.asset('assets/download.jpeg'),
    );
  }
```

## Steps to Reproduce
1. Have a widget with an image on screen
2. Background the app or pull down the shade.
3. Observe issue

No analyzer issues or logs

```
[✓] Flutter (Channel master, v1.1.10-pre.83, on Mac OS X 10.13.6 17G4015, locale en-US)
    • Flutter version 1.1.10-pre.83 at /Users/KG/Developer/Flutter/flutter
    • Framework revision b4e9d0a440 (2 hours ago), 2019-01-16 08:47:37 -0800
    • Engine revision 3c0aa918de
    • Dart version 2.1.1 (build 2.1.1-dev.1.0 492df72739)

⡿f⢿^R
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2018.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 29.1.3
    • Dart plugin version 182.4892.25

[✓] Connected device (2 available)
    • iPhone    • 00008020-000A60D43688003A            • ios • iOS 12.1.2
    • iPhone XR • E16CDE36-3E2E-4C5D-B55B-6617AB71FA2F • ios • iOS 12.1 (simulator)

```

**Comment by tomknappe** [comment]
i can confirm this behavior on android also.

```
[✓] Flutter (Channel master, v1.1.10-pre.91, on Mac OS X 10.13.6 17G4015, locale de-DE)
    • Flutter version 1.1.10-pre.91 at /Users/tknappe/flutter
    • Framework revision 8f65ee9f53 (63 minutes ago), 2019-01-16 21:30:37 +0100
    • Engine revision 3c0aa918de
    • Dart version 2.1.1 (build 2.1.1-dev.1.0 492df72739)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/tknappe/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/tknappe/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 31.3.4
    • Dart plugin version 183.5153.38

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.0

[✓] Connected device (2 available)
    • SM A600FN         • 5200210646a3a587          • android-arm • Android 8.0.0 (API 26)
    • iPhone von Thomas • 00008020-001C18E41087493A • ios         • iOS 12.1.2
```

**Comment by kangwang1988** [comment]
@KevinTheGray 
Can you create a minimal runnable demo project to help to reproduce this issue?

**Comment by KevinTheGray** [comment]
@kangwang1988 : https://github.com/KevinTheGray/flutterissues

see README there for steps to reproduce

**Comment by tomknappe** [comment]
additional to that:
if you have a longer list of images, some images are broken ( black background with red noise...),some where displayed at the wrong place or the images contain some text of the list.

**Comment by TheBogueRat** [comment]
Same issue, it was worse on my iPod than Pixel 2.  Didn't notice this issue until upgrading flutter today. Last upgrade was earlier this week and didn't have an issue under heavy testing this week in prep for release.

Switched to stable branch and the issue was resolved. 

[✓] Flutter (Channel master, v1.1.10-pre.99, on Mac OS X 10.14.2 18C54, locale en-US)
    • Flutter version 1.1.10-pre.99 at /Users/jodyroth/flutter
    • Framework revision 244b077bee (6 hours ago), 2019-01-17 11:29:18 +0000
    • Engine revision 1e93a8eb39
    • Dart version 2.1.1 (build 2.1.1-dev.2.0 f701e11756)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jodyroth/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/jodyroth/Library/Android/sdkexport
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • Dev 6th Gen • 7171fc2fc8b2eac0ac95de05b8ef5c00f6950108 • ios • iOS 12.1.1

• No issues found!

![img_0201](https://user-images.githubusercontent.com/3030061/51336058-a423e600-1a51-11e9-8c3e-fc034d1a2998.PNG)

**Comment by knopp** [comment]
Same here, current master seems to be rather broken.

**Comment by knopp** [comment]
Also, hot restart after app has been in background causes crash.

**Comment by salehahmedZ** [comment]
Yes I faced this issue today on production app on IOS

**Comment by dnfield** [comment]
'Holding this open til engine rolls into framework

**Comment by dnfield** [comment]
To fill out some context here:

Updates were made on the engine side to better manage how and when a GrContext for resources is propagated.  Previous code led to missing the resource context if it was created too late in the engine's lifecycle.  

Unfortunately, the patch to fix this led to incorrectly revoking a valid GrContext that Dart still needed to display, e.g., images and fonts.

The linked patch fixes this.  It should land in the framework soon.

**Comment by jelenalecic** [comment]
@dnfield 

It happened again
"Flutter`SkNVRefCnt<GrBackendTextureImageGenerator::RefHelper>::unref:"

Happens each time ios app stays a while in a background. 

![screen shot 2019-01-22 at 1 46 13 pm](https://user-images.githubusercontent.com/17471080/51600524-7e3f8b00-1f02-11e9-81b8-f4cb4f73963c.png)

**Comment by zoechi** [comment]
@jelenalecic ensure you're on the latest `master` branch.
```
flutter channel master
flutter doctor
```

**Comment by jelenalecic** [comment]
@zoechi  @dnfield 

yup. we have been using master channel for a while now.

[✓] Flutter (Channel master, v1.1.10-pre.117, on Mac OS X 10.14.2 18C54, locale en-RS)
    • Flutter version 1.1.10-pre.117 at /Users/btomic/Documents/flutter
    • Framework revision 4fe79442c8 (5 days ago), 2019-01-17 19:36:48 -0800
    • Engine revision 4acfced383
    • Dart version 2.1.1 (build 2.1.1-dev.2.0 da09945643)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/btomic/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected device (1 available)
    • Borko4vp • 9ee55b20cec62d7ab4ae0a71dbbecb78ecc48f24 • ios • iOS 12.1.2

• No issues found!

**Comment by dnfield** [comment]
Some changes landed yesterday, can you update and check again?

**Comment by dnfield** [comment]
@jelenalecic Can you try latest master again?  Another lingering issue related to this was resolved just 30 minutes or so ago.

I'm going to remove TODAY from this since I don't have any reproducible cases for this - it's also a little suspicious that the doctor output there reported the revision from where this bug was still known.

**Comment by jelenalecic** [comment]
@dnfield 
Sorry, I'm waiting for a colleague of mine to test this.
He tried yesterday, but flutterView in our iOS app was totally empty.
 
I will let you know as soon as we check this issue in detail.

**Comment by jelenalecic** [comment]
@dnfield 

Borkos-iMac:flutter-comment-wall btomic$ flutter doctor -v
[✓] Flutter (Channel master, v1.1.10-pre.180, on Mac OS X 10.14.2 18C54, locale en-RS)
    • Flutter version 1.1.10-pre.180 at /Users/btomic/Documents/flutter
    • Framework revision 789376b830 (3 hours ago), 2019-01-25 02:27:39 -0500
    • Engine revision 36acd02c94
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 f4afaee422)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/btomic/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected device (2 available)
    • Borko4vp  • 9ee55b20cec62d7ab4ae0a71dbbecb78ecc48f24 • ios • iOS 12.1.2
    • iPhone 6s • 79EAAB25-894C-428A-969B-134C927671A7     • ios • iOS 11.4 (simulator)

• No issues found!

and this is how our viewController inside iOS app looks like(just black background):

![6ea58ca8-b554-4815-b564-26d9c43b338e](https://user-images.githubusercontent.com/17471080/51740651-e3c38100-2094-11e9-9d64-75fec51d3714.jpg)



class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?
    var flutterEngine : FlutterEngine?
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil) -> Bool {
        if CommandLine.arguments.contains(uiTesting) {
            resetState()
        }
        
        self.flutterEngine = FlutterEngine(name: "io.flutter", project: nil)
        self.flutterEngine?.run(withEntrypoint: nil)
        GeneratedPluginRegistrant.register(with: self.flutterEngine)
        
        
        if let launchOptions = launchOptions {
            handleAppStartedWith(launchOptions: launchOptions)
        }
 return true
}


and displaying the view:

    let flutterEngine = (UIApplication.shared.delegate as? AppDelegate)?.flutterEngine
        let vc = CommentWallViewController(engine: flutterEngine, nibName: nil, bundle: nil)
        self.navigationController?.pushViewController(vc!, animated: true)






open class CommentWallViewController: FlutterViewController {....}
... with our logic for setting route.

**Comment by jelenalecic** [comment]
@dnfield @zoechi 
any updates on this? we can not merge this feature into our existing iOS app :)

**Comment by kangwang1988** [comment]
@jelenalecic 
Fail to reproduce this issue using the latest master.
Besides, should 'class AppDelegate: UIResponder' be 'class AppDelegate: FlutterAppDelegate'?

**Comment by Borko4vp** [comment]
Hi @kangwang1988, 
I am @jelenalecic 's colleague, and i have just reproduced the exact same issue as @jelenalecic described few posts above, with latest flutter built from master channel. 
Please let us know, if you need additional information from our side to help you work on this issue.

**Comment by Borko4vp** [comment]
1. First of all to try to explain how we use flutter within our app:
		1. We have a flutter project created by @jelenalecic
		2. We have a "wrapper framework" project named OctopusCommentWall (which we link with flutter using cocoa_pods and suggested scripts from https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps), 
		which produce OctopusCommentWall.framework to be used by the main app.
		3. We have a standalone app (CommentWallFlutterTest for the purpose of this thread) in which we manually link following items (as resources within the project):
			1. OctopusCommentWall.framework - produced by "wrapper framework" explained in step 2
			2. FlutterPluginRegistrant.framework 
			3. Flutter.framework
			4. flutter_assets
	2. I have created new sample project and pushed to the repository: 
	https://github.com/Borko4vp/CommentWallFlutterTest
	There are 3 commits on the repository: 
		1. First commit is the working version built with flutter engine from master channel on January 21st (not sure about the exact revision)
		2. Second commit is version built with flutter engine from master channel (built today, Framework • revision bb5663d2d8, Engine • revision 9b6d5031a3).
		In console output of the sample application, I have noticed following errors: 
		_**2019-01-29 11:38:29.680171+0100 CommentWallFlutterTest[34715:6056223] Failed to find assets path for "Frameworks/App.framework/flutter_assets"
		2019-01-29 11:38:29.774702+0100 CommentWallFlutterTest[34715:6056316] [VERBOSE-2:engine.cc(115)] Engine run configuration was invalid.
		2019-01-29 11:38:29.774771+0100 CommentWallFlutterTest[34715:6056316] [VERBOSE-2:FlutterEngine.mm(291)] Could not launch engine with configuration.
		2019-01-29 11:38:29.840150+0100 CommentWallFlutterTest[34715:6056324] flutter: Observatory listening on http://127.0.0.1:60887/**_
		I believe it has something to do with the following statement in your instruction on https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps which says: "The flutter_assets folder gets embedded into App.framework as of flutter/flutter#26630, and this step is no longer necessary."
		And our project (which is using flutter) is not a standalone application, but we built a framework,  which we linked in our app manually along with the "flutter_assets".
		3. Third commit is just: 
		Adding FlutterEngine property to AppDelegate
		*as suggested by latest instruction from "https://github.com/flutter/flutter/wiki/Add- 
                 Flutter-to-existing-apps" Just to show black ViewController issue we reproduce with latest 
                 flutter engine from master channel.

Hope all this makes sense to you and will help you track down the problem we encounter.

**Comment by dnfield** [comment]
That's definitely a different error but it makes sense.

The default location for flutter_assets has been updated.  The engine now expects to find it in `Frameworks/App.framework/flutter_assets`, whereas it used to look for it at the root of the project.

You can override this setting using FLTAssetPath in your Info.plist.  https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm#L183

Can you check where this folder is actually ending up in your app and either mvoe it or update FLTAssetPath?

**Comment by dnfield** [comment]
(Original comment said `FLTAssetPath` - it's actually `FLTAssetsPath`, with an extra S in there)

**Comment by Borko4vp** [comment]
Thanks @dnfield . I have added this into my Info.plist. Looks like it worked. We will do some additional testing today and let you know if original issue(crash) from this thread is fixed.

**Comment by Borko4vp** [comment]
After some additional testing, looks like the initial issue(crash) is resolved. Thanks for your support on this.

**Comment by dnfield** [comment]
Great, I'm going to close this.  Please feel free to open another issue if you're seeing any problems!

**Comment by partnercloudsupport** [comment]
Hi. We are experiencing this issue now. We see that your recommend "(Original comment said `FLTAssetPath` - it's actually `FLTAssetsPath`, with an extra S in there)" Where is this file located. Can you give the exact location? We have searched and can not locate this in the info file. Where to we insert this?

**Comment by dnfield** [comment]
@partnercloudsupport - would you mind opening a new issue with your exact problem, logs, and ideally a reproduction?  This issue got a bit overloaded with a few different seemingly related problems that weren't actually related.  I'm not sure which one you're saying is the same.  Feel free to tag me in the new issue!

**Comment by long1eu** [comment]
I still have this issue.
<img width="300" src="https://user-images.githubusercontent.com/9283414/52988828-75f74480-3409-11e9-8abd-67e5a5bc2b9c.png">

```
[✓] Flutter (Channel master, v1.2.1, on Mac OS X 10.13.6 17G5019, locale en-RO)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.4)
[✓] Connected device (1 available)
```

**Comment by long1eu** [comment]
Same thing on latest master.

```
[✓] Flutter (Channel master, v1.2.2-pre.21, on Mac OS X 10.13.6 17G5019, locale en-RO)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.4)
[✓] Connected device (1 available)
```

<img width="300" src="https://user-images.githubusercontent.com/9283414/52989189-f9656580-340a-11e9-88e2-225a52b1143f.png">

**Comment by dnfield** [comment]
Same request as above @long1eu.  If you could, please open a new issue with reproduction steps.  Feel free to tag me in it.

**Comment by slightfoot** [comment]
Relates to #27675
