### ISSUE TITLE
GoogleSignIn.signIn() fails with ActivityNotFoundException

### ISSUE THREAD

**Issue by autolainen** [flutter/flutter#26777]
I am trying to sign in to Firebase using google account:

```dart
class _MyHomePageState extends State<MyHomePage> {
  final GoogleSignIn _googleSignIn = GoogleSignIn();
  final FirebaseAuth _auth = FirebaseAuth.instance;

  @override
  void initState() {
    super.initState();
    _handleSignIn();
  }

  Future<FirebaseUser> _handleSignIn() async {
    GoogleSignInAccount googleUser = await _googleSignIn.signIn();  // fails here
    GoogleSignInAuthentication googleAuth = await googleUser.authentication;
    FirebaseUser user = await _auth.signInWithGoogle(
        idToken: googleAuth.idToken,
        accessToken: googleAuth.accessToken);
    return user;
  }
```
The exception is:
```
E/MethodChannel#plugins.flutter.io/google_sign_in( 7487): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.shoppinglistflutter/com.google.android.gms.auth.api.signin.internal.SignInHubActivity}; have you declared this activity in your AndroidManifest.xml?
E/MethodChannel#plugins.flutter.io/google_sign_in( 7487): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1820)
E/MethodChannel#plugins.flutter.io/google_sign_in( 7487): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1531)
E/MethodChannel#plugins.flutter.io/google_sign_in( 7487): 	at android.app.Activity.startActivityForResult(Activity.java:4403)
E/MethodChannel#plugins.flutter.io/google_sign_in( 7487): 	at android.app.Activity.startActivityForResult(Activity.java:4362)
E/MethodChannel#plugins.flutter.io/google_sign_in( 7487): 	at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate.signIn(GoogleSignInPlugin.java:292)
E/MethodChannel#plugins.flutter.io/google_sign_in( 7487): 	at io.flutter.plugins.googlesignin.GoogleSignInPlugin.onMethodCall(GoogleSignInPlugin.java:77)
E/MethodChannel#plugins.flutter.io/google_sign_in( 7487): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#plugins.flutter.io/google_sign_in( 7487): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#plugins.flutter.io/google_sign_in( 7487): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/google_sign_in( 7487): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#plugins.flutter.io/google_sign_in( 7487): 	at android.os.Looper.loop(Looper.java:136)
E/MethodChannel#plugins.flutter.io/google_sign_in( 7487): 	at android.app.ActivityThread.main(ActivityThread.java:6776)
E/MethodChannel#plugins.flutter.io/google_sign_in( 7487): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/google_sign_in( 7487): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
E/MethodChannel#plugins.flutter.io/google_sign_in( 7487): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
D/AndroidRuntime( 7487): Shutting down VM
E/AndroidRuntime( 7487): FATAL EXCEPTION: main
E/AndroidRuntime( 7487): Process: com.example.shoppinglistflutter, PID: 7487
E/AndroidRuntime( 7487): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=53293, result=0, data=null} to activity {com.example.shoppinglistflutter/com.example.shoppinglistflutter.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 7487): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4520)
E/AndroidRuntime( 7487): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4563)
E/AndroidRuntime( 7487): 	at android.app.ActivityThread.-wrap22(ActivityThread.java)
E/AndroidRuntime( 7487): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
E/AndroidRuntime( 7487): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 7487): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime( 7487): 	at android.app.ActivityThread.main(ActivityThread.java:6776)
E/AndroidRuntime( 7487): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7487): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
E/AndroidRuntime( 7487): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
E/AndroidRuntime( 7487): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 7487): 	at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:174)
E/AndroidRuntime( 7487): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:208)
E/AndroidRuntime( 7487): 	at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate.finishWithError(GoogleSignInPlugin.java:386)
E/AndroidRuntime( 7487): 	at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate.onActivityResult(GoogleSignInPlugin.java:517)
E/AndroidRuntime( 7487): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:210)
E/AndroidRuntime( 7487): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:139)
E/AndroidRuntime( 7487): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:138)
E/AndroidRuntime( 7487): 	at android.app.Activity.dispatchActivityResult(Activity.java:7280)
E/AndroidRuntime( 7487): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4516)
E/AndroidRuntime( 7487): 	... 9 more
I/art     ( 7487): Background sticky concurrent mark sweep GC freed 20986(1372KB) AllocSpace objects, 7(140KB) LOS objects, 48% free, 3MB/6MB, paused 18.082ms total 61.512ms
E/flutter ( 7487): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 7487): PlatformException(error, Unable to find explicit activity class {com.example.shoppinglistflutter/com.google.android.gms.auth.api.signin.internal.SignInHubActivity}; have you declared this activity in your AndroidManifest.xml?, null)
E/flutter ( 7487): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter ( 7487): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
E/flutter ( 7487): <asynchronous suspension>
E/flutter ( 7487): #2      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:217:58)
E/flutter ( 7487): <asynchronous suspension>
E/flutter ( 7487): #3      GoogleSignIn._addMethodCall (package:google_sign_in/google_sign_in.dart:256:20)
E/flutter ( 7487): #4      GoogleSignIn.signIn (package:google_sign_in/google_sign_in.dart:324:48)
E/flutter ( 7487): #5      _MyHomePageState._handleSignIn (package:shopping_list_flutter/main.dart:89:58)
E/flutter ( 7487): <asynchronous suspension>
E/flutter ( 7487): #6      _MyHomePageState.initState (package:shopping_list_flutter/main.dart:67:5)
E/flutter ( 7487): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3830:58)
E/flutter ( 7487): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter ( 7487): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 7487): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 7487): #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter ( 7487): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 7487): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 7487): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter ( 7487): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter ( 7487): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter ( 7487): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter ( 7487): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 7487): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 7487): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter ( 7487): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 7487): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 7487): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter ( 7487): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 7487): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 7487): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter ( 7487): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 7487): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 7487): #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter ( 7487): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 7487): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 7487): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter ( 7487): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter ( 7487): #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter ( 7487): #35     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
E/flutter ( 7487): #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter ( 7487): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 7487): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 7487): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter ( 7487): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter ( 7487): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter ( 7487): #42     ComponentElement.mount (package:flutter/src
```
Dependencies are:
```yml
  firebase_auth:  ^0.6.6
  google_sign_in: ^3.2.4
```
Doctor:
```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 6.1.7601], locale ru-RU)
    • Flutter version 1.0.0 at C:\flutter
    • Framework revision 5391447fae (7 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:/Android_sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:/Android_sdk
    • Java binary at: C:\Program Files\Android\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\android-studio
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] Connected device (1 available)
    • SM A310F • 310084d1272f13c7 • android-arm • Android 7.0 (API 24)

! Doctor found issues in 1 category.
```
The log says Flutter plugins not installed but in fact they are installed.

**Comment by CaptMustache** [comment]
Same here

`[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-DE)
    • Flutter version 1.0.0 at /Users/cm/flutter/sdk
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/cm/android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Pixel 3 XL • 8ABY0H8D2 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
`

` google_sign_in: ^4.0.1+1
  firebase_auth: ^0.8.1+1`

**Comment by gi097** [comment]
Same. Really annoying, I experience a lot of issues with the Firebase plugins for Flutter.

**Comment by autolainen** [comment]
This issue and another one https://github.com/flutter/flutter/issues/27300  actually stopped my development for few weeks now. I can not login to firebase in any way.

**Comment by gi097** [comment]
I will do an attempt to fix it and create a PR.

**Comment by gi097** [comment]
Fixed in https://github.com/flutter/plugins/pull/1234

**Comment by gi097** [comment]
@zoechi could the `waiting for PR to land (fixed)` label be added?

**Comment by autolainen** [comment]
Yes the solution worked. The code slightly changed though:
```
  Future<FirebaseUser> _handleSignIn() async {
    GoogleSignInAccount googleUser = await _googleSignIn.signIn();
    GoogleSignInAuthentication googleAuth = await googleUser.authentication;
    final AuthCredential credential = GoogleAuthProvider.getCredential(
        idToken: googleAuth.idToken, accessToken: googleAuth.accessToken);
    FirebaseUser user = await _auth.signInWithCredential(credential);
    return user;
  }
```
To connect to firebase realtime database under Google account make sure:
1. you have SHA-1 certificate properly setup in Firebase console on the page where you downloaded google-services.json. I added my debug certificate there and it worked fine. How to find it read [here](https://stackoverflow.com/a/35201531/5526845)
2. login under Google account is allowed in the Firebase console. The setting is in Auth section.

Fragment of code which actually gets the data:
```
  void initState() {
    super.initState();
    _handleSignIn().then((user) {
      print("user.uid: " + user.uid);
      DatabaseReference reference = FirebaseDatabase.instance
          .reference()
          .child("users")
          .child(user.uid)
          .child("shopping_lists");
      reference.onChildAdded.listen((Event event) {
        Map valueMap = event.snapshot.value;
        String name = valueMap['name'] as String;
        print("name: " + name);
      });
    });
  }
```

**Comment by function1983** [comment]
Maybe they also need to update the installation instruction to include this piece of code inside the <application> tag of your AndroidManifest.xml

```
<application>
......
<activity
          android:name="com.google.android.gms.auth.api.signin.internal.SignInHubActivity"
android:screenOrientation="portrait"
android:windowSoftInputMode="stateAlwaysHidden|adjustPan" />
......
</application>
```

**Comment by mohammadanton** [comment]
> Maybe they also need to update the installation instruction to include this piece of code inside the tag of your AndroidManifest.xml
> 
> ```
> <application>
> ......
> <activity
>           android:name="com.google.android.gms.auth.api.signin.internal.SignInHubActivity"
> android:screenOrientation="portrait"
> android:windowSoftInputMode="stateAlwaysHidden|adjustPan" />
> ......
> </application>
> ```

Although I add this to manifest, the error still saying this

**Comment by mohammadanton** [comment]
> Fixed in [flutter/plugins#1234](https://github.com/flutter/plugins/pull/1234). @autolainen you can fix it locally by editing the file directly in `/Users/username/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.8.1+1 /` and clearing the build cache.

How to clear the build cache?
I'm run 'flutter packages get'
then 'flutter run' but the problem still persist
Failed to find activity signInHubActivity

**Comment by NHuyHoang** [comment]
Thank you so much @gi097, I successfully fixed it by adding
`dependencies {
     ...
     api 'com.google.android.gms:play-services-auth:16.0.1'
}` in the directory `~/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-<version>/android/build.gradle`

**Comment by nonComBen** [comment]
'flutter clean' command from the project directory worked for me

**Comment by mohammadanton** [comment]
Somehow after I clean project and rebuild it with android studio, it workings

**Comment by cyanglaz** [comment]
As I am reading through the issue, it seems that the issue can be fixed by cleaning the project? Is there an actionable item that we can do to make the experience better? And it seems that `api 'com.google.android.gms:play-services-auth:16.0.1'` is already in the google_sign_in plugin so it shouldn't be a problem.

**Comment by abdoutech93** [comment]
I'm getting a same error trying to setup social login in Flutter App using GoogleSignIn and facebookSignIn via Firebase-auth I'm getting this error :

`java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/LifecycleEventObserver`

I'm using thoses packages :

```
flutter_facebook_login: ^3.0.0
 google_sign_in: ^4.0.14
 firebase_auth: ^0.15.1
```

With **flutter 1.9.1 + hotfix.6** 

If sharing my code will be helpfull I'll do but I'm using the same function shared on official example. 

I would say also that maybe have relation with **AndroidX** cause my project if under AndroidX and **Landroidx**/lifecycle/LifecycleEventObserver`
