### ISSUE TITLE
Lost connection to device on save

### ISSUE THREAD

**Issue by YAPPDEF** [flutter/flutter#26945]
**Steps to reproduce:**
* Start app in debug mode
* Do any change in the code and save (hot reload)
* App crashes

```
Launching lib/main.dart on iPhone XS in debug mode...
Xcode build done.                                            8.2s
Reloaded 23 of 717 libraries in 3’584ms.
Lost connection to device.
Exited (sigterm)
```

I didn't update and have this issue since yesterday. Any ideas?

```
flutter doctor -v
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.2 18C54, locale de-CH)
    • Flutter version 1.0.0 at /Users/defuns/Development/Tools/flutter
    • Framework revision 5391447fae (8 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/defuns/Library/Android/sdk
    • Android NDK at /Users/defuns/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/defuns/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (2 available)
    • Philippe  • 00008020-000A615C11E2002E            • ios • iOS 12.1.2
    • iPhone XS • 3B2D3077-9F8D-43A6-B013-71ABC41CC464 • ios • iOS 12.1 (simulator)

• No issues found!
```

**Comment by YAPPDEF** [comment]
@zoechi I was not able to get the logs from XCode but I got them from the Simulator itself (Debug > Open System Log...)

I cleaned the log after startup and this is what's logged on save.
```
Jan 23 13:54:37 philippe-macbook-pro com.apple.CoreSimulator.SimDevice.8215D839-35A9-4573-A99C-ACA63767F281[58358] (com.apple.securityuploadd): Service only ran for 5 seconds. Pushing respawn out by 5 seconds.
Jan 23 13:54:37 philippe-macbook-pro com.apple.CoreSimulator.SimDevice.8215D839-35A9-4573-A99C-ACA63767F281[58358] (UIKitApplication:com.yapeal.core[0xf9a4][58380][66817]): Service exited due to SIGSEGV | sent by exc handler[66817]
```

**Comment by zoechi** [comment]
You are not by any chance use a proxy or self-signed certificates?

**Comment by zoechi** [comment]
Try manually uninstall from the phone/simulator and run `flutter clean`.

**Comment by MisterJimson** [comment]
I started seeing this about 3 weeks ago. Very often I get Lost Connection when hot reloading on iOS.

I've tried flutter clean and uninstalling the app.

**Comment by MisterJimson** [comment]
I just see.

```
Performing hot reload...
Syncing files to device iPad Air 2...
Lost connection to device.
```

And the app is left frozen.

**Comment by zoechi** [comment]
You can raise priority with thumbs-up on the initial comment 
https://github.com/flutter/flutter/wiki/Issue-hygiene#thumbs-up-reactions

**Comment by Genert** [comment]
Bump.

**Comment by MisterJimson** [comment]
I no longer am seeing this issue as of around Flutter 1.5

**Comment by hetkpatel** [comment]
I am on version 1.5.4 and having this issue. As soon as I run my app, it says `Syncing files to device...` then says `Lost connection to device`

**Comment by aiman5252** [comment]
> I am on version 1.5.4 and having this issue. As soon as I run my app, it says `Syncing files to device...` then says `Lost connection to device`
> 
> I have tried to reboot Android Studio and my laptop but nothing seemed to work.

Me too, It's my first time building flutter on MacOS and right after my app launched the log says `Lost connection to device`.

**Comment by nielslbeck** [comment]
Same behavior for me. MacOS and after launch, it loses the connection to the device.

**Comment by mtin79** [comment]
+1 same issue.
Just did $ flutter upgrade.
Now running a freshly created flutter app via vscode in debug mode doesn't hot reload any longer and i get the error:
"Lost connection to device."

**Comment by zmhbh** [comment]
> **+1 Same issue here.**
> 
> Just did: `$ flutter upgrade`
> Now running a freshly created flutter app via vscode in debug mode doesn't hot reload any longer and
> 
> i get the error:
> `"Lost connection to device."`


Same here as well. "Lost connection to device." immediately after launch. Hot reloading not working properly

**Comment by aeriu** [comment]
Same here as well. "Lost connection to device." immediately after launch. Debugging is not working.
Even after downgrading to 1.5.0 I get the same error message!

**Comment by daniel-v** [comment]
I too experienced this. Tried mostly everything I could find on the internet. Tried 

* `NO_PROXY=127.0.0.1,localhost; flutter run -v`, 
* turned off debugging over WiFi in XCode
* killed iTunes and disabled syncing
* switched cables (original iPhone cables)
* switched iPhones (both iPhone X, iOS v 12.3.1)

*Versions:*

Mac OS Mojave 10.14.5
XCode 10.2.1
MacBook Pro 2016
iOS 12.3.1
Flutter 1.5.4, Flutter beta, even tried on some older 1.0+ versions

I think, the error message is a tad misleading; I don't think flutter command runner could make connection to the observatory at all, however I don't have any evidence to this.

After a few attempts, there are a number of `iproxy` instances "stuck", as though `flutter run` didn't terminate normally.

What worked without hickup is running the same app on Android device.

For now, just a wild idea is that docker virtual interfaces might be interfering?

**Comment by daniel-v** [comment]
Update:

after killing all docker related services and removed the networks created for docker, the error has changed from `lost connection to device` to `Error connecting to service protocol`. 

![error](https://user-images.githubusercontent.com/2668320/60115555-79fbf000-9776-11e9-930a-11e10b36b0a3.png)

**Comment by sendwich** [comment]
Tried all of these, still can't debug on a physical device. 

> Lost connection to device.
Solutions??

**Comment by passol1988** [comment]
+1
Same issue here.

**Comment by elixiao** [comment]
Same problem. Every time I run `flutter run`, it loses connection to the device immediately after app launch.

```
$ flutter run
Launching lib/main.dart on LX in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: HD5523TJD5
Running Xcode build...                                                  
                                                   
 ├─Assembling Flutter resources...                           2.5s
 └─Compiling, linking and signing...                         3.7s
Xcode build done.                                            8.3s
Installing and launching...                                        13.0s
Syncing files to device LX...                                       
 2,587ms (!)                                       

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on LX is available at: http://127.0.0.1:1024/lhuDWtJTrdo=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
Lost connection to device.
```

**Comment by follyxing** [comment]
Same problem +1

![image](https://user-images.githubusercontent.com/4349448/60263470-55894a80-9913-11e9-8d66-2ce4fd34da9e.png)

MacOS Mojave 10.14.5

**Comment by luisabreuacevedo** [comment]
+1
Same issue here.

Flutter 1.5.4-hotfix.2
MacOS Mojave 10.14.5
Xcode 10.2.1

**Comment by najeira** [comment]
https://github.com/flutter/flutter/issues/35102#issuecomment-505952116 is a workaround for this. see that.

**Comment by lvyaojia** [comment]
+1
Same issue here.

**Comment by daniel-v** [comment]
> [#35102 (comment)](https://github.com/flutter/flutter/issues/35102#issuecomment-505952116) is a workaround for this. see that.

This seem to have fixed both MacOS installs I knew of that had this problem. Single note: iproxy instances were stuck, computer restart was needed.

**Comment by Genert** [comment]
This issue is fixed. Please close this.

**Comment by myvsparth** [comment]
You can check stackoverflow answer. This may solve your problem
Flutter: “Lost connection to device” error after Hot Reload

**Comment by TheKashe** [comment]
I'm getting this in Android Studio, with usbmux updated. VSC works.

So for me, with Android Studio, this is not closed.

**Comment by seb-almeida** [comment]
+1 Same here, still having this issue.

macOS Mojave 10.14.6
Xcode 10.2.1
Flutter 1.7.8+hotfix.4
Intellij Idea 2019.2 with Flutter Plugin 38.1.4

**Comment by MisterJimson** [comment]
I still see this from time to time as well, using Android Studio.

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88,
    locale en-CA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version
    28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
[✓] Android Studio (version 3.5)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
[✓] VS Code (version 1.40.0)
[✓] Connected device (1 available)

• No issues found!

```

**Comment by CedYF** [comment]
I'm getting this as well after doing Flutter Upgrade.

**Comment by muhammadfaisal970** [comment]
getting Lost connection to device after upgrading using flutter upgrade!

**Comment by GeorgeKnap** [comment]
I am getting the same behavior and it  turns out it works if you disable automatic opening of dart devtools in chrome.  (applies to lost connection to device in vscode)

https://stackoverflow.com/a/59748306/5790305

**Comment by believejava** [comment]
I am also got the same issue as below,

huangweipeng@huangweipengs-MacBook-Pro colorful_classroom_app % flutter run   
Launching lib/main.dart on iPhone 11 Pro in debug mode...
Running Xcode build...                                                  
                                                   
 └─Compiling, linking and signing...                         9.6s
Xcode build done.                                           21.4s
Waiting for iPhone 11 Pro to report its views...                     3ms
Lost connection to device.                                              
Syncing files to device iPhone 11 Pro...

**Comment by jonahwilliams** [comment]
There are a lot of unrelated issues posted in this thread, unfortunately that is making it impossible to tell what is tracking. Generally this could happen if the application crashes, but then we need a stack trace to figure out what is happening.

Without a way to reproduce the issue on our end there is nothing for us to do here. I'm closing the issue for now, but feel free to re-open if you can provide a [minimal reproducible-example](https://stackoverflow.com/help/minimal-reproducible-example)
