### ISSUE TITLE
GoogleMaps android OS freeze

### ISSUE THREAD

**Issue by awazgyawali** [flutter/flutter#27190]
## Steps to Reproduce

Its an issue with google maps which directly relates to platform view. Whenever I add a google map widget on screen and minimize the app and get out of it, without closing. After a certain time, the entire phone freezes, (not only the flutter application). I have to forcefully restart the device to get out of the tragedy. OnePlus 6 is where this is happening, not sure if its device specific.

Code to reproduce, I am contributing on google maps plugin and the example app crashes too.

## Logs

I am unable to attach it, coz its not certain when It happens. I may attach something soon though.

```
[✓] Flutter (Channel dev, v1.1.9, on Mac OS X 10.14.2 18C54, locale en-US)
    • Flutter version 1.1.9 at /Users/aawaz/development/flutter
    • Framework revision 1407091bfb (3 weeks ago), 2019-01-08 20:40:19 -0800
    • Engine revision e5ec3cf3ea
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 2cb346bd0c)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/aawaz/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[!] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.1

[✓] Connected device (1 available)
    • ONEPLUS A6000 • 3fabac74 • android-arm64 • Android 9 (API 28)

```

**Comment by kangwang1988** [comment]
@awazgyawali 
We can't move further before we can reproduce this issue.
I would suggest you to dig more to see if there is any log(adb logcat,etc) which can provide much more useful information.

**Comment by gopchi** [comment]
Hey guys, I am experiencing severe crashes when re-rendering the map. For example: my app contains a couple of pages, which have a Google map (the official plugin with inline maps). Sometimes when I load a page and then go to another one with a map the app crashes. On some phones the map renders on init and the on navigate to another page, again crashes. We tested and removed the map from the app and it did NOT crash. 

We connected Firebase Crashlytics and we got this error: **java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.Display.getDisplayId()' on a null object reference**

We found an issue here #26345 but nothing is happening with it, too. This is a very serious issue and we really need some help with it from someone. We need to put our app in production and we are open to suggestions and help. If anyone can offer some help, would be appreciated and rewarded. Thanks in advance!

**Comment by davidgalarza** [comment]
Any update I'm Having the same error hoanglm4/flutter_youtube_view#5

**Comment by sergicastellsague** [comment]
Does anybody have a workaround for this? Maybe delaying the initialization of the map?

**Comment by rafaelcorbellini-egsys** [comment]
any update?

**Comment by yuridiniz** [comment]
This also happens on the LG K10 Android 7, it does not happen all the time, but in the moments that happens I had to remove the battery, also makes the device very hot

**Comment by rafaelcorbellini-egsys** [comment]
any alternative? my application is totally map based and this error makes the application unfeasible

**Comment by awazgyawali** [comment]
Is there any update on this from the team, I  am stuck on this for about a year now. The whole phone freezes and as I result I have to remove all the platform view widgets from the widget tree in order to build and debug the app. 

Its a nightmare for me.

**Comment by EbenezerGH** [comment]
Happening on Oneplus 6 as well.

**Comment by thevishvajeet** [comment]
happpening one one plus 7t as well

**Comment by davbaron** [comment]
I have a OnePlus 7T as well and am experiencing the exact same problem - it is quite scary, as you never know if the phone will 'come back' or not...   From observing my app many times, it seems that yes, once the app goes into the background, it takes approximately 3 minutes for the entire phone to freeze up/crash.  If however, during those 3 minutes, you bring the app back to front, then you do NOT get a crash after the total of 3 minutes... Meaning, as long as the app is in the front, all is good.

**Comment by PingShen** [comment]
@kangwang1988 this crash so frequency,it blocks our schedule,The flutter team does not have any conclusion?

**Comment by KhoaSuperman** [comment]
Same here. Happen on my Samsung Note 10 Android 10. Flutter 1.9.1+hotfix.6.
it freezes the phone then I have to hard reset.

**Comment by nihar1024** [comment]
Multiple users of our app with OnePlus devices are reporting this issue. It seems to completely freeze their device and only a reboot fixes it.

**Comment by KlausJokinen** [comment]
Coupe toi test If the issue exists with this PR: https://github.com/flutter/plugins/pull/2458

**Comment by davbaron** [comment]
I would like to test... please show me how to configure my dependencies within pubspec.yaml to reference the test version of the plugin

**Comment by KlausJokinen** [comment]
> I would like to test... please show me how to configure my dependencies within pubspec.yaml to reference the test version of the plugin

```
name: map_test
description: Map test.

version: 1.0.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  google_maps_flutter:
    git:
      url: git://github.com/klausjokinen/plugins/
      path: packages/google_maps_flutter
      ref: map_fixes


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```

**Comment by davbaron** [comment]
Unfortunately this did not fix the problem for me. I tried two tests:  First I left the running app 'on top' (active) and let the phone 'go to sleep'.  After 4 minutes the phone was non-responsive - had to be hard-rebooted.  Second I brought another app to top, and 'used it' for several minutes.  After the 3rd minute or so the top app froze and the device had to be hard rebooted.

-David

**Comment by KlausJokinen** [comment]
> Unfortunately this did not fix the problem for me. I tried two tests: First I left the running app 'on top' (active) and let the phone 'go to sleep'. After 4 minutes the phone was non-responsive - had to be hard-rebooted. Second I brought another app to top, and 'used it' for several minutes. After the 3rd minute or so the top app froze and the device had to be hard rebooted.
> 
> -David

Sorry to hear that. I've been unable to reproduce this error myself. What devices you are using and are you using real devices or emulators. Can you also post the code which you were using to test?

**Comment by davbaron** [comment]
This is happening on my own OnePlus 7T.  Others on this thread (and the other threads) report this happening to OnePlus 6, Note 10 and others. It does NOT happen on the emulator.

I have already posted the code I am using, and you have already acknowledged it, on thread #43579 ([https://github.com/flutter/flutter/issues/43579]).  It is the 'sample' code from the google_maps_flutter site - as simple as it gets.

There will need to be some amount of instrumentation or some kind of app placed on an affected device that can record exactly what is going on, not just with the Flutter app, but with the Android OS.  Something 'dies' on the device, though, interestingly, not everything. Just a couple of nights ago I was running the app on my device while talking to a friend/tester of my app. I forgot all about the app and my friend and I talked for over 30 minutes (with the app in the background, phone display falling asleep.  After hanging up with my friend, I remembered that the app had been running.  The phone continued to work, but the UI (or something) of the device had crashed and the device had to be hard-rebooted. As I think of it now, it isn't exactly the 'UI'...I have an animated fish aquarium as my screen saver.  Once my device goes to sleep after a minute of none use, the aquarium continues to run/animate. But the device cannot 'wake up', i.e., the aquarium runs, but cannot be stopped... again, a hard reboot is needed.

**Comment by davbaron** [comment]
Possible break-thru? My OnePlus 7T received an update from OnePlus today (Oxygen OS 10.0.7.HD65AA) _and_ an update from Google (?) in the form of a newer version of the Android WebView widget. After both finished installing, I thought I would give my app a test, and lo and behold, the device-crashing bug is gone! My phone has now run for hours with my app in the background...when I want I can bring it to front and it works perfectly.

I do not see how the Android WebView widget could have made a difference.  Here are the publicly displayed release notes from OnePlus for _their_ update:

- improved the launching speed of some apps
- optimized the RAM Management
- optimized the black and white screen issues with some apps
- improved system stability and general bug fixes
- updated Android security patch to 2019.11

I do not see how any of those could have helped either... but to be honest, I an not qualified to know _exactly_ what they are or how they could affect anything.

For all you non-OnePlus-ers out there... maybe look for an update from your device vendor?

Good luck!

**Comment by sergicastellsague** [comment]
To be honest this is quite extrange @davbaron we have a pool of thousands of users and nobody reported that their device froze because of using our app. They reported random crashes and such, related with the Google maps component itself.
Hopefully, somebody from Google can shed some light.

**Comment by spitfire55** [comment]
On my OnePlus 6t running Android 10, this crash also occurs. Open Flutter app w/ Google Maps, let app go to background for approx. 3-4 minutes, and without fail, the phone completely freezes and requires a hard reboot to fix.

**Comment by EbenezerGH** [comment]
Fixed on latest OS for one plus 6.. version 10.3.1.

 Haven't seen crash yet.

**Comment by spitfire55** [comment]
Can confirm. 10.3.1 on Oneplus 6t fixed the issue for me.

**Comment by awazgyawali** [comment]
This thread had multiple reports from one plus devices. And finally, including me many other developers have reported that the issue has gone away. I am closing this issue, please let me know if this issue still persists on other OEM devices, will reopen the issue.

**Comment by DanielFortuyn** [comment]
Just in case anyone comes looking.. I am currently using a fully updated one plus 5T and am still experiencing this issue..

**Comment by Gozubenli** [comment]
Same issue, Samsung Galaxy A50, fully updated.

**Comment by racacere** [comment]
Same issue using Motorola G6 plus and Xiaomi Redmi 5

**Comment by edmbn** [comment]
Just in case your issue is like mine. Reading the log I saw wake_lock permissions were needed to avoid platform exception. 

By adding this permission on AndroidManifest.xml my issue never appeared again :

`<uses-permission android:name="android.permission.WAKE_LOCK" />`

Just make sure you see this exception on your log, if its the case it may solve your problem.

**Comment by mritunjay10** [comment]
> <uses-permission android:name="android.permission.WAKE_LOCK" />

Thanks, this worked.

**Comment by omarmir** [comment]
I understand that the 

> Just in case your issue is like mine. Reading the log I saw wake_lock permissions were needed to avoid platform exception.
> 
> By adding this permission on AndroidManifest.xml my issue never appeared again :
> 
> `<uses-permission android:name="android.permission.WAKE_LOCK" />`
> 
> Just make sure you see this exception on your log, if its the case it may solve your problem.

Thanks for this! I really don't want to ask a permission that shouldn't really be needed. Any reason why this is needed?

**Comment by AliEasy** [comment]
Still having issue on for `google_maps_flutter: ^1.0.6`

**Comment by Marcosmaliki** [comment]
Still an issue on Samsung a71 android 10. It's not frequent but can easily be recreated.
step 1: Create a flutter app with two screens; one with GoogleMaps widget (maybe add a marker and a circle) and another with a button to open the GoogleMaps screen
step2: Open the google maps screen and close 3 times in less than 10 seconds

result: Phone freezes

**Comment by fritsstegmann** [comment]
I've had some issues too. I got it working by forking the repo and making two changes on my side. not sure if it's the same problem everyone else is having. My phone is a HTC One M8.
