### ISSUE TITLE
One selection only in ListView

### ISSUE THREAD

**Issue by monxarat** [flutter/flutter#27270]
In My App, I want to change the background  when selected an item in the ListView(single selection.)
How to one selection only in `ListView` using `ListTile`,
Such as `RadioListTile`, but `RadioListTile` I can't change background when selected. And custom RadioButton.

**Comment by zoechi** [comment]
Does this mean the issue is solved?

**Comment by monxarat** [comment]
@zoechi 
issue is solved

**Comment by nicksav** [comment]
Guys what ...., menas?
I cant get this to compile...

**Comment by monxarat** [comment]
@nicksav 
You can get this to compile, but this is not basically supported in this Flutter lib. 
First of all, you can use this, We'll wait for Flutter full support this feature! :-D

**Comment by nicksav** [comment]
Sorry, but still cant get this working:
![image](https://user-images.githubusercontent.com/9266365/60479603-c5a81f80-9cc9-11e9-8564-9fd2cf25023f.png)
Any clue?

**Comment by monxarat** [comment]
@nicksav 
What "this"?
The child must be a Widget. In the above example, the child is `StatefulWidget`
`class ItemWidget extends StatefulWidget`
