### ISSUE TITLE
Flutter firebase_admob show only once

### ISSUE THREAD

**Issue by developernca** [flutter/flutter#27520]
The following code show the banner ad at the bottom of the application and show interstitial ad when the button is clicked. No problem with banner ad.  The problem is, when the app start and click button for the first time, the interstitial is shown but the interstitial is not shown again starting from second time the button is clicked. There are no errors and all log message show success. Something wrong in my code? I'm testing on android device. And also posted this question [here](https://stackoverflow.com/questions/54516583/flutter-firebase-admob-show-only-once) but get no answers yet.

```dart
import 'package:firebase_admob/firebase_admob.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {

  final admobAppId = 'ca-app-pub-3940256099942544~3347511713';
  final bannerId = 'ca-app-pub-3940256099942544/6300978111';
  final interstitialId = 'ca-app-pub-3940256099942544/1033173712';

  BannerAd bannerAd;
  InterstitialAd interstitialAd;

  MyApp() {
    FirebaseAdMob.instance.initialize(appId: admobAppId);
    makeBannerAd();
    initInterstitialAd();
  }

  makeBannerAd() {
    bannerAd = BannerAd(
        adUnitId: bannerId,
        size: AdSize.smartBanner,
        listener: (MobileAdEvent me) {
          print('MobileAdEvent $me');
        });
    bannerAd
      ..load()
      ..show();
  }

  initInterstitialAd() {
    interstitialAd = InterstitialAd(
        adUnitId: interstitialId,
        listener: (MobileAdEvent me) {
          print(
              '========== Interstitial ad mobile ad event =========== \n $me');
          if (me == MobileAdEvent.closed) {
            print('Interstitial closed');
            loadInterstitialAd();
          } 
        });
    loadInterstitialAd();
  }

  loadInterstitialAd() {
    interstitialAd.load().then((val) {
      if (val) {
        print('Interstitial ad loaded callback success');
      } else {
        print('Interstitial ad loaded callback failed');
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('AdMob plugin test'),
        ),
        body: Center(
          child: RaisedButton(
            child: Text('Show Interstitial!'),
            onPressed: () {
              interstitialAd.show().then((val) {
                if (val) {
                  print('Interstitial ad show callback success');
                } else {
                  print('Interstitial ad show callback fail');
                }
              });
            },
          ),
        ),
      ),
    );
  }
}
```

**Comment by nemoryoliver** [comment]
Try adding another event check if the interstitial is loaded. Then that's the time you can only click the show function. Sometimes ads fail to load so you also have to check for that too

**Comment by developernca** [comment]
> Try adding another listener event condition if the interstitial is loaded.
What does it mean? Will you please elaborate?

**Comment by nemoryoliver** [comment]
I'm so sorry if you don't understand my english. but this is how I would do it

```
if (me == MobileAdEvent.failedToLoad) { 
  // try to reload after a few seconds maybe
} else if (me == MobileAdEvent.loaded) { 
  // this is the time you can show the ad since it successfully loaded
} else if (me == MobileAdEvent.closed) { 
  // you can reload the ad here again
}
```

**Comment by zoechi** [comment]
@developernca did @nemoryoliver's suggestion help?

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by developernca** [comment]
Here is how I fixed the code. Now, whenever the button is pressed the ad is shown. I tested 10+ times and it work well. It seem InterstitialAd need to create every time the ad is wanted to show. But I don't know exactly.

```
import 'package:flutter/material.dart';
import 'package:firebase_admob/firebase_admob.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  BannerAd myBanner;

  MyApp() {
    FirebaseAdMob.instance.initialize(appId: FirebaseAdMob.testAppId);
    myBanner =
        BannerAd(adUnitId: BannerAd.testAdUnitId, size: AdSize.smartBanner);
    myBanner
      ..load()
      ..show();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("Interstitial Ad test"),
        ),
        body: Center(
          child: RaisedButton(
            child: Text("Interstitial ad"),
            onPressed: () {
              InterstitialAd interstitialAd = new InterstitialAd(
                  adUnitId: InterstitialAd.testAdUnitId,
                  listener: (MobileAdEvent e) {
                    print("Mobile ad event => $e");
                  });
              interstitialAd.load().then((val) {
                interstitialAd.show();
              });
            },
          ),
        ),
      ),
    );
  }
}
```

**Comment by anderscheow** [comment]
Does this related to this [issue](https://github.com/flutter/flutter/issues/27671)?

**Comment by theneshofficial** [comment]
Each time you create the interstitial ad you need to dispose it. Add a dispose method. That should help.

**Comment by hexdump2002** [comment]
Please, fixt this issue. Performance gets affected if we have to re-instantiante interstitial every time we want to show it. This is not how it should be. On Android native reusing same interstitial with differnt Request works perfectly.

**Comment by hasen6** [comment]
A few months on and still this problem persists. Can't see anything more important than fixing this issue? I mean, the interstitials only show once so it's basically a useless package as it is.

I can confirm that it's nothing to do with loading either. Even after the listener reports that the ad has fully reloaded, it still will not show a second time. I get the same error "Interstitial has already been presented".

**Comment by Qualcuno** [comment]
I have the same problem. For now i've write this workaround that allow you to show every N seconds if  it doesn't show yet, disposing the old interstitial object and recreating a new interstitial object.

Declaration on top
```dart
InterstitialAd interstitial;
Timer interstitialTimer;
bool interstitialShown;
```

show interstitial every 15 seconds ( if not already shown )
```dart     
interstitialShown = false;
interstitialTimer = Timer.periodic(Duration(seconds: 15), (Timer t) => createInterstitial());
``` 

create and handle interstitial called recursively when MobileEvent.closed event is out
```dart 
void createInterstitial(){
    if(interstitialShown == false){
      interstitial = new InterstitialAd(
          adUnitId: 'ca-app-pub-********/**********',
          listener: (MobileAdEvent e) {
            if(e == MobileAdEvent.closed){     
              interstitial.dispose();
              createInterstitial();
              interstitialShown = false;
            }
          });
      interstitial.load().then((val) {
        interstitial.show().then((show){
          interstitialShown = true;
        });
      });
    }
  }
```

**Comment by kroikie** [comment]
@developernca

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/464. Any further collaboration will be done there.

**Comment by kroikie** [comment]
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by anilbhomi** [comment]
InterstitialAd interstitialAd;

void createInterstitialAd() {
  interstitialAd = InterstitialAd(
    adUnitId: InterstitialAd.testAdUnitId,
    targetingInfo: targetingInfo,
    listener: (MobileAdEvent event) {
      if (event == MobileAdEvent.loaded) {
      } else if (event == MobileAdEvent.failedToLoad) {
      } else if (event == MobileAdEvent.closed) {
        interstitialAd.dispose();
        createInterstitialAd();
        interstitialAd..load();
      }
      print("InterstitialAd event is $event");
    },
  );
}

void showInterstitialAd() async {
  interstitialAd..show();
}

**Comment by anilbhomi** [comment]
I got the same issue with interstitial ad,
I managed to solve this issue by disposing of the current instance and re-creating the instance.
I tried and it's working.
``
InterstitialAd interstitialAd;

void createInterstitialAd() {
  interstitialAd = InterstitialAd(
    adUnitId: InterstitialAd.testAdUnitId,
    targetingInfo: targetingInfo,
    listener: (MobileAdEvent event) {
      if (event == MobileAdEvent.loaded) {
      } else if (event == MobileAdEvent.failedToLoad) {
      } else if (event == MobileAdEvent.closed) {
        interstitialAd.dispose();
        createInterstitialAd();
        interstitialAd..load();
      }
      print("InterstitialAd event is $event");
    },
  );
}

void showInterstitialAd() async {
  interstitialAd..show();
}

**Comment by Logic2Paradigm** [comment]
I had the same problem. What worked for me:

```
    import 'package:firebase_admob/firebase_admob.dart';
    
    InterstitialAd _interstitialAd;
    bool _isInterstitialAdReady;
    
    void prepAd(){
      initState();
      _loadInterstitialAd();
    }
    
    void runAd() {
      _interstitialAd.show();
    }
    
    void initState() {
      _isInterstitialAdReady = false;
      _interstitialAd = InterstitialAd(
        adUnitId: InterstitialAd.testAdUnitId,
        listener: _onInterstitialAdEvent,
      );
    }
    
    
    void _loadInterstitialAd() {
      _interstitialAd.load();
    }
    // TODO: Implement _onInterstitialAdEvent()
    void _onInterstitialAdEvent(MobileAdEvent event) {
      switch (event) {
        case MobileAdEvent.loaded:
          _isInterstitialAdReady = true;
          break;
        case MobileAdEvent.failedToLoad:
          _isInterstitialAdReady = false;
          print('Failed to load an interstitial ad');
          break;
        case MobileAdEvent.closed:
          dispose();
          prepAd();
          break;
        default:
        // do nothing
      }
    }
    
    void dispose() {// TODO: Dispose InterstitialAd object
      _interstitialAd?.dispose();
    }
```

I ran prepAd() once in the beginning and then just runAd() when I need it. You can check _isInterstitialAdReady == true inside runAd() if you want

**Comment by stuartmorgan** [comment]
Closing, as `firebase_admob` is [now deprecated](https://pub.dev/packages/firebase_admob/versions/0.11.0+2).
