### ISSUE TITLE
PackageInfoPlugin.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by NatoBoram** [flutter/flutter#28155]
With this package : https://pub.dartlang.org/packages/package_info

## Steps to Reproduce

1. 

```yaml
dependencies:
  package_info: ^0.4.0+1
```

2.

```dart
import "package:package_info/package_info.dart";
```

3.

```bash
flutter build apk
```

## Logs

```
Note: /home/natoboram/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.0+1/android/src/main/java/io/flutter/plugins/packageinfo/PackageInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.    
```

```
Analyzing store_manager...                                              
No issues found! (ran in 3.5s)
```

```
[✓] Flutter (Channel master, v1.2.2-pre.21, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.2.2-pre.21 at /home/natoboram/GitHub/flutter/flutter
    • Framework revision 035e0765cc (4 days ago), 2019-02-16 01:48:28 -0500
    • Engine revision f37b09a11b
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 c92d5ca288)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/natoboram/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/natoboram/Android/Sdk
    • ANDROID_SDK_ROOT = /home/natoboram/Android/Sdk
    • Java binary at: /snap/android-studio/70/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /snap/android-studio/70/android-studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is 10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,127.0.0.1,localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[✓] Connected device (2 available)
    • Nexus 5 • 05473ea90a673764 • android-arm • Android 7.1.2 (API 25)
    • Nexus 5 • 10.4.0.5:5555    • android-arm • Android 7.1.2 (API 25)

• No issues found!
```

**Comment by NatoBoram** [comment]
This fixed it for me : https://github.com/apptreesoftware/flutter_barcode_reader/issues/71#issuecomment-465299793

```
android.useAndroidX=true
android.enableJetifier=true

ext.kotlin_version = '1.3.0'
com.android.tools.build:gradle:3.3.0
```

There should probably be a way to inform users of how to fix the Support Library migration. I'm not familiar with that, and I'd appreciate not to have to open issues because I didn't understand what was happening given the un-informative message.

Issue can be closed if there's no work to do on it.

**Comment by NatoBoram** [comment]
Hm. The error went away for a short while, but now it's there again.

**Comment by sjmcdowall** [comment]
Note: /Users/sjm/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.0+1/android/src/main/java/io/flutter/plugins/packageinfo/PackageInfoPlugin.java uses or overrides a deprecated API.

I know not very helpful but should still be enough info to figure out what the issue is .. and this is with the latest everything in "beta" flutter.

**Comment by cyanglaz** [comment]
This issue has been fixed with https://github.com/flutter/plugins/pull/1275
If any related issue is found, please feel free to reopen it with details.

**Comment by julienrbrt** [comment]
Everything is updated:

```
Upgrading Flutter from /home/julien/Tools/flutter...
Already up to date.

Upgrading engine...
Already up-to-date.

Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (6 weeks ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

Running "flutter packages upgrade" in [redacted]-app...                6.8s

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.32.3)
[✓] Connected device (1 available)

• No issues found!
```

but still gives the issue every APK build:

```
Initializing gradle...                                              1.6s
Resolving dependencies...                                          16.6s
Note: Some input files use unchecked or unsafe operations.              
Note: Recompile with -Xlint:unchecked for details.                      
Note: /home/julien/Tools/flutter/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.0+2/android/src/main/java/io/flutter/plugins/packageinfo/PackageInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      56.1s
Built build/app/outputs/apk/release/app-release.apk (8.1MB).
```

**Comment by cyanglaz** [comment]
reopen to investigate.

**Comment by deakjahn** [comment]
Then how come we still see the warning with 0.4.0+4? This should be reopened and investigated.

**Comment by inja** [comment]
I updated to package_info: ^0.4.0+5 and the message is gone.

**Comment by Nico04** [comment]
Unfortunately I still have the issue ...

Note: C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.3+6\android\src\main\java\io\flutter\plugins\connectivity\ConnectivityPlugin.java uses or overrides a deprecated
 API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\ProgramData\flutter\.pub-cache\hosted\pub.dartlang.org\package_info-0.4.0+5\android\src\main\java\io\flutter\plugins\packageinfo\PackageInfoPlugin.java uses or overrides a deprecated A
PI.
Note: Recompile with -Xlint:deprecation for details.

**Comment by inja** [comment]
> Unfortunately I still have the issue ...
> 
> Note: C:\ProgramData\flutter.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.3+6\android\src\main\java\io\flutter\plugins\connectivity\ConnectivityPlugin.java uses or overrides a deprecated
> API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: C:\ProgramData\flutter.pub-cache\hosted\pub.dartlang.org\package_info-0.4.0+5\android\src\main\java\io\flutter\plugins\packageinfo\PackageInfoPlugin.java uses or overrides a deprecated A
> PI.
> Note: Recompile with -Xlint:deprecation for details.

Do you have 
android.enableJetifier=true
android.useAndroidX=true
in gradle.properties?

**Comment by Nico04** [comment]
Yes :
android.enableJetifier=true
android.useAndroidX=true
org.gradle.jvmargs=-Xmx1536M

**Comment by deakjahn** [comment]
So do I. Still, it must come from this package because I simply removed the reference to tha package, copied the relevant code to my source, added the 'don't-warn-me-about-deprecation' to this very line and the rest is silence... :-)

**Comment by nishtahir** [comment]
I can confirm that this is still an issue.

```
  private static long getLongVersionCode(PackageInfo info) {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
      return info.getLongVersionCode();
    }

    //noinspection deprecation
    return info.versionCode;
  }
```

It looks like `info.versionCode` is deprecated in favor of `info.getLongVersionCode()`

**Comment by jmagman** [comment]
The ongoing issue is being tracked at https://github.com/flutter/flutter/issues/28772.

**Comment by MahdiPishguy** [comment]
+1
