### ISSUE TITLE
Initial screen is badly displayed on startup

### ISSUE THREAD

**Issue by fvisticot** [flutter/flutter#28568]
```
[✓] Flutter (Channel beta, v1.2.1, on Mac OS X 10.14.2 18C54, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.31.0)
[✓] Connected device (1 available)
```
Issue on iOS only
No specific logs or exception in the app

Image for the bug is available here : https://stackoverflow.com/questions/54895990/initial-screen-is-badly-displayed-on-startup

![img_0963](https://user-images.githubusercontent.com/153679/53481371-62895080-3a7d-11e9-982a-800ea687bda1.PNG)
![img_0961](https://user-images.githubusercontent.com/153679/53481383-6a48f500-3a7d-11e9-93da-c40f051f6bf0.PNG)

**Comment by zoechi** [comment]
Can you please try `master` channel. I think I saw a comment to a similar issue that this is fixed or at least improved.

**Comment by fvisticot** [comment]
Tx for your suggestion. I confirm it is working on the master channel. Is a bug fix in progress on beta channel ?

**Comment by zoechi** [comment]
@fvisticot a new `stable` was just released. I assume it will take about +3 months for the next beta. 
You can check `dev` which is much more stable than `master` and updated every ~1-5 days.

**Comment by siperman** [comment]
`[✓] Flutter (Channel dev, v1.3.12, on Mac OS X 10.14.3 18D109, locale zh-Hans-CN)`
I still have the same error when packaging and installing to iOS devices. @zoechi

**Comment by maddesa** [comment]
I have this exact same issue on iOS.  If I take the one stateful widget that this happens to, and put it inside a very simple app, the issue goes away.

I believe it has to do with when setState() is getting called.
