### ISSUE TITLE
FirebaseCorePlugin.java uses unchecked or unsafe operations.

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/flutter#28770]
Note: C:\Tools\flutter_windows_v1.0.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.3.1+1\android\src\main\java\io\flutter\plugins\firebase\core\FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

**Comment by breezage** [comment]
I also got this warning just now

**Comment by joxad** [comment]
Same here, I updated my project to be Android X compliant, but it is still working.

**Comment by hariangr** [comment]
I am currently trying to install Crashlytics, and get the same error

**Comment by gagaJay** [comment]
Im getting the same error now. the only difference I can tell is I recently upgraded to AndroidX.

**Comment by admintrack** [comment]
still not found a solution?

**Comment by EduardoLR10** [comment]
The solution for this problem is all about using the latest and "greatest" versions of the packages. Once I started using the latest version all the warnings disappear.

**Comment by ktchernov** [comment]
@EduardoLR10 on latest packages, still getting the same problem: 

  google_sign_in: ^4.0.1+3
  firebase_auth: ^0.11.0

**Comment by GustavoContreiras** [comment]
Same here today with these versions
```
Note: G:\Dev\Flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.11.0+2\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.
Note: G:\Dev\Flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.11.0+2\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: G:\Dev\Flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.3+1\android\src\main\java\io\flutter\plugins\connectivity\ConnectivityPlugin.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.
Note: G:\Dev\Flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.0+1\android\src\main\java\io\flutter\plugins\firebase\core\FirebaseCorePlugin.java uses unchecked or unsafe operations.
```

**Comment by Matze5590** [comment]
+1

**Comment by bradmuzza** [comment]
I have the same issue

**Comment by miente-dijkstra** [comment]
Had the same issue and solved it (in Android Studio): Go into File → Invalidate Caches / Restart

**Comment by kw2019ltd** [comment]
not related to   Android Studio its during the build in Jenkins or another
pipeline.

**Comment by mohamedHassanKa** [comment]
i got the same problem too any solution

**Comment by juanagu** [comment]
same problem

**Comment by julianfalcionelli** [comment]
Got the same, fixed it by running Invalidate Caches & Restart, and then I was getting the "D8: Cannot fit requested classes in a single dex file (# methods: 90804 > 65536)" error which got fixed by enabling Multidex.

In the Project Gradle (project/app/build.gradle) add the following lines:

```
defaultConfig {
    ...

    multiDexEnabled true
}
```
and

```
dependencies {
    ...

    implementation 'com.android.support:multidex:1.0.3'
}
```

**Comment by kw2019ltd** [comment]
still same issue with the newest versions

**Comment by jeanbatm** [comment]
fixed with : 

> pub cache repair

see: [https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#generated-project-files-outdated](url)

**Comment by repentsinner** [comment]
@jeanbatm, can you repro after a `flutter clean`?

The following still results in `FirebaseCorePlugin.java uses unchecked or unsafe operations` here.

Also tried `rm -rf .pub-cache` followed by `flutter package get` as an alternative cache repair mechanism and still no luck.

```
> flutter upgrade
> flutter --version
Flutter 1.7.8+hotfix.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b712a172f9 (7 days ago) • 2019-07-09 13:14:38 -0700
Engine • revision 54ad777fd2
Tools • Dart 2.4.0
```

```
> flutter clean
> flutter pub cache repair
```

```
> flutter build appbundle --target-platform android-arm64                                                         12:25:27
Initializing gradle...                                              1.5s
Resolving dependencies...                                           2.7s
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Note: /Users/deg/Development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.0+6/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                      
Running Gradle task 'bundleRelease'...                                  
Running Gradle task 'bundleRelease'... Done                        53.9s
Built build/app/outputs/bundle/release/app.aab (7.8MB).
```

**Comment by jeanbatm** [comment]
@repentsinner, you also need to update the google-services to the version 4.3.0 in android/build.gradle.


```
  dependencies {
      ...
      classpath 'com.google.gms:google-services:4.3.0'
    }
```

And then, if the pb is still there: 

`> pub cache clean`

**Comment by kw2019ltd** [comment]
we are getting this issue also in cloud build gitlab build not only local
how  pub cache clean will help?

**Comment by repentsinner** [comment]
@jeanbatm 

Interestingly upgrading google-services to 4.3.0 fixes a different issue (`registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)` as documented on [StackOverflow](https://stackoverflow.com/a/56845863/6820891)), but I still see the `FirebaseCorePlugin.java uses unchecked or unsafe operations` after this change.

I also tried upgrading everything to AndroidX in the meantime as well, with no change.

google-services 4.2.0:
```
flutter run                                                                                                     11:32:05
Launching lib/main.dart on Pixel 2 in debug mode...
Initializing gradle...                                              1.9s
Resolving dependencies...                                           5.2s
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Note: /Users/deg/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.0+6/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                      
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        45.0s
Built build/app/outputs/apk/debug/app-debug.apk.
...
```

google-services 4.3.0
```
flutter run                                                                                               11:38:46
Launching lib/main.dart on Pixel 2 in debug mode...
Initializing gradle...                                              1.8s
Resolving dependencies...                                           5.1s
Note: /Users/deg/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.0+6/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                      
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        27.6s
Built build/app/outputs/apk/debug/app-debug.apk.
...
```

**Comment by collinjackson** [comment]
@repentsinner thanks for the suggestion, I've filed #1885 to fix the registerResGeneratingTask deprecation warning

**Comment by collinjackson** [comment]
Fixed in flutter/plugins#1883

**Comment by kroikie** [comment]
@kw2019ltd

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/403. Any further collaboration will be done there.

**Comment by msaad5746** [comment]
> Got the same, fixed it by running Invalidate Caches & Restart, and then I was getting the "D8: Cannot fit requested classes in a single dex file (# methods: 90804 > 65536)" error which got fixed by enabling Multidex.
> 
> In the Project Gradle (project/app/build.gradle) add the following lines:
> 
> ```
> defaultConfig {
>     ...
> 
>     multiDexEnabled true
> }
> ```
> 
> and
> 
> ```
> dependencies {
>     ...
> 
>     implementation 'com.android.support:multidex:1.0.3'
> }
> ```

thanks, it worked for me on first try

**Comment by xx1196** [comment]
> Got the same, fixed it by running Invalidate Caches & Restart, and then I was getting the "D8: Cannot fit requested classes in a single dex file (# methods: 90804 > 65536)" error which got fixed by enabling Multidex.
> 
> In the Project Gradle (project/app/build.gradle) add the following lines:
> 
> ```
> defaultConfig {
>     ...
> 
>     multiDexEnabled true
> }
> ```
> 
> and
> 
> ```
> dependencies {
>     ...
> 
>     implementation 'com.android.support:multidex:1.0.3'
> }
> ```

waw its cool, work for me tanks

**Comment by saffer4u** [comment]
> > Got the same, fixed it by running Invalidate Caches & Restart, and then I was getting the "D8: Cannot fit requested classes in a single dex file (# methods: 90804 > 65536)" error which got fixed by enabling Multidex.
> > In the Project Gradle (project/app/build.gradle) add the following lines:
> > ```
> > defaultConfig {
> >     ...
> > 
> >     multiDexEnabled true
> > }
> > ```
> > 
> > 
> > and
> > ```
> > dependencies {
> >     ...
> > 
> >     implementation 'com.android.support:multidex:1.0.3'
> > }
> > ```
> 
> thanks, it worked for me on first try

**Comment by rahmanrezaee** [comment]
add this dependencies to your (android/app/build.gradle)
```
dependencies {
    ...

    implementation 'com.android.support:multidex:1.0.3'
}
```

**Comment by Valentin-Seehausen** [comment]
> > > Got the same, fixed it by running Invalidate Caches & Restart, and then I was getting the "D8: Cannot fit requested classes in a single dex file (# methods: 90804 > 65536)" error which got fixed by enabling Multidex.
> > > In the Project Gradle (project/app/build.gradle) add the following lines:
> > > ```
> > > defaultConfig {
> > >     ...
> > > 
> > >     multiDexEnabled true
> > > }
> > > ```
> > > 
> > > 
> > > and
> > > ```
> > > dependencies {
> > >     ...
> > > 
> > >     implementation 'com.android.support:multidex:1.0.3'
> > > }
> > > ```
> > 
> > 
> > thanks, it worked for me on first try

+1
