### ISSUE TITLE
flutter release isn't making Api call working on debug[android/emulator]

### ISSUE THREAD

**Issue by danish-khan-I** [flutter/flutter#31019]
On development everything is working fine but on production version api not being called.
using http library[http: any]
i made apps before using same code. may be after updating it started to occur.
what i tried so far.
 1.flutter clean
 2.creating new project (still happens)
3.flutter build apk --release
everytime works on emulator or phone but app-release fails.
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
[  +37 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +130 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] origin/stable
[        ] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[  +91 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] executing: [C:\flutter\] git ls-remote --get-url origin
[  +96 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [C:\flutter\] git log -n 1 --pretty=format:%H
[  +85 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 8661d8aecd626f7f57ccbcb735553edc05a2e713
[        ] executing: [C:\flutter\] git log -n 1 --pretty=format:%ar
[  +83 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 8 weeks ago
[   +1 ms] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +96 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.2.1-0-g8661d8aec
[ +501 ms] executing: C:\android\platform-tools\adb devices -l
[  +48 ms] Exit code 0 from: C:\android\platform-tools\adb devices -l
[        ] List of devices attached
[  +18 ms] No connected devices.
[  +14 ms] "flutter run" took 433ms.
[        ] "flutter run" took 433ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:240:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:525:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:482:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:473:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:111:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:48:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#34     main (file:///E:/b/rr/tmpdrhwmy/w/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

```
Analyzing jansamparklifedotcom...
No issues found! (ran in 29.4s)
```

```
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.706], locale en-US)
    • Flutter version 1.2.1 at C:\flutter
    • Framework revision 8661d8aecd (8 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\android
    • Java binary at: C:\Program Files\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\AndroidStudio
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.33.1)
    • VS Code at C:\Users\danish\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.25.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by danish-khan-I** [comment]
the problem was with the INTERNET permission...

**Comment by erfanasg** [comment]
I have this issue as well
You mean i need to put a permission for using internet?

**Comment by danish-khan-I** [comment]
> I have this issue as well
> You mean i need to put a permission for using internet?

yes. you need INTERNET permission.
for that you need to goto `android/app/src/main/AndroidManifest.xml `     
`<uses-permission android:name="android.permission.INTERNET"/>`

**Comment by akashpunagin** [comment]
rf

**Comment by tieorange** [comment]
Fixed on Android. 

**But on iOS I still can't do requests!**

**Comment by sewah2012** [comment]
Thanks a lot my problem is gone!.

**Comment by domizilver** [comment]
> yes. you need INTERNET permission.

i already have this INTERNET permission but still not working on real device. any idea?

**Comment by danish-khan-I** [comment]
> > yes. you need INTERNET permission.
> 
> i already have this INTERNET permission but still not working on real device. any idea?

can you share your `AndroidManifest.xml`

**Comment by domizilver** [comment]
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.my_app">
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="my_app"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
        
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-3940256099942544~3347511713"/>
    </application>
</manifest>
`

**Comment by domizilver** [comment]
`
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.my_app">
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="my_app"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
        
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-3940256099942544~3347511713"/>
    </application>
</manifest>
`

**Comment by domizilver** [comment]
here is my code: https://codeshare.io/5DRJqO

**Comment by marhyno** [comment]
have you solved this issue ? I have the same as on Emulator I have Android version 8.1.1 and real device has 8.1.0 but on real device the network doesnt work, I added permission to main also to debug and also to profile to test it, none of that works

**Comment by Fraganya** [comment]
> > I have this issue as well
> > You mean i need to put a permission for using internet?
> 
> yes. you need INTERNET permission.
> for that you need to goto `android/app/src/main/AndroidManifest.xml `
> `<uses-permission android:name="android.permission.INTERNET"/>`

Thanks, this solved my issue

**Comment by hughsheehy** [comment]
Ditto. Fixed the problem. Thanks. 

It's odd that nothing throws a warning or error of any sort (anywhere, that I can see).

**Comment by mshere9** [comment]
> > I have this issue as well
> > You mean i need to put a permission for using internet?
> 
> yes. you need INTERNET permission.
> for that you need to goto `android/app/src/main/AndroidManifest.xml `
> `<uses-permission android:name="android.permission.INTERNET"/>`

Thanks, this solved my issue

**Comment by zohaib304** [comment]
> the problem was with the INTERNET permission...

Thanks ❤

**Comment by sushantsinghELS** [comment]
I have same problem, i also added Internet permission but not working in signed apk or in release mode..

**Comment by muhamed7** [comment]
The same issue Any solutions?

**Comment by muhamed7** [comment]
Hello I have fixed it 
U have to use https in your API URL instead of http.

**Comment by san-2015** [comment]
i have added internet permission,but its not working yet.

**Comment by DarienRomero** [comment]
In my case I was using two differente urls to fetch data. And one of them wasn't working despite I included internet permission. This solution works for me https://github.com/flutter/flutter/issues/40719#issuecomment-533202279

**Comment by AbdulSubcodevs** [comment]
You need to add this line in the manifest file.
Go to manifest file android/app/src/main/AndroidManifest.xml
add below line in application with internet permission.
<application android:usesCleartextTraffic="true">
</application>

**Comment by san-2015** [comment]
This too does not solve the issue,Here is my manifest file
https://codeshare.io/5M6nA3

**Comment by san-2015** [comment]
It is now working by adding the internet permission.

**Comment by MerdanDev** [comment]
Same problem, it works with adding internet permision in debug mode but it doesn't work in release mode. Any solition for http?
Not https!

**Comment by gurkanucar** [comment]
i have same problem too for http library. I already added permission to  the manifest file but it's not working in release apk.

**Comment by AbdulManan999** [comment]
> i have same problem too for http library. I already added permission to the manifest file but it's not working in release



> i have same problem too for http library. I already added permission to the manifest file but it's not working in release apk.

Are you using http or https links??

**Comment by gurkanucar** [comment]
> > i have same problem too for http library. I already added permission to the manifest file but it's not working in release
> 
> > i have same problem too for http library. I already added permission to the manifest file but it's not working in release apk.
> 
> Are you using http or https links??

The Problem was in my release AndroidManifest.xml file but i solved, thanks.
