### ISSUE TITLE
[google_maps_flutter] Marker onTap randomly called on iOS when pushing Named Route

### ISSUE THREAD

**Issue by Hawlitschek** [flutter/flutter#32207]
## Steps to Reproduce

1. ... Use A Google Map inside a stack with buttons above.
2. ... Add Markers to the map (like the example PlaceMarker)
3. ... Use a button above to navigate to a named route
4. ... When coming back (popping the route) you can see that the camera has moved

(In the test case I directly pressed the info button that triggers the Navigator. No touch to something else before)

Using print statements I got the following order of events:
flutter: On Info clicked
flutter: On Marker for Toilet Friedhof Sindlingen clicked

=> The random marker click had happened directly after the push.

Code Snippets:

**Body**
```
body: Stack(children: <Widget>[
          GoogleMap(
            onTap: _onMapClicked,
            myLocationButtonEnabled: false,
            myLocationEnabled: true,
            mapType: MapType.normal,
            markers: Set<Marker>.of(_markers.values),
            onCameraMove: (cameraPosition) {
              _currentCameraPosition = cameraPosition;
            },
            initialCameraPosition: _initialCameraPosition,
            onMapCreated: (GoogleMapController controller) {
              _controller.complete(controller);
              _initMarkers();
            },
          ),
          SafeArea(
            child: Padding(
              padding: const EdgeInsets.only(top: 32.0),
              child: Align(
                alignment: Alignment.topLeft,
                child: Material(
                  elevation: 6.0,
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                          topRight: Radius.circular(30),
                          bottomRight: Radius.circular(30))),
                  shadowColor: Colors.grey,
                  color: Colors.white,
                  child: InkWell(
                    borderRadius: BorderRadius.only(
                        topRight: Radius.circular(30),
                        bottomRight: Radius.circular(30)),
                    onTap: _onInfoClicked,
                    splashColor: COLOR_FEATURE_UNAVAILABLE,
                    child: Container(
                      padding: EdgeInsets.only(
                          left: 20, top: 16, right: 16, bottom: 12),
                      child: Hero(
                        tag: 'fes_logo',
                        child: SvgPicture.asset(
                          'assets/svg/fes_logo_blue.svg',
                          width: 50,
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
          SafeArea(
            child: Padding(
              padding: const EdgeInsets.only(right: 16.0, bottom: 64.0),
              child: Align(
                alignment: Alignment.bottomRight,
                child: FloatingActionButton(
                  child: Icon(
                    Icons.gps_fixed,
                    color: Colors.grey.shade700,
                  ),
                  backgroundColor: Colors.white,
                  onPressed: _onRequestLocationClicked,
                ),
              ),
            ),
          )
        ]),
```

**click handler**
```
Future _onReportIncidentClicked(Toilet toilet) async {
    markerTapValid = false;
    final result =
        await Navigator.of(context).pushNamed('/incident', arguments: toilet);
    markerTapValid = true;
    print('Popping Back from incident with result "$result"');
    if (result == 'Success') {
    ...
```

** Creating of Markers**
```
Marker _createMarkerForToilet(Toilet toilet, bool selected) {
    MarkerId markerId = MarkerId(toilet.name);

    return Marker(
        // This marker id can be anything that uniquely identifies each marker.
        markerId: markerId,
        position: LatLng(toilet.latitude, toilet.longitude),
        onTap: () {
          _onMarkerClicked(markerId, toilet);
        },
        icon: _getOsAwareDefaultMarkerBitmapFor(toilet, selected));
  }
```

** On Marker clicked**
```
void _onMarkerClicked(MarkerId markerId, Toilet selectedToilet) {
    print(
        'On Marker for Toilet ${selectedToilet.name} clicked valid=$markerTapValid');

    if(!markerTapValid){
      return;
    }

    final Marker tappedMarker = _markers[markerId];
    if (tappedMarker != null) {
      // Set back old tapped & set new one as tapped
      setState(() {
        _resetOldTappedMarker();
        _updateTappedMarker(selectedToilet, tappedMarker);
      });
    }

    _controller.future.then((GoogleMapController controller) {
      controller.animateCamera(CameraUpdate.newLatLng(LatLng(
          selectedToilet.latitude -
              MapUtils.calculateLatitudeOffset(_currentCameraPosition),
          selectedToilet.longitude -
              MapUtils.calculateLongitudeOffset(_currentCameraPosition))));
    });

    // Store selected toilet and update bottom sheet
    _selectedToilet = selectedToilet;
    if (_bottomSheetController == null) {
      print('calling _showBottomSheet');
      _showBottomSheet();
    } else {
      print('calling _bottomSheetController.setState');
      _bottomSheetController.setState(() {});
    }
  }
```

## Logs

```
[ +318 ms] [DEVICE LOG] 2019-05-07 17:58:30.710418+0200  localhost Runner[79279]: (CoreLocation) Created Activity ID: 0x136938, Description: CL: CLLocationManager
[        ] [DEVICE LOG] 2019-05-07 17:58:30.710484+0200  localhost Runner[79279]: (CoreLocation) [com.apple.locationd.Core:Client] {"msg":"CLLocationManager", "event":"activity", "_cmd":"requestWhenInUseAuthorization", "self":"0x60000200f740"}
[        ] [DEVICE LOG] 2019-05-07 17:58:30.710702+0200  localhost Runner[79279]: (CoreLocation) Created Activity ID: 0x136939, Description: CL: CLLocationManager
[        ] [DEVICE LOG] 2019-05-07 17:58:30.710740+0200  localhost Runner[79279]: (CoreLocation) [com.apple.locationd.Core:Client] {"msg":"CLLocationManager", "event":"activity", "_cmd":"startUpdatingLocation", "self":"0x60000200f740"}
[        ] [DEVICE LOG] 2019-05-07 17:58:30.710778+0200  localhost Runner[79279]: (CoreLocation) [com.apple.locationd.Core:Core] {"msg":"state transition", "event":"state_transition", "state":"LocationManager", "id":"0x60000200f740", "property":"updatingLocation", "old":0, "new":1}
[        ] [DEVICE LOG] 2019-05-07 17:58:30.710978+0200  localhost Runner[79279]: (CoreLocation) Created Activity ID: 0x13693a, Description: CL: CLLocationManager
[ +400 ms] [DEVICE LOG] 2019-05-07 17:58:30.711015+0200  localhost Runner[79279]: (CoreLocation) [com.apple.locationd.Core:Client] {"msg":"CLLocationManager", "event":"activity", "_cmd":"startUpdatingHeading", "self":"0x60000200f740"}
[        ] [DEVICE LOG] 2019-05-07 17:58:30.711051+0200  localhost Runner[79279]: (CoreLocation) [com.apple.locationd.Core:Core] {"msg":"state transition", "event":"state_transition", "state":"LocationManager", "id":"0x60000200f740", "property":"updatingHeading", "old":0, "new":1}
[        ] [DEVICE LOG] 2019-05-07 17:58:30.711079+0200  localhost Runner[79279]: (CoreLocation) [com.apple.locationd.Core:Client] Start updating heading. HeadingFilter, 1.00
[        ] [DEVICE LOG] 2019-05-07 17:58:30.725938+0200  localhost Runner[79279]: (SystemConfiguration) Created Activity ID: 0x13693b, Description: processing SCNetworkReachability notification
[        ] [DEVICE LOG] 2019-05-07 17:58:30.726800+0200  localhost Runner[79279]: (CFNetwork) Task <B5DF4ED7-4BCB-48B7-BDAB-46BF0889BD62>.<1> resuming, QOS(0x21)
[        ] [DEVICE LOG] 2019-05-07 17:58:30.726888+0200  localhost Runner[79279]: (CoreLocation) [com.apple.locationd.Core:Core] {"msg":"state transition", "event":"state_transition", "state":"LocationManager", "id":"0x60000200f740", "property":"previousAuthorizationStatus", "old":"NotDetermined", "new":"AuthorizedWhenInUse"}
[        ] [DEVICE LOG] 2019-05-07 17:58:30.726924+0200  localhost Runner[79279]: (CoreLocation) [com.apple.locationd.Core:Core] {"msg":"state transition", "event":"state_transition", "state":"LocationManager", "id":"0x60000200f740", "property":"previousAuthorizationStatusValid", "old":0, "new":1}
[        ] [DEVICE LOG] 2019-05-07 17:58:30.728441+0200  localhost Runner[79279]: (Security) Created Activity ID: 0x13693c, Description: SecTrustEvaluateIfNecessary
[        ] [DEVICE LOG] 2019-05-07 17:58:30.737473+0200  localhost Runner[79279]: (CFNetwork) [com.apple.CFNetwork:ATS] Task <B5DF4ED7-4BCB-48B7-BDAB-46BF0889BD62>.<1> {strength 1, tls 8, ct 0, sub 0, sig 0, ciphers 1, bundle 0, builtin 0}
[        ] [DEVICE LOG] 2019-05-07 17:58:30.770795+0200  localhost Runner[79279]: (Security) Created Activity ID: 0x13693d, Description: SecTrustEvaluateIfNecessaryFastAsync
[        ] [DEVICE LOG] 2019-05-07 17:58:30.775442+0200  localhost Runner[79279]: (CoreLocation) [com.apple.locationd.Core:Client] delivering locations to client's delegate
[        ] [DEVICE LOG] 2019-05-07 17:58:30.778470+0200  localhost Runner[79279]: (CFNetwork) System Trust Evaluation yielded status(0)
[        ] [DEVICE LOG] 2019-05-07 17:58:30.849713+0200  localhost Runner[79279]: (CFNetwork) TIC TLS Trust Result [1:0x600001710cc0]: 0
[        ] [DEVICE LOG] 2019-05-07 17:58:30.856948+0200  localhost Runner[79279]: (CFNetwork) TIC TLS Event [1:0x600001710cc0]: 2, Pending(0)
[        ] [DEVICE LOG] 2019-05-07 17:58:30.865724+0200  localhost Runner[79279]: (Security) Created Activity ID: 0x13693e, Description: SecTrustReportTLSAnalytics
[        ] [DEVICE LOG] 2019-05-07 17:58:30.866412+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] nw_endpoint_flow_protocol_connected [C1.1 172.217.23.174:443 in_progress socket-flow (satisfied)] Output protocol connected
[        ] [DEVICE LOG] 2019-05-07 17:58:30.867381+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] nw_connection_report_state_with_handler_locked [C1] reporting state ready
[        ] [DEVICE LOG] 2019-05-07 17:58:30.869113+0200  localhost Runner[79279]: (CFNetwork) TIC Enabling TLS [2:0x600001711680]
[        ] [DEVICE LOG] 2019-05-07 17:58:30.869183+0200  localhost Runner[79279]: (CFNetwork) TIC TCP Conn Start [2:0x600001711680]
[        ] [DEVICE LOG] 2019-05-07 17:58:30.869726+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] [C2 clients4.google.com:443 tcp, url hash: eeaec306, tls] start
[        ] [DEVICE LOG] 2019-05-07 17:58:30.873913+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] nw_connection_report_state_with_handler_locked [C2] reporting state preparing
[        ] [DEVICE LOG] 2019-05-07 17:58:30.878983+0200  localhost Runner[79279]: (CFNetwork) Task <B5DF4ED7-4BCB-48B7-BDAB-46BF0889BD62>.<1> setting up Connection 2
[        ] [DEVICE LOG] 2019-05-07 17:58:30.879577+0200  localhost Runner[79279]: (CFNetwork) TIC TLS Event [1:0x600001710cc0]: 20, Pending(0)
[        ] [DEVICE LOG] 2019-05-07 17:58:30.879664+0200  localhost Runner[79279]: (CFNetwork) TIC TCP Conn Connected [1:0x600001710cc0]: Err(16)
[        ] [DEVICE LOG] 2019-05-07 17:58:30.880173+0200  localhost Runner[79279]: (CFNetwork) TIC TCP Conn Event [1:0x600001710cc0]: 1
[        ] [DEVICE LOG] 2019-05-07 17:58:30.880210+0200  localhost Runner[79279]: (CFNetwork) TIC TCP Conn Event [1:0x600001710cc0]: 8
[        ] [DEVICE LOG] 2019-05-07 17:58:30.880235+0200  localhost Runner[79279]: (CFNetwork) TIC TLS Handshake Complete [1:0x600001710cc0]
[        ] [DEVICE LOG] 2019-05-07 17:58:30.881323+0200  localhost Runner[79279]: (CFNetwork) [com.apple.CFNetwork:Coalescing] new connection to dl.google.com config 0x600002241300
[        ] [DEVICE LOG] 2019-05-07 17:58:30.884254+0200  localhost Runner[79279]: (CoreLocation) [com.apple.locationd.Core:Client] delivering locations to client's delegate
[        ] [DEVICE LOG] 2019-05-07 17:58:30.898440+0200  localhost Runner[79279]: (CFNetwork) Task <5EE101A2-8373-41A5-AA01-67F6C3021656>.<1> now using Connection 1
[        ] [DEVICE LOG] 2019-05-07 17:58:30.898647+0200  localhost Runner[79279]: (CFNetwork) Task <5EE101A2-8373-41A5-AA01-67F6C3021656>.<1> sent request, body N
[        ] [DEVICE LOG] 2019-05-07 17:58:30.901886+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] nw_endpoint_flow_protocol_connected [C1.1 172.217.23.174:443 ready socket-flow (satisfied)] Output protocol connected
[        ] [DEVICE LOG] 2019-05-07 17:58:30.920798+0200  localhost Runner[79279]: (CFNetwork) Task <5EE101A2-8373-41A5-AA01-67F6C3021656>.<1> received response, status 200 content K
[        ] [DEVICE LOG] 2019-05-07 17:58:30.920851+0200  localhost Runner[79279]: (CFNetwork) Task <5EE101A2-8373-41A5-AA01-67F6C3021656>.<1> done using Connection 1
[        ] [DEVICE LOG] 2019-05-07 17:58:31.050212+0200  localhost Runner[79279]: (CFNetwork) Task <5EE101A2-8373-41A5-AA01-67F6C3021656>.<1> response ended
[        ] [DEVICE LOG] 2019-05-07 17:58:31.050519+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] nw_socket_handle_socket_event [C2.1:3] Socket received CONNECTED event
[        ] [DEVICE LOG] 2019-05-07 17:58:31.050695+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] nw_endpoint_flow_protocol_connected [C2.1 216.58.205.238:443 in_progress socket-flow (satisfied)] Transport protocol connected
[        ] [DEVICE LOG] 2019-05-07 17:58:31.055726+0200  localhost Runner[79279]: (CFNetwork) TIC TLS Event [2:0x600001711680]: 1, Pending(0)
[        ] [DEVICE LOG] 2019-05-07 17:58:31.069931+0200  localhost Runner[79279]: (CFNetwork) TIC TLS Event [2:0x600001711680]: 11, Pending(0)
[        ] [DEVICE LOG] 2019-05-07 17:58:31.070033+0200  localhost Runner[79279]: (CFNetwork) TIC TLS Event [2:0x600001711680]: 14, Pending(0)
[        ] [DEVICE LOG] 2019-05-07 17:58:31.070372+0200  localhost Runner[79279]: (Security) Created Activity ID: 0x13693f, Description: SecTrustEvaluateIfNecessary
[        ] [DEVICE LOG] 2019-05-07 17:58:31.075817+0200  localhost Runner[79279]: (Security) Created Activity ID: 0x136970, Description: SecTrustEvaluateIfNecessaryFastAsync
[        ] [DEVICE LOG] 2019-05-07 17:58:31.082240+0200  localhost Runner[79279]: (CFNetwork) System Trust Evaluation yielded status(0)
[        ] [DEVICE LOG] 2019-05-07 17:58:31.082289+0200  localhost Runner[79279]: (CFNetwork) TIC TLS Trust Result [2:0x600001711680]: 0
[        ] [DEVICE LOG] 2019-05-07 17:58:31.084004+0200  localhost Runner[79279]: (CFNetwork) TIC TLS Event [2:0x600001711680]: 2, Pending(0)
[   +1 ms] [DEVICE LOG] 2019-05-07 17:58:31.089883+0200  localhost Runner[79279]: (Security) Created Activity ID: 0x136971, Description: SecTrustReportTLSAnalytics
[        ] [DEVICE LOG] 2019-05-07 17:58:31.090398+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] nw_endpoint_flow_protocol_connected [C2.1 216.58.205.238:443 in_progress socket-flow (satisfied)] Output protocol connected
[        ] [DEVICE LOG] 2019-05-07 17:58:31.090634+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] nw_connection_report_state_with_handler_locked [C2] reporting state ready
[        ] [DEVICE LOG] 2019-05-07 17:58:31.091121+0200  localhost Runner[79279]: (CFNetwork) TIC TLS Event [2:0x600001711680]: 20, Pending(0)
[        ] [DEVICE LOG] 2019-05-07 17:58:31.091166+0200  localhost Runner[79279]: (CFNetwork) TIC TCP Conn Connected [2:0x600001711680]: Err(16)
[        ] [DEVICE LOG] 2019-05-07 17:58:31.091403+0200  localhost Runner[79279]: (CFNetwork) TIC TCP Conn Event [2:0x600001711680]: 1
[        ] [DEVICE LOG] 2019-05-07 17:58:31.091432+0200  localhost Runner[79279]: (CFNetwork) TIC TCP Conn Event [2:0x600001711680]: 8
[        ] [DEVICE LOG] 2019-05-07 17:58:31.091541+0200  localhost Runner[79279]: (CFNetwork) TIC TLS Handshake Complete [2:0x600001711680]
[        ] [DEVICE LOG] 2019-05-07 17:58:31.094033+0200  localhost Runner[79279]: (CFNetwork) [com.apple.CFNetwork:Coalescing] new connection to clients4.google.com config 0x60000222c740
[        ] [DEVICE LOG] 2019-05-07 17:58:31.094657+0200  localhost Runner[79279]: (CFNetwork) Task <B5DF4ED7-4BCB-48B7-BDAB-46BF0889BD62>.<1> now using Connection 2
[        ] [DEVICE LOG] 2019-05-07 17:58:31.094750+0200  localhost Runner[79279]: (CFNetwork) Task <B5DF4ED7-4BCB-48B7-BDAB-46BF0889BD62>.<1> sent request, body S
[        ] [DEVICE LOG] 2019-05-07 17:58:31.094833+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] nw_endpoint_flow_protocol_connected [C2.1 216.58.205.238:443 ready socket-flow (satisfied)] Output protocol connected
[  +57 ms] [DEVICE LOG] 2019-05-07 17:58:31.181066+0200  localhost Runner[79279]: (CFNetwork) Task <B5DF4ED7-4BCB-48B7-BDAB-46BF0889BD62>.<1> received response, status 200 content K
[   +1 ms] [DEVICE LOG] 2019-05-07 17:58:31.182902+0200  localhost Runner[79279]: (CFNetwork) Task <B5DF4ED7-4BCB-48B7-BDAB-46BF0889BD62>.<1> done using Connection 2
[   +2 ms] [DEVICE LOG] 2019-05-07 17:58:31.184378+0200  localhost Runner[79279]: (CFNetwork) Task <B5DF4ED7-4BCB-48B7-BDAB-46BF0889BD62>.<1> response ended
[+1412 ms] [DEVICE LOG] 2019-05-07 17:58:32.566281+0200  localhost Runner[79279]: (CoreLocation) [com.apple.locationd.Core:Client] delivering locations to client's delegate
[ +148 ms] [DEVICE LOG] 2019-05-07 17:58:32.740284+0200  localhost Runner[79279]: (CFNetwork) [com.apple.CFNetwork:Coalescing] removing all entries config 0x600002241300
[        ] [DEVICE LOG] 2019-05-07 17:58:32.740584+0200  localhost Runner[79279]: (CFNetwork) TIC TCP Conn Cancel [1:0x600001710cc0]
[        ] [DEVICE LOG] 2019-05-07 17:58:32.740692+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] [C1 dl.google.com:443 tcp, url hash: 67d62be7, tls] cancel
[        ] [DEVICE LOG] 2019-05-07 17:58:32.740820+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] [C1 dl.google.com:443 tcp, url hash: 67d62be7, tls] cancelled
[        ] [DEVICE LOG]         [C1.1 22B99B32-1FC1-422E-8F32-85D6F1C9877F 192.168.178.22:60150<->172.217.23.174:443]
[   +4 ms] [DEVICE LOG]         Connected Path: satisfied (Path is satisfied), interface: en0
[        ] [DEVICE LOG]         Duration: 2.620s, DNS @0.015s took 0.023s, TCP @0.057s took 0.006s, TLS took 0.684s
[        ] [DEVICE LOG]         bytes in/out: 4201/682, packets in/out: 9/8, rtt: 0.008s, retransmitted packets: 0, out-of-order packets: 0
[        ] [DEVICE LOG] 2019-05-07 17:58:32.740867+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] 0.000s [C1 82CDC96E-48DE-42E5-AB8D-1010B5C43510 dl.google.com:443 resolver] path:start
[        ] [DEVICE LOG] 2019-05-07 17:58:32.740912+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] 0.002s [C1 82CDC96E-48DE-42E5-AB8D-1010B5C43510 dl.google.com:443 resolver] path:satisfied
[        ] [DEVICE LOG] 2019-05-07 17:58:32.740953+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] 0.015s [C1 82CDC96E-48DE-42E5-AB8D-1010B5C43510 dl.google.com:443 resolver] resolver:start_dns
[        ] [DEVICE LOG] 2019-05-07 17:58:32.740982+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] 0.038s [C1 82CDC96E-48DE-42E5-AB8D-1010B5C43510 dl.google.com:443 resolver] resolver:receive_dns
[        ]      [C1.1 22B99B32-1FC1-422E-8F32-85D6F1C9877F 192.168.178.22:60150<->172.217.23.174:443]
[        ]      Connected Path: satisfied (Path is satisfied), interface: en0
[        ]      Duration: 2.620s, DNS @0.015s took 0.023s, TCP @0.057s took 0.006s, TLS took 0.684s
[        ]      bytes in/out: 4201/682, packets in/out: 9/8, rtt: 0.008s, retransmitted packets: 0, out-of-order packets: 0
[        ] [DEVICE LOG] 2019-05-07 17:58:32.741075+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] 0.039s [C1.1 22B99B32-1FC1-422E-8F32-85D6F1C9877F 192.168.178.22:60150<->172.217.23.174:443 socket-flow] path:start
[        ] [DEVICE LOG] 2019-05-07 17:58:32.741136+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] 0.039s [C1.1 22B99B32-1FC1-422E-8F32-85D6F1C9877F 192.168.178.22:60150<->172.217.23.174:443 socket-flow] path:satisfied
[        ] [DEVICE LOG] 2019-05-07 17:58:32.741179+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] 0.057s [C1.1 22B99B32-1FC1-422E-8F32-85D6F1C9877F 192.168.178.22:60150<->172.217.23.174:443 socket-flow] flow:start_connect
[        ] [DEVICE LOG] 2019-05-07 17:58:32.741694+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] 0.063s [C1.1 22B99B32-1FC1-422E-8F32-85D6F1C9877F 192.168.178.22:60150<->172.217.23.174:443 socket-flow] flow:finish_transport
[        ] [DEVICE LOG] 2019-05-07 17:58:32.741804+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] 0.063s [C1 82CDC96E-48DE-42E5-AB8D-1010B5C43510 dl.google.com:443 resolver] flow:finish_transport
[        ] [DEVICE LOG] 2019-05-07 17:58:32.743717+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] 0.747s [C1.1 22B99B32-1FC1-422E-8F32-85D6F1C9877F 192.168.178.22:60150<->172.217.23.174:443 socket-flow] flow:finish_connect
[        ] [DEVICE LOG] 2019-05-07 17:58:32.743760+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] 0.747s [C1 82CDC96E-48DE-42E5-AB8D-1010B5C43510 dl.google.com:443 resolver] flow:finish_connect
[        ] [DEVICE LOG] 2019-05-07 17:58:32.743798+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] 0.747s [C1.1 22B99B32-1FC1-422E-8F32-85D6F1C9877F 192.168.178.22:60150<->172.217.23.174:443 socket-flow] flow:changed_viability
[        ] [DEVICE LOG] 2019-05-07 17:58:32.744912+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] 0.747s [C1 82CDC96E-48DE-42E5-AB8D-1010B5C43510 dl.google.com:443 resolver] flow:changed_viability
[        ] [DEVICE LOG] 2019-05-07 17:58:32.744949+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] 2.620s [C1] path:cancel
[        ] [DEVICE LOG] 2019-05-07 17:58:32.747193+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] nw_endpoint_flow_protocol_disconnected [C1.1 172.217.23.174:443 cancelled socket-flow (null)] Output protocol disconnected
[        ] [DEVICE LOG] 2019-05-07 17:58:32.747290+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] nw_connection_report_state_with_handler_locked [C1] reporting state cancelled
[        ] [DEVICE LOG] 2019-05-07 17:58:32.747338+0200  localhost Runner[79279]: (CFNetwork) TIC TCP Conn Destroyed [1:0x600001710cc0]
[        ] [DEVICE LOG] 2019-05-07 17:58:32.747418+0200  localhost Runner[79279]: (libboringssl.dylib) [com.apple.network.boringssl:BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C1.1:2][0x7fe07b556d30] get output frames failed, state 8196
[        ] [DEVICE LOG] 2019-05-07 17:58:32.747471+0200  localhost Runner[79279]: (libboringssl.dylib) [com.apple.network.boringssl:BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C1.1:2][0x7fe07b556d30] get output frames failed, state 8196
[        ] [DEVICE LOG] 2019-05-07 17:58:32.747779+0200  localhost Runner[79279]: (CFNetwork) TIC Read Status [1:0x0]: 1:57
[        ] [DEVICE LOG] 2019-05-07 17:58:32.747810+0200  localhost Runner[79279]: (CFNetwork) TIC Read Status [1:0x0]: 1:57
[ +131 ms] [DEVICE LOG] 2019-05-07 17:58:32.886420+0200  localhost Runner[79279]: Google Maps SDK for iOS version: 3.0.33124.0
[        ] Google Maps SDK for iOS version: 3.0.33124.0
[   +1 ms] [DEVICE LOG] 2019-05-07 17:58:32.887557+0200  localhost Runner[79279]: New version of Google Maps SDK for iOS available: 3.1.206.0
[        ] New version of Google Maps SDK for iOS available: 3.1.206.0
[ +256 ms] [DEVICE LOG] 2019-05-07 17:58:33.138404+0200  localhost Runner[79279]: (CFNetwork) [com.apple.CFNetwork:Coalescing] removing all entries config 0x600002241300
[+2960 ms] [DEVICE LOG] 2019-05-07 17:58:36.090181+0200  localhost Runner[79279]: (Flutter) flutter: On Info clicked
[   +4 ms] flutter: On Info clicked
[ +884 ms] [DEVICE LOG] 2019-05-07 17:58:36.996007+0200  localhost Runner[79279]: (UIKitCore) Created Activity ID: 0x136972, Description: send gesture actions
[        ] [DEVICE LOG] 2019-05-07 17:58:36.996052+0200  localhost Runner[79279]: (UIKitCore) Created Activity ID: 0x136973, Description: send gesture actions
[        ] [DEVICE LOG] 2019-05-07 17:58:36.996088+0200  localhost Runner[79279]: (UIKitCore) Created Activity ID: 0x136974, Description: send gesture actions
[  +38 ms] [DEVICE LOG] 2019-05-07 17:58:37.035326+0200  localhost Runner[79279]: (Flutter) flutter: On Marker for Toilet Friedhof Sindlingen clicked valid=false
[        ] flutter: On Marker for Toilet Friedhof Sindlingen clicked valid=false
[+60149 ms] [DEVICE LOG] 2019-05-07 17:59:37.183533+0200  localhost Runner[79279]: (CFNetwork) [com.apple.CFNetwork:Coalescing] removing all entries config 0x60000222c740
[        ] [DEVICE LOG] 2019-05-07 17:59:37.183644+0200  localhost Runner[79279]: (CFNetwork) [com.apple.CFNetwork:Coalescing] removing all entries config 0x60000222c740
[        ] [DEVICE LOG] 2019-05-07 17:59:37.183872+0200  localhost Runner[79279]: (CFNetwork) TIC TCP Conn Cancel [2:0x600001711680]
[        ] [DEVICE LOG] 2019-05-07 17:59:37.183946+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] [C2 clients4.google.com:443 tcp, url hash: eeaec306, tls] cancel
[        ] [DEVICE LOG] 2019-05-07 17:59:37.184105+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] [C2 clients4.google.com:443 tcp, url hash: eeaec306, tls] cancelled
[        ] [DEVICE LOG]         [C2.1 F85FE12B-5ECF-4650-8E52-B682979DDBE2 192.168.178.22:60156<->216.58.205.238:443]
[        ] [DEVICE LOG]         Connected Path: satisfied (Path is satisfied), interface: en0
[   +1 ms] [DEVICE LOG]         Duration: 66.313s, DNS @0.003s took 0.030s, TCP @0.038s took 0.142s, TLS took 0.040s
[        ] [DEVICE LOG]         bytes in/out: 5054/1489, packets in/out: 10/9, rtt: 0.006s, retransmitted packets: 0, out-of-order packets: 0
[        ]      [C2.1 F85FE12B-5ECF-4650-8E52-B682979DDBE2 192.168.178.22:60156<->216.58.205.238:443]
[        ]      Connected Path: satisfied (Path is satisfied), interface: en0
[        ]      Duration: 66.313s, DNS @0.003s took 0.030s, TCP @0.038s took 0.142s, TLS took 0.040s
[        ]      bytes in/out: 5054/1489, packets in/out: 10/9, rtt: 0.006s, retransmitted packets: 0, out-of-order packets: 0
[        ] [DEVICE LOG] 2019-05-07 17:59:37.184169+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] 0.000s [C2 0E4E2E9C-1F7E-4003-8536-030979F44802 clients4.google.com:443 resolver] path:start
[        ] [DEVICE LOG] 2019-05-07 17:59:37.184224+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] 0.001s [C2 0E4E2E9C-1F7E-4003-8536-030979F44802 clients4.google.com:443 resolver] path:satisfied
[        ] [DEVICE LOG] 2019-05-07 17:59:37.184284+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] 0.003s [C2 0E4E2E9C-1F7E-4003-8536-030979F44802 clients4.google.com:443 resolver] resolver:start_dns
[        ] [DEVICE LOG] 2019-05-07 17:59:37.184337+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] 0.033s [C2 0E4E2E9C-1F7E-4003-8536-030979F44802 clients4.google.com:443 resolver] resolver:receive_dns
[   +1 ms] [DEVICE LOG] 2019-05-07 17:59:37.184383+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] 0.034s [C2.1 F85FE12B-5ECF-4650-8E52-B682979DDBE2 192.168.178.22:60156<->216.58.205.238:443 socket-flow] path:start
[        ] [DEVICE LOG] 2019-05-07 17:59:37.184499+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] 0.035s [C2.1 F85FE12B-5ECF-4650-8E52-B682979DDBE2 192.168.178.22:60156<->216.58.205.238:443 socket-flow] path:satisfied
[        ] [DEVICE LOG] 2019-05-07 17:59:37.184708+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] 0.038s [C2.1 F85FE12B-5ECF-4650-8E52-B682979DDBE2 192.168.178.22:60156<->216.58.205.238:443 socket-flow] flow:start_connect
[        ] [DEVICE LOG] 2019-05-07 17:59:37.185118+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] 0.180s [C2.1 F85FE12B-5ECF-4650-8E52-B682979DDBE2 192.168.178.22:60156<->216.58.205.238:443 socket-flow] flow:finish_transport
[        ] [DEVICE LOG] 2019-05-07 17:59:37.185167+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] 0.180s [C2 0E4E2E9C-1F7E-4003-8536-030979F44802 clients4.google.com:443 resolver] flow:finish_transport
[        ] [DEVICE LOG] 2019-05-07 17:59:37.185213+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] 0.220s [C2.1 F85FE12B-5ECF-4650-8E52-B682979DDBE2 192.168.178.22:60156<->216.58.205.238:443 socket-flow] flow:finish_connect
[        ] [DEVICE LOG] 2019-05-07 17:59:37.186413+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] 0.220s [C2 0E4E2E9C-1F7E-4003-8536-030979F44802 clients4.google.com:443 resolver] flow:finish_connect
[        ] [DEVICE LOG] 2019-05-07 17:59:37.186465+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] 0.220s [C2.1 F85FE12B-5ECF-4650-8E52-B682979DDBE2 192.168.178.22:60156<->216.58.205.238:443 socket-flow] flow:changed_viability
[        ] [DEVICE LOG] 2019-05-07 17:59:37.186497+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] 0.220s [C2 0E4E2E9C-1F7E-4003-8536-030979F44802 clients4.google.com:443 resolver] flow:changed_viability
[        ] [DEVICE LOG] 2019-05-07 17:59:37.186525+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] 66.313s [C2] path:cancel
[        ] [DEVICE LOG] 2019-05-07 17:59:37.187686+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] nw_endpoint_flow_protocol_disconnected [C2.1 216.58.205.238:443 cancelled socket-flow (null)] Output protocol disconnected
[        ] [DEVICE LOG] 2019-05-07 17:59:37.187750+0200  localhost Runner[79279]: (libnetwork.dylib) [com.apple.network:] nw_connection_report_state_with_handler_locked [C2] reporting state cancelled
[        ] [DEVICE LOG] 2019-05-07 17:59:37.187797+0200  localhost Runner[79279]: (CFNetwork) TIC TCP Conn Destroyed [2:0x600001711680]
[        ] [DEVICE LOG] 2019-05-07 17:59:37.187834+0200  localhost Runner[79279]: (libboringssl.dylib) [com.apple.network.boringssl:BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C2.1:2][0x7fe07b42b900] get output frames failed, state 8196
[        ] [DEVICE LOG] 2019-05-07 17:59:37.188078+0200  localhost Runner[79279]: (libboringssl.dylib) [com.apple.network.boringssl:BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C2.1:2][0x7fe07b42b900] get output frames failed, state 8196
[        ] [DEVICE LOG] 2019-05-07 17:59:37.188401+0200  localhost Runner[79279]: (CFNetwork) TIC Read Status [2:0x0]: 1:57
[        ] [DEVICE LOG] 2019-05-07 17:59:37.188438+0200  localhost Runner[79279]: (CFNetwork) TIC Read Status [2:0x0]: 1:57

```

```
info • Unused import: 'dart:async' • lib/main.dart:1:8 • unused_import
   info • Name non-constant identifiers using lowerCamelCase • lib/model/Toilet.dart:30:29 • non_constant_identifier_names
   info • Always override `hashCode` if overriding `==` • lib/model/incident_type.dart:9:17 • hash_and_equals
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: LegalScreen._markdownData • lib/screens/legal_screen.dart:9:7 • must_be_immutable
   info • Don't explicitly initialize variables to null • lib/screens/map_screen.dart:35:41 • avoid_init_to_null
   info • Don't explicitly initialize variables to null • lib/screens/map_screen.dart:36:10 • avoid_init_to_null
   info • 'fromAsset' is deprecated and shouldn't be used • lib/screens/map_screen.dart:268:31 • deprecated_member_use
   info • 'fromAsset' is deprecated and shouldn't be used • lib/screens/map_screen.dart:272:31 • deprecated_member_use
   info • Don't explicitly initialize variables to null • lib/screens/report_incident_screen.dart:21:16 • avoid_init_to_null

```

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale de-DE)
    • Flutter version 1.2.1 at /Users/adrian/Development/flutter
    • Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/adrian/Library/Android/sdk
    • Android NDK at /Users/adrian/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio 3.4.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected device (3 available)
    • SM T580                   • 52003158e2231509                     • android-arm • Android 8.1.0 (API 27)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone Xʀ                 • 4F39F049-E21A-4749-AA57-FA51D1CB133C • ios         • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

```

**Comment by sam-toon** [comment]
This is the same as issue #28659 which has been fixed - I was seeing the same issue and it was fixed on master on March.  The fix is now available in the stable channel which has just been updated to 1.5.4.  Doing "flutter upgrade" should fix the issue.

**Comment by Hawlitschek** [comment]
I can confirm that. 
It is working know!

**Comment by Toolenaar** [comment]
I am still having this issue :(

**Comment by vitulgoyani** [comment]
not working still got that issue

**Comment by kapilvallamkonda** [comment]
I am still having the issue..using the latest version 0.5.21+15

**Comment by Hannesalm** [comment]
I am also having the same problem. In version 0.5.21+15

**Comment by Toolenaar** [comment]
This should really be reopned. I keep having this issue

**Comment by diegoveloper** [comment]
same here
