### ISSUE TITLE
flutter run: Error connecting to the service protocol on Android Q (API level 29) emulator

### ISSUE THREAD

**Issue by audkar** [flutter/flutter#33050]
## Steps to Reproduce

1. Execute `flutter run` for fresh project on Android Q emulator

Issue 100% reproducible. People created bunch of issues with only "solution" - downgrade/useRealDevice which is not a solution :)

#32394
#32587
#32696

Even video was created ([Youtube link](https://www.youtube.com/watch?v=6gS0_s2K_gk)) :)))

### flutter run -v
```
Android SDK built for x86 startApp
[   +2 ms] executing: /home/audrius/Documents/android-sdk-canary/platform-tools/adb -s emulator-5554
shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez
enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true
app.nameplaceholder.emute/app.nameplaceholder.emute.MainActivity
[ +100 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000
cmp=app.nameplaceholder.emute/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +676 ms] Observatory URL on device: http://127.0.0.1:35187/JlHwNFYXz7o=/
[   +1 ms] executing: /home/audrius/Documents/android-sdk-canary/platform-tools/adb -s emulator-5554
forward tcp:0 tcp:35187
[  +11 ms] 36495
[        ] Forwarded host port 36495 to device port 35187 for Observatory
[   +6 ms] Connecting to service protocol: http://127.0.0.1:36495/JlHwNFYXz7o=/
[  +25 ms] Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:36495/JlHwNFYXz7o=/ws
```

### flutter doctor -v
```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.5.4-hotfix.2 at /home/audrius/Documents/flutter
    • Framework revision 7a4c33425d (3 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/audrius/Documents/android-sdk-canary
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/audrius/Documents/android-sdk-canary
    • Java binary at:
      /home/audrius/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-1/183.5522156/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 28) (emulator)
```

**Comment by AlanWalk** [comment]
same problem on Android Q emulator

**Comment by jason-simmons** [comment]
The adb port forwarding mechanism used by flutter_tools seems to be failing in the latest Android Q beta on emulators.

See https://issuetracker.google.com/issues/132325318

**Comment by appjitsu** [comment]
This happens to me on a Pixel XL device with Android 9.

Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49511/d1vS-fxaMNY=/ws

**Comment by biklas7** [comment]
This also happens on a real device. Not only emulators.

**Comment by PsychoXIVI** [comment]
Any milestone for this? :C  Downgrading from Q isn't an option for me...

**Comment by julian-sf** [comment]
If you didn't read/see @jason-simmons's [comment](https://github.com/flutter/flutter/issues/33050#issuecomment-494522740), there seems to be a bug in the Android Q Emulator.  Which, if true, means the Flutter team has nothing to do with this bug.  We just need to wait for a resolution from the Emulator team.

See the bug report here: https://issuetracker.google.com/issues/132325318

**Comment by DanTup** [comment]
The linked issue says this is fixed in [Beta 5](https://developer.android.com/preview/release-notes#android_q_beta_5). I just [updated everything through the SDK Manager](https://developer.android.com/preview/get#on_emulator) and created a Q emulator, and I can launch without any issues on it - however I didn't have Q set up before-hand, so I hadn't seen it fail.

Can someone that has been seeing this try updating everything through the SDK Manager in Android Studio, then creating a new Q emulator, and test whether it's fixed?

Thanks!

**Comment by audkar** [comment]
Just checked. Can confirm that it works now!

**Comment by DanTup** [comment]
Great, thanks for confirming! I'll close then, but if anyone is still seeing the issue after upgrading to the latest Q bits in SDK Manager and creating a new Q emulator, do post back.

**Comment by creativecreatorormaybenot** [comment]
@DanTup 

> after upgrading to the latest Q bits in SDK Manager

Well, I am pretty certain that I am on the latest update, i.e. I have te following SDK Platforms and SDK Tools installed:
```
Android SDK Build-Tools Version 29.0.1
Android Emulator Version 29.0.11
Android SDK Platforms-Tools 29.0.1
Android SDK Tools Version 26.1.1
Android 10.0 (Q) Android SDK Platform 29 Revision 1
Android 10.0 (Q) Google APIs Intel x86 Atom System Image Revision 5
```
I cannot see an option to update any further. I created a new AVD with the system image and I am still getting the error, nothing changed.  
Is there any way to update any further? I have installed `Android Studio 3.5 RC 1`.

**Comment by audkar** [comment]
My `Android Emulator` version is `29.1.6`. Thought I am not sure if it is required along emulators image. Also I am on sdk `canary` channel.

**Comment by DanTup** [comment]
> Android 10.0 (Q) Google APIs Intel x86 Atom System Image Revision 5

I appear to have Revision 6 here (it also says Android 9.+ and not Android 10 🤔):

<img width="705" alt="Screenshot 2019-07-25 at 4 50 39 pm" src="https://user-images.githubusercontent.com/1078012/61888918-5b675100-aefc-11e9-8570-ce9541f3db24.png">

**Comment by creativecreatorormaybenot** [comment]
@audkar Well, I am on the `Beta` channel. Is there a way to switch channels just for the SDK?

@DanTup There is no `9.+` option for me, only `10`.

![](https://i.imgur.com/zmoPKIL.png)

**Comment by filiph** [comment]
I just performed clean install of both Flutter and Android on a Windows PC, and got the same error. I went with everything default when installing. (Android Q is not shown as experimental in the Android Studio wizard, so I went with that as well.)

```
PS C:\Users\filip\dev> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17763.615], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[√] Android Studio (version 3.4)
[√] Connected device (1 available)

• No issues found!
```

![Screenshot (12)](https://user-images.githubusercontent.com/919717/62094092-b8327680-b230-11e9-9619-bb504a7180da.png)

I have Android Studio 3.4.2 (latest, just downloaded). I'm not sure how to get to other version numbers. I don't strictly need to develop on this machine, so if it helps, I can keep it in the broken state to troubleshoot.

**Comment by creativecreatorormaybenot** [comment]
@filiph Just for your information: [Here](https://developer.android.com/studio/preview/) you could get preview versions.

**Comment by filiph** [comment]
Let me reopen this. Rationale:

* Developers will get to the broken state by default, just by following [installation instructions](https://flutter.dev/docs/get-started/install/windows).
* The error is not helpful, and it takes motivation and effort to track down the fix.
* The issue affects new users disproportionately.
* Seems to occur on many, if not all, Windows installations.

Is there any way Flutter (tool or plugin) can mitigate this issue? If not, should we add info to https://flutter.dev/docs/get-started/install/windows?

// cc @csells

**Comment by blasten** [comment]
cc @zanderso for visibility

**Comment by filiph** [comment]
FWIW, I have the laptop with me at work (it's my personal machine), in Mountain View. If that helps, I'm happy to lend it. I keep it in the broken state.

If that's not likely to be helpful, let me know and I'll use the workaround (download Pie image).

**Comment by blasten** [comment]
The Flutter tool will now print a message recommending to use a simulator running a lower API level while Q stabilizes.

**Comment by miyoyo** [comment]
I don't remember where I saw it, but adding `android:usesCleartextTraffic="true"` to the AndroidManifest.xml allows it to work, so I'd assume Flutter has cleartext debug traffic.

**Comment by filiph** [comment]
I upgraded both Android Studio and the Flutter plugin today and no longer see the issue. The app starts in the emulator even with Android Q. I didn't see any warning from Flutter.

Not sure if it's related to Android Q vs Flutter, but I get a lot of logging:

```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
W/win_flutter_ap( 6432): Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (greylist, reflection, allowed)
W/win_flutter_ap( 6432): Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (greylist, reflection, allowed)
W/win_flutter_ap( 6432): Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (greylist, reflection, allowed)
W/win_flutter_ap( 6432): Accessing hidden method Landroid/util/LongArray;->get(I)J (greylist, reflection, allowed)
D/        ( 6432): HostConnection::get() New Host Connection established 0xd2226be0, tid 6464
D/        ( 6432): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_host_composition_v1 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2 
W/OpenGLRenderer( 6432): Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/eglCodecCommon( 6432): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation( 6432): eglCreateContext: 0xd222b180: maj 2 min 0 rcv 2
D/EGL_emulation( 6432): eglMakeCurrent: 0xd222b180: ver 2 0 (tinfo 0xbb56c0b0)
Syncing files to device Android SDK built for x86...
D/        ( 6432): HostConnection::get() New Host Connection established 0xbb741370, tid 6468
D/        ( 6432): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_host_composition_v1 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2 
D/eglCodecCommon( 6432): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation( 6432): eglCreateContext: 0xd222cfe0: maj 2 min 0 rcv 2
W/Gralloc3( 6432): mapper 3.x is not supported
D/        ( 6432): createUnique: call
D/        ( 6432): createUnique: call
D/        ( 6432): HostConnection::get() New Host Connection established 0xbb7413c0, tid 6468
D/        ( 6432): HostConnection::get() New Host Connection established 0xd22289e0, tid 6464
D/        ( 6432): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_host_composition_v1 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2 
D/        ( 6432): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_host_composition_v1 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2 
D/EGL_emulation( 6432): eglMakeCurrent: 0xd222cfe0: ver 2 0 (tinfo 0xd225cdb0)
D/EGL_emulation( 6432): eglMakeCurrent: 0xd222b180: ver 2 0 (tinfo 0xbb56c0b0)
D/eglCodecCommon( 6432): setVertexArrayObject: set vao to 0 (0) 1 0
D/EGL_emulation( 6432): eglMakeCurrent: 0xd222cfe0: ver 2 0 (tinfo 0xd225cdb0)
D/eglCodecCommon( 6432): setVertexArrayObject: set vao to 0 (0) 1 0
D/EGL_emulation( 6432): eglMakeCurrent: 0xd222b180: ver 2 0 (tinfo 0xbb56c0b0)
```

**Comment by miyoyo** [comment]
Looks like it's not filtering superficial things from ADB anymore, I recognize those "accessing hidden methods" showing up when doing add2app.

**Comment by blasten** [comment]
@shihaohong I saw you were working on AndroidQ support. Does the issue look familiar?:
```
W/win_flutter_ap( 6432): Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (greylist, reflection, allowed)
W/win_flutter_ap( 6432): Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (greylist, reflection, allowed)
W/win_flutter_ap( 6432): Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (greylist, reflection, allowed)
W/win_flutter_ap( 6432): Accessing hidden method Landroid/util/LongArray;->get(I)J (greylist, reflection, allowed)
```

**Comment by shihaohong** [comment]
@blasten No, it does not. However, it might be showing up on `flutter run` and I may simply have been ignoring it while working through my changes

**Comment by miyoyo** [comment]
These aren't issues, they're just warnings that greylisted hidden methods are being used, just to remind you of all potential issues that might arise because of using non public APIs, but I'm sure the flutter team will handle those if they ever become an issue.

**Comment by TutOsirisOm** [comment]
After the official OTA update for Android 10 my physical Pixel XL device is no longer able to run my app. There's no errors or anything, everything says it went through and it's installed and running but nothing happens on the device. It worked before in all the beta versions of Android 10 on the same device. Not sure if I should open a new issue, seems like it might be related to things discussed here. Same app works perfectly on a different physical device not on Android 10 and on emulator. Anyone else experience this?

**Comment by audkar** [comment]
Create separate issue. You are definitely having different problem. Try to look what android logcat prints out. Maybe application is crashing at start-up. 

Seems todays most voted Flutter topic on reddit might be related to your [issue](https://www.reddit.com/r/FlutterDev/comments/czg1qy/flutter_on_android_10_api_level_29_issues/).

**Comment by tvolkert** [comment]
https://github.com/flutter/flutter/issues/33050#issuecomment-494522740:

> The adb port forwarding mechanism used by flutter_tools seems
> to be failing in the latest Android Q beta on emulators.
> 
> See https://issuetracker.google.com/issues/132325318

Word from the Android team is that they think this is resolved in latest preview -- and to try preview 6

**Comment by DanTup** [comment]
@tvolkert if I understand @TutOsirisOm's first line correctly, this is on a physical device that received the final release Android 10 update (not preview).

**Comment by tvolkert** [comment]
Yes, sorry - I was responding to the OP issue.

**Comment by tvolkert** [comment]
@TutOsirisOm your issue looks different - please file a new issue at https://github.com/flutter/flutter/issues/new?assignees=tvolkert&template=BUG.md . Thanks!

**Comment by DanTup** [comment]
To avoid confusion, should this one be closed (as fixed in the Android SDK)? The non-preview bits for Android 10 are now available - my Android Studio just prompted me to download them.

**Comment by tvolkert** [comment]
Has anyone verified that the "Error connecting to the service protocol" error is fixed in Android 10 emulators?

**Comment by shihaohong** [comment]
@tvolkert I've been testing Android 10 features on the emulators and they've been working fine for me

**Comment by audkar** [comment]
For me it is working for a long time https://github.com/flutter/flutter/issues/33050#issuecomment-515015689 
@filiph had some troubles on windows though https://github.com/flutter/flutter/issues/33050#issuecomment-516606134

**Comment by tvolkert** [comment]
Ok, let's close this one since it's overloaded, and indications are that the original issue has been fixed.

@audkar please re-open if that's not the case!

**Comment by Adilson72** [comment]
I had the same problem...
To solve it, try using an android emulator with API 28...
