### ISSUE TITLE
google sign in ^4.0.1+3 plugin: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null) 

### ISSUE THREAD

**Issue by bradmuzza** [flutter/flutter#33393]
Configuration fix that seems to have helped many people: 
https://github.com/flutter/flutter/issues/33393#issuecomment-964728679 

## Details
After sigining in to google at this line (Android)  

`  GoogleSignInAccount googleUser = await _googleSignIn.signIn();`

I get this exception 

`PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null)
`

I have tired all the advice from this issue https://github.com/flutter/flutter/issues/27599 including linking firebase and google account, adding SHA1 and SHA256 to firebase and changing the classpath to `com.android.tools.build:gradle:3.2.1/com.google.gms:google-services:4.2.0.` which threw build errors, after adding sub project script to fix, build errors was gone however sign in still did not function.

I also deleted my Android folder recreated the project and redid all the steps again. The error throw in both release and debug builds  

I believe I have migrated to AndriodX however it is hard to say with 100% certainty as the documentation is vague and Andriod studio tools said "no found issues". 
  
The error started after I move from the master channel to the stable channel. I move channels because the release built of my app was crashing on launch and I read that it could help solve the issue

I have been working on this problem for serval weeks so please help. 

From time to time I also get this build warning
```
Note: /Users/bradmurray/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.0+1/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

## Flutter DR

```
```

✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-AU)
    • Flutter version 1.5.4-hotfix.2 at /Users/bradmurray/Developer/flutter
    • Framework revision 7a4c33425d (4 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/bradmurray/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] Connected device
    ! No devices available

## Build Gradle
```
buildscript {
    repositories {
        google()
        jcenter()
        mavenLocal()
    }

    dependencies {
         classpath 'com.android.tools.build:gradle:3.3.1'
        classpath 'com.google.gms:google-services:4.2.0'
 
    
    }
   


}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

##Pub spec
```
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
   sdk: flutter
  firebase_core: 
  firebase_database:
  cached_network_image:
  firebase_storage:
  location : ^2.3.0
  flutter_calendar_carousel: ^1.3.16
  carousel_pro: ^0.0.13
  shared_preferences: ^ 0.4.3
  url_launcher: ^4.2.0+3
  flutter_local_notifications: ^0.5.0
  after_layout: ^1.0.7
  geolocator: ^3.0.0
  google_sign_in: ^4.0.1+3
  firebase_auth: ^0.11.1
  font_awesome_flutter: ^8.4.0
  scoped_model: ^1.0.1
  google_maps_flutter:
   path: ../google_maps_flutter
  permission_handler: ^3.0.1
  cupertino_icons: ^0.1.2
```

**Comment by mehmetf** [comment]
Perhaps https://github.com/googlesamples/google-services/issues/360 would help.

**Comment by DaathGit** [comment]
Having the same problem: I created an app, a few months ago, with google sign-in, using the SHA1 and SHA256 from the command:
keytool -list -v -alias androiddebugkey -keystore %USERPROFILE%\.android\debug.keystore

That app works. But when I create another app with the same procedure, i get:
PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 12500: , null)
Even if its the same app, with the same code from the first one. (the SHA1 and SHA256 are the same for both apps, the packages names are different)

I tried to follow this guide:
https://sheeeng.github.io/dart/firebase/flutter/authentication/2019/01/20/sign-in-failed-on-flutter.html
to create another debug.keystore file to get a different SHA1 and SHA256.
If I add the new fingerprints to the Firebase Configuration, while keeping the old ones, i still get the same error.
If i remove the old fingerprints, i get:
PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null)

**Comment by DaathGit** [comment]
I added a support email in the Settings - General - Public Settings and it works

**Comment by Ale-Digitale** [comment]
> I added a support email in the Settings - General - Public Settings and it works

I can't believe this is the trick to make it work !!! I confirm this solved this identical problem, at least in my case.

Thank you so much @DaathGit !!!

I've been going crazy with this EXCEPTION for days... and "simply" adding the support email did the magic !

How can this be undocumented ??? The EXCEPTION we receive from Google, didn't mention this at all.

Did you find it out just by luck / trials and errors ?!?

**Comment by DaathGit** [comment]
Found the solution on the 100th random google page with a post about this problem.
Glad it worked for you too!

**Comment by aldarisbm** [comment]
Thanks @DaathGit you're the real MVP, this just fixed a problem I've been dealing with all day.

**Comment by xero88** [comment]
Not working for me. I think i will not migrate to flutter because of this bug. I tried everthing. 
-remove my debugkeystore, recreate one
-add support email
-change versions of plugin
-update google on my device

nothing is working, getting this shit error ApiException: 12500

**Comment by kalismeras61** [comment]
> Not working for me. I think i will not migrate to flutter because of this bug. I tried everthing.
> -remove my debugkeystore, recreate one
> -add support email
> -change versions of plugin
> -update google on my device
> 
> nothing is working, getting this shit error ApiException: 12500

Same with me i didnt find any solution..

**Comment by xero88** [comment]
@kalismeras61 I found the solution

https://stackoverflow.com/questions/47632035/google-sign-in-error-12500

the answer of Pranjal Gupta says : 

And Last and most important Save OAuth consent under credentials in google api, OAuth Screen This took a long to figure out. And it worked fine after this.

So I went to this page (https://console.developers.google.com/apis/credentials)
Do not forget to select your project on the list (top left). Then go on "Oauth consent screen"

I filled the application logo and the application homepage link and aplication privacy policy link (with the project.firebaseapp.com) and saved.

![alt text](https://i.ibb.co/m65jTQC/Capture-d-cran-de-2019-07-11-10-49-02.png)

Now it's working, I can login.

This must be explained in the documentation. People are going to be crazy and to don't try flutter with this kind of lack of documentation.

Hope this will help

**Comment by kalismeras61** [comment]
Thanks :)) now it is working :))

> @kalismeras61 I found the solution
> 
> https://stackoverflow.com/questions/47632035/google-sign-in-error-12500
> 
> the answer of Pranjal Gupta says :
> 
> > And Last and most important Save OAuth consent under credentials in google api, OAuth Screen This took a long to figure out. And it worked fine after this.
> 
> So I went to this page (https://console.developers.google.com/apis/credentials)
> Do not forget to select your project on the list (top left). Then go on "Oauth consent screen"
> 
> I filled the application logo and the application homepage link and aplication privacy policy link (with the project.firebaseapp.com) and saved.
> 
> ![alt text](https://camo.githubusercontent.com/266ae6f842802001487958cdbd603da406176de9/68747470733a2f2f692e6962622e636f2f6d36356a5451432f436170747572652d642d6372616e2d64652d323031392d30372d31312d31302d34392d30322e706e67)
> 
> Now it's working, I can login.
> 
> This must be explained in the documentation. People are going to be crazy and to don't try flutter with this kind of lack of documentation.
> 
> Hope this will help

Yes i really helps me!! Thanks...

**Comment by klaszlo8207** [comment]
Working finally :DDDD

**Comment by vurvn** [comment]
> 
> 
> @kalismeras61 I found the solution
> 
> https://stackoverflow.com/questions/47632035/google-sign-in-error-12500
> 
> the answer of Pranjal Gupta says :
> 
> > And Last and most important Save OAuth consent under credentials in google api, OAuth Screen This took a long to figure out. And it worked fine after this.
> 
> So I went to this page (https://console.developers.google.com/apis/credentials)
> Do not forget to select your project on the list (top left). Then go on "Oauth consent screen"
> 
> I filled the application logo and the application homepage link and aplication privacy policy link (with the project.firebaseapp.com) and saved.
> 
> ![alt text](https://camo.githubusercontent.com/266ae6f842802001487958cdbd603da406176de9/68747470733a2f2f692e6962622e636f2f6d36356a5451432f436170747572652d642d6372616e2d64652d323031392d30372d31312d31302d34392d30322e706e67)
> 
> Now it's working, I can login.
> 
> This must be explained in the documentation. People are going to be crazy and to don't try flutter with this kind of lack of documentation.
> 
> Hope this will help

BOOM!! You're awesome. I maximum effort last night. After waking up, I see Deadpool's awswer! 💯  thanks so much @xero88

**Comment by blackerpaper** [comment]
> @kalismeras61 I found the solution
> 
> https://stackoverflow.com/questions/47632035/google-sign-in-error-12500
> 
> the answer of Pranjal Gupta says :
> 
> > And Last and most important Save OAuth consent under credentials in google api, OAuth Screen This took a long to figure out. And it worked fine after this.
> 
> So I went to this page (https://console.developers.google.com/apis/credentials)
> Do not forget to select your project on the list (top left). Then go on "Oauth consent screen"
> 
> I filled the application logo and the application homepage link and aplication privacy policy link (with the project.firebaseapp.com) and saved.
> 
> ![alt text](https://camo.githubusercontent.com/266ae6f842802001487958cdbd603da406176de9/68747470733a2f2f692e6962622e636f2f6d36356a5451432f436170747572652d642d6372616e2d64652d323031392d30372d31312d31302d34392d30322e706e67)
> 
> Now it's working, I can login.
> 
> This must be explained in the documentation. People are going to be crazy and to don't try flutter with this kind of lack of documentation.
> 
> Hope this will help

I just add the logo and boom its working. Awesome, thx.

**Comment by mertgonkesen** [comment]
> @kalismeras61 I found the solution
> 
> https://stackoverflow.com/questions/47632035/google-sign-in-error-12500
> 
> the answer of Pranjal Gupta says :
> 
> > And Last and most important Save OAuth consent under credentials in google api, OAuth Screen This took a long to figure out. And it worked fine after this.
> 
> So I went to this page (https://console.developers.google.com/apis/credentials)
> Do not forget to select your project on the list (top left). Then go on "Oauth consent screen"
> 
> I filled the application logo and the application homepage link and aplication privacy policy link (with the project.firebaseapp.com) and saved.
> 
> ![alt text](https://camo.githubusercontent.com/266ae6f842802001487958cdbd603da406176de9/68747470733a2f2f692e6962622e636f2f6d36356a5451432f436170747572652d642d6372616e2d64652d323031392d30372d31312d31302d34392d30322e706e67)
> 
> Now it's working, I can login.
> 
> This must be explained in the documentation. People are going to be crazy and to don't try flutter with this kind of lack of documentation.
> 
> Hope this will help

omg i update logo and now it is working. Hours and hours of researches should not be for this :( Thank you by the way.

**Comment by kalismeras61** [comment]
If anyone have this problem i published medium article for fix;

https://medium.com/@yasinilhan/how-to-fix-flutter-google-sign-in-plugin-12500-error-ed2de7f5276f

**Comment by amrit-citrusleaf** [comment]
It's not working even after updating the correct SHA1 and updating the OAuth Consent Screen with all the required values. The consent screen has been verified from Google as well. Does google API console maintain any kind of error logs?

**Comment by PfaffDev** [comment]
I'm trying the solution @xero88 posted, filling in the consent screen, but it requires verification for adding the icon, which the *Google Cloud Platform/API Trust & Safety* rep I was assigned to is refusing to do because my app is still in development. Any suggestions?

![](https://raw.githubusercontent.com/PfaffDev/assets/master/gcp-verification-issue-002.png)
![](https://raw.githubusercontent.com/PfaffDev/assets/master/gcp-verification-issue-003.png)
![](https://raw.githubusercontent.com/PfaffDev/assets/master/gcp-verification-issue-004.png)

**Comment by deadsoul44** [comment]
@amrit-citrusleaf did you find any solution?

I am in the same situation. I tried every solution but I still get ApiException: 10.

**Comment by sachinPramodya** [comment]
make sure you have added

```
 dependencies {
    classpath 'com.google.gms:google-services:4.2.0'
}
```
in android/build.gradle and

`apply plugin: 'com.google.gms.google-services'`

in **android/app/build.gradle**. Also, make sure applicationId in **android/app/build.gradle** is the same as your package name in **AndroidManifest.xml**(You may forget to change applicationId after changing package name sometimes). This applicatioonId or package name in manifest file should be the name of your android package name in firebase app.

**Comment by PfaffDev** [comment]
@sachinPramodya I have checked that. I'm getting ApiException: 4, but all issues referencing that lead here and provide no useful information. I'm also only getting it with silent sign in, so maybe that can help narrow it down.

**Comment by PfaffDev** [comment]
Nevermind, I got it figured out. Google silent sign-in fails with ApiException 4 if you haven't signed in before. I had something misconfigured, so it wasn't handling it properly. They really need better error messages in it.

**Comment by kinex** [comment]
@mpfaff Same problem here. This problem occurred after I switched from Flutter 1.9.1 hotfix.4 (stable channel) to Flutter 1.10.7 (beta channel). The same code worked in the stable channel.

**Comment by erperejildo** [comment]
I tried everything and didn't work

**Comment by kinex** [comment]
Check also https://github.com/flutter/flutter/issues/42682 related to `WidgetsFlutterBinding.ensureInitialized()` and `runZoned`. That was the issue I had.

**Comment by erperejildo** [comment]
sorry @kinex but not sure how is that related

**Comment by toughthomas** [comment]
I tried everything stated before, but still get the error :

- Fill the Oauth Consent screen on the correct project
- Select an email on firebase general setting
-created application on firebase with the certificate SHA1 of ~/.android/debug.keystore
-allowed Google sign in on firebase Auth
-copied google-service.json in my project 

tried com.google.android.gms.common v 4.2.0, 4.2.2, 4.2.1

This is driving mad, any ideas ?

**Comment by sokhasen** [comment]
✅ **Just complete these enough steps below**

1. Enable **Google** Auth Method
2. Configure **certificate fingerprints** in your current project at `project-level setting`. [How to Generate certificate](https://developers.google.com/android/guides/client-auth).
3. Select email for **Project support email**
4. Download `google-service.json` into my project.
5. Run `flutter clean`
6. start `flutter run`

![image](https://user-images.githubusercontent.com/26691076/75997267-aedd5b00-5f31-11ea-9eaa-847b9ed3c310.png)

**Comment by erperejildo** [comment]
I think also after you make all of these changes you need to wait for a while. Not sure for how long tbh, don't think it takes days, but definitely is not straight away. For me is working now and I did not try anything else

**Comment by TUKenStone** [comment]
> I added a support email in the Settings - General - Public Settings and it works

is that android studio because im not following the path?

**Comment by devDeejay** [comment]
**In addition to above fix,** Another possible cause of the problem is that you may have not added both DEBUG and RELEASE SHA1 KEY to Firebase Project Settings and have not downloaded and added the latest googleservices.config file to your project.

**Comment by Azeem1111** [comment]
I/flutter (19738): Error signing in: PlatformException(sign_in_required, com.google.android.gms.common.api.ApiException: 4: 4: , null)

**Comment by Azeem1111** [comment]
I got the same problem and none of the above  given solution helping 
I/flutter (19738): Error signing in: PlatformException(sign_in_required, com.google.android.gms.common.api.ApiException: 4: 4: , null)

**Comment by avijitnagare** [comment]
I encountered this error when i changed machine. I regenerated SH1 key and downloaded google-services.json file.

**Comment by RaitonGG** [comment]
> @kalismeras61 I found the solution
> 
> https://stackoverflow.com/questions/47632035/google-sign-in-error-12500
> 
> the answer of Pranjal Gupta says :
> 
> > And Last and most important Save OAuth consent under credentials in google api, OAuth Screen This took a long to figure out. And it worked fine after this.
> 
> So I went to this page (https://console.developers.google.com/apis/credentials)
> Do not forget to select your project on the list (top left). Then go on "Oauth consent screen"
> 
> I filled the application logo and the application homepage link and aplication privacy policy link (with the project.firebaseapp.com) and saved.
> 
> ![alt text](https://camo.githubusercontent.com/266ae6f842802001487958cdbd603da406176de9/68747470733a2f2f692e6962622e636f2f6d36356a5451432f436170747572652d642d6372616e2d64652d323031392d30372d31312d31302d34392d30322e706e67)
> 
> Now it's working, I can login.
> 
> This must be explained in the documentation. People are going to be crazy and to don't try flutter with this kind of lack of documentation.
> 
> Hope this will help

jezuz, google has terrible documents i swear to god.
so, since i have "sensitive" scopes, I am waiting for confirmation on their end. does this mean I will be able to login only when they aprove? considering the app has been pending on the playstore for over a week now i'm assuming this will take months?

**Comment by lielvan** [comment]
Currently having tried literally everything mentioned above, I'm still receiving this ApiException: 10... (HOWEVER - weird part at the end of comment).

I've followed these issues/articles to attempt to solve it:
- https://stackoverflow.com/questions/54557479/flutter-and-google-sign-in-plugin-platformexceptionsign-in-failed-com-google/54696963#54696963
- https://medium.com/flutter-community/flutter-implementing-google-sign-in-71888bca24ed
- https://medium.com/@yasinilhan/how-to-fix-flutter-google-sign-in-plugin-12500-error-ed2de7f5276f

What my past few days have accomplished:
* Enabled Google sign in through Firebase console (sign-in method).
* Have a support email, SH1 & SH256 keys along with correct package name (Using the latest google-services.json).
* Dependencies are present, applicationId matches package name, per @sachinPramodya
* Updated Google Play services.
* Filled the OAuth Consent as mentioned by @xero88 .

At first I thought this happened because of my OAuth consent was needing verification since I uploaded a logo, which automatically requires verification. (There's an open issue to change that - https://issuetracker.google.com/u/1/issues/158736319)

Now, weirdest part is, I get this error on 3 different physical Android devices including my mac's AVD emulator (Nexus 6, Android 9.0, API Level 28 (Pie)). **HOWEVER**, on a different pc (Windows 10) using AVD emulator (Pixel 3, Android 10, API Level 29) everything runs perfectly... I'm able to signInWithGoogle and remain signed in. Funny part, I even tried recreating the same emulator on my mac and even that didn't work.

**Comment by avijitnagare** [comment]
Can you try production SHA1 from play.google.cosole app. Information to
firebase. That works for me.

**Comment by lielvan** [comment]
@avijitnagare I've already created production keys following this guide - https://flutter.dev/docs/deployment/android#signing-the-app and added them to Firebase.
My Firebase SHA certificate fingerprints has 4 keys - two SHA1 (debug/release) and 2 SHA256 (debug/release).
The Pixel 3 emulator where I mentioned that the Google sign-in works doesn't care about the release keys. I've removed their reference and it still runs fine.

**Comment by lielvan** [comment]
> Currently having tried literally everything mentioned above, I'm still receiving this ApiException: 10... (HOWEVER - weird part at the end of comment).
> 
> I've followed these issues/articles to attempt to solve it:
> 
> * https://stackoverflow.com/questions/54557479/flutter-and-google-sign-in-plugin-platformexceptionsign-in-failed-com-google/54696963#54696963
> * https://medium.com/flutter-community/flutter-implementing-google-sign-in-71888bca24ed
> * https://medium.com/@yasinilhan/how-to-fix-flutter-google-sign-in-plugin-12500-error-ed2de7f5276f
> 
> What my past few days have accomplished:
> 
> * Enabled Google sign in through Firebase console (sign-in method).
> * Have a support email, SHA1 & SHA256 keys along with correct package name (Using the latest google-services.json).
> * Dependencies are present, applicationId matches package name, per @sachinPramodya
> * Updated Google Play services.
> * Filled the OAuth Consent as mentioned by @xero88 .
> 
> At first I thought this happened because of my OAuth consent was needing verification since I uploaded a logo, which automatically requires verification. (There's an open issue to change that - https://issuetracker.google.com/u/1/issues/158736319)
> 
> Now, weirdest part is, I get this error on 3 different physical Android devices including my mac's AVD emulator (Nexus 6, Android 9.0, API Level 28 (Pie)). **HOWEVER**, on a different pc (Windows 10) using AVD emulator (Pixel 3, Android 10, API Level 29) everything runs perfectly... I'm able to signInWithGoogle and remain signed in. Funny part, I even tried recreating the same emulator on my mac and even that didn't work.

**Update**: I've found a difference with */build/app/outputs/apk/debug/app-debug.apk/AndroidManifest.xml*.

**working version:**
```
            android:name="com.google.android.gms.auth.api.signin.RevocationBoundService"
            android:permission="com.google.android.gms.auth.api.signin.permission.REVOCATION_NOTIFICATION"
            android:exported="true"
            android:visibleToInstantApps="true" />
```

**ApiException version**:
```
            android:name="com.google.android.gms.auth.api.signin.RevocationBoundService"
            android:permission="com.google.android.gms.auth.api.signin.permission.REVOCATION_NOTIFICATION"
            android:exported="true" />
```

Executed **flutter clean**, ran the app again, but that last line `android:visibleToInstantApps="true"` was still missing. So after checking *manifest-merger-debug-report.txt* I noticed that Gradle is using cached files from .gradle/caches, and again, there were discrepancies with some of the plugin versions between the working and ApiException builds. 

After deleting the *caches* folder, hoping that once I execute **flutter run**, everything will magically work. Unfortunately, I now ran into a gradle build issue (open flutter issue - https://github.com/flutter/flutter/issues/58637).

**Comment by hamza-gaya** [comment]
Tried everything nothing works all above solutions are useless,

**Comment by m4n4n-j** [comment]
In my case, after trying some of the things mentioned, I got to know that my Virtual Device was unable to connect to the internet. After restarting, IT WORKED!

**Comment by festapp86** [comment]
Did you link your project to Firebase and use the google-services.json with all the client_ids, too?

**Comment by m4n4n-j** [comment]
Yes, I did all of that but still, the exception persisted. There was some issue with the emulator connecting to the network and not with the code I think.

**Comment by rohitsainik** [comment]
the only solution to this hilarious problem is you have to add play store shakey in your firebase account.

**Comment by manish-jandu** [comment]
`PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null)`
Solution:
**Don't** generatate sh1 using-
`keytool -list -v -keystore "C:\Users\yourusernamehere\.android\debug.keystore" -alias androiddebugkey -storepass android -keypass android`
**But Instead**
```
cd android
./gradlew signinReport
```
I don't know why but I am getting 2 different sh1 from these 2 methods but second worked for me.

**Comment by satyamraj123** [comment]
tried everything here but still same apiException 10 is there.

**Comment by fluttercorner1** [comment]
Here Is All Possible Solution added [Flutter and google_sign_in plugin: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null)](https://fluttercorner.com/flutter-and-google_sign_in-plugin-platformexceptionsign_in_failed-com-google-android-gms-common-api-apiexception-10-null/)

**Comment by jkbngl** [comment]
For me the issue was that I created the app in debug mode, but used a production keystore, adding the debug keystore in firebase fixed the issue for me:
```
keytool -alias androiddebugkey -keystore "%USERPROFILE%"\.android\debug.keystore -list -v
```

**Comment by gab07** [comment]
What worked for us was to [link our Firebase project to Google Play](https://stackoverflow.com/a/47620437/6275643)

**Comment by saurabhdtu** [comment]
I am facing this same exception 10. Prior to this, I was facing exception 12500 which got resolved on its own when I deleted the project and my debug keystore and created everything again.

_I have done all of the things mentioned below:_

1. Uploaded SHA-1 and SHA-256 of both debug and release on firebase
2. Enabled google login in authentication
3. Added support email on firebase
4. I have filled the consent form on google developers console with logo, support email and domains (using the ones available in firebase)
5. Matched my debug and release keys with firebase and developers console
6. Enabled the google APIs on google developers console
7. Updated my google play services in SDK.
8. Recreated the virtual device
9. My debug keys are same either generated via gradlew or keytool
10. I have tried on my real device too, but the same error
11. I have added the profile, email and open id scopes
12. WidgetsFlutterBinding.ensureInitialized() and runZoned  is done

I am using  **google_sign_in: 5.0.2** & **classpath 'com.google.gms:google-services:4.3.5'**

My Flutter doctor
<img width="985" alt="Screenshot 2021-05-05 at 10 16 48 PM" src="https://user-images.githubusercontent.com/7895040/117178408-9dbb0300-adef-11eb-9ab5-2c02c43438d7.png">

I have just started, so I don't have play store developers account right now, so that hasn't been linked
I have been stuck over this issue for a week. I have gone through all the articles and posts and tried everything. It would be a great help if somebody can help me in figuring out the issue

**Comment by saurabhdtu** [comment]
Solved it. It wasn't mentioned anywhere but by adding the google auth dependency in gradle alongside the flutter package solved it

**Comment by ascott18** [comment]
I wanted to summarize what I found about this after trawling dozens of other issues about this problem, as well as the problem where idToken comes back as null:

---

If you specify a `clientId` parameter to `GoogleSignIn`, **this `clientId` MUST be a clientID of a "Web application" type OAuth2 client created in the GCP console. If you give a `clientId` for any other type of OAuth2 client (e.g. an "Android" client), you'll get error 10.**

If you do not need an `idToken`, you can omit `clientId`. But if you need a `idToken`, you must either be using the Firebase setup with the google-services.json file, OR you must specify a Web Application `clientId`.

Note that this `clientId` parameter is an _override_ of the one that will be injected from your Firebase google-services.json file. See [this comment](https://github.com/flutter/flutter/issues/12140#issuecomment-348720774) for details on how google-services.json is actually used by the build process.

The documentation comment for `clientId` that states "Only supported on web" is patently false, and grossly misrepresents what the purpose of this parameter is for.

See the source code of the https://github.com/flutter/plugins/blob/1a2fbe878d86ee74fc46a422619442d4c5a74945/packages/google_sign_in/google_sign_in/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java#L338-L352

**Comment by hpoit** [comment]
Hi @dnfield and @Hixie, how are you? I am also having this issue and I was told that you all might be directly involved in this. Is there any forecast on when this issue should be closed and solved? What should I do in the meantime? I have tried the hacks suggested in here, but had no success in any of them. I appreciate your help. Thank you very much.

**Comment by chhsh122** [comment]
> Found the solution on the 100th random google page with a post about this problem.
> Glad it worked for you too!

where can setting email  solve problem ??  console.cloud.google.com??

**Comment by candstechnologies** [comment]
We are also facing same issue with Google oauth. We have tried all the relevant options provided on this post but not able to get thru it. We are not using firebase. Please help

**Comment by SungHyun22** [comment]
@ascott18  

thank you!!

using web oauth key is work for me

**Comment by tuanbs** [comment]
> I wanted to summarize what I found about this after trawling dozens of other issues about this problem, as well as the problem where idToken comes back as null:
> 
> If you specify a `clientId` parameter to `GoogleSignIn`, **this `clientId` MUST be a clientID of a "Web application" type OAuth2 client created in the GCP console. If you give a `clientId` for any other type of OAuth2 client (e.g. an "Android" client), you'll get error 10.**
> 
> If you do not need an `idToken`, you can omit `clientId`. But if you need a `idToken`, you must either be using the Firebase setup with the google-services.json file, OR you must specify a Web Application `clientId`.
> 
> Note that this `clientId` parameter is an _override_ of the one that will be injected from your Firebase google-services.json file (if you're using Firebase). See [this comment](https://github.com/flutter/flutter/issues/12140#issuecomment-348720774) for details on how google-services.json is actually used by the build process.
> 
> The documentation comment for `clientId` that states "Only supported on web" is patently false, and grossly misrepresents what the purpose of this parameter is for.
> 
> [See the source code of the plugin](https://github.com/flutter/plugins/blob/1a2fbe878d86ee74fc46a422619442d4c5a74945/packages/google_sign_in/google_sign_in/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java#L338-L352) to see how clientId gets used. The `TODO(jackson)` comment in the code about adding an override there was since implemented (on March 18, 2021) - that's what the `clientId` parameter is, but the TODO comment was never removed.
> 
> [This bit of documentation](https://developers.google.com/identity/sign-in/android/start-integrating#get_your_backend_servers_oauth_20_client_id) about doing Google auth natively in Android explains why the Web Application client ID is needed.

I got another error (`PlatformException(sign_in_failed, r4.b: 10: , null, null)`) after publishing to Google Play.

Particularly, at the beginning I got the error `PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)`. Then I followed your instruction to replace the Android Client Id with Web Client Id. Then I built the app bundle and tested the app bundle on my Android device. It works fine. But after I published the app bundle to the Google Play Console, I downloaded the app directly from Google Play and got this error. Any idea? Thanks in advance.

**Comment by trinhjorwe** [comment]
The fix for me turned out to be the OAuth2.0 client package name I had set initially when I was first developing the app, was now different to the current package name. Ensuring the "Package name" in OAuth 2.0 Client ID matches the package name in your AndroidManifest.xml fixed it for me.

**Comment by ibrahimeth** [comment]
Hi @erperejildo  ! Was your error message  ApiException: 10 ? 
İf it was What did you do on your code ?
thanks

**Comment by ibrahimeth** [comment]
@trinhjorwe  how did you solve your error .ApiException: 10: was it

**Comment by ibrahimeth** [comment]
Hello, I solved this problem. This problem is related to your SHA-1 key being wrong, please type the following command in the terminal in the android directory.
Type ./gradlew signingReport and one of the keys when creating firebase android

**Comment by hwebservices** [comment]
Hello, anyone know the solution for this error with NO firebase implementation? I am using this plug-in without firebase... upgrading version won't help...

**Comment by jerbio** [comment]
Hello,

Has any one found the solution to this problem. The issue with this bug is specific to releasing to the play store and not using firebase.  Most Api Exceptions 10 codes are related to Sha-1 fingerprint mismatches. However as the original posted noted the apk build works without issues. 
Troubleshooting steps: 
- I extracted and installed the apk from the aab using buildtools and the sign in works on the device.
- I compared the Sha-1 fingerprint from the Apk build and the AAB build, they both match, so we know this isn't a Sha1 local build issue.

Is there an issue with using this package on the google play store without firebase?

**Comment by jerbio** [comment]
Hello,

Finally figured this one out, the issue is still related to sha-1 Certifcate but however the problem is you need to create a new andorid oauth client-id for android using the Sha-1 finger print of the google play console app signing certificate .

have to your app page on the 
Google Play Console -> Your Application -> Setup -> App Integrity.

Click on "App Signing Tab"

Under this page you should see there are two sections "App signing key certificate" and "Upload key certificate"
![Screenshot 2023-07-05 at 2 34 51 AM](https://github.com/flutter/flutter/assets/4109175/5daa4bc1-7535-4b2b-ac12-b3c0072de1ec)
You need to copy the sha-1 fingerprint Under "App signing key certificate"

Go to your google cloud console.
Create a new Oauth client id for android:
![Screenshot 2023-07-05 at 2 41 28 AM](https://github.com/flutter/flutter/assets/4109175/5250e14a-2b5a-4948-8242-686a9a94c41b)

Paste the Sha-1 key in the newly created Android Oauth client-id

![Screenshot 2023-07-05 at 2 44 11 AM](https://github.com/flutter/flutter/assets/4109175/c78e1a67-b7a6-4d8c-bfe7-3d459e7582d0)


Note none of this required Firebase integration.  Hope this cracks it for every one.

**Comment by lukehutch** [comment]
> Hope this cracks it for every one.

This is only relevant if you are using Google Play to sign your release apks.

For debug apks, you need to get the debug SHA-1 fingerprint by doing: `./gradlew app:signingReport` -- and then you need to paste that into your Play Developer Console under the Android OAuth2 Client as "SHA-1 certificate fingerprint". This solved the problem for me once before.

It stopped working for me again now though, after some unrelated tinkering (I'm not sure what triggered this to suddenly stop working again). I have triple-checked everything in the Developer Console and in my code, and I have no idea what else can cause this error 10.

**Comment by BilalKashif** [comment]
In my case I am using the web client id from google console to communicate with my backed according to the O-Auth documentation

https://developers.google.com/identity/sign-in/android/start-integrating#get_your_backend_servers_oauth_20_client_id

And, I thought that there is no more need for android, and IOS client-id on google console. So, I removed them. That is why I was getting this error. So, I add them back and my issue resolved.

**Comment by denysvitali** [comment]
In my case the legacy key was still being used to sign my releases - for whatever reason - and I was whitelisting the latest key instead.

**Comment by guplem** [comment]
This worked like a charm for me: https://medium.com/codebrew/flutter-google-sign-in-without-firebase-3680713966fb
In summary: I created new OAuth 2.0 Client IDs using the SHA1 keys from the command `./gradlew signInReport`.

**Comment by AgustinIMassa** [comment]
> > I wanted to summarize what I found about this after trawling dozens of other issues about this problem, as well as the problem where idToken comes back as null:
> > If you specify a `clientId` parameter to `GoogleSignIn`, **this `clientId` MUST be a clientID of a "Web application" type OAuth2 client created in the GCP console. If you give a `clientId` for any other type of OAuth2 client (e.g. an "Android" client), you'll get error 10.**
> > If you do not need an `idToken`, you can omit `clientId`. But if you need a `idToken`, you must either be using the Firebase setup with the google-services.json file, OR you must specify a Web Application `clientId`.
> > Note that this `clientId` parameter is an _override_ of the one that will be injected from your Firebase google-services.json file (if you're using Firebase). See [this comment](https://github.com/flutter/flutter/issues/12140#issuecomment-348720774) for details on how google-services.json is actually used by the build process.
> > The documentation comment for `clientId` that states "Only supported on web" is patently false, and grossly misrepresents what the purpose of this parameter is for.
> > [See the source code of the plugin](https://github.com/flutter/plugins/blob/1a2fbe878d86ee74fc46a422619442d4c5a74945/packages/google_sign_in/google_sign_in/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java#L338-L352) to see how clientId gets used. The `TODO(jackson)` comment in the code about adding an override there was since implemented (on March 18, 2021) - that's what the `clientId` parameter is, but the TODO comment was never removed.
> > [This bit of documentation](https://developers.google.com/identity/sign-in/android/start-integrating#get_your_backend_servers_oauth_20_client_id) about doing Google auth natively in Android explains why the Web Application client ID is needed.
> 
> I got another error (`PlatformException(sign_in_failed, r4.b: 10: , null, null)`) after publishing to Google Play.
> 
> Particularly, at the beginning I got the error `PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)`. Then I followed your instruction to replace the Android Client Id with Web Client Id. Then I built the app bundle and tested the app bundle on my Android device. It works fine. But after I published the app bundle to the Google Play Console, I downloaded the app directly from Google Play and got this error. Any idea? Thanks in advance.

Works for me :), tranks!

**Comment by newtox** [comment]
> @amrit-citrusleaf did you find any solution?
> 
> I am in the same situation. I tried every solution but I still get ApiException: 10.

Yea, same situation here. Been looking for a solution for hours and tried almost everything, anyone told me to try from different sources. Still getting the error.

**Comment by lukehutch** [comment]
The most common cause for this error is that you have stored the wrong SHA-1 key fingerprint in the Google OAurh settings. You can actually store multiple fingerprints there, so store your development, release and Play Store Signing fingerprints just to be safe. (The release fingerprint doesn't really need to be there though, because in general you never run a release build, you just upload it to Play where it is re-signed).

**Comment by fpereiro** [comment]
For those that 1) don't use Firebase; 2) have their own backend; 3) already have the app published in the Play Store, here's what worked for us:

- Do not bother creating an Android OAuth client; just create a **web** OAuth client, and use that client id from your Flutter code.
- Locate the key that you already use to sign your app. If it's not in the repo, put it somewhere in the `android` folder. We put it in `android/app/androidkey`.
- Modify `android/app/build.gradle` as follows:

```
    buildTypes {
        release {
            signingConfig signingConfigs.debug
        }
        debug {
            signingConfig signingConfigs.debug
        }
    }
    signingConfigs {
        debug {
            keyAlias 'REPLACE_ME'
            // Yes, the password is committed, but the key is not.
            keyPassword 'REPLACE_ME'
            storeFile file('androidkey')
            storePassword 'REPLACE_ME'
        }
    }

```

If you replace the keyAlias with the alias of the key, and the key password and store password, you should be good to go, assuming that your key indeed is at `android/app/androidkey`.

If you're concerned about committing your key to your git repository, it seems to be already .gitignored by default.

This was only possible thanks to @ascott18 's [[brilliant observation](https://github.com/flutter/flutter/issues/33393#issuecomment-964728679)], as well as Danial's article [[link](https://medium.danials.space/google-sign-in-in-flutter-without-firebase-bacab8319d49)].

This was a very frustrating experience, but we finally got it working after +12 hours of debugging. Hope the above helps someone.

**Comment by abdullahalamodi** [comment]
using web key for android work for me

**Comment by lukehutch** [comment]
> generating **OAuth client web key** and use it with android platform is work for me.

Yes, that's because the web key doesn't use the app signing key, so there is no SHA1 check.

However, using the web key instead of the Android key exposes your key to being stolen from your app to be used by other apps. This could mean someone else could run up a large bill at your expense.

This exception can be caused by multiple things, but in the most common case, the fix is to make sure you have set the correct SHA1 key fingerprint for your signing key in the Google Cloud Console, under the Maps API. You need at least two SHA1 fingerprints if you have published the app: the fingerprint for your debug key, and the fingerprint for the Play Signing key. After that, you can lock down the key to the Android app.

**Comment by fpereiro** [comment]
Hi @lukehutch , thanks for your comment! I don't understand why you say that using the web key exposes a key that could be stolen to be used by other apps. I believe you're referring to the `clientId` that one gets when creating a new Web OAuth client.

Unless I'm wrong (which I might), this client id *has* to be publicly exposed to make a web OAuth flow to work. Exposing the clientId is not only safe, it is actually required by the OAuth protocol. There should be no safety concern when exposing it, in the same way that there should be no safety concern when exposing the client key of an Android OAuth client.

@lukehutch am I missing something?

**Comment by lukehutch** [comment]
@fpereiro not the client id, I'm talking about the API key.

If someone steals you API key, they can use it in their own app.

Yes, you have to have the API key in your app, so anyone can reverse engineer the app and steal the API key.

That is why Google allows you to restrict the API key on Android and iOS. The Google native libraries do some magic (probably cryptographic signing, I don't know what it is) to ensure that the key is being used in the unmodified app that the developer put it in. On Android, what is checked for a match is the SHA1 fingerprint of the signing key of the app; on iOS, it is the bundle ID of the app.

It's possibly not bulletproof, but it makes it much harder for hackers to run up an expensive Google API bill at your expense.

If you use just a web API key for any Google service (maps, OAuth2, etc.), then people can just steal the API key and start using it. The only way to protect against this is to restrict the web API key based on HTTP referrers, but I suspect this is the easiest mechanism to get around of all, since you could presumably just spoof the HTTP `Referer` header. Also whatever library you use to talk to Google may not have the ability to set the `Referer` header, so unless you are issuing raw HTTPS requests against the Google API endpoint, you may not be able to restrict in this way.

(There is also IP-based restriction, which would be bulletproof but very limiting.)

In other words, more or less, if you use an unrestricted web API key rather than a restricted Android and iOS key, then you have to assume that your key is available for anyone else to steal and use. Will any hacker be sufficiently motivated that they will steal your key? Probably not. But it's a risk.

**Comment by abdullahalamodi** [comment]
> @fpereiro not the client id, I'm talking about the API key.
> 
> If someone steals you API key, they can use it in their own app.
> 
> Yes, you have to have the API key in your app, so anyone can reverse engineer the app and steal the API key.
> 
> That is why Google allows you to restrict the API key on Android and iOS. The Google native libraries do some magic (probably cryptographic signing, I don't know what it is) to ensure that the key is being used in the unmodified app that the developer put it in. On Android, what is checked for a match is the SHA1 fingerprint of the signing key of the app; on iOS, it is the bundle ID of the app.
> 
> It's possibly not bulletproof, but it makes it much harder for hackers to run up an expensive Google API bill at your expense.
> 
> If you use just a web API key for any Google service (maps, OAuth2, etc.), then people can just steal the API key and start using it. The only way to protect against this is to restrict the web API key based on HTTP referrers, but I suspect this is the easiest mechanism to get around of all, since you could presumably just spoof the HTTP `Referer` header. Also whatever library you use to talk to Google may not have the ability to set the `Referer` header, so unless you are issuing raw HTTPS requests against the Google API endpoint, you may not be able to restrict in this way.
> 
> (There is also IP-based restriction, which would be bulletproof but very limiting.)
> 
> In other words, more or less, if you use an unrestricted web API key rather than a restricted Android and iOS key, then you have to assume that your key is available for anyone else to steal and use. Will any hacker be sufficiently motivated that they will steal your key? Probably not. But it's a risk.

thank you for clarify

**Comment by fpereiro** [comment]
Hi @lukehutch , thank you for your clarification! Now indeed I get your point.

I think that in the example above, @abdullahalamodi is using a `clientId`, not a secret key.

```
serverClientId: _webId,
```

We did something similar, with the difference that we used `clientId` === web OAuth client id -- we used this when making the call to authenticate the user from our app to Google's servers.

However, I don't know whether his approach actually involves adding a private key to the app. Our use case requires a server, and that's where we keep our secret keys, never putting them in the app.

But you do raise a great point, which is that if you don't use a server, you might have to bundle your secret key in the app somehow. I'm not sure, however, if that actually happens, whether one uses a backend or not. My understanding was that a secret key was used to sign the app, but not shipped along with it. Nowhere in the instructions I read online it was stated that the secret API key should be bundled somewhere with the app.

What I still don't understand is how something as easy as an OAuth flow can become so complicated. We're still stuck on this and cannot make app bundles that will successfully authenticate with one click in Android.

**Comment by lukehutch** [comment]
You can't authenticate with OAurh with just a client ID. You need an OAuth API key. You set that up in the Cloud Console.

However, let's not distract the discussion here from the error in the original report.

**Comment by fpereiro** [comment]
Hi again. Replying only in the interest of 1) not misunderstanding anything myself (since I haven't gotten this thing to work after all) and 2) not misleading anyone. I'm definitely not trying to "win" an argument -- I'd rather be wrong and learn something.

To the best of my knowledge, the client part of the oauth flow does not require an OAuth API key, only a OAuth client id. Each OAuth client also has a corresponding secret. In our case, we use this secret in the server to verify a login token sent to us by a user trying to authenticate with us (we only need this in the pure web login, not the ones we do with Flutter). From what I've read, serverless OAuth uses the PKCE flow, which also doesn't include client secrets.

Based on the above, I think then that there should be no security concern in using a web client id, as opposed to an android client id. It indeed would be unsafe, however, to put the client secret somewhere in the app, because that would let others impersonate your app, as well as get user data from Google on behalf of your app. But that goes for any client secret, whether it is web or it is android.

**Comment by lukehutch** [comment]
Ok, there must be two different login flows then, because the one I'm using requires an API key.

**Comment by fpereiro** [comment]
Good to know! If that's the case then your warning is very valuable to others who are using the same flow. Thanks for clarifying!

**Comment by lukehutch** [comment]
@fpereiro I went back and double-checked, because it didn't seem right that there would be two different flows, and it turns out you are right, there is no API key for OAuth2, only a client id. I was looking at the wrong entry on the Cloud Console. Everything else I said about locking down access with SHA1 / the bundleId still stands, but I was wrongly referring to the API key. You instead lock down the client id in this way. I will go back and edit my previous comments so that I don't confuse people! Thanks for pointing this out!

**Comment by fpereiro** [comment]
Hi @lukehutch ! Thanks for taking the effort to check, and apologies for the delay in replying.

I just checked whether Android client ids are supposed to be secret, and couldn't find anything to that effect. In the general context of oauth, client ids are never considered secret, but rather a public value [[source](https://www.oauth.com/oauth2-servers/client-registration/client-id-secret/)].

In our case, we tried to use the web client id (successfully for .apks but not for .aabs) to perform the oauth flow. We expose that same web client id for supporting oauth flow against our webapp.

**Comment by vkpandit1137** [comment]
![IMG-20240918-WA0045](https://github.com/user-attachments/assets/c2647bc7-1869-4b79-93b8-985d3be7f5af)
I am also facing an issue like this but here the catch is that it's on release and another catch is that it's working for majority of the people but only a few people are struggling with the error. Can anyone tell me what could be the problem?

**Comment by lukehutch** [comment]
@vkpandit1137 `ERROR, null, null` is different than `ApiException: 10, , null`, so this probably has a different cause. I'm not an expert, but the only thing I can think of is that maybe the handful of users who have the issue are using Gmail on a custom business domain, and the rules may be different there?

@darshankawar can you please triage this through to the Google sign-in team? There need to be much better error messages here. These sorts of issues could be triggered by a wide array of issues (OAuth config, missing/incorrect signing keys, who knows what else...). It is almost impossible to debug what is happening when these exceptions are thrown.

**Comment by InvincibleSihag** [comment]
@darshankawar @vkpandit1137 @lukehutch If you found the solution for this issue. please let us know here. As the production app is being affected and handful of users are reporting the same.

**Comment by trunghieuvn** [comment]
I happened same as issue, I tried fixed and work well for me
https://github.com/googlesamples/google-services/issues/253#issuecomment-2365227410

**Comment by Nde-Dilan** [comment]
I recently ran into the same issue while developing my app. I started off in debug mode and, following the docs, I added the SHA-1 and SHA-256 keys to the Firebase project settings. Everything was working fine so far. But when I switched to the release version to see how my app behaves in that environment, I started encountering errors.

I tried a bunch of different solutions, including directly adding the key to Google Cloud 
![GCP interface to add restrictions to API keys](https://github.com/user-attachments/assets/51e485db-c260-46fa-bb30-efb9807d7885)
, but none of that worked. After some more troubleshooting, I decided to try adding the key back to Firebase's project settings. And to my surprise, that fixed the issue! Now, everything works as expected in both debug and release mode.
 
![Firebase project settings](https://github.com/user-attachments/assets/aca8d237-923f-4969-b167-8dccdfc21cba)
 As you can see I have 4 keys now(2 for debugging and 2 for release)

So, if you're facing similar issues, make sure you've added both SHA-1 and SHA-256 keys to Firebase's project settings. That might just do the trick!

**Comment by lukehutch** [comment]
Right, this is almost always the type of fix that is needed. What needs fixing is the error message, because it gives no indication of what is wrong. We need a Google platform team member to take a look at this issue...

**Comment by Artemoire** [comment]
**No firebase setup**
The following worked for me:
1. Create OAuth Client **of Android type** with signing key given from command `./gradlew signingReport` as stated in other comments
2. Create OAuth Client **of Web type** (redirect uris dont seem to matter)
3. use value of web client id as serverClientId for configuring (clientId empty)

**Side notes**
- After getting it to work with web client, upon inspection of the idToken after getting a successful login, i noticed "azp" field is not my web client id but rather the android client id. 
- I tried recreating the android client to validate the flow works, but it seems google servers (or local data) cache the token by the fingerprint as key, since i kept getting back the old (deleted) OAuth client as "azp" until the token expired. Explicitly setting the clientId to the new one did nothing for me
- Always do flutter run when trying out setup, as I think hot reload doesn't seem to do nothing for the internal state of the GoogleSignIn
- I only need the idToken to identify the user on my backend server, so if this doesn't work for getting google service authorization, sorry

**pubspec.yaml**
```yaml
version: 1.0.0+1
environment:
  sdk: ^3.5.3
  
dependencies:
  google_sign_in: ^6.2.2
```

**Comment by okandemirofficial** [comment]
> I wanted to summarize what I found about this after trawling dozens of other issues about this problem, as well as the problem where idToken comes back as null:
> 
> If you specify a `clientId` parameter to `GoogleSignIn`, **this `clientId` MUST be a clientID of a "Web application" type OAuth2 client created in the GCP console. If you give a `clientId` for any other type of OAuth2 client (e.g. an "Android" client), you'll get error 10.**
> 
> If you do not need an `idToken`, you can omit `clientId`. But if you need a `idToken`, you must either be using the Firebase setup with the google-services.json file, OR you must specify a Web Application `clientId`.
> 
> Note that this `clientId` parameter is an _override_ of the one that will be injected from your Firebase google-services.json file (if you're using Firebase). See [this comment](https://github.com/flutter/flutter/issues/12140#issuecomment-348720774) for details on how google-services.json is actually used by the build process.
> 
> The documentation comment for `clientId` that states "Only supported on web" is patently false, and grossly misrepresents what the purpose of this parameter is for.
> 
> [See the source code of the plugin](https://github.com/flutter/plugins/blob/1a2fbe878d86ee74fc46a422619442d4c5a74945/packages/google_sign_in/google_sign_in/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java#L338-L352) to see how clientId gets used. The `TODO(jackson)` comment in the code about adding an override there was since implemented (on March 18, 2021) - that's what the `clientId` parameter is, but the TODO comment was never removed.
> 
> [This bit of documentation](https://developers.google.com/identity/sign-in/android/start-integrating#get_your_backend_servers_oauth_20_client_id) about doing Google auth natively in Android explains why the Web Application client ID is needed.

It's worked after hours of tries. Thanks!

**Comment by anasmuhmd** [comment]
What I found is that both android and web clients have to be created. (Android key should match the one in playstore app signing or local debug store) and ClientId should be web client key.

**Comment by stuartmorgan** [comment]
Closing as this issue is not actionable; this is a generic error returned from the underlying SDK when there are configuration problems, and can be caused by any number of different issues in either the client or server configuration. The only thing we can do in general is improve the README and API docs about how to configure everything, which there are other issues tracking already.

> can you please triage this through to the Google sign-in team? There need to be much better error messages here

The team that would need to be reported to to is the Android team that owns the relevant SDK, via the standard Android issue reporting mechanisms. At the plugin level, we don't have any information about what the configuration issue is.
