### ISSUE TITLE
Cannot execute operation because FlutterJNI is not attached to native.

### ISSUE THREAD

**Issue by LinXiaoTao** [flutter/flutter#33511]
## Steps to Reproduce

crash devices

<img width="442" alt="4FE97FD6-0A7C-4B20-8862-681B6E174A79" src="https://user-images.githubusercontent.com/19836925/58551410-827a0d00-8242-11e9-9542-0c3fd3770569.png">

## Logs
crash logs

```
io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:597)
--
io.flutter.embedding.engine.FlutterJNI.setSemanticsEnabled(FlutterJNI.java:402)
io.flutter.embedding.engine.systemchannels.AccessibilityChannel.onAndroidAccessibilityEnabled(AccessibilityChannel.java:97)
io.flutter.view.AccessibilityBridge$2.onAccessibilityStateChanged(AccessibilityBridge.java:279)
android.view.accessibility.AccessibilityManager.lambda$notifyAccessibilityStateChanged$0(AccessibilityManager.java:1152)
android.view.accessibility.-$$Lambda$AccessibilityManager$yzw5NYY7_MfAQ9gLy3mVllchaXo.run(Unknown Source:4)
android.os.Handler.handleCallback(Handler.java:891)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:207)
android.app.ActivityThread.main(ActivityThread.java:7470)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

flutter doctor -v

```
[✓] Flutter (Channel unknown, v1.6.0, on Mac OS X 10.14.2 18C54, locale
    zh-Hans-CN)
    • Flutter version 1.6.0 at /Users/leo/Documents/flutter
    • Framework revision ed90d05596 (2 weeks ago), 2019-05-14 17:09:29 -0700
    • Engine revision 832cdacc6f
    • Dart version 2.3.1 (build 2.3.1-dev.0.0 a0290f823c)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/leo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    ✗ CocoaPods installed but not initialized.
        CocoaPods is used to retrieve the iOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work
        on iOS.
        For more info, see https://flutter.dev/platform-plugins
      To initialize CocoaPods, run:
        pod setup
      once to finalize CocoaPods' installation.

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 191.6183.88
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.2

[✓] Connected device (1 available)
    • BLN AL10 • UEUDU17221002776 • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 2 categories.
```

**Comment by icecreamco** [comment]
I have a same problem, hope to fixed it quickly~

**Comment by fightingalso** [comment]
我也有同样的问题，怎么解决啊？

**Comment by LinXiaoTao** [comment]
maybe you can consider using aspectjx to add judgment to the relevant code.

**Comment by hahafather007** [comment]
I have a same problem, hope to fixed it quickly~

**Comment by hahafather007** [comment]
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.7.8+hotfix.4-pre.5, on Mac OS X 10.14.6 18G87,
    locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Community Edition (version 2018.2.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by RootKatherine** [comment]
I have a same problem, hope to fixed it quickly~

**Comment by LinXiaoTao** [comment]
use [aspect framework](https://github.com/HujiangTechnology/gradle_plugin_android_aspectjx)

``` java
@Keep
@Aspect
public class FixFlutterJNI {

    @Pointcut("target(io.flutter.embedding.engine.FlutterJNI)")
    public void targetFlutterJNI() {

    }

    @Pointcut("targetFlutterJNI() && execution(void ensureAttachedToNative())")
    public void executionEnsureAttachedToNative() {

    }

    @Around("executionEnsureAttachedToNative()")
    public Object checkExecutionEnsureAttachedToNative(ProceedingJoinPoint joinPoint) throws Throwable {

        boolean isAttached = isAttached(joinPoint.getThis());

        if (!isAttached) {
            // not attach
            // 参考 FlutterJNI 的处理方法
            Log.w("FlutterJNI", "Tried to ensureAttachedToNative, but FlutterJNI was detached from native C++. Could not ensureAttachedToNative.");
            return null;
        }

        return joinPoint.proceed(joinPoint.getArgs());

    }


    private static boolean isAttached(Object thisObj) {

        try {
            return (boolean) thisObj.getClass().getDeclaredMethod("isAttached").invoke(thisObj);
        } catch (Throwable throwable) {
            throwable.printStackTrace();
        }

        return true;
    }


}
```

**Comment by chenqingfeid** [comment]
I not add 

`GeneratedPluginRegistrant.registerWith(this);`

Whether it has anything to do with him

**Comment by xmc123456** [comment]
I have a same problem, hope to fixed it quickly~

**Comment by MrLittleStrong** [comment]
Same issue. What is the status now?

**Comment by erickcchoi** [comment]
I have the save issue, it always happen in "Huawei" devices.

**Comment by Nikiezi** [comment]
Same issue. It always happens on huawei & android9.0 phones. What is the status now?

**Comment by qq326646683** [comment]
same issue
<img width="948" alt="android_crash" src="https://user-images.githubusercontent.com/15717688/67459294-cb57b580-f66a-11e9-8870-6e7ac0778a22.png">

**Comment by jp1017** [comment]
same issue: 

![image](https://user-images.githubusercontent.com/7868514/67731791-4ab30380-fa34-11e9-9df5-2c05992d900d.png)

**Comment by hahafather007** [comment]
I found this crash happened on "Huawei" with Android9 only.
![4B5B76DE-4F5F-4D11-AC6B-EA4CB458EC93](https://user-images.githubusercontent.com/23414420/67755488-37735880-fa73-11e9-8c2e-8fa91f210b43.png)
```
java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
    at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:2)
    at io.flutter.embedding.engine.FlutterJNI.setSemanticsEnabled(FlutterJNI.java:2)
    at io.flutter.embedding.engine.systemchannels.AccessibilityChannel.onAndroidAccessibilityDisabled(AccessibilityChannel.java:1)
    at io.flutter.view.AccessibilityBridge$2.onAccessibilityStateChanged(AccessibilityBridge.java:4)
    at android.view.accessibility.AccessibilityManager.lambda$notifyAccessibilityStateChanged$0(AccessibilityManager.java:1157)
    at android.view.accessibility.-$$Lambda$AccessibilityManager$yzw5NYY7_MfAQ9gLy3mVllchaXo.run(Unknown Source:4)
    at android.os.Handler.handleCallback(Handler.java:907)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:216)
    at android.app.ActivityThread.main(ActivityThread.java:7625)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Comment by jp1017** [comment]
@hahafather007  @Nikiezi @LinXiaoTao 1.9.1的sdk我测试没问题，试下

**Comment by LinXiaoTao** [comment]
@jp1017 我已经自己解决了，看下抛异常的代码有没有处理就可以了

**Comment by jp1017** [comment]
嗯嗯，很强！我的是进入flutter页面就崩，需要改sdk版本 @LinXiaoTao

**Comment by xster** [comment]
Can someone share an exact set of repro steps we can follow? 

Are these on x86 devices?

**Comment by jp1017** [comment]
> Are these on x86 devices?

None of theses phones are x86, some Huawei phones makes this issue.

**Comment by LinXiaoTao** [comment]
@xster no rules were found, which were found in the logs reported by our customers' mobile phones.

**Comment by LinXiaoTao** [comment]
@xster what is certain is that Huawei mobile phones are currently

**Comment by MrLittleStrong** [comment]
> @jp1017 我已经自己解决了，看下抛异常的代码有没有处理就可以了

This solution seems only solved the Exception. Can it make Flutter JNI attached to native?

**Comment by LinXiaoTao** [comment]
@MrLittleStrong No, but this has solved the problem.

**Comment by erickcchoi** [comment]
Please advice, How to solve the problem?

**Comment by ParadiseHell** [comment]
I maybe found what causes the exception.
First, let's see code in **FlutterJNI**:
```java
  private void ensureAttachedToNative() {
    if (this.nativePlatformViewId == null) {
      throw new RuntimeException("Cannot execute operation because FlutterJNI is not attached to native.");
    }
  }
```
You can see, the only reason cause the execption is `nativePlatformViewId == null`.
And Who creates **FlutterJNI**? It's **FlutterNativeView** :
```java
  public FlutterNativeView(@NonNull Context context, boolean isBackgroundView) {
    ...
    this.mFlutterJNI = new FlutterJNI();
    ...
    this.attach(this, isBackgroundView);
    ...
  }
```
Let's see the method **attach**:
```java
  private void attach(FlutterNativeView view, boolean isBackgroundView) {
    this.mFlutterJNI.attachToNative(isBackgroundView);
    ...
  }
```
Now, let's see the method **attachToNative**:
```java
  public void attachToNative(boolean isBackgroundView) {
    ...
    this.nativePlatformViewId = this.nativeAttach(this, isBackgroundView);
  }
````
So from the codes above, we can know **nativePlatformViewId** **CANNOT** be null when the **FlutterJNI** instance once be created.

So who makes **nativePlatformViewId** to be null? **FlutterJNI** itself, let's see the method **detachFromNativeAndReleaseResources**:
```java
  public void detachFromNativeAndReleaseResources() {
    ...
    this.nativePlatformViewId = null;
  }
```
And it's **THE ONLY PLACE** where **nativePlatformViewId** can be null.

So Why the SDK called **detachFromNativeAndReleaseResources** and still call ** setSemanticsEnabled** which will call **ensureAttachedToNative** to make such exeption.

I think SDK should have a flag to mark if FlutterJNI is detached.

The solutions I can figure out are **Hook Method** and **AOP**, but I don't think it's a good way, by the way, I don't know **Hook Method** and **AOP**.

**Comment by ParadiseHell** [comment]
[LinXiaoTao's isuue](https://github.com/flutter/flutter/issues/33511#issuecomment-530681593) may fix the problem, but I have not tried to confirm it.

**Comment by ParadiseHell** [comment]
I have tried @LinXiaoTao 's way, it just works.
So I will some detail configure:

In the **Project** build.gradle add the classpath
```
classpath 'com.github.franticn:gradle_plugin_android_aspectjx:2.0.6'
```

In the **module** build.gradle which you write your aspectj code:

```gradle
apply plugin: 'android-aspectjx'
....
aspectjx {
  enabled = true
  include "io.flutter.embedding.engine"
}
....
dependencies {
....
}
```
Finnaly, copy [LinXiaoTao's code](https://github.com/flutter/flutter/issues/33511#issuecomment-530681593) to your module.

So it will work, and if you doubt you can just have a look at the **FlutterJNI**'s bytecode using your debug APK.

**Comment by fauzipadlaw** [comment]
I don't get it, I just got this issue from my google play store console crash reports. Anyone explain the steps to solve it? pls

**Comment by ParadiseHell** [comment]
> I don't get it, I just got this issue from my google play store console crash reports. Anyone explain the steps to solve it? pls

To fix this crash, we need to modify **FlutterJNI**'s byte code, [AOP](https://en.wikipedia.org/wiki/Aspect-oriented_programming) is one of the solutions to make it. 

The following is the detail steps using [HujiangTechnology/gradle_plugin_android_aspectjx](https://github.com/HujiangTechnology/gradle_plugin_android_aspectjx):

1. Add classpath to the **Root Project**'s build.gradle :
```gradle
buildscript {
    repositories {
        ...
        // it seems you have to add this maven because the plugin is pushed in jitpack
        maven { url "https://jitpack.io" }
        ...
    }
    dependencies {
         // AOP classpath
        classpath 'com.github.franticn:gradle_plugin_android_aspectjx:2.0.6'
        ...
    }
}
```
2. Create a file (any name is ok, I use FlutterAspect) to in your **app module** to fix the crash :
```java
@Aspect
public final class FlutterAspect {
  @Pointcut("target(io.flutter.embedding.engine.FlutterJNI)")
  public void targetFlutterJNI() {
  }

  @Pointcut("targetFlutterJNI() && execution(void ensureAttachedToNative())")
  public void executionEnsureAttachedToNative() {
  }

  @Around("executionEnsureAttachedToNative()")
  public Object checkExecutionEnsureAttachedToNative(ProceedingJoinPoint joinPoint)
      throws Throwable {
    boolean isAttached = isAttached(joinPoint.getThis());
    if (!isAttached) {
      return null;
    }
    return joinPoint.proceed(joinPoint.getArgs());
  }

  private static boolean isAttached(Object thisObj) {
    try {
      return (boolean) thisObj.getClass().getDeclaredMethod("isAttached").invoke(thisObj);
    } catch (Throwable throwable) {
      throwable.printStackTrace();
    }
    return true;
  }
}
```
3. Config Aspect in your **app module**'s build.gradle :
```gradle
apply plugin: 'android-aspectjx'
....
aspectjx {
  // default is true
  enabled = true
  // include FlutterJNI package path
  include "io.flutter.embedding.engine"
}
....
dependencies {
....
}
```

That's all.

Check whether it makes it.
1. Build Project.
2. Build a debug APK.
3. Analyze APK(Android Studio : Build --> Analyze APK).
4. Find **FlutterJNI**'s byte code in all **.dex** files.
5. Check **FlutterJNI**'s method **ensureAttachedToNative** in the **FlutterJNI**'s byte code whether it changes.

**Comment by fauzipadlaw** [comment]
@ParadiseHell i got this error when trying to run the app

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:javaPreCompileDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Failed to transform file 'libs.jar' to match attributes {artifactType=android-classes, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}
      > Execution failed for JetifyTransform: E:\elxr\v12\elxr_mobile\build\app\intermediates\flutter\debug\libs.jar.
         > Failed to transform 'E:\elxr\v12\elxr_mobile\build\app\intermediates\flutter\debug\libs.jar' using Jetifier. Reason: Cannot open a library at 'FileMapping(from=E:\elxr\v12\elxr_mobile\build\app\intermediates\flutter\debug\libs.jar, to=C:\Users\fauzi\.gradle\caches\transforms-2\files-2.1\9ca15f2d300cf336a363a520c0b2e836\jetified-libs.jar)'. (Run with --stacktrace for more details.)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Finished with error: Gradle task assembleDebug failed with exit code 1
```

**Comment by ParadiseHell** [comment]
@fauzipadlaw 
When I search JetifyTransform, I found some AndroidX results, so I don't know whether it has reference to AndroidX if you use AndroidX.

**Comment by sanekyy** [comment]
Same issue.

![image](https://user-images.githubusercontent.com/18647037/73829964-e82c8900-4814-11ea-8338-5ed017137e0f.png)

**Comment by edukun** [comment]
I have had the same issue when pressing back button while loading the app with a library using JNI. Aspect framework solution didn't work because of JetifyTransform error. 

The only solution that works for me is the one posted here: https://github.com/flutter/flutter/issues/48063#issuecomment-581124422

In Android MainActivity.kt, just add this:
`    override fun onDestroy() {
        flutterEngine?.platformViewsController?.onFlutterViewDestroyed()
        super.onDestroy()
    }`

Just to ensure that FlutterRenderer method release() is invoked

**Comment by xster** [comment]
@jason-simmons would you like to take a swing at this one? Hard to tell what it is since there's no repro. From the screenshots, I'm only seeing Huawei, Honor (still Huawei) and Asus. Maybe some OEM tweaks on how native library loading works?

**Comment by xster** [comment]
Not related but looking at https://github.com/flutter/flutter/issues/47164, there are definitely odds that there are OEM specific behaviors going on.

**Comment by kw2019ltd** [comment]
same issue 

Fatal Exception: java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
       at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:227)
       at io.flutter.embedding.engine.FlutterJNI.setSemanticsEnabled(FlutterJNI.java:513)
       at io.flutter.embedding.engine.systemchannels.AccessibilityChannel.onAndroidAccessibilityDisabled(AccessibilityChannel.java:110)
       at io.flutter.view.AccessibilityBridge$2.onAccessibilityStateChanged(AccessibilityBridge.java:291)
       at android.view.accessibility.AccessibilityManager.lambda$notifyAccessibilityStateChanged$0(AccessibilityManager.java:1157)
       at android.view.accessibility.-$$Lambda$AccessibilityManager$yzw5NYY7_MfAQ9gLy3mVllchaXo.run(:4)
       at android.os.Handler.handleCallback(Handler.java:907)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by riswanmsm** [comment]
The same error occurs while using webview_flutter plugin

error
java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.

flutter version
Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.14393], locale en-US)

**Comment by ahmedthinkdifferent** [comment]
> override fun onDestroy() { flutterEngine?.platformViewsController?.onFlutterViewDestroyed() super.onDestroy() }

this is worked for me.
Thanks  @edukun

**Comment by sanekyy** [comment]
Again and again

![image](https://user-images.githubusercontent.com/18647037/76698003-da3d1400-66ae-11ea-8926-3871ffc0a2dc.png)

**Comment by sanekyy** [comment]
It happens when user hide application, use other apps some time and show app back

**Comment by kw2019ltd** [comment]
same getting this issue on different users 


Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/kw.ltd.instagram_app-m43sOhh5ZWkdavhNRJGoIQ==/base.apk"],nativeLibraryDirectories=[/data/app/kw.ltd.instagram_app-m43sOhh5ZWkdavhNRJGoIQ==/lib/arm, /system/lib, /system/vendor/lib]]] couldn't find "libflutter.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
       at java.lang.System.loadLibrary(System.java:1657)
       at io.flutter.embedding.engine.loader.FlutterLoader.startInitialization(FlutterLoader.java:122)
       at io.flutter.embedding.engine.loader.FlutterLoader.startInitialization(FlutterLoader.java:93)
       at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:45)
       at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1127)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6097)
       at android.app.ActivityThread.-wrap1()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1791)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:7000)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)


![image](https://user-images.githubusercontent.com/47334522/76699211-f55e5280-66b3-11ea-94a3-5ad3f6a4da92.png)

**Comment by l8023lxb** [comment]
I find the root cause.
 &nbsp;&nbsp;&nbsp;AccessibilityManager.notifyAccessibilityStateChanged() use post to call listener.onAccessibilityStateChanged(),if post and FlutterEngine.destroy() occur at the same time,it may be `post->FlutterEngine.destroy->FlutterJNI.nativePlatformViewId=null->listener.onAccessibilityStateChanged()`,and app will crash with FlutterJNI.ensureAttachedToNative.
&nbsp;&nbsp;&nbsp;For safety reasons,Huawei will close Accessibility when app quit completely.If phone low memory and try to kill some background app,onAccessibilityStateChanged and FlutterEngine.destroy will occur at the same time ,this will greatly increase the probability of crash.
&nbsp;&nbsp;&nbsp;If you usesdk ,you can remove AccessibilityListener when flutterview attach by reflection,if you use sourcecode,you can modify as [this(https://github.com/flutter/engine/pull/17311/commits)

**Comment by h4rdw1r3** [comment]
> I have had the same issue when pressing back button while loading the app with a library using JNI. Aspect framework solution didn't work because of JetifyTransform error.
> 
> The only solution that works for me is the one posted here: [#48063 (comment)](https://github.com/flutter/flutter/issues/48063#issuecomment-581124422)
> 
> In Android MainActivity.kt, just add this:
> ` override fun onDestroy() { flutterEngine?.platformViewsController?.onFlutterViewDestroyed() super.onDestroy() }`
> 
> Just to ensure that FlutterRenderer method release() is invoked

This fixed the issue.

**Comment by tomrozb** [comment]
I had the same issue with page that displays map with google_maps_flutter.

Repro steps:
- create simple page with a map e.g. take the sample code from google_maps_flutter
- start that page as a FlutterActivity from native Android code
```
            startActivity(
                FlutterActivity
                    .withNewEngine()
                    .initialRoute("/map")
                    .build(this)
            )
```
- click back
- start the activity again
- crash

It doesn't happen when you remove the map from your flutter page.

**Comment by FacuRossi** [comment]
same issue. using the camera plugin.
the devices are samsung and xiaomi. 
![image](https://user-images.githubusercontent.com/21088004/78940680-a5916200-7a8c-11ea-9809-0b30a30afa34.png)

any update on this?

**Comment by Sreejith93** [comment]
> > override fun onDestroy() { flutterEngine?.platformViewsController?.onFlutterViewDestroyed() super.onDestroy() }
> 
> this is worked for me.
> Thanks @edukun

where to put this code please show after paste the mainactivity.kt file

**Comment by edukun** [comment]
Just inside the MainActivity class, in MainActivity.kt, below configureFlutterEngine

**Comment by kw2019ltd** [comment]
How this help iam getting this issue on app startup

**Comment by KurdAppDev** [comment]
in my case uninstall and install solved!

**Comment by NaikSoftware** [comment]
App always crashed after exit with `flutter_youtube_view` plugin.

**Comment by GaryQian** [comment]
We have recently landed a change (https://github.com/flutter/engine/pull/17897) that resolves a crash with views for plugins, can someone try with master channel and see if this is resolved as well? It seems possibly connected.

**Comment by kw2019ltd** [comment]
hi
getting below issue with Flutter (Channel unknown, v1.17.1)


Fatal Exception: java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
       at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:222)
       at io.flutter.embedding.engine.FlutterJNI.markTextureFrameAvailable(FlutterJNI.java:543)
       at io.flutter.embedding.engine.renderer.FlutterRenderer.markTextureFrameAvailable(FlutterRenderer.java:295)
       at io.flutter.embedding.engine.renderer.FlutterRenderer.access$300(FlutterRenderer.java:35)
       at io.flutter.embedding.engine.renderer.FlutterRenderer$SurfaceTextureRegistryEntry$1.onFrameAvailable(FlutterRenderer.java:141)
       at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:203)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

image

$ flutter doctor -v
[✓] Flutter (Channel unknown, v1.17.1, on Linux, locale en_US.UTF-8)
• Flutter version 1.17.1 at /home/cirrus/sdks/flutter
• Framework revision f7a6a79 (3 days ago), 2020-05-12 18:39:00 -0700
• Engine revision 6bc433c6b6
• Dart version 2.8.2
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
• Android SDK at /opt/android-sdk-linux
• Platform android-29, build-tools 29.0.2
• ANDROID_HOME = /opt/android-sdk-linux
• ANDROID_SDK_ROOT = /opt/android-sdk-linux
• Java binary at: /usr/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[!] Android Studio (not installed)
• Android Studio not found; download from https://developer.android.com/studio/index.html
(or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
[!] Connected device
! No devices available
! Doctor found issues in 3 categories

**Comment by bnxm** [comment]
@GaryQian I just tested it and indeed it works for me. Thanks for the fix!

**Comment by kw2019ltd** [comment]
Can we add the fix to 1.17 flutter as hotfix

**Comment by guilhermeagostinelli** [comment]
@GaryQian tried on master branch and unfortunately the crash keeps happening

**Comment by guilhermeagostinelli** [comment]
> I have had the same issue when pressing back button while loading the app with a library using JNI. Aspect framework solution didn't work because of JetifyTransform error.
> 
> The only solution that works for me is the one posted here: [#48063 (comment)](https://github.com/flutter/flutter/issues/48063#issuecomment-581124422)
> 
> In Android MainActivity.kt, just add this:
> ` override fun onDestroy() { flutterEngine?.platformViewsController?.onFlutterViewDestroyed() super.onDestroy() }`
> 
> Just to ensure that FlutterRenderer method release() is invoked

Not working for me on Flutter v1.7.1
Is there a workaround?

**Comment by byshy** [comment]
this is not only on huawei devices, I got same error on a s20 ultra

![Annotation 2020-05-31 162756](https://user-images.githubusercontent.com/33957976/83353660-c4112c80-a35c-11ea-86b7-0d494379120f.png)

**Comment by singun-lxd** [comment]
> We have recently landed a change ([flutter/engine#17897](https://github.com/flutter/engine/pull/17897)) that resolves a crash with views for plugins, can someone try with master channel and see if this is resolved as well? It seems possibly connected.

@GaryQian I'm using Flutter v1.17.2, this crash still exists

> 1	io.flutter.embedding.engine.FlutterJNI.void ensureAttachedToNative()(SourceFile:2)
2	io.flutter.embedding.engine.FlutterJNI.void markTextureFrameAvailable(long)(SourceFile:2)
3	io.flutter.embedding.engine.renderer.FlutterRenderer.void markTextureFrameAvailable(long)(SourceFile:1)
4	io.flutter.embedding.engine.renderer.FlutterRenderer.access$300(SourceFile:1)
5	io.flutter.embedding.engine.renderer.FlutterRenderer$SurfaceTextureRegistryEntry$1.void onFrameAvailable(android.graphics.SurfaceTexture)(SourceFile:2)
6	android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:203)
7	android.os.Handler.dispatchMessage(Handler.java:102)
8	android.os.Looper.loop(Looper.java:158)
9	android.app.ActivityThread.main(ActivityThread.java:7230)
10	java.lang.reflect.Method.invoke(Native Method)
11	com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
12	com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by YuriOliveiraAbel** [comment]
same issue with v1.17.4, detected on dashboard in play store

**Comment by AlexMV12** [comment]
> We have recently landed a change ([flutter/engine#17897](https://github.com/flutter/engine/pull/17897)) that resolves a crash with views for plugins, can someone try with master channel and see if this is resolved as well? It seems possibly connected.

Unfortunately, the crash still happens also on Beta (master doesn't wort at the moment).

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.19.0-4.2.pre, on Linux, locale it_IT.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 4.0)
[!] IntelliJ IDEA Community Edition (version 2019.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)
```

As mentioned by @tomrozb, I have the crash with the GMaps plugin. However, with the Beta channel the log is quite different:
```
2020-06-30 00:55:32.310 19574-19574/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dima.alga, PID: 19574
    java.lang.RuntimeException: Unable to destroy activity {com.dima.alga/com.dima.alga.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.maps.api.android.lib6.impl.bp.q()' on a null object reference
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4963)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4992)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2022)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:359)
        at android.app.ActivityThread.main(ActivityThread.java:7418)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.maps.api.android.lib6.impl.bp.q()' on a null object reference
        at com.google.maps.api.android.lib6.impl.cw.d(:com.google.android.gms.dynamite_mapsdynamite@201215083@20.12.15 (120408-0):1)
        at com.google.android.gms.maps.internal.q.a(:com.google.android.gms.dynamite_mapsdynamite@201215083@20.12.15 (120408-0):12)
        at ch.onTransact(:com.google.android.gms.dynamite_mapsdynamite@201215083@20.12.15 (120408-0):4)
        at android.os.Binder.transact(Binder.java:914)
        at com.google.android.gms.internal.maps.zza.zzb(Unknown Source:20)
        at com.google.android.gms.maps.internal.zzk.onDestroy(Unknown Source:26)
        at com.google.android.gms.maps.MapView$zza.onDestroy(Unknown Source:34)
        at com.google.android.gms.dynamic.DeferredLifecycleHelper.onDestroy(com.google.android.gms:play-services-base@@17.2.1:71)
        at com.google.android.gms.maps.MapView.onDestroy(Unknown Source:40)
        at io.flutter.plugins.googlemaps.GoogleMapController.dispose(GoogleMapController.java:474)
        at io.flutter.plugin.platform.VirtualDisplayController.dispose(VirtualDisplayController.java:171)
        at io.flutter.plugin.platform.PlatformViewsController.flushAllViews(PlatformViewsController.java:532)
        at io.flutter.plugin.platform.PlatformViewsController.onDetachedFromJNI(PlatformViewsController.java:421)
        at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:296)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:500)
        at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:576)
        at android.app.Activity.performDestroy(Activity.java:8048)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1342)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4948)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4992) 
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2022) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:359) 
        at android.app.ActivityThread.main(ActivityThread.java:7418) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

With the Stable channel, the crash, which happened at the very same moment, was:
```
2020-06-30 00:31:45.604 16370-16370/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dima.alga, PID: 16370
    java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
        at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:222)
        at io.flutter.embedding.engine.FlutterJNI.markTextureFrameAvailable(FlutterJNI.java:543)
        at io.flutter.embedding.engine.renderer.FlutterRenderer.markTextureFrameAvailable(FlutterRenderer.java:295)
        at io.flutter.embedding.engine.renderer.FlutterRenderer.access$300(FlutterRenderer.java:35)
        at io.flutter.embedding.engine.renderer.FlutterRenderer$SurfaceTextureRegistryEntry$1.onFrameAvailable(FlutterRenderer.java:141)
        at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:211)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:359)
        at android.app.ActivityThread.main(ActivityThread.java:7418)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

Hope it can help.

**Comment by yikekunkun** [comment]
https://github.com/flutter/flutter/issues/33511#issuecomment-651413090 same issue.
hope to fixed it quickly~

**Comment by yikekunkun** [comment]
@AlexMV12 please help me >_<

**Comment by AlexMV12** [comment]
> @AlexMV12 please help me >_<

I am sorry man, I am not a Flutter developer. In my case the crash happened only if you opened and closed very fast the GMaps screen, so it's tollerable. Let's follow the bug and see if it gets solved.

**Comment by Augustinekan** [comment]
Mine occurs when i add the flutter_admob plugin , mainly on Samsung and Huawei phones plus devices on Android 9 and 10. Has anybody found a permanent fix?

**Comment by guilhermeagostinelli** [comment]
This PR (https://github.com/flutter/engine/pull/19558) by GaryQian seems to solve the problem. For those experiencing the `markTextureFrameAvailable` version of the crash, please try it again on `master` channel.

**Comment by uzumaki258** [comment]
I have faced this issue with HUAWEI device.

**Comment by GaryQian** [comment]
@uzumaki258 Have you tried on master or dev channels? We have since fixed 3 versions of the JNI crash

I have recently closed https://github.com/flutter/flutter/issues/28651 which this bug seems to be a subset of the issues reported there. We have landed 3 fixes for various reported forms of this crash. Please verify that the crash is no longer occurring on master or dev channels please :)

**Comment by LuisCalderonAchio** [comment]
I had this issue using [admob_flutter](https://pub.dev/packages/admob_flutter), I then tested using master channel and it seems fixed now.

**Comment by Heipi** [comment]
I encountered this problem when Using the HUAWEI P30 Android 10 device (Android + Flutter). When I switched to the background, it would appear when I clicked the app

**Comment by GaryQian** [comment]
@Heipi please try with the master channel, I do believe we have fixed the 3 bugs reported here.

I will close this issue for now to make that more clear, but please don't hesitate to report any new versions of this issue. If you are still seeing it, please try on master channel to see if it is fixed before reporting it!

**Comment by jensencelestial** [comment]
Is the fix included in 1.20 release?

**Comment by Heipi** [comment]
> Is the fix included in 1.20 release?
I try master channel，when I  int the method “cleanUpFlutterEngine” destroy the engine, the error still happen， If  don't destroy it，not the error

**Comment by PreviousTlx** [comment]
I have faced this issue with HUAWEI device.
In Activity the code like that:
  flutterView.detachFromFlutterEngine();
            if (flutterEngine != null) {
                flutterEngine.getLifecycleChannel().appIsDetached();
                flutterEngine.getPlatformViewsController().onFlutterViewDestroyed();
                flutterEngine.destroy();
                flutterEngine = null;

            }
            nativeChannel.setMethodCallHandler(null);
            flutterView = null;
            nativeChannel = null;
--end
flutter doctor
Flutter (Channel stable, v1.17.5, on Mac OS X 10.14.5 18F132)

**Comment by PreviousTlx** [comment]
Is the fix included in 1.20 release?

**Comment by z234009184** [comment]
the same  flutter version 1.20.1 stable

**Comment by kw2019ltd** [comment]
why flutter team not able to solve it,  pls escalate this issue

**Comment by PreviousTlx** [comment]
> I have the save issue, it always happen in "Huawei" devices.

It always happen in "Vivo" devices

**Comment by SebAubin** [comment]
I get this error:

``` [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.UnsatisfiedLinkError: Can't obtain class com.sun.jna.Pointer
08-13 14:35:59.628 20513 20513 E flutter : 	at com.sun.jna.Native.initIDs(Native Method)
08-13 14:35:59.628 20513 20513 E flutter : 	at com.sun.jna.Native.<clinit>()
08-13 14:35:59.628 20513 20513 E flutter : 	at com.sun.jna.Native.a()
08-13 14:35:59.628 20513 20513 E flutter : 	at h.a.a.d.<clinit>()
08-13 14:35:59.628 20513 20513 E flutter : 	at h.a.a.g.<init>()
08-13 14:35:59.628 20513 20513 E flutter : 	at net.devolutions.authenticator.MainActivity.d()
08-13 14:35:59.628 20513 20513 E flutter : 	at net.devolutions.authenticator.MainActivity$b.a()
08-13 14:35:59.628 20513 20513 E flutter : 	at e.a.c.a.k$a.a()
08-13 14:35:59.628 20513 20513 E flutter : 	at io.flutter.embedding.engine.b.b.a()
08-13 14:35:59.628 20513 20513 E flutter : 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage()
08-13 14:35:59.628 20513 20513 E flutter : 	at android.os.MessageQueue.nativePollOnce(Native Method)
08-13 14:35:59.628 20513 20513 E flutter : 	at android.os.MessageQueue.next(MessageQueue.java:323)
08-13 14:35:59.628 20513 20513 E flutter : 	at android.os.Looper.loop(Looper.java:136)
08-13 14:35:59.628 20513 20513 E flutter : 	at android.app.ActivityThread.main(ActivityThread.java:6682)
08-13 14:35:59.628 20513 20513 E flutter : 	at java.lang.reflect.Method.invoke(Native Method)
08-13 14:35:59.628 20513 20513 E flutter : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
08-13 14:35:59.628 20513 20513 E flutter : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
08-13 14:35:59.628 20513 20513 E flutter :
08-13 14:35:59.628 20513 20513 F flutter : [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env).
08-13 14:35:59.629 20513 20513 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 20513 (s.authenticator)```

Seems to be related even though it's not EXACTLY the same error as you guys

**Comment by IamGiel** [comment]
any update here?

**Comment by kbrmimbyl** [comment]
Here's some info if it helps. When is the fix expected?

89% Vivo
97% Android 10
99% Background

![Screenshot from 2020-12-19 11-11-59](https://user-images.githubusercontent.com/15169779/102681917-5854bb00-41eb-11eb-80ea-b03e67c8dbf0.png)

**Comment by kbrmimbyl** [comment]
3 Months and no update from Google on this... disappointing!
