### ISSUE TITLE
Could not open library '/data/app/... .../lib/arm64/libapp.so' due to error 'dlopen failed: missing PT_DYNAMIC in "/data/app/... .../lib/arm64/libapp.so"

### ISSUE THREAD

**Issue by Lolingew** [flutter/flutter#34308]
## Steps to Reproduce

before steps followed, i run "flutter upgrade" and get a new version flutter of master channel.

1. add flutter module to existing android app, and i have run debug mode well. all features work.
2. change all build variants of android app to RELEASE
3. run "flutter build apk --release". (i was surprised to see that armeabi-v7a and arm64-v8a can be both built in one apk! that's great!)
4. but when i run my android app and just the time i enter flutter view, app crashed. i also tried run flutter module independently and also get the same result. the following logs' error output is mostly same.

the point error message is: 

[  +61 ms] E/flutter ( 4911): [ERROR:flutter/fml/platform/posix/native_library_posix.cc(16)] Could not open library '/data/app/com.ccbscf.ccbscf_module_flutter.host-1/lib/arm64/libapp.so' due to error 'dlopen
failed: missing PT_DYNAMIC in "/data/app/com.ccbscf.ccbscf_module_flutter.host-1/lib/arm64/libapp.so"'.
[   +3 ms] E/flutter ( 4911): [ERROR:flutter/fml/platform/posix/native_library_posix.cc(16)] Could not open library '/data/app/com.ccbscf.ccbscf_module_flutter.host-1/lib/arm64/libapp.so' due to error 'dlopen
failed: missing PT_DYNAMIC in "/data/app/com.ccbscf.ccbscf_module_flutter.host-1/lib/arm64/libapp.so"'.

## Logs

https://gist.github.com/tvolkert/52f2f2e9986f0f7d1e5f802fd97bc66c

**Comment by Lolingew** [comment]
add a new state, i return to build a debug, but i can't build an independent debug apk...
yes, debug failed, too.

PS D:\work\Codes\ccbscf_module_flutter> flutter run --debug
Launching lib/main.dart on OS105 in debug mode...
Initializing gradle...                                              1.8s
Resolving dependencies...                                          17.6s

FileSystemException: Cannot open file, path = 'build\app.dill' (OS Error: 系统找不到指定的文件�?
, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:364:9)
#1      _rootRunUnary (dart:async/zone.dart:1132:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:483:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)


FAILURE: Build failed with an exception.

* Where:
Script 'D:\software\Android\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 712

* What went wrong:
Execution failed for task ':flutter:compileflutterBuildDebugArm64'.
> Process 'command 'D:\software\Android\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        11.3s
Gradle task assembleDebug failed with exit code 1

**Comment by tvolkert** [comment]
Labeling as TODAY to block a dev release until this is at least triaged.

**Comment by xster** [comment]
Tentatively assigning to @blasten to assess severity

**Comment by blasten** [comment]
My first impression is that it seems the lib headers got corrupted. I will update the thread as I find out more. cc @jason-simmons

**Comment by blasten** [comment]
It looks like this issue may have been fixed by https://github.com/flutter/flutter/pull/34250. The problem is that in add to app cases, [this configuration](https://github.com/flutter/flutter/blob/d9c19629737e8b3a7c29041c22f353eeae7ac20f/packages/flutter_tools/gradle/flutter.gradle#L188)  doesn't affect the packaging options of the host app, but now we strip the debugging symbols earlier in the pipeline.

@Lolingew would you mind running `flutter upgrade` on the master branch and trying again?

**Comment by blasten** [comment]
One update, I was able to reproduce this issue in master.

This is the workaround. If you add the following:

```gradle
android {
  packagingOptions {
    // Prevent the ELF library from getting corrupted.
    doNotStrip "*/arm64-v8a/libapp.so"
    doNotStrip "*/armeabi-v7a/libapp.so"
  }
}
```

to your app's `build.gradle` then the issue is fixed.

**Comment by rmacnak-google** [comment]
Strip messes up the segment containing the program header table. It moves the table and changes its size so that it overlaps with other segments.

**Comment by Lolingew** [comment]
> One update, I was able to reproduce this issue in master.
> 
> This is the workaround. If you add the following:
> 
> ```groovy-gradle
> android {
>   packagingOptions {
>     // Prevent the ELF library from getting corrupted.
>     doNotStrip "*/arm64-v8a/libapp.so"
>     doNotStrip "*/armeabi-v7a/libapp.so"
>   }
> }
> ```
> 
> to your app's `build.gradle` then the issue is fixed.

thanks a lot!!!! it works!!
i add these codes to flutter-module/.android/app/build.gradle, flutter-module/Flutter/build.gradle, and android app's build.gradle, 3 places in total.
(should i close these issue now? or wait until flutter fix it in future version?)

**Comment by blasten** [comment]
Once the issue is fixed in master, this issue can be closed.

**Comment by blasten** [comment]
The fix is being worked on https://dart-review.googlesource.com/c/sdk/+/106440

**Comment by blasten** [comment]
This was already fixed. Closing.

**Comment by bayuramadeza** [comment]
> This was already fixed. Closing.

What is the flutter channel can i use to fix this issue?

**Comment by tvolkert** [comment]
@bayuramadeza this is available on the dev channel.  It should be on the beta channel this Friday.

**Comment by bayuramadeza** [comment]
> @bayuramadeza this is available on the dev channel. It should be on the beta channel this Friday.

@tvolkert i have tried to update my flutter version in thte dev channel, but the same error still appear.

06-27 09:34:14.161 4458-4461/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
06-27 09:34:15.583 4458-4461/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [4, 0]
06-27 09:34:16.061 379-390/? E/cutils: Failed to openat(/storage/0403-0201): Permission denied
06-27 09:34:16.066 379-390/? E/cutils: Failed to openat(/storage/0403-0201): Permission denied
06-27 09:34:16.201 6198-6198/? E/flutter: [ERROR:flutter/fml/platform/posix/native_library_posix.cc(16)] Could not open library '/data/app/com.top.example-2/lib/arm64/libflutter.so' due to error 'dlopen failed: library "/data/app/com.top.example-2/lib/arm64/libflutter.so" not found'.
06-27 09:34:16.201 6198-6198/? A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8 in tid 6198 (p.exammple)
06-27 09:34:16.305 524-524/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-27 09:34:16.305 524-524/? A/DEBUG: Build fingerprint: 'Xiaomi/helium/helium:6.0.1/MMB29M/V7.3.14.0.MBDCNDE:user/release-keys'
06-27 09:34:16.305 524-524/? A/DEBUG: Revision: '0'
06-27 09:34:16.305 524-524/? A/DEBUG: ABI: 'arm64'
06-27 09:34:16.305 524-524/? A/DEBUG: pid: 6198, tid: 6198, name: top.example  >>> com.top.example <<<
06-27 09:34:16.305 524-524/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8

**Comment by tvolkert** [comment]
@bayuramadeza can you include the output of your `flutter build` command with `--verbose` turned on (as a https://gist.github.com/ link)?

**Comment by bayuramadeza** [comment]
@tvolkert this is my gist link, so please help me. 
https://gist.github.com/bayuramadeza/5f1bc8244a393a9072242bd3500e86a2

**Comment by blasten** [comment]
One more question, what Android version? It's strange that it's trying to look for the library `arm64/libflutter.so` instead of `arm64-v8a/ibflutter.so`.

**Comment by bayuramadeza** [comment]
@blasten the android version that has been crashed are the most of android 6.0.1 in Xiaomi redmi 3s and Xiaomi mi max

**Comment by bayuramadeza** [comment]
hai @blasten, is there any update about my issue?
https://github.com/flutter/flutter/issues/34308#issuecomment-506133166

**Comment by bayuramadeza** [comment]
is this issue has been fixed in beta channel or dev v1.8.0 channel?

**Comment by bayuramadeza** [comment]
> > @bayuramadeza this is available on the dev channel. It should be on the beta channel this Friday.
> 
> @tvolkert i have tried to update my flutter version in the dev channel 1.7.10, but the same error still appear after i upload my aab to playstore.
> 
> 06-27 09:34:14.161 4458-4461/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
> 06-27 09:34:15.583 4458-4461/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [4, 0]
> 06-27 09:34:16.061 379-390/? E/cutils: Failed to openat(/storage/0403-0201): Permission denied
> 06-27 09:34:16.066 379-390/? E/cutils: Failed to openat(/storage/0403-0201): Permission denied
> 06-27 09:34:16.201 6198-6198/? E/flutter: [ERROR:flutter/fml/platform/posix/native_library_posix.cc(16)] Could not open library '/data/app/com.top.example-2/lib/arm64/libflutter.so' due to error 'dlopen failed: library "/data/app/com.top.example-2/lib/arm64/libflutter.so" not found'.
> 06-27 09:34:16.201 6198-6198/? A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8 in tid 6198 (p.exammple)
> 06-27 09:34:16.305 524-524/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
> 06-27 09:34:16.305 524-524/? A/DEBUG: Build fingerprint: 'Xiaomi/helium/helium:6.0.1/MMB29M/V7.3.14.0.MBDCNDE:user/release-keys'
> 06-27 09:34:16.305 524-524/? A/DEBUG: Revision: '0'
> 06-27 09:34:16.305 524-524/? A/DEBUG: ABI: 'arm64'
> 06-27 09:34:16.305 524-524/? A/DEBUG: pid: 6198, tid: 6198, name: top.example >>> com.top.example <<<
> 06-27 09:34:16.305 524-524/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8

hai @tvolkert after i tried stable channel this is still happened, what should i do?

**Comment by blasten** [comment]
@bayuramadeza This is strange. I saw a similar issue when folks try to install 32-bit APKs in 64-bit devices, but in your case you uploaded an app bundle with 32/64-bit binaries, so this shouldn't be an issue. 

It might be worth to double check that you are downloading the latest APK by increasing `flutter.versionCode` in `android/local.properties` and updating the description on the Play Console, so it's clear you are downloading the latest APK. If you are still seeing this issue, feel free to share the app bundle on Google Drive and indicate the device model.

**Comment by bayuramadeza** [comment]
@blasten i'll make sure i downloaded the latest apk.
i got stuck with this issue, 
this is my appbundle link
https://drive.google.com/file/d/1ruDGNQ13nI2tuOrs2RPjvTFF0UI6nLRE/view?usp=sharing

Thankyou for your help

**Comment by blasten** [comment]
Closing this issue since it's already tracked in https://github.com/flutter/flutter/issues/36822
