### ISSUE TITLE
[Add2App] It's possible to lose the ability to input characters using the keyboard on Android

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#35054]
Using the new embedding API for Android to embed Flutter in an existing app, it is possible for the app to stop taking input from the keyboard.

The following simple Flutter module code will create a TextField.

1. Launch the Flutter module in the existing app
2. Start typing text in the field
3. With focus still in the field, background the app using the Home button
4. Come back to the app. Notice the focus is still in the field, but the keyboard is hidden (expected)
5. Select the field again and start typing. Notice text is not entered in the field.

The following is the code in the flutter module:

```
// Main app entry
void main() {
   runApp(MyApp());
}

class DefaultEmptyPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
            child: TextField(
              decoration: InputDecoration(
                  labelText: "Enter Text"
              ),
            )
        )
    );
  }
}

class MyApp extends StatelessWidget {
  MyApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'My App',
      home: DefaultEmptyPage(),
    );
  }
}
```

The following exception occurs after coming back to the app and tapping in the text field:

```
2019-06-25 09:17:51.732 7330-7330/com.example.app E/MethodChannel#flutter/textinput: Failed to handle method call
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
        at io.flutter.plugin.editing.TextInputPlugin.setTextInputEditingState(TextInputPlugin.java:208)
        at io.flutter.plugin.editing.TextInputPlugin.access$400(TextInputPlugin.java:26)
        at io.flutter.plugin.editing.TextInputPlugin$1.setEditingState(TextInputPlugin.java:66)
        at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:76)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:90)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:234)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
2019-06-25 09:17:51.775 7330-7471/com.example.app E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference, null)
    #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:149:7)
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
    <asynchronous suspension>
    #2      OptionalMethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:424:36)
    <asynchronous suspension>
    #3      TextInputConnection.setEditingState (package:flutter/src/services/text_input.dart:649:30)
    #4      EditableTextState._updateRemoteEditingValueIfNeeded (package:flutter/src/widgets/editable_text.dart:1093:26)
    #5      EditableTextState._didChangeTextEditingValue (package:flutter/src/widgets/editable_text.dart:1400:5)
    #6      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:206:21)
    #7      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:273:5)
    #8      TextEditingController.selection= (package:flutter/src/widgets/editable_text.dart:166:5)
    #9      EditableTextState._handleSelectionChanged (package:flutter/src/widgets/editable_text.dart:1211:23)
    #10     RenderEditable._handlePotentialSelectionChange (package:flutter/src/rendering/editable.dart:369:5)
    #11     RenderEditable.selectPositionAt (package:flutter/src/rendering/editable.dart:1416:9)
    #12     RenderEditable.selectPosition (package:flutter/src/rendering/editable.dart:1388:5)
    #13     _TextFieldState._handleSingleTapUp (package:flutter/src/material/text_field.dart:760:27)
    #14     _TextSelectionGestureDetectorState._handleTapUp (package:flutter/src/widgets/text_selection.dart:929:16)
    #15     TapGestureRecognizer._checkUp.<anonymous closure> (package:flutter/src/gestures/tap.dart:383:49)
    #16     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
    #17     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:383:11)
    #18     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:332:7)
    #19     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
    #20     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
    #21     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
    #22     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
    #23     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
    #24     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
    #25     _rootRunUnary (dart:async/zone.dart:1136:13)
    #26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
    #27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
    #28     _invoke1 (dart:ui/hooks.dart:239:10)
    #29     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
2019-06-25 09:17:51.935 7330-7330/com.example.app D/FlutterView: sendViewportMetricsToFlutter()
```

**Comment by matthew-carroll** [comment]
I was able to repro this issue with the new embedding. I believe I have a fix - it will require a framework PR and an engine PR.

The root cause is that the old embedding kept `FlutterActivity` and `FlutterView` around the entire time the application is in memory, along with the Flutter execution context. 

The new embedding detaches the Flutter execution context (`FlutterEngine`) from `FlutterActivity` and `FlutterView` every time it goes to the background, and re-attaches when `FlutterActivity` enters the foreground. This results in a `TextInputPlugin` being created on every foreground, and destroyed on every background, which loses the input connection, but the Flutter framework is unaware of any of this background/foreground shifting, so the Flutter framework still thinks the input connection exists. When the user taps on the field after foregrounding the app, the Flutter framework sends an input connection message, but there is no longer any Android-side input connection to control, thus the error that is reported.

The solution I will propose is one in which the destruction of the `TextInputPlugin` sends a message to the framework to clear out the input connection so that when `FlutterActivity` comes back to the foreground, the Flutter framework creates a new input connection and everything continues working as expected.

**Comment by dannyvalentesonos** [comment]
Thanks for confirming this @matthew-carroll. Could the following issue we've found be related to this kind of thing as well? With a PageView widget that snaps its scrolling to page boundaries, if you start scrolling, and while you're in the middle of a scroll, hit the home key to background the app, when you come back, the scrolling can either snap back after you touch the widget again, or it can be in an entirely broken state, where the scrolling no longer snaps to page boundaries anymore.
This cannot be reproduced in a regular Flutter app, using the same flutter code, or on iOS.

**Comment by matthew-carroll** [comment]
Seems possible that they're related. Do you think you could provide a video of the pageview scrolling issue? I think the solution will be different, but there might be a category of issues that we need to look at here.

**Comment by matthew-carroll** [comment]
@goderbauer @xster please take a look at @dannyvalentesonos's last comment. It's possible that we have a non-trivial issue with the platform/framework boundary now that Flutter's execution context can move between `FlutterActivity`s over time. If that problem proves to be generic in nature, we'll need to put our heads together about what an appropriate resolution looks like.

**Comment by matthew-carroll** [comment]
Update on this: I merged in an engine and framework change to fix this. However, that change caused an even more critical bug. We think we know how to solve the new bug, but we had to revert this change in the meantime.

@collinjackson is working on an improved testing boundary for text input related testing in the framework, which has been deemed necessary for the next attempt at this problem.

Once @collinjackson is done with that, either I can take another stab at this, or @HansMuller can select another dev to push through the fix for this.

**Comment by smitthakkar1** [comment]
@dannyvalentesonos thanks for reporting this. I am having the issue.

@matthew-carroll thanks for taking a look at this and explaining the bug. What is the current status on this ? You mentioned that you made a change to flutter engine and revert it back. Sounds like the bug still exist but I want to understand will I need to update my flutter to latest when you'll have fix to flutter-engine ?

**Comment by matthew-carroll** [comment]
I'll defer to @HansMuller on priority/triage.

Whenever the issue is resolved, you'll need to use the `master` channel to get it until it makes its way to more stable channels like `dev` and `stable`. So it's just a question of how long you can wait.

**Comment by HansMuller** [comment]
We can't try (again) to land a fix for this issue until we have a way to test the fix. As I understand it, @collinjackson is working on that.

**Comment by smitthakkar1** [comment]
Thanks @matthew-carroll @HansMuller for the reply. Is there ANY workaround you guys aware of ?

**Comment by dannyvalentesonos** [comment]
@matthew-carroll We've just run into a crash which is easy to repro. 
1. Launch an activity with a flutter embedding view
2. Pull up Android's Recent Apps list
3. While the list is showing, change the orientation
4. come back to the app

The crash log shows:
```
    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sonos.acr, PID: 5757
    java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.embedding.engine.systemchannels.LocalizationChannel io.flutter.embedding.engine.FlutterEngine.getLocalizationChannel()' on a null object reference
        at io.flutter.embedding.android.FlutterView.sendLocalesToFlutter(FlutterView.java:737)
        at io.flutter.embedding.android.FlutterView.onConfigurationChanged(FlutterView.java:262)
        at android.view.View.dispatchConfigurationChanged(View.java:10498)
        at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1312)
        at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1316)
        at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1316)
        at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1316)
        at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1316)
        at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1316)
        at android.view.ViewRootImpl.updateConfiguration(ViewRootImpl.java:3341)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1771)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
        at android.view.Choreographer.doFrame(Choreographer.java:621)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

I'm wondering if this is related? Or if we should log a separate bug?

**Comment by smitthakkar1** [comment]
I have seen this bug but I don't think it's related to this issue. Let me
know if you find any solution

**Comment by matthew-carroll** [comment]
@dannyvalentesonos I would recommend filing a new bug with the new repro steps. Worst case scenario we can mark it duplicate if it is.

**Comment by dannyvalentesonos** [comment]
Thanks @matthew-carroll. #43459

**Comment by xster** [comment]
@matthew-carroll, @nturgut I've asked Dan to take a look at this one too for Android. 

@dnfield, @nturgut has the framework part of this restored in https://github.com/flutter/flutter/pull/43466. But it's still needing the Android engine part.

**Comment by dnfield** [comment]
@xster  - I just reviewed @nturgut's PR and I believe it would suffer from the same problems as the original attempt.  It's not clear to me that it can land as-is.

**Comment by dnfield** [comment]
Talked offline - this won't be a problem for Android at this point because there are no corresponding changes to the engine yet.

**Comment by xster** [comment]
Right. The potentially 'incorrect' side-effects in the framework is never exercised on Android even after it merges. Though I think your review points are potentially still valid. We may still need to add some degree of differentiation in the APIs on the framework side itself.

**Comment by dnfield** [comment]
Here's what's happening from my observations:

1) Flutter side creates an input connection and keeps it with ID 1.
2) Flutter tells embedding about ID 1.
3) App is backgrounded; embedding loses view and associated state, including knowledge of ID 1.
4) App is foregrounded. Flutter thinks embedding still knows about ID 1 and keeps trying to talk to embedding without re-establishing connection.
5) Embedding swallows NPE(s) when it gets messages about text client it isn't aware of anymore.

We should be able to fix this by just re-establishing the input connection for text editing client(s) when coming back.  Have to determine the best place to do that, or if we need to create a new one. For the time being I was able to prove this works by adding some logic to the framework to let me manually trigger a call to `setClient` again.

**Comment by xster** [comment]
Awesomeness. Thanks for fixing this one Dan!
