### ISSUE TITLE
Method swizzling problem on firebase_auth phone auth iOS

### ISSUE THREAD

**Issue by Renziera** [flutter/flutter#35267]
I'm having an issue with firebase_auth verifyPhoneNumber on iOS.
I followed all requirements on documentation. APN works fine (FCM can be received). But whenever verifyPhoneNumber called, it always fail with exception message:

> If app delegate swizzling is disabled, remote notifications received by UIApplicationDelegate need to be forwarded to FIRAuth's canHandleNotification: method

I did pod upgrade to firebase_auth 6.3.0 and flutter to 1.7.11-pre43
still got the same problem. Android build works fine.

**Comment by Arno0216** [comment]
+1
In my case, the firebase auth by phone was working perfectly on production for few months. But all of sudden, user reported failed case yesterday.
Also tested other login methods, Android and FCM are working fine and got the same exception message.

**Comment by MustansirZia** [comment]
I can confirm this happened to me too when I upgraded my flutter to `v1.7.8+hotfix.2` from `v1.5.4-hotfix.2`. As soon as I downgraded the exception vanished.

**Comment by khainhero** [comment]
Same issue here. I think this is very important as users cannot properly register now. 
Just upgraded to v1.7.8+hotfix.3 and still an issue.
Everything was working before. 
I double checked my iOS capabilities section for push notification/background fetch/remote notifications and everything seems fine.
firebaseappdelegateproxyenabled in the info.plist was a type STRING with a value NO
I fixed that to type BOOLEAN with value YES
I also did pod update, clean install of the app and flutter clean.
Still an issue.

**Comment by gisinator** [comment]
Glad I'm not the only one facing this issue. I upgraded to newest stable 1.7.8 hotfix.3 yesterday and since then it doesnt work anymore. Unfortunately this is a major issue, users cant register any more. Flutter devs, can you help? :)

**Comment by collinjackson** [comment]
Firebase's automatic swizzling code lives here:

https://github.com/firebase/firebase-ios-sdk/blob/7eb1747e4b9be195ea9908b9da28b1d0f818afe3/GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m

It seems likely that some change in the engine broke their swizzling, and it seems like we have two options:

- We could try to fix the swizzling.
- We could just always register for notifications (`didReceiveRemoteNotification:...`).

The latter approach is easy but may result in warning emails being sent to firebase_auth users who aren't actually using the phone auth feature.

**Comment by kaumudpa** [comment]
Same problem here when upgraded to newest stable version 1.7.8-hotfix.3.

**Comment by kaumudpa** [comment]
The PR by @collinjackson is working, we can use it in the project in the following manner until the PR is merged in the main branch.

```
firebase_auth:
    git:
      url: https://github.com/collinjackson/plugins.git
      ref: 441417c2fed0ff26bf84a49ab2c5ffd2aa5487de
      path: packages/firebase_auth
```

**Comment by BPHvZ** [comment]
> The PR by @collinjackson is working, we can use it in the project in the following manner until the PR is merged in the main branch.
> 
> ```
> firebase_auth:
>     git:
>       url: https://github.com/collinjackson/plugins.git
>       ref: 441417c2fed0ff26bf84a49ab2c5ffd2aa5487de
>       path: packages/firebase_auth
> ```

This isn't working for me.

**Comment by gisinator** [comment]
@kaumudpa : May I ask you to check on another device on which the sms verification hasnt been tested yet? Reason I'm asking: Collin's PR does work on my testdevices where sms verification had worked before (and then stopped working with upgrade to latest stable). But when I try it on a new device, I get a "token mismatch" error.

I triplechecked all my settings and went over all configuration steps, but with no success: "Token mismatch". I recreated my APNS token in Apple developer portal, so right now I am wondering whether I did something wrong or there is an issue with new devices. 

Again, thank you Collin for the PR and everybody involved in investigating this issue. :)

**Comment by collinjackson** [comment]
I appreciate the help testing flutter/plugins#1826. (Unfortunately it's a bit tricky to test automatically.)


The "token mismatch" issues might be due to type:FIRAuthAPNSTokenTypeSandbox versus type:FIRAuthAPNSTokenTypeProd. The [official docs](https://firebase.google.com/docs/auth/ios/phone-auth#appendix:-using-phone-sign-in-without-swizzling) suggest always using prod so I've updated my PR to remove the #if DEBUG and always use prod.
```
[[FIRAuth auth] setAPNSToken:deviceToken type:FIRAuthAPNSTokenTypeProd];
```

I'm happy to go ahead and merge flutter/plugins#1826 if there's a consensus that it's an improvement while we investigate the larger swizzling issues. Or if folks feel that I revert https://github.com/flutter/plugins/pull/1826/commits/b57627f8bc88bed53ae8978ad181715cdcfb2040 let me know that too. Thanks.

**Comment by gisinator** [comment]
Update: I'm still getting the "token mismatch" error when running "flutter run --release" within AndroidStudio, even with your updated PR.
But, more important: When sending the exact same version to testflight and download it from there, SMS verification works, also on my new device. 
By the end of the day that's what counts, so I can definitely live with that.
So, appreciate your support, Collin, and, for my side, go and merge :)

**Comment by enzoftware** [comment]
> The PR by @collinjackson is working, we can use it in the project in the following manner until the PR is merged in the main branch.
> 
> ```
> firebase_auth:
>     git:
>       url: https://github.com/collinjackson/plugins.git
>       ref: 441417c2fed0ff26bf84a49ab2c5ffd2aa5487de
>       path: packages/firebase_auth
> ```

I have the same issue here and this works perfect for me. Thanks @collinjackson. 

Im not sure if this is currently working in a version of ```firebase_auth``` or fixed in a version of flutter. Because i have troubles using ```flutter v1.7.8+hotfix.3``` and ```firebase_auth: 0.11.1+7```.

**Comment by collinjackson** [comment]
> > The PR by @collinjackson is working, we can use it in the project in the following manner until the PR is merged in the main branch.
> > ```
> > firebase_auth:
> >     git:
> >       url: https://github.com/collinjackson/plugins.git
> >       ref: 441417c2fed0ff26bf84a49ab2c5ffd2aa5487de
> >       path: packages/firebase_auth
> > ```
> 
> I have the same issue here and this works perfect for me. Thanks @collinjackson.
> 
> Im not sure if this is currently working in a version of `firebase_auth` or fixed in a version of flutter. Because i have troubles using `flutter v1.7.8+hotfix.3` and `firebase_auth: 0.11.1+7`.

You'll need to update your firebase_auth to version 0.11.1+8 to get the fix.

**Comment by emersonsiega** [comment]
I'm having the same problem with `firebase_auth: 0.11.1+11`

flutter doctor:
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale pt-BR)
    • Flutter version 1.7.8+hotfix.4 at /Users/emerson.siega/development/flutter
    • Framework revision 20e59316b8 (7 days ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/emerson.siega/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

```

**Comment by nizo-m** [comment]
Same issue in Flutter v1.9.1+hotfix.2 .
tried with firebase_auth: ^0.14.0+5 and tried the solution @collinjackson made without luck.

**Comment by ordsen** [comment]
Hi, we are experiencing the same issue and I'm now trying to fix this since two days..
Flutter version: `Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.5 18F132, locale de-DE)`, firebase_auth: `firebase_auth: "^0.14.0+5"`

On Android everything seems to work just fine. iOS Simulator enters the reCaptcha verification which also works fine. However, on a real iOS device the verification code is never sent. Disabling background app refresh on iOS and thus forcing reCaptcha verification is also not working. The call to `FirebaseAuth.instance.verifyPhoneNumber(...)` always triggers the `verificationFailed` callback and `authException.message`/`authException.code` shows `Token mismatch`/`verifyPhoneNumberError`.

We use `firebase_messaging: "5.1.6"` and have set up APNs already some moths ago. Push notifications are working properly, so I initially didn't update any APNs credential files. Anyway, I now tried both renewing the old APNs Credential Keys and using APNs Certificates with no luck. I then tried to downgrade to `firebase_auth: 0.11.1+8`, which still didn't fix the issue. My next attempt was to fork the flutterfire repo and look into the auth initialization. I thought maybe there is an issue with the `APNSTokenType` being passed, but with my limited iOS native dev skills I can only roughly estimate that `setAPNSToken` is always passed `FIRAuthAPNSTokenTypeProd` which should work with APNs Authentication Key in the Firebase console..
My last attempt was to ask the user for granting the push notifications permission _before_ signing him up. I thought there might be an issue with the silent push notification not being delivered. But again, no luck with that.

Any help or hints for where to look at next would be appreciated! We are currently moving away from the facebook account kit (already removed the dependencies), but I cannot publish a new release with firebase_auth as long as the sign up does not work seamlessly on all devices. Leaving this on a feature branch but it would be nice to include that into our next release.

**Comment by Igalsr** [comment]
Hi @ordsen @nizo-m ,

Have you found a solution?

**Comment by nizo-m** [comment]
> Hi @ordsen @nizo-m ,
> 
> Have you found a solution?

hi @Igalsr ,
I did not find a solution, so I went back to flutter 1.5 for now.

**Comment by Igalsr** [comment]
> > Hi @ordsen @nizo-m ,
> > Have you found a solution?
> 
> hi @Igalsr ,
> I did not find a solution, so I went back to flutter 1.5 for now.

Thank you, that's really annoying.

**Comment by emersonsiega** [comment]
The same for me! I think I'll have to downgrade Flutter version just because of this... Really, really annoying...

**Comment by ordsen** [comment]
> > Hi @ordsen @nizo-m ,
> > Have you found a solution?
> 
> hi @Igalsr ,
> I did not find a solution, so I went back to flutter 1.5 for now.

Me neither. We added firebase auth to our backlog and will retry it after the next flutter release.

**Comment by emersonsiega** [comment]
@collinjackson I think this issue need to be reopened... There's some people with this problem yet...

**Comment by emersonsiega** [comment]
After some time, we can solve this issue following this two docs:

We configure the APNs how's described here.
https://firebase.google.com/docs/auth/ios/phone-auth#start-receiving-silent-notifications
But just this doesn't solve the problem.

We also need to add some changes into App's `Info.plist` and `Runner/AppDelegate.m`
https://firebase.google.com/docs/auth/ios/phone-auth#appendix:-using-phone-sign-in-without-swizzling

Working with Flutter `1.7.8+hotfix.4`

**Comment by Igalsr** [comment]
@emersonsiega  I still get a token mismatch on phone authentication

**Comment by emersonsiega** [comment]
@Igalsr maybe we are talking about different errors... For me the error message is: 
`If app delegate swizzling is disabled, remote notifications received by UIApplicationDelegate need to be forwarded to FIRAuth's canHandleNotificaton: method.`

This starts after upgrade from v1.5.4 to v1.7.8.

**Comment by Igalsr** [comment]
@emersonsiega yes you are right, my error appeared at the same time so I thought I would try your solution as well.

**Comment by kroikie** [comment]
@Renziera

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1102. Any further collaboration will be done there.

**Comment by 19hours** [comment]
@Igalsr @ordsen 

I think the token mismatch error happens when you test locally because firebase_auth looks for the production APNs but you are signing the app with a development profile. As a temporary workaround you can set the APNSTokentype for firebase to sandbox or unknown which would detect your APNs type based on your provisioning profile.

You can use my forked fix here: 
https://github.com/19hours/flutterfire/commit/3366091101b9e9701d23c49672bf2d9e6135d656

Relevant commit:
https://github.com/flutter/plugins/pull/1826/commits/b57627f8bc88bed53ae8978ad181715cdcfb2040

**Comment by LeeLoHoon** [comment]
@ordsen 
We have same error. Did you solve this problem anyway?
we tried above things but they didn't work.
Do you think this is version problem?

**Comment by enzoftware** [comment]
> @ordsen
> We have same error. Did you solve this problem anyway?
> we tried above things but they didn't work.
> Do you think this is version problem?

What is your version of flutter and the firebase depedencies?

**Comment by LeeLoHoon** [comment]
@enzoftware 
My flutter version is v1.12.13+hotfix.5
And my Firebase dependency is firebase_auth: ^0.14.0+8.
I think auth version is meaningful.
Do you have any idea?

**Comment by enzoftware** [comment]
Check the recommended versions for each firebase dependecies in https://github.com/FirebaseExtended/flutterfire

For `firebase_auth` would be `0.15.3+1`.

**Comment by LeeLoHoon** [comment]
I did that too.. But it still doesn't work..

**Comment by LeeLoHoon** [comment]
I solved this problem. It was related APN setting(SandBox Token)  not version problem.
Thanks :)

**Comment by dryaz** [comment]
> I solved this problem. It was related APN setting(SandBox Token) not version problem.
> Thanks :)

@leelohoon could you share what have you done to fix this?

**Comment by Abosrie** [comment]
I am facing the same problem! Any hint of how to fix it?

**Comment by LeeLoHoon** [comment]
@dryaz
@Abosrie
Here is my solution.
https://github.com/FirebaseExtended/flutterfire/issues/1102
:)
