### ISSUE TITLE
Unhandled Exception: NoSuchMethodError: The getter 'length' was called on null

### ISSUE THREAD

**Issue by elekson** [flutter/flutter#35629]
i have code with this,
```
simpan() async {
    final pos = await http.post(BaseUrl.simpanBacaan,body: {"foto" : foto,"judul" : judul,"penulis" : penulis,"isi" : isi});
    final data = jsonDecode(pos.body);
    int val = data['value'];
    if(val==0){
      Navigator.pop(context);
    }
  }
```

when i send data with some word is no problem. but if i send for long text i got this problem error, and data not send

```
E/flutter (12904): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'length' was called on null.
E/flutter (12904): Receiver: null
E/flutter (12904): Tried calling: length
E/flutter (12904): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:50:5)
E/flutter (12904): #1      _Uri._uriEncode  (dart:core-patch/uri_patch.dart:44:23)
E/flutter (12904): #2      Uri.encodeQueryComponent  (dart:core/uri.dart:1100:17)
E/flutter (12904): #3      mapToQuery.<anonymous closure>
E/flutter (12904): #4      CastMap.forEach.<anonymous closure>  (dart:_internal/cast.dart:286:8)
E/flutter (12904): #5      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach  (dart:collection-patch/compact_hash.dart:367:8)
E/flutter (12904): #6      CastMap.forEach  (dart:_internal/cast.dart:285:13)
E/flutter (12904): #7      mapToQuery
E/flutter (12904): #8      Request.bodyFields=
E/flutter (12904): #9      BaseClient._sendUnstreamed
E/flutter (12904): <asynchronous suspension>
E/flutter (12904): #10     BaseClient.post
E/flutter (12904): #11     post.<anonymous closure>
E/flutter (12904): #12     _withClient
E/flutter (12904): <asynchronous suspension>
E/flutter (12904): #13     post
E/flutter (12904): #14     _SimpanState.simpan
E/flutter (12904): <asynchronous suspension>
E/flutter (12904): #15     _SimpanState.checkForm
E/flutter (12904): #16     _SimpanState.build.<anonymous closure>
E/flutter (12904): #17     _InkResponseState._handleTap 
E/flutter (12904): #18     _InkResponseState.build.<anonymous closure> 
E/flutter (12904): #19     GestureRecognizer.invokeCallback 
E/flutter (12904): #20     TapGestureRecognizer._checkUp 
E/flutter (12904): #21     TapGestureRecognizer.acceptGesture 
E/flutter (12904): #22     GestureArenaManager.sweep 
E/flutter (12904): #23     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent 
E/flutter (12904): #24     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
E/flutter (12904): #25     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent 
E/flutter (12904): #26     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue 
E/flutter (12904): #27     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
E/flutter (12904): #28     _rootRunUnary  (dart:async/zone.dart:1136:13)
E/flutter (12904): #29     _CustomZone.runUnary  (dart:async/zone.dart:1029:19)
E/flutter (12904): #30     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:931:7)
E/flutter (12904): #31     _invoke1  (dart:ui/hooks.dart:233:10)
E/flutter (12904): #32     _dispatchPointerDataPacket  (dart:ui/hooks.dart:154:5)
E/flutter (12904):
```

flutter doctor -v
```
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.557], locale en-ID)
    • Flutter version 1.5.4-hotfix.2 at D:\flutter
    • Framework revision 7a4c33425d (10 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.36.0)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

• No issues found!
```

**Comment by tzifudzi** [comment]
For me this issue was caused by an invalid pubspec.yaml file. Check your pubspec.yaml for any issues. In my case I had the following:

```
  assets:
    - res/icons/logo.svg
    -
    - res/icons/logo_small.svg
```

**Comment by BondarenkoStas** [comment]
@eyallen Please report if the issue is solved.

**Comment by eyallen** [comment]
@BondarenkoStas I think you want @elekson.

**Comment by BondarenkoStas** [comment]
Oh sorry, my mistake. I fixed the name in the comment above.

**Comment by Nico04** [comment]
I had the same issue with Flutter 1.9.1, and in my case it was because one field of my data was null.
Something like that :
{"foto" : null, "judul" : judul, "penulis" : penulis, "isi" : isi}

Removing the null from the data solved my issue.

**Comment by BondarenkoStas** [comment]
@elekson May you check, as @Nico04 mentioned in the comment above?
I see you are using 1.5.4, can you try for the sake of reproducing it on current stable version?

**Comment by elekson** [comment]
i'm still not find how to solved this. i just remove some property and it work. but i don't like it too much 

> {"judul" : judul, "isi" : isi}

**Comment by BondarenkoStas** [comment]
@elekson Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by Henry667** [comment]
I am facing the same issue while caliing api.
`final response = await http.put(
          Uri(
            scheme: 'http',
            host: host,
            port: 3000,
            path: '/v1/saveBookmark',
          ),
          body: bookmarkData,
          headers: {'Content-Type': 'application/x-www-form-urlencoded'},
        );`

I have no idea why this issue come up.

[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Linux, locale en_IN)
    • Flutter version 1.9.1+hotfix.6 at /home/sunnynegi/Downloads/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /home/sunnynegi/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = /home/sunnynegi/Android/Sdk
    • Java binary at: /mnt/c68c209d-730c-47ba-a53e-a4f027ef29cf/android-studio-ide-183.5692245-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.4)
    • Android Studio at /mnt/c68c209d-730c-47ba-a53e-a4f027ef29cf/android-studio-ide-183.5692245-linux/android-studio
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.37.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • Redmi Note 6 Pro • 6222e236 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
`Exception has occurred.
NoSuchMethodError (NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length)`

**Comment by jdiego0102** [comment]
> Tuve el mismo problema con Flutter 1.9.1, y en mi caso fue porque un campo de mis datos era nulo.
> Algo así:
> {"foto": nulo, "judul": judul, "penulis": penulis, "isi": isi}
> 
> Eliminar el nulo de los datos resolvió mi problema.

This works for me, thanks friend

**Comment by Henry667** [comment]
Well problem is solved, thanks for feedback
