### ISSUE TITLE
W/BiChannelGoogleApi(27734): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@832113d

### ISSUE THREAD

**Issue by upalatucci** [flutter/flutter#37015]
Hello.
I'm working on a mobile application using Flutter and Firebase from a while but only now i encounter some problems as you can see here https://stackoverflow.com/questions/57211271/flutter-firebaseapp-with-name-default-doesnt-exist . 
So i decided to upgrade all the frameworks (firebase_auth: ^0.11.1+12 ),  google gms and also gradle. 
I moved to the 4.3.0 of google gms and 3.3.1 gradle. 
Also i notice some changes into the tutorial to download the google-service.json file and so i add into the dependencies of my android application that:

    implementation 'com.google.firebase:firebase-core:17.0.0'
    implementation 'com.google.firebase:firebase-auth:18.1.0'

I don't know if all this changes help me to solve my previous error because now i'm facing another problem:
W/BiChannelGoogleApi(27734): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@832113d

And i don't know what can i do. Can you help me? This means that i solve the previous problem? 

Thanks.

**Comment by upalatucci** [comment]
Thanks to the new update of flutter_auth  ( ^0.12.0 ) now I fixed the bug. 
With this version Android Studio give me an error in this line:
user = await FirebaseAuth.instance
          .signInWithEmailAndPassword(email: _email, password: _password).

Now signInWithEmailAndPassword return a different object AuthResult. With authResultInstance.user you can have the actual user.  

Thanks flutter team.

**Comment by Kiirous** [comment]
Same problem Here:


`W/BiChannelGoogleApi( 3105): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzak@c4e10b5
D/FirebaseAuth( 3105): Notifying id token listeners about user ( 6rhmWwGfU3WwgEi60gamcWzQ2jf1 ).
D/FirebaseAuth( 3105): Notifying auth state listeners about user ( 6rhmWwGfU3WwgEi60gamcWzQ2jf1 ).
E/MethodChannel#plugins.flutter.io/cloud_firestore( 3105): Failed to handle method call
E/MethodChannel#plugins.flutter.io/cloud_firestore( 3105): java.lang.NullPointerException: Firestore component is not present.
E/MethodChannel#plugins.flutter.io/cloud_firestore( 3105): 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:906)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 3105): 	at com.google.firebase.firestore.FirebaseFirestore.getInstance(com.google.firebase:firebase-firestore@@19.0.0:88)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 3105): 	at com.google.firebase.firestore.FirebaseFirestore.getInstance(com.google.firebase:firebase-firestore@@19.0.0:80)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 3105): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.getFirestore(CloudFirestorePlugin.java:89)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 3105): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.getDocumentReference(CloudFirestorePlugin.java:109)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 3105): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.onMethodCall(CloudFirestorePlugin.java:672)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 3105): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 3105): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 3105): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 3105): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 3105): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 3105): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 3105): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 3105): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 3105): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 3105): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
`
If you find out how to solve this, pls let me know.

**Comment by upalatucci** [comment]
Hi.
I find out that this is not a critical error message. I think is only a warning.
My application didn't work for another reason as you can see here https://stackoverflow.com/questions/57211271/flutter-firebaseapp-with-name-default-doesnt-exist. 
So i switch all my firebase plugins with lastest versions and change 

        classpath 'com.google.gms:google-services:4.1.0'

with 
        classpath 'com.google.gms:google-services:4.3.0'

that is the lastest version.

**Comment by Kiirous** [comment]
Hi Upalatucci, I tryied what you said, but it didn't work for me...

Current Classpath:
classpath 'com.google.gms:google-services:4.3.0'

Current Firebase_auth version:
firebase_auth: ^0.13.1+1

When I click to create my account on the app, in the tab RUN, still appearing:
W/BiChannelGoogleApi( 4362): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzak@c4e10b5

**Comment by upalatucci** [comment]
Okay. but now my application is working and this message still appear. I think that your problem is another, not this message. Do you intert into the firebase console di SHA1 code of you application? If you don't know what to do, you can try. To resolve my previous problem, i did also this step.

**Comment by Kiirous** [comment]
Upalatucci, U were eight, it is really working, it is saving the account, in Authentication - users.
The problem is : In DataBase it is not creating the collection "users":
![67963103_2419841544772907_1555654068192411648_o](https://user-images.githubusercontent.com/20067442/62155899-59c4d100-b2e0-11e9-8346-8d41f9690cec.jpg)


My userModel.dart :

_import 'package:scoped_model/scoped_model.dart';
import 'dart:async';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

class UserModel extends Model {
  FirebaseAuth _auth = FirebaseAuth.instance;

  FirebaseUser firebaseUser;
  Map<String, dynamic> userData = Map();

  bool isLoading = false;

  void signUp(
      {@required Map<String, dynamic> userData,
      @required String pass,
      @required VoidCallback onSuccess,
      @required VoidCallback onFail}) {
    isLoading = true;
    notifyListeners();

    _auth
        .createUserWithEmailAndPassword(
      email: userData['email'],
      password: pass,
    )
        .then((user) async {
      firebaseUser = user;
      await _saveUserData(userData);

      onSuccess();
      isLoading = false;
      notifyListeners();
    }).catchError((e) {
      onFail();
      isLoading = false;
      notifyListeners();
    });
  }

  void signIn() async {
    isLoading = true;
    notifyListeners();

    await Future.delayed(Duration(seconds: 3));

    isLoading = false;
    notifyListeners();
  }

  void recoverPass() {}

  _Future<Null> _saveUserData(Map<String, dynamic> userData) async {
    //Salva dados do usuário
    this.userData = userData;
    await Firestore.instance
        .collection('users')
        .document(firebaseUser.uid)
        .setData(userData);
  }
}




And this is the screen that I acess to create accounts:

import 'package:flutter/material.dart';
import 'package:i_nine_app/models/user_model.dart';
import 'package:scoped_model/scoped_model.dart';

class SignUpScreen extends StatefulWidget {
  @override
  _SignUpScreenState createState() => _SignUpScreenState();
}

class _SignUpScreenState extends State<SignUpScreen> {

  final _nameController = TextEditingController();
  final _emailController = TextEditingController();
  final _passController = TextEditingController();
  final _phoneController = TextEditingController();

  final _formKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0.0,
        title: Text('Criar conta',
            style: TextStyle(
              color: Colors.deepPurple,
            )),
        centerTitle: true,
        leading: IconButton(
            icon: Icon(
              Icons.arrow_back_ios,
              color: Colors.deepPurple,
              size: 30,
            ),
            onPressed: () {
              Navigator.of(context).pop();
            }),
      ),
      body: ScopedModelDescendant<UserModel>(
        builder: (context, child, model){
          if(model.isLoading)
            return Center(child: CircularProgressIndicator(),);
          return Material(
            color: Colors.white,
            child: Form(
              key: _formKey,
              child: ListView(
                padding: EdgeInsets.all(16.0),
                children: <Widget>[
                  TextFormField(
                    controller: _nameController,
                    decoration: InputDecoration(hintText: 'Nome Completo'),
                    validator: (text) {
                      if (text.isEmpty || text.length < 5) return 'Nome Inválido';
                    },
                  ),
                  SizedBox(height: 16),
                  TextFormField(
                    controller: _emailController,
                    decoration: InputDecoration(hintText: 'E-mail'),
                    keyboardType: TextInputType.emailAddress,
                    validator: (text) {
                      if (text.isEmpty || !text.contains('@'))
                        return 'E-mail Inválido';
                    },
                  ),
                  SizedBox(height: 16.0),
                  TextFormField(
                    controller: _passController,
                    decoration: InputDecoration(
                      hintText: 'Senha',
                    ),
                    validator: (text) {
                      if (text.isEmpty || text.length < 6) return 'Senha inválida';
                    },
                    obscureText: true,
                  ),
                  SizedBox(height: 16),
                  TextFormField(
                    controller: _phoneController,
                    decoration: InputDecoration(hintText: 'Telefone'),
                      keyboardType: TextInputType.numberWithOptions(),
                    validator: (text) {
                      if (text.isEmpty || text.length < 10)
                        return 'Número Inválido';
                    },
                  ),
                  SizedBox(height: 50),
                  SizedBox(
                    height: 45,
                    child: RaisedButton(
                        shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(20)),
                        child: Text(
                          'Criar',
                          style: TextStyle(fontSize: 18),
                        ),
                        textColor: Colors.white,
                        color: Colors.deepPurple,
                        onPressed: () {
                          if (_formKey.currentState.validate()) {

                            Map<String, dynamic> userData = {
                              'name': _nameController.text,
                              'email': _emailController.text,
                              'phone': _phoneController.text,
                            };

                            model.signUp(
                              userData: userData,
                              pass: _passController.text,
                              onSuccess: _onSuccess,
                              onFail: _onFail,
                            );
                          }
                        }),
                  )
                ],
              ),
            ),
          );
        },
      ),
    );
  }
  void _onSuccess(){
  }
  void _onFail(){
  }
}

Do you have any Idea wt is going wrong?

**Comment by alarichartsock** [comment]
Same problem here.

**Comment by mattpannella** [comment]
i have a project i've been working on, it was working last night. i woke up this morning and now i'm getting this exact error but i haven't changed a single line of code. i have no idea what's going on but it's super frustrating

**Comment by Chaitanyaha** [comment]
Check for this initially  https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility
then follow https://firebase.google.com/docs/android/setup-->Step 4: Add Firebase SDKs to your app
also classpath 'com.google.gms:google-services:4.3.2'

and add the sdk that you want also upgrade your kotlin version

**Comment by BondarenkoStas** [comment]
@Kiirous @mattpannella is the issue still relevant?

**Comment by irwinOT** [comment]
classpath 'com.google.gms:google-services:4.3.2'

**Comment by marcgr9** [comment]
i have the same problem. worked fine last night, woke up and the app won t register / login users, and this appears in the logs: " I/BiChannelGoogleApi: [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzao@a1a72c0 "

**Comment by anihow** [comment]
same issue. Suddenly not able to register users/not able to authenticate the users created some time back.
W/BiChannelGoogleApi( 9954): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzak@af11f2c

**Comment by MohammedShalan** [comment]
Anyone find out the solution ??! Same problem here :(

**Comment by alarichartsock** [comment]
@MohammedShalan Triple check dependencies, upgrade androidX, make sure your minimum android version is up to spec.

**Comment by kroikie** [comment]
@upalatucci

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/352. Any further collaboration will be done there.

**Comment by JAYAMURUGANJ** [comment]
[FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@11690f6

**Comment by JAYAMURUGANJ** [comment]
V/AudioManager( 5632): playSoundEffect   effectType: 0
I/BiChannelGoogleApi( 5632): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@f64ba1b
I/HwSecImmHelper( 5632): mSecurityInputMethodService is null
I/flutter ( 5632): null
E/flutter ( 5632): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: 'package:flutter/src/widgets/text.dart': Failed assertion: line 287 pos 10: 'data != null': A non-null String must be provided to a Text widget.
E/flutter ( 5632): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
E/flutter ( 5632): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
E/flutter ( 5632): #2      new Text (package:flutter/src/widgets/text.dart:287:10)
E/flutter ( 5632): #3      showSnackBar (package:bookurtablets/tools/app_tools.dart:68:18)
E/flutter ( 5632): #4      _TabsLoginLogoutState.verifyLoggin (package:bookurtablets/userScreens/login.dart:99:7)
E/flutter ( 5632): <asynchronous suspension>
E/flutter ( 5632): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:705:14)
E/flutter ( 5632): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:788:36)
E/flutter ( 5632): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 5632): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter ( 5632): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter ( 5632): #10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
E/flutter ( 5632): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:470:9)
E/flutter ( 5632): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter ( 5632): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
E/flutter ( 5632): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter ( 5632): #15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
E/flutter ( 5632): #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter ( 5632): #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter ( 5632): #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 5632): #19     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 5632): #20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 5632): #21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 5632): #22     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter ( 5632): #23     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 5632): #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter ( 5632): #25     _invoke1 (dart:ui/hooks.dart:274:10)
E/flutter ( 5632): #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:183:5)
E/flutter ( 5632):
I/HwSecImmHelper( 5632): mSecurityInputMethodService is null
W/InputMethodManager( 5632): startInputReason = 3
I/HwSecImmHelper( 5632): mSecurityInputMethodService is null
W/IInputConnectionWrapper( 5632): getTextBeforeCursor on inactive InputConnection
W/InputMethodManager( 5632): startInputReason = 8
W/IInputConnectionWrapper( 5632): getExtractedText on inactive InputConnection
V/ActivityThread( 5632): Finishing stop of ActivityRecord{ad4394c token=android.os.BinderProxy@6150f97 {com.example.bookurtablets/com.example.bookurtablets.MainActivity}}
W/InputMethodManager( 5632): startInputReason = 3
W/IInputConnectionWrapper( 5632): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 5632): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper( 5632): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 5632): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper( 5632): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 5632): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper( 5632): getTextBeforeCursor on inactive InputConnection

**Comment by ioana07** [comment]
> i have a project i've been working on, it was working last night. i woke up this morning and now i'm getting this exact error but i haven't changed a single line of code. i have no idea what's going on but it's super frustrating

I have the exact same problem. It was working great. I didn't change anything and now I'm getting this out of nowhere.

**Comment by ioana07** [comment]
> > i have a project i've been working on, it was working last night. i woke up this morning and now i'm getting this exact error but i haven't changed a single line of code. i have no idea what's going on but it's super frustrating
> 
> I have the exact same problem. It was working great. I didn't change anything and now I'm getting this out of nowhere.

It works again out of nowhere. I'd just suggest waiting/moving somewhere with a better connection.

**Comment by itentinc** [comment]
I was struggling with the same issue for a few hours, I found out that when I use an emulator with Google Play installed it works perfectly fine. Hope that helps.

**Comment by Jbz797** [comment]
@ioana07 Same with me, I've been trying to figure it out for a long time before I realized it came from the connection...

**Comment by SudhakarH** [comment]
> same issue. Suddenly not able to register users/not able to authenticate the users created some time back.
> W/BiChannelGoogleApi( 9954): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzak@af11f2c

@anihow Im also facing same problem , share the solution and how u tackle this problem.

**Comment by adriakkarr** [comment]
I'm kinda doomed with this problem..SMS never reaches the phone & the debug log shows the same message :

**I/BiChannelGoogleApi(18201): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@17e9650f
I/flutter (18201): printing the error : Instance of 'AuthException'**

Can the Flutter team please assist ? Anyone got some hints ?

**Comment by skylerknight** [comment]
For me, moving this line:

`apply plugin: 'com.google.gms.google-services'`

in the android/app/build.gradle to the very end of the file seems to have solved the issue.

**Comment by deepashelar11** [comment]
> Upalatucci, U were right, it is really working, it is saving the account, in Authentication - users.
> 
> ![67963103_2419841544772907_1555654068192411648_o](https://user-images.githubusercontent.com/20067442/62155899-59c4d100-b2e0-11e9-8346-8d41f9690cec.jpg)
> 
> The problem is : In DataBase it is not creating the collection "users". If i go to DataBase, it is totally empty:
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/20067442/62156592-b2e13480-b2e1-11e9-92c6-02c728ec60bf.png)
> 
> My userModel.dart :
> 
> ```
> _import 'package:scoped_model/scoped_model.dart';
> import 'dart:async';
> import 'package:firebase_auth/firebase_auth.dart';
> import 'package:flutter/material.dart';
> import 'package:cloud_firestore/cloud_firestore.dart';
> 
> class UserModel extends Model {
>   FirebaseAuth _auth = FirebaseAuth.instance;
> 
>   FirebaseUser firebaseUser;
>   Map<String, dynamic> userData = Map();
> 
>   bool isLoading = false;
> 
>   void signUp(
>       {@required Map<String, dynamic> userData,
>       @required String pass,
>       @required VoidCallback onSuccess,
>       @required VoidCallback onFail}) {
>     isLoading = true;
>     notifyListeners();
> 
>     _auth
>         .createUserWithEmailAndPassword(
>       email: userData['email'],
>       password: pass,
>     )
>         .then((user) async {
>       firebaseUser = user;
>       await _saveUserData(userData);
> 
>       onSuccess();
>       isLoading = false;
>       notifyListeners();
>     }).catchError((e) {
>       onFail();
>       isLoading = false;
>       notifyListeners();
>     });
>   }
> 
>   void signIn() async {
>     isLoading = true;
>     notifyListeners();
> 
>     await Future.delayed(Duration(seconds: 3));
> 
>     isLoading = false;
>     notifyListeners();
>   }
> 
>   void recoverPass() {}
> 
>   _Future<Null> _saveUserData(Map<String, dynamic> userData) async {
>     //Salva dados do usuário
>     this.userData = userData;
>     await Firestore.instance
>         .collection('users')
>         .document(firebaseUser.uid)
>         .setData(userData);
>   }
> }
> ```
> 
> And this is the screen that I acess to create accounts:
> 
> ```
> import 'package:flutter/material.dart';
> import 'package:i_nine_app/models/user_model.dart';
> import 'package:scoped_model/scoped_model.dart';
> 
> class SignUpScreen extends StatefulWidget {
>   @override
>   _SignUpScreenState createState() => _SignUpScreenState();
> }
> 
> class _SignUpScreenState extends State<SignUpScreen> {
> 
>   final _nameController = TextEditingController();
>   final _emailController = TextEditingController();
>   final _passController = TextEditingController();
>   final _phoneController = TextEditingController();
> 
>   final _formKey = GlobalKey<FormState>();
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         backgroundColor: Colors.white,
>         elevation: 0.0,
>         title: Text('Criar conta',
>             style: TextStyle(
>               color: Colors.deepPurple,
>             )),
>         centerTitle: true,
>         leading: IconButton(
>             icon: Icon(
>               Icons.arrow_back_ios,
>               color: Colors.deepPurple,
>               size: 30,
>             ),
>             onPressed: () {
>               Navigator.of(context).pop();
>             }),
>       ),
>       body: ScopedModelDescendant<UserModel>(
>         builder: (context, child, model){
>           if(model.isLoading)
>             return Center(child: CircularProgressIndicator(),);
>           return Material(
>             color: Colors.white,
>             child: Form(
>               key: _formKey,
>               child: ListView(
>                 padding: EdgeInsets.all(16.0),
>                 children: <Widget>[
>                   TextFormField(
>                     controller: _nameController,
>                     decoration: InputDecoration(hintText: 'Nome Completo'),
>                     validator: (text) {
>                       if (text.isEmpty || text.length < 5) return 'Nome Inválido';
>                     },
>                   ),
>                   SizedBox(height: 16),
>                   TextFormField(
>                     controller: _emailController,
>                     decoration: InputDecoration(hintText: 'E-mail'),
>                     keyboardType: TextInputType.emailAddress,
>                     validator: (text) {
>                       if (text.isEmpty || !text.contains('@'))
>                         return 'E-mail Inválido';
>                     },
>                   ),
>                   SizedBox(height: 16.0),
>                   TextFormField(
>                     controller: _passController,
>                     decoration: InputDecoration(
>                       hintText: 'Senha',
>                     ),
>                     validator: (text) {
>                       if (text.isEmpty || text.length < 6) return 'Senha inválida';
>                     },
>                     obscureText: true,
>                   ),
>                   SizedBox(height: 16),
>                   TextFormField(
>                     controller: _phoneController,
>                     decoration: InputDecoration(hintText: 'Telefone'),
>                       keyboardType: TextInputType.numberWithOptions(),
>                     validator: (text) {
>                       if (text.isEmpty || text.length < 10)
>                         return 'Número Inválido';
>                     },
>                   ),
>                   SizedBox(height: 50),
>                   SizedBox(
>                     height: 45,
>                     child: RaisedButton(
>                         shape: RoundedRectangleBorder(
>                             borderRadius: BorderRadius.circular(20)),
>                         child: Text(
>                           'Criar',
>                           style: TextStyle(fontSize: 18),
>                         ),
>                         textColor: Colors.white,
>                         color: Colors.deepPurple,
>                         onPressed: () {
>                           if (_formKey.currentState.validate()) {
> 
>                             Map<String, dynamic> userData = {
>                               'name': _nameController.text,
>                               'email': _emailController.text,
>                               'phone': _phoneController.text,
>                             };
> 
>                             model.signUp(
>                               userData: userData,
>                               pass: _passController.text,
>                               onSuccess: _onSuccess,
>                               onFail: _onFail,
>                             );
>                           }
>                         }),
>                   )
>                 ],
>               ),
>             ),
>           );
>         },
>       ),
>     );
>   }
>   void _onSuccess(){
>   }
>   void _onFail(){
>   }
> }
> ```
> 
> Do you have any Idea wt is going wrong?

I am facing the same issue. I tried most of the things. I added SHA 1 key, applied the plugin. But still, it is not working.
