### ISSUE TITLE
Image Picker Squashed images when taking picture/picking from gallery in Portrait mode on iOS real device

### ISSUE THREAD

**Issue by callumclift** [flutter/flutter#39311]
Internal: b/143434874

Tested on both a real iPhone 8 Plus & iPhone X device, when taking a portrait picture or selecting a portrait picture from the gallery it is squashing the image so the image appears flattened, i'm using the latest version of image picker (image_picker 0.6.1+4) the code i am using is the standard code when using image picker:

`var image = await ImagePicker.pickImage(source: source, maxWidth: 800.0);`

This was working fine in an earlier version of the plugin (I need this newest version as it has a fix for retrieveLostData) but now that i've updated i've noticed this is an issue. The below screenshots you can see the images really aren't great when they are squashed. If I do not specify a maxWidth then this seems to work but I never had an issue with this before, has something changed whereby if you only specify one dimension it is not longer working?

1. Image when taken by the camera:

![IMG_5756-min](https://user-images.githubusercontent.com/40245055/63750533-8b13cb00-c8a5-11e9-8e47-aea766b23c58.PNG)

2. Image after processed by the image picker:

![IMG_5757-min](https://user-images.githubusercontent.com/40245055/63750571-9c5cd780-c8a5-11e9-98ef-1e00bafb09bd.PNG)

**Comment by Hixie** [comment]
cc @cyanglaz

**Comment by cyanglaz** [comment]
This should be fixed with https://github.com/flutter/plugins/pull/2070. Could you update to 0.6.1+10 and confirm?

**Comment by cyanglaz** [comment]
@callumclift Did flutter/plugins#2070 fix the issue for you?

**Comment by callumclift** [comment]
@cyanglaz updated to 0.6.1+11 and it seems to working fine now, thanks!

**Comment by cyanglaz** [comment]
@callumclift That's great! I'm closing the issue now. Feel free to leave a comment here if the same issue occurs again and I'll reopen the issue to further investigate.

**Comment by imamabdulazis** [comment]
This issue is still exist on Iphone 12 pro, when I'm taking image from gallery image still rotate,
then I'am using custom code to disable rotate but still not working.

```dart
Future<File> fixExifRotation(File image, {deleteOriginal: false}) async {
  Directory tempDir = await getTemporaryDirectory();
  String tempPath = tempDir.path;
  var uuid = Uuid();
  final String processedImageUuid = uuid.v4();

  List<int> imageBytes = await image.readAsBytes();

  List<int> result = await FlutterImageCompress.compressWithList(
    imageBytes,
    quality: 100,
    rotate: 0,
  );

  String imageExtension = basename(image.path);

  File fixedImage = File('$tempPath/$processedImageUuid$imageExtension');

  await fixedImage.writeAsBytes(result);

  if (deleteOriginal) await image.delete();

  return fixedImage;
}

```
