### ISSUE TITLE
BUG IN "flutter.bat" causing "Unable to find git in your PATH"

### ISSUE THREAD

**Issue by dbareis** [flutter/flutter#39785]
"git" is in my path as proven by the fact that I just used it to install flutter.

Line 38 is wrong, it says:
`where /q git || ECHO Error: Unable to find git in your PATH. && EXIT /B 1`

It should say:
`where /q git.exe || ECHO Error: Unable to find git in your PATH. && EXIT /B 1`

The results of the "where" command on my computer:
`D:\TMP > where git.exe`
`C:\Program Files\Git\cmd\git.exe`

`D:\TMP > where git`
`Could not find git`

**Comment by susonsapkota** [comment]
`C:\Users\User>where git.exe`
`C:\Program Files\Git\cmd\git.exe`

`C:\Users\User>where git`
`C:\Program Files\Git\cmd\git.exe`

Both should work just fine. Have you added git to environmental variable?

**Comment by dbareis** [comment]
"where" searches the path, the working where proves it's in the path, the failing one proves they are not the same.  If you want me to specify better code that doesn't require where I can do that also...

**Comment by ChoiysApple** [comment]
I have EXACTLY same issue. I checked my powershell and git are up to date. Also i added env variable.
Also git is available in cmd.

**Comment by ChoiysApple** [comment]
I just fixed this, few minutes ago.
I tried to execute flutter doctor with cmd opened with administrator privileges, not flutter_console.bat and it worked.

**Comment by dbareis** [comment]
In my case it turns out I have a different version of "where.exe":

`where where.exe`

While unusual, I won't be the only one in this boat, proving it is always dangerous to use non-inbuilt commands to perform functions.  Better to only use inbuilt windows features or commands you install.

You can replace the failing where command line with the 2 (non-comment) lines below:

`:: http://dennisbareis.com/scriptingtipsandtricks/searchpath.htm`
`for %%E in ("git.exe") do set GitFullName=%%~$PATH:E`
`    if "%GitFullName%" == "" ECHO Error: Unable to find git.exe in your PATH. & EXIT /B 1`

_If the above code fails to find "git.exe" then it is definitely not in the path, and you either need to logoff & logon or shutdown & restart depending on how the path was updated._ 

_This command displays the contents of the "PATH":_

`path`

_The results should contain "**C:\Program Files\Git**"._

**Comment by shanmukmichael** [comment]
above problems are not worked..give a specific TRUE

**Comment by shanmukmichael** [comment]
above solutions are not worked...give a valid..

**Comment by takwachaabane** [comment]
me too have the some problem with 'where" on windows 10 . 
executing the prompt with admin privileges does not solve this .

**Comment by AndrewH2O** [comment]
I had this issue too when building demo app using Android studio on windows using the latest versions with git (git version 2.19.1.windows.1) correctly installed.
Running Gradle task 'assembleDebug'... at this point couldn't find git path
Even from within the android studio terminal git can be found in the path
Turns out the standard setup for git sets the following env variable C:\Program Files\Git\cmd
This works perfectly when using git normally
Flutter dart build looks in C:\Program Files\Git\bin, for some reason so the fix was to add this as a further env variable. 

'where git' produces:
C:\Program Files\Git\bin\git.exe
C:\Program Files\Git\cmd\git.exe [as per windows setup]

**Comment by MelquiEugenio** [comment]
Hello guys,

If you installed git correctly and set it up on the system environment variable 'Path' in this exact order:

1. System32 path;
2. cmd/git.exe path;
3. flutter/bin path;

Ex: Path: "C:\Windows\System32;C:\Program Files\Git\cmd\git.exe;D:\flutter\bin"

In **Windows 10** here, the solution was to **run the command line as administrator** and **navigate to the exact folder where the flutter was installed before running any flutter command**.

-> **NOT the flutter SDK folder** installed by the android studio or any other folder.

In my case it was at D:\flutter\flutter. The first flutter folder was the SDK installed by android.
If everything is set up and should be working, try reseting the cmd or even the pc.

Good luck.

**Comment by KelvinWB** [comment]
Anyone with a solution? I still facing this problem in one of my computers. My environmental variable and git is correctly set it up.

**Comment by dbareis** [comment]
Not apart from the one I posted

**Comment by peterkabz** [comment]
Same error here, I solved it by:
1) uninstalling and installing git
2) setting the path to git.exe executable  at File->Settings->Version Control->Git
3) Restart the computer
