### ISSUE TITLE
[google_maps_flutter] I am getting black screen before loading maps

### ISSUE THREAD

**Issue by zubairehman** [flutter/flutter#39797]
Internal: b/238240540

Hi,
I am getting black screen before loading maps, I tried creating a map widget on `build()` method and store it in a variable to use it whenever i open bottom sheet but i am still facing the same issue. Please have a look at the screenshot below:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7915601/64229575-9d27e600-cf03-11e9-8619-9a7d1892d58d.gif)

**Code**
```dart
  Widget _buildMap() {
    return Expanded(
      flex: 1,
      child: MapWidget(
        initialLocation: _center,
        zoomLevel: 11.0,
        locations: _jobStore.jobLocations,
        onMarkerTap: (id) {
          print('job id: $id');
          _jobStore.onItemClick(jobId: int.tryParse(id) ?? 0);
        },
      ),
    );
  }
```

**Flutter doctor**
```
macs-mbp:cubivue_app mac$ flutter doctor -v
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-PK)
    • Flutter version 1.7.8+hotfix.4 at /Users/mac/Documents/flutter
    • Framework revision 20e59316b8 (7 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • BV5500Pro • E535B1ZM960411E2 • android-arm • Android 9 (API 28)

• No issues found!

```

**Comment by zubairehman** [comment]
@zoechi could you please help me out with this

**Comment by guilhermedaldim** [comment]
I'm having the same issue, take a look at the screenshot below:

![Uploading MapProblem.gif…]()

**Comment by guilhermedaldim** [comment]
I'm having the same issue, take a look at the video below:

![MapProblem](https://user-images.githubusercontent.com/42361211/64730458-c6251980-d4b5-11e9-83ae-035200c04a3d.gif)

**Comment by allanwolski** [comment]
Same issue here

**Comment by mahmoudalaa97** [comment]
Same issue

**Comment by guilherme-ambrozio** [comment]
Same issue here too!

**Comment by deepakrana0011** [comment]
same issue here but occurring on Android device only and working fine on IOS device.

**Comment by ialhashim** [comment]
As @deepakrana0011 said, I am also facing the situation where this quick flashing black screen only seems to appear on Android.

**Comment by srombs** [comment]
I am seeing the same issue as well.

**Comment by Gnpiwano** [comment]
I am seeing the same issue as well.

**Comment by Hamza3620** [comment]
Not a very good solution but worked for me. 

bool _isLoading = false;
//when landing on the page, calling an API or doing some other work that takes time
setState(() {
      _isLoading = true;
    });

//do this in build
body: Stack(
        children: <Widget>[
          GoogleMap(
            //Map working here
          ),
          if (_isLoading)
            Container(
              color: Colors.white,
              constraints: BoxConstraints(maxHeight: MediaQuery.of(context).size.height),
              child: Center(
                child: CircularProgressIndicator(),
              ),
            ),
        ],
      ),

**Comment by victorEspitia** [comment]
sqcacasc

**Comment by victorEspitia** [comment]
It is not a good solution but it works.
In the background of the component I put a color similar to Google maps.
I declare a variable in true and when the map has loaded I put it in false.
If the variable is false the width and height are null, if I do not put the corresponding size.


Positioned(
                width: (mapsIsLoaded)? null : screenWidth,
                height: (mapsIsLoaded)? null : screenHeight,
                child: GoogleMap(
                  mapType: MapType.normal,
                  initialCameraPosition: _kGooglePlex,
                  onMapCreated: (GoogleMapController controller) {
                    setState(() {
                      mapsIsLoaded = false;
                    });
                    controllerMaps.complete(controller);
                  },
                ),
),

**Comment by allanwolski** [comment]
Could someone on the Flutter team help with this issue?

**Comment by cyanglaz** [comment]
Thanks for raising the issue. Can anyone provided a reduced test case to reproduce the issue? Possible a very simple main.dart?

**Comment by guilhermedaldim** [comment]
@cyanglaz thanks for listening,

Follows the code snippet for reproducing the problem:

```
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Map',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Go to Map'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            FlatButton(
              child: Text('Go to Map', style: TextStyle(color: Colors.white)),
              color: Colors.blue,
              onPressed: () => Navigator.push(
                  context, MaterialPageRoute(builder: (context) => Map())),
            ),
          ],
        ),
      ),
    );
  }
}

class Map extends StatefulWidget {
  @override
  _MapState createState() => _MapState();
}

class _MapState extends State<Map> {
  Completer<GoogleMapController> _controller = Completer();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Map'),
      ),
      body: GoogleMap(
        initialCameraPosition: CameraPosition(
          target: LatLng(37.42796133580664, -122.085749655962),
          zoom: 14.4746,
        ),
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
        markers: {
          Marker(
            markerId: MarkerId('Map'),
            position: LatLng(37.42796133580664, -122.085749655962),
            icon: BitmapDescriptor.defaultMarkerWithHue(
                BitmapDescriptor.hueRed),
          ),
        }
      ),
    );
  }
}

```

**Comment by Meysam547** [comment]
Same issue

**Comment by MitchSRobinson** [comment]
For anyone that can't wait for a proper solution, here's my quick fix. 
I just placed a placeholder over the map until it loaded and the black screen doesn't mess with the user.
Hope it helps in the short term.

```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class EventLocation extends StatefulWidget {
  const EventLocation({Key key}) : super(key: key);
  @override
  _EventLocationState createState() => _EventLocationState();
}

class _EventLocationState extends State<EventLocation> {
  bool _mapLoading = true;

  @override
  Widget build(BuildContext context) {
    Size size = MediaQuery.of(context).size;

    return Container(
      height: size.height,
      width: size.width,
      child: Stack(
        children: <Widget>[
          GoogleMap(
            initialCameraPosition: CameraPosition(
              target: LatLng(37.4220, -122.0841),
              zoom: 15,
            ),
            onMapCreated: (GoogleMapController controller) =>
                setState(() => _mapLoading = false),
          ),
          (_mapLoading)
              ? Container(
                  height: size.height,
                  width: size.width,
                  color: Colors.grey[100],
                  child: Center(
                    child: CircularProgressIndicator(),
                  ),
                )
              : Container(),
        ],
      ),
    );
  }
}
```

**Comment by brunoda6** [comment]
Hi,
Same problem here tried to hide with The loading but it shows the loading and the balcka again and loads

**Comment by cyanglaz** [comment]
un-assign myself from this issue as I don't have cycle to actively working on it currently.

**Comment by cyanglaz** [comment]
I have discovered that it is an issue with the virtual display API that we use for platform views on Android.
The black screen is only shown for certain devices.

**Comment by allanwolski** [comment]
Thanks, @cyanglaz 

Here it happens with all of our test devices.
Are there any predictions of when this would be corrected?

**Comment by alguintu** [comment]
Same issue with all our android test devices. We tried the loading screen workaround, but the issue persists when the map goes out of view and shown again. Please help fix the issue.

**Comment by ccamba** [comment]
Same issue with Android API 30

**Comment by allanwolski** [comment]
This problem is one year old and has no solution.

**Comment by lzzy12** [comment]
Is this ever going to be fixed?

**Comment by LimitlessFavour** [comment]
> This issue is one year old and has no solution.

I mean.I have been waiting for so long for the fix

**Comment by bajajsahil** [comment]
I am also facing this issue. But in my case, the screen remains blank if I open the camera and comes back. The issue seems to be related with **image_picker** package.

Below is the structure of the page.

```dart
build(){
	Stack () {
		WidgetWithInputsAndImagePicker(),
		GoogleMapWidget(),
	}
}
```
On page load, the google map is perfectly shown.

**_Not Working Scenario_**
- User picks the location
- Move map widget out of the screen using AnimatedPositioned widget.
- Now, the user sees the widget with input and image picker.
- The user fills the input and picks an image using image_picker package.
- The user clicks on the change location button(this button again put the google map on the top of stack using animated positioned).
- Map remains blank with google logo.

**_Working Scenario_**
- User picks the location
- Move map widget out of the screen using AnimatedPositioned widget.
- The user sees the widget with input and image picker.
- The user fills the input and clicks on the change location.
- Map widget loads fine and working as expected.

Whenever I am clicking the picture, map becomes blank. Otherwise, it is working fine.

**Comment by rusakoff** [comment]
This code is working for my project (without black screen):

bool mapsIsLoaded = true;
...
Container(
        width: (mapsIsLoaded) ? 1.0 : size.width,
        height: (mapsIsLoaded) ? 1.0 : size.height,
        child: GoogleMap(
          onMapCreated: (controller) {
            _controller.complete(controller);
            setState(() {
              mapsIsLoaded = false;
            });
          },
          initialCameraPosition: CameraPosition(
            target: LatLng(40.400575, 49.879827),
            zoom: 17,
          ),
        ),
      ),

**Comment by matthewlloyd** [comment]
This is probably related to https://github.com/flutter/flutter/issues/26771.

**Comment by bbmanuputty** [comment]
I am still having this issue

**Comment by shohel01716** [comment]
This Code solved my issue........................

Stack(
                    children: [
                      GoogleMap(
                        mapType: MapType.normal,
                        myLocationEnabled: true,
                        initialCameraPosition: _kGooglePlex,
                        markers: markers,
                        onMapCreated: (GoogleMapController controller) {
                          debugPrint("onMapCreated >>>>>>>>>>>>>>>>>>>>>>");
                          _controller.complete(controller);

                            Timer(Duration(seconds: 1), (){ setState(() {isMapVisible = false;  });});


                        },
                      ),

                      Visibility(visible: isMapVisible,
                        child: Container(
                          height: MediaQuery.of(context).size.height,
                          width: MediaQuery.of(context).size.width,
                          color: Colors.grey[100],
                          child: Center(
                            child: CircularProgressIndicator(),
                          ),
                        ),
                      )
                    ],
                  ),

**Comment by erikatvojo** [comment]
I am still having this issue with the production ready google_maps_flutter, 1.0.2. It would be nice if there was a solution to the black screen other than delaying visibility of the map.

**Comment by LimitlessFavour** [comment]
Has this been fixed in the latest flutter version(1.22)?

**Comment by worldofsites** [comment]
Same

**Comment by artem-bakuta** [comment]
Same issue, but when I'm on the Second Screen, Maps are blicking black under my main widget. I'm not using MapsWidget on that screen only in previous (First Screen).

**Comment by nehamdr225** [comment]
I am using google_maps_flutter version 2.0.3 and the problem of black screen is still persistent. 
I have tried all the above mentioned temporary solutions but none has worked for me so far. If there is anything else that can be done please let me know.

**Comment by pedromassangocode** [comment]
I can confirm that the problem still exists on latest version of the plugin.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  LatLng _position = LatLng(40.73215972821489, -73.980936957489);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: PageView(
          children: [
            GoogleMap(
              mapToolbarEnabled: false,
              initialCameraPosition: CameraPosition(target: _position, zoom: 15.0),
              cameraTargetBounds: CameraTargetBounds(new LatLngBounds(
                  northeast: LatLng(40.73215972821489, -73.980936957489),
                  southwest: LatLng(40.7152797683329, -74.01919598687743)
              )
              ),
            ),
            GoogleMap(
              mapToolbarEnabled: false,
              initialCameraPosition: CameraPosition(target: _position, zoom: 15.0),
              cameraTargetBounds: CameraTargetBounds(new LatLngBounds(
                  northeast: LatLng(40.73215972821489, -73.980936957489),
                  southwest: LatLng(40.7152797683329, -74.01919598687743)
              )
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 2.3.0-1.0.pre.143, on macOS 11.2.3 20D91 darwin-x64, locale en-AO)
    • Flutter version 2.3.0-1.0.pre.143 at /Users/pedromassango/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision aecd5e0302 (3 hours ago), 2021-04-28 00:53:57 -0300
    • Engine revision 92ef7b59c8
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/pedromassango/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.7179

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.93

! Doctor found issues in 1 category.
```

</details>

**Comment by Jaezic** [comment]
I think this code is the best solution.
``
bool isMapVisible = false;

AnimatedOpacity(
                              curve: Curves.fastOutSlowIn,
                              opacity: isMapVisible ? 1.0 : 0,
                              duration: Duration(milliseconds: 600),
                              child: GoogleMap(
                                initialCameraPosition: CameraPosition(
                                  target: LatLng(
                                      37.4503622703105, 127.12989966313339),
                                  zoom: 16,
                                ),
                                onMapCreated: (GoogleMapController controller) {
                                  _controller.complete(controller);
                                  Future.delayed(
                                      const Duration(milliseconds: 550),
                                      () => setState(() {
                                            isMapVisible = true;
                                          }));
                                },
                              ))
``

**Comment by bambinoua** [comment]
> 
> 
> I think this code is the best solution.
> 
@Jaezic did you test your code. The callback `onMapCreated` is not called if `opacity` is 0.0.

**Comment by ahetawal-p** [comment]
We were trying to do exact same thing as mentioned here : https://github.com/flutter/flutter/issues/39797#issuecomment-865704834

While this technique works on Flutter iOS and Android, but flutter web, The callback `onMapCreated` is not called if `opacity` is 0.0.

**Comment by lzzy12** [comment]
Can't believe issue is open since 2019, still hasn't been addressed

**Comment by yasargil** [comment]
Im interested in a fix too. Perhaps the platform view widget should render a configurable color until the underlying nativ view is rendered.

**Comment by alcampospalacios** [comment]
Same issue over here...

**Comment by JagaranMaharjan** [comment]
Stiil same issue exits. I have tried all the above mentioned temporary solutions but none has worked for me so far. If there is anything else that can be done please let me know.

**Comment by alcampospalacios** [comment]
Jaezic solution works for me. And look pretty well.

**Comment by 698373862** [comment]
2022 Still not fixed :-1:

**Comment by salpers** [comment]
Same flickering for me but with the Google Maps Widget. 
![flicker](https://user-images.githubusercontent.com/23464191/151599624-86a8daac-e22d-4b1c-8baf-3151f2873958.gif)

**Comment by atishdhu** [comment]
I use the following code as a work around to give the map time to load and provide a smooth transition using animatedOpacity to display it when loaded. Hope this can help you.

```
// Declare variables

GoogleMapController? _googleMapController;
final Future<bool> _mapFuture = Future.delayed(const Duration(milliseconds: 1000), () => true);

// Build map using FutureBuilder

FutureBuilder
(
  future: _mapFuture,
  builder: (context, AsyncSnapshot<bool> snapshot)
  {
    if(!snapshot.hasData)
    {
      return const Center
      (
        child: CircularProgressIndicator()
      );
    }

    return AnimatedOpacity
    (
      curve: Curves.fastOutSlowIn,
      opacity: isMapVisible ? 1.0 : 0,
      duration: const Duration(milliseconds: 600),
      child: GoogleMap
      (
        initialCameraPosition: _initialCameraPosition,
        onMapCreated: (controller) async
        {
          _googleMapController = controller;

          Future.delayed
          (
            const Duration(milliseconds: 550),
            () => setState
            (()
              {
                isMapVisible = true;
              }
            )
          );
        },
      ),
    );
  }
),
```

**Comment by deekshithx** [comment]
Just use SingleChildScrollView to wrap your GoogleMap Widget.
The flickering will be removed.

`    return SingleChildScrollView(
      physics: const NeverScrollableScrollPhysics(),
      child:SizedBox(
        width: MediaQuery.of(context).size.width,
        height: MediaQuery.of(context).size.height,
        child: //Your GoogleMap here,
      ),
    );`

    
upvote if this works. Thanks in advance

**Comment by chenbi2** [comment]
I'm also seeing this issue. Here are my findings:
- It only happens on Android and not iOS as others have noticed.
- It seems to only happen when the map is very zoomed in, it's very apparent for zoom level 16+, perceptible for zoom level 14, but not so much for zoom level <12.
- I only saw limited effectiveness by fiddling with timers and animations as a stop-gap solution. It seems like there's some optimization for 0 opacity now, because waiting at 0 opacity and then animate to show the map seems to delay the black flash, rather than hiding it.

**Comment by muhammadkamel** [comment]
Facing the same issue

**Comment by bryanoltman** [comment]
Upgrading to P2 as this is blocking an impending (August) customer launch.

**Comment by stuartmorgan** [comment]
Does this happen when using Hybrid Composition, with the instructions here https://pub.dev/packages/google_maps_flutter#android?

**Comment by chenbi2** [comment]
Hybrid composition seems to solve this problem, thanks!

**Comment by stuartmorgan** [comment]
Thanks, we'll most likely resolve this via https://github.com/flutter/flutter/issues/93335 then.

**Comment by bryanoltman** [comment]
Downgrading to P4 because we found a successful workaround.

**Comment by Shahmirzali-Huseynov** [comment]
@zubairehman  did you solve it?

**Comment by johnmccutchan** [comment]
I can't reproduce this issue at flutter head using version 2.5.3 of google_maps_flutter.

**Comment by erikatvojo** [comment]
I'm still getting this issue with google_maps_flutter  2.5.3 and latest flutter. I've solved it on Android by delaying visibility of the map after onMapCreated, similar to atishdhu's solution above, but I'm still getting a flicker before the map displays on iOS.
