### ISSUE TITLE
Snackbar gets stuck with showDialog

### ISSUE THREAD

**Issue by duzenko** [flutter/flutter#39898]
Internal: b/168806189

## Steps to Reproduce

1. Run the attached
2. Click the 'snackbar stuck' button
3. Dialog shows, but the snackbar gets stuck on the screen

## Logs

```
[ +202 ms] DevFS: Sync finished
[   +1 ms] Syncing files to device LGM G600L... (completed in 1,191ms)
[        ] Synced 0.9MB.
[   +1 ms] Sending to VM service: _flutter.listViews({})
[   +7 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x792a74d420, isolate: {type: @Isolate, fixedId: true, id: isolates/912687027, name: main.dart$main-912687027, number: 912687027}}]}
[        ] <- accept
[        ] Connected to _flutterView/0x792a74d420.
[   +1 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +1 ms] An Observatory debugger and profiler on LGM G600L is available at: http://127.0.0.1:64138/oqNUJbXibXU=/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+6333 ms] I/ViewRootImpl( 6337): ViewRoot's Touch Event : ACTION_DOWN
[  +75 ms] I/ViewRootImpl( 6337): ViewRoot's Touch Event : ACTION_UP
[ +176 ms] I/AudioManagerEx( 6337): AudioManagerEx created
```

```
T:\qwe1\flutter_app>flutter analyze
Analyzing flutter_app...
No issues found! (ran in 1.1s)

```

```
T:\qwe1\flutter_app>flutter doctor -v
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17134.885], locale en-GB)
    • Flutter version 1.7.8+hotfix.4 at C:\tools\flutter
    • Framework revision 20e59316b8 (7 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at c:\tools\Android-SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = c:\tools\Android-SDK
    • Java binary at: C:\tools\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\tools\android-studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] VS Code, 32-bit edition (version 1.37.1)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • LGM G600L • LGMG600Lf8469764 • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.
```

**Comment by duzenko** [comment]
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  var alertWidget = AlertWidget();

  tap1(BuildContext context) {
    toast(context, 'qwe');
    showDialog(
      context: context,
      builder: (ctx) => SimpleDialog(
        children: <Widget>[Text('123')],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceAround,
          children: <Widget>[
            Builder(
              builder: (ctx) => FlatButton(
                onPressed: () => tap1(ctx),
                child: Text('snackbar stuck'),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class AlertWidget extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => AlertWidgetState();
}

class AlertWidgetState extends State {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        FlatButton(
          child: Text('click me to test snackbar'),
          onPressed: btnTap(context),
        )
      ],
    );
  }

  btnTap(BuildContext context) => () {
        Navigator.of(context).pop();
        safeToast('qwe2');
      };
}

Function(String text) safeToast;

toast(BuildContext context, String text) {
  Scaffold.of(context).showSnackBar(SnackBar(
    content: Text(text),
    duration: Duration(seconds: 1),
  ));
}
```

**Comment by dmiedev** [comment]
A copy of #19246?

**Comment by duzenko** [comment]
> 
> 
> A copy of #19246?

Obviously, no

**Comment by TahaTesser** [comment]
### Snackbar does get stuck with showDialog 

![untitled](https://user-images.githubusercontent.com/48603081/75550784-a5974e80-5a58-11ea-80fe-899ba16a6c6c.gif)

**Comment by sumerdeveci** [comment]
The same issue for me too. Temporarily solved it by adding this to my `StatefulWidget` which is inside the `Dialog` widget.

```
@override
void dispose() {
  if (widget.scaffoldState != null) {
    widget.scaffoldState.hideCurrentSnackBar();
  }
  super.dispose();
}
```

Well, it does not solve the **exact** issue but at least removes the `SnackBar` a while later. And it is not really a good pattern imo.

Looking forward to hearing better & more reliable solutions!

**Comment by kskotheim** [comment]
I had this same issue, the snackbar being displayed by a stateful widget below a dialog would not disappear after the dialog was dismissed until some new event triggered a rebuild, but without further user interaction it would just stay there forever. My solution was probably not the most efficient, but the snackbar is now disappearing: I passed the Scaffold.of(context).hideCurrentSnackbar() function from the stateful widget w/the snackbar to a simple 'Executor' class I created that just stores and executes a function,  the instance of the executor is defined where the dialog is triggered, so I can just say showDialog( ... ).whenComplete(executor.hideSnackbar) ... It works, but depending on how things are arranged there is probably a simpler way to do this.

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-3.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.19.0-3.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 6135091de9 (3 days ago), 2020-06-01 17:17:03 -0700
    • Engine revision e39301f23f
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 6489a0c68d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      83.0.4103.97

• No issues found!
``` 

</details>

**Comment by mehmetf** [comment]
Bumping up the priority because this is biting internal clients.

**Comment by duzenko** [comment]
What are internal clients treated and how do I become one?

**Comment by HosseinArabbeigi** [comment]
@jonans It isn't good idea, show snackbar multiple times, and just first snackbar will dismiss.

**Comment by r3ddev1l** [comment]
Is there any new progress in this issue?

**Comment by tcd93** [comment]
This bug would most likely be fixed in 1.23, since snackbar is going to be managed by [ScaffoldMessenger](https://flutter.dev/docs/release/breaking-changes/scaffold-messenger) in the next release, I don't the Flutter dev is going to work on this

That said, the bug is from of this line of code: https://github.com/flutter/flutter/blob/78910062997c3a836feee883712c241a5fd22983/packages/flutter/lib/src/material/scaffold.dart#L2353-L2354
Just remove the `if` and it would hide the snackbar normally, **note that an error would be shown if the user switch screen (or dismiss the popup in this case) too early**

Or if you don't want to change source code, this works too:
```
final snackBar = SnackBar(content: const Text('SNACK!'));
Scaffold.of(scaffoldCtx).showSnackBar(snackBar);
Timer(snackBar.duration, () {
  Scaffold.of(scaffoldCtx).hideCurrentSnackBar(reason: SnackBarClosedReason.timeout);
});
```

**Comment by pedromassangocode** [comment]
This issue is still valid on latest master and stable channel. However, showing the SnackBar using the new ScaffoldMessenger API the issue is not reproducible anymore.

Since `Scaffold.of(context).showSnackBar` is being deprecated not sure if it is worth fixing? I think it is since the new API is not on stable channel yet.

Cc @Piinks 

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.22.5 at /Users/pedromassango/Code/flutter_stable
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.313, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.313 at /Users/pedromassango/Code/flutter_master
    • Framework revision 1cb0a24a46 (8 hours ago), 2021-01-12 21:39:27 -0800
    • Engine revision 10cee6abcb
    • Dart version 2.12.0 (build 2.12.0-214.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • macOS (desktop)            • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 87.0.4280.141

! Doctor found issues in 1 category.
```

</details>

**Comment by Piinks** [comment]
If the ScaffoldMessenger solves this issue, then I think that should be the recommended solution. We are currently planning to move away from the Scaffold snackbar methods, which is why they have been deprecated.

**Comment by pedromassangocode** [comment]
> If the ScaffoldMessenger solves this issue, then I think that should be the recommended solution.

FWIW, we don't have any workaround on the stable channel yet because `ScaffoldMessenger` has not landed on stable channel.

**Comment by Pherne** [comment]
I still have this exact issue using the ScaffoldMessenger in Flutter web.

**Comment by bobatsar** [comment]
Here the issue is also still there with scaffoldMessenger.

**Comment by bleroux** [comment]
@bobatsar @Pherne Can you please provide a code sample that reproduces this issue using `ScaffoldMessenger`?

Based on https://github.com/flutter/flutter/issues/39898#issuecomment-759479109 and the following code sample it seems to be fixed:

<details>
<summary>Updated code sample using ScaffoldMessenger</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Snackbar Issue',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: MyColumn(),
      ),
    );
  }
}

class MyColumn extends StatelessWidget {
  const MyColumn({super.key});

  void showSnackBar(String text, BuildContext context) {
    final ScaffoldMessengerState scaffold = ScaffoldMessenger.of(context);
    scaffold.hideCurrentSnackBar();
    scaffold.showSnackBar(SnackBar(
      content: Text(text),
      duration: const Duration(seconds: 1),
    ));
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: <Widget>[
        ElevatedButton(
          child: const Text("Snackbar only"),
          onPressed: () {
            showSnackBar("Snackbar Only", context);
          },
        ),
        ElevatedButton(
          child: const Text("Snackbar and dialog"),
          onPressed: () {
            showSnackBar("Snackbar with Dialog", context);
            showDialog(
                context: context,
                builder: (context) => const StartProgressDialog(),
                barrierDismissible: false);
          },
        )
      ],
    );
  }
}

class StartProgressDialog extends StatelessWidget {
  const StartProgressDialog({super.key});

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: const Text("My Dialog"),
      content: const Text(
        "Snackbar should close as after one second, but doesn't!",
        textAlign: TextAlign.center,
      ),
      actions: <Widget>[
        ElevatedButton(
          child: const Text("Cancel"),
          onPressed: () {
            Navigator.pop(context);
          },
        )
      ],
    );
  }
}
```

</details>
