### ISSUE TITLE
[web] Custom fonts don't render properly in WebKit browsers

### ISSUE THREAD

**Issue by jakcharvat** [flutter/flutter#41483]
## Description

Custom fonts (including MaterialIcons-Regular.ttf) don't seem to work in WebKit powered browsers. Text in my flutter app renders in what looks like Times New Roman in Safari on macOS and Safari as well as Chrome on iOS, but in Roboto Mono and Roboto Slab as intended in Chrome, Chromium Edge and Firefox on macOS. Screenshots of the same flutter app built for the web and tested on different platforms (both emulated and not) [here](https://photos.app.goo.gl/BBRbZGqQxwtXjHMV8). Platform and browser info in the info section of each screenshot.

## File Structure

```
-- root\
   |
   |--- ...
   |--- web\
       |
       |--- assets\
       |   |
       |   |---fonts\
       |   |   |
       |   |   |--- RobotoMono-Regular.ttf
       |   |   |--- RobotoSlab-Regular.ttf
       |   |
       |   |--- FontManifest.json
       |   |--- MaterialIcons-Regular.ttf
       |
       |--- index.html
```

## FontManifest.json

```
[
  {
    "family": "Roboto Mono",
    "fonts": [
      {
        "asset": "fonts/RobotoMono-Regular.ttf"
      }
    ]
  },
  {
    "family": "Roboto Slab",
    "fonts": [
      {
        "asset": "fonts/RobotoSlab-Regular.ttf"
      }
    ]
  },
  {
    "family": "MaterialIcons",
    "fonts": [
      {
        "asset": "MaterialIcons-Regular.ttf"
      }
    ]
  }
]
```

#### `flutter run -d chrome --verbose`
```
[  +16 ms] executing: [/Users/jakcharvat/dev/sdk/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[  +31 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] 04cf581d80dc83a8da050cbe8b4d8572c27aac2c
[        ] executing: [/Users/jakcharvat/dev/sdk/flutter/] git describe --match
v*.*.* --first-parent --long --tags
[  +20 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[        ] v1.10.5-59-g04cf581d8
[   +6 ms] executing: [/Users/jakcharvat/dev/sdk/flutter/] git rev-parse
--abbrev-ref --symbolic @{u}
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/jakcharvat/dev/sdk/flutter/] git ls-remote
--get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +40 ms] executing: [/Users/jakcharvat/dev/sdk/flutter/] git rev-parse
--abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[   +4 ms] executing: sw_vers -productName
[  +14 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +12 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.14.6
[        ] executing: sw_vers -buildVersion
[  +12 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 18G95
[  +11 ms] executing: /usr/bin/xcode-select --print-path
[  +10 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[        ] executing: /usr/bin/xcodebuild -version
[ +203 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +1 ms] Xcode 11.0
           Build version 11A420a
[  +43 ms] executing: /Users/jakcharvat/Library/Android/sdk/platform-tools/adb
devices -l
[   +7 ms] Exit code 0 from:
/Users/jakcharvat/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[   +9 ms] executing:
/Users/jakcharvat/dev/sdk/flutter/bin/cache/artifacts/libimobiledevice/idevice_i
d -h
[  +31 ms] /usr/bin/xcrun simctl list --json devices
[  +92 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
⣽[ +150 ms] executing:
[/Users/jakcharvat/dev/flutter/sticky_game/ios/Runner.xcodeproj/]
/usr/bin/xcodebuild -project
/Users/jakcharvat/dev/flutter/sticky_game/ios/Runner.xcodeproj -target Runner
-showBuildSettings
[   +1 ms] executing:
[/Users/jakcharvat/dev/flutter/sticky_game/ios/Runner.xcodeproj/]
/usr/bin/xcodebuild -project
/Users/jakcharvat/dev/flutter/sticky_game/ios/Runner.xcodeproj -target Runner
-showBuildSettings
⣟[+1286 ms] Build settings for action build and target Runner:
                        ACTION = build
                        AD_HOC_CODE_SIGNING_ALLOWED = NO
                        ALTERNATE_GROUP = staff
                        ALTERNATE_MODE = u+w,go-w,a+rX
                        ALTERNATE_OWNER = jakcharvat
                        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = NO
                        ALWAYS_SEARCH_USER_PATHS = NO
                        ALWAYS_USE_SEPARATE_HEADERMAPS = NO
                        APPLE_INTERNAL_DEVELOPER_DIR = /AppleInternal/Developer
                        APPLE_INTERNAL_DIR = /AppleInternal
                        APPLE_INTERNAL_DOCUMENTATION_DIR =
                        /AppleInternal/Documentation
                        APPLE_INTERNAL_LIBRARY_DIR = /AppleInternal/Library
                        APPLE_INTERNAL_TOOLS = /AppleInternal/Developer/Tools
                        APPLICATION_EXTENSION_API_ONLY = NO
                        APPLY_RULES_IN_COPY_FILES = NO
                        APPLY_RULES_IN_COPY_HEADERS = NO
                        ARCHS = armv7 arm64
                        ARCHS_STANDARD = armv7 arm64
                        ARCHS_STANDARD_32_64_BIT = armv7 arm64
                        ARCHS_STANDARD_32_BIT = armv7
                        ARCHS_STANDARD_64_BIT = arm64
                        ARCHS_STANDARD_INCLUDING_64_BIT = armv7 arm64
                        ARCHS_UNIVERSAL_IPHONE_OS = armv7 arm64
                        ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon
                        AVAILABLE_PLATFORMS = appletvos appletvsimulator
                        iphoneos iphonesimulator macosx watchos watchsimulator
                        BITCODE_GENERATION_MODE = marker
                        BUILD_ACTIVE_RESOURCES_ONLY = NO
                        BUILD_COMPONENTS = headers build
                        BUILD_DIR =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios
                        BUILD_LIBRARY_FOR_DISTRIBUTION = NO
                        BUILD_ROOT =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios
                        BUILD_STYLE = 
                        BUILD_VARIANTS = normal
                        BUILT_PRODUCTS_DIR =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Rele
                        ase-iphoneos
                        CACHE_ROOT =
                        /var/folders/1c/3y91fz8x6zl5mltl_j7rxbsw0000gn/C/com.app
                        le.DeveloperTools/11.0-11A420a/Xcode
                        CCHROOT =
                        /var/folders/1c/3y91fz8x6zl5mltl_j7rxbsw0000gn/C/com.app
                        le.DeveloperTools/11.0-11A420a/Xcode
                        CHMOD = /bin/chmod
                        CHOWN = /usr/sbin/chown
                        CLANG_ANALYZER_NONNULL = YES
                        CLANG_CXX_LANGUAGE_STANDARD = gnu++0x
                        CLANG_CXX_LIBRARY = libc++
                        CLANG_ENABLE_MODULES = YES
                        CLANG_ENABLE_OBJC_ARC = YES
                        CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING = YES
                        CLANG_WARN_BOOL_CONVERSION = YES
                        CLANG_WARN_COMMA = YES
                        CLANG_WARN_CONSTANT_CONVERSION = YES
                        CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS = YES
                        CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR
                        CLANG_WARN_EMPTY_BODY = YES
                        CLANG_WARN_ENUM_CONVERSION = YES
                        CLANG_WARN_INFINITE_RECURSION = YES
                        CLANG_WARN_INT_CONVERSION = YES
                        CLANG_WARN_NON_LITERAL_NULL_CONVERSION = YES
                        CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF = YES
                        CLANG_WARN_OBJC_LITERAL_CONVERSION = YES
                        CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR
                        CLANG_WARN_RANGE_LOOP_ANALYSIS = YES
                        CLANG_WARN_STRICT_PROTOTYPES = YES
                        CLANG_WARN_SUSPICIOUS_MOVE = YES
                        CLANG_WARN_UNREACHABLE_CODE = YES
                        CLANG_WARN__DUPLICATE_METHOD_MATCH = YES
                        CLASS_FILE_DIR =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Runn
                        er.build/Release-iphoneos/Runner.build/JavaClasses
                        CLEAN_PRECOMPS = YES
                        CLONE_HEADERS = NO
                        CODESIGNING_FOLDER_PATH =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Rele
                        ase-iphoneos/Runner.app
                        CODE_SIGNING_ALLOWED = YES
                        CODE_SIGNING_REQUIRED = YES
                        CODE_SIGN_CONTEXT_CLASS = XCiPhoneOSCodeSignContext
                        CODE_SIGN_IDENTITY = iPhone Developer
                        CODE_SIGN_INJECT_BASE_ENTITLEMENTS = YES
                        COLOR_DIAGNOSTICS = NO
                        COMBINE_HIDPI_IMAGES = NO
                        COMPILER_INDEX_STORE_ENABLE = Default
                        COMPOSITE_SDK_DIRS =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Comp
                        ositeSDKs
                        COMPRESS_PNG_FILES = YES
                        CONFIGURATION = Release
                        CONFIGURATION_BUILD_DIR =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Rele
                        ase-iphoneos
                        CONFIGURATION_TEMP_DIR =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Runn
                        er.build/Release-iphoneos
                        CONTENTS_FOLDER_PATH = Runner.app
                        COPYING_PRESERVES_HFS_DATA = NO
                        COPY_HEADERS_RUN_UNIFDEF = NO
                        COPY_PHASE_STRIP = NO
                        COPY_RESOURCES_FROM_STATIC_FRAMEWORKS = YES
                        CORRESPONDING_SIMULATOR_PLATFORM_DIR =
                        /Applications/Xcode.app/Contents/Developer/Platforms/iPh
                        oneSimulator.platform
                        CORRESPONDING_SIMULATOR_PLATFORM_NAME = iphonesimulator
                        CORRESPONDING_SIMULATOR_SDK_DIR =
                        /Applications/Xcode.app/Contents/Developer/Platforms/iPh
                        oneSimulator.platform/Developer/SDKs/iPhoneSimulator13.0
                        .sdk
                        CORRESPONDING_SIMULATOR_SDK_NAME = iphonesimulator13.0
                        CP = /bin/cp
                        CREATE_INFOPLIST_SECTION_IN_BINARY = NO
                        CURRENT_ARCH = arm64
                        CURRENT_PROJECT_VERSION = 1
                        CURRENT_VARIANT = normal
                        DEAD_CODE_STRIPPING = YES
                        DEBUGGING_SYMBOLS = YES
                        DEBUG_INFORMATION_FORMAT = dwarf-with-dsym
                        DEFAULT_COMPILER = com.apple.compilers.llvm.clang.1_0
                        DEFAULT_DEXT_INSTALL_PATH =
                        /System/Library/DriverExtensions
                        DEFAULT_KEXT_INSTALL_PATH = /System/Library/Extensions
                        DEFINES_MODULE = NO
                        DEPLOYMENT_LOCATION = NO
                        DEPLOYMENT_POSTPROCESSING = NO
                        DEPLOYMENT_TARGET_CLANG_ENV_NAME =
                        IPHONEOS_DEPLOYMENT_TARGET
                        DEPLOYMENT_TARGET_CLANG_FLAG_NAME =
                        miphoneos-version-min
                        DEPLOYMENT_TARGET_CLANG_FLAG_PREFIX =
                        -miphoneos-version-min=
                        DEPLOYMENT_TARGET_LD_ENV_NAME =
                        IPHONEOS_DEPLOYMENT_TARGET
                        DEPLOYMENT_TARGET_LD_FLAG_NAME = ios_version_min
                        DEPLOYMENT_TARGET_SETTING_NAME =
                        IPHONEOS_DEPLOYMENT_TARGET
                        DEPLOYMENT_TARGET_SUGGESTED_VALUES = 8.0 8.1 8.2 8.3 8.4
                        9.0 9.1 9.2 9.3 10.0 10.1 10.2 10.3 11.0 11.1 11.2 11.3
                        11.4 12.0 12.1 12.2 12.3 12.4 13.0
                        DERIVED_FILES_DIR =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Runn
                        er.build/Release-iphoneos/Runner.build/DerivedSources
                        DERIVED_FILE_DIR =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Runn
                        er.build/Release-iphoneos/Runner.build/DerivedSources
                        DERIVED_SOURCES_DIR =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Runn
                        er.build/Release-iphoneos/Runner.build/DerivedSources
                        DEVELOPER_APPLICATIONS_DIR =
                        /Applications/Xcode.app/Contents/Developer/Applications
                        DEVELOPER_BIN_DIR =
                        /Applications/Xcode.app/Contents/Developer/usr/bin
                        DEVELOPER_DIR =
                        /Applications/Xcode.app/Contents/Developer
                        DEVELOPER_FRAMEWORKS_DIR =
                        /Applications/Xcode.app/Contents/Developer/Library/Frame
                        works
                        DEVELOPER_FRAMEWORKS_DIR_QUOTED =
                        /Applications/Xcode.app/Contents/Developer/Library/Frame
                        works
                        DEVELOPER_LIBRARY_DIR =
                        /Applications/Xcode.app/Contents/Developer/Library
                        DEVELOPER_SDK_DIR =
                        /Applications/Xcode.app/Contents/Developer/Platforms/Mac
                        OSX.platform/Developer/SDKs
                        DEVELOPER_TOOLS_DIR =
                        /Applications/Xcode.app/Contents/Developer/Tools
                        DEVELOPER_USR_DIR =
                        /Applications/Xcode.app/Contents/Developer/usr
                        DEVELOPMENT_LANGUAGE = en
                        DOCUMENTATION_FOLDER_PATH =
                        Runner.app/en.lproj/Documentation
                        DONT_GENERATE_INFOPLIST_FILE = NO
                        DO_HEADER_SCANNING_IN_JAM = NO
                        DSTROOT = /tmp/Runner.dst
                        DT_TOOLCHAIN_DIR =
                        /Applications/Xcode.app/Contents/Developer/Toolchains/Xc
                        odeDefault.xctoolchain
                        DWARF_DSYM_FILE_NAME = Runner.app.dSYM
                        DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT = NO
                        DWARF_DSYM_FOLDER_PATH =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Rele
                        ase-iphoneos
                        EFFECTIVE_PLATFORM_NAME = -iphoneos
                        EMBEDDED_CONTENT_CONTAINS_SWIFT = NO
                        EMBEDDED_PROFILE_NAME = embedded.mobileprovision
                        EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE = NO
                        ENABLE_BITCODE = NO
                        ENABLE_DEFAULT_HEADER_SEARCH_PATHS = YES
                        ENABLE_HARDENED_RUNTIME = NO
                        ENABLE_HEADER_DEPENDENCIES = YES
                        ENABLE_NS_ASSERTIONS = NO
                        ENABLE_ON_DEMAND_RESOURCES = YES
                        ENABLE_STRICT_OBJC_MSGSEND = YES
                        ENABLE_TESTABILITY = NO
                        ENTITLEMENTS_ALLOWED = YES
                        ENTITLEMENTS_DESTINATION = Signature
                        ENTITLEMENTS_REQUIRED = YES
                        EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS = .DS_Store
                        .svn .git .hg CVS
                        EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES = *.nib
                        *.lproj *.framework *.gch *.xcode* *.xcassets (*)
                        .DS_Store CVS .svn .git .hg *.pbproj *.pbxproj
                        EXECUTABLES_FOLDER_PATH = Runner.app/Executables
                        EXECUTABLE_FOLDER_PATH = Runner.app
                        EXECUTABLE_NAME = Runner
                        EXECUTABLE_PATH = Runner.app/Runner
                        EXPANDED_CODE_SIGN_IDENTITY = 
                        EXPANDED_CODE_SIGN_IDENTITY_NAME = 
                        EXPANDED_PROVISIONING_PROFILE = 
                        FILE_LIST =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Runn
                        er.build/Release-iphoneos/Runner.build/Objects/LinkFileL
                        ist
                        FIXED_FILES_DIR =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Runn
                        er.build/Release-iphoneos/Runner.build/FixedFiles
                        FLUTTER_APPLICATION_PATH =
                        /Users/jakcharvat/dev/flutter/sticky_game
                        FLUTTER_BUILD_DIR = build
                        FLUTTER_BUILD_NAME = 1.0.0
                        FLUTTER_BUILD_NUMBER = 1
                        FLUTTER_FRAMEWORK_DIR =
                        /Users/jakcharvat/dev/sdk/flutter/bin/cache/artifacts/en
                        gine/ios
                        FLUTTER_ROOT = /Users/jakcharvat/dev/sdk/flutter
                        FLUTTER_TARGET =
                        /Users/jakcharvat/dev/flutter/sticky_game/lib/main.dart
                        FRAMEWORKS_FOLDER_PATH = Runner.app/Frameworks
                        FRAMEWORK_FLAG_PREFIX = -framework
                        FRAMEWORK_SEARCH_PATHS =
                        /Users/jakcharvat/dev/flutter/sticky_game/ios/Flutter
                        FRAMEWORK_VERSION = A
                        FULL_PRODUCT_NAME = Runner.app
                        GCC3_VERSION = 3.3
                        GCC_C_LANGUAGE_STANDARD = gnu99
                        GCC_INLINES_ARE_PRIVATE_EXTERN = YES
                        GCC_NO_COMMON_BLOCKS = YES
                        GCC_PFE_FILE_C_DIALECTS = c objective-c c++
                        objective-c++
                        GCC_SYMBOLS_PRIVATE_EXTERN = YES
                        GCC_THUMB_SUPPORT = YES
                        GCC_TREAT_WARNINGS_AS_ERRORS = NO
                        GCC_VERSION = com.apple.compilers.llvm.clang.1_0
                        GCC_VERSION_IDENTIFIER =
                        com_apple_compilers_llvm_clang_1_0
                        GCC_WARN_64_TO_32_BIT_CONVERSION = YES
                        GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR
                        GCC_WARN_UNDECLARED_SELECTOR = YES
                        GCC_WARN_UNINITIALIZED_AUTOS = YES_AGGRESSIVE
                        GCC_WARN_UNUSED_FUNCTION = YES
                        GCC_WARN_UNUSED_VARIABLE = YES
                        GENERATE_MASTER_OBJECT_FILE = NO
                        GENERATE_PKGINFO_FILE = YES
                        GENERATE_PROFILING_CODE = NO
                        GENERATE_TEXT_BASED_STUBS = NO
                        GID = 20
                        GROUP = staff
                        HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT =
                        YES
                        HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYP
                        ES = YES
                        HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS = YES
                        HEADERMAP_INCLUDES_PROJECT_HEADERS = YES
                        HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES = YES
                        HEADERMAP_USES_VFS = NO
                        HIDE_BITCODE_SYMBOLS = YES
                        HOME = /Users/jakcharvat
                        ICONV = /usr/bin/iconv
                        INFOPLIST_EXPAND_BUILD_SETTINGS = YES
                        INFOPLIST_FILE = Runner/Info.plist
                        INFOPLIST_OUTPUT_FORMAT = binary
                        INFOPLIST_PATH = Runner.app/Info.plist
                        INFOPLIST_PREPROCESS = NO
                        INFOSTRINGS_PATH = Runner.app/en.lproj/InfoPlist.strings
                        INLINE_PRIVATE_FRAMEWORKS = NO
                        INSTALLHDRS_COPY_PHASE = NO
                        INSTALLHDRS_SCRIPT_PHASE = NO
                        INSTALL_DIR = /tmp/Runner.dst/Applications
                        INSTALL_GROUP = staff
                        INSTALL_MODE_FLAG = u+w,go-w,a+rX
                        INSTALL_OWNER = jakcharvat
                        INSTALL_PATH = /Applications
                        INSTALL_ROOT = /tmp/Runner.dst
                        IPHONEOS_DEPLOYMENT_TARGET = 8.0
                        JAVAC_DEFAULT_FLAGS = -J-Xms64m -J-XX:NewSize=4M
                        -J-Dfile.encoding=UTF8
                        JAVA_APP_STUB =
                        /System/Library/Frameworks/JavaVM.framework/Resources/Ma
                        cOS/JavaApplicationStub
                        JAVA_ARCHIVE_CLASSES = YES
                        JAVA_ARCHIVE_TYPE = JAR
                        JAVA_COMPILER = /usr/bin/javac
                        JAVA_FOLDER_PATH = Runner.app/Java
                        JAVA_FRAMEWORK_RESOURCES_DIRS = Resources
                        JAVA_JAR_FLAGS = cv
                        JAVA_SOURCE_SUBDIR = .
                        JAVA_USE_DEPENDENCIES = YES
                        JAVA_ZIP_FLAGS = -urg
                        JIKES_DEFAULT_FLAGS = +E +OLDCSO
                        KASAN_DEFAULT_CFLAGS = -DKASAN=1 -fsanitize=address
                        -mllvm -asan-globals-live-support -mllvm
                        -asan-force-dynamic-shadow
                        KEEP_PRIVATE_EXTERNS = NO
                        LD_DEPENDENCY_INFO_FILE =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Runn
                        er.build/Release-iphoneos/Runner.build/Objects-normal/ar
                        m64/Runner_dependency_info.dat
                        LD_GENERATE_MAP_FILE = NO
                        LD_MAP_FILE_PATH =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Runn
                        er.build/Release-iphoneos/Runner.build/Runner-LinkMap-no
                        rmal-arm64.txt
                        LD_NO_PIE = NO
                        LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER = YES
                        LD_RUNPATH_SEARCH_PATHS =  @executable_path/Frameworks
                        LEGACY_DEVELOPER_DIR =
                        /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.idep
                        lugin/Contents/SharedSupport/Developer
                        LEX = lex
                        LIBRARY_DEXT_INSTALL_PATH = /Library/DriverExtensions
                        LIBRARY_FLAG_NOSPACE = YES
                        LIBRARY_FLAG_PREFIX = -l
                        LIBRARY_KEXT_INSTALL_PATH = /Library/Extensions
                        LIBRARY_SEARCH_PATHS =
                        /Users/jakcharvat/dev/flutter/sticky_game/ios/Flutter
                        LINKER_DISPLAYS_MANGLED_NAMES = NO
                        LINK_FILE_LIST_normal_arm64 = 
                        LINK_FILE_LIST_normal_armv7 = 
                        LINK_WITH_STANDARD_LIBRARIES = YES
                        LLVM_TARGET_TRIPLE_OS_VERSION = ios8.0
                        LLVM_TARGET_TRIPLE_VENDOR = apple
                        LOCALIZABLE_CONTENT_DIR = 
                        LOCALIZED_RESOURCES_FOLDER_PATH = Runner.app/en.lproj
                        LOCALIZED_STRING_MACRO_NAMES = NSLocalizedString
                        CFCopyLocalizedString
                        LOCALIZED_STRING_SWIFTUI_SUPPORT = YES
                        LOCAL_ADMIN_APPS_DIR = /Applications/Utilities
                        LOCAL_APPS_DIR = /Applications
                        LOCAL_DEVELOPER_DIR = /Library/Developer
                        LOCAL_LIBRARY_DIR = /Library
                        LOCROOT = 
                        LOCSYMROOT = 
                        MACH_O_TYPE = mh_execute
                        MAC_OS_X_PRODUCT_BUILD_VERSION = 18G95
                        MAC_OS_X_VERSION_ACTUAL = 101406
                        MAC_OS_X_VERSION_MAJOR = 101400
                        MAC_OS_X_VERSION_MINOR = 1406
                        METAL_LIBRARY_FILE_BASE = default
                        METAL_LIBRARY_OUTPUT_DIR =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Rele
                        ase-iphoneos/Runner.app
                        MODULES_FOLDER_PATH = Runner.app/Modules
                        MODULE_CACHE_DIR =
                        /Users/jakcharvat/Library/Developer/Xcode/DerivedData/Mo
                        duleCache.noindex
                        MTL_ENABLE_DEBUG_INFO = NO
                        NATIVE_ARCH = armv7
                        NATIVE_ARCH_32_BIT = i386
                        NATIVE_ARCH_64_BIT = x86_64
                        NATIVE_ARCH_ACTUAL = x86_64
                        NO_COMMON = YES
                        OBJECT_FILE_DIR =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Runn
                        er.build/Release-iphoneos/Runner.build/Objects
                        OBJECT_FILE_DIR_normal =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Runn
                        er.build/Release-iphoneos/Runner.build/Objects-normal
                        OBJROOT =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios
                        ONLY_ACTIVE_ARCH = NO
                        OS = MACOS
                        OSAC = /usr/bin/osacompile
                        PACKAGE_TYPE =
                        com.apple.package-type.wrapper.application
                        PASCAL_STRINGS = YES
                        PATH =
                        /Applications/Xcode.app/Contents/Developer/usr/bin:/usr/
                        local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jakcharva
                        t/dev/sdk/flutter/bin
                        PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES =
                        /usr/include /usr/local/include
                        /System/Library/Frameworks
                        /System/Library/PrivateFrameworks
                        /Applications/Xcode.app/Contents/Developer/Headers
                        /Applications/Xcode.app/Contents/Developer/SDKs
                        /Applications/Xcode.app/Contents/Developer/Platforms
                        PBDEVELOPMENTPLIST_PATH = Runner.app/pbdevelopment.plist
                        PFE_FILE_C_DIALECTS = objective-c
                        PKGINFO_FILE_PATH =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Runn
                        er.build/Release-iphoneos/Runner.build/PkgInfo
                        PKGINFO_PATH = Runner.app/PkgInfo
                        PLATFORM_DEVELOPER_APPLICATIONS_DIR =
                        /Applications/Xcode.app/Contents/Developer/Platforms/iPh
                        oneOS.platform/Developer/Applications
                        PLATFORM_DEVELOPER_BIN_DIR =
                        /Applications/Xcode.app/Contents/Developer/Platforms/iPh
                        oneOS.platform/Developer/usr/bin
                        PLATFORM_DEVELOPER_LIBRARY_DIR =
                        /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.idep
                        lugin/Contents/SharedSupport/Developer/Library
                        PLATFORM_DEVELOPER_SDK_DIR =
                        /Applications/Xcode.app/Contents/Developer/Platforms/iPh
                        oneOS.platform/Developer/SDKs
                        PLATFORM_DEVELOPER_TOOLS_DIR =
                        /Applications/Xcode.app/Contents/Developer/Platforms/iPh
                        oneOS.platform/Developer/Tools
                        PLATFORM_DEVELOPER_USR_DIR =
                        /Applications/Xcode.app/Contents/Developer/Platforms/iPh
                        oneOS.platform/Developer/usr
                        PLATFORM_DIR =
                        /Applications/Xcode.app/Contents/Developer/Platforms/iPh
                        oneOS.platform
                        PLATFORM_DISPLAY_NAME = iOS
                        PLATFORM_NAME = iphoneos
                        PLATFORM_PREFERRED_ARCH = arm64
                        PLATFORM_PRODUCT_BUILD_VERSION = 17A566
                        PLIST_FILE_OUTPUT_FORMAT = binary
                        PLUGINS_FOLDER_PATH = Runner.app/PlugIns
                        PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR = YES
                        PRECOMP_DESTINATION_DIR =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Runn
                        er.build/Release-iphoneos/Runner.build/PrefixHeaders
                        PRESERVE_DEAD_CODE_INITS_AND_TERMS = NO
                        PRIVATE_HEADERS_FOLDER_PATH = Runner.app/PrivateHeaders
                        PRODUCT_BUNDLE_IDENTIFIER = com.example.stickyGame
                        PRODUCT_BUNDLE_PACKAGE_TYPE = APPL
                        PRODUCT_MODULE_NAME = Runner
                        PRODUCT_NAME = Runner
                        PRODUCT_SETTINGS_PATH =
                        /Users/jakcharvat/dev/flutter/sticky_game/ios/Runner/Inf
                        o.plist
                        PRODUCT_TYPE = com.apple.product-type.application
                        PROFILING_CODE = NO
                        PROJECT = Runner
                        PROJECT_DERIVED_FILE_DIR =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Runn
                        er.build/DerivedSources
                        PROJECT_DIR =
                        /Users/jakcharvat/dev/flutter/sticky_game/ios
                        PROJECT_FILE_PATH =
                        /Users/jakcharvat/dev/flutter/sticky_game/ios/Runner.xco
                        deproj
                        PROJECT_NAME = Runner
                        PROJECT_TEMP_DIR =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Runn
                        er.build
                        PROJECT_TEMP_ROOT =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios
                        PROVISIONING_PROFILE_REQUIRED = YES
                        PUBLIC_HEADERS_FOLDER_PATH = Runner.app/Headers
                        RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS = YES
                        REMOVE_CVS_FROM_RESOURCES = YES
                        REMOVE_GIT_FROM_RESOURCES = YES
                        REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES = YES
                        REMOVE_HG_FROM_RESOURCES = YES
                        REMOVE_SVN_FROM_RESOURCES = YES
                        RESOURCE_RULES_REQUIRED = YES
                        REZ_COLLECTOR_DIR =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Runn
                        er.build/Release-iphoneos/Runner.build/ResourceManagerRe
                        sources
                        REZ_OBJECTS_DIR =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Runn
                        er.build/Release-iphoneos/Runner.build/ResourceManagerRe
                        sources/Objects
                        SCAN_ALL_SOURCE_FILES_FOR_INCLUDES = NO
                        SCRIPTS_FOLDER_PATH = Runner.app/Scripts
                        SDKROOT =
                        /Applications/Xcode.app/Contents/Developer/Platforms/iPh
                        oneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk
                        SDK_DIR =
                        /Applications/Xcode.app/Contents/Developer/Platforms/iPh
                        oneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk
                        SDK_DIR_iphoneos13_0 =
                        /Applications/Xcode.app/Contents/Developer/Platforms/iPh
                        oneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk
                        SDK_NAME = iphoneos13.0
                        SDK_NAMES = iphoneos13.0
                        SDK_PRODUCT_BUILD_VERSION = 17A566
                        SDK_VERSION = 13.0
                        SDK_VERSION_ACTUAL = 130000
                        SDK_VERSION_MAJOR = 130000
                        SDK_VERSION_MINOR = 000
                        SED = /usr/bin/sed
                        SEPARATE_STRIP = NO
                        SEPARATE_SYMBOL_EDIT = NO
                        SET_DIR_MODE_OWNER_GROUP = YES
                        SET_FILE_MODE_OWNER_GROUP = NO
                        SHALLOW_BUNDLE = YES
                        SHARED_DERIVED_FILE_DIR =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Rele
                        ase-iphoneos/DerivedSources
                        SHARED_FRAMEWORKS_FOLDER_PATH =
                        Runner.app/SharedFrameworks
                        SHARED_PRECOMPS_DIR =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Shar
                        edPrecompiledHeaders
                        SHARED_SUPPORT_FOLDER_PATH = Runner.app/SharedSupport
                        SKIP_INSTALL = NO
                        SOURCE_ROOT =
                        /Users/jakcharvat/dev/flutter/sticky_game/ios
                        SRCROOT = /Users/jakcharvat/dev/flutter/sticky_game/ios
                        STRINGS_FILE_OUTPUT_ENCODING = binary
                        STRIP_BITCODE_FROM_COPIED_FILES = YES
                        STRIP_INSTALLED_PRODUCT = YES
                        STRIP_STYLE = all
                        STRIP_SWIFT_SYMBOLS = YES
                        SUPPORTED_DEVICE_FAMILIES = 1,2
                        SUPPORTED_PLATFORMS = iphoneos
                        SUPPORTS_MACCATALYST = NO
                        SUPPORTS_TEXT_BASED_API = NO
                        SWIFT_COMPILATION_MODE = wholemodule
                        SWIFT_OBJC_BRIDGING_HEADER =
                        Runner/Runner-Bridging-Header.h
                        SWIFT_OPTIMIZATION_LEVEL = -O
                        SWIFT_PLATFORM_TARGET_PREFIX = ios
                        SWIFT_VERSION = 4.0
                        SYMROOT =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios
                        SYSTEM_ADMIN_APPS_DIR = /Applications/Utilities
                        SYSTEM_APPS_DIR = /Applications
                        SYSTEM_CORE_SERVICES_DIR = /System/Library/CoreServices
                        SYSTEM_DEMOS_DIR = /Applications/Extras
                        SYSTEM_DEVELOPER_APPS_DIR =
                        /Applications/Xcode.app/Contents/Developer/Applications
                        SYSTEM_DEVELOPER_BIN_DIR =
                        /Applications/Xcode.app/Contents/Developer/usr/bin
                        SYSTEM_DEVELOPER_DEMOS_DIR =
                        /Applications/Xcode.app/Contents/Developer/Applications/
                        Utilities/Built Examples
                        SYSTEM_DEVELOPER_DIR =
                        /Applications/Xcode.app/Contents/Developer
                        SYSTEM_DEVELOPER_DOC_DIR =
                        /Applications/Xcode.app/Contents/Developer/ADC Reference
                        Library
                        SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR =
                        /Applications/Xcode.app/Contents/Developer/Applications/
                        Graphics Tools
                        SYSTEM_DEVELOPER_JAVA_TOOLS_DIR =
                        /Applications/Xcode.app/Contents/Developer/Applications/
                        Java Tools
                        SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR =
                        /Applications/Xcode.app/Contents/Developer/Applications/
                        Performance Tools
                        SYSTEM_DEVELOPER_RELEASENOTES_DIR =
                        /Applications/Xcode.app/Contents/Developer/ADC Reference
                        Library/releasenotes
                        SYSTEM_DEVELOPER_TOOLS =
                        /Applications/Xcode.app/Contents/Developer/Tools
                        SYSTEM_DEVELOPER_TOOLS_DOC_DIR =
                        /Applications/Xcode.app/Contents/Developer/ADC Reference
                        Library/documentation/DeveloperTools
                        SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR =
                        /Applications/Xcode.app/Contents/Developer/ADC Reference
                        Library/releasenotes/DeveloperTools
                        SYSTEM_DEVELOPER_USR_DIR =
                        /Applications/Xcode.app/Contents/Developer/usr
                        SYSTEM_DEVELOPER_UTILITIES_DIR =
                        /Applications/Xcode.app/Contents/Developer/Applications/
                        Utilities
                        SYSTEM_DEXT_INSTALL_PATH =
                        /System/Library/DriverExtensions
                        SYSTEM_DOCUMENTATION_DIR = /Library/Documentation
                        SYSTEM_KEXT_INSTALL_PATH = /System/Library/Extensions
                        SYSTEM_LIBRARY_DIR = /System/Library
                        TAPI_VERIFY_MODE = ErrorsOnly
                        TARGETED_DEVICE_FAMILY = 1,2
                        TARGETNAME = Runner
                        TARGET_BUILD_DIR =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Rele
                        ase-iphoneos
                        TARGET_NAME = Runner
                        TARGET_TEMP_DIR =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Runn
                        er.build/Release-iphoneos/Runner.build
                        TEMP_DIR =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Runn
                        er.build/Release-iphoneos/Runner.build
                        TEMP_FILES_DIR =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Runn
                        er.build/Release-iphoneos/Runner.build
                        TEMP_FILE_DIR =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios/Runn
                        er.build/Release-iphoneos/Runner.build
                        TEMP_ROOT =
                        /Users/jakcharvat/dev/flutter/sticky_game/build/ios
                        TOOLCHAIN_DIR =
                        /Applications/Xcode.app/Contents/Developer/Toolchains/Xc
                        odeDefault.xctoolchain
                        TRACK_WIDGET_CREATION = true
                        TREAT_MISSING_BASELINES_AS_TEST_FAILURES = NO
                        UID = 501
                        UNLOCALIZED_RESOURCES_FOLDER_PATH = Runner.app
                        UNSTRIPPED_PRODUCT = NO
                        USER = jakcharvat
                        USER_APPS_DIR = /Users/jakcharvat/Applications
                        USER_LIBRARY_DIR = /Users/jakcharvat/Library
                        USE_DYNAMIC_NO_PIC = YES
                        USE_HEADERMAP = YES
                        USE_HEADER_SYMLINKS = NO
                        USE_LLVM_TARGET_TRIPLES = YES
                        USE_LLVM_TARGET_TRIPLES_FOR_CLANG = YES
                        USE_LLVM_TARGET_TRIPLES_FOR_LD = YES
                        USE_LLVM_TARGET_TRIPLES_FOR_TAPI = YES
                        VALIDATE_PRODUCT = YES
                        VALIDATE_WORKSPACE = NO
                        VALID_ARCHS = arm64 arm64e armv7 armv7s
                        VERBOSE_PBXCP = NO
                        VERSIONING_SYSTEM = apple-generic
                        VERSIONPLIST_PATH = Runner.app/version.plist
                        VERSION_INFO_BUILDER = jakcharvat
                        VERSION_INFO_FILE = Runner_vers.c
                        VERSION_INFO_STRING = "@(#)PROGRAM:Runner
                        PROJECT:Runner-1"
                        WRAPPER_EXTENSION = app
                        WRAPPER_NAME = Runner.app
                        WRAPPER_SUFFIX = .app
                        WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES = NO
                        XCODE_APP_SUPPORT_DIR =
                        /Applications/Xcode.app/Contents/Developer/Library/Xcode
                        XCODE_PRODUCT_BUILD_VERSION = 11A420a
                        XCODE_VERSION_ACTUAL = 1100
                        XCODE_VERSION_MAJOR = 1100
                        XCODE_VERSION_MINOR = 1100
                        XPCSERVICES_FOLDER_PATH = Runner.app/XPCServices
                        YACC = yacc
                        arch = arm64
                        variant = normal
[  +64 ms] Launching lib/main.dart on Chrome in debug mode...
[        ] Building application for the web...
[+8019 ms] Starting daemon...
[ +139 ms] Initializing inputs
[   +8 ms] Reading cached asset graph...
[ +142 ms] Reading cached asset graph completed, took 140ms

[ +185 ms] Checking for updates since last build...
[ +421 ms] Checking for updates since last build completed, took 421ms

[  +12 ms] Initializing inputs
[   +2 ms] Reading cached asset graph...
[        ] Reading cached asset graph completed, took 140ms
[        ] Checking for updates since last build...
[        ] Checking for updates since last build completed, took 421ms
[ +140 ms] Serving DevTools at http://127.0.0.1:63438

[ +709 ms] About to build [web]...
[   +4 ms] Running build...
[ +240 ms] Running build completed, took 81ms

[        ] Caching finalized dependency graph...
[   +6 ms] Caching finalized dependency graph completed, took 180ms

[   +3 ms] Succeeded after 267ms with 0 outputs (0 actions)

[+1864 ms] Failed to load asset at path:
packages/build_web_compilers/src/dev_compiler/dart_sdk.js.

                    Status code: 404

                    Headers:
                    {
                      "date": "Fri, 27 Sep 2019 16:31:03 GMT",
                      "content-length": "9",
                      "x-frame-options": "SAMEORIGIN",
                      "content-type": "text/plain; charset=utf-8",
                      "x-xss-protection": "1; mode=block",
                      "x-content-type-options": "nosniff",
                      "server": "dart:io with Shelf",
                      "via": "1.1 shelf_proxy"
                    }

                    Content:
                    Not Found

[ +596 ms] Debug service listening on ws://127.0.0.1:63503/SjuuflS4NRk=

[  +19 ms] Building application for the web... (completed in 12.5s)
[   +1 ms] 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 
[        ] Warning: Flutter's support for building web applications is highly
experimental.
[        ] For more information see
https://github.com/flutter/flutter/issues/34082.
[        ] 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 
[        ] 🔥  To hot restart (and rebuild state), press "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[   +7 ms] Debug service listening on ws://127.0.0.1:63503/SjuuflS4NRk=
```

#### `flutter analyze`

```
Analyzing sticky_game...                                                
No issues found! (ran in 1.4s)
```

#### `flutter doctor -v`

```
[✓] Flutter (Channel master, v1.10.6-pre.59, on Mac OS X 10.14.6 18G95, locale en-CZ)
    • Flutter version 1.10.6-pre.59 at /Users/jakcharvat/dev/sdk/flutter
    • Framework revision 04cf581d80 (3 days ago), 2019-09-24 20:18:32 -0700
    • Engine revision 63949eb0fd
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 69b5681546)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jakcharvat/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/jakcharvat/Library/Android/sdk
    • Java binary at: /Users/jakcharvat/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5791312/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/jakcharvat/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5791312/Android
      Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6817.14

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 77.0.3865.90
    • Server • web    • web-javascript • Flutter Tools

• No issues found!
```

**Comment by ookami-kb** [comment]
I've ran into this issue as well. The weird things are:

CSS is actually assigned correctly:

<img width="1538" alt="Screenshot 2019-09-27 at 18 50 07" src="https://user-images.githubusercontent.com/853356/65786888-f4625480-e157-11e9-8218-1315df8fc8d6.png">

And it's not reproducible everytime. Sometimes It renders correctly on first page open (but never on page refresh). Sometimes opening developer console and scrolling the page (triggers re-rendering?) helps to fix the fonts dynamically.

So I'm not sure if it's not some bag in Safari engine itself.

> Safari as well as Chrome on iOS

In iOS all the browsers use Safari engine internally, so I believe this is the issue with Safari only.

**Comment by jakcharvat** [comment]
> CSS is actually assigned correctly

Yes, I have noticed that as well, the issue has been consistent for me though. I've **never** had it render fonts properly in Safari. 

---
> So I'm not sure if it's not some bug in Safari engine itself

That was one of my previous assumptions as well:
> don't seem to work in WebKit powered browsers

Not sure if it's related or not, but Safari on my MacBook always fails to load the .dart.js.map file, whereas chrome, firefox and other browsers don't
<img width="1463" alt="Screenshot 2019-09-28 at 10 07 59" src="https://user-images.githubusercontent.com/26692059/65813043-0e437c00-e1d8-11e9-9ed0-6e79dee6c74c.png">
<img width="1312" alt="Screenshot 2019-09-28 at 10 10 01" src="https://user-images.githubusercontent.com/26692059/65813050-274c2d00-e1d8-11e9-8cbc-f388cba72065.png">

**Comment by cic1988** [comment]
same here. Seems only by Safari reproducible.

**Comment by HiroshiHorie** [comment]
Please fix this 🥺It's very ugly without fonts...

**Comment by sma** [comment]
I noticed that TTF resources are incorrectly served as `text/plain` instead of `application/x-font-ttf` by `flutter run` and that Safari's developer tools (therefore?) can't correctly display the font…

![image](https://user-images.githubusercontent.com/14989/66106710-d4e78380-e5be-11e9-9b16-b21b65066808.png)

Perhaps the incorrect content-type is also the reason that Safari ignores the font.

**Comment by ookami-kb** [comment]
@sma I don't think it's the root cause – I've tried inserting link to Google Font directly into the html like this:

```html
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,600" rel="stylesheet">
```

Same result.

**Comment by jakcharvat** [comment]
Also, the in the bundled output of `flutter build web` the fonts display properly in the web inspector for me.

<img width="1436" alt="Screenshot 2019-10-03 at 19 21 03" src="https://user-images.githubusercontent.com/26692059/66145210-0853fd80-e613-11e9-99cb-0cdacbb86d56.png">

**Comment by HiroshiHorie** [comment]
Isn't this supposed to be high priority ?  Since the samples look terrible also....
<img width="828" alt="スクリーンショット 2019-10-05 17 35 46" src="https://user-images.githubusercontent.com/548776/66253180-c18f1080-e796-11e9-9fb0-28636d603f54.png">

**Comment by nturgut** [comment]
I believe the solution is the same to this issue: https://github.com/flutter/flutter/issues/41218

This PR should fix it: https://github.com/flutter/engine/pull/12801

The reason is, the fonts are not loaded if there are special characters in the font family name. The custom fonts will have '/' for example. Code comments in the PR has a more detailed explanation.

**Comment by jakcharvat** [comment]
@nturgut yeah, seems like both issues stem from the same bug, since MaterialIcons are just a custom font as well

**Comment by nturgut** [comment]
I'm closing the issue, the PR is in

**Comment by ookami-kb** [comment]
Still not working with the latest master version:

```
Flutter 1.10.15-pre.142 • channel master • https://github.com/flutter/flutter.git
Framework • revision 430f4c13fa (33 minutes ago) • 2019-10-16 13:33:31 -0700
Engine • revision 5e6c005ef1
```

I believe that root cause is not connected to invalid family name. See my comments https://github.com/flutter/flutter/issues/41483#issuecomment-536017904 and https://github.com/flutter/flutter/issues/41483#issuecomment-537829863 – first, CSS is assigned correctly; second, if you include font directly into html via link to Google font and just use font-family name without any weird characters in it, it still won't work.

**Comment by nturgut** [comment]
Thanks Krill for checking.

Which Safari version are you on? Is it safari desktop?

/cc @hterkelsen

**Comment by HiroshiHorie** [comment]
Same issue here with Safari desktop 🥺

**Comment by DanielCardona** [comment]
Same here, hope it solves soon.

**Comment by nturgut** [comment]
I'll have another look.

**Comment by nturgut** [comment]
Hi,

I tested two custom fonts RobotoMono and ZCOOLXiaoWei on Safari on MacOs. Safari version is:Version 13.0.2. I also tested Chrome on MacOs and Firefox on MacOs.

Including Safari, text seems identical to how it should.

<img width="235" alt="Screen Shot 2019-10-28 at 1 29 42 PM" src="https://user-images.githubusercontent.com/50856934/67715430-133a4d80-f987-11e9-9667-41e53d69fcf2.png">

@hterkelsen pointed out the issue might be with the directory of the assets.

The assets should be in a directory under the root directory instead of under web. Looks like this:

```
-- root\
   |--- myfonts\
       |  --- RobotoMono-Regular.ttf
   |--- web\
       |
       |--- index.html

```
FontManifest.json wil be filled automatically when you run "flutter build web"

You can follow the cookbook link: https://flutter.dev/docs/cookbook/design/fonts

**Comment by DanielCardona** [comment]
Yes! I did a magic 'flutter upgrade' to last version and now it behave the same in every browser...even Safari, thank you very much @nturgut !!
