### ISSUE TITLE
TextDecoration.lineThrough line isn't straight across spaces in CJK text

### ISSUE THREAD

**Issue by giantsol** [flutter/flutter#41668]
When I use `TextDecoration.lineThrough` with other languages (e.g. Korean, Chinese), linethrough appears weird when there is space between characters.

Picture:
![linethrough_with_other_languages](https://user-images.githubusercontent.com/4879766/65938180-3f80ae00-e45d-11e9-82b7-04e8666f38df.jpeg)

## Steps to Reproduce

Simple layout:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Bug reporting',
      home: Material(
        child: SafeArea(
          child: Column(
            children: <Widget>[
              Text(
                'Hello World!', // English
                style: TextStyle(
                  decoration: TextDecoration.lineThrough,
                ),
              ),
              Text(
                '안녕 세계!', // Korean
                style: TextStyle(
                  decoration: TextDecoration.lineThrough,
                ),
              ),
              Text(
                '世界 你好', // Chinese
                style: TextStyle(
                  decoration: TextDecoration.lineThrough,
                ),
              ),
              Text(
                'こんにちは、 世界', // Japanese
                style: TextStyle(
                  decoration: TextDecoration.lineThrough,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

## Logs

```
No suspicious log output with `flutter run --verbose`
```

```
No issues found with `flutter analyze`
```

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.5 18F132, locale en-KR)
    • Flutter version 1.9.1+hotfix.2 at /Users/kakao/flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/kakao/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] IntelliJ IDEA Community Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • SM G950N • ce10171a80a04f3d02 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 2 categories.
```

Thank you in advance :)

**Comment by escamoteur** [comment]
Hi,

thanks for reporting. Could you please try if this is solved on latest master channel?

Does this happen on Android and iOS? 
 
Thanks
Thomas

**Comment by giantsol** [comment]
Hi!
I changed flutter channel to master and tried it again, but still the same. Below is the result of `flutter doctor`:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.7-pre.99, on Mac OS X 10.14.5 18F132, locale en-KR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2018.3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Community Edition (version 2018.2.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (4 available)

! Doctor found issues in 2 categories.
```

I just tested it with iPhone 11 Pro Max simulator, and it works fine on iPhone. I guess it's only an issue with Android.
![image](https://user-images.githubusercontent.com/4879766/65961408-74a6f380-e491-11e9-9e5e-581214b9ff7a.png)

Thanks!

**Comment by escamoteur** [comment]
Although there is still a small smudge when you zoom in.

**Comment by GaryQian** [comment]
The spaces here are alphabetic spaces (U+0020) rather than ideographic spaces (U+3000). These two characters are completely different unicode codepoints, different widths, and different metrics. You should try using the ideographic space in your code (I copied it here for ease of access): `　`.

If you type with a keyboard in the language in question, it should insert the correct type of space.

Please let me know if this fixes your problem!

**Comment by giantsol** [comment]
Hi!
I tested it again using explicit `\u3000` character with `Text` widget, but it doesn't solve this problem either :<
I also tested it with `TextField` using my own keyboard, but same problem occurs.

Below is the full code:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Bug reporting',
      home: Material(
        child: SafeArea(
          child: Column(
            children: <Widget>[
              Text(
                'Hello\u3000World!', // English
                style: TextStyle(
                  decoration: TextDecoration.lineThrough,
                ),
              ),
              Text(
                '안녕\u3000세계!', // Korean
                style: TextStyle(
                  decoration: TextDecoration.lineThrough,
                ),
              ),
              TextField(
                style: TextStyle(
                  decoration: TextDecoration.lineThrough,
                ),
              ),
              SelectableText(
                '世界\u3000你好', // Chinese
                style: TextStyle(
                  decoration: TextDecoration.lineThrough,
                ),
              ),
              Text(
                'こんにちは、\u3000世界', // Japanese
                style: TextStyle(
                  decoration: TextDecoration.lineThrough,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

And below is the screenshot:
![image](https://user-images.githubusercontent.com/4879766/66095073-2862cd00-e5d1-11e9-9568-f65550c566a0.png)

Thanks!

**Comment by GaryQian** [comment]
You are on iOS right?

This may be a font fallback issue. Since you are using Chinese as well as Korean, it could be that the ideographic space is being resolved as a Chinese space, and then the Korean glyphs are resolved to use Apple's korean font, which may have a different set of metrics than the Chinese ideographic space.

The current implementation will attempt to draw the strike through at the metric-specified position, and if unavailable, fall back to half of the X height. If you can provide me with the exact device/OS you are running on, I can try to reproduce this and see what metrics are actually being used.

**Comment by giantsol** [comment]
Thank you for your explanation!
It's on Android actually, and the device is GalaxyS8/9.0(Pie).
Thank you!

**Comment by giantsol** [comment]
Hello @GaryQian !
Any update on this?
Thanks!

**Comment by markusaksli-nc** [comment]
![Screenshot_1598444568]()
Closing since it seems fixed on the latest master `1.22.0-2.0.pre.78`.
<img src="https://user-images.githubusercontent.com/68219924/91303310-803d9000-e7b0-11ea-825a-cd87eeaa395d.png" height="300 />
" />
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-2.0.pre.78, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.22.0-2.0.pre.78 at C:\Development\flutter_master
    • Framework revision d0596582fe (2 hours ago), 2020-08-25 23:26:06 -0700
    • Engine revision b1d9f863db
    • Dart version 2.10.0 (build 2.10.0-56.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (5 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 84.0.4147.135

• No issues found!
```
</details>

**Comment by giantsol** [comment]
@markusaksli-nc 
Thanks. It looks like there's still a problem with `Hello World!`, but it sure has become better than before :)

**Comment by markusaksli-nc** [comment]
Yeah not sure what the expected behavior would be with this non-expected ideographic space, but the original issue is solved.

**Comment by jja08111** [comment]
This `　` space(`\u3000`) is too wide. Any other solution?

### screenshot
![화면 캡처 2021-04-28 155842](https://user-images.githubusercontent.com/57604817/116360201-a5503a00-a83a-11eb-82cb-3814388663bb.png)
![화면 캡처 2021-04-28 160359](https://user-images.githubusercontent.com/57604817/116360906-5e167900-a83b-11eb-98be-8365d272bf36.png)
### code
```dart
Text(
  '아직 문제가 존재해요',
  style: TextStyle(
    decoration: TextDecoration.lineThrough,
    decorationColor: Colors.white70,
    color: Colors.white54,
  ),
  overflow: TextOverflow.ellipsis,
);
```
```dart
Text(
  '띄어쓰기가\u3000너무\u3000커요',
  style: TextStyle(
    decoration: TextDecoration.lineThrough,
    decorationColor: Colors.white70,
    color: Colors.white54,
  ),
  overflow: TextOverflow.ellipsis,
);
```

### flutter doctor -v

```
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale ko-KR)
    • Flutter version 2.0.5 at C:\flutter
    • Framework revision adc687823a (12 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\AndroidSDK
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\AndroidSDK
    • ANDROID_SDK_ROOT = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 90.0.818.49
```
