### ISSUE TITLE
Running on iOS hardware is broken

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#4598]
## Steps to Reproduce

- usb connect iPhone 5s
- cd examples/flutter_gallery
- flutter run

The simulator works fine.

## Flutter Doctor

```
flutter_gallery (master)$ flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/drewwarren/flutter
    • Framework revision e9edf7a0af (83 minutes ago), engine revision 93e9328662

[x] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.2
    • dartlang plugin version 0.6.12
```

## Logs and Crash Reports

```
...
♦  /Users/drewwarren/flutter/bin/flutter --suppress-analytics build aot --target-platform=ios --target=/Users/drewwarren/flutter/examples/flutter_gallery/lib/main.dart --interpreter --debug
Building AOT snapshot in debug mode (ios)...             
Error: Dart_SetField: did not find top-level variable '_isolateId'.
Failed to build /Users/drewwarren/flutter/examples/flutter_gallery.
Command /bin/sh failed with exit code 255


Could not build the precompiled application for the device.
Error running application on drewwarren’s iPhone.
```

**Comment by eseidelGoogle** [comment]
I believe this was just fixed by @abarth.

**Comment by drewwarren** [comment]
I updated to f6b8220c2eefe2e215b2af375855b10d250caceb and the same issue is present.

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/engine/commit/a89a5c91c4a9d2f3dcba832935d19333c1d442e1 was intended to fix exactly this.  @abarth?

**Comment by abarth** [comment]
Yes, this should be fixed at that revision.  Maybe try a clean build in Xcode.

**Comment by abarth** [comment]
Looks like there's still an issue on Mac hosts.  /me investigates.

**Comment by abarth** [comment]
Should be fixed in d11d388d5a91c0b41a6abf80e30b41b1bcb74f14
