### ISSUE TITLE
Could not determine the dependencies of task ':url_launcher:compileDebugAidl'

### ISSUE THREAD

**Issue by pamir72** [flutter/flutter#46753]
**url_launcher 5.4.0**

```bash
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':url_launcher:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':url_launcher:debugCompileClasspath'.
   > Could not resolve project :url_launcher_macos.
     Required by:
         project :url_launcher
      > Unable to find a matching configuration of project :url_launcher_macos:
          - None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Finished with error: Gradle task assembleDebug failed with exit code 1

```

```bash
[✓] Flutter (Channel dev, v1.13.0, on Mac OS X 10.15.1 19B88, locale ru-RU)
    • Flutter version 1.13.0 at /Users/pavelmiheev/Flutter
    • Framework revision 09126abb22 (7 days ago), 2019-12-03 17:43:00 -0800
    • Engine revision 6179380243
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 a4d799c402)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/pavelmiheev/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • SM G973F          • RF8M206Y41Z                          • android-arm64 • Android 10 (API 29)

• No issues found!

```

**Comment by daffigusti** [comment]
same here...

**Comment by iapicca** [comment]
Hi @pamir72 and @daffigusti 
I'm not calling it a solution, but on master works

<details>
  <summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) => MaterialApp(home: HomePage());
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {

  static const String _url = 'https://flutter.dev';

  static Future<void> get _launchURL async => await canLaunch(_url)
    ? await launch(_url) : throw 'Could not launch $_url';

  @override
  Widget build(BuildContext context) => Scaffold(
    floatingActionButton: FloatingActionButton(
      onPressed: ()=> _launchURL,
    ),
  );
}
```

</details>

<details>
  <summary>flutter doctor -v</summary>

```bash
[√] Flutter (Channel master, v1.13.1-pre.94, on Microsoft Windows [Version 10.0.19013.1122], locale en-US)
    • Flutter version 1.13.1-pre.94 at C:\src\flutter
    • Framework revision 36e599eb5d (5 hours ago), 2019-12-11 07:27:13 +0100
    • Engine revision 12bf95fd49
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 8b8894648f)

 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\iapic\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.40.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.0

[√] Connected device (3 available)
    • Pixel 3a   • 965AY0WP5C • android-arm64  • Android 10 (API 29)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

</details>


<details>
  <summary>flutter run --verbose</summary>

```bash 
[  +27 ms] executing: [C:\src\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +74 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 36e599eb5d1bc1c8d98d1c32f2149803fc7ff74e
[   +1 ms] executing: [C:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +164 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +2 ms] v1.13.0-94-g36e599eb5
[  +15 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +49 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\src\flutter\] git ls-remote --get-url origin
[  +60 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +134 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref HEAD
[  +53 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[ +111 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +21 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +30 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +15 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[  +14 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +142 ms] executing: C:\Users\iapic\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +30 ms] Exit code 0 from: C:\Users\iapic\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
           965AY0WP5C             device product:sargo model:Pixel_3a device:sargo transport_id:1
[  +30 ms] C:\Users\iapic\AppData\Local\Android\sdk\platform-tools\adb.exe -s 965AY0WP5C shell getprop
[ +178 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +10 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +10 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +24 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +228 ms] Found plugin url_launcher at C:\Users\iapic\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\url_launcher-5.4.0\
[  +11 ms] Found plugin url_launcher_macos at
C:\Users\iapic\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1\
[  +36 ms] Found plugin url_launcher_web at
C:\Users\iapic\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\url_launcher_web-0.1.0+1\
[ +163 ms] Found plugin url_launcher at C:\Users\iapic\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\url_launcher-5.4.0\
[   +3 ms] Found plugin url_launcher_macos at
C:\Users\iapic\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1\
[  +39 ms] Found plugin url_launcher_web at
C:\Users\iapic\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\url_launcher_web-0.1.0+1\
[ +145 ms] Generating
C:\Users\iapic\Documents\Code\Nevercode\eleventh_december\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +99 ms] ro.hardware = sargo
[        ] ro.build.characteristics = nosdcard
[ +131 ms] Launching lib\main.dart on Pixel 3a in debug mode...
[  +69 ms] executing: C:\Users\iapic\AppData\Local\Android\sdk\build-tools\28.0.3\aapt dump xmltree
C:\Users\iapic\Documents\Code\Nevercode\eleventh_december\build\app\outputs\apk\app.apk AndroidManifest.xml
[  +44 ms] Exit code 0 from: C:\Users\iapic\AppData\Local\Android\sdk\build-tools\28.0.3\aapt dump xmltree
C:\Users\iapic\Documents\Code\Nevercode\eleventh_december\build\app\outputs\apk\app.apk AndroidManifest.xml
[   +2 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.eleventh_december" (Raw: "com.example.eleventh_december")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="eleventh_december" (Raw: "eleventh_december")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")    
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.eleventh_december.MainActivity" (Raw:
                   "com.example.eleventh_december.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: intent-filter (line=35)
                     E: action (line=36)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=38)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")                 E: meta-data (line=45)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: activity (line=49)
                   A: android:theme(0x01010000)=@0x1030007
                   A: android:name(0x01010003)="io.flutter.plugins.urllauncher.WebViewActivity" (Raw:
                   "io.flutter.plugins.urllauncher.WebViewActivity")
                   A: android:exported(0x01010010)=(type 0x12)0x0
[ +105 ms] executing: C:\Users\iapic\AppData\Local\Android\sdk\platform-tools\adb.exe -s 965AY0WP5C shell -x logcat -v time -t
1
[ +143 ms] Exit code 0 from: C:\Users\iapic\AppData\Local\Android\sdk\platform-tools\adb.exe -s 965AY0WP5C shell -x logcat -v
time -t 1
[   +1 ms] --------- beginning of main
           12-11 13:33:38.648 I/CHRE    (  857): @ 140555.050: [ImuCal] [NanoSensorCal:GYRO_RPS] Temp Intercept: -0.003811,    
           0.003099, 0.002574
[  +17 ms] executing: C:\Users\iapic\AppData\Local\Android\sdk\platform-tools\adb.exe -s 965AY0WP5C logcat -v time -T 12-11
13:33:38.648
[  +17 ms] executing: C:\Users\iapic\AppData\Local\Android\sdk\platform-tools\adb.exe version
[ +101 ms] Android Debug Bridge version 1.0.41
                    Version 29.0.5-5949299
                    Installed as C:\Users\iapic\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +2 ms] executing: C:\Users\iapic\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +33 ms] Building APK
[  +44 ms] Running Gradle task 'assembleDebug'...
[  +14 ms] gradle.properties already sets `android.enableR8`
[  +33 ms] Using gradle from C:\Users\iapic\Documents\Code\Nevercode\eleventh_december\android\gradlew.bat.
[  +62 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +159 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +2 ms] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
           OpenJDK 64-Bit Server VM (build 25.202-b03, mixed mode)
[  +19 ms] executing: [C:\Users\iapic\Documents\Code\Nevercode\eleventh_december\android\]
C:\Users\iapic\Documents\Code\Nevercode\eleventh_december\android\gradlew.bat -Pverbose=true
-Ptarget=C:\Users\iapic\Documents\Code\Nevercode\eleventh_december\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-arm64 assembleDebug
[+5028 ms] > Task :app:compileFlutterBuildDebug
[ +205 ms] [  +28 ms] executing: [C:\src\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] [  +71 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] [        ] 36e599eb5d1bc1c8d98d1c32f2149803fc7ff74e
[        ] [        ] executing: [C:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[        ] [  +82 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] [        ] v1.13.0-94-g36e599eb5
[        ] [  +17 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] [  +51 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] [        ] origin/master
[        ] [        ] executing: [C:\src\flutter\] git ls-remote --get-url origin
[   +1 ms] [  +43 ms] Exit code 0 from: git ls-remote --get-url origin
[ +112 ms] [        ] https://github.com/flutter/flutter.git
[   +3 ms] [ +133 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref HEAD
[  +25 ms] [ +176 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +4 ms] [        ] master
[   +3 ms] [  +33 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[  +75 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +49 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[  +34 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ +137 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] [  +44 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[  +97 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[  +94 ms] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[  +30 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +27 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +32 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [ +240 ms] Initializing file store
[  +41 ms] [  +54 ms] Done initializing file store
[+1835 ms] [+2310 ms] kernel_snapshot: Starting due to {InvalidatedReason.inputChanged}
[   +2 ms] [  +14 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe
C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --target=flutter
-Ddart.developer.causal_async_stacks=true -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --no-link-platform --packages
C:\Users\iapic\Documents\Code\Nevercode\eleventh_december\.packages --output-dill
C:\Users\iapic\Documents\Code\Nevercode\eleventh_december\.dart_tool\flutter_build\c0a4f7c902291f145574d55718e56c57\app.dill   
--depfile
C:\Users\iapic\Documents\Code\Nevercode\eleventh_december\.dart_tool\flutter_build\c0a4f7c902291f145574d55718e56c57\kernel_snapshot.d package:eleventh_december/main.dart
[+7495 ms] [+7469 ms] kernel_snapshot: Complete
[ +490 ms] [ +451 ms] debug_android_application: Starting due to {InvalidatedReason.inputChanged,
InvalidatedReason.outputMissing}
[ +209 ms] [ +262 ms] debug_android_application: Complete
[  +11 ms] [  +18 ms] Persisting file store
[  +27 ms] [  +19 ms] Done persisting file store
[   +9 ms] [   +8 ms] build succeeded.
[  +46 ms] [  +44 ms] "flutter assemble" took 11,161ms.
[ +300 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[  +36 ms] > Task :app:preBuild UP-TO-DATE
[  +16 ms] > Task :app:preDebugBuild UP-TO-DATE
[  +49 ms] > Task :url_launcher:preBuild UP-TO-DATE
[   +1 ms] > Task :url_launcher:preDebugBuild UP-TO-DATE
[   +1 ms] > Task :url_launcher_web:preBuild UP-TO-DATE
[   +2 ms] > Task :url_launcher_web:preDebugBuild UP-TO-DATE
[        ] > Task :url_launcher_web:compileDebugAidl NO-SOURCE
[        ] > Task :url_launcher:compileDebugAidl NO-SOURCE
[ +115 ms] > Task :app:compileDebugAidl NO-SOURCE
[   +8 ms] > Task :url_launcher:packageDebugRenderscript NO-SOURCE
[   +3 ms] > Task :url_launcher_web:packageDebugRenderscript NO-SOURCE
[   +1 ms] > Task :app:checkDebugManifest UP-TO-DATE
[   +1 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[   +1 ms] > Task :app:cleanMergeDebugAssets
[   +1 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[  +27 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[   +2 ms] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :url_launcher:mergeDebugShaders UP-TO-DATE
[  +16 ms] > Task :url_launcher:compileDebugShaders UP-TO-DATE
[   +8 ms] > Task :url_launcher:generateDebugAssets UP-TO-DATE
[   +9 ms] > Task :url_launcher:packageDebugAssets UP-TO-DATE
[ +115 ms] > Task :url_launcher_web:mergeDebugShaders UP-TO-DATE
[  +39 ms] > Task :url_launcher_web:compileDebugShaders UP-TO-DATE
[   +1 ms] > Task :url_launcher_web:generateDebugAssets UP-TO-DATE
[   +1 ms] > Task :url_launcher_web:packageDebugAssets UP-TO-DATE
[   +1 ms] > Task :app:mergeDebugAssets
[ +337 ms] > Task :app:copyFlutterAssetsDebug
[   +1 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[   +1 ms] > Task :app:generateDebugResValues UP-TO-DATE
[  +22 ms] > Task :app:generateDebugResources UP-TO-DATE
[   +2 ms] > Task :url_launcher:generateDebugResValues UP-TO-DATE
[   +3 ms] > Task :url_launcher:compileDebugRenderscript NO-SOURCE
[   +1 ms] > Task :url_launcher:generateDebugResources UP-TO-DATE
[   +1 ms] > Task :url_launcher:packageDebugResources UP-TO-DATE
[   +1 ms] > Task :url_launcher_web:generateDebugResValues UP-TO-DATE
[  +46 ms] > Task :url_launcher_web:compileDebugRenderscript NO-SOURCE
[   +1 ms] > Task :url_launcher_web:generateDebugResources UP-TO-DATE
[        ] > Task :url_launcher_web:packageDebugResources UP-TO-DATE
[   +8 ms] > Task :app:mergeDebugResources UP-TO-DATE
[  +23 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[  +87 ms] > Task :url_launcher:checkDebugManifest UP-TO-DATE
[  +14 ms] > Task :url_launcher:processDebugManifest UP-TO-DATE
[   +9 ms] > Task :url_launcher_web:checkDebugManifest UP-TO-DATE
[ +114 ms] > Task :url_launcher_web:processDebugManifest UP-TO-DATE
[   +6 ms] > Task :app:processDebugManifest UP-TO-DATE
[   +2 ms] > Task :url_launcher:parseDebugLibraryResources UP-TO-DATE
[  +67 ms] > Task :url_launcher_web:parseDebugLibraryResources UP-TO-DATE
[ +114 ms] > Task :url_launcher_web:generateDebugRFile UP-TO-DATE
[   +1 ms] > Task :url_launcher:generateDebugRFile UP-TO-DATE
[ +333 ms] > Task :app:processDebugResources UP-TO-DATE
[  +62 ms] > Task :url_launcher:generateDebugBuildConfig UP-TO-DATE
[   +1 ms] > Task :url_launcher_web:generateDebugBuildConfig UP-TO-DATE
[   +2 ms] > Task :url_launcher_web:javaPreCompileDebug UP-TO-DATE
[  +89 ms] > Task :url_launcher_web:compileDebugJavaWithJavac UP-TO-DATE
[  +15 ms] > Task :url_launcher_web:bundleLibCompileDebug UP-TO-DATE
[ +176 ms] > Task :url_launcher:javaPreCompileDebug UP-TO-DATE
[ +162 ms] > Task :url_launcher:compileDebugJavaWithJavac UP-TO-DATE
[   +1 ms] > Task :url_launcher:bundleLibCompileDebug UP-TO-DATE
[   +1 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[   +1 ms] > Task :app:javaPreCompileDebug UP-TO-DATE
[   +1 ms] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[  +27 ms] > Task :app:compileDebugSources UP-TO-DATE
[   +2 ms] > Task :app:processDebugJavaRes NO-SOURCE
[   +1 ms] > Task :url_launcher:processDebugJavaRes NO-SOURCE
[   +1 ms] > Task :url_launcher:bundleLibResDebug UP-TO-DATE
[   +1 ms] > Task :url_launcher_web:processDebugJavaRes NO-SOURCE
[  +32 ms] > Task :url_launcher_web:bundleLibResDebug UP-TO-DATE
[  +77 ms] > Task :url_launcher_web:bundleLibRuntimeDebug UP-TO-DATE
[   +5 ms] > Task :url_launcher_web:createFullJarDebug UP-TO-DATE
[   +4 ms] > Task :app:mergeDebugJavaResource UP-TO-DATE
[  +10 ms] > Task :url_launcher:bundleLibRuntimeDebug UP-TO-DATE
[   +3 ms] > Task :url_launcher:createFullJarDebug UP-TO-DATE
[  +14 ms] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[  +12 ms] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[   +1 ms] > Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[        ] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:signingConfigWriterDebug UP-TO-DATE
[   +1 ms] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[  +21 ms] > Task :url_launcher:mergeDebugJniLibFolders UP-TO-DATE
[   +2 ms] > Task :url_launcher:mergeDebugNativeLibs UP-TO-DATE
[   +1 ms] > Task :url_launcher:stripDebugDebugSymbols UP-TO-DATE
[   +1 ms] > Task :url_launcher:transformNativeLibsWithIntermediateJniLibsForDebug UP-TO-DATE
[   +1 ms] > Task :url_launcher_web:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :url_launcher_web:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :url_launcher_web:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :url_launcher_web:transformNativeLibsWithIntermediateJniLibsForDebug UP-TO-DATE
[  +25 ms] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[   +3 ms] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[   +1 ms] Compatible side by side NDK version was not found.
[+1541 ms] > Task :app:packageDebug
[   +1 ms] > Task :app:assembleDebug
[ +110 ms] > Task :url_launcher:extractDebugAnnotations UP-TO-DATE
[   +2 ms] > Task :url_launcher:mergeDebugGeneratedProguardFiles UP-TO-DATE
[  +28 ms] > Task :url_launcher:mergeDebugConsumerProguardFiles UP-TO-DATE
[  +12 ms] > Task :url_launcher:prepareLintJarForPublish UP-TO-DATE
[  +80 ms] > Task :url_launcher:mergeDebugJavaResource UP-TO-DATE
[   +3 ms] > Task :url_launcher:transformClassesAndResourcesWithSyncLibJarsForDebug UP-TO-DATE
[        ] > Task :url_launcher:transformNativeLibsWithSyncJniLibsForDebug UP-TO-DATE
[   +1 ms] > Task :url_launcher:bundleDebugAar UP-TO-DATE
[        ] > Task :url_launcher_web:extractDebugAnnotations UP-TO-DATE
[   +1 ms] > Task :url_launcher:mergeDebugResources UP-TO-DATE
[        ] > Task :url_launcher:compileDebugSources UP-TO-DATE
[   +1 ms] > Task :url_launcher:assembleDebug UP-TO-DATE
[   +3 ms] > Task :url_launcher_web:mergeDebugGeneratedProguardFiles UP-TO-DATE
[  +15 ms] > Task :url_launcher_web:mergeDebugConsumerProguardFiles UP-TO-DATE
[   +4 ms] > Task :url_launcher_web:prepareLintJarForPublish UP-TO-DATE
[   +2 ms] > Task :url_launcher_web:mergeDebugJavaResource UP-TO-DATE
[   +1 ms] > Task :url_launcher_web:transformClassesAndResourcesWithSyncLibJarsForDebug UP-TO-DATE
[        ] > Task :url_launcher_web:transformNativeLibsWithSyncJniLibsForDebug UP-TO-DATE
[        ] > Task :url_launcher_web:bundleDebugAar UP-TO-DATE
[        ] > Task :url_launcher_web:compileDebugSources UP-TO-DATE
[        ] > Task :url_launcher_web:assembleDebug UP-TO-DATE
[        ] BUILD SUCCESSFUL in 20s
[        ] 87 actionable tasks: 5 executed, 82 up-to-date
[ +495 ms] Running Gradle task 'assembleDebug'... (completed in 21.5s)
[  +56 ms] calculateSha: LocalDirectory:
'C:\Users\iapic\Documents\Code\Nevercode\eleventh_december\build\app\outputs\apk'/app.apk
[  +97 ms] calculateSha: reading file took 92us
[ +765 ms] calculateSha: computing sha took 764us
[   +7 ms] √ Built build\app\outputs\apk\debug\app-debug.apk.
[  +13 ms] executing: C:\Users\iapic\AppData\Local\Android\sdk\build-tools\28.0.3\aapt dump xmltree
C:\Users\iapic\Documents\Code\Nevercode\eleventh_december\build\app\outputs\apk\app.apk AndroidManifest.xml
[  +42 ms] Exit code 0 from: C:\Users\iapic\AppData\Local\Android\sdk\build-tools\28.0.3\aapt dump xmltree
C:\Users\iapic\Documents\Code\Nevercode\eleventh_december\build\app\outputs\apk\app.apk AndroidManifest.xml
[   +4 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.eleventh_december" (Raw: "com.example.eleventh_december")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="eleventh_december" (Raw: "eleventh_december")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")    
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.eleventh_december.MainActivity" (Raw:
                   "com.example.eleventh_december.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: intent-filter (line=35)
                     E: action (line=36)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=38)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")                 E: meta-data (line=45)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: activity (line=49)
                   A: android:theme(0x01010000)=@0x1030007
                   A: android:name(0x01010003)="io.flutter.plugins.urllauncher.WebViewActivity" (Raw:
                   "io.flutter.plugins.urllauncher.WebViewActivity")
                   A: android:exported(0x01010010)=(type 0x12)0x0
[  +92 ms] Stopping app 'app.apk' on Pixel 3a.
[  +18 ms] executing: C:\Users\iapic\AppData\Local\Android\sdk\platform-tools\adb.exe -s 965AY0WP5C shell am force-stop
com.example.eleventh_december
[ +163 ms] executing: C:\Users\iapic\AppData\Local\Android\sdk\platform-tools\adb.exe -s 965AY0WP5C shell pm list packages
com.example.eleventh_december
[ +149 ms] package:com.example.eleventh_december
[   +4 ms] executing: C:\Users\iapic\AppData\Local\Android\sdk\platform-tools\adb.exe -s 965AY0WP5C shell cat
/data/local/tmp/sky.com.example.eleventh_december.sha1
[ +135 ms] 13aef1a9dc242ee9e5eb70a753d76092f7a789f6
[   +2 ms] Installing APK.
[   +2 ms] executing: C:\Users\iapic\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +59 ms] Android Debug Bridge version 1.0.41
           Version 29.0.5-5949299
           Installed as C:\Users\iapic\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +2 ms] executing: C:\Users\iapic\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +64 ms] Installing build\app\outputs\apk\app.apk...
[   +8 ms] executing: C:\Users\iapic\AppData\Local\Android\sdk\platform-tools\adb.exe -s 965AY0WP5C install -t -r
C:\Users\iapic\Documents\Code\Nevercode\eleventh_december\build\app\outputs\apk\app.apk
[+4443 ms] Performing Streamed Install
                    Success
[   +1 ms] Installing build\app\outputs\apk\app.apk... (completed in 4.4s)
[   +2 ms] executing: C:\Users\iapic\AppData\Local\Android\sdk\platform-tools\adb.exe -s 965AY0WP5C shell echo -n
d06629609566396b47ffdff1cbf9504ab294c59b > /data/local/tmp/sky.com.example.eleventh_december.sha1
[  +73 ms] Pixel 3a startApp
[   +7 ms] executing: C:\Users\iapic\AppData\Local\Android\sdk\platform-tools\adb.exe -s 965AY0WP5C shell am start -a
android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez
enable-checked-mode true --ez verify-entry-points true com.example.eleventh_december/com.example.eleventh_december.MainActivity[ +148 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.eleventh_december/.MainActivity (hasextras) }
[   +1 ms] Waiting for observatory port to be available...
[ +604 ms] D/FlutterActivity(29911): Using the launch theme as normal theme.
[   +4 ms] D/FlutterActivityAndFragmentDelegate(29911): Setting up FlutterEngine.
[  +10 ms] D/FlutterActivityAndFragmentDelegate(29911): No preferred FlutterEngine was provided. Creating a new FlutterEngine
for this FlutterFragment.
[ +781 ms] D/FlutterActivityAndFragmentDelegate(29911): Attaching FlutterEngine to the Activity that owns this Fragment.
[  +85 ms] D/FlutterView(29911): Detaching from a FlutterEngine: null
[   +1 ms] D/FlutterView(29911): Not attached to an engine. Doing nothing.
[   +4 ms] D/FlutterView(29911): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@48e80fb
[  +36 ms] D/FlutterActivityAndFragmentDelegate(29911): Executing Dart entrypoint: main, and sending initial route: /
[ +233 ms] Observatory URL on device: http://127.0.0.1:41583/5E1Oi3QgBZI=/
[   +2 ms] executing: C:\Users\iapic\AppData\Local\Android\sdk\platform-tools\adb.exe -s 965AY0WP5C forward tcp:0 tcp:41583
[  +61 ms] 62794
[   +1 ms] Forwarded host port 62794 to device port 41583 for Observatory
[  +12 ms] Connecting to service protocol: http://127.0.0.1:62794/5E1Oi3QgBZI=/
[ +791 ms] Successfully connected to service protocol: http://127.0.0.1:62794/5E1Oi3QgBZI=/
[   +4 ms] Sending to VM service: getVM({})
[  +25 ms] Result: {type: VM, name: vm, architectureBits: 64, hostCPU: Qualcomm Technologies, Inc SDM670, operatingSystem:
android, targetCPU: arm64, version: 2.7.0-dev.2.1.flutter-8b8894648f (Mon Dec 9 13:45:47 2019 +0000) on "android_arm64",       
_profilerMode: VM, _na...
[  +12 ms] Sending to VM service: getIsolate({isolateId: isolates/1963739645523011})
[  +21 ms] Sending to VM service: _flutter.listViews({})
[  +14 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x766946b620, isolate: {type: @Isolate,fixedId: true, id: isolates/1963739645523011, name: main.dart$main-1963739645523011, number: 1963739645523011}}]}
[  +17 ms] DevFS: Creating new filesystem on the device (null)
[   +1 ms] Sending to VM service: _createDevFS({fsName: eleventh_december})
[  +42 ms] Result: {type: Isolate, id: isolates/1963739645523011, name: main, number: 1963739645523011, _originNumber:
1963739645523011, startTime: 1576064049163, _heaps: {new: {type: HeapSpace, name: new, vmName: Scavenger, collections: 0,      
avgCollectionPeriodMillis...
[ +142 ms] Result: {type: FileSystem, name: eleventh_december, uri:
file:///data/user/0/com.example.eleventh_december/code_cache/eleventh_decemberTAIZFL/eleventh_december/}
[   +1 ms] DevFS: Created new filesystem on the device
(file:///data/user/0/com.example.eleventh_december/code_cache/eleventh_decemberTAIZFL/eleventh_december/)
[  +16 ms] Updating assets
[ +134 ms] Syncing files to device Pixel 3a...
[   +3 ms] Scanning asset files
[  +18 ms] <- reset
[   +7 ms] Compiling dart to kernel with 0 updated files
[  +25 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe
C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter
-Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\iapic\AppData\Local\Temp\flutter_tool.12792a75-1c0a-11ea-919a-5800e3f99032\app.dill --packages
C:\Users\iapic\Documents\Code\Nevercode\eleventh_december\.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
[  +16 ms] <- compile package:eleventh_december/main.dart
[+7036 ms] Updating files
[ +188 ms] W/Gralloc3(29911): mapper 3.x is not supported
[   +5 ms] DevFS: Sync finished
[  +11 ms] Syncing files to device Pixel 3a... (completed in 7,309ms, longer than expected)
[   +4 ms] Synced 0.8MB.
[  +20 ms] Sending to VM service: _flutter.listViews({})
[   +4 ms] D/FlutterView(29911): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@48e80fb
[   +1 ms] D/FlutterView(29911): Already attached to this engine. Doing nothing.
[   +9 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x766946b620, isolate: {type: @Isolate,fixedId: true, id: isolates/1963739645523011, name: main.dart$main-1963739645523011, number: 1963739645523011}}]}
[  +18 ms] <- accept
[        ] Connected to _flutterView/0x766946b620.
[   +3 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[  +33 ms] An Observatory debugger and profiler on Pixel 3a is available at: http://127.0.0.1:62794/5E1Oi3QgBZI=/
[   +2 ms] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+4710 ms] D/FlutterView(29911): Detaching from a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@48e80fb
[+9726 ms] D/FlutterActivityAndFragmentDelegate(29911): Detaching FlutterEngine from the Activity that owns this Fragment.
[  +63 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
[   +5 ms] executing: C:\Users\iapic\AppData\Local\Android\sdk\platform-tools\adb.exe -s 965AY0WP5C forward --list
[  +31 ms] Exit code 0 from: C:\Users\iapic\AppData\Local\Android\sdk\platform-tools\adb.exe -s 965AY0WP5C forward --list
[        ] 965AY0WP5C tcp:62794 tcp:41583
[   +2 ms] executing: C:\Users\iapic\AppData\Local\Android\sdk\platform-tools\adb.exe -s 965AY0WP5C forward --remove tcp:62794
[  +66 ms] DevFS: Deleting filesystem on the device
(file:///data/user/0/com.example.eleventh_december/code_cache/eleventh_decemberTAIZFL/eleventh_december/)
[   +1 ms] Sending to VM service: _deleteDevFS({fsName: eleventh_december})
[ +260 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +3 ms] executing: C:\Users\iapic\AppData\Local\Android\sdk\platform-tools\adb.exe -s 965AY0WP5C forward --list
[  +55 ms] Exit code 0 from: C:\Users\iapic\AppData\Local\Android\sdk\platform-tools\adb.exe -s 965AY0WP5C forward --list
[   +5 ms] "flutter run" took 55,483ms.
PS C:\Users\iapic\Documents\Code\Nevercode\eleventh_december> 
```
  
</details>

could you please provide your  `flutter run --verbose` 
and  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by jwehrle** [comment]
Same problem here.

Verbose doctor:

[✓] Flutter (Channel dev, v1.13.0, on Mac OS X 10.15.1 19B88, locale en-US)
    • Flutter version 1.13.0 at /Users/johnwehrle/Flutter/flutter
    • Framework revision 09126abb22 (8 days ago), 2019-12-03 17:43:00 -0800
    • Engine revision 6179380243
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 a4d799c402)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/johnwehrle/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • Pixel 2                   • HT8671A02214  • android-arm64 • Android 10 (API 29)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 8.0.0 (API 26) (emulator)

• No issues found!
Process finished with exit code 0

**Comment by urmilshroff** [comment]
Same here

**Comment by juniorsistemasufms** [comment]
I'm the same problem.

**Comment by juniorsistemasufms** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':url_launcher:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':url_launcher:debugCompileClasspath'.
   > Could not resolve project :url_launcher_macos.
     Required by:
         project :url_launcher
      > Unable to find a matching configuration of project :url_launcher_macos:
          - None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by Brabalawuka** [comment]
This is because the latest dev channel release the lock to macos support and some library may have error.

I reliased that ```flutter stable``` has upgraded to ```v1.12.13+hotfix.5```

So for those only develop Android and iOS apps, if you are using ```dev``` or ```beta```, you can change to stable channel by

```flutter channel stable``` then
run ```fltter clean``` then ```flutter upgrade```,

My error get solved with ```url_launcher: ^5.4.1```

**Comment by jwehrle** [comment]
That may have fixed it for me - I'm still getting some other errors for different libraries but this one seems to be gone. Thanks!

**Comment by marinat** [comment]
@Brabalawuka After upgrading to flutter stable v1.12.13+hotfix.5 I started to get this error.

**Comment by pr-Mais** [comment]
I'm getting a similar error and tried all possible solutions but didn't work.

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'flutter_image_compress'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/mais/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_image_compress-0.6.3/android/local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 417ms


The plugin flutter_image_compress could not be built due to the issue above.
```

**Comment by Saifallak** [comment]
> I'm getting a similar error and tried all possible solutions but didn't work.
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring root project 'flutter_image_compress'.
> > SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/mais/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_image_compress-0.6.3/android/local.properties'.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 417ms
> 
> 
> The plugin flutter_image_compress could not be built due to the issue above.
> ```

simply add "ANDROID_SDK_ROOT" in your path

**Comment by tudor07** [comment]
I downgraded to `url_launcher: 5.3.0` and it works (this is the version before they added macOS support). Also this is true for all plugins that added macOS support (shared_preferences is another one).

**Comment by webtfdml** [comment]
Same issue. I have tried all of the proposed fixes above. This all began after upgrading to 1.12.13. 

Getting the following:

```
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Could not determine the dependencies of task ':url_launcher:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':url_launcher:debugCompileClasspath'.
   > Could not resolve project :url_launcher_macos.                     
     Required by:                                                       
         project :url_launcher                                          
      > Unable to find a matching configuration of project :url_launcher_macos:
          - None of the consumable configurations have attributes.      
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org         
```
Verbose Doctor:

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale en-US)
    • Flutter version 1.12.13+hotfix.5 at /Users/mjones/dev/flutter
    • Framework revision 27321ebbad (2 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mjones/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
```

**Comment by pratikpparikh** [comment]
@amirh can you please help us understand the right configuration to use in pubspec to correctly use the latest version?

**Comment by jwehrle** [comment]
I tried `flutter pub cache repair` and, even though the cache repair ultimately failed on an unused package it did fix this problem and I was able to build. I don't actually know why invalidating caches and refetching them doesn't do the same thing but my project is now building. Just passing this along.

https://github.com/FirebaseExtended/flutterfire/issues/1615#issuecomment-564902839``

**Comment by webtfdml** [comment]
So... Upgrading the compileSdkVersion to 28 in build.gradle fixed my problem.

**Comment by hqwlkj** [comment]
Hi @marinat  !

I also encountered this problem.

Have your questions been dealt with?

**Comment by marinat** [comment]
Hi @hqwlkj 
No, still trying every workarounds :(

**Comment by hqwlkj** [comment]
@marinat 

I used the newly created project, re-added the dependencies and ran it without reproducing the above error message.


```

MacBook-Pro app % flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.5 at /usr/local/flutter
    • Framework revision 27321ebbad (2 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/yanghc/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 42.0.4
    • Dart plugin version 193.5731

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 297F1EBD-45F0-42E7-845B-2BD64E4A74BC • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

• No issues found!


```

**Comment by marinat** [comment]
@hqwlkj But what to do with existing project? :)

**Comment by marinat** [comment]
Removed project from disk, got it from git - problem gone.

**Comment by amirh** [comment]
The issue should now be resolved, if you're hitting the failure please run `flutter pub upgrade` to upgrade to the latest version of all packages.

If you're still hitting the issue after upgrading your project's dependencies please leave a comment on: https://github.com/flutter/flutter/issues/46898

**Comment by pratikpparikh** [comment]
thank you @amirh

**Comment by therealphatmike** [comment]
For reference for anyone that comes across this in the future:

I removed the `settings_aar.gradle` and `AndroidManifest.xml` files and was able to rebuild.

**Comment by ihsanalgul** [comment]
> **Quick Slove**
> This is because the latest dev channel release the lock to macos support and some library may have error.
> 
> I reliased that `flutter stable` has upgraded to `v1.12.13+hotfix.5`
> 
> So for those only develop Android and iOS apps, if you are using `dev` or `beta`, you can change to stable channel by
> 
> `flutter channel stable` then
> run `fltter clean` then `flutter upgrade`,
> 
> My error get solved with `url_launcher: ^5.4.1`

In my case it also worked. Thanks a lot. But I still have a problem with this..below..

Note: /Users/username/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.10/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by yourshinsuke** [comment]
Why closed?
it also happned

```
url_launcher-5.4.10/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java
```

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by evanezcent** [comment]
Try `flutter pub cache repair`, it's work for me
