### ISSUE TITLE
`_resolveImage` should be smarter about whether the image has actually changed or not

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#47383]
The `_ImageState` class tries to resolve the image every time it is rebulit/dependencies change.

This works fine when the image is in the cache.  However, we should also try to make it work if the image is still available in the render tree (i.e. the image is still on screen or almost on screen), but not in the cache.

This could possibly be achieved by having some object that tracks on-screen ui.Images, perhaps one that `RenderImage` adds its images to and removes from when it's `detach`ed.

/cc @gaaclarke @liyuqian @goderbauer @Hixie @cbracken @zmtzawqlp @jonahwilliams

**Comment by dnfield** [comment]
What I think we'd want for this is to have some way for the widget to check if the `PictureProvider.obtainKey` key has changed between states.  If not, then just reuse its render object's image. So before we call `image.resolve`, we'd want to do something like `widget.image.obtainKey` and see if the key has changed from the old key.

Where the widget state tries to resolve the image:

https://github.com/flutter/flutter/blob/beb86d2cc408eb54d92ab96ddef8a8fb69182071/packages/flutter/lib/src/widgets/image.dart#L1008-L1016

Where `ImageProvider` resolves the image:

https://github.com/flutter/flutter/blob/beb86d2cc408eb54d92ab96ddef8a8fb69182071/packages/flutter/lib/src/painting/image_provider.dart#L274-L336

**Comment by dnfield** [comment]
xref https://github.com/flutter/flutter/pull/46357 and https://github.com/flutter/flutter/issues/47380

With this logic, we could be less concerned about whether the image is "long term" cached in the ImageCache, making it easier to work on those issues.

**Comment by liyuqian** [comment]
Thank you @dnfield for the proposal! If the fix you suggested were implemented, I wonder if one of our existing driver/performance tests (with ImageCache size set to 0) would reveal the improvement? If not, it might be helpful to first come up with a test. It would also help us understand exactly what the problem looks like.

**Comment by dnfield** [comment]
Does the existing test you wrote to capture memory usage while scrolling track memory _during_ the scrolling, or only at the end?

**Comment by dnfield** [comment]
Alternatively, I would expect us to perform much better with this change and cache size set to 0 on any of the existing tests (we'd not be decoding images every frame).  But I'm not sure if we have any tests that set the size to 0 - if not it should be esay to add one.

**Comment by liyuqian** [comment]
My test doesn't track memory during the scrolling. I expect that it would become easy to track the memory during the scroll after https://github.com/flutter/flutter/issues/44013 is solved.

For now, I agree that modifying one of our existing test and setting its cache size to 0 is promising.

**Comment by dnfield** [comment]
Hmm.  I'm doing some pretty simple testing here and I'm having a hard time finding a case where we end up calling `_resolveImage` while the widget/render object are still in the tree.

I could probably contrive an example to try to force it to happen, but I'm having trouble coming up with one that would occur naturally.

For a simple case of a grid or list view of images, just scrolling isn't enough to trigger this.

**Comment by gaaclarke** [comment]
@dnfield I just spent some time trying to create a pathological case too and I also couldn't get `_resolveImage` to get called again either.  I created a custom ImageCache that throws everything out and triggered `build` on the StatefulWidget which was the parent to the AssetImage.

You know more about how the framework works, is this a non-issue because of the caching mechanism that appears to be at work at a higher level?

**Comment by dnfield** [comment]
I'm pretty sure there's _some_ path where this happens, and we should fix it, but at this point I'm also convinced that such a path is unlikely to arise in normal usage.

**Comment by dnfield** [comment]
I found a way to make this happen.  If you subscribe the image widget to some inherited widget, didChangeDependencies will get called when that widget changes, which could result in trying to resolve the image multiple times.

We don't currently do this in the image widget and it's not clear to me that we ever will.  We should still fix this issue, but I still don't think it's a pressong one.

**Comment by dnfield** [comment]
I'm going to close this as a less interesting sub-issue of #49456 - fixing that issue will fix this one, and this one is a bit too narrowly scoped to be a serious issue anyway.
