### ISSUE TITLE
[android] on "app exit" : Runtime exception at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative

### ISSUE THREAD

**Issue by hosaysg** [flutter/flutter#48063]
Below is the Flutter/Dart version I am using.   

```console
 • Flutter version 1.12.13+hotfix.5 
 • Framework revision 27321ebbad
 • Engine revision 2994f7e1e6
 • Dart version 2.7.0
```

Here is the crash log:

```bash
java.lang.RuntimeException: 
  at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative (Unknown Source:9)
  at io.flutter.embedding.engine.FlutterJNI.markTextureFrameAvailable (Unknown Source:3)
  at io.flutter.embedding.engine.h.a.a (Unknown Source:2)
  at io.flutter.embedding.engine.h.a.a (Unknown Source)
  at io.flutter.embedding.engine.h.a$b$a.onFrameAvailable (Unknown Source:17)
  at android.graphics.SurfaceTexture$1.handleMessage (SurfaceTexture.java:206)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7073)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)

```
I am unable to reproduce this as I did not experience the issue myself. From the console, it seems to be affecting Android 8/9 users.  Kindly advise how I can resolve this.

**Comment by iapicca** [comment]
Hi @hosaysg 
the issue it's hardly workable without steps to reproduce
are you experiencing crashes in debug?
thank you

**Comment by hosaysg** [comment]
> Hi @hosaysg
> the issue it's hardly workable without steps to reproduce
> are you experiencing crashes in debug?
> thank you

No thus I did not know this issue exists till I check google play console. I just submitted a new version with Firebase Crashlytics but I am not sure if that is going to help.

**Comment by jmagman** [comment]
Maybe https://github.com/flutter/flutter/issues/30952.  Is there an error message in the crash log in addition to that stack?

**Comment by hosaysg** [comment]
> Maybe #30952. Is there an error message in the crash log in addition to that stack?

No. I did not use the connectivity package in my app.

**Comment by hosaysg** [comment]
Firebase Crashlytics doesn't help much as I am seeing the same error. 

Fatal Exception: java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
       at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(:9)
       at io.flutter.embedding.engine.FlutterJNI.markTextureFrameAvailable(:3)
       at io.flutter.embedding.engine.h.a.a(:2)
       at io.flutter.embedding.engine.h.a.a()
       at io.flutter.embedding.engine.h.a$b$a.onFrameAvailable(:17)
       at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:206)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:7025)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by hosaysg** [comment]
Finally managed to reproduce the issue. It happens when the back button is tapped and the app exit. This is the full stack trace.

Fatal Exception: java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
       at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:227)
       at io.flutter.embedding.engine.FlutterJNI.markTextureFrameAvailable(FlutterJNI.java:554)
       at io.flutter.embedding.engine.renderer.FlutterRenderer.markTextureFrameAvailable(FlutterRenderer.java:274)
       at io.flutter.embedding.engine.renderer.FlutterRenderer.access$300(FlutterRenderer.java:38)
       at io.flutter.embedding.engine.renderer.FlutterRenderer$SurfaceTextureRegistryEntry$1.onFrameAvailable(FlutterRenderer.java:145)
       at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:206)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by iapicca** [comment]
Hi @hosaysg 
since you managed to reproduce the issue
could you provide a minimal sample code or the steps to reproduce it?
thank you

possibly related to https://github.com/flutter/flutter/issues/48039

**Comment by bhan** [comment]
Hi @hosaysg 

Please see https://github.com/flutter/flutter/issues/48015. There are two commits you can compare to see if we are running into the same bug.

**Comment by hosaysg** [comment]
> Hi @hosaysg
> 
> Please see #48015. There are two commits you can compare to see if we are running into the same bug.

I have managed to isolated the issue to the Admob Banner view.  An issue has been filed.  Thanks for all the help here. 

[https://github.com/kmcgill88/admob_flutter/issues/118
](url)

**Comment by frasker** [comment]
I find  FlutterRenderer method release() never invoked ，it should be a bug in package io.flutter.embedding.android ，i fix it by following code 
```
class FixFlutterActivity : FlutterActivity() {

    override fun onDestroy() {
        flutterEngine?.platformViewsController?.onFlutterViewDestroyed()
        super.onDestroy()
    }

    companion object {
        fun createIntent(context: Context, initialRoute: String = "/"): Intent {
            return Intent(context, FixFlutterActivity::class.java)
                    .putExtra("initial_route", initialRoute)
                    .putExtra("background_mode", "opaque")
                    .putExtra("destroy_engine_with_activity", true)
        }
    }
}
```

**Comment by sanekyy** [comment]
Same issue

```
Flutter 1.14.6 • channel dev • https://github.com/flutter/flutter.git
Framework • revision fabeb2a16f (8 days ago) • 2020-01-28 07:56:51 -0800
Engine • revision c4229bfbba
Tools • Dart 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)
```
![image](https://user-images.githubusercontent.com/18647037/73830521-ddbebf00-4815-11ea-880b-919994004f94.png)

**Comment by TAMILSELVAN943** [comment]
![Screenshot_20200205-115123](https://user-images.githubusercontent.com/59245291/73843132-08277100-4844-11ea-96cb-57fc03d4b52d.jpg)
Why this error comes Pls replay em

**Comment by xalikoutis** [comment]
same problem i am using webview

**Comment by singun-lxd** [comment]
I've meet the same crash...

**Comment by musathegeek** [comment]
same crash in release, especially android 9 users

**Comment by singun-lxd** [comment]
> I find FlutterRenderer method release() never invoked ，it should be a bug in package io.flutter.embedding.android ，i fix it by following code
> 
> ```
> class FixFlutterActivity : FlutterActivity() {
> 
>     override fun onDestroy() {
>         flutterEngine?.platformViewsController?.onFlutterViewDestroyed()
>         super.onDestroy()
>     }
> 
>     companion object {
>         fun createIntent(context: Context, initialRoute: String = "/"): Intent {
>             return Intent(context, FixFlutterActivity::class.java)
>                     .putExtra("initial_route", initialRoute)
>                     .putExtra("background_mode", "opaque")
>                     .putExtra("destroy_engine_with_activity", true)
>         }
>     }
> }
> ```
> 
> ps: this crash happens when i use flutter-webview

can this code fix the crash?

**Comment by kmfish** [comment]
I met same crash. I wrote a demo for reproduce it. And give a workaround same as @frasker 

see details：https://github.com/kmfish/FlutterPlatformViewDemo

**Comment by pamir72** [comment]
We use PageView with BottomNavigationBar and always meet this issue when exit app from page with google map. I consider this the hardest issue not allowing us to use flutter for public applications :-(

**Comment by Omi231** [comment]
This issue has ruined by app rating on playstore. Today i am regretting using flutter...

**Comment by jmagman** [comment]
This is engine code, not plugin.
\cc @jason-simmons

**Comment by jmagman** [comment]
\cc @matthew-carroll (not sure if you're still looking at any of this)

**Comment by matthew-carroll** [comment]
I haven't been looking into this issue. I know for a while the reports seemed to be coming from people using non-released versions of the new embedding. I'm not sure what the current state of the issue really is.

**Comment by sanekyy** [comment]
@matthew-carroll 
This issue still happens on latest a Flutter on dev channel.

**Comment by frasker** [comment]
> > I find FlutterRenderer method release() never invoked ，it should be a bug in package io.flutter.embedding.android ，i fix it by following code
> 
> > 
> 
> > ```
> 
> > class FixFlutterActivity : FlutterActivity() {
> 
> > 
> 
> >     override fun onDestroy() {
> 
> >         flutterEngine?.platformViewsController?.onFlutterViewDestroyed()
> 
> >         super.onDestroy()
> 
> >     }
> 
> > 
> 
> >     companion object {
> 
> >         fun createIntent(context: Context, initialRoute: String = "/"): Intent {
> 
> >             return Intent(context, FixFlutterActivity::class.java)
> 
> >                     .putExtra("initial_route", initialRoute)
> 
> >                     .putExtra("background_mode", "opaque")
> 
> >                     .putExtra("destroy_engine_with_activity", true)
> 
> >         }
> 
> >     }
> 
> > }
> 
> > ```
> 
> > 
> 
> > ps: this crash happens when i use flutter-webview
> 
> 
> 
> Can you tell us could the crash fixed by this code?

Yes

**Comment by Omi231** [comment]
Any update about the issue?

**Comment by ozzy1873** [comment]
I got this error using a stable channel release.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by leocornillon** [comment]
@frasker is right in his comment, his solution worked for me too. My guess is that this bug was shipped in a fairly new version of Flutter. If we take a look at the Flutter Main Activity located under `android/app/src/main`:

An old project I made a while ago, working perfectly fine with plateform_views
```kotlin
package com.example.sample_app

import android.os.Bundle

import io.flutter.app.FlutterActivity
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    GeneratedPluginRegistrant.registerWith(this)
  }
}
```

The new MainActivity.kt obtained with flutter create on the stable branch:
```kotlin
package com.example.sample_app

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}
```
Overriding the destroy method to properly take care of plateform_views should resolve the problem:
```kotlin
package com.example.sample_app

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {

    override fun onDestroy() {
        flutterEngine?.platformViewsController?.onFlutterViewDestroyed()
        super.onDestroy()
    }
    
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}
```

**Comment by lidongze91** [comment]
We have a similar issue that the app crashes on "app exit". This is after the fix I suppose. The log messages are here: `04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.maps.api.android.lib6.impl.bp.q()' on a null object reference
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at com.google.maps.api.android.lib6.impl.cw.d(:com.google.android.gms.dynamite_mapsdynamite@201216065@20.12.16 (100400-0):1)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at com.google.android.gms.maps.internal.q.a(:com.google.android.gms.dynamite_mapsdynamite@201216065@20.12.16 (100400-0):12)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at ch.onTransact(:com.google.android.gms.dynamite_mapsdynamite@201216065@20.12.16 (100400-0):4)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at android.os.Binder.transact(Binder.java:667)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at com.google.android.aidl.BaseProxy.transactAndReadExceptionReturnVoid(BaseProxy.java:65)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at com.google.android.gms.maps.internal.IMapViewDelegate$Stub$Proxy.onDestroy(IMapViewDelegate.java:218)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at com.google.android.gms.maps.MapView$MapViewDelegate.onDestroy(MapView.java:176)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at com.google.android.gms.dynamic.DeferredLifecycleHelper.onDestroy(DeferredLifecycleHelper.java:410)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at com.google.android.gms.maps.MapView.onDestroy(MapView.java:411)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at io.flutter.plugins.googlemaps.GoogleMapController.dispose(GoogleMapController.java:541)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at io.flutter.plugin.platform.VirtualDisplayController.dispose(VirtualDisplayController.java:163)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at io.flutter.plugin.platform.PlatformViewsController.flushAllViews(PlatformViewsController.java:533)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at io.flutter.plugin.platform.PlatformViewsController.onDetachedFromJNI(PlatformViewsController.java:422)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:293)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:500)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterFragment.onDetach(FlutterFragment.java:640)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at android.support.v4.app.Fragment.performDetach(Fragment.java:3046)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at android.support.v4.app.FragmentStateManager.detach(FragmentStateManager.java:711)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at android.support.v4.app.FragmentManager.moveToState(FragmentManager.java:1363)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at android.support.v4.app.FragmentManager.moveToState(FragmentManager.java:1417)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at android.support.v4.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1495)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at android.support.v4.app.FragmentManager.moveToState(FragmentManager.java:1561)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at android.support.v4.app.FragmentManager.dispatchStateChange(FragmentManager.java:2805)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at android.support.v4.app.FragmentManager.dispatchDestroy(FragmentManager.java:2789)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:334)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:367)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at android.app.Activity.performDestroy(Activity.java:7395)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1306)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4443)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	... 11 more`.

I suppose this only relates to google map plugin, it hit null exception while trying to destroy the mapview.

**Comment by xster** [comment]
Trying to collect some more info

The issues above should have been fixed by #17379 which is now in 1.18.0-dev.0.0

Can anyone confirm? 

If it's still not fixed, it seems like the issue should only be reproducible with a plugin. Seems like above comments mentioned webview and google maps. Is that the repro? 

Also, are people using add-to-app only for this? Which UI component is being used? FlutterActivity? FlutterFragment? FlutterFragmentActivity?

@lidongze91 says his crashing line is

`04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at com.google.android.gms.maps.MapView$MapViewDelegate.onDestroy(MapView.java:176)`

**Comment by xster** [comment]
For @lidongze91's issue, I have a suspicious that all these setters for listeners we're setting in https://github.com/flutter/plugins/blob/c2f74efb9daaf22e2f1854f41d7ed35e40a7a5b6/packages/google_maps_flutter/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java#L207 but that doesn't seem to be removed looks suspicious.

**Comment by xster** [comment]
Looking into this a bit. Since the original issue is referencing the general platform view issue and it's since been fixed in https://github.com/flutter/engine/pull/17379, I'm closing this issue. I'm splitting https://github.com/lidongze91's issue into https://github.com/flutter/flutter/issues/55406 since it's a google maps plugin specific issue.

**Comment by Omi231** [comment]
> @frasker is right in his comment, his solution worked for me too. My guess is that this bug was shipped in a fairly new version of Flutter. If we take a look at the Flutter Main Activity located under `android/app/src/main`:
> 
> An old project I made a while ago, working perfectly fine with plateform_views
> 
> ```kotlin
> package com.example.sample_app
> 
> import android.os.Bundle
> 
> import io.flutter.app.FlutterActivity
> import io.flutter.plugins.GeneratedPluginRegistrant
> 
> class MainActivity: FlutterActivity() {
>   override fun onCreate(savedInstanceState: Bundle?) {
>     super.onCreate(savedInstanceState)
>     GeneratedPluginRegistrant.registerWith(this)
>   }
> }
> ```
> 
> The new MainActivity.kt obtained with flutter create on the stable branch:
> 
> ```kotlin
> package com.example.sample_app
> 
> import androidx.annotation.NonNull;
> import io.flutter.embedding.android.FlutterActivity
> import io.flutter.embedding.engine.FlutterEngine
> import io.flutter.plugins.GeneratedPluginRegistrant
> 
> class MainActivity: FlutterActivity() {
>     override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
>         GeneratedPluginRegistrant.registerWith(flutterEngine);
>     }
> }
> ```
> 
> Overriding the destroy method to properly take care of plateform_views should resolve the problem:
> 
> ```kotlin
> package com.example.sample_app
> 
> import androidx.annotation.NonNull;
> import io.flutter.embedding.android.FlutterActivity
> import io.flutter.embedding.engine.FlutterEngine
> import io.flutter.plugins.GeneratedPluginRegistrant
> 
> class MainActivity: FlutterActivity() {
> 
>     override fun onDestroy() {
>         flutterEngine?.platformViewsController?.onFlutterViewDestroyed()
>         super.onDestroy()
>     }
>     
>     override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
>         GeneratedPluginRegistrant.registerWith(flutterEngine);
>     }
> }
> ```

I used your fix in flutter 1.16 and it solved the problem but after upgrading to flutter 1.18 it is giving me build error about the code your provided to add. I removed it and it is now running. I want to make sure that is this issue fixed in flutter 1.18 and I should remove that code?

**Comment by jezsung** [comment]
Does this issue ruin user experience? I don't know how it is seen to users.

**Comment by karmazinkd** [comment]
@frasker  how can I implement your workaround if I'm on v2 embedding and we don't override FlutterActivity ?
Our AndroidManifest.xml looks like this:
```
<application
        android:name="io.flutter.app.FlutterApplication"
        android:allowBackup="false"
        android:icon="@mipmap/ic_launcher"
        android:label="MyApp"
        tools:replace="android:allowBackup">

        <activity
            android:name="io.flutter.embedding.android.FlutterActivity"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:windowSoftInputMode="adjustResize">
```

**Comment by EricMikaelson** [comment]
“**flutterEngine?.platformViewsController?.detachFromView()**”， This API I recommend！

"**flutterEngine?.platformViewsController?.onFlutterViewDestroyed()**"，This API I don't recommend !

because, ‘ onFlutterViewDestroyed’ will released vdControllers HashMap，and cause a new exception："**java.lang.IllegalStateException: Trying to dispose a platform view with unknown id: 10**"

Exception details
```
PlatformException(error, java.lang.IllegalStateException: Trying to dispose a platform view with unknown id: 10
	at io.flutter.plugin.platform.PlatformViewsController$1._41_abev(PlatformViewsController.java:157)
	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1._41_addn(PlatformViewsChannel.java:105)
	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1._41_ac(PlatformViewsChannel.java:62)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler._41_aaxz(MethodChannel.java:226)
	at io.flutter.embedding.engine.dart.DartMessenger._41_aayf(DartMessenger.java:85)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:184)
	at android.app.ActivityThread.main(ActivityThread.java:7840)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:985)
```

Location Code 
```PlatformViewsController.java
        @Override
        public void disposePlatformView(int viewId) {
          ensureValidAndroidVersion();

          VirtualDisplayController vdController = vdControllers.get(viewId);
          if (vdController == null) {
            throw new IllegalStateException(
                "Trying to dispose a platform view with unknown id: " + viewId);
          }

          if (textInputPlugin != null) {
            textInputPlugin.clearPlatformViewClient(viewId);
          }

          contextToPlatformView.remove(vdController.getView().getContext());
          vdController.dispose();
          vdControllers.remove(viewId);
        }
```

**Comment by ayush221b** [comment]
@EricMikaelson I added the following code in my MainAcitivity.kt

```
override fun onDestroy() {
        flutterEngine?.platformViewsController?.detachFromView()
        super.onDestroy()
    }
```

but I am still seeing this crash:

```
10-01 10:24:13.843 26615 26615 E AndroidRuntime: FATAL EXCEPTION: main
10-01 10:24:13.843 26615 26615 E AndroidRuntime: Process: io.connectcourses.app, PID: 26615
10-01 10:24:13.843 26615 26615 E AndroidRuntime: java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
10-01 10:24:13.843 26615 26615 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:2)
10-01 10:24:13.843 26615 26615 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterJNI.markTextureFrameAvailable(FlutterJNI.java:2)
10-01 10:24:13.843 26615 26615 E AndroidRuntime: 	at io.flutter.embedding.engine.h.a.a(FlutterRenderer.java:22)
10-01 10:24:13.843 26615 26615 E AndroidRuntime: 	at io.flutter.embedding.engine.h.a.a(FlutterRenderer.java:2)
10-01 10:24:13.843 26615 26615 E AndroidRuntime: 	at io.flutter.embedding.engine.h.a$b$a.onFrameAvailable(FlutterRenderer.java:2)
10-01 10:24:13.843 26615 26615 E AndroidRuntime: 	at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:211)
10-01 10:24:13.843 26615 26615 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
10-01 10:24:13.843 26615 26615 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
10-01 10:24:13.843 26615 26615 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7710)
10-01 10:24:13.843 26615 26615 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-01 10:24:13.843 26615 26615 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
10-01 10:24:13.843 26615 26615 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

I am running the latest Flutter stable release:
```
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-IN)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.2)
[✓] Connected device (1 available)
```

Any ideas on what I might be missing? Thanks in advance.

**Comment by aknolldev** [comment]
We experienced a similar issue. The setup is as follows:

- Flutter module is used in a host native app (add to app)

- MainActivity starts FlutterActivity

- FlutterActivity is visible

- Push Notification comes in

- Tapping the push notification starts the MainActivity via intent

- App crashes

Logs:
`    --------- beginning of crash
2020-10-06 12:38:28.647 24965-24965/com.grohe.smarthome.v2.staging E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.grohe.smarthome.v2.staging, PID: 24965
    java.lang.RuntimeException: Unable to destroy activity {com.grohe.smarthome.v2.staging/io.flutter.embedding.android.FlutterActivity}: java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4941)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4970)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
        at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:259)
        at io.flutter.embedding.engine.FlutterJNI.onSurfaceDestroyed(FlutterJNI.java:369)
        at io.flutter.embedding.engine.renderer.FlutterRenderer.stopRenderingToSurface(FlutterRenderer.java:219)
        at io.flutter.embedding.android.FlutterView.detachFromFlutterEngine(FlutterView.java:1005)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDestroyView(FlutterActivityAndFragmentDelegate.java:462)
        at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:576)
        at android.app.Activity.performDestroy(Activity.java:8048)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1334)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4926)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4970) 
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) `

**Comment by ahzmie** [comment]
I got the same crash only when clicking the back button till the exit of the app (on Destroy activity).
The crash only happened after I have used the HMS SDK (Huawei Sdk):

`java.lang.RuntimeException: 
  at android.app.ActivityThread.performDestroyActivity (ActivityThread.java:5456)
  at android.app.ActivityThread.handleDestroyActivity (ActivityThread.java:5493)
  at android.app.servertransaction.DestroyActivityItem.execute (DestroyActivityItem.java:44)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2267)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:8167)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:496)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1100)
Caused by: java.lang.NullPointerException: 
  at com.huawei.hms.flutter.account.HmsAccountPlugin.onDetachedFromEngine (HmsAccountPlugin.java:55)
  at io.flutter.embedding.engine.FlutterEnginePluginRegistry.remove (FlutterEnginePluginRegistry.java:252)
  at io.flutter.embedding.engine.FlutterEnginePluginRegistry.remove (FlutterEnginePluginRegistry.java:260)
  at io.flutter.embedding.engine.FlutterEnginePluginRegistry.removeAll (FlutterEnginePluginRegistry.java:268)
  at io.flutter.embedding.engine.FlutterEnginePluginRegistry.destroy (FlutterEnginePluginRegistry.java:112)
  at io.flutter.embedding.engine.FlutterEngine.destroy (FlutterEngine.java:360)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach (FlutterActivityAndFragmentDelegate.java:522)
  at io.flutter.embedding.android.FlutterActivity.onDestroy (FlutterActivity.java:578)
  at android.app.Activity.performDestroy (Activity.java:8225)
  at android.app.Instrumentation.callActivityOnDestroy (Instrumentation.java:1342)
  at android.app.ActivityThread.performDestroyActivity (ActivityThread.java:5441)`

**Comment by ChopinDavid** [comment]
It seems that `flutterEngine?.platformViewsController?.onFlutterViewDestroyed()` has been renamed in Flutter 1.22.0. Anybody know what it was renamed to?

**Comment by Fatimamostafa** [comment]
> It seems that `flutterEngine?.platformViewsController?.onFlutterViewDestroyed()` has been renamed or no longer exists in Flutter 1.22.0. Anybody know what `.onFlutterViewDestroyed()` was renamed to, or what happened to it?

This worked for me

```
    override fun onDestroy() {
        flutterEngine?.platformViewsController?.detach()
        super.onDestroy()
    }
```

**Comment by jmagman** [comment]
> It seems that `flutterEngine?.platformViewsController?.onFlutterViewDestroyed()` has been renamed or no longer exists in Flutter 1.22.0. Anybody know what `.onFlutterViewDestroyed()` was renamed to, or what happened to it?

`onFlutterViewDestroyed` was removed with https://github.com/flutter/engine/pull/17379 in version 1.18.0-6.0.pre, which closed this issue.
