### ISSUE TITLE
crash bug: io.flutter.view.AccessibilityBridge 

### ISSUE THREAD

**Issue by AlexNW** [flutter/flutter#48573]
java.lang.NullPointerException: Attempt to read from field 'int io.flutter.view.AccessibilityBridge$SemanticsNode.platformViewId' on a null object reference

	at io.flutter.view.AccessibilityBridge$SemanticsNode.access$1400(AccessibilityBridge.java:1710)

	at io.flutter.view.AccessibilityBridge.onAccessibilityHoverEvent(AccessibilityBridge.java:1129)

	at io.flutter.view.FlutterView.onHoverEvent(FlutterView.java:462)

	at android.view.View.dispatchHoverEvent(View.java:12821)

	at android.view.View.dispatchGenericMotionEvent(View.java:12738)

	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2524)

	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2157)

	at android.view.View.dispatchGenericMotionEvent(View.java:12738)

	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2524)

	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2157)

	at android.view.View.dispatchGenericMotionEvent(View.java:12738)

	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2524)

	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2157)

	at android.view.View.dispatchGenericMotionEvent(View.java:12738)

	at com.android.internal.policy.DecorView.superDispatchGenericMotionEvent(DecorView.java:573)

	at com.android.internal.policy.PhoneWindow.superDispatchGenericMotionEvent(PhoneWindow.java:1939)

	at android.app.Activity.dispatchGenericMotionEvent(Activity.java:3630)

	at com.android.internal.policy.DecorView.dispatchGenericMotionEvent(DecorView.java:532)

	at android.view.View.dispatchPointerEvent(View.java:12879)

	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5771)

	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5535)

	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4983)

	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5036)

	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5002)

	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5157)

	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5010)

	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5214)

	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4983)

	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5036)

	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5002)

	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5010)

	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4983)

	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7803)

	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7768)

	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7726)

	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8007)

	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:202)

	at android.os.MessageQueue.nativePollOnce(Native Method)

	at android.os.MessageQueue.next(MessageQueue.java:386)

	at android.os.Looper.loop(Looper.java:175)

	at android.app.ActivityThread.main(ActivityThread.java:7625)

	at java.lang.reflect.Method.invoke(Native Method)

	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)

	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by jonahwilliams** [comment]
This looks like an issue we fixed many months ago - Please include the output of `flutter doctor -v`.

**Comment by 33-Elephants** [comment]
Just have received a couple of similar crashes:

```
java.lang.NullPointerException: 
   at io.flutter.view.AccessibilityBridge$SemanticsNode.access$1400 (AccessibilityBridge.java:1774)
   at io.flutter.view.AccessibilityBridge.onAccessibilityHoverEvent (AccessibilityBridge.java:1156)
   at io.flutter.view.FlutterView.onHoverEvent (FlutterView.java:461)
   at android.view.View.dispatchHoverEvent (View.java:11962)
   at android.view.View.dispatchGenericMotionEvent (View.java:11879)
   at android.view.ViewGroup.dispatchTransformedGenericPointerEvent (ViewGroup.java:2453)
   at android.view.ViewGroup.dispatchHoverEvent (ViewGroup.java:2086)
   at android.view.View.dispatchGenericMotionEvent (View.java:11879)
   at android.view.ViewGroup.dispatchTransformedGenericPointerEvent (ViewGroup.java:2453)
   at android.view.ViewGroup.dispatchHoverEvent (ViewGroup.java:2086)
   at android.view.View.dispatchGenericMotionEvent (View.java:11879)
   at android.view.ViewGroup.dispatchTransformedGenericPointerEvent (ViewGroup.java:2453)
   at android.view.ViewGroup.dispatchHoverEvent (ViewGroup.java:2086)
   at android.view.View.dispatchGenericMotionEvent (View.java:11879)
   at com.android.internal.policy.DecorView.superDispatchGenericMotionEvent (DecorView.java:485)
   at com.android.internal.policy.PhoneWindow.superDispatchGenericMotionEvent (PhoneWindow.java:1845)
   at android.app.Activity.dispatchGenericMotionEvent (Activity.java:3362)
   at com.android.internal.policy.DecorView.dispatchGenericMotionEvent (DecorView.java:453)
   at android.view.View.dispatchPointerEvent (View.java:12020)
   at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent (ViewRootImpl.java:4829)
   at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess (ViewRootImpl.java:4643)
   at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4181)
   at android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4234)
   at android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4200)
   at android.view.ViewRootImpl$AsyncInputStage.forward (ViewRootImpl.java:4327)
   at android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:4208)
   at android.view.ViewRootImpl$AsyncInputStage.apply (ViewRootImpl.java:4384)
   at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4181)
   at android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4234)
   at android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4200)
   at android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:4208)
   at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4181)
   at android.view.ViewRootImpl.deliverInputEvent (ViewRootImpl.java:6744)
   at android.view.ViewRootImpl.doProcessInputEvents (ViewRootImpl.java:6683)
   at android.view.ViewRootImpl.enqueueInputEvent (ViewRootImpl.java:6644)
   at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent (ViewRootImpl.java:6847)
   at android.view.InputEventReceiver.dispatchInputEvent (InputEventReceiver.java:193)
   at android.os.MessageQueue.nativePollOnce (Native Method)
   at android.os.MessageQueue.next (MessageQueue.java:325)
   at android.os.Looper.loop (Looper.java:142)
   at android.app.ActivityThread.main (ActivityThread.java:6626)
   at java.lang.reflect.Method.invoke (Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:811)
```

doctor -v output:

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.5 at /home/artem/Development/flutter
    • Framework revision 27321ebbad (6 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/artem/Development/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /home/artem/Development/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/artem/Development/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
Process finished with exit code 0
```

**Comment by VladyslavBondarenko** [comment]
Related to https://github.com/flutter/flutter/issues/34415

**Comment by sunndog** [comment]
@jonahwilliams 

The NullPointerException is still happening on the line following this assignment at line 1155 of AccessibilityBridge.java:  SemanticsNode semanticsNodeUnderCursor = getRootSemanticsNode().hitTest(new float[] {event.getX(), event.getY(), 0, 1});

The easiest way to reproduce it is to simply have TalkBack enabled and then swipe down a Flutter screen into the Android Navigation Bar (Where the home, back and overview buttons live).

**Comment by sunndog** [comment]
I was able to fork and build the FlutterEngine.  I modified 'public boolean onAccessibilityHoverEvent(MotionEvent event)' by adding a check for null on semanticsNodeUnderCursor:

    if (semanticsNodeUnderCursor == null) {
      return false;
    }

With this customization my app no longer crashes.  @jonahwilliams @eseidel @eseidelGoogle Can this check be added?

**Comment by VladyslavBondarenko** [comment]
@sunndog 
https://github.com/flutter/flutter/issues/34415#issuecomment-616828212
