### ISSUE TITLE
Deactivate does not get called on push

### ISSUE THREAD

**Issue by tewshi** [flutter/flutter#50147]
## Steps to Reproduce

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(App());
}

class App extends StatefulWidget {
  const App({Key key}) : super(key: key);

  @override
  AppState createState() => AppState();
}

class AppState extends State<App> {
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'App',
      initialRoute: A.routeName,
      onUnknownRoute: (RouteSettings settings) {
        return _buildNotFoundSceneRoute(settings);
      },
      onGenerateRoute: (RouteSettings settings) {
        switch (settings.name) {
          case A.routeName:
            return MaterialPageRoute(
              builder: (BuildContext context) {
                return SafeArea(
                  child: Container(
                    child: A(),
                    color: Colors.white,
                  ),
                );
              },
              settings: RouteSettings(name: A.routeName),
            );
          case B.routeName:
            return MaterialPageRoute(
              builder: (BuildContext context) {
                return SafeArea(
                  child: Container(
                    child: B(),
                    color: Colors.white,
                  ),
                );
              },
              settings: RouteSettings(name: B.routeName),
            );
          default:
            return _buildNotFoundSceneRoute(settings);
        }
      },
    );
  }

  PageRoute _buildNotFoundSceneRoute(RouteSettings settings) {
    return MaterialPageRoute(
      builder: (BuildContext context) {
        return SafeArea(
          top: false,
          bottom: false,
          child: Material(
            type: MaterialType.card,
            child: Center(
              child: Text(
                'Content not found: ${settings.name}',
                style: TextStyle(
                  fontFamily: 'Sensation',
                  fontSize: 18.0,
                  decoration: TextDecoration.none,
                  color: Colors.red,
                ),
              ),
            ),
          ),
        );
      },
      settings: RouteSettings(name: '/not-found'),
    );
  }
}

class A extends StatefulWidget {
  static const String routeName = '/';

  @override
  _AState createState() => _AState();
}

class _AState extends State<A> {
  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: <Widget>[
        RaisedButton(
          child: Text('Push B on A'),
          onPressed: () {
            Navigator.of(context).pushNamed(B.routeName);
          },
        ),
        RaisedButton(
          child: Text('Replace A with B'),
          onPressed: () {
            Navigator.of(context).pushReplacementNamed(B.routeName);
          },
        ),
        if (ModalRoute.of(context).canPop)
          RaisedButton(
            child: Text('Back to B'),
            onPressed: () {
              Navigator.of(context).pop();
            },
          ),
      ],
    );
  }

  @override
  void deactivate() {
    print('A deactivated');
    super.deactivate();
  }

  @override
  void dispose() {
    print('A disposed');
    super.dispose();
  }
}

class B extends StatefulWidget {
  static const String routeName = '/b';

  @override
  _BState createState() => _BState();
}

class _BState extends State<B> {
  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: <Widget>[
        RaisedButton(
          child: Text('Push A on B'),
          onPressed: () {
            Navigator.of(context).pushNamed(A.routeName);
          },
        ),
        RaisedButton(
          child: Text('Replace B with A'),
          onPressed: () {
            Navigator.of(context).pushReplacementNamed(A.routeName);
          },
        ),
        if (ModalRoute.of(context).canPop)
          RaisedButton(
            child: Text('Back to A'),
            onPressed: () {
              Navigator.of(context).pop();
            },
          ),
      ],
    );
  }

  @override
  void deactivate() {
    print('B deactivated');
    super.deactivate();
  }

  @override
  void dispose() {
    print('B disposed');
    super.dispose();
  }
}
```
</details>

Run the app, based on the code above, click on `Push B on A` which is supposed to call the `deactivate` method of `A`
**Expected results:** Expect to print `'A deactivated'`

**Actual results:** nothing printed

<details>

[✓] Flutter (Channel master, v1.14.7-pre.58, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.14.7-pre.58 at ~/dev/src/flutter
    • Framework revision 83d4d63a71 (5 days ago), 2020-01-30 18:10:36 -0800
    • Engine revision e5209202fb
    • Dart version 2.8.0 (build 2.8.0-dev.6.0 162d6c5634)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at ~/dev/src/android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = ~/dev/src/android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (3 available)
    • Tewshi’s iPhone • 6fe9acfdbee6d2defb8769d328547267f0f • ios            • iOS 13.3
    • Chrome          • chrome                                   • web-javascript • Google Chrome 79.0.3945.130
    • Web Server      • web-server                               • web-javascript • Flutter Tools

• No issues found!
</details>

**Comment by helinanever** [comment]
Hi @tewshi 
`deactivate` doesn't get called when using Navigator.push or Navigator.pushNamed.
You can use Navigator.pushReplacement or Navigator.pop to call `deactivate`

Closing, as this isn't an issue with Flutter itself. If you disagree please write in the comments
and I will reopen it. 
Thank you.

**Comment by tewshi** [comment]
this is an issue, because it has changed, `deactivate` is usually called when you `push` on a route and when you `pop` back to it, and also when you `pushReplacement` `deactivate` is called just before `dispose`.

but what it currently does now is no different from `dispose`, only called when you remove the route.

How I noticed was that, I had a timer, which I pause when I push a new route, and resume when I pop back, but this no longer works because of this change in `deactivate`

is there an alternative way to do this? if we can no longer use `deactivate` this way.

**Comment by iapicca** [comment]
Hi @tewshi 
I believe @helinanever  is correct
the [doc](https://api.flutter.dev/flutter/widgets/State/deactivate.html)  states
`The framework calls this method whenever it removes this State object from the tree. `
I believe `push` does not remove the state from the widget, while `pushReplacement` does remove from the tree;
does this answer the issue?
thank you

**Comment by tewshi** [comment]
@iapicca 
I’m not saying @helinanever is wrong though, I’m saying there’s been a change, and it has greatly affected two of my apps.

You can try an earlier version of master, maybe mid Jan and you’ll see that `deactivate` is always called when a widget is no longer in view, either by a `push`, `pop` or `replacement`.

But it’s fine if this is the new behavior, I’ll find a way to fix what I did with it.

If `deactivate` is only called when the state object is removed from the tree then why do we have `dispose`?

**Comment by iapicca** [comment]
Hi @tewshi 
quoting the docs
https://api.flutter.dev/flutter/widgets/State/deactivate.html
`In some cases, the framework will reinsert the State object into another part of the tree (e.g., if the subtree containing this State object is grafted from one location in the tree to another).`
while https://api.flutter.dev/flutter/widgets/NavigatorState/dispose.html
`The framework calls this method when this State object will never build again.`

does this answer your question?
thank you

**Comment by tewshi** [comment]
it's okay if this is how it works now, like I said, there was a change.

I guess I'll have to use the `Future` that's returned from `push` to handle this issue from here.

**Comment by iapicca** [comment]
Hi @tewshi 
I'm glad that you found a solution to solve the issue
thank you for letting me know

**Comment by jordan-maulana** [comment]
Hi @tewshi 
I'm in total agree with you. This behavior changes really mess my projects that depends on deactivate method.

In v 1.12.13 when I place a deactivate in A then I push route to B. When I pop B or press back, deactivate in A would be called. Now that behavior is changed.

**Comment by tewshi** [comment]
Exactly what I was trying to explain in my previous messages @jordan-maulana

**Comment by adriana-elizondo** [comment]
Hi @helinanever , I think @tewshi has a very valid question and I don't think it was answered before closing this issue.
I stumbled into this post because I am having the same question right now so I would like to ask if again. Is there a method that gets called when a stateful widget is not visible anymore? 
This used to be the deactivate method, is there something replacing that now?
Thanks!

**Comment by iapicca** [comment]
Hi @adriana-elizondo 
please note the answers above [[1](https://github.com/flutter/flutter/issues/50147#issuecomment-582350864), [2](https://github.com/flutter/flutter/issues/50147#issuecomment-582385045), [3](https://github.com/flutter/flutter/issues/50147#issuecomment-582851794)]

this [code sample](https://dartpad.dartlang.org/5f1529d84dbdfef1ce04968ee9ca4da8) represent the different behaviour
does this solve the issue for you?
Thank you

**Comment by adriana-elizondo** [comment]
Hi @iapicca, thanks for your answer. 
I found a workaround for my specific situation, but if someone is still having this issue:
In the code sample you are using pushReplacement, which will indeed call the "deactivate" method, but the question was for push without replacing the current widget in the stack.
Also, it prints deactivate on initState, not sure if that was the intention?
Thank you! :)

**Comment by hangaoke1** [comment]
same problem😂

**Comment by iapicca** [comment]
Hi @adriana-elizondo 
thanks for catching my bad copy paste
I used in the [code sample](https://dartpad.dartlang.org/5f1529d84dbdfef1ce04968ee9ca4da8) a list view builder, but
unfortunately due to this [issue](https://github.com/flutter/flutter/issues/58917)
since the elements are disposed
I cannot double-check if deactivate works properly.
I'll keep the issue open for now, hoping to be able to check when the issue linked is solved
Thank you

**Comment by hangaoke1** [comment]
@iapicca , In your example, using push does not trigger the deactivate of the previous page. Is there a function  on the previous page that can be execute when pushing & also can be execute when back to the page。 just like activated and deactivated in other framework

**Comment by Mhsanjib** [comment]
I am also facing similar issue due to the change in the deactivate function. I am unable to understand the change and now after the change whats the difference between the deactivate and dispose. As per the definition of deactivate in the [link](https://api.flutter.dev/flutter/widgets/State/deactivate.html) , it must be called whenever it is removed from the tree and when it resumes. Since, we do not have any callback function(in flutter) when the route resumes and '`deactivate`' function was only the way to catch it, can some one explain how to do that now? 
`For example. PageA navigates to PageB using push method and now when we click back button or call pop function, PageA is resumed and there is no callback function in `PageA` to deal with the pop and no I cannot use `await` here because of the app setup.`
Is there a bug in `deactivate` function or an intentional change ?

**Comment by hangaoke1** [comment]
@Mhsanjib you can use routeObserver

**Comment by 120011676** [comment]
#58485 resolvent

**Comment by Andrious** [comment]
Yes, what's going on here?!  Ten months ago you would call `deactivate` with every push to another route. 
This [screenshot](https://files.gitter.im/5faad372d73408ce4ff3bb9a/foOV/image.png) includes four more lines (highlighted with red arrows) that would be printed when the little bit of code below pushed on to the 'Second Page.'  Run this code now and those four lines don't appear?!
Not good. 
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  MyApp() : super() {
    print(
        ">>>>>>>>>>>>>>>>>>>>>>>>>   MyApp being created. Constructor called.");
  }
  @override
  Widget build(BuildContext context) {
    print(">>>>>>>>>>>>>>>>>>>>>>>>>   MyApp build() called!");
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Home Page'),
    );
  }
}

/// High-level variable. Identifies the widget. New key? New widget!
Key _key = UniqueKey();

class MyHomePage extends StatefulWidget {
  // constructor
  MyHomePage({Key key, this.title}) : super(key: key) {
    print(
        ">>>>>>>>>>>>>>>>>>>>>>>>>   MyHomePage StatefulWidget being created. Constructor called.");
  }
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  // constructor
  _MyHomePageState() : super() {
    print(
        ">>>>>>>>>>>>>>>>>>>>>>>>>   _MyHomePageState being created. Constructor called.");
  }
  int _counter = 0;

  void initState() {
    print(">>>>>>>>>>>>>>>>>>>>>>>>>   _MyHomePageState initState() called.");
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    print(">>>>>>>>>>>>>>>>>>>>>>>>>   _MyHomePageState build() called!");
    return _FirstPage(
      key: _key,
      title: "${widget.title} counter pressed: $_counter",
      state: this,
    );
  }
}

class _FirstPage extends StatefulWidget {
  // constructor
  _FirstPage({Key key, @required this.title, this.state}) : super(key: key) {
    print(
        ">>>>>>>>>>>>>>>>>>>>>>>>>   FirstPage StatefulWidget being created. Constructor called.");
  }
  final String title;
  final _MyHomePageState state;

  @override
  State createState() => _FirstPageState();
}

class _FirstPageState extends State<_FirstPage> {
  // constructor
  _FirstPageState() : super() {
    print(
        ">>>>>>>>>>>>>>>>>>>>>>>>>   _FirstPageState being created. Constructor called.");
  }
  int counter = 0;
  _MyHomePageState state;

  void initState() {
    print(">>>>>>>>>>>>>>>>>>>>>>>>>   _FirstPageState initState() called.");
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    print(">>>>>>>>>>>>>>>>>>>>>>>>>   _FirstPageState build() called!");
    if (widget.state == null && state == null) {
      // the first instance of that state object.
      state = context.findAncestorStateOfType<_MyHomePageState>();
    } else {
      state ??= widget.state;
    }
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          print(
              ">>>>>>>>>>>>>>>>>>>>>>>>>   First page Button is pressed. setState() called.");
          setState(() {
            counter++;
          });
        },
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
      persistentFooterButtons: <Widget>[
        RaisedButton(
          child: Text(
            'Home Page Counter',
          ),
          onPressed: () {
            print(
                ">>>>>>>>>>>>>>>>>>>>>>>>>   'Home Page Counter' button pressed. HomePage setState() called.");
            state?.setState(() {
              state._counter++;
            });
          },
        ),
        RaisedButton(
          child: Text(
            'Second Page',
          ),
          onPressed: () {
            print(">>>>>>>>>>>>>>>>>>>>>>>>>   'Second Page' button pressed.");
            Navigator.push(
                context,
                MaterialPageRoute(
                    builder: (BuildContext context) => _SecondPage(
                        title: "You're on the Second Page", homeState: state)));
          },
        ),
      ],
    );
  }

  void deactivate() {
    super.deactivate();
    print(">>>>>>>>>>>>>>>>>>>>>>>>>   _FirstPageState deactiviated.");
  }

  void dispose() {
    super.dispose();
    print(
        ">>>>>>>>>>>>>>>>>>>>>>>>>   _FirstPageState disposed. Counter was $counter");
  }
}

class _SecondPage extends StatefulWidget {
  _SecondPage({Key key, @required this.title, @required this.homeState})
      : super(key: key) {
    print(
        ">>>>>>>>>>>>>>>>>>>>>>>>>   SecondPage StatefulWidget being created. Constructor called.");
  }
  final String title;
  final _MyHomePageState homeState;

  @override
  _SecondPageState createState() => _SecondPageState();
}

class _SecondPageState extends State<_SecondPage> {
  _SecondPageState() : super() {
    print(
        ">>>>>>>>>>>>>>>>>>>>>>>>>   _SecondPageState being created. Constructor called.");
  }
  int _counter = 0;

  void initState() {
    print(">>>>>>>>>>>>>>>>>>>>>>>>>   _SecondPageState initState() called.");
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    print(">>>>>>>>>>>>>>>>>>>>>>>>>   _SecondPageState build() called!");
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text("You're on this second page."),
            const Text('You have pushed the button this many times:'),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          print(
              ">>>>>>>>>>>>>>>>>>>>>>>>>   Second page Button is pressed. setState() called.");
          setState(() {
            _counter++;
          });
        },
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
      persistentFooterButtons: <Widget>[
        RaisedButton(
          child: Text(
            'New Key',
          ),
          onPressed: () {
            print(">>>>>>>>>>>>>>>>>>>>>>>>>   'New Key' button pressed. HomePage setState() called.");
            widget.homeState.setState(() {
              _key = UniqueKey();
            });
          },
        ),
        RaisedButton(
          child: Text(
            'Home Page Counter',
          ),
          onPressed: () {
            print(
                ">>>>>>>>>>>>>>>>>>>>>>>>>   'Home Page Counter' button pressed. HomePage setState() called.");
            widget.homeState.setState(() {
              widget.homeState._counter++;
            });
          },
        ),
        RaisedButton(
          child: Text(
            'First Page',
          ),
          onPressed: () {
            print(">>>>>>>>>>>>>>>>>>>>>>>>>   'First Page' button pressed.");
            Navigator.pop(context);
          },
        ),
      ],
    );
  }

  void deactivate() {
    super.deactivate();
    print(">>>>>>>>>>>>>>>>>>>>>>>>>   _SecondPageState deactiviated.");
  }

  void dispose() {
    super.dispose();
    print(
        ">>>>>>>>>>>>>>>>>>>>>>>>>   _SecondPageState disposed. Counter was $_counter");
  }
}
```
Reference: [StatefulWidget's Key & State](https://andrious.medium.com/statefulwidgets-key-state-8ad83ac2e54f#275f)

**Comment by srdjus** [comment]
In the end what was the best practice to handle this? Route Observer is a pretty inelegant solution for such simple task, deactivate was perfect for this and workarounds like using PushReplacment are not always a wanted behavior.

For example if someone navigates using back button _deactivate_ was run and I can pause a socket or make a small clean up, but when I navigate through my main menu (which uses pushNamed) there is no elegant way to handle it.

**Comment by zhangjk4859** [comment]
any solutions now?just like `viewWillAppear()` and `viewWillDisappear()`hook method in iOS,the Route Observer is a little bit complex and deactivate's still not working

**Comment by tewshi** [comment]
What I finally used then was the Future returned by `push()` or `pushNamed()`

so, if I want to do something after a `pushed` component is `popped` I'll attach a callback like this:

```dart
...

Navigator.of(context).push(ComponentA()).then((data) {
    print('ComponentA deactivated');
});

...
```

NB: the above is much like a pseudo-code, to express how it was done;

**Comment by mrgnedy** [comment]
> 
> 
> What I finally used then was the Future returned by `push()` or `pushNamed()`
> 
> so, if I want to do something after a `pushed` component is `popped` I'll attach a callback like this:
> 
> ```dart
> ...
> 
> Navigator.of(context).push(ComponentA()).then((data) {
>     print('ComponentA deactivated');
> });
> 
> ...
> ```
> 
> NB: the above is much like a pseudo-code, to express how it was done;

That still doesn't solve the problem if you have like ten pages(as in my case) to choose between to navigate to I don't think it'd be quite inelegant to attach a then function to every Nav.push in the screen

**Comment by smelcher** [comment]
> > What I finally used then was the Future returned by `push()` or `pushNamed()`
> > so, if I want to do something after a `pushed` component is `popped` I'll attach a callback like this:
> > ```dart
> > ...
> > 
> > Navigator.of(context).push(ComponentA()).then((data) {
> >     print('ComponentA deactivated');
> > });
> > 
> > ...
> > ```
> > 
> > 
> > NB: the above is much like a pseudo-code, to express how it was done;
> 
> That still doesn't solve the problem if you have like ten pages(as in my case) to choose between to navigate to I don't think it'd be quite inelegant to attach a then function to every Nav.push in the screen

I agree. Its not practical to sift through all of the Nav push calls and add more code.  Deactivate was the only hook to know when navigation took place.

**Comment by tewshi** [comment]
it all depends on how large your app is, for an app with a few screens, it wouldn't be much of a problem, I only wrote my own workaround for this issue.

So, sometimes, even if the app has so many screens, you may not need to use the `deactivate` on all screen push

**Comment by TahaTesser** [comment]
<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(App());
}

class App extends StatefulWidget {
  const App({Key key}) : super(key: key);

  @override
  AppState createState() => AppState();
}

class AppState extends State<App> {
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'App',
      initialRoute: A.routeName,
      onUnknownRoute: (RouteSettings settings) {
        return _buildNotFoundSceneRoute(settings);
      },
      onGenerateRoute: (RouteSettings settings) {
        switch (settings.name) {
          case A.routeName:
            return MaterialPageRoute(
              builder: (BuildContext context) {
                return SafeArea(
                  child: Container(
                    child: A(),
                    color: Colors.white,
                  ),
                );
              },
              settings: RouteSettings(name: A.routeName),
            );
          case B.routeName:
            return MaterialPageRoute(
              builder: (BuildContext context) {
                return SafeArea(
                  child: Container(
                    child: B(),
                    color: Colors.white,
                  ),
                );
              },
              settings: RouteSettings(name: B.routeName),
            );
          default:
            return _buildNotFoundSceneRoute(settings);
        }
      },
    );
  }

  PageRoute _buildNotFoundSceneRoute(RouteSettings settings) {
    return MaterialPageRoute(
      builder: (BuildContext context) {
        return SafeArea(
          top: false,
          bottom: false,
          child: Material(
            type: MaterialType.card,
            child: Center(
              child: Text(
                'Content not found: ${settings.name}',
                style: TextStyle(
                  fontFamily: 'Sensation',
                  fontSize: 18.0,
                  decoration: TextDecoration.none,
                  color: Colors.red,
                ),
              ),
            ),
          ),
        );
      },
      settings: RouteSettings(name: '/not-found'),
    );
  }
}

class A extends StatefulWidget {
  static const String routeName = '/';

  @override
  _AState createState() => _AState();
}

class _AState extends State<A> {
  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: <Widget>[
        RaisedButton(
          child: Text('Push B on A'),
          onPressed: () {
            Navigator.of(context).pushNamed(B.routeName);
          },
        ),
        RaisedButton(
          child: Text('Replace A with B'),
          onPressed: () {
            Navigator.of(context).pushReplacementNamed(B.routeName);
          },
        ),
        if (ModalRoute.of(context).canPop)
          RaisedButton(
            child: Text('Back to B'),
            onPressed: () {
              Navigator.of(context).pop();
            },
          ),
      ],
    );
  }

  @override
  void deactivate() {
    print('A deactivated');
    super.deactivate();
  }

  @override
  void dispose() {
    print('A disposed');
    super.dispose();
  }
}

class B extends StatefulWidget {
  static const String routeName = '/b';

  @override
  _BState createState() => _BState();
}

class _BState extends State<B> {
  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: <Widget>[
        RaisedButton(
          child: Text('Push A on B'),
          onPressed: () {
            Navigator.of(context).pushNamed(A.routeName);
          },
        ),
        RaisedButton(
          child: Text('Replace B with A'),
          onPressed: () {
            Navigator.of(context).pushReplacementNamed(A.routeName);
          },
        ),
        if (ModalRoute.of(context).canPop)
          RaisedButton(
            child: Text('Back to A'),
            onPressed: () {
              Navigator.of(context).pop();
            },
          ),
      ],
    );
  }

  @override
  void deactivate() {
    print('B deactivated');
    super.deactivate();
  }

  @override
  void dispose() {
    print('B disposed');
    super.dispose();
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (12 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
```bash
[✓] Flutter (Channel master, 1.26.0-18.0.pre.156, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-18.0.pre.156 at /Users/tahatesser/Code/flutter_master
    • Framework revision 45508985b1 (8 hours ago), 2021-02-02 22:46:04 -0500
    • Engine revision 2c144c3eeb
    • Dart version 2.12.0 (build 2.12.0-282.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>

**Comment by VenatusSimpleX** [comment]
Any workarounds for this issue? As I needed to clean up socketio connections on page change. It does not make sense if the connection is retained after I pushed another page on top of it in the stack. But it also does not make sense if I use `pushReplacementNamed` since I need the back button to work correctly to go back to previous page.

RouteObserver seem overkill for this, I won't shy away from it if I really need to use this, but am looking for an elegant workaround to this.

**Comment by iapicca** [comment]
@TahaTesser 

if @superbaymax1201 [report](https://github.com/flutter/flutter/issues/78781#issue-837597653) is verified
> Widget A->Widget B (Widget B call Navigator.pop()) Widget B->Widget A
> in flutter 1.12.13+hotfix.9 will call A Widget deactive method;
> in flutter 1.22.4 won't call A Widget deactive method ;
> in different versions have different behaviors ，why?
> How will it be implemented in future versions?

wouldn't make it a regression?

**Comment by benIsCome** [comment]
So long since this issue created and now there is no any solution from flutter development team.
It's very nessary and useful for developer to know the change of page state, when become visible, when become unvisible, but not.
Before flutter2.0, deactivate method will call when page become visible or unvisible. Update to flutter2.0, it didn't work ! ! ! 
Why there are not methods like onVisible and onUnvisible, developer need.

**Comment by skast96** [comment]
This is still an issue and in my opinion really bad state handling to not have a Resume and Pause behavior like in Android.

**Comment by SalathielGenese** [comment]
It should bug the architects behinds the navigator lifecycle.

**Comment by Pierre-Monier** [comment]
> 

Note that you can use [RouteObserver](https://api.flutter.dev/flutter/widgets/RouteObserver-class.html) to detect when a page became visible or not. But I agree that it will be better if this was directly inside the widget lifecycle

**Comment by Pierre-Monier** [comment]
> So long since this issue created and now there is no any solution from flutter development team.
> It's very nessary and useful for developer to know the change of page state, when become visible, when become unvisible, but not.
> Before flutter2.0(test in v1.12.13), deactivate method will call when page become visible or unvisible. Update to flutter2.0(test in v2.2.3), it didn't work ! ! !
> Why there are not methods like onVisible and onUnvisible, developer need.

@benIsCome 
Note that you can use [RouteObserver](https://api.flutter.dev/flutter/widgets/RouteObserver-class.html) to detect when a page became visible or not. But I agree that it will be better if this was directly inside the widget lifecycle

**Comment by maheshmnj** [comment]
As the [doc reads](https://api.flutter.dev/flutter/widgets/State/deactivate.html), deactivate is called when the widget is removed from the tree or reinserted to a different part of the widget tree.

> The framework calls this method whenever it removes this [State](https://api.flutter.dev/flutter/widgets/State-class.html) object from the tree. In some cases, the framework will reinsert the [State](https://api.flutter.dev/flutter/widgets/State-class.html) object into another part of the tree (e.g., if the subtree containing this [State](https://api.flutter.dev/flutter/widgets/State-class.html) object is grafted from one location in the tree to another due to the use of a [GlobalKey](https://api.flutter.dev/flutter/widgets/GlobalKey-class.html)).

Pushing a new Route would still have both the routes in the widget tree, so it is intended that deactivate won't be called.


<details>
<summary>flutter doctor -v</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
    Navigator.of(context)
        .push(MaterialPageRoute(builder: (context) => const NewScreen()));
  }

  @override
  void deactivate() {
    // TODO: implement deactivate
    print('Home Page deactivated');
    super.deactivate();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

class NewScreen extends StatefulWidget {
  const NewScreen({Key? key}) : super(key: key);

  @override
  _NewScreenState createState() => _NewScreenState();
}

class _NewScreenState extends State<NewScreen> {
  @override
  void deactivate() {
    // TODO: implement deactivate
    print('New Screen deactivated');

    super.deactivate();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Second AppBar'),
      ),
      body: const Center(
        child: Text('Second Scren'),
      ),
    );
  }
}

```
</details>

logs for the above code sample

```console
Launching lib[/main.dart]() on Chrome in debug mode...
lib/main.dart:1
This app is linked to the debug service: ws://127.0.0.1:56923[/55P3j1A9hwI]()%3D[/ws]()
Debug service listening on ws://127.0.0.1:56923[/55P3j1A9hwI]()=[/ws]()
💪 Running with sound null safety 💪
Connecting to VM Service at ws://127.0.0.1:56923[/55P3j1A9hwI]()=[/ws]()
New Screen deactivated
```

Seeing the above comments It feels like this behavior has changed over the years, But the present behavior seems consistent with the documentation and is working as intended.

**Comment by maheshmnj** [comment]
As the [doc reads](https://api.flutter.dev/flutter/widgets/State/deactivate.html), deactivate is called when the widget is removed from the tree or reinserted to a different part of the widget tree.

> The framework calls this method whenever it removes this [State](https://api.flutter.dev/flutter/widgets/State-class.html) object from the tree. In some cases, the framework will reinsert the [State](https://api.flutter.dev/flutter/widgets/State-class.html) object into another part of the tree (e.g., if the subtree containing this [State](https://api.flutter.dev/flutter/widgets/State-class.html) object is grafted from one location in the tree to another due to the use of a [GlobalKey](https://api.flutter.dev/flutter/widgets/GlobalKey-class.html)).

Pushing a new Route would still have both the routes in the widget tree, so it is intended that deactivate won't be called for any of the widgets.


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
    Navigator.of(context)
        .push(MaterialPageRoute(builder: (context) => const NewScreen()));
  }

  @override
  void deactivate() {
    // TODO: implement deactivate
    print('Home Page deactivated');
    super.deactivate();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

class NewScreen extends StatefulWidget {
  const NewScreen({Key? key}) : super(key: key);

  @override
  _NewScreenState createState() => _NewScreenState();
}

class _NewScreenState extends State<NewScreen> {
  @override
  void deactivate() {
    // TODO: implement deactivate
    print('New Screen deactivated');

    super.deactivate();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Second AppBar'),
      ),
      body: const Center(
        child: Text('Second Scren'),
      ),
    );
  }
}

```
</details>

logs for the above code sample when `Push` and `Pop` is performed.

```console
Launching lib[/main.dart]() on Chrome in debug mode...
lib/main.dart:1
This app is linked to the debug service: ws://127.0.0.1:56923[/55P3j1A9hwI]()%3D[/ws]()
Debug service listening on ws://127.0.0.1:56923[/55P3j1A9hwI]()=[/ws]()
💪 Running with sound null safety 💪
Connecting to VM Service at ws://127.0.0.1:56923[/55P3j1A9hwI]()=[/ws]()
New Screen deactivated
```

Seeing the above comments I realize that this behavior has changed over the years, But the present behavior seems consistent with the documentation and is working as intended.

**Comment by maheshmnj** [comment]
cc: @chunhtai

**Comment by hello-paulvin** [comment]
Feels like RouteObserver is the way forward here.

**Comment by hello-paulvin** [comment]
One way I recently fix this is: 
is set mainState to false

 ```
MaterialPageRoute(
      maintainState: maintainState,
      builder: (context) => page,
    );
```

/// By default, when a modal route is replaced by another, the previous route
/// remains in memory. To free all the resources when this is not necessary, set
/// [maintainState] to false.

**Comment by goderbauer** [comment]
This is currently working as expected (https://github.com/flutter/flutter/issues/50147#issuecomment-1033773923 explains this pretty well). I am going to close this as there are no further actions we plan to take from this.
