### ISSUE TITLE
Cirrus network connection failures on flutter/plugins CI

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#51074]
Right now our flutter/plugins and FirebaseExtended/flutterfire tests are encountering frequent and unpredictable network connection failures.

Here are some examples from the past 24 hours. Basically every flutter/plugins and FirebaseExtended/flutterfire test run has some of these:

Failure talking to gcloud:
https://cirrus-ci.com/task/6632847574302720?command=main#L686
https://cirrus-ci.com/task/5909730719694848

Failure retrieving Dart SDK: https://cirrus-ci.com/task/6562478830125056

Failure talking to pub.dartlang.org: https://cirrus-ci.com/task/4505654371024896

Failure connecting to jcenter: https://cirrus-ci.com/task/5065305789562880?command=main#L413

Failed downloading iOS tools. https://cirrus-ci.com/task/6233047267803136

~I'm wondering if we're getting pre-empted somehow (perhaps due to analysis failures or lack of credits?). If so, information from Cirrus indicating the cause of the failures would be helpful.~ Edit: Fixing analysis failures did NOT improve the issue, see https://cirrus-ci.com/task/5510431355699200

**Comment by collinjackson** [comment]
FYI @fkorotkov @amirh @godofredoc

**Comment by fkorotkov** [comment]
Seems like a duplicate of https://github.com/flutter/flutter/issues/50730 beside the first issue where `(gcloud.config.set) timed out`. Could you please try to re-run that task?

**Comment by collinjackson** [comment]
#50730 implies that this issue is specific to MacOS but I'm seeing failures on Linux as well for "Failure connecting to jcenter"

https://cirrus-ci.com/task/5065305789562880?command=main#L413

**Comment by fkorotkov** [comment]
Yeah, the issues occur mostly on macOS but not exclusively. Changed title of the issue.

**Comment by collinjackson** [comment]
I thought that maybe the my test runs were getting pre-empted by flutter analyze failures, but that seems not to be the case. Updated the issue description.

**Comment by fkorotkov** [comment]
I can see from the metrics chart that Flakiness started around February 5th. And seems most of the flakes are around `gcloud` which is called from `firebase-test-lab` which was released on February 7th. Were there any changes around that time that you are aware of?

![image](https://user-images.githubusercontent.com/989066/74970189-f1f4e580-53eb-11ea-9441-d0569e01ccdf.png)

**Comment by collinjackson** [comment]
0.0.32+6 (released Feb 7) was an attempt to address long-standing test flakiness; it wasn't a reaction to something that happened on Feb 5.

https://github.com/flutter/plugin_tools/commit/7defb590cf3e55a968e1671e13b3bff6f3a6478e

We're still seeing lots of network issues on the Mac builders for things that have nothing to do with gcloud (failures to connect to github and pub). I think resolving those might be a higher priority and then we can see if the gcloud issue is still there.

**Comment by collinjackson** [comment]
Here's a network failure on the Linux builders that is a 503 Service Unavailable, in case that's helpful.

https://cirrus-ci.com/task/4923127473897472?command=main#L369

```
http://download.flutter.io/io/flutter/x86_debug/1.0.0-e1e6ced81d029258d449bdec2ba3cddca9c2ca0c/x86_debug-1.0.0-e1e6ced81d029258d449bdec2ba3cddca9c2ca0c.pom'. Received status code 503 from server: Service Unavailable
```

**Comment by fkorotkov** [comment]
I don't think these 500s and `gcloud` time outs are Cirrus related. Especially since it's Linux which is on GCP and there were no changes to the GKE cluster in quite a while.

There are defiantly network issues on macOS and looks like in virtualization software. There is a new virtualization release coming out tomorrow that includes a few fixes and support of the virtualization provider claims that it should fix the issues that we see here.

**Comment by collinjackson** [comment]
I wanted to check in on this since we're still seeing Mac network issues on our plugins CI and I'm not sure if there's anything we can do on our end to improve reliability. Example:

https://cirrus-ci.com/task/6651773293166592

```
    [!] Couldn't determine repo type for URL: `https://cdn.cocoapods.org/`: Failed to open TCP connection to cdn.cocoapods.org:443 (getaddrinfo: nodename nor servname provided, or not known)
```

I can add a retry on the gcloud set; if that's really our only problem I think we can deal but it's less reasonable to be retrying things like pod install.

**Comment by fkorotkov** [comment]
Yeah, might be the same **since it's Mac**. I've upgraded the virtualization last night and saw the issue still occurring. I was able to somewhat reliable reproduce the issue on my local Mac Mini and debugging it with Anka folks right now.

**Comment by fkorotkov** [comment]
But yeah, `gcloud` looks different.

**Comment by collinjackson** [comment]
Is there any help coming for networking on Linux? I'm not sure how to address failures like this one

https://cirrus-ci.com/task/5375307637063680
https://cirrus-ci.com/task/5797520102129664

I'm seeing 504 gateway timeouts doing gradle resolution on multiple builders.

> Could not GET 'https://jcenter.bintray.com/com/google/code/gson/gson-parent/2.8.0/gson-parent-2.8.0.pom'. Received status code 504 from server: Gateway Time-out

Does this seem like an issue with jcenter or can it be fixed on our end somehow? I'm not sure what the resolution should be... is it reasonable to attempt every build 5 times?

**Comment by fkorotkov** [comment]
@collinjackson tasks are using [Gradle 4.10.2](https://cirrus-ci.com/task/5797520102129664?command=main#L271) which doesn't have retries. It's understandable for `stable` but `master` should have https://github.com/flutter/flutter/pull/50388

**Comment by collinjackson** [comment]
I reduced the number of calls to gcloud set and made it ignore failures (since they aren't actually an indication of a problem) and that seems to have improved the reliability of Firebase Test Lab a lot.

Still a flake here and there, though. Here's one from tip of tree:

https://cirrus-ci.com/task/5126493739155456?command=main#L2835

ERROR: (gcloud.firebase.test.android.run) timed out

Should we check for this specific string and retry the test?

**Comment by fkorotkov** [comment]
It seems it failed first with 500 ^^ https://cirrus-ci.com/task/5126493739155456?command=main#L563

> ERROR: gcloud crashed (MetadataServerException): HTTP Error 500: Internal Server Error

Something weird. Is there a way to see all the command the script runs and maybe pass `--version` flag to `gcloud` invocations.

**Comment by collinjackson** [comment]
Seems like Cirrus networking is no long causing lots of failures

<img width="703" alt="Screen Shot 2020-04-01 at 12 13 04" src="https://user-images.githubusercontent.com/394889/78176985-3a9fb580-7412-11ea-8854-af5289daf0ea.png">
