### ISSUE TITLE
Flutter OnScreen Keyboard opens on physical key press

### ISSUE THREAD

**Issue by SebastianRuettger** [flutter/flutter#51478]
I have a device that uses a laserscanner to scan barcodes and outputs the result as simulated keypresses. I've used this with a RawKeyboardListener and it worked fine. Since then I've added a login screen to the app, that is only shown if the user hasn't logged in. If the login screen has been shown and disposed the onscreen keyboard opens when i press the physical scanner button. This should not happen and doesn't happen if the login screen hasn't been shown. My guess is, that there still are some remains of the textfields used in the login screen, after it is disposed. I've tried setting the FocusNodes for the Textfields and then disposing them in the dispose method, but that didn't work

I've asked a question on StackOverflow: [https://stackoverflow.com/questions/60417173/flutter-onscreen-keyboard-opens-on-physical-key-press](url)

## Steps to Reproduce

1. Screen with one or more Textfields
2. focus one or more
3. navigate to new screen
4. press physical button

**Expected results:** button is pressed but only the keyevents are fired

**Actual results:** the onscreen keyboard opens

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.16299.1686], locale de-DE)
    • Flutter version 1.12.13+hotfix.8 at C:\Users\sruettge\Documents\flutter
    • Framework revision 0b8abb4724 (2 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\sruettge\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.42.1)
    • VS Code at C:\Users\sruettge\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • MEMOR 10 • S19H00332 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

</details>

**Comment by artemtkachenko** [comment]
Same issue
I am really disappointed since it blocks flutter development for android applications that have a virtual keyboard but does not have a touch screen. 
It is not a rare case, it is a large market of android tv applications.

**Comment by darshankawar** [comment]
Hi @SebastianRuettger,
Can you please confirm if you still experience the issue on latest Stable version ?
Thanks.

**Comment by SebastianRuettger** [comment]
Hey, I've changed jobs and have no access to the device and the appAm 25.08.2020 12:56 schrieb darshankawar <notifications@github.com>:
Hi @SebastianRuettger,
Can you please confirm if you still experience the issue on latest Stable version ?
Thanks.

**Comment by NitrofCG** [comment]
i have same problem with flutter 1.17.5.
i will test on 1.2.3

**Comment by NitrofCG** [comment]
I debuged.
The method TextInputPlugin.getLastInputConnection keep a reference to an old lastInputConnection when the bug is produced.
When i resume application, the lastInputConnection property begin null and the keyevent work.

**Comment by CyrilHu** [comment]
i have same problem with flutter 1.22.1

**Comment by nrutledge** [comment]
I've just encountered this in Flutter 1.22.4. This is a major problem for any apps integrated with external input devices like barcode scanners.

Has anyone found a suitable workaround that can be used until this is resolved? Currently, I'm resorting to hiding the keyboard after each scan but it causes the keyboard to flash on screen each time which is jarring.

**Comment by pkotowski** [comment]
Same issue:
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19041.630], locale pl-PL)

Also very import for me as POS systems manufacturer.

OnScreen keyboard is not showing until any TextField input got focus. After that, keyboard will be shown on every keyboard input, also when no TextField widgets are on current Scaffold.

**Comment by fredrikjacobson** [comment]
@aakashbapna Are you performing any workaround currently?
How's the experience with hiding keyboard on keypress?

**Comment by aakashbapna** [comment]
@fredrikjacobson no workaround excepting switching to beta channel to atleast get the RawKeyEvent. Hiding the keyboard is very jarring experience for the user, if I don't hide the keyboard `onKey`, the only way for user to dismiss keyboard is to focus a text field and then dismiss (using "done" on keyboard or un-focussing text field).

**Comment by misha** [comment]
I have a completely different use case. The app is a game that brings up a `TextField` for entering text commands, but otherwise uses all keyboard events for in-game actions. 

After bringing up the `TextField` just once, `RawKeyDownEvent` stops being delivered to the `RawKeyboardListener`, and every press triggers the soft keyboard. As a user above mentioned, pausing and resuming the app appears to fix the state, but I have no workaround. Very, very stuck!

```
Flutter 2.2.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision b22742018b (5 weeks ago) • 2021-05-14 19:12:57 -0700
Engine • revision a9d88a4d18
Tools • Dart 2.13.0
```

**Comment by fanchou** [comment]
TextInputType.none: #83974

**Comment by red282** [comment]
With some debugging, I found that the `selectionChanged` value is always `true` on pressing any key from my bluetooth keyboard.

https://github.com/flutter/flutter/blob/361d416e6abb66bf601c5a6600fbc37706bb6c14/packages/flutter/lib/src/widgets/editable_text.dart#L2485

For example, my printed values are following: 
- from `TextSelection.collapsed(offset: 1, affinity: TextAffinity.downstream, isDirectional: false)`
- to ` TextSelection.collapsed(offset: 2, affinity: TextAffinity.downstream, isDirectional: false)`

So, this condition is also always true.
https://github.com/flutter/flutter/blob/361d416e6abb66bf601c5a6600fbc37706bb6c14/packages/flutter/lib/src/widgets/editable_text.dart#L2507-L2516

And, in `_handleSelectionChanged` function, `requestKeyboard()` is called, which brings to show the on-screen keyboard.
https://github.com/flutter/flutter/blob/361d416e6abb66bf601c5a6600fbc37706bb6c14/packages/flutter/lib/src/widgets/editable_text.dart#L2334-L2345

I checked both `master` & `stable` branches.

Is it a normal behavior that the selection change is evaluated always as true with an external keyboard? (I have not overall understanding for logics around those codes.)

**Comment by red282** [comment]
Additional info: 
Above issue that I mentioned is ocurred when using Samsung keyboard. 
Not reproduced with Gboard.

**Comment by gomcodoctor** [comment]
I am facing same issue with Gboard !

**Comment by rekire** [comment]
Related Android Bug: https://issuetracker.google.com/issues/300236999

**Comment by karatekid430** [comment]
It's 2024 and they have not fixed a simple bug which clearly is affecting a people in a serious way.

**Comment by bleroux** [comment]
Closing because this is fixed on master, see https://github.com/flutter/engine/pull/49829.

Before this fix, the IME internal state was reset when a text field is focused but not when it was unfocused. Depending on the IME this results on the IME still reacting based on the configuration of the last focused text field.
With this fix, the IME internal state is reset when a text field is unfocused.

**Comment by bleroux** [comment]
Reopening because https://github.com/flutter/engine/pull/49829 was reverted.
Calling `InputMethodManager.restartInput` (to reset IMEs internal states) automatically at the end of `TextInputPlugin.clearTextInputClient` solved that issue but it led to strange behaviors.

For the moment, I see two possible directions:
- find another place to automatically call `InputMethodManager.restartInput`
- find a way to explicitely trigger `InputMethodManager.restartInput`

**Comment by dayoul** [comment]
@bleroux Hello. Do you have any plan to fix this issue again? This happens for all Samsung Galaxy users when the device is connected to Bluetooth keyboard. Thanks in advance.  
@goderbauer Please consider to elevate the priority of this issue. It is actually critical for users who are using hardware keyboard.

**Comment by bleroux** [comment]
@dayoul I might work again on this but a solution is not obvious for the moment.
The flickering you observed seems to be exactly https://github.com/flutter/flutter/issues/101259. and I'm not sure that those issues are exactly the same.

Do you get this flickering when using Flutter 3.22? (which includes https://github.com/flutter/engine/pull/49829)

**Comment by dayoul** [comment]
@bleroux I've tried on 3.22.3 and the flickering still occurs. But on 3.19, when I type something on physical keyboard it does not flicker but just loses focus.

**Comment by bleroux** [comment]
@dayoul If the flickering was there on Flutter 3.22, this issue is not the one you are interested in, please have a look to https://github.com/flutter/flutter/issues/101259. Especially, it would be interesting to know if https://github.com/flutter/flutter/issues/101259 is reproducible on a Samsung device when using GBoard.

**Comment by dayoul** [comment]
@bleroux On 3.22.3, Samsung Device, Microsoft Swift Key and Samsung Keyboard reproduces flickering and when using GBoard, it does not flicker but the software keyboard comes up at the initial type on hardware keyboard and stays on the screen. Is this issue still related to #101259? or this issue?

**Comment by bleroux** [comment]
@dayoul Thanks a lot for the summary.
For the moment flickering is tracked on https://github.com/flutter/flutter/issues/101259. There might be a common root cause but the issue are separated for the moment (the flickering being the differentiator).

I don't know if I will work on this soon, I already dedicated a lot of time to thoses issues and it is difficult to find the root cause. At first it can seem there is something obvious on the Flutter side such as calling the `hideSoftInputFromWindow` and `showSoftInput` APIs at wrong time. But I once tried to comment those API calls (and most of the `TextInputPlugin` logic on the engine side) and some issues were still reproducible. 
For instance, see https://github.com/flutter/flutter/issues/148117#issuecomment-2166029309

Calling `restartInput` helped for some cases but it creates other issues. It seems that the way the Flutter app is structured (the way it creates the Android view) or maybe the way it is configured (missing parameters in the manifest file for instance, something related to [systemUIVisibility](https://developer.android.com/reference/android/view/View#setSystemUiVisibility(int))n etc) leads to either the Android system or the IME deciding to close or reopen.

The fact that some of thoses IME issues are specific to some IME and some phones makes this even harder to investigate. The Android version is also in play, for instance https://github.com/flutter/flutter/issues/148117#issuecomment-2166029309 does not happen on Android API 30 but it does on later Android versions.

**Comment by DeuMiAn** [comment]
@nkek1027  
I searched and analyzed your app and i think you used webview. I also don't have this symptom in textInput in webview, but when I use textInput provided by default by flutter, this symptom occurs.

**Comment by NilouMinooei** [comment]
I still have this issue with flutter 3.29.3 and Gboard
we have this functionality that we can navigate through app with physical keyboard (with tab and shift tab)
if the page has any kind of TextField after leaving it and navigating to next element, app dismisses the keyboard and from the next one after that, again triggers the soft keyboard.

some logs that might be helpful:
```
I/HandWritingStubImpl(29379): getCurrentKeyboardType: 1

I/HandWritingStubImpl(29379): isKeyboardTypeChanged: false

D/InputMethodManager(29379): showSoftInput() view=io.flutter.embedding.android.FlutterView{f477820 VFED..... .F...... 0,0-1080,2270 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT

2

I/HandWritingStubImpl(29379): isKeyboardTypeChanged: false

D/InputMethodManager(29379): showSoftInput() view=io.flutter.embedding.android.FlutterView{f477820 VFED..... .F...... 0,0-1080,2270 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT

I/AssistStructure(29379): Flattened final assist data: 496 bytes, containing 1 windows, 3 views

I/HandWritingStubImpl(29379): isKeyboardTypeChanged: false

W/OnBackInvokedCallback(29379): OnBackInvokedCallback is not enabled for the application.

W/OnBackInvokedCallback(29379): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.

2

D/InsetsController(29379): show(ime(), fromIme=true)

3

I/HandWritingStubImpl(29379): isKeyboardTypeChanged: false

W/OnBackInvokedCallback(29379): OnBackInvokedCallback is not enabled for the application.

W/OnBackInvokedCallback(29379): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.

I/HandWritingStubImpl(29379): isKeyboardTypeChanged: false

D/InsetsController(29379): show(ime(), fromIme=true)

I/HandWritingStubImpl(29379): isKeyboardTypeChanged: false
```
