### ISSUE TITLE
Cannot access 'android.arch.lifecycle.LifecycleOwner' which is a supertype of 'com.ex.app.MainActivity'. Check your module classpath for missing or conflicting dependencies

### ISSUE THREAD

**Issue by Adgeros** [flutter/flutter#52077]

**Comment by TahaTesser** [comment]
Hi @Adgeros 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by Adgeros** [comment]
I opened up the android project, the compile succeeded, but the ide reported an error

`flutter doctor -v`

```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.657], locale zh-CN)
    • Flutter version 1.12.13+hotfix.8 at D:\Flutter\flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-R, build-tools 29.0.3
    • ANDROID_HOME = D:\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] Connected device
    • Device 75ABBKM22SWH is not authorized.
      You might need to check your device for an authorization dialog.

! Doctor found issues in 1 category.

```

`flutter run --verbose`

**Comment by TahaTesser** [comment]
Hi @Adgeros 
Have you modified your `build.gradle` in anyway?
Can you post your `build.gradle`?
Thank you

**Comment by glitchedmob** [comment]
I think this issue might have something to do with a recent version of the Kotlin plugin for Android Studio. I had run into the error shortly after installing a recent update of that plugin. I created a brand new flutter project to make sure it wasn't just something weird with the project I was working on and I was still seeing this error there. After removing the plugin update I had installed the error disappeared.

I could be wrong but it appears to be what was causing issues for me.

**Comment by KohlsAdrian** [comment]
I think it is related to the new 1.3.70 kotlin version

**Comment by Skyost** [comment]
Got the same error with `1.3.50` kotlin version.

**Comment by KohlsAdrian** [comment]
try 1.3.61

**Comment by Skyost** [comment]
Thanks for your help @KohlsAdrian but it's still not working.

**Comment by mweiczorek** [comment]
Same issue here. I work on the Flutter project with VS Code, but I needed to open it in Android Studio to add a library to the native side of the project, and I get this same error with Kotlin 1.3.50. The fact that we're all getting the same errors with different versions of Kotlin would suggest the problem does not lie with Kotlin.

**Comment by mweiczorek** [comment]
Update. The FlutterActivity implements `android.arch.lifecycle.LifecycleOwner`, but the `android.arch`package is missing from my SDK.

Another issue is that the `app/build.gradle` file specifies API version 28, but the libraries show 29
![111](https://user-images.githubusercontent.com/224439/76400060-45869d80-63b2-11ea-8ffa-08eaa19d2b8a.png)

```
android {
    compileSdkVersion 28
    ....
    defaultConfig {
        ....
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
}
```
I haven't changed anything in either gradle file. All SDK's listed int eh SDK manager are labeled as 'Installed'. 

This project was created in the terminal with `flutter create`. This works perfectly using the emulator via the VS Code debugger, even with the missing package.

I created a new Flutter project using Adroid Studio with the exact same result.

I've looked at [this link](https://developer.android.com/jetpack/androidx/releases/lifecycle#kotlin) regarding adding this dependency manually (even though I am not using `androidx` artifacts, the method should be the same), but any change I make to the gradle file does not result in anything being downloaded and installed. In the past, when I build a native Android app with Java, any edits made to the gradle would immediately trigger the update (as indicated by a progress indicator at the right of the application's status bar). With this, nothing happens.

I should also note that I have no gradle functionality, and I have no way to open the "Project Settings" dialog.

**Comment by Adgeros** [comment]
I uninstalled the kotlin plugin to solve this problem

**Comment by jeromoney** [comment]
I fixed this issue by downgrading my Kotlin plugin from 1.3.70-release-Studio3.6-1 to [1.3.61-release-Studio3.6-1](https://plugins.jetbrains.com/plugin/6954-kotlin/versions) Even with the bug, Kotlin would compile just fine (flutter run), just wouldn't have access to the nice IDE features.

**Comment by blasten** [comment]
Did you follow the steps outlined on https://flutter.dev/docs/development/androidx-migration?   That error message indicates you haven’t migrated to AndroidX

**Comment by Skyost** [comment]
Yep. In fact, my project has been created using flutter 1.12.

**Comment by xster** [comment]
Can someone who can still reproduce this issue share their full app/build.gradle file (please remove PII) for us to better understand the issue? 

Please also describe how you did the integration from https://flutter.dev/docs/development/add-to-app/android/project-setup. Also confirm that 

```
compileOptions {
    sourceCompatibility 1.8
    targetCompatibility 1.8
  }
```

is present.

**Comment by bjzhou** [comment]
> Can someone who can still reproduce this issue share their full app/build.gradle file (please remove PII) for us to better understand the issue?
> 
> Please also describe how you did the integration from https://flutter.dev/docs/development/add-to-app/android/project-setup. Also confirm that
> 
> ```
> compileOptions {
>     sourceCompatibility 1.8
>     targetCompatibility 1.8
>   }
> ```
> 
> is present.

Android Studio: 3.6.1

for me, new project created by `File -> New -> New Flutter Project` can reproduce this issue too.

**Comment by Skyost** [comment]
@xster That was not added in my `build.gradle`. I've added it, did a refresh restart and still have the same error. Here's [my project](https://github.com/Skyost/UnicaenTimetable/tree/dart-rewrite) if you want.

**Comment by faithang** [comment]
I also have this same issue. I have uninstalled and installed the Kotlin plugin multiple times to no avail. Problem still persists. I am using the latest version of Kotlin, 1.3.70. I created my project with AndroidX artifacts - does that still mean I have to do the migration? 

To reproduce the issues, I create a new Flutter project through `File > New > New Flutter Project`. 

`flutter doctor -v`
`[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76,
    locale en-GB)
    • Flutter version 1.12.13+hotfix.8 at /Users/faith/Documents/flutter
    • Framework revision 0b8abb4724 (4 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/faith/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.0)
    • VS Code at /Users/faith/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (2 available)
    • AOSP on IA Emulator • emulator-5554                        • android-x86 •
      Android 9 (API 28) (emulator)
    • iPhone 11 Pro Max   • 570D77CB-B188-47E9-AFE7-8FE8EA64CDD3 • ios         •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)`

`app build-gradle`
`def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.lwn.lwntracker2"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
}`

**Comment by xuyisheng** [comment]
I have the same error, but the app can run as well, only the error lint in AS.

**Comment by Bottlezn** [comment]
My solution was downgrade the Kotlin Plguin from 1.3.70 to 1.3.61.    
I meet the same lint error when i update the Kotlin Plguin from 1.3.61 to 1.3.70.Although my app  
 still can run in debug-mode or release-mode.
It's was gone when i uninstall the updated Kotlin Plguin.
btw,my version of Android Stuido was 3.6.1_192.7142.36.36.6241897.

**Comment by dbacinski** [comment]
I am having the same error with Android Studio Koltin **Plugin** 1.3.70, but the app runs correctly.

With Kotlin **Plugin** 1.3.61, the error is not present.

The problem is that FlutterActivity depends on old support libraries and not androidx.

```
package io.flutter.embedding.android;

import android.arch.lifecycle.Lifecycle;
import android.arch.lifecycle.LifecycleOwner;
import android.arch.lifecycle.LifecycleRegistry;

public class FlutterActivity extends Activity
    implements FlutterActivityAndFragmentDelegate.Host,
    LifecycleOwner {
```

android.enableJetifier=true is used to automatically convert dependencies to androidx during the build process (and not before).

To solve this issue we should also have Flutter artifacts that depend on androidx. and don't need to use enableJetifier.

**Comment by KohlsAdrian** [comment]
This is my default class, with just `registerWith(this)` for firebase related plugins:
![Untitled 2](https://user-images.githubusercontent.com/6604704/76762805-be9a4200-6770-11ea-9bfe-df37504f50cd.png)

Project build.gradle(project) with latest kotlin plugin:
![Untitled](https://user-images.githubusercontent.com/6604704/76762810-be9a4200-6770-11ea-8552-bb67586054f1.png)

This guy fixed my lint errors in build.gradle(app)
![Untitled 3](https://user-images.githubusercontent.com/6604704/76762801-bcd07e80-6770-11ea-86e0-9a0b7fbc6be9.png)

Delete all `*.iml` files, and delete `.idea` folder inside android/app folder, sometimes references are broken causing lint errors
![lint](https://user-images.githubusercontent.com/6604704/76763254-86473380-6771-11ea-8c4f-aed53d2aaf4c.png)

Doing all these steps will fix most errors, I have this kind of issues constantly, if you get this fixed, make a feedback, I think I must be very important in this issue helping you guys, solved many things alone and never shared

**Comment by xuyisheng** [comment]
> This is my default class, with just `registerWith(this)` for firebase related plugins:
> ![Untitled 2](https://user-images.githubusercontent.com/6604704/76762805-be9a4200-6770-11ea-9bfe-df37504f50cd.png)
> 
> Project build.gradle(project) with latest kotlin plugin:
> ![Untitled](https://user-images.githubusercontent.com/6604704/76762810-be9a4200-6770-11ea-8552-bb67586054f1.png)
> 
> This guy fixed my lint errors in build.gradle(app)
> ![Untitled 3](https://user-images.githubusercontent.com/6604704/76762801-bcd07e80-6770-11ea-86e0-9a0b7fbc6be9.png)
> 
> Delete all `*.iml` files, and delete `.idea` folder inside android/app folder, sometimes references are broken causing lint errors
> ![lint](https://user-images.githubusercontent.com/6604704/76763254-86473380-6771-11ea-8c4f-aed53d2aaf4c.png)
> 
> Doing all these steps will fix most errors, I have this kind of issues constantly, if you get this fixed, make a feedback, I think I must be very important in this issue helping you guys, solved many things alone and never shared

I'm afraid it is not work for me ,I don't know why, I only update kotlin plugin to 1.3.70, sad

**Comment by dbacinski** [comment]
I am afraid that it can't be fixed without either fix in Kotlin Plugin that would respect `enableJetifier=true` or Flutter flavor of dependencies that depend on androidx.

**Comment by KohlsAdrian** [comment]
I am really sad that is not working for you guys, for me it is working flawlessly and perfect

**Comment by xster** [comment]
I've been trying to reproduce but haven't been able to so far. Trying on Android Studio 3.6.1. Gradle 5.6.4, Android gradle plugin 3.6.1, kotlin 1.3.70. I'm seeing emulators in the flutter doctors so I'm trying API 28 x86 emulators like described above. I'm still not able to reproduce.

I'm assuming using plugins are needed to reproduce this perhaps? 

Could someone confirm the exact set of conditions needed to reproduce this plus the list of plugins used?

**Comment by bctpl** [comment]
> 
> 
> I've been trying to reproduce but haven't been able to so far. Trying on Android Studio 3.6.1. Gradle 5.6.4, Android gradle plugin 3.6.1, kotlin 1.3.70. I'm seeing emulators in the flutter doctors so I'm trying API 28 x86 emulators like described above. I'm still not able to reproduce.
> 
> I'm assuming using plugins are needed to reproduce this perhaps?
> 
> Could someone confirm the exact set of conditions needed to reproduce this plus the list of plugins used?

It's produce issue everytime I created `File -> New -> New Flutter Project`  I have latest version of kotlin and downgrading kotlin version not solving issue.

**Comment by bjzhou** [comment]
@xster my my project can produce this issue on  windows computer, but works perfect on macOS.

**Comment by dbacinski** [comment]
To me the key thing was AS/Intellij Kotlin **Plugin** in version 1.3.70. Downgrade to 1.3.61 helped me:

![Screenshot from 2020-03-18 08-04-47](https://user-images.githubusercontent.com/454414/76934338-4017de80-68ef-11ea-9893-9bbaeaa8f274.png)

Version of Kotlin in project didn't matter for me.
I am on Ubuntu 18.04.3 LTS.

**Comment by xster** [comment]
I was trying on the Android Studio Kotlin plugin 1.3.70-release-Studio3.6-1. 

Can someone describe the complete repro environments so I can try to replicate? (though I only have a mac at home). 

AS version, Flutter version, gradle version, Android Gradle Plugin version, ideally a project in GitHub we can directly download and try to reproduce.

**Comment by Skyost** [comment]
@xster, [flutter doctor & gradle](https://github.com/flutter/flutter/issues/52077#issuecomment-597352231) + [my project](https://github.com/Skyost/UnicaenTimetable/tree/dart-rewrite) on Github.

**Comment by dev-horacebg** [comment]
This happens for me literally every single time I create a new Flutter project.

My setup:

```
macOS Catalina: 10.15.3 (19D76)

Android Studio 4.0 Beta 1
Build #AI-193.6494.35.40.6220182, built on February 19, 2020
Runtime version: 1.8.0_212-release-1586-b4-5784211 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
GC: ParNew, ConcurrentMarkSweep
Memory: 3987M
Cores: 16
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: BashSupport, Dart, org.jetbrains.kotlin, io.flutter, com.azoft.json2dart, com.localizely.flutter-intl, com.squareup.sqldelight
```

Flutter doctor:
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-GB)
    • Flutter version 1.12.13+hotfix.8 at /Users/horacebell-gam/flutter
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/horacebell-gam/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio 3.6 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[!] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio 3.6 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.0 Preview.app/Contents
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6494.35
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
    • iPhone 11 Pro Max         • 151EC602-72B6-4D2A-AC47-C14835B31A70 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

! Doctor found issues in 3 categories.

```
On this machine, I only use Flutter on Android Studio 4.0.
I've tried this with Kotlin plugins 1.3.61, 1.3.50 and 1.3.70 to no avail.

As others have mentioned above; the project still compiles and works as it should, it's just very difficult to write any Android code when _everything_ is an error.   

[Here is a simple repo](https://github.com/dev-horacebg/flutter_bug_repro) (an untouched default Flutter app) that demonstrates the issue.

**Comment by andvalsol** [comment]
is there any advance on this topic, I'm getting the exact same error. Also I can't see where I can add swift file in Android Studio

**Comment by xuyisheng** [comment]
Kotlin plugin 1.3.71 has the same error.

**Comment by YugeCse** [comment]
I have got the error,too, The situation is the same as theirs.

**Comment by pinhassi** [comment]
**The error is caused due to Kotlin plugin v1.3.71**
You download [previous version](https://plugins.jetbrains.com/plugin/6954-kotlin/versions) and manually install it: IntelliJ IDEA -> Preferences -> Plugins -> install plugin from disk
I opened an issue at [JetBrains](https://youtrack.jetbrains.com/issue/KT-37355)

**Comment by xster** [comment]
This shouldn't be closed. Reopening.

**Comment by xkeyC** [comment]
I uninstalled the kotlin plugin to solve this problem too!

**Comment by akadatsky** [comment]
@xster @Adgeros Any solution without uninstalling kotlin plugin?

**Comment by TahaTesser** [comment]
Reopened [comment](https://github.com/flutter/flutter/issues/52077#issuecomment-608107307)

**Comment by maddenbrain** [comment]
I still have this issue in my project.

**Comment by xkeyC** [comment]
> I still have this issue in my project.

You can try downgrade your kotlin plugin

**Comment by maddenbrain** [comment]
> > I still have this issue in my project.
> 
> You can try downgrade your kotlin plugin

This is not the solution to The Problem.
We have a pretty big and old project, there kotlin is main language. We are using latest kotlin features. And currently flutter added as a module. We are researching opportunities we can get with flutter. So we can easily remove flutter because of bugs.

**Comment by yy1300326388** [comment]
![image](https://user-images.githubusercontent.com/8764899/79047802-90aefd00-7c4b-11ea-8a0f-b8bffa8977c6.png)
![image](https://user-images.githubusercontent.com/8764899/79047829-bb995100-7c4b-11ea-85ff-ee2fd7ed2bd8.png)
![image](https://user-images.githubusercontent.com/8764899/79047873-f69b8480-7c4b-11ea-8f54-b1d2d9ca430f.png)

I am following [here](https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration) to upgrade my plugin, when I visit `ActivityControlSurface.java`, it prompts me to find To `Lifecycle`, my plugin is supported by` AndroidX`, so I think it is caused by `io.flutter.embedding` without migrating AndroidX.

@xster @TahaTesser

**Comment by fedochet** [comment]
@yy1300326388 Hi! Can you please try to enable `Enable code completion...` checkbox and see if that helps?
![image](https://user-images.githubusercontent.com/8393617/79048605-f5a42c00-7c26-11ea-90fe-034de9db6527.png)

**Comment by ochrin** [comment]
I have same issue with Kotlin 1.3.71 plugin.
I just enabled code completion, restarted Android Studio, but the problem is still here...

**Comment by yy1300326388** [comment]
![image](https://user-images.githubusercontent.com/8764899/79049022-9f011700-7c53-11ea-8311-118ee7d71334.png)

@fedochet  Do you see the configuration right? Doesn't seem to solve my problem.

**Comment by fedochet** [comment]
@ochrin @yy1300326388 can you please show how your `External Libraries` folder looks like?

![image](https://user-images.githubusercontent.com/8393617/79049164-7c0e3d00-7c2a-11ea-8acd-a2bd6d0ad929.png)

**Comment by ochrin** [comment]
Here they are (they all fit on my display so none is missing):
![Capture d’écran de 2020-04-11 18-34-26](https://user-images.githubusercontent.com/45735356/79049320-3a2dc880-7c23-11ea-8087-75fce601769a.png)

**Comment by yy1300326388** [comment]
![image](https://user-images.githubusercontent.com/8764899/79049463-6878cb80-7c56-11ea-8849-9bbea4e571ba.png)

@fedochet  Mine is like this

**Comment by yy1300326388** [comment]
@fedochet  I normally create a project here is no problem, maybe there is a problem with my usage, I refer to the usage of other people, I will try again.

**Comment by AyonAB** [comment]
Is there any workaround for this issue? For now at least.

**Comment by yapcwed** [comment]
Yap, seeing the same behavior when using  FlutterFragmentActivity. Tried adding the respective dependency as well as the androidx equivalent. Did not solve the issue. I have downgraded the Kotlin plugin to [1.3.61-release-Studio3.6-1(https://plugins.jetbrains.com/plugin/6954-kotlin/versions) as mentioned by @jeromoney. The syntax errors are still there just less obnoxious.

**Comment by xster** [comment]
I tried it on master again and still wasn't able to reproduce this.

I'm on 

Android Studio 3.6.1

<img width="648" alt="Screen Shot 2020-04-15 at 5 57 13 PM" src="https://user-images.githubusercontent.com/156888/79403435-caca1880-7f43-11ea-94b8-0cb09b02214d.png">

Kotlin plugin 1.3.72

<img width="1072" alt="Screen Shot 2020-04-15 at 5 59 36 PM" src="https://user-images.githubusercontent.com/156888/79403434-ca318200-7f43-11ea-921b-fc6adf7da5ab.png">

<img width="771" alt="Screen Shot 2020-04-15 at 6 00 00 PM" src="https://user-images.githubusercontent.com/156888/79403432-c998eb80-7f43-11ea-8a0e-0df79f700734.png">

The default main activity kotlin file correctly references FlutterActivity from the io.flutter:flutter_embedding_debug maven package

<img width="628" alt="Screen Shot 2020-04-15 at 6 05 13 PM" src="https://user-images.githubusercontent.com/156888/79403431-c998eb80-7f43-11ea-99b7-590ec20835f9.png">
<img width="1060" alt="Screen Shot 2020-04-15 at 6 05 22 PM" src="https://user-images.githubusercontent.com/156888/79403427-c69dfb00-7f43-11ea-862b-fa43bbd4e124.png">

2 follow up questions:

- Is there a difference between Flutter framework master and stable for reproducing this? 
- Is the issue that you're opening the Flutter project in Android Studio rather than the Android folder in the Flutter project in Android Studio? And when you do, classes weren't loading like below?
<img width="1394" alt="Screen Shot 2020-04-15 at 6 10 54 PM" src="https://user-images.githubusercontent.com/156888/79403714-825f2a80-7f44-11ea-9085-0571a11e113d.png">

If that's the issue, we might need to move this to the intellij plugin repo (cc @stevemessick or @devoncarew). It seems like there might be situations where we need to gradle sync when looking at the Android files of a Flutter project and we're not.

**Comment by Skyost** [comment]
@xster 

**Android Studio :**

<details>
<pre>
Android Studio 3.6.2
Build #AI-192.7142.36.36.6308749, built on March 18, 2020
Runtime version: 1.8.0_212-release-1586-b04 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1246M
Cores: 4
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: com.thoughtworks.gauge, com.vladsch.idea.multimarkdown, org.jetbrains.kotlin, com.google.services.firebase, Dart, io.flutter, pl.pszklarska.pubversionchecker
</pre>
</details>

**Plugins :**

<details>
<img src="https://user-images.githubusercontent.com/3882599/79438203-87b78600-7fd3-11ea-944c-cb2bb3b35eb4.png">
</details>

**build.gradle** :

<details>
<img src="https://user-images.githubusercontent.com/3882599/79439472-2b556600-7fd5-11ea-9d8d-bf894d2c0417.png">
</details>

App **build.gradle** :

<details>
<img src="https://user-images.githubusercontent.com/3882599/79439463-285a7580-7fd5-11ea-8c70-658d41564bd8.png">
</details>

**Flutter doctor :**

<details>
<img src="https://user-images.githubusercontent.com/3882599/79439724-77a0a600-7fd5-11ea-85b7-6201abf659c8.png">
</details>

**Opening the Flutter project :**

<details>
<img src="https://user-images.githubusercontent.com/3882599/79440752-a8350f80-7fd6-11ea-9b3c-009ca5075870.png">
</details>

**Opening the Android folder in the Flutter project :**

<details>
<img src="https://user-images.githubusercontent.com/3882599/79440065-da923d00-7fd5-11ea-9477-fefdfd08b96b.png">
</details>

**Comment by Kimxu** [comment]
Do not use Kotlin activity， Try to use Java activity 。can solve this problem

**Comment by Skyost** [comment]
@Kimxu This is definitely not a fix.

**Comment by baiyinshi** [comment]
I backtracked the version of the kotlin plugin into 1.36.1, and the error disappeared

**Comment by yapcwed** [comment]
@baiyinshi Correct me if I'm wrong but the error did not disappear. It is just not shown as prominently anymore. If you open `FlutterActivity.java` Android Studio still can't resolve any imports from `android.arch.lifecycle.*` and `android.support.annotation.*`.

**Comment by xster** [comment]
Thanks all for the data. In my limited ability to reproduce, I've determined that the issue is most likely in the IDE plugin since if I triggered a gradle sync, the upstream dependencies resolve.

**Comment by alex-pl** [comment]
Had a similar issue (not even using flutter) on my new MacBook with a fresh installation of IntelliJ IDEA. Build worked without issues but IDE showed many errors in the code and debugging was not possible. I fixed the problem by installing the current version of OpenJDK (e.g. `brew install java`) and setting it up for the project in the `Project Settings`.

**Comment by FavazCL** [comment]
I tried all possible solutions and none worked for me.

I decided to start a new flutter project with java. (flutter create -a java name_proyect)

**Comment by hs029** [comment]
> My solution was downgrade the Kotlin Plguin from 1.3.70 to 1.3.61.
> I meet the same lint error when i update the Kotlin Plguin from 1.3.61 to 1.3.70.Although my app
> still can run in debug-mode or release-mode.
> It's was gone when i uninstall the updated Kotlin Plguin.
> btw,my version of Android Stuido was 3.6.1_192.7142.36.36.6241897.

How to downgrade?

**Comment by david-huck** [comment]
encountered this bug, too. Out of nowhere.
Tried to downgrade to 1.3.61 as mentioned by @jeromoney by specifying the version in the build.gradle (android) file without luck though.

Then I updated the gradle version to 3.6.3, restarted Android Studio, but no luck.
However, building the app still works.

So with all things being up to date, there are still several things underlined displaying the "cannot access 'android...LifecycleOwner' error :/

**Comment by tolg** [comment]
> > My solution was downgrade the Kotlin Plguin from 1.3.70 to 1.3.61.
> > I meet the same lint error when i update the Kotlin Plguin from 1.3.61 to 1.3.70.Although my app
> > still can run in debug-mode or release-mode.
> > It's was gone when i uninstall the updated Kotlin Plguin.
> > btw,my version of Android Stuido was 3.6.1_192.7142.36.36.6241897.
> 
> How to downgrade?

1. https://plugins.jetbrains.com/plugin/6954-kotlin/update/73178 从这里下载后解压
2. 打开应用程序文件夹，找到Android Studio，右键->显示包内容->Contents->plugins
3. 用下载并解压的Kotlin文件夹替换plugins里面的Kotlin文件夹

**Comment by takecare** [comment]
i believe this is an issue with the android build and not with flutter. i'm seeing it in a 100% android project.

**Comment by asidt** [comment]
Same problem here, Flutter project, enabling code completion or moving kotlin gradle plugin to 1.3.61 and to 1.6.72 didn't help

**Comment by maheshkumar2150** [comment]
> I think it is related to the new 1.3.70 kotlin version
> 
> downgrading may fix the issue

How did you downgrade. The development was faster with flutter. Once i started to touch the android, everything is becoming worst. The implementation for iOS was super fast. But android is giving me headache

Please tell me how to downgrade.

**Comment by lhholylight** [comment]
I downgrade kotlin from 1.3.70 to 1.3.61 didn't help

**Comment by MichaelM97** [comment]
This is fixed for me on Gradle version `3.3.0` and Kotlin version `1.3.72`.
Can anybody test if this is also the case for the latest Gradle version `3.6.3`?
(I can't as one of my apps dependencies causes build issues on the latest Gradle version)

**Comment by arunkbabu90** [comment]
Same issue here

**Comment by darrinps** [comment]
I'm on the latest Kotlin 1.3.72, and running Gradle 3.6.3 and I see it.

My app build.gradle looks like this

`def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 29

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.hagerty.flutterwithnativeble"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.robotpajamas.blueteeth:blueteeth:0.2.0'
    implementation 'com.jakewharton.timber:timber:4.7.1'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.2'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.2'
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-rx2:1.3.2"
    implementation "android.arch.lifecycle:extensions:1.1.1"

}
`

When I try to debug a line of my native Kotlin code I see that message.

Cannot access 'androidx.lifecycle.LifecycleOwner' which is a supertype of 'com.mycompany.flutterwithnativeble.MainActivity'

**Comment by nihithreddy** [comment]
I recently updated my android studio to 4.0  as it is stable.Now when i create a new flutter project iam getting the same error.Can any one tell me how to resolve it?

**Comment by TesLake** [comment]
This is the error I get

C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_secure_storage-3.3.3\android\src\main\java\com\it_nomads\fluttersecurestorage\FlutterSecureStoragePlugin.java:56: error: cannot access LifecycleOwner
      initInstance(binding.getBinaryMessenger(), binding.getApplicationContext());
                          ^
  class file for android.arch.lifecycle.LifecycleOwner not found
1 error

**Comment by xster** [comment]
Since this is a closed issue, we're not actively monitoring it anymore. If you're still experiencing issue, please file a new bug with reproduction details so we'll put it back on our roadmap.

If you're entirely unable to build on Android, it's likely a flutter framework issue. Please file in this repo. If it builds but you're seeing errors in Android Studio, it's likely an IntelliJ plugin issue. Please file in https://github.com/flutter/flutter-intellij.

**Comment by lalitkhandal** [comment]
To fix this issue need to enable code completion option.

![image](https://user-images.githubusercontent.com/5876372/83951813-e241c580-a851-11ea-843d-36bd937ace33.png)

**Comment by OseyereProg** [comment]
> I recently updated my android studio to 4.0 as it is stable.Now when i create a new flutter project iam getting the same error.Can any one tell me how to resolve it?

I am having the samae issue too

**Comment by lalitkhandal** [comment]
> > I recently updated my android studio to 4.0 as it is stable.Now when i create a new flutter project iam getting the same error.Can any one tell me how to resolve it?
> 
> I am having the samae issue too

Please look into my reply. Thanks

**Comment by kevinbtesar** [comment]
Fixed it. For me, it was because I didn't have the Flutter SDK path set in the Settings (aka Preferences)  -> Language & Frameworks -> Flutter -> Flutter SDK path.
<img src="http://kevintesar.com/mPublic/flutterFixForAS.png">

**Comment by Harishpenta** [comment]
I have upgraded my Flutter version from **1.12.13+hotfix.8** to **1.17.2** and it worked for me.

**Comment by TemuulenA** [comment]
I was having this problem too. The problem was I have changed flutter version to other version than created this project. So I changed flutter version to original version that created project. Hope this helps.

**Comment by Licloudev** [comment]
![image](https://user-images.githubusercontent.com/80983281/111868249-29c8b680-8979-11eb-87b9-02792d4ca3d7.png)

in my case i updating kotlin version in settings. its okey now
