### ISSUE TITLE
Text on desktop Windows 10 looks rough(no antialiasing)

### ISSUE THREAD

**Issue by nerocui** [flutter/flutter#53308]
Flutter channel: master
Flutter version: 1.16.3-pre.40
Windows 10 build: 19592
Monitor native resolution: 3840x2160
System resolution: 2560x1440
Scaling: 100%
[![Annotation-2020-03-25-141948.png](https://i.postimg.cc/7L5vFdWk/Annotation-2020-03-25-141948.png)](https://postimg.cc/qtHZnbrb)

Left is flutter, right is UWP(expected text smoothing)

A more closed up screenshot comparison
[![flutter.png](https://i.postimg.cc/tCnxg4nZ/flutter.png)](https://postimg.cc/D8FZjFgn)
flutter
[![uwp.png](https://i.postimg.cc/MT4Gk1Ds/uwp.png)](https://postimg.cc/0MYvDMhm)
uwp

Reproduction steps:
In powershell, run
`$env:ENABLE_FLUTTER_DESKTOP="true"`
In terminal, run
`flutter config --enable-windows-desktop`
`flutter create <your-app-name>`
`flutter run -d windows`
See the text on the screen for result

**Comment by timsneath** [comment]
Can you give us the results of `flutter doctor -v` just for completeness? I haven't seen this on my machine... This is the five hour-old Windows Insider build, right? Have you seen this on older builds?

**Comment by nerocui** [comment]
[✓] Flutter (Channel master, v1.16.3-pre.40, on Microsoft Windows [Version 10.0.19592.1001], locale en-US)
    • Flutter version 1.16.3-pre.40 at C:\src\flutter
    • Framework revision ec3653f41d (4 hours ago), 2020-03-25 11:57:05 -0700
    • Engine revision 945967054b
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 62f84880ef)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Nero\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.5.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.5.29920.165

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.43.1)
    • VS Code at C:\Users\Nero\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • Windows • Windows • windows-x64 • Microsoft Windows [Version 10.0.19592.1001]

• No issues found!

**Comment by nerocui** [comment]
@timsneath Yes it's a new windows insider build. I have not yet tried it on other builds. I can do it tho, testing in something like a vm.

**Comment by clarkezone** [comment]
Is the UWP using XAML for the text?

**Comment by nerocui** [comment]
@clarkezone Yes it's a text block.

**Comment by clarkezone** [comment]
What font are you using in each case?

**Comment by nerocui** [comment]
@clarkezone both default. I didn't change font family, font size or font weight.

**Comment by clarkezone** [comment]
Also how do they compare if you increase the scaling to 150%.  We’ve implemented per monitor V2 DPI support in flutter on windows so on a high DPI display with scaling set at an appropriate value,  the perceived quality should be better than when running at 100% as there are more pixels to antialias over.

**Comment by clarkezone** [comment]
> @clarkezone both default. I didn't change font family, font size or font weight.

It’s not an apples to apples comparison if you are using different fonts.

**Comment by nerocui** [comment]
New screenshots, both using Lato font, 14 font size, 400 font weight. Taken on both 100% scaling and 150% scaling.
[![samefontflutter.png](https://i.postimg.cc/MGbFcyyW/samefontflutter.png)](https://postimg.cc/gwjDQLS5)
Flutter at 100% scaling
[![samefontuwp.png](https://i.postimg.cc/tTsvB8Kg/samefontuwp.png)](https://postimg.cc/wydkv4TK)
UWP at 100% scaling
[![samefontflutter150.png](https://i.postimg.cc/SxVZkyqs/samefontflutter150.png)](https://postimg.cc/jDw6hYD0)
Flutter at 150% scaling
[![samefontuwp150.png](https://i.postimg.cc/jSqX8GNr/samefontuwp150.png)](https://postimg.cc/Cztk5rmv)
UWP at 150% scaling

**Comment by timsneath** [comment]
Looking at those two screenshots, I'm still seeing a difference in the font being rendered: only the Flutter screenshot is Lato. Compare the descenders on the lower case letter 'y' with the [Google Fonts Lato page](https://fonts.google.com/specimen/Lato).

Sorry to continue to push on this, but having a like-for-like comparison is important. It may simply be that what you're observing is the result of these font differences, or simply expected differences between different text shaping engines. (Windows itself isn't pixel-identical for font rendering across WinForms, WPF and UWP, for example, at least last time I worked on it.)

**Comment by knopp** [comment]
@dnfield, won't raster cache become a problem here? There might be inconsistent result depending on which layers are raster cached, which can change dynamically. 

In general it's not possible to do subpixel antialiasing with transparent background (on OS X there is `CGContextSetFontSmoothingBackgroundColor` private API that sets "fake" background color of CGContext so that subpixel antialiasing works over NSEffectView, but to my best of knowledge there is no such thing in Skia) so I'm a bit worried that subpixel antialiasing will be on/off depending on whether rasterized layer paints background below text or not

**Comment by dnfield** [comment]
OSX is dropping support for subpixel antialiasing, and we won't be supporting it there.

In general, it's not something we'll be toggling on or off unless you move to a display that doesn't support it. I'm not really clear what the problem would be. It's not as if we'd toggle it on for one layer and off for another layer in the same scene - and the way I'm planning to do this will be at the surface level anyway, not at the layer level.

**Comment by knopp** [comment]
@dnfield, imagine the following LayerTree

```
Container
  - PictureLayer A (paints background)
  ...
  - PictureLayer B (paints transparent text)
```

Normally both of these layers will be painted to same surface and subpixel antialiasing will work. However eventually, after few frames, the engine may decide that it is worth raster-caching PictureLayer B so it will rasterize PictureLayer B to a transparent surface. And that point, you'll lose the subpixel antialiasing, because that only works when drawing text to a non-transparent background.

**Comment by dnfield** [comment]
Ahh, I see what you're saying now.

I guess one "easy" way to work around this would be to exclude anything that contains text from the raster cache.

@chinmaygarde @bungeman WDYT?

**Comment by knopp** [comment]
That'd certainly help, although my hunch is that most expensive layers (worth rasterizing) are going to contain text. Also raster-caching will work just fine if (non transparent) background underneath the text is painted in same layer.

I don't think there is a silver bullet solution here. I'm guessing there is a good reason why Apple dropped subpixel antialiasing, and so did Microsoft in UWP. This is a tricky thing to solve and may require additional (user provided) hints coming from the framework.

**Comment by knopp** [comment]
Also another problem with flutter being blurry on desktop may be that many widgets will simply not be aligned on physical pixel boundary. This may not be obvious on high resolution phone/tablets displays, but can be very obvious on desktop.

I haven't given this much though, but I think layout widgets (Flex, Center, etc) should make best effort to land the children positions and dimensions on physical pixel boundaries.

**Comment by dnfield** [comment]
Yeah, we have a number of physical pixel boundary related issues - someone recently tried to patch it for images, but there are a bunch of things that can end up impacting that (#67041)

**Comment by dnfield** [comment]
I'm curious about how often we actually raster cache a single layer with a transparent background. I would have thought we would raster cache composited layers in that case.

**Comment by knopp** [comment]
@dnfield, I think layer hierarchy is only cached for `OpacityLayer` and `ImageFilterLayer`. Otherwise PictureLayers are cached individually.

**Comment by cjng96** [comment]
Is there any progress or plans on this issue? text quality is important to our app.

**Comment by DesmondFox** [comment]
Any progress?

**Comment by tofutim** [comment]
Gray normal text looks particularly bad on Windows.

![image](https://user-images.githubusercontent.com/157766/140781652-7682c68f-1520-4676-9cff-f2956f2efe14.png)

**Comment by tofutim** [comment]
Depending on what surrounds my Text widget, I see different aliasing in Windows. First is just normal flutter, 

![image](https://user-images.githubusercontent.com/157766/140783177-289b0a45-a9b9-4549-b487-eb65a02c6aed.png)

second the widget (look at the definitions) is inside an SfDataGrid.

![image](https://user-images.githubusercontent.com/157766/140783218-24f871de-4981-4888-9b00-d14c593b130a.png)

**Comment by tofutim** [comment]
I agree that Windows fonts look rough. Any progress on this?

**Comment by rokk4** [comment]
Has someone found a solution to this?

**Comment by tofutim** [comment]
As alluded to above, I found that Windows was not actually pulling the Roboto font at all. I ended up having to do the following:
```
         textTheme: GoogleFonts.robotoTextTheme(Theme.of(context).textTheme),
```
which brought the roboto fonts to my app on Windows.

**Comment by pdyason** [comment]
Do we have any updates on this now that desktop is better supported?

**Comment by asmith20002** [comment]
This issue is still there. Text on windows looks bad.

**Comment by emexal-company** [comment]
I 've just downloaded the application https://www.appflowy.io/, and I'm seeing the font rendering on Windows 10 is very bad. The application is almost unusable because of that.

**Comment by wharjack** [comment]
> I 've just downloaded the application https://www.appflowy.io/, and I'm seeing the font rendering on Windows 10 is very bad. The application is almost unusable because of that.

Hi! I was just searching for a fix for AppFlowy's font rendering problem on Windows 10 but I think we can't fix it and only the Devs can.

**Comment by cjng96** [comment]
The RenderRepaintBoundary has the toImage function with the pixelRatio parameter.

I found that a low pixelRatio value reduces the text quality of the generated image.

Can I set the virtual internal pixelRatio for Windows platform before rastering on the screen?

I think Android and iPhone has a higher DPI, so text quality is better. but generally the DPI of Windows desktop and the web on  Windows is low,  so the text quality is not good. 

However, as in the case of the toImage function, If we can set virtual high pixelRatio for text, it can help text quality.

Is it possible?

**Comment by sirgru** [comment]
This is extremely disappointing. Please look into https://github.com/flutter/flutter/issues/63043
