### ISSUE TITLE
Creating multiple engines crashes on Windows

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#53372]
I did some refactoring to make the Windows runner template not be so specific to a single engine+window; in theory it should be possible to make any number of windows in a process, each with their own engine. In practice, doing so very quickly crashes. From just a bit of initial investigation:
- The Flutter view window class registration always uses the same name, and it's done in each instance. We should either use a unique name (e.g., include the pointer value), or use a class name registrar as I did in the runner.
- Even with that fixed, there was quickly a crash deep in ANGLE code. I assume it's probably a configuration error at the embedding level, assuming code will only run once, rather than an ANGLE bug, but it'll need investigation.

/cc @clarkezone FYI. (Not a priority at the moment, but something we'll need to fix if it still happens post surface restructuring.)

**Comment by stuartmorgan** [comment]
@clarkezone Is `AngleSurfaceManager` multi-instance safe? I'm not sufficiently familiar with the GL code, but there's some code that seems suspicious (e.g., all instances using the default display, and each of them destroying the display in their destructors--that wouldn't explain this crash since it happens before closing any window, but maybe the whole pipeline is incorrectly sharing things?).

**Comment by stuartmorgan** [comment]
I'm going to take this off the alpha list; it's obviously something we need to fix, but since it seems very likely to be related to the creation of the surface, which is internal to the engine, I think it's very unlikely that fixing this will require any API changes.

**Comment by clarkezone** [comment]
I didn't specifically test that scenario so likely not.

**Comment by stuartmorgan** [comment]
https://github.com/stuartmorgan/engine/commit/e48ce683a53a56d5cb5ada9373a9b547ac550000 should fix the first issue; I haven't turned it into a PR yet since I was hoping to get it working end-to-end first. It could be landed separately though.

**Comment by stuartmorgan** [comment]
I suspect having multiple render threads interacting with ANGLE may be the issue here; I'll try a custom task runner setup with a shared render thread and see if that prevents the crash.

**Comment by stuartmorgan** [comment]
I've verified that using a shared render thread fixes this. As expected it then crashes when closing one of the windows, due to some incorrect destructor code (like that referenced above, but also I believe some in the ANGLE manager as well), but that should be straightforward to fix.

**Comment by stuartmorgan** [comment]
@knopp How feasible is fully separating the ANGLE state? That may be simpler than a custom renderer task runner, depending.

**Comment by knopp** [comment]
Shared render thread doesn't completely fix this, because `make_resource_current` is invoked from I/O thread and if frame render is in progress it will crash it. Possible solution is to ensure that angle creates separate egl display for each instance, so there is no shared state.

**Comment by knopp** [comment]
I'll push PR in few minutes.

**Comment by stuartmorgan** [comment]
Awesome! I'll set you as the assignee then, since you're actively working on it. I'm happy to have someone with actual expertise here take over 🙂

**Comment by stuartmorgan** [comment]
(Presumably that will also fix the issue mentioned above where the surface manager is currently tearing down global state in its destructor.)

**Comment by knopp** [comment]
Not sure if I'd call it expertise :), but I do have multi window prototype up and running an so far no issues during clean-up if there is no shared state.

**Comment by knopp** [comment]
So, I did get stuck here a bit. The reason why multiple engine crash, is that when calling `eglGetPlatformDisplayEXT`, Angle reuses existing display if any exists, which results in shared non thread safe state.

To the best of my knowledge, the only way to prevent Angle reusing display is right now to use `EGL_PLATFORM_ANGLE_ANGLE` when creating display with custom created d3d11 device. The major issue here, other than duplicating code already present in Angle is that as far as I can tell there is no way to create display from a D3D9 device. 

So if we go with the custom device approach, multiple engines will crash as soon as flutter falls back to d9d device. If fixing this in Angle (i.e. adding flag to explicitly request not to reuse existing display) something that can be considered?

Another approach would be to move all rasterization to single thread, but that doesn't solve egl_resource_context (AngleSurfaceManager::MakeResourceCurrent) which is invoked from I/O thread. 

@stuartmorgan, @clarkezone, any ideas?

**Comment by knopp** [comment]
Actually, I can't reproduce the crash anymore after [this](https://github.com/google/angle/commit/e7ca0aa289b0d9a9df8f4099d7630c652c570a0e) landed in Angle. So I'm guessing multiple contexts in different threads were actually supposed to work and it was a bug in the end.

**Comment by knopp** [comment]
I don't think the window class registration is a big issue, duplicate registrations just (silently) fail and class won't get unregistered while any windows of such class exist. The Angle crash got fixed. Perhaps this can be closed?

**Comment by stuartmorgan** [comment]
> and class won't get unregistered while any windows of such class exist.

Oops, I missed that in the doc, and assumed it would lead to issues. There are a few things that should still potentially be salvaged from that PR (using a fixed class name instead of basing it on the window title, using the DLL rather than the exe as the module)—@cbraken to decide if you want to follow up on those—but if the crash no longer happens we should in fact close it.
