### ISSUE TITLE
Scrollbar always shown property bugs when set to true

### ISSUE THREAD

**Issue by kunit1** [flutter/flutter#53771]
When setting Scrollbar isAlwaysShown to true the following bugs are observed.
1. The scrollbar will only show and persist after scrolling at least once using the mouse wheel or by dragging.

2. If the application is in debug mode and the isAlwaysShown property is changed by the developer from false to true, a hot reload will cause an assertion error to be thrown.

Both feature and bug introduced in [PR50752](https://github.com/flutter/flutter/pull/50752)
cc\ @justinmc @onatcipli 

## Steps to Reproduce
Reproduced on Desktop Web
Reproduced on Desktop Windows
```
@override
  Widget build(BuildContext context) {
    return Material(
      color: Colors.white,
      child: Scrollbar(
        isAlwaysShown: true, // Toggle then hot reload
        child: ListView(
          children: <Widget>[
            for (int i = 0; i < 20; i++)
              ListTile(
                leading: CircleAvatar(
                  child: FlutterLogo(size: 20),
                ),
                title: Text("Jon Do"),
                subtitle: Text("Some Text"),
                trailing: Text("Other Text"),
                onTap: () {},
              )
          ],
        ),
      ),
    );
  }
```

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel master, v1.16.4-pre.33, on Microsoft Windows [Version 10.0.18363.720], locale en-CA)
    • Flutter version 1.16.4-pre.33 at D:\flutter
    • Framework revision aee9e94c21 (2 days ago), 2020-03-30 16:12:40 -0700
    • Engine revision c779894d08
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 1402e8e1a4)

 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\kusay\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_SDK_ROOT = C:\Users\kusay\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.3.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.3.29424.173

[!] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code, 64-bit edition (version 1.43.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (3 available)
    • Windows    • Windows    • windows-x64    • Microsoft Windows [Version 10.0.18363.720]
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.149
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

```
```

```
```

</details>

**Comment by onatcipli** [comment]
thank you for reporting this, I will try to reproduce the problem and try to find a solution to that

**Comment by emilyab3** [comment]
Experiencing this issue too! The crash is as follows:

`I/flutter (20070): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (20070): The following assertion was thrown during a scheduler callback:
I/flutter (20070): 'package:flutter/src/material/scrollbar.dart': Failed assertion: line 111 pos 20: 'widget.controller
I/flutter (20070): != null': is not true.
I/flutter (20070):
I/flutter (20070): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (20070): more information in this error message to help you determine and fix the underlying cause.
I/flutter (20070): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (20070):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (20070):
I/flutter (20070): When the exception was thrown, this was the stack:
I/flutter (20070): #2      _ScrollbarState.didChangeDependencies.<anonymous closure> (package:flutter/src/material/scrollbar.dart:111:20)
I/flutter (20070): #3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
I/flutter (20070): #4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1060:9)
I/flutter (20070): #5      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
I/flutter (20070): #9      _invoke (dart:ui/hooks.dart:261:10)
I/flutter (20070): #10     _drawFrame (dart:ui/hooks.dart:219:3)
I/flutter (20070): (elided 5 frames from class _AssertionError and dart:async)
I/flutter (20070): ════════════════════════════════════════════════════════════════════════════════════════════════════`

**Comment by onatcipli** [comment]
I did debug the case and figure out the problem @justinmc 
 
1: `Scrollbar`'s `isAlwaysShown` property is false
2: toggle it to true
3: expect to be shown

first of all, `CupertinoScrollbar` works fine but in material `Scrollbar` the `didChangeDependencies` not calling after a dependency(`isAlwaysShown`) change. However, this progress works fine in `CupertinoScrollbar` so that I  update `didUpdateWidget` as following
```dart
  @override
  void didUpdateWidget(Scrollbar oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (widget.isAlwaysShown != oldWidget.isAlwaysShown) {
      assert(widget.controller != null);
      if (widget.isAlwaysShown == false) {
        _fadeoutAnimationController.reverse();
      } else {
        widget.controller.position.didUpdateScrollPositionBy(0);
        _fadeoutAnimationController.animateTo(1.0);
      }
    }
  }
```
this line added 
`        widget.controller.position.didUpdateScrollPositionBy(0); `

it solves the current bug but I think we should figure out why `didChangeDependencies`

**Comment by justinmc** [comment]
@onatcipli Thanks for following up and looking into this!  If that solution works, do you think we should open a PR for it?  I'm happy to help out with code review again.  If you do, can you include an example of how to reproduce the problem?

I think we still need to fix the crash that @kunit1 reported, too.

**Comment by onatcipli** [comment]
@justinmc I already open it, https://github.com/flutter/flutter/pull/54128

I also added test case to the PR so you can get the scenario 


> first of all, `CupertinoScrollbar` works fine but in material `Scrollbar` the `didChangeDependencies` not calling after a dependency(`isAlwaysShown`) change. However, this progress works fine in `CupertinoScrollbar` so that I update `didUpdateWidget` as following

to explain it again, when I change the value of `isAlwaysShown` `didChangeDependencies` calling on `CupertinoScrollbar` but in material `Scrollbar` it isn't calling so that the painter has no information about the `ScrollMetrics` that's way `Scrollbar` couldn't appear. 

In `CupertinoScrollbar` this case works fine because after `isAlwaysShown` change `didChangeDependencies` calling

**Comment by justinmc** [comment]
Thanks for the explanation and for opening the PR already!  I thought we fixed that bug in the original PR, but it must have snuck back in because I can reproduce it.  I'll review your new PR.

**Comment by justinmc** [comment]
For anyone having this problem, keep in mind that you should be using a ScrollController on both the ListView and Scrollbar when using isAlwaysShown.  That should help with some of the problems here if you're seeing the exception mentioned above.

Then we should be ready with a fix in https://github.com/flutter/flutter/pull/54128 soon.

**Comment by k3wals** [comment]
@justinmc Thanks for your comment. Adding the controller to Scrollbar **AND** Listview prevented the assert.
```
Widget _buildEventsList() {
      return Align(
          alignment: Alignment.topCenter,
          child: Scrollbar(
            controller: _scrollController,
            isAlwaysShown: true,
            child: ListView.separated(
              itemCount: events.length,
              padding: const EdgeInsets.all(16.0),
              separatorBuilder: (BuildContext context, int index) => SizedBox(height: 5,),
              reverse: true,
              shrinkWrap: true,
              controller: _scrollController,
              itemBuilder: (BuildContext context, int index) {
...
```

**Comment by kunit1** [comment]
I am still seeing the exception after the PR was merged on the latest master
`flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: 'package:flutter/src/material/scrollbar.dart': Failed assertion: line 134 pos 16: 'widget.controller
flutter: != null': is not true.`

**Comment by justinmc** [comment]
@kunit1 Are you passing a controller to both the scrollbar and a scroll view?

I've opened https://github.com/flutter/flutter/pull/58258 to make the error messages a bit more clear.

**Comment by kunit1** [comment]
@justinmc I am not. I guess I misunderstood the purpose of the PR. I thought that the we won't need pass the controller to the scrollbar after the PR. However, looking at the code diff I see that it's still expecting controller. I am okay with passing controller when isAlwaysShown is set to true it would just be slightly more convenient if it worked without having to do it.

I didn't too deep into the code, but just curious about the reason that it's now required to pass the controller. Is it because of the need to send a scroll event to paint the thumb?

**Comment by justinmc** [comment]
Yeah exactly.  Without the controller, we wouldn't be able to make the thumb show in the case that the user hasn't scrolled at all yet.  I think it would be more confusing to work around the error and have that case not work without a controller, so I've explicitly made it clear that a controller is needed.

I think that's the best we can do in that situation.

**Comment by kunit1** [comment]
That sounds good to me. I appreciate all the work that went into fixing this issue. Please feel free to close this issue as you see fit.

**Comment by esskar** [comment]
I can still reproduce the problem that the scrollbar is only permanently shown when the content is initially scrolled with `isAlwaysShown` set to `true`.

**Comment by onatcipli** [comment]
Can you share the example code that you're reproducing the case

**Comment by esskar** [comment]
@onatcipli  I tried to add the functionality to a library, the commit sums it up
https://github.com/esskar/flutter-intro-slider/commit/4ab12038fe4e4277e9e72c3161c22802ebcc6abe

**Comment by esskar** [comment]
Is this enough, or do you need a full example?

**Comment by esskar** [comment]
What i noticed: the described behaviour happens initially; when i close and reopen the view/screen, the scrollbar is shown directly - as if it keeps some sort of cached information about the view. when i close and restart the app, the behaviour is again that the scrollbar is only shown after the initial scroll

**Comment by MartinhoMCM** [comment]
The solution is : 
Create a **`ScrollController`** variable (`ScrollController _scrollController`);
Instatiate _scrollController  inside initState() or wherever you want,    `_scrollController = ScrollController();`
Add _scrollController variable inside **Scrollbar**  and **ListView** properties,  **`controller:_scrollController`**

Here's the code:


```
ScrollController _scrollController;
  @override
  void initState() {
    super.initState();
    _scrollController = ScrollController();
  }
Scrollbar(
        isAlwaysShown: true,
         controller: _scrollController,
         child: ListView(
         controller: _scrollController,
   )
```

**Comment by esskar** [comment]
@MartinhoMCM i pretty much did that. i will try to reproduce the problem in a full working example

**Comment by esskar** [comment]
Ok, the problem occurs when i have content with images, that i load as assets without specifying the exact witdh/height. When i preload the images (or setting the height), the scrollbar behaves as expected.

**Comment by esskar** [comment]
The trick with preloading the images does only work on the simulator. on the real device it is not reliable. I played around with adding a container with a height that is greater then the available content but less then the expected height: the scrollbar is shown but when i start scrolling, the height of the scrollbar is adjusted. so it seems like that the initial height calculation is not working properly, and thats why it is not scrolling the scrollbar. any clues?

**Comment by kevin4dhd** [comment]
Create two controllers work correctly, no error appears

![image](https://user-images.githubusercontent.com/22886367/115949096-20f76300-a498-11eb-85fe-f8e1812b4e37.png)

But if that widget is hidden and turned into a drawer to be responsive, the following error appears

![image](https://user-images.githubusercontent.com/22886367/115949122-4e441100-a498-11eb-86c9-517a16936de4.png)

══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
Assertion failed: file:///C:/flutter/packages/flutter/lib/src/widgets/scroll_controller.dart:108:12
_positions.isNotEmpty
"ScrollController not attached to any scroll views."

When the exception was thrown, this was the stack:
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49     
throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3       
assertFailed
packages/flutter/src/widgets/scroll_controller.dart 108:23                                                                 getposition
packages/flutter/src/widgets/scrollbar.dart 862:25
<fn>
packages/flutter/src/scheduler/binding.dart 1144:15
[_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1090:9
handleDrawFrame
packages/flutter/src/scheduler/binding.dart 998:5
[_handleDrawFrame]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/platform_dispatcher.dart 896:13
invoke
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/platform_dispatcher.dart 145:5
invokeOnDrawFrame
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine.dart 259:45
<fn>

**Comment by nguyenxndaidev** [comment]
So will flutter team reopen and fix this issue or must developers apply the workaround https://github.com/flutter/flutter/issues/53771#issuecomment-693368430?

**Comment by khangahs** [comment]
I have the same issue with Scrollbar when building with widget which is hidden and animate responsively. I also followed @MartinhoMCM 's solution, however, the issue still persists. Please open this issue promptly.

**Comment by justinmc** [comment]
Can someone that's still having this problem open a new issue with a reproduction case and tag me?

**Comment by artoniaz** [comment]
I run into the same issue and I believe it's not the issue with flutter itself but rather confusing error message. 
So when you use
`isAlwaysShown: true`
you need to have the same scrollController defined for the Scrollbar **AND** the scrollable child (in my case ListView).
