### ISSUE TITLE
Running the any flutter app in Moto E (2nd Gen, 2015, codename: surnia) glitches.

### ISSUE THREAD

**Issue by edelvalle** [flutter/flutter#5383]
## Steps to Reproduce

I complied the Gallery example that comes with flutter and tried it in the Android emulator and everything went Ok; then I build the apk and tried to install it in my Moto E 2015 (2nd Gen) runing Android 6.0.1 CyanogenMod 13. and seems that the GPU does not know what to draw.

![](http://oi67.tinypic.com/2vnl66c.jpg)

## Flutter Doctor

[✓] Flutter (on Linux, channel alpha)
    • Flutter at /home/xigurat/d/flutter
    • Framework revision 9a0a0d9903 (30 hours ago), engine revision f8d80c4617

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at /home/xigurat/Android/Sdk
    • Platform android-23, build-tools 23.0.3
    • Java(TM) SE Runtime Environment (build 1.8.0_102-b14)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.35

## Logs and Crash Reports

Running it like:

`$ flutter run --debug`

Does not show any unusual and `adb logcat` don't show anything interesting aside from some network interaction.

**Comment by edelvalle** [comment]
This morning I compiled the same app and installed it in another Moto E 2015 (2nd gen, code name: surnia)  that uses the official ROM and I had the same results.

**Comment by abarth** [comment]
/cc @chinmaygarde 

It looks like we're not drawing properly and what you're seeing is uninitialized GPU memory.  We'll probably need to get our hands on a Moto E to replicate the issue.

**Comment by edelvalle** [comment]
I will rename this issue with the name of the device on it.

**Comment by eseidelGoogle** [comment]
We recently added some code to print GPU information when initialization fails.  But presumably initialization is succeeding here and we're still drawing garbage?  @chinmaygarde

I've ordered one and it will be on my desk Thurs.

**Comment by chinmaygarde** [comment]
Yeah. In case of any initialization errors, a lot of diagnostic information should be dumped before process termination. This is odd. Will investigate on an actual device.

**Comment by edelvalle** [comment]
Thanks, I'm looking forward for updates here :D

**Comment by eseidelGoogle** [comment]
Turns out I already have a Moto E.  Not sure if it's second gen or not.  I've placed it on your desk @chinmaygarde.

**Comment by chinmaygarde** [comment]
@eseidelGoogle, I have not been able to reproduce the issue on that device.It is a good device for profiling though. Will wait the device you ordered.

**Comment by eseidelGoogle** [comment]
The device has arrived, I just haven't picked it up from the mailroom yet.  I'll put it on your desk in the morning.

In terms of ordering, It's actually more important IMO that we reduce https://github.com/flutter/flutter/issues/5231 first so that we can get Skia starting to fix that. :)  Regardless, you'll have the other Moto E on your desk in the morning and you can do as you please.  Thanks!

**Comment by chinmaygarde** [comment]
Should be fixed on master on the engine.

**Comment by edelvalle** [comment]
This means that if I checkout flutter master and build for this phone it should work?

**Comment by eseidelGoogle** [comment]
Yes.  If master does not work on your phone please let us know!

**Comment by edelvalle** [comment]
@eseidelGoogle still not working, check out what I did (tell me if I'm doing something wrong)

```
flutter (alpha):days ago > git checkout  master 
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
flutter (master):hours ago > git pull
Already up-to-date.
flutter (master):hours ago > cd examples/flutter_gallery/
flutter (master):hours ago examples/flutter_gallery/ > flutter run
Building flutter tool...
Downloading package sky_engine...                    1.1s
Running 'pub get' in sky_engine...                   0.6s
Downloading package sky_services...                  0.5s
Running 'pub get' in sky_services...                 3.2s
Building Dart SDK summary...                         10.3s
Downloading engine artifacts android-arm...          2.5s
Downloading engine artifacts android-arm-profile...  2.4s
Downloading engine artifacts android-arm-release...  2.3s
Downloading engine artifacts android-x64...          1.9s
Downloading engine artifacts android-x86...          1.6s
Downloading engine artifacts linux-x64...            2.6s
Downloading linux-x64 tools...                       2.6s
Downloading android-arm-profile/linux-x64 tools...   3.4s
Downloading android-arm-release/linux-x64 tools...   2.9s
Running 'pub get' in flutter_gallery...              1.5s
Building APK in debug mode (android-arm)...              
Warning: signing the APK using the debug keystore.
Built build/app.apk (14.8MB).
Running lib/main.dart on XT1524...
--------- beginning of main
Observatory listening on http://127.0.0.1:8100
Diagnostic server listening on http://127.0.0.1:8101
Application running.
Connected to view '_flutterView/0xaa93eac0'.
Type "h" or F1 for help, "r" or F5 to restart the app, and "q", F10, or ctrl-c to quit.
Type "w" to print the widget hierarchy of the app, and "t" for the render tree.
```

And flutter doctor

```
[✓] Flutter (on Linux, channel master)
    • Flutter at /home/xigurat/d/flutter
    • Framework revision 20b9750a73 (17 hours ago), 2016-08-23 16:17:36
    • Engine revision 28e9b3bc49
    • Tools Dart version 1.19.0-dev.5.0

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.1)
    • Android SDK at /home/xigurat/Android/Sdk
    • Platform android-24, build-tools 24.0.1
    • Java(TM) SE Runtime Environment (build 1.8.0_102-b14)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.37
```
