### ISSUE TITLE
Potential memory leak issue in iOS

### ISSUE THREAD

**Issue by ksantiyanont** [flutter/flutter#54937]
We found a potential memory leak issue in iOS when our application is starting to crash more and more often in iOS. So, we created a test application to try to narrow down the scope. We found that even in our simple test app, the issue is still observable.

## Steps to Reproduce

1. Clone https://github.com/noleplay81/FlutterPluginMemoryTest/tree/IncludeHereMapView 
2. Run the application
3. After open and close the main map screen multiple times, the app will crash

**Expected results:** Application continue to run smoothly

**Actual results:** Application crash, out of memory

<details>
  <summary>Logs</summary>
Here is a sample profile from one of the test runs we did:

![1586752846243](https://user-images.githubusercontent.com/1126038/79431561-94ed6880-8005-11ea-88aa-fde57ed805be.png)

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.1 19B88, locale ko-KR)
    • Flutter version 1.12.13+hotfix.9 at /Users/*****/documents/flutter
    • Framework revision f139b11009 (13 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2
 
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/*****/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
 
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4
 
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
 
[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
 
[✓] Connected device (1 available)
    • ***** • ceb23a85ee8489e850d733d2ea4f35202d316802 • ios • iOS 13.3.1
```
</details>

**Comment by ksantiyanont** [comment]
Just want to add one additional information. We have also tried this with different widget (different map provider). It yields the same result so it should not have caused by the HERE Map plugin that we use in the posted sample app.

**Comment by zoeyfan** [comment]
@liyuqian FYI.

**Comment by cyanglaz** [comment]
@ksantiyanont Does this happen on device or on the simulator?

**Comment by cyanglaz** [comment]
@ksantiyanont I believe we had some PR landed to fix memory leak issues recently https://github.com/flutter/engine/pull/14326
https://github.com/flutter/engine/pull/14275
Unfortunately, it seems that they are not in the stable yet. If you change flutter to `dev` or `master`, it should fix the leak.

**Comment by Hixie** [comment]
@ksantiyanont Can you try the dev channel and see if you still see the leak?

**Comment by zhongwuzw** [comment]
@cyanglaz @Hixie Hi, This issue still existed, I created a PR to fix it.https://github.com/flutter/engine/pull/18164

**Comment by Hixie** [comment]
@zhongwuzw That's great! Should I assign the bug to you?

**Comment by zhongwuzw** [comment]
@Hixie Good, I'll fix it.

**Comment by zhongwuzw** [comment]
@Hixie Good, I'll fix it.

**Comment by Hixie** [comment]
@zhongwuzw Awesome. Do you have an estimated target milestone, just so we can update the bug? Definitely no rush, it can be far in the future, we just like to have an estimate so that people can plan around it. (See https://github.com/flutter/flutter/wiki/Issue-hygiene.)

**Comment by zhongwuzw** [comment]
@Hixie Hi, https://github.com/flutter/engine/pull/18164 fixed this, and already approved by @gaaclarke .

**Comment by joaovirgili** [comment]
> @ksantiyanont I believe we had some PR landed to fix memory leak issues recently [flutter/engine#14326](https://github.com/flutter/engine/pull/14326)
> [flutter/engine#14275](https://github.com/flutter/engine/pull/14275)
> Unfortunately, it seems that they are not in the stable yet. If you change flutter to `dev` or `master`, it should fix the leak.

is this already available on stable channel ?
