### ISSUE TITLE
SliverList Performance Issue for Building Large Dynamic List

### ISSUE THREAD

**Issue by Peng-Qian** [flutter/flutter#55144]
## Problem:

I found restoring the page position of SliverList with a large dynamic list that will be significantly slow and results in screen freeze. But there is no problem if use SliverGrid to build the same list.

Please use the following demo code to reproduce the problem.

If you have any idea of this problem or any suggestions for the usage of SliveList, please let me know.

Many Thanks!

## Demo
![list_view_performance](https://user-images.githubusercontent.com/37643086/79685366-75b43c80-828c-11ea-8498-2e93d63a8b7a.gif)

## Demo Code

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Lab',
      theme: ThemeData(
        primarySwatch: Colors.blueGrey,
        backgroundColor: Colors.white,
      ),
      home: MainApp(),
    );
  }
}

class MainApp extends StatefulWidget {
  MainApp({Key key}) : super(key: key);

  @override
  _MainAppState createState() => _MainAppState();
}

class _MainAppState extends State<MainApp>{
  int _tabIndex;

  @override
  void initState() {
    super.initState();
    _tabIndex = 0;
  }

  void _selectPage(int index) {
    setState(() {
      _tabIndex = index;
    });
  }

  Widget get _body {
    switch (_tabIndex) {
      case 0:
        return Center(child: Text('Home Page'));
      case 1:
        return CustomScrollView(
          key: PageStorageKey('grid'),
          slivers: <Widget>[
            SliverAppBar(
              pinned: true,
              title: Text('Grid View Builder'),
            ),
            SliverGrid(
              gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                childAspectRatio: 10/1,
                crossAxisCount: 1,
              ),
              delegate: SliverChildBuilderDelegate(
                    (context, index){
                  return Card(
                    color: Colors.blue[300],
                    child: Center(child: Text('Grid View $index')),
                  );
                },
                childCount: 1000,
              ),
            ),
          ],
        );
      case 2:
        return CustomScrollView(
          key: PageStorageKey('lsit'),
          slivers: <Widget>[
            SliverAppBar(
              pinned: true,
              title: Text('List View Builder'),
            ),
            SliverList(
              delegate: SliverChildBuilderDelegate(
                    (context, index){
                  return SizedBox(
                    height: MediaQuery.of(context).size.width/10,
                    child: Card(
                      color: Colors.blue[300],
                      child: Center(child: Text('List View $index')),
                    ),
                  );
                },
                childCount: 1000,
              ),
            ),
          ],
        );
      default:
        return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: _body,
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: _tabIndex,
        onTap: _selectPage,
        backgroundColor: Colors.blueGrey,
        selectedItemColor: Colors.blue[300],
        unselectedItemColor: Colors.white,
        items: [
          BottomNavigationBarItem(icon: Icon(Icons.home), title: Text('Home'),),
          BottomNavigationBarItem(icon: Icon(Icons.grid_on), title: Text('Grid')),
          BottomNavigationBarItem(icon: Icon(Icons.view_list), title: Text('List'),),
        ],
      ),
    );
  }
}
```

## Logs

```
Analyzing lab...                                                        
No issues found! (ran in 1.5s)
```

```
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale zh-Hans-NZ)
    • Flutter version 1.17.0 at /Users/pq/Developer/SDK/flutter
    • Framework revision d3ed9ec945 (13 days ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/pq/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.6494.35

[✓] Connected device (2 available)
    • sdk gphone x86    • emulator-5554             • android-x86 • Android 10 (API 29) (emulator)
    • iPhone 11 Pro Max • 00008030-001208443AD0802E • ios         • iOS 13.4

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @pqsky7 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 

It seems smooth on latest `dev`
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287,
    locale en-GB)
    • Flutter version 1.12.13+hotfix.9 at /Users/taha/Code/flutter_stable
    • Framework revision f139b11009 (3 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API
      29) (emulator)
• No issues found!
```

</details>

Thank you

**Comment by pqsky7** [comment]
Hi @TahaTesser ,
Have you scrolled to the end of the list before the test?
I already provided `flutter doctor -v` above and the 'flutter run --verbose' seem print very long log, should I paste all of it?
I just test the above code on the lasted dev channel and beta channel, this problem happens in both versions.

**Comment by liyuqian** [comment]
Calculating the height of those dynamic list items might be the reason why it's slow as illustrated in https://github.com/flutter/flutter/issues/52207. I'm surprised that the problem only exists in SliverList but not SliverGrid. CC @dnfield for visibility.

**Comment by Kavantix** [comment]
@liyuqian the grid has a fixed aspect ratio, maybe that’s why?

**Comment by amankr** [comment]
from the docs of sliver.dart : 
```If the children have a fixed extent in the main axis, consider using
[SliverFixedExtentList] rather than [SliverList] because
[SliverFixedExtentList] does not need to perform layout on its children to
obtain their extent in the main axis and is therefore more efficient.

**Comment by liyuqian** [comment]
@Kavantix @amankr thanks for the info! Yes, indeed `SliverGrid` fixes the aspect ratio and the width (cross-axis) is usually fixed as well so it's equivalent to have a `SliverList` where the height (extent) is fixed.

**Comment by darshankawar** [comment]
Hi @Peng-Qian,
I tried your code sample on latest beta on Android emulator (api 29) and didn't notice the performance issue. I scrolled to the end of both lists and tried to switch between tabs to see the behavior.

[55144_1.mov.zip](https://github.com/flutter/flutter/files/5282789/55144_1.mov.zip)


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.4 19E2269, locale
    en-IN)
    • Flutter version 1.22.0-12.1.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8b3760638a (9 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    •
      Android 10 (API 29) (emulator)
    • Web Server (web)                   • web-server    • web-javascript •
      Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript •
      Google Chrome 85.0.4183.121

• No issues found!

```

</details>

Can you verify at your end on latest version to see if you still get the issue ?
Thanks.

**Comment by Kavantix** [comment]
@darshankawar you can see it in your video
When you click on the grid tab it switches instantaneously but when you click on the list there is a delay

This is btw causes because the list is not mounted anymore when switching tabs so it needs to go through the entire list to calculate which items to show at the stored scroll offset

**Comment by Peng-Qian** [comment]
Hi @darshankawar , 

The problem still there on lasted beta on Android emulator 28/30/R.

```
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.6 19G2021, locale en-NZ)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.2)
[✓] VS Code (version 1.46.0)
[✓] Connected device (1 available)
```

![listview](https://user-images.githubusercontent.com/37643086/94277542-d105fb80-ff9d-11ea-95b0-543f4861fc74.gif)

**Comment by eugene-kalaganov** [comment]
there is no performance issue with SliverList

if you add `print('$index')`you'll see that SliverList rebuilds ALL 1000 items after bottom bar clicked
because list doesn't know height of list item and it have to be calculated for every list item
GridView has `childAspectRatioParameter`

as mentioned above you need to use `SliverFixedExtentList`
```
            SliverFixedExtentList(
              itemExtent: MediaQuery.of(context).size.width / 10,,
              delegate: SliverChildBuilderDelegate(
                (context, index) {
                  return SizedBox(
                    height: MediaQuery.of(context).size.width / 10,
                    child: Card(
                      color: Colors.blue[300],
                      child: Center(child: Text('List View $index')),
                    ),
                  );
                },
                childCount: 1000,
              ),
            ),
```
and that performance "issue" will magicaly disappeared

**Comment by Peng-Qian** [comment]
Hi, @eugene-kalaganov ,

I don't think you really understand the problem. 

Firstly, high performance means efficiency, and it mainly involves time complexity and space complexity. This is an obvious performance issue for Flutter rendering, and that is why it is marked as 'severe: performance' by the Flutter team.

Secondly, finish to build a widget does not mean flutter finish the rendering, I hope you understand how Flutter works.

Thirdly, the Flutter team member is already elaborate on the reason for this problem, but a reason does not mean a solution. what if there is a list view contains a large amount of the dynamic height list item? (And this is common use case)

Personally, I think there are two possible solutions: 
1. when PageStorageKey applied to CustomScrollView, it also saves the current extent height in the state (if this approach does not involve high memory usage), so when the user back to the page, the time-consuming calculation may be avoided.  

1. compute the extent height in a different isolate, but it may involve breaking changes as the builder function in SliverChildBuilderDelegate may need a snapshot parameter like FutureBuilder.

**Comment by eugene-kalaganov** [comment]
i think you don’t understand the problem and how it works, not me

the tag added by regular user doesn’t mean the real issue exist

**Comment by dnfield** [comment]
I'd encourage all participants in this issue to review the Flutter Code of Conduct. Please make sure we are treating each other respectfully. I would also suggest that a great way to show which side of a technical disagreement about performance would be to write some benchmarks :)

----

I'll add to this that this issue seems very similar to some other ones we have filed about the performace of rapidly scrolling through a long list of items. In general, if you don't tell the framework ahead of time about the height of the slivers, it will have to do a lot of work to figure that out for you. We have to come up with a way to give developers more control over that though, since you may not want every sliver to be exactly the same height (but we could figure out more quickly than actually doing the layout forall the widgets in all the slivers we'll have to show).

**Comment by Kavantix** [comment]
I agree with @dnfield, there is definitely a possibility of improving performance here and with long lists in general.
However I want to add that the native platforms are also doing things to improve these same issues (which we might look at as examples)
For instance on iOS there is the possibility to have the height of a cell be dynamic, this however means that the initial scrolling and scrollbar and such will be done using an estimated cell size instead of actual sizes such that not everything will need to be layed out. And it also has some drawbacks like weird jerky behavior when reloading the list.

For flutter however we could do something similar or perhaps something entirely different, my point being that it will definitely not be trivial and might even require every user to optimise somewhat for their usecase.

As for the exact performance issue pointed out by this issue something like solution 1 of @Peng-Qian sounds possible to me
And as a workaround in the mean time I suggest to use the keepalive machanism

@dnfield could you link (some) of these other issues here?

**Comment by dnfield** [comment]
https://github.com/flutter/flutter/issues/59404 is the main one I have in mind. I think there may be others, but that one has a lot of discussion.

**Comment by Peng-Qian** [comment]
Hi @Kavantix and @dnfield,

thx for your reply and suggestion, sorry to be a little bit aggressive. I should be more patient to explain the problem here.

I am waiting for this optimization for a while and the quality of our products deeply relies on Flutter. we are really seeking Flutter to have an awesome performance.

for [#59404](https://github.com/flutter/flutter/issues/59404), we also notice that Flutter List sometimes may have a high CPU and Memory usage when contains images( but we are currently more focusing on feature development, not a performance optimization, I did not dig this too much yet).

I found two articles (from Alibaba, [Article one](https://mp.weixin.qq.com/s/Mcfj3lRR8VJACxsjjIiVsA) and [Article two](https://developer.aliyun.com/article/753812)) that have a really nice understanding and explanation for this particular issue. It also provides a solution, but personally, I think the solution is too complicated since the improvement is not significant. (Unfortunately, these articles are written in Chinese, but I am sure the Flutter team has someone who can understand Chinese.)

**Comment by dnfield** [comment]
Ah, that one might be related, but I actually meant to link this one: #52207

**Comment by cangSDARM** [comment]
Is this issue resolved?

**Comment by siddharthadevops** [comment]
Hi, I have been developing with this platform for a short time and I am not sure that the solution that I am going to propose is possible.

I think it would be interesting to implement a view whose position is determined by the index of the element plus the visible pixels of that element.

Thus, instant view positioning could be done. The renderer would start with the element in question, and from that position, it would go back until the screen was completed.
The scrolling could be done by elements or by pixels. If done by pixels, it would work as the current implementation does.

Rendering the entire view to establish a position is a very poor design. I think there must be a better method to do this. Applications like WhatsApp implement scrolling in tens of thousands of items in a smooth way.

**Comment by maxwell-nc** [comment]
may be CustomScrollView bug or SliverList bug in some case.
SliverFixedExtentList is work fine because itemExtent

**Comment by Levi-Coinmerce** [comment]
Adding `ValueKey`'s to, for example the SliverList already improved performance on my side.

**Comment by Piinks** [comment]
We're in the stages of planning to resolve this, so I am going to close this issue to refer to https://github.com/flutter/flutter/issues/52207 to focus all conversation and updates in one place. That one has the highest number of upvotes regarding this performance issue, and is why I chose it. Thank you all for providing test cases on this!
