### ISSUE TITLE
Hot reload received invalid response: {type: Sentinel, kind: Collected, valueAsString: <collected>}

### ISSUE THREAD

**Issue by vanlooverenkoen** [flutter/flutter#56455]
I am constantly receiving this error on 1.17.0

```
Hot reload received invalid response: {type: Sentinel, kind: Collected, valueAsString: <collected>}
```

flutter doctor 

```
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E266, locale en-BE)
    • Flutter version 1.17.0 at /Users/vanlooverenkoen/flutter
    • Framework revision e6b34c2b5c (4 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/vanlooverenkoen/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (1 available)
    • iPhone 11 • 69AE6491-C438-4A06-8C08-B7443994F67D • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!
```

**Comment by christopherfujino** [comment]
@vanlooverenkoen thank you for filing! To help us debug, could you run the following commands:

```
cd /Users/vanlooverenkoen/flutter
git merge-base --is-ancestor 485188886 e6b34c2b5c; echo $?
```

This is specifically checking if https://github.com/flutter/flutter/commit/4851888864348524b4065e18cd6e2597f906fd8d is included in your git history of the flutter tool. I would expect the output to be `1` (meaning it is not), but if it is `0` (meaning it is), then something with either the release process or your upgrade flow got messed up.

Also, did you upgrade via `flutter upgrade`?

**Comment by vanlooverenkoen** [comment]
The output is indeed 1. 

Yes I did a flutter upgrade

When I hot restart the app works. but after "some" time I get the error again.

**Comment by jonahwilliams** [comment]
Could you include the output of `flutter run -v` from one of these hot reload runes thats crashing? This might give us a hint where the error might be.

**Comment by HugoHeneault** [comment]
This seems related to https://github.com/flutter/flutter/issues/55552. Having the issue too, will try to provide some logs when it fails :

**Comment by Lucas0Braz** [comment]
I am facing the same issue some times

**Comment by fralways** [comment]
Im getting this error very often. nothing seems to fix it, just a complete restart of the app.
```
Performing hot reload...
[   +2 ms] Refreshing active FlutterViews before reloading.
[        ] Sending to VM service: _flutter.listViews({})
[   +3 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x10883ee20, isolate: {type: @Isolate, fixedId: true, id:
isolates/183285536330507, name: main.dart$main-183285536330507, number: 183285536330507}}]}
[   +8 ms] Scanned through 670 files in 5ms
[        ] Syncing files to device Filip's iPhone...
[        ] Scanning asset files
[  +29 ms] Compiling dart to kernel with 1 updated files
[   +1 ms] <- recompile package:p83/main.dart 6a196a14-895f-4236-8fb2-654839256ad1
[        ] package:p83/providers/main_hub_provider.dart
[        ] <- 6a196a14-895f-4236-8fb2-654839256ad1
[ +255 ms] Updating files
[  +50 ms] DevFS: Sync finished
[        ] Syncing files to device Filip's iPhone... (completed in 337ms)
[        ] Synced 0.7MB.
[   +2 ms] Sending to VM service: _flutter.setAssetBundlePath({isolateId: isolates/183285536330507, viewId: _flutterView/0x10883ee20, assetDirectory:
/private/var/mobile/Containers/Data/Application/E277520D-88AB-4C77-ABFA-FC63D1D16E28/tmp/p83-flutterghLjDj/p83-flutter/build/flutter_assets})
[   +3 ms] Result: {type: Success, view: {type: FlutterView, id: _flutterView/0x10883ee20, isolate: {type: @Isolate, fixedId: true, id: isolates/183285536330507,
name: main.dart$main-183285536330507, number: 183285536330507}}}
[   +1 ms] Sending to VM service: _reloadSources({pause: false, rootLibUri:
file:///private/var/mobile/Containers/Data/Application/E277520D-88AB-4C77-ABFA-FC63D1D16E28/tmp/p83-flutterghLjDj/p83-flutter/lib/main.dart.incremental.dill,
isolateId: isolates/1859235700279611})
[        ] Sending to VM service: _reloadSources({pause: false, rootLibUri:
file:///private/var/mobile/Containers/Data/Application/E277520D-88AB-4C77-ABFA-FC63D1D16E28/tmp/p83-flutterghLjDj/p83-flutter/lib/main.dart.incremental.dill,
isolateId: isolates/183285536330507})
[   +3 ms] Result: {type: Sentinel, kind: Collected, valueAsString: <collected>}
[ +221 ms] Notification from VM: {streamId: Isolate, event: {type: Event, kind: IsolateReload, isolate: {type: @Isolate, id: isolates/183285536330507, name: main,
number: 183285536330507}, timestamp: 1589758008960, status: success}}
[        ] Result: {type: ReloadReport, success: true, details: {finalLibraryCount: 1140, receivedLibraryCount: 33, receivedLibrariesBytes: 781976,
receivedClassesCount: 134, receivedProceduresCount: 2, savedLibraryCount: 1107, loadedLibraryCount: 33, shapeChangeMap...
[   +2 ms] <- reject
[  +68 ms] Hot reload received invalid response: {type: Sentinel, kind: Collected, valueAsString: <collected>}
+2 ms] Performing hot reload... (completed in 658ms)
[        ] Try again after fixing the above error(s).
```

**Comment by rohitsainik** [comment]
I am also facing the same error 
`Hot reload received invalid response: {type: Sentinel, kind: Collected, valueAsString: <collected>}`

**Comment by CCLemonMaster** [comment]
Me as well.
Performing hot reload...
Syncing files to device Android SDK built for x86...
Hot reload received invalid response: {type: Sentinel, kind: Collected, valueAsString: <collected>}

**Comment by mhswork** [comment]
Sorry to say but after upgrading the flutter last week (current version being 1.17.1), I get this error often (on my VSCode) and this spoils the whole idea of decreasing development time because Hot reload is not working and I have to restart it everytime. Downgrading to previous version is not the apt way out. 

Any better solution is needed at the earliest.

**Comment by sebastiw** [comment]
I also got this error.
```
[✓] Flutter (Channel stable, v1.17.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.0 at /opt/flutter
    • Framework revision e6b34c2b5c (3 weeks ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/seba/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • G8141 • CB512EUXV7 • android-arm64 • Android 9 (API 28)

• No issues found!
```
It is the same as #7248 which fixed it for me by running `flutter doctor`. Took a while to debug :P

**Comment by sultanularefin** [comment]
I have faced this issue in Windows where my flutter version is this:
_Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.752], locale en-US)_
 With **flutter doctor** 

i just ran **./gradlew clean** from android directory and **flutter clean** from project directory and now hot reload is working. It happened today and yesterday too.

**Comment by dev-caritativo** [comment]
I faced same issue. What I did was 

on the terminal: **flutter clean**

then I clicked STOP

![image](https://user-images.githubusercontent.com/63072522/82745857-afacbd00-9dbb-11ea-9367-058228a01b38.png)

Then click **Run without Debugging**

now everything works fine :)

**Comment by HugoHeneault** [comment]
It seems an hotfix has been approved for 1.17 in https://github.com/flutter/flutter/issues/55552#issuecomment-631744053: 
> eng approval for cp of #53960 into 1.17

**Comment by vinothvino42** [comment]
I am also getting the same issue but it's working when I run without debugging in VSCode. My flutter version is v1.17.1 (stable channel) on macOS.

**Comment by andrros3030** [comment]
Got this issue right now, doctor says that there is no issues found, hot restart works, but hot reload doesn't

**Comment by meherulsust** [comment]
I am facing the issue 
Performing hot reload...
Hot reload received invalid response: {type: Sentinel, kind: Collected, valueAsString: <collected>}

**Comment by Melak12** [comment]
I am facing the same problem on Android Studio with the latest Flutter Release v1.17.

**Comment by TheFe91** [comment]
Me too, same problem on IntelliJ with Flutter 1.17, please solve quickly!

**Comment by mittalsam98** [comment]
I am also facing this issue, pls solve ASAP as it decrease the dev time and as I have te restart the app again and again

**Comment by HugoHeneault** [comment]
Still having this issue on 1.17.2, even with https://github.com/flutter/flutter/issues/55552 cherrypicked...

Seems to only happen during debug mode on Android Studio thought.

**Comment by makadiyakeval** [comment]
I faced Same Issue

I tried to run following commands in Terminal :

**flutter clean**

**flutter run**

and it worked for me.

**Comment by macabeus** [comment]
I'm having the same issue as well...
Sometimes the hot reload works on my iPhone, and when I receive this error message, I need to stop and start the debug session again.

**Comment by BEARlogin** [comment]
I'm too having the issue  on VsCode, Flutter v1.17.2

**Comment by aerosasi** [comment]
Is there any proper solution to get rid of this , i need to cold restart my app literally everytime and this is so bad . One of the main reason for using the flutter has been the hot reload but with this i cant perform the hot relod ... Let me knw if someone got solution for it ,

**Comment by zhuyifan2013** [comment]
Same issue. .

**Comment by kuntojirohan** [comment]
Has this issue come up with the latest release (1.17.3)?

**Comment by quetool** [comment]
> Has this issue come up with the latest release (1.17.3)?

Yes! I upgraded yesterday to 1.17.3 and this is still a very annoing issue. I find myself frequently hot restarting the project... 

```
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale es-AR)
    • Flutter version 1.17.3 at /Users/alfredo/Desktop/flutter
    • Framework revision b041144f83 (5 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/alfredo/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPhone Alfredo • 00008020-001A03CE1161002E • ios • iOS 13.4.1

• No issues found!
```

**Comment by aerosasi** [comment]
Ya even me upgraded it and deleted all build files with flutter clean. Then restarted it . Somehow after some point it stopped popping up.

**Comment by leonardopaim** [comment]
Same issue... Flutter 1.17.3

**Comment by kalismeras61** [comment]
Same issue Flutter 1.17.3

**Comment by stylehuan** [comment]
restart simulator  and it worked for me.

**Comment by BEARlogin** [comment]
It happens only with debugger enabled in vscode and idea. "flutter run" works properly

**Comment by macabeus** [comment]
> It happens only with debugger enabled in vscode and idea. "flutter run" works properly
@DanTup Could you check this, please? It's a bug that are affecting many users  ⬆️

**Comment by DanTup** [comment]
> @DanTup Could you check this, please? It's a bug that are affecting many users ⬆️

I'm not very familiar with what this code is doing, but in https://github.com/flutter/flutter/issues/55552#issuecomment-643369679 @jonahwilliams has requested logs from someone that can still repro. You can use the [**Dart: Capture Logs**](https://dartcode.org/docs/logging/#capture-logs-command) command to get verbose logs through VS Code (you can untick Analysis Server, but easiest to leave everything else ticked).

There's also https://github.com/flutter/flutter/issues/55552#issuecomment-643871430 suggesting it doesn't repro on `master`, so I wonder if there are other changes that contributed to fixing it that weren't included in the latest hotfix.

**Comment by BEARlogin** [comment]
> > @DanTup Could you check this, please? It's a bug that are affecting many users ⬆️
> 
> I'm not very familiar with what this code is doing, but in [#55552 (comment)](https://github.com/flutter/flutter/issues/55552#issuecomment-643369679) @jonahwilliams has requested logs from someone that can still repro. You can use the [**Dart: Capture Logs**](https://dartcode.org/docs/logging/#capture-logs-command) command to get verbose logs through VS Code (you can untick Analysis Server, but easiest to leave everything else ticked).
> 
> There's also [#55552 (comment)](https://github.com/flutter/flutter/issues/55552#issuecomment-643871430) suggesting it doesn't repro on `master`, so I wonder if there are other changes that contributed to fixing it that weren't included in the latest hotfix.

Here my logs
[Dart-Code-Log-2020-05-01 16-32-08.txt](https://github.com/flutter/flutter/files/4780546/Dart-Code-Log-2020-05-01.16-32-08.txt)

**Comment by DanTup** [comment]
@BEARlogin it'd be better to post them on the other issue, as this one should probably be closed as a dupe.

You should start logging before launching the debug session though, as that will run Flutter with `-v`, as I the info Jonah was after might only appear in verbose mode.

Since the new log will be very large, the useful parts are probably between the reload request:

```
[{"id":"22","method":"app.restart","params":{
```

And the error:

```
Hot reload received invalid response: {type: Sentinel, kind: Collected, valueAsString: <collected>}
```

**Comment by mambel** [comment]
> I faced same issue. What I did was
> 
> on the terminal: **flutter clean**
> 
> then I clicked STOP
> 
> ![image](https://user-images.githubusercontent.com/63072522/82745857-afacbd00-9dbb-11ea-9367-058228a01b38.png)
> 
> Then click **Run without Debugging**
> 
> now everything works fine :)

Works for me

**Comment by DanTup** [comment]
According to https://github.com/flutter/flutter/issues/55552#issuecomment-647673706 this is fixed on the beta channel. If anyone still sees it on there, please comment on #55552 (to keep everything in one issue). Thanks!

**Comment by fjlJENNY** [comment]
> and it worked for me.

it work for me

**Comment by fjlJENNY** [comment]
> I faced Same Issue
> 
> I tried to run following commands in Terminal :
> 
> **flutter clean**
> 
> **flutter run**
> 
> and it worked for me.

it works for me

**Comment by adarshbalu** [comment]
> I faced same issue. What I did was
> 
> on the terminal: **flutter clean**
> 
> then I clicked STOP
> 
> ![image](https://user-images.githubusercontent.com/63072522/82745857-afacbd00-9dbb-11ea-9367-058228a01b38.png)
> 
> Then click **Run without Debugging**
> 
> now everything works fine :)

Tried this. But it just does not work for me.

**Comment by ivan-pavliuk** [comment]
This issue is still around. I can always replicate it on a simulator, for example, iPhone X 14.3.
Flutter 1.22.5

**Comment by apoleo88** [comment]
I found this bug with 
`Flutter 1.25.0-8.3.pre • channel beta`

**Comment by jonasbark** [comment]
It happened to me because of outdated build caches. Running `flutter clean` on the project fixed it.

The last version that I compiled was without build flavors on Android, then I pulled the changes that introduced flavors, ran the build again, and while it started up correctly a lot of things were not working properly. Among other debugging breakpoints and hot reload + hot restart gave the issue from this GitHub issue. 
No idea why it could compile in the first place.
