### ISSUE TITLE
TextField show error "SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length" when typing space

### ISSUE THREAD

**Issue by Aljabri-Salman** [flutter/flutter#56514]
I am getting this error after updating to 1.17.0 version. The text field used to work fine before. Whenever I type space it types extra space then unable to delete the text.

my code:
```
class SearchScreen extends StatefulWidget {
  @override
  _SearchScreenState createState() => _SearchScreenState();
}

class _SearchScreenState extends State<SearchScreen> {
  TextEditingController _searchController = TextEditingController();

  @override
  void dispose() {
    _searchController.dispose();
    super.dispose();
  }

  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (_) => SearchProvider(),
      child: Builder(builder: (context) {
        SearchProvider searchProv = Provider.of<SearchProvider>(context);
        return Scaffold(
          drawer: KiraDrawer(),
          appBar: AppBar(
            title: Form(
              key: _formKey,
              child: TextField(
                enableSuggestions: false,
                controller: _searchController,
                style: tajwal.copyWith(
                  color: Colors.white,
                  fontSize: 14,
                ),
                decoration: InputDecoration(
                    border: InputBorder.none,
                    hintText: 'أدخل للبحث',
                    hintStyle: TextStyle(color: Colors.white)),
                onChanged: (String value) {
                  print(value.length);
                  searchProv.fetchResults(newSearch: true, query: value);
                },
              ),
            ),
            actions: <Widget>[
   
            ],
          ),
          body: Container(),
        );
      }),
    );
  }
```
```
[  +30 ms] W/IInputConnectionWrapper(24634): getExtractedText on inactive InputConnection
[   +1 ms] W/IInputConnectionWrapper(24634): getTextBeforeCursor on inactive InputConnection
[  +34 ms] W/IInputConnectionWrapper(24634): getExtractedText on inactive InputConnection
[  +27 ms] W/IInputConnectionWrapper(24634): getTextBeforeCursor on inactive InputConnection
[  +31 ms] W/IInputConnectionWrapper(24634): getExtractedText on inactive InputConnection
[  +55 ms] W/IInputConnectionWrapper(24634): getTextBeforeCursor on inactive InputConnection
[ +121 ms] E/SpannableStringBuilder(24634): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
[   +7 ms] E/SpannableStringBuilder(24634): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
[  +20 ms] E/SpannableStringBuilder(24634): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
[   +1 ms] E/SpannableStringBuilder(24634): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
[+8628 ms] E/SpannableStringBuilder(24634): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
[ +112 ms] E/SpannableStringBuilder(24634): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
```

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 10.0.18362.778], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.44.2)
[√] Connected device (1 available)

• No issues found!
```

**Comment by TahaTesser** [comment]
duplicate of [#9471](https://github.com/flutter/flutter/issues/9471)

**Comment by HansMuller** [comment]
@TahaTesser - in this case the developer is't just concerned about the warning messages. The stated problem was:

**Comment by TahaTesser** [comment]
Hi @Aljabri-Salman 
So sorry, i missed your typing line

Here i reproduced your issue 

### Urdu (RTL) when tying space
```
I/flutter (27577): 0
I/flutter (27577): 1
I/flutter (27577): 2
I/flutter (27577): 3
I/flutter (27577): 5
```

### English (LTR) when tying space
```
I/flutter (27577): 1
I/flutter (27577): 2
I/flutter (27577): 3
I/flutter (27577): 4
I/flutter (27577): 5
```

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  TextEditingController _searchController = TextEditingController();

  @override
  void dispose() {
    _searchController.dispose();
    super.dispose();
  }

  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Form(
          key: _formKey,
          child: TextField(
            enableSuggestions: false,
            controller: _searchController,
            decoration: InputDecoration(
                border: InputBorder.none,
                hintText: 'أدخل للبحث',
                hintStyle: TextStyle(color: Colors.white)),
            onChanged: (String value) {
              print(value.length);
              // searchProv.fetchResults(newSearch: true, query: value);
            },
          ),
        ),
        actions: <Widget>[],
      ),
      body: Container(),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel master, 1.19.0-2.0.pre.214, on Mac OS X 10.15.5 19F96, locale en-GB)
    • Flutter version 1.19.0-2.0.pre.214 at /Users/tahatesser/Code/flutter_master
    • Framework revision 1d395c5e18 (24 hours ago), 2020-05-31 07:41:50 -0700
    • Engine revision 923687f0e7
    • Dart version 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.5 19F96
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
``` 

</details> 

Thank you! @HansMuller

**Comment by Aljabri-Salman** [comment]
@TahaTesser  Thanks for the reply. I just test it without it the localization and it works fine. It seems the issue appear when I type English while the localization is Arabic (rtl) which my app is currently using.
```
I/flutter (21913): 0
I/flutter (21913): o
I/flutter (21913): 1
I/flutter (21913): on
I/flutter (21913): 2
I/flutter (21913): one
I/flutter (21913): 3
I/flutter (21913): one ‎
I/flutter (21913): 5
E/SpannableStringBuilder(21913): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(21913): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
I/flutter (21913): one ‎p
I/flutter (21913): 6
```
<details>
<summary>Code with localization</summary>
  
```
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: [
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
          ],
          supportedLocales: [
            Locale('ar', 'AE'),
            Locale('en', 'EN'),
          ],
          locale: Locale('ar', 'AE'),
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  TextEditingController _searchController = TextEditingController();

  @override
  void dispose() {
    _searchController.dispose();
    super.dispose();
  }

  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Form(
          key: _formKey,
          child: TextField(
            enableSuggestions: false,
            controller: _searchController,
            decoration: InputDecoration(
                border: InputBorder.none,
                hintText: 'أدخل للبحث',
                hintStyle: TextStyle(color: Colors.white)),
            onChanged: (String value) {
              print(value);
              print(value.length);
              // searchProv.fetchResults(newSearch: true, query: value);
            },
          ),
        ),
        actions: <Widget>[],
      ),
      body: Container(),
    );
  }
}
```
</details>



<details>
<summary>flutter doctor -v</summary>

```

[√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [Version 10.0.18362.836], locale en-US)
    • Flutter version 1.17.2 at C:\Users\sajj7\flutter
    • Framework revision 5f21edf8b6 (4 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\sajj7\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\sajj7\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.2

[√] Connected device (1 available)
    • INE LX2 • JUC7N18717002322 • android-arm64 • Android 9 (API 28)

• No issues found!
```
</details>

<details>
<summary> pubspec.yaml</summary>

```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
```
</details>

**Comment by justinmc** [comment]
@Aljabri-Salman Can you still reproduce this on master?  I tried your code on a few different devices and couldn't get the error message:

iPhoneXS simulator iOS 14
```
flutter: a
flutter: 1
flutter: ab
flutter: 2
flutter: abc
flutter: 3
flutter: abc ‎
flutter: 5
flutter: abc ‎d
flutter: 6
```

Pixel 3a emulator API 30
```
I/flutter (14243): a
I/flutter (14243): 1
I/flutter (14243): ab
I/flutter (14243): 2
I/flutter (14243): abc
I/flutter (14243): 3
I/flutter (14243): abc ‎
I/flutter (14243): 5
I/flutter (14243): abc ‎d
I/flutter (14243): 6
```

Physical Pixel2XL on Android 10
```
I/flutter ( 7655): a
I/flutter ( 7655): 1
I/flutter ( 7655): ab
I/flutter ( 7655): 2
I/flutter ( 7655): abc
I/flutter ( 7655): 3
I/flutter ( 7655): abc ‎
I/flutter ( 7655): 5
I/flutter ( 7655): abc ‎d
I/flutter ( 7655): 6
```

**Comment by Aljabri-Salman** [comment]
@justinmc I haven't test it on master yet, though I will. However, the main problem is the regression for me and not the error message. as you can see once you type space after "abc" the number of characters jumped to 5 from 3. It should be 4.

**Comment by justinmc** [comment]
Ah got it!  I see that it's actually entering an [LRM](https://en.wikipedia.org/wiki/Left-to-right_mark#:~:text=use%20in%20HTML-,Unicode,Unicode%20Bidi%20(bidirectional)%20algorithm.) character in addition to a space.  That could be what was causing that error as well...

**Comment by justinmc** [comment]
@GaryQian It seems that, in an RTL input with LTR characters in it, we insert an LRM character when the user types a space.  Could you explain why we do that if you know?  Our code seems deliberate and consistent about that, but the behavior above with an invisible character with every space seems wrong.

https://github.com/flutter/flutter/blob/06d0cd514e40e7aadd6ef820c30ffc39db7db233/packages/flutter/lib/src/widgets/editable_text.dart#L2616

**Comment by GaryQian** [comment]
This was part of a change to move handling of trailing whitespace handling out of the text shaping library as performing it at the layout level resulted in ignoring unicode spec and doing totally off-spec behavior. This technique allows spaces to appear at the end instead of being truncated.

I recently landed changes to fix the inability to backspace, if you try it on master/dev, I believe the inability to backspace is resolved.

**Comment by Aljabri-Salman** [comment]
Just tested it on master. The issue is still appearing.
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.20.0-3.0.pre.77, on Microsoft Windows [Version 10.0.18362.900], locale en-US)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.4.0)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.46.1)
[√] Connected device (5 available)

• No issues found!
```
```
I/flutter (21302): a
I/flutter (21302): 1
I/flutter (21302): ab
I/flutter (21302): 2
I/flutter (21302): abc
I/flutter (21302): 3
E/SpannableStringBuilder(21302): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(21302): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
I/flutter (21302): abc ‎
I/flutter (21302): 5
I/flutter (21302): abc ‎d
I/flutter (21302): 6
```

This issue is causing so much problems for me. When users search in the TextField no results show due to the wrong number of characters (space).

**Comment by justinmc** [comment]
@Aljabri-Salman Are you still seeing the backspace bug as well?  It seems to work for me if I'm doing it right:

<img width="360" src="https://user-images.githubusercontent.com/389558/86652591-65615300-bf99-11ea-97fb-200366e3bc6a.gif" />

One option for searching is to programmatically remove the LRM character `0x200E` from the search query before submitting.  @GaryQian Is the intended behavior that users will have to remove LRM characters like this?

**Comment by Aljabri-Salman** [comment]
@justinmc the backspace seems to work fine in the master branch. but the extra character still. Could you tell me how to remove the LRM. How to remove using unicode?

**Comment by justinmc** [comment]
Here you go, let me know if this doesn't make sense: https://dartpad.dartlang.org/769702188834e465be686d044f0591eb

If this is all good otherwise and working as intended, maybe we can update the docs to make people aware that the LRM characters will show up when LTR text is input in an RTL field.

**Comment by Aljabri-Salman** [comment]
Thanks a lot, that solved my problem.

**Comment by justinmc** [comment]
Great!  This issue is WAI then.  I opened a quick PR to improve the docs around this to hopefully help other people with this problem. https://github.com/flutter/flutter/pull/61104

**Comment by muchirajunior** [comment]
this issue have not been resolved to me yet. any help
