### ISSUE TITLE
Unable to use local_auth 0.6.2

### ISSUE THREAD

**Issue by SuperBelette** [flutter/flutter#57678]
Hello!
I'm having some issues using **Local_Auth 6.0.2+2** on Android. 
In this version, it is requested to change the FlutterActivity to FlutterFragmentActivity, but when I make the change, I get errors when calling the methods of local_auth.

**Flutter version: 1.17.1**

**MainActivity.kt**:
```
import io.flutter.embedding.android.FlutterFragmentActivity

class MainActivity: FlutterFragmentActivity() {
}
```

**Main.dart**
```
import 'package:coupdepouce/modules/account/view.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:local_auth/local_auth.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Coup de pouce poc'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final LocalAuthentication auth = LocalAuthentication();

  Future<bool> checkEnabledBiometrics() async{
    bool canCheckBiometrics;
    try {
      canCheckBiometrics = await auth.canCheckBiometrics;
    } on PlatformException catch (e) {
      print(e);
    }

    return canCheckBiometrics;
  }

  Future<List<BiometricType>> getAvaibleBiometrics() async{
    List<BiometricType> availableBiometrics;
    try {
      availableBiometrics = await auth.getAvailableBiometrics();
    } on PlatformException catch (e) {
      print(e);
    }

    return availableBiometrics;
  }

  Future<void> checkBiometrics() async{
    bool canCheckBiometrics = await checkEnabledBiometrics();
    List<BiometricType> avaibleBiometrics = await getAvaibleBiometrics();

    showDialog(
      context: context,
      builder: (BuildContext context) {
        return AlertDialog(
          title: Text('Biometrics'),
          content: Text(
              'can check biometrics: $canCheckBiometrics \n'
              'avaible biometrics: $avaibleBiometrics'),
        );
      }
    );
  }

  Future<void> authenticate() async{
    bool authenticated;
    authenticated = await auth.authenticateWithBiometrics(
        localizedReason: 'Scan your fingerprint to authenticate',
        useErrorDialogs: true,
        stickyAuth: true);

    print(authenticated);
    Navigator.push(context, MaterialPageRoute(
      builder: (context) => AccountView(),
    ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            RaisedButton(
                color: Colors.blue,
                child: Text('chech avaible biometrics'),
                onPressed: (){
                  checkBiometrics();
                }),
            RaisedButton(
              color: Colors.blue,
              child: Text('log in with biometrics'),
                onPressed: (){
                authenticate();
            }),
          ],
        ),
      ),
    );
  }
}
```

and this is the error I get when I call 'auth.canCheckBiometrics':

```
E/flutter (11442): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getAvailableBiometrics on channel plugins.flutter.io/local_auth)
E/flutter (11442): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (11442): <asynchronous suspension>
E/flutter (11442): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (11442): #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:342:40)
E/flutter (11442): #3      LocalAuthentication.canCheckBiometrics (package:local_auth/local_auth.dart:115:23)
E/flutter (11442): #4      _MyHomePageState.checkEnabledBiometrics (package:coupdepouce/main.dart:39:39)
E/flutter (11442): #5      _MyHomePageState.checkBiometrics (package:coupdepouce/main.dart:59:37)
E/flutter (11442): #6      _MyHomePageState.build.<anonymous closure> (package:coupdepouce/main.dart:103:19)
E/flutter (11442): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
E/flutter (11442): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter (11442): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (11442): #10     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter (11442): #11     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter (11442): #12     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
E/flutter (11442): #13     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter (11442): #14     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (11442): #15     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (11442): #16     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (11442): #17     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (11442): #18     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (11442): #19     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (11442): #20     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (11442): #21     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (11442): #22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (11442): #23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (11442): #24     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter (11442): #25     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (11442): #26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (11442): #27     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter (11442): #28     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
```

previous version 0.4 of local_auth works without the need to change FlutterActivity, and I have no problem using this version.

**Flutter doctor**

```
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [version 10.0.16299.1806], locale fr-FR)
    • Flutter version 1.17.1 at C:\Applications\flutter
    • Framework revision f7a6a7906b (8 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\rkpz0338\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • SM G975F • R58M52RJ6ZT • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment]
Hi @SuperBelette 
Please add this to your `MainActivity.kt`
```
class MainActivity: FlutterFragmentActivity() {
    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine)
    }
}
```

Thank you

**Comment by nvmav** [comment]
@TahaTesser I am also facing same issue. But I have code in Java instead of Kotlin. 

I tried your suggestion.  But it seems there is no configureFlutterEngine() method to override.

I also looked into source code of FlutterFragmentActivity(using decompiled .class file in android studio). I don't see such method. 

![Screenshot](https://user-images.githubusercontent.com/6573890/82551182-5a836800-9b7d-11ea-931f-bbc1dde9703d.png)

The build.gradle file for local_auth contains dependencies in alpha versions. I also updated them to following stable version and performed gradle sync again. Still the issue exists.

```
dependencies {
    api "androidx.core:core:1.2.0"
    api "androidx.biometric:biometric:1.0.1"
    api "androidx.fragment:fragment:1.2.4"
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test:rules:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}
```

**Comment by Renatinaveen** [comment]
I'm having issues with on screen finger print. First thing there's no dialog showing up. If an unregistered fingerprint is used the scanner just disappear and the error will be auth_in_progress. But when it comes to ios and hardware fingerprints there's no issue.

**Comment by Renatinaveen** [comment]
This is my main activity 


import android.os.Bundle
import io.flutter.app.FlutterFragmentActivity
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterFragmentActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    GeneratedPluginRegistrant.registerWith(this)
  }
}

**Comment by nvmav** [comment]
@Renatinaveen post all your content in single comment. You can delete the 2nd comment and copy these changes by editing 1st comment. Also, please select code and format it by clicking **<>**

**Comment by nvmav** [comment]
@TahaTesser I am also facing same issue. But I have code in Java instead of Kotlin.
 
I tried your suggestion. But it seems there is no `configureFlutterEngine()` method to override. 
I also looked into source code of `FlutterFragmentActivity `(using decompiled .class file in android studio). I don't see such method. 

[screenshot.png](https://user-images.githubusercontent.com/6573890/82551182-5a836800-9b7d-11ea-931f-bbc1dde9703d.png) 

The `build.gradle` file for local_auth contains dependencies in alpha versions. I also updated them to following stable versions and performed gradle sync again. Still the issue exists. 

```
dependencies {
    api "androidx.core:core:1.2.0"
    api "androidx.biometric:biometric:1.0.1"
    api "androidx.fragment:fragment:1.2.4"
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test:rules:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}
```

**Comment by sespaces** [comment]
I too experience problems with the Java implementation for local_auth ^0.6.1

only the Kotlin version works for me

I tried many suggestions; the failure occurs even for the plugins/packages/local_auth/example example

will use Kotlin for now and can provide more information if needed

flutter --version
Flutter 1.19.0-2.0.pre.131 • channel master • https://github.com/flutter/flutter
Framework • revision 478d4c9c1a (3 days ago) • 2020-05-19 20:22:01 -0700
Engine • revision 2d4e83921d
Tools • Dart 2.9.0 (build 2.9.0-9.0.dev 40f7a11d89)

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.19.0-2.0.pre.131, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)
[✓] Connected device (2 available)

flutter devices
2 connected devices:

Pixel • FA6A10320178 • android-arm64 • Android 10 (API 29)
Linux • Linux        • linux-x64     • Linux

**Comment by SuperBelette** [comment]
> 
> Hi @SuperBelette
> Please add this to your `MainActivity.kt`
> 
> ```
> class MainActivity: FlutterFragmentActivity() {
>     override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
>         GeneratedPluginRegistrant.registerWith(flutterEngine)
>     }
> }
> ```
> 
> Thank you

Hi  @TahaTesser

I tried to update my activity, but when I build I end up with these errors:

```
'configureFlutterEngine' overrides nothing
Unresolved reference: FlutterEngine
Unresolved reference: GeneratedPluginRegistrant
```

**Comment by TahaTesser** [comment]
Hi @SuperBelette 
I wasn't able to reproduce this issue using official example 
Please make sure activity extends `FlutterFragmentActivity` 
Thank you

**Comment by jonsamwell** [comment]
I am seeing the same thing using a Java based project rather than a Kotlin one - is there a solution other than to convert to Kotlin?

**Comment by SuperBelette** [comment]
> 
> 
> Hi @SuperBelette
> I wasn't able to reproduce this issue on latest `stable` channel using official example
> 
> ```
> import io.flutter.embedding.android.FlutterActivity
> import io.flutter.embedding.android.FlutterFragmentActivity
> import io.flutter.embedding.engine.FlutterEngine
> import io.flutter.plugins.GeneratedPluginRegistrant
> 
> class MainActivity: FlutterFragmentActivity() {
>     override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
>         GeneratedPluginRegistrant.registerWith(flutterEngine)
>     }
> }
> ```

It's working, thank you! The problem was probably due to the imports, everything works fine with the ^0.6.2+3 version of local_auth

**Comment by ghenry** [comment]
On master (939b9a6f) if I do `flutter run` in `packages/local_auth/example` I get:

```
E/flutter (23389): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getAvailableBiometrics on channel plugins.flutter.io/local_auth)
E/flutter (23389): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (23389): <asynchronous suspension>
E/flutter (23389): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (23389): #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:342:40)
E/flutter (23389): #3      LocalAuthentication.canCheckBiometrics (package:local_auth/local_auth.dart:115:23)
E/flutter (23389): #4      _MyAppState._checkBiometrics (package:local_auth_example/main.dart:32:39)
E/flutter (23389): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
E/flutter (23389): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter (23389): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (23389): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter (23389): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter (23389): #10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
E/flutter (23389): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter (23389): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (23389): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (23389): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (23389): #15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (23389): #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (23389): #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (23389): #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (23389): #19     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (23389): #20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (23389): #21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (23389): #22     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter (23389): #23     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (23389): #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (23389): #25     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter (23389): #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
E/flutter (23389): 
```
flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.1, on Linux, locale en_GB.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)
```

**Comment by TahaTesser** [comment]
@ghenry Just tested on latest `master` channel, no issue
This exception indicate you don't have proper setup done, use the class i posted earlier, make sure to add `<uses-permission android:name="android.permission.USE_FINGERPRINT"/>` in your `manifest.xml`

```
E/flutter (23389): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getAvailableBiometrics on channel plugins.flutter.io/local_auth)
```

@SuperBelette 
Glad your issue is resolved, given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you"

**Comment by ghenry** [comment]
@TahaTesser I'm just running `flutter run` in the example, so this should work out of the box:

```
~/development/flutter_plugins/packages/local_auth/example [(HEAD detached at local_auth-v0.6.2+2)*]$ 

and it does!!! I was running on master not the latest tag. Apologies. Just noting here to confirm.

**Comment by campioncino** [comment]
> I am seeing the same thing using a Java based project rather than a Kotlin one - is there a solution other than to convert to Kotlin?
> 
> This happened right after following the steps (https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects) to upgrade a pre 1.12 project so I am guess there is something weird going on with the plugin system when using a `FlutterFragmentActivity` with a Java based project.

have you find a solution to use a java based project?

**Comment by jonsamwell** [comment]
@campioncino after following the steps to upgrade the pre 1.12 project I had to make the MainActivity.java look like this:

```
package com.domain.namespace;

import io.flutter.embedding.android.FlutterFragmentActivity;
import io.flutter.plugins.GeneratedPluginRegistrant;
import io.flutter.embedding.engine.FlutterEngine;

public class MainActivity extends FlutterFragmentActivity {
  @Override
  public void configureFlutterEngine(FlutterEngine flutterEngine) {
    GeneratedPluginRegistrant.registerWith(flutterEngine);
  }
}
```

Also ensuring that the below XML is in the AndroidManifest.xml
```
<meta-data
            android:name="flutterEmbedding"
            android:value="2" />
```

Also ensure that your namespaces all match for some reason the folder namespace and the namespace in the android manifest were slightly different.

I hope this helps

**Comment by campioncino** [comment]
@jonsamwell thanks a lot, but it didn't solve my problem.

I followed the guide to upgrade, and add the meta-data ...
Everythings works good on Android >27 and iOs, but there's no way to show fingerprint in android <28.

So, if I create a new project may this will be helpful?

I need the fingerprint authentication
