### ISSUE TITLE
Google Sign In 4.5.1 - ServerAuthCode returns null value

### ISSUE THREAD

**Issue by Faiyyaz** [flutter/flutter#57712]
The serverauthcode still coming null in the new version of plugin.

```
GoogleSignIn _googleSignIn = GoogleSignIn(
      scopes: [
        'email',
       'https://www.googleapis.com/auth/contacts.readonly',
       'https://mail.google.com',
      ],
    );
    try {
      GoogleSignInAccount googleSignInAccount = await _googleSignIn.signIn();
      GoogleSignInAuthentication googleSignInAuthentication =
          await googleSignInAccount.authentication;
      String code = googleSignInAuthentication.serverAuthCode;
      print(code);
    } catch (error) {
      print(error);
    }
```

Flutter doctor
```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.1 at /users/faiyyazkhatri/StudioProjects/flutter
    • Framework revision f7a6a7906b (8 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /users/faiyyazkhatri/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /users/faiyyazkhatri/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 690EC0B1-6D79-42BE-8447-4746C5E2FAAD • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!
```

**Comment by TahaTesser** [comment]
<details> 
<summary>Code Sample</summary> 

```
// Copyright 2019 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// ignore_for_file: public_member_api_docs

import 'dart:async';
import 'dart:convert' show json;

import "package:http/http.dart" as http;
import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';

GoogleSignIn _googleSignIn = GoogleSignIn(
  scopes: <String>[
    'email',
    'https://www.googleapis.com/auth/contacts.readonly',
  ],
);

void main() {
  runApp(
    MaterialApp(
      title: 'Google Sign In',
      home: SignInDemo(),
    ),
  );
}

class SignInDemo extends StatefulWidget {
  @override
  State createState() => SignInDemoState();
}

class SignInDemoState extends State<SignInDemo> {
  GoogleSignInAccount _currentUser;
  String _contactText;

  @override
  void initState() {
    super.initState();
    _googleSignIn.onCurrentUserChanged.listen((GoogleSignInAccount account) {
      setState(() {
        _currentUser = account;
      });
      if (_currentUser != null) {
        _handleGetContact();
      }
    });
    _googleSignIn.signInSilently();
  }

  Future<void> _handleGetContact() async {
    setState(() {
      _contactText = "Loading contact info...";
    });
    final http.Response response = await http.get(
      'https://people.googleapis.com/v1/people/me/connections'
      '?requestMask.includeField=person.names',
      headers: await _currentUser.authHeaders,
    );
    if (response.statusCode != 200) {
      setState(() {
        _contactText = "People API gave a ${response.statusCode} "
            "response. Check logs for details.";
      });
      print('People API ${response.statusCode} response: ${response.body}');
      return;
    }
    final Map<String, dynamic> data = json.decode(response.body);
    final String namedContact = _pickFirstNamedContact(data);
    setState(() {
      if (namedContact != null) {
        _contactText = "I see you know $namedContact!";
      } else {
        _contactText = "No contacts to display.";
      }
    });
  }

  String _pickFirstNamedContact(Map<String, dynamic> data) {
    final List<dynamic> connections = data['connections'];
    final Map<String, dynamic> contact = connections?.firstWhere(
      (dynamic contact) => contact['names'] != null,
      orElse: () => null,
    );
    if (contact != null) {
      final Map<String, dynamic> name = contact['names'].firstWhere(
        (dynamic name) => name['displayName'] != null,
        orElse: () => null,
      );
      if (name != null) {
        return name['displayName'];
      }
    }
    return null;
  }

  Future<void> _handleSignIn() async {
    try {
      GoogleSignInAccount googleSignInAccount = await _googleSignIn.signIn();
      GoogleSignInAuthentication googleSignInAuthentication =
          await googleSignInAccount.authentication;
      String code = googleSignInAuthentication.serverAuthCode;
      print('serverAuthCode: $code');
    } catch (error) {
      print(error);
    }
  }

  Future<void> _handleSignOut() => _googleSignIn.disconnect();

  Widget _buildBody() {
    if (_currentUser != null) {
      return Column(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: <Widget>[
          ListTile(
            leading: GoogleUserCircleAvatar(
              identity: _currentUser,
            ),
            title: Text(_currentUser.displayName ?? ''),
            subtitle: Text(_currentUser.email ?? ''),
          ),
          const Text("Signed in successfully."),
          Text(_contactText ?? ''),
          RaisedButton(
            child: const Text('SIGN OUT'),
            onPressed: _handleSignOut,
          ),
          RaisedButton(
            child: const Text('REFRESH'),
            onPressed: _handleGetContact,
          ),
        ],
      );
    } else {
      return Column(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: <Widget>[
          const Text("You are not currently signed in."),
          RaisedButton(
            child: const Text('SIGN IN'),
            onPressed: _handleSignIn,
          ),
        ],
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Google Sign In'),
        ),
        body: ConstrainedBox(
          constraints: const BoxConstraints.expand(),
          child: _buildBody(),
        ));
  }
}
 
``` 

</details> 

```
I/flutter (10569): serverAuthCode: null
```

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.19.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 456d80b9dd (10 days ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (7 available)
    • SM M305F                  • 32003c30dc19668f                     •
      android-arm64  • Android 10 (API 29)
    • Android SDK built for x86 • emulator-5554                        •
      android-x86    • Android 10 (API 29) (emulator)
    • Taha’s iPhone             • 00008020-001059882212002E            • ios
      • iOS 13.5
    • iPhone 11                 • F067D2F5-5386-4EBE-8600-326B40C64462 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS                     • macOS                                •
      darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server                • web-server                           •
      web-javascript • Flutter Tools
    • Chrome                    • chrome                               •
      web-javascript • Google Chrome 81.0.4044.138

• No issues found!
``` 

</details>

**Comment by zeeshanhussain** [comment]
@Faiyyaz you can pull these changes,it works for me now. [https://github.com/flutter/plugins/pull/2792](url)

**Comment by Faiyyaz** [comment]
@zeeshanhussain i don't want to pull any outside commit bcoz even i have one of my commit and a commit of another user with me which works but i want to use official plugin bcoz if they make any updation in future then we need to implement in our commit as well so its better to wait and get this issue solved in official repo itself.

**Comment by scaraux** [comment]
@zeeshanhussain I pulled your code but still get null for `serverAuthCode` am I missing something ? Testing on iOS simulator.

**Comment by zeeshanhussain** [comment]
@scaraux my changes were only for android, you can pull this for iOs https://github.com/flutter/plugins/pull/2788

**Comment by ditman** [comment]
As you can see here:
https://github.com/flutter/plugins/blob/master/packages/google_sign_in/google_sign_in_web/lib/google_sign_in_web.dart#L135-L146

Web has never had this feature (although it seems it may be implemented, if you can request offline access after authenticating).

I'm reviving #62474 to track progress of the web implementation, if anybody wants to tackle it ASAP. I'll assign the "new feature" label as well.

**Comment by DreamCatcher-SM** [comment]
Is there any work around for getting serverAuthCode on android/iOS??
let's just say my future depends on it 😅.
Thanks for all your efforts you are doing a great job 👌🏻

**Comment by zeeshanhussain** [comment]
> Is there any work around for getting serverAuthCode on android/iOS??
> let's just say my future depends on it .
> Thanks for all your efforts you are doing a great job 👌🏻

You can pick these pull requests 
https://github.com/flutter/plugins/pull/2788
https://github.com/flutter/plugins/pull/2792

**Comment by aseef17** [comment]
> Is there any work around for getting serverAuthCode on android/iOS??
> let's just say my future depends on it 😅.
> Thanks for all your efforts you are doing a great job 👌🏻

I merged the changes from the 2 PRs into one so that it's easier to use. 

You can just add google_sign_in your project like
(in your pubspec.yaml file)

```
  google_sign_in:
    git:
      url: https://github.com/aseef17/plugins.git
      path: packages/google_sign_in/google_sign_in
      ref: master
```

And add a dependacy override for google_sign_in_platform_interface

```
dependency_overrides:
  google_sign_in_platform_interface:
    git:
      url: https://github.com/aseef17/plugins.git
      path: packages/google_sign_in/google_sign_in_platform_interface
```

To get this to work in for iOS, you have to add a new key in your GoogleService-Info.plist file

```
<key>SERVER_CLIENT_ID</key>
<string>YOUR_CLIENT_ID_HERE</string>
```

You can find it in your firebase project settings or you can just check your google-services.json file 
It'll be under "oauth_client" object with the name "client_id"

This has been tested on both Android and iOS to obtain the **serverAuthCode**. 

Hope this helps until the current PRs are merged

_NOTE:- This is a current fork of the plugins in their current state and I have no intention to update them with the newer updates from the Flutter Team_

**Comment by trieuvusetacinq** [comment]
[google_sign_in 4.5.6] I still get serverAuthCode as null.

**Comment by DreamCatcher-SM** [comment]
> 
> 
> [google_sign_in 4.5.6] I still get serverAuthCode as null.

use the solution provided by : @aseef17 


> 
> 
> > Is there any work around for getting serverAuthCode on android/iOS??
> > let's just say my future depends on it 😅.
> > Thanks for all your efforts you are doing a great job 👌🏻
> 
> I merged the changes from the 2 PRs into one so that it's easier to use.
> 
> You can just add google_sign_in your project like
> (in your pubspec.yaml file)
> 
> ```
>   google_sign_in:
>     git:
>       url: https://github.com/aseef17/plugins.git
>       path: packages/google_sign_in/google_sign_in
>       ref: master
> ```
> 
> And add a dependacy override for google_sign_in_platform_interface
> 
> ```
> dependency_overrides:
>   google_sign_in_platform_interface:
>     git:
>       url: https://github.com/aseef17/plugins.git
>       path: packages/google_sign_in/google_sign_in_platform_interface
> ```
> 
> To get this to work in for iOS, you have to add a new key in your GoogleService-Info.plist file
> 
> ```
> <key>SERVER_CLIENT_ID</key>
> <string>YOUR_CLIENT_ID_HERE</string>
> ```
> 
> You can find it in your firebase project settings or you can just check your google-services.json file
> It'll be under "oauth_client" object with the name "client_id"
> 
> This has been tested on both Android and iOS to obtain the **serverAuthCode**.
> 
> Hope this helps until the current PRs are merged
> 
> _NOTE:- This is a current fork of the plugins in their current state and I have no intention to update them with the newer updates from the Flutter Team_

**Comment by scaraux** [comment]
@darshankawar is there anything you can do on your end? PRs have been sitting for months, ready to be merge. Google Sign in is a standard and so is the server auth code.

**Comment by t-kozak** [comment]
It is possible to fix this problem without the need to change the implementation of the google_sign_in Flutter plugin, at least on Android.

If you check the sources of the Android implementation, specifically: [GoogleSignInPlugin.java#L488](https://github.com/flutter/plugins/blob/master/packages/google_sign_in/google_sign_in/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java#L488), you can see that the plugin will populate both the `serverAuthCode` and `idToken` properties from the `GoogleSignInAccount` result. 

Then, check the documentation of [GoogleSignInAccount#getServerAuthCode()](https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInAccount#getServerAuthCode()) - the value will be set only if it's being requested when building sign in options: (GoogleSignInOptions.Builder.requestServerAuthCode(String))[https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInOptions.Builder#requestServerAuthCode(java.lang.String)].

Now, going back to the plugin sources, you can see that the plugin will request these ids, if the `clientId` property is defined in resources: [GoogleSignInPlugin.java#L333](https://github.com/flutter/plugins/blob/master/packages/google_sign_in/google_sign_in/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java#L333)

So, ultimately to have these props being non-null on Android, you simply have to add a resource file in the $PROJECT_ROOT/android/app/src/res/values/strings.xml with content:

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="default_web_client_id">XXX</string>
</resources>
```
Where XXX is client id from appropriate OAuth 2.0 Client IDs from here: [https://console.cloud.google.com/apis/credentials](https://console.cloud.google.com/apis/credentials).

I didn't need this on iOS, so really don't know how to fix it there.

**Comment by stadia** [comment]
@t-kozak i didn't work. only  did work by changing the impl.

**Comment by Noufalsubair** [comment]
[google_sign_in 4.5.9] I still get serverAuthCode as null in both android & ios

**Comment by ManasviPatidar** [comment]
> > Is there any work around for getting serverAuthCode on android/iOS??
> > let's just say my future depends on it sweat_smile.
> > Thanks for all your efforts you are doing a great job 👌🏻
> 
> I merged the changes from the 2 PRs into one so that it's easier to use.
> 
> You can just add google_sign_in your project like
> (in your pubspec.yaml file)
> 
> ```
>   google_sign_in:
>     git:
>       url: https://github.com/aseef17/plugins.git
>       path: packages/google_sign_in/google_sign_in
>       ref: master
> ```
> 
> And add a dependacy override for google_sign_in_platform_interface
> 
> ```
> dependency_overrides:
>   google_sign_in_platform_interface:
>     git:
>       url: https://github.com/aseef17/plugins.git
>       path: packages/google_sign_in/google_sign_in_platform_interface
> ```
> 
> To get this to work in for iOS, you have to add a new key in your GoogleService-Info.plist file
> 
> ```
> <key>SERVER_CLIENT_ID</key>
> <string>YOUR_CLIENT_ID_HERE</string>
> ```
> 
> You can find it in your firebase project settings or you can just check your google-services.json file
> It'll be under "oauth_client" object with the name "client_id"
> 
> This has been tested on both Android and iOS to obtain the **serverAuthCode**.
> 
> Hope this helps until the current PRs are merged
> 
> _NOTE:- This is a current fork of the plugins in their current state and I have no intention to update them with the newer updates from the Flutter Team_

This solution works :+1: , but now i wish to migrate my app to null safety and since this fork depends on non null safe versions of packages I am facing issues with dependency resolution. @aseef17 is it possible for you to update the fork just this one time as null safety is a very big feature, or do you suggest any other method?

**Comment by aseef17** [comment]
> This solution works 👍 , but now i wish to migrate my app to null safety and since this fork depends on non null safe versions of packages I am facing issues with dependency resolution. @aseef17 is it possible for you to update the fork just this one time as null safety is a very big feature, or do you suggest any other method?

@ManasviPatidar 
May I know what are issues you are facing. I recently did an update to null safety for one of my client projects and was able to resolve this without the need of updating the package?

**Comment by ManasviPatidar** [comment]
Running "flutter pub get" in my_app...                      
Because every version of google_sign_in_platform_interface from git depends on quiver ^2.0.0 and camera >=0.8.0 depends on quiver ^3.0.0, google_sign_in_platform_interface from git is incompatible with camera >=0.8.0.
So, because prescription_app depends on both camera ^0.8.1 and google_sign_in_platform_interface from git, version solving failed.

**Comment by Aqua-Ye** [comment]
I have the same issue regarding quiver dependency:

```
Because every version of google_sign_in_platform_interface from git depends on quiver ^2.0.0 and every version of dio_http_cache from git depends on quiver ^3.0.0, google_sign_in_platform_interface from git is incompatible with dio_http_cache from git.
```

**Comment by OhTerryTorres** [comment]
@aseef17's workaround has done well for a while, but version solving has become an issue as we've updated other dependencies in our project. Integrating GoogleSignInPlatform has not helped either, as getTokens also returns a null serverAuthCode.

**Comment by aseef17** [comment]
I'll try to update the dependencies by this weekend. I still don't understand why the Flutter team has not integrated this yet though.

**Comment by OhTerryTorres** [comment]
@aseef17 Obviously I didn't expect you to have to do that kind of work, but of course I appreciate it.

**Comment by Julcarl** [comment]
> > Is there any work around for getting serverAuthCode on android/iOS??
> > let's just say my future depends on it 😅.
> > Thanks for all your efforts you are doing a great job 👌🏻
> 
> I merged the changes from the 2 PRs into one so that it's easier to use.
> 
> You can just add google_sign_in your project like
> (in your pubspec.yaml file)
> 
> ```
>   google_sign_in:
>     git:
>       url: https://github.com/aseef17/plugins.git
>       path: packages/google_sign_in/google_sign_in
>       ref: master
> ```
> 
> And add a dependacy override for google_sign_in_platform_interface
> 
> ```
> dependency_overrides:
>   google_sign_in_platform_interface:
>     git:
>       url: https://github.com/aseef17/plugins.git
>       path: packages/google_sign_in/google_sign_in_platform_interface
> ```
> 
> To get this to work in for iOS, you have to add a new key in your GoogleService-Info.plist file
> 
> ```
> <key>SERVER_CLIENT_ID</key>
> <string>YOUR_CLIENT_ID_HERE</string>
> ```
> 
> You can find it in your firebase project settings or you can just check your google-services.json file
> It'll be under "oauth_client" object with the name "client_id"
> 
> This has been tested on both Android and iOS to obtain the **serverAuthCode**.
> 
> Hope this helps until the current PRs are merged
> 
> _NOTE:- This is a current fork of the plugins in their current state and I have no intention to update them with the newer updates from the Flutter Team_

This solution works for me in mobile device however in web I still got null value

**Comment by vlidholt** [comment]
It would be great to get this issue fixed as it is a blocker for anyone who wants to do server-side authentication for Google sign-in.

I did a null-safe version that is working for me. Just add the git dependency:

    google_sign_in:
        git:
          url: https://github.com/serverpod/plugins.git
          path: packages/google_sign_in/google_sign_in
          ref: serverpod

It's possible you also need to add to your GoogleService-Info.plist (didn't try without):

    <key>SERVER_CLIENT_ID</key>
    <string>YOUR_CLIENT_ID_HERE</string>

You can find it in your firebase project settings or you can just check your google-services.json file
It'll be the object with the name "client_id".

**Comment by OhTerryTorres** [comment]
> google_sign_in:
>     git:
>       url: https://github.com/serverpod/plugins.git
>       path: packages/google_sign_in/google_sign_in
>       ref: serverpod

I can confirm this works without GoogleService-Info.plist for those who aren't using Firebase.

It's pretty astonished this issue, which essentially makes server side authentication impossible, has gone unaddressed over almost a dozen new versions.

**Comment by sailes-shakya** [comment]
> > Is there any work around for getting serverAuthCode on android/iOS??
> > let's just say my future depends on it 😅.
> > Thanks for all your efforts you are doing a great job 👌🏻
> 
> I merged the changes from the 2 PRs into one so that it's easier to use.
> 
> You can just add google_sign_in your project like
> (in your pubspec.yaml file)
> 
> ```
>   google_sign_in:
>     git:
>       url: https://github.com/aseef17/plugins.git
>       path: packages/google_sign_in/google_sign_in
>       ref: master
> ```
> 
> And add a dependacy override for google_sign_in_platform_interface
> 
> ```
> dependency_overrides:
>   google_sign_in_platform_interface:
>     git:
>       url: https://github.com/aseef17/plugins.git
>       path: packages/google_sign_in/google_sign_in_platform_interface
> ```
> 
> To get this to work in for iOS, you have to add a new key in your GoogleService-Info.plist file
> 
> ```
> <key>SERVER_CLIENT_ID</key>
> <string>YOUR_CLIENT_ID_HERE</string>
> ```
> 
> You can find it in your firebase project settings or you can just check your google-services.json file
> It'll be under "oauth_client" object with the name "client_id"
> 
> This has been tested on both Android and iOS to obtain the **serverAuthCode**.
> 
> Hope this helps until the current PRs are merged
> 
> _NOTE:- This is a current fork of the plugins in their current state and I have no intention to update them with the newer updates from the Flutter Team_



> > [google_sign_in 4.5.6] I still get serverAuthCode as null.
> 
> use the solution provided by : @aseef17
> 
> > > Is there any work around for getting serverAuthCode on android/iOS??
> > > let's just say my future depends on it 😅.
> > > Thanks for all your efforts you are doing a great job 👌🏻
> > 
> > 
> > I merged the changes from the 2 PRs into one so that it's easier to use.
> > You can just add google_sign_in your project like
> > (in your pubspec.yaml file)
> > ```
> >   google_sign_in:
> >     git:
> >       url: https://github.com/aseef17/plugins.git
> >       path: packages/google_sign_in/google_sign_in
> >       ref: master
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And add a dependacy override for google_sign_in_platform_interface
> > ```
> > dependency_overrides:
> >   google_sign_in_platform_interface:
> >     git:
> >       url: https://github.com/aseef17/plugins.git
> >       path: packages/google_sign_in/google_sign_in_platform_interface
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > To get this to work in for iOS, you have to add a new key in your GoogleService-Info.plist file
> > ```
> > <key>SERVER_CLIENT_ID</key>
> > <string>YOUR_CLIENT_ID_HERE</string>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can find it in your firebase project settings or you can just check your google-services.json file
> > It'll be under "oauth_client" object with the name "client_id"
> > This has been tested on both Android and iOS to obtain the **serverAuthCode**.
> > Hope this helps until the current PRs are merged

i implement this,,still my  serverauthcode is comming null.

**Comment by f-person** [comment]
@OhTerryTorres your proposed solution doesn't work on Android. Do you have any ideas why?

**Comment by f-person** [comment]
> @OhTerryTorres your proposed solution doesn't work on Android (but works on iOS). Do you have any ideas why?

I got it working on Android but the server throws `Error fetching OAuth2 access token, message: 'unauthorized_client: Unauthorized'`

**Comment by mikeyyyzhao** [comment]
I tried @vlidholt 's branch but after I hit login, the simulator would always crash. However, when I ran the same code but with the default google_sign_in library (5.0.7), I got null as the response when trying to get the serverAuthCode. Does any know why the simulator would crash?

**Comment by vanfresh** [comment]
Its been over a year, why isn't this fixed?  However is everyone else getting the refresh token without the server auth code?

**Comment by vanfresh** [comment]
For those looking to implement this, these are the steps I took: 

**Part 1: Fork repo**
1. Fork flutter/plugin (https://github.com/flutter/plugins.git)
2. Add a second remote repo from Aseef17 (https://github.com/aseef17/plugins.git)
3. Merge second remote repo into master
4. Add dependency override for `google_sign_in_platform_interface` in the pubspec.yaml 
```
dependency_overrides:
  google_sign_in_platform_interface:
    git:
      url: https://github.com/aseef17/plugins.git
      path: packages/google_sign_in/google_sign_in_platform_interface
```
5. Push to origin

**Part 2: Create Client ID**
1. Go to Google OAuth Console
2. Create a new Client ID for **Web Applications**
3. Save the Client ID and Client Secret 

**Part 3a: Setup Android**
1. Add the new Client ID to string.xml
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="default_web_client_id">XXX</string>
</resources>
```
2. If you have Firebase, update new google-services.json which now has the new Client ID (optional) 

**Part 3b: Setup iOS**
1. **Manually** add the new Client ID to `GoogleService-Info.plist`
```
<key>SERVER_CLIENT_ID</key>
<string>YOUR_CLIENT_ID_HERE</string>
```

**Part 4: Override dependencies**
1. Override `google_sign_in` and `google_sign_in_platform_interface` in your project with your fork repo
```dependency_overrides:
  google_sign_in:
    git:
      url: https://github.com/your_repo/plugins.git
      path: packages/google_sign_in/google_sign_in
      ref: branch or specific_commit
  google_sign_in_platform_interface:
    git:
      url: https://github.com/your_repo/plugins.git
      path: packages/google_sign_in/google_sign_in_platform_interface
      ref: branch or specific_commit```

**Comment by vanfresh** [comment]
I am getting 

```
Error 400: invalid_request 
Custom scheme URIs are not allowed for 'WEB' client type
```
I am using SERVER_CLIENT_ID. 

Do @zeeshanhussain @aseef17 know how to resolve this?

**Comment by nikita-filimonau** [comment]
@vanfresh Hi,  could you please help me little bit.
After all suggested changes I have started to catch the error:
`flutter: PlatformException(google_sign_in, Your app is missing support for the following URL schemes: {MY_WEB_CLIENT_ID_REVERSED}, NSInvalidArgumentException, null)`
`Lost connection to device.`

**Comment by JeromeGsq** [comment]
> It would be great to get this issue fixed as it is a blocker for anyone who wants to do server-side authentication for Google sign-in.
> 
> I did a null-safe version that is working for me. Just add the git dependency:
> 
> ```
> google_sign_in:
>     git:
>       url: https://github.com/serverpod/plugins.git
>       path: packages/google_sign_in/google_sign_in
>       ref: serverpod
> ```
> 
> It's possible you also need to add to your GoogleService-Info.plist (didn't try without):
> 
> ```
> <key>SERVER_CLIENT_ID</key>
> <string>YOUR_CLIENT_ID_HERE</string>
> ```
> 
> You can find it in your firebase project settings or you can just check your google-services.json file It'll be the object with the name "client_id".

Thanks for your work, it works fine on Android and iOS. On the other hand, I cannot launch the application on the iOS simulator because of an error. You know why? 

```

building for iOS Simulator, but linking in object file built for iOS, file '/ios/Pods/GoogleSignIn/Frameworks/GoogleSignIn.framework/GoogleSignIn' for architecture arm64

```

**Comment by stuartmorgan** [comment]
Closing as fixed by https://github.com/flutter/plugins/pull/4180
