### ISSUE TITLE
PlatformException when trying to create flutter webview.

### ISSUE THREAD

**Issue by micrcx** [flutter/flutter#59951]
An error occurs when trying to create a **FlutterFragment** from a native android application:

_MainActivity.java:_
```
   private void prepareButton(MainActivity context) {
        final String link = "http://flutter.dev";

        mInvokeFlutterView = findViewById(R.id.invoke_flutter_view);
        mInvokeFlutterView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                prepareEngine(link);
            }
        });
    }

    private void prepareEngine(String link) {
        FragmentManager fragmentManager = getSupportFragmentManager();
        if (fragmentManager != null) {
           flutterFragment = (FlutterFragment) fragmentManager
                    .findFragmentByTag(TAG_FLUTTER_FRAGMENT);
            if (flutterFragment == null) {
                flutterFragment = FlutterFragment.withNewEngine()
                        .initialRoute(link)Trace log:Trace log:
                        .build();
                fragmentManager
                        .beginTransaction()
                        .replace(
                                R.id.flutter_view,
                                flutterFragment,
                                TAG_FLUTTER_FRAGMENT
                        )
                        .commit();
            }
        }
    }
```
_main.dart:_
```
import 'dart:ui';
import 'package:flutter/material.dart';
import 'web_view_container.dart';

void main() {
  print ("main()->${window.defaultRouteName}");
  runApp(chooseWidget(window.defaultRouteName));
}

Widget chooseWidget(String url) {
  return FlutterActivityWrapper(url);
}

class FlutterActivityWrapper extends StatefulWidget {
  String _link;
  FlutterActivityWrapper(this._link);

  @override
  createState() => _FlutterActivityWrapperState();

}

class _FlutterActivityWrapperState extends State<FlutterActivityWrapper> {
  @override
  void initState() {
    print('_FlutterActivityWrapperState.initState');
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: WebViewContainer(widget._link /*widget.__link*/),
    );
  }
}
```
_web_view_container.dart:_
```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'dart:async';

class WebViewContainer extends StatefulWidget {
  final  url;

  WebViewContainer(this.url){
    print ('WebViewContainer->$url');
  }

  @override
  createState() => _WebViewContainerState(this.url);
}

class _WebViewContainerState extends State<WebViewContainer> {
  var _url;
  bool _progress = false;
  final _key = UniqueKey();
  _WebViewContainerState(this._url);
  WebViewController _controller;webview_flutter: ^ 0.3.22 + 1
  bool _enableJS = true; //true;

  final Completer<WebViewController> _controllerCompleter =
        Completer<WebViewController>();

  @override
  void initState() {
    print('_WebViewContainerState.initState');
    super.initState();
  }

  Future<void> _onWillPop(BuildContext context) async {
    print("onwillpop");
    if (await _controller.canGoBack()) {
      _controller.goBack();
    } else {
      setState(() {
        _enableJS = false;
      });

      SystemChannels.platform.invokeMethod<void>('SystemNavigator.pop');

      return Future.value(false);
    }
  }

  @override
  Widget build(BuildContext context) {
    print ("_WebViewContainerState.build->$_url");
    return
      WillPopScope(
        onWillPop: () => _onWillPop(context),
      child:
      Scaffold(
       appBar:

      AppBar(
        titleSpacing: 0.0,
        title: Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                  IconButton(
                    icon: Icon(Icons.keyboard_backspace),
                    onPressed: () {
                      _onWillPop(context);
                    }
                  ),
                  Text ("FLUTTER WEB VIEW"),
                ]
              ),
        ),

        body: Column(
          children: [
            Center(
              child:
              _progress ?
              new SizedBox(
                height: 64.0,
                width: 64.0,
                child: new CircularProgressIndicator(
                  value: null,
                  strokeWidth: 8.0,
                ),
              )
              :
              SizedBox.shrink()
            ),
            Expanded(
                child: WebView(
                  key: _key, javascriptMode: _enableJS ? JavascriptMode.unrestricted : JavascriptMode.disabled, initialUrl: _url,
                    onWebViewCreated: _onWebViewCreated, onPageFinished: _onPageFinished, )
            )
          ],
        ),
        ));
  }

  void _onWebViewCreated(WebViewController controller) {
    print("------- OnWebViewCreated -------");
    _controllerCompleter.future.then((value) => _controller = value);
    _controllerCompleter.complete(controller);
    setState(() {
      _progress = true;
    });
  }

  void _onPageFinished(String url) {
    print("------- _onPageFinished -------");
    setState(() {
      _progress = false;
    });
  }
}
```
Used by **webview_flutter: ^ 0.3.22 + 1**

_Trace log:_
```
I/flutter: main()->http://flutter.dev
I/flutter: _FlutterActivityWrapperState.initState
I/flutter: WebViewContainer->http://flutter.dev
I/flutter: _WebViewContainerState.initState
I/flutter: _WebViewContainerState.build->http://flutter.dev
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: plugins.flutter.io/webview
        at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:97)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:95)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:170)
        at android.app.ActivityThread.main(ActivityThread.java:6991)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
    , null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
    <asynchronous suspension>
    #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
    #3      AndroidViewController._create (package:flutter/src/services/platform_views.dart:633:54)
    #4      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:550:14)
    #5      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:175:29)
    #6      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:156:5)
    #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1746:9)
    #8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
    #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
    #10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
    #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
    #12     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:808:17)
    #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
    #14     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:11)
    #15     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:484:7)
    #16     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
    #17     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:399:14)
    #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
    #19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
    #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
    #21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
    #22     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1248:11)
    #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
    #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
    #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
    #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
    #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
    #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
    #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
    #30     RenderProxyBoxMixin.performLayout (packa
```
_Flutter doctor:_
```
	micrcx@micrcx-desktop:~/AndroidStudioProjects/TestFlutterView/web_viewer$ ./../../../flutter/bin/flutter doctor -v
[✓] Flutter (Channel stable, v1.17.3, on Linux, locale en_IL)
    • Flutter version 1.17.3 at /home/micrcx/flutter
    • Framework revision b041144f83 (2 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/micrcx/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/micrcx/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/micrcx/android-studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • LG H870 • LGH870f90ccfe • android-arm64 • Android 9 (API 28)

• No issues found!
```
**PS.The detected error maybe is close to the bug https://github.com/flutter/flutter/issues/25714, but appears in a different context.**
PPS. The most interesting thing is that the same code when using **FlutterActivity** is executed without problems.

**Comment by TahaTesser** [comment]
Hi @micrcx 
i can reproduce this issue

<details> 
<summary>logs</summary> 

``` 

06/22 20:13:34: Launching 'app' on samsung SM-M305F.
$ adb shell am start -n "com.nevercode.triage/com.nevercode.triage.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 26397 on device 'samsung-sm_m305f-32003c30dc19668f'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/ResourceExtractor: Found extracted resources res_timestamp-1-1592836941616
I/MultiWindowDecorSupport: updateCaptionType >> DecorView@1d33146[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
D/MultiWindowDecorSupport: setCaptionType = 0, DecorView = DecorView@1d33146[]
I/flutter: Observatory listening on http://127.0.0.1:43330/wyk3EVNL_aE=/
W/evercode.triag: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/evercode.triag: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
D/ViewRootImpl@7223919[MainActivity]: setView = com.android.internal.policy.DecorView@1d33146 TM=true MM=false
D/ViewRootImpl@7223919[MainActivity]: stopped(false) old=false
D/ViewRootImpl@7223919[MainActivity]: Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)0 dur=16 res=0x40007 s={true 532096536576} ch=true
D/ViewRootImpl@7223919[MainActivity]: RELAYOUT_RES_KEEP_ALIVE_SURFACE on 40007
D/OpenGLRenderer: createReliableSurface : 0x7be36ac700, 0x7be36cd000
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
W/Gralloc3: mapper 3.x is not supported
I/gralloc: Arm Module v1.0
D/ViewRootImpl@7223919[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager: prepareNavigationBarInfo() DecorView@1d33146[MainActivity]
    getNavigationBarColor() -855310
D/InputMethodManager: prepareNavigationBarInfo() DecorView@1d33146[MainActivity]
    getNavigationBarColor() -855310
V/InputMethodManager: Starting input: tba=com.nevercode.triage ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager: startInputInner - Id : 0
I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
D/ViewRootImpl@7223919[MainActivity]: MSG_RESIZED: frame=(0,0,1080,2340) ci=(0,83,0,39) vi=(0,83,0,39) or=1
D/InputMethodManager: prepareNavigationBarInfo() DecorView@1d33146[MainActivity]
    getNavigationBarColor() -855310
V/InputMethodManager: Starting input: tba=com.nevercode.triage ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager: startInputInner - Id : 0
I/flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
I/flutter: The following message was thrown:
    Could not navigate to initial route.
    The requested route name was: "/cached_fragment"
    There was no corresponding route in the app, and therefore the initial route specified will be
    ignored and "/" will be used instead.
    ════════════════════════════════════════════════════════════════════════════════════════════════════
D/ViewRootImpl@7223919[MainActivity]: ViewPostIme pointer 0
D/ViewRootImpl@7223919[MainActivity]: ViewPostIme pointer 1
W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@ec9e2af
I/MultiWindowDecorSupport: updateCaptionType >> DecorView@84508fd[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
D/MultiWindowDecorSupport: setCaptionType = 0, DecorView = DecorView@84508fd[]
W/evercode.triag: Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (greylist, reflection, allowed)
    Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (greylist, reflection, allowed)
    Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (greylist, reflection, allowed)
    Accessing hidden method Landroid/util/LongArray;->get(I)J (greylist, reflection, allowed)
D/ViewRootImpl@a2f84a1[DefaultActivity]: setView = com.android.internal.policy.DecorView@84508fd TM=true MM=false
D/SurfaceView: onWindowVisibilityChanged(0) true io.flutter.embedding.android.FlutterSurfaceView{62ab6c6 V.E...... ......I. 0,0-0,0} of ViewRootImpl@a2f84a1[DefaultActivity]
D/ViewRootImpl@a2f84a1[DefaultActivity]: Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)0 dur=16 res=0x7 s={true 529740554240} ch=true
D/OpenGLRenderer: createReliableSurface : 0x7b500aa680, 0x7b56ff6000
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/SurfaceView: surfaceCreated 1 #8 io.flutter.embedding.android.FlutterSurfaceView{62ab6c6 V.E...... ......ID 0,0-1080,2218}
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/SurfaceView: surfaceChanged (1080,2218) 1 #8 io.flutter.embedding.android.FlutterSurfaceView{62ab6c6 V.E...... ......ID 0,0-1080,2218}
D/ViewRootImpl@7223919[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager: prepareNavigationBarInfo() DecorView@1d33146[MainActivity]
    getNavigationBarColor() -855310
D/ViewRootImpl@a2f84a1[DefaultActivity]: Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)0 dur=28 res=0x1 s={true 529740554240} ch=false
D/ViewRootImpl@a2f84a1[DefaultActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager: prepareNavigationBarInfo() DecorView@84508fd[DefaultActivity]
    getNavigationBarColor() -855310
D/InputMethodManager: prepareNavigationBarInfo() DecorView@84508fd[DefaultActivity]
D/InputMethodManager: getNavigationBarColor() -855310
V/InputMethodManager: Starting input: tba=com.nevercode.triage ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager: startInputInner - Id : 0
I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport: Input channel destroyed: 'ClientS', fd=82
D/ViewRootImpl@a2f84a1[DefaultActivity]: MSG_RESIZED: frame=(0,0,1080,2340) ci=(0,83,0,39) vi=(0,83,0,39) or=1
W/libEGL: EGLNativeWindowType 0x7be36ac710 disconnect failed
D/ViewRootImpl@7223919[MainActivity]: Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)8 dur=17 res=0x5 s={false 0} ch=true
D/ViewRootImpl@7223919[MainActivity]: stopped(true) old=false
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: plugins.flutter.io/webview
        at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:98)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:95)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:664)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:197)
        at android.app.ActivityThread.main(ActivityThread.java:7807)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
    , null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161:18)
    <asynchronous suspension>
    #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
    #3      AndroidViewController._create (package:flutter/src/services/platform_views.dart:636:54)
    #4      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:553:14)
    #5      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:178:29)
    #6      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:159:5)
    #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1748:9)
    #8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #12     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:11)
    #13     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:482:7)
    #14     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:242:7)
    #15     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:401:14)
    #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #20     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1269:11)
    #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
    #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
    #30     RenderProxyBoxMixin.perfo

``` 

</details> 


<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel master, 1.20.0-1.0.pre.132, on Mac OS X 10.15.5 19F101,
    locale en-GB)
    • Flutter version 1.20.0-1.0.pre.132 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 5995661777 (3 days ago), 2020-06-19 16:15:58 -0700
    • Engine revision 676cd566f7
    • Dart version 2.9.0 (build 2.9.0-17.0.dev 7e72c9ae7e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (6 available)
    • SM M305F                  • 32003c30dc19668f          • android-arm64  •
      Android 10 (API 29)
    • Android SDK built for x86 • emulator-5554             • android-x86    •
      Android 8.0.0 (API 26) (emulator)
    • Taha’s iPhone             • 00008020-001059882212002E • ios            •
      iOS 13.5.1
    • macOS desktop             • macos                     • darwin-x64     •
      Mac OS X 10.15.5 19F101
    • Web Server                • web-server                • web-javascript •
      Flutter Tools
    • Chrome                    • chrome                    • web-javascript •
      Google Chrome 83.0.4103.106

• No issues found!
``` 

</details>

**Comment by FredDominant** [comment]
Hello, I'm currently facing this issue. Is there any fix for this yet?

**Comment by rh-id** [comment]
Hi, same issue for `webview_flutter: ^1.0.7` it works fine until I run `flutter upgrade`, many plugin breaks.

other plugins `android_alarm_manager: 0.4.5+17`
```
E/flutter (12289): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method AlarmService.start on channel base.plugins.flutter.io/android_alarm_manager)
E/flutter (12289): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (12289): <asynchronous suspension>
E/flutter (12289): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (12289): #2      AndroidAlarmManager.initialize (package:android_alarm_manager/android_alarm_manager.dart:96:35)
```

other plugins `package_info: 0.4.3+2`
```
E/flutter (12289): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel base.plugins.flutter.io/package_info)
E/flutter (12289): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (12289): <asynchronous suspension>
E/flutter (12289): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (12289): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:359:49)
E/flutter (12289): #3      PackageInfo.fromPlatform (package:package_info/package_info.dart:43:25)
E/flutter (12289): #4      AboutScreen.build.<anonymous closure> (package:my_gig_profile/ui/about.dart:21:31)
E/flutter (12289): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter (12289): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter (12289): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter (12289): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter (12289): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter (12289): #10     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:259:7)
E/flutter (12289): #11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
E/flutter (12289): #12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362:20)
E/flutter (12289): #13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter (12289): #14     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter (12289): #15     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (12289): #16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter (12289): #17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter (12289): #18     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (12289): #19     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (12289): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (12289): #21     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (12289): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter (12289): 
```
flutter doctor
```
[✓] Flutter (Channel stable, 1.22.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.5 at /home/rubyh/Flutter/flutter
    • Framework revision 7891006299 (35 hours ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/rubyh/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64 • Android 5.0.2 (API 21) (emulator)

! Doctor found issues in 1 category.
Process finished with exit code 0
```

**Comment by vikskod** [comment]
Does this problem have a solution? Flutter web view doesn't work on release mode.
https://stackoverflow.com/questions/65876867/flutter-web-view-doesnt-work-on-release-mode

**Comment by praharshbhatt** [comment]
Any updates here? Facing the same issue.

**Comment by sushil7271** [comment]
Facing the same issue. This work properly in debug mode but, doesn't work in release mode. Any solution for this issue?

**Comment by DaleSmith** [comment]
Facing the same issue. Any solutions?

**Comment by Abdelaty** [comment]
Facing the same issue, any updates?

**Comment by behradkhadem** [comment]
Any solutions guys?

**Comment by clyndonwooliesx** [comment]
Adding to the queue who are also facing the same issue. 

I'm not sure if helpful but this occurred using the same `webview_flutter ^1.0.7`

Seems to be when the platformViewRegistry registers this view factory here:

```
  @Override
  public void onAttachedToEngine(FlutterPluginBinding binding) {
    BinaryMessenger messenger = binding.getBinaryMessenger();
    binding
        .getPlatformViewRegistry()
        .registerViewFactory(
            "plugins.flutter.io/webview", new WebViewFactory(messenger, /*containerView=*/ null));
    flutterCookieManager = new FlutterCookieManager(messenger);
  }
```

It is not found when attempting to retrieve here: 

```
  @Override
  public boolean registerViewFactory(String viewTypeId, PlatformViewFactory factory) {
    if (viewFactories.containsKey(viewTypeId)) return false;
    viewFactories.put(viewTypeId, factory);
    return true;
  }

  PlatformViewFactory getFactory(String viewTypeId) {
    return viewFactories.get(viewTypeId);
  }
```

called by:

```
@TargetApi(Build.VERSION_CODES.JELLY_BEAN_MR1)
@Override
public long createVirtualDisplayForPlatformView(@NonNull PlatformViewsChannel.PlatformViewCreationRequest request) {

 // removed out of context code 

  PlatformViewFactory viewFactory = registry.getFactory(request.viewType);
  if (viewFactory == null) {
    throw new IllegalStateException(
        "Trying to create a platform view of unregistered type: " + request.viewType);
  }

```

**Comment by behradkhadem** [comment]
My problem solved after I ran another debug session. I think problem was caused by `pubspec.lock` file.

**Comment by vikskod** [comment]
> My problem solved after I ran another debug session. I my think problem was caused by `pubspec.lock` file.

What didi you changed

**Comment by behradkhadem** [comment]
> > My problem solved after I ran another debug session. I my think problem was caused by `pubspec.lock` file.
> 
> What did you changed

Nothing! It got solved by it's own. `pubspec.lock` wasn't updated after changes I made, so running debug session again updated the `pubspeck.lock` file and problem got solved, probably!

**Comment by vikskod** [comment]
> > > My problem solved after I ran another debug session. I my think problem was caused by `pubspec.lock` file.
> > 
> > 
> > What did you changed
> 
> Nothing! It got solved by it's own. `pubspec.lock` wasn't updated after changes I made, so running debug session again updated the `pubspeck.lock` file and problem got solved, probably!

I can see on my pubspec.yaml
  webview_flutter:
    dependency: "direct dev"
    description:
      name: webview_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.7"

Which seems fine for me but still getting problem when I create release apk (Working fine on debug apk).
This is the question on stackoverflow
https://stackoverflow.com/questions/65876867/flutter-web-view-doesnt-work-on-release-mode

**Comment by clyndonwooliesx** [comment]
@vikskod are you using a cached Flutter engine?

**Comment by vikskod** [comment]
> @vikskod are you using a cached Flutter engine?

I'm not

**Comment by Anuj-logiciel** [comment]
Anybody with solution or trick?

**Comment by clyndonwooliesx** [comment]
Not sure if useful but I've also been seeing in the logs that this must be to do with the way the plugins are being registered. I received this message as well:
`W/FlutterEnginePluginRegistry: Attempted to register plugin (io.flutter.plugins.webviewflutter.WebViewFlutterPlugin@2faf0f4) but it was already registered with this FlutterEngine (io.flutter.embedding.engine.FlutterEngine@ca1790c).`

**Comment by clyndonwooliesx** [comment]
So I'm not sure if this is useful to anyone but we did manage to solve this issue. 

Firstly, we are an add-to-app situation of course and essentially what was happening was that we found in another location we had initialised a cached Flutter engine to test that functionality, but then separately we were building a whole new engine for each FlutterFragment.

Each FlutterFragment at this point was then not initialising with the expected plugins for some reason.

Instead what we found to work was to use the Cached Flutter Engine and use a MethodChannel for navigating to the desired Flutter route before opening the FlutterFragment.

So at some point somewhere(probably in your MainActivity or equivalent) setup your Cached Flutter Engine:

```
       val flutterEngine = FlutterEngine(this)

        flutterEngine.dartExecutor.executeDartEntrypoint(
                DartExecutor.DartEntrypoint.createDefault()
        )

        FlutterEngineCache
                .getInstance()
                .put(INSERT_YOUR_DESIRED_FLUTTER_ENGINE_ID_HERE, flutterEngine)
```

Then when you want to open your FlutterFragment:

```
       var flutterEngine = FlutterEngineCache
                .getInstance()
                .get(INSERT_YOUR_FLUTTER_ENGINE_ID_FROM_BEFORE_HERE)

       var flutterFragment = FlutterFragment
               .withCachedEngine(INSERT_YOUR_FLUTTER_ENGINE_ID_FROM_BEFORE_HERE)
               .build()

        MethodChannel(
                flutterEngine.dartExecutor.binaryMessenger,
                INSERT_YOUR_DESIRED_METHOD_CHANNEL_NAME_HERE
        ).invokeMethod("setRoute", INSERT_ROUTE_YOU_WANT_HERE)

        openFragment(flutterFragment!!)
```

And an example of how you might use this method channel in your Flutter Dart code

```
class _MyViewState extends State<MyView> {

  static const myMethodChannel = const MethodChannel(INSERT_YOUR_DESIRED_METHOD_CHANNEL_NAME_HERE);

  Future<void> _handleMethodCalls(MethodCall call) async {
    switch (call.method) {
      case "setRoute":
        Navigator.pushReplacmentNamed(context, INSERT_YOUR_DESIRED_ROUTE_NAME_HERE)
       ...
    }
  }

...

  @override
  void initState() {
    super.initState();
    platform.setMethodCallHandler(_handleMethodCalls);
  }

}
```

**Comment by thinhlh** [comment]
I have just facing this issue. Got out of this by running `flutter clean` then reinstall the application with the package version 2.0.4. Still don't know how it can be resolved.

**Comment by taqi92** [comment]
still got the same issue

**Comment by tentenponce** [comment]
As for me, I fixed the issue after I checked each library that I'm using, the library causing the error was the `flutter_facebook_login: ^3.0.0`, after removing it, it fixes the problem.

Try creating new project with the `webview_flutter` library only, and put one by one, or put everything and remove one by one (depends on you) all of the libraries that you are using until the issue comes out or until it is fixed.

**Comment by danagbemava-nc** [comment]
Issue is reproducible on `stable 2.2.3` and `master 2.5.0-7.0.pre.129` with `webview_flutter: ^2.0.12`.

For sample code, [follow Add Flutter Fragment in Add to App section of docs](https://flutter.dev/docs/development/add-to-app/android/add-flutter-fragment?tab=launch-with-initial-route-kotlin-tab)

<details>
<summary>main.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(const FlutterActivityWrapper());
}

class FlutterActivityWrapper extends StatelessWidget {
  const FlutterActivityWrapper({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(
          title: const Text('A2A - Webview - Fragment'),
        ),
        body: const WebView(
          initialUrl: 'http://flutter.dev',
        ),
      ),
    );
  }
}

```
</details>

<details>
<summary>logs</summary>

```console
08/18 09:12:49: Launching 'app' on Xiaomi M2007J20CG.
Install successfully finished in 3 s 748 ms.
$ adb shell am start -n "dev.flutter.example.androidfullscreen/dev.flutter.example.androidfullscreen.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 20865 on device 'xiaomi-m2007j20cg-5dd3be00'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
D/ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
I/Perf: Connecting to perf service.
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
I/MultiDex: VM with version 2.1.0 has multidex support
    Installing application
    VM has multidex support, MultiDex support library is disabled.
I/ResourceExtractor: Found extracted resources res_timestamp-1-1629277819076
    Resource version mismatch res_timestamp-1-1629277974577
I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/kernel_blob.bin
I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/vm_snapshot_data
I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/isolate_snapshot_data
W/droidfullscreen: type=1400 audit(0.0:894996): avc: denied { read } for name="max_map_count" dev="proc" ino=22733357 scontext=u:r:untrusted_app_27:s0:c122,c257,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=com.netflix.mediaclient
I/AdrenoGLES-0: QUALCOMM build                   : 3142bdd, I7afe4835b7
    Build Date                       : 09/16/20
    OpenGL ES Shader Compiler Version: EV031.32.02.00
    Local Branch                     : 
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
    Build Config                     : S P 10.0.6 AArch64
I/AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
I/AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
W/Looper: PerfMonitor longMsg : seq=3 plan=09:12:55.421 late=2ms wall=1027ms running=293ms runnable=17ms io=2ms h=android.app.ActivityThread$H w=110 procState=2
D/View: dev.flutter.example.androidfullscreen initForcedUseForceDark: 1
W/droidfullscree: Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (greylist,test-api, reflection, allowed)
    Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (greylist, reflection, allowed)
    Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (greylist, reflection, allowed)
    Accessing hidden method Landroid/util/LongArray;->get(I)J (greylist, reflection, allowed)
I/flutter: Observatory listening on http://127.0.0.1:41707/UeEZ5hIIFIE=/
W/Looper: PerfMonitor looperActivity : package=dev.flutter.example.androidfullscreen/.MainActivity time=300ms latency=1025ms running=196ms  procState=2 ClientTransaction{ callbacks=[android.app.servertransaction.LaunchActivityItem] lifecycleRequest=android.app.servertransaction.ResumeActivityItem } historyMsgCount=1 (msgIndex=1 wall=1027ms seq=3 running=293ms runnable=17ms io=2ms late=2ms h=android.app.ActivityThread$H w=110)
W/Looper: PerfMonitor looperActivity : package=dev.flutter.example.androidfullscreen/.MainActivity time=1ms latency=1323ms running=0ms  procState=2 ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] } historyMsgCount=2 (msgIndex=1 wall=1027ms seq=3 running=293ms runnable=17ms io=2ms late=2ms h=android.app.ActivityThread$H w=110) (msgIndex=2 wall=300ms seq=4 running=196ms runnable=56ms late=1025ms h=android.app.ActivityThread$H w=159)
D/SurfaceView: UPDATE null, mIsCastMode = false
D/SurfaceView: UPDATE null, mIsCastMode = false
W/Looper: PerfMonitor doFrame : time=493ms vsyncFrame=0 latency=1ms procState=2
W/Looper: PerfMonitor doFrame : time=1ms vsyncFrame=0 latency=480ms procState=2 historyMsgCount=2 (msgIndex=1 wall=493ms seq=10 running=43ms runnable=26ms late=1ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method create on channel flutter/platform_views)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
    <asynchronous suspension>
    #1      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1043:18)
    <asynchronous suspension>
    #2      AndroidViewController.create (package:flutter/src/services/platform_views.dart:748:5)
    <asynchronous suspension>
    #3      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:193:7)
    <asynchronous suspension>
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: plugins.flutter.io/webview
        at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:192)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:7861)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
    , null, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
    <asynchronous suspension>
    #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1043:18)
    <asynchronous suspension>
    #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:748:5)
    <asynchronous suspension>
    #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:193:7)
    <asynchronous suspension>
I/droidfullscree: ProcessProfilingInfo new_methods=1181 is saved saved_to_disk=1 resolve_classes_delay=8000
```
</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel master, 2.5.0-7.0.pre.129, on macOS 11.5.1 20G80
    darwin-arm, locale en-GH)
    • Flutter version 2.5.0-7.0.pre.129 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 29c089c2ed (80 minutes ago), 2021-08-18 01:37:04 -0400
    • Engine revision b13c765675
    • Dart version 2.15.0 (build 2.15.0-24.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile)    • 5dd3be00                  • android-arm64  •
      Android 11 (API 30)
    • Nexus’ IPhone (mobile) • 00008020-001875E83A38002E • ios            • iOS
      14.6 18F72
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 92.0.4515.131

• No issues found!
```

```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-arm, locale
    en-GH)
    • Flutter version 2.2.3 at /Users/nexus/dev/sdks/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile)    • 5dd3be00                  • android-arm64  •
      Android 11 (API 30)
    • Nexus’ IPhone (mobile) • 00008020-001875E83A38002E • ios            • iOS
      14.6
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 92.0.4515.131

• No issues found!
```

</details>

**Comment by orenwang** [comment]
> So I'm not sure if this is useful to anyone but we did manage to solve this issue.
> 
> Firstly, we are an add-to-app situation of course and essentially what was happening was that we found in another location we had initialised a cached Flutter engine to test that functionality, but then separately we were building a whole new engine for each FlutterFragment.
> 
> Each FlutterFragment at this point was then not initialising with the expected plugins for some reason.
> 
> Instead what we found to work was to use the Cached Flutter Engine and use a MethodChannel for navigating to the desired Flutter route before opening the FlutterFragment.
> 
> So at some point somewhere(probably in your MainActivity or equivalent) setup your Cached Flutter Engine:
> 
> ```
>        val flutterEngine = FlutterEngine(this)
> 
>         flutterEngine.dartExecutor.executeDartEntrypoint(
>                 DartExecutor.DartEntrypoint.createDefault()
>         )
> 
>         FlutterEngineCache
>                 .getInstance()
>                 .put(INSERT_YOUR_DESIRED_FLUTTER_ENGINE_ID_HERE, flutterEngine)
> ```
> 
> Then when you want to open your FlutterFragment:
> 
> ```
>        var flutterEngine = FlutterEngineCache
>                 .getInstance()
>                 .get(INSERT_YOUR_FLUTTER_ENGINE_ID_FROM_BEFORE_HERE)
> 
>        var flutterFragment = FlutterFragment
>                .withCachedEngine(INSERT_YOUR_FLUTTER_ENGINE_ID_FROM_BEFORE_HERE)
>                .build()
> 
>         MethodChannel(
>                 flutterEngine.dartExecutor.binaryMessenger,
>                 INSERT_YOUR_DESIRED_METHOD_CHANNEL_NAME_HERE
>         ).invokeMethod("setRoute", INSERT_ROUTE_YOU_WANT_HERE)
> 
>         openFragment(flutterFragment!!)
> ```
> 
> And an example of how you might use this method channel in your Flutter Dart code
> 
> ```
> class _MyViewState extends State<MyView> {
> 
>   static const myMethodChannel = const MethodChannel(INSERT_YOUR_DESIRED_METHOD_CHANNEL_NAME_HERE);
> 
>   Future<void> _handleMethodCalls(MethodCall call) async {
>     switch (call.method) {
>       case "setRoute":
>         Navigator.pushReplacmentNamed(context, INSERT_YOUR_DESIRED_ROUTE_NAME_HERE)
>        ...
>     }
>   }
> 
> ...
> 
>   @override
>   void initState() {
>     super.initState();
>     platform.setMethodCallHandler(_handleMethodCalls);
>   }
> 
> }
> ```

This worked for me for shared_preferences `MissingPluginException`, which only happens when I try to use FlutterFragment in an add-to-app case. Thanks a lot!
Not sure for webview_flutter though.
