### ISSUE TITLE
[tool_crash] FileSystemException: Creation failed, OS Error: The system cannot find the path specified., errno = 3

### ISSUE THREAD

**Issue by praveenamona** [flutter/flutter#60272]
## Command
```
flutter run --machine --target lib\main.dart -d 100.80.52.107:5555 --track-widget-creation --start-paused --web-server-debug-protocol ws --web-allow-expose-url
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Creation failed, OS Error: The system cannot find the path specified.
, errno = 3
```
#0      _Directory.createSync (dart:io/directory_impl.dart:140:7)
#1      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#2      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#3      _ensureExists (package:flutter_tools/src/cache.dart:1378:15)
#4      Cache.downloadFile (package:flutter_tools/src/cache.dart:465:5)
#5      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:608:23)
#6      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:604:55)
#7      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:638:26)
#8      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:604:12)
#9      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:625:12)
#10     EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:753:13)
#11     CachedArtifact.update (package:flutter_tools/src/cache.dart:560:11)
#12     Cache.updateAll (package:flutter_tools/src/cache.dart:432:24)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:773:27)
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:695:33)
#15     _rootRunUnary (dart:async/zone.dart:1192:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:715:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:303:13)
#23     RunCommand.usagePath (package:flutter_tools/src/commands/run.dart)
#24     _rootRunUnary (dart:async/zone.dart:1192:38)
```
```
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [Version 10.0.10586], locale en-US)
    • Flutter version 1.18.0-11.1.pre at F:\flutter
    • Framework revision 2738a1148b (6 weeks ago), 2020-05-13 15:24:36 -0700
    • Engine revision <<<<<<< HE
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Hp\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: F:\Andriod studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\Hp\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.5)
    • Android Studio at F:\Andriod studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] VS Code (version 1.46.1)
    • VS Code at C:\Users\Hp\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • SM J720F   • 100.80.52.107:5555 • android-arm64  • Android 8.0.0 (API 26) (emulator)
    • Web Server • web-server         • web-javascript • Flutter Tools
    • Chrome     • chrome             • web-javascript • Google Chrome 83.0.4103.106

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 2294d75bfa8d067ba90230c0fc2268f3636d7584
### Plugins
esys_flutter_share-1.0.2
file_picker-1.9.0+1
flutter_plugin_android_lifecycle-1.0.7
image_picker-0.6.6+5
path_provider-1.6.7
path_provider_macos-0.0.4+1
share-0.6.4+2
sqflite-1.3.0

**Comment by TahaTesser** [comment]
Related https://github.com/flutter/flutter/issues/56775

**Comment by iapicca** [comment]
@TahaTesser 
according to this [comment](https://github.com/flutter/flutter/issues/66415#issuecomment-701003004)
this issue might have been fixed in the master channel

**Comment by TahaTesser** [comment]
Thanks @iapicca 
Hi @praveenamona 
This seems to be fixed on the latest `master` channel  https://github.com/flutter/flutter/issues/66415#issuecomment-701003004
Closing, as fixed. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by iapicca** [comment]
@TahaTesser this issue seems quite frequent,
maybe could be considered for cherry pick

**Comment by adilwahla** [comment]
hi still not resolved can you tell me ? how could it be resolved ?
one thing there is no file "GeneratedPluginRegistrant.java" created 
thanks in advance

**Comment by iapicca** [comment]
@adilwahla 
did you upgrade to master?
