### ISSUE TITLE
Videos recorded with an orientation of 180° ( landscapeRight) are reversed using video_player.

### ISSUE THREAD

**Issue by laurentP22** [flutter/flutter#60327]
When playing a video recorded with an orientation of 180° ( landscapeRight) the video is reversed. I could reproduce the error using the example of the video_player plugin. 

When playing the video with the gallery of the phone there is no problem, the orientation is respected.

I tried with the others orientations (landscapeLeft, portraitDown and portraitUp) and there is no problem.

The problem might comes from the dependencie exoplayer2 which is applying a rotation of 180 to the surface when it is unnecessary. 

## Steps to Reproduce

1. Record a video with the device's camera application, **screen's orientation: landscapeRight**.
2. Add the video to the assets of the example of the video_player plugin.
3. Update the pubsec.yaml to reference the video.
4. Update the controller of the `_ButterFlyAssetVideoState` class to load the video : 
`_controller = VideoPlayerController.asset('assets/video_name.mp4');`

**Expected results:** 
The video should be displayed with the same orientation as it was recorded. 
<img width="182" alt="expected_orientation" src="https://user-images.githubusercontent.com/55256645/85807158-e13fdd80-b705-11ea-8e83-1e0d1adfd338.png">

**Actual results:** 
The video is reversed.
<img width="182" alt="bad_orientation" src="https://user-images.githubusercontent.com/55256645/85806976-637bd200-b705-11ea-8c1e-cd45ee2fa6c5.png">

<details>
  <summary>Logs</summary>

```
I/ExoPlayerImpl(15219): Init 1dbf3a4 [ExoPlayerLib/2.9.6] [river, moto g(7), motorola, 29]
I/MediaCodec(15219): (0x76bd584600) init name(OMX.qcom.video.decoder.avc)
I/OMXClient(15219): IOmx service obtained
I/MediaCodec(15219): (0x76bd584600) Component Allocated (OMX.qcom.video.decoder.avc)
I/MediaCodec(15219): (0x76bd584600) configure surface(0x772a1cf000) crypto(0x0) flags(0)
D/MediaCodec(15219): (0x76bd584600) configure format: AMessage(what = 0x00000000) = {
D/MediaCodec(15219):       Buffer csd-1 = {
D/MediaCodec(15219):         00000000:  00 00 00 01 68 ee 06 e2  c0                       ....h....
D/MediaCodec(15219):       }
D/MediaCodec(15219):       int32_t max-height = 1080
D/MediaCodec(15219):       int32_t max-width = 1920
D/MediaCodec(15219):       string mime = "video/avc"
D/MediaCodec(15219):       int32_t width = 1920
D/MediaCodec(15219):       int32_t priority = 0
D/MediaCodec(15219):       int32_t rotation-degrees = 180
D/MediaCodec(15219):       int32_t max-input-size = 335781
D/MediaCodec(15219):       int32_t height = 1080
D/MediaCodec(15219):       Buffer csd-0 = {
D/MediaCodec(15219):         00000000:  00 00 00 01 67 64 00 28  ac b4 03 c0 11 3f 2c ac  ....gd.(.....?,.
D/MediaCodec(15219):         00000010:  18 18 18 1b 42 84 d4                              ....B..
D/MediaCodec(15219):       }
D/MediaCodec(15219):     }
D/SurfaceUtils(15219): connecting to surface 0x772a1cf010, reason connectToSurface
I/MediaCodec(15219): [OMX.qcom.video.decoder.avc] setting surface generation to 15584260
D/SurfaceUtils(15219): disconnecting from surface 0x772a1cf010, reason connectToSurface(reconnect)
D/SurfaceUtils(15219): connecting to surface 0x772a1cf010, reason connectToSurface(reconnect)
I/ACodec  (15219): DRC Mode: Dynamic Buffer Mode
I/ExtendedACodec(15219): setupVideoDecoder()
I/ACodec  (15219): [OMX.qcom.video.decoder.avc] setupVideoDecoder Width Height (1920x1080)
I/ACodec  (15219): mime (video/avc) compressionFormat (7)
I/ExtendedACodec(15219): Decoder will be in frame by frame mode
I/MediaCodec(15219): (0x76bd584600) start
D/SurfaceUtils(15219): set up nativeWindow 0x772a1cf010 for 1920x1080, color 0x7fa30c06, rotation 180, usage 0x20002900
I/MediaCodec(15219): (0x76bd584600) kWhatStartCompleted
I/MediaCodec(15219): (0x76bd585400) init name(OMX.google.aac.decoder)
I/OMXClient(15219): IOmx service obtained
I/MediaCodec(15219): (0x76bd585400) Component Allocated (OMX.google.aac.decoder)
I/MediaCodec(15219): (0x76bd585400) configure surface(0x0) crypto(0x0) flags(0)
D/MediaCodec(15219): (0x76bd585400) configure format: AMessage(what = 0x00000000) = {
D/MediaCodec(15219):       float operating-rate = 48000.000000
D/MediaCodec(15219):       int32_t sample-rate = 48000
D/MediaCodec(15219):       string mime = "audio/mp4a-latm"
D/MediaCodec(15219):       int32_t channel-count = 2
D/MediaCodec(15219):       int32_t priority = 0
D/MediaCodec(15219):       int32_t max-input-size = 998
D/MediaCodec(15219):       Buffer csd-0 = {
D/MediaCodec(15219):         00000000:  11 90                                             ..
D/MediaCodec(15219):       }
D/MediaCodec(15219):     }
I/ACodec  (15219): codec does not support config priority (err -2147483648)
I/ACodec  (15219): codec does not support config operating rate (err -2147483648)
I/MediaCodec(15219): (0x76bd585400) start
I/MediaCodec(15219): (0x76bd585400) kWhatStartCompleted
D/MediaCodec(15219): (0x76bd585400) kWhatOutputBuffersChanged
D/SurfaceUtils(15219): set up nativeWindow 0x772a1cf010 for 1920x1088, color 0x7fa30c06, rotation 180, usage 0x20002900
D/MediaCodec(15219): (0x76bd584600) kWhatOutputBuffersChanged
I/MediaCodec(15219): (0x76bd584600) setParameters
E/qdgralloc(15219): Unknown Color Space = 0
D/AudioTrack(15219): getTimestamp_l(310): device stall time corrected using current time 25545472079019
W/AudioTrack(15219): getTimestamp_l(310): retrograde timestamp time corrected, 25545476506623 < 25545482079801
E/qdgralloc(15219): Unknown Color Space = 0
I/MediaCodec(15219): (0x76b4524e00) stop
I/ExoPlayerImpl(15219): Release 5db5b5b [ExoPlayerLib/2.9.6] [river, moto g(7), motorola, 29] [goog.exo.core]
E/BufferQueueProducer(15219): [SurfaceTexture-0-15219-2] cancelBuffer: BufferQueue has been abandoned
I/chatty  (15219): uid=10457(io.flutter.plugins.videoplayerexample) JNISurfaceTextu identical 5 lines
E/BufferQueueProducer(15219): [SurfaceTexture-0-15219-2] cancelBuffer: BufferQueue has been abandoned
D/SurfaceUtils(15219): disconnecting from surface 0x76d5a67010, reason disconnectFromSurface
I/MediaCodec(15219): (0x76b4524e00) release
I/MediaCodec(15219): (0x76b4525c00) stop
I/MediaCodec(15219): (0x76b4525c00) release
E/qdgralloc(15219): Unknown Color Space = 0
```

```
Analyzing video_player...                                               
No issues found! (ran in 9.8s)
```

```
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-MX)
    • Flutter version 1.17.3 at /Users/laurent/Tools/flutter
    • Framework revision b041144f83 (3 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/laurent/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/laurent/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • moto g 7 • ZY225BM4TR • android-arm64 • Android 10 (API 29)
```

</details>

**Comment by VladyslavBondarenko** [comment]
Reproduced with `video_player: ^0.10.11+1` with all current channels on Redmi Note 7 Android 9 (API 28)

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.20.0-1.0.pre.220, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-1.0.pre.220 at /Users/nevercode/dev/flutter
    • Framework revision 1e6e7150f3 (7 hours ago), 2020-06-26 12:01:59 +0800
    • Engine revision 22b099bc63
    • Dart version 2.9.0 (build 2.9.0-19.0.dev ea87c9b01a)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • Redmi Note 7  • 6345c469   • android-arm64  • Android 9 (API 28)
    • macOS desktop • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server    • web-server • web-javascript • Flutter Tools
    • Chrome        • chrome     • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

</details>

**Comment by marchelo** [comment]
I'm experiencing the same issue. Any news about when it will be fixed?

**Comment by marcelotten** [comment]
Same here...

**Comment by kiskunk** [comment]
Same here... using 0.11.0

**Comment by Ehesp** [comment]
Can someone upload an example video they're having issues with. I've just tried an emulated one and don't have an issue. I suspect there's some property metadata on the video which needs investigating.

**Comment by cyanglaz** [comment]
Looks like the issue didn't happen with the offical expoplayer demo on android, so the root cause is highly likely within the plugin, or the flutter framework.

**Comment by karmazinkd** [comment]
@Ehesp [here](https://drive.google.com/file/d/1yjZ5ovT1klAt0o3TgfKRtSZZ-ITrvoF5/view?usp=sharing ) is the video sample recorded in landscape on Nexus5X, Android 8.1, on the native camera app.

and here are the details of this video file fetched by ffmpeg lib:
`{streams: [{color_range: pc, pix_fmt: yuvj420p, r_frame_rate: 30/1, start_pts: 0, duration_ts: 1232763, duration: 13.697367, bit_rate: 11926139, sample_aspect_ratio: 1:1, is_avc: true, codec_tag_string: avc1, avg_frame_rate: 12330000/410921, color_space: bt470bg, nb_frames: 411, codec_long_name: unknown, height: 720, color_primaries: bt470bg, nal_length_size: 4, chroma_location: left, time_base: 1/90000, coded_height: 720, level: 31, color_transfer: smpte170m, profile: 66, bits_per_raw_sample: 8, index: 0, codec_name: h264, tags: {creation_time: 2020-10-22T19:38:48.000000Z, rotate: 180, handler_name: VideoHandle, language: eng}, start_time: 0.000000, disposition: {dub: 0, karaoke: 0, default: 1, original: 0, visual_impaired: 0, forced: 0, attached_pic: 0, timed_thumbnails: 0, comment: 0, hearing_impaired: 0, lyrics: 0, clean_effects: 0}, codec_tag: 0x31637661, has_b_frames: 0, refs: 1, codec_time_base: 410921/24660000, width: 1280, display_aspect_ratio: 16:9, side_data_list: [{side_data_type: Display Matrix,`

Note tags: {**rotate: 180**} property. Normal videos don't have that field. Only those videos which are displayed upside down.

How to record such video: hold the phone in landscape and make sure that the top is on the left and the bottom is on the right, here is the screenshot: 
![Screenshot_20201022-225644](https://user-images.githubusercontent.com/15160049/96923737-61aafb00-14ba-11eb-899b-c40ba5e7ef02.png)

so the workaround for now I guess is to get metadata of the video and if there is `rotate: 180` than rotate the `VideoPlayer` widget

**Comment by Ehesp** [comment]
@karmazinkd Awesome thanks for the extra details 👍

**Comment by DevonJerothe** [comment]
I am running into this issue as well. Rotating the widget does not help me as I am sending the recorded video via Email / Share..

**Comment by KyleFin** [comment]
[VideoPlayer.java#L283](https://github.com/flutter/plugins/blob/0892a2d292c27458591f76e1239148799ee6da08/packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java#L283) may be related. I'll keep looking into how to set Java breakpoints and investigate further.

**Comment by KyleFin** [comment]
I created a [draft PR](https://github.com/flutter/plugins/pull/3820) with comments about my reasoning. (I just rotated the VideoPlayer widget, but I'd prefer to get the rotation correct in the Java code.)

If this PR seems like a reasonable fix, I'll add tests etc and clean it up for more thorough review.

**Comment by nuhash** [comment]
I don't think flipping the player is the solution to this problem, videos recorded using the flutter camera plugin always display incorrectly on VLC. So is VLC suddenly broken? Videos recorded in portrait are sometimes rotated by 90deg, videos in landscape are sometimes flipped 180deg.


I found that locking the orientation into LandscapeRight and modifying the getMediaOrientation function in DeviceOrientationManager.java produced correctly oriented videos.
`
  public int getMediaOrientation(PlatformChannel.DeviceOrientation orientation) {
    int angle = 0;

    // Fallback to device orientation when the orientation value is null
    if (orientation == null) {
      orientation = getUIOrientation();
    }

    switch (orientation) {
      case PORTRAIT_UP:
        angle = 0;
        break;
      case PORTRAIT_DOWN:
        angle = 180;
        break;
      case LANDSCAPE_LEFT:
        angle = 270;
        break;
      case LANDSCAPE_RIGHT:
        angle = 90;
        break;
    }
    if (isFrontFacing) angle *= -1;
    return (angle + sensorOrientation + 360) % 360;
  }
`

**Comment by KyleFin** [comment]
@nuhash that seems like a separate issue (Flutter camera plugin _recording_ in wrong orientation. Maybe related to https://github.com/flutter/flutter/issues/78685?).

If I understand correctly, this issue is about video_player plugin _playing_ videos upside-down. The first step to reproduce in the first comment on this issue says `Record a video with the device's camera application`, not `record with Flutter camera plugin` and the sample video provided in https://github.com/flutter/flutter/issues/60327#issuecomment-714729881 (which I've been using in debugging) was recorded using native camera app.

**Comment by nuhash** [comment]
@KyleFin Yeah sorry about that, I think I had the wrong tab open. The issue you linked isn't the issue I have though.

**Comment by KyleFin** [comment]
No worries. Maybe https://github.com/flutter/flutter/issues/27201? It would be nice if someone can update the title of this issue with [video_player] to make it more clear this issue isn't about recording.

**Comment by IvanPavliuk** [comment]
Any updates?

**Comment by KyleFin** [comment]
I'm planning to add tests and send this for review by the end of the month.

**Comment by maheshmnj** [comment]
Hi @laurentP22,
 Thanks for filing the issue, I am able to reproduce this issue on the latest stable and master channel with latest video player plugin ```video_player: ^2.1.6```. The video recorded with landscape right rotation are displayed with 180° rotation in the video player this happens regardless of whether the video is served via asset or file.

 <details>
<summary>code sample</summary>

```
import 'package:video_player/video_player.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: VideoAppDocs(),
    ),
  );
}

class VideoAppDocs extends StatefulWidget {
  @override
  _VideoAppDocsState createState() => _VideoAppDocsState();
}

class _VideoAppDocsState extends State<VideoAppDocs> {
  late VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.asset('assets/rotatedVideo.mp4')
            ..initialize().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
      });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: Center(
          child: _controller.value.isInitialized
              ? AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer(_controller),
                )
              : Container(),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              _controller.value.isPlaying
                  ? _controller.pause()
                  : _controller.play();
            });
          },
          child: Icon(
            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}

```
</details>
 
  <details>
<summary>Output</summary>

<img src="https://user-images.githubusercontent.com/31410839/123964045-b0594f00-d9d0-11eb-9bc4-6633d24ec779.png" width ="350">

 </details>
 
 <details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-arm, locale en-IN)
    • Flutter version 2.2.2 at /Users/mahesh/Documents/flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile)     • d9dac45d                             • android-arm64  • Android 10 (API 29)
    • iPhone 12 Pro Max (mobile) • 6A434744-B348-4FB3-AB10-131292174456 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```

```
mahesh@Maheshs-Air-M1 example % flutterm doctor -v
[✓] Flutter (Channel master, 2.3.0-17.0.pre.538, on macOS 11.4 20F71 darwin-arm, locale en-IN)
    • Flutter version 2.3.0-17.0.pre.538 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1fd2f7c400 (2 days ago), 2021-06-27 22:51:02 -0400
    • Engine revision 5d287a2061
    • Dart version 2.14.0 (build 2.14.0-250.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile)     • d9dac45d                             • android-arm64  • Android 10 (API 29)
    • iPhone 12 Pro Max (mobile) • 6A434744-B348-4FB3-AB10-131292174456 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```
</details>

**Comment by cvphat4796** [comment]
Any updates ??

**Comment by riki08** [comment]
Buen día, ya hay una solución para ese problema de orientación de los videos. gracias

**Comment by KyleFin** [comment]
Finally sent https://github.com/flutter/plugins/pull/3820 for review! Sorry it took me longer than I hoped to write the tests 😞

**Comment by lukehmcc** [comment]
> Finally sent [flutter/plugins#3820](https://github.com/flutter/plugins/pull/3820) for review! Sorry it took me longer than I hoped to write the tests disappointed

Glad that this is being actively worked on, it's quite an annoying bug and having something in the pipeline to fix is is great. 

Hope it goes through soon.

**Comment by moosoul** [comment]
> I don't think flipping the player is the solution to this problem, videos recorded using the flutter camera plugin always display incorrectly on VLC. So is VLC suddenly broken? Videos recorded in portrait are sometimes rotated by 90deg, videos in landscape are sometimes flipped 180deg.
> 
> I found that locking the orientation into LandscapeRight and modifying the getMediaOrientation function in DeviceOrientationManager.java produced correctly oriented videos.
> 
> ```
> public int getMediaOrientation(PlatformChannel.DeviceOrientation orientation) {
>     int angle = 0;
> 
>     // Fallback to device orientation when the orientation value is null
>     if (orientation == null) {
>       orientation = getUIOrientation();
>     }
> 
>     switch (orientation) {
>       case PORTRAIT_UP:
>         angle = 0;
>         break;
>       case PORTRAIT_DOWN:
>         angle = 180;
>         break;
>       case LANDSCAPE_LEFT:
>         angle = 270; //EDIT - This was 90 and LANDSCAPE_RIGHT was 270...
>         break;
>       case LANDSCAPE_RIGHT:
>         angle = 90;
>         break;
>     }
>     if (isFrontFacing) angle *= -1;
>     return (angle + sensorOrientation + 360) % 360;
>   }
> ```

The camera landscape not work correct and the video_player is also, it's make me crazy.

**Comment by cvphat4796** [comment]
My customer is complaining that this issue is resolved too slow and ask me why did you choose Flutter. I can't talk any more 😥 😟

**Comment by maheshmnj** [comment]
@cvphat4796 until this lands, as a temporary fix you could try wrapping your video player in [RotatedBox](https://api.flutter.dev/flutter/widgets/RotatedBox-class.html)

**Comment by cvphat4796** [comment]
> @cvphat4796 until this lands, as a temporary fix you could try wrapping your video player in [RotatedBox](https://api.flutter.dev/flutter/widgets/RotatedBox-class.html), wouldn't that work?

It doesn't work because We don't know the rotation of the video. My project is using the camera plugin and take a video only in landscape. It work well with landscape left video but not with landscape right

**Comment by sunilguptasg** [comment]
Hi, I can confirm that this issue persists even on the latest build (0.9.4+16). With an Android tablet in landscape mode I observe this (same tab in Portrait works just fine):

1. record video
2. preview with video_payer (is fine)
3. save to a CDN (I use bunny.net)
4. playback from CDN
5. video is 180 flipped

on the web (default is set to landscape) there is no issue... as a side, on the web I use the browsers inbuilt player and the preview is flipped horizontally.

**Comment by acquytrenthienduong** [comment]
i have the same issue when using videoplayer with src by s3 (some file is oke but some file rotate 180).
i try to download all file to my PC and it's still ok. it's only wrong when showing on android phone

**Comment by acquytrenthienduong** [comment]
any update for dislay file recording by landscapeRight on android?

**Comment by cvphat4796** [comment]
@KyleFin , Please see the review from Flutter team in [#4634](https://github.com/flutter/plugins/pull/4634). I really really need it.

**Comment by phanvankhai98** [comment]
> @KyleFin , Please see the review from Flutter team in [#4634](https://github.com/flutter/plugins/pull/4634). I really really need it.
fix work around it with code below, hope it work for u
`return Transform.rotate(
      angle:
          Platform.isIOS || (_controller?.value.aspectRatio ?? 0) < 1 ? 0 : pi,
      child: Positioned(
          child: Align(
              alignment: Alignment.center,
              child: Container(
                  width: Get.width,
                  child: AspectRatio(
                    aspectRatio: _controller!.value.aspectRatio,
                    child: Stack(
                      children: <Widget>[
                        VideoPlayer(_controller!),
                      ],
                    ),
                  )))),
    );`

**Comment by KyleFin** [comment]
> @KyleFin , Please see the review from Flutter team in [#4634](https://github.com/flutter/plugins/pull/4634). I really really need it.

@cvphat4796 I've addressed the review comments. Hopefully that gets merged soon and I'll plan to finalize https://github.com/flutter/plugins/pull/3820#pullrequestreview-835892052 💙

**Comment by sunilguptasg** [comment]
Hi, just to restate - my videos are flipped vertically. The top is down. This may not be the same as the flipped 180 degree of the other comments here. This happens on android when the device is in landscape mode.

**Comment by phanvankhaicd** [comment]
Any update

**Comment by sunilguptasg** [comment]
I have not tried this, but I will: https://roszkowski.dev/2020/rotate-image-from-camera-in-flutter/

**Comment by Zhenhau1** [comment]
Any update? I really need this

**Comment by KyleFin** [comment]
This should be fixed now that https://github.com/flutter/plugins/pull/3820 is merged!

**Comment by maheshmnj** [comment]
Closing since the related PR has been merged https://github.com/flutter/plugins/pull/3820
