### ISSUE TITLE
Gtk Keyboard mapping thinks Num Lock is on when it isn't.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#60922]
I think there's some oddness in the modifier detection for Gtk.  When I run [this code](https://dartpad.dartlang.org/571fe1daed69359b62ea1d889a16dcda) code as a Linux app, it doesn't detect the tab key for moving the focus because it thinks that the Num Lock is also down all the time.  The key event `state` is 0x10 (16), which does imply that the Num Lock is down, but it is not enabled on my keyboard (and I've tried pressing to to see if it's just "stuck").  My `xmodmap` is pretty normal: I don't map anything to something weird (although we should probably handle that properly in any case).

```
xmodmap:  up to 4 keys per modifier, (keycodes in parentheses):

shift       Shift_L (0x32),  Shift_R (0x3e)
lock        Caps_Lock (0x42)
control     Control_L (0x25),  Control_R (0x69)
mod1        Alt_L (0x40),  Alt_R (0x6c),  Meta_L (0xcd)
mod2        Num_Lock (0x4d)
mod3      
mod4        Super_L (0x85),  Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf)
mod5        ISO_Level3_Shift (0x5c),  Mode_switch (0xcb)
```

It always reports that the Num Lock is down, whether is it enabled or not, or whether the key is currently pressed or not.

**Comment by gspencergoog** [comment]
I also tried using xvkbd (a virtual keyboard), and got the same behavior, so it's not a hardware thing.

**Comment by robert-ancell** [comment]
I'm getting the issue that having num lock or caps lock on stops tab from working.

**Comment by HidenoriMatsubayashi** [comment]
FYI.

I use the real keyboard. The following is the log when the Caps lock key is pressed.
(No problem with macos.)

![image](https://user-images.githubusercontent.com/62131389/88992430-5a8ea980-d31e-11ea-9e2a-12e98966852b.png)

```
flutter: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a platform message callback:
flutter: 'package:flutter/src/widgets/shortcuts.dart': Failed assertion: line 77 pos 16: 'keys.isNotEmpty':
flutter: is not true.
flutter: 
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #2      new KeySet.fromSet (package:flutter/src/widgets/shortcuts.dart:77:16)
flutter: #3      new _LogicalKeySet&KeySet&Diagnosticable.fromSet (package:flutter/src/widgets/shortcuts.dart)
flutter: #4      new LogicalKeySet.fromSet (package:flutter/src/widgets/shortcuts.dart:181:63)
flutter: #5      ShortcutManager.handleKeypress (package:flutter/src/widgets/shortcuts.dart:309:63)
flutter: #6      _ShortcutsState._handleOnKey (package:flutter/src/widgets/shortcuts.dart:472:20)
flutter: #7      FocusManager._handleRawKeyEvent (package:flutter/src/widgets/focus_manager.dart:1625:43)
flutter: #8      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:598:68)
flutter: #9      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76:49)
flutter: #10     _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:284:33)
flutter: #11     _invoke3.<anonymous closure> (dart:ui/hooks.dart:282:15)
flutter: #15     _invoke3 (dart:ui/hooks.dart:281:10)
flutter: #16     _dispatchPlatformMessage (dart:ui/hooks.dart:156:5)
flutter: (elided 5 frames from class _AssertionError and dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: 'package:flutter/src/widgets/shortcuts.dart': Failed assertion: line 77 pos 16: 'keys.isNotEmpty': is not true.
```

**Comment by gspencergoog** [comment]
@HidenoriMatsubayashi That looks like a separate problem (it looks like the Gtk implementation isn't mapping the Caps Lock key correctly). Can you please file a separate issue for that?

**Comment by gspencergoog** [comment]
Note that this causes pretty much all keyboard shortcuts to stop working on Linux.

**Comment by HidenoriMatsubayashi** [comment]
@gspencergoog 

>  Can you please file a separate issue for that?

I'm sorry for late reply. OK.

**Comment by gspencergoog** [comment]
Some more investigation here reveals that, at least for my keyboard and linux setup, pressing the numlock doesn't actually produce any key events at all in x11 (xev doesn't report any event, at least). The corresponding keys on the keyboard change meaning (they give numbers instead of letters), but no key event reaches the x event system.  This would be fine, except that x11 seems to think that the numlock key is ALWAYS down. I.e. every key event has a gdk_keymap_get_num_lock_state() result of `true`, and the state bitfield always has GDK_MOD2_MASK set. The keyboard does have an embedded keypad (meaning that 10 arbitrary keys on the keyboard become the number pad instead of producing their regular codes).

My suspicion was that the keyboard (Goldtouch SK-2720), was handling the NumLock itself, and just sending out different values when it is toggled on, but I tested three other keyboards of various makes/models, and they all produce key events with the state set to 0x10 (GDK_MOD2_MASK is 0x10). I didn't try rebooting my machine with a different keyboard attached, that's next (and checking the BIOS settings on my computer).

I have no idea how to fix this.  We can't just turn off the GDK_MOD2_MASK on all keyboards, because some of them probably report it properly.

**Comment by mivoligo** [comment]
Is there any easy way I can help with testing the issue? I use a laptop with build in keyboard.

**Comment by gspencergoog** [comment]
OK, after rebooting a couple of times and changing some BIOS settings, I can say that it doesn't have to do with the keyboard type.  I turned off the "Num lock on at startup" setting in my BIOS, which had no effect (I didn't think it would, but you never know!), and I tried rebooting with an Apple keyboard attached instead, and in both cases, all events have the state "0x10" attached to them (GDK_MOD2_MASK set).

**Comment by gspencergoog** [comment]
@mivoligo If you can run `xev -event keyboard` on your machine and tell me what the value of "state" is when you press a key and it prints the event in the terminal where you started `xev`, that might give us some more information.  I suspect yours will say "0x0" if it is "normal", and "0x10" if it's broken like mine.

**Comment by mivoligo** [comment]
OK. So after running `xev -event keyboard` a small window with a title 'Event Tester' showed up. I guess I should press a buttons when that window is in focus, right? If yes, then 'state' is:
- 0x12 when CapsLock is on and NumLock is on,  
- 0x10 when CapsLock is off and NumLock is on,
- 0x0 when CapsLock is off and NumLock is off,
- 0x2 when CapsLock is on and NumLock is off.

Or should I run this when I run a Flutter app? Please let me know. I have to finish for now but I'll be happy to test tomorrow.

**Comment by gspencergoog** [comment]
@mivoligo No, that's all I needed to know, except maybe what type of keyboard is it? I know it's a laptop, but does it happen to have a separate number pad or not (some huge laptops do!).

**Comment by mivoligo** [comment]
@gspencergoog Yes, It has a separate number pad.

**Comment by gspencergoog** [comment]
OK, some more observations.  I think that Flutter is missing a concept in our key handling: we don't make a distinction between a lock key (NumLock, ShiftLock, or ScrollLock) being currently pressed, and the "lock" state being on/off.

On GTK, the modifier is turned "on" if the lock state is on, regardless of whether the key is down or not, and Flutter doesn't like that much.  I think Flutter should keep its current behavior with respect to key presses (and we should fix the GTK implementation to only set it when the key is actually down), and add some API to ask if a lock state is currently enabled (and we should implement that on all platforms). (This might be hard to implement on macOS, where the lock keys are don't send one of the key press events, key up, I think?).

I also suspect that Linux sets NumLock on permanently when a keyboard doesn't have a separate number pad, at least for the keyboards I was able to test.

**Comment by mivoligo** [comment]
I've done one extra test. I've set the layout to English as usually I use Polish. When I used English I got similar results for 'state' but with '20' at the beginning. So instead of 0x0 I had 0x2000, 0x2 -> 0x2002, 0x10 -> 0x2010, 0x12 -> 0x2012

**Comment by gspencergoog** [comment]
Thanks! The 0x2000 is a reserved code (GDK_MODIFIER_RESERVED_13_MASK), which GTK is probably using to indicate that the keyboard is not using a native layout (or something), so it probably doesn't matter for this case.

**Comment by mivoligo** [comment]
Hi @gspencergoog,
Is this change already in Flutter master? I've switched few minutes ago from devel to master to test keyboard navigation. Unfortunately it still doesn't work for me.

**Comment by gspencergoog** [comment]
No, it's not quite part of master yet.  Should happen sometime today, I would think.

**Comment by mivoligo** [comment]
@gspencergoog thanks :+1:

**Comment by mivoligo** [comment]
@gspencergoog, I've just did `flutter upgrade` and the keyboard navigation works as it should. Many thanks for your work :heart_eyes:
