### ISSUE TITLE
Can't `pub publish` with version of dart-sdk in Flutter master

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#61747]
The current version of flutter `master` contains a version of `pub` that is not able to publish packages. It fails with the following error:

**Invalid argument(s) (sdkPath): Must not be null**

See [this issue](https://github.com/dart-lang/pub/issues/2563) for more details.

This seems to be [breaking CI in the `flutter/plugins` repo](https://github.com/flutter/plugins/pulls) already (see the `publishable` checks on the latest PRs).

## Steps to Reproduce

1. Go to flutter master channel
2. Ensure you're using the dart-sdk coming from flutter
3. `pub publish --dry-run` on any package

## Logs

```
$ which pub
/usr/local/google/home/dit/github/flutter/bin/cache/dart-sdk/bin/pub
```

pub error:

```
$ pub publish --dry-run
Publishing extension_google_sign_in_as_googleapis_auth 1.0.0 to https://pub.dartlang.org:
|-- .gitignore
...
|-- pubspec.yaml
'-- test
    '-- extension_google_sign_in_as_googleapis_auth_test.dart
Invalid argument(s) (sdkPath): Must not be null
dart:core                                                      ArgumentError.checkNotNull
package:analyzer/src/dart/analysis/context_builder.dart 49:19  ContextBuilderImpl.createContext
package:pub/src/dart.dart 115:36                               AnalysisContextManager.createContextsForDirectory
package:pub/src/validator/strict_dependencies.dart 27:28       new StrictDependenciesValidator
package:pub/src/validator.dart 135:7                           Validator.runAll
package:pub/src/command/lish.dart 165:21                       LishCommand._validate
package:pub/src/command/lish.dart 141:15                       LishCommand.run
package:args/command_runner.dart 197:27                        CommandRunner.runCommand
package:pub/src/command_runner.dart 193:39                     PubCommandRunner.runCommand.<fn>
dart:async                                                     new Future.sync
package:pub/src/utils.dart 113:12                              captureErrors.wrappedCallback
dart:async                                                     runZoned
package:pub/src/utils.dart 130:5                               captureErrors
package:pub/src/command_runner.dart 193:13                     PubCommandRunner.runCommand
This is an unexpected error. Please run

    pub --trace publish --dry-run

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

```

doctor:

```
$ flutter doctor -v

[✓] Flutter (Channel master, 1.21.0-2.0.pre.55, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-2.0.pre.55 at /usr/local/google/home/dit/github/flutter
    • Framework revision 1840b7121a (11 hours ago), 2020-07-16 23:15:23 -0700
    • Engine revision d3b81f19fc
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 06183779d7)
```

(Labeling as P0 to prevent this from going to `dev`, which is not exhibiting the issue yet!)

**Comment by ditman** [comment]
Bisected (issue reproduced by running `flutter clean && pub publish --dry-run` on some random pkg and observing the pub output):

<details>
<summary><tt>git bisect</tt> log</summary>

```
$ git bisect start
$ git bisect bad master
$ git bisect good f25bd9c55c
Bisecting: 29 revisions left to test after this (roughly 5 steps)
[d90a24646122fc2ab4f44b6751540c6f88fabca2] Corrected splash color for TextButton, ElevatedButton, OutlinedButton (#61576)
$ git bisect bad
Bisecting: 14 revisions left to test after this (roughly 4 steps)
[3631adc99aa11dfb9f052e28389c68bb97053524] Fixing patch for coming breaking change in HttpClientRequest (#61138)
$ git bisect bad
Bisecting: 7 revisions left to test after this (roughly 3 steps)
[6f56ba453d476a13ccd5f7dbb71db682861aa1a1] Automatically scale down Dialog padding for larger text scale factors (#58245)
$ git bisect bad
Bisecting: 3 revisions left to test after this (roughly 2 steps)
[f95f46e91052f23b945671cc918bd523caa4898e] Roll Engine from 99c2b3a24555 to be7595bafb14 (2 revisions) (#61504)
$ git bisect good
Bisecting: 1 revision left to test after this (roughly 1 step)
[26a5f5c3d6b5b3a5ce59bdf43eac356d6da83b79] [ListTileTheme] adds properties to customize tile color at theme level (#61532)
$ git bisect bad
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[d7933fadfde3a327c5d4a7d70a17bbdee54fee95] Roll Engine from be7595bafb14 to 7b1515ed292a (5 revisions) (#61515)
$ git bisect bad
```

</details>

```
d7933fadfde3a327c5d4a7d70a17bbdee54fee95 is the first bad commit
commit d7933fadfde3a327c5d4a7d70a17bbdee54fee95
Author: engine-flutter-autoroll <engine-flutter-autoroll@skia.org>
Date:   Wed Jul 15 08:41:03 2020 -0400

    Roll Engine from be7595bafb14 to 7b1515ed292a (5 revisions) (#61515)

 bin/internal/engine.version | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

**Comment by zanderso** [comment]
It looks like this has been fixed upstream, and rolled into the Dart SDK here: https://github.com/dart-lang/sdk/commit/ad3be0ab96c8a790015d82e0bf703122d6423a04. Flutter will pick up the fix in the usual roll process, so I'll go ahead and close this.

**Comment by ditman** [comment]
I'd keep this reopen, so we don't roll a bad version of `flutter master` to `dev`.

I'm keeping an eye into the engine roller, I'll close this when the roll from the engine happens (I've just verified the latest engine works)

**Comment by zanderso** [comment]
sg. thanks!

**Comment by ditman** [comment]
The engine roller has picked the fix, here: https://github.com/flutter/flutter/pull/61880 

This is the one:

```
2020-07-20 skia-flutter-autoroll@skia.org Roll Dart SDK from bf814cfe61b9 to 0de2455c02a5 (6 revisions) (flutter/engine#19885)
```

**Comment by ditman** [comment]
Engine rolls to flutter are failing, the fix is still not available in master.

**Comment by zanderso** [comment]
The Dart -> Engine roll here: https://github.com/flutter/engine/pull/19885 includes the fix, and was included in the engine -> framework roll here: https://github.com/flutter/flutter/pull/61944.

**Comment by ditman** [comment]
Thanks @zanderso! I just verified this now works in the latest version of flutter master!

**Comment by zanderso** [comment]
The roll was reverted.

**Comment by kf6gpe** [comment]
Since this was (temporarily) fixed by a revert, I'm leaving this open as an issue, but downgrading the priority.

**Comment by ditman** [comment]
(This seems to be fixed in the tip of `master` as of right now.)

**Comment by zanderso** [comment]
Yup, the engine roll re-landed. Closing.
