### ISSUE TITLE
[webview]Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference

### ISSUE THREAD

**Issue by Mauiie** [flutter/flutter#62022]
## When I use two pages containing webview_flutter, as long as I open the second page and return to the first page, the input box in the first page cannot be used normally.
It will cause the app to crash or not be able to input.
this issue is same with #58299

You  can use  follow code in webview_flutter example.  do with follows:
1. After first page loaded.
2. go next webPage by Menu.
3. back to first page , try input something.

**Expected results:** 
Can input content normally

**Actual results:** 
It will cause the app to crash or not be able to input.

<details>
  <summary>code</summary>

```
import 'dart:async';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(
    ColorFiltered(colorFilter: ColorFilter.mode(Colors.grey, BlendMode.color), child: MaterialApp(home: WebViewExample())));

class WebViewExample extends StatefulWidget {
  @override
  _WebViewExampleState createState() => _WebViewExampleState();
}

class _WebViewExampleState extends State<WebViewExample> {
  final Completer<WebViewController> _controller = Completer<WebViewController>();

//String initialUrl = 'https://github.com/flutter/flutter/issues/58229';
  String initialUrl = 'https://github.com/login';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter WebView example'),
        actions: <Widget>[SampleMenu(_controller.future)],
      ),
      body: Builder(builder: (BuildContext context) {
        return WebView(
          initialUrl: initialUrl,
          javascriptMode: JavascriptMode.unrestricted,
          onWebViewCreated: (WebViewController webViewController) {
            _controller.complete(webViewController);
          },
          gestureNavigationEnabled: true,
          debuggingEnabled: false,
//          disableInputProxy: true,
          gestureRecognizers:
              Platform.isAndroid ? (Set()..add(Factory<EagerGestureRecognizer>(() => EagerGestureRecognizer()))) : null,
          initialMediaPlaybackPolicy: AutoMediaPlaybackPolicy.always_allow,
        );
      }),
    );
  }
}

enum MenuOptions { goWebPage }

class SampleMenu extends StatelessWidget {
  SampleMenu(this.controller);

  final Future<WebViewController> controller;
  final CookieManager cookieManager = CookieManager();

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<WebViewController>(
      future: controller,
      builder: (BuildContext context, AsyncSnapshot<WebViewController> controller) {
        return PopupMenuButton<MenuOptions>(
          onSelected: (MenuOptions value) {
            switch (value) {
              case MenuOptions.goWebPage:
                _goFlutterPage(context);
                break;
            }
          },
          itemBuilder: (BuildContext context) => <PopupMenuItem<MenuOptions>>[
            const PopupMenuItem<MenuOptions>(
              value: MenuOptions.goWebPage,
              child: Text('go next webPage'),
            )
          ],
        );
      },
    );
  }

  void _goFlutterPage(BuildContext context) async {
    Navigator.push(context, MaterialPageRoute(builder: (context) => WebPage()));
  }
}
class WebPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomPadding: false,
      resizeToAvoidBottomInset: false,
      appBar: AppBar(
        title: Text("Flutter page"),
      ),
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            Text(
              "When  you  input someThing Android  back to First Page,  First Page can not show Thew Keyboard",
              style: TextStyle(color: Colors.red),
            ),
            SizedBox(height: 30),
            Container(
              height: 500,
              child: WebView(
                initialUrl: "https://github.com/login",
                javascriptMode: JavascriptMode.unrestricted,
                gestureNavigationEnabled: true,
                debuggingEnabled: false,
//                disableInputProxy: true,
                gestureRecognizers:
                    Platform.isAndroid ? (Set()..add(Factory<EagerGestureRecognizer>(() => EagerGestureRecognizer()))) : null,
                initialMediaPlaybackPolicy: AutoMediaPlaybackPolicy.always_allow,
              ),
            )
          ],
        ),
      ),
    );
  }
}

```

</details>

#### The disableInputProxy property in the code is my extension to remove the Input Proxy so that the app will not crash but cannot be input. 

<details>
<summary>The key code about disableInputProxy is in InputAwareWebView:</summary>

```
private void setInputConnectionTarget(final View targetView) {
        if (containerView == null) {
            Log.e(TAG, "Can't set the input connection target because there is no containerView to use as a handler.");
            return;
        }
        targetView.requestFocus();
        
        if (disableInputProxy) {
            return;
        }
        containerView.post(new Runnable() {
                    @Override
                    public void run() {
                        try {
                            InputMethodManager imm = (InputMethodManager) getContext().getSystemService(INPUT_METHOD_SERVICE);
                            targetView.onWindowFocusChanged(true);
                            imm.isActive(containerView);
                        } catch (Exception e) {
                            System.out.println("---->>>>>>   " + e.getMessage());
                        }
                    }
                });
    }
```

</details>

<details>
  <summary>Log without disableInputProxy</summary>

```
I/flutter (27181): https://github.com/login loaded
E/chromium(27181): [ERROR:ssl_client_socket_impl.cc(941)] handshake failed; returned -1, SSL error code 1, net_error -100
I/AwareBitmapCacher(27181): init lrucache size: 2097152 pid=27181
I/Hwaps   (27181): APS: EventAnalyzed: initAPS: version is 10.1.0.18
D/Hwaps   (27181): Fpsrequest create,type:EXACTLY_IDENTIFY
I/hwaps   (27181): HwAps: JNI_OnLoad
D/Hwaps   (27181): Fpsrequest create,type:EXACTLY_IDENTIFY
D/Hwaps   (27181): Fpsrequest create,type:OPENGL_SETTING
D/Hwaps   (27181): FpsController create
D/Hwaps   (27181): APS: EventAnalyzed: reInitFpsPara :mBaseFps = 60; mMaxFps = 60
W/Settings(27181): Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
V/HiTouch_HiTouchSensor(27181): User setup is finished.
W/HwApsManager(27181): HwApsManagerService, registerCallback, start !
D/Hwaps   (27181): APS: EventAnalyzed: registerCallbackInApsManagerService, mPkgName:io.flutter.plugins.webviewflutterexample; result = true
E/InputMethodManager(27181): b/117267690: Failed to get fallback IMM with expected displayId=272 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b1e2ff0 VFED..C.. .F...... 0,0-1080,1971}
I/InputMethodManager(27181): showSoftInput
I/AssistStructure(27181): Flattened final assist data: 308 bytes, containing 1 windows, 1 views
W/InputMethodManager(27181): startInputReason = 3
E/InputMethodManager(27181): b/117267690: Failed to get fallback IMM with expected displayId=272 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b1e2ff0 VFED..C.. ......ID 0,0-1080,1971}
E/InputMethodManager(27181): b/117267690: Failed to get fallback IMM with expected displayId=272 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b1e2ff0 VFED..C.. ......ID 0,0-1080,1971}
W/InputMethodManager(27181): startInputReason = 3
I/DecorView[](27181):  old windowMode:0 new windoMode:1
W/libEGL  (27181): EGLNativeWindowType 0x72f845d810 disconnect failed
I/HiTouch_HiTouchSensor(27181): HiTouch restricted: Sub windows restricted.
D/HiTouch_PressGestureDetector(27181): onAttached, package=io.flutter.plugins.webviewflutterexample, windowType=2037, mHiTouchRestricted=true
D/mali_winsys(27181): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
E/InputMethodManager(27181): b/117267690: Failed to get fallback IMM with expected displayId=273 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b1e2ff0 VFED..C.. .F...... 0,0-1080,1136}
W/InputMethodManager(27181): startInputReason = 3
W/IInputConnectionWrapper(27181): getTextAfterCursor on inactive InputConnection
D/OpenGLRenderer(27181): disableOutlineDraw is true
V/AudioManager(27181): querySoundEffectsEnabled...
W/InputMethodManager(27181): startInputReason = 3
E/InputMethodManager(27181): b/117267690: Failed to get fallback IMM with expected displayId=273 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b1e2ff0 VFED..C.. ........ 0,0-1080,1136}
E/InputMethodManager(27181): b/117267690: Failed to get fallback IMM with expected displayId=273 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b1e2ff0 VFED..C.. ........ 0,0-1080,1136}
W/InputMethodManager(27181): startInputReason = 3
I/DecorView[](27181):  old windowMode:0 new windoMode:1
W/libEGL  (27181): EGLNativeWindowType 0x72f845d810 disconnect failed
I/HiTouch_HiTouchSensor(27181): HiTouch restricted: Sub windows restricted.
D/HiTouch_PressGestureDetector(27181): onAttached, package=io.flutter.plugins.webviewflutterexample, windowType=2037, mHiTouchRestricted=true
D/mali_winsys(27181): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer(27181): disableOutlineDraw is true
V/AudioManager(27181): querySoundEffectsEnabled...
V/AudioManager(27181): querySoundEffectsEnabled...
I/DecorView[](27181):  old windowMode:0 new windoMode:1
I/HiTouch_HiTouchSensor(27181): HiTouch restricted: Sub windows restricted.
D/HiTouch_PressGestureDetector(27181): onAttached, package=io.flutter.plugins.webviewflutterexample, windowType=2030, mHiTouchRestricted=true
D/mali_winsys(27181): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
I/System.out(27181): ---->>>>>>   Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference
D/OpenGLRenderer(27181): disableOutlineDraw is true
E/InputMethodManager(27181): b/117267690: Failed to get fallback IMM with expected displayId=275 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{5fd4cb0 VFED..C.. ........ 0,0-1080,1500}
W/System.err(27181): java.lang.NullPointerException: Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference
W/System.err(27181): 	at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1668)
W/System.err(27181): 	at android.view.inputmethod.InputMethodManager.restartInput(InputMethodManager.java:1637)
W/System.err(27181): 	at org.chromium.content.browser.input.ImeAdapterImpl.s(PG:4)
W/System.err(27181): 	at org.chromium.content.browser.input.ImeAdapterImpl.updateState(PG:28)
W/System.err(27181): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(27181): 	at android.os.MessageQueue.next(MessageQueue.java:363)
W/System.err(27181): 	at android.os.Looper.loop(Looper.java:176)
W/System.err(27181): 	at android.app.ActivityThread.main(ActivityThread.java:8347)
W/System.err(27181): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(27181): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
W/System.err(27181): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
F/chromium(27181): [FATAL:jni_android.cc(249)] Please include Java exception stack in crash report
E/chromium(27181): [ERROR:ssl_client_socket_impl.cc(941)] handshake failed; returned -1, SSL error code 1, net_error -100
F/libc    (27181): Fatal signal 5 (SIGTRAP), code -6 (SI_TKILL) in tid 27181 (wflutterexample), pid 27181 (wflutterexample)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'HUAWEI/ELE-AL00/HWELE:10/HUAWEIELE-AL00/10.1.0.160C00:user/release-keys'
Revision: '0'
ABI: 'arm64'
SYSVMTYPE: Maple
APPVMTYPE: Art
Timestamp: 2020-07-22 17:08:57+0800
pid: 27181, tid: 27181, name: wflutterexample  >>> io.flutter.plugins.webviewflutterexample <<<
uid: 10642
signal 5 (SIGTRAP), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:jni_android.cc(249)] Please include Java exception stack in crash report
'
    x0  0000000000000000  x1  0000000000000081  x2  000000007fffffff  x3  0000000000000000
    x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  7f7f7f7f7f7f7f7f
    x8  0000000000000000  x9  0000000000000000  x10 0000000000000001  x11 0000000000000000
    x12 00000072a85d4020  x13 ffffffffffffffff  x14 0000000000000004  x15 ffffffffffffffff
    x16 00000073e6774a40  x17 00000073e6705ae0  x18 00000073e9df6000  x19 0000007fc12c6970
    x20 0000007fc12c6978  x21 0000007fc12c6980  x22 000000000000004f  x23 00000073e676f508
    x24 00000073092fa000  x25 00000073e92fe020  x26 0000000000000000  x27 0000007fc12c64c0
    x28 0000000000000000  x29 0000007fc12c6910
    sp  0000007fc12c64b0  lr  0000007306e070f4  pc  0000007306e072dc
backtrace:
      #00 pc 00000000017db2dc  /system/product/app/WebViewGoogle/WebViewGoogle.apk!libmonochrome.so (offset 0x15b000) (BuildId: 91f66442222b8f8666fc861062cac07a47eac7b6)
Lost connection to device.

```

</details>

<details>

  <summary>Log with disableInputProxy</summary>

```
I/flutter (27826): https://github.com/login loaded
E/chromium(27826): [ERROR:ssl_client_socket_impl.cc(941)] handshake failed; returned -1, SSL error code 1, net_error -100
I/AwareBitmapCacher(27826): init lrucache size: 2097152 pid=27826
I/Hwaps   (27826): APS: EventAnalyzed: initAPS: version is 10.1.0.18
D/Hwaps   (27826): Fpsrequest create,type:EXACTLY_IDENTIFY
I/hwaps   (27826): HwAps: JNI_OnLoad
D/Hwaps   (27826): Fpsrequest create,type:EXACTLY_IDENTIFY
D/Hwaps   (27826): Fpsrequest create,type:OPENGL_SETTING
D/Hwaps   (27826): FpsController create
D/Hwaps   (27826): APS: EventAnalyzed: reInitFpsPara :mBaseFps = 60; mMaxFps = 60
W/Settings(27826): Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
V/HiTouch_HiTouchSensor(27826): User setup is finished.
W/HwApsManager(27826): HwApsManagerService, registerCallback, start !
D/Hwaps   (27826): APS: EventAnalyzed: registerCallbackInApsManagerService, mPkgName:io.flutter.plugins.webviewflutterexample; result = true
W/InputMethodManager(27826): startInputReason = 3
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=276 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. .F...... 0,0-1080,1971}
I/InputMethodManager(27826): showSoftInput
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=276 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. .F...... 0,0-1080,1971}
I/AssistStructure(27826): Flattened final assist data: 308 bytes, containing 1 windows, 1 views
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=276 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. ......ID 0,0-1080,1971}
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=276 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. ......ID 0,0-1080,1971}
W/InputMethodManager(27826): startInputReason = 3
I/DecorView[](27826):  old windowMode:0 new windoMode:1
W/libEGL  (27826): EGLNativeWindowType 0x72f84cee10 disconnect failed
I/HiTouch_HiTouchSensor(27826): HiTouch restricted: Sub windows restricted.
D/HiTouch_PressGestureDetector(27826): onAttached, package=io.flutter.plugins.webviewflutterexample, windowType=2037, mHiTouchRestricted=true
D/mali_winsys(27826): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=277 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. .F...... 0,0-1080,1136}
W/InputMethodManager(27826): startInputReason = 3
W/IInputConnectionWrapper(27826): getTextAfterCursor on inactive InputConnection
D/OpenGLRenderer(27826): disableOutlineDraw is true
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=277 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. .F...... 0,0-1080,1136}
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=277 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. .F...... 0,0-1080,1136}
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=277 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. .F...... 0,0-1080,1136}
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=277 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. .F...... 0,0-1080,1136}
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=277 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. .F...... 0,0-1080,1136}
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=277 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. .F...... 0,0-1080,1136}
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=277 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. .F...... 0,0-1080,1136}
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=277 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. .F...... 0,0-1080,1136}
V/AudioManager(27826): querySoundEffectsEnabled...
V/AudioManager(27826): querySoundEffectsEnabled...
I/DecorView[](27826):  old windowMode:0 new windoMode:1
I/HiTouch_HiTouchSensor(27826): HiTouch restricted: Sub windows restricted.
D/HiTouch_PressGestureDetector(27826): onAttached, package=io.flutter.plugins.webviewflutterexample, windowType=2030, mHiTouchRestricted=true
D/mali_winsys(27826): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer(27826): disableOutlineDraw is true
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=278 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{f6a85fe VFED..C.. ........ 0,0-1080,1500}
W/InputMethodManager(27826): startInputReason = 3
E/chromium(27826): [ERROR:ssl_client_socket_impl.cc(941)] handshake failed; returned -1, SSL error code 1, net_error -100
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=277 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. ........ 0,0-1080,1136}
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=277 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. ........ 0,0-1080,1136}
I/DecorView[](27826):  old windowMode:0 new windoMode:1
W/libEGL  (27826): EGLNativeWindowType 0x72f84cee10 disconnect failed
I/HiTouch_HiTouchSensor(27826): HiTouch restricted: Sub windows restricted.
D/HiTouch_PressGestureDetector(27826): onAttached, package=io.flutter.plugins.webviewflutterexample, windowType=2037, mHiTouchRestricted=true
D/mali_winsys(27826): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer(27826): disableOutlineDraw is true
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=278 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{f6a85fe VFED..C.. .F....ID 0,0-1080,1500}
I/InputMethodManager(27826): showSoftInput
W/InputMethodManager(27826): startInputReason = 3
W/IInputConnectionWrapper(27826): getTextBeforeCursor on inactive InputConnection
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=279 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. ........ 0,0-1080,1971}
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=279 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. ........ 0,0-1080,1971}
I/DecorView[](27826):  old windowMode:0 new windoMode:1
W/libEGL  (27826): EGLNativeWindowType 0x72f84cee10 disconnect failed
I/HiTouch_HiTouchSensor(27826): HiTouch restricted: Sub windows restricted.
D/HiTouch_PressGestureDetector(27826): onAttached, package=io.flutter.plugins.webviewflutterexample, windowType=2037, mHiTouchRestricted=true
D/mali_winsys(27826): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer(27826): disableOutlineDraw is true
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=278 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{f6a85fe VFED..C.. .F...... 0,0-1080,1500}
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=278 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{f6a85fe VFED..C.. .F...... 0,0-1080,1500}
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=278 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{f6a85fe VFED..C.. .F...... 0,0-1080,1500}
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=278 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{f6a85fe VFED..C.. .F...... 0,0-1080,1500}
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=278 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{f6a85fe VFED..C.. .F...... 0,0-1080,1500}
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=278 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{f6a85fe VFED..C.. .F...... 0,0-1080,1500}
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=278 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{f6a85fe VFED..C.. .F...... 0,0-1080,1500}
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=278 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{f6a85fe VFED..C.. .F...... 0,0-1080,1500}
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=278 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{f6a85fe VFED..C.. .F...... 0,0-1080,1500}
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=278 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{f6a85fe VFED..C.. .F...... 0,0-1080,1500}
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=280 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. ........ 0,0-1080,1136}
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=280 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. ........ 0,0-1080,1136}
I/DecorView[](27826):  old windowMode:0 new windoMode:1
W/libEGL  (27826): EGLNativeWindowType 0x72f84cee10 disconnect failed
I/HiTouch_HiTouchSensor(27826): HiTouch restricted: Sub windows restricted.
D/HiTouch_PressGestureDetector(27826): onAttached, package=io.flutter.plugins.webviewflutterexample, windowType=2037, mHiTouchRestricted=true
D/mali_winsys(27826): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer(27826): disableOutlineDraw is true
W/InputMethodManager(27826): startInputReason = 3
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=278 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{f6a85fe VFED..C.. ........ 0,0-1080,1500}
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=278 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{f6a85fe VFED..C.. ........ 0,0-1080,1500}
W/libEGL  (27826): EGLNativeWindowType 0x73535b58d0 disconnect failed
E/BufferQueueProducer(27826): [SurfaceTexture-0-27826-1]:399: dequeueBuffer: BufferQueue has been abandoned
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=281 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. .F...... 0,0-1080,1971}
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=281 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. .F...... 0,0-1080,1971}
I/InputMethodManager(27826): showSoftInput
W/InputMethodManager(27826): The current service view is not the focus view
D/OpenGLRenderer(27826): disableOutlineDraw is true
D/mali_winsys(27826): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=281 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. .F...... 0,0-1080,1971}
I/InputMethodManager(27826): showSoftInput
W/InputMethodManager(27826): The current service view is not the focus view
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=281 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. .F...... 0,0-1080,1971}
I/InputMethodManager(27826): showSoftInput
W/InputMethodManager(27826): The current service view is not the focus view
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=281 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. .F...... 0,0-1080,1971}
I/InputMethodManager(27826): showSoftInput
W/InputMethodManager(27826): The current service view is not the focus view
D/TextClassifierService(27826): No configured system TextClassifierService
W/libEGL  (27826): EGLNativeWindowType 0x73535b58d0 disconnect failed
D/TextClassifierService(27826): No configured system TextClassifierService
D/OpenGLRenderer(27826): disableOutlineDraw is true
D/mali_winsys(27826): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/mali_winsys(27826): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer(27826): disableOutlineDraw is true
D/androidtc(27826): Loading ModelFile { path=/data/misc/textclassifier/lang_id.model name=lang_id.model version=0 locales=und }
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=281 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. .F...... 0,0-1080,1971}
I/InputMethodManager(27826): showSoftInput
W/InputMethodManager(27826): The current service view is not the focus view
D/androidtc(27826): Loading ModelFile { path=/data/misc/textclassifier/textclassifier.model name=textclassifier.model version=711 locales=zh }
I/tflite  (27826): Initialized TensorFlow Lite runtime.
W/libEGL  (27826): EGLNativeWindowType 0x73535b58d0 disconnect failed
W/libEGL  (27826): EGLNativeWindowType 0x73535b5a10 disconnect failed
D/OpenGLRenderer(27826): disableOutlineDraw is true
D/mali_winsys(27826): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=281 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. .F...... 0,0-1080,1971}
I/InputMethodManager(27826): showSoftInput
W/InputMethodManager(27826): The current service view is not the focus view
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=281 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. .F...... 0,0-1080,1971}
I/InputMethodManager(27826): showSoftInput
W/InputMethodManager(27826): The current service view is not the focus view
D/TextClassifierService(27826): No configured system TextClassifierService
W/libEGL  (27826): EGLNativeWindowType 0x73535b5a10 disconnect failed
D/TextClassifierService(27826): No configured system TextClassifierService
W/LabeledIntent(27826): resolveInfo or activityInfo is null
D/mali_winsys(27826): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/mali_winsys(27826): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer(27826): disableOutlineDraw is true
D/OpenGLRenderer(27826): disableOutlineDraw is true
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=281 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. .F...... 0,0-1080,1971}
I/InputMethodManager(27826): showSoftInput
W/InputMethodManager(27826): The current service view is not the focus view
W/libEGL  (27826): EGLNativeWindowType 0x73535b5a10 disconnect failed
W/libEGL  (27826): EGLNativeWindowType 0x73535b58d0 disconnect failed
D/mali_winsys(27826): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer(27826): disableOutlineDraw is true
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=281 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. .F...... 0,0-1080,1971}
I/InputMethodManager(27826): showSoftInput
W/InputMethodManager(27826): The current service view is not the focus view
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=281 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. .F...... 0,0-1080,1971}
I/InputMethodManager(27826): showSoftInput
W/InputMethodManager(27826): The current service view is not the focus view
D/TextClassifierService(27826): No configured system TextClassifierService
W/libEGL  (27826): EGLNativeWindowType 0x73535b58d0 disconnect failed
D/TextClassifierService(27826): No configured system TextClassifierService
W/LabeledIntent(27826): resolveInfo or activityInfo is null
D/OpenGLRenderer(27826): disableOutlineDraw is true
D/mali_winsys(27826): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/mali_winsys(27826): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer(27826): disableOutlineDraw is true
D/mali_winsys(27826): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer(27826): disableOutlineDraw is true
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=281 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. .F...... 0,0-1080,1971}
I/InputMethodManager(27826): showSoftInput
W/InputMethodManager(27826): The current service view is not the focus view
W/libEGL  (27826): EGLNativeWindowType 0x73535b58d0 disconnect failed
W/libEGL  (27826): EGLNativeWindowType 0x73535b5a10 disconnect failed
D/OpenGLRenderer(27826): disableOutlineDraw is true
D/mali_winsys(27826): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
W/libEGL  (27826): EGLNativeWindowType 0x72f84cef50 disconnect failed
E/InputMethodManager(27826): b/117267690: Failed to get fallback IMM with expected displayId=281 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{7064cfa VFED..C.. .F...... 0,0-1080,1971}
I/InputMethodManager(27826): showSoftInput
W/InputMethodManager(27826): The current service view is not the focus view

```

</details>

<details>

<summary>flutter doctor -v</summary>

```
wangxindeMacBook-Pro:~ wangxin$ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.1 19B88, locale
    zh-Hans-CN)
    • Flutter version 1.17.4 at /Users/wangxin/Library/flutter/flutter
    • Framework revision 1ad9baa8b9 (5 weeks ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/wangxin/Library/Android/sdk
    • Platform android-30, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.9.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • ELE AL00 • GBGDU19821001370 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 2 categories.
wangxindeMacBook-Pro:~ wangxin$ 
```

</details>

webview_flutter version : 0.3.22+1

**Comment by TahaTesser** [comment]
Hi @Mauiie 
I cannot reproduce your issue on latest `stable` and `dev` channel on Android 10 running on Galaxy M30 on ` webview_flutter: ^0.3.22+1`

<details> 
<summary>Code Sample</summary> 

```
import 'dart:async';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(ColorFiltered(
    colorFilter: ColorFilter.mode(Colors.grey, BlendMode.color),
    child: MaterialApp(home: WebViewExample())));

class WebViewExample extends StatefulWidget {
  @override
  _WebViewExampleState createState() => _WebViewExampleState();
}

class _WebViewExampleState extends State<WebViewExample> {
  final Completer<WebViewController> _controller =
      Completer<WebViewController>();

//String initialUrl = 'https://github.com/flutter/flutter/issues/58229';
  String initialUrl = 'https://github.com/login';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter WebView example'),
        actions: <Widget>[SampleMenu(_controller.future)],
      ),
      body: Builder(builder: (BuildContext context) {
        return WebView(
          initialUrl: initialUrl,
          javascriptMode: JavascriptMode.unrestricted,
          onWebViewCreated: (WebViewController webViewController) {
            _controller.complete(webViewController);
          },
          gestureNavigationEnabled: true,
          debuggingEnabled: false,
//          disableInputProxy: true,
          gestureRecognizers: Platform.isAndroid
              ? (Set()
                ..add(Factory<EagerGestureRecognizer>(
                    () => EagerGestureRecognizer())))
              : null,
          initialMediaPlaybackPolicy: AutoMediaPlaybackPolicy.always_allow,
        );
      }),
    );
  }
}

enum MenuOptions { goWebPage }

class SampleMenu extends StatelessWidget {
  SampleMenu(this.controller);

  final Future<WebViewController> controller;
  final CookieManager cookieManager = CookieManager();

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<WebViewController>(
      future: controller,
      builder:
          (BuildContext context, AsyncSnapshot<WebViewController> controller) {
        return PopupMenuButton<MenuOptions>(
          onSelected: (MenuOptions value) {
            switch (value) {
              case MenuOptions.goWebPage:
                _goFlutterPage(context);
                break;
            }
          },
          itemBuilder: (BuildContext context) => <PopupMenuItem<MenuOptions>>[
            const PopupMenuItem<MenuOptions>(
              value: MenuOptions.goWebPage,
              child: Text('go next webPage'),
            )
          ],
        );
      },
    );
  }

  void _goFlutterPage(BuildContext context) async {
    Navigator.push(context, MaterialPageRoute(builder: (context) => WebPage()));
  }
}

class WebPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomPadding: false,
      resizeToAvoidBottomInset: false,
      appBar: AppBar(
        title: Text("Flutter page"),
      ),
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            Text(
              "When  you  input someThing Android  back to First Page,  First Page can not show Thew Keyboard",
              style: TextStyle(color: Colors.red),
            ),
            SizedBox(height: 30),
            Container(
              height: 500,
              child: WebView(
                initialUrl: "https://github.com/login",
                javascriptMode: JavascriptMode.unrestricted,
                gestureNavigationEnabled: true,
                debuggingEnabled: false,
//                disableInputProxy: true,
                gestureRecognizers: Platform.isAndroid
                    ? (Set()
                      ..add(Factory<EagerGestureRecognizer>(
                          () => EagerGestureRecognizer())))
                    : null,
                initialMediaPlaybackPolicy:
                    AutoMediaPlaybackPolicy.always_allow,
              ),
            )
          ],
        ),
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.17.5 at /Users/taha/Code/flutter_stable
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • SM M305F • 32003c30dc19668f • android-arm64 • Android 10 (API 29)

• No issues found!

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.6 19G73, locale
    en-GB)
    • Flutter version 1.21.0-1.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision f25bd9c55c (7 days ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

 
[✓] Connected device (4 available)            
    • SM M305F (mobile) • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 84.0.4147.89

• No issues found!

```

</details> 

Can you please more details on what devices you experiencing this issue? Can you try another device or emulator to reproduce this issue?

**Comment by Mauiie** [comment]
Sorry  @TahaTesser ,  I modified the code in order to avoid crash when using select.
When  created the InputAwareWebView, the context I passed was Activity, so I can use select normally, but it also caused this problem.
 If you also pass an Activity, I think you should be able to reproduce this problem.

But in https://github.com/flutter/flutter/issues/25767, I noticed that the select problem was fixed in the new version of flutter, so I temporarily restored it.

By the way, there is another problem that bothers me https://github.com/flutter/flutter/issues/61137. I thought that iOS can use ColorFiltered as simple as Android. Now I have to write a lot of code for Avoid the problem that iOS UiKitView cannot be displayed normally.

**Comment by RicardoRB** [comment]
@Mauiie 

It still happens in webview_flutter: 2.0.4
Flutter: 2.0.6

```java
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference
       at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1657)
       at android.view.inputmethod.InputMethodManager.checkFocus(InputMethodManager.java:1926)
       at android.view.inputmethod.InputMethodManager.isActive(InputMethodManager.java:1196)
       at io.flutter.plugins.webviewflutter.InputAwareWebView$1.run(InputAwareWebView.java:26)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7697)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```
