### ISSUE TITLE
Android nav bar appearing after screen tap when only SystemUiOverlay.top is set

### ISSUE THREAD

**Issue by Fleximex** [flutter/flutter#62412]
When calling `SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.top])` in a new Flutter project (in `main()`, `initState()` or `build()`) the Android navigation bar is correctly hidden. However, every (first) tap on the screen, when the navigation bar is hidden, is consumed and the navigation bar appears. When the navigation bar is on screen taps are not consumed, meaning I can interact with widgets.
It however also doesn't hide automatically anymore. If I call `SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.top])` again, i.e. when navigating to a new screen, the navigation bar hides. But now we are in the same starting situation where the first tap in consumed and the navigation bar appears again...
Another small issue is that with `SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom])` the statusbar doesn't auto hide after trigger it to show (swipe on top of screen).

Examples gifs:
<details>
<summary>Only status bar [SystemUiOverlay.top]</summary>
<p></p>

First tap on the Floating Action Button is consumed by... I don't know what. And for some reason the navigation bar appears.
After the navigation bar has appeared the button is tappable and the navigation bar does not auto hide.
<img src="https://thumbs.gfycat.com/BlushingEnchantedAlbertosaurus-small.gif" width="300">
</details>
<details>
<summary>Only navigation bar [SystemUiOverlay.bottom]</summary>
<p></p>

This does work as expected. Up until triggering the status bar to show. It does not auto hide anymore.
<img src="https://thumbs.gfycat.com/DenseTidyAlpineroadguidetigerbeetle-small.gif" width="300">
</details>
<details>
<summary>Hide status and navigation bar []</summary>
<p></p>

This works as expected and after a swipe to trigger either to show, they auto hide.
<img src="https://thumbs.gfycat.com/RegularEssentialGelada-small.gif" width="300">
</details>
<details>
<summary>Flutter Doctor output</summary>

```
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.959], locale en-GB)
    • Flutter version 1.17.5 at C:\flutter
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\*hidden*\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 10 (API 29) (emulator)

• No issues found!
```
</details>

This occurs both on an Android 10 emulator and Android 10 device (Pixel 3a).

Could someone explains this behavior?

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.17.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

 
[✓] Connected device (1 available)            
    • SM M305F • 32003c30dc19668f • android-arm64 • Android 10 (API 29)

• No issues found!
```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision f25bd9c55c (2 weeks ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (4 available)
    • SM M305F (mobile) • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

</details> 

https://github.com/flutter/flutter/issues/28426

**Comment by ossgoossgo** [comment]
Same problem at Flutter 1.22.2

**Comment by eriklange** [comment]
Same problem at 1.23.0-18.1.pre

**Comment by darkwolf66** [comment]
Same issue

**Comment by kashishkhullar** [comment]
Same issue 1.22.4 • channel stable

**Comment by TahaTesser** [comment]
Hi everyone
Please put a thumbs up reaction to OP https://github.com/flutter/flutter/issues/62412#issue-667101935  instead of commenting channel version

**Comment by saveKenny** [comment]
Any news? Don't forget to thumbs up the [question](https://github.com/flutter/flutter/issues/62412#issue-667101935)!!

**Comment by jannikbryld** [comment]
Are there any workarounds available? 
Works perfectly on iOS, but the issue is still present on Android on 1.22.6

**Comment by yom-ko** [comment]
Seconded. Not a showstopper, of course, but a fix would make UX more sensible in certain cases.

**Comment by wailashraf71** [comment]
Any solutions?

**Comment by charlinjoec** [comment]
Facing same problem with flutter 2.0.5

**Comment by flawnn** [comment]
Same issue on [✓] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale de-DE)

here a showcase

https://user-images.githubusercontent.com/19386703/117009803-6ca5da00-acec-11eb-8e26-bf6aaa1c13ad.mp4

**Comment by zenkog** [comment]
Its May 2021. Still facing the same issue?

**Comment by Fleximex** [comment]
Seeing as I opened this issues almost a year ago and there is seemingly zero progress. Can a Flutter developer (@TahaTesser ?) look into this with a higher priority? Maybe the P4 label should change to at least P3. And that's being generous.

The description on the [Issue hygiene page ](https://github.com/flutter/flutter/wiki/Issue-hygiene) that fits this issue in my opinion is the following:
_Similarly, a bug should only be marked `customer: crowd` `P2` if people are threatening to never upgrade to the next release because of this bug._

Hiding either the Android status bar or navigation bar is a very basic feature. And at the moment it is not consistently usable. For example for a phone with a notch you might want to fill the space around the notch with the status bar while hiding the nav bar for a nice full screen experience.

I think, also considering how easy it is to reproduce, this is an issue affecting many people. And inhibits some from building an app or discourages them using the Flutter framework altogether.

**Comment by supermuesli** [comment]
Seconding this.

**Comment by ilkercankaya** [comment]
I have been waiting for this for a long time (around 5 months), I want to hide only the bottom navigation bar to ensure a better UX for my music app. Sad to see that no progress has been made on this, hopefully soon.

**Comment by rahul-chaudhary** [comment]
On flutter 2.3.0 still no fix. 😐

**Comment by marcoazevedo01** [comment]
Same issue 2.3.0   :(

**Comment by Piinks** [comment]
I think this issue has been resolved.  We recently landed new Android fullscreen support (flutter/engine#25785, #81303), which 
- deprecates the old `SystemChrome.setEnabledSystemUIOverlays` in favor of `SystemChrome.setEnabledSystemUIMode`.
- It also introduces `SystemUiMode` each of which describes how gestures are handled and affect the system UI status.
- Lastly, it adds `SystemChrome.setSystemUIChangeCallback`. This allows you to be notified when the fullscreen status changes as a result of user interactions, so you can re-hide the UI or respond in another way. :)

If there is still an issue here, please update the bug, if it is resolved by the latest changes, please close. Thank you!

**Comment by sukaper** [comment]
tried recent changes with `Flutter 2.5.0-1.0.pre • channel dev`  and used `SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: [SystemUiOverlay.top]);` and the problem is, manual mode acts like `SystemUiMode.leanBack` in a sense that bottom navigation bar returns as soon as user presses the screen. I want to have `SystemUiMode.immersiveSticky` mode with only `[SystemUiOverlay.top]` enable. Is this possible?

**Comment by Piinks** [comment]
Hi @sukaper I don't think that this is possible.

According to the Android documentation immersive sticky does not show any overlays (status or navigation bars) https://developer.android.com/training/system-ui/immersive#sticky-immersive, and only presents them when the user swipes from the edge of the screen. 

I also don't think this is possible because sticky immersive requires the `SYSTEM_UI_FLAG_FULLSCREEN` flag to be set and showing the top overlay requires the `SYSTEM_UI_FLAG_FULLSCREEN` _**not**_ be set.

**Comment by subzero911** [comment]
Same problem,
`SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.top]);`
Android bottom nav bar still persists.
Android 11 device and Flutter 2.2.3

**Comment by TahaTesser** [comment]
@subzero911 
`setEnabledSystemUIOverlays` is deprecated, please try `SystemChrome.setEnabledSystemUIMode(SystemUiMode.immersive);` on current `Channel beta, 2.5.0-5.3.pre,` and above
