### ISSUE TITLE
[profiler] Mach thread_info kernel call fails while trying to mach_msg_send. Error MACH_SEND_INVALID_DEST

### ISSUE THREAD

**Issue by awhitford** [flutter/flutter#63025]
## Steps to Reproduce

Since upgrading to **Flutter 1.20.0**, when I `flutter run` my app using the iOS Simulator, I sometimes see 1 or more of this warning:
```
An Observatory debugger and profiler on iPhone 11 Pro Max is available at: http://127.0.0.1:49425/MFzU_2A99ig=/
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
```

**Expected results:** 

I expect no errors.

**Actual results:** 

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 1.20.0, on Mac OS X 10.15.6 19G73, locale en-US)
    • Flutter version 1.20.0 at /Users/anthony/flutter
    • Framework revision 840c9205b3 (19 hours ago), 2020-08-04 20:55:12 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc4)
    • Android SDK at /Users/anthony/Library/Android/sdk
    • Platform android-R, build-tools 30.0.0-rc4
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • iPhone 11 Pro Max (mobile)     • B7F2DF40-38F4-4D13-81B0-D47A17126D4F     • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6
      (simulator)
    • iPad (7th generation) (mobile) • 91CAF267-2193-4752-A4B2-E035A2B3FC87     • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6
      (simulator)

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
hI @awhitford 
not able to reproduce, i have run the flutter multiples on `stable` channel all day
Can you please reproduce it again? please provide your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by Vanson** [comment]
I have the same issue.

flutter channel
Flutter channels:
  master
  dev
  beta
* stable

flutter doctor --verbose
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G73, locale zh-Hans-CN)
    • Flutter version 1.20.1 at /Users/chaijun/Library/flutter
    • Framework revision 2ae34518b8 (31 hours ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/chaijun/Library/Android/sdk
    • Platform android-29, build-tools 30.0.1
    • ANDROID_HOME = /Users/chaijun/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • CFB31139-5963-4154-8B2B-8E9154B88106 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6
      (simulator)

• No issues found!


The issue log is:
[DEBUG]--ADD--PageStack uid/name-->0/PlayerHomePage
2020-08-07 17:27:52.887598+0800 Radio[10463:538495] [VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
2020-08-07 17:28:58.565015+0800 Radio[10463:538495] [VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port

**The issue is show the flutter page is blank.**

**Comment by linhmanh92** [comment]
i have the same issue. How can I fix it?

**Comment by bulgarian-beast** [comment]
I have the same issue this morning I made the flutter upgrade, now the application is running perfectly all synchrone and async functions work perfect but I have this message on terminal : "[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port"

**Comment by bulgarian-beast** [comment]
Oh sorry I apology for my msg, just after writing my previous comments I remember that after the upgrade I dosent restart my computer.
I restart it and now the error msg disappear

**Comment by barboraplasovska** [comment]
I have also the same issue. I tried restarting my computer, the app and rebugging it again, but it didn't disappear. Does anyone has ANY SOLUTION please? Thanks!

**Comment by AurelianTimu** [comment]
have the same issue.

**Comment by devrajraut** [comment]
> Oh sorry I apology for my msg, just after writing my previous comments I remember that after the upgrade I dosent restart my computer.
> I restart it and now the error msg disappear

I have the same issue. But Restarting the System didn't do the trick. Still wonder what error it is?

**Comment by sscast** [comment]
Same issue.

**Comment by hnnhnn** [comment]
I have the same issue.

**Comment by sofferjacob** [comment]
Same, have it since before I upgraded to 1.20.0 when I switched to the beta channel a few weeks ago.

**Comment by abdulrojak288** [comment]
I have the same issue.

**Comment by javyliu** [comment]
I have the same issue since I upgraded to 1.20.0.

**Comment by a7medpa** [comment]
On Channel stable, 1.20.1. Same issue 👎 
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port

**Comment by waretec** [comment]
same issue! 

[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port .

**Comment by jpvanmuijen** [comment]
I had this issue as well, restarting the simulator solved it for me.

**Comment by a7medpa** [comment]
> I had this issue as well, restarting the simulator solved it for me. Restarting my Mac didn't help, because by default it restores all windows including the simulator, which might still be a badly cached version or something.

Fixed it temporarily then came back not sure if the same happened to you.

**Comment by cqllzp** [comment]
I have the same issue since I upgraded to 1.20.0.

**Comment by dasmobile** [comment]
Same issue here since upgrading to 1.20 and 1.20.1:

<img width="1062" alt="Screen Shot 2020-08-11 at 9 41 10 AM" src="https://user-images.githubusercontent.com/27285006/89904447-f211b900-dbb6-11ea-9b12-00da44f59100.png">

However, the app seems to run just fine.

**Comment by ArnoldGihozo** [comment]
> Same issue here since upgrading to 1.20 and 1.20.1:
> 
> <img alt="Screen Shot 2020-08-11 at 9 41 10 AM" width="1062" src="https://user-images.githubusercontent.com/27285006/89904447-f211b900-dbb6-11ea-9b12-00da44f59100.png">
> 
> However, the app seems to run just fine.

same issue as well. The apps runs fine tho

**Comment by real1900** [comment]
restarting simulator worked for me too

**Comment by Vanson** [comment]
> **The issue is show the flutter page is blank.**

I have solved this problem, check the pubspec.yaml,there are blank dir by the  assets.

**Comment by chinmaygarde** [comment]
This should not happen in any of the release modes and should not affect rendering or execution in other modes. It seems like the call to [task_threads](https://github.com/flutter/engine/blob/41971f48c370a6a3e29ff623b2d46008a9a83bf5/shell/platform/darwin/ios/framework/Source/profiler_metrics_ios.mm#L161) is failing. @iskakaushik for thoughts on what to do in case of this failure? Maybe disable the profiling?

**Comment by bossanyit** [comment]
same problem (flutter 1.20.2 on iOS), I have downgraded to 1.17.5 to solve it

**Comment by NateGiraudeau** [comment]
I started having this issue when I upgraded from 1.17 to 1.20. My app gets stuck on the splash screen. It happens on an iOS simulator and a physical device.

**Comment by NateGiraudeau** [comment]
I downgraded to v1.15.5 and I still get the error:
`[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port`

**Comment by ovaldi** [comment]
+1

**Comment by Liight** [comment]
Same Issue!

**Comment by TahaTesser** [comment]
Please thumbs up the original description https://github.com/flutter/flutter/issues/63025#issue-673911573 instead of "same issue" or "met too" comments

**Comment by Peet-A** [comment]
have same issue , any update ?

**Comment by fnicastri** [comment]
The situation is getting worse day by day.
From this morning `flutter clean` is not a solution anymore.
In the end i reverted to flutter 1.17.5

**Comment by kharitonovAL** [comment]
hi everyone! did anyone have troubles with receiving push notifications from FCM accordingly to this issue - `Error retrieving thread information: (ipc/send) invalid destination port`? 
thanks!

**Comment by sofferjacob** [comment]
@kharitonovAL I am having issues receiving notifications. They arrive to the system tray but the handlers aren't called (not even onMessage). It was working fine until the upgrade to the new FlutterFire plugins

**Comment by csacchetti** [comment]
I upgraded to version 1.20.3 but the problem remains.

**Comment by kharitonovAL** [comment]
> @kharitonovAL I am having issues receiving notifications. They arrive to the system tray but the handlers aren't called (not even onMessage). It was working fine until the upgrade to the new FlutterFire plugins

I solved same issue by installing (or running) my app from Xcode. If I'll install from VS Code or Android Studio, it won't work.

**Comment by racknoris** [comment]
Does it affect on the application in production? Anyone had issues other than the error message?

**Comment by Development4A** [comment]
I believe I have the same issue running 1.22.0-10.0.pre.62 on a new app. 
I do not know if this is related to the above error message I am not getting a display on my List.generate until I do a hot reload. After the reload I get the error messages. I am new to this language, so my lack of experience with Flutter may be part of the problem.

Thanks for your help.


[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port


[✓] Flutter (Channel master, 1.22.0-10.0.pre.62, on Mac OS X 10.15.6 19G2021, locale en)
    • Flutter version 1.22.0-10.0.pre.62 at /Users/administrator/Developer/flutter
    • Framework revision 020215bb4c (5 days ago), 2020-09-02 18:35:05 -0700
    • Engine revision 165abef0a2
    • Dart version 2.10.0 (build 2.10.0-77.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/administrator/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (3 available)
    • iPhone SE (2nd generation) (mobile) • 2D27CCAF-0DF0-4A40-9FCB-F8334E1265FC • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • Web Server (web)                    • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome

**Comment by sofferjacob** [comment]
@Development4A it shouldn't be related to this error. My guess would be that you're pulling the data that populates the list asynchronously (like from a db) and not awaiting it or setting the state afterwards. However, I would need more information to confirm it. Since this is probably unrelated to this issue I'd suggest opening a new one where you specify more information.

**Comment by Annelein** [comment]
is there any fix for this issue yet? I'm experiencing the same..

**Comment by viktorgvozdikov** [comment]
i was able to fix the problem

1. I downgraded to v1.17.5 from v1.20
`flutter downgrade v1.17.5`
2. rename folder "ios" to "ios1"
3. next
`flutter create -i swift .`
in result i have new folder "ios" with project
4. `flutter build ios` for install pods
5. set up the ios project again
6. `flutter run` without any problem

**Comment by ZhuBoao** [comment]
I am still having this problem. I don't wanna downgrade my flutter version. 😔

**Comment by DomingoMG** [comment]
I have the same problem with FCM notifications from Firebase Messaging. I wait for a solution please.

` Error retrieving thread information: (ipc/send) invalid destination port`

**Comment by brianschardt** [comment]
Same problem. I am using FCM. Dont want to downgrade

**Comment by jhubbardsf** [comment]
I was getting the same problem on stable but it went away when I switched to the beta channel (1.22.0-12.1.pre). So something in those updates must have fixed it. If anybody else could test that and confirm it goes away after upgrading?

**Comment by DomingoMG** [comment]
It was breaking my mind and since I upgraded flutter to beta mode everything worked as expected.
Hope the next stable update fixes the problem.

**Comment by awhitford** [comment]
(Was something truly _fixed_, or was the message simply _suppressed_?) 🤔

**Comment by DomingoMG** [comment]
@awhitford The message keeps popping up, but my FCM plugins started working.

**Comment by spareblock** [comment]
I still get messages after upgrading from 1.20.0-7.2.pre to 1.22.0-12.1.pre although somewhat less than before...

**Comment by awhitford** [comment]
I am still seeing this after upgrading to Flutter 1.22, running against iPhone simulator.  (Admittedly, this does not seem very serious, but I honestly have no idea.)

**Comment by congfandi** [comment]
i have same issue. xcode 12 simulator 14 and  Flutter (Channel stable, 1.20.4

**Comment by shaishalevss** [comment]
same issue... any solution?

**Comment by nwparker** [comment]
same issue

**Comment by Barry0501** [comment]
Same issue, any update for this issue?

**Comment by TahaTesser** [comment]
Everyone please  instead of writing "same issue" or "me too", add your a 👍  reaction to the OP
Thank you

**Comment by eli-front** [comment]
still an issue in v: 1.22

**Comment by HasithaPriyasad** [comment]
common still not fixed? I cannot run the app.

**Comment by jhubbardsf** [comment]
@HasithaPriyasad 

This issue doesn't prevent the app from running. As far as I can tell it doesn't actually effect the app at all, it's just an annoying error we can't get rid of. Your issue might be something else or closely related. Can you go into some more detail or if you feel it's different enough open another ticket for it?

**Comment by HasithaPriyasad** [comment]
> @HasithaPriyasad
> 
> This issue doesn't prevent the app from running. As far as I can tell it doesn't actually effect the app at all, it's just an annoying error we can't get rid of. Your issue might be something else or closely related. Can you go into some more detail or if you feel it's different enough open another ticket for it?

"error retrieving thread information (ipc/send) invalid destination port"

Hi, I'm getting this error over and over again and the app is only white screen any idea about it?

**Comment by jhubbardsf** [comment]
Without seeing the rest of your code it's a little hard to tell. If you upload it to a repo and link to it I'll check it out for you.

**Comment by FTK09** [comment]
same issue on 1.20 stable version

**Comment by diegoporfirio** [comment]
Same issue

[✓] Flutter (Channel master, 1.23.0-19.0.pre.118, on Mac OS X 10.15.7 19H2 darwin-x64, locale pt-BR)
    • Flutter version 1.23.0-19.0.pre.118 at /Users...
    • Framework revision dd9323bdfb (52 minutes ago), 2020-10-19 15:47:04 -0700
    • Engine revision d03b759d04
    • Dart version 2.11.0 (build 2.11.0-229.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/...
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone 8 (mobile) • 84CE03FB-304D-426B-8DBD-F22E1E644F68 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

**Comment by diegoporfirio** [comment]
FIX issue new flutter version =) :

[✓] Flutter (Channel master, 1.24.0-2.0.pre.86, on Mac OS X 10.15.7 19H2 darwin-x64, locale pt-BR)
    • Flutter version 1.24.0-2.0.pre.86 at /Users/...
    • Framework revision dde20448f7 (7 hours ago), 2020-10-20 00:59:56 -0400
    • Engine revision ea2aea1c61
    • Dart version 2.11.0 (build 2.11.0-234.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/...
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone 7 (mobile) • D1223C47-4747-4E7F-B8CC-C85721F90880 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!
Process finished with exit code 0

**Comment by ylzgit** [comment]
Use this command to solve the problem of white screen

flutter run --enable-software-rendering

**Comment by csacchetti** [comment]
The upgrade to Channel stable, 1.22.2 fix the problem. Great thing.

**Comment by rahulvyas** [comment]
> The upgrade to Channel stable, 1.22.2 fix the problem. Great thing.

I'm still getting this error on master. Should I switch to stable ? The only problem I have with stable channel is it doesn't support web.

**Comment by rahulvyas** [comment]
> Use this command to solve the problem of white screen
> 
> flutter run --enable-software-rendering

Will it work for iOS Simulator ?

**Comment by awhitford** [comment]
@rahulvyas I'm not sure that I would switch channels if I were you because I don't think this issue is that serious. I logged it because it is something that should be fixed, but it does seem to have a low severity.

I'd rather see you exercise that web support. 😉

**Comment by csacchetti** [comment]
PRECISATION!
As I said above in a new project after updating to version stable 1.22.2 the problem is solved. Today I had to go back to a project started a few months ago to fix a bug and I notice that despite the update the problem remains. So for new projects it is solved but for projects opened a few months ago it is not.

**Comment by yourshinsuke** [comment]
Flutter 1.20.4
```
Error retrieving thread information: (ipc/send) invalid destination port
```

**Comment by yourshinsuke** [comment]
Ah, I should use 1.22.2

**Comment by NarHakobyan** [comment]
Any solution? 🤔

**Comment by ylzgit** [comment]
> > Use this command to solve the problem of white screen
> > flutter run --enable-software-rendering
> 
> Will it work for iOS Simulator ?

yes

**Comment by rahulvyas** [comment]
> > > Use this command to solve the problem of white screen
> > > flutter run --enable-software-rendering
> > 
> > 
> > Will it work for iOS Simulator ?
> 
> yes

Sysqure-Mac-Mini-2019s-Mac-mini:woodstock sysquare$ flutter run --enable-software-rendering
Multiple devices found:
Sysquare iPhone 6 (mobile) • 6738046e36c4b034575b53705583f06ca5192db2 • ios            • iOS 12.4.6
iPhone 11 Pro (mobile)     • CE5AD89F-2EC3-44D7-9D02-778EA9F2ECCD     • ios            •
com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
Web Server (web)           • web-server                               • web-javascript • Flutter Tools
Chrome (web)               • chrome                                   • web-javascript • Google Chrome 86.0.4240.111
[0]: Sysquare iPhone 6 (6738046e36c4b034575b53705583f06ca5192db2)
[1]: iPhone 11 Pro (CE5AD89F-2EC3-44D7-9D02-778EA9F2ECCD)
[2]: Web Server (web-server)
[3]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 1
Launching lib/main.dart on iPhone 11 Pro in debug mode...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         8.3s
Xcode build done.                                           19.8s
[VERBOSE-2:profiler_metrics_ios.mm(186)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(186)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(186)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(186)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(186)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(186)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(186)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(186)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(186)] Error retrieving thread information: (ipc/send) invalid destination port
Waiting for iPhone 11 Pro to report its views...                    5.7s
Error connecting to the service protocol: _flutter.listViews: (-32000) Bad state: The client closed with pending request
"_flutter.listViews".





**Still getting error**

**Comment by sulfy** [comment]
I also have the same issue but the app works fine, any fix? 

```
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
```

**Comment by iskakaushik** [comment]
I wasn't able to reproduce this issue, after some research I think I have an understanding of what might be going on. I have proposed a fix at https://github.com/flutter/engine/pull/22170.

**Comment by rahulvyas** [comment]
> > > Use this command to solve the problem of white screen
> > > flutter run --enable-software-rendering
> > 
> > 
> > Will it work for iOS Simulator ?
> 
> yes

Now I'm getting the below error

Xcode build done.                                           130.9s
[VERBOSE-2:profiler_metrics_ios.mm(186)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(186)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(186)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(186)] Error retrieving thread information: (ipc/send) invalid destination port
[VERBOSE-2:profiler_metrics_ios.mm(186)] Error retrieving thread information: (ipc/send) invalid destination port
Waiting for iPhone 11 Pro to report its views...                   21.7s
Error connecting to the service protocol: _flutter.listViews: (-32000) Bad state: The client closed with pending request
"_flutter.listViews".

**Comment by fadious** [comment]
I'm using `Flutter 1.22.4` and seeing same issue 
`[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port`

**Comment by kamilcglr** [comment]
> I'm using `Flutter 1.22.4` and seeing same issue
> `[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port`

Same here with Flutter 1.22.4

**Comment by Kogami233** [comment]
Same issue.
On macOS Big Sur 11.0.1(Macbook Pro with M1 chipset)  IPhone simulator
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
But nothing error with my android phone, it's working good.
It seems this error in IPhone simulator.
I hope to fix it soon. _(:з」∠)_

**Comment by gazialankus** [comment]
Sorry to sidetrack but this may help some people: If you landed here because you searched for
`Error connecting to the service protocol: _flutter.listViews: (-32000) Bad state: The client closed with pending request "_flutter.listViews".`
You probably have an uncaught exception in your `configureFlutterEngine` function.

**Comment by GiacomoPignoni** [comment]
Same issue with default project, without any edit

`[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port`

macOS Big Sur 11.0.1 (M1 chip) iPhone 12 Simulator

**Comment by shintard** [comment]
>I'm using Flutter 1.22.4 and seeing same issue
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port

Same here with Flutter 1.23.0

**Comment by jerryzhoujw** [comment]
Clean folder of `DerivedData` may solve this issue.

**Comment by seekcx** [comment]
> 默认项目存在相同问题，无需任何编辑
> 
> `[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port`
> 
> macOS Big Sur 11.0.1（M1芯片）iPhone 12模拟器

Exactly the same configuration as you, also encountered this problem.

**Comment by AntonyLeons** [comment]
I also had this issue, however in my case it was because my info.plist was malformed.
I changed the UILaunchStoryboardName to Main to avoid the IOS splash screen, changing this back to launchscreen fixed this.
```
<key>UILaunchStoryboardName</key>
<string>Main</string>
```
to 
```
<key>UILaunchStoryboardName</key>
<string>LaunchScreen</string>
```

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by awhitford** [comment]
It looks like this commit should solve the issue: https://github.com/flutter/engine/commit/f81bc371c09f6565a0e7c420732666bc593ac0b5

However, I am unable to tell its status.  I don't think any of us are running this new code yet.

**Comment by yourideatech** [comment]
> I also had this issue, however in my case it was because my info.plist was malformed.
> I changed the UILaunchStoryboardName to Main to avoid the IOS splash screen, changing this back to launchscreen fixed this.
> 
> ```
> <key>UILaunchStoryboardName</key>
> <string>Main</string>
> ```
> 
> to
> 
> ```
> <key>UILaunchStoryboardName</key>
> <string>LaunchScreen</string>
> ```

solved by following this
thank you

**Comment by youyiqin** [comment]
default project
Apple M1 environment.
Same issue...
```shell
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
```
But,demo project running well...

**Comment by dariowskii** [comment]
Default project, macOS Big Sur 11.0.1 (M1 chip).
Flutter 1.22.4 stable

Infinite loop of this error only on iPhone 12 Pro Max Simulator:

`[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port`

**Comment by chornbe** [comment]
> Clean folder of `DerivedData` can solve this issue.

FWIW, I did this manually, and the errors are still there, and at roughly twice the frequency. I don't know if that's a print issue, or whatever is triggering this is doubling up or running twice as quickly, etc. So, beware.

**Comment by chornbe** [comment]
> Default project, macOS Big Sur 11.0.1 (M1 chip).
> Flutter 1.22.4 stable
> 
> Infinite loop of this error only on iPhone 12 Pro Max Simulator:
> 
> `[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port`

Yep. now it's completely unresponsive in the UI, and banging Q to quit the debugger hangs. Awesome; fire pan to fire. 

Editorial: So much for catching up on lost productivity today because of ferreting out other Flutter related issues all week. This platform is getting more fragile as time goes on. :(  I've been doing this a very long time, and I've seen many of these platforms and "operating environments" start off with a great idea and slowly fade (sometimes not so slow and more of a crash and burn than a fade) due to sloppy support :( I hope Flutter gets back on track. If we all bought our dev tools like the "old days", there'd be a commercially viable interested in ensuring the tools would be more solid and reliable. Borland Pascal, Borland C++, Microsoft Visual Studio 6.0, Visual Basic 3.0 - these were rock solid products. (sigh)

**Comment by stenlee** [comment]
Same issue here
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-arm, locale en-CZ)

[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port

this issue should be reopen

**Comment by iskakaushik** [comment]
Hi, this problem has been fixed on never versions of the Flutter engine, one quick way to see that you are still on a older version of engine is that after this change the line on the error if it ever happens will be on line 203 (see: https://github.com/flutter/engine/pull/22170/files). Can you see if this problem occurs on master channel? Thanks.

There isn't an easy way for me to reproduce this error and the linked change tried to pre-emptively handle this.

**Comment by chornbe** [comment]
I'm on Flutter 1.22.4, Dart 2.10.4, seeing it at 184.

**Comment by iskakaushik** [comment]
Updated my original comment: if you see this error on line 203 that means that this issue needs to be re-opened. If it happens on line: 184, you are on an older version of Flutter, please try the master channel and see if this is still a problem there. Thanks.

**Comment by chornbe** [comment]
I don't recall ever switching channels. Running flutter update shows I'm on Stable. 

Current (before switching to master)
chris@chriss-mac-mini diary_app_flutter % flutter upgrade
Flutter is already up to date on channel stable
Flutter 1.22.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1aafb3a8b9 (3 weeks ago) • 2020-11-13 09:59:28 -0800
Engine • revision 2c956a31c0
Tools • Dart 2.10.4

flutter channel master -> Enter
flutter upgrade -> Enter

chris@chriss-mac-mini diary_app_flutter % flutter upgrade
Flutter is already up to date on channel master
Flutter 1.25.0-5.0.pre.93 • channel master • https://github.com/flutter/flutter.git
Framework • revision d35dd9f8a6 (2 hours ago) • 2020-12-07 09:23:04 -0800
Engine • revision 6491c7518f
Tools • Dart 2.12.0 (build 2.12.0-120.0.dev)
chris@chriss-mac-mini diary_app_flutter % 

flutter clean; flutter run -> Enter

Emits same error, on 184.

**Comment by iskakaushik** [comment]
@chornbe you switch channels by doing `flutter channel master`. Can you please see if this error happens on channel master?

**Comment by chornbe** [comment]
Please re-read my whole post. I did.

**Comment by iskakaushik** [comment]
Seems like the older version of engine is being used still, given the errors. I'm not sure what is going on. I noticed that you did do a `flutter clean` and then `flutter run` which I would expect would have cleared any caches by the flutter tool and the new `flutter run` would've linked the project to the latest engine.

To me it still looks like the stable engine is being used. I'll reopen this issue.

**Comment by chornbe** [comment]
Cool, thanks. Happy to help with any future specific-version testing, logs, etc. 

Thanks!

**Comment by chornbe** [comment]
Interesting to note, and might help debugging... there's a flurry of these things, maybe 3-4 times faster than before, at the very beginning as it's building and deploying to the simulator. I didn't see those before until after the app started on the simulator. All this up-front error reporting is new since switching to the master branch. Not sure if that helps.

**Comment by hengsoheak** [comment]
I can not sleep 4days because of this

**Comment by subhassl** [comment]
Same issue.
On macOS Big Sur 11.0.1(Macbook Pro with M1 chipset) iPhone simulator
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port

**Comment by subhassl** [comment]
> hI @awhitford
> not able to reproduce, i have run the flutter multiples on `stable` channel all day
> Can you please reproduce it again? please provide your `flutter run --verbose` and a complete reproducible minimal code sample
> Thank you

Try with M1 Mac.

**Comment by phx** [comment]
No idea if this helps or how it's related, but I was running a new version of XCode and handn't installed the CLI utils yet.  After running `xcode-select --install` and restarting the simulator, I stopped receiving the error message.

**Comment by leman7193** [comment]
> No idea if this helps or how it's related, but I was running a new version of XCode and handn't installed the CLI utils yet. After running `xcode-select --install` and restarting the simulator, I stopped receiving the error message.

Same issue.
On macOS Big Sur 11.0.1(Macbook Air with M1 chipset) iPhone simulator
I also try reinstall CLI but still get logs
VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port

**Comment by abdulrojak288** [comment]
@iskakaushik do you know the solution?

**Comment by subhassl** [comment]
> Hi, this problem has been fixed on never versions of the Flutter engine, one quick way to see that you are still on a older version of engine is that if the error happens on line 184 as opposed to 203. (see: https://github.com/flutter/engine/pull/22170/files). Can you see if this problem occurs on master channel? Thanks.
> 
> 203 as opposed to 184 as seen in `[VERBOSE-2:profiler_metrics_ios.mm(184)] `
> 
> There isn't an easy way for me to reproduce this error and the linked change tried to pre-emptively handle this.

When does this update come to the stable relase?

**Comment by chornbe** [comment]
> hI @awhitford
> not able to reproduce, i have run the flutter multiples on `stable` channel all day
> Can you please reproduce it again? please provide your `flutter run --verbose` and a complete reproducible minimal code sample
> Thank you

If you're not working on an M1 or DTK pre-release Mac, tracking this down may not be possible or worth your while. 

The apple DTKs have been available since summer time, and the transition from DTK to retail-ready M1 systems was pretty painless. You can still get in on the DTK program (I think), and if not, a base level Mini with M1 is pretty cheap. It benefits us, the community, so I'm sure there's a way to cost this out to somewhere and bypass having to pull coin from your own pocket. 

Frankly, Google should have been all over this day 1 of the DTK program. Any big-company-backed software there still isn't on M1 is kind of silly.

**Comment by hacnguyen1412** [comment]
I have the same issue, but it is not a bug of flutter. My observer was not released so it makes double Navigator.pop and this thing make the monitor goes dark.

**Comment by Pablo-Aldana** [comment]
Still having this issue even with version 1.22.5

Always in line 184 and as mentioned above seems to be thrown even faster.

I have tried the Xcode cli too but hasn't fixed it.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.0 20A2411 darwin-arm, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.52.0)
[✓] Connected device (1 available)

• No issues found!

**Comment by abdulrojak288** [comment]
flutter channel master -> Masuk ke
flutter upgrade -> Enter
flutter clean
 flutter run

ERROR :  
[VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument

**Comment by GlennThompson** [comment]
I have been getting the same errors UNTIL this morning. I did the following:
flutter upgrade
restart machine
ran app on simulator, and noticed the same errors still appearing...

Then ran:
flutter channel master
flutter upgrade
flutter run
The errors have now gone. I hope it helps. (I didnt run flutter clean)

**Comment by abdulrojak288** [comment]
> Updated my original comment: if you see this error on line 203 that means that this issue needs to be re-opened. If it happens on line: 184, you are on an older version of Flutter, please try the master channel and see if this is still a problem there. Thanks.

I have changed the channel from stable to master but this error appears:
ERROR :
[VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument

**Comment by will-heali** [comment]
flutter channel master
flutter upgrade
flutter run

worked for me as well

**Comment by Gambit-Play** [comment]
> flutter channel master

This did help me. Just make sure to restart vscode or whatever editor that your using.

**Comment by rahulvyas** [comment]
I also got the same error but the fix is totally different which nobody can think of. What I did is opened project in Xcode and changed **LaunchScreen** from **Main** to **LaunchScreen** **Storyboard**.  This fixed the issue for me.

**Comment by jackleemeta** [comment]
flutter 1.22.4

**Comment by DSolanki91** [comment]
@iskakaushik i got an error **[VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument**

i alos did 
flutter channel master
flutter upgrade
flutter clean
flutter run

but not resolve **[VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument**

please help me.

**Comment by snadon** [comment]
Here's how I made it disappear.

Close your simulator if it's already opened and then:

```
flutter channel beta
flutter upgrade
flutter clean
open -a Simulator
flutter run
```

```
Flutter 1.25.0-8.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision b0a2299859
Engine • revision 92ae191c17
Tools • Dart 2.12.0 (build 2.12.0-133.2.beta)
```

And the error is gone. I noticed this issue was closed so I tried the beta channel before trying on master.

**Comment by aschlemmer** [comment]
> Here's how I made it disappear.
> 
> Close your simulator if it's already opened and then:
> 
> ```
> flutter channel beta
> flutter upgrade
> flutter clean
> open -a Simulator
> flutter run
 
can verify. Same here. Thanks!

**Comment by P-Jag** [comment]
I also had this error. (with Flutter 1.22.6 and iOS 14.4)

`[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port`

 I've tried a lot fo solutions and nothing works for me. In my case this error occurs when I tried to filter list with usage of my current location. Everything was fine - no different errors but data was continuously loading (never ending loading). 
 
 On Android was perfectly fine so error had to be related with iOS setting, so I've checked info.plist and found some outdated key's like [NSLocationAlways....](https://developer.apple.com/documentation/bundleresources/information_property_list/nslocationalwaysandwheninuseusagedescription) I replace them and puff error disappear, location services works and that's all. fixed. 
 
 So my advice is track where exactly error occur because maybe updating some pakacges/info.plist is everything you'll need.

**Comment by hassan123123** [comment]
> flutter channel master -> Masuk ke
> flutter upgrade -> Enter
> flutter clean
>  flutter run
> 
> ERROR :  
> [VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument

I'm getting the same error, but I'm not on M1 chipset.
Any help?

**Comment by hussamDana92** [comment]
have the same issue.

**Comment by dcchristopher** [comment]
> I also got the same error but the fix is totally different which nobody can think of. What I did is opened project in Xcode and changed **LaunchScreen** from **Main** to **LaunchScreen** **Storyboard**. This fixed the issue for me.

The following settings (Info.plist) should be the only correct settings:

	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>

Setting the UIMainStoryboardFile to LaunchScreen will break the app. Setting the UILaunchStoryboardName to Main will give you a steady stream of these profiler errors (one or two orders of magnitude more). The above settings should have never been changed from the flutter template defaults. Glad to hear the above is what worked for you but it's really puzzling how you ended up in a different state.

**Comment by panzee54** [comment]
Can't find keyplane that supports type 4 for keyboard iPhone-PortraitChoco-NumberPad; using 25889_PortraitChoco_iPhone-Simple-Pad_Default
Can't find keyplane that supports type 8 for keyboard iPhone-PortraitChoco-DecimalPad; using 25930_PortraitChoco_iPhone-Simple-Pad_Default
Can't find keyplane that supports type 4 for keyboard iPhone-PortraitChoco-NumberPad; using 25889_PortraitChoco_iPhone-Simple-Pad_Default
Can't find keyplane that supports type 4 for keyboard iPhone-PortraitChoco-NumberPad; using 25889_PortraitChoco_iPhone-Simple-Pad_Default
Can't find keyplane that supports type 8 for keyboard iPhone-PortraitChoco-DecimalPad; using 25930_PortraitChoco_iPhone-Simple-Pad_Default
Can't find keyplane that supports type 4 for keyboard iPhone-PortraitChoco-NumberPad; using 25889_PortraitChoco_iPhone-Simple-Pad_Default
Can't find keyplane that supports type 4 for keyboard iPhone-PortraitChoco-NumberPad; using 25889_PortraitChoco_iPhone-Simple-Pad_Default
Can't find keyplane that supports type 4 for keyboard iPhone-PortraitChoco-NumberPad; using 25889_PortraitChoco_iPhone-Simple-Pad_Default
Can't find keyplane that supports type 4 for keyboard iPhone-PortraitChoco-NumberPad; using 25889_PortraitChoco_iPhone-Simple-Pad_Default
[User Defaults] Couldn't read values in CFPrefsPlistSource<0x280e07900> (Domain: com.apple.Sharing, User: kCFPreferencesCurrentUser, ByHost: No, Container: kCFPreferencesNoContainer, Contents Need Refresh: Yes): accessing preferences outside an application's container requires user-preference-read or file-read-data sandbox access
[User Defaults] Couldn't read values in CFPrefsPlistSource<0x280e07900> (Domain: com.apple.Sharing, User: kCFPreferencesCurrentUser, ByHost: No, Container: kCFPreferencesNoContainer, Contents Need Refresh: Yes): accessing preferences outside an application's container requires user-preference-read or file-read-data sandbox access
<CATransformLayer: 0x28207ce60> - changing property backgroundColor in transform-only layer, will have no effect
[LayoutConstraints] Unable to simultaneously satisfy constraints.
        Probably at least one of the constraints in the following list is one you don't want. 
        Try this: 
                (1) look at each constraint and try to figure out which you don't expect; 
                (2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x2803fe490 _UIActivityActionCellTitleLabel:0x11c2edd80.height >= 22   (active)>",
    "<NSLayoutConstraint:0x2803fdfe0 V:|-(15)-[_UIActivityActionCellTitleLabel:0x11c2edd80]   (active, names: '|':UIView:0x11c2ee980 )>",
    "<NSLayoutConstraint:0x2803fe030 V:[_UIActivityActionCellTitleLabel:0x11c2edd80]-(15)-|   (active, names: '|':UIView:0x11c2ee980 )>",
    "<NSLayoutConstraint:0x2803ffd40 'UIView-Encapsulated-Layout-Height' UIView:0x11c2ee980.height == 50.3333   (active)>"
)


Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x2803fe490 _UIActivityActionCellTitleLabel:0x11c2edd80.height >= 22   (active)>


Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
[WindowServer] display_timer_callback: unexpected state (now:6c854651320 < expected:6c8546b29ef)
[VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument
[VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument

**Comment by panzee54** [comment]
[VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) object terminated
[VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument
[core] SLRemoteComposeViewController: (this may be harmless) viewServiceDidTerminateWithError: Error Domain=_UIViewServiceErrorDomain Code=1 "(null)" UserInfo={Terminated=disconnect method}
[ShareSheet] connection invalidated

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
