### ISSUE TITLE
App builds and installs but wont open after the last push from stable branch

### ISSUE THREAD

**Issue by AbdoZDGaia** [flutter/flutter#63310]
hello,

Yesterday my application was building smoothly with no errors what so ever.
Today i pulled the latest Flutter sdk stable version.
and right now my application can't start on my phone, it builds and everything and then installs but it doesnt open.
screen just flashes as if the app just opened and closed instantly and i get this error

![image](https://user-images.githubusercontent.com/57171672/89722755-a65fe380-d9ed-11ea-91ab-ad1e83334d0f.png)

**Comment by darshankawar** [comment]
Hi @AbdoZDGaia,
Usually whenever you upgrade, try to run `flutter pub cache repair` or `flutter clean` and then `flutter run`. Can you try these commands and see if it resolves the issue ?
If problem persists, provide `flutter doctor -v` and a minimal complete reproducible code sample.
Thanks.

**Comment by AbdoZDGaia** [comment]
i did run a flutter clean then a flutter pub cache repair, unfortunately the issue still persists.

this is what i got after i ran flutter doctor -v
![image](https://user-images.githubusercontent.com/57171672/89845915-17cf9b80-db80-11ea-9dbe-eb18c1ea301a.png)

this is my github repo if u wanna try it
https://github.com/AbdoZDGaia/MeTube

**Comment by darshankawar** [comment]
@AbdoZDGaia,
I cloned your repo but it seems to be incomplete, as I am getting below error during flutter run:

```
lib/services/api.dart:6:8: Error: Error when reading 'lib/utilities/keys.dart': No such file or directory
import 'package:metube/utilities/keys.dart';
```
I guess it's looking for `utilities` folder which isn't there in repo.

**Comment by AbdoZDGaia** [comment]
i have added the unversioned file, pulling the repo should fix the issue u have.

**Comment by darshankawar** [comment]
@AbdoZDGaia, I see the crash on latest Stable 1.20.1 and 1.20.0 upon app launch itself with below log:

<details>
<summary>log</summary>

```
   E/AndroidRuntime(18499): FATAL EXCEPTION: main
E/AndroidRuntime(18499): Process: com.example.metube, PID: 18499
E/AndroidRuntime(18499): java.lang.RuntimeException: Unable to instantiate application io.flutter.app.MeTube: java.lang.ClassNotFoundException: Didn't find class "io.flutter.app.MeTube" on path: DexPathList[[zip file "/data/app/com.example.metube-3CnRuus93wFMzqkcZY71NA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.metube-3CnRuus93wFMzqkcZY71NA==/lib/arm, /data/app/com.example.metube-3CnRuus93wFMzqkcZY71NA==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
E/AndroidRuntime(18499):        at android.app.LoadedApk.makeApplication(LoadedApk.java:989)
E/AndroidRuntime(18499):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5745)
E/AndroidRuntime(18499):        at android.app.ActivityThread.-wrap1(Unknown Source:0)
E/AndroidRuntime(18499):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1662)
E/AndroidRuntime(18499):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(18499):        at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(18499):        at android.app.ActivityThread.main(ActivityThread.java:6543)
E/AndroidRuntime(18499):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18499):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
E/AndroidRuntime(18499):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
E/AndroidRuntime(18499): Caused by: java.lang.ClassNotFoundException: Didn't find class "io.flutter.app.MeTube" on path: DexPathList[[zip file "/data/app/com.example.metube-3CnRuus93wFMzqkcZY71NA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.metube-3CnRuus93wFMzqkcZY71NA==/lib/arm, /data/app/com.example.metube-3CnRuus93wFMzqkcZY71NA==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
E/AndroidRuntime(18499):        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
E/AndroidRuntime(18499):        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(18499):        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(18499):        at android.app.Instrumentation.newApplication(Instrumentation.java:1087)
E/AndroidRuntime(18499):        at android.app.LoadedApk.makeApplication(LoadedApk.java:983)
E/AndroidRuntime(18499):        ... 9 more
```

</details>

Since we can't downgrade Stable to 1.17.5, can you try to see if this also happens on latest Master ?

**Comment by AbdoZDGaia** [comment]
it does

**Comment by darshankawar** [comment]
@AbdoZDGaia,
I downgraded to 1.17.5 and still see the error upon app launch. Can you please specify which version you were earlier on, on which the app was working ?

**Comment by AbdoZDGaia** [comment]
i tried downgrading it and it doesnt even work on the version it used to work on which is 1.20.
what would be the problem?
or how could i get extra info about the problem? or where it originates?

**Comment by darshankawar** [comment]
@AbdoZDGaia,
The crash log I see is:

`E/AndroidRuntime(18499): java.lang.RuntimeException: Unable to instantiate application io.flutter.app.MeTube: java.lang.ClassNotFoundException: Didn't find class "io.flutter.app.MeTube" on path: DexPathList[[zip file "/data/app/com.example.metube-3CnRuus93wFMzqkcZY71NA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.metube-3CnRuus93wFMzqkcZY71NA==/lib/arm, /data/app/com.example.metube-3CnRuus93wFMzqkcZY71NA==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]`

Also, I saw this crash log only when I tried on 1.20 version, but not on 1.17.5, although it crashed there as well.
Usually the error occurs if there were any changes made in `MainActivity.kt` or if this file is misplaced. But in your case, the file is intact.
I am wondering if this has to do with the plugin you are using `youtube_player_flutter`, may be with update, some changes went incompatible with this plugin.

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue.
We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
