### ISSUE TITLE
Android 10 incorrect insets when navigation bar is translucent

### ISSUE THREAD

**Issue by jacek-marchwicki** [flutter/flutter#63761]
First of all thanks for the great Flutter toolkit if you'll have some follow up questions to the issue, I'll be glad to answer.

## Steps to Reproduce

The example app is available here: https://github.com/jacek-marchwicki/flutter-insets-bug

Changes to the example project that are necessary to reproduce the issue: https://github.com/jacek-marchwicki/flutter-insets-bug/commit/f23e6d89da417a7ee28dc4f745ddb32d7eec103a
<details>
  <summary>Diff</summary>

```patch
Index: lib/main.dart
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- lib/main.dart	(revision d3362aabdefa74cc479fc50b8994f00b57b230a8)
+++ lib/main.dart	(date 1597401415000)
@@ -72,6 +72,25 @@
     // fast, so that you can just rebuild anything that needs updating rather
     // than having to individually change instances of widgets.
     return Scaffold(
+      bottomNavigationBar: BottomNavigationBar(
+        items: const <BottomNavigationBarItem>[
+          BottomNavigationBarItem(
+            icon: Icon(Icons.home),
+            title: Text('Home'),
+          ),
+          BottomNavigationBarItem(
+            icon: Icon(Icons.business),
+            title: Text('Business'),
+          ),
+          BottomNavigationBarItem(
+            icon: Icon(Icons.school),
+            title: Text('School'),
+          ),
+        ],
+        currentIndex: 0,
+        selectedItemColor: Colors.amber[800],
+        onTap: (_) {},
+      ),
       appBar: AppBar(
         // Here we take the value from the MyHomePage object that was created by
         // the App.build method, and use it to set our appbar title.
Index: android/app/src/main/kotlin/com/example/insetstest/MainActivity.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- android/app/src/main/kotlin/com/example/insetstest/MainActivity.kt	(revision d3362aabdefa74cc479fc50b8994f00b57b230a8)
+++ android/app/src/main/kotlin/com/example/insetstest/MainActivity.kt	(date 1597397196000)
@@ -1,7 +1,17 @@
 package com.example.insetstest
 
+import android.graphics.Color
+import android.os.Build
+import android.view.View
 import io.flutter.embedding.android.FlutterActivity
 
-class MainActivity : FlutterActivity() {
-
+class MainActivity: FlutterActivity() {
+    override fun onWindowFocusChanged(hasFocus: Boolean) {
+        super.onWindowFocusChanged(hasFocus)
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
+            window.decorView.systemUiVisibility = View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION or View.SYSTEM_UI_FLAG_LAYOUT_STABLE
+            window.navigationBarColor = Color.TRANSPARENT
+            window.statusBarColor = Color.TRANSPARENT
+        }
+    }
 }

```

</details>

   1. We need to enable transparent navigation bar. According to (the Android documentation: https://developer.android.com/training/gestures/gesturenav) we need to set:
       ```kotlin
            window.decorView.systemUiVisibility = View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION or View.SYSTEM_UI_FLAG_LAYOUT_STABLE
            window.navigationBarColor = Color.TRANSPARENT
            window.statusBarColor = Color.TRANSPARENT
       ```
      
  2. We need to check if insets are updated correctly, In the example I'm using BottomNavigationBar but we could also use SafeArea to reproduce the same issue.

| **Expected results** | **Actual results** | **Actual results** | **On iOS** |
|---|---|---|---|
| We should see the BottomNavigationBar displayed right above system navigation bar. | We see system navigation bar displayed on BottomNavigationBar. | On Android, we can observe the same results when gestures navigation is disabled and standard 3 buttons navigation is set. | The same code works perfectly fine on iOS |
| ![android-with-fix](https://user-images.githubusercontent.com/689211/90238803-cc8ae680-de26-11ea-8c6e-625199699ec8.png) | ![android](https://user-images.githubusercontent.com/689211/90238895-f6440d80-de26-11ea-9d5b-f4715ebaf70a.png) | ![android-no-gestures](https://user-images.githubusercontent.com/689211/90240521-afa3e280-de29-11ea-9803-2c78a3f915d6.png) | ![ios](https://user-images.githubusercontent.com/689211/90239030-33100480-de27-11ea-9fea-778fe20a3226.png) |

# Findings

After debugging I found out that Android sets `Window.viewInsets.bottom` to the height of the navigation bar. 
The different is on iOS where `Window.viewInsets.bottom` is set to 0, but the height of the navigation bar is set in `Window.padding.bottom` and `Window.padding.viewPadding`. By looking through the [window documentation](https://api.flutter.dev/flutter/dart-ui/Window-class.html) and the following [video](https://flutter.github.io/assets-for-api-docs/assets/widgets/window_padding.mp4) looks like the iOS implementation is correct.

# Workaround

I've created a widget that does workaround the issue: https://github.com/jacek-marchwicki/flutter-insets-bug/commit/f5eb07af06e9cfee2124d97e33aa2e4189e728f9#diff-fe53fad46868a294b309fc85ed138997R143-R168
With the fix, the app looks correctly:

| Gesture navigation | standard 3 buttons navigation |
|---|---|
| ![android-with-fix](https://user-images.githubusercontent.com/689211/90240707-11fce300-de2a-11ea-989b-3cfd62a08058.png) | ![android-with-fix-no-gestures](https://user-images.githubusercontent.com/689211/90240717-145f3d00-de2a-11ea-8df4-f12160f0c02c.png) |

# Logs
<details>
  <summary>Logs</summary>

### `flutter run --verbose` results:
[logs.txt](https://github.com/flutter/flutter/files/5074061/logs.txt)

### `flutter analyze` results:
```
Analyzing insets_test...                                                
No issues found! (ran in 6.6s)
```

### `flutter doctor -v` results:
[doctor-result.txt](https://github.com/flutter/flutter/files/5074037/doctor-result.txt)

</details>

# Related tickets: 
* https://github.com/flutter/flutter/issues/34678
* https://github.com/flutter/flutter/issues/40974
* https://github.com/flutter/flutter/issues/39061

**Comment by TahaTesser** [comment]
I can reproduce it on Galaxy M30

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel beta, 1.20.0, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.0 at /Users/tahatesser/Code/flutter_beta
    • Framework revision 916c3ac648 (13 days ago), 2020-08-01 09:01:12 -0700
    • Engine revision d6ee1499c2
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (4 available)
    • SM M305F (mobile)  • 32003c30dc19668f                     • android-arm64  • Android 10 (API 29)
    • iPhone 11 (mobile) • A63D6F51-59F3-4A75-961F-3769709F3A92 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • Web Server (web)   • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome
      84.0.4147.125

• No issues found!

```

</details>

**Comment by Zazo032** [comment]
Related to https://github.com/flutter/flutter/issues/40974

**Comment by lazylazyllama** [comment]
I also want to add, that you have to set `selectedFontSize``to 0, because for some reason, that I don't understand, the BottomAppBar widget divides the bottom padding by the selectedFontSize...

```dart
final double additionalBottomPadding = math.max(MediaQuery.of(context).padding.bottom - widget.selectedFontSize / 2.0, 0.0);
```

as you can see [here](https://github.com/flutter/flutter/blob/4732a214a7362a3781989977429f14202143b4f5/packages/flutter/lib/src/material/bottom_navigation_bar.dart#L930)

**Comment by lazylazyllama** [comment]
This should be fixed since flutter/engine#21730 landed in current flutter master branch

**Comment by MrBirb** [comment]
@TahaTesser Can you confirm this is fixed now?

**Comment by TahaTesser** [comment]
@MrBirb 
I can see still the BottomNavigationBar isn't matching the  expected behavior but looks better than before and the workaround works far better when used from https://github.com/flutter/flutter/issues/63761#issue-679070951 

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (12 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios • iOS 14.4

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 1.26.0-18.0.pre.186, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-18.0.pre.186 at /Users/tahatesser/Code/flutter_master
    • Framework revision 39114251af (2 hours ago), 2021-02-04 01:16:04 -0500
    • Engine revision 1c2c78398c
    • Dart version 2.12.0 (build 2.12.0-284.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 14.4
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>

Thank you

**Comment by lazylazyllama** [comment]
@tadaspetra 

That's because the BottomNavigationBar does some weird things paddings depending on the current fontsize.

#75360 seems to be fixing exactly that. :)

**Comment by noordawod** [comment]
This still happens in any Android emulator with SDK 28 and 29.

**Comment by noordawod** [comment]
Update: and SDK 30.

**Comment by Piinks** [comment]
Hey @noordawod thanks for the update. I think I have a solution for this, I am just testing it now across devices and different SDKs. The insets should be available as part of `MediaQueryData.systemGestureInsets` if that helps in the meantime. My current plan of action if all goes well is to update all affected widgets to include this part of media query data during layout.

**Comment by noordawod** [comment]
Thanks @Piinks, sounds like a you're on top of it! Meanwhile, I've adapted https://github.com/jacek-marchwicki/flutter-insets-bug/commit/f5eb07af06e9cfee2124d97e33aa2e4189e728f9#diff-e61eb31d013d12616f5532636a88cfa63631dda8f7829e5424e68542214d1608R143 to my needs and it seems to work. So it may be an inspiration.

PS: weirdly enough, between SDK 29 and 30, the values of `viewInsets` and `viewPadding` seem to switch places. So when `viewInsets` is `0.0` in one SDK and `viewPadding` is larger than `0.0`, if I switch to SDK 30 the values flip -- the first becomes larger than `0.0` while the second is `0.0`. Something weird indeed...

**Comment by LasseRosenow** [comment]
@noordawod, would you like to share an example code where this issue happens?

Because I had the same problem, but then I fixed it in flutter/engine#21730 and since this got merged everything is working perfectly withe edge-to-edge on api 28 - 30 for me.

Would be interesting to see if I missed something :)

**Comment by noordawod** [comment]
I'll try and find it in-between the 10,000 of lines of Dart code...

**Comment by Piinks** [comment]
Update to the [update](https://github.com/flutter/flutter/issues/63761#issuecomment-821325080): I have found a different solution that is actually way better. There was a system ui flag we were setting in the engine that created a conflict. :tada: 

This new solution will not require going through the framework and updating widgets to use additional media query data as I thought before. I think we should still update widgets to consider `systemGestureInsets` just generally, but it won't be required for us to get this right. I can file that as a separate issue. :) 

I am just working now on getting everything wired up in the engine. I'll share back the design doc I've been putting together once it has been published.
