### ISSUE TITLE
ListView is missing frames when using API "animateTo"

### ISSUE THREAD

**Issue by PilotLee** [flutter/flutter#65224]
## Details

1.  Please tell us exactly how to reproduce the problem you are running into.

     **hi~@liyuqian  I wrote a demo called flutteranimatelist. 
    in this demo, i placed a listView and two buttons.
    first, run the demo in profile mode. then press the 'up' or 'down' button.
    you will find the Frame rendering times  shows red. 
    FPS is about 45 in this simple demo.
    my device is vivoY9s  **   

2.  Please attach a small application (ideally just one main.dart file) that
     reproduces the problem. You could use https://gist.github.com/ for this.

     **https://github.com/PilotLee/flutter_animateto_issue**

3.  Switch flutter to master channel and run this app on a physical device
     using profile mode with Skia tracing enabled, as follows:
       flutter channel master
       flutter run --profile --trace-skia
     Then press ‘P’ to enable the performance overlay.

     The bleeding edge master channel is encouraged here because Flutter is
     constantly fixing bugs and improving its performance. Your problem in an
     older Flutter version may have already been solved in the master channel.

4.  Record a video of the performance issue using another phone so we
     can have an intuitive understanding of what happened. Don’t use
     "adb screenrecord", as that affects the performance of the profile run.

      **https://github.com/PilotLee/flutter_animateto_issue/tree/master/video%26capture**

5.  Open Observatory and save a timeline trace of the performance issue
     so we know which functions might be causing it. See "How to Collect
     and Read Timeline Traces" on this blog post:
       https://medium.com/flutter/profiling-flutter-applications-using-the-timeline-a1a434964af3#a499

       **https://github.com/PilotLee/flutter_animateto_issue/blob/master/dart_devtools_2020_9_4-1599185470866000.json**

**Target Platform:**  Android
**Target OS version/browser:**  android 9
**Devices:** vivo Y9s

## Logs

![image](https://user-images.githubusercontent.com/15953395/92190354-88be5680-ee93-11ea-9f52-1014f775511e.png)

```
```

![image](https://user-images.githubusercontent.com/15953395/92190380-9a076300-ee93-11ea-99c1-5ca065037f98.png)

```
```

**Comment by pedromassangocode** [comment]
Here is one of the videos shared by the OP (I just converted to GIF to share here)

![gif](https://user-images.githubusercontent.com/67424416/92218217-adfd9580-ee90-11ea-9dae-f871a25eb51e.gif)

**Comment by pedromassangocode** [comment]
I'm unable to reproduce this due to lack of device, so this will need additional triage.

**Comment by PilotLee** [comment]
> device

**Comment by PilotLee** [comment]
> I'm unable to reproduce this due to lack of device, so this will need additional triage.

This issue has nothing to do with the device.  
you can reproduce it on any android device.

**Comment by pedromassangocode** [comment]
Hi @PilotLee 
Did you closed this by mistake?

**Comment by PilotLee** [comment]
> Hi @PilotLee
> Did you closed this by mistake?

sorry   -_-!

**Comment by Hixie** [comment]
cc @liyuqian

**Comment by liyuqian** [comment]
@PilotLee : it turns out that the `ListView` is still fast with `animateTo`. The things that are really slowing you down are `RaisedButtons`, their ripple animations/shadows. See https://gist.github.com/liyuqian/09c3948bac261fe882548a4819f75193 and tap the `GestureDetector` directly to see the difference.

Additionally, the IntelliJ IDE plugin you're using is giving some confusing information. Currently, it shows red bars when `frame_build_time + frame_raster_time > 16ms`. It should instead only show red bars when `max(frame_build_time, frame_raster_time) > 16ms`. A similar issue was fixed in https://github.com/flutter/devtools/pull/1999 for DevTools. CC @kenzieschmoll

**Comment by PilotLee** [comment]
> @PilotLee : it turns out that the `ListView` is still fast with `animateTo`. The things that are really slowing you down are `RaisedButtons`, their ripple animations/shadows. See https://gist.github.com/liyuqian/09c3948bac261fe882548a4819f75193 and tap the `GestureDetector` directly to see the difference.
> 
> Additionally, the IntelliJ IDE plugin you're using is giving some confusing information. Currently, it shows red bars when `frame_build_time + frame_raster_time > 16ms`. It should instead only show red bars when `max(frame_build_time, frame_raster_time) > 16ms`. A similar issue was fixed in [flutter/devtools#1999](https://github.com/flutter/devtools/pull/1999) for DevTools. CC @kenzieschmoll

After I replaced RaisedButtons with GestureDetector, still reproduced.
so I tried to slow down the animation, the red is obviously displayed during the animation. So the proof has nothing to do with RaisedButtons
And when I turn on the performance overlay option, even a single frame_raster_time thread exceeds 16ms when the list scrolls.
you can refer to the video i attached.
https://github.com/PilotLee/flutter_animateto_issue/blob/master/video%26capture/IMG_3471.mov

**Comment by kenzieschmoll** [comment]
We should find a way to either a) share the FPS calculation code between DevTools and IntelliJ or b) find a way to embed the flutter frames chart from DevTools into IntelliJ. CC @jacob314 

Option b) may be more challenging but is definitely an interesting thought with the work @helin24 has been doing to embed DevTools views into the IntelliJ plugin.

Filed https://github.com/flutter/flutter-intellij/issues/4815 to track this.

**Comment by liyuqian** [comment]
@PilotLee : I can't reproduce your performance issue on my Moto G4 with Flutter version 9e315985d if I remove `RaisedButtons` . See this screenshot:  https://photos.app.goo.gl/v5H5ka8vnjGeJGQn9

Maybe this performance issue is specific to your vivo Y9s device? Can you try a different device and see if it persists?

**Comment by PilotLee** [comment]
I found the same problem on oppo realmeX and xiaomi shark devices.
Then I found that even very high-end mobile phones performed poorly on Huawei equipment.
On my huawei mate 30 pro and honor 9 devices, both manual sliding and animateto performed very badly.
The data performance is not even as good as your very old moto device.  It's terrible...
Also, I run very smoothly on google pixel, and the max_frame is kept at about 8ms
Here is the videos from Huawei
https://github.com/PilotLee/flutter_animateto_issue/blob/master/video%26capture/huawei_honor_9.mov
https://github.com/PilotLee/flutter_animateto_issue/blob/master/video%26capture/huawei_mate_30_pro.mov

**Comment by liyuqian** [comment]
I see. So this is not an `animateTo` performance issue, but some hardware-specific performance issue. @kf6gpe has previously helped us collect a bunch of low-end Chinese mobile devices for performance testing. Now it seems that we also need to test some high-end Chinese mobile devices. Having a 1-year-old $1000 mate 30 pro perform worse than a 7-year-old original pixel phone does look worrisome.

**Comment by PilotLee** [comment]
After I tried a lot of mobile devices, I summarized the following tips.
1 On many mobile devices released abroad, such as google pixel, moto, one plus. They have good sliding and animateto performance.
2 On Chinese mobile phones, Huawei performed poorly in both scenarios.
3 In some other Chinese mobile phones such as vivo, oppo, xiaomi and so on. The performance of animateto is obviously inferior to manual sliding.
I hope the above items can help you.

**Comment by liyuqian** [comment]
Thanks, that's very helpful!

Here's a summary of the problematic devices and their GPUs mentioned in this issue

|  Phone | GPU |
| --- | --- |
|  Huawei Mate 30 Pro | Mali-G76 MP16 |
|  Huawei Honor 9 | Mali-G71 |
|  Vivo Y9s | Adreno 610 |
|  Oppo Realme X | Adreno 616 |
|  Xiaomi Mi 10 | Adreno 650 |

**Comment by liyuqian** [comment]
I created https://github.com/flutter/flutter/issues/65795 to track the performance  issue that's bad in both manual and animateTo scrolls. I'll leave this issue open to focus on Vivo, Oppo, and Xiaomi devices which seems to be only bad for animateTo scroll performance.

**Comment by kf6gpe** [comment]
I've sourced the Mate 30 Pro, the Honor 9, the Realme X, and the Xiaomi Mi 10. I'll let you know when they come in and we'll figure out how to get them to you, @liyuqian . I couldn't find the others.

**Comment by a1239897580** [comment]
Is there a solution to this problem? After our application was launched, the user reported that the vivo Y9s model may experience severe lag. We tested that other models are functioning normally, which occurred on specific devices
