### ISSUE TITLE
A required argument was added to VelocityTracker's constructor

### ISSUE THREAD

**Issue by yunior123** [flutter/flutter#66063]
Hello , I am having this issue in my flutter project in github due to updates on the framework, please do not close this question without giving an explanation, thank you
/C:/hostedtoolcache/windows/flutter/1.22.0-12.1.pre-beta/x64/.pub-cache/hosted/pub.dartlang.org/optimized_gesture_detector-0.0.5/lib/scale.dart:229:55: Error: Too few positional arguments: 1 required, 0 given.
Running Gradle task 'assembleRelease'...                        
    _velocityTrackers[event.pointer] = VelocityTracker();

**Comment by PixelToast** [comment]
VelocityTracker's default contructor was given a non-optional parameter, this was fixed in #66043

**Comment by PixelToast** [comment]
Actually, it wasn't merged yet so I'll link the issue

**Comment by PixelToast** [comment]
Merged right when I said that, aaaaaaaa

**Comment by yunior123** [comment]
My problem still persist since this package https://pub.dev/packages/mp_chart is also depending on another package that uses the Velocity tracker class optimized_gesture_detector-0.0.5/lib/scale.dart:229:55:

**Comment by yunior123** [comment]
> Merged right when I said that 🙃

My problem still persist since this package https://pub.dev/packages/mp_chart is also depending on another package that uses the Velocity tracker class optimized_gesture_detector-0.0.5/lib/scale.dart:229:55:

**Comment by PixelToast** [comment]
There is an open issue at https://github.com/SunPointed/OptimizedGestureDetector/issues/2
