### ISSUE TITLE
[video_player] Playing video from asset on Android throws an exception

### ISSUE THREAD

**Issue by iNima** [flutter/flutter#66627]
## Steps to Reproduce
1. Switch to Flutter beta channel 1.22.0-12.1.pre
2. Clone flutter plugin repository
3. Run the video_player example app on an Android device.
4. When the app starts, select the `Asset` tab.

**Expected results:** 
The asset video should be played

**Actual results:** 
The video won't play and we see this exception in the console:

```
E/flutter (27373): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/services/message_codec.dart': Failed assertion: line 111 pos 15: 'code != null': is not true.
E/flutter (27373): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (27373): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (27373): #2      new PlatformException (package:flutter/src/services/message_codec.dart:111:15)
E/flutter (27373): #3      VideoPlayerApi.create (package:video_player_platform_interface/messages.dart:278:13)
E/flutter (27373): <asynchronous suspension>
E/flutter (27373): #4      MethodChannelVideoPlayer.create (package:video_player_platform_interface/method_channel_video_player.dart:46:42)
E/flutter (27373): #5      VideoPlayerController.initialize (package:video_player/video_player.dart:275:45)
E/flutter (27373): #6      _ButterFlyAssetVideoState.initState (package:video_player_example/main.dart:164:17)
E/flutter (27373): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
E/flutter (27373): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (27373): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (27373): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (27373): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (27373): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (27373): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (27373): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (27373): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (27373): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (27373): #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (27373): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (27373): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (27373): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (27373): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (27373): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (27373): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (27373): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (27373): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (27373): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (27373): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (27373): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (27373): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (27373): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (27373): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (27373): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (27373): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (27373): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (27373): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (27373): #36     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter (27373): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (27373): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (27373): #39     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4791:11)
E/flutter (27373): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (27373): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (27373): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (27373): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
```

Flutter Doctor -v

```
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.5 19F101, locale en-AU)
    • Flutter version 1.22.0-12.1.pre at /Users/iNima/Projects/AssetOwl/SampleProjects/flutter
    • Framework revision 8b3760638a (9 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/iNima/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/iNima/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 94DAX0ZTOP • android-arm64  • Android 10 (API 29)
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 85.0.4183.121
```

**Comment by darshankawar** [comment]
Hi @iNima,
Tried the official video_player plugin example on Pixel 3 emulator with Android 10 on latest beta and didn't see the exception in the console. The video too played well, as expected.

[66627.mov.zip](https://github.com/flutter/flutter/files/5281693/66627.mov.zip)

<img width="685" alt="Screenshot 2020-09-25 at 2 25 15 PM" src="https://user-images.githubusercontent.com/67046386/94248258-d92d4f00-ff3b-11ea-8df4-8272d7c54d83.png">
<img width="795" alt="Screenshot 2020-09-25 at 2 25 44 PM" src="https://user-images.githubusercontent.com/67046386/94248264-db8fa900-ff3b-11ea-8fb3-53f54f459552.png">


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.4 19E2269, locale
    en-IN)
    • Flutter version 1.22.0-12.1.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8b3760638a (9 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    •
      Android 10 (API 29) (emulator)
    • Web Server (web)                   • web-server    • web-javascript •
      Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript •
      Google Chrome 85.0.4183.121

• No issues found!

```

</details>

Are you getting the exception consistently ? Does the video play or gets stuck ?
Thanks.

**Comment by iNima** [comment]
Hi @darshankawar ,
Thanks for your reply.
It happens consistently on both emulator and real device.
I set a breakpoint where the exception occurs and it seems that the root cause of the error is this:
```
java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference
```
It happens at line 277 of `messages.dart` in the `create` method.
This is what I see in the app:
[3453.webm.zip](https://github.com/flutter/flutter/files/5286064/3453.webm.zip)

![Screenshot_1601086509](https://user-images.githubusercontent.com/4446420/94327982-51564c00-fff2-11ea-954c-61d0d613a32c.png)

Thanks

**Comment by tomykho** [comment]
Same happens to me when upgrade to `video_player: ^0.11.0`

**Comment by darshankawar** [comment]
I am unable to replicate the issue on the devices and emulators I tried, but per author it seem to be happening consistently at their end. Keeping this issue open for further analysis.

**Comment by midi1007** [comment]
For me `video_player: ^0.11.0`  works only on stable channel.

Its not working on master or beta channel!

**Comment by barees63** [comment]
I'm getting the same issue with a video in assets, initialize fails with:

`code != null`
 
but that's just an error creating a PlatformException, the actual exception is:

`java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference`

Both device (Samsung S8+) and emulator.

**Comment by DannyJoinedApps** [comment]
I get the same thing as barees63. Cannot get asset videos to work on android emulators or physical android. Same error as barrees63. I've tried video_player 0.10.0 & 0.11.0, I have tried master, beta & stable. Same thing every time. This is with the example app on github, I even downloaded the same video files and put them in the same place and registered in pubspec. If I change the path for the flutter-mark... image file the example uses, the one in that assets folder, then the inclusion of that image breaks and more debug messages. I did this just to prove point or rather testing that: the image really is getting loaded from that correctly registered folder. So I'm sure the files are really getting to that folder and I'm addressing and registering them correctly, however if I then change the path for the video asset, nothing changes with the error resulting from initialize, remains at: 
`E/flutter (17519): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/services/message_codec.dart': Failed assertion: line 111 pos 15: 'code != null': is not true.`

To my (very) naive understanding this seems possible that the library loading the video files from storage is failing, if you change to a nonsense path and the error stays the same I mean. Maybe thats bad logic though, I don't know much.

My flutter doctor:
`[√] Flutter (Channel stable, 1.22.0, on Microsoft Windows [Version 10.0.18363.1082], locale en-GB)
    • Flutter version 1.22.0 at C:\flutter
    • Framework revision d408d302e2 (3 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\mrdan\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.49.2)
    • VS Code at C:\Users\mrdan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (1 available)
    • SM G975F (mobile) • 192.168.0.36:5555 • android-arm64 • Android 10 (API 29)`

**Comment by samderlust** [comment]
I have the same issue after update to flutter 1.22. only happens on Android

`
E/flutter (14128): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/services/message_codec.dart': Failed assertion: line 111 pos 15: 'code != null': is not true.
E/flutter (14128): #0      _AssertionError._doThrowNew  (dart:core-patch/errors_patch.dart:46:39))
E/flutter (14128): #1      _AssertionError._throwNew  (dart:core-patch/errors_patch.dart:36:5))
E/flutter (14128): #2      new PlatformException 
package:flutter/…/services/message_codec.dart:111
E/flutter (14128): #3      VideoPlayerApi.create 
package:video_player_platform_interface/messages.dart:205
E/flutter (14128): <asynchronous suspension>
E/flutter (14128): #4      MethodChannelVideoPlayer.create 
package:video_player_platform_interface/method_channel_video_player.dart:46
E/flutter (14128): #5      VideoPlayerController.initialize 
package:video_player/video_player.dart:282`

**Comment by DannyJoinedApps** [comment]
Found the 'fix': downgrade :)
1.20.0-3.0.pre
is the last version I had and suddenly the example jumps into life, pretty butterfly. My 3 year old is helping so I shouted "ah-ha!" and he contributed: "Mariposa papa, mariposa!"

**Comment by DannyBoyNg** [comment]
I'm having the same problem everyone else here is having. Only happened when I upgraded to flutter 1.22. Dang it, it was working just fine on 1.20.4

**Comment by wuweijian1997** [comment]
The same question. Flutter 1.22.0,  video_player: ^0.11.0,Android

**Comment by TomKrauss** [comment]
I'm having the problem too, but only, if I upgrade my app to use the new Android Plugin API (see https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration).

**Comment by iNima** [comment]
I run the android project to find the exact location of the crash.
It happens in `fullAssetPathFrom` method in the `io.flutter.embedding.engine.loaderFileLoader.java` class file.
The method is:
```  
@NonNull
private String fullAssetPathFrom(@NonNull String filePath) {
   return flutterApplicationInfo.flutterAssetsDir + File.separator + filePath;
 }
```

and the reason of the crash is that the `flutterApplicationInfo` is null.

**Comment by geekydiamond** [comment]
Same issue. Moved back to version 0.10.11+1 and it is working for us.

**Comment by philiplindberg** [comment]
The latest version that works on Android seems to be 0.10.12+3.

**Comment by DannyBoyNg** [comment]
0.11.0 works fine as long as I use flutter 1.20.4. When I upgrade to flutter 1.22.0 it breaks.

**Comment by intraector** [comment]
same here

**Comment by pablopantaleon** [comment]
same here

**Comment by arpitjacob** [comment]
Same here breaks when I upgraded to 1.22 on android

**Comment by grantamos** [comment]
Also having this issue when using latest for both Flutter & video_player

**Comment by ponnamkarthik** [comment]
https://github.com/flutter/plugins/pull/3123

this PR Fixes it 

for temp till the PR merged and released you can use

```yaml
video_player:
    git:
      url: git@github.com:ponnamkarthik/plugins.git
      path: packages/video_player/video_player
```

**Comment by kofan** [comment]
Same problem for me with video_player 0.11.0 and flutter 1.22.1

**Comment by pythoneer** [comment]
I can confirm this behavior. Unfortunately i do not see an exception or error message. A downgrade of flutter to version 1.20 from 1.22 does "solve" the problem. 

@ponnamkarthik are you sure that pubspec.yaml entry does work? I am having problems getting it to work – nevertheless the diff looks quite small and is entirely constrained to the `video_player` plugin so it looks like we don't need a fix in flutter (and a hotfix release) but "just" a new version of the player i guess.

**Comment by ponnamkarthik** [comment]
@pythoneer the pubspec change will work I have did a pr to the plugins repo flutter tema is reviewing it till it's merged we can use from my fork repo to get it working

**Comment by geekydiamond** [comment]
I couldn't connect to your repo either @ponnamkarthik (although I did then see you had created ext_video_player so I'm now using that instead of having both video player and a youtube video player lol)

**Comment by iOSQiao** [comment]
Same problem for me with video_player 0.11.0 and flutter 1.22.1. It just crashed on Android.

**Comment by pythoneer** [comment]
@ponnamkarthik @geekydiamond the correct entry for the fix created by @ponnamkarthik  in the `pubspec.yaml` is

```yaml
  video_player:
    git:
      url: git://github.com/ponnamkarthik/plugins.git
      path: packages/video_player/video_player
```

I hope the pr is accepted soon.

**Comment by ponnamkarthik** [comment]
@pythoneer after some research I found that my implementation works but your public key is registered with GitHub 

Thanks for correcting it updated my above reply

**Comment by TahaTesser** [comment]
The app throws assertion on the assets tab in debugging mode on the official example  on latest `video_player: ^0.11.0` 

**Preview**
![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/95854043-fd7a8f80-0d73-11eb-8a6c-15f93babbc12.gif)


<details> 
<summary>complete code sample</summary> 

```dart
// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// ignore_for_file: public_member_api_docs

/// An example of using the plugin, controlling lifecycle and playback of the
/// video.

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(
    MaterialApp(
      home: _App(),
    ),
  );
}

class _App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 3,
      child: Scaffold(
        key: const ValueKey<String>('home_page'),
        appBar: AppBar(
          title: const Text('Video player example'),
          actions: <Widget>[
            IconButton(
              key: const ValueKey<String>('push_tab'),
              icon: const Icon(Icons.navigation),
              onPressed: () {
                Navigator.push<_PlayerVideoAndPopPage>(
                  context,
                  MaterialPageRoute<_PlayerVideoAndPopPage>(
                    builder: (BuildContext context) => _PlayerVideoAndPopPage(),
                  ),
                );
              },
            )
          ],
          bottom: const TabBar(
            isScrollable: true,
            tabs: <Widget>[
              Tab(
                icon: Icon(Icons.cloud),
                text: "Remote",
              ),
              Tab(icon: Icon(Icons.insert_drive_file), text: "Asset"),
              Tab(icon: Icon(Icons.list), text: "List example"),
            ],
          ),
        ),
        body: TabBarView(
          children: <Widget>[
            _BumbleBeeRemoteVideo(),
            _ButterFlyAssetVideo(),
            _ButterFlyAssetVideoInList(),
          ],
        ),
      ),
    );
  }
}

class _ButterFlyAssetVideoInList extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView(
      children: <Widget>[
        _ExampleCard(title: "Item a"),
        _ExampleCard(title: "Item b"),
        _ExampleCard(title: "Item c"),
        _ExampleCard(title: "Item d"),
        _ExampleCard(title: "Item e"),
        _ExampleCard(title: "Item f"),
        _ExampleCard(title: "Item g"),
        Card(
            child: Column(children: <Widget>[
          Column(
            children: <Widget>[
              const ListTile(
                leading: Icon(Icons.cake),
                title: Text("Video video"),
              ),
              Stack(
                  alignment: FractionalOffset.bottomRight +
                      const FractionalOffset(-0.1, -0.1),
                  children: <Widget>[
                    _ButterFlyAssetVideo(),
                    Image.asset('assets/flutter-mark-square-64.png'),
                  ]),
            ],
          ),
        ])),
        _ExampleCard(title: "Item h"),
        _ExampleCard(title: "Item i"),
        _ExampleCard(title: "Item j"),
        _ExampleCard(title: "Item k"),
        _ExampleCard(title: "Item l"),
      ],
    );
  }
}

/// A filler card to show the video in a list of scrolling contents.
class _ExampleCard extends StatelessWidget {
  const _ExampleCard({Key key, this.title}) : super(key: key);

  final String title;

  @override
  Widget build(BuildContext context) {
    return Card(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: <Widget>[
          ListTile(
            leading: const Icon(Icons.airline_seat_flat_angled),
            title: Text(title),
          ),
          ButtonBar(
            children: <Widget>[
              FlatButton(
                child: const Text('BUY TICKETS'),
                onPressed: () {
                  /* ... */
                },
              ),
              FlatButton(
                child: const Text('SELL TICKETS'),
                onPressed: () {
                  /* ... */
                },
              ),
            ],
          ),
        ],
      ),
    );
  }
}

class _ButterFlyAssetVideo extends StatefulWidget {
  @override
  _ButterFlyAssetVideoState createState() => _ButterFlyAssetVideoState();
}

class _ButterFlyAssetVideoState extends State<_ButterFlyAssetVideo> {
  VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.asset('assets/Butterfly-209.mp4');

    _controller.addListener(() {
      setState(() {});
    });
    _controller.setLooping(true);
    _controller.initialize().then((_) => setState(() {}));
    _controller.play();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Column(
        children: <Widget>[
          Container(
            padding: const EdgeInsets.only(top: 20.0),
          ),
          const Text('With assets mp4'),
          Container(
            padding: const EdgeInsets.all(20),
            child: AspectRatio(
              aspectRatio: _controller.value.aspectRatio,
              child: Stack(
                alignment: Alignment.bottomCenter,
                children: <Widget>[
                  VideoPlayer(_controller),
                  _PlayPauseOverlay(controller: _controller),
                  VideoProgressIndicator(_controller, allowScrubbing: true),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _BumbleBeeRemoteVideo extends StatefulWidget {
  @override
  _BumbleBeeRemoteVideoState createState() => _BumbleBeeRemoteVideoState();
}

class _BumbleBeeRemoteVideoState extends State<_BumbleBeeRemoteVideo> {
  VideoPlayerController _controller;

  Future<ClosedCaptionFile> _loadCaptions() async {
    final String fileContents = await DefaultAssetBundle.of(context)
        .loadString('assets/bumble_bee_captions.srt');
    return SubRipCaptionFile(fileContents);
  }

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
      'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4',
      closedCaptionFile: _loadCaptions(),
    );

    _controller.addListener(() {
      setState(() {});
    });
    _controller.setLooping(true);
    _controller.initialize();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Column(
        children: <Widget>[
          Container(padding: const EdgeInsets.only(top: 20.0)),
          const Text('With remote mp4'),
          Container(
            padding: const EdgeInsets.all(20),
            child: AspectRatio(
              aspectRatio: _controller.value.aspectRatio,
              child: Stack(
                alignment: Alignment.bottomCenter,
                children: <Widget>[
                  VideoPlayer(_controller),
                  ClosedCaption(text: _controller.value.caption.text),
                  _PlayPauseOverlay(controller: _controller),
                  VideoProgressIndicator(_controller, allowScrubbing: true),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _PlayPauseOverlay extends StatelessWidget {
  const _PlayPauseOverlay({Key key, this.controller}) : super(key: key);

  final VideoPlayerController controller;

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: <Widget>[
        AnimatedSwitcher(
          duration: Duration(milliseconds: 50),
          reverseDuration: Duration(milliseconds: 200),
          child: controller.value.isPlaying
              ? SizedBox.shrink()
              : Container(
                  color: Colors.black26,
                  child: Center(
                    child: Icon(
                      Icons.play_arrow,
                      color: Colors.white,
                      size: 100.0,
                    ),
                  ),
                ),
        ),
        GestureDetector(
          onTap: () {
            controller.value.isPlaying ? controller.pause() : controller.play();
          },
        ),
      ],
    );
  }
}

class _PlayerVideoAndPopPage extends StatefulWidget {
  @override
  _PlayerVideoAndPopPageState createState() => _PlayerVideoAndPopPageState();
}

class _PlayerVideoAndPopPageState extends State<_PlayerVideoAndPopPage> {
  VideoPlayerController _videoPlayerController;
  bool startedPlaying = false;

  @override
  void initState() {
    super.initState();

    _videoPlayerController =
        VideoPlayerController.asset('assets/Butterfly-209.mp4');
    _videoPlayerController.addListener(() {
      if (startedPlaying && !_videoPlayerController.value.isPlaying) {
        Navigator.pop(context);
      }
    });
  }

  @override
  void dispose() {
    _videoPlayerController.dispose();
    super.dispose();
  }

  Future<bool> started() async {
    await _videoPlayerController.initialize();
    await _videoPlayerController.play();
    startedPlaying = true;
    return true;
  }

  @override
  Widget build(BuildContext context) {
    return Material(
      elevation: 0,
      child: Center(
        child: FutureBuilder<bool>(
          future: started(),
          builder: (BuildContext context, AsyncSnapshot<bool> snapshot) {
            if (snapshot.data == true) {
              return AspectRatio(
                aspectRatio: _videoPlayerController.value.aspectRatio,
                child: VideoPlayer(_videoPlayerController),
              );
            } else {
              return const Text('waiting for video to load');
            }
          },
        ),
      ),
    );
  }
}

```

</details> 

<details> 
<summary>logs</summary> 

```bash
Launching lib/main.dart on RMX2001 in debug mode...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:55456/J9U0cI44N3k=/ws
I/GED     (12501): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 27, oppidx_max 27, oppidx_min 0
I/BufferQueue(12501): [unnamed-12501-0](this:0x7950622800,id:0,api:0,p:-1,c:-1) BufferQueue core=(12501:com.nevercode.triage)
E/libc    (12501): Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer(12501): [unnamed-12501-0](this:0x7950622800,id:0,api:0,p:-1,c:12501) connect(C): consumer=(12501:com.nevercode.triage) controlledByApp=true
E/libc    (12501): Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer(12501): [unnamed-12501-0](this:0x7950622800,id:0,api:0,p:-1,c:12501) setConsumerName: unnamed-12501-0
E/libc    (12501): Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer(12501): [SurfaceTexture-0-12501-0](this:0x7950622800,id:0,api:0,p:-1,c:12501) setConsumerName: SurfaceTexture-0-12501-0
W/evercode.triage(12501): type=1400 audit(0.0:114442): avc: denied { read } for name="u:object_r:debug_bq_dump_prop:s0" dev="tmpfs" ino=10945 scontext=u:r:untrusted_app_27:s0:c122,c257,c512,c768 tcontext=u:object_r:debug_bq_dump_prop:s0 tclass=file permissive=0
W/evercode.triag(12501): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (greylist, reflection, allowed)
I/ExoPlayerImpl(12501): Init 82220fe [ExoPlayerLib/2.9.6] [RMX2001L1, RMX2001, realme, 29]
I/System.out(12501): [socket] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
W/AudioCapabilities(12501): Unsupported mime audio/x-adpcm-ms
W/AudioCapabilities(12501): Unsupported mime audio/x-adpcm-dvi-ima
W/AudioCapabilities(12501): Unsupported mime audio/alac
W/AudioCapabilities(12501): Unsupported mime audio/ape
W/AudioCapabilities(12501): Unsupported mime audio/ffmpeg
W/AudioCapabilities(12501): Unsupported mime audio/x-ms-wma
W/VideoCapabilities(12501): Unsupported mime video/divx
W/VideoCapabilities(12501): Unsupported mime video/divx3
W/VideoCapabilities(12501): Unrecognized profile/level 1/32 for video/mp4v-es
W/VideoCapabilities(12501): Unrecognized profile/level 32768/2 for video/mp4v-es
W/VideoCapabilities(12501): Unrecognized profile/level 32768/64 for video/mp4v-es
W/VideoCapabilities(12501): Unsupported mime video/ffmpeg
W/VideoCapabilities(12501): Unsupported mime video/x-ms-wmv
W/VideoCapabilities(12501): Unsupported mime video/xvid
W/VideoCapabilities(12501): Unrecognized profile/level 1/32 for video/mp4v-es
I/MediaCodec(12501): CreateByComponentName(), name = OMX.MTK.VIDEO.DECODER.AVC
I/MediaCodec(12501): new MediaCodec()
D/ACodec  (12501): ACodec() multimedia.audio.effect.type = dirac
I/OMXClient(12501): IOmx service obtained
I/MediaCodec(12501): configure()
D/SurfaceUtils(12501): connecting to surface 0x79d4f7c010, reason connectToSurface
D/Surface (12501): Surface::connect(this=0x79d4f7c000,api=3)
I/BufferQueueProducer(12501): [SurfaceTexture-0-12501-0](this:0x7950622800,id:0,api:3,p:12501,c:12501) connect(P): api=3 producer=(12501:com.nevercode.triage) producerControlledByApp=true
I/MediaCodec(12501): [OMX.MTK.VIDEO.DECODER.AVC] setting surface generation to 12801025
D/SurfaceUtils(12501): disconnecting from surface 0x79d4f7c010, reason connectToSurface(reconnect)
D/Surface (12501): Surface::disconnect(this=0x79d4f7c000,api=3)
I/BufferQueueProducer(12501): [SurfaceTexture-0-12501-0](this:0x7950622800,id:0,api:3,p:12501,c:12501) disconnect(P): api 3
D/SurfaceUtils(12501): connecting to surface 0x79d4f7c010, reason connectToSurface(reconnect)
D/Surface (12501): Surface::connect(this=0x79d4f7c000,api=3)
I/BufferQueueProducer(12501): [SurfaceTexture-0-12501-0](this:0x7950622800,id:0,api:3,p:12501,c:12501) connect(P): api=3 producer=(12501:com.nevercode.triage) producerControlledByApp=true
I/ACodec  (12501): codec does not support config priority (err -1010)
I/MtkACodec(12501): setMTKParameters, width: 1280
I/MtkACodec(12501): setMTKParameters, height: 720
I/MtkACodec(12501): set rotation-degrees 0
E/MtkACodec(12501): setConfig(OMX_CONFIG_ROTATIONTYPE) returned error 0xfffffc0e
E/ACodec  (12501): [OMX.MTK.VIDEO.DECODER.AVC] failed to setViLTEParameters 1
I/MediaCodec(12501): Video start()
D/SurfaceUtils(12501): set up nativeWindow 0x79d4f7c010 for 1280x720, color 0x7f000001, rotation 0, usage 0x402933
W/ACodec  (12501): [OMX.MTK.VIDEO.DECODER.AVC] setting nBufferCountActual to 6 failed: -22
D/Surface (12501): Surface::setBufferCount(this=0x79d4f7c000,bufferCount=5)
I/MediaCodec(12501): CreateByComponentName(), name = c2.android.aac.decoder
I/MediaCodec(12501): new MediaCodec()
W/Gralloc3(12501): allocator 3.x is not supported
E/ion     (12501): ioctl c0044901 failed with code -1: Invalid argument
D/CCodec  (12501): allocate(c2.android.aac.decoder)
I/Codec2Client(12501): Available Codec2 services: "software"
I/Codec2Client(12501): Creating a Codec2 client to service "software"
I/Codec2Client(12501): Client to Codec2 service "software" created
I/CCodec  (12501): Created component [c2.android.aac.decoder]
D/CCodecConfig(12501): read media type: audio/mp4a-latm
D/BufferQueueProducer(12501): [SurfaceTexture-0-12501-0](this:0x7950622800,id:0,api:3,p:12501,c:12501) cancelBuffer: slot 0
D/SurfaceUtils(12501): set up nativeWindow 0x79d4f7c010 for 1280x720, color 0x7f000001, rotation 0, usage 0x402933
W/ACodec  (12501): [OMX.MTK.VIDEO.DECODER.AVC] setting nBufferCountActual to 20 failed: -22
D/Surface (12501): Surface::setBufferCount(this=0x79d4f7c000,bufferCount=19)
D/ReflectedParamUpdater(12501): extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater(12501): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater(12501): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater(12501): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater(12501): extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater(12501): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater(12501): extent() != 1 for single value type: algo.buffers.pool-ids.values
I/CCodecConfig(12501): query failed after returning 17 values (BAD_INDEX)
D/CCodecConfig(12501): c2 config is Dict {
D/CCodecConfig(12501):   c2::u32 coded.aac-packaging.value = 0
D/CCodecConfig(12501):   c2::u32 coded.bitrate.value = 64000
D/CCodecConfig(12501):   c2::u32 coded.pl.level = 0
D/CCodecConfig(12501):   c2::u32 coded.pl.profile = 8192
D/CCodecConfig(12501):   c2::float coding.drc.attenuation-factor.value = 1
D/CCodecConfig(12501):   c2::float coding.drc.boost-factor.value = 1
D/CCodecConfig(12501):   c2::i32 coding.drc.compression-mode.value = 3
D/CCodecConfig(12501):   c2::i32 coding.drc.effect-type.value = 3
D/CCodecConfig(12501):   c2::float coding.drc.encoded-level.value = 0.25
D/CCodecConfig(12501):   c2::float coding.drc.reference-level.value = -16
D/CCodecConfig(12501):   c2::u32 input.buffers.max-size.value = 8192
D/CCodecConfig(12501):   c2::u32 input.delay.value = 0
D/CCodecConfig(12501):   string input.media-type.value = "audio/mp4a-latm"
D/CCodecConfig(12501):   c2::u32 output.delay.value = 2
D/CCodecConfig(12501):   string output.media-type.value = "audio/raw"
D/CCodecConfig(12501):   c2::u32 raw.channel-count.value = 1
D/CCodecConfig(12501):   c2::u32 raw.max-channel-count.value = 8
D/CCodecConfig(12501):   c2::u32 raw.sample-rate.value = 44100
D/CCodecConfig(12501): }
I/MediaCodec(12501): configure()
D/CCodecConfig(12501): config failed => CORRUPTED
D/CCodecConfig(12501): c2 config is Dict {
D/CCodecConfig(12501):   c2::u32 coded.aac-packaging.value = 0
D/CCodecConfig(12501):   c2::u32 coded.bitrate.value = 64000
D/CCodecConfig(12501):   c2::u32 coded.pl.level = 0
D/CCodecConfig(12501):   c2::u32 coded.pl.profile = 8192
D/CCodecConfig(12501):   c2::float coding.drc.attenuation-factor.value = 1
D/CCodecConfig(12501):   c2::float coding.drc.boost-factor.value = 1
D/CCodecConfig(12501):   c2::i32 coding.drc.compression-mode.value = 3
D/CCodecConfig(12501):   c2::i32 coding.drc.effect-type.value = 3
D/CCodecConfig(12501):   c2::float coding.drc.encoded-level.value = 0.25
D/CCodecConfig(12501):   c2::float coding.drc.reference-level.value = -16
D/CCodecConfig(12501):   c2::u32 input.buffers.max-size.value = 8192
D/CCodecConfig(12501):   c2::u32 input.delay.value = 0
D/CCodecConfig(12501):   string input.media-type.value = "audio/mp4a-latm"
D/CCodecConfig(12501):   c2::u32 output.delay.value = 2
D/CCodecConfig(12501):   string output.media-type.value = "audio/raw"
D/CCodecConfig(12501):   c2::u32 raw.channel-count.value = 2
D/CCodecConfig(12501):   c2::u32 raw.max-channel-count.value = 8
D/CCodecConfig(12501):   c2::u32 raw.sample-rate.value = 48000
D/CCodecConfig(12501): }
W/Codec2Client(12501): query -- param skipped: index = 1107298332.
D/CCodec  (12501): client requested max input size 628, which is smaller than what component recommended (8192); overriding with component recommendation.
W/CCodec  (12501): This behavior is subject to change. It is recommended that app developers double check whether the requested max input size is in reasonable range.
D/CCodec  (12501): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  (12501):   int32_t aac-max-output-channel_count = 8
D/CCodec  (12501):   int32_t channel-count = 2
D/CCodec  (12501):   int32_t level = 0
D/CCodec  (12501):   int32_t max-input-size = 8192
D/CCodec  (12501):   string mime = "audio/mp4a-latm"
D/CCodec  (12501):   int32_t profile = 2
D/CCodec  (12501):   int32_t sample-rate = 48000
D/CCodec  (12501): } and output: AMessage(what = 0x00000000) = {
D/CCodec  (12501):   int32_t aac-max-output-channel_count = 8
D/CCodec  (12501):   int32_t channel-count = 2
D/CCodec  (12501):   string mime = "audio/raw"
D/CCodec  (12501):   int32_t sample-rate = 48000
D/CCodec  (12501): }
I/MediaCodec(12501): Audio start()
W/Codec2Client(12501): query -- param skipped: index = 1342179345.
W/Codec2Client(12501): query -- param skipped: index = 2415921170.
W/Codec2Client(12501): query -- param skipped: index = 1610614798.
D/CCodecBufferChannel(12501): [c2.android.aac.decoder#316] Created input block pool with allocatorID 16 => poolID 17 - OK (0)
I/CCodecBufferChannel(12501): [c2.android.aac.decoder#316] Created output block pool with allocatorID 16 => poolID 1086 - OK
D/CCodecBufferChannel(12501): [c2.android.aac.decoder#316] Configured output block pool ids 1086 => OK
D/CCodecConfig(12501): c2 config is Dict {
D/CCodecConfig(12501):   c2::u32 coded.aac-packaging.value = 0
D/CCodecConfig(12501):   c2::u32 coded.bitrate.value = 64000
D/CCodecConfig(12501):   c2::u32 coded.pl.level = 0
D/CCodecConfig(12501):   c2::u32 coded.pl.profile = 8192
D/CCodecConfig(12501):   c2::i32 coding.drc.album-mode.value = 0
D/CCodecConfig(12501):   c2::float coding.drc.attenuation-factor.value = 1
D/CCodecConfig(12501):   c2::float coding.drc.boost-factor.value = 1
D/CCodecConfig(12501):   c2::i32 coding.drc.compression-mode.value = 1
D/CCodecConfig(12501):   c2::i32 coding.drc.effect-type.value = 3
D/CCodecConfig(12501):   c2::float coding.drc.encoded-level.value = 0.25
D/CCodecConfig(12501):   c2::float coding.drc.reference-level.value = -16
D/CCodecConfig(12501):   c2::u32 input.buffers.max-size.value = 8192
D/CCodecConfig(12501):   c2::u32 input.delay.value = 0
D/CCodecConfig(12501):   string input.media-type.value = "audio/mp4a-latm"
D/CCodecConfig(12501):   c2::u32 output.delay.value = 2
D/CCodecConfig(12501):   string output.media-type.value = "audio/raw"
D/CCodecConfig(12501):   c2::u32 raw.channel-count.value = 2
D/CCodecConfig(12501):   c2::u32 raw.max-channel-count.value = 8
D/CCodecConfig(12501):   c2::u32 raw.sample-rate.value = 48000
D/CCodecConfig(12501): }
D/mmscene (12501): open config fail
D/mmscene (12501): config version remote=, local=20191205
D/mmscene (12501): use local config: r=, l=20191205
D/mmscene (12501): getHint applicationScene=com.nevercode.triage,idx=5 none
D/OppoSmartVolume(12501): mEnginerringFeatureSwtich:1, mSmartVolumeAPKSwtich:-22, mSmartVolumePcmDumpSwitch:0
D/OppoSmartVolume(12501): mWechatDbLevel:19, mWechatUseDynamicMode:1
D/IAtlas  (12501): IAtlas::init CallingPid 12501
D/IAtlas  (12501): IAtlas::init this 0x79d3ed4f00
D/AudioTrack(12501): set(): 0x79d3fa9d00, streamType -1, sampleRate 48000, format 0x1, channelMask 0x3, frameCount 12000, flags #0, notificationFrames 0, sessionId 0, transferType 3, uid -1, pid -1
D/AudioTrack(12501): set() multimedia.audio.effect.type = dirac
D/MMListParser(12501): onlineVersion -1 defaultVersion 20200122
E/AudioTrack(12501): filename is /proc/12501/cmdline
W/AudioTrack(12501): Get process name fail
E/AudioTrack(12501): process name is com.nevercode.triage
D/AudioTrack(12501): set(): Building AudioTrack with attributes: usage = 1, content = 3, flags = 0xa00, tags = []
D/AudioTrack(12501): set(): 0x79d3fa9d00, Create AudioTrackThread, tid = 12597
D/AudioTrack(12501): createTrack state 0 output.outputId=21
D/AudioTrack(12501): createTrack_l(2409): 0x79d3fa9d00, mCblk = 0x7917126000, mLatency = 378, mAfLatency = 128, frameCount = 12000, mSampleRate = 48000, mFlags = 0x8, mReqFrameCount = 12000, mNotificationFramesAct = 6000
D/AudioTrack(12501): setVolume(2409): 0x79d3fa9d00, left = 1.000000, right = 1.000000
I/GPUD    (12501): @gpudInitialize: successfully initialized with GPUD, dbg=0 mmdump_dbg=0 mmpath_dbg=0
I/GPUAUX  (12501): [AUX]GPUAUXContext:69: create: 0x79374bc480
W/1.raster(12501): type=1400 audit(0.0:114447): avc: granted { open } for path="/dev/ashmem" dev="tmpfs" ino=17464 scontext=u:r:untrusted_app_27:s0:c122,c257,c512,c768 tcontext=u:object_r:ashmem_device:s0 tclass=chr_file
D/ColorViewRootUtil(12501): nav gesture mode swipeFromBottom ignore false downY 913 mScreenHeight 2400 mScreenWidth 1080 mStatusBarHeight 54 globalScale 1.125 nav mode 3 event MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=506.0, y[0]=913.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x2, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=262579219, downTime=262579219, deviceId=3, source=0x1002, displayId=0 } rotation 0
D/AudioTrack(12501): start(2409): 0x79d3fa9d00, prior state:STATE_STOPPED
D/AudioTrack(12501): getTimestamp_l(2409): device stall time corrected using current time 262579478099111
W/1.raster(12501): type=1400 audit(0.0:114453): avc: granted { open } for path="/dev/ashmem" dev="tmpfs" ino=17464 scontext=u:r:untrusted_app_27:s0:c122,c257,c512,c768 tcontext=u:object_r:ashmem_device:s0 tclass=chr_file
I/BufferQueueProducer(12501): [SurfaceTexture-0-12501-0](this:0x7950622800,id:0,api:3,p:12501,c:12501) queueBuffer: slot 4 is dropped, handle=0x794a21cac0
I/MediaCodec(12501): (0x797ca8ac00) Decoder: mInputBufCnt = 8 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 3 fps
W/1.raster(12501): type=1400 audit(0.0:114454): avc: granted { open } for path="/dev/ashmem" dev="tmpfs" ino=17464 scontext=u:r:untrusted_app_27:s0:c122,c257,c512,c768 tcontext=u:object_r:ashmem_device:s0 tclass=chr_file
I/BufferQueueProducer(12501): [SurfaceTexture-0-12501-0](this:0x7950622800,id:0,api:3,p:12501,c:12501) queueBuffer: slot 13 is dropped, handle=0x7921a6c000
D/ColorViewRootUtil(12501): nav gesture mode swipeFromBottom ignore false downY 958 mScreenHeight 2400 mScreenWidth 1080 mStatusBarHeight 54 globalScale 1.125 nav mode 3 event MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=541.0, y[0]=958.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x2, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=262580231, downTime=262580231, deviceId=3, source=0x1002, displayId=0 } rotation 0
I/BufferQueueProducer(12501): [SurfaceTexture-0-12501-0](this:0x7950622800,id:0,api:3,p:12501,c:12501) queueBuffer: slot 8 is dropped, handle=0x794a21d880
D/AudioTrack(12501): pause(2409): 0x79d3fa9d00, prior state:STATE_ACTIVE
D/ColorViewRootUtil(12501): nav gesture mode swipeFromBottom ignore false downY 444 mScreenHeight 2400 mScreenWidth 1080 mStatusBarHeight 54 globalScale 1.125 nav mode 3 event MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=532.0, y[0]=444.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x2, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=262580997, downTime=262580997, deviceId=3, source=0x1002, displayId=0 } rotation 0
I/BufferQueue(12501): [unnamed-12501-1](this:0x794a321000,id:1,api:0,p:-1,c:-1) BufferQueue core=(12501:com.nevercode.triage)
W/evercode.triage(12501): type=1400 audit(0.0:114455): avc: denied { read } for name="u:object_r:debug_bq_dump_prop:s0" dev="tmpfs" ino=10945 scontext=u:r:untrusted_app_27:s0:c122,c257,c512,c768 tcontext=u:object_r:debug_bq_dump_prop:s0 tclass=file permissive=0
E/libc    (12501): Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer(12501): [unnamed-12501-1](this:0x794a321000,id:1,api:0,p:-1,c:12501) connect(C): consumer=(12501:com.nevercode.triage) controlledByApp=true
E/libc    (12501): Access denied finding property "vendor.debug.bq.dump"
W/evercode.triage(12501): type=1400 audit(0.0:114456): avc: denied { read } for name="u:object_r:debug_bq_dump_prop:s0" dev="tmpfs" ino=10945 scontext=u:r:untrusted_app_27:s0:c122,c257,c512,c768 tcontext=u:object_r:debug_bq_dump_prop:s0 tclass=file permissive=0
I/BufferQueueConsumer(12501): [unnamed-12501-1](this:0x794a321000,id:1,api:0,p:-1,c:12501) setConsumerName: unnamed-12501-1
W/evercode.triage(12501): type=1400 audit(0.0:114457): avc: denied { read } for name="u:object_r:debug_bq_dump_prop:s0" dev="tmpfs" ino=10945 scontext=u:r:untrusted_app_27:s0:c122,c257,c512,c768 tcontext=u:object_r:debug_bq_dump_prop:s0 tclass=file permissive=0
E/libc    (12501): Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer(12501): [SurfaceTexture-0-12501-1](this:0x794a321000,id:1,api:0,p:-1,c:12501) setConsumerName: SurfaceTexture-0-12501-1
I/BufferQueue(12501): [SurfaceTexture-0-12501-1](this:0x794a321000,id:1,api:0,p:-1,c:-1) ~BufferQueueCore
I/SurfaceView(12501): 68987751 visibleChanged:true -> SurfaceHolder.Callback.surfaceDestroyed
E/flutter (12501): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/services/message_codec.dart': Failed assertion: line 111 pos 15: 'code != null': is not true.
[38;5;244mE/flutter (12501): #0      _AssertionError._doThrowNew  (dart:core-patch/errors_patch.dart:46:39))[39;49m
[38;5;244mE/flutter (12501): #1      _AssertionError._throwNew  (dart:core-patch/errors_patch.dart:36:5))[39;49m
[38;5;244mE/flutter (12501): #2      new PlatformException[39;49m 
 package:flutter/…/services/message_codec.dart
[38;5;248mE/flutter (12501): #3      VideoPlayerApi.create[39;49m 
 package:video_player_platform_interface/messages.dart
E/flutter (12501): <asynchronous suspension>
[38;5;248mE/flutter (12501): #4      MethodChannelVideoPlayer.create[39;49m 
 package:video_player_platform_interface/method_channel_video_player.dart
[38;5;248mE/flutter (12501): #5      VideoPlayerController.initialize[39;49m 
 package:video_player/video_player.dart
[38;5;248mE/flutter (12501): #6      _ButterFlyAssetVideoState.initState[39;49m 
 package:triage/main.dart
[38;5;244mE/flutter (12501): #7      StatefulElement._firstBuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #8      ComponentElement.mount[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #9      Element.inflateWidget[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #10     Element.updateChild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #11     ComponentElement.performRebuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #12     Element.rebuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #13     ComponentElement._firstBuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #14     ComponentElement.mount[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #15     Element.inflateWidget[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #16     Element.updateChild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #17     SingleChildRenderObjectElement.mount[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #18     Element.inflateWidget[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #19     Element.updateChild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #20     SingleChildRenderObjectElement.mount[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #21     Element.inflateWidget[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #22     Element.updateChild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #23     ComponentElement.performRebuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #24     Element.rebuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #25     ComponentElement._firstBuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #26     ComponentElement.mount[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #27     Element.inflateWidget[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #28     Element.updateChild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #29     ComponentElement.performRebuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #30     Element.rebuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #31     ComponentElement._firstBuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #32     ComponentElement.mount[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #33     Element.inflateWidget[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #34     Element.updateChild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #35     ComponentElement.performRebuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #36     StatefulElement.performRebuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #37     Element.rebuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #38     ComponentElement._firstBuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #39     StatefulElement._firstBuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #40     ComponentElement.mount[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #41     Element.inflateWidget[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #42     Element.updateChild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #43     ComponentElement.performRebuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (12501): #44     Element.rebuild[39;49m 
 package:flutter/…/widgets/framework.dart
D/RefBase (12501): RefBase: Explicit destruction, weak count = 0 (in 0x7937392e28)
W/RefBase (12501): CallStack::getCurrentInternal not linked, returning null
W/RefBase (12501): CallStack::logStackInternal not linked
I/GPUAUX  (12501): [AUX]~GPUAUXContext:77: destory: 0x79374bc480
D/Surface (12501): Surface::disconnect(this=0x79503be000,api=1)
D/ViewRootImpl(12501): setSurfaceViewCreated, created:false
D/Surface (12501): Surface::disconnect(this=0x79503be000,api=-1)
D/SurfaceView(12501): updateScreenMode w:0 h:0 ViewRoot w:1080 h:2400
D/SurfaceView(12501): try to resquest 90Hz
D/ViewRootImpl(12501): set screen refresh mode 0 due to SurfaceView-68987751
D/Surface (12501): Surface::disconnect(this=0x79503bc000,api=1)
E/ANR_LOG (12501): >>> msg's executing time is too long
E/ANR_LOG (12501): Blocked msg = { when=-21s119ms what=0 target=android.view.Choreographer$FrameHandler callback=android.view.Choreographer$FrameDisplayEventReceiver } , cost  = 21119 ms
E/ANR_LOG (12501): >>>Current msg List is:
I/GED     (12501): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 27, oppidx_max 27, oppidx_min 0
E/ANR_LOG (12501): Current msg <1>  = { when=-3d0h56m49s961ms what=1 target=android.view.Choreographer$FrameHandler }
E/ANR_LOG (12501): Current msg <2>  = { when=-21s120ms what=159 target=android.app.ActivityThread$H obj=ClientTransaction hashCode, mActivityToken = android.os.BinderProxy@d64a4b4 }
E/ANR_LOG (12501): >>>CURRENT MSG DUMP OVER<<<
V/PhoneWindow(12501): DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@856b268, this = DecorView@25a4f05[MainActivity]

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel dev, 1.23.0-13.0.pre, on Mac OS X 10.15.7 19H2 x86_64,
    locale en-GB)
    • Flutter version 1.23.0-13.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 4fa4f91d5c (7 days ago), 2020-10-06 12:31:25 -0700
    • Engine revision 443cd5a1e1
    • Dart version 2.11.0 (build 2.11.0-186.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

 
[✓] Connected device (1 available)            
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64 • Android 10 (API 29)

• No issues found!

```

</details>

**Comment by gpprshnth** [comment]
dependencies:
  video_player: 0.10.11+1

This should take care of this issue.

**Comment by llucax** [comment]
You can go as high as `0.10.12+3`, but of course this is just a workaround until the issue is fixed. The issue was introduced exactly in the only commit done for `0.10.12+4`, here are more details: https://github.com/flutter/flutter/issues/68010.

**Comment by hyobbb** [comment]
on flutter 1.22.2 stable & video player 0.10.12+3 it works but throw error when the video player version gets higher.

**Comment by huihliu** [comment]
flutter 1.22.2 stable & video player 0.10.12+3 does not work for me. I am new to flutter and am using the example program in the flutter chewie package to learn. All I did was to change VideoPlayerController.network  to VideoController.asset (with pubspec.yaml  change to add asset ) . The chewie example program is here:       https://pub.dev/packages/chewie/example

**Comment by Christyansoft** [comment]
already fixed the problem ?

**Comment by Vanessa-Berazategui** [comment]
I have the same problem with flutter 1.22.3 and chewie 0.9.10 (video_player: ">=0.7.0 <0.11.0"). I had to downgrade flutter to version 1.20.4 to get it working.

**Comment by cyanglaz** [comment]
Fixed with https://github.com/flutter/plugins/pull/3123, closing the issue.

**Comment by huihliu** [comment]
Thanks !

**Comment by samuelezedi** [comment]
> 0.10.11+1

This worked.

**Comment by smedic** [comment]
[✓] Flutter (Channel unknown, 1.22.3, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.22.3 at /Users/smedic/fvm/versions/1.22.3
    • Framework revision 8874f21e79 (3 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

I see this error. I saw somebody said it's fixed but I still can reproduce it on  video_player: ^1.0.1

`'package:flutter/src/services/message_codec.dart': Failed assertion: line 111 pos 15: 'code != null': is not true., stack: #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
I/flutter (22365): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
I/flutter (22365): #2      new PlatformException (package:flutter/src/services/message_codec.dart:111:15)
I/flutter (22365): #3      VideoPlayerApi.create (package:video_player_platform_interface/messages.dart:205:13)
I/flutter (22365): <asynchronous suspension>
I/flutter (22365): #4      MethodChannelVideoPlayer.create (package:video_player_platform_interface/method_channel_video_player.dart:46:42)
I/flutter (22365): #5      VideoPlayerController.initialize (package:video_player/video_player.dart:282:45)`

Any ideas?

**Comment by vivekkhurana** [comment]
Issue is still present in flutter version 1.22.4 and plugin version ^1.0.1. Here is the error log 

```
E/flutter (18071): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/services/message_codec.dart': Failed assertion: line 111 pos 15: 'code != null': is not true.
E/flutter (18071): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (18071): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (18071): #2      new PlatformException (package:flutter/src/services/message_codec.dart:111:15)
E/flutter (18071): #3      VideoPlayerApi.create (package:video_player_platform_interface/messages.dart:205:13)
E/flutter (18071): <asynchronous suspension>
E/flutter (18071): #4      MethodChannelVideoPlayer.create (package:video_player_platform_interface/method_channel_video_player.dart:46:42)
E/flutter (18071): #5      VideoPlayerController.initialize (package:video_player/video_player.dart:282:45)
E/flutter (18071): #6      _VideoDialogState.initState (package:joytish/widgets/videodialog.dart:21:9)
E/flutter (18071): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)

```

flutter doctor output

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-GB)
    • Flutter version 1.22.4 at /Users/apple/flutter
    • Framework revision 1aafb3a8b9 (2 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-30, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0


```

**Comment by Lix-ai** [comment]
Same... issue >_<

**Comment by yashbansal042** [comment]
The issue is still not working with flutter version 1.22.5. Did anyone get a fix apart from downgrading the flutter version.

**Comment by TahaTesser** [comment]
@vivekkhurana  @yash1200  @smedic  
I just tried to reproduce the issue again using `video_player: ^1.0.1` on the latest `Channel stable, 1.22.5`.
Running in debug mode, no exception when loading asset video from the  [official example ](https://github.com/flutter/plugins/tree/master/packages/video_player/video_player/example) on a physical or emulator

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D          • android-arm64 • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios           • iOS 14.3

! Doctor found issues in 1 category.
```

</details>
