### ISSUE TITLE
flutter_test doesn't break on breakpoints in some files

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#66832]
## Steps to Reproduce

please clone https://github.com/escamoteur/get_it_mixin/tree/breakpoint-bug

set a breakpoint as shown in this screenshot:

![image](https://user-images.githubusercontent.com/16635729/94457519-f456c380-01b4-11eb-83fd-fe2d16922778.png)

And start a debug run of the first test. It won't stop at the breakpoint.

VS code shows this break points like this

![image](https://user-images.githubusercontent.com/16635729/94458836-cc685f80-01b6-11eb-826a-a207bdf80978.png)

And when you hover about them tells me 'unverified breakpoint'
I also tried Android Studio but it too doesn't break

I tried with this setup:

```
C:\Entwicklung\packages\get_it_mixin>flutter doctor -v
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18362.1082], locale de-DE)
    • Flutter version 1.20.4 at C:\Entwicklung\Flutter
    • Framework revision fba99f6cf9 (2 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\escam\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.49.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.14.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
````

and with 

```` 
C:\Entwicklung\packages\get_it_mixin>flutter doctor -v     
[√] Flutter (Channel master, 1.22.0-10.0.pre.386, on Microsoft Windows [Version 10.0.18362.1082], locale de-DE)
    • Flutter version 1.22.0-10.0.pre.386 at C:\Entwicklung\Flutter
    • Framework revision 8db31a556b (4 hours ago), 2020-09-28 14:32:00 +0200
    • Engine revision 3a73d073c8
    • Dart version 2.11.0 (build 2.11.0-161.0.dev)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)    
    • Android SDK at C:\Users\escam\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30413.136
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.49.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.18362.1082]
```

If you use the mixin inside a real app, the breakpoints work

**Comment by csells** [comment]
I believe this is a timing issue with the debugger. @devoncarew is this a known issue?

**Comment by escamoteur** [comment]
but way only in this file, and why are the breakpoints marked disabled while executing?

**Comment by devoncarew** [comment]
Is it just that assert line or do you see the same behavior with other lines?

**Comment by escamoteur** [comment]
It happens anywhere in that file

**Comment by TahaTesser** [comment]
Hi @escamoteur 
Using your code sample I does break on the assert breakpoint and I can't find  anywhere where it says  'unverified breakpoint'
![image](https://user-images.githubusercontent.com/48603081/94807906-e780dc80-040d-11eb-8084-6ed97174e27a.png)
<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.20.4 at C:\Code\flutter_stable
    • Framework revision fba99f6cf9 (2 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.49.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)

• No issues found!
```

</details>

**Comment by escamoteur** [comment]
It only happens if you debug the test. not the sample app, there they work

**Comment by TahaTesser** [comment]
Hi @escamoteur 
That's my bad, I can reproduce it now 
### Code Sample
https://github.com/escamoteur/get_it_mixin/tree/breakpoint-bug
### Screenshot
![image](https://user-images.githubusercontent.com/48603081/94811846-86f49e00-0413-11eb-906b-b99a45db2262.png)
<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutt er version 1.20.4 at C:\Code\flutter_stable
    • Framework revision fba99f6cf9 (2 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.49.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)

• No issues found!
```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.450, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.22.0-10.0.pre.450 at C:\Code\flutter_master
    • Framework revision 9d41ddcbac (7 hours ago), 2020-10-01 08:01:58 +0200
    • Engine revision 612acf349e
    • Dart version 2.11.0 (build 2.11.0-180.0.dev)


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30523.141
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.49.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[✓] Connected device (5 available)
    • RMX2001 (mobile)                      • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • Android SDK built for x86 64 (mobile) • emulator-5554    • android-x64    • Android 9 (API 28) (emulator)
    • Windows (desktop)                     • windows          • windows-x64    • Microsoft Windows [Version
      10.0.19041.508]
    • Web Server (web)                      • web-server       • web-javascript • Flutter Tools
    • Chrome (web)                          • chrome           • web-javascript • Google Chrome 85.0.4183.121

• No issues found!
```

</details>

**Comment by escamoteur** [comment]
It's extremely annoying. I currently debug with print statements.

**Comment by devoncarew** [comment]
cc @DanTup

**Comment by DanTup** [comment]
This looks like the same issue reported at https://github.com/Dart-Code/Dart-Code/issues/2461

When adding a breakpoint the VM responds with an error:

```
{
	"jsonrpc": "2.0",
	"error": {
		"code": 102,
		"message": "Cannot add breakpoint",
		"data": {
			"request": {
				"method": "addBreakpointWithScriptUri",
				"params": {
					"isolateId": "isolates/3327579749583871",
					"scriptUri": "file:///private/tmp/get_it_mixin/lib/src/mix_in.dart",
					"line": "424"
				}
			},
			"details": "addBreakpointWithScriptUri: Cannot add breakpoint at line '424'"
		}
	},
	"id": "752"
}
```

If I try to add the breakpoint via Observatory using the package URI, I get this:

```
break package:get_it_mixin/src/mix_in.dart:424
Script 'package:get_it_mixin/src/mix_in.dart' is ambiguous
```

In the other issue, I hacked a call to getScripts() in and ran it, and found the script was loaded twice - I suspect the same would be true here.

```
{
	"type": "@Script",
	"fixedId": true,
	"id": "libraries\/@23474256\/scripts\/package%3Afazua_toolbox%2Fwidgets%2Fquestionnaire_lib%2Fquestionnaire_bloc.dart\/1722782b696",
	"uri": "package:fazua_toolbox\/widgets\/questionnaire_lib\/questionnaire_bloc.dart",
	"_kind": "kernel"
},
{
	"type": "@Script",
	"fixedId": true,
	"id": "libraries\/@27439137\/scripts\/package%3Afazua_toolbox%2Fwidgets%2Fquestionnaire_lib%2Fquestionnaire_bloc.dart\/1722782b664",
	"uri": "package:fazua_toolbox\/widgets\/questionnaire_lib\/questionnaire_bloc.dart",
	"_kind": "kernel"
},
```

I'm not sure why it's being loaded twice (they seem to have different library IDs in the script ID), it may need an opinion from the VM team (cc @bkonyi).

**Comment by bkonyi** [comment]
Strange that we're seeing two of the same script with exactly the same URI but different ID. I'll take a look, but maybe @rmacnak-google has insight as to why this can happen.

**Comment by ricbat9000** [comment]
Started happening this to me too, any updates on this ?

**Comment by DanTup** [comment]
@nfsxreloader if downgrading only the VS Code extensions fixed anything (without changing Flutter/Dart SDK versions) that sounds like a bug that should be fixed. If you can provide some specific details of what wasn't working on the latest version in an issue at https://github.com/Dart-Code/Dart-Code/issues, I'd like to take a look. Thanks!

**Comment by dolpheen** [comment]
Same here
Debugger in VSCode stopped work 
VScode plugins downgrade, flutter downgrade do not help
`[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale ru-RU)
    • Flutter version 1.22.2 at /Users/vadimlukicev/development/flutter
    • Framework revision 84f3d28555 (7 дней назад), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/vadimlukicev/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • Mi 9T (mobile) • aba16ce4 • android-arm64 • Android 10 (API 29)`

**Comment by acoutts** [comment]
I've had the same issue myself. Breakpoints not working.

**Comment by acoutts** [comment]
For what it's worth I tried Code with Dart-Code 3.14.1 and it was still broken there, seems like a flutter issue then.

**Comment by escamoteur** [comment]
I encountered the same problem when trying to debug parts of the Flutter framework while working on a PR.
I'm on latest master. 
It happens in VS code and in AS

**Comment by escamoteur** [comment]
@csells some others could also reproduce it inside the flutter repo

**Comment by knaeckeKami** [comment]
I can confirm the behavior that @escamoteur described, too, on Android Studio 4.1.1 / Flutter Plugin 51.0.2/  Flutter Stable 1.22.4.

**Comment by letsar** [comment]
I can also confirm this
```bash
[✓] Flutter (Channel stable, 1.22.3)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] VS Code (version 1.51.0)
```

**Comment by 2dxgujun** [comment]
Could not set breakpoint on mixin method after Hot Restart, Flutter Stable 1.22.4

**Comment by bkonyi** [comment]
I've been able to reproduce with a small example:

```dart
/// test_project/test/test.dart
import 'package:flutter_test/flutter_test.dart';

import 'package:test_project/main.dart';

void main() {
  test('Counter increments smoke test', () async {
    print(foo());
  });
}
```

```dart
/// test_project/lib/main.dart
int foo() {
  // breakpoint here
  return 0;
}
```

However, making a single change seems to allow for us to hit breakpoints: 

```dart
/// test_project/test/test.dart
import 'package:flutter_test/flutter_test.dart';

/// Using a relative import, breakpoints are hit.
import '../lib/main.dart';

void main() {
  test('Counter increments smoke test', () async {
    print(foo());
  });
}
```

It looks like there's an issue where `package:test_project/main.dart` isn't mapping to `file:///some_path/test_project/lib/src/main.dart`. Oddly enough this only seems to be an issues in Flutter, not in the standalone Dart VM. I'll keep digging.

**Comment by bkonyi** [comment]
Done some more digging and it seems like this only happens when we try and set a breakpoint in a file with a mixin declaration.

From what I've been able to gather, it seems like the following is happening:

- The main library (`file:///test_project/test/test.dart`) is loaded immediately and includes the `file:///test_project/lib/main.dart` script as part of the library due to the mixin application on `Bar`
- `main.dart` is loaded and another script object is created for `package:test_project/main.dart`, resulting in a differing ID for the script
- When trying to set a breakpoint in `main.dart`, the VM iterates through all libraries, attempting to lookup `main.dart` by its URI. The VM finds two script different instances with the same URI and gives up due to the ambiguity.

I'm starting to thing this is more of a CFE issue, potentially even just related to how Flutter has configured its compilation service, but I'm not sure where to look next. @mraleph, maybe you have some insights or know someone who would?

**Comment by jensjoha** [comment]
Thank you for reporting this. I'll look into it!

Until we have a fix note one can `import 'dart:developer';` and then call `debugger();` over the place you want the debugger to stop. This is obviously not perfect, but is probably better than print-debugging.

**Comment by jensjoha** [comment]
Explanation of whats happening / my conclusions:

- In the Flutter compilation pipeline the dill file given to the VM actually contains several components. We split them by package in an attempt to be able to re-use the serialization on unchanged packages. In this case, importing via the package uri means that the main file comes into its own component and the non-packaged stuff comes into its own component. The non-packaged stuff still have data from the package though as the mixin code is copied into it. When loading this dill file it will have 2 scripts representing "the same thing" (but not really the same thing as it is from two different parts of the dill file so they can't just be merged) and the debugger can't handle that.
  - When doing a relative import instead the package doesn't exist at all and everything is placed in the same component, there is only one script and it works.
- This is not a problem isolated to Flutter though, as in plain Dart the platform is generally always a separate dill already, so mixing in something from the platform and trying to set a breakpoint on that doesn't work either.
  - also (not verified) this must be a problem on hot reload if old versions survive e.g. surviving closures etc.
- This cannot be fixed in the front end. The VM has to be able to support it. On the top of my head, this could for instance be via
  -  The debugger directly supporting several scripts with the same uri
  - Splitting scripts up into "normal scripts" and "parent scripts" where then only "parent scripts" are used for some stuff (e.g. in the debugger), but "normal scripts" are used for the more specific stuff (e.g. kernel program info). This would in most normal cases double the number of scripts though (by adding a parent script for each normal script).
  - A variant of the "normal/parent" script above could be that each script points to a "primary script" which is then just the first one or something like that. But then again, the debugger could make sure to go via the primary script pointer to operate on the one that makes it work. This would avoid doubling the number of scripts, but will probably be problematic in regards to GC in that we shouldn't keep scripts (and whatever content like for instance kernel program infos that they contain) alive by this link only (while at the same time making sure that one script for each logical group is in fact the primary one for that entire group). Modulo the GC issue this would probably be somewhat simple as we already find any existing script then creating the new ones to make sure to copy over sources and line starts (this was done - if I recall correctly - to make coverage collection work).
  - (Someone with actual insights into the VM might have better ideas though.)

I'll re-assign this back to Ben.

**Comment by bkonyi** [comment]
This should be resolved by https://github.com/dart-lang/sdk/commit/302e42da44b1d395680c097623c6a92a1c1d9bb2.

**Comment by escamoteur** [comment]
confirmed, thanks a lot
