### ISSUE TITLE
image_picker Plugin: Uncaught NSInternalInconsistencyException (iOS) on simulator 

### ISSUE THREAD

**Issue by maerlynflagg** [flutter/flutter#68283]
i want to take a picture from gallery on a iOS device. in this example i'm using iPad Air 2, iOS 14.0.1.

## Steps to Reproduce

1. use Flutter 1.22.0 and `image_picker: ^0.6.7+11`
2. call `await _imagePicker.getImage(source: ImageSource.gallery, maxHeight: 1024, maxWidth: 1024, imageQuality: 100)`
3. click on cancel
4. call `await _imagePicker.getImage(source: ImageSource.gallery, maxHeight: 1024, maxWidth: 1024, imageQuality: 100)` again

the second call ended up in a App crash. you can only see the crash in XCode Log:

```
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.'
terminating with uncaught exception of type NSException.
```

**EDIT**

on Android all is fine.

**Comment by maerlynflagg** [comment]
on Android all is fine.

**Comment by TahaTesser** [comment]
Hi @maerlynflagg 
Unable to reproduce the issue on the latest `stable` flutter channel  on iOS 14

<details> 
<summary>complete code sample</summary> 

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  File _image;
  final picker = ImagePicker();

  Future getImage() async {
    final pickedFile = await picker.getImage(
        source: ImageSource.gallery,
        maxHeight: 1024,
        maxWidth: 1024,
        imageQuality: 100);

    setState(() {
      if (pickedFile != null) {
        _image = File(pickedFile.path);
      } else {
        print('No image selected.');
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Image Picker Example'),
      ),
      body: Center(
        child: _image == null ? Text('No image selected.') : Image.file(_image),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: getImage,
        tooltip: 'Pick Image',
        child: Icon(Icons.add_a_photo),
      ),
    );
  }
}

```

</details> 

<details> 
<summary>logs</summary> 

```bash
2020-10-16 16:18:40.481318+0530 Runner[9912:2493988] Metal API Validation Enabled
2020-10-16 16:18:40.605506+0530 Runner[9912:2494190] flutter: Observatory listening on http://127.0.0.1:53110/F79qwt5zClM=/
2020-10-16 16:18:40.940584+0530 Runner[9912:2494180] fopen failed for data file: errno = 2 (No such file or directory)
2020-10-16 16:18:40.940652+0530 Runner[9912:2494180] Errors found! Invalidating cache...
2020-10-16 16:18:41.018985+0530 Runner[9912:2494180] fopen failed for data file: errno = 2 (No such file or directory)
2020-10-16 16:18:41.019071+0530 Runner[9912:2494180] Errors found! Invalidating cache...
2020-10-16 16:18:41.033238+0530 Runner[9912:2493988] [VERBOSE-2:FlutterObservatoryPublisher.mm(115)] Failed to register observatory port with mDNS with error -65555.
2020-10-16 16:18:41.033301+0530 Runner[9912:2493988] [VERBOSE-2:FlutterObservatoryPublisher.mm(117)] ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
On iOS 14+, local network broadcast in apps need to be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features such as hot reload and DevTools.

To make your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations.

For more information, see https://flutter.dev/docs/development/add-to-app/ios/project-setup
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
2020-10-16 16:19:25.516681+0530 Runner[9912:2494179] flutter: No image selected.
2020-10-16 16:19:28.251134+0530 Runner[9912:2494179] flutter: No image selected.

```

</details> 
<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f30b7f4db9 (8 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios • iOS 14.0.1

! Doctor found issues in 1 category.
```

</details> 

Can you please provide your `flutter doctor -v` and a complete reproducible minimal code sample
Thank you

**Comment by maerlynflagg** [comment]
today I gave you `flutter doctor -v`. the other informations I will gave you later.


<details>
<summary>Flutter Doctor</summary>

```
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Apples-Mac-mini:VisitCube apple-car$ flutter doctor -v
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ A new version of Flutter is available!                                     ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝


[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.6 19G2021, locale de-DE)
    • Flutter version 1.22.0 at /Users/apple-car/Documents/flutter
    • Framework revision d408d302e2 (2 weeks ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


 
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • iPadAir2 (mobile) • 6ddad0a077ccf4852202848a54f459a4dc4a1dd7 • ios • iOS 14.0.1

! Doctor found issues in 2 categories.
Apples-Mac-mini:VisitCube apple-car$ 
```

</details>

**Comment by maerlynflagg** [comment]
I founded a similar thread, which the same issue #66244. so there are informations to about the `NSInternalInconsistencyException`.

**Comment by TahaTesser** [comment]
Hi @maerlynflagg 
I'm aware of this issue, it is fixed on the latest plugin https://github.com/flutter/flutter/issues/65995#issuecomment-704589211
please update your stable channel and use the latest `image_picker`,
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by wagnerlino** [comment]
Hi @TahaTesser 
I'm having this error in the iOS simulator when trying to open the photo gallery a second time. If the problem is with my code, please ignore it, I'm still learning.

<details>
<summary>Code sample</summary>
  
``` javascript
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(
    MaterialApp(
      home: Home(),
    ),
  );
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  File _image;
  final picker = ImagePicker();

  Future getImage(bool fromCamera) async {
    final _source = fromCamera ? ImageSource.camera : ImageSource.gallery;
    final pickedFile = await picker.getImage(source: _source);

    setState(() {
      if (pickedFile != null) {
        _image = File(pickedFile.path);
      } else {
        print('No image selected.');
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Select image"),
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            RaisedButton(
              child: Text("Camera"),
              onPressed: () {
                getImage(true);
              },
            ),
            RaisedButton(
              child: Text("Gallery"),
              onPressed: () {
                getImage(false);
              },
            ),
            _image == null ? Text("No image selected") : Image.file(_image)
          ],
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>
  
```
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.6 19G2021, locale en-BR)
    • Flutter version 1.22.1 at /Users/lino/Flutter
    • Framework revision f30b7f4db9 (8 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/lino/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/lino/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.8.4

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • iPhone 8 (mobile) • 51A65CDC-1516-4768-9E4D-910A986A7D61 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

! Doctor found issues in 1 category.
```
</details>

**Comment by cpboyd** [comment]
@TahaTesser @cyanglaz closed that specific PR without merging pending the engine fix, which I don't yet think has made it to `stable`.

**Comment by varun-horizon** [comment]
I can confirm this issue is still happening, running stable flutter engine 1.22.2 with latest image_picker so I am sure fix didn't make it to stable channel.

**Comment by yangxin6** [comment]
I also confirm this issue is still happening, running stable flutter engine 1.22.2 with image_picker 0.6.7+12.

**Comment by cyanglaz** [comment]
@varun-horizon @yangxin6 The fix for simulator didn't go to stable. On stable, the crash for real devices should be fixed. The fix for simulator is on master.

**Comment by varun-horizon** [comment]
Okay so that makes sense. I was testing on simulator. I usually only test profile and release builds on real device. Thanks for letting us know. I will test on real device and get back to you. Thanks

**Comment by yangxin6** [comment]
Ok,I switch to the master and the problem has been resloved on real device. Thank you very much.

**Comment by Peet-A** [comment]
when can we expect to have the fix for the simulator into the stable channel ? thanks .

**Comment by maerlynflagg** [comment]
thanks, no it's working on device.

**Comment by TahaTesser** [comment]
This issue persists on `Channel stable, 1.22.3`, not able to crash it on beta `Channel beta, 1.23.0-18.1.pre`  

### Preview
![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/98947336-11541580-251b-11eb-81ac-b9cda82c2742.gif)


### Code Sample
[Offical Example](https://pub.dev/packages/image_picker/example)

<details> 
<summary>logs</summary> 

```bash
2020-11-12 19:19:26.450865+0530 Runner[54049:487979] flutter: Observatory listening on http://127.0.0.1:50887/CS7eUwG2Rak=/
2020-11-12 19:20:49.571335+0530 Runner[54049:487966] This application is modifying the autolayout engine from a background thread after the engine was accessed from the main thread. This can lead to engine corruption and weird crashes.
 Stack:(
	0   CoreAutoLayout                      0x00007fff5884fb9b _AssertAutoLayoutOnAllowedThreadsOnly + 190
	1   CoreAutoLayout                      0x00007fff5884f926 -[NSISEngine _optimizeWithoutRebuilding] + 54
	2   CoreAutoLayout                      0x00007fff5884f459 -[NSISEngine optimize] + 92
	3   CoreAutoLayout                      0x00007fff5884a8c4 -[NSISEngine performPendingChangeNotifications] + 82
	4   UIKitCore                           0x00007fff24bc3dc9 -[UIView(Hierarchy) layoutSubviews] + 491
	5   UIKitCore                           0x00007fff24bd750c -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2924
	6   QuartzCore                          0x00007fff27a7718f -[CALayer layoutSublayers] + 258
	7   QuartzCore                          0x00007fff27a7d641 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 575
	8   QuartzCore                          0x00007fff27a89399 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 65
	9   QuartzCore                          0x00007fff279c9114 _ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd + 496
	10  QuartzCore                          0x00007fff279ffeaf _ZN2CA11Transaction6commitEv + 783
	11  QuartzCore                          0x00007fff27a0106b _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 79
	12  CoreFoundation                      0x00007fff2038b1e8 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	13  CoreFoundation                      0x00007fff20385a67 __CFRunLoopDoObservers + 547
	14  CoreFoundation                      0x00007fff2038600a __CFRunLoopRun + 1113
	15  CoreFoundation                      0x00007fff203856c6 CFRunLoopRunSpecific + 567
	16  Flutter                             0x00000001043c9781 _ZN3fml17MessageLoopDarwin3RunEv + 65
	17  Flutter                             0x00000001043c47fa _ZN3fml15MessageLoopImpl5DoRunEv + 22
	18  Flutter                             0x00000001043c8480 _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN3fml6ThreadC1ERKNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEE3$_0EEEEEPvSJ_ + 170
	19  libsystem_pthread.dylib             0x00007fff5e73d109 _pthread_start + 148
	20  libsystem_pthread.dylib             0x00007fff5e738b8b thread_start + 15
)
2020-11-12 19:20:49.583569+0530 Runner[54049:487966] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2041daf2 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   CoreAutoLayout                      0x00007fff5884fc89 -[NSISEngine tryToOptimizeReturningMutuallyExclusiveConstraints] + 0
	3   CoreAutoLayout                      0x00007fff5884f926 -[NSISEngine _optimizeWithoutRebuilding] + 54
	4   CoreAutoLayout                      0x00007fff5884f459 -[NSISEngine optimize] + 92
	5   CoreAutoLayout                      0x00007fff5884a8c4 -[NSISEngine performPendingChangeNotifications] + 82
	6   UIKitCore                           0x00007fff24bc3dc9 -[UIView(Hierarchy) layoutSubviews] + 491
	7   UIKitCore                           0x00007fff24bd750c -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2924
	8   QuartzCore                          0x00007fff27a7718f -[CALayer layoutSublayers] + 258
	9   QuartzCore                          0x00007fff27a7d641 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 575
	10  QuartzCore                          0x00007fff27a89399 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 65
	11  QuartzCore                          0x00007fff279c9114 _ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd + 496
	12  QuartzCore                          0x00007fff279ffeaf _ZN2CA11Transaction6commitEv + 783
	13  QuartzCore                          0x00007fff27a0106b _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 79
	14  CoreFoundation                      0x00007fff2038b1e8 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	15  CoreFoundation                      0x00007fff20385a67 __CFRunLoopDoObservers + 547
	16  CoreFoundation                      0x00007fff2038600a __CFRunLoopRun + 1113
	17  CoreFoundation                      0x00007fff203856c6 CFRunLoopRunSpecific + 567
	18  Flutter                             0x00000001043c9781 _ZN3fml17MessageLoopDarwin3RunEv + 65
	19  Flutter                             0x00000001043c47fa _ZN3fml15MessageLoopImpl5DoRunEv + 22
	20  Flutter                             0x00000001043c8480 _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN3fml6ThreadC1ERKNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEE3$_0EEEEEPvSJ_ + 170
	21  libsystem_pthread.dylib             0x00007fff5e73d109 _pthread_start + 148
	22  libsystem_pthread.dylib             0x00007fff5e738b8b thread_start + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.'
terminating with uncaught exception of type NSException
CoreSimulator 732.18.0.2 - Device: iPhone 12 (A7813C6B-51C7-4BBA-A494-4925360F9BD3) - Runtime: iOS 14.2 (18B79) - DeviceType: iPhone 12
(lldb)
```

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H15, locale en-GB)
    • Flutter version 1.22.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 8874f21e79 (2 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/SanDisk/Xcode-beta.app/Contents/Developer
    • Xcode 12.2, Build version 12B5044c
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D                     • android-arm64
      • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios
      • iOS 14.2
    • iPhone 12 (mobile)   • A7813C6B-51C7-4BBA-A494-4925360F9BD3 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by cyanglaz** [comment]
I'm going to close this issue as the simulator issue is fixed on master and beta channel.

**Comment by 50431040** [comment]
> This issue persists on `Channel stable, 1.22.3`, not able to crash it on beta `Channel beta, 1.23.0-18.1.pre`
> 
> ### Code Sample
> [Offical Example](https://pub.dev/packages/image_picker/example)
> 
> logs
> flutter doctor -v
> Note:
> This was a known issue, [#65995 (comment)](https://github.com/flutter/flutter/issues/65995#issuecomment-704589211)
> fixed for the device, only happens on the simulator on stable
> 
> CC @pcsosinski

I resolved by this
