### ISSUE TITLE
[tool_crash] FileSystemException: Cannot copy file to 'C:\Users\USER\Desktop\stiw2044 lab 1\stiw2044_lab1\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', OS Error: Access is denied., errno = 5

### ISSUE THREAD

**Issue by madihahdihah97** [flutter/flutter#69116]
## Command
```
flutter create --ios-language swift --android-language kotlin .
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs

`FileSystemException: Cannot copy file to 'C:\Users\USER\Desktop\stiw2044 lab 1\stiw2044_lab1\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', OS Error: Access is denied.
, errno = 5`

```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.copySync (dart:io/file_impl.dart:340:5)
#2      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#3      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#4      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:256:18)
#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#6      Template.render (package:flutter_tools/src/template.dart:182:24)
#7      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:781:21)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#16     Template.fromName (package:flutter_tools/src/template.dart)
#17     _rootRunUnary (dart:async/zone.dart:1198:47)
#18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#23     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#24     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
```
```
[✓] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18363.1139], locale en-US)
    • Flutter version 1.20.2 at C:\flutter
    • Framework revision bbfbf1770c (3 months ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\USER\AppData\Local\Android\sdk
    • Platform android-29, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Users\USER\AppData\Local\JetBrains\IntelliJ IDEA 2019.2.2
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761

[✓] VS Code (version 1.47.1)
    • VS Code at C:\Users\USER\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[✓] VS Code, 64-bit edition (version 1.42.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.12.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by hamdikahloun** [comment]
Hi @madihahdihah97 

This issue was [fixed](https://github.com/flutter/flutter/issues/50880) and [merged](https://github.com/flutter/flutter/pull/63540).

Also see [this](https://github.com/flutter/flutter/issues/67093#issuecomment-702497613) comment and try the same at your end to see if it works.

Thank you

**Comment by darshankawar** [comment]
@madihahdihah97 
Please upgrade to latest stable version and try again. Should be fixed in latest.

**Comment by TomGao2001** [comment]
From #70781: Similar issue occurred to me for the latest stable (1.22.4) version. I tried 1.24.0-10.1.pre as well but that had other issues as well as this one.
Doesn't seem to be sudo problems - I ran everything I could as admin, and checked that everything can be rwx'ed. 
Also tried putting both the SDK and project locations in different places as suggested, incl. on Desktop, in Documents, as well as C:\ root directory.

**Comment by TahaTesser** [comment]
CC @jonahwilliams

**Comment by MatamandoKalilani** [comment]
I have the latest stable build of flutter 
[flutter_01.log](https://github.com/flutter/flutter/files/5906334/flutter_01.log)
but i'm still getting this issue. Please Help.. I really want to get to work here.

**Comment by iapicca** [comment]
@TahaTesser this is definitely a `windows 10` issue

<details>
<summary>empirical evidence</summary>

https://github.com/flutter/flutter/issues/69953 `[✓] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.18363.1139], locale`
https://github.com/flutter/flutter/issues/69825 `[✓] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.18363.1139], locale ar-TN)`
https://github.com/flutter/flutter/issues/70064 `[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)`
https://github.com/flutter/flutter/issues/70067 `[✓] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.18362.1139], locale en-US)`
https://github.com/flutter/flutter/issues/70190 `[✓] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.17763.1518], locale en-IN)`
https://github.com/flutter/flutter/issues/70694 `[✓] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)`
https://github.com/flutter/flutter/issues/70781 `[✓] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18363.1198], locale en-US)`
https://github.com/flutter/flutter/issues/71133 `[✓] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.10240], locale en-US)`
https://github.com/flutter/flutter/issues/71916 `[✓] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19041.630], locale en-US)`
https://github.com/flutter/flutter/issues/72229 `[✓] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19042.685], locale en-US)`
https://github.com/flutter/flutter/issues/72348 `[✓] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18363.1256], locale en-US)`
https://github.com/flutter/flutter/issues/72505 `[✓] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19041.685], locale tr-TR)`
https://github.com/flutter/flutter/issues/72570 `[✓] Flutter (Channel stable, 1.22.5, on Microsoft Windows [versÃ£o 6.3.9600], locale pt-BR)`
https://github.com/flutter/flutter/issues/72610 `[✓] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.18363.1198], locale en-US)`
https://github.com/flutter/flutter/issues/72658 `[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1139], locale en-US)`
https://github.com/flutter/flutter/issues/73419 `[✓] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19041.685], locale en-US)`
https://github.com/flutter/flutter/issues/73832 `[✓] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.18363.418], locale en-MY)`
https://github.com/flutter/flutter/issues/74241 `[✓] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.10240], locale en-US)`
https://github.com/flutter/flutter/issues/74409 `[✓] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1316], locale en-IN)`
https://github.com/flutter/flutter/issues/74470 `[✓] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1316], locale en-IN)`
https://github.com/flutter/flutter/issues/74723 `[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1256], locale en-US)`
https://github.com/flutter/flutter/issues/75440 `[✓] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1316], locale en-US`
https://github.com/flutter/flutter/issues/75558 `[✓] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1316], locale en-GB)`

</details>

whoever is encountering the issue please try following the steps provided in the link below
["Access Denied" or other errors when you access or work with files and folders in Windows](https://support.microsoft.com/en-us/topic/-access-denied-or-other-errors-when-you-access-or-work-with-files-and-folders-in-windows-219af563-1953-ab4a-f17e-b0182755214e)

**Comment by TahaTesser** [comment]
@iapicca 
That's great work, thanks!

**Comment by AlexV525** [comment]
Permissions can be modified for various reasons on Windows. Administrators don't guarantee full access to some paths. When this kind of issue occurs on Windows, check the following conditions first:
- Flutter is installed with an accessible path to the current user, e.g. `D:\flutter`, `C:\Users\username\Documents`, rather than `C:\src\flutter\`, `C:\Program Files\flutter`.
- The project is fully accessible (including subfolders and their files) to the current user.

Additionally, to reset the permission of a specific path, run `icacls "full path to the folder" /reset /t /c /l`.

Closing as nothing can be done by the `flutter_tools` currently. Proposals like #121586 might help with administrative permissions.
