### ISSUE TITLE
[web] Scroll is not recognized by the browser

### ISSUE THREAD

**Issue by jamesblasco** [flutter/flutter#69529]
## Steps to Reproduce

Flutter is painted on a canvas and the browser doesn't detect the scroll.

This causes problems when the native browser uses the scroll to perform their own actions. 

Current problems:

- Safari and Chrome iOS address and bottom bar navigation doesn't collapse when scrolling:
Issues: https://github.com/flutter/flutter/issues/64572 https://github.com/flutter/flutter/issues/68877

|  Current behavior  |  Expected behavior (would also need to scroll) |
|---|---|
|   <img height="400" src="https://user-images.githubusercontent.com/19904063/97805735-36fa3880-1c58-11eb-92ca-0c7436080c6f.gif" />  |   <img height="400" src="https://user-images.githubusercontent.com/19904063/97805757-52654380-1c58-11eb-95a5-8d747c560240.gif" />  |
- iOS scroll to top by tapping on the status bar doesn't work. A feature available for any website in any ios browser or WKWebView

- iOS Facebook & Facebook Messenger displays in-app websites inside a draggable modal. Because of scroll is not detected, the modal is closed instead of scrolling upwards.

<img height="400" src="https://user-images.githubusercontent.com/19904063/97805974-9efd4e80-1c59-11eb-941a-910518366ac0.gif" />

**Comment by pedromassangocode** [comment]
Issue reproducible on latest `master` channel.

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-7.0.pre.47, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.24.0-7.0.pre.47 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 2f18e0b23d (20 hours ago), 2020-11-01 20:58:04 +0530
    • Engine revision 3460519398
    • Dart version 2.12.0 (build 2.12.0-3.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 50.0
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • iPhone 12 Pro Max (mobile) • ECCF5C4A-8BEC-411D-B23E-85A836C3847E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)           • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 86.0.4240.111

• No issues found!
```
</details>

**Comment by yjbanov** [comment]
I thought we had a duplicate issue for this, but I failed to find one. I'm accepting this as a feature request.

**Comment by yjbanov** [comment]
I've been thinking about some ideas for fixing this. Leaving this idea before I forget: the web engine could use a signal from the framework that there's a scrollable area that the user is interacting with as well as when the start/end has been reached. We could then make the body element (or some other top-level element) scrollable while keeping the Flutter View in a fixed position. The browser will see the element scrolling and react appropriately.

**Comment by yjbanov** [comment]
@jamesblasco Curious how did you get it to behave correctly in the "Expected behavior" screen recording?

**Comment by jamesblasco** [comment]
Hey yjbanov, you can see a detailed ex planation in this comment 

https://github.com/flutter/flutter/issues/68877#issuecomment-720091525

**Comment by abarge** [comment]
Hi, is there any update on this? I have the same issue, the scroll isn't recognised when I open the app from a link in a facebook post or messenger.

**Comment by jamesblasco** [comment]
I've just discovered it also happens with the Google Assistant app:

<img height="400"  src="https://user-images.githubusercontent.com/19904063/106584774-e3dd9d80-6546-11eb-91ff-efecc7477227.gif" />

**Comment by Mravuri96** [comment]
> I thought we had a duplicate issue for this, but I failed to find one. I'm accepting this as a feature request.

Might that be this? #67832. if not, mentioning it here as it's in the same realm.

**Comment by luisdemarchi** [comment]
@jamesblasco Your script really works for an app without scrolling. However, when you add an internal scroll, the scroll dies (at least on iOS) :(

**Comment by ayushin** [comment]
Yes, this should really be fixed in flutter, not in css / index.html

**Comment by jamesblasco** [comment]
@ayushin the problem is that browsers do not provide an api to control this behavior and it is automatically sync with the body scroll

**Comment by ayushin** [comment]
But some PWAs manage it quite well still, like: https://www.wsj.com/

**Comment by Vluf** [comment]
How has this issue been known for 8 months and not fixed yet. This is _yet_ another issue that makes the "cross platform" Flutter a stupid advertisement.
This breaks any scrollable flutter web app on iOS (a lot of people use the in-app browsers).

**Comment by MarcelWilming** [comment]
@ayushin how do you get this working in a PWA ?

**Comment by ayushin** [comment]
Nope

**Comment by MarcelWilming** [comment]
@ayushin Do we have a workaround for a scrollView ?

**Comment by ayushin** [comment]
@MarcelWilming Not at the moment, I don't think I am the right person to ask.

**Comment by hightman** [comment]
I also encountered this problem, but it seems that there is still no solution. 
Because only scrolling on the body element can trigger the hiding URL bar of iOS-safari, all scrolling of flutter-web are not on the body, so I can't think of a way to modify or circumvent it.

**Comment by Piinks** [comment]
There was recently added a new `MaterialSate.scrolledUnder`, this may be useful in implementing this. It is currently being used so the AppBar can change when content scrolls under it, if we could pass that information on to the engine in a meaningful way it might work.

**Comment by yjbanov** [comment]
This continues to be a problem in Safari iOS 15 (https://github.com/flutter/flutter/issues/90506).

**Comment by skypu3** [comment]
hi @FantasyOR, it still can't expand to the full screen, there is blank area please see the attached: 

![IMG_4366](https://user-images.githubusercontent.com/70039/135006908-dc94f5db-b846-4267-8959-ce477c9b3738.jpg)

**Comment by hightman** [comment]
this seems bug only in iOS15, If you adjust URL bar to top position in safari setting, it may be ok.

**Comment by skypu3** [comment]
@hightman, I did the test, URL bar both on top and bottom, it doesn't work still has blank area.

**Comment by yjbanov** [comment]
Just leaving these resources for us to look into when we attempt a fix:

- https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html
- https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

Would be interesting to check how Flutter would behave with not engine-side changes if these tags are specified.

**Comment by josedoes** [comment]
following

**Comment by FantasyOR** [comment]
> hi @FantasyOR, it can expand to the full screen, but there is blank area please see the attached:
> 
> ![IMG_4366](https://user-images.githubusercontent.com/70039/135006908-dc94f5db-b846-4267-8959-ce477c9b3738.jpg)

maybe your app is not to match height? Please try set: 
``` dart
Scaffold(
        body: Container(
               height: MediaQuery.of(context).size.height,
               child: ...
```

**Comment by skypu3** [comment]
any updates on this issue ?

**Comment by yjbanov** [comment]
@skypu3 No update, unfortunately, but I've been trying to think of ideas for how to fix this. My latest idea is to add a two-way scrolling element under `<flt-glass-pane>` that would be scrolled by the browser whenever you drag your finger, in addition to reporting the pointer event to the Flutter framework so that Flutter can react to the scroll too. The downside is that if the framework doesn't tell the engine that it's scrolling the browser will always think that you are scrolling and minimize the address bar, even if the drag gesture is used for something else.

@hightman Thanks for trying! This gives me hope that this can work. We used to have issues with Safari temporarily reporting wrong window dimensions upon page load. This looks exactly like that problem. We implemented [this hack](https://github.com/flutter/engine/blob/0ec193f2407876472f2881c69103ad86be7363b9/lib/web_ui/lib/src/engine/embedder.dart#L313) for pre-13 Safari, but perhaps we still need this hack for newer Safari versions. If you are able to build the engine, could you try removing `html.window.visualViewport == null` from the `if` condition?

**Comment by lyf571321556** [comment]
following

**Comment by Vluf** [comment]
Just want to mention that this is breaks any flutter app (with some scrollable content) on iOS Safari popup views. For example the ones opening up when clicking a link in the Messenger app.

**Comment by jemutorres** [comment]
Following

**Comment by Akarshit-Git** [comment]
Following

**Comment by tarun-goHomely** [comment]
Following

**Comment by oliverpool** [comment]
Instead of spamming this issue with `Following` messages, please simply click the `Subscribe` button on the left side:

![image](https://user-images.githubusercontent.com/3864879/154706084-459e3f69-62e8-476e-b6b0-fca8cf2187c2.png)

_(sorry at all the followers for this message not related to the issue)_

**Comment by atgnatus** [comment]
This is a critical issue.  I do not think it is fair to say Flutter works on mobile web while this is still open.  It dramatically reduces the usable screen size which results in a significantly reduced end user experience.

**Comment by flutterhands** [comment]
> This is a critical issue. I do not think it is fair to say Flutter works on mobile web while this is still open. It dramatically reduces the usable screen size which results in a significantly reduced end user experience.

This.

If not fixable in Flutter, it should at least be fixed in Chrome on all devices. Without such fix we cannot claim Flutter for web is an alternative for anything. Unfortunately, because we love Flutter!

**Comment by temirfe** [comment]
I've been doing a work for client for more than a month, and when the project is almost done I have this problem. Also site is very logy and several other problems. Now I don't know how to present to client. Flutter web is not stable at all ((

**Comment by inagornyi** [comment]
Hey
Will there be an official solution to this problem?

**Comment by slavap** [comment]
@yjbanov 
Just FYI, this meta tag
```html
<meta name="apple-mobile-web-app-capable" content="yes">
```
does not helping with hiding bottom navigation/addressBar at all.

**Comment by jakusb** [comment]
Please up the priority!
Flutter is getting mature and bragging about all platforms it supports.
this feature should be supported.

**Comment by nyermakh** [comment]
Is there any workaround?

**Comment by winfryed** [comment]
If not fixed in flutter it would be very nice if there would be any reliable workaround.
As mentioned before: "Please up the priority!"

**Comment by inagornyi** [comment]
Vote and like to up the priority.

**Comment by inagornyi** [comment]
Is anybody here?

**Comment by AndreiMisiukevich** [comment]
You can kindly ask your users to hide the toolbar with some popup message on the first app start (not ideal at all, but at least something...)

![image](https://user-images.githubusercontent.com/10124814/170908612-cce2bca5-a60b-48ff-9ea8-6eb3397ca169.png)

**Comment by nyermakh** [comment]
Well, I am developing a website that is intended to be used within in-app web browsers (like within Google Assistant). In this case, asking your users wouldn't help :(

**Comment by iapicca** [comment]
tagging @huycozy since [referenced](https://github.com/flutter/flutter/issues/109502#issuecomment-1214868983) this issue
could you consider adding the `crowd` label

**Comment by huycozy** [comment]
@iapicca: Adding `crowd` label based on the number of affected users and upvotes. Thank you!

**Comment by Piinks** [comment]
Following up on https://github.com/flutter/flutter/issues/69529#issuecomment-1007736827 @yjbanov 

> The downside is that if the framework doesn't tell the engine that it's scrolling, the browser will always think that you are scrolling and minimize the address bar, even if the drag gesture is used for something else.

We could probably communicate this pretty easily to the engine. AFAIK that's the easy part. When scrolling is occurring, the framework could maybe use a platform channel to let the engine know? From what I can tell we already have all of the recommended and appropriate Apple meta tags and flags set, if we tell the engine we are scrolling, will your idea with `<flt-glass-pane>` work?

**Comment by riusaky007** [comment]
Hey, Any solution about the

> ## Steps to Reproduce
> Flutter is painted on a canvas and the browser doesn't detect the scroll.
> 
> This causes problems when the native browser uses the scroll to perform their own actions.
> 
> Current problems:
> 
> * Safari and Chrome iOS/Android address and bottom bar navigation doesn't collapse when scrolling:
>   Issues: [[web] Allow Flutter apps to have 13% bigger screen after being scrolled down #64572](https://github.com/flutter/flutter/issues/64572) [Flutter for Web does not hide url bar and navigation bar on scroll in iOS's Safari #68877](https://github.com/flutter/flutter/issues/68877)
> 
> Current behavior	Expected behavior (would also need to scroll)
> <img alt="" height="400" src="https://user-images.githubusercontent.com/19904063/97805735-36fa3880-1c58-11eb-92ca-0c7436080c6f.gif">	<img alt="" height="400" src="https://user-images.githubusercontent.com/19904063/97805757-52654380-1c58-11eb-95a5-8d747c560240.gif">
> * iOS scroll to top by tapping on the status bar doesn't work. A feature available for any website in any ios browser or WKWebView
> * iOS GoogleMaps, Google Assistant, Facebook & Facebook Messenger displays in-app websites inside a draggable modal. Because of scroll is not detected, the modal is closed instead of scrolling upwards.
> 
> <img alt="" height="400" src="https://user-images.githubusercontent.com/19904063/97805974-9efd4e80-1c59-11eb-941a-910518366ac0.gif"> [ <img alt="97805974-9efd4e80-1c59-11eb-941a-910518366ac0.gif" height="400" src="https://user-images.githubusercontent.com/19904063/97805974-9efd4e80-1c59-11eb-941a-910518366ac0.gif"> ](https://user-images.githubusercontent.com/19904063/97805974-9efd4e80-1c59-11eb-941a-910518366ac0.gif) [ ](https://user-images.githubusercontent.com/19904063/97805974-9efd4e80-1c59-11eb-941a-910518366ac0.gif)

Any updates about this? I'm facing the same problem (09/20/2022)

**Comment by rafaelmaia8384** [comment]
Following

**Comment by mateojc008** [comment]
Any update ? We are about to release a Flutter merchant web site so this feature is really important for us

**Comment by willcalderbank** [comment]
This issue negatively affects all flutter apps running on the web. Many people have 👍 'd to up the priority (https://github.com/flutter/flutter/issues/69529#issuecomment-1137345691) . @huycozy Could the priority be up'd please.

**Comment by jdaru** [comment]
Following

**Comment by inagornyi** [comment]
Guys, flutter for the web is not a good solution today, my team is now rewriting to reactjs 🤪. A lot of questions to performance, first loading the app, navigation, rendering and many other things where you need to 🩼. Flutter is cool for mobile development for android and ios 😎. I believe that in the future flutter for the web will be number one 🥇.

**Comment by slavap** [comment]
@inagornyi 
>>  flutter for the web is not a good solution today
it is a good solution, but not for every possible case.

**Comment by justinekatebe69** [comment]
> Guys, flutter for the web is not a good solution today, my team is now rewriting to reactjs 🤪. A lot of questions to performance, first loading the app, navigation, rendering and many other things where you need to 🩼. Flutter is cool for mobile development for android and ios 😎. I believe that in the future flutter for the web will be number one 🥇.

Yeah true. It's just not there yet as a web framework honestly. It needs more time...

**Comment by kyluke** [comment]
following

**Comment by Piinks** [comment]
Per our [issue hygiene](https://github.com/flutter/flutter/wiki/Issue-hygiene#comments), please keep comments on issues focused on the topic. Github issues are not the appropriate venue for conversation.

Also, `following` and `me too` comments are generally distracting and make it harder to find other more meaningful content in the bug. If you have no new details to add, consider just thumbs up-ing the issue. If you wish to subscribe to the issue, click the "subscribe" button in the right hand column of the GitHub UI.

**Comment by commandiron** [comment]
15 February 2023, this issue Not solved. OK.

**Comment by jiazhong520** [comment]
这个问题还没解决吗

**Comment by tompetk** [comment]
> For iOS this helps for me
> 
> add this code before closing body tag
> 
> ```
> <script>
>     var element = document.getElementsByTagName('body')[0];
> 
>     var handleScroll = function() {
>       	element.scrollTo(0, 0);  // required when scroll bar is drgged
>     };
> 
>     element.addEventListener('scroll', handleScroll, false);
> 
>     var handleEvent = function(e) {
>     	e.preventDefault();      // disables scrolling by mouse wheel and touch move
>     };
> 
>     element.addEventListener('scroll', handleEvent,{passive: false});
>     element.addEventListener('mousewheel', handleEvent,{passive: false});
>     element.addEventListener('touchmove', handleEvent, {passive: false});
>   </script>
> ```
> 
> Do you know any possible workaround for android devices?

This has fixed the issue on iOS for me, that scrolling in Flutter web app opened in Facebook Messenger was closing whole webview. Didn't notice any side effects yet. Thanks a lot!

**Comment by maRci002** [comment]
While I was searching for solutions I found this:

https://github.com/google/material-design-lite/issues/1072#issuecomment-357673854

> Side note: Just discovered that the URL address bar will not hide on Chrome browsers when scrolling down if your HTTP connection is insecure (possibly due to mixed content over the wire or an invalid SSL certificate). I guess that this is a security precaution to keep the user informed that their connection is not secure. This is not related to the fix above, but just to be aware in case you think that the fix is not working.

This can make testing the workarounds a bit more difficult for instance if we host the webserver from the PC via `flutter run -d web-server --web-hostname 0.0.0.0 --web-port=8080 --release --target lib/main.dart --web-renderer html` command and access application on the phone via `192.168.0.1:8080`.

This is also a problem for PWA installation so usually I'm hosting the server on the Android phone itself since NodeJS can be installed on the phone by using [Termux](https://termux.dev/en/). `localhost:8080` doesn't have certification issues so I can install PWA on my phone that's why I think that scrolling can also be tested on `localhost`.

**Comment by santa112358** [comment]
This works perfectly on iOS. 
https://github.com/flutter/flutter/issues/69529#issuecomment-1466313973

**Comment by Simileholluwa** [comment]
I am also experiencing this issue on flutter web app. I've tried different workarounds but none worked.
The flutter team should look into this.

**Comment by bobo2018cp** [comment]
Doesn’t flutter officially come out to solve the problem?

**Comment by Andrflor** [comment]
The proposed fix do not work anymore, but this code at the end of the head will make the browser scrollbar behave properly. 

```html
 <style>
    body {
      height: 200vh !important;
      position: static !important;
    }

    flt-glass-pane {
      position: fixed !important;
    }
  </style>
  ```

Then how to force rendering underneath address bar ?? I can't figure it out...

**Comment by iKK001** [comment]
This did now work [1653437178](https://github.com/flutter/flutter/issues/69529#issuecomment-1653437178).

The navigation bar only gets "blurry" - but it does not dissappear!

Any solution to this ?

Users really often open Web on their mobile phone. So Flutter-Web app with Scrolling should really work with the smooth nav-bar dissappear/show behaviour in the Browser that everybody is used to. Otherwise users will dislike Flutter-Web Apps on Mobile quite a bit.

**Comment by upsraka** [comment]
hi, i just face the same problem and i try this https://github.com/flutter/flutter/issues/69529#issuecomment-1712471508

the address bar is gone but the content does not expand. any solution for this?

thanks for the answer...

https://github.com/flutter/flutter/assets/57344209/979a3a7b-9224-40cc-81c1-b96d85534de5

**Comment by metafounder** [comment]
any plans to push the priority of this?

**Comment by shoaibomar** [comment]
@gspencergoog @gmackall @goderbauer I am adding you guys to this as I dont know who the relevant person would be to bring this up to but this not working is really ruing the flutter web experience on mobile, please let me know if there is any way I can help, but this needs to be fixed for flutter web mobile to be useable, I hope someone can push this issue up the priority chain and get a decent fix for this soon

**Comment by Piinks** [comment]
Referring to an earlier comment I made here: https://github.com/flutter/flutter/issues/69529#issuecomment-1215762415

AFAIK there is no available API from Apple to tell the browser the screen has scrolled some content. Since we are not rendering the browser bar, we do not have control over it. It would be very easy for us to do so if there were a way to communicate that to the platform, but I have looked many times over the years for this specific issue and have not found a way yet.

@yjbanov has suggested some ideas to approach this from the engine above, but I don't know if they have been tried or successful.

**Comment by shoaibomar** [comment]
@Piinks just a suggestion (I don't know how feasible it would be) is it possible to change it such that the scrolling is done through the browser instead of inside the flutter engine, and we have js communicate back to flutter to indicated the scroll position, that way we dont have to tell the browser anything, instead the browser is the source of truth for flutter and not flutter the source of truth for the browser ?

**Comment by Piinks** [comment]
> scrolling is done through the browser instead of inside the flutter engine

Scrolling is handled through the framework not the engine. Flutter does not use native elements in order to scroll, all of the physics, gesture handling etc. is all in the framework, above the engine.

**Comment by shoaibomar** [comment]
@Piinks  got it.

This is just a suggestion, and to be honest I think its maybe one of the only ways to fix it stably;

Either flutter needs to be able to tell the browser what's going (for that all major browsers need to write code to make it happen, which is probably more of a tall ask) or flutter needs to use the browsers the way they were designed to be used, at least until the browsers can be convinced the add this feature, because leaving it in this broken state is not really a solution.

Would it be out of the realm of practicality to change it around?

**Comment by Albekeio** [comment]
It's been almost three years since this topic was created. Can't believe that there 's still no solution to this. It makes Flutter apps on mobile browsers just BAD, especially for smaller screen sizes.

Bumping this...

**Comment by bobo2018cp** [comment]
I think the official Flutter team may have abandoned the web solution.

**Comment by commandiron** [comment]
This issue marked as P3 (Issues that we currently consider unimportant) - Is there anyone working on this problem?

**Comment by iKK001** [comment]
It is a killer argument to use Flutter Web, I think. Scrolling behaviour of Flutter-Web on Mobile as it currently is, is an absolute no-go for most users... The Flutter team should be aware of this, no?

Why isn't anyone from the Flutter team responding to this ? Is there severe technical reasons or what is the painpoint ?

**Comment by Albekeio** [comment]
It really is. If they don't care about it then they've officially abandoned web support which results in me abandoning Flutter as a whole.

**Comment by tubules** [comment]
It is so silly that this issue is 3 years old. Come on guys, Flutter is so awesome, why destroying all with this feature here? For me it is also a no go and I couldn't figure out any solution

**Comment by commandiron** [comment]
> Referring to an earlier comment I made here: [#69529 (comment)](https://github.com/flutter/flutter/issues/69529#issuecomment-1215762415)
> 
> AFAIK there is no available API from Apple to tell the browser the screen has scrolled some content. Since we are not rendering the browser bar, we do not have control over it. It would be very easy for us to do so if there were a way to communicate that to the platform, but I have looked many times over the years for this specific issue and have not found a way yet.
> 
> @yjbanov has suggested some ideas to approach this from the engine above, but I don't know if they have been tried or successful.

I really don't understand what's going on here. It's an almost 3-year-old problem and according to @Piinks, who works at Google and is the last person to respond to this problem; Inability to communicate with the platform. In other words, when the user interacts with the browser, there is no API to notify the internal framework. I am not an expert but I could understand the delay in this issue on Apple phones. But can someone explain to me why this problem has persisted for 3 years on an Android phone using Chrome? Can't the guys in the Flutter team contact the relevant people at Google and solve this problem?

If Flutter wants to be a permanent solution for multiple platforms, it should be aware that the web is one of the most important of these platforms.

**Comment by nialljawad96** [comment]
How is this not sorted? Remarkable. November next year, it will be half a decade. Please.

**Comment by nialljawad96** [comment]
@kevmoo Hi Kevin any update on this? We're desperate

**Comment by iapicca** [comment]
@yjbanov
is this `p3` the current, correct `p3` or the 2020 `p3`?
seems weird to me that such a bug labelled `crowd` has such low priority

**Comment by yjbanov** [comment]
I think once we fix https://github.com/flutter/flutter/issues/139263, then this functionality can be implemented as a pub package. The only way I know to make this work is to delegate scrolling to the browser, which is currently broken by https://github.com/flutter/flutter/issues/139263.

**Comment by nialljawad96** [comment]
@yjbanov surely this needs to be part of the framework? This is critical functionality for any web app, and any website really. It makes it impossible to use these web app's when you've got a massive URL + toolbar at the bottom on iOS safari or mobile Google Chrome. I am surprised this has been going on for 3.5 years.

**Comment by nialljawad96** [comment]
@yjbanov @kevmoo Any news on this? it is mission critical for Flutter Web - the apps are not functioning like normal web apps (or even websites) without it.

**Comment by huycozy** [comment]
Reproduced this issue on the latest stable/master channels. 

<details>
<summary>Sample code</summary>

Source: https://github.com/flutter/flutter/issues/109502

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    Widget text = const Text(
      'text',
      style: TextStyle(backgroundColor: Colors.black, color: Colors.white),
    );
    List<Widget> children = [];
    for (int i = 0; i < 100; i++) {
      children.add(text);
    }
    return MaterialApp(
      title: 'Scroll',
      home: Scrollbar(
        child: SingleChildScrollView(
          child: ColoredBox(
            color: Colors.black,
            child: Center(child: Column(children: children)),
          ),
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary>Demo</summary>

| Android Chrome browser | iOS Safari browser |
| --------------- | --------------- |
<video src="https://github.com/flutter/flutter/assets/104349824/20231d7a-edbc-437a-abe4-b8ac7dfbb742"/> | <video src="https://github.com/flutter/flutter/assets/104349824/d76aa0c9-df4f-493d-9fe3-f77e2efd5e48"/>

</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.19.0, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.19.0 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (2 days ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio Hedgehog.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.86.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 121.0.6167.160
    ! Error: Browsing on the local area network for iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.20.0-7.0.pre.79, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.20.0-7.0.pre.79 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7b9f7be7f6 (38 minutes ago), 2024-02-15 18:13:21 -0800
    • Engine revision bc4dd534a0
    • Dart version 3.4.0 (build 3.4.0-143.0.dev)
    • DevTools version 2.33.0-dev.6
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio Hedgehog.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.86.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D          • android-arm64  • Android 11 (API 30)
    • iPad (mobile)    • 00008103-000A1464346A201E • ios            • iOS 17.2 21C62
    • macOS (desktop)  • macos                     • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome                    • web-javascript • Google Chrome 121.0.6167.160

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by QoLTech** [comment]
Would love to see this addressed.

**Comment by metafounder** [comment]
So nice if this could get fixed

**Comment by nialljawad96** [comment]
Any news on this disabling problem for Flutter Web apps @huycozy @yjbanov @kevmoo? 

Thanks guys. Appreciate all you do.

**Comment by yjbanov** [comment]
Unfortunately, no news on this one. Flutter currently does custom scrolling and the browser is unaware that anything scrolls at all. However, we hope to start making progress on https://github.com/flutter/flutter/issues/139263 soon (once we find an owner we'll upgrade to P1). After it is fixed, it should be possible to implement this functionality as a package.

**Comment by nialljawad96** [comment]
@yjbanov Sad! This is the most important issue for Flutter Web currently. Yet the roadmap is focusing on WASM, which I find to be strange. This issue, hot reload, and general speed on lower-performance devices are the biggest problems. 

It needs to be prioritised, because next year, this problem will hit half a decade in existence. Half a decade! 

If I seem terse, it's because I love Flutter - I don't think the roadmap right now is aligned to what the masses want.

So how come, if you don't mind me asking, it isn't being prioritised? What could possibly be a bigger priority for Flutter Web (other than the other 2 issues mentioned?). Is this a prioritisation issue or a manpower issue? 

I appreciate you engaging on this matter at least, so thanks for that.

**Comment by kevmoo** [comment]
@nialljawad96 - "general speed on lower-performance devices" - Wasm will be a BIG help here.

**Comment by The-RootCause** [comment]
The web version is getting better thanks to skwasm. but this scrolling issue is making the web app look like a normal website. When scrolling the url bar and browser menu are not hidden as all single page app out there.
A fix for this issue is a major important step into making flutter web usable.

**Comment by sharan21** [comment]
Would really like to see this get addressed. In our case, this causes the URL bar to not auto-hide on scrolling and decreases the amount of usable screen we have left. It really is the difference between night and day

**Comment by geronimol** [comment]
Any updates? Do you think there is any chance to fix it?

**Comment by nialljawad96** [comment]
Any news on this guys? @kevmoo @yjbanov 

This would transform Flutter Web for mobile in a beautiful way

**Comment by knottx** [comment]
4 years issue 😞

**Comment by Oct7** [comment]
Is there any more important aspect regarding mobile web than this?
Has team tried using Flutter Web for mobile? If they did, they would know that this is the most crucial issue.
Does anyone know any current workaround for this?

**Comment by Snifftech** [comment]
I stopped using flutter, because of this issue. But seems that I will never get a chance to return. This currently is not the once promised „single code base“.

**Comment by AndreiMisiukevich** [comment]
I subscribe to this thread and, therefore, receive a ton of notifications.
Folks, come on! This is an open-source project. I think everyone should understand what this means.
It’s a little funny to read all these demands and ultimatums to the Flutter team, which already made the best cross-platform framework. Believe me, I know what I'm talking about (you can look at my GitHub profile).

So, let's be patient... or fix this problem yourself. This is the meaning of open source, isn't it? :)

Rays of goodness to everyone.

**Comment by QoLTech** [comment]
> I subscribe to this thread and, therefore, receive a ton of notifications. Folks, come on! This is an open-source project. I think everyone should understand what this means. It’s a little funny to read all these demands and ultimatums to the Flutter team, which already made the best cross-platform framework. Believe me, I know what I'm talking about (you can look at my GitHub profile).
> 
> So, let's be patient... or fix this problem yourself. This is the meaning of open source, isn't it? :)
> 
> Rays of goodness to everyone.

Fine - I'll do it myself. Just tell me how!

**Comment by wj-yang-pro** [comment]
> > I subscribe to this thread and, therefore, receive a ton of notifications. Folks, come on! This is an open-source project. I think everyone should understand what this means. It’s a little funny to read all these demands and ultimatums to the Flutter team, which already made the best cross-platform framework. Believe me, I know what I'm talking about (you can look at my GitHub profile).
> > So, let's be patient... or fix this problem yourself. This is the meaning of open source, isn't it? :)
> > Rays of goodness to everyone.
> 
> Fine - I'll do it myself. Just tell me how!

https://github.com/flutter/flutter/issues/69529#issuecomment-738469664
I would suggest this solution for now. 

The problem lies in the unique behavior which might be "only apple can do"

**Comment by geronimol** [comment]
> I think once we fix #139263, then this functionality can be implemented as a pub package. The only way I know to make this work is to delegate scrolling to the browser, which is currently broken by #139263.

That issue has just been marked as completed. Is it possible to fix this?

**Comment by Peshawa-k-kamil** [comment]
4.5 years of an issue ! 😩

**Comment by iapicca** [comment]
> Unfortunately, no news on this one. Flutter currently does custom scrolling and the browser is unaware that anything scrolls at all. However, we hope to start making progress on #139263 soon (once we find an owner we'll upgrade to P1). After it is fixed, it should be possible to implement this functionality as a package.

cc @yjbanov

**Comment by iapicca** [comment]
> > I think once we fix #139263, then this functionality can be implemented as a pub package. The only way I know to make this work is to delegate scrolling to the browser, which is currently broken by #139263.
> 
> > Unfortunately, no news on this one. Flutter currently does custom scrolling and the browser is unaware that anything scrolls at all. However, we hope to start making progress on #139263 soon (once we find an owner we'll upgrade to P1). After it is fixed, it should be possible to implement this functionality as a package.
> 
> That issue has just been marked as completed. Is it possible to fix this?

cc @yjbanov

**Comment by Blackkadder** [comment]
This would be a game changer for flutter on mobile web

**Comment by kevmoo** [comment]
@nopparatma – FLutter web is designed for apps, not websites.

**Comment by Peshawa-k-kamil** [comment]
it goes to 5 years !

**Comment by commandiron** [comment]
I think solution is;
1 - Call Apple safari team, request an api for Safari.
2 - Call Google chrome team, request an api for Chrome.

Is there a form or something we can use to make a request?

**Comment by rednikisfun** [comment]
Any updates on the issue?

**Comment by jmagman** [comment]
@yjbanov drive-by comment: do Safari 15.4 viewport units help with this problem? https://stackoverflow.com/a/75648985/431116

**Comment by mncorreia** [comment]
> Any updates on the issue?

I just add a body css `touch-action: 'none';` and worked. 
And our flutter web page was injected in a React App. And that flutter solution use ScrollView on PageWidget.

w/ @devguusta

**Comment by Piinks** [comment]
> Any updates on the issue?

As stated previously on this issue...
Per our wiki on [issue hygiene](https://github.com/flutter/flutter/tree/master/docs/contributing/issue_hygiene#do-not-add-me-too-or-same-or-is-there-an-update-comments-to-issues-or-prs):

> Do not add "me too" or "same" or "is there an update" comments to issues or PRs

Continued posts like this are not constructive and will result in restrictions to make further comments in this repository. They also make it hard to find helpful information like above.

**Comment by 1l0** [comment]
> I just added a css on body, like touch-action: 'none'; and worked.

Live examples?

**Comment by devguusta** [comment]
> > I just added a css on body, like touch-action: 'none'; and worked.
> 
> Live examples?

`<div style={{ touchAction: 'none' }}>`

**Comment by mncorreia** [comment]
> > > I just added a css on body, like touch-action: 'none'; and worked.
> > 
> > 
> > Live examples?
> 
> `<div style={{ touchAction: 'none' }}>`

I had this live example and just switch on/off `touch-action` body styles properties on devtools.

https://hivesey-88262.web.app/#/

**Comment by 1l0** [comment]
Thanks but, I don't have devtools on my mobile browser. I just wanted to see the live demo on mobile.

**Comment by iapicca** [comment]
> > > > I just added a css on body, like touch-action: 'none'; and worked.
> > > 
> > > 
> > > Live examples?
> > 
> > 
> > `<div style={{ touchAction: 'none' }}>`
> 
> I had this live example and just switch on/off `touch-action` body styles properties on devtools.
> 
> https://hivesey-88262.web.app/#/

 @mncorreia  it doesn't work on chrome/android

![scroll](https://github.com/user-attachments/assets/a4c0fa69-824a-4a1c-9753-b413f6d4100c)

 @mncorreia can you give an example?

**Comment by mncorreia** [comment]
> @mncorreia it doesn't work on chrome/android
> 
> ![scroll](https://private-user-images.githubusercontent.com/45637986/373668238-a4c0fa69-824a-4a1c-9753-b413f6d4100c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNTA4MzYsIm5iZiI6MTcyODA1MDUzNiwicGF0aCI6Ii80NTYzNzk4Ni8zNzM2NjgyMzgtYTRjMGZhNjktODI0YS00YTFjLTk3NTMtYjQxM2Y2ZDQxMDBjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA0VDE0MDIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxMDhlN2RkMGI0NzY5ZWViYjg1NWQyM2ZmZDkyNzQzNWNhOThkYWVmYzYzYTA3MWRmOGVlODVhNjhhYWE3ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3NNxilXVMRs68QxZfM7TcKP3bx5T2kKmFaW89lU11FI))
> 
> @mncorreia can you give an example?

I don't understand your gif because just worked, alright?! hahaha

But, I had put in `<body>` element follow with attribute `style="touch-action: 'none';"` (I just used a class btw but work as the same) or if you can, try this same  `style="touch-action: 'none';"`  in nearest element to your flutter web injection.

**Comment by 1l0** [comment]
@mncorreia 
OK, I just created a repo, but it doesn't seem to be working using your `style="touch-action: none;"`.
Demo: https://1l0.github.io/scroll_testbed/
Source: https://github.com/1l0/scroll_testbed

**Comment by iapicca** [comment]
> > > <img alt="" height="400" src="https://user-images.githubusercontent.com/19904063/97805735-36fa3880-1c58-11eb-92ca-0c7436080c6f.gif">	<img alt="" height="400" src="https://user-images.githubusercontent.com/19904063/97805757-52654380-1c58-11eb-95a5-8d747c560240.gif">
> >
> > @mncorreia it doesn't work on chrome/android
> >
> >![scroll](https://private-user-images.githubusercontent.com/45637986/373668238-a4c0fa69-824a-4a1c-9753-b413f6d4100c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxNDM2NjQsIm5iZiI6MTcyODE0MzM2NCwicGF0aCI6Ii80NTYzNzk4Ni8zNzM2NjgyMzgtYTRjMGZhNjktODI0YS00YTFjLTk3NTMtYjQxM2Y2ZDQxMDBjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDE1NDkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NDA1OThhMmQ2NzhlZjE3ZGZhYjU1ZjdhMTJlNjI0YzZjNmU5MjYyOWU5NjlhMzdkOTRiNDI1YzNkYjVlZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DTUaocVwDNKjJB_8Dah8Jk8vE72j5qHbhiMo1038fx8) 
>
> I don't understand your gif because just worked, alright?! hahaha

@mncorreia no it doesn't
this is how is supposed to work, focus on chrome's address bar

![scroll_ok](https://github.com/user-attachments/assets/9264084f-d9fa-4556-9e94-1ba824629b05)

I don't want to nitpick, 
I just want to avoid this issue to be slapped with `label:"workaround available"`
and forgot forever (like too many other `web` issues)

**Comment by QoLTech** [comment]
Okay, this thread is getting a little hard to follow recently.

Is there a workaround that we can add to an app that enables the behavior of the app bars to hide when a Flutter view is being scrolled? How exactly would someone implement this workaround?

**Comment by jongseokleedev** [comment]
Any Update?
I have been suffering from this issue

**Comment by gusflrnd** [comment]
None of the above workarounds (gambiarras) have worked for me as of today's date. I'm in the middle of developing an app that uses Flutter to display high-quality images and videos. I was excited to show it in full screen on mobile devices, but now I'm really frustrated by how long this issue has been open without being addressed. I guess I'll simply use React or another tool that already has this feature easily implemented. This is a HUGE problem in today's modern visual web applications.

**Comment by olof-dev** [comment]
Yes, this issue is a frustrating one. But also no: Flutter web has been getting love. They have worked on getting the wasm standards developed to support garbage collection to work better with Dart and Flutter (talk about long-term thinking!), they have implemented building separate framework bundles for different browsers to minimize download times, they've introduced new JS interop features, and I'm sure there's much more (maybe there's a web roadmap somewhere?). My 2 cents are: let's keep these GitHub issues focused on the technical issues (and solutions), let's put thumbs up on the issues we really want to see solved, and let's try to contribute and figure out fixes as best we can.

**Comment by flt-phy** [comment]
Thanks for the PoC! 

Any news on a potential fix being merged? 👀
