### ISSUE TITLE
"Ignore for baseline purposes" widget

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#7037]
We should have a widget that causes an entire subtree to be ignored for the purposes of baseline computations.

For example, we would use this to wrap the label of an `InputContainer`.

**Comment by Hixie** [comment]
Closing since there's been no demand for this, though it does make sense from a completeness perspective.

**Comment by Hixie** [comment]
The demand for this would be so that you can align a button and a text field without the text field label counting as the baseline.

**Comment by ko16a46** [comment]
Hello, just chipping in to say that I was recently looking for this feature as well.

My app had a row containing two columns, and I wanted to align the row's cross axis by baseline, but Flutter wasn't using the baseline of the right child basically
![Screenshot_20220616-154116~2](https://user-images.githubusercontent.com/100613422/174190527-dafc63b4-9d54-4efe-b438-ff25ae4d3eb2.png)

I wanted the two large text to be aligned by baseline, so I wanted flutter to ignore the baseline of the small text on the left.

 I fixed it by writing my own `IgnoreBaseline` widget. It uses my own `RenderIgnoreBaseline` that extends `RenderProxyBox` but returns `null` in `computeDistanceToActualBaseline`. 

Hopefully this is the 'right' way to do it, the results turned out like how I wanted:
![Screenshot_20220616-154124~2](https://user-images.githubusercontent.com/100613422/174190544-96acee53-6b83-401e-8a1c-1f9ca6270894.png)


I'd still like this widget to be in the framework itself though.

**Comment by Hixie** [comment]
@ko16a46 You should definitely feel empowered to contribute a widget! Check out our contributing guide (linked below). Feel free to reach out on our Discord server (on the #hackers-new channel) if you need help!

**Comment by Pierre2tm** [comment]
I think I just ran into this issue. I would like to have my button aligned with the inner text of text fields like so: (Texts in blue are `Text` widgets):

<img width="681" alt="Screenshot 2022-09-16 at 16 02 01" src="https://user-images.githubusercontent.com/80128417/190658911-0bba26f9-2e1d-443c-bf0c-9fd4f09cb21f.png">

Using baseline alignment I got the following:

<img width="1075" alt="Screenshot 2022-09-16 at 16 08 54" src="https://user-images.githubusercontent.com/80128417/190658930-a55e3d23-74b6-41e8-a0e2-e51883848b3d.png">

I've fixed this issue by following @ko16a46 method. I've just wrapped my labels inside a custom `IgnoreBaseline` widget.  Thank you :)

Here's the code for the widget:

```dart
class IgnoreBaseline extends SingleChildRenderObjectWidget {
  const IgnoreBaseline({super.key, super.child});

  @override
  RenderObject createRenderObject(BuildContext context) =>
      RenderIgnoreBaseline();
}

class RenderIgnoreBaseline extends RenderProxyBox {
  @override
  double? computeDistanceToActualBaseline(TextBaseline baseline) {
    return null;
  }
}
```

**Comment by Hixie** [comment]
That sounds right to me. You may wish to check the RenderBox class' definition to see if there's anything else in there that needs overriding.

**Comment by justinmc** [comment]
@pierre2tm Could you check if the button alignment problem you mentioned in https://github.com/flutter/flutter/issues/7037#issuecomment-1249451628 is still happening on master?  Or post the code that you used?  It seems to have been fixed based on [my review](https://github.com/flutter/flutter/pull/131220#pullrequestreview-1545988855) of the linked PR, but maybe I'm not doing it the same as you.
