### ISSUE TITLE
Suggestion code is not working

### ISSUE THREAD

**Issue by pqtrong17** [flutter/flutter#70693]
I have just updated `Android Studio to version 4.1.0` and `Flutter to version 1.22.3`. I get an error about suggestion code. I press `Ctrl + Space` but it's also not working. How to fix it?

`flutter doctor -v`
```
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.18363.1198], locale en-US)
    • Flutter version 1.22.3 at C:\Users\pqtrong17\AppData\Local\Android\flutter
    • Framework revision 8874f21e79 (3 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\pqtrong17\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
```

**Comment by yosikal** [comment]
Same here since installing Flutter 1.22.4. Quick fixes doesn't suggest adding imports and no suggestion for class names.

`
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 6.1.7601], locale he-IL)
    • Flutter version 1.22.4 at C:\tools\flutter
    • Framework revision 1aafb3a8b9 (4 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\yosikal\AppData\Local\Android\sdk1
    • Platform android-30, build-tools 29.0.0
    • ANDROID_HOME = C:\Users\yosikal\AppData\Local\Android\sdk1
    • ANDROID_SDK_ROOT = C:\Users\yosikal\AppData\Local\Android\sdk1
    • Java binary at: C:\Program Files\Android\Android Studio2\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\yosikal\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (1 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 2 categories.
`

**Comment by llullanqui** [comment]
Same issue happening here in 1.22.4. It occurs when a new build is in progress.

`flutter doctor -v`

```
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [VersiÃ³n 10.0.18363.1198], locale es-EC)
    • Flutter version 1.22.4 at C:\src\flutter
    • Framework revision 1aafb3a8b9 (4 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\larizaga\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\larizaga\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (1 available)
    • Redmi Note 9 Pro (mobile) • 935ea3bd • android-arm64 • Android 10 (API 29)
```

**Comment by pqtrong17** [comment]
Any update?

**Comment by dufei816** [comment]
me too

**Comment by TahaTesser** [comment]
Hi @pqtrong17 
Can't reproduce any issue with suggestions on Android Studio 4,.1.1 on the latest stable Flutter channel

Doctor -v doesn't correct exact version, known issue. 
```bash
[✓] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19042.630], locale en-US)
    • Flutter version 1.22.4 at C:\Code\flutter_stable
    • Framework revision 1aafb3a8b9 (5 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.51.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
```

Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by yosikal** [comment]
This issue happens to me on VsCode and is a serious bummer.  I'm not sure what do you relate to as Flutter issue but there were many dev env issues that were addressed, such as [43620](https://github.com/flutter/flutter/issues/43620) which was solved on Flutter 1.22.4 and perhaps related to this issue.

**Comment by pqtrong17** [comment]
Upgrade flutter version to 1.22.4 works for me.

**Comment by TahaTesser** [comment]
Hi @pqtrong17  @yosikal 
I have been working on the VS Code and Android Studio, had no such issue even on multiple laptops on  `1.22.4`
Please provide reproducible steps that reproduce this issue om this flutter version
Thank you

**Comment by pqtrong17** [comment]
> Hi @pqtrong17 @yosikal
> I have been working on the VS Code and Android Studio, had no such issue even on multiple laptops on `1.22.4`
> Please provide reproducible steps that reproduce this issue om this flutter version
> Thank you

Please import any 3rd library from pub.dev and call it anywhere in your project or  create a new class then call it. Does the IDE suggest code for you?

**Comment by pqtrong17** [comment]
Ex:  Use `shared_preferences 0.5.12+4` then typing `SharedPr..`, nothing happen

**Comment by yosikal** [comment]
> Hi @pqtrong17 @yosikal
> I have been working on the VS Code and Android Studio, had no such issue even on multiple laptops on `1.22.4`
> Please provide reproducible steps that reproduce this issue om this flutter version
> Thank you

I did the following: 

1. Run flutter clean
2. Close Vscode.
3. Open Vscode.
=> Everything works as expected at this stage. I get full autocomplete as expected.

4. Start device and run and the App 
=> No autocomplete besides for classes that are in the same file I'm editing.

**Comment by yosikal** [comment]
One thing to add, even though I don't get autocomplete for classes I do get autocomplete for the classes properties. For example, if I type SliverToBo... it won't autocomplete to SliverToBoxAdapter. But once I write the complete word SliverToBoxAdapter, it will suggest me properties for this class correctly.

**Comment by pqtrong17** [comment]
> One thing to add, even though I don't get autocomplete for classes I do get autocomplete for the classes properties. For example, if I type SliverToBo... it won't autocomplete to SliverToBoxAdapter. But once I write the complete word SliverToBoxAdapter, it will suggest me properties for this class correctly.

That's right. Me too.

**Comment by TahaTesser** [comment]
Hi @pqtrong17 @yosikal 
Steps from https://github.com/flutter/flutter/issues/70693#issuecomment-730182281, works fine
Tried flutter clean steps, https://github.com/flutter/flutter/issues/70693#issuecomment-730192551
No issues in VS Code or Android Studio
### VS Cide
<img width="692" alt="Screenshot 2020-11-19 at 6 07 55 PM" src="https://user-images.githubusercontent.com/48603081/99667404-5aafe200-2a92-11eb-8f33-cb4e222d5423.png">

### Android Studio
<img width="602" alt="Screenshot 2020-11-19 at 5 25 21 PM" src="https://user-images.githubusercontent.com/48603081/99667420-626f8680-2a92-11eb-95ea-c2d49d209d93.png">


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1aafb3a8b9 (6 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • Taha’s iPad (mobile)                • 00008020-000255113EE8402E
      • ios • iOS 14.2
    • iPhone SE (2nd generation) (mobile) • F0FD09FB-9ABB-402D-9712-7AC7278ED742
      • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by yosikal** [comment]
> Hi @pqtrong17 @yosikal
> Steps from [#70693 (comment)](https://github.com/flutter/flutter/issues/70693#issuecomment-730182281), works fine
> Tried flutter clean steps, [#70693 (comment)](https://github.com/flutter/flutter/issues/70693#issuecomment-730192551)
> No issues in VS Code or Android Studio
> 
> ### VS Cide
> <img alt="Screenshot 2020-11-19 at 6 07 55 PM" width="692" src="https://user-images.githubusercontent.com/48603081/99667404-5aafe200-2a92-11eb-8f33-cb4e222d5423.png">
> 
> ### Android Studio
> <img alt="Screenshot 2020-11-19 at 5 25 21 PM" width="602" src="https://user-images.githubusercontent.com/48603081/99667420-626f8680-2a92-11eb-95ea-c2d49d209d93.png">
> 
> flutter doctor -v

Maybe it's related to the project size (like [43620](https://github.com/flutter/flutter/issues/43620). Are there any logs we can supply you with that would help you debug or reproduce this issue?

**Comment by pqtrong17** [comment]
@TahaTesser Try again with larger size project and working at least 10 minutes. Because when I just open project, it's worked for me but after a period of time, it's not working.

**Comment by TahaTesser** [comment]
Hi @pqtrong17  @yosikal 
Cloned https://github.com/jesusrp98/spacex-go (good size project with many packages)  and played with the code for half an hour and ran it multiple times 
Ran fluttter clean and restart IDE, VSC Code and it still suggestion works fine on the stable channel 
![image](https://user-images.githubusercontent.com/48603081/99795359-a8d7ea80-2b51-11eb-87a9-d8ecd3c55bdc.png)

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1aafb3a8b9 (7 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

 
[✓] Connected device (1 available)            
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios • iOS 14.2

! Doctor found issues in 1 category.
```

</details>

**Comment by llullanqui** [comment]
In my case, I execute my project once, and the IDE stopped doing suggestions. After running the first `flutter clean`, the dart analyzer restarted. Then it started recommending widgets.
![image](https://user-images.githubusercontent.com/25188721/99804182-9a191580-2b08-11eb-9bd6-233fdf55a0d4.png)

When compiling, the Dart analyzer restarts (watch the bottom left numbers)
![image](https://user-images.githubusercontent.com/25188721/99804457-08f66e80-2b09-11eb-8a05-fb00f0415591.png)

And then it stops recommending 
![image](https://user-images.githubusercontent.com/25188721/99804679-5e328000-2b09-11eb-8463-7f8ad9a599cd.png)

Still don't know if this has something related with the 'The dart analyzer has terminated' issue that was solved in the last version of flutter `1.22.4`. The vs code notification does not appear in my screen, but the behaviour is the same.

**Comment by yosikal** [comment]
> Hi @pqtrong17 @yosikal
> Cloned https://github.com/jesusrp98/spacex-go (good size project with many packages) and played with the code for half an hour and ran it multiple times
> Ran fluttter clean and restart IDE, VSC Code and it still suggestion works fine on the stable channel
> ![image](https://user-images.githubusercontent.com/48603081/99795359-a8d7ea80-2b51-11eb-87a9-d8ecd3c55bdc.png)
> 
> flutter doctor -v

I cloned spacex project and could not reproduce the problem with this project. Furthermore, I added all the dependencies I have in my project to this project and still could not reproduce the issue. Still, in my own project, problem persist.

**Comment by dufei816** [comment]
> 我刚刚更新`Android Studio to version 4.1.0`和`Flutter to version 1.22.3`。我收到有关建议代码的错误。我按，`Ctrl + Space`但它也没有用。如何解决？
> 
> `flutter doctor -v`
> 
> ```
> [√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.18363.1198], locale en-US)
>     • Flutter version 1.22.3 at C:\Users\pqtrong17\AppData\Local\Android\flutter
>     • Framework revision 8874f21e79 (3 weeks ago), 2020-10-29 14:14:35 -0700
>     • Engine revision a1440ca392
>     • Dart version 2.10.3
> 
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at C:\Users\pqtrong17\AppData\Local\Android\sdk
>     • Platform android-30, build-tools 30.0.2
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
>     • All Android licenses accepted.
> 
> [!] Android Studio (version 4.1.0)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     X Flutter plugin not installed; this adds Flutter specific functionality.
>     X Dart plugin not installed; this adds Dart specific functionality.
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> ```

Deleting the SDK and downloading the new SDK can solve the problem

**Comment by pqtrong17** [comment]
@dufei816  Did you fix this problem by downloading and reinstalling the SDK?

**Comment by yosikal** [comment]
> > 我刚刚更新`Android Studio to version 4.1.0`和`Flutter to version 1.22.3`。我收到有关建议代码的错误。我按，`Ctrl + Space`但它也没有用。如何解决？
> > `flutter doctor -v`
> > ```
> > [√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.18363.1198], locale en-US)
> >     • Flutter version 1.22.3 at C:\Users\pqtrong17\AppData\Local\Android\flutter
> >     • Framework revision 8874f21e79 (3 weeks ago), 2020-10-29 14:14:35 -0700
> >     • Engine revision a1440ca392
> >     • Dart version 2.10.3
> > 
> > 
> > [√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
> >     • Android SDK at C:\Users\pqtrong17\AppData\Local\Android\sdk
> >     • Platform android-30, build-tools 30.0.2
> >     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
> >     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> >     • All Android licenses accepted.
> > 
> > [!] Android Studio (version 4.1.0)
> >     • Android Studio at C:\Program Files\Android\Android Studio
> >     X Flutter plugin not installed; this adds Flutter specific functionality.
> >     X Dart plugin not installed; this adds Dart specific functionality.
> >     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> > ```
> 
> Deleting the SDK and downloading the new SDK can solve the problem
> There was no problem with version 1.22.1

Tried that. Didn't work for me.

**Comment by dufei816** [comment]
> > > 我刚刚更新`Android Studio to version 4.1.0`和`Flutter to version 1.22.3`。我收到有关建议代码的错误。我按，`Ctrl + Space`但它也没有用。如何解决？
> > > `flutter doctor -v`
> > > ```
> > > [√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.18363.1198], locale en-US)
> > >     • Flutter version 1.22.3 at C:\Users\pqtrong17\AppData\Local\Android\flutter
> > >     • Framework revision 8874f21e79 (3 weeks ago), 2020-10-29 14:14:35 -0700
> > >     • Engine revision a1440ca392
> > >     • Dart version 2.10.3
> > > 
> > > 
> > > [√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
> > >     • Android SDK at C:\Users\pqtrong17\AppData\Local\Android\sdk
> > >     • Platform android-30, build-tools 30.0.2
> > >     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
> > >     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> > >     • All Android licenses accepted.
> > > 
> > > [!] Android Studio (version 4.1.0)
> > >     • Android Studio at C:\Program Files\Android\Android Studio
> > >     X Flutter plugin not installed; this adds Flutter specific functionality.
> > >     X Dart plugin not installed; this adds Dart specific functionality.
> > >     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> > > ```
> > 
> > 
> > 删除SDK并下载新的SDK可以解决问题
> > 1.22.1版本没有问题
> 
> 试过了。没为我工作。

我发现和项目有关系，我新建的项目没问题

**Comment by darshankawar** [comment]
@pqtrong17 
Are you still facing the issue ? I am on latest stable (1.22.4) using Android Studio and see no issues with suggestions.

<img width="548" alt="Screenshot 2020-11-24 at 3 04 03 PM" src="https://user-images.githubusercontent.com/67046386/100075794-6ae70900-2e66-11eb-8322-8c239682ee7b.png">

Can you possibly try `Invalidate Cache / Restart` from `File` menu and see if it works ?

**Comment by yosikal** [comment]
> @pqtrong17
> Are you still facing the issue ? I am on latest stable (1.22.4) using Android Studio and see no issues with suggestions.
> 
> <img alt="Screenshot 2020-11-24 at 3 04 03 PM" width="548" src="https://user-images.githubusercontent.com/67046386/100075794-6ae70900-2e66-11eb-8322-8c239682ee7b.png">
> 
> Can you possibly try `Invalidate Cache / Restart` from `File` menu and see if it works ?

Not sure if you meant to restart Analysis server but when I do that, the autocomplete is back again however hot reload on save is gone (clicking manually on hot reload does work)

**Comment by baku-apps** [comment]
I have the same issue with VS Code and Android Studio.

**Comment by pqtrong17** [comment]
Any update?

**Comment by pqtrong17** [comment]
> @pqtrong17
> Are you still facing the issue ? I am on latest stable (1.22.4) using Android Studio and see no issues with suggestions.
> 
> <img alt="Screenshot 2020-11-24 at 3 04 03 PM" width="548" src="https://user-images.githubusercontent.com/67046386/100075794-6ae70900-2e66-11eb-8322-8c239682ee7b.png">
> 
> Can you possibly try `Invalidate Cache / Restart` from `File` menu and see if it works ?

I have done this many times but issue is still exist. :(

**Comment by pqtrong17** [comment]
In my project, these keyword as `Container`, `Column` or `Row` (belong to Flutter) is work. But keyword as `SharedPreferences` or `Toast` (third-party library) is not working? @darshankawar

**Comment by pqtrong17** [comment]
I just found out that this problem is only present in a few projects.

**Comment by pqtrong17** [comment]
I have fixed this issue. I don't know what's reason. I have updated Flutter's version and Android studio's version. Delete cache and `flutter clean` then everything work for me.

**Comment by yosikal** [comment]
> I have fixed this issue. I don't know what's reason. I have updated Flutter's version and Android studio's version. Delete cache and `flutter clean` then everything work for me.

To which Flutter version did you update? how do you delete the cache?

**Comment by darshankawar** [comment]
@pqtrong17 Good to know your issue is resolved. I am going ahead and closing this as fixed.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by pqtrong17** [comment]
> > I have fixed this issue. I don't know what's reason. I have updated Flutter's version and Android studio's version. Delete cache and `flutter clean` then everything work for me.
> 
> To which Flutter version did you update? how do you delete the cache?

Update version Flutter from 1.22.3 to 1.22.4 and click `Invalidate Cache/ Restart` in `Files`. I fixed auto completion for 3rd library by put them below `depedences` not `dev_depedences` then everything work for me.

**Comment by llullanqui** [comment]
So, after reading all the responses, I tried updating Android Studio, the dart and flutter plugins; and then ran `flutter pub cache repair`. Started debugging, and, surprisingly, suggestions worked fine.

Had to stopped debugging, but after a few hours I came back, opened vscode, started debugging, and ran into the same issue again.

I ran `flutter doctor -v` to make this post, and this was the result:

```
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [VersiÃ³n 10.0.18363.1198], locale es-419)
    • Flutter version 1.22.4 at C:\src\flutter
    • Framework revision 1aafb3a8b9 (2 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\luis1\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\luis1\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (1 available)
    • Redmi Note 9 Pro (mobile) • 935ea3bd • android-arm64 • Android 10 (API 29)
```

Don't know why the dart and flutter plugins aren't recognized by the flutter doctor, but they are installed.

![image](https://user-images.githubusercontent.com/25188721/100517010-b7c42b80-3155-11eb-9082-5fb5beb1988b.png)

**Comment by ash2osh** [comment]
the problem i had was using older analyzer version
```
dependency_overrides:
  analyzer: "0.39.17"
```
once i commnted that and ran` flutter pub upgrade` everything was fine

**Comment by louisdeveseleer** [comment]
I experience the same issue as described, since a week or two: starting Android studio, everything works fine. After running the program, code suggestions stop working. If typing the whole class name, then suggestions for its properties do appear.
Running `flutter clean` solves the issue temporarily, until I stop and run the program again. Hours of research and I haven't found any solution that works.

**Comment by yosikal** [comment]
> I experience the same issue as described, since a week or two: starting Android studio, everything works fine. After running the program, code suggestions stop working. If typing the whole class name, then suggestions for its properties do appear.
> Running `flutter clean` solves the issue temporarily, until I stop and run the program again. Hours of research and I haven't found any solution that works.

Yes, it's still a problem over here for over a month. No solutions as for now.

**Comment by DarkHeros09** [comment]
i also still have this problem .

**Comment by hmawla** [comment]
Yep problem still exists.
I'm on Android Studio 4.1.1 & Flutter 1.22.5 & Dart 2.10.4

**Comment by DarkHeros09** [comment]
I don't know about android studio, but It's worth noting that i fixed my problem deleting my vscode configuration file, which made vscode create a new file then i applied my old configuration back.

**Comment by regisksc** [comment]
I mean, for real, is this EVER going to get fixed? It destroys the coding experience and my productivity having to reload the window on VSCode every 60 seconds or so. I remember having stopped coding on windows and moving to MacOS and there was no longer this kind of issue, but now I lost access for some time to MacOS and I went back to windows, and  8 months after experiencing this for the first time this still happens.

What is possibly wrong?

**Comment by y455ien** [comment]
How come this Issue is closed? man that's frustrating!

**Comment by hmawla** [comment]
Exactly, I can't understand how did the maintainers decide that this issue requires closing, this actually made me stop coding i  flutter for quite a while now with no solution available across the whole internet

**Comment by baku-apps** [comment]
It's a very frustrating issue, but there are several issues open which address the same problem. Hopefully they will find a fix soon.

https://github.com/Dart-Code/Dart-Code/issues/2990
https://github.com/dart-lang/sdk/issues/44574
https://github.com/dart-lang/sdk/issues/44650

**Comment by AdrienDelgado** [comment]
I have had the same problem for the past couple months too, just found this thread.
Basically whenever I open/reopen my project, the autocomplete fails to detect classes, as well as imports, and fails to auto-import the packages I need.

I have a workaround, it is a bit cumbersome but it works for me, I hope it will for you. I code on VSCode, but as it seems to be a Flutter-related issue it may work also on Android Studio. I hope they will fix that soon.

So, when you open your project on VSCode, just open a Terminal and run `flutter pub get`. It fixes everything for me. I also have to run the command if I add new files and they are not detected. After that, autocomplete works as a charm.

Hope it helps!

**Comment by DJSL1NKY** [comment]
Hello together, I have the same Problem with Android Studio.

When I want to add a decoration to a Container, when there is already something "inside" the Container, I'm not getting the Suggestion for that decoration, but when I create a new Contrainer and write then deco I get the Suggestion for Decoration

**Comment by hmawla** [comment]
@pqtrong17 I've managed to find the issue in my end which was an asset folder that contained a huge amount of images so whenever I run the app while using this asset folder my code suggestion stops for widgets so all I had to do is disable it and it worked like charm... <3
Not sure if it'll work for you, but it wouldn't hurt to try...
Though I will look into it furthermore to report such an issue

**Comment by Saliheen** [comment]
flutter sucks. I am leaving this framework. There are number of other issues like this in flutter which google does not take serious

**Comment by louisdeveseleer** [comment]
> _EDIT_
> Managed to get around the issue by just running flutter pub get after running the app.

Doing:
`flutter clean`
`flutter pub get`
after running the app, and while it's still running, makes code suggestions work again.
It's an annoying workaround to do after every run, but it works (been doing it for 3 months now).
Hot reload doesn't disturb this fragile working state, but hot restart does.

**Comment by DarkHeros09** [comment]
Turning off the LSP option is what worked out with me.
btw i'm using vscode.
And yeah i agree that the flutter team should address this issue it's very annoying.

**Comment by SonXuanNguyen2k** [comment]
> LSP

Could you please tell me where I can find this option?

**Comment by SonXuanNguyen2k** [comment]
> Turning off the LSP option is what worked out with me.
> btw i'm using vscode.
> And yeah i agree that the flutter team should address this issue it's very annoying.


@DarkHeros09  Could you please tell me where I can find this option?

**Comment by DarkHeros09** [comment]
> > Turning off the LSP option is what worked out with me.
> > btw i'm using vscode.
> > And yeah i agree that the flutter team should address this issue it's very annoying.
> 
> 
> @DarkHeros09  Could you please tell me where I can find this option?

@SonXuanNguyen2k hi, go to the settings and type 'ldp mode' in the search bar, them select Dart: preview lsp from the results, you should click on 'Edit in settings.json' specifically, after that a new tab should open with the cursor hovering on the "dart.previewLsp". Chahge the value from true to false.

Hope it helps, please lets us know if it worked for you.
