### ISSUE TITLE
Android build failed for new Flutter project (Flutter 1.22.4)

### ISSUE THREAD

**Issue by clive107** [flutter/flutter#71713]
## Steps to Reproduce

1. Create a new Flutter project with Android Studio.
2. Try to run the app on Android Emulator. 
3. Build failed. (run from Android Studio and also VS Code, both failed)
* I tried for hours but the issue is still not solved.
* I able to run the app on iOS Simulator.

## Logs

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find asm-commons.jar (org.ow2.asm:asm-commons:6.0).
     Searched in the following locations:
         https://jcenter.bintray.com/org/ow2/asm/asm-commons/6.0/asm-commons-6.0.jar
   > Could not find asm-util.jar (org.ow2.asm:asm-util:6.0).
     Searched in the following locations:
         https://jcenter.bintray.com/org/ow2/asm/asm-util/6.0/asm-util-6.0.jar
   > Could not find proguard-gradle.jar (net.sf.proguard:proguard-gradle:6.0.3).
     Searched in the following locations:
         https://jcenter.bintray.com/net/sf/proguard/proguard-gradle/6.0.3/proguard-gradle-6.0.3.jar
   > Could not find protobuf-java-util.jar (com.google.protobuf:protobuf-java-util:3.4.0).
     Searched in the following locations:
         https://jcenter.bintray.com/com/google/protobuf/protobuf-java-util/3.4.0/protobuf-java-util-3.4.0.jar
   > Could not find protobuf-java.jar (com.google.protobuf:protobuf-java:3.4.0).
     Searched in the following locations:
         https://jcenter.bintray.com/com/google/protobuf/protobuf-java/3.4.0/protobuf-java-3.4.0.jar
   > Could not find javawriter.jar (com.squareup:javawriter:2.5.0).
     Searched in the following locations:
         https://jcenter.bintray.com/com/squareup/javawriter/2.5.0/javawriter-2.5.0.jar
   > Could not find bcprov-jdk15on.jar (org.bouncycastle:bcprov-jdk15on:1.56).
     Searched in the following locations:
         https://jcenter.bintray.com/org/bouncycastle/bcprov-jdk15on/1.56/bcprov-jdk15on-1.56.jar
   > Could not find jimfs.jar (com.google.jimfs:jimfs:1.1).
     Searched in the following locations:
         https://jcenter.bintray.com/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar
   > Could not find httpcore.jar (org.apache.httpcomponents:httpcore:4.4.10).
     Searched in the following locations:
         https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.4.10/httpcore-4.4.10.jar
   > Could not find kotlin-reflect.jar (org.jetbrains.kotlin:kotlin-reflect:1.3.41).
     Searched in the following locations:
         https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-reflect/1.3.41/kotlin-reflect-1.3.41.jar
   > Could not find antlr4.jar (org.antlr:antlr4:4.5.3).
     Searched in the following locations:
         https://jcenter.bintray.com/org/antlr/antlr4/4.5.3/antlr4-4.5.3.jar
   > Could not find commons-io.jar (commons-io:commons-io:2.4).
     Searched in the following locations:
         https://jcenter.bintray.com/commons-io/commons-io/2.4/commons-io-2.4.jar
   > Could not find javapoet.jar (com.squareup:javapoet:1.8.0).
     Searched in the following locations:
         https://jcenter.bintray.com/com/squareup/javapoet/1.8.0/javapoet-1.8.0.jar
   > Could not find gson.jar (com.google.code.gson:gson:2.8.5).
     Searched in the following locations:
         https://jcenter.bintray.com/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar
   > Could not find kotlin-stdlib.jar (org.jetbrains.kotlin:kotlin-stdlib:1.3.41).
     Searched in the following locations:
         https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/1.3.41/kotlin-stdlib-1.3.41.jar
   > Could not find auto-value.jar (com.google.auto.value:auto-value:1.5.2).
     Searched in the following locations:
         https://jcenter.bintray.com/com/google/auto/value/auto-value/1.5.2/auto-value-1.5.2.jar
   > Could not find error_prone_annotations.jar (com.google.errorprone:error_prone_annotations:2.3.1).
     Searched in the following locations:
         https://jcenter.bintray.com/com/google/errorprone/error_prone_annotations/2.3.1/error_prone_annotations-2.3.1.jar
   > Could not find jdom2.jar (org.jdom:jdom2:2.0.6).
     Searched in the following locations:
         https://jcenter.bintray.com/org/jdom/jdom2/2.0.6/jdom2-2.0.6.jar
   > Could not find commons-compress.jar (org.apache.commons:commons-compress:1.12).
     Searched in the following locations:
         https://jcenter.bintray.com/org/apache/commons/commons-compress/1.12/commons-compress-1.12.jar
   > Could not find jsr305.jar (com.google.code.findbugs:jsr305:3.0.2).
     Searched in the following locations:
         https://jcenter.bintray.com/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar
   > Could not find failureaccess.jar (com.google.guava:failureaccess:1.0.1).
     Searched in the following locations:
         https://jcenter.bintray.com/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
   > Could not find listenablefuture.jar (com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava).
     Searched in the following locations:
         https://jcenter.bintray.com/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
   > Could not find checker-qual.jar (org.checkerframework:checker-qual:2.5.2).
     Searched in the following locations:
         https://jcenter.bintray.com/org/checkerframework/checker-qual/2.5.2/checker-qual-2.5.2.jar
   > Could not find animal-sniffer-annotations.jar (org.codehaus.mojo:animal-sniffer-annotations:1.17).
     Searched in the following locations:
         https://jcenter.bintray.com/org/codehaus/mojo/animal-sniffer-annotations/1.17/animal-sniffer-annotations-1.17.jar
   > Could not find commons-codec.jar (commons-codec:commons-codec:1.10).
     Searched in the following locations:
         https://jcenter.bintray.com/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
   > Could not find annotations.jar (org.jetbrains:annotations:13.0).
     Searched in the following locations:
         https://jcenter.bintray.com/org/jetbrains/annotations/13.0/annotations-13.0.jar
   > Could not find jaxb-core.jar (org.glassfish.jaxb:jaxb-core:2.2.11).
     Searched in the following locations:
         https://jcenter.bintray.com/org/glassfish/jaxb/jaxb-core/2.2.11/jaxb-core-2.2.11.jar
   > Could not find stax-ex.jar (org.jvnet.staxex:stax-ex:1.7.7).
     Searched in the following locations:
         https://jcenter.bintray.com/org/jvnet/staxex/stax-ex/1.7.7/stax-ex-1.7.7.jar
   > Could not find txw2.jar (org.glassfish.jaxb:txw2:2.2.11).
     Searched in the following locations:
         https://jcenter.bintray.com/org/glassfish/jaxb/txw2/2.2.11/txw2-2.2.11.jar
   > Could not find istack-commons-runtime.jar (com.sun.istack:istack-commons-runtime:2.21).
     Searched in the following locations:
         https://jcenter.bintray.com/com/sun/istack/istack-commons-runtime/2.21/istack-commons-runtime-2.21.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 838ms
Exception: Gradle task assembleDebug failed with exit code 1

```

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H15 darwin-x64,
    locale en-MY)
    • Flutter version 1.22.4 at /Users/clive/developer/flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/clive/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/clive/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.8.4

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
```

**Comment by ProfHercules** [comment]
I am experiencing the exact same issue, also on MacOS. 

Do you by any chance use TripMode or something similar?

**Comment by clive107** [comment]
> I am experiencing the exact same issue, also on MacOS.
> 
> Do you by any chance use TripMode or something similar?

I do not use that.

**Comment by ProfHercules** [comment]
> > I am experiencing the exact same issue, also on MacOS.
> > Do you by any chance use TripMode or something similar?
> 
> @ProfHercules
> I do not use that.

Awesome, I do so it's likely not related then.

I noticed on https://status.bintray.com that they experienced a high rate of 502 errors today between 8:20 and 8:28 UTC, perhaps the issue we're experiencing is related?

https://status.bintray.com Does say that all issues have been resolved at this time though.

**Comment by clive107** [comment]
@ProfHercules Have you tried again? It still doesn't work for me.

**Comment by ProfHercules** [comment]
I'm not certain if the JCenter fix maybe propagated in the mean time but here are the steps I've followed that *somehow* got everything working.

Also: I've tried switching between all of the release channels, nothing helped.

1. Flush DNS cache on MacOS using the following command: 
`sudo killall -HUP mDNSResponder; sudo killall mDNSResponderHelper; sudo dscacheutil -flushcache`

2. Delete ~/.gradle (I tried only deleting ~/.gradle/caches first, but that didn't seem to solve the problem)
    **Note:** This does mean you'll have to redownload however many packages were cached again.

3. In Android Studio: File -> Invalidate Caches / Restart.

4. Reboot computer.

Hope this helps.

**Comment by clive107** [comment]
@ProfHercules it doesn't work for me. Thanks anyway.

**Comment by TahaTesser** [comment]
Hi @clive107 
No issues on the stable here, it's probably your Gradle cache, please delete your Gradle cache and try again
Please check out this  [solution](https://stackoverflow.com/a/23271922)
or 
Open /Users/user_directoy/ in the terminal and execute `rm -rf .gradle`
If the problem persists
Can you please provide your complete `flutter run --verbose`
Thank you

**Comment by clive107** [comment]
@TahaTesser The problem still persists.
Log file:
[20201204_224322.Default.w0t0p0.69F094A4-6C5E-41AD-B0D6-4E484DE9D478.12345.2314025344.txt](https://github.com/flutter/flutter/files/5643404/20201204_224322.Default.w0t0p0.69F094A4-6C5E-41AD-B0D6-4E484DE9D478.12345.2314025344.txt)

**Comment by clive107** [comment]
I tried again without changing anything and now it works. (It failed on past Friday and Saturday).
Thanks.
