### ISSUE TITLE
Allow PgUp, PgDn, Home, End, ... keys for ListView scrolling

### ISSUE THREAD

**Issue by PavelPZ** [flutter/flutter#76918]
Scrolling without keyboard support is useless for Web and Desktop.
This feature is missing in https://github.com/flutter/flutter/issues/70866.
Maybe waiting for https://github.com/flutter/flutter/issues/44918?

**Comment by HansMuller** [comment]
CC @Piinks

**Comment by Piinks** [comment]
Hi @PavelPZ I believe we have implemented this feature already in https://github.com/flutter/flutter/pull/69795 and https://github.com/flutter/flutter/pull/72560
You can even specify your own custom keyboard shortcuts instead of the defaults if you like. :)

**Comment by PavelPZ** [comment]
Hi @Piinks, thanks a lot for excelent news. 

Unfortunately, I'm a little confused. Many web or windows desktop applications include a page with two independent scrollable ListView's. The one who has the focus responds to the scroll keys. I have no idea how to use PrimaryScrollController, PrioritizedIntents and others to modify my example, see below.

```
final sc1 = ScrollController();
final sc2 = ScrollController();

class TwoScrollBarApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Material(
        child: Row(children: [
          Expanded(
            child: Scrollbar(
              controller: sc1,
              isAlwaysShown: true,
              thickness: 16.0,
              hoverThickness: 16.0,
              child: ListView.builder(
                controller: sc1,
                itemExtent: 30,
                itemCount: 100,
                itemBuilder: (_, idx) => SizedBox(
                  height: 30,
                  child: Text('Left $idx'),
                ),
              ),
            ),
          ),
          Expanded(
            child: Scrollbar(
              controller: sc2,
              isAlwaysShown: true,
              thickness: 16.0,
              hoverThickness: 16.0,
              child: ListView.builder(
                controller: sc2,
                itemExtent: 30,
                itemCount: 100,
                itemBuilder: (_, idx) => SizedBox(
                  height: 30,
                  child: Text('Right $idx'),
                ),
              ),
            ),
          ),
        ]),
      ),
    );
  }
}

runApp(TwoScrollBarApp());
```

**Comment by Piinks** [comment]
Hey @PavelPZ, keyboard shortcuts are not dependent on the PrimaryScrollController or PrioritizedIntents, those are just options for different use cases. Fortunately, shortcuts in flutter are also based on focus, so wherever you currently have focus dictates how the keyboard events are handled. This might be helpful: https://stackoverflow.com/questions/61960260/how-to-handle-keyboard-shortcuts

The PrimaryScrollController allows you to specify a default scrollable, so if a scrolling key event is not handled by anyone else, it will use the primary. 
PrioritizedIntents allows you to set up multiple actions for the same key.

I think we can benefit from some samples and more documentation around this. I'll update here to reflect. :)

**Comment by PavelPZ** [comment]
It's still not clear to me. I don't think the problem is "How to handle keyboard shortcuts", it's a technical detail.

The problem is whether Flutter will support standart key shortcuts for widgets that make sense, such as TextField, ScrollView's, etc. 

I'm afraid that based on your answer, it's up to the developer to program PgDn, PgUp etc. for scrollable widgets, Ctrl+A, Ctrl+C for Textfield widget etc. Or am I missing something absolutely fundamental?

**Comment by Piinks** [comment]
No, it is not up to the developer alone. There are already default shortcuts provided based on the platform: https://github.com/flutter/flutter/blob/411cf8f61eca775183d197aa62d7f537c1c341d1/packages/flutter/lib/src/widgets/app.dart#L1082

**Comment by PavelPZ** [comment]
Ok, thanks a lot, I will wait for documentation or simple example.

**Comment by PavelPZ** [comment]
Notice: I am using flutter DEV channel.

After many hours of research the only ListView response to keyboard shortcut that I have achieved is Ctrl + Up and Ctrl + Down. See using ```primary: true``` in following code:

```
ListView.builder(
        primary: true,
        itemExtent: 30,
        itemCount: 100,
        itemBuilder: (_, idx) => SizedBox(height: 30, child: Text('$idx')),
      )
```

Unfortunately, 
- the Scrollbar widget has stopped working (needs the same ScrollController as ListView)
- only single ListView with ```preview: true``` is allowed.

I'm really curious what magic is needed to run keyboard shortcuts for two Listview on one page.

**Comment by 2002Bishwajeet** [comment]
Hey , I would like to work on this documentation issue. Can you provide me some leads ??

**Comment by Piinks** [comment]
Hey @2002Bishwajeet thanks! It looks like there are some examples in the Focus docs, maybe we can update those or modify them to use the built-in shortcuts instead of explicitly creating your own. https://api.flutter.dev/flutter/widgets/Focus-class.html
I think adding some examples to the Shortcuts. docs might be the right place for these. :)

**Comment by 2002Bishwajeet** [comment]
Hey @Piinks  Can you suggest me what type of examples should  I add in the shortcuts docs.? Furthermore I really didn't quite catch what were you trying to explain it to me .  A little more hints would make my day. :)  
Thanks in  Advance .

**Comment by 2002Bishwajeet** [comment]
hey @PavelPZ is this an add on for this issue??

**Comment by PavelPZ** [comment]
Hi @2002Bishwajeet, https://github.com/flutter/flutter/issues/64634 is part of https://github.com/flutter/flutter/projects/183 project. I hope that linking these two similar issues is a better chance of being solved within the mentioned project.

I find it depressing that although the default keyboard shortcuts for ListView are ready, I can't figure out how to use them.

**Comment by PavelPZ** [comment]
I am sorry but after digging into Flutter source code I thing that my example above (two ListViews with two ScrollController's) cannot work.

It seems than ScrollAction traverses primaryFocus **up** in order to find actual _ScrollableScope. So it needs some **FocusNode** inside the ListView. ListView does not seem to be focusable. 

Comparing to TextField, where I can find this:
``` FocusNode get _effectiveFocusNode => widget.focusNode ?? (_focusNode ??= FocusNode());```
and where default shortcuts works.

If I am true, it is not question of documentation.

Relevant code I found in flutter\lib\src\widgets\scrollable.dart:

```
class Scrollable {
  static ScrollableState? of(BuildContext context) {
    final _ScrollableScope? widget = context.dependOnInheritedWidgetOfExactType<_ScrollableScope>();
    return widget?.scrollable;
  }
}

class ScrollAction extends Action<ScrollIntent> {
  @override
  bool isEnabled(ScrollIntent intent) {
    final FocusNode? focus = primaryFocus;
    final bool contextIsValid = focus != null && focus.context != null;
    if (contextIsValid) {
      // Check for primary scrollable within the current context
      if (Scrollable.of(focus.context!) != null)
        return true;
    ...
  }
}
```

**Comment by Piinks** [comment]
Hi @PavelPZ I think your example can work. Since there are two ListViews in your example, it would first depend on where the current primaryFocus is in determining which ListView scrolled with the keyboard shortcut.
If you wanted to specify one ListView to be the default receiver of keyboard shortcuts, you could set one ListView.primary to true. This would make it such that the ListView will use the PrimaryScrollController for the route. That way, when the Shortcut is invoked, it will first consider where the primaryFocus is, if no Scrollable is found based on the primaryFocus, then it will consider the PrimaryScrollController to receive the shortcut.

**Comment by PavelPZ** [comment]
Hi @Piinks,

as a wrote in https://github.com/flutter/flutter/issues/76918#issuecomment-788446208, it does not work.

For ScrollBar to work I need to have an explicitly defined ScrollController (see https://github.com/flutter/flutter/issues/76783).

But then I get an following error:
```
Primary ScrollViews obtain their ScrollController via inheritance from a PrimaryScrollController widget. 
You cannot both set primary to true and pass an explicit controller
```

**Comment by Piinks** [comment]
The Scrollbar can use the PrimaryScrollController. It does not require an explicitly defined ScrollController.
If you set primary to true and wrap the primary ListView in a Scrollbar, they will both use the PrimaryScrollController. You cna set a separate controller for your second ListView, and then I think you'll be all set AFAICT.
