### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The method 'cancel' was called on null.Receiver: nullTried calling: cancel()

### ISSUE THREAD

**Issue by findtravishere** [flutter/flutter#77898]
I've followed the link on the error log to try to find solutions for this but it's still not working. I've ran `flutter upgrade` and i'm on the latest stable release and it's up to date. 
I've tried reinstalling the latest stable release from Flutter's website twice and the issue is still persisting when I do `flutter run` with an iPhone 12 Pro Max simulator running. 
I'm running this on MacOS Big Sur 11.2.2, 2019 16" Macbook Pro. 

## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The method 'cancel' was called on null.
Receiver: null
Tried calling: cancel()
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      AnsiSpinner.finish (package:flutter_tools/src/base/logger.dart:952:11)
#2      Status.stop (package:flutter_tools/src/base/logger.dart:775:5)
#3      AnsiStatus.stop (package:flutter_tools/src/base/logger.dart:1030:11)
#4      DevtoolsServerLauncher._activateDevTools (package:flutter_tools/src/devtools_launcher.dart:167:14)
<asynchronous suspension>
#5      DevtoolsServerLauncher.launch (package:flutter_tools/src/devtools_launcher.dart:71:42)
<asynchronous suspension>
#6      DevtoolsServerLauncher.serve (package:flutter_tools/src/devtools_launcher.dart:176:7)
<asynchronous suspension>
#7      ResidentRunner.serveDevToolsGracefully (package:flutter_tools/src/resident_runner.dart:1284:7)
<asynchronous suspension>
#8      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#9      HotRunner.attach (package:flutter_tools/src/run_hot.dart:178:7)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:639:26)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
```
```
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.2 20D80 darwin-x64, locale en-GB)
    • Flutter version 2.0.1 at /users/findtravishere/flutter
    • Framework revision c5a4b4029c (7 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/findtravishere/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /Users/findtravishere/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 126E9672-D2BF-4D32-9E88-3E7C7E58AFF6 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 89.0.4389.82

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: c5a4b4029c0798f37c4a39b479d7cb75daa7b05c

![image](https://user-images.githubusercontent.com/63047970/110770989-fad58500-8294-11eb-96a2-7347f41a1f60.png)

**Comment by darshankawar** [comment]
Similar issue was fixed recently  https://github.com/flutter/flutter/issues/75677 but seems to have come back.


Another similar : https://github.com/flutter/flutter/issues/65449

**Comment by darshankawar** [comment]
Cc: @jmagman

**Comment by jmagman** [comment]
@darshankawar The fix https://github.com/flutter/flutter/pull/75679 is available on `2.1.0-10.0.pre`, so not `2.0.1`, so it's a duplicate of https://github.com/flutter/flutter/issues/75677.

I'll add a request to hotfix that fix to stable.

**Comment by findtravishere** [comment]
I'm still receiving this error on 2.0.2 from the latest stable release on flutter.dev, do i downgrade my version?
