### ISSUE TITLE
pubspec with faulty git config leads to error 128 and infinite retries

### ISSUE THREAD

**Issue by abjorck** [flutter/flutter#78956]
My CI was up all night banging his head on the wall.
This git error should, IMO, ideally be caught and be deemed more terminal.

(For some reason it Worked On My Machine and I've since fixed the access for the CI too, this issue is really just about the infinite loop)

Log looping as follows:
```
Git error. Command: `git clone --mirror git@github.com:xxxxxxxxxxx.git xxxxxxxxxxxxxx`

stdout: 

stderr: Cloning into bare repository 'xxxxxxxxxxxxxx'...

git@github.com: Permission denied (publickey).

fatal: Could not read from remote repository.



Please make sure you have the correct access rights

and the repository exists.

exit code: 128

pub get failed (server unavailable) -- attempting retry 668 in 64 seconds...

```

**Comment by pedromassangocode** [comment]
Hi @abjorck 
Can you please provide your `flutter doctor -v` and the steps to reproduce this issue?
Does it occur locally or just in the CI?
Thank you

**Comment by abjorck** [comment]
Yes, sorry forgot the doctor/version output. As mentioned it only happened on the CI because of some git access setup.

```
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-SE)
    • Flutter version 2.0.3 at /Users/admin/flutter
    • Framework revision 4d7946a68d (5 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/admin/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/admin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.

```

**Comment by pedromassangocode** [comment]
Hi @abjorck 
if the issue does not occur locally, but only with your CI/CD
I recommend you to ask support directly to the service provider.
Closing, as this isn't an issue with Flutter itself.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by abjorck** [comment]
I do disagree. It's very easy to reproduce. Just a typo could emulate a misconfigured ssh key or something like that what problably happened to me.

Just try this and `pub get` never ends, it just retries. 
I think it sholuld be a terminal error, if at all possible. 

```
dependencies:
  flutter:
    sdk: flutter
  something-broken:
    git: git@git.github.com:somethinginaccessible/notathing.git

```

Just trying to help make the tooling friendlier :)

**Comment by pedromassangocode** [comment]
I was able to reproduce with the steps in https://github.com/flutter/flutter/issues/78956#issuecomment-808000636. Tool should probably limit the number of retries rather than infinite tentatives.

<details>
<summary>logs</summary>

```bash
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +67 ms] Found plugin android_alarm_manager at
/Users/pedromassango/.pub-cache/hosted/pub.dartlang.org/android_alarm_manager-2.0.0/
[  +34 ms] Found plugin path_provider at
/Users/pedromassango/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.1/
[   +3 ms] Found plugin path_provider_linux at
/Users/pedromassango/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[   +3 ms] Found plugin path_provider_macos at
/Users/pedromassango/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.0/
[   +6 ms] Found plugin path_provider_windows at
/Users/pedromassango/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.0/
[  +25 ms] Found plugin webview_flutter at
/Users/pedromassango/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.2/
[ +122 ms] Running "flutter pub get" in flutter_example...
[  +14 ms] Using /Users/pedromassango/Code/flutter_stable/.pub-cache for the pub cache.
[   +2 ms] executing: [/Users/pedromassango/dev/Projects/flutter_example/]
/Users/pedromassango/Code/flutter_stable/bin/cache/dart-sdk/bin/pub --verbose get --no-precompile
[ +125 ms] FINE: Pub 2.12.2
[ +165 ms] MSG : Resolving dependencies...
[  +50 ms] SLVR: fact: flutter_example is 1.0.0+1
[   +7 ms] SLVR: derived: flutter_example
[  +33 ms] SLVR: fact: flutter_example depends on flutter any from sdk
[        ] SLVR: fact: flutter_example depends on webview_flutter any
[        ] SLVR: fact: flutter_example depends on android_alarm_manager any
[        ] SLVR: fact: flutter_example depends on provider any
[        ] SLVR: fact: flutter_example depends on path_provider 2.0.1
[        ] SLVR: fact: flutter_example depends on animations any
[        ] SLVR: fact: flutter_example depends on something_broken from git
[        ] SLVR: fact: flutter_example depends on flutter_test any from sdk
[   +1 ms] SLVR:   selecting flutter_example
[        ] SLVR:   derived: flutter_test any from sdk
[        ] SLVR:   derived: something_broken from git
[        ] SLVR:   derived: animations any
[        ] SLVR:   derived: path_provider 2.0.1
[        ] SLVR:   derived: provider any
[        ] SLVR:   derived: android_alarm_manager any
[        ] SLVR:   derived: webview_flutter any
[        ] SLVR:   derived: flutter any from sdk
[  +58 ms] IO  : Spawning "git --version" in /Users/pedromassango/dev/Projects/flutter_example/.
[  +19 ms] IO  : Finished git. Exit code 0.
[        ]     | stdout:
[        ]     | | git version 2.28.0
[        ]     | Nothing output on stderr.
[        ] FINE: Determined git command git.
[   +1 ms] IO  : Spawning "git rev-parse --is-inside-git-dir" in
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a
[  +39 ms] IO  : Finished git. Exit code 0.
[        ]     | stdout:
[        ]     | | false
[        ]     | Nothing output on stderr.
[   +3 ms] IO  : Deleting directory
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a.
[   +6 ms] IO  : Spawning "git clone --mirror git@git.github.com:somethinginaccessible/notathing.git
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a"
in /Users/pedromassango/dev/Projects/flutter_example/.
[+76080 ms] IO  : Finished git. Exit code 128.
[        ]     | Nothing output on stdout.
[        ]     | stderr:
[        ]     | | Cloning into bare repository
'/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a'
...
[   +1 ms]     | | ssh: connect to host git.github.com port 22: Operation timed out
[        ]     | | fatal: Could not read from remote repository.
[        ]     | | 
[        ]     | | Please make sure you have the correct access rights
[        ]     | | and the repository exists.
[   +2 ms] IO  : Spawning "git rev-parse --is-inside-git-dir" in
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a
[  +14 ms] IO  : Finished git. Exit code 0.
[        ]     | stdout:
[        ]     | | false
[        ]     | Nothing output on stderr.
[        ] IO  : Deleting directory
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a.
[   +5 ms] SLVR: Version solving took 0:01:16.288573 seconds.
[        ]     | Tried 1 solutions.
[        ] FINE: Resolving dependencies finished (1:16.340s).
[   +8 ms] ERR : Git error. Command: `git clone --mirror git@git.github.com:somethinginaccessible/notathing.git
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a`
[        ]     | stdout: 
[        ]     | stderr: Cloning into bare repository
'/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a'
...
[        ]     | ssh: connect to host git.github.com port 22: Operation timed out
[        ]     | fatal: Could not read from remote repository.
[        ]     | 
[        ]     | Please make sure you have the correct access rights
[        ]     | and the repository exists.
[        ]     | exit code: 128
[        ] FINE: Exception type: GitException
[  +37 ms] FINE: package:pub/src/git.dart 60:7                                                         run
[        ]     | ===== asynchronous gap ===========================
[        ]     | dart:async
Future.catchError
[        ]     | package:pub/src/utils.dart 113:52
captureErrors.wrappedCallback
[   +1 ms]     | package:stack_trace
Chain.capture
[        ]     | package:pub/src/utils.dart 126:11
captureErrors
[   +1 ms]     | package:pub/src/command.dart 164:13
PubCommand.run
[        ]     | package:args/command_runner.dart 196:27
CommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 150:26
PubCommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 138:18
PubCommandRunner.run
[   +1 ms]     | /opt/s/w/ir/cache/builder/src/third_party/dart/third_party/pkg/pub/bin/pub.dart 9:48  main
[  +27 ms] pub get failed (server unavailable) -- attempting retry 1 in 1 second...
[+1006 ms] Using /Users/pedromassango/Code/flutter_stable/.pub-cache for the pub cache.
[        ] executing: [/Users/pedromassango/dev/Projects/flutter_example/]
/Users/pedromassango/Code/flutter_stable/bin/cache/dart-sdk/bin/pub --verbose get --no-precompile
[ +100 ms] FINE: Pub 2.12.2
[ +129 ms] MSG : Resolving dependencies...
[  +49 ms] SLVR: fact: flutter_example is 1.0.0+1
[  +10 ms] SLVR: derived: flutter_example
[  +38 ms] SLVR: fact: flutter_example depends on flutter any from sdk
[        ] SLVR: fact: flutter_example depends on webview_flutter any
[        ] SLVR: fact: flutter_example depends on android_alarm_manager any
[        ] SLVR: fact: flutter_example depends on provider any
[        ] SLVR: fact: flutter_example depends on path_provider 2.0.1
[        ] SLVR: fact: flutter_example depends on animations any
[        ] SLVR: fact: flutter_example depends on something_broken from git
[        ] SLVR: fact: flutter_example depends on flutter_test any from sdk
[   +1 ms] SLVR:   selecting flutter_example
[        ] SLVR:   derived: flutter_test any from sdk
[        ] SLVR:   derived: something_broken from git
[        ] SLVR:   derived: animations any
[        ] SLVR:   derived: path_provider 2.0.1
[        ] SLVR:   derived: provider any
[        ] SLVR:   derived: android_alarm_manager any
[        ] SLVR:   derived: webview_flutter any
[        ] SLVR:   derived: flutter any from sdk
[  +48 ms] IO  : Spawning "git --version" in /Users/pedromassango/dev/Projects/flutter_example/.
[  +32 ms] IO  : Finished git. Exit code 0.
[        ]     | stdout:
[        ]     | | git version 2.28.0
[        ]     | Nothing output on stderr.
[        ] FINE: Determined git command git.
[   +2 ms] IO  : Spawning "git clone --mirror git@git.github.com:somethinginaccessible/notathing.git
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a"
in /Users/pedromassango/dev/Projects/flutter_example/.
[+76240 ms] IO  : Finished git. Exit code 128.
[        ]     | Nothing output on stdout.
[        ]     | stderr:
[        ]     | | Cloning into bare repository
'/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a'
...
[   +1 ms]     | | ssh: connect to host git.github.com port 22: Operation timed out
[        ]     | | fatal: Could not read from remote repository.
[        ]     | | 
[        ]     | | Please make sure you have the correct access rights
[        ]     | | and the repository exists.
[   +2 ms] IO  : Spawning "git rev-parse --is-inside-git-dir" in
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a
[  +18 ms] IO  : Finished git. Exit code 0.
[        ]     | stdout:
[        ]     | | false
[        ]     | Nothing output on stderr.
[   +1 ms] IO  : Deleting directory
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a.
[   +3 ms] SLVR: Version solving took 0:01:16.416420 seconds.
[        ]     | Tried 1 solutions.
[   +1 ms] FINE: Resolving dependencies finished (1:16.462s).
[   +7 ms] ERR : Git error. Command: `git clone --mirror git@git.github.com:somethinginaccessible/notathing.git
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a`
[        ]     | stdout: 
[        ]     | stderr: Cloning into bare repository
'/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a'
...
[        ]     | ssh: connect to host git.github.com port 22: Operation timed out
[        ]     | fatal: Could not read from remote repository.
[        ]     | 
[        ]     | Please make sure you have the correct access rights
[        ]     | and the repository exists.
[        ]     | exit code: 128
[        ] FINE: Exception type: GitException
[  +33 ms] FINE: package:pub/src/git.dart 60:7                                                         run
[        ]     | ===== asynchronous gap ===========================
[        ]     | dart:async
Future.catchError
[        ]     | package:pub/src/utils.dart 113:52
captureErrors.wrappedCallback
[        ]     | package:stack_trace
Chain.capture
[        ]     | package:pub/src/utils.dart 126:11
captureErrors
[        ]     | package:pub/src/command.dart 164:13
PubCommand.run
[        ]     | package:args/command_runner.dart 196:27
CommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 150:26
PubCommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 138:18
PubCommandRunner.run
[   +3 ms]     | /opt/s/w/ir/cache/builder/src/third_party/dart/third_party/pkg/pub/bin/pub.dart 9:48  main
[   +8 ms] pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...
[+2006 ms] Using /Users/pedromassango/Code/flutter_stable/.pub-cache for the pub cache.
[        ] executing: [/Users/pedromassango/dev/Projects/flutter_example/]
/Users/pedromassango/Code/flutter_stable/bin/cache/dart-sdk/bin/pub --verbose get --no-precompile
[ +100 ms] FINE: Pub 2.12.2
[ +114 ms] MSG : Resolving dependencies...
[  +48 ms] SLVR: fact: flutter_example is 1.0.0+1
[  +10 ms] SLVR: derived: flutter_example
[  +41 ms] SLVR: fact: flutter_example depends on flutter any from sdk
[   +1 ms] SLVR: fact: flutter_example depends on webview_flutter any
[        ] SLVR: fact: flutter_example depends on android_alarm_manager any
[        ] SLVR: fact: flutter_example depends on provider any
[        ] SLVR: fact: flutter_example depends on path_provider 2.0.1
[        ] SLVR: fact: flutter_example depends on animations any
[        ] SLVR: fact: flutter_example depends on something_broken from git
[        ] SLVR: fact: flutter_example depends on flutter_test any from sdk
[   +2 ms] SLVR:   selecting flutter_example
[   +2 ms] SLVR:   derived: flutter_test any from sdk
[        ] SLVR:   derived: something_broken from git
[        ] SLVR:   derived: animations any
[        ] SLVR:   derived: path_provider 2.0.1
[   +5 ms] SLVR:   derived: provider any
[        ] SLVR:   derived: android_alarm_manager any
[        ] SLVR:   derived: webview_flutter any
[        ] SLVR:   derived: flutter any from sdk
[  +45 ms] IO  : Spawning "git --version" in /Users/pedromassango/dev/Projects/flutter_example/.
[  +27 ms] IO  : Finished git. Exit code 0.
[        ]     | stdout:
[        ]     | | git version 2.28.0
[        ]     | Nothing output on stderr.
[        ] FINE: Determined git command git.
[   +2 ms] IO  : Spawning "git clone --mirror git@git.github.com:somethinginaccessible/notathing.git
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a"
in /Users/pedromassango/dev/Projects/flutter_example/.
[+76124 ms] IO  : Finished git. Exit code 128.
[        ]     | Nothing output on stdout.
[        ]     | stderr:
[        ]     | | Cloning into bare repository
'/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a'
...
[        ]     | | ssh: connect to host git.github.com port 22: Operation timed out
[        ]     | | fatal: Could not read from remote repository.
[        ]     | | 
[        ]     | | Please make sure you have the correct access rights
[        ]     | | and the repository exists.
[   +4 ms] IO  : Spawning "git rev-parse --is-inside-git-dir" in
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a
[  +20 ms] IO  : Finished git. Exit code 0.
[        ]     | stdout:
[        ]     | | false
[        ]     | Nothing output on stderr.
[        ] IO  : Deleting directory
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a.
[   +3 ms] SLVR: Version solving took 0:01:16.306367 seconds.
[        ]     | Tried 1 solutions.
[   +1 ms] FINE: Resolving dependencies finished (1:16.351s).
[   +6 ms] ERR : Git error. Command: `git clone --mirror git@git.github.com:somethinginaccessible/notathing.git
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a`
[   +2 ms]     | stdout: 
[        ]     | stderr: Cloning into bare repository
'/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a'
...
[        ]     | ssh: connect to host git.github.com port 22: Operation timed out
[        ]     | fatal: Could not read from remote repository.
[        ]     | 
[        ]     | Please make sure you have the correct access rights
[        ]     | and the repository exists.
[        ]     | exit code: 128
[        ] FINE: Exception type: GitException
[  +28 ms] FINE: package:pub/src/git.dart 60:7                                                         run
[        ]     | ===== asynchronous gap ===========================
[        ]     | dart:async
Future.catchError
[        ]     | package:pub/src/utils.dart 113:52
captureErrors.wrappedCallback
[        ]     | package:stack_trace
Chain.capture
[        ]     | package:pub/src/utils.dart 126:11
captureErrors
[        ]     | package:pub/src/command.dart 164:13
PubCommand.run
[        ]     | package:args/command_runner.dart 196:27
CommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 150:26
PubCommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 138:18
PubCommandRunner.run
[  +17 ms]     | /opt/s/w/ir/cache/builder/src/third_party/dart/third_party/pkg/pub/bin/pub.dart 9:48  main
[   +1 ms] pub get failed (server unavailable) -- attempting retry 3 in 4 seconds...
[+4006 ms] Using /Users/pedromassango/Code/flutter_stable/.pub-cache for the pub cache.
[        ] executing: [/Users/pedromassango/dev/Projects/flutter_example/]
/Users/pedromassango/Code/flutter_stable/bin/cache/dart-sdk/bin/pub --verbose get --no-precompile
[  +91 ms] FINE: Pub 2.12.2
[ +110 ms] MSG : Resolving dependencies...
[  +44 ms] SLVR: fact: flutter_example is 1.0.0+1
[   +9 ms] SLVR: derived: flutter_example
[  +31 ms] SLVR: fact: flutter_example depends on flutter any from sdk
[        ] SLVR: fact: flutter_example depends on webview_flutter any
[        ] SLVR: fact: flutter_example depends on android_alarm_manager any
[        ] SLVR: fact: flutter_example depends on provider any
[        ] SLVR: fact: flutter_example depends on path_provider 2.0.1
[        ] SLVR: fact: flutter_example depends on animations any
[        ] SLVR: fact: flutter_example depends on something_broken from git
[        ] SLVR: fact: flutter_example depends on flutter_test any from sdk
[   +1 ms] SLVR:   selecting flutter_example
[        ] SLVR:   derived: flutter_test any from sdk
[        ] SLVR:   derived: something_broken from git
[        ] SLVR:   derived: animations any
[        ] SLVR:   derived: path_provider 2.0.1
[        ] SLVR:   derived: provider any
[        ] SLVR:   derived: android_alarm_manager any
[        ] SLVR:   derived: webview_flutter any
[        ] SLVR:   derived: flutter any from sdk
[  +39 ms] IO  : Spawning "git --version" in /Users/pedromassango/dev/Projects/flutter_example/.
[  +32 ms] IO  : Finished git. Exit code 0.
[        ]     | stdout:
[        ]     | | git version 2.28.0
[        ]     | Nothing output on stderr.
[        ] FINE: Determined git command git.
[   +1 ms] IO  : Spawning "git clone --mirror git@git.github.com:somethinginaccessible/notathing.git
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a"
in /Users/pedromassango/dev/Projects/flutter_example/.
[+76049 ms] IO  : Finished git. Exit code 128.
[        ]     | Nothing output on stdout.
[        ]     | stderr:
[        ]     | | Cloning into bare repository
'/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a'
...
[        ]     | | ssh: connect to host git.github.com port 22: Operation timed out
[        ]     | | fatal: Could not read from remote repository.
[        ]     | | 
[        ]     | | Please make sure you have the correct access rights
[        ]     | | and the repository exists.
[   +4 ms] IO  : Spawning "git rev-parse --is-inside-git-dir" in
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a
[  +17 ms] IO  : Finished git. Exit code 0.
[        ]     | stdout:
[        ]     | | false
[        ]     | Nothing output on stderr.
[        ] IO  : Deleting directory
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a.
[   +3 ms] SLVR: Version solving took 0:01:16.206081 seconds.
[        ]     | Tried 1 solutions.
[   +1 ms] FINE: Resolving dependencies finished (1:16.248s).
[   +6 ms] ERR : Git error. Command: `git clone --mirror git@git.github.com:somethinginaccessible/notathing.git
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a`
[        ]     | stdout: 
[        ]     | stderr: Cloning into bare repository
'/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a'
...
[        ]     | ssh: connect to host git.github.com port 22: Operation timed out
[        ]     | fatal: Could not read from remote repository.
[        ]     | 
[        ]     | Please make sure you have the correct access rights
[        ]     | and the repository exists.
[        ]     | exit code: 128
[        ] FINE: Exception type: GitException
[  +27 ms] FINE: package:pub/src/git.dart 60:7                                                         run
[        ]     | ===== asynchronous gap ===========================
[        ]     | dart:async
Future.catchError
[        ]     | package:pub/src/utils.dart 113:52
captureErrors.wrappedCallback
[        ]     | package:stack_trace
Chain.capture
[        ]     | package:pub/src/utils.dart 126:11
captureErrors
[        ]     | package:pub/src/command.dart 164:13
PubCommand.run
[        ]     | package:args/command_runner.dart 196:27
CommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 150:26
PubCommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 138:18
PubCommandRunner.run
[   +1 ms]     | /opt/s/w/ir/cache/builder/src/third_party/dart/third_party/pkg/pub/bin/pub.dart 9:48  main
[  +14 ms] pub get failed (server unavailable) -- attempting retry 4 in 8 seconds...
[+8007 ms] Using /Users/pedromassango/Code/flutter_stable/.pub-cache for the pub cache.
[        ] executing: [/Users/pedromassango/dev/Projects/flutter_example/]
/Users/pedromassango/Code/flutter_stable/bin/cache/dart-sdk/bin/pub --verbose get --no-precompile
[ +105 ms] FINE: Pub 2.12.2
[ +136 ms] MSG : Resolving dependencies...
[  +56 ms] SLVR: fact: flutter_example is 1.0.0+1
[  +13 ms] SLVR: derived: flutter_example
[  +41 ms] SLVR: fact: flutter_example depends on flutter any from sdk
[        ] SLVR: fact: flutter_example depends on webview_flutter any
[        ] SLVR: fact: flutter_example depends on android_alarm_manager any
[        ] SLVR: fact: flutter_example depends on provider any
[        ] SLVR: fact: flutter_example depends on path_provider 2.0.1
[        ] SLVR: fact: flutter_example depends on animations any
[        ] SLVR: fact: flutter_example depends on something_broken from git
[        ] SLVR: fact: flutter_example depends on flutter_test any from sdk
[   +2 ms] SLVR:   selecting flutter_example
[        ] SLVR:   derived: flutter_test any from sdk
[        ] SLVR:   derived: something_broken from git
[        ] SLVR:   derived: animations any
[        ] SLVR:   derived: path_provider 2.0.1
[  +18 ms] SLVR:   derived: provider any
[        ] SLVR:   derived: android_alarm_manager any
[        ] SLVR:   derived: webview_flutter any
[        ] SLVR:   derived: flutter any from sdk
[  +30 ms] IO  : Spawning "git --version" in /Users/pedromassango/dev/Projects/flutter_example/.
[  +30 ms] IO  : Finished git. Exit code 0.
[        ]     | stdout:
[        ]     | | git version 2.28.0
[        ]     | Nothing output on stderr.
[        ] FINE: Determined git command git.
[   +1 ms] IO  : Spawning "git clone --mirror git@git.github.com:somethinginaccessible/notathing.git
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a"
in /Users/pedromassango/dev/Projects/flutter_example/.
[+77668 ms] IO  : Finished git. Exit code 128.
[        ]     | Nothing output on stdout.
[        ]     | stderr:
[        ]     | | Cloning into bare repository
'/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a'
...
[        ]     | | ssh: connect to host git.github.com port 22: Operation timed out
[        ]     | | fatal: Could not read from remote repository.
[        ]     | | 
[        ]     | | Please make sure you have the correct access rights
[        ]     | | and the repository exists.
[   +5 ms] IO  : Spawning "git rev-parse --is-inside-git-dir" in
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a
[  +14 ms] IO  : Finished git. Exit code 0.
[        ]     | stdout:
[        ]     | | false
[        ]     | Nothing output on stderr.
[        ] IO  : Deleting directory
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a.
[   +3 ms] SLVR: Version solving took 0:01:17.846613 seconds.
[        ]     | Tried 1 solutions.
[   +1 ms] FINE: Resolving dependencies finished (1:17.902s).
[   +8 ms] ERR : Git error. Command: `git clone --mirror git@git.github.com:somethinginaccessible/notathing.git
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a`
[        ]     | stdout: 
[        ]     | stderr: Cloning into bare repository
'/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a'
...
[        ]     | ssh: connect to host git.github.com port 22: Operation timed out
[        ]     | fatal: Could not read from remote repository.
[        ]     | 
[        ]     | Please make sure you have the correct access rights
[        ]     | and the repository exists.
[        ]     | exit code: 128
[        ] FINE: Exception type: GitException
[  +29 ms] FINE: package:pub/src/git.dart 60:7                                                         run
[   +1 ms]     | ===== asynchronous gap ===========================
[        ]     | dart:async
Future.catchError
[        ]     | package:pub/src/utils.dart 113:52
captureErrors.wrappedCallback
[        ]     | package:stack_trace
Chain.capture
[        ]     | package:pub/src/utils.dart 126:11
captureErrors
[        ]     | package:pub/src/command.dart 164:13
PubCommand.run
[        ]     | package:args/command_runner.dart 196:27
CommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 150:26
PubCommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 138:18
PubCommandRunner.run
[        ]     | /opt/s/w/ir/cache/builder/src/third_party/dart/third_party/pkg/pub/bin/pub.dart 9:48  main
[  +11 ms] pub get failed (server unavailable) -- attempting retry 5 in 16 seconds...
[+16007 ms] Using /Users/pedromassango/Code/flutter_stable/.pub-cache for the pub cache.
[        ] executing: [/Users/pedromassango/dev/Projects/flutter_example/]
/Users/pedromassango/Code/flutter_stable/bin/cache/dart-sdk/bin/pub --verbose get --no-precompile
[  +90 ms] FINE: Pub 2.12.2
[ +120 ms] MSG : Resolving dependencies...
[  +46 ms] SLVR: fact: flutter_example is 1.0.0+1
[   +8 ms] SLVR: derived: flutter_example
[  +35 ms] SLVR: fact: flutter_example depends on flutter any from sdk
[        ] SLVR: fact: flutter_example depends on webview_flutter any
[        ] SLVR: fact: flutter_example depends on android_alarm_manager any
[        ] SLVR: fact: flutter_example depends on provider any
[        ] SLVR: fact: flutter_example depends on path_provider 2.0.1
[        ] SLVR: fact: flutter_example depends on animations any
[        ] SLVR: fact: flutter_example depends on something_broken from git
[        ] SLVR: fact: flutter_example depends on flutter_test any from sdk
[   +1 ms] SLVR:   selecting flutter_example
[        ] SLVR:   derived: flutter_test any from sdk
[        ] SLVR:   derived: something_broken from git
[        ] SLVR:   derived: animations any
[        ] SLVR:   derived: path_provider 2.0.1
[  +24 ms] SLVR:   derived: provider any
[        ] SLVR:   derived: android_alarm_manager any
[        ] SLVR:   derived: webview_flutter any
[        ] SLVR:   derived: flutter any from sdk
[  +24 ms] IO  : Spawning "git --version" in /Users/pedromassango/dev/Projects/flutter_example/.
[  +34 ms] IO  : Finished git. Exit code 0.
[        ]     | stdout:
[        ]     | | git version 2.28.0
[        ]     | Nothing output on stderr.
[        ] FINE: Determined git command git.
[   +2 ms] IO  : Spawning "git clone --mirror git@git.github.com:somethinginaccessible/notathing.git
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a"
in /Users/pedromassango/dev/Projects/flutter_example/.
[+76501 ms] IO  : Finished git. Exit code 128.
[        ]     | Nothing output on stdout.
[        ]     | stderr:
[        ]     | | Cloning into bare repository
'/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a'
...
[        ]     | | ssh: connect to host git.github.com port 22: Operation timed out
[        ]     | | fatal: Could not read from remote repository.
[        ]     | | 
[   +1 ms]     | | Please make sure you have the correct access rights
[        ]     | | and the repository exists.
[   +4 ms] IO  : Spawning "git rev-parse --is-inside-git-dir" in
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a
[  +24 ms] IO  : Finished git. Exit code 0.
[        ]     | stdout:
[        ]     | | false
[        ]     | Nothing output on stderr.
[        ] IO  : Deleting directory
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a.
[   +8 ms] SLVR: Version solving took 0:01:16.683025 seconds.
[        ]     | Tried 1 solutions.
[   +2 ms] FINE: Resolving dependencies finished (1:16.729s).
[   +9 ms] ERR : Git error. Command: `git clone --mirror git@git.github.com:somethinginaccessible/notathing.git
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a`
[        ]     | stdout: 
[        ]     | stderr: Cloning into bare repository
'/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a'
...
[        ]     | ssh: connect to host git.github.com port 22: Operation timed out
[        ]     | fatal: Could not read from remote repository.
[        ]     | 
[        ]     | Please make sure you have the correct access rights
[        ]     | and the repository exists.
[        ]     | exit code: 128
[        ] FINE: Exception type: GitException
[  +50 ms] FINE: package:pub/src/git.dart 60:7                                                         run
[        ]     | ===== asynchronous gap ===========================
[        ]     | dart:async
Future.catchError
[        ]     | package:pub/src/utils.dart 113:52
captureErrors.wrappedCallback
[        ]     | package:stack_trace
Chain.capture
[        ]     | package:pub/src/utils.dart 126:11
captureErrors
[        ]     | package:pub/src/command.dart 164:13
PubCommand.run
[        ]     | package:args/command_runner.dart 196:27
CommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 150:26
PubCommandRunner.runCommand
[   +1 ms]     | package:pub/src/command_runner.dart 138:18
PubCommandRunner.run
[  +19 ms]     | /opt/s/w/ir/cache/builder/src/third_party/dart/third_party/pkg/pub/bin/pub.dart 9:48  main
[   +1 ms] pub get failed (server unavailable) -- attempting retry 6 in 32 seconds...
[+32015 ms] Using /Users/pedromassango/Code/flutter_stable/.pub-cache for the pub cache.
[   +2 ms] executing: [/Users/pedromassango/dev/Projects/flutter_example/]
/Users/pedromassango/Code/flutter_stable/bin/cache/dart-sdk/bin/pub --verbose get --no-precompile
[ +103 ms] FINE: Pub 2.12.2
[ +119 ms] MSG : Resolving dependencies...
[  +61 ms] SLVR: fact: flutter_example is 1.0.0+1
[  +23 ms] SLVR: derived: flutter_example
[  +41 ms] SLVR: fact: flutter_example depends on flutter any from sdk
[        ] SLVR: fact: flutter_example depends on webview_flutter any
[        ] SLVR: fact: flutter_example depends on android_alarm_manager any
[        ] SLVR: fact: flutter_example depends on provider any
[        ] SLVR: fact: flutter_example depends on path_provider 2.0.1
[        ] SLVR: fact: flutter_example depends on animations any
[        ] SLVR: fact: flutter_example depends on something_broken from git
[        ] SLVR: fact: flutter_example depends on flutter_test any from sdk
[   +1 ms] SLVR:   selecting flutter_example
[        ] SLVR:   derived: flutter_test any from sdk
[        ] SLVR:   derived: something_broken from git
[        ] SLVR:   derived: animations any
[        ] SLVR:   derived: path_provider 2.0.1
[        ] SLVR:   derived: provider any
[        ] SLVR:   derived: android_alarm_manager any
[        ] SLVR:   derived: webview_flutter any
[        ] SLVR:   derived: flutter any from sdk
[  +51 ms] IO  : Spawning "git --version" in /Users/pedromassango/dev/Projects/flutter_example/.
[  +31 ms] IO  : Finished git. Exit code 0.
[        ]     | stdout:
[        ]     | | git version 2.28.0
[        ]     | Nothing output on stderr.
[        ] FINE: Determined git command git.
[   +3 ms] IO  : Spawning "git clone --mirror git@git.github.com:somethinginaccessible/notathing.git
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a"
in /Users/pedromassango/dev/Projects/flutter_example/.
[+76847 ms] IO  : Finished git. Exit code 128.
[        ]     | Nothing output on stdout.
[        ]     | stderr:
[        ]     | | Cloning into bare repository
'/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a'
...
[        ]     | | ssh: connect to host git.github.com port 22: Operation timed out
[        ]     | | fatal: Could not read from remote repository.
[        ]     | | 
[        ]     | | Please make sure you have the correct access rights
[        ]     | | and the repository exists.
[   +6 ms] IO  : Spawning "git rev-parse --is-inside-git-dir" in
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a
[  +55 ms] IO  : Finished git. Exit code 0.
[  +86 ms]     | stdout:
[        ]     | | false
[        ]     | Nothing output on stderr.
[        ] IO  : Deleting directory
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a.
[        ] SLVR: Version solving took 0:01:17.093437 seconds.
[        ]     | Tried 1 solutions.
[        ] FINE: Resolving dependencies finished (1:17.151s).
[        ] ERR : Git error. Command: `git clone --mirror git@git.github.com:somethinginaccessible/notathing.git
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a`
[        ]     | stdout: 
[        ]     | stderr: Cloning into bare repository
'/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a'
...
[  +93 ms]     | ssh: connect to host git.github.com port 22: Operation timed out
[        ]     | fatal: Could not read from remote repository.
[        ]     | 
[        ]     | Please make sure you have the correct access rights
[        ]     | and the repository exists.
[        ]     | exit code: 128
[        ] FINE: Exception type: GitException
[        ] FINE: package:pub/src/git.dart 60:7                                                         run
[        ]     | ===== asynchronous gap ===========================
[        ]     | dart:async
Future.catchError
[        ]     | package:pub/src/utils.dart 113:52
captureErrors.wrappedCallback
[        ]     | package:stack_trace
Chain.capture
[        ]     | package:pub/src/utils.dart 126:11
captureErrors
[        ]     | package:pub/src/command.dart 164:13
PubCommand.run
[        ]     | package:args/command_runner.dart 196:27
CommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 150:26
PubCommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 138:18
PubCommandRunner.run
[        ]     | /opt/s/w/ir/cache/builder/src/third_party/dart/third_party/pkg/pub/bin/pub.dart 9:48  main
[   +2 ms] pub get failed (server unavailable) -- attempting retry 7 in 64 seconds...
[+64007 ms] Using /Users/pedromassango/Code/flutter_stable/.pub-cache for the pub cache.
[        ] executing: [/Users/pedromassango/dev/Projects/flutter_example/]
/Users/pedromassango/Code/flutter_stable/bin/cache/dart-sdk/bin/pub --verbose get --no-precompile
[  +94 ms] FINE: Pub 2.12.2
[ +105 ms] MSG : Resolving dependencies...
[  +41 ms] SLVR: fact: flutter_example is 1.0.0+1
[   +7 ms] SLVR: derived: flutter_example
[  +31 ms] SLVR: fact: flutter_example depends on flutter any from sdk
[        ] SLVR: fact: flutter_example depends on webview_flutter any
[        ] SLVR: fact: flutter_example depends on android_alarm_manager any
[        ] SLVR: fact: flutter_example depends on provider any
[        ] SLVR: fact: flutter_example depends on path_provider 2.0.1
[        ] SLVR: fact: flutter_example depends on animations any
[        ] SLVR: fact: flutter_example depends on something_broken from git
[        ] SLVR: fact: flutter_example depends on flutter_test any from sdk
[   +1 ms] SLVR:   selecting flutter_example
[        ] SLVR:   derived: flutter_test any from sdk
[        ] SLVR:   derived: something_broken from git
[        ] SLVR:   derived: animations any
[        ] SLVR:   derived: path_provider 2.0.1
[        ] SLVR:   derived: provider any
[        ] SLVR:   derived: android_alarm_manager any
[        ] SLVR:   derived: webview_flutter any
[        ] SLVR:   derived: flutter any from sdk
[  +46 ms] IO  : Spawning "git --version" in /Users/pedromassango/dev/Projects/flutter_example/.
[  +27 ms] IO  : Finished git. Exit code 0.
[        ]     | stdout:
[        ]     | | git version 2.28.0
[        ]     | Nothing output on stderr.
[        ] FINE: Determined git command git.
[   +1 ms] IO  : Spawning "git clone --mirror git@git.github.com:somethinginaccessible/notathing.git
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a"
in /Users/pedromassango/dev/Projects/flutter_example/.
[+76326 ms] IO  : Finished git. Exit code 128.
[   +1 ms]     | Nothing output on stdout.
[        ]     | stderr:
[        ]     | | Cloning into bare repository
'/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a'
...
[   +1 ms]     | | ssh: connect to host git.github.com port 22: Operation timed out
[        ]     | | fatal: Could not read from remote repository.
[        ]     | | 
[        ]     | | Please make sure you have the correct access rights
[        ]     | | and the repository exists.
[        ] IO  : Spawning "git rev-parse --is-inside-git-dir" in
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a
[  +12 ms] IO  : Finished git. Exit code 0.
[        ]     | stdout:
[        ]     | | false
[        ]     | Nothing output on stderr.
[   +1 ms] IO  : Deleting directory
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a.
[   +4 ms] SLVR: Version solving took 0:01:16.476799 seconds.
[        ]     | Tried 1 solutions.
[   +1 ms] FINE: Resolving dependencies finished (1:16.517s).
[  +10 ms] ERR : Git error. Command: `git clone --mirror git@git.github.com:somethinginaccessible/notathing.git
/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a`
[   +1 ms]     | stdout: 
[        ]     | stderr: Cloning into bare repository
'/Users/pedromassango/Code/flutter_stable/.pub-cache/git/cache/notathing-7d729cae55054538c678918e4930e9757c94c38a'
...
[        ]     | ssh: connect to host git.github.com port 22: Operation timed out
[        ]     | fatal: Could not read from remote repository.
[        ]     | 
[        ]     | Please make sure you have the correct access rights
[        ]     | and the repository exists.
[        ]     | exit code: 128
[        ] FINE: Exception type: GitException
[  +35 ms] FINE: package:pub/src/git.dart 60:7                                                         run
[        ]     | ===== asynchronous gap ===========================
[        ]     | dart:async
Future.catchError
[        ]     | package:pub/src/utils.dart 113:52
captureErrors.wrappedCallback
[        ]     | package:stack_trace
Chain.capture
[        ]     | package:pub/src/utils.dart 126:11
captureErrors
[        ]     | package:pub/src/command.dart 164:13
PubCommand.run
[        ]     | package:args/command_runner.dart 196:27
CommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 150:26
PubCommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 138:18
PubCommandRunner.run
[        ]     | /opt/s/w/ir/cache/builder/src/third_party/dart/third_party/pkg/pub/bin/pub.dart 9:48  main
[  +17 ms] pub get failed (server unavailable) -- attempting retry 8 in 64 seconds...
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale en-AO)
    • Flutter version 2.0.3 at /Users/pedromassango/Code/flutter_stable
    • Framework revision 4d7946a68d (7 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/pedromassango/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • AE2F4F51-880E-44FB-BB29-171B766D9B54 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.
```

</details>

**Comment by jonahwilliams** [comment]
FYI @jonasfj

**Comment by jonasfj** [comment]
The `flutter_tool` retries `pub` invocations depending on exit-code (but there is no limit the number of retries).

Internally, `pub` also retries HTTP requests, with exponential backoff.

We could change `pub`'s exit code when failing to fetch a git repository. But I think the better answer is to not make `flutter_tool` retry `pub` invocations. If there are common errors which are not retried in the `pub` client, we should fix that in the `pub` client -- I know we have made some improvements since `flutter_tool` introduced indefinite retries.

Though, I don't think we're inclined to make `pub` retry request indefinitely.

**Comment by exaby73** [comment]
This issue still persists in the latest stable and master channels.

<details><summary>Logs</summary>

```
Please make sure you have the correct access rights
and the repository exists.
exit code: 128
pub get failed (server unavailable) -- attempting retry 6 in 32 seconds...
Git error. Command: `git clone --mirror git@github.com:flutter/flutterr.git /Users/nabeelparkar/.pub-cache/git/cache/flutterr-f6254990ecca96ebf39097b00cc4bf75568a68c9`
stdout:
stderr: Cloning into bare repository '/Users/nabeelparkar/.pub-cache/git/cache/flutterr-f6254990ecca96ebf39097b00cc4bf75568a68c9'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
exit code: 128
pub get failed (server unavailable) -- attempting retry 7 in 64 seconds...
```

</details>

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm, locale en-US)
    • Flutter version 3.0.0 at /Users/nabeelparkar/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (7 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 67.1.4
    • Dart plugin version 221.5591.52

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Brave Browser 101.1.38.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.745, on macOS 12.3.1 21E258 darwin-arm, locale en-US)
    • Flutter version 3.1.0-0.0.pre.745 at /Users/nabeelparkar/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c248854d17 (5 hours ago), 2022-05-16 23:57:08 -0400
    • Engine revision fce741dd83
    • Dart version 2.18.0 (build 2.18.0-120.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 67.1.4
    • Dart plugin version 221.5591.52

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • V2050 (mobile)  • 3085425058000NM • android-arm64  • Android 12 (API 31)
    • macOS (desktop) • macos           • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome          • web-javascript • Brave Browser 101.1.38.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by bkonyi** [comment]
Closing as fixed: the infinite retry loop in `_runWithRetries` was removed in flutter/flutter#115801. `flutter pub get` now forwards stdio and immediately exits with a `ToolExit` on non-zero pub exit codes (including exit code 69 from git clone failures) without retrying.
