### ISSUE TITLE
VideoPlayerController.seekTo() not changing video frame on iOS platform

### ISSUE THREAD

**Issue by oleggreen** [flutter/flutter#78998]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: 
main.dart
```
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: VideoPlayerScreen(),
    );
  }
}

class VideoPlayerScreen extends StatefulWidget {
  VideoPlayerScreen({Key key}) : super(key: key);

  @override
  _VideoPlayerScreenState createState() => _VideoPlayerScreenState();
}

class _VideoPlayerScreenState extends State<VideoPlayerScreen> {
  VideoPlayerController _controller;
  Future<void> _initializeVideoPlayerFuture;

  @override
  void initState() {
    // Create and store the VideoPlayerController. The VideoPlayerController
    // offers several different constructors to play videos from assets, files,
    // or the internet.
    _controller = VideoPlayerController.network(
      'https://flutter.github.io/assets-for-api-docs/assets/videos/butterfly.mp4',
    );

    // Initialize the controller and store the Future for later use.
    _initializeVideoPlayerFuture = _controller.initialize();

    // Use the controller to loop the video.
    _controller.setLooping(true);

    _controller.addListener(() {

    });

    super.initState();
  }

  @override
  void dispose() {
    // Ensure disposing of the VideoPlayerController to free up resources.
    _controller.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Butterfly Video'),
      ),
      // Use a FutureBuilder to display a loading spinner while waiting for the
      // VideoPlayerController to finish initializing.
      body: FutureBuilder(
        future: _initializeVideoPlayerFuture,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.done) {
            // If the VideoPlayerController has finished initialization, use
            // the data it provides to limit the aspect ratio of the video.
            return AspectRatio(
              aspectRatio: _controller.value.aspectRatio,
              // Use the VideoPlayer widget to display the video.
              child: VideoPlayer(_controller),
            );
          } else {
            // If the VideoPlayerController is still initializing, show a
            // loading spinner.
            return Center(child: CircularProgressIndicator());
          }
        },
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          final _videoDurationMillis = _controller.value.duration.inMilliseconds;
          final _step = _videoDurationMillis ~/ 10;
          final int _positionWithStep = _controller.value.position.inMilliseconds + _step;
          final int _newPosition = _positionWithStep > _videoDurationMillis ? 0 : _positionWithStep;
          // Wrap the play or pause in a call to `setState`. This ensures the
          // correct icon is shown.
          setState(() {
            _controller.seekTo(Duration(milliseconds: _newPosition));
            // // If the video is playing, pause it.
            // if (_controller.value.isPlaying) {
            //   _controller.pause();
            // } else {
            //   // If the video is paused, play it.
            //   _controller.play();
            // }
          });
        },
        // Display the correct icon depending on the state of the player.
        child: Icon(
          Icons.fast_forward_sharp
          // _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

pubspec.yaml
```
name: flutter_video_player_ios
description: Flutter app to test ios video issues with seekTo

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  video_player: ^2.0.2
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```

3. 
3.1 Run the app
3.2 Wait till the video will be loaded
3.3 Tap on action button to rewind the video
Under the hood I'm calling ```VideoPlayerController.seekTo()```

**Expected results:** 
Frame changes when rewinding

**Actual results:** 
Always remains 1st frame on the video player.

<details>
  <summary>Logs</summary>

```
```
```
Analyzing bug...
No issues found! (ran in 1.4s)
```

```
[✓] Flutter (Channel unknown, 2.0.3, on macOS 11.1 20C69 darwin-x64, locale en-UA)
    • Flutter version 2.0.3 at /Users/username/fvm/versions/2.0.3
    • Framework revision 4d7946a68d (6 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/username/Develop/android-sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone (mobile) • xxx • ios            • iOS 12.5.1
    • macOS (desktop)         • macos                                    • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)            • chrome                                   • web-javascript • Google Chrome 89.0.4389.90

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
<img width="346" alt="Screenshot 2021-03-25 at 3 36 23 PM" src="https://user-images.githubusercontent.com/67046386/112455843-1ace7380-8d80-11eb-8509-18e6dd3dd32c.png">


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.3 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 4d7946a68d (6 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.

```

</details>

**Comment by darshankawar** [comment]
Also noticed that the frame changes only when you put the app in background and bring it to front.

**Comment by TahaTesser** [comment]
### Steps to reproduce
1. Copy the code sample below
2. Run it on iOS  

Drag the seek slider when the video is playing, frames are updated (works)
Pause the video, drag seek slider, frames are not updated (issue on iOS, works on Android)


### Preview

![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/114828192-474f3b80-9dd2-11eb-9437-36dd1c1e8ff6.gif)



<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() => runApp(VideoApp());

class VideoApp extends StatefulWidget {
  @override
  _VideoAppState createState() => _VideoAppState();
}

class _VideoAppState extends State<VideoApp> {
  VideoPlayerController? _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
        'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4')
      ..initialize().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
      });

    _controller?.addListener(() {
      double pos = (_controller?.value.position.inSeconds.toDouble() ?? 0);
      setState(() {
        _sliderValue = pos;
      });

      if (pos >= (_controller?.value.duration.inSeconds ?? 0)) {
        setState(() {
          _controller?.pause();
          _controller?.seekTo(Duration.zero);
        });
      }
    });
  }

  double _sliderValue = 0;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: Column(
          children: [
            AspectRatio(
              aspectRatio: (_controller?.value.aspectRatio ?? 1.0),
              child: VideoPlayer(_controller!),
            ),
            Slider(
                min: 0,
                max: 15,
                value: _sliderValue,
                onChangeEnd: (value) {
                  _controller?.seekTo(Duration(seconds: _sliderValue.toInt()));
                },
                onChanged: (val) {
                  setState(() {
                    _sliderValue = val;
                  });
                }),
            Text('Position: ${_sliderValue.toInt()}'),
          ],
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              _controller?.value.isPlaying == true
                  ? _controller?.pause()
                  : _controller?.play();
            });
          },
          child: Icon(
            _controller?.value.isPlaying == true
                ? Icons.pause
                : Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller?.dispose();
  }
}

``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.0.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision b1395592de (13 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 14.4.2
    • iPhone 12 (mobile)     • 83060656-28E7-44CD-801E-B11EC3EC89BA • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4
      (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 89.0.4389.128

• No issues found!

```


```bash
[✓] Flutter (Channel master, 2.2.0-11.0.pre.126, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.2.0-11.0.pre.126 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 600e489313 (2 hours ago), 2021-04-15 01:04:03 -0400
    • Engine revision dcdc42b715
    • Dart version 2.14.0 (build 2.14.0-4.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 14.4.2
    • iPhone 12 (mobile)     • 83060656-28E7-44CD-801E-B11EC3EC89BA • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4
      (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 89.0.4389.128

• No issues found!
```
	
</details>

**Comment by gl-ihorkoblan** [comment]
Let us know please when it could be fixed?

**Comment by anhdhq** [comment]
i try to create a videoPlayer and create a scrollController to fake timeline of videoplayer.
then addLintener for scrollController to listen when user scroll. after that i'm try to change videoplayer video frame

on android it's work ok. but on IOS it's doesn't change video frame.
any solution? many thanks

**Comment by anhdhq** [comment]
```
timeLineController.addListener(() async {
      if (!isPlay.value) {
        final double position = timeLineController.position.pixels;
        await videoPlayerController.seekTo(
          Duration(milliseconds: (position * 1000) ~/ sizeWidgetTimeLine1s),
        );
        await videoPlayerController.play();
        await videoPlayerController.pause();
    });
```

**Comment by aytunch** [comment]
Is this solved in the latest video player update?
It is not optimal to have different executions on iOS and Android. Android seeks and displays the true frame as expected but iOS only seeks in the background and does not render the seeked frame atm.

**Comment by erkansahin** [comment]
The workaround did not work for me.  It causes a problem in my production app.  We should not be depending on workarounds for such an important feature. @darshankawar

**Comment by charlieforward9** [comment]
Requesting a priority bump. This issue is the source of limitations in other packages as seen in mentioned issue above. (seel-channel/video_editor#110)

**Comment by ViktorKirjanov** [comment]
2023 and still does not work on seekTo

the best solution i found to fix this issue is to start and pause after short delay. i know its not good but i do not see anything better so far

```
if (widget.videoPlayerController.value.isPlaying) {
  widget.videoPlayerController.seekTo(targetPosition);
} else {
  widget.videoPlayerController.seekTo(targetPosition).then((_) {
    widget.videoPlayerController.play().then((_) async {
      await Future.delayed(const Duration(milliseconds: 250)).then((_) {
        widget.videoPlayerController.pause();
      });
    });
  });
}
```

**Comment by Chris-FizziQ** [comment]
As I needed to use an older version of the plugin, I added a 100 ms delay in the function seekTo in FLTVideoPlayerPlugin.m before updating the frame and it works well : 

- (void)seekTo:(FLTPositionMessage *)input error:(FlutterError **)error {
  FLTVideoPlayer *player = self.playersByTextureId[input.textureId];
  [player seekTo:input.position.intValue];
    double delayInSeconds = 0.1; // 100 milliseconds is 0.1 seconds

    dispatch_time_t popTime = dispatch_time(DISPATCH_TIME_NOW, (int64_t)(delayInSeconds * NSEC_PER_SEC));
    dispatch_after(popTime, dispatch_get_main_queue(), ^{
        [self.registry textureFrameAvailable:input.textureId.intValue];
    });
  //[self.registry textureFrameAvailable:input.textureId.intValue];
}

**Comment by Henriquek47** [comment]
any updateds? I'm using seekTo, but there's still a slight delay; it's not smooth

**Comment by stuartmorgan-g** [comment]
This was fixed by https://github.com/flutter/packages/pull/5781, which added an expect-frame step to the post-seek callback handler for both iOS and macOS.
