### ISSUE TITLE
App won't run on ios simulator the second time, Runner.app: resource fork, Finder information, or similar detritus not allowed

### ISSUE THREAD

**Issue by ziz19** [flutter/flutter#79689]
This is an the same security problem in #49290
This happens on flutter 1.22 version. Every time I make a flutter run, I have to use flutter clean. 
## Steps to Reproduce
open the terminal
open the simulator using `open -a Simulator.app`
run `flutter clean` in my application folder
run `flutter run` in my application folder, this will launch my app in the simulator successfully
press cmd-c to terminate the running app.
run `flutter run` again, the error occurs

**Expected results:** 

The app should launch in the simulator. Both times should build successfully. 
The successful output is below:
```
Running "flutter pub get" in flutter_complete_guide...              0.3s
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         6.1s
Xcode build done.                                           19.2s
Waiting for iPhone 12 Pro Max to report its views...                 3ms
Syncing files to device iPhone 12 Pro Max...                       120ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on iPhone 12 Pro Max is available at: http://127.0.0.1:64352/kx8ABWIDjdI=/
Application finished.
```

**Actual results:** 

The second run has error saying build fail. 
```
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
 
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         4.7s
Xcode build done.                                            9.6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/zinan/Documents/Udemy/Flutter/flutter_complete_guide/build/ios/Debug-iphonesimulator/Runner.app: resource fork, Finder information, or similar detritus not
    allowed
    Command CodeSign failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development
    team in the Runner editor. (in target 'Runner' from project 'Runner')

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.
```

<details>
  <summary>Logs</summary>

```
```

```
```

The flutter doctor diagnosis is below
```
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
    • Flutter version 1.22.5 at /Users/zinan/opt/flutter
    • Framework revision 7891006299 (4 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[!] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /Users/zinan/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

 
[✓] Connected device (1 available)            
    • iPhone 12 Pro Max (mobile) • 2FACB414-2E2A-43FC-9F5B-ACCE70B14E8B • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
```

</details>

**Comment by iapicca** [comment]
@ziz19 
your flutter version is dated can you please run 
```console
flutter channel -master
flutter upgrade -f
```
your **_updated_** `flutter doctor -v`, your `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by ziz19** [comment]
@iapicca 
Below is my updated doctor diagnosis
```
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
    • Flutter version 2.0.4 at /Users/zinan/opt/flutter
    • Framework revision b1395592de (2 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage
        on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /Users/zinan/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 2FACB414-2E2A-43FC-9F5B-ACCE70B14E8B • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 89.0.4389.114
```

The minimal code is below:
open the terminal and type the following commands
```
open -a Simulator.app
flutter create myapp
cd myapp
flutter run
```
This will successfully run the initialized flutter app. Then in the terminal press ctrl-c to terminate the running app.
And run the app again using `flutter run`
The error occurs.

**Comment by jmagman** [comment]
@ziz19 Do you see this problem if you run twice from Xcode?

**Comment by ziz19** [comment]
> @ziz19 Do you see this problem if you run twice from Xcode?

It's strange that I could not run the app from Xcode. I followed the documentation [https://flutter.dev/docs/get-started/install/macos](url) to open the workspace in Xcode using `open ios/Runner.xcworkspace,` select the simulator and hit build&run on the top. This gives me the building error. 

[Build target Runner_2021-04-05T16-20-01.txt](https://github.com/flutter/flutter/files/6260749/Build.target.Runner_2021-04-05T16-20-01.txt)

**Comment by TahaTesser** [comment]
Hi @ziz19
Following the steps from  https://github.com/flutter/flutter/issues/79689#issuecomment-812915604 on the same, doesn't have any issue when running the app second time from the command line. 

However, the app fails to run from `ios/Runner.xcworkspace`, run into the same issue as you right. 
To reproduce the Xcode issue, run the app once from terminal and open `ios/Runner.xcworkspace` and run the app on the same simulator, this only happens on the `stable` channel.

<details> 
<summary>logs</summary> 

```bash
PhaseScriptExecution Thin\ Binary /Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-3B06AD1E1E4923F5004D2608.sh (in target 'Runner' from project 'Runner')
    cd /Users/tahatesser/AndroidStudioProjects/myapp/ios
    export ACTION\=build
    export AD_HOC_CODE_SIGNING_ALLOWED\=YES
    export ALTERNATE_GROUP\=staff
    export ALTERNATE_MODE\=u+w,go-w,a+rX
    export ALTERNATE_OWNER\=tahatesser
    export ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES\=NO
    export ALWAYS_SEARCH_USER_PATHS\=NO
    export ALWAYS_USE_SEPARATE_HEADERMAPS\=NO
    export APPLE_INTERNAL_DEVELOPER_DIR\=/AppleInternal/Developer
    export APPLE_INTERNAL_DIR\=/AppleInternal
    export APPLE_INTERNAL_DOCUMENTATION_DIR\=/AppleInternal/Documentation
    export APPLE_INTERNAL_LIBRARY_DIR\=/AppleInternal/Library
    export APPLE_INTERNAL_TOOLS\=/AppleInternal/Developer/Tools
    export APPLICATION_EXTENSION_API_ONLY\=NO
    export APPLY_RULES_IN_COPY_FILES\=NO
    export APPLY_RULES_IN_COPY_HEADERS\=NO
    export ARCHS\=x86_64
    export ARCHS_STANDARD\=arm64\ x86_64\ i386
    export ARCHS_STANDARD_32_64_BIT\=arm64\ i386\ x86_64
    export ARCHS_STANDARD_32_BIT\=i386
    export ARCHS_STANDARD_64_BIT\=arm64\ x86_64
    export ARCHS_STANDARD_INCLUDING_64_BIT\=arm64\ x86_64\ i386
    export ARCHS_UNIVERSAL_IPHONE_OS\=arm64\ i386\ x86_64
    export ASSETCATALOG_COMPILER_APPICON_NAME\=AppIcon
    export ASSETCATALOG_FILTER_FOR_DEVICE_MODEL\=iPhone13,2
    export ASSETCATALOG_FILTER_FOR_DEVICE_OS_VERSION\=14.4
    export AVAILABLE_PLATFORMS\=appletvos\ appletvsimulator\ iphoneos\ iphonesimulator\ macosx\ watchos\ watchsimulator
    export AppIdentifierPrefix\=RAN7JQUR5S.
    export BITCODE_GENERATION_MODE\=marker
    export BUILD_ACTIVE_RESOURCES_ONLY\=YES
    export BUILD_COMPONENTS\=headers\ build
    export BUILD_DIR\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Products
    export BUILD_LIBRARY_FOR_DISTRIBUTION\=NO
    export BUILD_ROOT\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Products
    export BUILD_STYLE\=
    export BUILD_VARIANTS\=normal
    export BUILT_PRODUCTS_DIR\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Products/Debug-iphonesimulator
    export BUNDLE_CONTENTS_FOLDER_PATH_deep\=Contents/
    export BUNDLE_EXECUTABLE_FOLDER_NAME_deep\=MacOS
    export BUNDLE_FORMAT\=shallow
    export BUNDLE_FRAMEWORKS_FOLDER_PATH\=Frameworks
    export BUNDLE_PLUGINS_FOLDER_PATH\=PlugIns
    export BUNDLE_PRIVATE_HEADERS_FOLDER_PATH\=PrivateHeaders
    export BUNDLE_PUBLIC_HEADERS_FOLDER_PATH\=Headers
    export CACHE_ROOT\=/var/folders/37/jzy2jdc16sb3p89cn_6g967c0000gn/C/com.apple.DeveloperTools/12.4-12D4e/Xcode
    export CCHROOT\=/var/folders/37/jzy2jdc16sb3p89cn_6g967c0000gn/C/com.apple.DeveloperTools/12.4-12D4e/Xcode
    export CHMOD\=/bin/chmod
    export CHOWN\=/usr/sbin/chown
    export CLANG_ANALYZER_NONNULL\=YES
    export CLANG_CXX_LANGUAGE_STANDARD\=gnu++0x
    export CLANG_CXX_LIBRARY\=libc++
    export CLANG_ENABLE_MODULES\=YES
    export CLANG_ENABLE_OBJC_ARC\=YES
    export CLANG_MODULES_BUILD_SESSION_FILE\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation
    export CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING\=YES
    export CLANG_WARN_BOOL_CONVERSION\=YES
    export CLANG_WARN_COMMA\=YES
    export CLANG_WARN_CONSTANT_CONVERSION\=YES
    export CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS\=YES
    export CLANG_WARN_DIRECT_OBJC_ISA_USAGE\=YES_ERROR
    export CLANG_WARN_EMPTY_BODY\=YES
    export CLANG_WARN_ENUM_CONVERSION\=YES
    export CLANG_WARN_INFINITE_RECURSION\=YES
    export CLANG_WARN_INT_CONVERSION\=YES
    export CLANG_WARN_NON_LITERAL_NULL_CONVERSION\=YES
    export CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF\=YES
    export CLANG_WARN_OBJC_LITERAL_CONVERSION\=YES
    export CLANG_WARN_OBJC_ROOT_CLASS\=YES_ERROR
    export CLANG_WARN_RANGE_LOOP_ANALYSIS\=YES
    export CLANG_WARN_STRICT_PROTOTYPES\=YES
    export CLANG_WARN_SUSPICIOUS_MOVE\=YES
    export CLANG_WARN_UNREACHABLE_CODE\=YES
    export CLANG_WARN__DUPLICATE_METHOD_MATCH\=YES
    export CLASS_FILE_DIR\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/JavaClasses
    export CLEAN_PRECOMPS\=YES
    export CLONE_HEADERS\=NO
    export CODESIGNING_FOLDER_PATH\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Products/Debug-iphonesimulator/Runner.app
    export CODE_SIGNING_ALLOWED\=YES
    export CODE_SIGNING_REQUIRED\=YES
    export CODE_SIGN_CONTEXT_CLASS\=XCiPhoneSimulatorCodeSignContext
    export CODE_SIGN_IDENTITY\=-
    export CODE_SIGN_INJECT_BASE_ENTITLEMENTS\=YES
    export COLOR_DIAGNOSTICS\=NO
    export COMBINE_HIDPI_IMAGES\=NO
    export COMPILER_INDEX_STORE_ENABLE\=Default
    export COMPOSITE_SDK_DIRS\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/CompositeSDKs
    export COMPRESS_PNG_FILES\=YES
    export CONFIGURATION\=Debug
    export CONFIGURATION_BUILD_DIR\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Products/Debug-iphonesimulator
    export CONFIGURATION_TEMP_DIR\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator
    export CONTENTS_FOLDER_PATH\=Runner.app
    export COPYING_PRESERVES_HFS_DATA\=NO
    export COPY_HEADERS_RUN_UNIFDEF\=NO
    export COPY_PHASE_STRIP\=NO
    export COPY_RESOURCES_FROM_STATIC_FRAMEWORKS\=YES
    export CORRESPONDING_DEVICE_PLATFORM_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform
    export CORRESPONDING_DEVICE_PLATFORM_NAME\=iphoneos
    export CORRESPONDING_DEVICE_SDK_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk
    export CORRESPONDING_DEVICE_SDK_NAME\=iphoneos14.4
    export CP\=/bin/cp
    export CREATE_INFOPLIST_SECTION_IN_BINARY\=NO
    export CURRENT_ARCH\=undefined_arch
    export CURRENT_PROJECT_VERSION\=1
    export CURRENT_VARIANT\=normal
    export DART_OBFUSCATION\=false
    export DEAD_CODE_STRIPPING\=YES
    export DEBUGGING_SYMBOLS\=YES
    export DEBUG_INFORMATION_FORMAT\=dwarf
    export DEFAULT_COMPILER\=com.apple.compilers.llvm.clang.1_0
    export DEFAULT_DEXT_INSTALL_PATH\=/System/Library/DriverExtensions
    export DEFAULT_KEXT_INSTALL_PATH\=/System/Library/Extensions
    export DEFINES_MODULE\=NO
    export DEPLOYMENT_LOCATION\=NO
    export DEPLOYMENT_POSTPROCESSING\=NO
    export DEPLOYMENT_TARGET_CLANG_ENV_NAME\=IPHONEOS_DEPLOYMENT_TARGET
    export DEPLOYMENT_TARGET_CLANG_FLAG_NAME\=mios-simulator-version-min
    export DEPLOYMENT_TARGET_CLANG_FLAG_PREFIX\=-mios-simulator-version-min\=
    export DEPLOYMENT_TARGET_LD_ENV_NAME\=IPHONEOS_DEPLOYMENT_TARGET
    export DEPLOYMENT_TARGET_LD_FLAG_NAME\=ios_simulator_version_min
    export DEPLOYMENT_TARGET_SETTING_NAME\=IPHONEOS_DEPLOYMENT_TARGET
    export DEPLOYMENT_TARGET_SUGGESTED_VALUES\=9.0\ 9.2\ 10.0\ 10.2\ 11.0\ 11.2\ 11.4\ 12.1\ 12.3\ 13.0\ 13.2\ 13.4\ 13.6\ 14.1\ 14.3\ 14.4
    export DERIVED_FILES_DIR\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
    export DERIVED_FILE_DIR\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
    export DERIVED_SOURCES_DIR\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
    export DEVELOPER_APPLICATIONS_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/Applications
    export DEVELOPER_BIN_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/usr/bin
    export DEVELOPER_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer
    export DEVELOPER_FRAMEWORKS_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/Library/Frameworks
    export DEVELOPER_FRAMEWORKS_DIR_QUOTED\=/Volumes/Extreme/Xcode.app/Contents/Developer/Library/Frameworks
    export DEVELOPER_LIBRARY_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/Library
    export DEVELOPER_SDK_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
    export DEVELOPER_TOOLS_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/Tools
    export DEVELOPER_USR_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/usr
    export DEVELOPMENT_LANGUAGE\=en
    export DOCUMENTATION_FOLDER_PATH\=Runner.app/en.lproj/Documentation
    export DONT_GENERATE_INFOPLIST_FILE\=NO
    export DO_HEADER_SCANNING_IN_JAM\=NO
    export DSTROOT\=/tmp/Runner.dst
    export DT_TOOLCHAIN_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
    export DWARF_DSYM_FILE_NAME\=Runner.app.dSYM
    export DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT\=NO
    export DWARF_DSYM_FOLDER_PATH\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Products/Debug-iphonesimulator
    export EFFECTIVE_PLATFORM_NAME\=-iphonesimulator
    export EMBEDDED_CONTENT_CONTAINS_SWIFT\=NO
    export EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE\=NO
    export ENABLE_BITCODE\=NO
    export ENABLE_DEFAULT_HEADER_SEARCH_PATHS\=YES
    export ENABLE_HARDENED_RUNTIME\=NO
    export ENABLE_HEADER_DEPENDENCIES\=YES
    export ENABLE_ON_DEMAND_RESOURCES\=YES
    export ENABLE_PREVIEWS\=NO
    export ENABLE_STRICT_OBJC_MSGSEND\=YES
    export ENABLE_TESTABILITY\=YES
    export ENABLE_TESTING_SEARCH_PATHS\=NO
    export ENTITLEMENTS_DESTINATION\=__entitlements
    export ENTITLEMENTS_REQUIRED\=YES
    export EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS\=.DS_Store\ .svn\ .git\ .hg\ CVS
    export EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES\=\*.nib\ \*.lproj\ \*.framework\ \*.gch\ \*.xcode\*\ \*.xcassets\ \(\*\)\ .DS_Store\ CVS\ .svn\ .git\ .hg\ \*.pbproj\ \*.pbxproj
    export EXECUTABLES_FOLDER_PATH\=Runner.app/Executables
    export EXECUTABLE_FOLDER_PATH\=Runner.app
    export EXECUTABLE_NAME\=Runner
    export EXECUTABLE_PATH\=Runner.app/Runner
    export EXPANDED_CODE_SIGN_IDENTITY\=-
    export EXPANDED_CODE_SIGN_IDENTITY_NAME\=-
    export FILE_LIST\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects/LinkFileList
    export FIXED_FILES_DIR\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/FixedFiles
    export FLUTTER_APPLICATION_PATH\=/Users/tahatesser/AndroidStudioProjects/myapp
    export FLUTTER_BUILD_DIR\=build
    export FLUTTER_BUILD_NAME\=1.0.0
    export FLUTTER_BUILD_NUMBER\=1
    export FLUTTER_ROOT\=/Users/tahatesser/Code/flutter_stable
    export FLUTTER_TARGET\=/Users/tahatesser/AndroidStudioProjects/myapp/lib/main.dart
    export FRAMEWORKS_FOLDER_PATH\=Runner.app/Frameworks
    export FRAMEWORK_FLAG_PREFIX\=-framework
    export FRAMEWORK_SEARCH_PATHS\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Products/Debug-iphonesimulator\ 
    export FRAMEWORK_VERSION\=A
    export FULL_PRODUCT_NAME\=Runner.app
    export GCC3_VERSION\=3.3
    export GCC_C_LANGUAGE_STANDARD\=gnu99
    export GCC_DYNAMIC_NO_PIC\=NO
    export GCC_INLINES_ARE_PRIVATE_EXTERN\=YES
    export GCC_NO_COMMON_BLOCKS\=YES
    export GCC_OBJC_LEGACY_DISPATCH\=YES
    export GCC_OPTIMIZATION_LEVEL\=0
    export GCC_PFE_FILE_C_DIALECTS\=c\ objective-c\ c++\ objective-c++
    export GCC_PREPROCESSOR_DEFINITIONS\=DEBUG\=1\ 
    export GCC_SYMBOLS_PRIVATE_EXTERN\=NO
    export GCC_TREAT_WARNINGS_AS_ERRORS\=NO
    export GCC_VERSION\=com.apple.compilers.llvm.clang.1_0
    export GCC_VERSION_IDENTIFIER\=com_apple_compilers_llvm_clang_1_0
    export GCC_WARN_64_TO_32_BIT_CONVERSION\=YES
    export GCC_WARN_ABOUT_RETURN_TYPE\=YES_ERROR
    export GCC_WARN_UNDECLARED_SELECTOR\=YES
    export GCC_WARN_UNINITIALIZED_AUTOS\=YES_AGGRESSIVE
    export GCC_WARN_UNUSED_FUNCTION\=YES
    export GCC_WARN_UNUSED_VARIABLE\=YES
    export GENERATED_MODULEMAP_DIR\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/GeneratedModuleMaps-iphonesimulator
    export GENERATE_MASTER_OBJECT_FILE\=NO
    export GENERATE_PKGINFO_FILE\=YES
    export GENERATE_PROFILING_CODE\=NO
    export GENERATE_TEXT_BASED_STUBS\=NO
    export GID\=20
    export GROUP\=staff
    export HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT\=YES
    export HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES\=YES
    export HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS\=YES
    export HEADERMAP_INCLUDES_PROJECT_HEADERS\=YES
    export HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES\=YES
    export HEADERMAP_USES_VFS\=NO
    export HEADER_SEARCH_PATHS\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Products/Debug-iphonesimulator/include\ 
    export HIDE_BITCODE_SYMBOLS\=YES
    export HOME\=/Users/tahatesser
    export ICONV\=/usr/bin/iconv
    export INFOPLIST_EXPAND_BUILD_SETTINGS\=YES
    export INFOPLIST_FILE\=Runner/Info.plist
    export INFOPLIST_OUTPUT_FORMAT\=binary
    export INFOPLIST_PATH\=Runner.app/Info.plist
    export INFOPLIST_PREPROCESS\=NO
    export INFOSTRINGS_PATH\=Runner.app/en.lproj/InfoPlist.strings
    export INLINE_PRIVATE_FRAMEWORKS\=NO
    export INSTALLHDRS_COPY_PHASE\=NO
    export INSTALLHDRS_SCRIPT_PHASE\=NO
    export INSTALL_DIR\=/tmp/Runner.dst/Applications
    export INSTALL_GROUP\=staff
    export INSTALL_MODE_FLAG\=u+w,go-w,a+rX
    export INSTALL_OWNER\=tahatesser
    export INSTALL_PATH\=/Applications
    export INSTALL_ROOT\=/tmp/Runner.dst
    export IPHONEOS_DEPLOYMENT_TARGET\=9.0
    export JAVAC_DEFAULT_FLAGS\=-J-Xms64m\ -J-XX:NewSize\=4M\ -J-Dfile.encoding\=UTF8
    export JAVA_APP_STUB\=/System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
    export JAVA_ARCHIVE_CLASSES\=YES
    export JAVA_ARCHIVE_TYPE\=JAR
    export JAVA_COMPILER\=/usr/bin/javac
    export JAVA_FOLDER_PATH\=Runner.app/Java
    export JAVA_FRAMEWORK_RESOURCES_DIRS\=Resources
    export JAVA_JAR_FLAGS\=cv
    export JAVA_SOURCE_SUBDIR\=.
    export JAVA_USE_DEPENDENCIES\=YES
    export JAVA_ZIP_FLAGS\=-urg
    export JIKES_DEFAULT_FLAGS\=+E\ +OLDCSO
    export KEEP_PRIVATE_EXTERNS\=NO
    export LD_DEPENDENCY_INFO_FILE\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/undefined_arch/Runner_dependency_info.dat
    export LD_ENTITLEMENTS_SECTION\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner.app-Simulated.xcent
    export LD_GENERATE_MAP_FILE\=NO
    export LD_MAP_FILE_PATH\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-LinkMap-normal-undefined_arch.txt
    export LD_NO_PIE\=NO
    export LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER\=YES
    export LD_RUNPATH_SEARCH_PATHS\=\ @executable_path/Frameworks
    export LEGACY_DEVELOPER_DIR\=/Volumes/Extreme/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
    export LEX\=lex
    export LIBRARY_DEXT_INSTALL_PATH\=/Library/DriverExtensions
    export LIBRARY_FLAG_NOSPACE\=YES
    export LIBRARY_FLAG_PREFIX\=-l
    export LIBRARY_KEXT_INSTALL_PATH\=/Library/Extensions
    export LIBRARY_SEARCH_PATHS\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Products/Debug-iphonesimulator\ 
    export LINKER_DISPLAYS_MANGLED_NAMES\=NO
    export LINK_FILE_LIST_normal_x86_64\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.LinkFileList
    export LINK_WITH_STANDARD_LIBRARIES\=YES
    export LLVM_TARGET_TRIPLE_OS_VERSION\=ios9.0
    export LLVM_TARGET_TRIPLE_SUFFIX\=-simulator
    export LLVM_TARGET_TRIPLE_VENDOR\=apple
    export LOCALIZED_RESOURCES_FOLDER_PATH\=Runner.app/en.lproj
    export LOCALIZED_STRING_MACRO_NAMES\=NSLocalizedString\ CFCopyLocalizedString
    export LOCALIZED_STRING_SWIFTUI_SUPPORT\=YES
    export LOCAL_ADMIN_APPS_DIR\=/Applications/Utilities
    export LOCAL_APPS_DIR\=/Applications
    export LOCAL_DEVELOPER_DIR\=/Library/Developer
    export LOCAL_LIBRARY_DIR\=/Library
    export LOCROOT\=/Users/tahatesser/AndroidStudioProjects/myapp/ios
    export LOCSYMROOT\=/Users/tahatesser/AndroidStudioProjects/myapp/ios
    export MACH_O_TYPE\=mh_execute
    export MAC_OS_X_PRODUCT_BUILD_VERSION\=20D91
    export MAC_OS_X_VERSION_ACTUAL\=110203
    export MAC_OS_X_VERSION_MAJOR\=110000
    export MAC_OS_X_VERSION_MINOR\=110200
    export METAL_LIBRARY_FILE_BASE\=default
    export METAL_LIBRARY_OUTPUT_DIR\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Products/Debug-iphonesimulator/Runner.app
    export MODULES_FOLDER_PATH\=Runner.app/Modules
    export MODULE_CACHE_DIR\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
    export MTL_ENABLE_DEBUG_INFO\=YES
    export NATIVE_ARCH\=x86_64
    export NATIVE_ARCH_32_BIT\=i386
    export NATIVE_ARCH_64_BIT\=x86_64
    export NATIVE_ARCH_ACTUAL\=x86_64
    export NO_COMMON\=YES
    export OBJC_ABI_VERSION\=2
    export OBJECT_FILE_DIR\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects
    export OBJECT_FILE_DIR_normal\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal
    export OBJROOT\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex
    export ONLY_ACTIVE_ARCH\=YES
    export OS\=MACOS
    export OSAC\=/usr/bin/osacompile
    export PACKAGE_CONFIG\=/Users/tahatesser/AndroidStudioProjects/myapp/.dart_tool/package_config.json
    export PACKAGE_TYPE\=com.apple.package-type.wrapper.application
    export PASCAL_STRINGS\=YES
    export PATH\=/Volumes/Extreme/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Volumes/Extreme/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/bin:/Volumes/Extreme/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Volumes/Extreme/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/bin:/Volumes/Extreme/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/local/bin:/Volumes/Extreme/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Volumes/Extreme/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/local/bin:/Volumes/Extreme/Xcode.app/Contents/Developer/usr/bin:/Volumes/Extreme/Xcode.app/Contents/Developer/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
    export PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES\=/usr/include\ /usr/local/include\ /System/Library/Frameworks\ /System/Library/PrivateFrameworks\ /Volumes/Extreme/Xcode.app/Contents/Developer/Headers\ /Volumes/Extreme/Xcode.app/Contents/Developer/SDKs\ /Volumes/Extreme/Xcode.app/Contents/Developer/Platforms
    export PBDEVELOPMENTPLIST_PATH\=Runner.app/pbdevelopment.plist
    export PER_ARCH_OBJECT_FILE_DIR\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/undefined_arch
    export PER_VARIANT_OBJECT_FILE_DIR\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal
    export PKGINFO_FILE_PATH\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/PkgInfo
    export PKGINFO_PATH\=Runner.app/PkgInfo
    export PLATFORM_DEVELOPER_APPLICATIONS_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications
    export PLATFORM_DEVELOPER_BIN_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin
    export PLATFORM_DEVELOPER_LIBRARY_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library
    export PLATFORM_DEVELOPER_SDK_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs
    export PLATFORM_DEVELOPER_TOOLS_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Tools
    export PLATFORM_DEVELOPER_USR_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr
    export PLATFORM_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform
    export PLATFORM_DISPLAY_NAME\=iOS\ Simulator
    export PLATFORM_FAMILY_NAME\=iOS
    export PLATFORM_NAME\=iphonesimulator
    export PLATFORM_PREFERRED_ARCH\=x86_64
    export PLATFORM_PRODUCT_BUILD_VERSION\=18D46
    export PLIST_FILE_OUTPUT_FORMAT\=binary
    export PLUGINS_FOLDER_PATH\=Runner.app/PlugIns
    export PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR\=YES
    export PRECOMP_DESTINATION_DIR\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/PrefixHeaders
    export PRESERVE_DEAD_CODE_INITS_AND_TERMS\=NO
    export PRIVATE_HEADERS_FOLDER_PATH\=Runner.app/PrivateHeaders
    export PRODUCT_BUNDLE_IDENTIFIER\=com.example.myapp
    export PRODUCT_BUNDLE_PACKAGE_TYPE\=APPL
    export PRODUCT_MODULE_NAME\=Runner
    export PRODUCT_NAME\=Runner
    export PRODUCT_SETTINGS_PATH\=/Users/tahatesser/AndroidStudioProjects/myapp/ios/Runner/Info.plist
    export PRODUCT_TYPE\=com.apple.product-type.application
    export PROFILING_CODE\=NO
    export PROJECT\=Runner
    export PROJECT_DERIVED_FILE_DIR\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/Runner.build/DerivedSources
    export PROJECT_DIR\=/Users/tahatesser/AndroidStudioProjects/myapp/ios
    export PROJECT_FILE_PATH\=/Users/tahatesser/AndroidStudioProjects/myapp/ios/Runner.xcodeproj
    export PROJECT_NAME\=Runner
    export PROJECT_TEMP_DIR\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/Runner.build
    export PROJECT_TEMP_ROOT\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex
    export PUBLIC_HEADERS_FOLDER_PATH\=Runner.app/Headers
    export RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS\=YES
    export REMOVE_CVS_FROM_RESOURCES\=YES
    export REMOVE_GIT_FROM_RESOURCES\=YES
    export REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES\=YES
    export REMOVE_HG_FROM_RESOURCES\=YES
    export REMOVE_SVN_FROM_RESOURCES\=YES
    export REZ_COLLECTOR_DIR\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/ResourceManagerResources
    export REZ_OBJECTS_DIR\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/ResourceManagerResources/Objects
    export REZ_SEARCH_PATHS\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Products/Debug-iphonesimulator\ 
    export SCAN_ALL_SOURCE_FILES_FOR_INCLUDES\=NO
    export SCRIPTS_FOLDER_PATH\=Runner.app/Scripts
    export SCRIPT_INPUT_FILE_COUNT\=0
    export SCRIPT_INPUT_FILE_LIST_COUNT\=0
    export SCRIPT_OUTPUT_FILE_COUNT\=0
    export SCRIPT_OUTPUT_FILE_LIST_COUNT\=0
    export SDKROOT\=/Volumes/Extreme/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk
    export SDK_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk
    export SDK_DIR_iphonesimulator14_4\=/Volumes/Extreme/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk
    export SDK_NAME\=iphonesimulator14.4
    export SDK_NAMES\=iphonesimulator14.4
    export SDK_PRODUCT_BUILD_VERSION\=18D46
    export SDK_VERSION\=14.4
    export SDK_VERSION_ACTUAL\=140400
    export SDK_VERSION_MAJOR\=140000
    export SDK_VERSION_MINOR\=140400
    export SED\=/usr/bin/sed
    export SEPARATE_STRIP\=NO
    export SEPARATE_SYMBOL_EDIT\=NO
    export SET_DIR_MODE_OWNER_GROUP\=YES
    export SET_FILE_MODE_OWNER_GROUP\=NO
    export SHALLOW_BUNDLE\=YES
    export SHARED_DERIVED_FILE_DIR\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Products/Debug-iphonesimulator/DerivedSources
    export SHARED_FRAMEWORKS_FOLDER_PATH\=Runner.app/SharedFrameworks
    export SHARED_PRECOMPS_DIR\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/PrecompiledHeaders
    export SHARED_SUPPORT_FOLDER_PATH\=Runner.app/SharedSupport
    export SKIP_INSTALL\=NO
    export SOURCE_ROOT\=/Users/tahatesser/AndroidStudioProjects/myapp/ios
    export SRCROOT\=/Users/tahatesser/AndroidStudioProjects/myapp/ios
    export STRINGS_FILE_OUTPUT_ENCODING\=binary
    export STRIP_BITCODE_FROM_COPIED_FILES\=NO
    export STRIP_INSTALLED_PRODUCT\=YES
    export STRIP_STYLE\=all
    export STRIP_SWIFT_SYMBOLS\=YES
    export SUPPORTED_DEVICE_FAMILIES\=1,2
    export SUPPORTED_PLATFORMS\=iphoneos\ iphonesimulator
    export SUPPORTS_TEXT_BASED_API\=NO
    export SWIFT_OBJC_BRIDGING_HEADER\=Runner/Runner-Bridging-Header.h
    export SWIFT_OPTIMIZATION_LEVEL\=-Onone
    export SWIFT_PLATFORM_TARGET_PREFIX\=ios
    export SWIFT_RESPONSE_FILE_PATH_normal_x86_64\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.SwiftFileList
    export SWIFT_VERSION\=5.0
    export SYMROOT\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Products
    export SYSTEM_ADMIN_APPS_DIR\=/Applications/Utilities
    export SYSTEM_APPS_DIR\=/Applications
    export SYSTEM_CORE_SERVICES_DIR\=/System/Library/CoreServices
    export SYSTEM_DEMOS_DIR\=/Applications/Extras
    export SYSTEM_DEVELOPER_APPS_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/Applications
    export SYSTEM_DEVELOPER_BIN_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/usr/bin
    export SYSTEM_DEVELOPER_DEMOS_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/Applications/Utilities/Built\ Examples
    export SYSTEM_DEVELOPER_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer
    export SYSTEM_DEVELOPER_DOC_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/ADC\ Reference\ Library
    export SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/Applications/Graphics\ Tools
    export SYSTEM_DEVELOPER_JAVA_TOOLS_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/Applications/Java\ Tools
    export SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/Applications/Performance\ Tools
    export SYSTEM_DEVELOPER_RELEASENOTES_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/ADC\ Reference\ Library/releasenotes
    export SYSTEM_DEVELOPER_TOOLS\=/Volumes/Extreme/Xcode.app/Contents/Developer/Tools
    export SYSTEM_DEVELOPER_TOOLS_DOC_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/ADC\ Reference\ Library/documentation/DeveloperTools
    export SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/ADC\ Reference\ Library/releasenotes/DeveloperTools
    export SYSTEM_DEVELOPER_USR_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/usr
    export SYSTEM_DEVELOPER_UTILITIES_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/Applications/Utilities
    export SYSTEM_DEXT_INSTALL_PATH\=/System/Library/DriverExtensions
    export SYSTEM_DOCUMENTATION_DIR\=/Library/Documentation
    export SYSTEM_KEXT_INSTALL_PATH\=/System/Library/Extensions
    export SYSTEM_LIBRARY_DIR\=/System/Library
    export TAPI_VERIFY_MODE\=ErrorsOnly
    export TARGETED_DEVICE_FAMILY\=1,2
    export TARGETNAME\=Runner
    export TARGET_BUILD_DIR\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Products/Debug-iphonesimulator
    export TARGET_DEVICE_IDENTIFIER\=83060656-28E7-44CD-801E-B11EC3EC89BA
    export TARGET_DEVICE_MODEL\=iPhone13,2
    export TARGET_DEVICE_OS_VERSION\=14.4
    export TARGET_NAME\=Runner
    export TARGET_TEMP_DIR\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
    export TEMP_DIR\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
    export TEMP_FILES_DIR\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
    export TEMP_FILE_DIR\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
    export TEMP_ROOT\=/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex
    export TEST_FRAMEWORK_SEARCH_PATHS\=\ /Volumes/Extreme/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks\ /Volumes/Extreme/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk/Developer/Library/Frameworks
    export TEST_LIBRARY_SEARCH_PATHS\=\ /Volumes/Extreme/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/lib
    export TOOLCHAINS\=com.apple.dt.toolchain.XcodeDefault
    export TOOLCHAIN_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
    export TRACK_WIDGET_CREATION\=true
    export TREAT_MISSING_BASELINES_AS_TEST_FAILURES\=NO
    export TREE_SHAKE_ICONS\=false
    export TeamIdentifierPrefix\=RAN7JQUR5S.
    export UID\=501
    export UNLOCALIZED_RESOURCES_FOLDER_PATH\=Runner.app
    export UNSTRIPPED_PRODUCT\=NO
    export USER\=tahatesser
    export USER_APPS_DIR\=/Users/tahatesser/Applications
    export USER_LIBRARY_DIR\=/Users/tahatesser/Library
    export USE_DYNAMIC_NO_PIC\=YES
    export USE_HEADERMAP\=YES
    export USE_HEADER_SYMLINKS\=NO
    export USE_LLVM_TARGET_TRIPLES\=YES
    export USE_LLVM_TARGET_TRIPLES_FOR_CLANG\=YES
    export USE_LLVM_TARGET_TRIPLES_FOR_LD\=YES
    export USE_LLVM_TARGET_TRIPLES_FOR_TAPI\=YES
    export VALIDATE_DEVELOPMENT_ASSET_PATHS\=YES_ERROR
    export VALIDATE_PRODUCT\=NO
    export VALIDATE_WORKSPACE\=YES_ERROR
    export VALID_ARCHS\=arm64\ arm64e\ i386\ x86_64
    export VERBOSE_PBXCP\=NO
    export VERSIONING_SYSTEM\=apple-generic
    export VERSIONPLIST_PATH\=Runner.app/version.plist
    export VERSION_INFO_BUILDER\=tahatesser
    export VERSION_INFO_FILE\=Runner_vers.c
    export VERSION_INFO_STRING\=\"@\(\#\)PROGRAM:Runner\ \ PROJECT:Runner-1\"
    export WRAPPER_EXTENSION\=app
    export WRAPPER_NAME\=Runner.app
    export WRAPPER_SUFFIX\=.app
    export WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES\=NO
    export XCODE_APP_SUPPORT_DIR\=/Volumes/Extreme/Xcode.app/Contents/Developer/Library/Xcode
    export XCODE_PRODUCT_BUILD_VERSION\=12D4e
    export XCODE_VERSION_ACTUAL\=1240
    export XCODE_VERSION_MAJOR\=1200
    export XCODE_VERSION_MINOR\=1240
    export XPCSERVICES_FOLDER_PATH\=Runner.app/XPCServices
    export YACC\=yacc
    export arch\=undefined_arch
    export variant\=normal
    /bin/sh -c /Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-3B06AD1E1E4923F5004D2608.sh

building file list ... done
App.framework/
App.framework/App
App.framework/Info.plist
App.framework/flutter_assets/
App.framework/flutter_assets/AssetManifest.json
App.framework/flutter_assets/FontManifest.json
App.framework/flutter_assets/NOTICES
App.framework/flutter_assets/isolate_snapshot_data
App.framework/flutter_assets/kernel_blob.bin
App.framework/flutter_assets/vm_snapshot_data
App.framework/flutter_assets/fonts/
App.framework/flutter_assets/fonts/MaterialIcons-Regular.otf
App.framework/flutter_assets/packages/
App.framework/flutter_assets/packages/cupertino_icons/
App.framework/flutter_assets/packages/cupertino_icons/assets/
App.framework/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf

sent 39931920 bytes  received 276 bytes  79864392.00 bytes/sec
total size is 39926079  speedup is 1.00
building file list ... done
Flutter.framework/
Flutter.framework/Flutter
Flutter.framework/Info.plist
Flutter.framework/icudtl.dat

sent 37865344 bytes  received 92 bytes  25243624.00 bytes/sec
total size is 37860418  speedup is 1.00
/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Products/Debug-iphonesimulator/Runner.app/Frameworks/App.framework/App: signed bundle with Mach-O thin (x86_64) [io.flutter.flutter.app]
/Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-alwwpcyunmhkgqdygpleqbvodfuz/Build/Products/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework/Flutter: signed bundle with Mach-O thin (x86_64) [io.flutter.flutter]
error: Runner.app/Info.plist does not exist. The Flutter "Thin Binary" build phase must run after "Copy Bundle Resources".

```

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision b1395592de (4 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 83060656-28E7-44CD-801E-B11EC3EC89BA • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 89.0.4389.114

• No issues found
```
	
</details>

**Comment by ziz19** [comment]
Hello @TahaTesser 
It seems that I have to use `flutter clean` to run my app in the first place. 
I performed a steps of 
```
open -a Simulator.app
flutter create myapp
cd myapp
flutter run -v
```
Followed up by
```
flutter clean
flutter run -v
```
ctrl-c to stop the process, and 
`flutter run` again. 
The log contains three outputs from`flutter run -v`
[flutter_log.txt](https://github.com/flutter/flutter/files/6266268/flutter_log.txt)

**Comment by ziz19** [comment]
> Hi @ziz19
> Following the steps from [#79689 (comment)](https://github.com/flutter/flutter/issues/79689#issuecomment-812915604) on the same, doesn't have any issue when running the app second time from the command line.
> 
> Can you please provide logs using the same steps you provided, instead of using `flutter_complete_guide` app
> 
> ```
> open -a Simulator.app
> flutter create myapp
> cd myapp
> flutter run -v
> ```
> 
> Please provide run logs from above steps
> 
> However, the app fails to run from `ios/Runner.xcworkspace`, run into the same issue as you right.
> To reproduce the Xcode issue, run the app once from terminal and open `ios/Runner.xcworkspace` and run the app on the same simulator, this only happens on the `stable` channel.
> 
> logs
> flutter doctor -v

I'm running into the same issue whenever I click the build&run within XCode workspace. I didn't seem to find the place to run my app using already opened simulator. Could you point me to the right direction please? Thanks

**Comment by jmagman** [comment]
The `Runner.app/Info.plist does not exist` is https://github.com/flutter/flutter/issues/70422 and the fix is available in the master channel.  In the meantime, you can work around this by 
1. Navigate to your Runner target Build Phases in Xcode
2. Expand `Thin Binary`.  Comment out the script:
```bash
# /bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed_and_thin
```
3. Build your app in Xcode
4. Restore the script.
```bash
/bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed_and_thin
```
Note, if you don't restore the script then Flutter won't be embedded in your app.

> I didn't seem to find the place to run my app using already opened simulator. 

You should just need to build, not run.  So ⌘B with a simulator selected
<img width="437" alt="Screen Shot 2021-04-06 at 11 15 20 AM" src="https://user-images.githubusercontent.com/682784/113758985-67437880-96c9-11eb-9b66-0fdf61e33787.png">

Let's keep the focus on `resource fork, Finder information, or similar detritus not allowed` problem in this issue.  Once you work around with the above steps, do you see that error running a second time in Xcode?

**Comment by ziz19** [comment]
@jmagman 
Thank you for the detailed instructions. I'm able to build it with your steps. 
In particular,
I build the app with thin binary commented in XCode. Then I uncomment the script, and use `flutter run` in the terminal. The error still occurs
[flutter_log.txt](https://github.com/flutter/flutter/files/6267124/flutter_log.txt)
However, one strange thing is that this error does not always occur. I created multiple myapp using `flutter create myapp` at different locations, then run `flutter run` multiple times within each of these apps. Not all the apps displays the `resource form` error, and some are working fine

**Comment by jmagman** [comment]
@ziz19 so you don't see `resource fork, Finder information, or similar detritus not allowed` from Xcode?

This is such a weird problem since Flutter doesn't make the `Debug-iphonesimulator/Runner.app` directory--Xcode tooling does.

**Comment by ziz19** [comment]
> @ziz19 so you don't see `resource fork, Finder information, or similar detritus not allowed` from Xcode?
> 
> This is such a weird problem since Flutter doesn't make the `Debug-iphonesimulator/Runner.app` directory--Xcode tooling does.

No, I don't. The build was successful. It is weird since it occurs randomly.

**Comment by ziz19** [comment]
I tried with a clean state by removing the myapp in the Simulator.
`open -a Simulator`, and deleting the existing app on the simulator
`flutter run` this gives me the error in the log
 ```
 error: Runner.app/Info.plist does not exist. The Flutter "Thin Binary" build phase must run after "Copy Bundle Resources".
```
Then I used `flutter clean`, and `flutter run`, this successfully build the app and gives the 
```
Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on iPhone 12 Pro Max is available at: http://127.0.0.1:51519/AOob0goqh5g=/
``` in the log
Finally, I ctrl-c to terminate the app from the terminal, and gives me the `fork error`. 
The `thin binary` error didn't occur before. I'm wondering could this be cache related?

**Comment by jmagman** [comment]
@ziz19 is there any way you can try this on the master channel?  https://flutter.dev/docs/development/tools/sdk/upgrading#switching-flutter-channels

**Comment by ziz19** [comment]
@jmagman I've upgraded my flutter version to master channel. 
Could you see if you could reproduce the error using the below altered instructions?

`open -a Simulator`, and make sure no myapp existed
`flutter create myapp` and `cd myapp`
`flutter run` this should run successful
ctrl-c to terminate the app, and **press home button to return to the home menu on the simulator**
![home_button](https://user-images.githubusercontent.com/20962494/113785583-0d5ca600-96fd-11eb-8cf3-de09e5a056e7.jpg)
`flutter run` again once the simulator is at home page

**Comment by TahaTesser** [comment]
Hi @ziz19 
Following the steps from above comment https://github.com/flutter/flutter/issues/79689#issuecomment-814475518, app launches fine also on `master`

@jmagman  Any ideas?

**Comment by jmagman** [comment]
> Any ideas?

Not really...  It's not a widely reported issue and it's from some xattr that Flutter doesn't add on a file Flutter doesn't create...

**Comment by TahaTesser** [comment]
@ziz19 
Unfortunately, this doesn't look like an issue from the Flutter side and the issue doesn't reproduce on any of the Flutter channels following the steps you provided. If you can reproduce the issue on a different macOS machine, let us know and provide those reproducible steps.

Closing, as this isn't an issue isn't an actionable issue. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by jmagman** [comment]
> Not really... It's not a widely reported issue and it's from some xattr that Flutter doesn't add on a file Flutter doesn't create...

Turns out this may be because of extended attributes present elsewhere in the project.  https://github.com/flutter/flutter/pull/81435 Is likely to fix this.

**Comment by ziz19** [comment]
@Baw-Appie @jmagman Thank you so much for mentioning this. The latest fix on master fix my issues too. There are no fork issues anymore! XD
