### ISSUE TITLE
[local_auth] App throws `Required security features not enabled` PlatformException 

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#80259]
### Description
A Java-based project throws `Required security features not enabled` PlatformException while Kotlin based project works when using the latest `local_auth: ^1.1.4` using [official sample](https://pub.dev/packages/local_auth/example) 

Edit
Happens with Kotlin as well https://github.com/flutter/flutter/issues/80352

### Note
Make sure you've all the security and biometrics features enabled, fingerprint registered on the device/emulator before reproducing the issue.

### Edit Note
App throws same error even when you don't have biometrics registered (it should lead to add biometrics instead https://github.com/flutter/flutter/issues/80510)
 
## Steps reproduce 
1. Create a project with java support on the latest flutter channel
2. Add the latest `local_auth: ^1.1.4` to your `pubspec.yaml` and bump min SDK to `2.12.0`  if it isn't already and click `pub get` in the IDE or execute `flutter pub get`
3. Copy [official sample](https://pub.dev/packages/local_auth/example) to `main.dart.
4. Add [Android Integration](https://pub.dev/packages/local_auth#android-integration)  to `MainActivity.java`
```java
import android.os.Bundle;
import io.flutter.app.FlutterFragmentActivity;
import io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin;
import io.flutter.plugins.localauth.LocalAuthPlugin;

public class MainActivity extends FlutterFragmentActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        FlutterAndroidLifecyclePlugin.registerWith(
                registrarFor(
                        "io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin"));
        LocalAuthPlugin.registerWith(registrarFor("io.flutter.plugins.localauth.LocalAuthPlugin"));
    }
}
```
and modify `AndroidManifest.xml` to add biometrics permission and `io.flutter.app.FlutterApplication` namespace for `application`
```xml
    <uses-permission android:name="android.permission.USE_BIOMETRIC"/>


    <application
       android:name="io.flutter.app.FlutterApplication"
```

5. Run flutter application on an Android device with biometrics registered 
6. Click the first two buttons and make sure biometrics are available to test and click authenticate button and see the error

<details> 
<summary>screenshot</summary> 

<img src="https://user-images.githubusercontent.com/48603081/114369627-4080b880-9b87-11eb-807c-888081778993.jpg" height="450" />

</details>

<details> 
<summary>logs</summary> 

```bash
Launching lib\main.dart on RMX2001 in debug mode...
Running Gradle task 'assembleDebug'...
Note: C:\Users\Taha\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\local_auth-1.1.4\android\src\main\java\io\flutter\plugins\localauth\LocalAuthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\Taha\AndroidStudioProjects\flutter_app\android\app\src\main\java\com\example\flutter_app\MainActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Debug service listening on ws://127.0.0.1:62882/bfmhV1NEw2k=/ws
Syncing files to device RMX2001...
I/GED     (21912): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 27, oppidx_max 27, oppidx_min 0
I/ple.flutter_ap(21912): ProcessProfilingInfo new_methods=585 is saved saved_to_disk=1 resolve_classes_delay=5000
D/ColorViewRootUtil(21912): nav bar mode ignore false downX 396 downY 957 mScreenHeight 2400 mScreenWidth 1080 mStatusBarHeight 54 globalScale 1.125 nav mode 0 rotation 0 event MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=396.0, y[0]=957.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=3215979, downTime=3215979, deviceId=4, source=0x1002, displayId=0 }
D/ColorViewRootUtil(21912): nav bar mode ignore false downX 438 downY 1468 mScreenHeight 2400 mScreenWidth 1080 mStatusBarHeight 54 globalScale 1.125 nav mode 0 rotation 0 event MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=438.0, y[0]=1468.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=3216784, downTime=3216784, deviceId=4, source=0x1002, displayId=0 }
D/ColorViewRootUtil(21912): nav bar mode ignore false downX 367 downY 2202 mScreenHeight 2400 mScreenWidth 1080 mStatusBarHeight 54 globalScale 1.125 nav mode 0 rotation 0 event MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=367.0, y[0]=2202.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=3217874, downTime=3217874, deviceId=4, source=0x1002, displayId=0 }
I/flutter (21912): PlatformException(NotAvailable, Required security features not enabled, null, null)
I/SurfaceView(21912): 238834373 visibleChanged:true -> SurfaceHolder.Callback.surfaceDestroyed
D/Surface (21912): Surface::disconnect(this=0x76c9092000,api=1)
D/ViewRootImpl(21912): setSurfaceViewCreated, created:false
D/Surface (21912): Surface::disconnect(this=0x76c9092000,api=-1)
D/SurfaceView(21912): updateScreenMode w:0 h:0 ViewRoot w:1080 h:2400
D/SurfaceView(21912): try to resquest 90Hz
D/ViewRootImpl(21912): set screen refresh mode 0 due to SurfaceView-238834373
D/Surface (21912): Surface::disconnect(this=0x76e28e4000,api=1)
V/PhoneWindow(21912): DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@28d9810, this = DecorView@61f4f0d[MainActivity]
I/GED     (21912): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 27, oppidx_max 27, oppidx_min 0
E/libEGL  (21912): call to OpenGL ES API with no current context (logged once per thread)
D/SurfaceView(21912): updateScreenMode w:0 h:0 ViewRoot w:1080 h:2400
D/SurfaceView(21912): try to resquest 90Hz
D/View    (21912): [Warning] assignParent to null: this = DecorView@61f4f0d[MainActivity]
I/InputTransport(21912): Destroy ARC handle: 0x76e2606280

```

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.870], locale en-US)
    • Flutter version 2.0.4 at C:\Users\Taha\Code\flutter_stable
    • Framework revision b1395592de (11 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31112.23
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin version 55.0.5
    • Dart plugin version 211.6693.108

[✓] VS Code (version 1.55.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • RMX2001 (mobile)  • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19042.870]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 89.0.774.68

! Doctor found issues in 1 category.
```
	

```bash
[✓] Flutter (Channel master, 2.1.0-13.0.pre.574, on Microsoft Windows [Version 10.0.19042.870], locale en-US)
    • Flutter version 2.1.0-13.0.pre.574 at C:\Users\Taha\Code\flutter_master
    • Framework revision 02efffc134 (2 days ago), 2021-04-10 03:49:01 -0400
    • Engine revision 8863afff16
    • Dart version 2.13.0 (build 2.13.0-222.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31112.23
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin version 55.0.5
    • Dart plugin version 211.6693.108

[✓] VS Code (version 1.55.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • RMX2001 (mobile)  • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19042.870]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 89.0.774.68

! Doctor found issues in 1 category.
```
	
</details>

Ran into this issue when reproducing https://github.com/flutter/flutter/issues/80021

**Comment by tazik561** [comment]
I create 2 projects by [local_auth: ^0.6.3+2](https://github.com/tazik561/local_auth_0.6) on flutter  sdk: ">=2.7.0 <3.0.0" and[ local_auth: ^1.1.4](https://github.com/tazik561/local_auth_1.1.4) and flutter  sdk: ">=2.12.0 <3.0.0".

I run both project in same emulator. Im Using using[ official sample](https://pub.dev/packages/local_auth/example) for both project. [It's video](https://drive.google.com/file/d/1wokUvTbioR26DMAtuuLl4FEMmkjg5Km1/view?usp=sharing)

When I [lunch local_auth: ^0.6.3+2 project](https://pasteboard.co/JWY7bT2.png) and tapped on Authenticate button  this dialog is appeared :
https://pasteboard.co/JWY7Yc9.png

But  when I [lunch  local_auth: ^1.1.4 project](https://pasteboard.co/JWY8HoC.png) and tapped on Authenticate button I just get this error:
`PlatformException(NotAvailable, Required security features not enabled, null, null)`

I expect to see this[ configuration dialog](https://pasteboard.co/JWY7Yc9.png
) like  local_auth: ^0.6.3+2 project on local_auth: ^1.1.4 project.

Both these project lunched in one emulator and no finger print configuration do on android security setting.

In  local_auth: ^0.6.3+2 project, default biometric dialog is appeared to send user to biometric configuration part but local_auth: ^1.1.4 project, I got just error.


 **All my problem is Why new local_auth plugin can't move the user to configuration biometric mobile part if did not set before like my video ?** yet.
And how can I fix the problem?

**Comment by darshankawar** [comment]
Issue verified on Samsung S10 and replicable using latest stable version which throws `Required security features not enabled` error on screen, as below:

<img width="328" alt="Screenshot 2021-04-13 at 1 33 41 PM" src="https://user-images.githubusercontent.com/67046386/114519157-beaf8e80-9c5d-11eb-92c2-064dab58cdcb.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.4 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision b1395592de (7 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)    

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

```

</details>

**Comment by nohli** [comment]
We have the same issue as in https://github.com/flutter/flutter/issues/80510

The PlatformException says `NotEnrolled` if there is no fingerprint registered. Should open settings.

**Comment by tazik561** [comment]
> prioritized

For this bug , I rollback my project into none sound null safety.  Unfortunately I didn't get any useful feedback from contributor.

**Comment by jobehi** [comment]
this is a major bug, could it be prioritised please ?

**Comment by Bunny1376** [comment]
same here! any update?

**Comment by kennethsancho** [comment]
I fixed this bug, changing this line in the AndroidManifest.xml.

 <activity
            android:name=".MainActivity"

Replace with:

<activity
            android:name="io.flutter.embedding.android.FlutterFragmentActivity"

**Comment by tazik561** [comment]
> I fixed this bug, changing this line in the AndroidManifest.xml.
> 
> <activity
> android:name=".MainActivity"
> 
> Replace with:
> 
> <activity
> android:name="io.flutter.embedding.android.FlutterFragmentActivity"

I still got error. Could you share your simple project ?

**Comment by TahaTesser** [comment]
I can confirm, on some device, it shows required security features not enabled and some devices `PlatformException(NotEnrolled, No biometrics enrolled on this device., null, null)`, instead of dialog

**Comment by sebastianbuechler** [comment]
> If there is no fingerprint registered, the PlatformException says `NotAvailable` on an Android emulator and `NotEnrolled` on a real device.
> 
> It should show a dialog for opening settings, instead it's doing nothing.
> 
> @TahaTesser since this is an important security feature and an official flutter.dev package, could this bug be prioritized?

I can confirm that this regression still exists. This is really bad for user experience and app stability.

**Comment by PeterWahba** [comment]
on Android Go to  : Settings => Security
Add fingerprint 
if you use emulator you can simulate finger touch from (fingerprint)

**Comment by tazik561** [comment]
> on Android Go to : Settings => Security
> Add fingerprint
> if you use emulator you can simulate finger touch from (fingerprint)

At previous versions(before null safety) , itself opened  fingerprint part

**Comment by PeterWahba** [comment]
> > on Android Go to : Settings => Security
> > Add fingerprint
> > if you use emulator you can simulate finger touch from (fingerprint)
> 
> At previous versions(before null safety) , itself opened fingerprint part

Here is work around : 
check if any biometrics enrolled on this device if not it will show settings to enroll biometrics, and setup PIN/Pattern/Pass if necessary.
using [open_settings](https://pub.dev/packages/open_settings) plugin 
https://pub.dev/packages/open_settings




```  
Future<void> authenticate() async {
    bool authenticated = false;
    if (await authenticateIsAvailable()) {
      try {
        authenticated = await auth.authenticate(
          localizedReason: 'Let OS determine authentication method',
          useErrorDialogs: true,
          biometricOnly: true,
        );
      } on PlatformException catch (e) {
        print(e);
        return;
      }
    } else {
      //   TODO OPEN SETTINGS;
      print(" Device Not Supported ");
      OpenSettings.openBiometricEnrollSetting();
    }
  }
```

```
  Future<bool> authenticateIsAvailable() async {
    final isAvailable = await auth.canCheckBiometrics;
    final isDeviceSupported = await auth.isDeviceSupported();
    return isAvailable && isDeviceSupported;
  }
```
note 
`  final LocalAuthentication auth = LocalAuthentication();
`

**Comment by Kukustar** [comment]
I find solution from this article https://medium.com/flutter-community/flutter-local-authentication-with-fingerprint-and-face-recognition-744d5d7f6c4

Author use get it library for using local_auth. Maybe it will useful for someone

**Comment by exaby73** [comment]
I have tested this on the latest stable and master versions on flutter along with `local_auth` version `2.0.2`. This issue seems to be fixed. I have tested on both a Java based project as well as a Kotlin based one. None throws any error and the authentication works as expected.

<details><summary>Code sample used</summary>

```dart
// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// ignore_for_file: public_member_api_docs

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:local_auth/local_auth.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final LocalAuthentication auth = LocalAuthentication();
  _SupportState _supportState = _SupportState.unknown;
  bool? _canCheckBiometrics;
  List<BiometricType>? _availableBiometrics;
  String _authorized = 'Not Authorized';
  bool _isAuthenticating = false;

  @override
  void initState() {
    super.initState();
    auth.isDeviceSupported().then(
          (bool isSupported) => setState(() => _supportState = isSupported
              ? _SupportState.supported
              : _SupportState.unsupported),
        );
  }

  Future<void> _checkBiometrics() async {
    late bool canCheckBiometrics;
    try {
      canCheckBiometrics = await auth.canCheckBiometrics;
    } on PlatformException catch (e) {
      canCheckBiometrics = false;
      print(e);
    }
    if (!mounted) {
      return;
    }

    setState(() {
      _canCheckBiometrics = canCheckBiometrics;
    });
  }

  Future<void> _getAvailableBiometrics() async {
    late List<BiometricType> availableBiometrics;
    try {
      availableBiometrics = await auth.getAvailableBiometrics();
    } on PlatformException catch (e) {
      availableBiometrics = <BiometricType>[];
      print(e);
    }
    if (!mounted) {
      return;
    }

    setState(() {
      _availableBiometrics = availableBiometrics;
    });
  }

  Future<void> _authenticate() async {
    bool authenticated = false;
    try {
      setState(() {
        _isAuthenticating = true;
        _authorized = 'Authenticating';
      });
      authenticated = await auth.authenticate(
        localizedReason: 'Let OS determine authentication method',
        options: const AuthenticationOptions(
          useErrorDialogs: true,
          stickyAuth: true,
        ),
      );
      setState(() {
        _isAuthenticating = false;
      });
    } on PlatformException catch (e) {
      print(e);
      setState(() {
        _isAuthenticating = false;
        _authorized = 'Error - ${e.message}';
      });
      return;
    }
    if (!mounted) {
      return;
    }

    setState(
        () => _authorized = authenticated ? 'Authorized' : 'Not Authorized');
  }

  Future<void> _authenticateWithBiometrics() async {
    bool authenticated = false;
    try {
      setState(() {
        _isAuthenticating = true;
        _authorized = 'Authenticating';
      });
      authenticated = await auth.authenticate(
        localizedReason:
            'Scan your fingerprint (or face or whatever) to authenticate',
        options: const AuthenticationOptions(
          useErrorDialogs: true,
          stickyAuth: true,
          biometricOnly: true,
        ),
      );
      setState(() {
        _isAuthenticating = false;
        _authorized = 'Authenticating';
      });
    } on PlatformException catch (e) {
      print(e);
      setState(() {
        _isAuthenticating = false;
        _authorized = 'Error - ${e.message}';
      });
      return;
    }
    if (!mounted) {
      return;
    }

    final String message = authenticated ? 'Authorized' : 'Not Authorized';
    setState(() {
      _authorized = message;
    });
  }

  Future<void> _cancelAuthentication() async {
    await auth.stopAuthentication();
    setState(() => _isAuthenticating = false);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Plugin example app'),
        ),
        body: ListView(
          padding: const EdgeInsets.only(top: 30),
          children: <Widget>[
            Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                if (_supportState == _SupportState.unknown)
                  const CircularProgressIndicator()
                else if (_supportState == _SupportState.supported)
                  const Text('This device is supported')
                else
                  const Text('This device is not supported'),
                const Divider(height: 100),
                Text('Can check biometrics: $_canCheckBiometrics\n'),
                ElevatedButton(
                  onPressed: _checkBiometrics,
                  child: const Text('Check biometrics'),
                ),
                const Divider(height: 100),
                Text('Available biometrics: $_availableBiometrics\n'),
                ElevatedButton(
                  onPressed: _getAvailableBiometrics,
                  child: const Text('Get available biometrics'),
                ),
                const Divider(height: 100),
                Text('Current State: $_authorized\n'),
                if (_isAuthenticating)
                  ElevatedButton(
                    onPressed: _cancelAuthentication,
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: const <Widget>[
                        Text('Cancel Authentication'),
                        Icon(Icons.cancel),
                      ],
                    ),
                  )
                else
                  Column(
                    children: <Widget>[
                      ElevatedButton(
                        onPressed: _authenticate,
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: const <Widget>[
                            Text('Authenticate'),
                            Icon(Icons.perm_device_information),
                          ],
                        ),
                      ),
                      ElevatedButton(
                        onPressed: _authenticateWithBiometrics,
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: <Widget>[
                            Text(_isAuthenticating
                                ? 'Cancel'
                                : 'Authenticate: biometrics only'),
                            const Icon(Icons.fingerprint),
                          ],
                        ),
                      ),
                    ],
                  ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

enum _SupportState {
  unknown,
  supported,
  unsupported,
}
```

</details>

<details><summary>Video</summary>

https://user-images.githubusercontent.com/50555895/167820834-bdac5e0c-3d0f-48bc-9d96-9159cb7bee77.mov

</details>

<details><summary><code>flutter doctor -v</code></summary>

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.1026, on macOS 12.3.1 21E258 darwin-arm, locale en-US)
    • Flutter version 2.13.0-0.0.pre.1026 at /Users/nabeelparkar/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c1b909e3fc (4 hours ago), 2022-05-10 22:49:08 -0700
    • Engine revision 70c5bdfa3b
    • Dart version 2.18.0 (build 2.18.0-103.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-32, build-tools 32.0.0-rc1
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /opt/homebrew/opt/openjdk@11/bin/java
    • Java version OpenJDK Runtime Environment Homebrew (build 11.0.15+0)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 67.0.4
    • Dart plugin version 221.5588

[✓] VS Code (version 1.67.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • V2050 (mobile)  • 3085425058000NM • android-arm64  • Android 12 (API 31)
    • macOS (desktop) • macos           • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome          • web-javascript • Brave Browser 101.1.38.111

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

### Device specifications
Vivo V21 5G - Android 12 (API 31)
