### ISSUE TITLE
Pub 0.0.21 -> 0.0.22 failure

### ISSUE THREAD

**Issue by xster** [flutter/flutter#8336]
Running flutter update-packages (or anything else that invokes pub like flutter run) triggers:

```
Running 'flutter packages get' in automated_tests...
The pubspec for flutter 0.0.21 from sdk has version 0.0.22.
pub get failed (65)
```

That package's pubspec.yaml says
```
name: flutter_automated_tests
dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
```

The pubspec.lock says
```
...
  flutter:
    description: flutter
    source: sdk
    version: "0.0.21"
...
```

Removing the like from pubspec.lock fixes it. 

```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/xster/development/flutter
    • Framework revision 72fa281f12 (48 minutes ago), 2017-02-22 11:32:22
    • Engine revision ab09530927
    • Tools Dart version 1.23.0-dev.0.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/xster/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1

[✓] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 2.14.1

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.10

[✓] Connected devices
    • Nexus 5 • 031462ee213e73b9 • android-arm • Android 6.0.1 (API 23)
```

**Comment by abarth** [comment]
You can work around this locally by running `flutter packages update`.  We should probably file a bug against `pub` to have looser locking behavior for sdk sources.

**Comment by yyoon** [comment]
I just ran into the same issue, and `flutter packages upgrade` (not `update`, BTW) solved the problem.

**Comment by abarth** [comment]
Oops, you're right./

**Comment by eseidelGoogle** [comment]
FYI @munificent

**Comment by xster** [comment]
`flutter packages upgrade` solves it partially. There's a bunch of flutter projects in the git root directory. One has to go to each one and flutter packages upgrade. Probably less of an issue for external users that just flutter creates one project.

**Comment by eseidelGoogle** [comment]
For flutter hackers there is a default-hidden command to upgrade everything `flutter update-packages --upgrade`

**Comment by xster** [comment]
That worked. Thanks!

Perhaps the AI here is just to automate and/or document a way to update when the flutter major/minor version changes? Or would this be handled in pub?

**Comment by abarth** [comment]
We should make this sort of change smoother, either in `pub` or in the `flutter` tool.  Let's start by talking with @munificent about whether he thinks the change should be in `pub`.

**Comment by abarth** [comment]
@munificent The underlying issue is as follows:

1. My package has an SDK dependency whose version gets written to the pubspec.lock file.
2. I update my SDK to a version that has a newer version of that package.
3. `pub get` gives me an error because it can't give me the version of the package that my pubspec.lock files says I should get (because it only has one choice---the one version in the SDK that doesn't match the pubspec.lock file).

**Comment by munificent** [comment]
@nex3 knows more about this than I do.

I think it's probably reasonable for `pub get` to unlock the SDK dependency if it doesn't match in the same way that it unlocks regular dependencies if you change the pubspec and run `pub get` again.

**Comment by nex3** [comment]
Yeah, this looks like a bug to me. Can you file an issue against `pub`?

**Comment by abarth** [comment]
Sure thing.

**Comment by abarth** [comment]
Done: https://github.com/dart-lang/pub/issues/1519

**Comment by eseidelGoogle** [comment]
I think we're going to need to either work around this somehow, or announce to users.  @Sfshaza also hit this this evening and was confused.

**Comment by abarth** [comment]
What workflow are people using when they run into this issue?  I understand how people on the Flutter team hit this issue because they manage their flutter.git directly, but if you follow our documented workflow and use `flutter upgrade` to update your Flutter SDK, you shouldn't hit this issue.

**Comment by eseidelGoogle** [comment]
@abarth that seems correct.  I just tried:

```
cd /src/flutter
git checkout -b old_version f9c2d7d9aa7af787ab06e44b5c507ac5ddfbf654
git branch --set-upstream-to=upstream/master
cd /tmp
flutter create foo
cd /tmp/foo
flutter packages get
flutter upgrade
```

And it successfully completed. So yes, this may only be an issue for flutter team members.

**Comment by yyoon** [comment]
People building flutter projects in fuchsia environment are all affected, since we don't use the `flutter upgrade` command. The flutter SDK is updated via `jiri update` command, which checks out the HEAD commit from GitHub.

Also, even when following the documented workflow using `flutter upgrade`, this issue still applies when multiple flutter projects are sharing the same flutter SDK installation.

(running `flutter upgrade` from one project, and then running `flutter packages get` from another project which already had `pubspec.lock` file would show the same error.)

**Comment by abarth** [comment]
Good point.

**Comment by xster** [comment]
This is perhaps a non-issue for external users. I may have triggered it by git pulling upstream master directly.

**Comment by abarth** [comment]
This was fixed in pub.
