### ISSUE TITLE
Error when building Flutter iOS project for simulator target: Module "path_provider" not found

### ISSUE THREAD

**Issue by TheColdVoid** [flutter/flutter#84386]
When I build a project with the "path_provider" plugin using Flutter, Xcode outputs the error that` Module "path_provider"` not found, which only appears in the build of the iOS simulator target, not in the build of the iOS physical machine target, and not in the build of the Android target
![image](https://user-images.githubusercontent.com/10008227/121600802-a4383c80-ca77-11eb-9ed0-7f2ca3fc1f48.png)

## Steps to Reproduce

1. Upgrade Flutter to lastest stable(2.2.1 02c026b) or master version
2. Downgrade Xcode to 11.x version and run `sudo xcode-select --switch path/to/Xcode-11.app` 
2. Use `flutter create` to create a project
3. Add `path_provider: ^2.0.2` to dependencies which in pubspec.yaml 
4. run pub get
5. open Xcode project and setup for siging
6. run `flutter run -d <iOS Simulator Deivce ID>` or use Xcode to run on iOS simulator

Minimal Working Example:https://github.com/TheColdVoid/flutter_issue_mwe

## Logs

flutter run -d <iOS Simulator ID> -v :
https://gist.github.com/TheColdVoid/677332022c5fd6223d44c121f519c672

flutter doctor -v:
https://gist.github.com/TheColdVoid/fdd4f3c8e937b6989d465d1fd2b9bb97

## Workarounds

I've tried all the workaround I found on Google, but none of them worked. Including but not limited to:
### 1.Clean cache
pub clean
flutter pub cache repair
rm -rf ~/flutter/.pub-cache
rm -rf ./Podfile ./Podfile.lock ./Pods
pod install 
pod install --clean-install
pod repo update
Delete Xcode DerivedData
Xcode clean build folder
Restart Xcode,Android Studio,my MacBook
Remove Flutter sdk and re-install it 
Upgrade Flutter to stable version or master version
re-install CocoaPods
re-install Xcode

### 2.Use Legacy Build System or New Build System
When I open ios/Runner.xcworkspace and build iOS simulator target via Xcode New Build System ,I will get some errors and warnings:
![image](https://user-images.githubusercontent.com/10008227/121600868-b914d000-ca77-11eb-8f04-92bebd583ed2.png)
![image](https://user-images.githubusercontent.com/10008227/121600878-bca85700-ca77-11eb-85b4-9e6d77a6513f.png)
so I modified the Exclude_Arch from `arm64 i386` to `i386`:
![image](https://user-images.githubusercontent.com/10008227/121600892-c03bde00-ca77-11eb-9498-648f870bbb57.png)

And then I bulit again.After re-building I got a  `ld: framework not found path_provider` error .
![image](https://user-images.githubusercontent.com/10008227/121600837-b023fe80-ca77-11eb-8a63-b4cffebce0a6.png)

When I open ios/Runner.xcworkproj and build iOS simulator target via Xcode Legacy Build System  ,I got a  `ld: framework not found path_provider` error too:
![image](https://user-images.githubusercontent.com/10008227/121600916-ccc03680-ca77-11eb-9c7c-b19927d97e4a.png)

Note that this build method can build an app that runs on a physical iPhone, but just not an app that runs on an iOS Simulator.

### 3.Manually add the plugin headers to the iOS source code folder
I put FLTPathProviderPlugin.h and FLTPathProviderPlugin.m which in the plugin's repo into iOS source code folder and add them to Xcode project,but it still doesn't make the build work, and the error is still outputed.

### 4.Other
I tried all the workarounds mentioned in #72069 #50607 #47833 #57923 #54657 #16360 #72371, but none of them worked

I would appreciate if the Flutter Team could assist me in solving this problem that has been bothering me for two days. Thank you very much! If there is any more information that I need to provide to help reproduce the problem, I am willing to provide it.

**Comment by TheColdVoid** [comment]
My MacBook OS is in the Mojave version and does not support XCode 12, so I can't try to upgrade XCode to 12.Sorry.

**Comment by TheColdVoid** [comment]
I tried all the workarounds mentioned in #72069 #50607 #47833 #57923 #54657 #16360 #72371, but none of them worked

**Comment by TahaTesser** [comment]
Hi @TheColdVoid 

> ## Steps to Reproduce
> 
> 
> 1. Upgrade flutter to lastest stable(2.2.1 02c026b) or master version
> 2. Use flutter create to create a project
> 3. Add `path_provider: ^2.0.2` to dependencies which in pubspec.yaml 
> 4. run pub get
> 5. open XCode project and setup for siging
> 6. run `flutter run -d <iOS Simulator Deivce ID>` or use XCode to run on iOS simulator


Following the steps, the app runs on simulator or physical (I even added the official sample for `path_provider`
Since you're running a completely different version of the OS and Xcode, the issue only exists on the simulator. Perhaps reset your simulators or delete create new ones, erase and start fresh and if possible clear all cache for Xcode itself and try again 


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale
    en-GB)
    • Flutter version 2.2.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 02c026b03c (2 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5154h
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • F0F01CEF-6AB8-4654-B53E-616A76808595 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 11.4 20F71 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 91.0.4472.77

• No issues found!
```

</details>

**Comment by TheColdVoid** [comment]
> Hi @TheColdVoid
> 
> > ## Steps to Reproduce
> > 
> > 1. Upgrade flutter to lastest stable(2.2.1 [02c026b](https://github.com/flutter/flutter/commit/02c026b03cd31dd3f867e5faeb7e104cce174c5f)) or master version
> > 2. Use flutter create to create a project
> > 3. Add `path_provider: ^2.0.2` to dependencies which in pubspec.yaml
> > 4. run pub get
> > 5. open XCode project and setup for siging
> > 6. run `flutter run -d <iOS Simulator Deivce ID>` or use XCode to run on iOS simulator
> 
> Following the steps, the app runs on simulator or physical (I even added the official sample for `path_provider`
> Since you're running a completely different version of the OS and Xcode, the issue only exists on the simulator. Perhaps reset your simulators or delete create new ones, erase and start fresh and if possible clear all cache for Xcode itself and try again
> 
> flutter doctor -v

Hi @TahaTesser ,
Thank you for your reply. I've tried resetting my simulator, I've tried different simulator (e.g. iPhone, iPad), I've  also tried downloading different iOS versions of the simulator runtime, I've tried clearing the entire Xcode cache, and I've even deleted all Xcode-related files and reinstalled Xcode, but unfortunately none of these methods solved the problem. This error occurs at the compile phase, so I have a feeling it may not be related to the simulator runtime.

**Comment by TheColdVoid** [comment]
I noticed that when I build with Xcode using the simulator as the target, there is no path_provider folder and no Pods_Runner.framework in the iphone simulator's products folder in Xcode's DerivedData directory(Xcode/DerivedData/Runner-…/Build/Products/Debug-iphonesimulator/).
![image](https://user-images.githubusercontent.com/10008227/121741486-305a6a80-cb31-11eb-8af0-f97aa8dbfaa8.png)
 Instead, when I build with the physical device as the target, the path_provider folder and Pods_Runner.framework exist in the products folder of the physical device(Xcode/DerivedData/Runner-…/Build/Products/Debug-iphoneos).
![image](https://user-images.githubusercontent.com/10008227/121741515-381a0f00-cb31-11eb-912d-d4973cee5b3d.png)

 That is, maybe there are no frameworks generated for the physical device when building with the iphonesimulator as the target. I don't understand the Xcode compile and build process, but I hope this will give you some insight to help me solve the problem.

**Comment by TheColdVoid** [comment]
When I downgraded the version of Flutter to 2.0.6, the problem was solved. This looks like it was caused by the new version of Flutter not being compatible with the lower version of Xcode. Now I'll have to settle for 2.0.6, with the many, many bugs that have been fixed in the new version.

**Comment by TahaTesser** [comment]
Hi @TheColdVoid 
Thanks for the details, I'm still unable to reproduce the issue on the latest `stable`

**Comment by TheColdVoid** [comment]
Hi @TahaTesser,Could you download an 11.x version of Xcode to reproduce this issue? This issue looks like it may only be reproduced with Flutter 2.1 and above when combined with Xcode versions below 12.

**Comment by tphuc012** [comment]
Same error on macos Big sur 11.3.1 and xcode 12.5. Please help :(
With "flutter run": everything is fine
With Xcode -> Archive or flutter build ipa: Module "path_provider" not found

**Comment by Alvaro-99** [comment]
@TahaTesser @TheColdVoid @tphuc012 Hello! I still have the same problem. I downgraded to Xcode 11.7, downgraded to Flutter version 2.0.4, downgraded to CocoaPods version 1.10.0, and I am now running on a iPhone 11 (iOS 13.7) simulator. And I still have the same problem: "fatal error: 'Flutter/Flutter.h' file not found; #import <Flutter/Flutter.h>". What should I do?

Also, after investigating the problem, the issue seems to come from 2 docs: "FLTPathProviderPlugin.h” (issue: “'Flutter/Flutter.h' file not found”) and “FLTPathProviderPlugin.m” (issue: “1. In file included from /Users/XnameX/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.2/ios/Classes/FLTPathProviderPlugin.m:5:”). Something that I noticed is that the folder “.pub-cache” does NOT seem to be in Users/XnameX/Desktop/flutter when I look for it in my Finder. What could it be?

**Comment by luokunman** [comment]
I had the same problem.
```
ld: framework not found path_provider

```dart
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.4 20F71 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.5.3 at /Users/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/jxmac001/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.57.1)
    • VS Code at /Users/jxmac001/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • iPhone (mobile) • a3036f74b765328c400fa4fbc3ccf74c238f5dd5 • ios            • iOS 14.7.1 18G82
    • Chrome (web)    • chrome

**Comment by zitob9** [comment]
> I had the same problem.

me too

**Comment by ashish12s3** [comment]
https://stackoverflow.com/questions/11390918/xcode-warning-directory-not-found-for-option

**Comment by camperdevmike** [comment]
I tried using the geolocator to get the current position, but Xcode (on M1 Mac/ arm64 ) was unable to detect the module. After some research, I simply changed the plugin and integrated the recommended pub locator. After that, however, the same error still occurs. This module is also not found.


````
↳
    objc[7998]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x1eab43130) and
    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1080f02c8). One of the two will be used. Which one is undefined.
    objc[7998]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x1eab43180) and
    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1080f0318). One of the two will be used. Which one is undefined.
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/campermike/Documents/projects/cnow/ios/Runner/GeneratedPluginRegistrant.m:18:9: fatal error: module 'location' not found
    @import location;
     ~~~~~~~^~~~~~~~
````
