### ISSUE TITLE
flutter run --no-sound-null-safety is not working 

### ISSUE THREAD

**Issue by Add00w** [flutter/flutter#84572]
flutter run --no-sound-null-safety is working for android but not working for ios.

Xcode's output:
↳
    Error: Cannot run with sound null safety, because the following dependencies
    don't support null safety:

     - package:go_sell_sdk_flutter
     - package:flushbar
     - package:smooth_star_rating
     - package:carousel_pro
     - package:geocoder

    For solutions, see https://dart.dev/go/unsound-null-safety

    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.

**Comment by darshankawar** [comment]
@Add00w 
If I understand the case correctly, you tried running `flutter run --no-sound-null-safety` on iOS, for which you received below error log:
```

Command PhaseScriptExecution failed with a nonzero exit code
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
```
Can you provide `flutter run --no-sound-null-safety --verbose` in properly formatted text ?

**Comment by Add00w** [comment]
> @Add00w
> If I understand the case correctly, you tried running `flutter run --no-sound-null-safety` on iOS, for which you received below error log:
> 
> ```
> 
> Command PhaseScriptExecution failed with a nonzero exit code
> note: Using new build system
> note: Building targets in parallel
> note: Planning build
> note: Constructing build description
> ```
> 
> Can you provide `flutter run --no-sound-null-safety --verbose` in properly formatted text ?

yes, you are right.

now when I run the command --verbose flag I got too much details which cant fit on here, what should I do?

**Comment by Riscait** [comment]
I'm having the same problem.
It happens with versions that include Flutter 2.2.2.
To work around this, you need to use Flutter 2.0.6.

**Comment by darshankawar** [comment]
@Add00w 
The log you shared is very difficult to read, since it's not formatted. Please put that in a text file and share it here.
Also, I tried to replicate the issue by adding `flushbar` dependency and then ran `flutter run` which by default runs with `sound null safety` and compiled properly. Same result using `--no-sound-null-safety` flag.

**Comment by Add00w** [comment]
> @Add00w
> The log you shared is very difficult to read, since it's not formatted. Please put that in a text file and share it here.
> Also, I tried to replicate the issue by adding `flushbar` dependency and then ran `flutter run` which by default runs with `sound null safety` and compiled properly. Same result using `--no-sound-null-safety` flag.

[no-null-safety-issue.txt](https://github.com/flutter/flutter/files/6662230/no-null-safety-issue.txt)

This is txt file 👆

**Comment by darshankawar** [comment]
@Add00w 
Can you provide `pubspec.yaml` ?

**Comment by Add00w** [comment]
> @Add00w
> Can you provide `pubspec.yaml` ?

<details>
<summary>pubspec.yaml</summary>
<pre><code>
analyzer:
  enable-experiment:
    - non-nullable

environment:
  sdk: ">=2.13.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  flushbar: ^1.10.4
  intl: any
  tuple: ^2.0.0
  dio: any
  http: ^0.13.1
  geocoder: ^0.2.1
  geolocator: ^7.0.1
  flutter_typeahead: ^3.1.3
  permission_handler: ^8.0.0+2
  autocomplete_textfield: ^1.7.3
  google_maps_webservice: ^0.0.20-nullsafety.5
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  http_interceptor: ^1.0.0
  expandable: ^5.0.1
  fluttertoast: ^8.0.7
  sliding_sheet: ^0.5.0
  after_layout: ^1.0.7+2
  google_maps_flutter: ^2.0.3
  carousel_slider: ^4.0.0-nullsafety.0
  smooth_star_rating: 1.1.1
#  carousel_pro: ^1.0.0
  cached_network_image: ^3.0.0
  location: ^4.1.1
  sticky_headers: ^0.2.0
  firebase_analytics: ^8.1.2
#  go_sell_sdk_flutter: ^2.0.3
  go_sell_sdk_flutter:
    git:
      url: https://github.com/Add00w/gosellSDK-Flutter.git
  table_calendar: ^3.0.0
  flutter_slidable: ^0.6.0
  flutter_pagewise: ^2.0.1
  pull_to_refresh: ^2.0.0
  firebase_messaging: ^10.0.0
  firebase_core: ^1.0.2
  flutter_local_notifications: ^6.0.0
  image_picker: ^0.8.0+3
  badges: ^2.0.1
  platform_device_id: ^1.0.1
  sentry_flutter: ^5.0.0
  connectivity: ^3.0.2
  package_info: ^2.0.2
  flutter_svg: ^0.22.0
  url_launcher: ^6.0.3
  day_night_time_picker: ^1.0.1
  store_redirect: ^2.0.0
  map_launcher: ^2.0.0
  add_2_calendar: ^2.0.2
  time: ^2.0.0
  firebase_performance: ^0.7.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # Adds code generation (synthetic package) support
  generate: true
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
    - assets/images/onboard/
    - assets/images/svg/
    - config/

  # list giving the asset and other descriptors for the font. For
  # example:
  #new fonts
  fonts:
    - family: aktiv_grotesk_trial_bold
      fonts:
        - asset: assets/fonts/aktiv_grotesk_trial_bold.ttf
    - family: aktiv_grotesk_trial_lite
      fonts:
        - asset: assets/fonts/aktiv_grotesk_trial_lite.ttf
  #
flutter_intl:
  enabled: true
</code></pre>
</details>

**Comment by darshankawar** [comment]
@Add00w 
Can you try by adding ` // @dart=2.9` at the top in your main.dart file and run the app using the Play ► icon

**Comment by Add00w** [comment]
> @Add00w
> Can you try by adding ` // @dart=2.9` at the top in your main.dart file and run the app using the Play ► icon
> 
> I used your pubspec.yaml in my sample app and ran it on iPhone 12 pro max simulator using `flutter run --no-sound-null-safety` command which ran properly for me, as below:
> 
> ```
> dhs@Dhss-MacBook-Pro macbug % flutter run --no-sound-null-safety 
> Running "flutter pub get" in macbug...                           1,890ms
> Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
> Running pod install...                                              8.6s
> Running Xcode build...                                                  
>  └─Compiling, linking and signing...                        17.8s
> Xcode build done.                                           82.4s
> Syncing files to device iPhone 12 Pro Max...                        66ms
> 
> Flutter run key commands.
> r Hot reload. 🔥🔥🔥
> R Hot restart.
> h Repeat this help message.
> d Detach (terminate "flutter run" but leave application running).
> c Clear the screen
> q Quit (terminate the application on the device).
> 
> Running with unsound null safety
> For more information see https://dart.dev/null-safety/unsound-null-safety
> ```

I get this error when I do that:
Error: Null safety features are disabled for this library.
    Try removing the `@dart=` annotation or setting the language version to 2.12 or higher.

**Comment by darshankawar** [comment]
@Add00w 
Ok, please ignore the `@dart` notation solution, your verbose log doesn't seem to contain the `Command PhaseScriptExecution failed with a nonzero exit code
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description` error block ?

And seem to have stopped after `Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:`, so can't really find the exact cause. Can you provide the failure part from the log here in comment ?

**Comment by Add00w** [comment]
> @Add00w
> Ok, please ignore the `@dart` notation solution, your verbose log doesn't seem to contain the `Command PhaseScriptExecution failed with a nonzero exit code note: Using new build system note: Building targets in parallel note: Planning build note: Constructing build description` error block ?
> 
> And seem to have stopped after `Error: Cannot run with sound null safety, because the following dependencies don't support null safety:`, so can't really find the exact cause. Can you provide the failure part from the log here in comment ?

do you mean this:
``` Xcode's output:
↳
    Error: Cannot run with sound null safety, because the following dependencies
    don't support null safety:

     - package:go_sell_sdk_flutter
     - package:sliding_sheet

    For solutions, see https://dart.dev/go/unsound-null-safety

    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

```

**Comment by darshankawar** [comment]
@Add00w 
Yes, does the log which consists above error, show any failures or other errors ? Usually it shows why the build failed. If you could find that from the log and share it, will be great.

**Comment by Add00w** [comment]
> @Add00w
> Yes, does the log which consists above error, show any failures or other errors ? Usually it shows why the build failed. If you could find that from the log and share it, will be great.

the problem is that `no-sound-null-safety` is not recognised and it giving me the following error `Cannot run with sound null safety`

**Comment by Riscait** [comment]
Could it be related or identical to this Issue?
https://github.com/flutter/flutter/issues/77912

**Comment by darshankawar** [comment]
Could very well be. Also, since the fix for 77912 was merged 11 days ago, it may only be available on latest master and not in stable yet. 

@Riscait @Add00w Please switch to latest master and try again to see if it resolves.

```
flutter channel master
flutter upgrade 
```

**Comment by Add00w** [comment]
> Could very well be. Also, since the fix for 77912 was merged 11 days ago, it may only be available on latest master and not in stable yet.
> 
> @Riscait @Add00w Please switch to latest master and try again to see if it resolves.
> 
> ```
> flutter channel master
> flutter upgrade 
> ```

bro even master is the same and I noticed when I run on iphone it downloads web sdk too I dont know why

```
Flutter is already up to date on channel master
Flutter 2.3.0-17.0.pre.444 • channel master • https://github.com/flutter/flutter.git
Framework • revision f451fe1514 (2 hours ago) • 2021-06-23 01:51:02 -0400
Engine • revision 12c25d03d3
Tools • Dart 2.14.0 (build 2.14.0-236.0.dev)
addow@Apples-iMac salon-frontend % flutter run --no-sound-null-safety
Downloading Web SDK...                                             51.6s
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running pod install...                                              8.7s
Running Xcode build...                                                  
Xcode build done.                                           34.6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    Error: Cannot run with sound null safety, because the following dependencies
    don't support null safety:

     - package:go_sell_sdk_flutter

    For solutions, see https://dart.dev/go/unsound-null-safety

    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max. ```

**Comment by Add00w** [comment]
> Could it be related or identical to this Issue?
> #77912

I saw this issue before I open this issue but unfortunately it is closed without the author saying the issue is solved  😢 and it seems like mine.

**Comment by darshankawar** [comment]
@Add00w 
I tried again on latest master by adding below plugins that you have and ran it on iOS which compiled and built properly without any issues:

```
dependencies:
  flutter:
    sdk: flutter
  flushbar: ^1.10.4
  smooth_star_rating: ^1.1.1
  carousel_pro: ^1.0.0
  geocoder: ^0.2.1

  js: ^0.6.3
  provider: ^5.0.0
  url_launcher: ^6.0.6
  animations: ^2.0.0
  image_picker: ^0.7.4
  flutter_markdown: ^0.6.2
#  quick_actions: ^0.6.0+1
#  flutter_image: ^3.0.0
  flutter_localizations:
    sdk: flutter
  video_player: ^2.1.1
#  http: ^0.13.1
  camera: ^0.8.1
```

```
dhs@Dhss-MacBook-Pro macbug % flutter run --no-sound-null-safety
Downloading ios tools...                                           12.2s
Downloading ios-profile tools...                                    9.6s
Downloading ios-release tools...                                   23.9s
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Upgrading AppFrameworkInfo.plist
Running pod install...                                           2,332ms
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         9.7s
Xcode build done.                                           37.0s
Syncing files to device iPhone 12 Pro Max...                        75ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

An Observatory debugger and profiler on iPhone 12 Pro Max is available at: http://127.0.0.1:51157/76wmdAS7ZiU=/
Activating Dart DevTools...                                         5.0s
The Flutter DevTools debugger and profiler on iPhone 12 Pro Max is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:51157/76wmdAS7ZiU=/
```

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel master, 2.3.0-17.0.pre.504, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-17.0.pre.504 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 102acbe39d (43 minutes ago), 2021-06-24 22:51:02 -0700
    • Engine revision 4bf9d638c2
    • Dart version 2.14.0 (build 2.14.0-245.0.dev)

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114

• No issues found!


```

</details>

Can you try one more time by removing the `package:go_sell_sdk_flutter` and see if you still see the same behavior ?

**Comment by Add00w** [comment]
> @Add00w
> I tried again on latest master by adding below plugins that you have and ran it on iOS which compiled and built properly without any issues:
> 
> ```
> dependencies:
>   flutter:
>     sdk: flutter
>   flushbar: ^1.10.4
>   smooth_star_rating: ^1.1.1
>   carousel_pro: ^1.0.0
>   geocoder: ^0.2.1
> 
>   js: ^0.6.3
>   provider: ^5.0.0
>   url_launcher: ^6.0.6
>   animations: ^2.0.0
>   image_picker: ^0.7.4
>   flutter_markdown: ^0.6.2
> #  quick_actions: ^0.6.0+1
> #  flutter_image: ^3.0.0
>   flutter_localizations:
>     sdk: flutter
>   video_player: ^2.1.1
> #  http: ^0.13.1
>   camera: ^0.8.1
> ```
> 
> ```
> dhs@Dhss-MacBook-Pro macbug % flutter run --no-sound-null-safety
> Downloading ios tools...                                           12.2s
> Downloading ios-profile tools...                                    9.6s
> Downloading ios-release tools...                                   23.9s
> Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
> Upgrading AppFrameworkInfo.plist
> Running pod install...                                           2,332ms
> Running Xcode build...                                                  
>  └─Compiling, linking and signing...                         9.7s
> Xcode build done.                                           37.0s
> Syncing files to device iPhone 12 Pro Max...                        75ms
> 
> Flutter run key commands.
> r Hot reload. 🔥🔥🔥
> R Hot restart.
> h List all available interactive commands.
> d Detach (terminate "flutter run" but leave application running).
> c Clear the screen
> q Quit (terminate the application on the device).
> 
> Running with unsound null safety
> For more information see https://dart.dev/null-safety/unsound-null-safety
> 
> An Observatory debugger and profiler on iPhone 12 Pro Max is available at: http://127.0.0.1:51157/76wmdAS7ZiU=/
> Activating Dart DevTools...                                         5.0s
> The Flutter DevTools debugger and profiler on iPhone 12 Pro Max is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:51157/76wmdAS7ZiU=/
> ```
> 
> flutter doctor -v
> Can you try one more time by removing the `package:go_sell_sdk_flutter` and see if you still see the same behavior ?

You are just adding to dependencies but not using may be that is the difference.
Unfortunately I can't remove it because it is very important package.

**Comment by darshankawar** [comment]
Keeping this issue open for further insights from team, as I am unable to replicate it.

A similar issue was fixed, https://github.com/flutter/flutter/issues/77912.

**Comment by Add00w** [comment]
> flutter run --no-sound-null-safety is working for android but not working for ios.
> 
> Xcode's output:
> ↳
> Error: Cannot run with sound null safety, because the following dependencies
> don't support null safety:
> 
> ```
>  - package:go_sell_sdk_flutter
>  - package:flushbar
>  - package:smooth_star_rating
>  - package:carousel_pro
>  - package:geocoder
> 
> For solutions, see https://dart.dev/go/unsound-null-safety
> 
> Command PhaseScriptExecution failed with a nonzero exit code
> note: Using new build system
> note: Building targets in parallel
> note: Planning build
> note: Constructing build description
> ```
> 
> Could not build the application for the simulator.
> Error launching application on iPhone 12 Pro Max.

**Comment by darshankawar** [comment]
@Add00w 
Did you close this by accident or intentionally ?

**Comment by Add00w** [comment]
> @Add00w
> Did you close this by accident or intentionally ?

Sorry It was accident even I don't know when it happened I won't close it because it is very important for me.

 I have an app in production now we are adding new features to it and I need a way to build for ios, I tried my best but didn't get solution even I checked the code changes [#77912](https://github.com/flutter/flutter/issues/77912) in my local machine and it was there but didn't fix the issue for me plz suggest any solutions.

**Comment by Den-Ree** [comment]
@Add00w I fixed it by doing on my local machine the same fix like here https://github.com/flutter/flutter/pull/84372/files

**Comment by lewcianci** [comment]
I fixed this on my build box with the following option:

`set EXTRA_FRONT_END_OPTIONS=--no-sound-null-safety`

Also, I love Flutter, but these kind of regressions are lame and break me for hours for no good reason. Again, there really should have been a test case for this particular issue.

**Comment by Add00w** [comment]
Hi @darshankawar  We solved our issue by replacing non-sound-null safety packages with another packages with null safety and forked some other packages to support null safety, if you want to close this issue you can but the issue may exist for other developers thanks.

**Comment by darshankawar** [comment]
Thanks for coming back with an update. Closing this based on above comment.
