### ISSUE TITLE
[Web][Canvaskit]: Setting ImageFilter.blur value to 0 throws `Expected a value of type 'SkDeletable', but got one of type 'Null'` error

### ISSUE THREAD

**Issue by Patrick386** [flutter/flutter#89433]
Has this problem been resolved?
The Chrome browser is the latest version.
If the value of the image filter is 0, an error occurs.

**Another exception was thrown: Expected a value of type 'SkDeletable', but got one of type 'Null'**

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.7 19H1323 darwin-x64, locale ko-KR)
    • Flutter version 2.2.3 at /Users/patrick386/Developer/flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/patrick386/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H1323 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.63

! Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment]
@Patrick386 
This issue was fixed recently on master, https://github.com/flutter/flutter/issues/86422
Please switch to latest master and try again to see if it works for you. It may not have reached on stable version yet.

```
flutter channel master
flutter upgrade
```

**Comment by Patrick386** [comment]
Same problem with the master version.


```
Another exception was thrown: Unexpected null value.
Another exception was thrown: Unexpected null value.
Another exception was thrown: A RenderFlex overflowed by 99760 pixels on the right.
Another exception was thrown: A RenderFlex overflowed by 99802 pixels on the right.
BlockHeight:0
Another exception was thrown: Expected a value of type 'SkDeletable', but got one of type 'Null'
BlockHeight:0
Another exception was thrown: Expected a value of type 'SkDeletable', but got one of type 'Null'
BlockHeight:0
Another exception was thrown: Expected a value of type 'SkDeletable', but got one of type 'Null'
BlockHeight:0
Another exception was thrown: Expected a value of type 'SkDeletable', but got one of type 'Null'
BlockHeight:0
Another exception was thrown: Expected a value of type 'SkDeletable', but got one of type 'Null'
BlockHeight:0
Another exception was thrown: Expected a value of type 'SkDeletable', but got one of type 'Null'
BlockHeight:0
Another exception was thrown: Expected a value of type 'SkDeletable', but got one of type 'Null'
BlockHeight:0
Another exception was thrown: Expected a value of type 'SkDeletable', but got one of type 'Null'
BlockHeight:0
Another exception was thrown: Expected a value of type 'SkDeletable', but got one of type 'Null'
BlockHeight:0
Another exception was thrown: Expected a value of type 'SkDeletable', but got one of type 'Null'
BlockHeight:0
Another exception was thrown: Expected a value of type 'SkDeletable', but got one of type 'Null'
BlockHeight:0
Another exception was thrown: Expected a value of type 'SkDeletable', but got one of type 'Null'
BlockHeight:0
Another exception was thrown: Expected a value of type 'SkDeletable', but got one of type 'Null'
BlockHeight:0
Another exception was thrown: Expected a value of type 'SkDeletable', but got one of type 'Null'
BlockHeight:0
Another exception was thrown: Expected a value of type 'SkDeletable', but got one of type 'Null'
BlockHeight:0
Another exception was thrown: Expected a value of type 'SkDeletable', but got one of type 'Null'
BlockHeight:0
Another exception was thrown: Expected a value of type 'SkDeletable', but got one of type 'Null'
BlockHeight:0
Another exception was thrown: Expected a value of type 'SkDeletable', but got one of type 'Null'
BlockHeight:0
Another exception was thrown: Expected a value of type 'SkDeletable', but got one of type 'Null'
BlockHeight:0
Another exception was thrown: Expected a value of type 'SkDeletable', but got one of type 'Null'
BlockHeight:0
Another exception was thrown: Expected a value of type 'SkDeletable', but got one of type 'Null'
BlockHeight:0
Another exception was thrown: Expected a value of type 'SkDeletable', but got one of type 'Null'
BlockHeight:0
Another exception was thrown: Expected a value of type 'SkDeletable', but got one of type 'Null'
Application finished.

C:\Dev\Projects\slp_console>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 2.6.0-1.0.pre.193, on Microsoft Windows [Version 10.0.19042.1165], locale ko-KR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.4)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.52.1)
[√] Connected device (3 available)

• No issues found!
```

**Comment by darshankawar** [comment]
> If the value of the image filter is 0, an error occurs.

Can you please provide a minimal code sample ?

**Comment by Patrick386** [comment]
Sample Code:

```
![2021-09-07_154158](https://user-images.githubusercontent.com/49754877/132296905-3a11be70-ab08-4cf2-83ae-7b317cff1d48.png)

import 'dart:ui';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class ImageFilterTest extends StatefulWidget {
  const ImageFilterTest({Key? key}) : super(key: key);

  @override
  _ImageFilterTestState createState() => _ImageFilterTestState();
}

class _ImageFilterTestState extends State<ImageFilterTest> {

  @override
  Widget build(BuildContext context) {


    return ConstrainedBox(
      constraints: BoxConstraints(
        minHeight: 200
      ),
      child: Container(
          padding: EdgeInsets.all(10),
          alignment: Alignment.centerLeft,

          decoration: BoxDecoration(
            color: Colors.blueAccent,
            image: DecorationImage(

                fit: BoxFit.cover,
                image: NetworkImage('https://source.unsplash.com/category/fashion/900x600'),
                colorFilter: ColorFilter.mode(
                    Colors.black.withOpacity(0.1),
                    BlendMode.srcOver)),
          ),


//todo Error: Expected a value of type 'SkDeletable', but got one of type 'Null'
          child: BackdropFilter(
            filter: ImageFilter.blur(
                sigmaX: 0.0, //<<<<---- 0.01 no error
                sigmaY: 0.0), //<<<---- 0.01 no error


            child: LayoutBuilder(
              builder: (context, contstraints) {
                return ConstrainedBox(
                    constraints: BoxConstraints(
                      minHeight: 200,
                      maxWidth: 400,
                    ),
                    child: Image.network('https://source.unsplash.com/category/fashion/900x600'));
              },
            ),
          )),
    );
  }

}
```

**Comment by darshankawar** [comment]
Thanks. I see the same behavior running on latest master with canvaskit rendering.

<img width="554" alt="Screenshot 2021-09-07 at 12 23 40 PM" src="https://user-images.githubusercontent.com/67046386/132298219-04e78f59-c5f0-4237-8f28-96df7abdc16f.png">

A similar issue was fixed and merged, https://github.com/flutter/flutter/issues/86422

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.3 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision f4abaa0735 (4 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • iPhone 12 Pro Max (mobile)                     •
      A5473606-0213-4FD8-BA16-553433949729 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • iPad Pro (12.9-inch) (4th generation) (mobile) •
      AD9F1B85-B622-485E-97E8-E4AC866D5770 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)                                • macos
      • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                                   • chrome
      • web-javascript • Google Chrome 92.0.4515.159


• No issues found!

[✓] Flutter (Channel master, 2.6.0-1.0.pre.193, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.6.0-1.0.pre.193 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0c5431d99c (4 hours ago), 2021-09-05 22:31:02 -0400
    • Engine revision b9c633900e
    • Dart version 2.15.0 (build 2.15.0-82.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • iPhone 12 Pro Max (mobile)                     •
      A5473606-0213-4FD8-BA16-553433949729 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • iPad Pro (12.9-inch) (4th generation) (mobile) •
      AD9F1B85-B622-485E-97E8-E4AC866D5770 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)                                • macos
      • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                                   • chrome
      • web-javascript • Google Chrome 92.0.4515.159


• No issues found!




```

</details>

/cc: @yjbanov

**Comment by Patrick386** [comment]
Web Canvaskit:

![2021-09-07_160058](https://user-images.githubusercontent.com/49754877/132299288-74c87911-a200-47ee-a1a4-d2cc8b9d3724.png)

**Comment by hterkelsen** [comment]
The problem has been fixed in the master branch: https://github.com/flutter/engine/pull/27710

I can add it to the list of PRs for the next stable hot patch.

**Comment by paynekw** [comment]
Still not fixed in `master`...

```
[✓] Flutter (Channel master, 2.10.0-1.0.pre.355, on Microsoft Windows [Version 10.0.19043.1466], locale en-GI)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.0 Preview 4.0)
    ✗ Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[✓] Android Studio (version 3.6)
[✓] Android Studio (version 2021.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```
```
======== Exception caught by widgets library =======================================================
The following TypeErrorImpl was thrown building Builder(dirty):
Expected a value of type 'SkDeletable', but got one of type 'Null'
```
```
ImageFiltered(
    child: Text(
        _totalAvailableBalance
    ),
    imageFilter: ImageFilter.blur(
        sigmaX: _balancesVisible ? 0 : 2.5,
        sigmaY: _balancesVisible ? 0 : 2.5 
    )
)
```

**Comment by hterkelsen** [comment]
I don't see an error when using `ImageFilter.blur` with `sigmaX` and `sigmaY` set to `0`, but I do see an exception when using `ColorFilter.mode` with `Colors.black.withOpacity(0)`

**Comment by kyl3r92** [comment]
BackdropFilter ui.ImageFilter.blur crashes on web

This code works fine on android:

```
return BackdropFilter(
      filter: ui.ImageFilter.blur(
      sigmaX: _expandAnimation.value * 6.0,
      sigmaY: _expandAnimation.value * 6.0,
      ),
      child: [...]
```

But it crashes on web with this log:

Expected a value of type 'JavaScriptObject', but got one of type 'Null'
Note: Setting sigmaX and sigmaY to 0 still crashes.

```
The relevant error-causing widget was: 
  ExpandableFab ExpandableFab:file:///C:/Users/USERNAME/AndroidStudio/PROJECT_NAME/lib/expandable_floating_action_button.dart:16:12
When the exception was thrown, this was the stack: 
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 99:3        castError
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 452:10  cast
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/classes.dart 635:14     as_C
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_shared/lib/js_util_patch.dart 80:3                      callMethod$
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/canvaskit_api.dart 1165:26           SkImageFilterNamespaceExtension.MakeBlur
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/image_filter.dart 102:34             [_initSkiaObject]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/image_filter.dart 43:36              createDefault
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/skia_object_cache.dart 222:41        new
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/image_filter.dart 35:3               __
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/image_filter.dart 81:15              new
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/ui/painting.dart 402:35                                       blur
packages/ultimatedrinkinggame/expandable_floating_action_button.dart 82:30  
```

Happens on Flutter 3.3.2 and 3.3.3 (I just upgraded and tried again)

Flutter Doctor (1 Issue, unrelated to this problem):

```
[√] Flutter (Channel stable, 3.3.3, on Microsoft Windows [Version 10.0.19044.2006], locale de-DE)
    • Flutter version 3.3.3 on channel stable at C:\Users\kaifo\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (3 days ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\kaifo\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31402.337
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (4 available)
    • DN2103 (mobile)   • U8NRBMLNXWM7FAY9 • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19044.2006]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 105.0.5195.127
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 105.0.1343.53

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
