### ISSUE TITLE
A black layer shows when launch a translucent Activity and turn it back to foreground

### ISSUE THREAD

**Issue by Iridescentangle** [flutter/flutter#89957]
## Steps to Reproduce

- start App and press the FloatingActionButton in [Flutter Demo Home Page]    -> App will launch a half translucent Android Activity.
- Get app into background  or  just switch your recent apps. Then switch app to the foreground.

**Expected results:** 

The screen will show the same as before.

**Actual results:** 

The Translucent Android Activity shows correctly , but the Flutter content is covered by a black layer.

BTW, when I press back button, the activity finished and the black layer disappeared either.

**More Info**

The problem happened when I'm using GoogleBilling . This is also a common scene that my application calls GoogleBilling SDK ,and the latter will launch a translucent interface for paying.In this moment ,I turn my app into background and then turn it back (It is nothing to do with the length of time), my flutter page looks like being covered by a black layer.just like this
![](https://s3.bmp.ovh/imgs/2021/09/f7b8378be4e14ee0.png)

To reproduce this bug , all you need to do is just provide the ability to launch **a translucent Native Android Activity**(Not Dialog or Popup) for your flutter application,launch it and switch the app between foreground and background

<details>
  <summary>Logs</summary>

```
flutter analyze
Analyzing bug...                                                        

   info • The declaration '_incrementCounter' isn't referenced • lib/main.dart:52:8 • unused_element

1 issue found. (ran in 1.9s)
```

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.2.3 at /Users/zhangduan/Documents/flutter
    • Framework revision f4abaa0735 (2 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/zhangduan/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio的副本.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.159

! Doctor found issues in 2 categories.
```

</details>

**Comment by maheshmnj** [comment]
Hi @Iridescentangle, Thanks for filing the issue. Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue.

Thanks

**Comment by Iridescentangle** [comment]
@maheshmnj This is a sample demo for reproducing this bug

Flutter:

main.dart

``` dart
class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  late MethodChannel _channel;

  @override
  void initState() {
    super.initState();
    _channel = MethodChannel('translucent_activity_channel');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _startTranslucentActivity,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }

  void _startTranslucentActivity() async {
    _channel.invokeMethod('startTranslucentActivity');
  }
}
```

Android part:

MainActivity.kt

``` kotlin
package com.example.bug

import android.content.Intent
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodCall
import io.flutter.plugin.common.MethodChannel

class MainActivity: FlutterActivity(),MethodChannel.MethodCallHandler {
    val CHANNEL = "translucent_activity_channel"
    lateinit var methodChannel: MethodChannel
    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        methodChannel = MethodChannel(flutterEngine.dartExecutor, CHANNEL)
        methodChannel.setMethodCallHandler(this)
         
    }
    override fun onMethodCall(call: MethodCall, result: MethodChannel.Result) {
        when(call.method){
            "startTranslucentActivity"->{
                startActivity(Intent(this, TranslucentActivity::class.java))
            }
        }
    }
}

```

TransparentActivity.kt

``` kotlin
package com.example.bug

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import com.example.bug.R

class TranslucentActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_transparent)
    }
}
```

activity_translucent.xml

``` xml
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".TranslucentActivity">
    <LinearLayout
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginBottom="40dp"
        android:layout_marginLeft="18dp"
        android:layout_marginRight="18dp"
        android:orientation="vertical" >

        <TextView
            android:id="@+id/tv_delete"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="#F00"
            android:gravity="center"
            android:paddingBottom="15dp"
            android:paddingTop="15dp"
            android:text="delete"
            android:textColor="#FFFFFF"
            android:textSize="20sp" />

        <TextView
            android:id="@+id/tv_cancel"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="20dp"
            android:background="#7F7F7F"
            android:gravity="center"
            android:paddingBottom="15dp"
            android:paddingTop="15dp"
            android:text="cancel"
            android:textColor="#FFFFFF"
            android:textSize="20sp" />
    </LinearLayout>

</androidx.constraintlayout.widget.ConstraintLayout>
```

AndroidManifest.xml

``` xml
<activity android:name=".TranslucentActivity"
            android:theme="@style/ActivityTranslucent"/>
```

res/values/style.xml

``` xml
<style name="ActivityTranslucent" parent="Theme.AppCompat.Light">
  			<!--the background color has to be translucent-->
        <item name="android:windowBackground">#50000000</item>
        <item name="android:windowIsTranslucent">true</item>
        <item name="android:windowNoTitle">true</item>
        <item name="android:windowAnimationStyle">@null</item>
    </style>
```

Thank you for helping me address this problem ^_^

**Comment by Iridescentangle** [comment]
@maheshmnj Yes... As my understanding , it is incorrect for this interact scene . What the user did is just switching the application to background and then turn it back , the black layer should not appear . I found out that these people met the same problem in #59552
One developer mentioned that you can take a screenshot when onPause and show it , and remove it when onResume [https://github.com/flutter/flutter/issues/59552#issuecomment-737767770](url)
But I think it is not necessary and I tried this.
``` kotlin
override fun getBackgroundMode(): FlutterActivityLaunchConfigs.BackgroundMode {
    return BackgroundMode.transparent
}
```
↑This really work for me in 
Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-arm, local zh-Hans-CN)

Maybe it's just a misunderstanding , and for me it was solved by overriding a method in my FlutterActivity , but I also hope it be fixed in new stable version :) thank you dude!

**Comment by chinmaygarde** [comment]
cc @blasten

**Comment by muccy** [comment]
I used this override a lot in the past but, today, as I was releasing updating using Flutter 2.5, I've tested a strange issue on my old Moto E4: sometimes, not everytime, the screen turns black after the native splash layout. This happens only in release mode. I still see Dart `print` statements emit proper messages, but nothing on screen

**Comment by shubhral** [comment]
I have a translucent activity that had the black background issue when the activity was resumed from background, and like others have mentioned, I resolved it by overriding getBackgrounndMode() like this - 
```
override fun getBackgroundMode(): FlutterActivityLaunchConfigs.BackgroundMode {
        return FlutterActivityLaunchConfigs.BackgroundMode.transparent
    }
```
This was working fine till now. But now after updating to **Flutter 2.5**, it was required that we have to remove **SplashScreenDrawable** from the AndroidManifest since it has been deprecated, but after removing it, we start seeing this Black screen when the app is launched as also mentioned by @muccy above. So it seems like if we remove the SplashScreenDrawable from Manifest, Flutter is defaulting to showing some black screen. 

Kindly let us know a resolution to this. 🙏

**Comment by Iridescentangle** [comment]
> I have a translucent activity that had the black background issue when the activity was resumed from background, and like others have mentioned, I resolved it by overriding getBackgrounndMode() like this -
> 
> ```
> override fun getBackgroundMode(): FlutterActivityLaunchConfigs.BackgroundMode {
>         return FlutterActivityLaunchConfigs.BackgroundMode.transparent
>     }
> ```
> 
> This was working fine till now. But now after updating to **Flutter 2.5**, it was required that we have to remove **SplashScreenDrawable** from the AndroidManifest since it has been deprecated, but after removing it, we start seeing this Black screen when the app is launched as also mentioned by @muccy above. So it seems like if we remove the SplashScreenDrawable from Manifest, Flutter is defaulting to showing some black screen.
> 
> What's interesting to know is that if I don't override the **getBackgroundMode()** method, then the above Black screen issue at app launch doesn't occur, but then it leads to the original black screen issue when the app is resumed from background as confirmed by @maheshmnj above. So it's like if you try to solve one, you get the other issue.
> 
> Kindly let us know a resolution to this. 🙏

Have you updated the flutter version that your project relied on to 2.5 ? Or just updated your local Flutter SDK ? I'm considering updating my local Flutter SDK ...

**Comment by luojt** [comment]
Same issue. Open the app, and then cut into the Android background. After a period of time, open it again, and the app has a probability of black screen; Another interesting phenomenon is that if there are two pages, we open the first and then the second, and then the app cuts into the background. After a period of time, when it is opened again, the screen will be black. Click the physical return key, and the first page will be displayed normally.

**Comment by llgoer** [comment]
Same issue +1

**Comment by luisjavierglb** [comment]
Same issue +1

**Comment by zhancheng** [comment]
same issue +1

**Comment by Stage18** [comment]
同样的问题 +1

**Comment by Stage18** [comment]
same issue + 1

flutter doctor -v
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.0.1 21A559 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.10.1 at /Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (11 天前), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/xs/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.35.20220201

[!] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1
    • NO_PROXY contains localhost
    • NO_PROXY contains 127.0.0.1
    ! NO_PROXY does not contain ::1

[✓] Connected device (3 available)
    • M2011K2C (mobile) • 556178c5                  • android-arm64  • Android 11 (API 30)
    • Xs  (mobile)      • 00008030-001058822600802E • ios            • iOS 15.2.1 19C63
    • Chrome (web)      • chrome                    • web-javascript • Google Chrome 98.0.4758.102
    ! Error: Xs  is busy: Preparing the watch for development via Xs . Xcode will continue when Xs  is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by saurabhK002** [comment]
facing same issue  +1

**Comment by ZRXXUAN** [comment]
same issue +1

**Comment by visitorvisit** [comment]
same issue +1

**Comment by maheshmnj** [comment]
Everyone who is affected by this issue please upvote 👍🏻 the original issue report https://github.com/flutter/flutter/issues/89957#issue-994404744. The number of upvotes helps the flutter team in prioritizing the issue.
