### ISSUE TITLE
Chrome crashes when starting Flutter Web app in debug mode with breakpoints set

### ISSUE THREAD

**Issue by obeobe** [flutter/flutter#90844]
# Chrome crashes when starting Flutter Web app in debug mode with breakpoints set

## Steps to Reproduce

1. Create the Flutter Counter demo project.
2. Add many breakpoints. I added 26 breakpoints:
<details> 
<summary>Screenshot</summary> 

![image](https://user-images.githubusercontent.com/1394039/135003019-bb663480-0ca7-4cdd-b0ad-e48e9d5b3ee0.png)

</details>

3. Start the program in Chrome, in debug mode: (I only tried this with Android Studio and IntelliJ).
![image](https://user-images.githubusercontent.com/1394039/135003166-9f59629b-588e-4b01-b6d4-32efcf256a9f.png)

**Expected results:**
The program starts in Chrome.

**Actual results:**
4. Chrome will likely crash with an "Aw, Snap!" message, with error code "SIGILL".
5. If I refresh the browser - I will likely get it again. And again. And again.
6. Eventually, the page will load correctly. From that point on - it will keep loading correctly with additional refreshes, until I close it and start again.
7. The more breakpoints I add - the more likely it is to crash when it's opened, and the more times I need to refresh the page afterwards until it starts to work.

Note: this issue is not new for the recent Flutter version; I've had it since I started using Flutter, several months ago.

<details>
  <summary>Logs</summary>

```
[  +62 ms] executing: uname -m
[  +31 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +5 ms] executing: [/home/user/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +8 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] ffb2ecea5223acdd139a5039be2f9c796962833d
[        ] executing: [/home/user/flutter/] git tag --points-at ffb2ecea5223acdd139a5039be2f9c796962833d
[  +11 ms] Exit code 0 from: git tag --points-at ffb2ecea5223acdd139a5039be2f9c796962833d
[        ] 2.5.1
[   +6 ms] executing: [/home/user/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/user/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +77 ms] executing: [/home/user/flutter/] git rev-parse --abbrev-ref HEAD
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +54 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +59 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +64 ms] Skipping pub get: version match.
[  +93 ms] Generating /home/user/tmp/2021-09-27.2/test5/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[{"event":"daemon.connected","params":{"version":"0.6.1","pid":826353}}]
[{"event":"app.start","params":{"appId":"d208f67c-74c5-4061-8d19-4221950063a9","deviceId":"chrome","directory":"/home/user/tmp/2021-09-27.2/test5","supportsRestart":true,"launchMode":"run"}}]
[ +126 ms] Launching lib/main.dart on Chrome in debug mode...
[  +82 ms] Updating assets
Waiting for connection from debug service on Chrome...
[{"event":"app.progress","params":{"appId":"d208f67c-74c5-4061-8d19-4221950063a9","id":"0","progressId":null,"message":"Waiting for connection from debug service on Chrome...","finished":false}}]
[ +101 ms] <- reset
[   +6 ms] /home/user/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/user/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /home/user/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -Dflutter.inspector.structuredErrors=true -DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.OSANXP/flutter_tool.UHCLXC/app.dill --libraries-spec file:///home/user/flutter/bin/cache/flutter_web_sdk/libraries.json --packages /home/user/tmp/2021-09-27.2/test5/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root /tmp/flutter_tools.OSANXP/flutter_tools.WHXMXX --filesystem-scheme org-dartlang-app --initialize-from-dill build/9da3ff2a5297e0c47025236ff84e71f4.cache.dill.track.dill --platform file:///home/user/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[  +11 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[{"event":"app.progress","params":{"appId":"d208f67c-74c5-4061-8d19-4221950063a9","id":"0","progressId":null,"finished":true}}]
[+12927 ms] Synced 26.2MB.
[        ] <- accept
[        ] Caching compiled dill
[ +102 ms] Using Google Chrome 94.0.4606.54 

[  +33 ms] executing: uname -m
[   +9 ms] Exit code 0 from: uname -m
[        ] x86_64
[ +155 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on ws://127.0.0.1:37385/devtools/browser/175a7ad5-c7ee-4c17-b390-5f475bba1593
[{"event":"app.webLaunchUrl","params":{"url":"http://localhost:37229","launched":true}}]
[ +308 ms] DwdsInjector: Received request for entrypoint at http://localhost:37229/main_module.bootstrap.js
[   +6 ms] MetadataProvider: Loading debug metadata...
[  +18 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[   +4 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:37229/main_module.bootstrap.js
[+1926 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[  +65 ms] DevHandler: Debug service listening on ws://127.0.0.1:43725/LbsTbcQwKa4=/ws

[  +19 ms] This app is linked to the debug service: ws://127.0.0.1:43725/LbsTbcQwKa4=/ws
[   +5 ms] Debug service listening on ws://127.0.0.1:43725/LbsTbcQwKa4=/ws
[        ] 💪 Running with sound null safety 💪
[{"event":"app.started","params":{"appId":"d208f67c-74c5-4061-8d19-4221950063a9"}}]
Debug service listening on ws://127.0.0.1:43725/LbsTbcQwKa4=/ws
[{"event":"app.debugPort","params":{"appId":"d208f67c-74c5-4061-8d19-4221950063a9","port":43725,"wsUri":"ws://127.0.0.1:43725/LbsTbcQwKa4=/ws"}}]
```

```
user@ubuntu:~/tmp/2021-09-27.2/test5 $ flutter analyze
Analyzing test5...
No issues found! (ran in 1.0s)
```

```
[✓] Flutter (Channel stable, 2.5.1, on Ubuntu 20.04.1 LTS 5.8.0-59-generic, locale en_US.UTF-8)
• Flutter version 2.5.1 at /home/user/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision ffb2ecea52 (10 days ago), 2021-09-17 15:26:33 -0400
• Engine revision b3af521a05
• Dart version 2.14.2
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
• Android SDK at /home/user/Android/Sdk
✗ cmdline-tools component is missing
Run `path/to/sdkmanager --install "cmdline-tools;latest"`
See https://developer.android.com/studio/command-line for more details.
✗ Android license status unknown.
Run `flutter doctor --android-licenses` to accept the SDK licenses.
See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[✓] Chrome - develop for the web
• CHROME_EXECUTABLE = /usr/bin/google-chrome
[✓] Linux toolchain - develop for Linux desktop
• clang version 10.0.0-4ubuntu1
• cmake version 3.16.3
• ninja version 1.10.0
• pkg-config version 0.29.1
[✓] Android Studio (version 4.2)
• Android Studio at /home/user/Downloads/android-studio
• Flutter plugin version 58.0.1
• Dart plugin version 202.8488
• Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
• IntelliJ at /snap/intellij-idea-ultimate/253
• Flutter plugin version 59.0.1
• Dart plugin version 202.8531
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
• IntelliJ at /home/user/Downloads/ideaIU-2021.2.1/idea-IU-212.5080.55
• Flutter plugin version 60.1.4
• Dart plugin version 212.5080.8
[✓] Connected device (2 available)
• Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.1 LTS 5.8.0-59-generic
• Chrome (web)    • chrome • web-javascript • Google Chrome 94.0.4606.54
! Doctor found issues in 1 category.
```

</details>

**Comment by maheshmnj** [comment]
Hi @obeobe Thanks for filing the issue, I can reproduce the issue on the latest `stable 2.5.1` and the latest master `2.6.0-12.0.pre.98` The issue also reproduces when debugging from vscode.

![image](https://user-images.githubusercontent.com/31410839/135086361-f1602604-dcaf-4d6f-80e3-a466c4a35da7.png)


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.98, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.98 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 48e6758fb5 (35 hours ago), 2021-09-26 21:28:03 -0400
    • Engine revision 65ad5a4836
    • Dart version 2.15.0 (build 2.15.0-150.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 94.0.4606.61

• No issues found!

```

```
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.5.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (11 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B622CBB7-F906-4FA7-8F49-FACEAAC905AB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 94.0.4606.61

• No issues found!

```
</details>

**Comment by semsturgut** [comment]
I have to run `flutter clean` to be able to run the project again. 

It's happening when I refresh the page or re-run it from scratch without `flutter clean`.

Current Flutter version: Channel stable, 2.2.3


<details><summary>flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.6 20G165 darwin-arm, locale en-TR)
    • Flutter version 2.2.3 at /Users/semsturgut/flutter
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/semsturgut/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Zulu11.48+21-CA (build 11.0.11+9-LTS)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2021.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 59.0.3
    • Dart plugin version 211.7727

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 94.0.4606.61

! Doctor found issues in 1 category.
```

</p>
</details>

**Comment by dev-mush** [comment]
I am experiencing chrome crashes all of a sudden, probably after chrome update that was released on 24 september, am I the only one?

**Comment by obeobe** [comment]
(just to re-iterate - the issue I reported used to already happen to me consistently months ago, so random new crashes might be a separate problem)

**Comment by mdrideout** [comment]
Similar to my issue (same crash in Chrome for Flutter Web Debug Mode) but in different circumstances: https://github.com/flutter/flutter/issues/91008

**Comment by annagrin** [comment]
I cannot repro this on current master:

Flutter 2.6.0-12.0.pre.159 • channel master • git@github.com:annagrin/flutter.git
Framework • revision c48c428e46 (5 hours ago) • 2021-09-30 12:23:55 -0700
Engine • revision e83795a0a7
Tools • Dart 2.15.0 (build 2.15.0-166.0.dev)

It also looks like the issue I fixed before:

issue: https://github.com/Dart-Code/Dart-Code/issues/3518
fix: https://github.com/dart-lang/webdev/pull/1384

It was rolled to flutter at: https://github.com/flutter/flutter/commit/cd112e551c6a49434e30bd375e28144ab739c7a3 
So it looks like it should be working on the latest master and 2.6.0-11.0.pre

@maheshmnj would you be able to try it again on the latest master?

@semsturgut @dev-mush  your issues seem to be a different one and each other, would you be able to open a separate issue for that?

**Comment by maheshmnj** [comment]
> @maheshmnj would you be able to try it again on the latest master? 

Sure

**Comment by maheshmnj** [comment]
@annagrin I upgraded to the latest master `2.6.0-12.0.pre.165` and I could still reproduce the issue but it was very less frequent and intermittent, I could not find any pattern but I was able to reproduce the issue when refreshing the browser.


https://user-images.githubusercontent.com/31410839/135571044-96462c7c-71b6-490b-a5e6-348a87d3425e.mov




<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.165, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.165 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a20743ddfe (2 hours ago), 2021-09-30 23:43:02 -0400
    • Engine revision 8ec71b64f6
    • Dart version 2.15.0 (build 2.15.0-167.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 94.0.4606.71

• No issues found!
```
</details>

**Comment by maheshmnj** [comment]
Sometimes the issue is also reproduced by just refreshing the browser without any breakpoints.

**Comment by annagrin** [comment]
Thanks, will investigate!

**Comment by elliette** [comment]
Note: This looks like a duplicate of https://github.com/flutter/flutter/issues/90822, which is an issue seen on Chrome Version 94.0.4606.61 (Official Build).

**Comment by obeobe** [comment]
@elliette as I mentioned, this also happened to me on earlier Chrome versions, for months now.

**Comment by nyck33** [comment]
What is the best workaround?  My boss wants me to use Chromedriver for testing Flutter web so I upgraded Chrome to the 94 version and having this same problem.

**Comment by ishan0805** [comment]
> What is the best workaround? My boss wants me to use Chromedriver for testing Flutter web so I upgraded Chrome to the 94 version and having this same problem.

use Flutter run mean while  , it is working

**Comment by nyck33** [comment]
@ishan0805 `flutter run mean` is the command?
I changed my `CHROME_EXECUTABLE` environment variable to brave browser in .bashrc as someone else said to do that in a similar issue but now Brave is having the same problems.

**Comment by ishan0805** [comment]
Yes flutter run is a command , or if you are using windows try edge

**Comment by safield** [comment]
I am also seeing this issue.

Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (4 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4

**Comment by nyck33** [comment]
Related to this?  https://github.com/dart-lang/sdk/issues/47645#issuecomment-967718351
Mine was.

**Comment by annagrin** [comment]
I still cannot repro the issue on the latest master. 
My chrome version is Version 96.0.4664.55 (Official Build) (x86_64)

I wonder if the bug the users experience is related to a chrome version as in  https://github.com/flutter/flutter/issues/90822

Please note that there is a different bug that manifests similarly in Flutter 2.5.3 on all chrome versions, which is currently fixed in master, so the issue seems to be related to chrome.

@maheshmnj could you please share information about your chrome version?

**Comment by maheshmnj** [comment]
[Last time](https://github.com/flutter/flutter/issues/90844#issuecomment-931921537) I verified this was on `Google Chrome 94.0.4606.71`

Currently, I am on the latest chrome `96.0.4664.55 (Official Build) (arm64)` will verify and update.

**Comment by maheshmnj** [comment]
@annagrin I am not able to reproduce it on the master channel using `Google Chrome 96.0.4664.93`, probably this is fixed.

<details>
<summary>flutter doctor -v</summary>


```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.789, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.789 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6ae721de3d (2 weeks ago), 2021-11-21 15:22:37 -0500
    • Engine revision ad00d12833
    • Dart version 2.16.0 (build 2.16.0-35.0.dev)
    • DevTools version 2.8.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.5:5555                     • android-arm64  • Android 11 (API
      30)
    • iPhone 11 (mobile)     • FC644E6C-7F02-40E5-9998-1F0CD162FBD8 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.0.1
      21A559 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome
      96.0.4664.93

• No issues found!
```
</details>

**Comment by annagrin** [comment]
Thank you @maheshmnj! I am closing this issue as duplicate of https://github.com/flutter/flutter/issues/90822

Folks seeing this failure on master, please update chrome and reopen or open a new issue if the error comes back on master.

Please note that Flutter 2.5.3  has a different issue that manifests as a similar crash happening intermittently, which will be fixed in a future stable release. Thank you for your patience!

Previously fixed issue:

issue: Dart-Code/Dart-Code#3518
fix: dart-lang/webdev#1384

It was rolled to flutter at: cd112e5
So it looks like it should be working on the latest master and 2.6.0-11.0.pre

**Comment by annagrin** [comment]
Duplicate of https://github.com/flutter/flutter/issues/90822
