### ISSUE TITLE
Video Player HDR Problem

### ISSUE THREAD

**Issue by ibrahimdevs** [flutter/flutter#91241]
Hi,

Video player plugin is not supporting HDR videos. When you try to play HDR video, it plays like SDR and different color.
You can try it video_player plugin's example, simply try to play any HDR video, you will notice different color video.

Video Player is top of AVPlayer and AVPlayer should play HDR videos automatically, but it didn't. I tried everything to find a workaround but no luck. Maybe https://developer.apple.com/news/?id=rwbholxw this helps.

Thanks,

**Comment by ibrahimdevs** [comment]
Hey @jmagman , I suspect about "kCVPixelFormatType_32BGRA" in FLTVideoPlayerPlugin.m > createVideoOutputAndDisplayLink() function. But I'm not sure which value should be there.

**Comment by danagbemava-nc** [comment]
Hi @ibrahimdevs, 

Can you please provide a link to any HDR videos so that I may confirm this behaviour? 

Thank you

**Comment by ibrahimdevs** [comment]
Hi @danagbemava-nc ,

Thanks for your interest. I'm really stuck in this issue and very surprise that nobody even mentioned it until now.
Example HDR video link: https://drive.google.com/file/d/12plWrjPfp1Hh1G7LHHTBXaOAi8ki7m5d/view?usp=sharing 

I'm getting lots of complaints about this issue from my app. If you provide any workaround, it will be great. 
I moved video_player package files to locale, so I can try your workarounds. 

Screenshots:
![mix_player](https://user-images.githubusercontent.com/2773578/135998217-329a735c-5db4-462b-966f-441d2ec154ce.png)


Thank you so much again,

**Comment by danagbemava-nc** [comment]
Hi @ibrahimdevs, thanks for the sample. I can reproduce this with the `video_player: ^2.2.5`. 
I haven't looked dived deep into the source code of the plugin so I can't suggest a work around at the moment, I will however label it so that someone with more experience can offer some more insight. 

<details>
<summary>screenshots</summary>

| AVPlayer iOS | video_player ios |
| -----------| -----------------|
| ![IMG_82E456A9AE58-1](https://user-images.githubusercontent.com/88313112/136015869-3c249cbc-e07e-47c5-ac2c-47c638d70c80.jpeg) | ![IMG_3002](https://user-images.githubusercontent.com/88313112/136015923-89692c7c-ece1-481d-a286-42e1e4c9a315.PNG) |

</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.5.1 20G80 darwin-arm, locale en-GB)
    • Flutter version 2.5.2 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (5 days ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 11.5.1 20G80 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 94.0.4606.61

• No issues found!
```
</details>

<details>
<summary>code sample</summary>

```dart
import 'package:video_player/video_player.dart';
import 'package:flutter/material.dart';

void main() => runApp(const VideoApp());

class VideoApp extends StatefulWidget {
  const VideoApp({Key? key}) : super(key: key);

  @override
  _VideoAppState createState() => _VideoAppState();
}

class _VideoAppState extends State<VideoApp> {
  late VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.asset('assets/hdr_video.MOV')
      ..initialize().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
      });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: Center(
          child: _controller.value.isInitialized
              ? AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer(_controller),
                )
              : Container(),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              _controller.value.isPlaying
                  ? _controller.pause()
                  : _controller.play();
            });
          },
          child: Icon(
            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}

```
</details>

<details>
<summary>video asset</summary>

[hdr_video.MOV.zip](https://github.com/flutter/flutter/files/7285510/hdr_video.MOV.zip)

</details>

**Comment by timcreatedit** [comment]
better_player displays HDR correctly for some reason, I'd be very happy if this plugin could do it too! I'll try to see if I can find something.

**Comment by timcreatedit** [comment]
I have noticed that I have way too little experience in native iOS development to understand anything 😅 So any help would be greatly appreciated! I'm happy to provide assistance wherever I can help

**Comment by ibrahimdevs** [comment]
Hi @danagbemava-nc and @stuartmorgan ,
It's been a long time, what is the latest status of this issue?

**Comment by blackox626** [comment]
> 

I have the same problem 
but I only fix the color by tonemap,so the video color look correct
I have no idea how to fix the brightness 

this is my solution ，I hope it helps
```
- (CVPixelBufferRef)pixelBufferFormCIImage:(CIImage *)image {
    NSDictionary *options = [NSDictionary dictionaryWithObjectsAndKeys:
                                    @{}, kCVPixelBufferIOSurfacePropertiesKey,
                                    @YES, kCVPixelBufferCGImageCompatibilityKey,
                                    @YES, kCVPixelBufferCGBitmapContextCompatibilityKey, nil];
    
    CVPixelBufferRef pixelBufferCopy = NULL;
    CVReturn status = CVPixelBufferCreate(kCFAllocatorDefault,
                                          image.extent.size.width,
                                          image.extent.size.height,
                                          kCVPixelFormatType_32BGRA,
                                          (__bridge CFDictionaryRef) options,
                                          &pixelBufferCopy);
    
    if (status == kCVReturnSuccess) {
        CIRenderDestination *destination = [[CIRenderDestination alloc] initWithPixelBuffer:pixelBufferCopy];
        [self.mContext startTaskToRender:image toDestination:destination error:nil];
    }
    return pixelBufferCopy;
}

- (CVPixelBufferRef)copyPixelBuffer {
    CMTime outputItemTime = [_videoOutput itemTimeForHostTime:CACurrentMediaTime()];
    if ([_videoOutput hasNewPixelBufferForItemTime:outputItemTime]) {
        if (!_isFirstFrameDisplay) {
            _isFirstFrameDisplay = YES;
            [self.utManager invokingFirstFrame];
        }
        CVPixelBufferRef p = [_videoOutput copyPixelBufferForItemTime:outputItemTime itemTimeForDisplay:NULL];
        CFTypeRef colorPrimaries = CVBufferGetAttachment(p, kCVImageBufferTransferFunctionKey, NULL);
        if (colorPrimaries && CFEqual(colorPrimaries, kCVImageBufferTransferFunction_ITU_R_2100_HLG)) {
            if (@available(iOS 14.1, *)) {
                CIImage *image = [CIImage imageWithCVPixelBuffer:p options:@{kCIImageToneMapHDRtoSDR : @(YES)}];
                CVPixelBufferRef newP = [self pixelBufferFormCIImage:image];
                CVPixelBufferRelease(p);
                return newP;
            }
        }
        return p;
    } else {
        return NULL;
    }
}
```

**Comment by jmagman** [comment]
@blackox626 we take pull requests 🙂

**Comment by timcreatedit** [comment]
@blackox626 Yeah tonemapping would at least help this package deal with HDR video in a decent way. As far as I understand we could only achieve HDR brightness by using an embedded native view, so I think this is the way to go for now?

**Comment by blackox626** [comment]
> 

you mean platform view？

**Comment by BurykinNikolay** [comment]
@blackox626 
"
    if (status == kCVReturnSuccess) {
        CIRenderDestination *destination = [[CIRenderDestination alloc] initWithPixelBuffer:pixelBufferCopy];
        [self.mContext startTaskToRender:image toDestination:destination error:nil];
    }
"

Where did you get in self mContext?

**Comment by wukong86372** [comment]
I have encountered the same problem, will it be fixed in the future?

**Comment by TMcClain5** [comment]
> @blackox626 " if (status == kCVReturnSuccess) { CIRenderDestination *destination = [[CIRenderDestination alloc] initWithPixelBuffer:pixelBufferCopy]; [self.mContext startTaskToRender:image toDestination:destination error:nil]; } "
> 
> Where did you get in self mContext?

@BurykinNikolay  Did you ever find out what mContext was?

**Comment by bac-huuk** [comment]
anything new?

**Comment by blackox626** [comment]
My approach is to make modifications by duplicating the plugin code and defining a new variable called mcontext to handle the pixelBuffer.

**Comment by arakcheev** [comment]
Hello everyone,

I am seeking recommendations on playing HDR videos in Flutter. Currently, I see two potential solutions:

1. Transcoding the video with tonemap and pixel format adjustments. However, this approach results in color loss and still doesn't leverage the HDR playback capabilities of modern smartphones.
2. Creating a custom UiKitView for video rendering, although this method presents other challenges as well.

I find it hard to believe that there aren't any Flutter video applications addressing this issue. So, I am curious to know how others have tackled the problem of HDR playback in Flutter. Could someone help with ideas, plz) 

Thank you!

**Comment by TMcClain5** [comment]
I just found this package recently, I don't know if it addresses the issue with HDR.
https://pub.dev/packages/media_kit

**Comment by hellohejinyu** [comment]
> I just found this package recently, I don't know if it addresses the issue with HDR, I have not been able to test it. https://pub.dev/packages/media_kit

It works! https://github.com/flutter/flutter/issues/129238#issuecomment-1784501802

**Comment by qpalzm963** [comment]
> > I just found this package recently, I don't know if it addresses the issue with HDR, I have not been able to test it. https://pub.dev/packages/media_kit
> 
> It works! [#129238 (comment)](https://github.com/flutter/flutter/issues/129238#issuecomment-1784501802)

What should I do if I encounter the same problem?

**Comment by hellohejinyu** [comment]
@qpalzm963 You can refer to the documentation of `media_kit` and use it to play videos. But you should test it more to avoid other problems. I simply tested it on an HDR video.

**Comment by qpalzm963** [comment]
> @qpalzm963 You can refer to the documentation of `media_kit` and use it to play videos. But you should test it more to avoid other problems. I simply tested it on an HDR video.

i try video_player_media_kit example but same question

**Comment by indacurdev** [comment]
Estoy intentando instalar media_kit pero aparece el siguiente error:

* Qué salió mal:
Se produjo un problema al evaluar el proyecto ':media_kit_libs_android_video'.
> media_kit: Error en la verificación del JAR arm64-v8a.

**Comment by indacurdev** [comment]
I am trying to install media_kit but I get the following error:
* Where:
Build file 'C:\Users\pc\AppData\Local\Pub\Cache\hosted\pub.dev\media_kit_libs_android_video-1.3.6\android\build.gradle' line: 102

* What went wrong:
A problem occurred evaluating project ':media_kit_libs_android_video'.
> media_kit: arm64-v8a JAR verification failed.

**Comment by vanvixi** [comment]
@hellohejinyu 
Even with media_kit this problem still exists
<table>
    <tr>
         <th style="text-align: center">Native IOS Player</th>
         <th style="text-align: center">media_kit </th>
    </tr>
    <tr>
    <td> <img src="https://github.com/flutter/flutter/assets/75975945/1e145f12-2752-40c1-8859-49e6be76699a"  alt="1" width = 360px height = 640px ></td>
    <td><img src="https://github.com/flutter/flutter/assets/75975945/b9763331-8bb9-4baa-87f9-09baeffa735e" alt="2" width = 360px height = 640px></td>
    </tr> 
</table>

**Comment by vanvixi** [comment]
@hellohejinyu 
This problem also appears on media_kit (https://github.com/media-kit/media-kit/issues/615)

**Comment by mertalev** [comment]
This is a big issue with the explosion of HDR content in recent years, especially when it's increasingly common for phones to shoot HDR videos.

I see that the re-triage tag was recently removed from this issue. Are there any plans underway to bring HDR to Flutter? This is the single feature I'm most looking forward to.

**Comment by benmccann** [comment]
Perhaps this would be fixed by switching to PlatformView: https://github.com/flutter/flutter/issues/86613

**Comment by kkpsiren** [comment]
it's 2024, are there any ongoing efforts to integrate HDR into Flutter?

**Comment by bselwe** [comment]
This is a huge issue in our app, and many users have reported this in other Flutter apps:

- Immich app: https://github.com/immich-app/immich/issues/5120
- Aves app: https://github.com/deckerst/aves/issues/924
- Ente app: https://github.com/ente-io/ente/issues/1166#issuecomment-2030367991

From Apple docs: `iPhone 12 models, iPhone 13 models, iPhone 14 models, and iPhone 15 models record video in HDR to capture true-to-life color and contrast`, meaning that most of the videos shared by iOS users are rendering incorrectly, I think we should bring more attention to this issue especially now when HDR usage is becoming more common.

**Comment by Deathproof76** [comment]
Just to underscore: And of course it's the same problem with Android phones. The friends and family, I share my Immich server with, who are using their Samsung S23U, Z Flip 5, S22FE, Google Pixel 6 Pro etc. with the Immich mobile app, are reporting the same issue with HDR videos, that are also locally available on their phone.

**Comment by stuartmorgan** [comment]
@bselwe Please don't just ping everyone who has ever touched the labels on a bug. The front-line triage team, for instance, is not an escalation path for already-triaged issues.

> This is a huge issue in our app

Anyone for whom it is a huge issue is encouraged to contribute improvements to the plugin.

**Comment by stuartmorgan** [comment]
As a reminder to everyone, please read our issue guidance before commenting, in particular https://github.com/flutter/flutter/blob/master/docs/contributing/issue_hygiene/README.md#do-not-add-me-too-or-same-or-is-there-an-update-comments-to-bugs and https://github.com/flutter/flutter/blob/master/docs/contributing/issue_hygiene/README.md#escalating-an-issue-that-has-the-wrong-priority

**Comment by maRci002** [comment]
I've been following the discussions about the HDR problem with the video player and noticed that there have been significant updates in Android PR flutter/packages#8237 and iOS PR flutter/packages#8237. Can anyone confirm if these updates have resolved the HDR issue?

Note: _Since the app-facing package still does not support `viewType`, it's a bit challenging to test. However `video_player_platform_interface` already supports [`VideoViewType`](https://github.com/flutter/packages/pull/8453/files#diff-6480bcec21eff8c085e1b1b3fbd5ca69e76212a9843ca76a3dd3ab861f81eef9R528), it's not difficult to fork the repository and make `platformView` the default renderer._

**Comment by ibrahimdevs** [comment]
@maRci002 and anyone waiting this issue. Android and iOS platform plugins now supports Platform Views. But somehow, VideoPlayerController doesn't expose this settings for now. (As V2.9.3)

If you want to use Platform View:
video_player.dart > VideoPlayerController > initialize()

Change this:
`_textureId = (await _videoPlayerPlatform.create(dataSourceDescription)) ?? kUninitializedTextureId;
`
to this:
`    _textureId = (await _videoPlayerPlatform.createWithOptions(VideoCreationOptions(dataSource: dataSourceDescription, viewType: VideoViewType.platformView))) ?? kUninitializedTextureId; `

And it will use Platform Views. But I'm wondering why this platform view not exposed.

**Comment by SungjunApp** [comment]
@ibrahimdevs amazing it works. I used your fix by cloning this plugin, applying your fix and testing my app with the local plugin. it works fine. Do you have any idea whether this plugin apply this improvement?

**Comment by rubengmlp** [comment]
I recently published a fork of video_player called video_player_hdr. It allows you to specify the desired viewType (either platform views or textures) in the initialize method. I've also added support methods to retrieve video metadata and check the device's HDR capabilities.
Feel free to try it out and suggest any improvements, thank you!

**Comment by Sk8er22** [comment]
I keep experiencing the same issue

**Comment by acheronian-flame** [comment]
Same, shows desaturated version of video on mobile (ios, android), web is fine.
