### ISSUE TITLE
flutter-devicelab-mac-6 app did not launch: This accessory may not be supported

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#93946]
Test failed.  Screenshot shows blocking modal "This accessory may not be supported."
https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20tiles_scroll_perf_ios__timeline_summary/2838

<img src="https://storage.googleapis.com/flutter_logs/flutter/7355cec5d5a18783ec8f7a288c2a89f3dd46ef9f/tiles_scroll_perf_ios__timeline_summary/798ade90-8c48-4eb9-873a-c638026750f5/drive_01.png" width="500">

Bad cable?
https://github.com/flutter/flutter/issues/66153

**Comment by keyonghan** [comment]
This needs a lab visit, and should be resolved until Monday.
Manually quarantined the bot for now.

**Comment by godofredoc** [comment]
This is most likely because an update of the Mac OS requires additional software to be installed.

**Comment by godofredoc** [comment]
Actually the phone is not recognized at all. Needs a lab visit.

**Comment by CaseyHillers** [comment]
I went into the lab for manual recovery. Bot is online - https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-6

The device was turned off when I got to it, but had a full charge. \cc @godofredoc @yusuf-goog

**Comment by jmagman** [comment]
`flutter-devicelab-mac-6` device is still having issues: https://github.com/flutter/flutter/issues/96794#issuecomment-1015993811

If the cable has already been swapped, recommend switching out the phone.

**Comment by jmagman** [comment]
Filed https://github.com/flutter/flutter/issues/96832 to detect these as infra failures instead of test flakes.

**Comment by CaseyHillers** [comment]
\cc @yusuf-goog (current on-call)

**Comment by yusuf-goog** [comment]
@jmagman mac-6 device was brought back online, but cables are still on back order. Hopefully will arrive this week.

**Comment by yusuf-goog** [comment]
Cable has been replaced today, hopefully this mitigates the issue.

**Comment by jmagman** [comment]
Let's close then, will reopen if we see this again.  Thanks @yusuf-goog!
