### ISSUE TITLE
compile error, bad gateway

### ISSUE THREAD

**Issue by stoneLee81** [flutter/flutter#94400]
https://google.bintray.com/exoplayer/androidx/core/core-ktx/maven-metadata.xml
This address cannot be found when compiling android app

**Comment by mamuseferha** [comment]
Hi @stoneLee81 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by TBoonkwan** [comment]
i got same error like you guy.

Execution failed for task ':location:mergeReleaseResources'.
> Could not resolve all files for configuration ':location:releaseRuntimeClasspath'.
   > Could not resolve com.google.android.gms:play-services-location:16.+.
     Required by:
         project :location
      > Failed to list versions for com.google.android.gms:play-services-location.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

Flutter doctor 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.2.3 20D91 darwin-x64, locale en-TH)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Community Edition (version 2020.2.4)
[✓] VS Code (version 1.62.3)
[✓] Connected device (2 available)

**Comment by karishma251** [comment]
I got same error :

gradle version is 6.7 and build.gradle is 4.1.0

Execution failed for task ':location:mergeReleaseResources'.

Could not resolve all files for configuration ':location:releaseRuntimeClasspath'.
Could not resolve com.google.android.gms:play-services-location:16.+.
Required by:
project :location
> Failed to list versions for com.google.android.gms:play-services-location.
> Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml.
> Could not get resource 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml'.
> Could not GET 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

flutter run --verbose

[   +6 ms] FAILURE: Build failed with an exception.
[   +5 ms] * What went wrong:
[        ] Execution failed for task ':app:checkDebugAarMetadata'.
[        ] > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
[        ]    > Could not resolve com.google.android.gms:play-services-location:16.+.
[        ]      Required by:
[        ]          project :app > project :location
[        ]       > Failed to list versions for com.google.android.gms:play-services-location.
[        ]          > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml.
[        ]             > Could not get resource 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml'.
[        ]                > Could not GET 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml'. Received status code 502 from server:
Bad Gateway
[        ] * Try:
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 58 actionable tasks: 2 executed, 56 up-to-date
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 15s
[ +560 ms] Running Gradle task 'assembleDebug'... (completed in 16.5s)
[   +2 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +1 ms] "flutter run" took 17,627ms.
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>

**Comment by go2hyder** [comment]
Getting same error

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.google.android.gms:play-services-location:16.+.
     Required by:
         project :app > project :location
      > Failed to list versions for com.google.android.gms:play-services-location.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s

**Comment by atelog** [comment]
Having the same issue. Tried to upgrade both `gradle` and `google-services` versions. Nothing works.

**Comment by iqfareez** [comment]
![image](https://user-images.githubusercontent.com/60868965/144146287-44a6e4f8-2ef2-4374-ad9b-d475789d0a98.png)
 seems like [Bintray](https://google.bintray.com/) is down. Can't find any official statement from their side.

**Comment by yashpathack** [comment]
[Bintray is down](https://twitter.com/search?q=bintray&src=recent_search_click&f=live)
Prolly the [Bintray sunset](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) is taking effect all over.

**Comment by yashpathack** [comment]
Moreover, saw few answers suggesting to replace all instances of `jcenter()` with `mavenCentral()`

**Comment by JulioCGMC** [comment]
Any news on this? How can this be closed without an anwser? THIS IS CRITICAL

**Comment by kartikpandey** [comment]
getting same error
```FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.google.android.gms:play-services-location:16.+.
     Required by:
         project :app > project :location
      > Failed to list versions for com.google.android.gms:play-services-location.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

also tried to replace all instances of jcenter() with mavenCentral() in project level build.gradle but this doesn't worked for me.

is there any solution of this??

**Comment by kartikpandey** [comment]
> Moreover, saw few answers suggesting to replace all instances of `jcenter()` with `mavenCentral()` in project level _build.gradle_

@yashpathack  have you got any solution?

**Comment by JulioCGMC** [comment]
For me this have worked, but i also needed to run `flutter clean && flutter packages get`

> > Moreover, saw few answers suggesting to replace all instances of `jcenter()` with `mavenCentral()` in project level _build.gradle_
> 
> @stoneLee81 have you got any solution?

**Comment by tanutwits** [comment]
@JulioCGMC     flutter 1.22.6  Will it work?

**Comment by JulioCGMC** [comment]
> @JulioCGMC flutter 1.22.6 Will it work?

For me it did

**Comment by stoneLee81** [comment]
I upgraded flutter to the latest version and the problem was solved
mavenCentral()  instead of jcenter() in build.gradle

**Comment by idipak** [comment]
I can't upgrade flutter to latest version but tried all of the above solutions, none of them worked for me. Any other solutions anyone have got???

[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19044.1348], locale en-US)
    • Flutter version 2.2.3 at C:\Users\PC\Documents\src\flutter
    • Framework revision f4abaa0735 (5 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\PC\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.62.3)
    • VS Code at C:\Users\PC\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 96.0.1054.43

• No issues found!

**Comment by ShreshtaRupa** [comment]
Same issue with me tries changing jcentre to mavencentral. in build.gradel. but it dint resolve the issue:

  FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Could not determine the dependencies of task ':agora_rtc_engine:generateDebugRFile'.
> Could not resolve all task dependencies for configuration ':agora_rtc_engine:debugRuntimeClasspath'.
   > Could not resolve com.github.agorabuilder:native-full-sdk:3.5.0.3. 
     Required by:                                                       
         project :agora_rtc_engine                                      
      > Could not resolve com.github.agorabuilder:native-full-sdk:3.5.0.3.
         > Could not get resource 'https://google.bintray.com/exoplayer/com/github/agorabuilder/native-full-sdk/3.5.0.3/native-full-sdk-3.5.0.3.pom'.
            > Could not HEAD 'https://google.bintray.com/exoplayer/com/github/agorabuilder/native-full-sdk/3.5.0.3/native-full-sdk-3.5.0.3.pom'. Received status code 502 from server: Bad Gateway
   > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-241c87ad800beeab545ab867354d4683d5bfb6ce.
     Required by:                                                       
         project :agora_rtc_engine                                      
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-241c87ad800beeab545ab867354d4683d5bfb6ce.
         > Could not get resource 'https://google.bintray.com/exoplayer/io/flutter/flutter_embedding_debug/1.0.0-241c87ad800beeab545ab867354d4683d5bfb6ce/flutter_embedding_debug-1.0.0-241c87ad800beeab545ab867354d4683d5bfb6ce.pom'.
            > Could not HEAD 'https://google.bintray.com/exoplayer/io/flutter/flutter_embedding_debug/1.0.0-241c87ad800beeab545ab867354d4683d5bfb6ce/flutter_embedding_debug-1.0.0-241c87ad800beeab545ab867354d4683d5bfb6ce.pom'. Received status code 502 from server: Bad Gateway

**Comment by rivetingpeppermint** [comment]
> getting same error
> 
> ```
> 
> * What went wrong:
> Execution failed for task ':app:checkDebugAarMetadata'.
> > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
>    > Could not resolve com.google.android.gms:play-services-location:16.+.
>      Required by:
>          project :app > project :location
>       > Failed to list versions for com.google.android.gms:play-services-location.
>          > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml.
>             > Could not get resource 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml'.
>                > Could not GET 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 13s
> [!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
> Exception: Gradle task assembleDebug failed with exit code 1
> Exited (sigterm)
> ```
> 
> also tried to replace all instances of jcenter() with mavenCentral() in project level build.gradle but this doesn't worked for me.
> 
> is there any solution of this??

I have the exact same issue. Tried `mavenCentral()` and `flutter clean` too but nothing works.

**Comment by shirenhu** [comment]
> I can't upgrade flutter to latest version but tried all of the above solutions, none of them worked for me. Any other solutions anyone have got???
> 
> [√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19044.1348], locale en-US) • Flutter version 2.2.3 at C:\Users\PC\Documents\src\flutter • Framework revision [f4abaa0](https://github.com/flutter/flutter/commit/f4abaa0735eba4dfd8f33f73363911d63931fe03) (5 months ago), 2021-07-01 12:46:11 -0700 • Engine revision 241c87ad80 • Dart version 2.13.4
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 30.0.3) • Android SDK at C:\Users\PC\AppData\Local\Android\sdk • Platform android-31, build-tools 30.0.3 • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174) • All Android licenses accepted.
> 
> [√] Chrome - develop for the web • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> 
> [√] Android Studio • Android Studio at C:\Program Files\Android\Android Studio • Flutter plugin can be installed from: https://plugins.jetbrains.com/plugin/9212-flutter • Dart plugin can be installed from: https://plugins.jetbrains.com/plugin/6351-dart • android-studio-dir = C:\Program Files\Android\Android Studio • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
> 
> [√] VS Code (version 1.62.3) • VS Code at C:\Users\PC\AppData\Local\Programs\Microsoft VS Code • Flutter extension version 3.25.0
> 
> [√] Connected device (3 available) • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator) • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.45 • Edge (web) • edge • web-javascript • Microsoft Edge 96.0.1054.43
> 
> • No issues found!

getting same error, omg

[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.19043.928], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.2)
[√] Connected device (2 available)

**Comment by marcellodesales** [comment]
# Same error :(

Flutter `1.21` :( SAME ERRORRRRRRRR

**Comment by phu-bc** [comment]
I have same problem

**Comment by shirenhu** [comment]
> Having the same issue. Tried to upgrade both `gradle` and `google-services` versions. Nothing works.
> 
> EDIT After hours of debugging. I fixed the build just by removing the `pubspec.lock` file and updating the `firebase_messaging` from `^9.1.4` to `^11.1.0`. I don't know why I don't know how this fixed the issue. Mb can be helpful for you as well.

I fixed the build  by removing the `pubspec.lock` file , great

**Comment by ShreshtaRupa** [comment]
i changed the version of this in build.grale

classpath 'com.android.tools.build:gradle:4.0.1'

it built the debug apk but not the release

**Comment by marcellodesales** [comment]
> i changed the version of this in build.grale
> 
> classpath 'com.android.tools.build:gradle:4.0.1'
> 
> it built the debug apk but not the release

Had the same problem @ShreshtaRupa ... I'm on Flutter 1.23.xxx... I upgraded to `com.android.tools.build:gradle:4.2.0` and using crashlytics now... trying the build...

**Comment by marcellodesales** [comment]
> > Having the same issue. Tried to upgrade both `gradle` and `google-services` versions. Nothing works.
> > EDIT After hours of debugging. I fixed the build just by removing the `pubspec.lock` file and updating the `firebase_messaging` from `^9.1.4` to `^11.1.0`. I don't know why I don't know how this fixed the issue. Mb can be helpful for you as well.
> 
> I fixed the build by removing the `pubspec.lock` file , great

@shirenhu I tried to removed it but it didn't change anything...

**Comment by Felix-Seip** [comment]
I tried upgrading flutter from 2.2.3 to 2.8.0. Didn't change anything.
I also tried upgrading my dependencies, including firebase_messaging.... also didn't work
https://google.bintray.com/ still shows 502 error

**Comment by djbuen** [comment]
do you guys know whats the current status of bintray it says 'Investigating - Thanks for supporting Bintray! This service has now been sunset.' ? I wonder if this is temporary or for good?

**Comment by Felix-Seip** [comment]
> do you guys know whats the current status of bintray it says 'Investigating - Thanks for supporting Bintray! This service has now been sunset.' ? I wonder if this is temporary or for good?

What are the alternatives to bintray? If so, how do we configure this in our projects?
I already updated my build.gradle to use maven instead of jcenter

**Comment by marcellodesales** [comment]
# Since Nov 30th

* Since then, we have been experiencing this... we can't migrate to Flutter 2.x just yet... Is this our Xmas gift??? Wow, it really sucks... I've been trying to call their attention on twitter https://twitter.com/marcellodesales/status/1465800280381870085 At least provide a workaround for those older versions... Apparently they don't even know there's still a huge part of the community that hasn't had the time, money, energy, resources to migrate apps... It's just frastrating:

1. Tried to upgrade and downgrade flutter to 1.26.x, 1.22.x, from 1.23... Nothing worked... 
2. Tried replacing the maven repositories... Nothing...
3. Tried deleting `pubspec.lock`, nothing...

```gradle
* What went wrong:                                                      
Execution failed for task ':app:mergeReleaseAssets'.                    
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve com.google.android.gms:play-services-location:16.+.
     Required by:                                                       
         project :app > project :location                               
      > Failed to list versions for com.google.android.gms:play-services-location.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
```

**Comment by Felix-Seip** [comment]
> # 📆 Since Nov 30th
> * Since then, we have been experiencing this... we can't migrate to Flutter 2.x just yet... Is this our Xmas gift??? Wow, it really sucks... I've been trying to call their attention on twitter https://twitter.com/marcellodesales/status/1465800280381870085 At least provide a workaround for those older versions... Apparently they don't even know there's still a huge part of the community that hasn't had the time, money, energy, resources to migrate apps... It's just frastrating:
> 
> 1. Tried to upgrade and downgrade flutter to 1.26.x, 1.22.x, from 1.23... Nothing worked...
> 2. Tried replacing the maven repositories... Nothing...
> 3. Tried deleting `pubspec.lock`, nothing...
> 
> # 🔉 Logs
> Still getting to the same place after upgrading, downloading libraries...
> 
> ```groovy-gradle
> * What went wrong:                                                      
> Execution failed for task ':app:mergeReleaseAssets'.                    
> > Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
>    > Could not resolve com.google.android.gms:play-services-location:16.+.
>      Required by:                                                       
>          project :app > project :location                               
>       > Failed to list versions for com.google.android.gms:play-services-location.
>          > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml.
>             > Could not get resource 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml'.
>                > Could not GET 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
> ```

I migrated, but I still have the same error.... Really sucks since I want to release a new version of my app before Christmas

**Comment by daoibrahim** [comment]
I finally solved this issue by : 
- Removing jcenter() from gradle project level
- removing maven { url 'https://dl.bintray.com/kotlin/kotlin-eap' } from gradle project level
- Adding maven { url 'https://dl.google.com/dl/android/maven2' } to the repositories
And my project finally launched successfully 👍 
My gradle look now like : 
`buildscript {
    ext.kotlin_version = '1.5.10'
    repositories {
        maven {
            url 'https://dl.google.com/dl/android/maven2'
        }
        google()
        mavenCentral()
        //maven { url 'https://dl.bintray.com/kotlin/kotlin-eap' }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.8'
    }
}

allprojects {
    repositories {
        maven {
            url 'https://dl.google.com/dl/android/maven2'
        }
        google()
        mavenCentral()
        //maven { url 'https://dl.bintray.com/kotlin/kotlin-eap' }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}`

**Comment by Felix-Seip** [comment]
`buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        maven {
            url 'https://dl.google.com/dl/android/maven2'
        }
        google()
        mavenCentral()
        //maven { url 'https://dl.bintray.com/kotlin/kotlin-eap' }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.8'
    }
}

allprojects {
    repositories {
        maven {
            url 'https://dl.google.com/dl/android/maven2'
        }
        google()
        mavenCentral()
        //maven { url 'https://dl.bintray.com/kotlin/kotlin-eap' }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

> I finally solved this issue by :
> 
> * Removing jcenter() from gradle project level
> * removing maven { url 'https://dl.bintray.com/kotlin/kotlin-eap' } from gradle project level
> * Adding maven { url 'https://dl.google.com/dl/android/maven2' } to the repositories
>   And my project finally launched successfully 👍
>   My gradle look now like :
> 
> ```
> buildscript {
>     ext.kotlin_version = '1.5.10'
>     repositories {
>         maven {
>             url 'https://dl.google.com/dl/android/maven2'
>         }
>         google()
>         mavenCentral()
>         //maven { url 'https://dl.bintray.com/kotlin/kotlin-eap' }
>     }
> 
>     dependencies {
>         classpath 'com.android.tools.build:gradle:4.2.0'
>         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
>         classpath 'com.google.gms:google-services:4.3.8'
>     }
> }
> 
> allprojects {
>     repositories {
>         maven {
>             url 'https://dl.google.com/dl/android/maven2'
>         }
>         google()
>         mavenCentral()
>         //maven { url 'https://dl.bintray.com/kotlin/kotlin-eap' }
>     }
> }
> 
> rootProject.buildDir = '../build'
> subprojects {
>     project.buildDir = "${rootProject.buildDir}/${project.name}"
> }
> subprojects {
>     project.evaluationDependsOn(':app')
> }
> 
> task clean(type: Delete) {
>     delete rootProject.buildDir
> }
> ```

Tried to do the same thing:
build.gradle
`buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        maven {
            url 'https://dl.google.com/dl/android/maven2'
        }
        google()
        mavenCentral()
        //maven { url 'https://dl.bintray.com/kotlin/kotlin-eap' }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.8'
    }
}

allprojects {
    repositories {
        maven {
            url 'https://dl.google.com/dl/android/maven2'
        }
        google()
        mavenCentral()
        //maven { url 'https://dl.bintray.com/kotlin/kotlin-eap' }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

However still receiving:
`[+4702 ms] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Could not determine the dependencies of task ':app:lintVitalRelease'.
[        ] > Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
[        ]    > Could not resolve com.google.android.gms:play-services-location:16.+.
[        ]      Required by:
[        ]          project :app > project :location
[        ]       > Failed to list versions for com.google.android.gms:play-services-location.
[        ]          > Unable to load Maven meta-data from
https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-meta
data.xml.
[        ]             > Could not get resource
'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-met
adata.xml'.
[        ]                > Could not GET
'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-met
adata.xml'. Received status code 502 from server: Bad Gateway
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 9s`

**Comment by marcellodesales** [comment]
# 🧾 Maven Repo Copy

* Yeah, @daoibrahim I found the Google's Maven repo https://maven.google.com/web/index.html?q=play-services-location#com.google.android.gms:play-services-location:6.5.87 So, 

Based on the links, we should be able to download the pom files through one of the `pom` links... For instance:

https://dl.google.com/android/maven2/com/google/android/gms/play-services-location/6.5.87/play-services-location-6.5.87.pom

Based on that, I tried using the Maven repo as `https://dl.google.com/android/maven2` instead of `https://dl.google.com/dl/android/maven2` 

Will try now...

**Comment by daoibrahim** [comment]
> > I finally solved this issue by :
> > 
> > * Removing jcenter() from gradle project level
> > * removing maven { url 'https://dl.bintray.com/kotlin/kotlin-eap' } from gradle project level
> > * Adding maven { url 'https://dl.google.com/dl/android/maven2' } to the repositories
> >   And my project finally launched successfully 👍
> >   My gradle look now like :
> > 
> > ```
> > buildscript {
> >     ext.kotlin_version = '1.5.10'
> >     repositories {
> >         maven {
> >             url 'https://dl.google.com/dl/android/maven2'
> >         }
> >         google()
> >         mavenCentral()
> >         //maven { url 'https://dl.bintray.com/kotlin/kotlin-eap' }
> >     }
> > 
> >     dependencies {
> >         classpath 'com.android.tools.build:gradle:4.2.0'
> >         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
> >         classpath 'com.google.gms:google-services:4.3.8'
> >     }
> > }
> > 
> > allprojects {
> >     repositories {
> >         maven {
> >             url 'https://dl.google.com/dl/android/maven2'
> >         }
> >         google()
> >         mavenCentral()
> >         //maven { url 'https://dl.bintray.com/kotlin/kotlin-eap' }
> >     }
> > }
> > 
> > rootProject.buildDir = '../build'
> > subprojects {
> >     project.buildDir = "${rootProject.buildDir}/${project.name}"
> > }
> > subprojects {
> >     project.evaluationDependsOn(':app')
> > }
> > 
> > task clean(type: Delete) {
> >     delete rootProject.buildDir
> > }
> > ```
> 
> Tried to do the same thing: build.gradle
> 
> ```
> buildscript {
>     ext.kotlin_version = '1.3.50'
>     repositories {
>         maven {
>             url 'https://dl.google.com/dl/android/maven2'
>         }
>         google()
>         mavenCentral()
>         //maven { url 'https://dl.bintray.com/kotlin/kotlin-eap' }
>     }
> 
>     dependencies {
>         classpath 'com.android.tools.build:gradle:4.2.0'
>         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
>         classpath 'com.google.gms:google-services:4.3.8'
>     }
> }
> 
> allprojects {
>     repositories {
>         maven {
>             url 'https://dl.google.com/dl/android/maven2'
>         }
>         google()
>         mavenCentral()
>         //maven { url 'https://dl.bintray.com/kotlin/kotlin-eap' }
>     }
> }
> 
> rootProject.buildDir = '../build'
> subprojects {
>     project.buildDir = "${rootProject.buildDir}/${project.name}"
> }
> subprojects {
>     project.evaluationDependsOn(':app')
> }
> 
> task clean(type: Delete) {
>     delete rootProject.buildDir
> }
> ```
> 
> However still receiving:
> 
> ```
> [+4702 ms] FAILURE: Build failed with an exception.
> [        ] * What went wrong:
> [        ] Could not determine the dependencies of task ':app:lintVitalRelease'.
> [        ] > Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
> [        ]    > Could not resolve com.google.android.gms:play-services-location:16.+.
> [        ]      Required by:
> [        ]          project :app > project :location
> [        ]       > Failed to list versions for com.google.android.gms:play-services-location.
> [        ]          > Unable to load Maven meta-data from
> https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-meta
> data.xml.
> [        ]             > Could not get resource
> 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-met
> adata.xml'.
> [        ]                > Could not GET
> 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-met
> adata.xml'. Received status code 502 from server: Bad Gateway
> [        ] * Try:
> [        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug
> option to get more log output. Run with --scan to get full insights.
> [        ] * Get more help at https://help.gradle.org
> [        ] BUILD FAILED in 9s```
> ```

Your issue seems mainly due to something related to exoplayer. Can you search in your whole project this "https://google.bintray.com/exoplayer"?

**Comment by marcellodesales** [comment]
# Disable or Exclude dependency of exoplayer

* Has anyone tried to `exclude` the dependency to the exoplayer in `gradle`? 
  * That way this dependency would be skipped...
* Is there a way to disable the use of `exoplayer`?

As `gradle dependencies:tree` fails due to the problem above, it's hard to exclude/disable if we can't see the current packages...

**Comment by daoibrahim** [comment]
@marcellodesales  We will try something. Do you use any video player on your app? Or does any of your packages use location service?

**Comment by Felix-Seip** [comment]
> https://dl.google.com/dl/android/maven2

The build is looking better. I am no longer receiving the 502 error after removing the https://google.bintray.com/exoplayer from my .idea folder. I did also remove the entire .idea folder.

I am now getting:
```
[  +27 ms] 
           FAILURE: Build failed with an exception.
           
           * What went wrong:
           Could not open cp_init remapped class cache for d7lz4udat99d148wopreyiv89
(/Users/felixseip/.gradle/caches/5.4.1/scripts-remapped/aar_init_script_biyn0lkz3jim1
f5m96w50nolf/d7lz4udat99d148wopreyiv89/cp_initdcd040730888da95d185715568c9cc57).
           > Could not open cp_init generic class cache for initialization script
'/Users/felixseip/Documents/dev-tools/flutter/packages/flutter_tools/gradle/aar_init_
script.gradle'
(/Users/felixseip/.gradle/caches/5.4.1/scripts/d7lz4udat99d148wopreyiv89/cp_init/cp_i
nitdcd040730888da95d185715568c9cc57).
              > Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
           
           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or
--debug option to get more log output. Run with --scan to get full insights.
           
           * Get more help at https://help.gradle.org
           
           BUILD FAILED in 29s

...

[   +8 ms] The plugin barcode_scan could not be built due to the issue above.
[   +1 ms] 
```

I'll try to remove the pubspec.lock file and flutter clean. That might resolve the problem.

**Comment by marcellodesales** [comment]
@daoibrahim I found out that the dependency to the location service is indeed here, but I don't think we are using it...

```yaml
  location: ^3.2.4
```

Running without it..

**Comment by daoibrahim** [comment]
@marcellodesales  Does the project run when you comment this package? (Hopefully you aren't using it)

**Comment by marcellodesales** [comment]
@daoibrahim So, I had asked for a feature that uses the location service... I guess it was left out here... so I'm removing it completely as this should have been removed a couple of weeks ago... So, I'm doing it right now and see how it affects the build...

Our builds are isolated in Docker containers so if it works at least we solved by removing the dependency to the location service...

**Comment by folkdeveloper** [comment]
> @daoibrahim So, I had asked for a feature that uses the location service... I guess it was left out here... so I'm removing it completely as this should have been removed a couple of weeks ago... So, I'm doing it right now and see how it affects the build...
> 
> Our builds are isolated in Docker containers so if it works at least we solved by removing the dependency to the location service...

@marcellodesales i commented few lines in gradel and seems like it works my project is building

following is the code
    buildscript {
        ext.kotlin_version = '1.4.32'
        repositories {
            google()
            mavenCentral()
            maven { url 'https://maven.aliyun.com/repository/google' }
            maven { url 'https://maven.aliyun.com/repository/public' }
        }
    
        dependencies {
             classpath 'com.android.tools.build:gradle:4.0.1'
            classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
            classpath 'com.google.gms:google-services:4.3.3'
            classpath 'com.google.firebase:firebase-crashlytics-gradle:2.4.1'
        }
    }
    
    allprojects {
        repositories {
            google()
            mavenCentral()
            maven { url 'https://maven.aliyun.com/repository/google' }
            maven { url 'https://maven.aliyun.com/repository/public' }
            // maven {
            //     url 'https://google.bintray.com/exoplayer/'
            // }
            maven {
                url 'https://www.jitpack.io'
            }
        }
        configurations.all {
            exclude group: 'com.google.guava', module: 'failureaccess'
    
            resolutionStrategy {
                eachDependency { details ->
                    if('guava' == details.requested.name) {
                        details.useVersion '27.0-android'
                    }
                }
            }
        }
    }
    
    rootProject.buildDir = '../build'
    subprojects {
        project.buildDir = "${rootProject.buildDir}/${project.name}"
    }
    subprojects {
        project.evaluationDependsOn(':app')
    }
    
    task clean(type: Delete) {
        delete rootProject.buildDir
    }


i commented out these lines:

     // maven {
                //     url 'https://google.bintray.com/exoplayer/'
                // }

**Comment by marcellodesales** [comment]
> maven { url 'https://maven.aliyun.com/repository/google' }
> maven { url 'https://maven.aliyun.com/repository/public' }

@folkdeveloper I will try adding those as well... I could remove the dependency and still waiting for the build as I deleted a lot of references to the classes referring to the location service... Let's see if I can get a clean build...

**Comment by folkdeveloper** [comment]
@marcellodesales what i was actually asking is to comment these not to add

 // maven {
            //     url 'https://google.bintray.com/exoplayer/'
            // }

**Comment by marcellodesales** [comment]
I don't have any of bintray :) The build just passed without the location service...

**Comment by daoibrahim** [comment]
Good job to all. Congratulation to us 💯

**Comment by Felix-Seip** [comment]
> > Your issue seems mainly due to something related to exoplayer. Can you search in your whole project this
> > "https://google.bintray.com/exoplayer"?
> 
> The build is looking better. I am no longer receiving the 502 error after removing the https://google.bintray.com/exoplayer from my .idea folder. I did also remove the entire .idea folder.
> 
> I am now getting:
> 
> ```
> [  +27 ms] 
>            FAILURE: Build failed with an exception.
>            
>            * What went wrong:
>            Could not open cp_init remapped class cache for d7lz4udat99d148wopreyiv89
> (/Users/felixseip/.gradle/caches/5.4.1/scripts-remapped/aar_init_script_biyn0lkz3jim1
> f5m96w50nolf/d7lz4udat99d148wopreyiv89/cp_initdcd040730888da95d185715568c9cc57).
>            > Could not open cp_init generic class cache for initialization script
> '/Users/felixseip/Documents/dev-tools/flutter/packages/flutter_tools/gradle/aar_init_
> script.gradle'
> (/Users/felixseip/.gradle/caches/5.4.1/scripts/d7lz4udat99d148wopreyiv89/cp_init/cp_i
> nitdcd040730888da95d185715568c9cc57).
>               > Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
>            
>            * Try:
>            Run with --stacktrace option to get the stack trace. Run with --info or
> --debug option to get more log output. Run with --scan to get full insights.
>            
>            * Get more help at https://help.gradle.org
>            
>            BUILD FAILED in 29s
> 
> ...
> 
> [   +8 ms] The plugin barcode_scan could not be built due to the issue above.
> [   +1 ms] 
> ```
> 
> I'll try to remove the pubspec.lock file and flutter clean. That might resolve the problem.

Still not out of the woods yet :(
Even with removing barcode_scan, I'm still receiving the same error dealing with cp_init. I have no idea what it could be

**Comment by marcellodesales** [comment]
@daoibrahim I think that's always a good lesson: when removing a feature, remove all the unused dependencies... That's always the case... I did reviewed the PR for our app and I did let it pass as `"we were in a rush"`...  Trying to conclude this... Thank you as well!!!

**Comment by marcellodesales** [comment]
> > > Your issue seems mainly due to something related to exoplayer. Can you search in your whole project this
> > > "https://google.bintray.com/exoplayer"?
> > 
> > 
> > The build is looking better. I am no longer receiving the 502 error after removing the https://google.bintray.com/exoplayer from my .idea folder. I did also remove the entire .idea folder.
> > I am now getting:
> > ```
> > [  +27 ms] 
> >            FAILURE: Build failed with an exception.
> >            
> >            * What went wrong:
> >            Could not open cp_init remapped class cache for d7lz4udat99d148wopreyiv89
> > (/Users/felixseip/.gradle/caches/5.4.1/scripts-remapped/aar_init_script_biyn0lkz3jim1
> > f5m96w50nolf/d7lz4udat99d148wopreyiv89/cp_initdcd040730888da95d185715568c9cc57).
> >            > Could not open cp_init generic class cache for initialization script
> > '/Users/felixseip/Documents/dev-tools/flutter/packages/flutter_tools/gradle/aar_init_
> > script.gradle'
> > (/Users/felixseip/.gradle/caches/5.4.1/scripts/d7lz4udat99d148wopreyiv89/cp_init/cp_i
> > nitdcd040730888da95d185715568c9cc57).
> >               > Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
> >            
> >            * Try:
> >            Run with --stacktrace option to get the stack trace. Run with --info or
> > --debug option to get more log output. Run with --scan to get full insights.
> >            
> >            * Get more help at https://help.gradle.org
> >            
> >            BUILD FAILED in 29s
> > 
> > ...
> > 
> > [   +8 ms] The plugin barcode_scan could not be built due to the issue above.
> > [   +1 ms] 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'll try to remove the pubspec.lock file and flutter clean. That might resolve the problem.
> 
> Still not out of the woods yet :( Even with removing barcode_scan, I'm still receiving the same error dealing with cp_init. I have no idea what it could be

So, am I reading right, or is the library being loaded is pointing to a `Java 7` version???

` Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7` Is that normal?

**Comment by marcellodesales** [comment]
Felix-Seip try removing the gradle caches... That `.gradle` cache is suspicious... Have you tried running `gradle clean` inside the android dir? At least from the IDE you can verify if this works ... https://stackoverflow.com/questions/37015872/could-not-open-cp-init-class-cache-for-initialization-script/66011700#66011700

**Comment by marcellodesales** [comment]
# 👍 Resolution

* Removing dependencies that are not in use is helpful..
* We are all busy with so much... Bintray or Google should have provided an alternative to the sun setting of these... 
  * Never trust no one? It sux... we are in the OSS space as well... 

It's so specific for each of us... I does end up being too expensive to get to the bottom of things... I'm just doing a dockerized builds for the Flutter team and now I'm unblocked... thank you guys....

# 🔉 Logs

```console
Removed unused resources: Binary resource data reduced from 553KB to 510KB: Removed 7%
Running Gradle task 'bundleRelease'...                                  
Running Gradle task 'bundleRelease'... Done                       405.6s
✓ Built build/app/outputs/bundle/release/app-release.aab (40.6MB).
INFO: Generating app apk with version in pubspec.yaml

Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                     153.6s
✓ Built build/app/outputs/flutter-apk/app-release.apk (41.5MB).
```

**Comment by Felix-Seip** [comment]
> @Felix-Seip try removing the gradle caches... That `.gradle` cache is suspicious... Have you tried running `gradle clean` inside the android dir? At least from the IDE you can verify if this works ... https://stackoverflow.com/questions/37015872/could-not-open-cp-init-class-cache-for-initialization-script/66011700#66011700

I deleted the .grade cache. Didn't help much. And it is quite strange that the dependency is trying to load in Java 7 but I'm unsure if that is normal. 
I haven't seen this error message up until now....

**Comment by idipak** [comment]
Still no success :(

buildscript {
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://dl.google.com/dl/android/maven2'
        }
//        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.0'
        classpath 'com.google.gms:google-services:4.3.10'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://dl.google.com/dl/android/maven2'
        }
//        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by idipak** [comment]
Sill stuck, what to do now?

`
buildscript {
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://dl.google.com/dl/android/maven2'
        }
//        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.0'
        classpath 'com.google.gms:google-services:4.3.10'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://dl.google.com/dl/android/maven2'
        }
//        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}



`

**Comment by tanutwits** [comment]
@idipak how to fix

**Comment by djbuen** [comment]
> 

in my case, i disable location package for now, cause i really need to continue development

**Comment by tanutwits** [comment]
i disable in pubspec yes ? @djbuen

**Comment by djbuen** [comment]
> you disable in pubspec yes ? @djbuen

yes and code using it

**Comment by idipak** [comment]
@tanutwits In my case I replaced the location package with geolocator and it's working fine now :)

**Comment by phu-bc** [comment]
@idipak can you share your grade file please?

**Comment by idipak** [comment]
@phu-bc 

```
buildscript {
    repositories {
        google()
        mavenCentral()
//        maven {
//            url 'https://dl.google.com/dl/android/maven2'
//        }
//        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.0'
        classpath 'com.google.gms:google-services:4.3.10'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
//        maven {
//            url 'https://dl.google.com/dl/android/maven2'
//        }
//        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
I had also raised this issue on stackoverflow, rest of the details you can checkout there : https://stackoverflow.com/questions/70306564/flutter-error-could-not-resolve-com-google-android-gmsplay-services-location

**Comment by pedrocganem** [comment]
This fixed the issue to me:

```gradle
// project level

buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        mavenCentral() // <- replaced jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.+' // <- updated this
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.10'
    }
}


// app level

configurations.all {
    resolutionStrategy {
        force 'com.google.android.gms:play-services-location:16.0.0' 
    }
}
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.firebase:firebase-analytics:17.2.2'
    implementation 'com.google.android.gms:play-services-location:16.0.0' // ADD THIS
}

```

also, on `gradle-wrapper.properties`:

```properties
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip
```

**Comment by alexgularte** [comment]
I just changed the distributionUrl property of file android/gradle/wrapper/gradle-wrapper.properties

from:
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip

to:
distributionUrl=https\://services.gradle.org/distributions/gradle-6.6.1-all.zip

and works.

**Comment by phu-bc** [comment]
For this issue, I have resolved by upgrade to Null Safety version, and then update distributionUrl from gradle-5.6.2-all.zip to gradle-6.6.1-all.zip

**Comment by 78Ronin** [comment]
> 6.6.1


I tried absolutely every suggested solution to the problem, but alas, if the package is removed from the cache, then no option will help.
The service https://google.bintray.com/exoplayer/androidx/core/core-ktx/maven-metadata.xml completely closed the campaign, you will have to abandon audioplayers in my project and look for something new, or wait for bintray to come to life ...

**Comment by rivetingpeppermint** [comment]
If you've successfully debugged your app on Android before (on the same machine you're using now), you might still have your cached packages. I turned my internet connection off completely, just for when I debug, and it works. I haven't tried releasing though.

**Comment by PaoloDooM** [comment]
> # 👍 Resolution
> 
>     * Removing dependencies that are not in use is helpful..
> 
>     * We are all busy with so much... Bintray or Google should have provided an alternative to the sun setting of these...
>       
>       * Never trust no one? It sux... we are in the OSS space as well...
> 
> 
> It's so specific for each of us... I does end up being too expensive to get to the bottom of things... I'm just doing a dockerized builds for the Flutter team and now I'm unblocked... thank you guys.... For this one to work:
> ## Upgrade the gradle version of your `android/gradlew/gradle-wrapper.properties`
> 
> > NOTE: This is specific for each project and may differ... Just upgrade from 5.x to 6.7.x
> 
> ```diff
> --- a/android/gradle/wrapper/gradle-wrapper.properties
> +++ b/android/gradle/wrapper/gradle-wrapper.properties
> @@ -3,4 +3,4 @@ distributionBase=GRADLE_USER_HOME
>  distributionPath=wrapper/dists
>  zipStoreBase=GRADLE_USER_HOME
>  zipStorePath=wrapper/dists
> -distributionUrl=https://services.gradle.org/distributions/gradle-5.6.2-all.zip
> +idistributionUrl=https://services.gradle.org/distributions/gradle-6.7.1-all.zip
> ```
> 
> ## Replace the `jcenter()` with `mavenCentral()` at `android/build.gradle`
> 
> > NOTE: May differ depending on how the file has been maintained
> 
> ```diff
> diff --git a/android/build.gradle b/android/build.gradle
> index e6952b0..ea767bf 100644
> --- a/android/build.gradle
> +++ b/android/build.gradle
> @@ -6,7 +6,7 @@ buildscript {
>              url 'https://dl.google.com/dl/android/maven2'
>          }
>          google()
> -        jcenter()
> +       mavenCentral()
>      }
>  
>      dependencies {
> @@ -26,7 +26,7 @@ allprojects {
>              url 'https://dl.google.com/dl/android/maven2'
>          }
>          google()
> -        jcenter()
> +       mavenCentral()
>      }
>  }
> ```
> 
> # 🔉 Logs
> 
> ```
> Removed unused resources: Binary resource data reduced from 553KB to 510KB: Removed 7%
> Running Gradle task 'bundleRelease'...                                  
> Running Gradle task 'bundleRelease'... Done                       405.6s
> ✓ Built build/app/outputs/bundle/release/app-release.aab (40.6MB).
> INFO: Generating app apk with version in pubspec.yaml
> 
> Building without sound null safety
> For more information see https://dart.dev/null-safety/unsound-null-safety
> 
> Running Gradle task 'assembleRelease'...                                
> Running Gradle task 'assembleRelease'... Done                     153.6s
> ✓ Built build/app/outputs/flutter-apk/app-release.apk (41.5MB).
> ```

It works, thank you!

**Comment by daoibrahim** [comment]
Another solution for those who are still facing the issue :

The problem is that a plugin (location in this case) didn't specify a fixed version of an Android library. So in order to find which versions are available, Gradle must go to the repository to check. In this case, that repository is Bintray, which has been down for days and returning HTTP 502 Bad Request.

The steps below provide a quick and dirty workaround so you can build the app while Bintray is down. A more proper solution would be to fork the plugin and make changes to your fork as suggested by Eldar Miensutov, but it might be a bit overkill for a temporary server error.

1. In the Project tool window (where your files are listed), scroll all the way down until you find Flutter Plugins. If you don't see it, make sure that Project is selected in the dropdown at the top of the Project tool window.
2. Open Flutter plugins, find location-4.0.0 and open it (you might have a different version number after location-, that's fine).
3. Open the file location-4.0.0/android/build.gradle
4. Find the line api 'com.google.android.gms:play-services-location:16.+'
5. Change it to api 'com.google.android.gms:play-services-location:16.0.0'. If your editor says that the file does not belong to your project, select "I want to edit this file anyway".

You should now be able to build the app.

This change is of course a temporary solution, and if you update the location plugin your changes will be overwritten. But at least you'll be able to build until Bintray comes online again (or until you had time to migrate to another more recently updated plugin).

Source : https://stackoverflow.com/a/70319873/11311849
