### ISSUE TITLE
Error using NestedScrollView when header is higher than viewportDimension

### ISSUE THREAD

**Issue by cr1992** [flutter/flutter#94846]
## Steps to Reproduce

1. Execute `flutter run` on the code sample with **iOS Siumlator**
![result](https://tva1.sinaimg.cn/large/008i3skNly1gx6iraqmjzj30p01gogni.jpg)
As you can see, body is **outside** screen.
2. Pull down NestedScrollView, and we'll check console's outputs.

**Expected results:** 
NestedScrollView's body's pixel.
**Actual results:** 
```
[+681577 ms] flutter: 0.0
[        ] flutter: 0.0
[ +229 ms] flutter: 0.0
[   +1 ms] flutter: 0.0
[        ] flutter: -196.3333282470703
[  +15 ms] flutter: -480.99998474121094
[  +23 ms] flutter: -978.9999694824219
[  +22 ms] flutter: -1976.3332824707031
[  +21 ms] flutter: -3962.333221435547
[  +26 ms] flutter: -7944.666442871094
[  +18 ms] flutter: -15903.666229248047
[  +25 ms] flutter: -31823.332458496094
[  +20 ms] flutter: -63663.33157348633
[  +22 ms] flutter: -127345.32981872559
[  +17 ms] flutter: -254700.3263092041
[  +27 ms] flutter: -509422.6526184082
[  +21 ms] flutter: -1018860.3052368164
[  +22 ms] flutter: -2037728.277130127
[  +24 ms] flutter: -4075462.220932007
[  +20 ms] flutter: -8150929.108535767
[  +22 ms] flutter: -16301863.883728027
[  +21 ms] flutter: -32603732.434127808
[  +23 ms] flutter: -65207467.20158386
[  +22 ms] flutter: -130414936.73651123
[  +21 ms] flutter: -260829876.8063507
[  +22 ms] flutter: -521659757.6127014
[  +22 ms] flutter: -1043319523.2254028
[  +28 ms] flutter: -2086639051.4508057
[  +15 ms] flutter: -4173278107.9016113
[  +26 ms] flutter: -8346556220.803223
[  +19 ms] flutter: -16693112444.939774
[  +22 ms] flutter: -33386224891.21289
[  +23 ms] flutter: -66772449783.09244
[  +21 ms] flutter: -133544899567.85155
[  +22 ms] flutter: -267089799137.36975
[  +23 ms] flutter: -534179598275.7395
[  +20 ms] flutter: -1068359196552.1456
[  +22 ms] flutter: -2136718393104.6245
[  +23 ms] flutter: -4273436786210.249
[  +23 ms] flutter: -8546873572421.164
[  +31 ms] flutter: -17093747144842.66
[  +36 ms] flutter: -34187494289686.984
[  +19 ms] flutter: -68374988579374.64
[ +171 ms] flutter: 0.0
[        ] flutter: -68374988579374.64
[        ] flutter: -68374988579374.305
[        ] flutter: -136749977158748.61
[  +16 ms] flutter: 0.0
[   +2 ms] flutter: 0.0
[        ] flutter: -136749977158748.61
[  +27 ms] flutter: -133545527632334.83
[  +16 ms] flutter: -125874445529229.75
[  +21 ms] flutter: -115875793897621.05
[  +13 ms] flutter: -104923932590711.62
[  +15 ms] flutter: -93875042336339.44
[  +18 ms] flutter: -83245918754160.19
[  +14 ms] flutter: -73325947484071.34
[  +17 ms] flutter: -64255312675949.586
[  +15 ms] flutter: -56082134228758.01
[  +17 ms] flutter: -48795967073571.82
[  +16 ms] flutter: -42352679227878.17
[  +17 ms] flutter: -36688654039255.93
[  +16 ms] flutter: -31733241515201.812
[  +19 ms] flutter: -27413797111863.48
[  +13 ms] flutter: -23659188216764.02
[  +17 ms] flutter: -20402517596615.01
[  +16 ms] flutter: -17583446735392.13
[  +18 ms] flutter: -15146170562369.61
[  +18 ms] flutter: -13041487257186.404
[  +13 ms] flutter: -11225744113676.719
[  +16 ms] flutter: -9660211084883.785
[  +17 ms] flutter: -8311272809809.535
[  +16 ms] flutter: -7149563856862.15
[  +16 ms] flutter: -6149347514711.736
[  +16 ms] flutter: -5288486016808.643
[  +18 ms] flutter: -4547740948172.524
[  +15 ms] flutter: -3910510383203.235
[  +17 ms] flutter: -3362347697491.224
[  +15 ms] flutter: -2890892730563.7227
[  +16 ms] flutter: -2485451927002.389
[  +17 ms] flutter: -2136829335876.2192
[  +15 ms] flutter: -1837062575937.872
[  +17 ms] flutter: -1579304160778.779
[  +15 ms] flutter: -1357690837304.958
[  +16 ms] flutter: -1167149904838.7583
[  +17 ms] flutter: -1003357978974.3268
[  +16 ms] flutter: -862544805228.8279
[  +16 ms] flutter: -741488786779.9963
[  +16 ms] flutter: -637413547080.5074
[  +16 ms] flutter: -547943971096.13116
[  +19 ms] flutter: -471031048822.7161
[  +13 ms] flutter: -404916678632.8151
[  +17 ms] flutter: -348078255613.68506
[  +15 ms] flutter: -299220461586.8808
[  +17 ms] flutter: -257217858379.35498
[  +15 ms] flutter: -221111048748.71274
[  +16 ms] flutter: -190074259536.50916
[  +16 ms] flutter: -163392418941.41898
[  +16 ms] flutter: -140455980024.0128
[  +17 ms] flutter: -120739216830.34822
[  +16 ms] flutter: -103791131218.44911
[  +17 ms] flutter: -89221199408.37866
[  +16 ms] flutter: -76697233611.75587
[  +16 ms] flutter: -65930643018.198494
[  +20 ms] flutter: -56675947935.31927
[  +12 ms] flutter: -48719887240.50788
[  +17 ms] flutter: -41880678557.90435
[  +18 ms] flutter: -36001542364.43012
[  +13 ms] flutter: -30947987706.60368
[  +16 ms] flutter: -26603560124.02666
[  +17 ms] flutter: -22868995099.256435
[  +17 ms] flutter: -19658681594.218765
[  +14 ms] flutter: -16899179713.908957
[  +20 ms] flutter: -14526898716.232239
[  +13 ms] flutter: -12487634657.618982
[  +16 ms] flutter: -10734736660.171463
[  +16 ms] flutter: -9227810315.975458
[  +16 ms] flutter: -7932423968.33179
[  +16 ms] flutter: -6818943868.847557
[  +16 ms] flutter: -5861710540.808402
[  +17 ms] flutter: -5038897926.371251
[  +16 ms] flutter: -4331544793.219331
[  +15 ms] flutter: -3723488847.3970113
[  +18 ms] flutter: -3200790900.395942
[  +15 ms] flutter: -2751493496.0121727
[  +15 ms] flutter: -2365264298.9670753
[  +16 ms] flutter: -2033213474.2353132
[  +21 ms] flutter: -1747809775.7974443
[  +12 ms] flutter: -1502454771.1551576
[  +16 ms] flutter: -1291554067.290237
[  +17 ms] flutter: -1110247576.6274366
[  +16 ms] flutter: -954392628.2504578
[  +16 ms] flutter: -820416371.6974287
[  +16 ms] flutter: -705253908.589586
[  +16 ms] flutter: -606251384.7596561
[  +17 ms] flutter: -521151421.69695824
[  +16 ms] flutter: -447988872.7934224
[  +17 ms] flutter: -385104337.50807804
[  +15 ms] flutter: -331043947.30104136
[  +16 ms] flutter: -284575059.1791632
[  +17 ms] flutter: -244597963.6224845
[  +17 ms] flutter: -210288372.25797373
[  +16 ms] flutter: -180768394.49895012
[  +18 ms] flutter: -155392388.54563725
[  +13 ms] flutter: -133578629.62793343
[  +17 ms] flutter: -114828096.78740373
[  +16 ms] flutter: -98708694.51554255
[  +18 ms] flutter: -84852110.636761
[  +14 ms] flutter: -72940693.97595598
[  +15 ms] flutter: -62701953.826497465
[  +16 ms] flutter: -53899944.1657914
[  +16 ms] flutter: -46333968.40725735
[  +17 ms] flutter: -39829672.88407251
[  +16 ms] flutter: -34238440.96628464
[  +16 ms] flutter: -29432365.22000273
[  +18 ms] flutter: -25300692.32579681
[  +16 ms] flutter: -21749017.70137696
[  +15 ms] flutter: -18696091.705498558
[  +16 ms] flutter: -16071561.371210538
[  +14 ms] flutter: -13815584.196563743
[  +16 ms] flutter: -11876172.45311432
[  +19 ms] flutter: -10209012.52739549
[  +15 ms] flutter: -8775886.102691673
[  +17 ms] flutter: -7544008.360509727
[  +17 ms] flutter: -6484991.3693288
[  +15 ms] flutter: -5574637.652895462
[  +16 ms] flutter: -4792121.566768818
[  +15 ms] flutter: -4119447.853038192
[  +17 ms] flutter: -3541165.716778547
[  +15 ms] flutter: -3044061.99108398
[  +18 ms] flutter: -2616740.9679970825
[  +16 ms] flutter: -2249427.067401327
[  +17 ms] flutter: -1933638.1974862942
[  +16 ms] flutter: -1662227.0329502923
[  +15 ms] flutter: -1428886.004283793
[  +16 ms] flutter: -1228301.052001412
[  +17 ms] flutter: -1055873.9254388288
[  +16 ms] flutter: -907660.1072450617
[  +17 ms] flutter: -780237.0119653502
[  +16 ms] flutter: -670714.5549244275
[  +16 ms] flutter: -576560.6150080449
[  +16 ms] flutter: -495623.8691076374
[  +16 ms] flutter: -426052.7732990984
[  +15 ms] flutter: -366244.1007067206
[  +15 ms] flutter: -314834.14043693687
[  +18 ms] flutter: -270640.63501199655
[  +16 ms] flutter: -232648.4937936982
[  +16 ms] flutter: -199989.63445410595
[  +17 ms] flutter: -171915.37859064454
[  +15 ms] flutter: -147783.48741190194
[  +16 ms] flutter: -127037.85502289656
[  +16 ms] flutter: -109204.46452746735
[  +16 ms] flutter: -93874.49961731063
[  +16 ms] flutter: -80697.26540013227
[  +16 ms] flutter: -69369.72947505889
[  +17 ms] flutter: -59631.16591158873
[  +14 ms] flutter: -51260.69423862385
[  +18 ms] flutter: -44065.19197899892
[  +16 ms] flutter: -37879.38401116174
[  +16 ms] flutter: -32561.93082623801
[  +17 ms] flutter: -27990.68000112619
[  +15 ms] flutter: -24061.82554161737
[  +17 ms] flutter: -20683.87352618638
[  +15 ms] flutter: -17780.462620305
[  +16 ms] flutter: -15284.605690119583
[  +16 ms] flutter: -13138.974832361102
[  +16 ms] flutter: -11294.54453359002
[  +16 ms] flutter: -9709.032694624942
[  +16 ms] flutter: -8346.168462475945
[  +16 ms] flutter: -7174.610509097551
[  +17 ms] flutter: -6167.44905444067
[  +16 ms] flutter: -5301.62335358177
[  +17 ms] flutter: -4557.38912901089
[  +15 ms] flutter: -3917.7005397193307
[  +17 ms] flutter: -3367.708835594009
[  +16 ms] flutter: -2894.981009796886
[  +16 ms] flutter: -2488.5877594129256
[  +16 ms] flutter: -2139.2628212298114
[  +15 ms] flutter: -1838.956198007388
[  +18 ms] flutter: -1580.8205313986502
[  +16 ms] flutter: -1358.9072297725816
[  +17 ms] flutter: -1168.1457967239062
[  +16 ms] flutter: -1004.1722913950413
[  +17 ms] flutter: -863.2080363396436
[  +17 ms] flutter: -742.0254053274441
[  +15 ms] flutter: -637.8725293461408
[  +17 ms] flutter: -548.3239291218543
[  +16 ms] flutter: -471.35100837901007
[  +15 ms] flutter: -405.1907896494405
[  +16 ms] flutter: -348.3106921724512
[  +16 ms] flutter: -299.41534057724886
[  +16 ms] flutter: -257.3861837019864
[  +16 ms] flutter: -221.254683203504
[  +16 ms] flutter: -190.1969966740872
[  +16 ms] flutter: -163.49741715004993
[  +16 ms] flutter: -140.54588601387405
[  +16 ms] flutter: -120.81625764947961
[  +14 ms] flutter: -103.85718856490132
[  +19 ms] flutter: -89.27705627930118
[  +16 ms] flutter: -76.74516864625484
[  +15 ms] flutter: -65.9723915192265
[  +17 ms] flutter: -56.71128253979912
[  +16 ms] flutter: -48.7506770949769
[  +16 ms] flutter: -41.90674716697635
[  +15 ms] flutter: -36.02393856250774
[  +18 ms] flutter: -30.967512221143892
[  +16 ms] flutter: -26.62009601453183
[  +17 ms] flutter: -22.88341308682241
[  +16 ms] flutter: -19.671251156130094
[  +16 ms] flutter: -16.909829347349444
[  +17 ms] flutter: -14.536051941331305
[  +16 ms] flutter: -12.495501977032168
[  +16 ms] flutter: -10.741498952954176
[  +17 ms] flutter: -9.233539052982122
[  +16 ms] flutter: -7.937420221450429
[  +14 ms] flutter: -6.823176641771496
[  +18 ms] flutter: -5.865402197376722
[  +16 ms] flutter: -5.042025513476335
[  +17 ms] flutter: -4.334233258533611
[  +16 ms] flutter: -3.7258336715061358
[  +16 ms] flutter: -3.2028065252038465
[  +16 ms] flutter: -2.7532261609199495
[  +17 ms] flutter: -2.3667107719220803
[  +16 ms] flutter: -2.0344937982703213
[  +15 ms] flutter: -1.7489103714345386
[  +17 ms] flutter: -1.503400860984457
[  +14 ms] flutter: -1.2923556208056972
[  +17 ms] flutter: -1.1109366064446857
[  +17 ms] flutter: -0.9549849311363668
[  +15 ms] flutter: -0.820932977061937
[  +17 ms] flutter: -0.7056915921386568
[  +16 ms] flutter: -0.6066331318260738
[  +15 ms] flutter: -0.5214748494749605
[  +17 ms] flutter: -0.4482750320813929
[  +16 ms] flutter: -0.38534333367523
[  +14 ms] flutter: 0.0
[        ] flutter: 0.0

```

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(MyApp());
}

class MyWidgetsFlutterBinding extends WidgetsFlutterBinding {
  @override
  ViewConfiguration createViewConfiguration() {
    return super.createViewConfiguration();
  }
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        scaffoldBackgroundColor: Colors.white,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with TickerProviderStateMixin {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: buildNestedScrollView(),
    );
  }

  Widget buildNestedScrollView() {
    return NotificationListener<ScrollNotification>(
      onNotification: (scrollNotification) {
        print(scrollNotification.metrics?.pixels);
        return false;
      },
      child: DefaultTabController(
        length: 4,
        child: NestedScrollView(
          headerSliverBuilder: (_, __) {
            return [
              SliverList(
                delegate: SliverChildBuilderDelegate(
                  (_, index) => SizedBox(
                    height: 44,
                    child: Center(
                      child: Text(
                        index.toString(),
                      ),
                    ),
                  ),
                  childCount: 20,
                ),
              ),
              SliverPersistentHeader(
                delegate: MyDelegate(
                  (context, shrinkOffset, overlapsContent) => SizedBox(
                    height: 53,
                    child: TabBar(
                      tabs: List.generate(
                        4,
                        (index) => Text(
                          index.toString(),
                        ),
                      ),
                      labelStyle: TextStyle(fontSize: 16),
                      labelColor: Colors.black,
                      isScrollable: false,
                    ),
                  ),
                  maxExtent: 53,
                  minExtent: 53,
                ),
                pinned: true,
              ),
            ];
          },
          body: TabBarView(
            children: List.generate(
              4,
              (index) => ListView.builder(
                itemBuilder: (_, index) => SizedBox(
                  height: 44,
                  child: Center(
                    child: Text(
                      index.toString(),
                    ),
                  ),
                ),
                itemCount: 40,
              ),
            ),
          ),
        ),
      ),
    );
  }
}

class MyDelegate extends SliverPersistentHeaderDelegate {
  MyDelegate(
    this.builder, {
    double maxExtent,
    double minExtent,
  })  : _maxExtent = maxExtent,
        _minExtent = minExtent;

  final double _maxExtent;
  final double _minExtent;

  final Widget Function(
      BuildContext context, double shrinkOffset, bool overlapsContent) builder;

  @override
  Widget build(
      BuildContext context, double shrinkOffset, bool overlapsContent) {
    return builder(context, shrinkOffset, overlapsContent);
  }

  @override
  double get maxExtent => _maxExtent;

  @override
  double get minExtent => _minExtent;

  @override
  bool shouldRebuild(covariant MyDelegate oldDelegate) {
    return oldDelegate != this;
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by cr1992** [comment]
I've debug the code and I've figure what was wrong:
1. _NestedScrollCoordinator # applyUserOffset
When dragging down, innerPositions will call function applyFullDragUpdate with remainingDelta.
```dart
  @override
  void applyUserOffset(double delta) {
    updateUserScrollDirection(
      delta > 0.0 ? ScrollDirection.forward : ScrollDirection.reverse,
    );
    assert(delta != 0.0);
    if (_innerPositions.isEmpty) {
      _outerPosition!.applyFullDragUpdate(delta);
    } else if (delta < 0.0) {
      // Dragging "up"
      // Prioritize getting rid of any inner overscroll, and then the outer
      // view, so that the app bar will scroll out of the way asap.
      double outerDelta = delta;
      for (final _NestedScrollPosition position in _innerPositions) {
        if (position.pixels < 0.0) { // This inner position is in overscroll.
          final double potentialOuterDelta = position.applyClampedDragUpdate(delta);
          // In case there are multiple positions in varying states of
          // overscroll, the first to 'reach' the outer view above takes
          // precedence.
          outerDelta = math.max(outerDelta, potentialOuterDelta);
        }
      }
      if (outerDelta != 0.0) {
        final double innerDelta = _outerPosition!.applyClampedDragUpdate(
          outerDelta,
        );
        if (innerDelta != 0.0) {
          for (final _NestedScrollPosition position in _innerPositions)
            position.applyFullDragUpdate(innerDelta);
        }
      }
    } else {
      // Dragging "down" - delta is positive
      double innerDelta = delta;
      // Apply delta to the outer header first if it is configured to float.
      if (_floatHeaderSlivers)
        innerDelta = _outerPosition!.applyClampedDragUpdate(delta);

      if (innerDelta != 0.0) {
        // Apply the innerDelta, if we have not floated in the outer scrollable,
        // any leftover delta after this will be passed on to the outer
        // scrollable by the outerDelta.
        double outerDelta = 0.0; // it will go positive if it changes
        final List<double> overscrolls = <double>[];
        final List<_NestedScrollPosition> innerPositions = _innerPositions.toList();
        for (final _NestedScrollPosition position in innerPositions) {
          final double overscroll = position.applyClampedDragUpdate(innerDelta);
          outerDelta = math.max(outerDelta, overscroll);
          overscrolls.add(overscroll);
        }
        if (outerDelta != 0.0)
          outerDelta -= _outerPosition!.applyClampedDragUpdate(outerDelta);

        // Now deal with any overscroll
        for (int i = 0; i < innerPositions.length; ++i) {
          final double remainingDelta = overscrolls[i] - outerDelta;
          if (remainingDelta > 0.0)
            innerPositions[i].applyFullDragUpdate(remainingDelta);
        }
      }
    }
  }
```
2. _NestedScrollPosition # applyFullDragUpdate
This function will calculate a newPixel with ScrollPhysics, the fuction is applyPhysicsToUserOffset.
```dart
// Returns the overscroll.
  double applyFullDragUpdate(double delta) {
    assert(delta != 0.0);
    final double oldPixels = pixels;
    // Apply friction:
    final double newPixels = pixels - physics.applyPhysicsToUserOffset(
      this,
      delta,
    );
    if (oldPixels == newPixels)
      return 0.0; // delta must have been so small we dropped it during floating point addition
    // Check for overscroll:
    final double overscroll = physics.applyBoundaryConditions(this, newPixels);
    final double actualNewPixels = newPixels - overscroll;
    if (actualNewPixels != oldPixels) {
      forcePixels(actualNewPixels);
      didUpdateScrollPositionBy(actualNewPixels - oldPixels);
    }
    if (overscroll != 0.0) {
      didOverscrollBy(overscroll);
      return overscroll;
    }
    return 0.0;
  }
```
3. BouncingScrollPhysics # applyPhysicsToUserOffset
When sliver is outside screen, ScrollMetrics's viewportDimension will be zero, and friction's value will be infinity.
Function _applyFriction will return the sum of overscrollPast and  offset.
```dart
@override
  double applyPhysicsToUserOffset(ScrollMetrics position, double offset) {
    assert(offset != 0.0);
    assert(position.minScrollExtent <= position.maxScrollExtent);

    if (!position.outOfRange)
      return offset;

    final double overscrollPastStart = math.max(position.minScrollExtent - position.pixels, 0.0);
    final double overscrollPastEnd = math.max(position.pixels - position.maxScrollExtent, 0.0);
    final double overscrollPast = math.max(overscrollPastStart, overscrollPastEnd);
    final bool easing = (overscrollPastStart > 0.0 && offset < 0.0)
        || (overscrollPastEnd > 0.0 && offset > 0.0);

    final double friction = easing
        // Apply less resistance when easing the overscroll vs tensioning.
        ? frictionFactor((overscrollPast - offset.abs()) / position.viewportDimension)
        : frictionFactor(overscrollPast / position.viewportDimension);
    final double direction = offset.sign;

    return direction * _applyFriction(overscrollPast, offset.abs(), friction);
  }

  static double _applyFriction(double extentOutside, double absDelta, double gamma) {
    assert(absDelta > 0);
    double total = 0.0;
    if (extentOutside > 0) {
      final double deltaToLimit = extentOutside / gamma;
      if (absDelta < deltaToLimit)
        return absDelta * gamma;
      total += extentOutside;
      absDelta -= deltaToLimit;
    }
    return total + absDelta;
  }
```

**Comment by danagbemava-nc** [comment]
Hi @cr1992, thanks for filing the issue. 

I'm not entirely sure as to what exactly the issue you're describing here is. 

Please provide a more detailed description. 

Thank you

**Comment by cr1992** [comment]
@danagbemava-nc
When NestedScrollView is at top bound, and NestedScrolView's **header**'s height is higher than viewportDimension, pull down NestedScrollView, then the **body**'s  scrollPosition's pixel is error, because body is outside of screen, the body's **viewportDimension is zero**, it will let BouncingScrollPhysics returning a error offset. And NestedScrollView will'not be able to scroll until **body**'s scrollPosition's pixel is corrected by BouncingScrollPhysics.
You can try to run my code sample,  thanks. Sorry for my poor English.

**Comment by danagbemava-nc** [comment]
I'm still not sure what the issue is even after running your sample. 

On my end the `scrollNotification.metrics.pixels` starts from `0`, and increases until I get to the end of the list. The only time I get a negative value is when I scroll up.  See video below

How are you determining that the body's `viewportDimension` is zero? 

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/88313112/145210203-c262782e-e044-424c-a99c-3cb8d4eb6e6e.mov

</details>

**Comment by lycstar** [comment]
@danagbemava-nc Can you test @cr1992 's demo again? Note that after pulling down hard ! and scroll up the list immediately, expect it should behave as can't scroll. 

Because this time, position.viewportDimension = 0, the friction is incorrectly calculated as infinite.

Related code in BouncingScrollPhysics # applyPhysicsToUserOffset : 
```dart 
final double friction = easing
        // Apply less resistance when easing the overscroll vs tensioning.
        ? frictionFactor((overscrollPast - offset.abs()) / position.viewportDimension)
        : frictionFactor(overscrollPast / position.viewportDimension);
```
Thank you!

**Comment by cr1992** [comment]
> @danagbemava-nc Can you test @cr1992 's demo again? Note that after pulling down hard ! and scroll up the list immediately, expect it should behave as can't scroll.
> 
> Because this time, position.viewportDimension = 0, the friction is incorrectly calculated as infinite.
> 
> Related code in BouncingScrollPhysics # applyPhysicsToUserOffset :
> 
> ```dart
> final double friction = easing
>         // Apply less resistance when easing the overscroll vs tensioning.
>         ? frictionFactor((overscrollPast - offset.abs()) / position.viewportDimension)
>         : frictionFactor(overscrollPast / position.viewportDimension);
> ```
> 
> Thank you!

Thanks forlycstar's comment.
@danagbemava-nc 

https://user-images.githubusercontent.com/14345890/145319349-a42f9278-b62a-46b1-9584-0978e0214946.mov


I've recorded a video. Just like @lycstar saied, when NestedScrollView is at top bounds, pull down harder,
and you'll see the problem.Like what I do in video.

**Comment by danagbemava-nc** [comment]
Issue is reproducible using sample provided by OP above. 

## Steps to reproduce
1. Run the code sample
2. Scroll/Pull downwards for a long stretch
3. Attempt to scroll up
4. Notice that the content doesn't immediately change unless you scroll a couple of times. See video below


<details>
<summary>video</summary>

https://user-images.githubusercontent.com/88313112/145354277-21766978-1d30-4f74-9bb5-2e239dc47b7b.mov


</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.8.0, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.8.0 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (10 hours ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:197:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:53:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1290:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (4 available)
    • Nexus (mobile)     • 00008020-001875E83A38002E            • ios            • iOS 15.0.2 19A404
    • iPhone 13 (mobile) • 7515F01A-C1B6-456E-8559-8D2383D3719D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 96.0.4664.93

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.6.0-12.0.pre.975, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.975 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9b1bbdbd16 (3 hours ago), 2021-12-09 00:04:07 -0500
    • Engine revision 30b0105c72
    • Dart version 2.16.0 (build 2.16.0-85.0.dev)
    • DevTools version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:198:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:302:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (4 available)
    • Nexus (mobile)     • 00008020-001875E83A38002E            • ios            • iOS 15.0.2 19A404
    • iPhone 13 (mobile) • 7515F01A-C1B6-456E-8559-8D2383D3719D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 96.0.4664.93

! Doctor found issues in 1 category.
```
</details>

**Comment by AlexV525** [comment]
cc @Piinks

**Comment by HaijunWei** [comment]
I have the same problem, is there a temporary fix?

**Comment by kuikuiGe** [comment]
Is there any solution?
