### ISSUE TITLE
Crashed: com.apple.main-thread EXC_BAD_ACCESS KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by Tom3652** [flutter/flutter#95568]
## Steps to Reproduce

Unfortunately i am unable to reproduce it for now and it happens only in ```release``` mode affecting my beta testers.

<img width="1429" alt="Capture d’écran 2021-12-20 à 15 40 43" src="https://user-images.githubusercontent.com/32631467/146784585-40427623-82e1-44c5-bfdf-43f48b243e4e.png">

The error description is : 

```
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x2d623636612d6365
```

This crash occurred 10 times and each time with a little bit different ```StackTrace``` apparently.  
I have made this [issue](https://github.com/FirebaseExtended/flutterfire/issues/7642) because of the ```FirebaseDatabase``` log in the trace, but there is no such logs in more recent errors. 

I have also focused on ```firebase_database``` because it's the main change between my ```0.0.06``` release and ```0.0.07``` including a real time chat feature in app.  
I have also added ```flutter_sound_lite``` to play and record audio messages.  
According to the popularity, i would think now that the error would come from the [flutter_sound_lite](https://pub.dev/packages/flutter_sound_lite) rather than ```firebase_database```, but ```FirebaseDatabase``` appeared in the first logs sequences so... 
There is no evident log for me pointing towards a specific package anyway, it could be conflict between several packages as well (```flutter_sound_lite``` and ```camera``` for example...) 

In addition, the latest crash gave these ```keys``` :

<img width="1218" alt="Capture d’écran 2021-12-20 à 15 42 16" src="https://user-images.githubusercontent.com/32631467/146784826-c71501a6-3b3d-42a4-b46f-7b0409357208.png">

I will update the full trace (you will see the difference with the one in ```FlutterFire``` repo that i have mentioned.  
Below you will see the latest crash (with the above ```keys```).

**Expected results:** 

The app should not crash.

**Actual results:** 

The app is crashing.

<details>
  <summary>Logs</summary>

```
Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x15c8 objc_msgSend + 8
1  Flutter                        0x4f02b0 (Missing)
2  Flutter                        0x3c664 (Missing)
3  Flutter                        0x3bc204 (Missing)
4  Flutter                        0x2eb0d8 (Missing)
5  Flutter                        0x2ee6a4 (Missing)
6  CoreFoundation                 0xae268 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
7  CoreFoundation                 0x32c40 __CFRunLoopDoTimer + 1076
8  CoreFoundation                 0x2d43c __CFRunLoopDoTimers + 328
9  CoreFoundation                 0xbc58 __CFRunLoopRun + 1944
10 CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
11 GraphicsServices               0x138c GSEventRunModal + 164
12 UIKitCore                      0x5196a8 -[UIApplication _run] + 1100
13 UIKitCore                      0x2987f4 UIApplicationMain + 2092
14 Runner                         0x7ab0 main + 7 (AppDelegate.swift:7)
15 ???                            0x1034a9a24 (Missing)

Thread
0  libsystem_pthread.dylib        0xe8c start_wqthread + 258

com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x1504 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1b9c mach_msg + 76
2  CoreFoundation                 0x7688 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb97c __CFRunLoopRun + 1212
4  CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
5  Foundation                     0x18354 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236
6  Foundation                     0x59c28 -[NSRunLoop(NSRunLoop) runUntilDate:] + 92
7  UIKitCore                      0x4928a4 -[UIEventFetcher threadMain] + 524
8  Foundation                     0x6836c __NSThread__start__ + 808
9  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
10 libsystem_pthread.dylib        0xea0 thread_start + 8

io.flutter.1.ui
0  libsystem_kernel.dylib         0x1504 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1b9c mach_msg + 76
2  CoreFoundation                 0x7688 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb97c __CFRunLoopRun + 1212
4  CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
5  Flutter                        0x2ee570 (Missing)
6  Flutter                        0x2edd30 (Missing)
7  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
8  libsystem_pthread.dylib        0xea0 thread_start + 8

io.flutter.1.raster
0  libsystem_kernel.dylib         0x1558 semaphore_timedwait_trap + 8
1  libdispatch.dylib              0x4c6c _dispatch_sema4_timedwait + 64
2  libdispatch.dylib              0x5270 _dispatch_semaphore_wait_slow + 76
3  QuartzCore                     0x32290 -[CAMetalLayer nextDrawable] + 1044
4  Flutter                        0x295604 (Missing)
5  Flutter                        0x1a3f68 (Missing)
6  Flutter                        0x187470 (Missing)
7  Flutter                        0x187ba8 (Missing)
8  Flutter                        0x5567c (Missing)
9  Flutter                        0x4f9274 (Missing)
10 Flutter                        0x47e558 (Missing)
11 Flutter                        0x3b4704 (Missing)
12 Flutter                        0x3b4c20 (Missing)
13 Flutter                        0x2ec868 (Missing)
14 Flutter                        0x3b4318 (Missing)
15 Flutter                        0x3b5c50 (Missing)
16 Flutter                        0x3b4ed4 (Missing)
17 Flutter                        0x3bd314 (Missing)
18 Flutter                        0x2eb0d8 (Missing)
19 Flutter                        0x2ee6a4 (Missing)
20 CoreFoundation                 0xae268 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
21 CoreFoundation                 0x32c40 __CFRunLoopDoTimer + 1076
22 CoreFoundation                 0x2d43c __CFRunLoopDoTimers + 328
23 CoreFoundation                 0xbc58 __CFRunLoopRun + 1944
24 CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
25 Flutter                        0x2ee570 (Missing)
26 Flutter                        0x2edd30 (Missing)
27 libsystem_pthread.dylib        0x19a4 _pthread_start + 148
28 libsystem_pthread.dylib        0xea0 thread_start + 8

io.flutter.1.io
0  libsystem_kernel.dylib         0x1504 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1b9c mach_msg + 76
2  CoreFoundation                 0x7688 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb97c __CFRunLoopRun + 1212
4  CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
5  Flutter                        0x2ee570 (Missing)
6  Flutter                        0x2edd30 (Missing)
7  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
8  libsystem_pthread.dylib        0xea0 thread_start + 8

io.worker.1
0  libsystem_kernel.dylib         0x1f90 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8254 _pthread_cond_wait + 1228
2  libc++.1.dylib                 0x9ddc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  Flutter                        0x2e8928 (Missing)
4  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
5  libsystem_pthread.dylib        0xea0 thread_start + 8

io.worker.2
0  libsystem_kernel.dylib         0x1f90 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8254 _pthread_cond_wait + 1228
2  libc++.1.dylib                 0x9ddc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  Flutter                        0x2e8928 (Missing)
4  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
5  libsystem_pthread.dylib        0xea0 thread_start + 8

io.worker.3
0  libsystem_kernel.dylib         0x1f90 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8254 _pthread_cond_wait + 1228
2  libc++.1.dylib                 0x9ddc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  Flutter                        0x2e8928 (Missing)
4  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
5  libsystem_pthread.dylib        0xea0 thread_start + 8

io.worker.4
0  libsystem_kernel.dylib         0x1f90 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8254 _pthread_cond_wait + 1228
2  libc++.1.dylib                 0x9ddc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  Flutter                        0x2e8928 (Missing)
4  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
5  libsystem_pthread.dylib        0xea0 thread_start + 8

io.worker.5
0  libsystem_kernel.dylib         0x1f90 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8254 _pthread_cond_wait + 1228
2  libc++.1.dylib                 0x9ddc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  Flutter                        0x2e8928 (Missing)
4  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
5  libsystem_pthread.dylib        0xea0 thread_start + 8

io.worker.6
0  libsystem_kernel.dylib         0x1f90 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8254 _pthread_cond_wait + 1228
2  libc++.1.dylib                 0x9ddc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  Flutter                        0x2e8928 (Missing)
4  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
5  libsystem_pthread.dylib        0xea0 thread_start + 8

dart:io EventHandler
0  libsystem_kernel.dylib         0x2e7c kevent + 8
1  Flutter                        0x4b14dc (Missing)
2  Flutter                        0x4e04e8 (Missing)
3  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
4  libsystem_pthread.dylib        0xea0 thread_start + 8

com.google.firebase.crashlytics.MachExceptionServer
0  FirebaseCrashlytics            0x1f44c FIRCLSProcessRecordAllThreads + 184
1  FirebaseCrashlytics            0x1f82c FIRCLSProcessRecordAllThreads + 1176
2  FirebaseCrashlytics            0x167f0 FIRCLSHandler + 48
3  FirebaseCrashlytics            0x195b8 FIRCLSMachExceptionServer + 1248
4  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
5  libsystem_pthread.dylib        0xea0 thread_start + 8

Thread
0  libsystem_pthread.dylib        0xe8c start_wqthread + 258

AVAudioSession Notify Thread
0  libsystem_kernel.dylib         0x1504 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1b9c mach_msg + 76
2  CoreFoundation                 0x7688 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb97c __CFRunLoopRun + 1212
4  CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
5  AudioSession                   0x6308 CADeprecated::GenericRunLoopThread::Entry(void*) + 164
6  AudioSession                   0xfd64 CADeprecated::CAPThread::Entry(CADeprecated::CAPThread*) + 92
7  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
8  libsystem_pthread.dylib        0xea0 thread_start + 8

com.apple.CoreMotion.MotionThread
0  libsystem_kernel.dylib         0x1504 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1b9c mach_msg + 76
2  CoreFoundation                 0x7688 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb97c __CFRunLoopRun + 1212
4  CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
5  CoreFoundation                 0x9fa78 CFRunLoopRun + 64
6  CoreMotion                     0x13544 CLMotionActivity::isTypeInVehicle(CLMotionActivity::Type) + 21264
7  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
8  libsystem_pthread.dylib        0xea0 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x1f90 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8254 _pthread_cond_wait + 1228
2  libc++.1.dylib                 0x9ddc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  leveldb                        0x15ef0 leveldb::(anonymous namespace)::PosixEnv::BackgroundThreadMain() + 80
4  leveldb                        0x15ea0 leveldb::(anonymous namespace)::PosixEnv::BackgroundThreadEntryPoint(leveldb::(anonymous namespace)::PosixEnv*) + 10
5  leveldb                        0x15f84 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(leveldb::(anonymous namespace)::PosixEnv*), leveldb::(anonymous namespace)::PosixEnv*> >(void*) + 44
6  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
7  libsystem_pthread.dylib        0xea0 thread_start + 8

com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x1504 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1b9c mach_msg + 76
2  CoreFoundation                 0x7688 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb97c __CFRunLoopRun + 1212
4  CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
5  CFNetwork                      0x27a6a0 _CFURLStorageSessionCopyIdentifier + 59784
6  Foundation                     0x6836c __NSThread__start__ + 808
7  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
8  libsystem_pthread.dylib        0xea0 thread_start + 8

com.squareup.SocketRocket.NetworkThread
0  libsystem_kernel.dylib         0x1504 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1b9c mach_msg + 76
2  CoreFoundation                 0x7688 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb97c __CFRunLoopRun + 1212
4  CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
5  Foundation                     0x18354 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236
6  FirebaseDatabase               0x52f5c -[_FSRRunLoopThread main] + 252
7  Foundation                     0x6836c __NSThread__start__ + 808
8  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
9  libsystem_pthread.dylib        0xea0 thread_start + 8

com.apple.CFSocket.private
0  libsystem_kernel.dylib         0x21d0 select$DARWIN_EXTSN + 8
1  libsystem_kernel.dylib         0x21d0 __select + 8
2  CoreFoundation                 0xaa740 __CFSocketManager + 648
3  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
4  libsystem_pthread.dylib        0xea0 thread_start + 8

Thread
0  libsystem_pthread.dylib        0xe8c start_wqthread + 258

com.apple.coreaudio.AQClient
0  libsystem_kernel.dylib          0x1504 mach_msg_trap + 8
1  libsystem_kernel.dylib          0x1b9c mach_msg + 76
2  CoreFoundation                  0x7688 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                  0xb97c __CFRunLoopRun + 1212
4  CoreFoundation                  0x1f3b8 CFRunLoopRunSpecific + 600
5  AudioToolbox                    0x1cf25c <redacted> + 164
6  libAudioToolboxUtility.dylib    0x140f8 CADeprecated::CAPThread::Entry(CADeprecated::CAPThread*) + 92
7  libsystem_pthread.dylib         0x19a4 _pthread_start + 148
8  libsystem_pthread.dylib         0xea0 thread_start + 8

Thread
0  libsystem_pthread.dylib        0xe8c start_wqthread + 258

Thread
0  libsystem_kernel.dylib         0x1b2c __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1140 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xe94 start_wqthread + 8

DartWorker
0  libsystem_kernel.dylib         0x1f90 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8280 _pthread_cond_wait + 1272
2  Flutter                        0x5a221c (Missing)
3  Flutter                        0x5e8634 (Missing)
4  Flutter                        0x5a1b44 (Missing)
5  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
6  libsystem_pthread.dylib        0xea0 thread_start + 8

DartWorker
0  libsystem_kernel.dylib         0x1f90 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8280 _pthread_cond_wait + 1272
2  Flutter                        0x5a221c (Missing)
3  Flutter                        0x5e8634 (Missing)
4  Flutter                        0x5a1b44 (Missing)
5  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
6  libsystem_pthread.dylib        0xea0 thread_start + 8
```

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale fr-FR)
    • Flutter version 2.8.1 at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Users/foxtom/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • CPH1931 (mobile) • ee9b32b5 • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos    • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/95568#issue-1084883468 ios release arm64

**Comment by darshankawar** [comment]
@flutter-symbolizer-bot #95568 (comment) ios release arm64 890a5fca2e

**Comment by darshankawar** [comment]
@flutter-symbolizer-bot #95568 (comment) ios release

**Comment by darshankawar** [comment]
@Tom3652 
Does the stack trace shows something like `CrashDoctor Diagnosis:` or `Application Stats` at the end of the trace ?
If so, can you provide the same ?

**Comment by RomainFranceschini** [comment]
@darshankawar hi,
I'm facing a similar issue. Below is a sentry crash report with symbolication https://sentry.io/share/issue/715ae351e141453da7731bb01276b1f9/

**Comment by Tom3652** [comment]
@darshankawar no there is nothing like you show. However, when i check the other 9 crashes with the same error i am getting these differences : 

On one of the crash / 10 i am getting the following as the second trace : 

``` 
com.Metal.CommandQueueDispatch
0  libsystem_kernel.dylib         0x1504 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1b9c mach_msg + 76
2  IOKit                          0x41f4 io_connect_method + 440
3  IOKit                          0x35a4 IOConnectCallMethod + 176
4  IOGPU                          0x34c8 IOGPUCommandQueueSubmitCommandBuffers + 144
5  IOGPU                          0x3820 -[IOGPUMetalCommandQueue _submitCommandBuffers:count:] + 804
6  IOGPU                          0x5148 -[IOGPUMetalCommandQueue submitCommandBuffers:count:] + 88
7  Metal                          0x12f3c -[_MTLCommandQueue _submitAvailableCommandBuffers] + 672
8  libdispatch.dylib              0x4660 _dispatch_client_callout + 20
9  libdispatch.dylib              0x7b34 _dispatch_continuation_pop + 504
10 libdispatch.dylib              0x1ac38 _dispatch_source_invoke + 1356
11 libdispatch.dylib              0xbcbc _dispatch_lane_serial_drain + 376
12 libdispatch.dylib              0xc958 _dispatch_lane_invoke + 392
13 libdispatch.dylib              0x171a8 _dispatch_workloop_worker_thread + 656
14 libsystem_pthread.dylib        0x10f4 _pthread_wqthread + 288
15 libsystem_pthread.dylib        0xe94 start_wqthread + 8
```

in another i am getting both of the followings in the same trace :  

```
JavaScriptCore bmalloc scavenger
0  libsystem_kernel.dylib         0x1f90 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8254 _pthread_cond_wait + 1228
2  libc++.1.dylib                 0x9ddc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  JavaScriptCore                 0x11b21d4 void std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::unique_lock<bmalloc::Mutex>&) + 108
4  JavaScriptCore                 0x11b69a4 bmalloc::Scavenger::threadRunLoop() + 340
5  JavaScriptCore                 0x11b6544 bmalloc::Scavenger::Scavenger(std::__1::scoped_lock<bmalloc::Mutex> const&) + 14
6  JavaScriptCore                 0x11b7a00 std::__1::__thread_specific_ptr<std::__1::__thread_struct>::set_pointer(std::__1::__thread_struct*) + 46
7  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
8  libsystem_pthread.dylib        0xea0 thread_start + 8
```

```
FirebaseWorker
0  libobjc.A.dylib                0x1878 objc_msgSendSuper2 + 24
1  FirebaseDatabase               0x2d1d0 -[FLLRBValueNode initWithKey:withValue:withColor:withLeft:withRight:] + 72
2  FirebaseDatabase               0x2d4a4 -[FLLRBValueNode copyWith:withValue:withColor:withLeft:withRight:] + 380
3  FirebaseDatabase               0x2e590 -[FLLRBValueNode colorFlip] + 404
4  FirebaseDatabase               0x2df04 -[FLLRBValueNode fixUp] + 472
5  FirebaseDatabase               0x2eb98 -[FLLRBValueNode remove:withComparator:] + 1332
6  FirebaseDatabase               0x2e91c -[FLLRBValueNode remove:withComparator:] + 696
7  FirebaseDatabase               0x2e91c -[FLLRBValueNode remove:withComparator:] + 696
8  FirebaseDatabase               0x2e91c -[FLLRBValueNode remove:withComparator:] + 696
9  FirebaseDatabase               0x2eb38 -[FLLRBValueNode remove:withComparator:] + 1236
10 FirebaseDatabase               0x2eb38 -[FLLRBValueNode remove:withComparator:] + 1236
11 FirebaseDatabase               0x2e91c -[FLLRBValueNode remove:withComparator:] + 696
12 FirebaseDatabase               0x5e534 -[FTreeSortedDictionary removeKey:] + 172
13 FirebaseDatabase               0xb99c -[FChildrenNode updateImmediateChild:withNewChild:] + 192
14 FirebaseDatabase               0x18e00 -[FIndexedNode updateChild:withNewChild:] + 116
15 FirebaseDatabase               0x2c930 __57-[FLimitedFilter updateFullNode:withNewNode:accumulator:]_block_invoke + 552
16 FirebaseDatabase               0x19950 __52-[FIndexedNode enumerateChildrenReverse:usingBlock:]_block_invoke + 128
17 FirebaseDatabase               0x5edf4 __67-[FTreeSortedDictionary enumerateKeysAndObjectsReverse:usingBlock:]_block_invoke + 40
18 FirebaseDatabase               0x2d758 -[FLLRBValueNode reverseTraversal:] + 176
19 FirebaseDatabase               0x2d700 -[FLLRBValueNode reverseTraversal:] + 88
20 FirebaseDatabase               0x2d700 -[FLLRBValueNode reverseTraversal:] + 88
21 FirebaseDatabase               0x2d700 -[FLLRBValueNode reverseTraversal:] + 88
22 FirebaseDatabase               0x5ece8 -[FTreeSortedDictionary enumerateKeysAndObjectsReverse:usingBlock:] + 172
23 FirebaseDatabase               0x14c68 -[FImmutableSortedSet enumerateObjectsReverse:usingBlock:] + 156
24 FirebaseDatabase               0x19868 -[FIndexedNode enumerateChildrenReverse:usingBlock:] + 248
25 FirebaseDatabase               0x2c5e0 -[FLimitedFilter updateFullNode:withNewNode:accumulator:] + 892
26 FirebaseDatabase               0x67ba0 -[FViewProcessor generateEventCacheAfterServerEvent:path:writesCache:source:accumulator:] + 1388
27 FirebaseDatabase               0x68390 -[FViewProcessor applyServerOverwriteTo:changePath:snap:writesCache:completeCache:filterServerNode:accumulator:] + 1468
28 FirebaseDatabase               0x67218 -[FViewProcessor applyOperationOn:operation:writesCache:completeCache:] + 1336
29 FirebaseDatabase               0x65c74 -[FView applyOperation:writesCache:serverCache:] + 252
30 FirebaseDatabase               0x53414 -[FSyncPoint applyOperation:toView:writesCache:serverCache:] + 80
31 FirebaseDatabase               0x53920 __53-[FSyncPoint applyOperation:writesCache:serverCache:]_block_invoke + 44
32 CoreFoundation                 0x40664 __NSDICTIONARY_IS_CALLING_OUT_TO_A_BLOCK__ + 24
33 CoreFoundation                 0x5877c -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 208
34 FirebaseDatabase               0x53870 -[FSyncPoint applyOperation:writesCache:serverCache:] + 428
35 FirebaseDatabase               0x59e70 -[FSyncTree applyOperationDescendantsHelper:syncPointTree:serverCache:writesCache:] + 452
36 FirebaseDatabase               0x599fc -[FSyncTree applyOperationHelper:syncPointTree:serverCache:writesCache:] + 188
37 FirebaseDatabase               0x59bb0 -[FSyncTree applyOperationHelper:syncPointTree:serverCache:writesCache:] + 624
38 FirebaseDatabase               0x59bb0 -[FSyncTree applyOperationHelper:syncPointTree:serverCache:writesCache:] + 624
39 FirebaseDatabase               0x598f4 -[FSyncTree applyOperationToSyncPoints:] + 192
40 FirebaseDatabase               0x55b38 -[FSyncTree applyServerOverwriteAtPath:newData:] + 284
41 FirebaseDatabase               0x44568 -[FRepo onDataUpdate:forPath:message:isMerge:tagId:] + 656
42 FirebaseDatabase               0x39588 -[FPersistentConnection onDataPushWithAction:andBody:] + 556
43 FirebaseDatabase               0x35de4 -[FPersistentConnection onDataMessage:withMessage:] + 640
44 FirebaseDatabase               0x10c88 -[FConnection onDataMessage:] + 132
45 FirebaseDatabase               0x10ba4 -[FConnection onMessage:withMessage:] + 300
46 FirebaseDatabase               0x6b838 -[FWebSocketConnection appendFrame:] + 372
47 FirebaseDatabase               0x6b8c8 -[FWebSocketConnection handleIncomingFrame:] + 92
48 FirebaseDatabase               0x4fdd8 __31-[FSRWebSocket _handleMessage:]_block_invoke + 132
49 libdispatch.dylib              0x2914 _dispatch_call_block_and_release + 32
50 libdispatch.dylib              0x4660 _dispatch_client_callout + 20
51 libdispatch.dylib              0xbde4 _dispatch_lane_serial_drain + 672
52 libdispatch.dylib              0xc958 _dispatch_lane_invoke + 392
53 libdispatch.dylib              0x171a8 _dispatch_workloop_worker_thread + 656
54 libsystem_pthread.dylib        0x10f4 _pthread_wqthread + 288
55 libsystem_pthread.dylib        0xe94 start_wqthread + 8
```

This is actually the trace i have provided [here](https://github.com/FirebaseExtended/flutterfire/issues/7642).

All of the remaining trace is the same except the number of Thread or DartWorkers that changes a bit.

**Comment by darshankawar** [comment]
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/95568#issue-1084883468 force ios arm64 release flutter#v2.8.1

**Comment by darshankawar** [comment]
Leaving it open and labeling it for further insights from the team based on above symbolicated crash log.

/cc @chinmaygarde

**Comment by iampawan** [comment]
Facing a similar issue. Looks like it started appearing after the upgrade to Flutter 2.8

**Comment by Tom3652** [comment]
Yes it also started to happen with flutter 2.8 in my case.

**Comment by jmagman** [comment]
Duplicate of https://github.com/flutter/flutter/issues/95459.

**Comment by Tom3652** [comment]
Hello @jmagman, both issues are different in my opinion. 

What makes you think that this is the same please ?

**Comment by kinex** [comment]
I have this crash in my app, but I am not using `camera` -plugin (`camera` not found even from *.lock files).

**Comment by jmagman** [comment]
At first I thought https://github.com/flutter/flutter/issues/95459 wasn't related to the plugin, that there was an overrelease in the message handling logic: 
```
0  libobjc.A.dylib                0x15c8 objc_msgSend + 8
1  Flutter                        0x4ecd60 ___ZL39SetStreamHandlerMessageHandlerOnChannelPU31objcproto20FlutterStreamHandler8NSObjectP8NSStringPU33objcproto22FlutterBinaryMessengerS_PU29objcproto18FlutterMethodCodecS__block_invoke + 628
2  Flutter                        0x3eca8 flutter::PlatformViewIOS::HandlePlatformMessage(std::__1::unique_ptr<flutter::PlatformMessage, std::__1::default_delete<flutter::PlatformMessage> >) + 524

**Comment by ajdll5dev** [comment]
> Facing a similar issue. Looks like it started appearing after the upgrade to Flutter 2.8
> 
> EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000000000006a8
> 
> ```
> Crashed: com.apple.main-thread
> 0  Flutter                        0x3b8404 (Missing)
> 1  Flutter                        0x3e464 (Missing)
> 2  Flutter                        0x3c1f0 (Missing)
> 3  Flutter                        0x3c67ac (Missing)
> 4  Flutter                        0x3c6150 (Missing)
> 5  Flutter                        0x12b2c (Missing)
> 6  Flutter                        0xf1cc (Missing)
> 7  CoreFoundation                 0x2aed8 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 28
> 8  CoreFoundation                 0xc6b8c ___CFXRegistrationPost_block_invoke + 52
> 9  CoreFoundation                 0x99f44 _CFXRegistrationPost + 456
> 10 CoreFoundation                 0x40d44 _CFXNotificationPost + 716
> 11 Foundation                     0x1a628 -[NSNotificationCenter postNotificationName:object:userInfo:] + 96
> 12 UIKitCore                      0xf50e9c -[UIApplication _terminateWithStatus:] + 300
> 13 UIKitCore                      0x63bd14 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 128
> 14 UIKitCore                      0x830c5c -[_UISceneLifecycleMultiplexer forceExitWithTransitionContext:scene:] + 224
> 15 UIKitCore                      0xf4dae4 -[UIApplication workspaceShouldExit:withTransitionContext:] + 212
> 16 FrontBoardServices             0x4fc38 __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke_2 + 80
> 17 FrontBoardServices             0xa6b4 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 240
> 18 FrontBoardServices             0x4fbd0 __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke + 132
> 19 libdispatch.dylib              0x4660 _dispatch_client_callout + 20
> 20 libdispatch.dylib              0x8118 _dispatch_block_invoke_direct + 264
> 21 FrontBoardServices             0xbf94 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 48
> 22 FrontBoardServices             0xb3d4 -[FBSSerialQueue _targetQueue_performNextIfPossible] + 220
> 23 FrontBoardServices             0xf9e4 -[FBSSerialQueue _performNextFromRunLoopSource] + 28
> 24 CoreFoundation                 0xbb020 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
> 25 CoreFoundation                 0xcbce0 __CFRunLoopDoSource0 + 208
> 26 CoreFoundation                 0x6054 __CFRunLoopDoSources0 + 376
> 27 CoreFoundation                 0xb7f4 __CFRunLoopRun + 820
> 28 CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
> 29 GraphicsServices               0x138c GSEventRunModal + 164
> 30 UIKitCore                      0x5196a8 -[UIApplication _run] + 1100
> 31 UIKitCore                      0x2987f4 UIApplicationMain + 2092
> 32 Runner                         0x8424 main + 10 (AppDelegate.swift:10)
> 33 ???                            0x1039a5a24 (Missing)
> ```

I have same issue.

```
Crashed: com.apple.main-thread
0  Flutter                        0x3b8404 (누락)
1  Flutter                        0x3e464 (누락)
2  Flutter                        0x3c1f0 (누락)
3  Flutter                        0x3c67ac (누락)
4  Flutter                        0x3c6150 (누락)
5  Flutter                        0x12b2c (누락)
6  Flutter                        0xf1cc (누락)
7  CoreFoundation                 0x2aed8 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 28
8  CoreFoundation                 0xc6b8c ___CFXRegistrationPost_block_invoke + 52
9  CoreFoundation                 0x99f44 _CFXRegistrationPost + 456
10 CoreFoundation                 0x40d44 _CFXNotificationPost + 716
11 Foundation                     0x1a628 -[NSNotificationCenter postNotificationName:object:userInfo:] + 96
12 UIKitCore                      0xf50e9c -[UIApplication _terminateWithStatus:] + 300
13 UIKitCore                      0x63bd14 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 128
14 UIKitCore                      0x830c5c -[_UISceneLifecycleMultiplexer forceExitWithTransitionContext:scene:] + 224
15 UIKitCore                      0xf4dae4 -[UIApplication workspaceShouldExit:withTransitionContext:] + 212
16 FrontBoardServices             0x4fc38 __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke_2 + 80
17 FrontBoardServices             0xa6b4 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 240
18 FrontBoardServices             0x4fbd0 __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke + 132
19 libdispatch.dylib              0x4660 _dispatch_client_callout + 20
20 libdispatch.dylib              0x8118 _dispatch_block_invoke_direct + 264
21 FrontBoardServices             0xbf94 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 48
22 FrontBoardServices             0xb3d4 -[FBSSerialQueue _targetQueue_performNextIfPossible] + 220
23 FrontBoardServices             0xf9e4 -[FBSSerialQueue _performNextFromRunLoopSource] + 28
24 CoreFoundation                 0xbb020 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
25 CoreFoundation                 0xcbce0 __CFRunLoopDoSource0 + 208
26 CoreFoundation                 0x5fe8 __CFRunLoopDoSources0 + 268
27 CoreFoundation                 0xb7f4 __CFRunLoopRun + 820
28 CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
29 GraphicsServices               0x138c GSEventRunModal + 164
30 UIKitCore                      0x5196a8 -[UIApplication _run] + 1100
31 UIKitCore                      0x2987f4 UIApplicationMain + 2092
32 Runner                         0x77a0 main + 5 (AppDelegate.swift:5)
33 ???                            0x100c11a24 (누락)
```

**Comment by ajdll5dev** [comment]
@iampawan can you share your pubspec.yaml ??

**Comment by CubitSpeed** [comment]
I'm also running into this issue (Flutter 2.8). I'm seeing quite a few crashes.

Happy to share logs from Crashlytics, Sentry, or Xcode (I have crash logs for this in each system)

**Comment by BENALIsalahEDDINE** [comment]
That's good man , keep going!

**Comment by CubitSpeed** [comment]
Downgraded to Flutter 2.5.3 and still having the issue. I think instead this is caused by Firebase deps:

Already linked earlier, but here's that issue (also from @Tom3652):
https://github.com/FirebaseExtended/flutterfire/issues/7642

**Comment by ajdll5dev** [comment]
@CubitSpeed I have same issue. but im not using firebase_database. 
Im upgrade 2.8.1 and change pubspec.yaml like blew.

```

firebase_core: 1.10.0 -> 1.10.5
firebase_messaging: 11.1.0 -> 11.2.3
firebase_analytics: 8.3.4 -> 9.0.3
firebase_crashlytics: 2.3.0 -> 2.4.3
google_mobile_ads: 1.0.1 -> 0.13.6
flutter_local_notifications: 9.1.5 -> 9.1.4
get: 4.6.1 -> 4.3.8
dio: 4.0.4 -> 4.0.3
cached_network_image: 3.2.0 -> 3.1.0+1
reorderables: 0.4.2 -> 0.4.1

```

any idea?

**Comment by dodatw** [comment]
I face same issue on flutter 2.8.1, 
These issue from firebase crashlytics, I cannot reproduce on my side.

```
Crashed: com.apple.main-thread
0  Flutter                        0x3b8404 (Missing)
1  Flutter                        0x3e464 (Missing)
2  Flutter                        0x3c1f0 (Missing)
3  Flutter                        0x3c67ac (Missing)
4  Flutter                        0x3c6150 (Missing)
5  Flutter                        0x12b2c (Missing)
6  Flutter                        0xf1cc (Missing)
7  CoreFoundation                 0x2aed8 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 28
8  CoreFoundation                 0xc6b8c ___CFXRegistrationPost_block_invoke + 52
9  CoreFoundation                 0x99f44 _CFXRegistrationPost + 456
10 CoreFoundation                 0x40d44 _CFXNotificationPost + 716
11 Foundation                     0x1a628 -[NSNotificationCenter postNotificationName:object:userInfo:] + 96
12 UIKitCore                      0xf50e9c -[UIApplication _terminateWithStatus:] + 300
13 UIKitCore                      0x63bd14 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 128
14 UIKitCore                      0x830c5c -[_UISceneLifecycleMultiplexer forceExitWithTransitionContext:scene:] + 224
15 UIKitCore                      0xf4dae4 -[UIApplication workspaceShouldExit:withTransitionContext:] + 212
16 FrontBoardServices             0x4fc38 __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke_2 + 80
17 FrontBoardServices             0xa6b4 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 240
18 FrontBoardServices             0x4fbd0 __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke + 132
19 libdispatch.dylib              0x4660 _dispatch_client_callout + 20
20 libdispatch.dylib              0x8118 _dispatch_block_invoke_direct + 264
21 FrontBoardServices             0xbf94 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 48
22 FrontBoardServices             0xb3d4 -[FBSSerialQueue _targetQueue_performNextIfPossible] + 220
23 FrontBoardServices             0xf9e4 -[FBSSerialQueue _performNextFromRunLoopSource] + 28
24 CoreFoundation                 0xbb020 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
25 CoreFoundation                 0xcbce0 __CFRunLoopDoSource0 + 208
26 CoreFoundation                 0x6054 __CFRunLoopDoSources0 + 376
27 CoreFoundation                 0xb7f4 __CFRunLoopRun + 820
28 CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
29 GraphicsServices               0x138c GSEventRunModal + 164
30 UIKitCore                      0x5196a8 -[UIApplication _run] + 1100
31 UIKitCore                      0x2987f4 UIApplicationMain + 2092
32 Runner                         0xb148 main + 11 (AppDelegate.swift:11)
33 ???                            0x105401a24 (Missing)
```

**Comment by Levi-Lesches** [comment]
I'm not an expert, but this seems related to https://github.com/flutter/flutter/issues/95844, which is supposedly fixed by https://github.com/flutter/engine/pull/30835

**Comment by Tom3652** [comment]
I could not get any zombies for this crash in ```profile``` or ```debug``` mode for now, will do more tests.

**Comment by deepak786** [comment]
@Tom3652 so is this issue resolved in the master branch for now?

**Comment by Tom3652** [comment]
@deepak786 I will make a new release for my app this week and see if this still happen using the master branch, according to this [comment](https://github.com/flutter/flutter/issues/95844#issuecomment-1017857861) there is a good chance it has been fixed indeed.

**Comment by Tom3652** [comment]
I will update here by the end of next week if this was trully fixed, i could not make a new release due to some technical issues in my app, even with the master branch and now stable flutter ```2.10.0```. 

I have updated now my project to the stable release ```2.10.0``` and release my app to my testers today.  
I will give the answer on 11/02/2022 if it's fixed in my case :)

Sorry for the delay

**Comment by Tom3652** [comment]
Alright guys, i have a good and a bad news : 
- Bad news : the crash still exist :( 
- Good news : the crash happens very rarely compared to `flutter: 2.8` 

I have only got 1 crash over a week of tests.  
With `flutter 2.8`, i have got 38 crashes in 2 weeks. 

So thank you for the fix you have made already, it's much more usable than before but still an issue.

![Capture d’écran 2022-02-11 à 16 16 33](https://user-images.githubusercontent.com/32631467/153617759-ed831b22-3771-42fd-a1eb-7d9a61d68646.png)

**Comment by deepak786** [comment]
Same here.
Our app version 2.4.1 is updated with flutter stable 2.10 but still has the crashes.

![Screen Shot 2022-02-11 at 10 12 13 PM](https://user-images.githubusercontent.com/14223997/153632072-d710b03b-6885-4be0-b1a8-525fab0ca846.png)

**Comment by TheJulianJES** [comment]
Does the issue still happen on 2.10.1 for anyone?

**Comment by Tom3652** [comment]
I didn't know that there was already a `2.10.1` @TheJulianJES, is it supposed to fix this issue especially or something else ?  
I am upgrading the project then, but i will have to make more tests to see if this has been fixed.

**Comment by Tom3652** [comment]
I confirm that this is still an issue under `2.10.1` unfortunately

**Comment by Tom3652** [comment]
Guys i am very pleased to tell that so far from `2.10.3` i have no more crashes :) 
Can anyone confirm what i am saying ? 

I will increase a lot the number of beta test users next week and see if this still happens.

**Comment by Tom3652** [comment]
I must say that i have not seen this crash since Flutter `3.0.x`.

**Comment by the-best-is-best** [comment]
Any news

**Comment by Tom3652** [comment]
I keep confirming my last comment, i have not seen this crash in Flutter `3.x.y`.

**Comment by the-best-is-best** [comment]
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x000000000008d208
0
libobjc.A.dylib
objc_msgSend + 56

Flutter 3.16

This means i need to upgrade flutter to 3.24 and upload a new version is it right ?

**Comment by Tom3652** [comment]
Well i would say yes @the-best-is-best in 3.24 I have not gotten this crash even once and i have few thousands daily active users
-> Before that it was with few hundred users and appearing often enough for a crash

**Comment by jmagman** [comment]
Given the author isn't seeing this any more (for years), I'm going close. If you're seeing a crash in your app please file a new issue and completely fill out the template. We now ship iOS and macOS with symbols, so symbolication and triage should be faster now than it was when this was filed.
