### ISSUE TITLE
[iOS] Flutter 2.8, fine frame drop detected in native listview on iOS.

### ISSUE THREAD

**Issue by idompolo** [flutter/flutter#95838]
Flutter 2.8, fine frame drop detected in native listview on iOS.

This is normal in flutter 2.5.

Create a listview with about 200 items.. If you scroll slowly and smoothly at a constant speed, you may find it stuttering.

 2.5 example url : https://drive.google.com/file/d/1v9q2T6m_haEdvbV416rC9bhObAZ4HHFy/view?usp=sharing
 2.8 example url : https://drive.google.com/file/d/1_1Xq7Fw03AaSKGQ3DA6OIQjKYQN7mR9i/view?usp=sharing

<details>
<summary>sample code </summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const App());
}

class App extends StatefulWidget {
  const App({Key? key}) : super(key: key);

  @override
  _AppState createState() => _AppState();
}

class _AppState extends State<App> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text("Flutter 2.8 Test")),
        body: ListView.separated(
          separatorBuilder: (_, __) => const Divider(),
          itemCount: 200,
          itemBuilder: (context, index) {
            return ListTile(
              key: ValueKey(index),
              title: Text("item $index"),
            );
          },
        ),
      ),
    );
  }
}
```
</details>

**Comment by idompolo** [comment]
마스터 버전 (2.9.0--1.0.pre.199) 에서도 마찬가지

**Comment by jiabin87428** [comment]
+1

**Comment by jiabin87428** [comment]
Also in the swipe return

**Comment by hubertqiu** [comment]
Also in the swipe return

**Comment by JangHyun0828** [comment]
+1

**Comment by Ec7i9se** [comment]
Swipe return +1

**Comment by mamuseferha** [comment]
Hi @idompolo, I verified on the latest stable and master channel and it is reproducible.

<details>
<summary>output</summary>

https://user-images.githubusercontent.com/92717368/147560461-93ab5dd2-ae00-484c-9a98-23d97a7d64af.mp4


https://user-images.githubusercontent.com/92717368/147560476-ef96e225-5e68-430b-a95c-a57da4af2d87.mp4



</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /Users/flo/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (12 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 13 (mobile)      • EF1251D3-C9C4-475E-9F91-58CD010FDA48 • ios            •
    • iPhone (mobile)         • 7a7ab8dfee530a7b4f54e3e3c3544a66a506fdae • ios            • iOS 14.4.2 18D70
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)         • macos                                • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```
```bash
[✓] Flutter (Channel master, 2.9.0-1.0.pre.205, on macOS 12.1 21C52 darwin-x64, locale en-US)
    • Flutter version 2.9.0-1.0.pre.205 at /Users/flo/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6ec059c994 (3 hours ago), 2021-12-28 00:29:08 -0500
    • Engine revision 31fcaf3ce4
    • Dart version 2.16.0 (build 2.16.0-134.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 13 (mobile)      • EF1251D3-C9C4-475E-9F91-58CD010FDA48 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • iPhone (mobile)         • 7a7ab8dfee530a7b4f54e3e3c3544a66a506fdae • ios            • iOS 14.4.2 18D70
    • macOS (desktop)         • macos                                • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 93.0.4577.63

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

Thank you

**Comment by chinmaygarde** [comment]
I could not observe a noticeable difference in the movies you attached but maybe this isn't noticeable in the performance overlay. Can you also attach timeline traces places?

**Comment by idompolo** [comment]
> 첨부한 동영상에서는 눈에 띄는 차이를 관찰할 수 없었지만 성능 오버레이에서는 눈에 띄지 않을 수 있습니다. 타임라인 추적도 첨부할 수 있습니까?

It's really funny..
If you build and run the release directly on the iOS device, you will see a clear difference...

**Comment by idompolo** [comment]
> @idompolo 안녕하세요 , 최신 안정 및 마스터 채널에서 확인했으며 재현 가능합니다.
> 
> 산출
> 플러터 닥터 -v
> 감사합니다

Hello
I think this problem is very serious.
I'm currently hesitant to upgrade from version 2.5 of flutter.
Is there any action on this issue yet?

**Comment by Ec7i9se** [comment]
Same using 2.10.0-0.1.pre(( Its critical mistake, ios application no longer feels like native

**Comment by nialljawad96** [comment]
Hi - I'm also experiencing this issue - quite noticeable on iOS ListView - not present on Android whatsoever. 
It's occurring for me on iPhone X on Flutter 2.8 - is anyone working on this issue? 
I am going to downgrade to 2.5 to see if this solves the issue.

**Comment by jmagman** [comment]
> Can you also attach timeline traces please?

If you can reproduce this, can you please attach the requested timeline traces? https://docs.flutter.dev/development/tools/devtools/performance

**Comment by b3nni97** [comment]
I also have the lags every animation is affected on iOS. The app is almost unusable. With version 2.5 everything ran 100% smoothly

**Comment by jiabin87428** [comment]
It looks resolved in 2.10

**Comment by jiabin87428** [comment]
> It looks resolved in 2.10

Sorry, in 2.10, the swipe back looks fine, but the list still has problems

**Comment by AlexSmirnov9107** [comment]
same, it still exists in 2.10

**Comment by Ec7i9se** [comment]
Interesting, for me swipe back still laggy in 2.10

**Comment by b3nni97** [comment]
I still have the problem with the latest master version.

I am beginning to suspect that this is a "different" type of jank. It's not that there are long lags but it's really just micro lags. 
There are some open issues which show exactly the same micro lagging.
(#95838, #95986, #97998)

Is it possible that this is due to any changes from the iOS side? I am having a hard time finding these lags in the profiler.

**Comment by desmeit** [comment]
I have this jank issue especially with a page transition with ZoomPageTransitionsBuilder.
But its extremely if I push from Appbar or bottomNavigationBar.
If I push from inside the tab there is no jank.

**Comment by jmagman** [comment]
> > Can you also attach timeline traces please?
>
> If you can reproduce this, can you please attach the requested timeline traces? https://docs.flutter.dev/development/tools/devtools/performance

**Comment by desmeit** [comment]
@jmagman please check my devtools screenshot there are massive janks during a push from the appbar.
SkSL warmup does not help here either. the jank is always there.
do you need the devtools json file or anything else?

![Bildschirmfoto 2022-02-10 um 10 10 02](https://user-images.githubusercontent.com/9454529/153374759-4760c66a-4a3d-4b63-bb26-7efe70db8f36.png)

**Comment by jmagman** [comment]
> do you need the devtools json file or anything else?

Yes, we need the trace data.

**Comment by jiabin87428** [comment]
> > do you need the devtools json file or anything else?
> 
> Yes, we need the trace data.

Any results? No matter how the trace data shows, the SDK after Flutter 2.8 is really not smooth looks on iOS(long list scrolling and swipe return).
Before 2.8, everything is ok.

**Comment by jiabin87428** [comment]
> > do you need the devtools json file or anything else?
> 
> Yes, we need the trace data.

Here is a list page in my project, you can see in 2.10.1, when you drag with different swipe speeds, there will be slight jumps in the display content, but in 2.5, it's ok.
Flutter 2.10.1 url: https://drive.google.com/file/d/19t6R0z7Ji2eNv3FV6EVVSQRYee5y2LeC/view?usp=sharing
Flutter 2.5 url: https://drive.google.com/file/d/1bM19B_fHe9t8aiW0XRhrdQPFKQEArf_x/view?usp=sharing

**Comment by jmagman** [comment]
If you can reproduce this, please attach the requested timeline traces. We only have one from @desmeit so far (thank you!).  The more of them we have the easier it is to diagnose if they are the same issues, or if this needs to be split this up into different causes. https://docs.flutter.dev/development/tools/devtools/performance

**Comment by b3nni97** [comment]
Hi because my app is very laggy in lists I tried to identify the problem (I thought maybe the problem occurs only in combination with a certain widget).

I have tried 2 attempts: 

With different texts (see video 1) you can see at the beginning that actually each frame has enough time to build. Only when the list runs slower you see that there are many spikes at the end. 
Trace: 
[different-texts-trace.zip](https://github.com/flutter/flutter/files/8076275/different-texts-trace.zip)
Video: 
https://drive.google.com/file/d/1RvGvjjHRYKMHjIei5V2gf2fNECHopaTe/view?usp=sharing


But now I discovered that there are also these microlags with same texts. But these do NOT show up in the profiler anymore. The lags appear less often but they are live in any case noticeable. (Hard to see in the video, Keep an eye on it when the list is about 1 second before stop, there you see a few lags ).
Trace:
[same-texts-trace.zip](https://github.com/flutter/flutter/files/8076324/same-texts-trace.zip)
Video:
https://drive.google.com/file/d/1gC8Werj3oFX7Ak3L8Mn9PcD4iiAyCzaM/view?usp=sharing


Tested on iPhone 12 Pro Max running iOS 15.3

<details>
  <summary>flutter doctor</summary>

  ```
 Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.11.0-0.0.pre.576, on macOS 11.5.2 20G95 darwin-arm, locale de-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.64.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
  ```
</details>

**Comment by ColdPaleLight** [comment]
fixed by https://github.com/flutter/engine/pull/31513
