### ISSUE TITLE
Maintain scroll location to prevent content jumping when network images or dynamic network content loads into a listview that has already been laid out

### ISSUE THREAD

**Issue by mark8044** [flutter/flutter#99158]
Consider, if there is a listview with a number of variable height Widgets with further contain network image's that load at their own pace.

When the images load the height of each individual listview item widget will change (increase) appropriately

If this set of events occurs above the users current scroll position in the listview, then the content will shift / jump so that the user is now looking at content that was formerly above their last viewed position.  

This gives for bad user experience.

Is it possible to add an option to listviews (or any scrollable view) that the scroll position should maintain itself relative to the bottom extent of the listview when a layout change occurs above the current position or vice versa when it occurs under neath the current position (as it is currently works).  In this way from the user POV, there is not content jumping effect

**Comment by darshankawar** [comment]
@mark8044 
Thanks for the report. In order to address this properly, can you provide `flutter doctor -v`, a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the behavior you reported along with actual vs expected result ?

**Comment by mark8044** [comment]
```
[✓] Flutter (Channel stable, 2.10.3, on macOS 11.6.4 20G417 darwin-x64, locale en-US)
    • Flutter version 2.10.3 at /Users//Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (5 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users//Library/Android/sdk
    • Platform android-31, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Connected device (1 available)
    • iPhone 13 (mobile) • • ios • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```

```
class Test extends StatelessWidget {
  const Test({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ListView(
      children: [
        Text('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sodales mi vel nisi efficitur, sed sollicitudin orci dictum. Phasellus pellentesque ex et libero accumsan porttitor. Ut at enim ex. Nam ultrices risus massa, et tempor lectus finibus eu. Phasellus varius lorem ante, vitae varius nisi elementum nec. Vestibulum blandit ut metus at ultrices. Fusce rhoncus mi enim, a gravida enim egestas ac. Duis nec consequat lectus. Integer vulputate metus ac neque molestie dignissim. Integer lacinia congue nulla molestie elementum. Nulla quis eleifend tortor. In ac nisi ligula. Proin laoreet, metus in ornare tristique, orci lorem aliquet magna, id finibus nisi libero id erat.\n\n'),
        Text('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sodales mi vel nisi efficitur, sed sollicitudin orci dictum. Phasellus pellentesque ex et libero accumsan porttitor. Ut at enim ex. Nam ultrices risus massa, et tempor lectus finibus eu. Phasellus varius lorem ante, vitae varius nisi elementum nec. Vestibulum blandit ut metus at ultrices. Fusce rhoncus mi enim, a gravida enim egestas ac. Duis nec consequat lectus. Integer vulputate metus ac neque molestie dignissim. Integer lacinia congue nulla molestie elementum. Nulla quis eleifend tortor. In ac nisi ligula. Proin laoreet, metus in ornare tristique, orci lorem aliquet magna, id finibus nisi libero id erat.\n\n'),

        Image.network('https://repository-images.githubusercontent.com/31792824/fb7e5700-6ccc-11e9-83fe-f602e1e1a9f1'),

        Text('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sodales mi vel nisi efficitur, sed sollicitudin orci dictum. Phasellus pellentesque ex et libero accumsan porttitor. Ut at enim ex. Nam ultrices risus massa, et tempor lectus finibus eu. Phasellus varius lorem ante, vitae varius nisi elementum nec. Vestibulum blandit ut metus at ultrices. Fusce rhoncus mi enim, a gravida enim egestas ac. Duis nec consequat lectus. Integer vulputate metus ac neque molestie dignissim. Integer lacinia congue nulla molestie elementum. Nulla quis eleifend tortor. In ac nisi ligula. Proin laoreet, metus in ornare tristique, orci lorem aliquet magna, id finibus nisi libero id erat.\n\n'),
        Text('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sodales mi vel nisi efficitur, sed sollicitudin orci dictum. Phasellus pellentesque ex et libero accumsan porttitor. Ut at enim ex. Nam ultrices risus massa, et tempor lectus finibus eu. Phasellus varius lorem ante, vitae varius nisi elementum nec. Vestibulum blandit ut metus at ultrices. Fusce rhoncus mi enim, a gravida enim egestas ac. Duis nec consequat lectus. Integer vulputate metus ac neque molestie dignissim. Integer lacinia congue nulla molestie elementum. Nulla quis eleifend tortor. In ac nisi ligula. Proin laoreet, metus in ornare tristique, orci lorem aliquet magna, id finibus nisi libero id erat.\n\n'),

      ],
    );
  }
}
```
Here in this listview, when the lsitview is first shown you see the four blocks of `Lorem ipsum` text next to each other
- When the Network.image loads, then the 3rd&4th paragraphs moves downward (appropriately)

**Question here is: Can it be reversed somehow where the 1st&2nd paragraphs actually move upward?**

For example, maintain the `.extentAfter` somehow.

I myself tried to manually adjust the `ScrollController.position` by doing a `ScrollController.jumpTo` as soon as the image loads, but unfortunately there is a very slight but minimal glitch perceived by the user as the image pushes down and then the screen jumps down to match its old position

**Comment by darshankawar** [comment]
@mark8044 
Please check below issues and see if they help.

https://github.com/flutter/flutter/issues/40340
https://github.com/flutter/flutter/issues/63946

**Comment by mark8044** [comment]
@darshankawar Unfortunately those two refer to to different scenarios to this one

#40340 refers to maintaining a scrollview position between states using a PageStorageKey
#63946 refers to scroll position when adding (or removing) listview items

The case I'm describing is a dynamic change in a Container (or otherwise) height which then affects the Listview item height pushing the content to a different location from the current scrollview location, giving an unpleasant experience.  

In the HTML/CSS world this effect has sometimes been called Layout Jank (https://css-tricks.com/the-fight-against-layout-jank/) which has been addressed with various forms of scroll anchoring (https://blog.chromium.org/2017/04/scroll-anchoring-for-web-developers.html) 

https://www.youtube.com/watch?time_continue=15&v=-Fr-i4dicCQ&feature=emb_title

**Comment by darshankawar** [comment]
Thanks for the update. 

> **Question here is: Can it be reversed somehow where the 1st&2nd paragraphs actually move upward?**
> 
> For example, maintain the `.extentAfter` somehow.
> 
> I myself tried to manually adjust the `ScrollController.position` by doing a `ScrollController.jumpTo` as soon as the image loads, but unfortunately there is a very slight but minimal glitch perceived by the user as the image pushes down and then the screen jumps down to match its old position
> 
> Maybe a `ScrollPhysics` could address this case?

I'll keep this issue open and label it for further insights on potential solution to address maintaining scroll location.

/cc @Piinks

**Comment by Piinks** [comment]
I think the scroll position change is inevitable because the content of the list view changes. For example, if we are at a scroll position of 10 pixels down, and a picture 50 pixels tall above loads, the position of 10 is not longer the same location as it was before - you would want it to adjust to 60.

Scroll position is not content aware, so I don't know that it would be possible for the scroll position to accurately and reliably recalculate where the position 'should' be when the content of the list view is dynamically changing. Similarly, the ListView does not know anything about its children, it does not have specific knowledge of various widgets and does not treat them differently based on what they are.

Have you tried this with the `ListView.builder` constructor? The snippet of code you provided above does not lazily build its children. Using a builder may improve performance since it won't be building those images that are out of view.

You can also try using `ListView.itemExtent` or `ListView.prototypeItem` to better control the length of the list and the calculation of the extent.

**Comment by mark8044** [comment]
> I think the scroll position change is inevitable because the content of the list view changes. For example, if we are at a scroll position of 10 pixels down, and a picture 50 pixels tall above loads, the position of 10 is not longer the same location as it was before - you would want it to adjust to 60.
> 
> Scroll position is not content aware, so I don't know that it would be possible for the scroll position to accurately and reliably recalculate where the position 'should' be when the content of the list view is dynamically changing. Similarly, the ListView does not know anything about its children, it does not have specific knowledge of various widgets and does not treat them differently based on what they are.
> 
> Have you tried this with the `ListView.builder` constructor? The snippet of code you provided above does not lazily build its children. Using a builder may improve performance since it won't be building those images that are out of view.
> 
> You can also try using `ListView.itemExtent` or `ListView.prototypeItem` to better control the length of the list and the calculation of the extent.

Yes I usually use .builder, I just put that example there to demonstrate the concept for triage reasons, but I think most people understand the issue as you demonstrated.  

Regardless of what kind of listview we use, an image will load at the speed the network allows and this kind of jank is inevitable if either flutter or us developers can control these page jumps.

The point here is to try to elevate Flutter.  Tackling this kind of scroll jank sets browsers and websites apart from the rest.

Why not here as well?   So much of Flutter is based around smooth UI, this kind of jank stands out a bit in 2022

If unwilling, how about opening up paths for us to deall with this issue?  Every attempt I've tried to make to compensate the page scroll position based on image load fails because there will always be a 1 frame difference between when the image is presented and when the scrollcontroller jumpTo can be executed, resulting in an every so slight 'glitch' seen on screen as the image loads and position jumps, which is at least equally if not more unappealing as the layout jank or cumulative layout shift or whatever you want to call it.

In terms of UI/UX I would consider this a major issue-- Google's own Core Web Vitals initiative: https://web.dev/cls/

Thank you!

**Comment by Piinks** [comment]
> If unwilling, how about opening up paths for us to deall with this issue?

I don't think that anyone is unwilling to resolve this issue, it is currently open. Flutter too is also an open project, and all contributions are welcome from anyone that wishes to do so. If that is something you are interested in, please see our [contributing guide](https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md). 

I just remembered there is a widget of the week video for this exact use case though, I hope it is of some help to your use case: https://youtu.be/pK738Pg9cxc

**Comment by mark8044** [comment]
> > If unwilling, how about opening up paths for us to deall with this issue?
> 
> I don't think that anyone is unwilling to resolve this issue, it is currently open. Flutter too is also an open project, and all contributions are welcome from anyone that wishes to do so. If that is something you are interested in, please see our [contributing guide](https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md).
> 
> I just remembered there is a widget of the week video for this exact use case though, I hope it is of some help to your use case: https://youtu.be/pK738Pg9cxc

I wish I was talented enough to contribute a fix for this, for now all I can contribute is the identification of UI issues and some ***hope***.  That someone has an idea for this issue.  Best general idea could come up with is that ScrollPhysics might tackle this?

TBH, I was able to do a hacky, but pixel perfect, correction for the issue by monitoring the size of the widget for changes.  When the widget changed size, the function would calculate the difference between the old widget size and new widget size and then move the scrollcontroller position down by that many pixels using `jumpTo`.  The main issue is the timing of that series of events.  In reality, what is happening is that the image loads, pushes content down and then the `jumpTo` is fired  sequentially rather then simultaneously so there is a frame delay with that.  I ended up throwing it in the trash bin because it is a hack and the frame shift is just as bad as a the core problem in terms of a smooth and professional UI experience.

That `FadeInImage` widget won't work because the crux of the problem here is that the image size isn't known until after it is retrieved, and really the problem applies to more then just images, any kind of dynamic content change will result in the same effect.  Framing all images in a one size fits all box ahead of time also skirts the issue, but is not a viable solution if you want to display images in their true dimensions.

**Comment by DennisAshford** [comment]
Has there been any progress on this issue? I am experiencing the same issue, as are many others. It makes the UI of the Flutter app very janky on scrolling up in a ListView.

**Comment by gdagitrep** [comment]
Not sure if you are interested, but you may be able to address this issue by wrapping the image in a fix size Widget, so when the image loads up, it doesn't expand beyond that size.
If you are looking for different sized images to show up to remove monotonicity, you can fake that kind of behavior using different sized (but fixed size) Widgets in the ListView, and let images load up in those different sized Widgets, irrespective for their own size. Anyway, it won't be a good design to show the full size image.

**Comment by mark8044** [comment]
> Not sure if you are interested, but you may be able to address this issue by wrapping the image in a fix size Widget, so when the image loads up, it doesn't expand beyond that size.
> If you are looking for different sized images to show up to remove monotonicity, you can fake that kind of behavior using different sized (but fixed size) Widgets in the ListView, and let images load up in those different sized Widgets, irrespective for their own size. Anyway, it won't be a good design to show the full size image.

Not a reasonable solution, that is just a hack to fake it

**Comment by jinyuanqing** [comment]
The same problem happened to me, too

**Comment by hgraceb** [comment]
I spent a whole week dealing with this issue. At first, I tried using `ScrollPhysics.adjustPositionForNewDimensions` and `ScrollPosition.jumpTo`, but both had obvious stuttering. However, before I was about to give up on my career as a programmer, I came up with a relatively perfect solution inspired by [scrollable_positioned_list](https://github.com/google/flutter.widgets/blob/656f058b957b79cdae6e6f83bbdb9f3545fa6a52/packages/scrollable_positioned_list/lib/src/positioned_list.dart#L172). The code was a bit more involved, but I can briefly explain the idea:

1. Use a `CustomScrollView` that contains three `SliverList` and set the center.
2. Use a `GlobalKey` to wrap each list item.
3. Detect position changes and change the center `SliverList` content.
4. Use the `ScrollPosition.correctBy` method to correct the list's position. 

By the way, with the idea in mind, it should only take a few hours to achieve a perfect effect, except for the problem of some images being reloaded when scrolling quickly. So, half of the time I was dealing with this problem, and I finally found out that this was caused by didChangeDependencies and ScrollAwareImageProvider, which I solved by copying the Image source code. 

My time and ability are limited, so I can only briefly mention the solution I came up with. I hope it helps those who need it.

**Comment by mark8044** [comment]
> I spent a whole week dealing with this issue. At first, I tried using `ScrollPhysics.adjustPositionForNewDimensions`, `ScrollPosition.jumpTo`, `ScrollPosition.correctPixels`, and `RenderSliver.centerOffsetAdjustment` but all of them had obvious stuttering or other issues. However, before I was about to give up on my career as a programmer, I came up with a relatively perfect solution inspired by [scrollable_positioned_list](https://github.com/google/flutter.widgets/blob/656f058b957b79cdae6e6f83bbdb9f3545fa6a52/packages/scrollable_positioned_list/lib/src/positioned_list.dart#L172). The code was a bit more involved, but I can briefly explain the idea:
> 
> 1. Use a `CustomScrollView` that contains three `SliverList` and set the center.
> 2. Use a `GlobalKey` to wrap each list item.
> 3. Detect position changes and change the center `SliverList` content.
> 4. Use the `ScrollPosition.correctBy` method to correct the list's position.
> 
> By the way, with the idea in mind, it should take a day or two to achieve a relatively perfect effect, except for the problem of some images being reloaded when scrolling quickly. So, half of the time I was dealing with this problem, and I finally found out that this was caused by `Image.didChangeDependencies` and `ScrollAwareImageProvider`, which I solved by copying the `Image` source code.
> 
> My time and ability are limited, so I can only briefly mention the solution I came up with. I hope it helps those who need it.

This sounds very cool.  I think I understand how you did it from your description.  I tried something very similar using two sliver lists, but ultimately still failed because of how I loaded the data into the  slivers.  The idea of 3 slivers is very intriguing, but I'm not exactly sure what content you are putting in what.

You should turn your idea into a package, it sounds pretty good....!

**Comment by mark8044** [comment]
> > This sounds very cool. I think I understand how you did it from your description. I tried something very similar using two sliver lists, but ultimately still failed because of how I loaded the data into the slivers. The idea of 3 slivers is very intriguing, but I'm not exactly sure what content you are putting in what.
> > I ended up making a future builder that loads the images and then gets the image size. Using that and using scrollposition.correctby method I could flawlessly make the correction jumps, even while the user is scrolling. I got caught up because Im not exactly sure if I'm making two image calls (one to get the image, and the other to get the size) and every so often my triggers to make a pixel correction were not correct, because the image was not exactly above the current scroll location (the image comes in as the user is scrolling, or my app is doing an automatic scroll to a position).
> > So while I got 95% to the solution, it sounds like you have gotten to 100% of the solution? You way sounds better.
> > You should turn your idea into a package, it sounds pretty good.... and I would love to try it!
> 
> Alright, I didn't originally want to make it a package. You know, packages usually require stronger robustness, and I needed to spend more time programming and testing. I spent a week uploading a package before, but not many people liked it, which made me feel a little sad. I copied the code I was using in my own project, and uploaded it to https://github.com/hgraceb/flop_list_view and https://pub.dev/packages/flop_list_view. However, it's worth mentioning that only the basic usage works, and there are still many areas that haven't been handled yet, so you may encounter various problems. I will spend more time later to improve it, it's not an easy thing to do. I think my idea can be expressed more clearly through the code, I hope you will like it.

It looks very cool!  

It is missing many of the other things listview.builder has such as controller, shrink-wrap, cache extent, etc... could all the usual listview options be exposed in your implementation?

**Comment by hgraceb** [comment]
> It looks very cool!
> 
> It is missing many of the other things listview.builder has such as controller, shrink-wrap, cache extent, etc... could all the usual listview options be exposed in your implementation?

I'm sorry, but currently there are many options that have not been provided because I am currently working on the issue of unexpected bounces when jumping. Being able to jump to a specific position in the list is more important to me than these options. I am currently working on this issue, so I do not have any extra time to test and provide more options at this time.

**Comment by khomin** [comment]
In android you can insert items in any direction
the view stays still!!
and you can scroll to new items (if you need)
so somehow they know how to do it

**Comment by megur0** [comment]
In a similar case, with SingleChildScrollView I tried the implementation.
I tried to make the offset not change with the size change of SingleChildScrollView child.
I did this by making subclass for ScrollPosition and related class.
It may not answer this issue, but it might be of some help. 
Below is my program.

I think you can do the same with ListView.
But for ListView there are more considerations.
The ListView calculates the entire scroll extent from the current "cache area" extent. 
Therefore, it often happens that the entire scroll extent (not the exact value but the calculated value) changes just by moving the scroll of the UI.  may related #97676 
Therefore, for ListView,  I think we cannot take the way that the ScrollPosition subclass adjusts the offset at any time, as in my below implementation of SingleChildScrollView. This is because it is not clear whether the change in extent is due to child content or due to re-computation.
To achieve this with ListView, one possible method is to prepare a callback that is processed at the timing of applyContentDimensions or applyNewDimensions in the ScrollPosition subclass, and the programmer using ListView can adjust the extent within that callback. Let that callback run when you need it, for example, it can be done immediately after loading "Image.network" or after loading additional data with infinite scroll that changes the dimensions of the content.

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late final CustomScrollController scrollController;

  @override
  void initState() {
    super.initState();
    scrollController =
        CustomScrollController(maintainScrollPositionAtExtentChange: true);
    scrollController.isEndScrollAtInitial = true;
  }

  @override
  void dispose() {
    scrollController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          backgroundColor: Theme.of(context).colorScheme.inversePrimary,
          title: Text(widget.title),
        ),
        body: SingleChildScrollView(
          controller: scrollController,
          child: Column(
            children: [/*  Some widget that changes extent such as Image.network */],
          ),
        ));
  }
}

/// I needed to create the [CustomScrollController] to use [CustomScrollPositionWithSingleContext].
class CustomScrollController extends ScrollController {
  CustomScrollController({
    super.initialScrollOffset,
    super.keepScrollOffset,
    super.debugLabel,
    this.maintainScrollPositionAtExtentChange = false,
    this.isEndScrollAtInitial = false,
  });

  /// [maintainScrollPositionAtExtentChange] be used to maintain 
  /// scroll offset when extent changes.
  /// [isEndScrollAtInitial] be used to set an offset to the end of 
  /// the scroll range at the initial time. I don't want to use the
  /// jump method because it has to be called inside the 
  /// addPostFrameCallback and the scroll movement is drawn on 
  /// the screen.
  bool maintainScrollPositionAtExtentChange = false;
  bool isEndScrollAtInitial = false;

  @override
  ScrollPosition createScrollPosition(
    ScrollPhysics physics,
    ScrollContext context,
    ScrollPosition? oldPosition,
  ) {
    return CustomScrollPositionWithSingleContext(
      physics: physics,
      context: context,
      initialPixels: initialScrollOffset,
      keepScrollOffset: keepScrollOffset,
      oldPosition: oldPosition,
      debugLabel: debugLabel,
      maintainScrollPositionAtExtentChange:
          maintainScrollPositionAtExtentChange,
      forceToEndScroll: isEndScrollAtInitial,
    );
  }
}

class CustomScrollPositionWithSingleContext
    extends ScrollPositionWithSingleContext
    implements CustomScrollActivityDelegate {
  CustomScrollPositionWithSingleContext({
    required super.physics,
    required super.context,
    double? initialPixels,
    super.keepScrollOffset,
    super.oldPosition,
    super.debugLabel,
    this.maintainScrollPositionAtExtentChange = false,
    this.forceToEndScroll = false,
  });

  bool _needsToRelayoutAfterApplyContentDimensions = false;
  ScrollMetrics get oldScrollMetrics => _oldScrollMetrics!;
  ScrollMetrics? _oldScrollMetrics;
  bool maintainScrollPositionAtExtentChange = false;
  bool forceToEndScroll = false;

  @override
  bool applyContentDimensions(double minScrollExtent, double maxScrollExtent) {
    _oldScrollMetrics = copyWith();
    bool ret = super.applyContentDimensions(minScrollExtent, maxScrollExtent);

    // This causes the RenderViewport's performLayout to re-layout by returning the result as false.
    if (maintainScrollPositionAtExtentChange &&
        _needsToRelayoutAfterApplyContentDimensions) {
      _needsToRelayoutAfterApplyContentDimensions = false;
      return false;
    }
    return ret;
  }

  @override
  void applyNewDimensions() {
    if (maintainScrollPositionAtExtentChange &&
        _oldScrollMetrics != null &&
        _oldScrollMetrics!.hasContentDimensions &&
        maxScrollExtent != _oldScrollMetrics!.maxScrollExtent) {
      final double correctValue =
          maxScrollExtent - _oldScrollMetrics!.maxScrollExtent;
      if (activity != null && activity! is CustomBallisticScrollActivity) {
        /// While the scroll animation is running, 
        /// in other words, while the activity is running,
        /// Every frame the offset is overwritten by the activity. 
        /// So we need to override the animation itself that runs 
        /// in this activity.
        correctPositionDuringBallisticScrollActivity(correctValue);
      } else {
        correctPixels(pixels + correctValue);
      }
      _needsToRelayoutAfterApplyContentDimensions = true;
    }
    if (forceToEndScroll) {
      correctPixels(maxScrollExtent);
      forceToEndScroll = false;
    }
    super.applyNewDimensions();
  }

  /// Function only to replace [BallisticScrollActivity] with
  /// [CustomBallisticScrollActivity]
  @override
  void goBallistic(double velocity) {
    assert(hasPixels);
    final Simulation? simulation =
        physics.createBallisticSimulation(this, velocity);
    if (simulation != null) {
      beginActivity(CustomBallisticScrollActivity(
        this,
        simulation,
        context.vsync,
        activity?.shouldIgnorePointer ?? true,
      ));
    } else {
      goIdle();
    }
  }

  /// Replaces the current activity's simulation with the corrected value of offset.
  @override
  void goBallisticWithCorrectedPixel(double velocity, double value) {
    assert(hasPixels);
    if (value <= 0) {
      return;
    }
    double correctedPixel = pixels + value;
    final Simulation? simulation = physics.createBallisticSimulation(
        copyWith(pixels: correctedPixel), velocity);

    if (simulation != null) {
      correctPixels(simulation.x(0.0));
      beginActivity(CustomBallisticScrollActivity(
        this,
        simulation,
        context.vsync,
        activity?.shouldIgnorePointer ?? true,
      ));
    } else {
      goIdle();
    }
  }

  void correctPositionDuringBallisticScrollActivity(double pixels) {
    assert(activity! is CustomBallisticScrollActivity);
    (activity as CustomBallisticScrollActivity)
        .applyNewDimentionsWithCorrect(pixels);
  }
}

/// Implemented just to use the [applyNewDimentionsWithCorrect] function
class CustomBallisticScrollActivity extends BallisticScrollActivity {
  CustomBallisticScrollActivity(
    CustomScrollActivityDelegate delegate,
    Simulation simulation,
    TickerProvider vsync,
    bool shouldIgnorePointer,
  )   : changealbeDelegate = delegate,
        super(delegate, simulation, vsync, shouldIgnorePointer);

  CustomScrollActivityDelegate changealbeDelegate;

  void applyNewDimentionsWithCorrect(double value) {
    changealbeDelegate.goBallisticWithCorrectedPixel(velocity, value);
  }
}

/// Implemented just to provide an abstraction for
///  [goBallisticWithCorrectedPixel].
abstract class CustomScrollActivityDelegate extends ScrollActivityDelegate {
  void goBallisticWithCorrectedPixel(double velocity, double pixel);
}
```

**Comment by rjcalifornia** [comment]
> I think you can do the same with ListView. But for ListView there are more considerations. The ListView calculates the entire scroll extent from the current "cache area" extent. Therefore, it often happens that the entire scroll extent (not the exact value but the calculated value) changes just by moving the scroll of the UI. Therefore, for ListView, I think we cannot take the way that the ScrollPosition subclass adjusts the offset at any time, as in my below implementation of SingleChildScrollView. This is because it is not clear whether the change in extent is due to child content or due to re-computation. To achieve this with ListView, one possible method is to prepare a callback that is processed at the timing of applyContentDimensions or applyNewDimensions in the ScrollPosition subclass, and the programmer using ListView can adjust the extent within that callback. Let that callback run when you need it, for example, it can be done immediately after loading "Image.network" or after loading additional data with infinite scroll that changes the dimensions of the content.

I do appreciate the effort but this is really bad. This doesn't happen in Kotlin or React Native. 

Does anyone knows how other major projects tackle this?

**Comment by cateyelow** [comment]
try cacheExtent 5000

```
ListView.builder(
  cacheExtent: 5000,
  …
),
```

**Comment by tiyberius** [comment]
I was experiencing the issue that @mark8044 described in the original post and I can confirm that this fix works! It should be noted that the units are in pixels, *not* items.

**Comment by SongRongLee** [comment]
I'm experiencing the same issue here, trying to create a twitter like experience.

When we scroll up in a normal `ListView.builder`, the items previously disposed are building back on top of the list, causing the scrolling to be janky.

What's worse is, if the placeholders (like loaders) of new items are "taller" than the actual loaded content, causing items shrink after loaded, the new items might become out-of-range again, and jumping indefinitely.

**Comment by fyxtc** [comment]
@SongRongLee Yes, very bad, hope they can solve it quickly

**Comment by jinyuanqing** [comment]
i have a idea.把其中的内容作为widget即可

**Comment by iulian0512** [comment]
still occuring.

**Comment by avocadohooman** [comment]
Same issue here unfortunately

**Comment by sohneg** [comment]
I also have this issue. Sadly no fix right now except for the cacheExpand: 5000

**Comment by avocadohooman** [comment]
> Same issue here unfortunately

I fixed it in my case, giving each element in my reorderable list view list (they are feature widgets) a fixed height. this seems to have fixed the issue.

**Comment by cateyelow** [comment]
@avocadohooman yeah this issue has occured because of dynamic height and content element. When i used Future Builder with ListView, i faced the issue

**Comment by OptimisticSean** [comment]
I've been exploring Flutter recently for rewriting a React Native app, and I've enjoyed it a lot (so much easier to set up, and the dev tools are great compared to RN), but was surprised that this isn't currently implemented. Scroll anchoring is available in RN when maintainVisibleContentPosition is set to true on a ScrollView/FlatList, and it's also the default behavior in most browsers. Having this available in Flutter so that people don't have to do some little hacks themselves would be a wonderful enhancement.

**Comment by Mikephii** [comment]
Pretty crazy that this still isnt adressed with a new listview.builder widget. nearly every networked application with scrolling requires paginating above and below as the user scrolls. does this mean infinite scroll is not possible in flutter without jank?

**Comment by Mikephii** [comment]
Ive found a solution that works in principle and might be useful for anyone visiting this issue and perhaps could be useful for the flutter team in providing an official widget. 

it implements virtual scrolling similar to : https://blog.logrocket.com/virtual-scrolling-core-principles-and-basic-implementation-in-react/

basically there is only ever max N elements in the list, when new elements are added to the front of the list, overflow is popped off the back of the list and vice versa. 

it supports dynamically sized items and maintains the view position of the item in the view

ive provided the code here as a working example of the logic in principle, its a mess and im sure there is some unforseen performance issues i havent taken into account. 

The core logic is as follows:

- the position in px of an element in the view is:  elViewPos = elPositionInList - scrollPosOfController(the top of the view as a pos in the list)
- likewise to determine the correct scrollPosition of the controller to position an element at a particular screen position we can scrollPosOfController = elPositionInList - desiredViewPos
- so to place an element at a particular desiredPosition all we need to know is where it starts in the list based on the item extents
- We find the first visible element in the list in the scrollListener and track its view position as our anchor element (we want to return to this element when we update the list)
- We provide items with fixed heights (but they can all be different heights) and ensure that the items dont change their heights on their own
- if we do want to update an item in the list, we have to pass an entire new list of items to the list ( i think this is ok because we are only every holding a small amount of items and a rebuild only rebuilds visible items)
- in didWidgetUpdate when we receive the new list of items, we locate our anchor item by its id in the new list of items, and track how far in px it is down the list, then we recenter this item to the screen position that it was in before we updated the list

heres an example using randomly sized boxes that are added at the start and end of the list without jittering

excuse the slightly stuttery scrolling, thats its own seperate issue for flutter scrolling jank caused by un-animated scroll position changes from scrollwheels as tracked by [https://github.com/flutter/flutter/issues/32120](url)

![CleanShot 2024-08-22 at 14 58 30](https://github.com/user-attachments/assets/3129c0a1-403c-4258-bcd3-21741d7db0b2)


```import 'dart:math';
import 'package:flutter/material.dart';


class TestScreen extends StatelessWidget {
  const TestScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Parent(),
    );
  }
}

class Parent extends StatefulWidget {
  const Parent({super.key});

  @override
  State<Parent> createState() => _ParentState();
}

class _ParentState extends State<Parent> {
  List<ListItem> myItems = [];

  static const maxItems = 20;
  bool autoAddOnScroll = false;

  ListItem _buildRandomHeightItem(int id) {
    double height = Random().nextInt(64) + 64; // min height of 64 max of 128

    return ListItem(
      id: id,
      child: Container(
        color: Colors.primaries[id % Colors.primaries.length],
        height: height,
        child: Center(
          child: Text('Item $id'),
        ),
      ),
      extent: height,
    );
  }

  @override
  void initState() {
    myItems = List.generate(
      maxItems,
      (index) => _buildRandomHeightItem(index),
    );
    super.initState();
  }

  addItemsToStartOfList(int n) {
    List<ListItem> newItems = List.from(myItems);
    int currentStartingId = myItems.isEmpty ? 0 : myItems.first.id;
    newItems.insertAll(
      0,
      List.generate(
        n,
        (index) => _buildRandomHeightItem(currentStartingId - index - 1),
      ).reversed,
    );

    int overflow = newItems.length - maxItems;
    if (overflow > 0) {
      newItems.removeRange(maxItems, maxItems + overflow);
    }
    setState(() {
      myItems = newItems;
    });
  }

  addItemsToEndOfList(int n) {
    List<ListItem> newItems = List.from(myItems);
    int currentEndingId = myItems.isEmpty ? 0 : myItems.last.id;
    newItems.addAll(
      List.generate(
        n,
        (index) => _buildRandomHeightItem(currentEndingId + index + 1),
      ),
    );

    int overflow = newItems.length - maxItems;
    if (overflow > 0) {
      newItems.removeRange(0, overflow);
    }
    setState(() {
      myItems = newItems;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        Column(
          children: [
            ElevatedButton(
              onPressed: () {
                addItemsToStartOfList(5);
              },
              child: Text('Add 5 items to start of list'),
            ),
            ElevatedButton(
              onPressed: () {
                addItemsToEndOfList(5);
              },
              child: Text('Add 5 items to end of list'),
            ),
            Row(
              children: [
                Text('Auto add items on scroll'),
                Switch(
                  value: autoAddOnScroll,
                  onChanged: (value) {
                    setState(() {
                      autoAddOnScroll = value;
                    });
                  },
                ),
              ],
            ),
          ],
        ),
        Expanded(
          child: VirtualScrollList(
            items: myItems,
            onHitBottom: autoAddOnScroll
                ? () {
                    addItemsToEndOfList(5);
                  }
                : null,
            onHitTop: autoAddOnScroll
                ? () {
                    addItemsToStartOfList(5);
                  }
                : null,
          ),
        ),
      ],
    );
  }
}

class ListItem {
  final int id;
  final Widget child;
  final double extent;
  ListItem({required this.child, required this.extent, required this.id});
}

class VirtualScrollList extends StatefulWidget {
  final List<ListItem> items;
  final Function? onHitBottom;
  final Function? onHitTop;
  final double boundaryDetectRange;
  const VirtualScrollList({
    super.key,
    required this.items,
    this.onHitBottom,
    this.onHitTop,
    this.boundaryDetectRange = 100,
  });

  @override
  State<VirtualScrollList> createState() => _VirtualScrollListState();
}

class VisibleItemInfo {
  final int id;
  final double extentFromListStart;
  final double screenPosition;
  VisibleItemInfo({
    required this.id,
    required this.extentFromListStart,
    required this.screenPosition,
  });
}

class _VirtualScrollListState extends State<VirtualScrollList> {
  final ScrollController _scrollController = ScrollController();
  VisibleItemInfo? _anchorItem;

  @override
  void initState() {
    super.initState();
    _scrollController.addListener(_scrollListener);
  }

  @override
  void dispose() {
    _scrollController.removeListener(_scrollListener);
    _scrollController.dispose();
    super.dispose();
  }

  void _scrollListener() {
    // final RenderBox renderBox = context.findRenderObject() as RenderBox;
    // final listViewOffset = renderBox.localToGlobal(Offset.zero);
    final viewportStart = _scrollController.position.pixels;
    // final viewportEnd = viewportStart + renderBox.size.height;

    double currentExtent = 0;
    for (int i = 0; i < widget.items.length; i++) {
      final item = widget.items[i];
      final itemStartExtent = currentExtent;

      if (itemStartExtent > viewportStart) {
        // This item is visible
        final screenPosition = itemStartExtent - viewportStart;
        _anchorItem = VisibleItemInfo(
          id: item.id,
          extentFromListStart: itemStartExtent,
          screenPosition: screenPosition,
        );
        print('Anchor item: ${_anchorItem!.id} at index ${i}');
        print('Screen position: ${_anchorItem!.screenPosition}');
        print('Extent from list start: ${_anchorItem!.extentFromListStart}');
        // print('listview offset ${listViewOffset.dy}');
        break;
      }

      currentExtent += item.extent;
    }
    print("currentExtentToAnchor: $currentExtent");

    if (_anchorItem != null && widget.onHitBottom != null) {
      if (_scrollController.position.pixels >=
          _scrollController.position.maxScrollExtent -
              widget.boundaryDetectRange) {
        widget.onHitBottom!();
      }
    }

    if (_anchorItem != null && widget.onHitTop != null) {
      if (_scrollController.position.pixels <= widget.boundaryDetectRange) {
        widget.onHitTop!();
      }
    }
  }

  void _scrollAnchorItemToItsScreenPosition() {
    if (_anchorItem == null) return;

    // Find the new position of the anchor item in the list (the anchor item has a new index and the total extent has changed)
    double newExtentToAnchor = 0;
    bool foundAnchor = false;
    for (var item in widget.items) {
      if (item.id == _anchorItem!.id) {
        foundAnchor = true;
        break;
      }
      newExtentToAnchor += item.extent;
    }
    print("newExtentToAnchor: $newExtentToAnchor");

    if (!foundAnchor) {
      print('Anchor item not found');
      return;
    }

    // Calculate the new scroll position
    // final RenderBox renderBox = context.findRenderObject() as RenderBox;
    // final listViewOffset = renderBox.localToGlobal(Offset.zero);
    final desiredScreenPosition = _anchorItem!.screenPosition;

    double newScrollPosition = newExtentToAnchor - desiredScreenPosition;

    // Ensure the new scroll position is within bounds
    newScrollPosition = newScrollPosition.clamp(
        0.0, _scrollController.position.maxScrollExtent);

    // Scroll to the new position
    _scrollController.jumpTo(newScrollPosition);

    // // Update the anchor item info
    // _anchorItem = VisibleItemInfo(
    //   id: _anchorItem!.id,
    //   extentFromListStart: newExtentToAnchor,
    //   screenPosition: desiredScreenPosition + listViewOffset.dy,
    // );

    print(
        'Scrolled anchor item ${_anchorItem!.id} to screen position ${_anchorItem!.screenPosition}');
    print("using scrollpos: ${newScrollPosition} extent: ${newExtentToAnchor}");
  }

  @override
  didUpdateWidget(VirtualScrollList oldWidget) {
    double oldExtent = oldWidget.items.fold(
      0.0,
      (previousValue, element) => (previousValue as double) + element.extent,
    );

    double newExtent = widget.items.fold(
      0.0,
      (previousValue, element) => (previousValue as double) + element.extent,
    );

    double extentToAnchor = 0;
    for (var i = 0; i < widget.items.length; i++) {
      if (widget.items[i].id == _anchorItem!.id) {
        break;
      }
      extentToAnchor += widget.items[i].extent;
    }

    print('oldExtent: $oldExtent, newExtent: $newExtent');
    print("newextentToAnchor didupdate: $extentToAnchor");
    _scrollAnchorItemToItsScreenPosition();
    super.didUpdateWidget(oldWidget);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Theme(
        data: Theme.of(context).copyWith(
            scrollbarTheme: ScrollbarThemeData(
          thumbColor: WidgetStateProperty.all(Colors.black),
        )),
        child: ListView.builder(
          physics: BouncingScrollPhysics(),
          itemExtentBuilder: (index, dim) => widget.items[index].extent,
          controller: _scrollController,
          itemCount: widget.items.length,
          itemBuilder: (context, index) {
            return widget.items[index].child;
          },
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _scrollAnchorItemToItsScreenPosition,
        child: Icon(Icons.refresh),
        tooltip: 'Scroll to anchor item',
      ),
    );
  }
}
```

hopefully flutter team can look into supporting a virtual scrolling widget like this offically

**Comment by Mikephii** [comment]
hgraceb's solution appears to be the only correct one i can find. You need to use two slivers, above and below and then reposition where the split happens. The only extra thing is if everything is in the top sliver you actually want to remove the center key and just make that a reversed sliver so that you cant ovderscroll. If you use a center key and place everything in the top sliver, the controller allows you to scroll to scroll position 0, and with everything in the top (negative scroll positions) this mean nothing is displayed on screen. 

This solutions is good because it allows dynamically sized items, lazily loaded items, and doesnt require expanding cache-extent. when the slivers settle with the split, you can resize the window and items that change in size wont shift the list around

The calculations about how to maintain the screen position of an item before adjusting the list is relatively straightforward, but there are issues around maintaining ballistic simulations after reversing the list or un-reversing it. you need to pause the simulations using goBallistic(0.0) and adjust the list to reversed or un-reversed and then restart the simulation using the previous velocity but with an inverted sign. so goBallistic(-existingVelocity). 

While this solution requires a GlobalKey on every item, actually when we search and measure the items on screen we only care about the few items that are currently on screen. most of the items will be offscreen and un-built due to lazy loading and so their render contexts will be null and can be quickly skipped.

I think flutter should be able to implement this at a framework level but some state needs to be maintained between layouts, an item that is in the current layout needs its viewport position measured, and then in the next layout that item needs to be re-identified by key and it needs to have the centerkey offset or the scroll offset adjusted such that the screen position == the old screen position. if the new layout of items doesnt contain any items from the previous layout of items obviously theres nothing that can be done. 

I think this could be done during layout using RenderSliver.centerOffsetAdjustment and for some RenderSliver.centerOffsetAdjustment is hard-coded to 0.0 so unsure what thats about or if im missing something. 

if you go ahead and implement this on your own at the parent widget level theres a few things you need to know

- You need to override the scrollController and scrollposition class to expose a getter to get the current ballistic velocity, if the current scroll activity is ballistic and has velocity. this is so drag velocities can be maintained after re-layouting the list
- you need to use position.correct() or position.correctBy() as it doesnt cancel the current scroll activities and also doesnt notify listeners. theres a warnign about using this as it should only be used during layout, but thats basically what we are doing, hacking around the existing layout
- If you want to hard stop at the bottom of the list, you need to change to a single reversed list when the last item becomes visible  and then change back to the sliver split once the bottom item is not visible, because reversed lists have there scroll position set as the distance of the **_bottom_** of the viewport from center, and the distance of an item from the center of the viewport is also measured to the **_bottom_** of the item rather than the top there are some transformations that need to be done to get screen positions measured as the top of the item to the top of the viewport. likewise maintaining ballistics across this transformation requires flipping the sign before restarting the sim

Im not going to post my code because its also riddled with other workarounds i have for smooth scroling on scrollwheel events as well as application level logic for my application

Also every now and then correctBy() is being called by the internal scrollable layout process and shifting my scroll position by exact integer multiples of 20px for some reason. Not sure why but it happens very rarely and only when using mouse scroll wheel events (which i have converted to animateTo for smooth scrolling) its so rare i dont care right now and so am going to live with it.

oh and also the scroll bar seems to be completely incompatible with this and will require some custom scroll bar implementation to account for all the scroll position corrections happening while the user is interacting with the scrollbar. Im so exhausted after spending so long trying to get this to work similar to the scroll experience in modern chat apps that im just going to disable the scroll bar for now. 

![CleanShot 2024-08-30 at 11 20 34](https://github.com/user-attachments/assets/6f46e304-eccb-4415-9081-d460a563fccd)

**Comment by haroke4** [comment]
Hello everyone!
I've run into the same problem when building my chat application. I wanted the smoothness of Telegram, so the performance and FPS were vital to me. 
After spending days and hours,  I got the solution, and it's in package: [flutter_list_view](https://pub.dev/packages/flutter_list_view)

It works perfectly, without any junks. Also, in my opinion it is much easier to set up that building custom scroll view with two/three slivers.

**Comment by hgraceb** [comment]
> After spending days and hours, I got the solution, and it's in package: [flutter_list_view](https://pub.dev/packages/flutter_list_view)
> 
> It works perfectly, without any junks. Also, in my opinion it is much easier to set up that building custom scroll view with two/three slivers.

@haroke4 Hi, I tried the example code for this package, but no position is anchored when the item height changes. Did I do something wrong? Could you share how you use it?

<details open><summary>Code sample</summary>

https://github.com/robert-luoqing/flutter_list_view/blob/c976d1041ca1e1341a7fc71788b560bc9a426ac9/example/lib/init_jump_keep_position.dart

```dart
import 'dart:math';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:flutter_list_view/flutter_list_view.dart';

class InitJumpKeepPositionPage extends StatefulWidget {
  const InitJumpKeepPositionPage({Key? key}) : super(key: key);

  @override
  State<InitJumpKeepPositionPage> createState() =>
      _InitJumpKeepPositionPageState();
}

class _InitJumpKeepPositionPageState extends State<InitJumpKeepPositionPage> {
  int currentId = 0;

  List<Map<String, String>> data = [];
  final _random = Random();
  FlutterListViewController viewController = FlutterListViewController();
  String htmlLine = "<div>Single line</div>";

  final _itemCount = 100;
  late final List<double> _itemExtents;

  @override
  initState() {
    super.initState();
    for (var i = 0; i < 100; i++) {
      data.add({
        "key": currentId.toString(),
        "display": "<div><b>$i</b></div>" +
            List.filled(2 + _random.nextInt(10), '\n').join(htmlLine)
      });
      currentId++;
    }

    final heightGenerator = math.Random(2147483647);
    _itemExtents = List.generate(_itemCount, (index) {
      return 80.0 + heightGenerator.nextInt(120);
    });
  }

  @override
  dispose() {
    super.dispose();
  }

  void _insertDataAndRestoreSaveScrollPosition() {
    data.insert(0, {
      "key": currentId.toString(),
      "display": List.filled(2 + _random.nextInt(10), '\n').join(htmlLine)
    });
    currentId++;
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Jump to the index what you want"),
      ),
      body: Column(
        children: [
          Wrap(spacing: 20, children: [
            ElevatedButton(
                onPressed: _insertDataAndRestoreSaveScrollPosition,
                child: const Text("Insert line at index 0")),
          ]),
          Expanded(
            child: Scrollbar(
              child: FlutterListView(
                key: ObjectKey(data.hashCode),
                controller: viewController,
                delegate: FlutterListViewDelegate(
                  (BuildContext context, int index) => _buildItem(index),
                  childCount: data.length,
                  keepPosition: true,
                  keepPositionOffset: 0,
                  onItemKey: (index) {
                    return data[index]["key"]!;
                  },
                  initIndex: 90,
                  firstItemAlign: FirstItemAlign.end,
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildItem(int index) {
    return FutureBuilder(
      future: Future.delayed(
        Duration(milliseconds: 1000 + _itemExtents[index].toInt() * 5),
        () => _itemExtents[index].toDouble(),
      ),
      builder: (context, snapshot) {
        if (snapshot.hasData) {
          return Card(
            child: SizedBox(
              width: snapshot.data!,
              height: snapshot.data!,
              child: Center(child: Text('Item $index')),
            ),
          );
        }
        return Card(
          child: SizedBox(
            width: 120,
            height: 120,
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                const Flexible(
                  child: SizedBox(
                    width: 10,
                    height: 10,
                    child: CircularProgressIndicator(strokeWidth: 2),
                  ),
                ),
                const Flexible(
                  child: SizedBox(width: 10),
                ),
                Flexible(
                  flex: 10,
                  child: Text('Item $index'),
                ),
              ],
            ),
          ),
        );
      },
    );
  }
}
```

</details>

**Comment by haroke4** [comment]
Hi @hgraceb! Sorry for the late reply.

In my code, I've set the `keepPositionOffset` of the `FlutterListView` to 0.1, and before adding any data to my List, I check if the curr offset (using FlutterListViewController) is less than or equal to 0.1. if so, I jump/animate to offset 0.15 (which is barely visible on UI).
My code is identical to yours except for the if statement before adding an item to the list.

`
// initialize controller
final listViewController = FlutterListViewController();

// UI 
  Widget _messagesListView() {
    return FlutterListView(
      /// Fresh messages are always at the bottom!
      reverse: true,

      // assign controller 
      controller: listViewController,
      physics: const BouncingScrollPhysics(),

      delegate: FlutterListViewDelegate(
        (context, index) => _itemBuilder(context, index),
        childCount: data.length, // your data length
        onItemKey: _onItemKey,
        keepPosition: true,
        keepPositionOffset: 0.1, // 
        firstItemAlign: FirstItemAlign.end,
      ),
    );
  }


// before adding any data to your list
if (listViewController.hasClients && listViewController.offset < 0.1) {
    listViewController.jumpTo(0.15);
}
`

I hope helps :3

**Comment by lxchx** [comment]
Hi @hgraceb!

I tried your package. It does maintain the scroll position when the height of previous items changes. However, when adding new items at the top, the position still shifts. 

On the other hand, flutter_list_view does not change position when adding items at the top, though it does shift when item heights change. I’d like to know if this is the expected behavior.

I'm using the version from the master branch([code](https://github.com/hgraceb/tsukuyomi/tree/master/packages/tsukuyomi_list)).

**Comment by Piinks** [comment]
Hi folks,
To prevent confusion on debugging/addressing this issue, please do not provide feedback for other packages outside of flutter in this issue. :)

**Comment by santiagos01** [comment]
Bringing the discussion from https://github.com/flutter/flutter/issues/165414 here

I'd like to echo what others have said that this is ideally something that can directly be solved within Flutter's list view instead of requiring lots of manual workaround or external packages.

This is applicable not only for loading images, but also for pagination and real-time content updates, which are very common across many apps.

Hope that the Flutter team could consider to increase the priority for this issue

**Comment by mark8044** [comment]
@santiagos01 and everyone else, make sure to thumb up the original report, as that is how I believe the flutter team decides which issues to elevate or tackle?

**Comment by ksokolovskyi** [comment]
To reproduce the issue, I created two minimal examples. In both, the `ListView.builder` includes the items that change their height at some point in time.

<details closed><summary>Example 1</summary>
<video src="https://github.com/user-attachments/assets/5751fb4e-4e9f-441e-b93f-cd1cddf5aa58"/>
</details>

<details closed><summary>Example 2</summary>
<video src="https://github.com/user-attachments/assets/6753939b-fc6f-4619-a854-d72849820017"/>
</details>

<details closed><summary>Source Code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(
          title: Text('Scroll Issues'),
          elevation: 10,
          scrolledUnderElevation: 10,
        ),
        body: Builder(builder: (context) {
          return ListView(
            padding: EdgeInsets.symmetric(horizontal: 10),
            children: [
              Card(
                clipBehavior: Clip.antiAlias,
                child: ListTile(
                  title: Text('Loaders Example'),
                  onTap: () {
                    Navigator.of(context).push(
                      MaterialPageRoute(builder: (_) => LoadersExample()),
                    );
                  },
                ),
              ),
              Card(
                clipBehavior: Clip.antiAlias,
                child: ListTile(
                  title: Text('Image Loading Example'),
                  onTap: () {
                    Navigator.of(context).push(
                      MaterialPageRoute(builder: (_) => ImageLoadingExample()),
                    );
                  },
                ),
              ),
            ],
          );
        }),
      ),
    );
  }
}

class LoadersExample extends StatefulWidget {
  const LoadersExample({super.key});

  @override
  State<LoadersExample> createState() => _LoadersExampleState();
}

class _LoadersExampleState extends State<LoadersExample> {
  final _controller = ScrollController();

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Loaders Example'),
        elevation: 10,
        scrolledUnderElevation: 10,
      ),
      body: NotificationListener(
        onNotification: (notification) {
          print(notification);
          print(_controller.position);
          print('');
          return false;
        },
        child: ListView.builder(
          controller: _controller,
          itemCount: 20,
          itemBuilder: (context, index) {
            return FutureBuilder<String>(
              future: Future.delayed(
                Duration(milliseconds: 1000),
                () => 'Item $index',
              ),
              builder: (context, snapshot) {
                final data = snapshot.data;

                if (data == null) {
                  return Center(child: CircularProgressIndicator());
                }

                return Padding(
                  padding: EdgeInsetsGeometry.all(8),
                  child: ColoredBox(
                    color: Colors.white,
                    child: SizedBox(
                      height: 80,
                      child: Center(child: Text(data)),
                    ),
                  ),
                );
              },
            );
          },
        ),
      ),
    );
  }
}

class ImageLoadingExample extends StatefulWidget {
  const ImageLoadingExample({super.key});

  @override
  State<ImageLoadingExample> createState() => _ImageLoadingExampleState();
}

class _ImageLoadingExampleState extends State<ImageLoadingExample> {
  final _controller = ScrollController();
  final _isLoading = ValueNotifier(true);

  @override
  void dispose() {
    _controller.dispose();
    _isLoading.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Image Loading Example'),
        elevation: 10,
        scrolledUnderElevation: 10,
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () {
          _isLoading.value = !_isLoading.value;
        },
        label: Text('Switch'),
        icon: Icon(Icons.swap_horizontal_circle_outlined),
      ),
      body: NotificationListener(
        onNotification: (notification) {
          print(notification);
          print(_controller.position);
          print('');
          return false;
        },
        child: ListView.builder(
          controller: _controller,
          itemCount: 20,
          itemBuilder: (context, index) {
            if (index == 4) {
              return ValueListenableBuilder(
                valueListenable: _isLoading,
                builder: (context, isLoading, _) {
                  if (isLoading) {
                    return Center(child: CircularProgressIndicator());
                  }

                  return Padding(
                    padding: EdgeInsetsGeometry.all(8),
                    child: ColoredBox(
                      color: Colors.red.shade500,
                      child: SizedBox(
                        height: 200,
                        child: Center(child: Text('Image')),
                      ),
                    ),
                  );
                },
              );
            }

            return Padding(
              padding: EdgeInsetsGeometry.all(8),
              child: ColoredBox(
                color: Colors.white,
                child: SizedBox(
                  height: 80,
                  child: Center(child: Text('$index')),
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}
```

</details>

I explored the internals of the `RenderSliverList` class. To work around the jumping behavior mentioned in this issue, I added logic to detect when an item's extent (height) changed compared to a previous layout pass. When a size change is detected, I return a `SliverGeometry` with a `scrollOffsetCorrection` value like this:

```dart
class RenderSliverList extends RenderSliverMultiBoxAdaptor {
...
  double? _prevSize;

  @override
  void performLayout() {
    ...
   // Now find the first child that ends after our end.
    while (endScrollOffset < targetEndScrollOffset) {
      if (!advance()) {
        reachedEnd = true;
        break;
      }
      if (index == 4) {
        final double newSize = paintExtentOf(child!);
        if (_prevSize == null) {
          _prevSize = newSize;
        } else if (_prevSize != newSize) {
          geometry = SliverGeometry(scrollOffsetCorrection: newSize - _prevSize!);
          _prevSize = newSize;
          return;
        }
      }
    }
    ...
  }
...
}
```

This correction signals the `RenderViewport` to adjust the scroll offset accordingly, and it worked correctly for that particular item (see recording below). 

<details closed><summary>Scroll Offset Correction</summary>
<video src="https://github.com/user-attachments/assets/d45ee619-51bb-450b-a6ea-62ae7f855b1f"/>
</details>

However, there is an important limitation. `RenderViewport` allows a maximum of 10 layout passes with correction per child, as defined here: https://github.com/flutter/flutter/blob/76747c0ecef6b24087f451f64142c7d053bd71a4/packages/flutter/lib/src/rendering/viewport.dart#L1538

This means that if multiple items resize in a single frame (for example, several images finish loading at once), and the correction takes more than 10 layout cycles to stabilize, the scroll offset might still jump or end up incorrect.

I also reviewed related comments from Flutter contributors that clarify the current architecture and its limitations:

From @Piinks https://github.com/flutter/flutter/issues/99158#issuecomment-1064402384:

> Scroll position is not content aware, so I don't know that it would be possible for the scroll position to accurately and reliably recalculate where the position 'should' be when the content of the list view is dynamically changing. ... You can also try using `ListView.itemExtent` or `ListView.prototypeItem` to better control the length of the list and the calculation of the extent.

From @knopp https://github.com/flutter/flutter/pull/134864#issuecomment-1975787616:

> You can always fix this by caching the size of images yourself and then use `SizedBox` with cached size when buildings item while scrolling back. The main issue here is that your initially create all your items with very small extent and then they resize after a while when the image is loaded. No `ListView` implementation can fix this (in theory resizing items in cache area can correct the scroll offset transparently but this will fall apart when you scroll too quickly so the best way is to always create the widget with proper size once you know it).

In summary, the most progress I was able to make to fix the issue at the framework level was through the scroll offset correction implemented in `RenderSliverList`. While this helps mitigate the issue in some cases, it is not a practical solution due to the `RenderViewport`’s fixed limit of 10 layout cycles per child.

The current recommendation is to avoid dynamic size changes by estimating item sizes in advance, using fixed-size placeholders, or caching image dimensions.

**Comment by CHTNANKO** [comment]
Same issue here. I hope the Flutter team can add a scroll anchor feature soon.

**Comment by rlim1987** [comment]
Hi flutter team. please help fix this issue - it has been long enough
