### ISSUE TITLE
[Android TV][Video_player]: Rendered video is smaller in size than actual video size and not taking parent size

### ISSUE THREAD

**Issue by predatorx7** [flutter/flutter#99273]
- This only happened on Android TVs and not on other platforms.
- This issue only happens with the HLS URL from my company's collection. They work well with Android Native ExoPlayer on mobiles, the same Android TV devices and with videoJS video player on the web.
- This issue only happens when video resolution is smaller than TV's resolution.

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. The video would autoplay when the app launches

**Expected results:** Video must scale to fit the screen with no graphical issues and should be centered.

**Actual results:** 
- Observe the app video does not fit the larger form factor of screen.
- The playing video has a very small size and is positioned on the top left side.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

const _url =
'https://d26s11bgjh4m50.cloudfront.net/eeffb82b-eac6-4e8e-92a9-49bc3797814f/AppleHLS1/fddf6330-b32a-4d76-9e7b-c2cefe6cf866.m3u8';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(_url);
    _initialize();
  }

  void _initialize() async {
    try {
      await _controller.initialize();
      // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
      setState(() {});
      Future.microtask(_controller.play);
    } catch (e, s) {
      print('Error: $e\n$s');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      body: Center(
        child: _controller.value.isInitialized
            ? AspectRatio(
                aspectRatio: _controller.value.aspectRatio,
                child: VideoPlayer(_controller),
              )
            : Container(),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          setState(() {
            _controller.value.isPlaying
                ? _controller.pause()
                : _controller.play();
          });
        },
        child: Icon(
          _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}
```

</details>

<details>
  <summary>Logs</summary>

[Logs from `flutter run -v` in logs.txt](https://github.com/flutter/flutter/files/8153488/logs.txt)

```
Analyzing test_drive...

   info - Avoid `print` calls in production code - lib\main.dart:75:7 - avoid_print
   info - Avoid `print` calls in production code - lib\main.dart:81:5 - avoid_print

2 issues found. (ran in 24.6s)
```

```
[✓] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.22000.527], locale en-IN)
    • Flutter version 2.10.2 at D:\Devel\flutter_2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (9 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at D:\Linux\devel\android-sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31424.327
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at D:\Apps\IntelliJ IDEA 2021.2.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.64.2)
    • VS Code at C:\Users\smush\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[✓] Connected device (5 available)
    • MiTV AESP0 (mobile)     • 192.168.5.163:5555 • android-arm    • Android 9 (API 28)
    • AOSP TV on x86 (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows            • windows-x64    • Microsoft Windows [Version 10.0.22000.527]
    • Chrome (web)            • chrome             • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)              • edge               • web-javascript • Microsoft Edge 98.0.1108.56

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

![flutter_02](https://user-images.githubusercontent.com/33719927/155985393-11bf566e-5f2b-43e7-8484-0d581f139fe0.png)
![flutter_03](https://user-images.githubusercontent.com/33719927/155985402-1120d2d0-094f-4e99-8a55-0b094bb8ed68.png)
![flutter_04](https://user-images.githubusercontent.com/33719927/155985412-f99a3555-e13e-4626-a245-b8ef220a4dfd.png)
![flutter_05](https://user-images.githubusercontent.com/33719927/155985419-3a9d8b7f-0c81-43bc-ae22-4a218c9b597b.png)
![flutter_01](https://user-images.githubusercontent.com/33719927/155985423-d67c0086-a039-460e-b8a5-c598e2f68391.png)

**Comment by darshankawar** [comment]
I tried to replicate this behavior by creating an Android TV emulator (Android 12,4K) and ran the code but getting below log in the console:

```
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
W/FlutterActivityAndFragmentDelegate( 3762): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
Debug service listening on ws://127.0.0.1:57104/LNHATNq_Cwk=/ws
Syncing files to device AOSP TV on x86...
W/mple.test_issu( 3762): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (unsupported, reflection, allowed)
I/ExoPlayerImpl( 3762): Init 4b4f112 [ExoPlayerLib/2.14.1] [generic_x86_arm, AOSP TV on x86, unknown, 31]
E/ExoPlayerImplInternal( 3762): Playback error
E/ExoPlayerImplInternal( 3762):   UnknownHostException (no network)
I/flutter ( 3762): Error: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)
```

Based on the report, I'll label this for further investigation.

**Comment by predatorx7** [comment]
@darshankawar Same with me in release mode. I tested the same video URL on Exoplayer on [Exoplayer's main demo app](https://github.com/google/ExoPlayer/tree/release-v2/demos/main) and it was working well without any issues.

**Comment by predatorx7** [comment]
@darshankawar That might have happened in _release mode_ because of missing internet permission `<uses-permission android:name="android.permission.INTERNET"/>` in `AndroidManifest.xml`. 

I tested the same video URL on Exoplayer on [Exoplayer's main demo app](https://github.com/google/ExoPlayer/tree/release-v2/demos/main) and it was working well without any issues.

**Comment by predatorx7** [comment]
In my testing, on slower internet, HLS would return lower resolution videos that were smaller than the TV's resolution.  This issue would not happen with tracks with resolution closer or higher than the TV's resolution.

**Comment by predatorx7** [comment]
I understand that the maintainers would be busy with other issues and this issue has been marked with a low priority but resolving this is important to me and my organization. 

Can someone from this plugin's maintainers guide me (just hint or nudge in the right direction) to find a solution?

Right now we are using a workaround for this issue.

**Comment by Josebergon** [comment]
Hi, I'm dealing with the same issue, specifically on fireTV 4k. Right now we are using as well a workaround to make it work but we would really appreciate an update on this issue or a possible solution.

**Comment by Josebergon** [comment]
@predatorx7 I tried that solution too but my client demanded the adaptive streaming, so I had to make it work. Thanks for sharing your workaround though, let's hope for a solution soon.

**Comment by smedasn** [comment]
please fix. having the same issue

**Comment by ds84182** [comment]
This should be fixed by https://github.com/flutter/engine/pull/24888. Some devices decode video into large surfaces. Flutter Engine was not handling the transformation matrix correctly previously, but it is handled correctly now.

Also duplicate of #85583

**Comment by predatorx7** [comment]
Thanks, @ds84182. I'll check this issue on Flutter master for my apps.

**Comment by postacik** [comment]
Hi @ds84182,
I tested this commit (Flutter channel master 3.1.0-0.0.pre.2125) with my TV player application.

Although compilation gave some errors complaining about missing overrides and parameters in ".pub-cache/hosted/pub.dartlang.org/fwfh_text_style-2.7.3+1/lib/fwfh_text_style.dart", I managed to fix it with small additions.

I do confirm that the problem is solved on my Mi Smart Projector running Android TV 9.0.

Can you please add a notification on this post when this fix is merged into stable channel?

**Comment by Josebergon** [comment]
Hi @ds84182, I can confirm too that problem is solved on master 3.1.0-0.0.pre.2136 on all the previous devices that had the issue. Waiting for this fix to get merged into stable. Cheers to team for the fix :)

**Comment by cool2apps** [comment]
I am using flutter 3.3.9 and this problem still exists. Is https://github.com/flutter/engine/pull/24888 applied to flutter 3.3.9?

**Comment by kerimamansaryyev** [comment]
The problem occurs on while testing with Android TV Emulator, SDK 33. I've tested it with SDK 28 and everything was fine. While testing with SDK 33 the problem persists on Flutter 3.7

**Comment by Josebergon** [comment]
Last time I checked the problem is solved on the master channel since august but they haven't merged it yet.

**Comment by stuartmorgan** [comment]
Closing as a duplicate of https://github.com/flutter/flutter/issues/46460
